
!if $cmd=help and $help_subject iswordof conf soft and $wims_ismanager=2
 !changeto conf/help-$help_subject.phtml
!endif

!header

!if $wims_ismanager iswordof -1 1
$name_intromain
 <tt>log/wims.conf</tt>. <p>
!endif

!if $job!=$empty
 !read $job.phtml
!endif
!if $wims_ismanager=2 and $job!=list
 !set wims_menu_items=!append line sitegestion,1,cmd=reply&job=list\
 to $wims_menu_items

!endif

!tail

!reset auth,save,abandon
