
!read adm/title.phtml 3\
\
Rebuild resource index

!if $atdate!=$empty
 Resource index rebuilding is scheduled. 
 You will receive a mail containing the
 result of resource rebuilding.
 !goto end
!endif

<b><font color=red>$wims_name_warning</font></b> Rebuilding resource index takes server 
resources, so should better be avoided when the server is very busy.
<p>
!if $lastdate!=$empty
 :result
 Result of last resource index building at $lastdate:
 <p><pre>
 $output
 </pre>
 <p>
 !href cmd=reply&job2=run Click here
 to restart a resource index rebuilding (you shouldn't).
!else
<p>
 !href cmd=reply&job2=run Click here
 to start resource index rebuilding.
!endif
:end
!reset job2

