<p>
Quicktool is an administrative module which can be used by Modtool developpers to create 
language exercises. It is not in the standard distribution.
The exercises which are created with are completely compatible with current
version of wims for the stable version.
<p>
Download Quicktool : 

!form reply

!formradio job2 list 1,2 prompt Quicktool-1.50,svn version
<p><small> 
 For svn version, need svn client.
 </small>
<center> <input type=submit value=OK></center>
</form>
