!if robot isin $session
 <html><body $wims_htmlbody>
 本页不能用自动方式进入.
 </body></html>
 !exit
!endif

!set wims_html_onload=!append word window.focus(); to $wims_html_onload
!header1

<h1 class="wims_title">
<font color=red>W</font>WW
<font color=red>I</font>nteractive
<font color=red>M</font>ultipurpose
<font color=red>S</font>erver<br>
<font size="-1">设于 <a href="/">$httpd_HTTP_HOST</a></font><BR>
网上互动式多功能服务站
</h1>

!read $job.phtml

!if $job!=home
 <p>
!set wims_menu_items=!append line browse,1,module=$module&cmd=new&job=home\
to $wims_menu_items

!endif

!tail

