
<center><h3>$title</h3></center>

!if $parm=$empty
 $name_domain
 <ul class="wims_browse_subject_list">
 !for d in $tot_dom
  <li class="wims_browse_subject_list">
   !set l_=$(dom_$d)
    !href module=$module&cmd=new&job=$job&parm=$d <b>$(chname_$d)</b>
   !if $l_=$empty
    .
   !else
    $ :
    !for v in $l_
     !href module=$module&cmd=new&job=$job&parm=$v $(chname_$v)
     &nbsp;
    !next v
   !endif
   </li>
 !next d
 </ul>
!else
 在<i><font color=blue>$(chname_$parm)</font></i>领域里, 有以下科目可供选择.
 !href module=$module&cmd=new&job=subject 其它领域
.
 <p><table border=0 cellpadding=2 cellspacing=1>
 !for t in $list
  <tr>
  <td align=left nowrap><b>$(chname_$t)</b></td>
  !if $has_enc=yes
   <td nowrap><small>
   !href target=wims_ref module=adm/enc&dom=math&job=search&search=$t $name_L
   </small></td>
  !endif
  !set key=$(enname_$t)
  !for i in T,P,X,S
   !set cat=$i
   <td nowrap><small>
   !href $search_addr $(name_$i)
   </small></td>
  !next i
  !next t
 </table> <p>
!endif

