<script language="javascript" type="text/javascript">
function emptyfield() {
 alert("$name_warning_empty"); return false;
}
function formcheck() {
 if(document.getElementById('source').value=="") return emptyfield();
return true ; 
}
</script>

!read lang/name.phtml.$modu_lang register
<p>Enregistrer l'exercice dans le compte développeur <tt>$wims_developer</tt> : </p>
!form reply onsubmit="return formcheck();"
<ul>
<li>
$name_choice_module

!formselect catmodule1 list $list_mod_oef
</li>
<li>
$name_choice_filename
<input id="source" type="text" size="12" name="file_name_src" value="">
</li>
</ul>
<center>
<input type="submit" value="OK">
!set wims_ref_class=wims_button
!href cmd=reply&level=3 $wims_name_giveup
</center>
<input type="hidden" name="level" value="4">
</form>

