!if $wims_developer!=$empty and ..devel/ isin ..$catmodule
 !if $reg1=success
  $name_update1
  <tt>$catmodule</tt>
  
 !else
 $name_update2
  <tt>$catmodule</tt>.
  <pre>$wims_exec_error</pre>
 !endif
 <p>
 !href cmd=reply&level=3 $name_prevstep
 !exit
!endif

!if $wims_user=$empty
 !read level5.phtml
!else
 !if $already!=yes
  $name_update3
 !else
  $name_update4 <p>
 !endif
 $name_update5
 <p>
 !if $wims_user!=supervisor
  $name_youcan
  !href module=classes/$lang&special_parm=.nocache. $name_consult
.
 !else
  $name_youcan
  <ul>
  <li>
  !href module=classes/$lang&special_parm=.nocache. $name_consult
  ($name_sheet).
  </li><li>
  !href cmd=reply&level=3&success=1 $name_prevstep.
  </li></ul>
 !endif
!endif

