
!form reply
<input type=hidden name="level" value=2>
$name_givetitle<br>
<input size=40 maxlength=40 name="oef_title" value="$oef_title"> <p>
$name_giveformat
!formselect oef_format list tex,html
 [
 !href target=wims_mhelp cmd=help&special_parm=format $wims_name_help
 ]<p>
$name_exo
!formselect oef_answercnt from 0 to 10
$name_answer1
!formselect oef_choicecnt from 0 to 10
$name_answer2.
$name_nonnumeric
!formselect oef_computeanswer list yes,no prompt $name_prompt
!formselect oef_condcnt from 0 to $condlim
$name_condition
 [
 !href target=wims_mhelp cmd=help&special_parm=reply $wims_name_help
 ]
<p><table border=0><tr><td align="right">
$wims_name_Author<td><input size=30 maxlength=60 name="oef_author" value="$oef_author">
<tr><td align="right">
$wims_name_email<td><input size=30 maxlength=80 name="oef_email" value="$oef_email">
</table>
<p><center>
<input class="wims_button" type=submit value="$name_continue">
</center>
</form>

!if $wims_user=supervisor
 !read wimshome/log/classes/$wims_class/Exindex
 !if $exototal>0
  <p>
  !form new
  <input type=hidden name="module" value="$module">
  $name_modify
  !formselect existing list $exolist prompt $titlelist
  <input class="wims_button" type=submit value="$wims_name_tosave"></form>
 !endif
!endif

