!set sizex=65

!set types=!nonempty lines $types
!set typelist=!column 2 of $types
!set typenames=!column 1 of $types

$name_content
<font color="red"><b>$oef_title</b></font>.
!href cmd=reply&level=1 $name_menuback
. <p>

!form reply
<input type="hidden" name="level" value="3">
$name_alea [
!href target=wims_mhelp cmd=help&special_parm=parameters $wims_name_Explanations
 ]<br>
!set o_parms=!reinput $oef_parms
<textarea wrap="off" rows="6" cols="$sizex" name="oef_parms">$o_parms</textarea>
<p>
$name_statement ($oef_format)&nbsp;: [
!href target=wims_mhelp cmd=help&special_parm=format $wims_name_Explanations
 ]<br>
!set o_statement=!reinput $oef_statement
<textarea wrap="off" rows="6" cols="$sizex" name="oef_statement">$o_statement</textarea>
<p>
!if $oef_answercnt>0
$table_header
 <caption>$name_free
$table_tr<th>$wims_name_name</th><th>$name_goodsol</th><th>$wims_name_Type</b><small>
 !href target=wims_mhelp cmd=help&special_parm=reply#freestyle [$wims_name_help]
 </small></th></tr>
 !for i=1 to $oef_answercnt
  !default anstype$i=default
  !set p_=!reinput $(ansprompt$i)
 $table_tr<td> <input size="$[$promptlim-3]" maxlength="$promptlim" name="ansprompt$i" value="$p_">
  !set p_=!reinput $(ansgood$i)
  </td><td> <input size="30" name="ansgood$i" value="$p_"></td>
  <td><small>
  !formselect anstype$i list $typelist prompt $typenames
  </small></td></tr>
 !next i
 $table_end <p>
 $name_precision:
 !formselect oef_precision list 100,1000,10000,100000,1000000 prompt 1/100,1/1000,1/10 000,1/100 000,1/1 000 000
 <br>$name_function
 (&nbsp;<input size="6" name="oef_rangel" value="$oef_rangel">,<input size="6" name="oef_ranger" value="$oef_ranger">&nbsp;).
 <p>
!endif

!if $oef_condcnt>0
 $table_header
 <caption>$name_condition_numeric,
 $table_tr<th>$name_name_condition</th><th>$name_definition</th></tr>
 !for i=1 to $oef_condcnt
  !set p_=!reinput $(Condname$i)
   $table_tr<td><input size=$promptlim maxlength=$promptlim name="Condname$i" value="$p_"></td>
  !set p_=!reinput $(Condtest$i)
  <td> <input size="40" name="Condtest$i" value="$p_"></td></tr>
 !next i
$table_end <p>
!endif

!if $oef_choicecnt>0
 $table_header
 <caption>$name_multiple
  $table_tr<th>$wims_name_name</th><th>$name_goodchoice</th><th>$name_badchoice</th></tr>
 !for i=1 to $oef_choicecnt
  !set p_=!reinput $(choiprompt$i)
 $table_tr<td> <input size=$promptlim maxlength=$promptlim name="choiprompt$i" value="$p_"></td>
  !set p_=!reinput $(choigood$i)
  <td> <input size="10" name="choigood$i" value="$p_"></td>
  !set p_=!reinput $(choibad$i)
  <td> <input size="30" name="choibad$i" value="$p_"></td></tr>
 !next i
 $table_end <p>
!endif

<p><center>
<input type="submit" value="$wims_name_tosave">
</center> <p>
$name_option
<table border="0" align="center">
<tr><td>$name_indication</td>
!set pp=!reinput $oef_hint
<td><textarea wrap="off" rows="3" cols="$[$sizex-10]" name="oef_hint">$pp</textarea></td></tr>
<tr><td>$name_solution</td>
!set pp=!reinput $oef_solution
<td><textarea wrap="off" rows="3" cols="$[$sizex-10]" name="oef_solution">$pp</textarea></td></tr>
</table>
</form>

