
Recursos de còpia de seguretat restaurats de la classe&nbsp;: $restored.

!if $user_bad!=$empty
 <p>
 No es permet la restauració dels comptes dels participants (i els registres d'activitat),
 perquè no hi ha prou espai disponible.
!endif

!if $exp_bad!=$empty
 !distribute items irreconeixible, massa aviat, massa tard into ebad,eearly,elate
 <p>
 La data de caducitat de la classe ha estat canviada després de la restauració,
 perquè la data restaurada és  $(e$exp_bad).
!endif

