!if $devno>0
 Modification of properties of a developer account. (Leave the password field
 empty if you don't want to change the old password.)
!else
 To add a new developer account, please specify: (All the fields are
mandatory)
!endif

!form reply
<input type=hidden name=job2 value=mod2>
<center><table border=0>
<tr><td align=right>$wims_name_Login
<td><input size=16 name=devlogin value="$login">
<tr><td align=right>$wims_name_Password:
<td><input type=password size=16 name=devpasswd>
<tr><td align=right>$wims_name_name
<td><input size=40 name=devname value="$name">
<tr><td align=right>$wims_name_email:
<td><input size=30 name=devemail value="$email">
</table>
 <input type=submit value="$wims_name_tosave">
</center>
</form>

!reset devlogin, devpasswd, devname, devemail

