
!set monthnames=jan,fév,mars,avril,mai,juin,juil,août,sep,oct,nov,déc
!set name_wroteon=wrote on

!distribute item <i>sujet&nbsp;:</i> <b>,</b> into subj1,subj2
!distribute item <hr>,<hr> into body1,body2

!distribute line Liste des messages par date\
	Liste des messages par fil\
	Lire un message\
	Ecrire un nouveau message\
	Répondre\
	Aperçu de votre message\
	Envoyer un message\
	Configurer le forum\
	Liste par sujets\
	into n_list,n_thread,n_read,n_compose,n_follow,n_preview,n_send,n_config,n_subjectlist

!set n_otherforums=Autres forums
!set n_welcome=Bienvenue
!set n_list_subject_month = Liste des sujets du mois de
!set n_email=email
!set n_list_month = Liste de messages du mois de
!set n_most=le plus
!set n_old=récent en premier,ancien en premier
!set n_new=Nouveau message
!set n_archives=Archives mensuelles&nbsp;
!set n_following=Réponses au message
!set n_reverse=Renverser l'ordre
!set n_recent=Messages récents
!set n_erased=effacé
!set n_giveup=Abandonner
!set n_send=Envoyer le message
!set n_edit=Retourner éditer
!set n_emptymsg=Votre message est vide&nbsp;
!set n_listforum=Liste de forums accessibles sur ce serveur.
!set n_by=par
!set n_newfollow=Nouvelle réponse à
!set n_subject=Sujet&nbsp;
!set n_content=Contenu du message&nbsp;
!set n_preview=Aperçu
!set n_send0=Envoyer
!set n_orig=Message d'origine
!set n_help=Aide
!set n_mathhelp=pour écrire des formules mathématiques dans vos messages.
!set n_yourname=Votre nom&nbsp;
!set n_cautious=<b>Attention.</b> Votre message ne sera pris en compte que si vous donnez\
  une adresse électronique valide.
!set n_anonymous=Visiteur anonyme.
!set n_emptyforum=Ce forum est encore vide.
!set n_nomessage=Aucun message accessible correspondant à votre requête. Désolé.
!set n_erasedmsg=Message effacé
!set n_with=avec
!set n_or=ou
!set n_without=sans
!set n_citation=citation
!set n_source=Source
!set n_format=Formaté
!set n_erase=$wims_name_erase
!set n_follow_c=Répondre avec citation
!set n_follow_nc=Répondre sans citation
!set n_add=Votre message a été ajouté à ce forum.
!set n_bydate=Par date
!set n_bysubject=Par sujet
!set n_prec=Précédent
!set n_first=1ère réponse
!set n_allfollowing=Toutes les réponses
!set n_statusask=Ce forum n'accepte pas les messages anonymes. Il utilise votre adresse \
 électronique actuelle pour garder votre identité dans le but d'éviter des \
 abus. <p> \
 Afin de vérifier la validité de votre adresse électronique, le serveur vous \
 a envoyé un code secret par email. Veuillez lire ce mail et copier le code ici&nbsp;:
!set n_warning=Un message a été rajouté au forum. Ne pas répondre à ce message.
!set n_forum=Forum
!set n_thread=Tout le fil
!if $job=compose and $c_prec!=$empty
 !set n_compose=Répondre
!endif

!if $job notwordof read list config
 !set nextline= <br>--- $(n_$job) ---
!endif

!set module_title=$module_title$nextline
