
!if $title=$empty
 Error fetching the module <tt><b>$addr</b></tt>.
 !href cmd=reply&job2=first $wims_name_back2
.
 !exit
!endif

!if $muauto iswordof update install
 !if $output!=ok
  Error installing/updating <tt><b>$addr</b></tt>.
 !else
  Installing/updating <tt><b>$addr</b></tt>: successful.
  !href target=wims_test module=$addr test it
.
  You will need to
  !href cmd=reply&job=mkindex rebuild module index
.
 !endif
 !href cmd=reply&job2=first Back to module management
.
 !reset muauto
 !exit
!endif

$table_header
<caption>
!if $vtest=$empty
 New module <tt><b>$addr</b></tt> <br>
 !href cmd=reply&job2=one&muauto=install Install
!else
 New version of <tt><b>$addr</b></tt> <br>
 !href cmd=reply&job2=one&muauto=update Update
!endif
&nbsp;&nbsp;&nbsp;
!href cmd=reply&job2=first $wims_name_giveup
</caption>
$table_tr<th align=right>$wims_name_title<td>$title
$table_tr<th align=right>$wims_name_Description<td>$description
$table_tr<th align=right>$wims_name_Type<td>$category
$table_tr<th align=right>wims_name_Version<td>$version
!if $vtest!=$empty
 (versus $vtest)
!endif
$table_tr<th align=right>$wims_name_Language<td>$language
$table_tr<th align=right>$wims_name_Author<td>
  <a href="mailto:$address">$author</a>
!if $translator!=$empty
 $table_tr<th align=right>$wims_name_Translator<td>
  <a href="mailto:$translator_address">$translator</a>
 
!endif
$table_tr<th align=right>$wims_name_require<td>$require
!if $news!=$empty
 $table_tr<th align=right>Changes<td>
 <small><pre>$news</pre></small>
!endif
$table_end <p>

