<h1 class="wims_title">$module_title</h1>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!if $doccnt<1
 !if $wims_class!=$empty and $wims_user!=supervisor
  Sorry, your class don't have document yet. Verify with your supervisor.
 !else
  !if $authoring=$empty
   Sorry, no document is available to the public yet.
  !else
   Sorry, there is no document of this author.
  !endif
 !endif
!else
 !if $ii>0
  !read scripts/table.phtml
 !else
  !if $wims_class!=$empty
   Here are the documents of your class.
  !else
   Here are the documents of this site accessible to you.
  !endif
  <ul>
  !for t=1 to $doccnt
   !set s_=!line $t of $slist
   !set t_=!line $t of $tlist
   !set a_=!line $t of $alist
   !set t_=!trim $t_
   !default t_=$n_notitle
   <li>
   !href module=$module&cmd=reply&job=read&doc=$s_&block=main $t_
   !if $wims_ismanager=2
    &nbsp;
    !href cmd=reply&job=erase&doc=$s_ $n_erase
&nbsp;
   !endif
   <small>$n_by $a_</small>
  !next t
  </ul>
 !endif
!endif

!if $wims_class=$empty and $wims_ismanager<2
 !form reply
 For your own documents, give the author's name:
 <input size=20 name=authoring value="$authoring">
 <input type=submit value=OK>
 </form> <p>
!endif

!if $wims_ismanager<2 and ($wims_class=$empty or $wims_user=supervisor)
 !href cmd=reply&job=creat Create a new document
, or
 !href cmd=reply&job=auth2&doc=$draftd&block=main&coder=dddd write on a draft document
. <p>
!endif

!tail

