!!##language independant
<h1 class="wims_title">$n_properties<br>
--- $tit ---</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!read propform.phtml

!if class != $doctype
 !href cmd=reply&job=recode $n_codechange
.&nbsp;
!endif

!href cmd=reply&job=list $n_blocklist
.
!!!href cmd=reply&job=file $n_file
!!.
<p>
Code du document&nbsp;: $doc.
$n_freespace1 $quota_total Meg
$n_freespace2 $quota_free Meg.
<p>

