
<h1 class="wims_docu_title">$tit
!if $editable=yes
 </b><font size="-1">[
 !if $block=main
  !href cmd=reply&job=prop $n_properties
  ] [
  !href cmd=reply&job=erase $n_erase
 !else
  !href cmd=reply&job=list $n_otherblocks
 !endif
 ]</font>
!endif
</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 The block <tt>$block</tt> is not yet created.
 !if $editable=yes
  !href cmd=reply&job=edit&block=$block $n_create2.
.
 !endif
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 This page is not yet open to reading. Come back later!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 This page is expired. You can no longer read it. Sorry!
 <p>
 !exit
!endif

<h3>$titb
!if $editable=yes
 </b><font size="-1">[
 !href cmd=reply&job=edit&doc=$doc&block=$block $n_edit
 ]</font>
!endif
</h3>

!read $docdir/$doc/$block.def content


