
<h1 class="wims_docu_title">$tit<br>
$n_codechange
</h1>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!set wims_form_method=post
!form reply
<center><table border=0 cellspacing=5>
<tr><td nowrap align=right>Type the actual code:
<td align=left><input type=password size=20 name=coder1>
<tr><td nowrap align=right>And the new secret code:
<td align=left><input type=password size=20 name=coder>
<tr><td nowrap align=right>Repeat the new code:
<td align=left><input type=password size=20 name=coder2>

<tr><td colspan=2 align=center>
<input type=submit value="Register">
<input type=submit name=abandon value="Cancel">
</table></center></form>

<p><b>Recall</b>. The secret code gives right to modifying the document.
It must be composed of between $codemin and $codemax alpha-numéric letters.

