#! /bin/sh

if [ ! -d scenarios ]; then exit; fi

rm -f Exindex Extitles >/dev/null
cd scenarios
list=`ls -d *.def 2>/dev/null | sed 's/\.def//g'`
cd ..

if [ -z "$list" ]; then exit; fi
titlist=
for i in $list
do
 tit=`cat scenarios/$i.def/.title | tr ',\11' '; '`
 echo "$i:$tit" >>Extitles
 titlist="$titlist$tit
"
 ss=`ls scenarios/$i.def`
 echo :$ss >scenarios/$i.def/.files
done

echo "$titlist" >tmp1
echo "$list" >tmp2
llist=`paste tmp1 tmp2 | sort -f`
list=`echo "$llist" | awk -F'\11' 'length()>2 {print $2}' | tr '\n' ','`
titlist=`echo "$llist" | awk -F'\11' 'length()>2 {print $1}' | tr '\n' ','`

cat >Exindex <<@
!set exolist  =!char 1 to -2 of $list
!set titlelist=!char 1 to -2 of $titlist
!set exototal =!itemcnt \$exolist

@

rm -f tmp1 tmp2

