!!<html><head>
!!$wims_html_header
!!</head>
!!<body $wims_htmlbody>
!!!headmenu
!header1

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

<center>$classname
<p>
<h1>Manually entered participant grades
</h1></center> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Back to home page of the class
. <p>
 !goto end
!endif

!form reply
<input type=hidden name=method value=percent>
Here you can manually attribute grades to the participants of the 
class. Each participant can consult his/her own grades when logged to the
class. Average will also be computed on these grades, which will count for
<input size=4 name=per value="$percent">%
(<small><input type=submit name=reg value=change></small>)
in the global average for each participant.
!if $method!=list
 !href cmd=reply&method=list Abandon the changes
.
!endif
</form> <p>

!read $method.phtml

!if $method!=list
 !href cmd=reply&method=list Abandon the changes
.
!endif

<p>
!href module=adm/class/userlist The other grades
.

:end
!tail

!reset reg

