!set wims_module_log=error: $error

!if not_supervisor=$error
 Sorry, but only the registered supervisor of a class can access this page.
 !exit
!endif

!if bad_class=$error
 Strange, but I find that your class is not valid!
 !exit
!endif

!if too_many_users=$error
 Your class has too many participants ($ucnt).
 Grades can only be manually entered
 for classes with at most $maxuser participants. Sorry.
 !exit
!endif

!msg $error

