
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=gener,febrer,març,abril,maig,juny,juliol,agost,setembre,octubre,novembre,desembre

!set wims_name_endexam=Acabar la sessió d'examen
!set wims_name_scoreexam=Puntuació obtinguda

!set name_mainpage=Pàgina principal de l'examen
!set name_dependency=Dependències de les notes&nbsp;
!set name_Options=Opcions
!set name_All=Totes
!set name_title=Preparació de l'examen
!set name_expire=Acabar ara l'examen
!set name_done=fet

!distribute items pes,coeficient\
into name_weight,name_coeff

!distribute lines Acabar aquesta sessió d'examen\
Tornar a treballar sobre l'examen\
Vista de professor de l'examen\
Presentació als participants\
Detalls de la puntuació actual\
Aquest examen és buit&nbsp;!  Pel que sembla és un error de maneig del vostre professor.\
Contingut de l'examen&nbsp;\
Aquest examen està actuellement tancat per la vostra connexió.\
Podeu fer aquest examen una sola vegada.\
Així que no podeu millorar les vostres qualificacions.\
Aquesta és la teva última oportunitat. Tingues compte&nbsp;!\
comença el compte enrere i el nombre d'intents realitzats s'incrementarà en 1.\
comença el compte enrere.\
Requereix l'èxit en altres exercicis\
into name_endexam,name_backexam,name_teacherview,name_presentation,\
name_scoreexam,name_empty,name_content,name_examclosed,name_exam1,name_exam5,\
name_lasttry,name_exam7,name_exam8,name_depend

!set name_exam2=!nosubst Podeu fer aquest examen només $stries vegades en total.

!set name_exam3=!nosubst Ha acabat la teva sessió d'examen aamb $tried intents, 
!set name_exam4=!nosubst Ja has fet l'examen $tried vegades,
!set name_exam6=!nosubst I encara us resten $tryremain intent(s) permesos.

!set name_exam9=!nosubst Teniu $sdure minuts per treballar en aquest examen. \
En fer clic en un dels exercicis anteriors,
 
!set name_simulation=Aquest examen està en mode de simulació. Funciona exactament igual que l'examen real \
  però la puntuació no queda registrada i el vostre intent no serà comptat.
