!set done=fait

!read adm/title.phtml 1\
$wims_classname, $wims_institutionname\
$title

!if $wims_user=supervisor
<center>(Présentation aux participants)</center>
!endif
 <p>
$desc<p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Retourner à la page d'accueil
. <p>
 !exit
!endif

!if $registered<0 or ($registered>0 and $timeleft<=0)
 !changeto score.phtml
!endif

!if $exocnt=0
 Cet examen est vide&nbsp;! Il s'agit apparemment d'une
 erreur de manipulation de votre enseignant.
!else
 Contenu de l'examen&nbsp;:
!! !href cmd=reply&job=student [rafraîchir cette page]
 !set activeexo=0
 <p>
 !let maxcol=$[min(ceil(($exocnt+3)/10),5)]
 !let maxlig=$[ceil($exocnt/$maxcol)]
 !if $maxcol>1
  <center>
 !endif
 <table border=0 class="wims_exam">
  !for lig=1 to $maxlig
   <tr>
    !for col=1 to $maxcol
     !let i=$[$col*$maxlig+$lig-$maxlig]
      !if $i<=$exocnt
!! -------------------------- debut de la ligne correspondant à un exercice de l'examen
 !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
 !distribute lines $ex into we,li,ti,de,op
 !set de=!trim $de
 <td>$i.</td> 
 !if $t_=yes and ($allowtype=simulation or $tryremain>0 or \
   ($tryremain=0 and $registered!=$empty))
   !if $(replied$i)>0
    <td>$ti </td><td>$done</td>
   !else
    !if $de!=$empty
     !set dt=!examdep $exam $de
    !else
     !set dt=yes
    !endif
    !if $dt=yes
     !advance activeexo
     <td>
     !href target=wims_exam cmd=new&worksheet=$exam.$i $ti
</td><td class="empty">&nbsp;</td>
     !if autogen iswordof $op and $wims_exam_remain!=$empty
      !set ss=$(wims_session)t$(exam)t$i
      !set test=!defof w_cmd in wimshome/sessions/$ss/var
      !if $test=$empty
       !set test=$wims_ref_name?wims_window=new&+session=$(wims_session)_exam&+cmd=new&+worksheet=$exam.$i
       <img src="$test" height=1 width=1 border=0>
      !endif
     !endif
    !else
     <td><b><font color=red>$ti</font></b> </td><td>Nécessite
     !href cmd=reply&job=student le succès sur d'autres exercices
.</td>
    !endif
   !endif
  !else
   <td>$ti.</td><td class="empty"></td>
  !endif
!! ------------------------------fin d'affichage de la ligne correspondant à  un exercice
      !endif
    !next col
   </tr>
  !next lig
 </table>
 !if $maxcol>1
  </center>
 !endif
 !if $t_=no
  Cet examen est actuellement fermé pour votre connexion.
  !href cmd=reply&job=student Rafraîchir cette page.
 !else
  !if $stries=1
   Vous pouvez faire cet examen une seule fois.
  !else
   Vous pouvez faire cet examen jusqu'à $stries fois au total.
  !endif
  !if $tryremain<0 or ($tryremain=0 and ($registered=$empty or $allowtype=simulation))
   !if $trcut=0
    Vous avez déjà terminé votre séance d'examen avec $tried essais,
   !else
    Vous avez déjà fait l'examen $tried fois,
   !endif
   donc vous ne pouvez plus améliorer vos scores.
   !set exhausted=yes
  !endif
  !if $tryremain>0
   Et il vous reste actuellement $tryremain essai(s) permis.
  !endif
  !if $registered=$empty and $exhausted!=yes
   Vous avez $sdure minutes pour travailler sur cet examen.
   Quand vous cliquerez sur un des exercices ci-dessus,
   !if $allowtype!=simulation
    le compte à rebours commencera et le nombre d'essais tentés sera augmenté de 1.
   !else
    le compte à rebours commencera.
   !endif
  !else
   !if $allowtype!=simulation and $tryremain=0 and $exhausted!=yes
    C'est votre dernier essai disponible. Faites attention&nbsp;!
   !endif
  !endif
!set wims_menu_items=!append line refresh,1,cmd=reply&job=student\
scoreexam,1,cmd=reply&job=score \
to $wims_menu_items
!!<p>
!!  !href cmd=reply&job=student Rafraîchir cette page.
!!&nbsp;
!!  !href cmd=reply&job=score Mon score.
  !if $activeexo<1
&nbsp;
!set wims_menu_items=!append line endexam,1,cmd=reply&job=scorereg\
to $wims_menu_items
 !!  !href cmd=reply&job=scorereg Terminer
 !!  cette session d'examen (car il n'y a plus rien à faire).
  !endif
 !endif
!endif

!if $t_=yes
 !if $allowtype=simulation
  <p>Cet examen est en mode simulation. Il fonctionne exactement comme le vrai examen 
  mais le score n'est pas enregistré et votre essai ne sera pas compté.
 !endif
!endif

!if $wims_user=supervisor
!set wims_menu_items=!append line backteacher,1,cmd=resume\
 to $wims_menu_items
!endif

!tail

!reset job


