
!set form_OK=Enviar la modificación
!set form_titlename=Título
!set form_caption=Propiedades de la clase
!set title=$class_description
!set sup=$class_Supervisor
!read scripts/classform.phtml

<p>
!if $coursecnt=0
 Esta clase aún no tiene cursos.
 !href cmd=reply&cparent=class&job=addcourse $wims_name_addcourse
.<sup>
 !href cmd=help&special_parm=course $wims_name_help
</sup>
!else
 $table_header
 <caption>Cursos existentes<sup>
 !href cmd=help&special_parm=course $wims_name_help
 </sup> en esta clase
 !href cmd=reply&cparent=class&job=addcourse $wims_name_addcourse
 </small></caption>
 $table_hdtr
 <th>Código<th>Nombre</th><th>-</th><th>Responsable</th>
 </tr>
 !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into l_,s_,t_,n_
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=course&cparent=class&course=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=delcourse&cparent=class&del=$l_ $wims_name_erase
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $s_
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
    No disponible
   !endif
 !next i
 $table_end

!endif

!reset title

