
<center><h3>Borrar el curso <em>$class_description</em></h3></center>

<blink><b>AVISO</b>.</blink> ¡Esta operación es irreversible!
¡Y <font color=red>TODO</font>
lo que hay en este curso será borrado <font color=red>DEFINITIVAMENTE</font>:
cuentas de alumnos, actividades, notas!
<p>
¿Está seguro de querer borrar este curso?
<p><center><font size=+1>

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent Sí
&nbsp;&nbsp;
!href cmd=reply&job=$parent No

</font></center> <p>

