
!read adm/title.phtml 3\
$name_delclass0 <em>$class_description</em>

<font color=red><b>AVISO</b>.</font> ¡Esta operación es irreversible!
¡Y <font color=red>TODO</font>
lo que hay en esta clase será borrado <font color=red>DEFINITIVAMENTE</font>: 
cursos, cuentas de alumnos, actividades, notas!
<p>
¿Está seguro de querer borrar esta clase?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level $wims_name_no

</font></center> <p>

