
<center><h3>Borrar la clase <em>$class_description</em></h3></center>

<blink><b>AVISO</b>.</blink> ¡Esta operación es irreversible!
¡Y <font color=red>TODO</font>
lo que hay en esta clase será borrado <font color=red>DEFINITIVAMENTE</font>: 
cursos, cuentas de alumnos, actividades, notas!
<p>
¿Está seguro de querer borrar esta clase?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes Sí
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level No

</font></center> <p>

