
<center><h3>Borrar el nivel <em>$class_description</em></h3></center>

<blink><b>AVISO</b>.</blink> ¡Esta operación es irreversible!
¡Y <font color=red>TODO</font>
lo que hay en este nivel será borrado <font color=red>DEFINITIVAMENTE</font>:
clases, programas, cursos, cuentas de alumnos, actividades, notas!
<p>
¿Está seguro de querer borrar este nivel?
<p><center><font size=+1>

!href cmd=reply&job=$job&del=$del&confirm=yes Sí
&nbsp;&nbsp;
!href cmd=reply&job=first No

</font></center> <p>

