
!read adm/title.phtml 3\
$name_deltest0 <em>$class_description</em>

<font color=red><b>AVISO</b>.</font> ¡Esta operación es irreversible!
¡Y <font color=red>TODO</font>
lo que hay en esta zona de pruebas será borrado <font color=red>DEFINITIVAMENTE</font>!
<p>
¿Está seguro de que quiere borrar la zona de pruebas?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=$parent $wims_name_no

</font></center> <p>

