
$table_header
<caption>Cuentas de profesor
!href cmd=reply&job=addteacher Añadir&nbsp;uno
</caption>
$table_hdtr
<th>Cuenta</th>
<th>Nombre</th>
<th>-</th>
!for i=1 to $teachercnt
 !set l=!line $i of $teacherlist
 !distribute items $l into l_,f_,c_
 $table_tr
 <td><tt>$c_</tt></td>
 <td>
 !href cmd=reply&job=modteacher&teacher=$c_ $l_, $f_
 </td>
 <td>
 !href cmd=reply&job=delteacher&del=$c_ borrar
 </td>
!next i
$table_end

