
!mailto $sup_email\
WIMS codice per la gestione di un corso\
\
Avete chisto di accedere alle pagine di configurazione del vostro corso vituale\
$wims_classname presso $httpd_HTTP_HOST,\
per il quale non avete definito alcuno host sicuro.\
\
Questo è il codice segreto (valido per una sola volta e a breve termine) per questo 
scopo: $code\
\
Fate un copia e incolla di questo codice nella pagina di gestione del corso per\
avere acesso.\
\
Se non sapete di che cosa si sta parlando, allora qualcuno si è impossessato\
della password di gestione del vostro corso. Cambiatela non appena possible.\
\
$wims_site_manager\

