
!set classname=$wims_classname - $wims_institutionname
 
!set months=Jan,Feb,Mei,Apr,May,Jun,Jul,Aug,Sept,Okt,Nov,Dec

!set wims_name_sheetcheck=Bekijk dit Werkblad
!set wims_name_moduback=Terug naar de module

!set name_choose= Kies het werkblad waarin je deze oefening in wilt opnemen
!set name_title=Voeg een oefening toe aan een Werkblad

!set name_insert=Je wilt enkele oefeningen toevoegen
!set name_parm=met "init parameters"
!set name_modifytitle=Je kunt nu ook de titel en de omschrijving van het werkblad veranderen.
!set name_required=Het aantal punten dat minimaal gevraagt wordt te halen voor deze opdracht
!set name_repeat=elk 100% correct antwoord levert 10 punten op: dus als je meer dan\
  10 punten vraagt moet de leerling deze opdracht dus meerdere keren doen
   
!set name_weight=Het gewicht van de punten (deze weging wordt gebruikt voor de berekening van het gemiddelde):
!set name_end=!nosubst De oefening ``<tt>$title</tt>'' is succesvol toegevoegd aan het werkblad