
Para entrar en <b><font color=green>$mb_title</font></b>
como <em>usuario inscrito</em> por favor introduzca su nombre de
usuario (login) y su contraseña personal.

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.es">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value="$forum">
<center><table border=0>
 <tr><td>Nombre de usuario: <td><input size=20 name=fuser>
 <tr><td>Contraseña: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="Enviar">
</center>
</form>

