
Para entrar en  <b><font color=green>$mb_title</font></b> como su
<em>propietario</em>, por favor, introduzca la contraseña del propietario.

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.es">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value=$forum>
<input type=hidden name=fuser value=supervisor>
<center><table border=0>
 <tr><td>Contraseña del propietario: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="Enviar">
</center>
</form>

