!!<html><head>
!!$wims_html_header
!!</head>
!!<body $wims_htmlbody>
!!!headmenu
!header1

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

<center>$classname
<p>
<h1>Notes attribuées manuellement
</h1></center> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Retour à la page d'accueil de la classe
. <p>
 !goto end
!endif

!form reply
<input type=hidden name=method value=percent>
Ici vous pouvez manuellement attribuer des notes aux participants de la
classe. Chaque participant peut consulter ses notes une fois qu'il est dans
la classe. Les moyennes de ces notes seront aussi calculées, qui compteront
pour
<input size=4 name=per value="$percent">%
(<small><input type=submit name=reg value=changer></small>)
dans la moyenne globale de chaque participant.
!if $method!=list
 !href cmd=reply&method=list Abandonner les changements
.
!endif
</form> <p>

!read $method.phtml

!if $method!=list
 !href cmd=reply&method=list Abandonner les changements
.
!endif

<p>
!href module=adm/class/userlist Les autres notes
.

:end
!tail

!reset reg

