
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=gener,febrer,març,abril,maig,juny,juliol,agost,setembre,octubre,novembre,desembre

!set wims_name_otherscore=Les altres notes
!set wims_name_back4=Tornar a la llista
!set wims_name_addmanual=Afegir una columna
!set wims_name_raw=Modificar la font

!set name_weight=Weight
!set name_average=Average

!set name_enter=Enter grades
!set name_enterof=Enter grades for

!set name_manual_title=Manually notes
!set name_explanation=Here you can manually attribute grades to the participants of the \
class. Each participant can consult his/her own grades when logged to the \
class. Average will also be computed on these grades, which will count \
in the global average for each participant for

!set name_nomanual=There is no manually entered grades yet in your class.
!set name_modify=Click on the name of a column or a participant to modify grades

!set name_can_also=You can also directly
!set name_can_also2=or download the notes
