!read adm/title.phtml 3\
\
Rebuild indices<

These tools are reserved for power users who do manual modifications to the
content of the class. After the modifications, you can click on the
corresponding link to update the index.
<p>
You probably need to study the source code of the software for details on how to
manually modify the class content.
<p>
It doesn't matter if you click on one of the links inadvertently.

