
<b>Declare another class as neighbor</b>.
<br>
!href cmd=help&special_parm=neighbor Neighborhood relation
 between two classes will be effective only when
supervisors of both classes declare the other as its neighbor, either for
supervisor, for participants, or for both.
<p>
Although the principle is that people from a neighboring class can never
modify your class (unless they are 
!href cmd=help&special_parm=share sharing resources
 with you), you should
declare another class as neighbor only if you can trust its supervisor.
<p>
By declaring a class as your neighbor for supervisor, you are allowing the
latter to
!href cmd=help&special_parm=import import
 resources from your class. That means that he will gain access to possible
sensible data of your class, such as hidden sheets or exercises. Make sure
that he will not reveal these data back to your participants.
<p>
What's more, by importing participant accounts from your class, the
supervisor of your neighbor may have means to read personal passwords of
your participants. (This fact is also true if you declare the other class as
your neighbor for participants.) Make sure that he will keep them secret.
<p>
In order to keep security level as high as possible, the principle is that
you declare neighborhood of another class only when it is really necessary.
