
!set sp2=$special_parm2
!bound sp2 within secure,supervisor,email,lang,level,limit,expiration,\
	bgcolor,homepage,bgimg,theme,theme_icon,css,logo,lock,exolog,examlog,examshow,option\
	default $

!if $sp2=$empty
 !exit
!endif

!goto $sp2

:secure
<b>Estaciones de trabajo seguras</b>.
Plantéese la posibilidad de que se filtre la contraseña del profesor;
cuando se conecta a la clase como profesor en un aula, un estudiante puede
verle teclear a sus espaldas, o incluso instalar un programa de captura del
teclado para grabar todo lo que teclea (incluida la contraseña). Créame:
si guarda calificaciones reales en su clase virtual, la contraseña del
profesor puede llegar a ser muy codiciada.
<p>
Las consecuencias de una filtración tal pueden ser catastróficas para la
clase: los datos pueden sufrir daños, las notas pueden ser modificadas o
puede incluso perder su acceso como profesor si el estudiante le cambia
la contraseña.
<p>
La definición de estaciones de trabajo seguras añade una capa suplementaria
de seguridad: las manipulaciones sensibles como la configuración de la
clase, el cambio de contraseña o la modificación de las notas sólo pueden
realizarse desde una <em>estación de trabajo segura</em> predefinida si está
seguro de que sus alumnos no tienen acceso a estas estaciones. Así,
incluso si un estudiante le roba la contraseña no podrá hacerle gran cosa
a la clase. 
<p>
!read help/hosts.phtml
<p>
A este respecto, si está obligado a introducir su contraseña en un
entorno muy hostil (por ejemplo entre ordenadores de estudiantes),
debe plantearse también la utilización de contraseñas desechables
(ver la página sobre el cambio de contraseña).
!exit

:supervisor
 <b>Nombre del profesor</b>. Introduzca aquí su nombre completo, no importa en qué forma.
!exit

:email
 <b>Dirección de correo electrónico del profesor</b>.
 Varias notificaciones importantes (códigos secretos, avisos de expiración, 
 etc.) le serán enviados a esta dirección. También será la que reciba los
 mensajes de los participantes. Por tanto DEBE dar una dirección de correo
 activa, de lo contrario puede incluso perder el control de su clase.
!exit

:option
 <b>Opciones de la clase</b>. Se pueden utilizar aquí las siguientes palabras:
 <ul>
 <li><tt>showshexpire</tt>. Mostrar la fecha de expiración de las hojas de
  trabajo en la página de acceso de los participantes.
 <li><tt>showexexpire</tt>. Mostrar la fecha de expiración de las hojas 
  de examen en la página de acceso de los participantes.
 <li><tt>showshweight</tt>. Show sheet weight in the
  home page of participants.
 </ul> 
!exit

:lang
 Idiomas válidos: <ul>
 <li>cn (Chino gb)
 <li>en (Inglés)
 <li>es (Español)
 <li>fr (Francés)
 <li>it (Italiano)
 <li>tw (Chino big5)
</ul>
!exit

:level
 Significado de los niveles: <ul>
 <li>E1 - E6: Enseñanza primaria, cursos 1 a 6.
 <li>H1 - H6: Enseñanza secundaria, cursos 1 a 6.
 <li>U1 - U5: Enseñanza Universitaria, cursos 1 a 5.
 <li>G: Universidad, tercer ciclo.
 <li>R: Investigación.
</ul>
!exit

:limit
 <b>Límite del número de participantes</b>. La inscripción de nuevos participantes
 será rechazada si se alcanza este límite. Hay un límite definido por el
 sitio ($wims_class_user_limit) que no puede ser superado.
!exit

:expiration
 <b>Fecha de expiración</b>. Esta clase se cerrará cuando llegue la fecha
 de expiración. Puede cambiar esta fecha en todo momento, pero se rechazará
 una extensión más allá de un año a partir de la fecha en que tiene lugar la
 la operación de extensión.
<p>
 Si desea extender esta fecha más de un año, puede hacerlo por partes
 en varios intervalos o
 <a href="mailto:$wims_site_manager?subject=Extensión de una clase virtual
 demand">pedir al administrador del sitio</a> que lo haga por usted.
 <p>
 Esta fecha debe ser introducida en forma de 8 cifras (aaaammdd).
 Ejemplo: 20120523 significa 23 de mayo de 2012.
!exit

:bgcolor
 <b>Color de fondo de las páginas y de los menúes</b>. 
 Estos dos colores pueden
 ayudarle a encontrar rápidamente las páginas en el interior de su clase
 virtual. Los valores de estos campos deben ser mombres html de color
 válidos.
 <p>
 Valores predefinidos: fondo de página = white, fondo de menú = #D0C080
!exit

:homepage
 <b>Página de los participantes</b>. Puede poner la dirección de un bloque de
 documento (por ejemplo <tt>c1/main</tt>) como página inicial de la clase
 para los participantes. No es necesario que los participantes puedan leer 
 el documento mismo.
 <p>
 Deje el campo en blanco si desea utilizar la página inicial estándar.
 <p>
 Todos los enlaces del bloque deben ser definidos usando la orden <tt>\adm</tt>.
 Puede utilizar las siguientes variables predefinidas:<ul>
 <li><tt>\firstname</tt> Nombre del participante</li>
 <li><tt>\lastname</tt> Apellidos del participante.</li>
 <li><tt>\scores</tt> Resumen de las calificaciones del participante. Se trata de una lista de
 números. Cada par de números corresponde a una hoja: el porcentaje
 de puntos obtenidos más la calidad de los puntos.</li>
 <li><tt>\newmsgcnt</tt> Número de nuevos mensajes en el foro de la clase.</li>
 <li><tt>\today</tt> Fecha de hoy, aaaammdd.</li>
 <li><tt>\sheets</tt> Número de hojas de trabajo.</li>
 <li><tt>\exams</tt> Número de exámenes.</li>
 <li><tt>\expiration1</tt>, <tt>\expiration2</tt>, <tt>\expirationE1</tt>, ...
 Fecha de expiración de la hoja 1, hoja 2, examen 1, ..., aaaammdd.
 <li><tt>\status1</tt>, <tt>\status2</tt>, <tt>\statusE1</tt>, ...
 Estado de la hoja 1, hoja 2, examen 1, ... Es un entero no negativo;
 0 = en preparación, 1 = activa, 2 = caducada, 3 = oculta.</li>
 </ul>
!exit

:bgimg
 Fichero de la imagen de fondo (o pieza de mosaico) para las páginas de la 
 clase. Puede utilizar cualquier dirección URL válida. Hay también ficheros 
 de imagen preparados que puede usar sin añadir el prefijo de dirección:<p>
 <tt>$bgimgs</tt>
!exit

:theme
El tema de estilo de su clase.
!exit

:theme_icon
The icons in the menu
!exit

:css
La hoja de estilo se aplica a casi todas las páginas de su clase.
<p>
Elija `<tt>----</tt>' para desactivar la hoja de estilo.
<p>
Elija `<tt>-tema-</tt>' para utilizar la hoja de estilo correspondiente
al tema de la clase.
<p>
Elija `<tt>clase</tt>' para utilizar una hoja de estilo (css) definida por
usted. Por favor consulte la documentación de css para conocer su sintaxis.
<b>Nota</b>. ¡Si define su propia css, por favor pruébela
con TODOS los navegadores que puedan utilizar sus alumnos
para descubrir eventuales incompatibilidades!
<p>
Las otras opciones corresponden a los estilos predefinidos en este sitio WIMS.
!exit

:logo
El logo de la clase es un fichero gráfico que se mostrará en la parte superior
de la página inicial de la clase tanto para el profesor como para los participantes.
Este logo puede ir en la parte superior izquierda o en la superior derecha.
<p>
Seleccione `<tt>none</tt>' (ninguno) si no desea un logo.
<p>
Si elije un texto en blanco o `<tt>wims</tt>', se utilizará el logo de WIMS.
<p>
Si no, puede introducir la dirección URL del fichero gráfico que desee.
!exit

:lock
El bloqueo de conexión ayuda al seguimiento de los usuarios y puede 
contribuir a hacer fracasar los intentos de fraude. Hay 7 niveles.<ul>

<li><p>0: No hay activado ningún bloqueo.

<li><p>1: Está activado el envío de cookies. Las conexiones que no devuelven 
una cookie serán rechazadas.

<li><p>2: Es necesaria una conexión segura (https). Se rechazarán las 
conexiones con peticiones http normales. Debe asegurarse previamente
de que el servidor web de este sitio WIMS acepta las conexiones https.

<li><p>3: El bloqueo del puesto desde el que se produce la conexión 
está activado. Los participantes no pueden cambiar de dirección IP
durante una sesión. Esto puede ocasionar dificultades cuando las
conexiones se hacen mediante números IP asignados dinámicamente.


<li><p>4: Cookie + https.
<li><p>5: Cookie + bloqueo del puesto.
<li><p>6: Todos los métodos están activados.
</ul> <p>
!exit

:exolog
Número de registro de ejercicios (limitado a $wims_exolog_limit)
<p>
Es el número máximo de ejercicios que pueden registrarse con detalle
para cada participante.
<p>
Estos detalles permiten a los participantes y al profesor revisar
paso a paso el ejercicio y discurtirlo.
<p>
Los detalles de un ejercicio sólo se registran si lo ordena el
participante. Cuando se supera el número máximo, los registros más antiguos
se pierden.
!goto logs

:examlog
Número de registros de exámenes (limitado a $wims_examlog_limit)
<p>
Es el número máximo de sesiones de examen que pueden registrarse con
detalle para cada participante.
<p>
Estos detalles permiten a los participantes y al profesor revisar
el examen ejercicio a ejercicio.
<p>
El registro de exámenes es automático. Cuando se ha superado el número máximo,
se perderán los registros más antiguos.
!exit

:logs
<p>
Ponga este número a 0 para desactivar este registro.
<b>ATENCIÓN</b>: ¡Los registros de ejercicios y de exámenes pueden
ocupar mucho espacio! Si permite límites demasiado grandes, su clase
corre el riesgo de superar la cuota de disco.

!exit

:examshow
Dans le cas où cette option est mise sur <tt>Non</tt>, les élèves ne peuvent
pas revoir les enregistrements d'examens. Seul l'enseignant le peut.

!exit

:ent
<b>Links on another plateform</b> :
You may add a link on another plateform :
<pre> link_title,link_adress</pre>
For example,
<pre>Dokeos,http://-------</pre>
If you need more than one link, they must be seperate by ";". 

!exit

:end

:end
