!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu
!read adm/css.phtml
!header1

<center>$classname
<h1>$cdt_title</h1>
<font size="+1">Configurazione</font></center> 

<p><hr width="40%"> <p>

Questi sono i parametri che è possibile modificare:

!form reply
<input type=hidden name=job value=config>
<ul>
 <li><p>Titolo:<br>
  <input size=60 name=cf_title value="$cf_title">
 <li><p>Descrizione:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <li><p>Testo che compare come link in Home page: <input size=60 name=cf_link value="$cdt_link"></li> 
 <li><p>
  !href cmd=renew&job=logfile Visualizza
  il log dell'agenda.</li>
</ul>
<p><center><input type=submit name=cf_set value="Salva">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Annulla">
</center> <p></form>
!!<p>
!! !href cmd=reply&job=home Indietro
!! .
!set wims_menu_tail=!append line back2,1,cmd=reply&job=home\
to $wims_menu_tail
