<html><head>
$wims_html_header
</head>
<body>

<script language='javascript'>
  function addsheet(num,msg){
       ta1=window.opener.document.forms[0].elements['$cible'];
       ta1.value=ta1.value+' test di autovalutazione n. '+num+': \\exercise{module=adm%2Fsheet&+sh='+num+'}{'+msg+'}';
  }
  function addexam(num,msg){
       ta1=window.opener.document.forms[0].elements['$cible'];
       ta1.value=ta1.value+' esame n. '+num+': \\exercise{module=adm%2Fclass%2Fexam&+exam='+num+'}{'+msg+'}';
  }
  function addfile(msg){
     ta1=window.opener.document.forms[0].elements['$cible'];
     ta1.value=ta1.value+'<a href=\\filedir/'+msg+'>'+msg+'</a>';
  }
</script>

!let nb=!itemcnt $sheet_nums
!if $nb!=0
  Inserisci test di autovalutazione:<br>
  !for i in $sheet_nums
   <a href="javascript:addsheet($i,'$(sheet_titles[$i])');">$(sheet_titles[$i])</a> ; &nbsp; 
  !next i
!endif

!let nb=!itemcnt $exam_nums
!if $nb!=0
  <p>
  Inserisci esame:<br>
  !for i in $exam_nums
   <a href="javascript:addexam($i,'$(exam_titles[$i])');">$(exam_titles[$i])</a> ; &nbsp; 
  !next i
!endif

!if $nbfile > 0
 <p>
  Inserisci file:<br>
  !for i=1 to $nbfile
   <a href="javascript:addfile('$(file_titles[$i])');">$(file_titles[$i])</a> ; &nbsp; 
  !next i
!endif

</html>

