!set wims_module_log=error: $error
<b>Errore: </b>
!goto $error
!exit

:not_supervisor
spiacente, solo il docente può modificare l'agenda.
!exit

:bad_class
il corso non esiste!!
!exit

:bad_day
la data inserita non è valida.
!exit

:bad_jday
la data indicata per il compito non è valido.
!exit

:bad_date
la data che si vuole modificare non esiste.
!exit

:day_exists
la data inserita esiste già.
!exit

:same_devoir
non è possibile inserire due volte la stessa data per l'assegnazione di un compito.
!exit

:same_devoir2
 non è possibile inserire due volte la stessa data per l'assegnazione di un compito.<br>
 &Egrave; possibile invece 
 !href cmd=new&job=adddate&filename=$jyear$jmonth$jday modificare una data già inserita
 .
!exit

:toomany_todo
è stato raggiunto il numero massimo di compiti assegnabili in una stessa data.
!exit

:day_dontexist
la data inserita non esiste.
!exit