
!read names enter

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value="$forum">
<center><table border=0>
 <tr><td>$wims_name_Login<td><input size=20 name=fuser>
 <tr><td>$wims_name_Password<td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_send">
</center>
</form>

