<center><h3>Dynamic drawing</h3></center>

It is possible to include 2D drawings into the statement of your exercises
(under html format). These drawings are dynamic, that is, you can use variables in your draw commands, and the result will vary with the values of the variables. It is even possible to produce animations.

<p>
Syntax&#58; <tt>\draw{xsize,ysize}{command...}</tt>, where <tt>xsize, ysize</tt> are respectively the width and height of the picture (in number of pixels), and <tt>command...</tt> is the content of the commands. That is a text composed of several lines, each line being one command.
<p>
!href cmd=help&special_parm=draw_example Exemple.

<p><hr> <p>

!changeto help/$lang/flydraw.phtml
