
<p>
La definizione delle postazioni in WIMS può essere fatta sia tramite
<em>nome</em> che tramite numero IP. Si raccomanda l'utilizzo dei numeri
IP in quanto i nomi non sono altrettando sicuri.
<p>
&Egrave; anche possibile definire reti e sottoreti nel modo usuale: <tt>127.0.0.</tt>
(attenzione al punto finale, non <tt>127.0.0</tt>)
sta ad indicare tutti gli IP nella rete da 127.0.0.1 a 127.0.0.255, e <tt>.unice.fr</tt>
(ma non <tt>unice.fr</tt>) permette di indicare tutte le postazioni del dominio  <em>unice.fr</em>.
<p>
<p>
Infine, la parola <tt>all</tt> permette l'accesso da qualsiasi postazione. Si tratta ovviamente di una scelta che può compromettere la sicurezza del sito. 
<p>
Se la vostra connessione avviene attraverso un IP dinamico, non indicate 
   questo IP, in quanto si modifica tra una connessione e l'altra.

