
<p>
La definizione delle postazioni in WIMS può essere fatta sia tramite
<em>nome</em> che tramite numero IP. Si raccomanda l'utilizzo dei numeri
IP in quanto i nomi non sono altrettando sicuri.
</p><p>
È anche possibile definire reti e sottoreti nel modo usuale: <span class="tt wims_code_words">127.0.0.</span>
(attenzione al punto finale, non <span class="tt wims_code_words">127.0.0</span>)
sta ad indicare tutti gli IP nella rete da 127.0.0.1 a 127.0.0.255, e <span class="tt wims_code_words">.unice.fr</span>
(ma non <span class="tt wims_code_words">unice.fr</span>) permette di indicare tutte le postazioni del dominio  <em>unice.fr</em>.
</p>
<p>
Infine, la parola <span class="tt wims_code_words">all</span> permette l'accesso da qualsiasi postazione. Si tratta ovviamente di una scelta che può compromettere la sicurezza del sito. 
</p><p>
Se la connessione avviene attraverso un IP dinamico, questo IP non può
   essere utilizzato, in quanto si modifica tra una connessione e l'altra.
</p>
