<p>Livelli scolastici:</p> <ul>
 <li>E1 - E5: Infanzia/Primaria.
 </li><li>E6,H1 - H6: Secondaria (di primo e secondo grado).
 </li><li>U1 - U5: Università.
 </li><li>G: Università, studi post-laurea.
 </li><li>R: Ricerca.
</li></ul>
<p>NOTA: come si vede i livelli <em>elementare</em> e <em>secondario</em> non
  combaciano esattamente con la struttura italiana (ad esempio la quinta
  superiore/maturità corrisponde al livello H6).</p>
