!read adm/title.phtml 3\
\
Resource dependencies in a class

There are many complicated dependencies between different types of resources
in a virtual class, and you are probably not aware of them all.
<p>
For example, exam sheets are defined by referencing to worksheets, the
latter may use class exercises. So if you modify or erase the latter, the
former will probably not be able to work correctly.
<p>
Also, participant scores are computed on the fly, based on their activity
register as well as worksheet severity setups. So if you the active worksheets 
are changed, scores can no longer be computed even if the activity
register is intact.
