
<b>Backup your class</b>. <br>
You can download a backup copy of the class as a compressed file. If your
class is very active, you can also make backups of selected teaching materials. The
backup file can later be sent back to the server in order to restore your
class, or to copy some of the teaching materials to a new class.
<p>
All the sources of the class is written in text files, so that you can also
read (or even edit) them on your local computer.
<p>
Available compressed file format: <ul>
 <li><em>zip</em> that can be decompressed and read on
pratically any system (Windows, Mac, Linux/BSD, etc.), but is not always
very efficiently compressed; 
 <li><em>tgz</em> that can only be decompressed and read on Unix-type systems
(Linux, BSD, Sun OS, etc.), but has a better compression ratio;
 <li><em>tar.gz</em> that is simply a synonym of tgz.
</ul>
<p>
Of course, all the above formats are accepted by WIMS for restoration.

