
<b>Neighboring classes</b>.
<br>
Neighborhood relations among virtual classes on a same site can be
established. Two classes will become neighbors when supervisors of both have
!href cmd=help&special_parm=neibordecl declared
 the other as their neighbors. Teaching resources (documents,
exercises, worksheets) as well participant information can be
!href cmd=help&special_parm=import exchanged
 or
!href cmd=help&special_parm=share shared
 between neighboring classes, and participants having identical accounts in
neighboring classes can travel from one to the other without retyping their
passwords. A class can have as many neighbors as it likes.
<p>
Neighboring relations can be established between two classes with different
objectives: for supervisors, for participants, or both.
<p>
A neighboring relation for supervisors allows exchange/sharing of resources
between the two classes. And that for participants allows exchange of
participant accounts, as well as direct travel of participants from one
class to the other.
<p>
Some examples of typical setup of neighboring class clusters can be found
!href cmd=help&special_parm=neiexample here
.
