
<b>Allow other classes to share your resources</b>.
<p>
If you allow the
!href cmd=help&special_parm=neighbor Neighboring class
 to
!href cmd=help&special_parm=share share
 your resources, you should also be aware of the risks this brings to your
class.
</p><p>
Once you declare a type of resources sharable, the other class may
effectively share them. This means that it may modify your resources,
including damaging it (by a false manoeuvre).
</p><p>
It is particularly risky to allow others share your supervisor account. If
the other changes the supervisor password (or if there is an intrusion to
the other class), you will lose control of your class.
</p><p>
Whenever possible, it is preferable to invite the other class to
!href cmd=help&special_parm=import import
 your resources, rather than letting it to share them with you.
</p>
<p>
Il y a des dépendances entre les ressources : le partage de certaines vous obligera à en partager d'autres (par exemple les examens sont dépendants des feuilles d'exercices).
</p>
<p>
Les questionnaires ne peuvent pas être partagés si l'un d'entre eux est un modèle préparé utilisant des variables techniques.
</p>
