
<b>Stop a resource sharing</b>.
<br>
Only a secondary sharing class can stop a 
!href cmd=help&special_parm=share sharing resource share
 among
!href cmd=help&special_parm=neighbor neighboring classes
.
<p>
If you stop the share, your class will be left with a copy of the shared
resources, in current status. Therefore stopping a share does not have any
immediate effect on your class. The only difference is that future
modifications on the resources, either by you or by the other classes, will
no longer affect the other.
<p>
In some cases, if you stop a sharing relation, you will be unable to recover
it. If this is the case, the server will prompt you before the stop operation
takes effect.

