
!set classname=<b><font color=green>$wims_classname</font></b>,\
  <b><font color=green>$wims_institutionname</font></b>
 
!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

!distribute items Exam, Sheet into name_E, name_S

!set name_title=活动统计
!distribute items 总计,要求的<br>得分,权重,难度<br>指数,\
按得分平均,按参加者平均,标准偏差,duration,score,\
理论持续时间,和, 分.,极小,极大\
into name_totals,name_required,_points,name_coeff,name_index,\
name_avg_score,name_avg_participant,name_deviation,name_duration,name_score,\
name_theoric,name_sum,name_minute,name_min,name_max

!distribute line 统计显示\
数据类型\
记录的活动, 不记录的活动, 所有活动\
与你共享作业页的<br>班级活动计数\
into name_showstat,name_data,name_typ_activities,name_shareclass

!set name_prompt=所需分数, 权重,\
    难度指数, 总计,\
    按得分平均, 按参加者平均,\
    极小与极大, 标准偏差