!if $exocnt<=0
 This sheet does not contain any exercise, hence its source is empty.
 !goto end
!endif

Here is the source of this sheet. You can copy this source (between the
two lines composed of `*'; use the press-paper)
in a file, which will allow you to reuse the content in another sheet
later. <br>
!href cmd=resume Main page for sheet maintenance.

<p>
******************************************************************
!read wimshome/$wims_sesdir/home_sheet.src
******************************************************************

:end

<p><center>
!href cmd=resume Main page for sheet maintenance.
</center> <p>

