
<hr width=1>
<center><h3>$wims_classname, $wims_institutionname</h3>
<hr> <p><h1>Work sheet #$sheet<br>$title</h1>
(Presentation for participants)
</center> <p>
<div class="wims_sheet_desc">$desc</div><p>

!if $exocnt=0
 The sheet is empty! Nothing is assigned for you in it. Possibly an 
 error in the manipulation by your supervisor.
!else
 Assigned works in this sheet:<p><ul>
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sheet
  !distribute lines $ex into di,pa,re,we,ti,de,dep
  <li><p>$i. 
  !href module=$di&cmd=new&worksheet=$parm1&$pa $ti
, $de
  !if $re>0
   <small>0 out of $[$re] points obtained, quality
   0/10. </small>
  !endif
 !next i
 </ul>
!endif
<p>
!homeref
<p><hr> <p>
<center>
!href cmd=resume Back to the page for supervisor.
</center>

!tail

!set job=

