<center><h3>Imágenes dinámicas</h3></center>

Es posible incluir imágenes en 2D en sus documentos. Estos dibujos son
programables, es decir que puede utilizar variables en sus instrucciones de dibujo, 
y el resultado variará con los valores de las variables. Es incluso posible 
generar animaciones.
<p>
Sintaxis&#58; <tt>\draw{xsize,ysize}{instrucción...}</tt>, 
donde <tt>xsize, ysize</tt> son respectivamente la longitud y la altura del 
dibujo (en pixels) e <tt>instrucción...</tt> es el contenido de las instrucciones.
Este es un texto compuesto por varias líneas, en las que cada línea es una instrucción.
<p>
!href cmd=help&special_parm=draw_example Ejemplo.

<p><hr> <p>

!changeto help/flydraw.phtml
