<center><h3>Dynamische Plaatjes</h3></center>
Het is onder Createxo --in html-formaat--  mogelijk om 
plaatjes op te nemen in het <em>statement</em> van de oefening.
<p>
Deze plaatjes worden dynamische gegenereerd, dwz je kunt (random)variabelen
gebruiken in de definitie van dit plaatje, tekening of functieplot. 

<p>
Syntax&#58; <tt>\draw{breedte,hoogte}{commando...}</tt>, waarin <tt>de breedte (xsize) en de hoogte (ysize) wordt uitgedrukt in pixels</tt>  <tt>commando...</tt> 
is de inhoud van de tekening. Deze inhoud mag uit meerdere opdrachten bestaan, elke opdracht op een nieuwe regel.
De draw{}{} functie kent ook het commando <em>curve of plot</em> waarin een mathematische formule kan worden geplot 
<tt>\draw{400,400}{ <br>
xrange -2*pi,2*pi
yrange -1*\a,1*\a
curve red,\a*sin(x)<br>
}<br>
geeft een 400 bij 400 pixel plaatje van met de rode curve f(x)=a*sin(x) tussen 2*pi en 2*pi met \a als -bijvoorbeeld- random variabele 
<p>

!href cmd=help&special_parm=draw_example voorbeeld

!changeto help/flydraw.phtml
