
!set field=!item 2 of $special_parm

!if $field=$empty
 !exit
!endif

!set embraced_randitem=<p> \
Dit veld accepteerd geneste accolades voor <em>random items</em>.\
<p>\
Als er tussen de accolades een lijst woorden of groepen woorden \
staat, gescheiden door komma's [een item lijst] , dan wordt een\
willekeurig item uit deze lijst gekozen.<br>\
Bijvoorbeeld wanneer U de volgende zin opneemt in een oefening:<br>\
\<font color=blue><tt>Ik ga naar {Parijs, New York, Londen, Amsterdam} \
{morgen,maandag ,volgende week !, op vakantie,als ik tijd heb}</tt></font><br>\
Dan kan die regel worden getoond als:\
<pre>\
Ik ga naar Amsterdam als ik tijd heb\
Ik ga naar Paris op vakantie\
Ik ga naar Parijs morgen\
Ik ga naar London volgende week !\
Ik ga naar New York maandag\
etc\
</pre>

!if $(special_parm[3])!=$empty
 !readproc model/cut.proc model/src/$(special_parm[3]).oef
 !set title$field=$model_title
!else
 !readproc model/cut.proc
 !set title1=$model_title
!endif

<center><h2>$(title$field)</h2></center>

!if $field=1
 <center><b>$desc</b></center> <p>
!endif

$(help$field)

!if $(name$field) iswordof $model_random
 <p>
 Enkele voorbeelden van willekeurig gekozen parameters:
 <ul>
 <li>een integer getal tussen 10 en 100 (inclusief):
	 <tt>randint(10..100)</tt>
 <li>een integer getal&times;10 tussen 10 en 1000  (inclusive):
	<tt>randint(1..100)*10</tt>
 <li>een decimaal getal tussen 0 en 2:
	<tt>random(0..2)</tt>
 <li>een willekeurig item uit een lijst:
	<tt>randitem(a,b,c,10,100,woord,of een komplete zin, f(x)=sin(x)</tt>
 </ul> <p>
!endif

!if $(name$field) iswordof $model_computed $model_random
 <p>
 Klik
 !href cmd=help&special_parm=parameters hier
 voor een gedetaileerdere uitleg over parameters.
!endif

