
<center><h3>Het OEF formaat</h3></center> <p>

OEF betekend ``online exercise format'', 
een formaat voor interactieve oefeningen bedoeld voor computer ondersteund onderwijs.
<p>
Het doel is om tot een goed uitwisselbaar formaat te komen.
Het voordeel van het OEF formaat is dat de oefeningen erg gemakkelijk te produceren zijn.
<p>
Om een beter inzicht te krijgen in de structuur van het OEF-formaat
kunt U de volgende
!href cmd=help&special_parm=examples voorbeelden
  bestuderen. <p>
<h4>Elementaire Syntax</h4> <p>
De schrijfwijze van het OEF-formaat is vergelijkbaar met die van LaTeX,
en opgebouwd uit "woorden of namen" (oef-directives) voorafgegaan door karakter <tt><b><font color=green>\</font></b></tt>,
en gevold door parameters omgeven door accolades.
Bij voorbeeld, in de volgende zin
<pre>
   \choice{het antwoord is }{ja}{nee}
</pre>
wordt het "woord" <tt>choice</tt> gebruikt, 
met een 3-tal parameters, namenlijk, <tt>het antwoord is</tt>, <tt>ja</tt>
en  <tt>nee</tt>.
<p>
<h4>Lijst van oef-directives</h4> 
<p>
Hier volgt een kort lijst van "woorden & namen" voor gebruik
in het oef-formaat 
Zie ook:
!href cmd=help&special_parm=parameters help bij parameters
 voor de gebruikte syntax om parameters te definieren.

<p>
<center>
<table border=2 bgcolor=$wims_ref_bgcolor>
$table_hdtr<th>oef-directive<th>aantal<br>parameters<th>omschrijving
$table_tr<td>titel<td align=center>1<td>definieert de titel van de oefening
$table_tr<td>taal<td align=center>1<td>de voertaal van de oefening zoals  
<tt>en</tt> of <tt>nl</tt>
$table_tr<td>schrijver<td align=center>1<td>de schrijver dan deze oefening
$table_tr<td>email<td align=center>1<td>het emailadres van de auteur
$table_tr<td>formaat<td align=center>1<td>formaat van het "statement": zie
!href cmd=help&special_parm=format help bij formaat van het "statement"
.
$table_tr<td>precisie<td align=center>1<td>precisie voor vergelijking  van het antwoord
met de goede oplossing. Een positief geheel getal n; de vergelijking wordt dan
op 1/n nauwkeurig
$table_tr<td>bereik<td align=center>1<td>het bereik van een variabele, wanneer een functie
met deze variabele wordt geevalueerd
Moet worden opgesteld in de vorm <tt>n1..n2</tt>, waarbij
<b>n1</b> het startpunt is en <b>n2</b> het eindpunt voorstelt.
<tr>
$table_tr<td>"statement"<td align=center>1<td>deze parameter is het "statement"
van de oefening
$table_tr<td>plot<td align=center>?<td>een dynamisch plot. (nog niet geheel klaar.)
<tr>
$table_tr<td>antwoord<td align=center>2<td>definieerd een freestyle antwoord. 
De eerste parameter is de gebruikersprompt voor het antwoord, de tweede parameter is
het goede antwoord zelf.<br> 
Het antwoord van de leerling kan aan de hand van diverse macro's worden gecontroleerd:
getal,functie,text enz
!href module=$module&cmd=help&special_parm=reply detail
.
$table_tr<td>choice<td align=center>3<td>definieerd een multiple choice vraag. 
De eerste parameter is wederom de prompt van de vraag, de tweede parameter is
de goede keuze (of meerdere goede keuzes), de derde parameter zijn de andere keuzes 
De tweede en derde parameters mogen/moeten ook een komma-seperated lijst zijn.
Meerdere goede oplossingen zijn uiteraard mogelijk.
Komt een bepaalde keuzemogelijkheid zowel voor in de "goede lijst" als ook
in de "foute lijst", wordt deze als goed beschouwd
$table_tr<td>condities<td align=center>2<td>definieerd een speciale randvoorwaarde
voor de evaluatie van het freestyle antwoord
Zie ook 
!href cmd=help&special_parm=reply help bij antwoorden
 voor de details.
<tr>
$table_tr<td>solution<td align=center>1<td>geeft de goede oplossing van de oefening,
met een uitleg hieraan gekoppeld
De "OEF manager" kan beslissen,gekoppeld aan de ingestelde moeilijkheidsgraad van de specifieke oefening, 
om dit wel of niet te laten zien.
$table_tr<td>hint<td align=center>1<td>geeft een tip bij de oefening
Ook hier geldt dat de "OEF manager" , wederom gekoppeld aan de door de
leerling/leraar ingestelde moeilijkheidsgraad, kan beslissen om deze wel of niet
te laten zien
$table_tr<td>help<td align=center>1<td>geeft hulp en toelichting bij de sommen.
Dit type help is altijd beschikbaar voor de leerling, en wordt getoond in een
klein popup-venster.
$table_tr<td>feedback<td align=center>2<td>geeft een feedback waarschuwing aan de leerling
wanneer er aan een speciale randvoorwaarde wordt voldaan.
Normaal zult U de feedback gebruiken om leerlingen te waarschuwen voor typische
fouten
!href cmd=help&special_parm=feedback Details over het feedback mechanisme
.
</table>

