
<center><h3>De beantwoording en beoordeling van een Createxo oefening</h3>
</center> <p>

Er zijn twee manieren waarop een "OEF" oefening antwoorden kan accepteren:
meerkeuze (multiple choices) en open (freestyle) antwoorden. 
Deze antwoorden kunnen worden beoordeeld naar gelang het type antwoord dat wordt gevraagd
Het is ook mogelijk om
!href cmd=help&special_parm=feedback feedbacks
 te geven aan de leerling, wanneer het antwoord aan een bepaalde
 randvoorwaarde of conditie voldoet. 
 (normaal om te waarschuwen voor een gebruikelijke fout) 

<p><h4>Multiple choice</h4> <p>
Een multiple choice is definieerd door een lijst van goede keuzes (een enkele of meerdere)
en een andere lijst van foute keuzes.<p>

Tot $choicelim verschillende multiple choice vragen kunnen binnen een enkele
OEF oefening worden gesteld, onder de huidige versie van WIMS.
Het aantal goede en slechte keuzes is vrijwel onbeperkt
(alleen beperk door de maximale stringlengte van 16kb in WIMS)
<p>
Zie ook 
!href cmd=help&special_parm=oef help bij het OEF formaat
voor de gebruikelijke syntax bij het definieren van multiple choice vragen 

<p><h4>Freestyle antwoorden</h4> <p>
Een freestyle antwoord wordt ingevoerd/ingevuld door de leerling
Tot  $answerlim  verschillende freestyle antwoorden kunnen in een enkele OEF oefening
worden verwerkt, onder de huidige versie van WIMS.
<p>

<a name=freestyle>
Elk freestyle antwoord  kan onafhankelijk van de eventuele andere freestyle antwoorden 
een van de volgende types zijn.<ol>
 <p><li>
 <b>Auto.</b> (naam: <tt>default</tt>)<br>
 De software tracht zelf vast te stellen van welk type het leerling antwoord moet zijn,
 afhankelijk van de gegeven goede oplossing.
 De mogelijkeden voor deze automatische herkening is natuurlijk beperkt, en kan
 aleen verschil zien tussen numerieke fucties/getallen/vergelijkingen/text.
 <p>
 <li>
 <b>Algebra&iuml;sche uitdrukking.</b> (naam: <tt>algexp</tt>) <br>
 Dit is een formele algebra&iuml;sche uitdrukking met beperkte vergelijkings mogelijkheden.
 Bijvoorbeeld <em>(x+1)(x-1)</em> wordt <b>niet</b> geaccepteerd wanneer het goede antwoord
 luidt <em>x^2-1</em>. 
 Het zelfde geldt voor sin(x)^2+cos(x)^2 versus 1.
 Alhoewel: x-y*y en -y^2+x wel als gelijk gelden .<p>
 

 <p><li>
 !read help/anstype/atext.phtml
 
 <p><li>
 <b>Karakter set.</b> (naam: <tt>chset</tt>) <br>
 Dit is een lijst met alpha-numerieke karakters,waarbij de volgorde geen rol speelt
 Case non-sensitive. <p>
 Dit kan worden gebruikt bij multiple-choice antwoorden, waarbij het aantal keuzes moet
 zijn vastgelegd, en waarbij er meerdere goede oplossingen zijn en de leerling
 ze allemaal moet vinden

 <p><li>
 <b>Finite set.</b> (naam: <tt>set</tt>) <br>
 Dit is een lijst met elementen, gescheiden door komma's, waarbij
 de volgorde der elementen geen rol speelt.
 Er wordt geen evaluatie uitgevoerd, zodat dus 2 en 1+1 niet gelijk zijn

 <p><li>
 <b>Finite set formal.</b> (naam: <tt>fset</tt>)<br>
 Gelijk aan <em>finite set</em>, behalve dat nu wel evaluatie plaats heeft,
 en de elementen als <em>formal expressions</em> worden geevalueerd.

 <p><li>
 <b>Finite set approximative.</b> (naam: <tt>aset</tt>)<br>
 Gelijk aan <em>finite set</em>,behalve dat de elementen worden geevalueerd als
 <em>approximative expressions</em>.

 <p><li>
 <b>Formal expression.</b> (naam: <tt>formal</tt>)<br>
 Gelijk aan numerieke functies, behalve dat er geen benadering is toegestaan

 
 <p><li>
 <b>Literal expression.</b> (naam: <tt>litexp</tt>)<br>
 Dit is een "formal expression" welke letterlijk wordt vergeleken met
 het goede antwoord. Er wordt geen algebraische vereenvoudiging toegepast
 Bijvoorbeeld x+y is niet gelijk aan y+x, 3/2 niet gelijk aan 6/4.
 Echter 2x en 2*x worden wel als gelijk gezien.
 Spaties verdwijnen tijdens deze controle. <p>

 <p><li>
 <b>Matrix.</b> (naam: <tt>matrix</tt>)<br>
 Gelijk aan "vector antwoord", elke co&euml;ffici&euml;nt wordt geevalueerd en
 vergeleken met de corresponderende co&euml;ffici&euml;nt in het goede antwoord

 <p><li>
 <b>Getal.</b> (naam: <tt>numeric</tt>)<br>
 Vergelijking van reeele getallen, tot de door de auteur bepaalde nauwkeurigheid.
 
 
 <p><li>
 <b>Getal met eenheden.</b> (naam: <tt>units</tt>)<br>
 Speciaal voor fysische grootheden met een bepaalde eenheid.
 Het antwoord wordt zo geevalueerd dat bijvoorbeeld <tt>1.5 cm</tt> en <tt>15 mm</tt>
 als gelijk worden beoordeeld !
 Ook hier tot een door de auteur vastgestelde nauwkeurigheid.
 
 <p><li>
 !read help/anstype/sigunits.phtml

 <p><li>
 !read help/anstype/chemeq.phtml

 <p><li>
 <b>Numerical function.</b> (naam: <tt>function</tt>)<br>
 Het antwoord wordt vergeleken met het goede antwoord, binnen een reeks waarden voor
 de variabelen zoals gedefinieerd door de auteur en
 ook hier tot een door de auteur vastgestelde nauwkeurigheid.
 
 
 <p><li>
 !read help/anstype/text.phtml
 
 <p><li>
 <b>Vector.</b> (name: <tt>vector</tt>)<br>
 Elke co&euml;ffici&euml;nt wordt geevalueerd en vergeleken met de corresponderende
 co&euml;ffici&euml;nt in de goede oplossing.
 Hierdoor kunnen alleen numerieke vectoren worden gebruikt.
 Het leerling antwoord als ook de goede oplossing kunnen met of zonder
 haakjes worden geformuleerd.
 
 <p><li>
 !read help/anstype/wlist.phtml
 
 <p><li><b>De keuzemenu's bij multiple choices</b>: <tt>checkbox</tt>,
 <tt>click</tt>, <tt>menu</tt>, <tt>radio</tt><br>
 Deze kunnen gebruikt worden om het standaard multiple choice input veld te 
 vervangen, om zo meer controle te krijgen over het uiterlijk van de oefeningen 
 De goede oplossing moet een tweetal velden bevatten, gescheiden door een  punt-komma
 ``<tt>;</tt>''. 
 Het tweede veld (achter de punt-komma) is de lijst van keuze teksten.
 Het eerste veld is een lijst getallen corresponderende met de goede keuzes
 In het geval van een <tt>checkbox</tt>, moet de leerling alle goede oplossingen aangeven. 
 Voor alle andere multipe choice inputvelden is een enkele goede oplossing afdoende
 <p>
 Een automatisch door elkaar schudden (shuffle) wordt in deze gevallen niet toegepast,
 en het aantal keuzes wordt niet automatisch beperkt.
 <p>
 <tt>click</tt> kan alleen gebruikt worden in die gevallen waar er geen
 anderen keuzes op invulvelden zijn.
 
 
</ol>

<p><h4>Test condities</h4> <p>
Onder sommige omstandigheden is het wenselijk dat de freestyle antwoorden worden
onderworpen aan speciale test condities, zoals bijvoorbeeld vragen met meerdere 
goede antwoorden, oefeningen die vragen om wat voorbeelden, antwoorden met ongelijkheidschema's
enzovoorts.
Dit kan op de volgende manier worden bereikt;
<p>
Als de goede oplossing of een freestyle vraag een ongedefinieerde variabele is,
kan het leerling antwoord  worden  ingevoerd in deze variabele, welke dan vervolgens
kan worden gebruikt om de testcondities te implementeren... 
Het cijfer voor een dergelijk opdracht wordt bepaald door het aantal testcondities
waaraan is voldaan ,en niet door het aantal antwoorden dat gelijk is aan
de goede oplossingen...  
<p>
Tot  $condlim  conditities kunnen in een enkele oef-oefening worden gedefinieerd
onder de huidige versie van WIMS. 
De syntax en verduidelijking is als volgt.
<p><tt>
\condition{prompt tekt}{test condities}
</tt> <p>
Hier zijn enkele voorbeelde van test condities.
 (<tt>\ans1</tt>  en <tt>\ans2</tt> zijn ongedefinieerde variabelen
zoals hierboven beschreven
<small>
!href target=wims_mhelp cmd=help&special_parm=if Complete lijst van relaties
</small>
<p>
$table_header
$table_hdtr<th>Conditie<th>betekenis
$table_tr<td><tt>\ans1>=0 and \ans1<=1</tt>
    <td>Goed als <tt>ans1</tt> is binnen het interval [0,1].
$table_tr<td><tt>\ans1=1 or \ans1=3 or \ans1=5</tt>
    <td>Goed als <tt>ans1</tt> is 1, 3 of 5.
$table_tr<td><tt>(\ans1)*(\ans2)=6 and (\ans1)+(\ans2)=5</tt>
    <td>Goed als <tt>ans1</tt> en <tt>ans2</tt> zijn de twee wortels 
    van de polynoom x<sup>2</sup>-5x+6.
$table_tr<td><tt>sin(\ans1)=0</tt>
    <td>Goed als <tt>ans1</tt> is een veelvoud van $m_pi.
$table_end <p>
Zie ook de help pagina bij het
!href cmd=help&special_parm=oef  OEF formaat
 ,voor de gebruikte syntax bij antwoorden.

