!!!Don't translate for the moment

<b>Mouvement dans un jeu d'échecs</b> (nom : <span class="tt wims_code_words">chessgame</span>)

La première ligne de la bonne réponse est la position des pièces présentée (entre crochets) :
<span class="tt">position des blancs ; position des noirs</span>.
La seconde ligne de la bonne réponse est formée des mouvements de pièces demandés (entre crochets).

La notation choisie est la notation algébrique internationale anglaise abrégée : 
<span class="tt">K</span> pour roi, <span class="tt">Q</span> pour reine, <span class="tt">R</span> pour tour, \
<span class="tt">B</span> pour fou, <span class="tt">N</span> pour cavalier et <span class="tt">P</span> pour pion.

Aucune vérification de règles n'est faite. Il s'agit simplement de mouvements de pièces.
Pour préciser la couleur (par défaut grise), mettre <span class="tt wims_code_words">color=nom_couleur</span>.
dans le champ <span class="tt wims_code_words">option</span>.
<pre>
\answer{}{[Kg1,g2,c3,f4,Rg8,Qh8;Qc7,f7,Rd6,c5,Kf5];[h8,e5;c3,c6]}{type=chessgame}{option=color=brown}
</pre>

Il peut y avoir plusieurs réponses possibles, elles sont séparées par le symbole 
<span class="tt wims_code_words">|</span>. Par exemple,
<pre>
\answer{}{[Kg1,g2,c3,f4,Rg8,Qh8;Qc7,f7,Rd6,c5,Kf5];[h8,e5;c3,c6|c7,e5]}{type=chessgame}
</pre>
signifie que la bonne réponse est soit deux déplacements successifs <span class="tt">h8,e5</span> puis <span class="tt">c3,c6</span> soit
un déplacement <span class="tt">c7,e5</span>.

!!Avec l'option <span class="tt wims_code_words">noorder</span> et dans le cas de plusieurs déplacements, l'ordre
!!des déplacements n'est pas imposé. (à supprimer ?)
<p>
L'option <span class="tt wims_code_words">noanswer</span> permet de ne pas afficher l'échiquier correspondant 
à la bonne réponse dans la partie principale de l'exercice. Celle-ci s'affiche alors simplement sous forme 
codée dans l'analyse de la réponse (pour supprimer l'analyse de la réponse, on peut utiliser l'option générale
<span class="tt wims_code_words">noanalyzeprint</span>).
</p>

<p>La variable <span class="tt wims_code_words">reply</span>n contient sur chaque ligne (indiquée par un 
point-virgule) les items suivants
</p>
<ul>
 <li>
le mouvement effectué,
 </li><li>
le nom des figures déplacées et (éventuellement remplacées)  entre crochets,
 </li><li>
le codage de l'échiquier après le mouvement.
 </li>
</ul>

