<b>Reconstituer une image présentée comme un puzzle.</b> (nom: <span class="tt wims_code_words">puzzle</span>)<br/>

<p> 
La bonne réponse contient deux champs, séparés par un point-virgule
 <span class="tt wims_code_words">;</span>. En général, le premier champ est le nom de l'image (qui doit être dans le dossier indiqué 
 par la variable <span class="tt wims_code_words">common_images</span>), le deuxième champ <span class="tt wims_code_words">N1 x N2 x W</span> indique que 
 l'image sera divisée en N1 lignes et N2 colonnes et que la largeur des morceaux du puzzle sera 
 de <span class="tt wims_code_words">W</span>. 

La taille totale de l'image (largeur x hauteur) doit être fournie dans le premier champ de <span class="tt wims_code_words">\embed</span> :
<span class="tt wims_code_words">\embed{r1, L x H}</span>.
</p>
<p>
Il est aussi possible de fournir une image déjà découpée. Dans ce cas, le deuxième champ est 
comme précédemment <span class="tt wims_code_words">N1 x N2 x W</span>, mais le premier champ est la liste des adresses 
des images dans l'ordre suivant : première ligne de gauche à droite,
deuxième ligne de gauche à droite, etc. (N1*N2 images doivent donc être fournies). 
Si le champ <span class="tt wims_code_words">option</span> contient le mot <span class="tt wims_code_words">text</span>, 
il est possible dans ce cas de remplacer toutes les images par du texte (sans virgule, ni point-virgule).
</p>
<p>
La variable <span class="tt wims_code_words">reply</span> i contient une suite de 1 et de 0 selon que le morceau correspondant 
est bien placé ou non.
</p>

Attention que deux morceaux ne soient pas identiques lors du découpage (par exemple, vides).

