#! /bin/sh

cd classification;
./classif.pl

cd ../sys;
taxonomy/taxo.pl --module=1 --output=adm/browse
taxonomy/taxo.pl --option=1  --output=adm/browse
taxonomy/taxo.pl --output=adm/tool/classification/keywords
