!set wims_html_header=!append line $oefcss to $wims_html_header
!header1
!read adm/title.phtml 2\
$sheet_title

<div class="wims_sheet_desc">$sheet_desc</div>

$sheet_remark

!if $error!=$empty
 !changeto lang/msg.phtml.$modu_lang
!endif

!if ($wims_developer!= or $wims_supervisor!= or $wims_user=supervisor) and $latex_exists=1
  <div class="wimscenter">
  !read oef/latex.proc print
  </div>
!endif
!for i=1 to $N
 <br class="spacer" />
 <span class="bold">$name_exo</span> $i - <span class="oefnameexo">$(title_$i)</span><br />
 !if $(question_$i)=$empty
  ($name_noprint)
 !else
  !if __EXECUTED_ isin $(question_$i) and _EXERCISE__ isin $(question_$i)
   !set e_=$(e_$i)
   !set thisexo=$e_
   !set m_=$(module_$i)
   !readproc imagedir.proc
   !for k=1 to $(varcnt_$i)+5
    !set val$k=!line $k of $(var_$i)
   !next k
   !set wims_prefix=
   !read $(class_header)def/$(e_$i).def question
   !set wims_prefix=$wims_prefix2
  !else
   $(question_$i)
  !endif
  <a></a>
  $(chce_$i)
 !endif
!next i

!if $public!=P and $wims_user!=supervisor
 !goto noans
!endif

<br class="spacer" /><hr/>
<div class="wims_solution">
<h3 class="wimscenter">$wims_name_answer</h3>
!for i=1 to $N
 !set t=!linecnt $(ans_$i)
 !if $t>0
  <br class="spacer" />
  <span class="bold">$name_answer $i.</span>
  <ul style="list-style-type:square;">
  !for k=1 to $t
   !set l__=!line $k of $(ans_$i)
   !if $l__ !=
    <li value="$k">
    !line $k of $(ans_$i)
    </li>
   !reset l__
   !endif
  !next k
  </ul>
 !endif
!next i
</div><!--end of wims_solution-->

:noans

!set wims_menu_items=!append line renew,1,cmd=reply\
back2,1,cmd=reply&job=read\
to $wims_menu_items
!tail
