
!if $datacnt<1
 Er staan geen modules geregistreerd op deze server.
 Let op: dit werkt alleen vanaf het in versie <b>WIMS-3.37f</b> 
 geintroduceerde publicatie en updating-systeem
 !exit
!endif

$table_header
<caption>Nieuwe modules geinstalleerd op deze server</caption>
$table_hdtr<th>Datum</th><th>Taal</th><th>Titel</th><th>Omschrijving</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_ 
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>$desc</td></tr>
 !reset desc tit
!next i
$table_end
