#! /bin/sh

if [ "$(id -ru)" = 0 ]; then
 cat <<@
You are trying to compile WIMS as 'root'. You should not do that !
Please compile as 'wims'.
@
 exit 1
fi

##########################################################################
cat <<@
Welcome to the compilation of WIMS (WWW Interactive Multipurpose Server)

@

cd `dirname $0`
cd src
if [ -f ../.wims_maintainer_mode ]; then
  if (autoconf); then :; else
    echo "[maintainer mode] Please install autoconf first."
    exit 1
  fi
  autoheader
fi
./configure || exit
make clean || exit
make all || exit
cd ..
cp src/defaults.conf public_html/bases/sys/defaults.conf
cat <<@

Please run 'bin/wrapuid' as root (e.g. using sudo) to finish WIMS setup.
See README about installation of help and teaching modules.

@
