#! /bin/sh

#Make distribution tgz packages

version=`cat version`
target=$HOME/transfer_wims

echo  "About to create release tarball wims-$version in $target."
echo  "Did you check your wims package (by hand, checkwims or test suite...)"
echo  "and agree to continue this script ? (y/n)? [n] "
read ans
if [ "$ans" != "y" ] && [ "$ans" != "Y" ]; then
  exit 
fi

echo "** Create or Clean $target..."
mkdir -p $target
rm -Rf $target/*

echo "** Export svn in $target/wims"
cd `dirname $0`
svn export . $target/wims
cd $target/wims
# disable "maintainer-only" extensions in the exported version : don't run
# autoconf / autoheader
rm -f .wims_maintainer_mode

# call script for permissions
bin/changepermissions

echo "** Insert current version number in README.template"
#on met le numéro de version où il faut
sed -e "s/WIMS_VERSION/$version/" $target/wims/README.template > $target/wims/README
rm -f $target/wims/README.template
cp $target/wims/README $target/wims/public_html/README

echo "** Create configure file using autoconf"
cd $target/wims/src; autoconf; autoheader

echo "** Remove temporary files"
rm -Rf *.cache *.log 2>/dev/null
rm $target/wims/mkdistsvn
find $target/wims -name .DS_Store -exec rm '{}' \;
find $target/wims -name \._* -exec rm '{}' \;

echo "** Archiving WIMS package..."
cd $target/wims ; tar -czf ../wims-$version.tgz .
