#! /bin/sh

#Je n'ai pas réglé le problème des images dont on a changé le nom ...
#C'est un problème dans un module
# Make distribution tgz packages
#on execute le script dans le dossier wims

#ligne à changer
# 3.63a = r256
# 3.63b = r468
# 3.63c = r677
# 3.63d = r720
# 3.64  = r798
# 3.65a = r798
# 3.65b = r940
# 3.65c = r1377
# 3.65d = r1451
# 3.65e = r1479
# 3.65f = r1511
# 3.65h = r1832
# 3.65i = r1872
# 3.65j = r1941
# 3.65k = r1989
# 3.65l = r2098
# 3.65m = r2626
# 3.65n = r2784
# 3.65o = r2907
# 3.65o = r3000
# 3.65p = r3??
# 3.65q = r3100
# 4.00  = r3243
# 4.01a = r3378
# 4.01c = r3585
# 4.01d = r3707
# 4.01e = r3745

version=`cat version`

#on mettra la version intermédiaire dans $target
target=$HOME/transfer_wims

#pense-bête
echo  "Did you check your wims package (by hand, checkwims or test suite...)"
echo  "and agree to continue this script ? (y/n)? [n] "
read ans
if [ "$ans" != "y" ] && [ "$ans" != "Y" ]; then
  exit 
fi

#on nettoie $target
echo "** Create or Clean $target..."
mkdir -p $target
rm -Rf $target/*

# Puis on y exporte la version SVN
echo "** Export svn in $target/wims"
cd `dirname $0`
svn export . $target/wims
cd $target/wims
# disable "maintainer-only" extensions in the exported version : don't run
# autoconf / autoheader
rm -f .wims_maintainer_mode

# call script for permissions
bin/changepermissions

echo "** Insert current version number in README.template"
#on met le numéro de version où il faut
sed -e "s/WIMS_VERSION/$version/" $target/wims/README.template > $target/wims/README
rm -f $target/wims/README.template
cp $target/wims/README $target/wims/public_html/README

echo "** Create configure file using autoconf"
cd $target/wims/src; autoconf; autoheader

echo "** Enlève les fichiers générés par autoconf"
rm -Rf *.cache *.log 2>/dev/null

echo "** On enlève le mkdistsvn de la nouvelle version"
rm $target/wims/mkdistsvn

echo "** On enlève les fichiers parasites"
find $target/wims -name .DS_Store -exec rm '{}' \;
find $target/wims -name \._* -exec rm '{}' \;

# problème avec forall, je l'ai enlevé du svn
#mkdir -m 777 $target/wims/tmp/forall

echo "** Archiving WIMS package..."
cd $target/wims ; tar -czf ../wims-$version.tgz .
