 Dans le mode sélectif, vous pouvez imposer une
 restriction dans le temps pour l'enregistrement des notes en ajoutant des
 mots
 <font color=blue><b>
 <tt>&gt;aaaammjj.hh:mm</tt></b></font>
 (début) et/ou
 <font color=blue><b>
 <tt>&lt;aaaammjj.hh:mm</tt></b></font>
 (fin). Les dates et heures doivent être en temps local du SERVEUR
 et ces mots doivent être séparés les uns des autres par des espaces.
 </small>

