
!if ~ notin $mod
 <b>注意</b>. 此模块只有简化地址"<tt>$mod</tt>".
建议作
 !href cmd=reply&jobreq=move&original=devel/$auth_login/$mod 地址更新
.
 <p>
!endif

!set doctest1=!module category devel/$auth_login/$mod

你的模块
<em><font color=blue>$title</font></em> ($description)
<small>
!href cmd=reply&jobreq=index $mod
</small>
包含下列文件. 
!if document isin $doctest1
 (<i>For document files, click on the link <tt>Document manager</tt></i>.)
!endif

!set table_cellpadding=1
!set table_cellspacing=0
!set table_center=
!set table_header=!replace internal <> by in $table_header
!set table_end=!replace internal </> by in $table_end
<p>$table_header
$table_hdtr
<th>名称<th>作用</th><th>解释
 !for f in $files
  $table_tr
  <td align=left nowrap>$f
  <td align=center nowrap>  
  !href cmd=reply&jobreq=showfile&fname=$f 显示
  &nbsp;
  !href cmd=reply&jobreq=edfile&fname=$f 编辑
  &nbsp;
  !href cmd=reply&jobreq=delfile&fname=$f 删除
  !if oef isin $doctest1 and ../src/ isin ../$f and .oef/.. isin $f/..
   !set f_=!translate internal / to , in $f
   !set f_=!item -1 of $f_
   !set f_=!replace internal .oef.. by in $f_..
   &nbsp;
   !href target=wims_test module=adm/createxo&catmodule=devel/$auth_login/$mod&existing=$f_ Createxo
  !endif
&nbsp;</td><td align=left>
  !set t_=!translate . to _ in $f
  !set t_=$($t_)
  !default t_=--
  $t_  
 !next f
$table_end

!form reply
<input type=hidden name=jobreq value=edfile>
添加新文件:
<input size=20 name=fname value="$lastfname">
<input type=submit value=提交>
!!!href cmd=reply&jobreq=binfile 二进制文件
!!&nbsp;
!!!href target=wims_test module=tool/directexec&cmd=new 脚本测试
</form>

!reset fname

