!set size=50

!if $title=$empty or $modreq=.new
 !set this=你的新模块
!else
 !set this=目前开发中的模块
!endif
!form reply
<input type=hidden name=jobreq value=flist>
$table_header
<caption>$this的属性</caption>

$table_tr<td align=right nowrap>地址
 <td>
 !if $title!=$empty and $modreq!=.new
  <tt>$modreq</tt>&nbsp;
  !href cmd=reply&jobreq=move&original=devel/$auth_login/$modreq 改名
&nbsp;
  !href cmd=reply&jobreq=copy&original=devel/$auth_login/$modreq 复制
 !else
  !set modreq=.new
  !read scripts/addressform.phtml nook
 !endif

$table_tr<td align=right nowrap>名称
 <td><input size=$size name=i_title value="$i_title">

$table_tr<td align=right nowrap>描述
 <td><input size=$size name=i_description value="$i_description">

$table_tr<td align=right nowrap>语言
 <td>
 !default i_language=$module_language
 !formselect i_language list $langlist prompt $langname

$table_tr<td align=right nowrap>类型
 <td nowrap>
 !set wims_formselect_switch=multiple
 !formcheckbox i_category list exercise,tool,document,recreation,oef,deductio

$table_tr<td align=right nowrap>领域
 <td>
 <input size=$size name=i_domain value="$i_domain">

$table_tr<td align=right nowrap>年级
 <td>
 !formcheckbox i_level list $levellist
 <br><small>E: 小学; H: 中学; U: 大学;
 <br>G: 研究生; R: 研究工作</small>

$table_tr<td align=right nowrap>评分机制<br>
 <small>(练习/游戏)</small>
 <td>
 !default i_scoring=no
 !formradio i_scoring list yes,no prompt 是, 不

$table_tr<td align=right nowrap>版本
 <td>
 !default i_version=1.00
 <input type=text size=6 name=i_version value="$i_version">
 <small>当你发布新版本时别忘了增加版本号!</small>

$table_tr<td align=right nowrap>WIMS版本号
 <td>
 !default i_wims_version=$wims_version
 <input type=text size=6 name=i_wims_version value="$i_wims_version">&nbsp;
 !href cmd=help&special_parm=wimsversion 帮助

$table_tr<td align=right nowrap>作者
 <td>
 !default i_author=$auth_name
 <input type=text size=$size name=i_author value="$i_author">

$table_tr<td align=right nowrap>作者电邮
 <td>
 !default i_address=$auth_email
 <input type=text size=$size name=i_address value="$i_address">

$table_tr<td align=right nowrap>翻译者
 <td>
 <input type=text size=$size name=i_translator value="$i_translator">

$table_tr<td align=right nowrap>翻译者电邮
 <td>
 <input type=text size=$size name=i_translator_address value="$i_translator_address">

$table_tr<td align=right nowrap>对支持软件的要求
 <td>
 !formcheckbox i_require list $swlist prompt $swname

$table_tr<td align=right nowrap>关键词
 <td><input size=$size name=i_keywords value="$i_keywords">

$table_tr<td align=right nowrap>版权
 <td>
 !set wims_formselect_switch=
 !formselect i_copyright list gnu prompt GNU GPL

$table_hdtr<td align=center nowrap colspan=2>
<input type=submit name=inddef value="记录修改">
&nbsp;&nbsp;
<input type=submit value="取消">
$table_end
</form>

