!read adm/css.phtml
!header

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif
!read $job.phtml

!if $auth_login!=$empty and $job!=modname
 <p>
 !if $job iswordof flist edfile showfile binfile
  !href target=wims_test module=devel/$auth_login/$mod 测试模块
. &nbsp;
  !set doctest=!module category devel/$auth_login/$mod
  !if document isin $doctest
   !href target=wims_test module=adm/doc.$module_language&devdoc=$mod&doc=1&job=read 文件管理者
. &nbsp;
  !endif
 !endif
 !if $job iswordof flist index publish prop diff binfile
  !if $job iswordof index publish diff
   !href cmd=reply&jobreq=flist 模块内容
. &nbsp;
   !href cmd=reply&jobreq=binfile 二进制文件
. &nbsp;
  !endif
  !if $job iswordof binfile
   !href cmd=reply&jobreq=flist 其它文件
. &nbsp;
  !endif
  !if $job iswordof flist publish diff binfile
   !href cmd=reply&jobreq=index 属性
. &nbsp;
  !endif
  !if $job notwordof publish prop diff
   !href cmd=reply&jobreq=backup 备份此模块
. &nbsp;
   !if $pubtit!=$empty
    !href cmd=reply&jobreq=diff 检查相互区别
. &nbsp;
   !endif
   !href cmd=reply&jobreq=publish 发布
. &nbsp;
  !endif
 !endif
 !href cmd=reply&jobreq=modname 模块表
.
!endif

!tail

!reset confirm target1 target2 target3 target4 vcheat \
    i_translator i_translator_address, modifiers \
    p_name p_email p_pass1 p_pass2 bin_job

