
!if $passchange!=yes
修改你的位于<font color=blue><tt>$httpd_SERVER_NAME</tt></font>的开发者账户的属性
 <font color=blue><tt><b>$auth_login</b></tt></font>:
 <small>(如果不想修改密码, 可把此栏留空)</small>
!else
你的账户密码已经修改.
!endif
<p>

!form reply
<center><table border=0>
<tr><td align=right nowrap><label for="p_name">姓名:</label> </td>
<td><input type=text size=40 name=p_name id="p_name" value="$auth_name">
</td></tr>
<tr><td align=right nowrap><label for="p_name">电邮地址:</label> </td>
<td><input type=text size=40 name=p_email id="p_email" value="$auth_email">
</td></tr>
<tr><td align=right nowrap><label for="p_name">密码:</label> </td>
<td><input type=password size=20 name=p_pass1 id="p_pass1">
</td></tr>
<tr><td align=right nowrap><label for="p_name">重复密码:</label> </td>
<td><input type=password size=20 name=p_pass2 id="p_pass2">
</td></tr>
<tr><td align=center colspan=2 nowrap>
<input type=submit name=confirm value="保存">
<input type=submit value="取消">
</td></tr></table> </center> <p>
</form>
