
!if $rep!=$empty
 !if $status=ERROR
  !read msgcl.phtml $rep2
  <p><hr width="50%"><p>
 !else
  <pre>$rep</pre>
  <p>
  !if $m1=local
几分钟后, 发布的模块就会出现在网站的搜索引擎里.
   <p>
如果这是一个错误, 请
   !mailurl $wims_site_manager 要求网站管理员
手工删除你已发布的模块.
  !else
你将收到一个确认你的发布的电邮.
  !endif
 !endif
 !exit
!endif

!if $askcheat=yes
本模块声明所需的WIMS版本是WIMS-$Wver2,
而本服务器的版本是$wims_version. 你应该更新模块的 INDEX 文件.
 <p><center>
 !href cmd=help&special_parm=wimsversion 解释
.
 !href cmd=reply&vcheat=no 好, 继续
.
 </center> <p>
如果你清楚你在做什么, 你可以
 !href cmd=reply&vcheat=yes 欺骗服务器
使它认为你是在一个旧版的服务器上(非常冒险的行为)!
 !exit
!endif

!if $pubprep=yes
 !if $local!=yes
  !href cmd=help&special_parm=publish 先阅读这里!
这是一个公开地址的模块, 它应被发布到发布中心 <tt>$centralhost</tt>.
请输入你的发布身份.
  !form reply
  <input type=hidden name=confirm value=yes>
  <input type=hidden name=vcheat value="$vcheat">
  <p><center><table border=0 cellpadding=4>
  <tr><td align=right>提交身份: </td>
  <td><input type=text size=20 name=submitauth value="$submitauth">
  </td></tr>
  <tr><td align=right>提交密码: </td>
  <td><input type=password size=20 name=submitpass value="$submitpass">
  </td></tr>
  <tr><td align=right>发布类型: </td>
  <td>
  !set submittype=devel
  !formselect submittype list devel,stable,new prompt \
    开发版, \
    稳定版 - 修改已有模块, \
    稳定版 - 新模块
  </td></tr>
  <tr><td align=right>本模块从别的<br>语言翻译的吗?
  </td><td>
  !set istranslate=no
  !formselect istranslate list yes,no prompt 是,否
  </td></tr>
  <tr><td align=right>授权的修改者:
  </td><td>
  <input size=40 name=modifiers value="$modifiers">
  !href cmd=help&special_parm=modifiers <sup>帮助</sup>
  </td></tr>
  <tr><td colspan=2 align=center><input type=submit value=提交>
  </tr>$table_end <p>
如果你是已有模块的新版, 你增加过版本号吗?
  <p>
如果没有, 则谁也不会更新到你的新版本.
 !else
你的模块有一个本地地址. 它只能发布在本服务器的本地空间. 
继续吗?
  <p><center>
  !href cmd=reply&confirm=yes&vcheat=$vcheat 继续
  &nbsp
  !href cmd=reply&jobreq=flist 取消
  </center> <p>
发布在本地空间的优点是此模块能被本地服务器的搜索引擎发现.
 !endif
!endif

