!set levelE=école élémentaire
!set levelH=école secondaire
!set levelU=universitaire

!set lang_fr=français
!set lang_en=English
!set lang_es=español
!set lang_nl=nederlands

!if $cltype iswordof 2 4
   !if $cltype=2
    !set name_classe=groupement de classes
    !set name_sup=de l'enseignant-administrateur
    !set name_classes= le $name_classe
    !set name_classess= un $name_classe
    !set name_classesss= du $name_classe
    !set name_classessss= Le $name_classe
   !else
    !set name_classe=établissement
    !set name_sup=de l'administrateur
    !set name_classes= l'$name_classe
    !set name_classess= un $name_classe
    !set name_classesss= de l'$name_classe
    !set name_classessss= L'$name_classe
    !endif
 !else
   !set name_classe=classe
   !set name_classes=la classe
   !set name_classess=une classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=de l'enseignant
 !endif



