
$table_header
<caption>Campi utilizzabili per i dati degli studenti</caption>
$table_hdtr<th>Nome</th><th>Significato</th></tr>
$table_tr<td><tt class="wims_code_variable">login</tt></td><td>login dell'iscritto</td></tr>
!if $special_parm!=upload
$table_tr<td><tt class="wims_code_variable">name</tt></td><td>cognome e nome (in quest'ordine, due colonne)</td></tr>
!endif
$table_tr<td><tt class="wims_code_variable">lastname</tt></td><td>cognome</td></tr>
$table_tr<td><tt class="wims_code_variable">firstname</tt></td><td>nome</td></tr>
$table_tr<td><tt class="wims_code_variable">password</tt></td><td>password dell'iscritto (in fase di download
è sempre codificata, ma può essere inserita sul server non codificata).</td></tr>
$table_tr<td><tt class="wims_code_variable">email</tt></td><td>indirizzo email</td></tr>
$table_tr<td><tt class="wims_code_variable">regnum</tt></td><td>registration number</td></tr>
$table_tr<td><tt class="wims_code_variable">photourl</tt></td><td>URL di una foto</td></tr>
$table_tr<td><tt class="wims_code_variable">comments</tt></td><td>commenti relativi all'iscritto</td></tr>

!if $special_parm!=upload
$table_tr<td><tt class="wims_code_variable">allscore</tt></td><td>tutti i punteggi e le m edie</td></tr>
$table_tr<td><tt class="wims_code_variable">averages</tt></td><td>medie (sia dei voti assegnati dal server, 
che dei voti assegnati dal docente)</td></tr>
$table_tr<td><tt class="wims_code_variable">average1</tt></td><td>media dei voti assegnati dal server</td></tr>
$table_tr<td><tt class="wims_code_variable">average2</tt></td><td>media dei voti assegnati dal docente</td></tr>
$table_tr<td><tt class="wims_code_variable">sheets</tt></td><td>punteggi ottenuti in tutti i test 
(uno per colonna)</td></tr>
$table_tr<td><tt class="wims_code_variable">sheet1,sheet2,...</tt></td><td>punteggio ottenuto nel test 1, 
test 2, ...</td></tr>
$table_tr<td><tt class="wims_code_variable">exams</tt></td><td>punteggi ottenuti in tutti gli esami</td></tr>
$table_tr<td><tt class="wims_code_variable">exam1,exam2,...</tt></td><td>punteggio ottenuto nell'esame1, 
esame 2, ...</td></tr>
$table_tr<td><tt class="wims_code_variable">manuals</tt></td><td>tutti i voti assegnati manualmente
(uno per colonna)</td></tr>
!else
$table_tr<td><tt class="wims_code_variable">participate (nel caso di un portale di sede e solo per
il coordinatore)</tt></td><td>sigle dei corsi a cui lo studente risulta iscritto 
nella forma abcdefg/1/101 dove abcdefg è il numero del portale. Se più corsi, 
separati da spazi.</td></tr>
!endif
$table_tr<td>manual1,manual2,...</td><td><tt class="wims_code_variable">voti assegnati manualmente 1, 2, ... (uno per colonna)</tt></td></tr>
$table_tr<td><tt class="wims_code_variable">var_xxx</tt></td><td>variabile tecnica <tt>xxx</tt></td></tr>

$table_end <p>

I campi non riconosciuti vengono ignorati. Le variabile tecniche possono 
essere utilizzare per limitare la registrazione dei punteggi nei
test di autovalutazione o nei temi d'esame.
<p>
!if $special_parm=upload
Dans le cas du champ <tt class="wims_code_variable">participate</tt>, il est possible de rajouter des classes mais pas d'en enlever.
!endif

