
!read adm/title.phtml 1\
\
Caricare dati in formato csv

Per caricare sul server dati da un foglio eletronico, salvare i dati
in un formato testo (txt, csv, o tsv), quindi inviare il file al server.
<p>
È possibile inserire dati sugli iscritti o voti. Per inserire dati sugli
utenti è necessario che il file non contenga voti.
<p>
La prima riga della tabella deve contenere i nomi di ciascuna colonna.
Nomi validi e relativo significato sono illustrati nella tabella che segue. 
È possibile scegliere ogni combinazione di colonne e inserirle in 
qualsiasi ordine, con l'unica condizione che deve essere presente
una colonna &lsquo;login&rsquo; (WIMS utilizza questo campo per individuare
ogni iscritto). Le righe che contengono &lsquo;#&rsquo; nel &lsquo;login&rsquo;
vengono ignorate dal server.
<p>
È possibile utilizzare questo metodo per aggiungere iscritti (molti alla
volta), ma in questo caso la tabella dei dati deve contenere informazioni
suffcienti (in particolare <tt class="wims_code_words">login</tt>firstname</tt>, 
<tt class="wims_code_words">login</tt>lastname</tt>, <tt class="wims_code_words">login</tt>password</tt>).
<p>
Si possono inserire voti solo per colonne già esistenti, in altre parole
prima di caricare i dati da un file occorre creare le colonne (non
si possono modificare i dati assegnati dal server).
<p>
Segue un esempio di file valdo per l'inserimento di nuovi studenti:
<pre>
login,firstname,lastname,password
toto,Claude,Toto,1234
</pre>
!read lang/help.$moduclass_lang/fieldtab.phtml
