
!read adm/title.phtml 1\
\
Caricare dati in formato csv

Per caricare sul server dati da un foglio eletronico, salvare i dati
in un formato testo (txt, csv, o tsv), quindi inviare il file al server.
<p>
È possibile inserire dati sugli iscritti o voti. Per inserire dati sugli
utenti è necessario che il file non contenga voti.
<p>
Si possono inserire voti solo per colonne già esistenti, in altre parole
prima di caricare i dati da un file occorre creare le colonne (non
si possono modificare i dati assegnati dal server).
</p><h3>Authentification via WIMS</h3>
La prima riga della tabella deve contenere i nomi di ciascuna colonna
(per esempio, <tt class="wims_code_words">login</tt>, <tt class="wims_code_words">firstname</tt>, ...).
Nomi validi e relativo significato sono illustrati nella tabella che segue. 
È possibile scegliere ogni combinazione di colonne e inserirle in 
qualsiasi ordine, con l'unica condizione che deve essere presente
una colonna <tt class="wims_code_words">login</tt> (WIMS utilizza questo campo per individuare
ogni iscritto). Le righe che contengono <tt class="wims_code_words">#</tt> 
nel campo <tt class="wims_code_words">login</tt>
vengono ignorate dal server.
<p>
È possibile utilizzare questo metodo per aggiungere iscritti (molti alla
volta), ma in questo caso la tabella dei dati deve contenere informazioni
suffcienti (in particolare nome, cognome, password).

<p>
Segue un esempio di file valdo per l'inserimento di nuovi studenti:
<pre>
login,firstname,lastname,password
toto,Claude,Toto,1234
</pre>

<h3>Autenticazione esterna</h3>
Il formato dei file è lo stesso, ma si può sostituire il campo <tt
class="wims_code_words">login</tt> con il campo <tt
class="wims_code_words">external_auth</tt>.
È necessario inserire i campi nome e cognome (<tt
class="wims_code_words">firstname</tt>, <tt
class="wims_code_words">lastname</tt>) a meno che non si utilizzi un
server di autenticazione ldap (cfr. pagine di configurazione del
corso).
In questo caso (e solo in questo caso) è sufficiente inserire
l'identificativo per autenticazione esterna (<tt
class="wims_code_words">external_auth</tt>).
Ricordiamo che la modifica del tipo di autenticazione è fortemente
sconsigliata una volta che gli studenti sono stati inseriti nel corso.

<p>
Segue un esempio di file valdo per l'inserimento di nuovi studenti:
<pre>
external_auth,firstname,lastname
toto,Claude,Toto
</pre>
!read lang/help.$moduclass_lang/fieldtab.phtml
