!set name_institution=nom de la institució
!set name_description=nom de la classe
!set name_supervisor=nom del supervisor
!set name_email=adreça electrònica
!set name_password=contrasenya de la classe
!set name_passsup=contrasenya del supervisor
!set levelid=M1,E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,U1,U2,U3,U4,U5,G,R
!set leveldesc=Pàrvuls,P1,P2,P3,P4,P5,P6,ESO1,ESO2,ESO3,ESO4,BAT1,BAT2,U1,U2,U3,U4,U5,Doctorat,Recerca
!set nblevel=!itemcnt $levelid

!set classname=<b><font color=green>$description</font></b>\
 de <b><font color=green>$institution</font></b>

!set months=gener,febrer,març,abril,maig,juny,juliol,agost,setembre,octubre,novembre,desembre

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=grup de classes
    !set name_sup=professor coordinador
   !else
    !set name_classe=portal de la institució
    !set name_sup=de l'administrador
   !endif
   !set name_classes= el $name_classe
   !set name_classess= un $name_classe
   !set name_classesss= del $name_classe
   !set name_classessss= El $name_classe
!else
   !set name_classe=classe
   !set name_classes=la $name_classe
   !set name_classess=una $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=del professor
!endif
