<p><h1 class="wims_title">Ho sento</h1> <p>
El nombre de classes en aquest lloc <font color=red>$httpd_HTTP_HOST</font>
que ja ha arribat al límit, el lliure
accés a la creació de classes està tancat. <p>

Si és realment important per a vossaltres crear una classe, podeu
!mailurl $wims_site_manager escriure al gestor del lloc\
WIMS@$httpd_HTTP_HOST creation of class
 demanant-li de crear manualment una classe per a vostè. <p>

Recordeu que també podeu crear una classe en qualsevol lloc WIMS que us
accepti. També podeu 
<a href="http://wims.unice.fr/download/wims">descarregar el programari de WIMS</a>
i instal·lar-lo al vostre lloc.
