<p><center><h1>Désolé</h1></center> <p>
Le nombre de classes sur ce site <font color=red>$httpd_HTTP_HOST</font>
ayant déjà atteint la limite, le libre
accès à la création de classes est fermé. <p>

S'il  est vraiment important pour vous de pouvoir créer une classe, vous pouvez
!mailurl $wims_site_manager écrire au gestionnaire du site\
WIMS@$httpd_HTTP_HOST creation of class
 pour lui demander de créer une classe pour vous manuellement. <p>

Sachez que vous pouvez aussi créer une classe sur tout site WIMS qui vous
accepte. Il vous est aussi possible de 
<a href="http://wims.unice.fr/download/wims">télécharger le logiciel de WIMS</a>
et de l'installer sur votre site.

