!read adm/title.phtml 3\
\
Dépendences de ressources dans une classe

<p>
Il y a beaucoup de dépendances compliquées entre les différents types de
ressources dans une classe virtuelle.
</p><p>
Par exemple, les feuilles d'examen sont définies en faisant référence aux feuilles d'exercices,
et les dernières peuvent utiliser des exercices de la classe. Donc si vous modifiez ou effacez
les derniers, les premiers ne pourront plus fonctionner correctement.
</p><p>
Aussi, les notes de participants sont calculées en temps réel, basées sur le
registre d'activités ainsi que sur les niveaux de sévérité des feuilles. Si
vos feuilles d'exercices actives sont changées, les notes ne pourront plus
être calculées correctement même si le registre d'activités est intact.
</p>
