<hr />
!form reply
<p>
$name_enterof: <em>$username</em> ( / $maxscore):
</p><table class="wimsnoborder">

!for g=1 to $gcnt
 !set t_=!item $g of $titles
 !set g_=!item $g of $grades
 <tr><td style="text-align:right">$t_</td>
 <td><input size="6" name="c$g" value="$g_" /></td>
 </tr>
!next g
</table>
<div class="wimscenter wimsform"><input type="submit" name="reg" value="$wims_name_tosave" /></div>

!formend
