!reset confirm
!read adm/css.phtml
!header1

!read names.phtml

!if $job iswordof student
 !changeto $job.phtml
!endif

!if $cmd=help
 !read help/$special_parm.phtml
 !goto end
!endif

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$name_title

<p>
!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !goto end
!endif

!if $job=getsource
 !read getsource.phtml
 !goto end
!endif

!if $activetest>-1
 <b>Werkblad informatie :</b>
!endif
!read adm/sheet/sheetinfo.phtml

!ifval $activetest=-1
 !goto end
!endif

:end1
<a name=list></a>
<b>Content of the sheet :</b>
!if $exocnt=0
 <p>Dit werkblad is leeg en heeft nog geen oefingen.
!else
 <small>[
 !href module=adm/sheet&sh=$sheet&job=print $wims_name_printable
 ]</small>
 !read adm/sheet/sheetcontent.phtml
!endif

!if $activetest=0
 <p>
 Om oefeningen (of cursussen, hulpmiddelen etc) aan een werkblad toe te voegen,
 stel deze dan in (afhankelijk van uw wensen) en start de oefening, 
gebruik de link onderaan de pagina van de oefening "Voeg toe aan werkblad".
 <p>
 U kunt :
  <ul>
   <li> de interne zoekmachine gebruiken :
	!read adm/search_engine/form.phtml
   </li>
   <li> 
    !href cmd=reply&job=prep_putsource $wims_name_putsource
   </li>
  </ul>
!endif

:end
!if $activetest>=0
 !if $activetest=0
  !let wims_menu_items=!append line putsource,1,cmd=reply&job=prep_putsource to $wims_menu_items
 !endif
 !if $job!=getsource
  !let wims_menu_items=!append line sheetsource,1,cmd=reply&job=getsource to $wims_menu_items
 !endif
 !let wims_menu_items=!append line ,0,\
printable,1,module=adm/sheet&sh=$sheet&job=print\
participantview,1,module=adm/sheet&sh=$sheet to $wims_menu_items
!endif

!tail

!distribute item ,, into job,source,title,desc,prpage

