
!set classname=<b><font color=green>$wims_classname</font></b>\
 van <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,Mei,Jun,Jul,Aug,Sept,Okt,Nov,Dec

!set statutname=!defof SU_Uprep,SU_Uprep,SU_Ac,SU_Ex,SU_Hi in wimshome/public_html/modules/home/names.$lang
!set statutaction=Activeren,Laat verlopen,Deactiveren,Verbergen,Tonen,$wims_name_erase
!set seriesaction=$wims_name_change,$wims_name_erase,$wims_name_up

!! definition des noms pour les liens dans le menubox (définis par wims_menu_items)
!distribute items Voeg een broncode toe,\
		zo zien studenten het werkblad,\
		Broncode van het werkblad \
into wims_name_putsource,wims_name_participantview,wims_name_sheetsource

!let name_shtab=No,$wims_name_title,$wims_name_Description,Punten,Gewicht,Afhankelijkheden,$wims_name_comment,$wims_name_action

!if $activetest<=0
 !let wims_name_sheetadmin=Werkblad aanmaak pagina
 !set name_title=!nosubst Aanmaken van werkblad $sheet
!else
 !let wims_name_sheetadmin=Werkblad beheer
 !set name_title=!nosubst Beheer van werkblad $sheet
!endif

!let name_shinfo=!nosubst $wims_name_title <small>(beperkt tot $title_limit karakters)</small>,$wims_name_Status,\
Omschrijving <br></small>(beperkt tot $desc_limit karakters; html en links toegestaan)</small>,\
Verloopdatum,Presentatie pagina,Cijfer registratie,voor alle delende klassen,$wims_name_comment
!let name_allowtype=open voor iedereen,gesloten voor iedereen, open voor de volgende netwerkadressen (en/of tijden) :
!let name_mksheet=Maak het werkblad

!distribute lines Werkblad informatie\
Inhoud van dit werkblad\
Dit werkblad is leeg en heeft nog geen oefeningen.\
De originele titel is\
Verandering van item\
Aantal vereiste punten\
met een weging: \
Correct the source\
The sheet expiration date of the sheet must be before the class expiration date which is\
Your request is ignored.\
into name_info,name_content,name_warning,name_oldtitle,name_titlemodif,\
name_pointsasked,name_ofweight,name_correctsource,name_expiration1,name_expiration2

!set name_text1=Om oefeningen (of cursussen, hulpmiddelen etc) aan een werkblad toe te voegen,\
 stel deze dan in (afhankelijk van uw wensen) en start de oefening, \
gebruik de link onderaan de pagina van de oefening "Voeg toe aan werkblad".<p> U kunt:

!set name_text2=De interne zoekmachine gebruiken
!set name_text3=Zoek een oefening onder 
!set name_text4=Zoek een oefening in uw eigen account

!if $job=student
  !set name_title=Werkblad $sheet<br>$title ( Presentatie voor studenten)
  !set name_sheetempty=Het werkblad is leeg! Waarschijnlijk een foutje van de docent.
  !set name_assignedwork=De opdrachten in dit werkblad&nbsp;
  !set name_quality=0 uit $[$re] punten behaald, kwaliteit
!endif

