!! +exec+ +html+
tit:href
type:$type_exec
syntax:!href ``parms text''
mean:Creates a hypertext reference pointing to the wims server. <br/>\
  Whenever possible, this command should be used instead of a direct use of\
  html tag ``&lt;a href="..."&gt;''. <br/>\
  ``parms'' is the string of parameters to the call to wims server,\
  which should not contain white spaces. Usually a ``cmd=...'' pair should be at least present;\
  on the other hand, the session number and prefered language will be directly added by the server. \
  <br/>\
  ``text'' is the text on which the hypertext link sits. It can be\
  any text or a &lt;img...&gt; tag, but dynamic insertions are not accepted yet.\
  <br/>There is no need to add the end tag ``&lt;/a&gt;''.\
  <p>The target of the reference can be controlled via the variable\
  ``wims_ref_target''. It can also be defined via an optional word\
  ``target=...''. Note that in this case the target must start with ``wims_''.\
  </p>
