!! +var+ +exec+ +string+
tit:makelist
type:$type_both
syntax:!makelist ``templ'' for ``v''=``v1'' to ``v2'' [step ``st''], or <br/>
$ !makelist ``templ'' for ``v'' in ``v1,v2,v3,...''
mean:Outputs a list consisting of ``templ'' with variable ``v'' successively substituted \
  by values ``v1'', ..., ``v2''. <p>\
  In the second syntax, the substitutions are done with respect to each item in\
  the list ``v1,v2,...''. </p><p>\
  The variable ``v'' should appear in ``templ'' as a math variable \
  (that is, with no preceeding character). </p><p>For example, the command</p>\
<pre>!makelist [x;x+1;xx] for x in a,x and y,1,(2,3)</pre>\
  gives the result\
  <pre>\
  !makelist [x;x+1;xx] for x in a,x and y,1,(2,3)\
  </pre>
