!! +exec+ +jump+
tit:read
type:$type_exec
alias:include, input
syntax:!read ``file'' [``parm'']
mean:Insert the content of ``file'', and process it. ``file'' must be a valid file name with \
  the module's home directory as base directory. (directory structure may be specified in ``file'',\
  but backtracing to parent directories is prohibited.)\
  <br/>And the parameter ``parm'' can be accessed from within\
  the called ``file'' under the variable name ``wims_read_parm''.\
  <br/>\
  WIMS will try to cache the file for repeated use, unless the filename  is preceded by "./".
