!! +var+ +exec+ +string+
tit:recursion
type:$type_both
syntax:!recursion ``fn'' for ``v''=``v1'' to ``v2'' [step ``st'']\
$ !recursion ``fn'' for ``v'' in ``v1,v2,v3,...''
mean:Computes the outcome of a recursion using the function ``fn'' in which the\
  variable ``v'' is replaced successively by values ``v1'', ..., ``v2''. <p>\
  In the second syntax, the values are given with respect to each item in\
  the list ``v1,v2,...''. </p><p>\
  The function ``fn'' should use the variable ``last'' to indicate the value of the previous \
  recursion step. And the starting value can be put into the WIMS variable\
  <span class="tt">&#36;recursion_start</span>. </p>
