<cebter><b>Suggerimenti per la registrazione dei voti</b></center>
Selezionando &ldquo;limitata ai seguenti IP (e/o periodi)&rdquo; 
è possobile restringere la registrazione dei voti utilizzando i seguenti
formati per le date:
<font color=blue><b>
<tt>&gt;yyyymmdd.hh:mm</tt></b></font>
(data e ora di inizio) and/or
<font color=blue><b>
<tt>&lt;yyyymmdd.hh:mm</tt></b></font>
(data e ora di fine). Queste date devono essere espresse nel fuso orario 
del SERVER, e devono essere separate tramite spazi l'una dall'altra (o da
eventuali altre istruzioni simili.

