
<ul>
 <li><p><b>Q.</b><i> ¡He olvidado mi contraseña personal!</i> <p>
 <b>A.</b>  Puede perdirle a su profesor que le asigne una nueva contraseña 
 a su inscripción (es conveniente que la modifique posteriormente).
 
 <li><p><b>Q.</b><i> He terminado un ejercicio pero no he recibido 
 puntuación.</i> <p>
 <b>A.</b>  Ciertos ejercicios requieren que termine una sesión de varias 
 preguntas antes de darle una puntuación. Asegúrese de que ha llegado al final 
 de la sesión.
 <li><p><b>Q.</b><i> El servidor no graba mi puntuación.</i> <p>
 <b>A.</b> Hay varias cosas que debe verificar.<ul>
  <li>A veces el profesor le permite trabajar en los ejercicios pero
   restringe la grabación de las puntuaciones a un periodo de tiempo o
   a unos ordenadores limitados. Si es este el caso, verá el mensaje
   <em>`no está permitida la grabación de puntuaciones desde su conexión'</em>
   en la parte inferior de su página de ejercicios.
   <li>Si obtiene más puntos en un ejercicio de los que solicita
   el profesor, la puntuación extra quedará oculta y no se tendrá en
   cuenta a la hora de calcular el total de puntos. Sin embargo la calidad
   de los puntos sí será calculada en TODAS las puntuaciones, ocultas o no.
   <li>Si cambia la configuración de un ejercicio, no se tendrán en
   cuenta los puntos obtenidos trabajando en el ejercicio reconfigurado.
   Y en este caso desaparecerá el enlace ``hoja de ejercicios'' de las
   partes superior e inferior de su hoja de ejercicios.
 </ul>
 <li><p><b>Q.</b><i> ¿Puedo elegir el mismo ejercicio varias veces
  antes de trabajar en él?</i> <p>
 <b>A.</b> Puede hacerlo unas cuantas veces (el número exacto es secreto) sin
  penalización. Pasado ese límite, recibirá varios ceros en este ejercicio
  (lo que reduce la calidad de la puntuación pero no cambia el número de
  puntos obtenidos).
 <li><p><b>Q.</b><i> ¿Puedo obtener más puntos en un ejercicio que el número
  asignado por el profesor?</i> <p>
 <b>A.</b> Puede trabajar en un ejercicio tantas veces quiera, y obtener 
  tantos puntos como desee. Sin embargo el servidor descartará los puntos que 
  sobrepasen el número asignado cuando calcule sus resultados (porcentaje
  de trabajo realizado).
  <p>
  Por otro lado la calidad de la puntuación se calcula sobre todo el
  trabajo que ha realizado en sus ejercicios, sean los asignados o extra.
  Por tanto si continúa trabajando en el ejercicio tiene la posibilidad de
  mejorar esta calidad (y también la posibilidad de empeorarla si comete
  errores).
 <li><p><b>Q.</b><i> ¿Cómo afectan a mis calificaciones globales ambos 
  números (el porcentaje de trabajo realizado y la calidad de la 
  puntuación?)? </i> <p>
 <b>R.</b> El servidor calcula las calificaciones según una fórmula que 
  depende del nivel de severidad de la hoja. Este nivel lo determina el 
  administrador del ejercicio, y las fórmulas están descritas en la página 
  de calificaciones (haga click en el enlace `ayuda' de la parte superior 
  de dicha página).
</ul>
