
El trabajo en las clases virtuales se organiza en hojas de ejercicios.
<p>
Cada clase virtual puede tener hasta 4 hojas de ejercicios, y cada hoja puede
incluir hasta 64 artículos. Un artículo de trabajo puede ser
cualquier módulo de WIMS: ejercicios, herramientas o cualquier otro.
<p>
Cada hoja de ejercicios tiene un estado. Una hoja recién creada está en
estado de <em>en preparación</em>, lo que permite que se añadan y modifiquen
artículos de trabajo. Este es el único estado en que se puede borrar la
hoja. Una hoja de ejercicios en preparación es visible únicamente para el
profesor responsable.
<p>
Cuando el profesor activa una hoja de ejercicios en preparación, la hoja 
pasa al estado de <em>activa</em>. Ya no puede modificarse ni borrarse, y
los participantes podrán trabajar en ella.
<p>
Cada hoja de ejercicios tiene una fecha de expiración. Tras esta fecha pasa
a <em>expirada</em>, en cuyo caso los participantes seguirán viéndola y
podrán trabajar en ella, pero no se grabará ninguna puntuación.
<p>
Y una hoja expirada puede pasar a <em>oculta</em>, en cuyo caso los 
participantes ya no la ven (pero siempre estará visible para el
profesor).
<p>
El profesor puede cambiar manualmente el estado de una hoja de ejercicios
entre <em>activa</em>, <em>expirada</em> y <em>oculta</em> (en cualquier
dirección, de activa a expirada o expirada a activa, etc.).
