<center><h3>Embed answers into the statements</h3></center>

:signification
It is possible to embed (include) answers into the statement of your
exercises under html format. The embedded replies and choices should be
defined usually.


:example
 <span class="wims_help_example">Examples</span>
 <ul>
<li><tt>\embed{reply 1}</tt> insert the first freestyle reply into the text.
<li><tt>\embed{reply 2,10}</tt> insert the second freestyle reply into the text,
with an input field of size 10.
<li><tt>\embed{choice 1}</tt> insert the first multiple choice into the text.
</ul>

Special case. If the type of <tt>reply 1</tt> is among <tt>checkbox</tt>,
<tt>click</tt>, <tt>radio</tt>, <tt>\embed{reply 1,2}</tt>
inserts only one of the choices (here the number 2 in this case), either
clickable (<tt>click</tt>) or with a button for marking it. This allows
insertions of the choices in versatile text structures.
