!set embraced_randitem=<p> \
This field accepts the randomization by nestable curly embraces.\
<p>\
If you put several words (or groups of words), separated by commas,\
within a pair of embraces, one of the words will be randomly drawn\
at the time when the text is presented to students. This will add\
randomness to your text. <p>\
For example, if you enter the text <p>\
<font color=blue><tt>I will go to {Paris, New York, London} \
{tomorrow, the next week}</tt></font>,\
<p>the result will be one of the following sentences, at random:\
<pre>\
I will go to Paris tomorrow\
I will go to New York tomorrow\
I will go to London tomorrow\
I will go to Paris the next week\
I will go to New York the next week\
I will go to London the next week\
</pre>

!set name_random=Some examples of random generation of parameter: <ul>\
 <li>For an integer between 10 and 100 (inclusive):\
	 <tt>randint(10..100)</tt>\
 <li>For an integer multiple of 10 between 10 and 1000 (inclusive):\
	<tt>randint(1..100)*10</tt>\
 <li>For a decimal number between 0 and 2:\
	<tt>random(0..2)</tt>\
 <li>For a random item within a list:\
	<tt>randitem(a,b,c,10,100,word,a phrase)</tt>\
 </ul>
 
!set name_detail_parm=More details on the computation of parameters.


