:Advanced facilities
:Function,Example,Effect
:pari
pari(factor(2^101-1))
call PARI/GP: here to factor an integer
:maxima
maxima(integrate(x^2+1,x);)
call Maxima: here to integrate a function
:yacas
yacas(Taylor(x,0,10) cos(x^2+x+1))
call Yacas: here to compute a Taylor expansion
:wims
wims(sort items \list) wims(listintersect \list1 and \list2)
use wims command : for example !sort command to sort items in the list \list, !listintersect command to get the common items of \list1 and \list2
:draw
draw(pixel_size_x,pixel_size_y<br>draw_source)
draw a picture, the source is the same as in <tt>\draw</tt>, with the image size as the first line. The output is an image URL.
:slib
slib(matrix/invertible 3,5)
use of macro routine (slib) : for example here an invertible 3x3 matrix of range 5.
