!set proc=oef
!header

!if $wims_class=$empty
 <p>
 Questo è un modulo interno di un corso virtuale, pertanto
 solo gli utenti registrati del corso possono
 accedervi.
 </p>
 <p style="text-align:center;">
 !href $ $wims_name_home
 </p>
 !exit
!endif

<p>Questo modulo raccoglie esercizi interattivi per il corso
<span class="wims_classdesc">$wims_classname</span>
(<span class="wims_institutiondesc">$wims_institutionname</span>).</p>
!if $wims_user=supervisor
 <p>
  !set wims_ref_class=wims_button
  !href module=adm/createxo  <span class="icon_button add_exo">Crea un nuovo esercizio</span>
 </p>
!endif

!read oef/intromenu.phtml
!tail

