<center>WIMS toegangs beleid</center>
<p>

Dit kan meerdere regels bevatten, en wordt regel voor regel ingelezen.
De beperkingen gelden niet voor de administatie modules.
Regels die beginnen met een  `<tt class="wims_code_words">#</tt>' worden genegeerd [commentaar].
<p>
Elke regel is in het formaat <tt class="wims_code_words">[toegangs condities : host conditions]</tt>.
<p>
De <tt class="wims_code_words">[toegangs condities]</tt> is een lijst met sleutelwoorden.
Meerdere "keyword" worden ge_AND.
Elk keyword kan eventueel voor afgegaan worden door <tt class="wims_code_words">non</tt>. 
De beschikbare keywords zijn:
<p>$table_header
$table_tr<th>keyword</th><th>betekenis</th></tr>
$table_tr<td><tt class="wims_code_words">class</tt></td><td>Voor het inloggen in een virtuele klas.</td></tr>
$table_tr<td><tt class="wims_code_words">com</tt></td><td>De opgevraagde module valt onder de publiek bereikbare algemene modules.</td></tr>
$table_tr<td><tt class="wims_code_words">document</tt></td><td>De opgevraagde module is een WIMS document.</td></tr>
$table_tr<td><tt class="wims_code_words">exercise</tt></td><td>De opgevraagde module is een WIMS oefening.</td></tr>
$table_tr<td><tt class="wims_code_words">hint</tt></td><td>Er wordt een hint verzocht.</td></tr>
$table_tr<td><tt class="wims_code_words">local</tt></td><td>De opgevraagde module valt onder lokaal geinstalleerde modules.</td></tr>
$table_tr<td><tt class="wims_code_words">recreation</tt></td><td>De opgevraagde module is van het type "ontspanning".</td></tr>
$table_tr<td><tt class="wims_code_words">tool</tt></td><td>De verzochte module is van het type "gereedschap" of popup calculators.</td></tr>
$table_end
<p>

De <tt>[host conditions]</tt> kan elke gangbare host_definitie zijn,
eventuel aangevuld met openinges en sluitings tijden , zoals deze ook voor werkbladen mogelijk is.
Als het eerste letterteken van zo'n 'host conditie' een ``<tt>!</tt>'' is , en
de 'host' of tijd komt overeen, dan wordt de toegang geblokkeerd.
In alle andere gevallen is de klas dan open.

<p><hr> <p>

!read help/hosts.phtml

<p><hr> <p>
Enkele voorbeelden:
<p>
# alle computers uit het sub domein 134.59.102.* krijgen geen toegang tot de "tools"
<br><tt>tool:! 134.59.102.</tt>
<p>
# alle anonieme computers afkomstig van het domein www.stmichaelscollege.nl worden geblokkeerd om vrije oefeningen te gebruiken
<br><tt>exercise nonclass:! www.stmichaelscollege.nl </tt>
<p>
# computers afkomstig van de provider zonnet.nl mogen geen wiskundige documenten opvragen
<br><tt>doc nonclass:! .zonnet.nl</tt>
<p>
# Leerlingen van Schaersvoorde mogen op 1 jan. 2009 niet werken met WIMS
<br><tt>class: ! .schaersvoorde.nl >20090101.00:00 <20090101.23:59</tt>
<p>

