<center><h3>De functie "Embed" :<br> antwoorden in statements</h3></center>

:signification
Het is ook mogelijk om midden in de html-text van het 
<em>statement</em> de leerling het antwoord te laten invoeren. 
Dit gebeurt met behulp van de </em>\embed{}</em> functie.
De syntax is eenvoudig:<br>
<em>\embed{rely n , m}</em><br>
<em>\embed{choice k}</em><br>
waarin reply<em>n</em> het n<sup>de</sup> antwoord is 
(per definitie is het eerste freestyle antwoord \answer{}{} reply 1) 
en <em>m</em> de invul-veldbreedte aangeeft 
(5 betekend een blanko veld van 5 karakters breed) 
Waarin </em>k</em> het k<sup>de</sup> multiple choice antwoord is.


:example
 <span class="wims_help_example">Voorbeelden</span>
 <ul>
<li><tt>\embed{reply 1}</tt>Vul het eerste freestyle antwoord in
<li><tt>\embed{reply 2,10}</tt>Vul het tweede freestyle antwoord in, veldbreedte is nu 10
<li><tt>\embed{choice 1}</tt> Vul de eerste multiple choice vraag in .
</ul>
Een speciaal geval: als het type <tt>reply 1</tt> is<br>
 <tt>checkbox</tt>,<br>
<tt>click</tt>,<br>
 <tt>radio</tt>, <br>
 dan geeft <tt>\embed{reply 1,2}</tt> 1 van de bovengenoemde alternatieven.<br>
  In dit geval dus nummer 2 , een klik-knop. 
