
<center><h3>Feedback bij de antwoorden </h3>
</center> 
<p>
U kunt diverse condities definieren waarbij bij bepaalde antwoorden een
opmerking (waarschuwing voor veel voorkomende fouten e.d.) wordt geplaatst
op de eind resultaat pagina.
<p>
Een willekeurig aantal feedbacks kan worden toegevoegd, bij elk antwoord model (freestyle of multiple choice). 
De syntax is als volgt:
<p><tt>
\feedback{CONDITION}{MESSAGE}
</tt> <p>
Deze regel kan in het parameter invulveld worden geplaats als je in "guided mode" werkt,
of op een willekeurige plek in de expert mode.
<p>
Wanneer aan de  <tt>CONDITION</tt> is voldaan, dan wordt
<tt>MESSAGE</tt> aan de leerling getoond op de eind resultat pagina.
De antwoorden kunnen zowel in de variabele <tt>\reply1</tt>,
<tt>\reply2</tt>,... (bij freestyle antwoorden), als ook in <tt>\choice1</tt>, 
<tt>\choice2</tt>,... (bij multiple choice). 
De volgorde van deze varabelen is gelijk aan die in de broncode.
<p>
<t>MESSAGE</tt> is "vrije" text, waaronder ook embedded html-tags en wiskundige symbolen.
<p>$table_header
<caption>Voorbeelden van deze condities/voorwaarden
<small>
!href target=wims_mhelp cmd=help&special_parm=if complete lijst
</small>
</caption>
$table_hdtr<th>conditie/voorwaarde<th>wanneer aan voldaan
$table_tr<td><tt>\reply1=5<td>eerste freestyle antwoord is exact gelijk aan 5
$table_tr<td><tt>\reply1&gt;\reply2+2<td>eerste freestyle antwoord is &gt; tweede  plus 2
$table_tr<td><tt>\choice1=JA en\choice2=NEE
<td>eerste multiple choice is JA en de tweede is NEE (<b>PAS OP</b>het vergelijken
in multiple choice mode is wel hoofdletter gevoelig/case-sensitive
$table_tr<td><tt>\reply1&lt;5 of \reply1&gt;8
  <td>eerste antwoord ligt buiten het bereik van  5 to 8.
$table_tr<td><tt>3 isitemof \reply1
  <td>het eerste antwoord, van het type "set" of "vector", bevat een component "3".

$table_end
<p>
<b>Known-bug</b>.Voorkom door elkaar gebruik van <tt>\reply</tt> en
<tt>\choice</tt>binnen een enkele conditie/randvoorwaarde.
Het resultaat wordt anders onvoorspelbaar. 


