
<h2 class="wimscenter">Feedback bij de antwoorden </h2>
<p>
U kunt diverse condities definieren waarbij bij bepaalde antwoorden een
opmerking (waarschuwing voor veel voorkomende fouten e.d.) wordt geplaatst
op de eind resultaat pagina.
</p><p>
Een willekeurig aantal feedbacks kan worden toegevoegd, bij elk antwoord model (freestyle of multiple choice).
De syntax is als volgt:
</p>
<pre>
\feedback{CONDITION}{MESSAGE}
</pre>
Deze regel kan in het parameter invulveld worden geplaats als je in "guided mode" werkt,
of op een willekeurige plek in de expert mode.
<p>
Wanneer aan de  <span class="tt">CONDITION</span> is voldaan, dan wordt
<span class="tt">MESSAGE</span> aan de leerling getoond op de eind resultat pagina.
De antwoorden kunnen zowel in de variabele <span class="tt wims_code_variable">\reply1</span>,
<span class="tt wims_code_variable">\reply2</span>,... (bij freestyle antwoorden), als ook in <span class="tt wims_code_variable">\choice1</span>,
<span class="tt wims_code_variable">\choice2</span>,... (bij multiple choice).
De volgorde van deze varabelen is gelijk aan die in de broncode.
</p><p>
<span class="tt">MESSAGE</span> is "vrije" text, waaronder ook embedded html-tags en wiskundige symbolen.
</p>
$table_header
<caption>Voorbeelden van deze condities/voorwaarden
<small>
!href target=wims_mhelp cmd=help&special_parm=if complete lijst
</small>
</caption>
$table_hdtr<th>conditie/voorwaarde<th>wanneer aan voldaan
$table_tr<td class="tt wims_code_words">\reply1=5</td><td>eerste freestyle antwoord is exact gelijk aan 5</td></tr>
$table_tr<td class="tt wims_code_words">\reply1&gt;\reply2+2</td><td>eerste freestyle antwoord is &gt; tweede  plus 2</td></tr>
$table_tr<td class="tt wims_code_words">\choice1=JA en\choice2=NEE</td>
<td>eerste multiple choice is JA en de tweede is NEE (<b>PAS OP</b>het vergelijken
in multiple choice mode is wel hoofdletter gevoelig/case-sensitive
</td></tr>$table_tr<td class="tt wims_code_words">\reply1&lt;5 of \reply1&gt;8</td>
  <td>eerste antwoord ligt buiten het bereik van  5 to 8.</td></tr>
$table_tr<td class="tt wims_code_words">3 isitemof \reply1</td>
  <td>het eerste antwoord, van het type "set" of "vector", bevat een component "3".
</td></tr>
$table_end
<p>
<b>Known-bug</b>.Voorkom door elkaar gebruik van <span class="tt wims_code_variable">\reply</span> en
<span class="tt wims_code_variable">\choice</span>binnen een enkele conditie/randvoorwaarde.
Het resultaat wordt anders onvoorspelbaar.
</p>

