
<h3>Het OEF formaat</h3>

<p>
OEF betekend ``online exercise format'', 
een formaat voor interactieve oefeningen bedoeld voor computer ondersteund onderwijs.
</p><p>
Het doel is om tot een goed uitwisselbaar formaat te komen.
Het voordeel van het OEF formaat is dat de oefeningen erg gemakkelijk te produceren zijn.
</p><p>
Om een beter inzicht te krijgen in de structuur van het OEF-formaat
kunt U de volgende
!href cmd=help&special_parm=examples voorbeelden
  bestuderen. </p>
<h4>Elementaire Syntax</h4>
<p>
De schrijfwijze van het OEF-formaat is vergelijkbaar met die van LaTeX,
en opgebouwd uit "woorden of namen" (OEF-directives) vooraf gegaan door een "slash" 
<tt class="wims_code_variable">\</tt>,
en gevolgd door parameters omgeven door accolades.<br>
Bij voorbeeld, in de volgende zin
</p>
<pre>
   \choice{het antwoord is }{ja}{nee}
</pre>
wordt het "woord" <tt class="wims_code_words">\choice</tt> gebruikt, 
met een 3-tal parameters: <tt class="wims_code_words">\het antwoord is</tt>, <tt class="wims_code_words">\ja</tt>
en  <tt class="wims_code_words">\nee</tt>.


<h4>Lijst van OEF-directives</h4> 
<p>
Hier volgt een korte lijst van "woorden & namen" voor gebruik
in het OEF-formaat.
Zie ook:
!href cmd=help&special_parm=parameters help bij parameters
 voor de gebruikte syntax om parameters te definieren.
</p>

