:Wiskundige functies
:Functie,Example,Effect
:evalue
evalue(x^2+sin(y),x=3,y=4)
evaluatie van functie x^2+sin(y), voor x=3, y=4
:solve
solve(x^3-3*x+1,x=0..1)
de numerieke wortel van x^3-3x+1 tussen 0 en 1
:simplify
simplify(x^5*y^3*x^2/y)
vereenvoudig algebraisch : x<sup>7</sup>y<sup>2</sup>
:diff
diff(sin(x)+cos(y),x)
de afgeleide van sin(x)+cos(y) naar x
:int
int(x^2+3*x+1,x)
de primitieve van x^2+3*x+1, geen contante vermeld.
:int
int(t^2+3*t+1,t=0..1)
de numerieke integratie van x^2+3*x+1, van 0 tot 1
:det
det(\mat)
determinant van matrix \mat
:htmlmath
htmlmath(2*x^2+3*x)
probeert op de beste manier de vergelijking in html weer te geven: <small>2</small><em>x</em><sup><small>2</small></sup>+<small>3</small><em>x</em>
:texmath
texmath(sin(x^2/pi)+3/x)
geeft de texcode: \sin(\frac{x^{2}}{\pi} + \frac{3}{x}

:sin tg tan sec (1/sin) cot cotan cotan ctg csc (1/cos)

fonctions trigonométriques
:acos acos arccos acos arcsin asin arctan atan arctg atan 

fonctions trigonométriques réciproques
:sh sinh tanh tanh th ch cosh coth cotanh 

fonctions hyperboliques

:Argch acosh argch Argsh asinh argsh Argth atanh argth

fonctions hyperboliques réciproques
:sqrt
\real{a=sqrt(32)}
racine carrée
:binomial
\integer{a=binomial(9,3)}
le coefficient binomial (pour des coefficients inférieurs à 10^7 sinon
utiliser la fonction de pari \text{a=pari(binomial(50,10))}
:ceil
\real{a=ceil(3.4)}
le plus petit entier supérieur
:floor
\real{a=floor(3.4)}
le plus grand entier inférieur
:rint round
\real{a=rint(3.4)}
closest integer
:e E
\real{a=e^2}
constante mathématique $m_e
:erf
:erfc
:EULER Euler euler
:exp
:factorial
\integer{a=factorial(4)}
factorielle
:Inf
\real{a=Inf + 3}
l'infini
:gcd
\integer{a=gcd(4,6)}
pgcd de deux entiers
:lcm
\integer{a=lcm(4,6)}
ppcm de deux entiers
:max
\real{a=max(4,6)}
maximum de deux nombres
:min
\real{a=gcd(4,6)}
minimum de deux nombres
:lg log10
\real{a=log10(10^4)}
log en base 10
:lgamma
\real{a=lgamma(e^(24))}
log de la fonction Gamma
:ln log
\real{a=ln(e^4)}
log népérien
:log2 mylog2
\real{a=log2(2^4)}
log en base 2
:pow
\real{a=pow(3,0.6)}
puissance, équivalent à  3^0.6
:sgn sign
\integer{a=sign(-4)}
signe de la valeur
:PI Pi pi
\real{a=sin(Pi)}
constante mathématique $m_pi
