
<h3><center>Een document als presentatie pagina voor een werkblad</center></h3>
U kunt een werkblad ook voorzien van een WIMS documenten blok, zoals
<tt>c1/main</tt>. Dit kan dienen als presentatie pagina voor de inhoud van het werkblad.
 Het behandelde materiaal in een werkblad kan zo meer samenhang en context krijgen.
 Het document zelf hoeft niet leesbaar te worden gemaakt voor leerlingen.
<p>
De syntax voor de links naar de individuele oefeningen:
<tt>\exercise</tt>.
<br>
De volgende variabelen zijn ook beschikbaar:
<ul>
 <li><tt>\scorerequire</tt> het benodigde aantal punten voor iedere oefening
 </li><li><tt>\scoregot</tt>  het behaalde aantal punten voor iedere oefening
 </li><li><tt>\scoremean</tt> de gemiddelde score voor elke oefening
 </li><li><tt>\expiration</tt> de verloopdatum van het werkblad [yyyymmdd]
 </li><li><tt>\today</tt> de datum [yyyymmdd]
 </li>
</ul>
<p>
Laat dit veld leeg als U de standaard opmaak wilt gebruiken.
