!set job2=first

!read lang/names.phtml.$moduclass_lang connect_first_info
<p>
!if $ccnt<1
 !set basedir=!sh cd ..; pwd
 !read lang/names.phtml.$moduclass_lang connect_first
 !exit
!endif

$name_listserver1
<p>$table_header
$table_hdtr<th>$wims_name_name
<th>$wims_name_Description<th>$wims_name_Address<th>$wims_name_Type<th>$wims_name_action
!for s in $Clist
 
 $table_tr
 <td>$s
 <td align=center>$(desc_$s)
 <td align=center><a href="$(url_$s)">$(site_$s)</a>
 <td align=center>$(type_$s)
 <td align=center nowrap><small>
 !href cmd=reply&job2=testserver&connident=$s $wims_name_test
 &nbsp;
 !href cmd=reply&job2=add1&connident=$s $wims_name_addconnection
 </small>
!next s
$table_end <p>

!if $clcnt<1
 $name_noconnection
 !exit
!endif

$name_declaration
<p>
!distribute items yes,no into io1,io0
$table_header
$table_hdtr<th>$wims_name_server<th>$wims_name_class
<th>$name_connexion_action<th>-
!for clc in $cllist
 !distribute words $clc into n_,c_,o_,i_
 
 $table_tr
 <td>$n_<td align=center>$c_
 <td>
 !href cmd=reply&job2=testclass&connident=$n_&connclass=$c_ $wims_name_test
 &nbsp;
 !href cmd=reply&job2=mod1&connident=$n_&connclass=$c_ $wims_name_Manage
&nbsp;
 !href cmd=reply&job2=del1&connident=$n_&connclass=$c_ $wims_name_erase
 <td>
 !href cmd=reply&job2=del1&connident=$n_&connclass=$c_&connopt=destroy $wims_name_destroy
!next clc
$table_end <p>

