$wims_name_Manage $name_remoteserver 
<font color=blue>$connident</font>
($ident_desc) located at
<a href="http://$site">$site</a>, of type
<font color=blue>$ident_type</font>.

!if $cn_status=$empty
 <p><b>$wims_name_Error</b>.
 !if $cn_status=$empty
  $name_errornoreply
  !mailurl $wims_site_manager webmaster
.
 !else
  $name_errorreject
<pre>
$cn_data
</pre>
 !endif
 !set error=yes
 !exit
!endif

