
Pour entrer dans <b><font
color=green>$mb_title</font></b>
en tant que <em>participant inscrit</em>, veuillez donner votre nom de login
et votre mot de passe personnel.

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.en">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value=$forum>
<center><table border=0>
 <tr><td>Nom de login&nbsp;: <td><input size=20 name=fuser>
 <tr><td>Mot de passe&nbsp;: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="Envoyer">
</center>
</form>

