<center><h3>Automatic daily maintenances</h3></center>

!if $error!=$empty
 !if $error=manual
  Manually installed crontab found. You should either continue to 
  manage cron jobs manually, or erase your manual crontab before
  switching to this online tool.
  <p>
  <font color=red><b>Never use this tool if you have a personalized
  crontab!</b></font>
 !endif
 !if $error=bad_base
  Strange error: I cannot recover my working directory.
  <p>
  Check your installation: it is not working normally.
 !endif
 !goto end
!endif

!form reply
<input type=hidden name=job2 value=second>
Available maintenance works:
<ul>
<li><p>Daily data backup at
!set crontab_backup_h=$oldbackup_h
!formselect crontab_backup_h from -1 to 23 prompt\
	none,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
H.
<input size=2 name=crontab_backup_m value="$oldbackup_m"> Min.
(Choose a time when the server is not busy.)
<li><p>Activity accounting (necessary for site statistics):
!formradio crontab_account list yes,no
</ul>
<center><input type=submit name=confirm value=Change>
<input type=submit name=abandon value=Cancel>
</center>
</form> <p>

:end
!reset job2 abandon

