¡<b>Advertencia</b>!<p>

Todavía no ha completado todos los ejercicios de este examen. Si los acaba
ahora congelará la puntuación y consumirá una oportunidad de hacer
el examen, y tendrá que empezar desde el principio la próxima vez.
<p>
¿Seguro que quiere terminarlos?
<p><center><font size="+1">
!href cmd=reply&job=scorereg&confirm_end=yes $wims_name_yes
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score $wims_name_no
</font></center> <p>

!tail
!reset job
