
!if $job=score
 !read adm/title.phtml 1\
 $wims_classname, $wims_institutionname\
 $title
 
 !if $wims_user=supervisor
  <center>($name_presentation)</center>
 !endif
  <p>$desc<p>
!endif

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_back
. <p>
 !goto end
!endif

!if $exocnt=0
 $name_empty
!else
 <p><center><table border=1 bgcolor=bisque>
 <caption>$name_scoreexam</caption>
 <tr><th>$wims_name_Exercise<th>$wims_name_title</th><th>$name_coeff<th>$name_Score
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,li,ti
  <tr><td align=center>$i
  <td align=center>$ti
  <td align=center>$we<td align=center>
  !if $(replied$i)>0
   $(got$i)
  !else
   <small>pendiente</small>
  !endif
 !next i
 <tr><td align=center colspan=4>
 !default score=$sprime
$name_scoreexam2: <b>$score</b> <small>/ 10</small>.
 $table_end
!endif
<p>

!if $registered=$empty
 Todavía no ha comenzado a trabajar en este examen.
 !href cmd=reply&job=student Comenzar a trabajar.
!else
 !if $timeleft<=0
   ¡Se acabó el tiempo!<p>
   Ya ha usado los $sdure minutos permitidos para este examen.
   <p>
 !endif
 !if $allowtype=simulation
  La puntuación actual no se tomará en cuenta, porque el examen está en modo
  simulación.
  !if $lastscore>0
   (Su puntuación real para esta hoja de examen es $lastscore).
  !endif
 !else
  Su mejor puntuación para este examen es $lastscore (la mejor
  puntuación es la que se tomará en cuenta).
 !endif
 <p>
!set test=!recordcnt wimshome/$wims_sesdir/examscore.$exam
!if $test>=2
 !href cmd=reply&job=scorereg $name_endexam.
&nbsp;&nbsp;
!endif
 !href cmd=reply&job=student $name_backexam.
!endif

!if $wims_user=supervisor
 <p><center>
 !href cmd=resume $name_teacherview.
 </center>
!endif

:end
!tail

!reset job

