!read adm/title.phtml 3\
Relazione con il corso <em><font color=blue>$nei_description</font></em> presso <em><font color=blue>$nei_institution</font></em>\
(Docente:<a href="mailto:$nei_email?subject=Class neighboring relations">$nei_supervisor</a>)
<p>
<b>Relazione di vicinao. </b> <small>[
!href cmd=help&special_parm=neibordecl $wims_name_help 
 ]</small> 
 <p>Il corso <em><font color=blue>
$nei_description</font></em>
!if $wims_class notitemof $nei_sup,$nei_part
 non ha dichiarato il vostro corso come vicino.
!else
 vi ha accettato come vicino.
 !if $wims_class isitemof $nei_sup and $wims_class isitemof $nei_part
  per il docente e gli iscritti.
 !else
  !if $wims_class isitemof $nei_sup
   per il docente.
  !else
   per gli iscritti.
  !endif
 !endif
!endif
<p>
!form reply
Accettate il corso <em><font color=blue>
$nei_description</font></em> come vostro vicino?
!formselect nlevel from 0 to 3 prompt No, Per il docente,\
	Per gli iscritti, Per docente e iscritti
<input type=submit value=Salva> 
</form> <p>


!if ($nei isitemof $n_sup,$n_part and $wims_class isitemof $nei_sup,$nei_part) or \
   all isitemof $nei_sup,$nei_part
 <p><b>Importazione delle risorse. </b> <small>[
 !href cmd=help&special_parm=import $wims_name_help
 ]</small>
 <p>Potete
 !href cmd=reply&job2=import importare le risorse
 de la classe <em><font color=blue>
$nei_description</font></em>.
 <p>
!endif

!if  $nei isitemof $n_sup
<p>
<b>Condivisione risorses.</b> 
<small>[
!href cmd=help&special_parm=share $wims_name_help
]</small>
<ul>
!endif

!if $wims_class isitemof $nei_sup and $nei isitemof $n_sup
 <li>
 !if $nsharable=$empty
  Non c'`e alcuna (nuova) risorsa nel corso
  <em><font color=blue>
$nei_description</font></em> che siete autorizzati a condividere.
 !else
 Il corso <em><font color=blue>
$nei_description</font></em> vi <b>autorizza</b> a condividere i suoi
  !set names=!replace , by , $$name_ in $$name_$nsharable
  <em>$names</em>.
  !href cmd=reply&job2=addshare Cliccare qui per accettare
.
 !endif
 <p>
!endif

!if $nei isitemof $sharing_all
 Voi condividete già le seguenti risorse del corso <em><font color=blue>
$nei_description</font></em>&nbsp;:<ul>
 !for r in $sharelist
  !if $(sharing_$r)=$nei
   <li><b><em>$(name_$r)</em></b>. 
   !href cmd=reply&job2=stopshare&stoprec=$r Interrompi la condivizione
. <small>[
   !href cmd=help&special_parm=stopshare $wims_name_help
   ]</small>
  !endif
 !next r 
 </ul>
 <p>
!endif
 </li>
!if $nei isitemof $n_sup and $sharablelist!=$empty
<li>
 !form reply
 <input type=hidden name=changeshare value=yes>
 Scegliete le risorse che voi <b>autorizzate</b> il corso <em><font color=blue>
$nei_description</font></em> a condividere&nbsp; (<i>selezionatele e quindi cliccate su <tt>Salva</tt></i>): <small>[
 !href cmd=help&special_parm=sharable $wims_name_help
 ]</small>
<p>
 !set sh=!nospace $sharablelist
 !set sh=!replace , by , $$name_ in $$name_$sharablelist
 !formcheckbox mksharable list $sharablelist prompt $sh
 <input type=submit value=$wims_name_tochange>
 </form> <p>
!if $nsharable!=$empty
<p><b>$wims_name_warning</b> Il corso <em><font color=blue>
$nei_description</font></em>
vi autorizza a condividere certe risorse.
Autorizzare la condivisioen delle medesime risorse può creare una grossa confusione.
Commencez per voi entendre avec elle et avec toutes les classes avec lesquelles vous
voulez partager des ressources. 
!endif
 </li>
!endif

</ul>

!reset stoprec
