!if $result=success
 !set wims_class_log=Import $import from $nei
!endif

!distribute item message du jour,\
	exercice,feuille de travail,examen,document,participant\
	into name_motd,name_exo,name_sheet,name_exam,name_doc,name_user

Importazione dal corso
!href cmd=reply&job2=def $nei_description
 presso
<em><font color=blue>$nei_institution</font></em>
<p>

!if $result=confirm
 !if dep iswordof $cfm
  !if $itype=sheet
   <b>Attenzione</b>.
   I test di autovalutazione che voi volete importare per potrebbero
   utilizzare esercizi definiti nell'altro corso.
   <p>
   Se gli stessi esercizi non esistono nel vostro corso, il test importato
   non funzionerà correttamente. Assicuratevi di importare nel vostro corso
   anche tutti le esercizi del corso vicino.
  !endif
  !if $itype=exam
   <b>ATTENZIONE</b>!!! I temi d'esame sono basati sui test di autovalutazione
   da cui prendono i contenuti. </p>
   <p>Importare un tema d'esame non ha senso se voi non avete esattamente
   gli stessi test di autovalutazione presenti nel corso vicino e se questi
   test non sono organizzati nello stesso ordine nei due corsi.
   <p>
   Se questo non è il caso, il tema d'esame importato avrà un comportamento
   imprevisto.
  !endif 
  <p>
 !endif
 !if replace iswordof $cfm
  <b>Attenzione</b>. Siete in procinto di sostituire un $(name_$itype)
  già presente nel vostro corso con la risorsa importata. Una volta 
  effettuata questa operazione non sarà possibile recuperare la vostra 
  risorsa originale.
  <p>
 !endif
 <p><center><font size="+1">
 !href cmd=reply&job2=import2&import=$import&impmethod=$impmethod&confirm=yes Confermare la sostituzione
 &nbsp;
 !href cmd=reply&job2=import $wims_name_giveup
 </font></center> <p>
 !exit
!endif

!if $result=none
 Alcuni account stduenti non sono stati aggiunti al vostro corso. 
 Verificare se il vostro corso è pieno (e se il sito permette ancora
 di aggiungere nuovi iscritti).
 <p>
 !exit
!endif

Trasferiti con successo:
!if $itype!=user
 1 $(name_$itype).
 !if $itype iswordof sheet exam
  (Il $(name_$itype) è stato messo in stato <em>in preparazione</em> per 
  permettervi di modificarlo.)<p>
 !endif
!else
 $importedcnt account studenti del corso vicino:
 <p><tt>
 $imported
 </tt> <p>
!endif

!href $verif Verificare il risultato
.&nbsp;
!href cmd=reply&job2=import Importare altre risorse
.
