
<center><h3>Interrompi una condivisione
</b><small>
!href cmd=help&special_parm=stopshare $wims_name_help
</small>
</h3></center>

!if $stoprec!=$empty and $(sharing_$stoprec)=$nei and \
	$(me_$(stoprec)cnt)>0 and $me_testcnt>0 and confirm!=yes and \
	$stoprec isitemof $nosharelist
 <b>ATTENZIONE</b>. Il vostro corso ha attività in corso e le risorso condivise
   non sono vuote. Se si interrompe la condivisione, non sarà più possibile
   ripristinarla.
 <p>
 Siete sicuri di voler interrompere definitivamente questa condivisione?
 <p><center><font size="+1"> 
 !href cmd=reply&stoprec=$stoprec&confirm=yes $wims_name_yes&nbsp;; interrompi
 &nbsp;&nbsp;
 !href cmd=reply&job2=def $wims_name_no&nbsp;; lascia le cose come stanno.
 </font></center> <p>
!else
 Errore!<br>
 Manipulation error: You should never land here.
!endif

