
WIMSтз╩╔а╙мЬлА╧╘╣двтси╥ЧнЯ╡╩╦╫╢Ьхн╨нюЮпм╣д╠ёж╓.

<p>╠╬╥ЧнЯфВ╣дЁлпРвЯя╜
<a href="COPYING" target="wims_external">GNU General Public Licence</a>. 
кЭ╣дт╢бК©им╗╧Щhttpтзртоб╣ьж╥обть
<p class="wimscenter">
<a href="http://wims.unice.fr/download/wims>http://wims.unice.fr/download/wims</a>
</p>
&copy; 1997-2000- ╥ЧнЯфВЁлпР╣двВуъ:
!mailurl xiao@unice.fr XIAO, Gang\
WIMS
, <a href=http://www.unice.fr>UniversitИ de Nice - Sophia Antipolis</a>.

<p>╥╠лЕжпндBig5╟Ф╠╬(╥ЧнЯфВсКдё©И)╣д╥╜рКси
!mailurl ychuang@cc.cktc.edu.tw Y. C. Huang
╣ёхн(╧╓вВряжп╤о).
</p>
<p>╪РлЕжпнд╟Ф╠╬(╥ЧнЯфВсКдё©И)╣д╥╜рКси
!mailurl zjchen@math.ecnu.edu.cn Ёбж╬╫э
╦╨тПвИж╞й╣й╘.
</p>
<p>рБ╢СюШнд╟Ф╠╬(╥ЧнЯфВсКдё©И)╣д╥╜рКси
!mailurl marina@matapp.unimib.it Marina Cazzola
╣ёхн.
</p>
<p>ц©╦ЖWIMSдё©Испвт╪╨╣д╟Фх╗т╜тР, ©идэ╡╩м╛сз╥ЧнЯфВЁлпР.
гК╡н©╢ц©╦Ждё©И╣дк╣цВ.
</p>
<p>©ивтси╥╒╡╪╣ддё©И╣дт╢бК©итз╥ЧнЯфВЁлпР╣добть╣ьж╥╣ц╣╫.
</p>
<p>дЁп╘дё©И╣дтквВпХр╙илр╣хМ╪Ч╣дж╖Ёж.
хГ╧Ш╥ЧнЯфВио╟╡в╟акуБяЫ╣ддё©И,
дгц╢мЬу╬╧эюМт╠сптПхноРхМ╪ЧЁЖйшуъ╨к╡ИуБяЫй╧сцйг╥Ягж╥╦ак╟Фх╗.
</p>
