
<center><h2>Profesor responsable de una zona</h2></center>

Cada zona (nivel, clase, programa, curso) de una estructura de centro educativo
debe tener un enseñante responsable. Los derechos de acceso a las páginas
de administración de la zona se rigen normalmente desde una cuenta de profesor.
<p>
Por defecto, el profesor responsable de la zona será el de la zona superior.
<p>
Si embargo cualquier otro enseñante del centro puede tener también acceso 
a la administración de la zona, si conoce la contraseña del profesor-responsable
de la misma. La única diferencia es que el nombre y la dirección de correo electrónico
que aparecerán en las páginas de los alumnos de la zona serán los del profesor
responsable "oficial".
