
!read adm/css.phtml
!header1

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!read names.phtml
!read adm/title.phtml 3\
WIMS $httpd_HTTP_HOST\
$title

!if $toomany=yes
 !read toomany.phtml
 !goto end
!endif

!if $error!=$empty
 <p>
 !read msg.phtml
 !if $restart!=no
  <p>
  !href module=$module&cmd=reply&step=0 $name_again
 !endif
 <p>
 !goto end
!endif

!if $step=$empty or $step=pre
 $name_choose
 <p>
 !href cmd=reply&step=0&cltype=0 $wims_name_create_class
 !set wims_menu_items=!append line create_class,1,cmd=reply&step=0&cltype=0\
 to $wims_menu_items
 <p>
 !if 2 isitemof $alltypes
  !href cmd=reply&step=0&cltype=2 $wims_name_create_superclass
  !set wims_menu_items=!append line create_superclass,1,cmd=reply&step=0&cltype=2\
 to $wims_menu_items
 !else
  <font color=blue><strike>$wims_name_create_superclass</strike></font> ($noright).
 !endif
 <p>
 !if 4 isitemof $alltypes
  !href cmd=reply&step=0&cltype=4 $wims_name_create_portal
  ($name_expert)
  !set wims_menu_items=!append line create_portal,1,cmd=reply&step=0&cltype=4\
 to $wims_menu_items
 !else
  <font color=blue><strike>$wims_name_create_portal</strike></font> ($noright).
 !endif
 <p>
 <b>$wims_name_help</b>:
 !read help.phtml.$lang 1
 !goto end
!endif

!if $step=0
 !read help.phtml.$lang 2
 !form reply
 <input type=hidden name=step value=1>
 <ul>
 <li><label for="institution">$name_Name_portal ($name_atmost $instlim $name_characters) :</label>
 !if $Cltype isin 13
  !default institution=$wims_institutionname
 !endif
  <input size=$instlim name=institution value="$institution" id="institution">
 </li>
 <li><label for="description">$wims_name_name $name_classesss ($name_atmost $desclim $name_characters) :</label>
  <input size=$desclim name=description value="$description" id="description">
 </li>
 
 !if $Cltype notin 24
 <li><label for="level">$wims_name_level $name_classesss</label>
  <select name=level id="level">
   !for k=1 to $nblevel
    !if $(levelid[$k])=$level
     <option selected value=$(levelid[$k])>$(leveldesc[$k])</option>
    !else
     <option value=$(levelid[$k])>$(leveldesc[$k])</option>    
    !endif
   !next k
  </select>
 </li>
 !endif

 <li><label for="supervisor">$wims_name_firstname  $wims_name_lastname ($wims_name_supervisor)</label>
  <input size=$suplim name=supervisor value="$supervisor" id="supervisor">
 </li>

 <li><label for="email">$wims_name_email</label>
  <input size=$emaillim name=email value="$email" id="email">
  !if $regpolicy=email
   <br>($name_regpolicy)
  !endif
  <br>
 </li>
 <li><label for="passsup">$wims_name_Password ($name_sup)</label>
  <input size=16 type=password name=passsup id="passsup"> <small>
  ($name_warningpass).
  $name_help1</small> <br>
 </li>

 <li><label for="password">$wims_name_Password ($name_classesss)</label>
  <input size=16 type=password name=password id="password">
  <small>($name_warningpass).
  !if $Cltype<2
  $name_help2
  !else
  $name_help3
 !endif
 </small><br>
 </li>
 
 <li><label for="exp_day">$wims_name_expiration</label>
 <select name=exp_day id="exp_day">
  !for i=1 to 31
   <option value=$i
   !ifval $i=$exp_day
    selected
   !endif
   >$i
  !next i
  </select> <select name=exp_month id="exp_month">
  !for i=1 to 12
   <option value=$i
   !ifval $i=$exp_month
    selected
   !endif
   >
   !item $i of $months
  !next i
  </select> <select name=exp_year id="exp_year">
  !for i=$thisyear to $thisyear+1
   <option value=$i
   !ifval $i=$exp_year
	selected
   !endif
   >$i
  !next i
  </select> <p>
 <li>課程中學生人數上限：
  <input size=3 name=limit value="$limit">
  (最高上限為 $wims_class_user_limit 人)<p>
 </ul>
 <center><input type=submit value=" 繼續 "></center>
 </form>

 !goto end
!endif

!if $step=1
  $supervisor 您好！<p>
  您正在 $httpd_HTTP_HOST 的  WIMS 伺服器上為  開設適用於
  <b><font color=green>$name_level</font></b> 的  $classname 課程，參與人數限制為  $ilimit
  人。本課程的註冊程序已
 !if $pword!=$empty
  被課程的密碼所保護。
 !else
  開放給網路上的任何人(您確定碼？)。
 !endif
 本課程將會於  $exp_month-$exp_day-$exp_year 到期。<p>
 如果您發現上述資訊有任何錯誤，請修正
 !href module=$module&cmd=reply&step=0 開課計劃
 。
 <p>
 為了確保您的密碼正確無誤，請再輸入一次。<p>
 !form reply
 <input type=hidden name=step value=2>
 管理者密碼：
 <input type=password name=passsup> <p>
 !if $pword!=$empty
 課程密碼：
  <input type=password name=password> <p>
 !endif
 <center><input type=submit value=" 繼續 "></center>
 </form>
 !goto end1
!endif

!if $step=2
  $supervisor 您好！<p>
現在您需要一組密碼來完成 $http_HTTP_HOST 上 WIMS 新課程的開設。<p>
這組密碼剛已送到您的電子信箱 "<tt>$email</tt>" 。
請到您的電子信箱(可能需要一點時間送信)中讀取信件。找到信件中的密碼並複製到下一欄。
 !form reply
 <input type=hidden name=step value=3>
 <center>課程密碼： <input size=12 name=typecode>
 <p><input type=submit value=" 繼續 "></center>
 </form>
 !goto end1
!endif

!if $step=3
 $supervisor 您好！<p>
 恭禧，您的 $classname 課程已開設完成，請盡情享用！<p>
 <font color=green>$name_level</font> 課程參與人數(包含您自己)限制為  $ilimit 人。
 !read links.phtml
 !goto end
!endif

:end1
<p>
[
!href module=$module&cmd=reply&step=0 回開課計劃
 ]
:end
<p><hr width="30%"> <p>
!homeref
!taile

!set step=

