!set name_institution=服務單位名稱
!set name_description=課程名稱
!set name_supervisor=管理者姓名
!set name_email=電子信箱
!set name_password=課程密碼
!set name_passsup=管理者密碼
!set lev_E=中小學
!set lev_H=高中
!set lev_U=大學
!set lv1=!char 1 of $ilevel
!set lv2=!char 2 of $ilevel
!set name_level=$(lev_$lv1) $lv2 年級

!set classname=<b><font color=green>$description</font></b>\
 of <b><font color=green>$institution</font></b>

!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

