
Vous pouvez parcourir le contenu de ce site par plusieurs méthodes.

<ul>
<li><p>
 !href module=$module&cmd=new&job=subject Par sujet
$ : algèbre, analyse, géométrie, probabilité, etc.
</p></li>
<li><p>
 !href module=$module&cmd=new&job=level Par niveau d'éducation
$ : école primaire, école secondaire, université, etc.
</p></li>
<li><p>
 !href module=$module&cmd=new&job=new Par date
$ : dernières nouveautés du serveur.
</p></li>
</ul>
Et vous pouvez également utiliser les sélections faites pour vous 
<ul>
 <li><p>
 !href module=$module&cmd=new&job=type Par type de ressource
$ : références, outils de calcul et de tracés, exercices, etc.
 </p></li>
<li><p>
 !href module=$module&cmd=new&job=best Une brève introduction
 $ de quelques meilleures activités du serveur. 
</p></li>
<li><p>
!href module=help/teacher/program Correspondance indicative
$ avec les programmes de l'enseignement français
 </p></li>
</ul>

