!read adm/title.phtml 1\
$classname\
$name_partdeleted


!if $delcnt<1
 No se ha dado de baja a ningún participante de esta clase.
 <p>
!else
 Pulse sobre un identificador de usuario (login)
 para volver a incluir al participante en la clase.
 $table_header
 $table_hdtr<th>$wims_name_Login<th>$wims_name_name
 !for i in $deleted
  !set names=!getdef user_lastname, user_firstname in wimshome/$userdir/.$i
  $table_tr<td>
  !href cmd=reply&job=recover&getuser=$i $i
  <td>$names</td>
 !next i
 $table_end <p>
!endif

</center> <p>

!set wims_menu_items=!append line part_list,1,cmd=resume\
to $wims_menu_items
