
Stre¾nik je sprejel va¹o vajo, v kateri je razpoznal naslednje podatke: (preverite, èe se ujemajo z naèrtovanimi)
<table bgcolor="#d0d0d0">
<tr><td align=right>Naslov<td><td>$title
<tr><td align=right>©tevilo parametrov<td><td>$varcnt
<tr><td align=right>©tevilo prostih odgovorov<td><td>$replycnt
<tr><td align=right>©tevilo odgovorov izbirnega tipa<td><td>$choicecnt
</table>
<ul><li>
Zdaj lahko
!href cmd=resume&realtest=yes&retest=again preizkusite vajo
.
!if $mode!=file
<li><p>
Èe jo ¾elite spremeniti, pojdite
!href cmd=reply&level=2 nazaj v meni
.
!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=level value=3>
 <li><p>
 ali pa spremenite datoteko s kodo in jo ponovno
 <input type=submit value="po¹ljite">:
 <input type=file name=wims_deposit>
 </form>  
 <li><p>
 !href cmd=reply&level=1&mode=normal Nazaj na zaèetni meni
.
!endif
!if $wims_user!=$empty
 <li><p>Vajo lahko opremite tudi s
 !href cmd=reply&level=6 slikovno datoteko
.
 !set wims_menu_items=!append line downloadbinary,1,cmd=reply&level=6\
 to $wims_menu_items
!endif
!if $wims_user!=$empty or $existing!=$empty
 <li><p>
 Èe je vaja brezhibno pripravljena, jo lahko
 !if $existing!=$empty
  !if ..devel/ notin ..$catmodule
  namestite v svoji uèilnici, tako da 
  !href cmd=reply&level=4 nadomestite staro
  ali pa kot
  !href cmd=reply&level=4&newone=1 novo vajo
   !set wims_menu_items=!append line replace,1,cmd=reply&level=4\
 newversion,1,cmd=reply&level=4&newone=1\
 to $wims_menu_items
  !else
   !href cmd=reply&level=4 namestite v svoji uèilnici
   !set wims_menu_items=!append line putmodtool,1,cmd=reply&level=4\
   to $wims_menu_items
  !endif
.
!else
 !href cmd=reply&level=4 save this exercise in your class
 !set wims_menu_items=!append line putclass,1,cmd=reply&level=4\
 to $wims_menu_items
 !endif
.
!endif
!if $mode!=file
 <li><p>
 Ne pozabite si
 !getfile submit.oef shraniti kode
 pravkar ustvarjene vaje!
!endif
</ul>
!set wims_menu_items=!append line testexo,1,cmd=resume&realtest=yes&retest=again\
to $wims_menu_items

!if $wims_version_theme=0
  !reset wims_menu_items
!endif

