!set sizex=65
!set types=!sort nocase lines \
avtomatièna zaznava,	default\
algebraièni izraz,	algexp\
besedilo (pribli¾no),	atext\
besedilo (velikost èrk nepomembna),	nocase\
besedilo (velikost èrk pomembna),	case\
mno¾ica znakov,		chset\
enaèba,			equation\
konèna mno¾ica,		set\
formalni izraz,		formal\
dobesedni izraz,	litexp\
matrika,		matrix\
¹tevilo,		numeric\
¹tevilo z obsegom,	range\
¹tevilo z enotami,	units\
numerièna funkcija,	function\
vektor,			vector\
besede v seznamu,	wlist

!set types=!nonempty lines $types
!set typelist=!column 2 of $types
!set typenames=!column 1 of $types

Vnesite vsebino va¹e vaje z naslovom <font color=red><b>$oef_title</b></font>.
!href cmd=reply&level=1 Nazaj na zaèetno stran
. <p>

!form reply
<input type=hidden name=level value=3>
Tukaj definirate spremenljivke in nakljuène parametre: [
!href target=wims_mhelp cmd=help&special_parm=parameters $wims_name_help
 ]<br>
!set o_parms=!reinput $oef_parms
<textarea wrap="off" rows=6 cols=$sizex name=oef_parms>$o_parms</textarea>
<p>
Tukaj vpi¹ete besedilo naloge ($oef_format format): [
!href target=wims_mhelp cmd=help&special_parm=format $wims_name_help
 ]<br>
!set o_statement=!reinput $oef_statement
<textarea wrap="off" rows=6 cols=$sizex name=oef_statement>$o_statement</textarea>
<p>
!if $oef_answercnt>0
 <table border=1>
 <caption>Prosti odgovori
 <tr><th>Ime<th>Pravi odgovor<th>Tip odgovora</b><small>
 !href target=wims_mhelp cmd=help&special_parm=reply#freestyle [$wims_name_help]
 !for i=1 to $oef_answercnt
  !default anstype$i=default
  !set p_=!reinput $(ansprompt$i)
  <tr><td> <input size=$[$promptlim-3] maxlength=$promptlim name=ansprompt$i value="$p_">
  !set p_=!reinput $(ansgood$i)
  <td> <input size=30 name=ansgood$i value="$p_">
  <td><small>
  !formselect anstype$i list $typelist prompt $typenames
 !next i
 </table> <p>
 Zahtevana natanènost pri numeriènih odgovorih:
 !formselect oef_precision list 100,1000,10000,100000,1000000 prompt 1/100,1/1000,1/10 000,1/100 000,1/1 000 000
 <br>Vrednosti numeriènih funkcij bodo primerjane na intervalu
 (&nbsp;<input size=6 name=oef_rangel value="$oef_rangel">,<input size=6 name=oef_ranger value="$oef_ranger">&nbsp;).
 <p>
!endif

!if $oef_condcnt>0
 <table border=1>
 <caption>Pogoji za analizo numeriènih odgovorov
 <tr><th>Ime pogoja<th>Definicija pogoja
 !for i=1 to $oef_condcnt
  !set p_=!reinput $(Condname$i)
  <tr><td><input size=$promptlim maxlength=$promptlim name=Condname$i value="$p_">
  !set p_=!reinput $(Condtest$i)
  <td> <input size=40 name=Condtest$i value="$p_">
 !next i
 </table> <p>
!endif

!if $oef_choicecnt>0
 <table border=1>
 <caption>Odgovori izbirnega tipa
 <tr><th>Ime<th>Dobri odgovori<th>Slabi odgovori
 !for i=1 to $oef_choicecnt
  !set p_=!reinput $(choiprompt$i)
  <tr><td> <input size=$promptlim maxlength=$promptlim name=choiprompt$i value="$p_">
  !set p_=!reinput $(choigood$i)
  <td> <input size=10 name=choigood$i value="$p_">
  !set p_=!reinput $(choibad$i)
  <td> <input size=30 name=choibad$i value="$p_">
 !next i
 </table> <p>
!endif

<p><center>
<input type=submit value="Registriraj vsebino">
</center> <p>
Èe ¾elite, lahko nalogi dodate tudi namig ali re¹itev:
<table border=0>
<tr><td>Namig<br>(html format)
!set pp=!reinput $oef_hint
<td><textarea wrap="off" rows=3 cols=$[$sizex-10] name=oef_hint>$pp</textarea>
<tr><td>Re¹itev<br>(html format)
!set pp=!reinput $oef_solution
<td><textarea wrap="off" rows=3 cols=$[$sizex-10] name=oef_solution>$pp</textarea>
</table>
</form>

