
Your exercise has been successfully registered in this server. We warmly thank
you for your contribution, in the name of all those who will benefit from it.
<p>
The administrator of this site will verify your exercise, and decide on whether
or not to put it in an appropriate category.
This may take a certain number of days.
<p><center>
!href module=incoming Module temporarily containing your exercise.
<p>
!href cmd=reply&level=$[$level-1] Back to the preceeding stage.
</center>


