!read names.phtml
!if $oef_test=yes
 !set wims_html_header=!append line $header_js to $wims_html_header
!endif
!read adm/css.phtml
!header

!if $modtoolhelp=yes
 !read help.phtml
 !goto end
!endif

!if $deleted!=$empty
 !read delete.phtml
 !goto end
!endif

!if $level=3 and $catsource=yes
 Tukaj je koda va¹e vaje za naslovom
 <font color=red><b>$oef_title</font></b> v OEF formatu (Open Exercise Format).
 Èe ¾elite, lahko besedilo med èrtama prenesete v svoj najljub¹i urejevalnik in ga shranite na disk ali drug medij.
 !href cmd=resume Nazaj na meni.
 <hr>
<pre>
!mexec catsrc.sh
</pre>
 <hr> <p>
 <center>
 !href cmd=resume Nazaj na meni.
 </center>
 !set catsource=no
 !goto end
!endif

!if $oef_test=yes
 <center>Tak¹na bo izvedba va¹e vaje:
 !href cmd=resume&realtest=no Nazaj na $module_title.
 </center>
 <p><hr> <p>
 !changeto oef/$module_language/Main.phtml
!endif

!if $error!=$empty
 !read msg.phtml
 <p>
 !href cmd=reply Popravi napako.
 !goto end
!endif

!if $mode!=$empty and $level<=2
 !read $mode$level.phtml
!else
 !read level$level.phtml
!endif

:end
!if $level notwordof 0 6
 !set wims_menu_items=!append line createxo,1,module=adm/createxo\
to $wims_menu_items
!else
 !set wims_menu_items=createxo,0,Createxo\
to $wims_menu_items
!endif
!if $level iswordof 0 1
!set wims_menu_items=!append line  model,1,cmd=reply&mode=model&level=1\
normalmode,1,cmd=reply&mode=normal&level=1\
rawmode,1,cmd=reply&rawinp=yes&level=1\
filemode,1,cmd=reply&mode=file&level=1\
 to $wims_menu_items
 
!set wims_menu_items=!append line ,0,\
othermethods,0,$wims_name_othermethods\
Createqcm,1,module=adm/auth/createqcm\
Confia2qcm,1,module=adm/auth/confia2qcm\
modtool,1,module=adm/modtool\
quicktool,1,module=adm/quicktool\
latex2wims,1,module=adm/latex2wims\
 to $wims_menu_items
!endif

!tail

!reset wims_deposit, delfile

