
!form reply
<input type=hidden name=level value=3>

!if $existing=$empty
 Ste v neposrednem naèinu za ustvarjanje vaje, v katerem morate roèno vnesti celotno kodo va¹e vaje. Ta naèin je namenjen izku¹enim uporabnikom, lahko pa ga uporabite tudi za registracijo ali popravljanje vaje, katere kodo imate ¾e napisano.
 Za zaèetnike je priporoèljiv
 !href cmd=reply&mode=normal vodeni naèin
 za ustvarjanje vaje.
 <p>
 Vnesite celotno kodo (
 !href target=wims_mhelp cmd=help&special_parm=oef OEF format
 ) va¹e vaje:
 (da bi registrirali ¾e pripravljeno kodo, jo skopirajte v okence)
!else
 Tukaj je koda
 !if $catmodule=$empty
  vaje, ki je ¾e registrirana v va¹i uèilnici. Lahko jo spreminjate v spodnjem okencu.
 !else
 vaje, ki ste jo uvozili. 
 Predno jo registrirate za uporabo v svoji uèilnici, jo lahko po svojih ¾eljah spreminjate, èe to dovoljuje njen avtor.
 !endif
!endif

<p><center>
!mexec textarea.sh
<p><input type=submit value="Registriraj kodo"></center>
</form>

