
!set sp2=$special_parm2
!bound sp2 within secure,supervisor,email,lang,level,limit,expiration,modtoolchg,\
	bgcolor,homepage,bgimg,theme,css,theme_icon,logo,lock,exolog,examlog,examshow,ent,option,authtype,topscores\
	default $

!if $sp2=$empty
 !exit
!endif

!goto $sp2

:secure
<b>Secure hosts</b>.
Bedenk de mogelijkheid van het "weglekken" van Uw supervisor wachtwoord:
Stel U logt in als supervisor en een leerling kijkt mee over Uw schouder.
U moet dus ,wanneer er echte cijfers worden behaald op uw server,
voorziching omgaan met het wachtwoord.
<p>
De consequentie van het wegleken van dit wachtwoord kan zijn, dat alle confidenti&euml;le data
op de server onbetrouwbaar worden. En U zelfs niet meer kunt inloggen.
<p>
Het vastleggen van secure hosts zorgt dus voor een extra beveilingslaag: alle server gevoelige
handelingen zijn alleen bereikbaar vanaf deze <em>secure hosts</em>.
Zelfs het weglekken van een wachtwoord hoeft dan geen desastreuze consequenties meer te hebben.
<p>
!read help/hosts.phtml
<p>
Overigens , wanneer U supervisor moet worden in een "vijandige" omgeving, is het gebruik
van &eacute;&eacute;nmalige wachtwoorden een goede oplossing.
Zie hieroor de wachtwoord-pagina
!exit

:supervisor
 <b>Supervisor naam</b>. Geef hier gewoon een naam.
!exit

:email
 <b>Supervisor email</b>.
 Alle belangrijke berichten (geheime aanmeldingscodes, beindigingsdata van uw klassen enz.)
 worden naar dit adres gestuurd. U moet dus een bestaand en actief emailadres opgeven, anders
 kunt U zelfs de controle verliezen over Uw klas.
!exit

:option
 <b>Tonen configuratie opties op homepagina van klas</b>. 
 De volgende 'woorden' kunnen worden gebruikt:
 <ul>
 <li><tt class="wims_code_words">showshexpire</tt> 
 Laat de einddatum van werkbladen zien aan studenten.
 </li><li><tt class="wims_code_words">showexexpire</tt>
 Laat de einddatum van proefwerken [examens] zien aan studenten.
 </li><li><tt class="wims_code_words">showshweight</tt>
 Laat het gewicht van een werkblad zien aan studenten
 </li></ul> 
!exit

:lang
Kies de taal waarin deze klas moet worden getoond.
Afhankelijk van de ondersteuning op deze wims server kan gekozen worden uit
de talen: <ul>
 <li>ca (Catalaans)
 </li><li>cn (Chinees gb)
 </li><li>de (Duits)
 </li><li>en (Engels)
 </li><li>es (Spaans)
 </li><li>fr (Frans)
 </li><li>it (Italiaas)
 </li><li>nl (Nerderlands)
 </li><li>si (Sloveens)
 </li><li>tw (Chinees big5)
</li></ul>
!exit

:level
 Betekenis van de diverse niveaus: <ul>
 <li>E1 - E6: Lagere school, klas 1 tot 6.
 </li><li>H1 - H6: Middelbare school, klas 1 tot 6.
 </li><li>U1 - U5: Universiteit, jaar 1 tot 5.
 </li><li>G: Universiteit, Afstudeer-richting.
 </li><li>R: Onderzoek.
</li></ul>
!exit

:limit
 <b>Deelnemer limiet</b>. 
 De aanmelding van nieuwe deelnemers of leerlingen wordt geweigerd als deze limiet is bereikt.
 Deze server heeft een harde limiet van ($wims_class_user_limit) welke niet kan worden overschreden.
!exit

:expiration
 <b>Verloop datum</b>. De klas wordt opgeheven wanneer deze datum is bereikt.
 U kunt deze datum altijd verlengen.
<p>
Als U deze klas langer dan een jaar wilt gebruiken, zijn er dus een tweetal opties:
Of U verlengt deze datum regelmatig op de normale manier, of U richt een 
 <a href="mailto:$wims_site_manager?subject=Verzoek tot verlenging  van een virtuele Klas">email</a> aan de systeem administrator. 
 <p>
 Deze datum moet dan  worden opgegeven in de 8-digit vorm (yyyymmdd).
 Bijvoorbeeld: 20120523 betekend  23 Mei 2012.
!exit

:bgcolor
 <b>Pagina achtergrond &amp; menu kleur</b>.
 Deze twee kleuren kunnen U helpen de herkenbaarheid van uw virtuele leeromgeving te vergroten.
 Deze kleurwaarden moeten standaard HTML kleurcodes zijn.
 <p>
 <b>Kleuren van links in menus en tabellen</b>
Als u deze optie wilt gebruiken is het verstandig een tabel achtergrond kleur te defini&euml;ren,
ook al dit dezelfde kleur als de "standaard/default" kleur.
 <p>
 "Default" waarden worden bepaald door de sitemanager.
!exit

:homepage
 <b>Deelnemer homepage</b>.
 U kunt hier het adres van een "wims document-blok" invoeren
 (zoals <tt class="wims_fname">c1/main</tt>) als homepagina.
 Het document zelf hoeft niet leesbaar te zijn voor leerlingen.
 <p>
 Laat dit veld leeg als U de standaard layout wilt gebruiken.
 <p>
 Alle links in dit document-blok moeten worden gedefinieerd met het <tt class="wims_code_variable">\adm</tt> commando.
 U kunt de volgende voorgedefinieerde wims-variabelen gebruiken:
 $table_header
 $table_tr<td><tt class="wims_code_variable">\firstname</tt></td><td>
 Voornaam van de leerling/deelnemer
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\lastname</tt> </td><td>
 Achternaam van de leerling/deelnemer
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\scores</tt></td><td>
 Score informatie van deze deelnemer. 
 Dit is dus een lijst getallen, corresponderende met één werkblad: percentage of punten
  en een gemiddelde score
  </td></tr>
 $table_tr<td><tt class="wims_code_variable">\newmsgcnt</tt></td><td>
 Ongelezen berichten in het klasse forum.
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\today</tt></td><td>
 Datum van vandaag, yyyymmdd.
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\sheets</tt></td><td>
 Aantal beschikbare werkbladen
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\exams</tt></td><td>
 Aantal digi-toetsen/tentamens.
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\expiration1</tt>, <tt class="wims_code_variable">\expiration2</tt>, <tt class="wims_code_variable">\expirationE1</tt>, ...</td><td>
 uiterste datum van werkblad 1, werkblad 2, tentamen 1, ..., yyyymmdd.
 </td></tr>
$table_tr<td><tt class="wims_code_variable">\status1</tt>, <tt class="wims_code_variable">\status2</tt>, <tt class="wims_code_variable">\statusE1</tt>, ...</td><td>
 Status van werkblad 1, werkblad 2, tentamen 1, ... dit is een niet negatief geheel getal; 0
 = nog niet klaar voor gebruik, 1 = actief, 2 = verlopen, 3 = onzichtbaar.
 </td></tr>
 $table_tr<td><tt class="wims_code_variable">\daymessage</tt></td><td>
 message du jour de la classe.
 </td></tr>
$table_tr<td><tt class="wims_code_variable">\userdaymessage</tt></td><td>
message du jour individuel de chaque participant.
</td></tr>
$table_end
!goto end

:bgimg
 Achtergrond plaatje (tegel) voor de pagina's in de digi-klas.
 U kunt elke valide URL gebruiken.
 Er zijn ook reeds ge&iuml;nstalleerde achtergrond plaatjes, die U kunt gebruiken zonder url-adres:<p>
 <pre>$bgimgs</pre>
!exit

:theme
Het stijl-thema van een klas.
!exit

:theme_icon
The icons in the menu
!exit

:css
Het style sheet beinvloed bijna alle pagina's van een klas.
<p>
Kies <tt class="wims_code_words">----</tt> om de stylesheets uit te schakelen.
<p>
Kies <tt class="wims_code_words">class</tt> om Uw eigen  style sheet (css) te gebruiken.
Gebruik de standaard css-syntax.
 <b>Opmerking</b>. 
 Wanneer U uw eigen css wilt gebruiken, test deze dan uitvoerig op 
 <b>alle</b> beschikbare browsers ,om zo compatibiliteits problemen te vermijden
<p>
De andere keuzes zijn voor-ingestelde styles van deze WIMS server.
!exit

:logo
Het logo van de klas is een plaatje dat wordt links of rechts bovenaan de pagina geplaatst.
(Zowel op de leerlingpagina als ook op de supervisor pagina.)
<p>
Kies <tt class="wims_code_words">none</tt> als U geen logo wenst.
<p>
Als U niets of <tt class="wims_code_words">wims</tt> invult, wordt het standaard WIMS logo gebruikt.
<p>
Elke plaatje met een geldige URL kan worden gebruikt. 
!exit

:lock
Connection lock helpt gebruikers te traceren, en kan helpen server-misbruik te achterhalen.
Er zijn 7 lock niveaus. <ul>
<li>0: Geen connection lock wordt gebruikt.

</li><li>1: Cookie-tracking is geactiveerd. Verbindingen zonder correct antwoord cookie worden geweigerd.

</li><li>2: Secure (https) verbinding is vereist. 
De verbindsingsopbouw gebruikt het https protocol. 
HTTP verzoeken zullen worden geweigerd.
Kontroleer wel eerst of de server https ondersteund !

</li><li>3: Host IP-adres lock is geactiveerd. 
Deelnemers mogen binnen een sessie niet van IP-adres veranderen.
Er kunnen zich dus problemen voordoen bij dynamische IP adressen.

</li><li>4: Cookie-tracking + https.
</li><li>5: Cookie-tracking + Host lock.
</li><li>6: Alle methodes geactiveerd.
</li><li>7: The class is closed. No participant connection accepted.
</li></ul> <p>
!exit

:exolog
Het maximale aantal gelogde oefeningen (beperkt tot $wims_exolog_limit)
<p>
Dit is het maximale aantal gelogde oefeningen die een leerling kan laten bewaren op deze server. 
<p>
Deze lijst gegevens kan als basis dienen voor "studie vorderings gesprekken" tussen leerling en docent.
<br>
Bij overschrijding van de toegestane hoeveelheid gelogde oefeningen, wordt de oudste oefening gewist.
!goto logs

:examlog
Aantal tentamen registraties (beperkt tot $wims_examlog_limit)
<p>
Dit is het maximum aantal examensessies dat wordt vastgelegd/bewaard op deze server voor een elke leerling.
<p>
Deze logfiles geven het precieze verloop van een tentamen sessie weer, oefening voor oefening.
En kan worden gebruikt voor het naspelen van een kompleet tentamen.
<p>
De registratie/vastlegging van tentamen-sessies verloopt automatisch.
Wanneer het maximum is bereikt , wordt het oudste tentamen gewist.
!exit

:logs
<p>
Geef een 0 als U geen registratie wenst.

<b>ATTENTIE</b> 
Dit type registratie kan een zeer groot beslag leggen op de harde schijf ruimte.
Bij een te hoge instelwaarde loopt U het risico dat Uw diskquotum wordt overschreden !
!exit

:examshow
Als deze optie op <tt class="wims_code_words">$wims_name_no</tt> staat, kunnen de studenten de resultaten van een tentamen niet zien.
De docent natuurlijk wel.
!exit

:authtype
<b>Soort authentificatie</b> : 
Er kan worden gekozen tussen authentificatie via <tt class="wims_code_words">ldap</tt> of via het wims eigen authentificatie systeem.
In het geval dat een inloggen cia <tt class="wims_code_words">ldap</tt> mislukt wordt geprobeerd een wims authentificatie op te starten..
<p>
Voorbeeld <tt class="wims_code_words">ldap</tt> configuratie:
<pre>
ldap_host=ldap.schaersvoorde.nl
ldap_port=389
ldap_version=3
ldap_base=ou=people,dc=schaersvoorde,dc=nl
ldap_branch=ou=people,dc=schaersvoorde,dc=nl
ldap_uid=uid
ldap_login=supannAliasLogin
</pre>
!exit

:modtoolchg
<b>Modtool account</b> :
Wanneer u -ingelogd- op de link <tt>modtool</tt> klikt wordt er een account aangemaakt.

!exit
:ent
<b>Verbinding met andere digitale leerplatformen</b> :
Hier kan een link worden geplaatst naar een andere ELO:
<pre> link_titel,link_adres</pre>
Bijvoorbeeld,
<pre>It's learning ,http://-------</pre>
Zijn er meerdere links gewenst, scheidt deze dan van elkaar door een ";".
!exit

:external_auth
<b>Adres ingeval van een externe authentificatie</b> : 
<i>
Dit is voor experts en het maakt het mogelijk om bijv. een CAS-authenticatie te gebruiken. </ I>
Het adres moet in de html zijn: <tt class="wims_address">&lt;a href="http:...">link naam &lt;/a&gt;</tt>.
Het adres kan ook worden geplaatst in een htmle frame :
<tt class="wims_address">&lt;iframe https:...." width="100%" height="400">&lt;/iframe&gt;</tt>. 
<p>Vous pouvez désactiver cette option tout en gardant le texte en cliquant sur <tt class="wims_code_words">$wims_name_no</tt>.
Si vous cochez <tt class="wims_code_words">$name_mix_auth</tt>, l'adresse html que vous avez donné apparaîtra mais
aussi l'authentification propre à wims comme une alternative. 

Vous devez mettre un code html valide, il ne sera pas vérifié et
vous assurez que l'authentification externe permet d'entrer dans votre classe.

!exit

:topscores
<center><b>Hoogste cijfers, anoniem of op naam</b></center>
<p> 
Wanneer het nummer <em>n</em> &ge; 1 is, zal een student bij het bestuderen van zijn/haar resultaten
tevens een lijst zien van de <em>n</em> beste medeleerlingen.
Als anonymity=yes worde de namen van deze leerlingen niet getoond (bij anonymity=no, worden deze wel geprint)
Deze voorziening geldt niet voor de handmatig ingevoerde scores/cijfers. 
<p>
Default=0/$wims_name_yes

!exit

:end

