
<b>Maak een Backup van uw klas</b>. <br>
U kunt een backup kopie van uw klas downloaden als een gecomprimeerde archief file
Bij een zeer actieve klas, kan er ook voor worden gekozen specifieke files te archiveren.
 
Een backupfile kan later naar de server worden opgestuurd om een klas te herstellen, of om deze gegevens in te voeren in een nieuwe klas.
<p>

Alle files in een klas zijn ascii bestanden : deze kunnen dus op elke lokale computer gelezen en bewerkt worden.

<p>
Beschikbare gecomprimeerde formaten zijn: <ul>
 <li><em>zip</em> deze kunnen worden uitgepakt op praktisch elk platform
 (Windows, Mac, Linux, BSD, etc.), maar is niet erg effectief gecomprimeerd.
 <li><em>tgz</em> deze kunnen alleen uigepakt worden op Unix-type systemen
(Linux, BSD, Sun OS, etc.) , en heeft een bettere compressie ratio;
 <li><em>tar.gz</em> een synoniem van tgz.
</ul>
Natuurlijk worden deze formaten door WIMS ondersteund voor een herstel procedure.

