
<b>Maak een Backup van Uw klas</b>. <br>
U kunt een backup kopie van Uw klas downloaden als een gecomprimeerde archief file
Hebt U een zeer actieve klas, kunt U er ook voor kiezen om specifieke files te 
archiveren.
 Een backupfile kan later naar de server worden opgestuurd om een klas te herstellen, of
 om deze gegevens in te voeren in een nieuwe klas.
<p>
Alle files in een klas zijn tekst-bestanden; die u dus op elke lokale computer kan lezen of bewerken.
<p>
Beschikbare gecomprimeerde bestands formaten zijn: <ul>
 <li><em>zip</em> deze kunnen worden uitgepakt op praktisch elk platform
 (Windows, Mac, Linux,BSD, etc.), maar is niet erg effectief gecomprimeerd.
 <li><em>tgz</em> deze kunnen alleen uigepakt worden op Unix-type systemen
(Linux, BSD, Sun OS, etc.) , en heeft een bettere compressie ratio;
 <li><em>tar.gz</em> een synoniem van tgz.
</ul>
<p>
Natuurlijk worden alle formaten door WIMS ondersteund voor een herstel procedure.

