!read adm/title.phtml 3\
\
Actualiseren van de index

Deze opdracht is gereserveerd voor ervaren gebruikers, die handmatig 
bestanden en configuraties hebben bijgewerkt.
Na dergelijke modificaties is het verstandig een nieuwe index van de veranderde gegevens aan te laten maken.
<p>
Bekijk de broncode van de programma's en scripten voor gedetaileerdere uitleg.
<p>
Het is geen probleem als per ongeluk een nieuwe index is gemaakt.

