
<b>Sta andere klassen toe Uw bronnen en materiaal te delen</b>.
<br>
Wanneer U een
!href cmd=help&special_parm=neighbor andere klas
toestaat materiaal 
!href cmd=help&special_parm=share te lenen
moet U zich wel de eventuele risico's die dit mee brengt realiseren.
<p>
Wanneer U een materiaal deelt/uitleent aan andere klassen,
kan deze uw materiaal ook wijzigen of beschadigen. 
<p>
In het bijzonder is het delen van een "supervisor account" risicovol.<br>
De lener kan uw wachtwoord veranderen: U kunt niet meer inloggen in uw eigen klas.
<p>
Soms is het dus verstandiger andere klassen uit te nodigen
 materiaal uit uw klas te  !href cmd=help&special_parm=import importeren
in plaats van te lenen .

 
