
<b>Upload een backup van Uw klas</b>. <br>
Er zijn in principe twee gevallen waarbij U een backup moet kunnen opsturen naar de server.
<p>
In het eerste geval wanneer bestanden ,om welke reden dan ook, zijn beschadigd.
<br>
In een dergelijk geval adviseren wij een zo volledig mogelijk backup
(liefst zonder klas configuratie en suppervisor-account, als deze tenminste niet ook beschadigd zijn)
<p>
In het tweede geval wanneer "onderdelen" van de ene klas gebruikt moeten worden in een andere klas.
Houd echter rekening met
!href cmd=help&special_parm=dependencies de "inter-klas" afhankelijkheden
. 
Als regel geldt dat U de scores niet mee kopieert, en dat
gedeeld lesmateriaal [documenten,werkbladen,proefwerken/tentamens] niet via een
backup mag worden hersteld.

