
!read adm/title.phtml 3\
\
Configuración de la normativa de acceso

!form reply
<input type=hidden name=job value=access>
<center>Definición de la normativa de acceso: 
!href cmd=help&help_subject=access [ayuda]
<br>
<textarea name=accessdef cols=70 rows=15>$accessdef</textarea>
<p>
<input type=submit name=save value=De acuerdo>
<input type=submit name=abandon value=Cancelar>
</center>
</form>

!reset job, accessdef

