
<blink>¡¡¡</blink><b>Atención</b><blink>!!!</blink> 
¡El fichero $fname tiene permisos de lectura por todo el mundo!
<p>
Hay un riesgo serio de que se haya producido una filtración de la configuración 
del administración del sitio y/o su contraseña. DEBE cambiar ahora mismo las 
propiedades de $fname haciéndolo legible sólo por su dueño,
!if $wims_ismanager=-1
 y aumentar la seguridad de las definiciones del fichero en tanto sea posible.
!else
 y definir una nueva contraseña de administrador.
!endif
<p>
Una vez haya hecho esto vuelva a intentar abrir esta página.

