
Directorio actual: <tt>
!href cmd=reply&fsdir=/ $base
!set t=
!for d in $dd
 !set t=$t/$d
/
 !href cmd=reply&fsdir=$t $d
!next d
</tt>

!if $modifok=yes
 !set wims_form_method=file
 !form reply
 <input type=hidden name=job value=$job>
 <input type=hidden name=job2 value=add>
 Añadirle un nuevo fichero:
 <input type=file name=wims_deposit size=40>
 <input type=submit value=OK>
 </form>
!endif
<p>

!if $dirs!=$empty
 Subdirectorios (pulse para ir): <tt>
 !for f in $dirs
  !if / notin $f
   !href cmd=reply&fsdir=$fsdir/$f $f
   &nbsp;
  !endif
 !next f
 </tt>
!endif

!if $links!=$empty
<p>Enlaces simbólicos:
 !for f in $links
  $f
 !next f
!endif

!if $files!=$empty
 <p>Ficheros: <br>
 <tt>
 !for f in $files
  !href cmd=reply&job=file&job2=first&file=$fsdir/$f $f
  &nbsp;
 !next f
 </tt>
!else
 <p>No hay ningún fichero normal en este directorio.
!endif

