!if $cmd=help and $help_subject iswordof conf soft and $wims_ismanager=2
 !changeto conf/help-$help_subject.phtml
!endif

!header

!if $wims_ismanager iswordof -1 1
 Esta utilidad le permite al administrador del sitio llevar en línea el mantenimiento
 de la instalación WIMS. El acceso a ella está controlado estrictamente mediante
 definiciones en el fichero de configuración  <tt>log/wims.conf</tt>. <p>
!endif

!if $job!=$empty
 !read $job.phtml
!endif
!if $wims_ismanager=2 and $job!=list
 <p><center>
 !href cmd=reply&job=list Otras tareas de mantenimiento
 </center> <p>
!endif

!tail

!reset auth,save,abandon
