
!if $job2=one
 !read mu/one.phtml
 !reset auto muauto
 !exit
!endif

!if $job2=all
 Se ha recibido la petición de ejecutar su orden $auto. 
 El resultado se le enviará por correo electrónico.
 <p>
 Por favor no repita la orden hasta que se haya completado su ejecución.
 <p> <hr width=70%> <p>
 !set job2=first
 !reset auto muauto
!endif

!form reply
<input type=hidden name=muauto value=check>
<center>
<table border=0>
<tr><td align=right>
<input type=submit value=Buscar> entre los anuncios de módulos:
<td><input size=40 name=musite value="$musite">
<tr><td align=right>módulos de la zona:
<td><input size=40 name=muzone value="$muzone">
<tr><td align=right>y categoría:
<td><input size=40 name=mucat value="$mucat">
<tr><td align=right>modificados al menos hace
<td><input size=4 name=mudelay value="$mudelay"> días
$table_end
</form>

<p> <hr width=70%> <p>

Tiene que
!href cmd=reply&job=mkindex reconstruir el índice de recursos
 después de una actualización de módulos.
!href cmd=reply&job=conf&confcat=6 Pulse aquí
 para configurar la actualización diaria automática de módulos.

!if $auto=check
 !read mu/$auto.phtml
!endif

!reset muauto
