
!read adm/title.phtml 3\
\
Sesión de usuario

Contenido de la sesión <tt>$checkses</tt>: <small>[
!href cmd=reply refrescar
 ]</small> <p>
<small><pre>----------------------------------------------------------------
$content
----------------------------------------------------------------</pre></small>
<p>

Contenido del fichero de variables de la sesión <tt>var</tt>:<p>
<small><pre>----------------------------------------------------------------
!sh cat $wims_home/sessions/$checkses/var
----------------------------------------------------------------</pre></small>
<p>

!if $varstat!=$empty
Contenido del fichero <tt>var.stat</tt>:<p>
<small><pre>----------------------------------------------------------------
$varstat
----------------------------------------------------------------</pre></small>
<p>
!endif

<center>
!href cmd=reply&job=activ Lista de sesiones activas
</center>

