
<center><h3>Actualización del software del servidor WIMS</h3></center>

!if $error!=$empty
 !if $error=no_script
  Lo sentimos, ha fallado la descarga de la nueva versión de WIMS de
  <tt>$download</tt>. Por favor vuelva a intentarlo más tarde.
 !endif
 
 !goto end
!endif

!if true iswordof $testing
<font color=red><em>Mode de pruebas.
Sólo se escribirá en el directorio de pruebas.</font></em>
<p>
!endif

!if $lockcheck != $empty
 Se está procediendo a la actualización del sistema WIMS. 
 El resumen actual de la salida del guión de actualización es el siguiente
 <small><pre>
 !sh cat ../log/update.log
 </pre></small>
 <a name=updateend>
 !href cmd=resume#updateend Refrescar la salida
.
 !goto end
!endif

!if $job2=check
 Resumen de la última actualización:
 (Por favor envíeselo a $wims_maintainer en caso de error).
 <small><pre>
 !sh cat ../log/update.log
 </pre></small>
 !goto check
!endif

!if $job2=check2
 Salida detallada de la última actualización:
 (Por favor envíeselo a $wims_maintainer en caso de error).
 <small><pre>
 !mexec scripts/cat_update2.sh
 </pre></small>
 !goto check
!endif

!if $pubversion=$empty
 Lo sentimos, no logramos contactar con el sitio de descarga de WIMS <tt>$download</tt>.
 !goto end
!endif

Este sitio WIMS está actualmente en la versión $wims_version.

!if $pubversion=$wims_version
 Es la versión pública más reciente del software, no necesita
 actualizarlo.
 !goto check
!endif

La versión pública más reciente es la $pubversion.
!if $recentversion<$thisversion
 ¡Su versión es más reciente que la versión pública! No es posible una actualización.
 !goto check
!endif

<p>
!href cmd=reply&job=update&job2=confirm Pulse aquí
 para descargar WIMS $pubversion de <tt>$download</tt> y actualizar el
servidor. <b><font color=red>¡AVISO!</font></b> Este proceso causará
la suspensión temporal de algunos servicios del servidor.
<em>No realice la actualización cuando el servidor esté sobrecargado.</em>
<p>
<b>Nota</b>. Las actualizaciones del servidor no tienen efecto negativo en
sus recursos locales (clases, ejercicios, documentos, módulos en desarrollo).
<p>
<b><font color=red>IMPORTANTE</font></b> ¡Debe hacer una revisión de los 
permisos de los ficheros antes de hacer una actualización de software!

:check
!if $logcheck!=$empty
<p>
 Salida de la última actualización:
 !href cmd=resume&job2=check resumen
,
 !href cmd=resume&job2=check2 detalle
.
!endif
:end
!reset job2

