
Wims is designed to provide free service on internet. The service on this
site is provided as-is, with no guarantee of whatever kind.

<p>The server program is subjet to
<a href=COPYING target=wims_external>GNU General Public Licence</a>. 
Its source code is available from http download (see
!href module=adm/light&phtml=download.phtml.$lang download information
)

</center> <p></tt>
&copy; 1997-2001- Main author of the server program:
!mailurl xiao@unice.fr XIAO, Gang
 of 
<a href="http://www.unice.fr">Université de Nice - Sophia Antipolis</a>.

The server program is now maintained by a group of persons
(wimsdev@cru.fr) which work on
<a href="http://sourcesup.cru.fr/frs/?group_id=379">http://sourcesup.cru.fr</a>.

<p>Translations into Chinese Big5 version is done by
!mailurl ychuang@cc.cktc.edu.tw Y. C. Huang
.

<p>Translations into simplified Chinese version (server and modules) is done by
a team led by
!mailurl zjchen@math.ecnu.edu.cn CHEN, Zhijie
.

<p>Translations into Italian version: 
!mailurl marina.cazzola@unimib.it Marina Cazzola
.

<p>Some translation into Spanish version:
!mailurl JMSS07@jazzfree.com José Maria Sanchez

!mailurl juanrafael.fernandez@hispalinux.es Juan Rafael Fernández García

Translation into Spanish version maintained by :
!mailurl didsene@wanadoo.fr Didier Sénéchal
.

<p>>Translations into Dutch version:
!mailurl jm.evers@schaersvoorde.nl J.M. Evers
.

<p>Translations into Slovenian version:
!mailurl bostjan.kuzman @gmail.com Bostjan Kuzman
.

<p>Translations into Catalan version:
!mailurl mquerol@xtec.cat Manel Querol
.


<p>Each wims module has its own authors/translators and its own
copyright policy, which may differ from that of the server program. 
Please refer to appropriate pages of the individual module for details.

<p>The source code of freely distributable modules are
available at the same ftp address as the server program.

<p>Some modules may use commercial softwares for their functionning. It is the
responsibility of the site maintainer to check with the software vendors
that such a use does not violate the licensing policy of the software, if he
wants to install that module on his server.


