This documentation is yet not finished ...
WIMS provides interfaces for some software packages which must be installed independantly. 

!read tabletheme
!reset table_center
!set cnt=!recordcnt interface0
!for j=1 to $cnt
  !set interf=!record $j of interface0
$table_header
$table_tr
<th style="width:150px;">$wims_name_name</th><td>
!line 1 of $interf
</td>
</tr>$table_tr
<th>$wims_name_Author</th><td>
!line 2 of $interf
!!!exec $name about
</td>
</tr>$table_tr
<th>$wims_name_Address</th><td>
!line 3 of $interf
</td>
</tr>$table_tr
<th>Use</th><td>
!line 4 of $interf
</td>
</tr>$table_end

!next

<h2>Logiciels internes à WIMS</h2>
!set cnt=!recordcnt interface1
!for j=1 to $cnt
  !set interf=!record $j of interface1
$table_header
$table_tr
<th style="width:150px;">$wims_name_name</th><td>
!set name=!line 1 of $interf
!line 1 of $interf
</td>
</tr>$table_tr<th>$wims_name_Author</th>
<td>
!line 2 of $interf
!!!exec $name about
</td>
</tr>$table_tr<th>Use</th>
<td>
!line 3 of $interf
</td>
</tr>$table_tr<th>Input data</th>
<td>
!line 4 of $interf
</td>
</tr>$table_tr<th>Output data</th>
<td>
!line 5 of $interf
</td>
</tr>$table_tr<th>Example</th><td>
!set example=!line 7 of $interf
!if $example!=
!set example=!replace internal \\ by $\
$ in $example
!set example=!replace internal xx by in $example
!set example0=!line 6 of $interf
!set example0=!replace internal \\ by $\
$ in $example0
!set u=!linecnt $example0
!for a=1 to $u
  !set a1=!replace internal = by , in $a1
  !set $(a1[1])=$(a1[2])
!next
<pre>
<span style="color:green">$example0
$name $example</span></pre>
 <br/>
 <pre>
 !exec $name $example
 </pre>
!endif
</td></tr>
$table_end

!next
