<p>
WIMS has a very simple way to let you make use of many of its features,
without being a specialist of its structure: $emph light phtml$emphend.
Just take any of your existing html page, add a few WIMS
commands here and there, and publish it on a WIMS site as a light phtml
file. And your page looks much more intelligent. 
<p>
Once your page is on a wims site, it can be called from anywhere on the web,
just like an ordinary web page.
<p>
It goes without saying that really intelligent pages require intelligent
programming, so if you want your page behave as intelligent as yourself, you
have to know a minimum of the principle of computer programming, and dig a bit into
the technical reference part of this documentation to know what commands and variables 
you should use for the
effects you want. However, even without interactivity and programming, your
page will get the following basic features:
<ol>
 <li>Inline mathematical symbols. Simply write
  <tt>$$m_alpha$$m_le$$m_beta</tt> in your phtml file, and you get
  $m_alpha$m_le$m_beta under wims. Your visitor will
  be able to choose the size of the font he wants (as well as the instex
  font sizes as below), without you having to worry about this. See also the section 
  $(ref1)mathfonts$(ref2)mathfonts">$title_mathfonts</a>. <p>
  
 <li>For more complicated mathematical formulas, you can choose to use
  $(ref1)cmdlist_instex_&+cmd_choose=all$(ref2)cmdlist_instex_">instex</a>.
  For example, the line 
  !set ins_align=middle
  <pre>
  $ !instex $$$$ \int^b_a \sqrt{x^2+1}dx $$$$
  </pre>
  in your phtml source will give the inline formula 
  !instex $$ \int^b_a\sqrt{x^2+1}dx $$
  , while <pre>
  $ !instex $$$$$$$$ \int^b_a \sqrt{x^2+1}dx $$$$$$$$
  </pre>
  gives the same formula in displayed style:
  !instex $$$$ \int^b_a \sqrt{x^2+1}dx $$$$
  . Unlike some other packages, you don't have to precompile your phtml
  file, and your formula can vary from request to request (see below).
  <p>Planned for near future, there will
  also be a WIMS command translating raw mathematical
  expressions into TeX source. So you even don't have to know TeX in order to
  insert beautified equations... <p>

 <li>Dynamic insertion of graphisms. Just one WIMS command
  ($(ref1)cmdlist_insplot_&+cmd_choose=all$(ref2)cmdlist_insplot_">insplot</a>)
  with an equation, and your page will contain a figure which may be
  animated in the way you like. And it may be made to vary from
  request to request... <p>

 <li>You may define and use substitutable variables. The value of these
  variables may be client-defined, random, etc... And you may put them in
  the sources of <tt>instex</tt>, <tt>insplot</tt>, etc. Imagine the
  effect. Such variables also allow you to define your style macros, among
  other things. <p>
 
 <li>Powerful mathematical softwares are directly at your disposal: A simple
  line <pre>!exec pari factor(2^67-1)</pre>
  gives you the factorisation of the number 2<sup>67</sup>-1 (but you have to 
  copy one of my modules to reformat the output in an intelligent way).
  <p> 
 <li>By using wims commands, you will automatically benefit from future
  enhancements/improvements of the wims server, without modifying your page: 
  e.g. better TeX fonts or graphics, more intelligent translations of
  mathematical expressions, etc.
</ol>

At any time, when you want heavy interactivity features, you can migrate
your light page into a real WIMS module which allows you to built very
complicated structures. See the chapter
$(ref1)migrate$(ref2)mibrate">$title_migrate</a>.

<p>

Now $(ref1)lighthowto$(ref2)lighthowto">read this</a> for the detail of how
to publish a light phtml page.

