!set x=<i>x</i>

<p>
$x is a real number, which can be replaced by an expression, to allow
composite functions.
<p>
<center><table border=2 cellspacing=1 cellpadding=3 bgcolor="#d0e0c0">
<tr><th>function<th>description<th>how to type
<tr>
<tr><td>$m_pi
    <td>constant known to all<td>
    <tt>pi</tt> or <tt>Pi</tt> or <tt>PI</tt>
<tr><td><i>e</i><td>base of natural logarithmic<td>
    <tt>e</tt> or <tt>E</tt>
<tr>
<tr><td>|$x|<td>absolute value of $x<td><tt>abs(x)
<tr><td>sign($x)<td>sign of $x:
       <br>&nbsp;=-1 if $x&lt;0<br>&nbsp;=0 if $x=0<br>&nbsp;=1 if $x>0
       <td><tt>sign(x)
<tr><td>
    !instex $$ \sqrt x $$
    <td>square root of $x
    <td><tt>sqrt(x)</tt> or <tt>x^(1/2)</tt>
<tr><td>?<td>closest integer to $x<td><tt>rint(x)</tt>
<tr><td>?<td>largest integer <=$x<td><tt>floor(x)</tt>
<tr><td>?<td>smallest integer >=$x<td><tt>ceil(x)</tt>
<tr>
<tr><td><i>e<sup>x</sup><td>exponential<td>
    <tt>exp(x)</tt> or <tt>e^x</tt> or <tt>E^x</tt>
<tr><td>ln($x)<td>natural logarithmic<td><tt>log(x)</tt> or <tt>ln(x)</tt>
<tr>
<tr><td>sin($x)<td>trigonometric sine<td><tt>sin(x)
<tr><td>cos($x)<td>trigonometric cosine<td><tt>cos(x)
<tr><td>tg($x)<td>trigonometric tangent<td><tt>tan(x)</tt> or <tt>tg(x)</tt>
<tr><td>ctg($x)<td>trigonometric cotangent<td><tt>cotan(x)</tt> or <tt>ctg(x)</tt>
    </tt> <br> or <tt>cot(x)
<tr><td>arcsin($x)<td>inverse trigonometric<td><tt>asin(x)</tt> or
    <tt>arcsin(x)</tt>
<tr><td>arccos($x)<td>inverse trigonometric<td><tt>acos(x)</tt> or
    <tt>arccos(x)</tt>
<tr><td>arctg($x)<td>inverse trigonometric<td><tt>atan(x)</tt> or
    <tt>arctan(x)</tt> <br>or <tt>arctg(x)</tt>
<tr>
<tr><td>sh($x)<td>parabolic sine<td><tt>sh(x)</tt> or <tt>sinh(x)</tt>
<tr><td>ch($x)<td>parabolic cosine<td><tt>ch(x)</tt> or <tt>cosh(x)</tt>
<tr><td>th($x)<td>parabolic tangent<td><tt>th(x)</tt> or <tt>tanh(x)</tt>
<tr><td>Argsh($x)<td>inverse parabolic<td><tt>asinh(x)</tt> or <tt>argsh(x)</tt>
    <br>or <tt>Argsh(x)</tt>
<tr><td>Argch($x)<td>inverse parabolic<td><tt>acosh(x)</tt> or <tt>argch(x)</tt>
    <br>or <tt>Argch(x)</tt>
<tr><td>Argth($x)<td>inverse parabolic<td><tt>atanh(x)</tt> or <tt>argth(x)</tt>
    <br>or <tt>Argth(x)</tt>
<tr><td>max(x,y)<td>Bigger among x and y<td><tt>max(x,y)</tt>
<tr><td>min(x,y)<td>Smaller among x and y<td><tt>min(x,y)
<tr><td>gcd(x,y)<td>Greatest Common Divisor<td><tt>max(x,y)
<tr><td>lcm(x,y)<td>Least Commun Multiple<td><tt>min(x,y)
</table></center>
!exit

!! Add the following:
<ul>
<li>lg(x): log of base 10</LI>
<li>j0(x), j1(x), y0(x), y1(x): Bessel functions</LI>
</ul>

