
The current version of wims is $wims_version.

<p>The development of wims system is still at a very priliminary stage. The few
applications available under current version are experimental and are often
not very refined. The main purpose of these applications is yet to demonstrate and
test the capabilities of the system.

<p>However, these currently available modules can already provide services
which either have no counterpart elsewhere, or 
achieves a combination of power and ease-of-use largely outpacing 
their competitors. And we now start to have enough applications to allow
real works at some levels (basically at beginning university year).
<p>
Wims is a very ambitious project, with more and more participants taking part
in its development. The
<a href=http://www.listes.cri74.org/wws/info/wims>WIMS mailing list</a>
is a good place for keeping track of the current development status.

