!set lang_exists=yes

!if $wims_read_parm!=
  !goto $wims_read_parm
!endif

!set name_title=nome del forum
!set name_description=descrizione del forum
!set name_supervisor=nome dell'owner
!set name_email=indirizzo e-mail
!set name_password=password del forum
!set name_passsup=password di gestione

!set forumname=<b><font color=green>$title</font></b>

!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!distribute lines Création d'un forum de discussion\
  Recommencer l'opération.\
  Nom et prénom du gérant du forum (c'est-à-dire vous)\
  Votre forum ne sera créé  que si vous fournissez une adresse électronique qui fonctionne en ce moment même.\
  Choisissez le mot de passe du gérant\
  Choisissez un mot de passe du forum\
  entre 4 et 16 caractères, chiffres ou lettres sans accent\
  Continuer\
  Bonjour\
  Mot de passe du gérant\
  Mot de passe du forum\
  Code pour le forum\
  caractères\
into title_title,name_restart,name_name_owner,name_warning1,name_choosepass1,name_choosepass2,\
  name_instruction,name_continue,name_hello,name_ownerpass,name_forumpass,name_code,\
  name_characters

!set name_name_forum=!nosubst Nom du forum (au plus $titlelim caractères)

!set name_help1=Ce mot de passe vous permettra d'accéder à la classe en tant\
  que gérant. Vous devez être le seul à le connaître. 

!set name_help2=Le mot de passe du forum sera exigé pour les inscriptions des utilisateurs du \
  forum ; vous pouvez donc le diffuser auprès de tous ceux que vous autorisez à participer aux discussions.
  
!set name_warning=Si vous créez un forum de discussion sur ce site WIMS, vous devez assumer \
  la responsabilité de sa maintenance. <p> Pour créer votre forum, veuillez remplir\
  les renseignements suivants.
 
!set name_warning2=<b>Attention</b> Ce code ne sert qu'une seule fois ici. Il ne peut pas \
 être utilisé pour vous connecter au forum&nbsp;!
 
!exit

:step1
Vous êtes en train de créer un forum de discussion $forumname sur le site
 WIMS à
 $httpd_HTTP_HOST.
 <p>
 Si vous décelez une erreur dans les renseignements ci-dessus, veuillez
 !href module=$module&cmd=reply&step=0 la corriger.
 <p>Sinon, afin de vérifier l'exactitude de vos mots de passe,
 veuillez les retaper encore une fois. 
 !exit
 
:step2
 Maintenant, vous avez besoin d'un code pour terminer l'opération de création
 d'un nouveau forum de discussion sous WIMS sur le site $http_HTTP_HOST. <p>
 Ce code vient d'être envoyé à votre adresse électronique
 ``<tt>$email</tt>''. Veuillez vérifier votre boîte à lettre
 électronique (attendez quelques instants si nécessaire) et lire le message
 qui vous a été envoyé.
 Relevez le code qui se trouve dans le message et copiez-le ci-dessous.
 !exit
 
 :step3
 Votre forum de discussion $forumname est maintenant en place. Félicitations
 et amusez-vous&nbsp;!<p>
 Vous pouvez accéder à votre forum 
 !href module=adm/forum/forum à partir d'ici
.
!exit