!reset confirm
!read adm/css.phtml
!header1

!read names.phtml

!if $job iswordof student
 !changeto $job.phtml
!endif

!if $cmd=help
 !read help/$special_parm.phtml
 !goto end
!endif

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$name_title

<p>
!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !goto end
!endif

!if $job=getsource
 !read getsource.phtml
 !goto end
!endif

!if $activetest>-1
 <b>Sheet information :</b>
!endif
!read adm/sheet/sheetinfo.phtml

!ifval $activetest=-1
 !goto end
!endif

:end1
<a name=list></a>
<b>Content of the sheet :</b>
!if $exocnt=0
 <p>This sheet has no content yet. 
!else
 <small>[
 !href module=adm/sheet&sh=$sheet&job=print $wims_name_printable
 ]</small>
 !read adm/sheet/sheetcontent.phtml
!endif

!if $activetest=0
 <p>To add a work (exercise, course, tool, etc.) to a sheet, you have to choose it (see below), choose its level of difficulty. Then use the link at the end of the page
 of this exercise to add it to the sheet.
 <p>
 You can :
  <ul>
   <li> use search engine :
	!read adm/search_engine/form.phtml
   </li>
   <li> 
    !href cmd=reply&job=prep_putsource $wims_name_putsource
   </li>
  </ul>
!endif

:end
!if $activetest>=0
 !if $activetest=0
  !let wims_menu_items=!append line putsource,1,cmd=reply&job=prep_putsource to $wims_menu_items
 !endif
 !if $job!=getsource
  !let wims_menu_items=!append line sheetsource,1,cmd=reply&job=getsource to $wims_menu_items
 !endif
 !let wims_menu_items=!append line ,0,\
printable,1,module=adm/sheet&sh=$sheet&job=print\
participantview,1,module=adm/sheet&sh=$sheet to $wims_menu_items
!endif

!tail

!distribute item ,, into job,source,title,desc,prpage

