
!set classname=<b><font color=green>$wims_classname</font></b>\
 <b><font color=green>($wims_institutionname)</font></b>
 
!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

!set statutname=!defof SU_Uprep,SU_Uprep,SU_Ac,SU_Ex,SU_Hi in wimshome/public_html/modules/home/names.$lang
!set statutaction=Activate,Expire it,Deactivate it,Hide it,show it,$wims_name_erase
!set seriesaction=$wims_name_change,$wims_name_erase,$wims_name_up

!! definition des noms pour les liens dans le menubox (d閒inis par wims_menu_items)
!distribute items 插入一个源文件,\
		participants' view of the sheet,\
		页的源码. \
into wims_name_putsource,wims_name_participantview,wims_name_sheetsource

!let name_shtab=No,$wims_name_title,$wims_name_Description,Points,Weight,得分相关性,$wims_name_comment,Actions

!if $activetest<=0
 !let wims_name_sheetadmin=返回页面维护的主页.
 !set name_title=!nosubst 准备页 $sheet
!else
 !let wims_name_sheetadmin=Page of management
 !set name_title=!nosubst Management of sheet $sheet
!endif

!let name_shinfo=!nosubst Title <small>(limited to 80 characters)</small>,Status,\
Description <br></small>(limited to $desc_limit characters; tags and html link allowed)</small>,\
Expiration date,Presentation page,Registration of scores,for all sharing classes,$wims_name_comment
!let name_allowtype=open to all,closed to all, open to the following hosts (and/or times) :
!let name_mksheet=Create the sheet

!distribute lines Sheet information\
Content of the sheet\
This sheet has no content yet.\
原标题为\
改变项目\
需得分\
权重  \
改正源码\
The sheet expiration date of the sheet must be before the class expiration date which is\
Your request is ignored.\
into name_info,name_content,name_warning,name_oldtitle,name_titlemodif,\
name_pointsasked,name_ofweight,name_correctsource,name_expiration1,name_expiration2

!set name_text1=To add a work (exercise, course, tool, etc.) to a sheet, you have to choose it (see below), choose its level of difficulty. Then use the link at the end of the page\
of this exercise to add it to the sheet.

!set name_text2= use search engine
!set name_text3=Find an exercise amongst
!set name_text4=Find an exercise in your account

!if $job=student
  !set name_title=作业页  $sheet<br>$title (学生用)
  !set name_sheetempty=T本页是空的! 没有为您指定任何作业. 可能是您的主持教师的失误.
  !set name_assignedwork=本页所指定的作业
  !set name_quality=$[$re] 分中得 0 分, 平均分
!endif

