
!if $fsize=$empty
对不起, 我们不能把你的班级存档. 这是内部错误.
 !exit
!endif

这里是你的班级的备份文件:
!getfile $fname.$format $fname.$format
 ($fsize K).
点击其上就可以存放到你的机器上.<p>

!if $fsize<50 and all isitemof $selection
 !exit
!endif

!form reply
<input type=hidden name=job value=$job>
<input type=hidden name=job2 value=$job2>
!if $fsize<500
你也可以选择欲保存的数据:
!else
备份文件对服务器而言太大了(它能接受文件的大小有限制).
为了减小备份的大小, 你可以做选择性备份:
!endif

<p>
!set selection=$select
!formcheckbox selection list $reclist prompt $tot
<p>
请点击
<input type=submit value="选择性备份">
以修改上述文件并保存它.

<b>说明</b>. 
根据班级的活动情况, 通常参加者活动、论坛信息以及班级文件比较大.
你可以考虑对不同资源做几个选择性备份.
</form>


