!if $devno>0
 $name_modification
!else
$name_add
!endif

!form reply
<input type=hidden name=job2 value=mod2>
<center><table border=0>
<tr><td>$wims_name_Login
<td><input size=16 name=devlogin value="$login">
<tr><td>$wims_name_Password
<td><input type=password size=16 name=devpasswd>
<tr><td>$wims_name_name
<td><input size=40 name=devname value="$name">
<tr><td>$wims_name_email
<td><input size=30 name=devemail value="$email">
</table>
 <input type=submit value="$wims_name_tosave">
</center>
</form>

!reset devlogin, devpasswd, devname, devemail

