!if $devno>0
 $name_modification
!else
$name_add
!endif

!! for cn versions can be redefine in lang/names.phtml.xx
!default name_name=$wims_name_name
!form reply
<input type="hidden" name="job2" value="mod2" />
<fieldset class="property_fields halfwidth blockcenter">
   <div class="field box">
    <label for="devlogin">$wims_name_Login</label>
    <input size="16" name="devlogin" id="devlogin" value="$login" />
   </div>
   <div class="field box">
    <label for="devpasswd">$wims_name_Password</label>
     <input type="password" size="16" name="devpasswd" id="devpasswd" />
   </div>
   <div class="field box">
    <label for="devname">$name_name</label>
    <input size="40" name="devname" value="$name" />
    <div class="formHelp tt">$wims_name_firstname,$wims_name_lastname</div>
   </div>
   <div class="field box">
    <label for="devemail">$wims_name_email</label>
    <input size="30" name="devemail" id="devemail" value="$email" />
   </div>
   <div class="wimscenter wimsform">
    <input type="submit" value="$wims_name_tosave" />
   </div>
 </fieldset>
!formend

!reset devlogin, devpasswd, devname, devemail

