<div id="wimstopbox">

  !!Site Title
  !read themes/_widgets/site_title.phtml

  !!Institution logo
  !set positionlogo=right
  !read themes/_widgets/institution_logo.phtml

  !!Language Selector
  !read themes/_widgets/language_selector.phtml

  <br class="clearall"/>

  <ul class="wimsmenu menuglobal">
    !!module_path = $module_path
    !!wims_hm_cnt = $wims_hm_cnt

    !if $[$wims_home_items_cnt + $wims_hm_cnt + $wims_link_close_cnt]!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
      !distribute items li into div1
      !!read themes/_widgets/headhome.phtml
      !read themes/_widgets/headmenu.phtml
      !read themes/_widgets/logout.phtml

      !distribute items li,div into div0,div1
      !read themes/$wims_theme/widgets/permalink.phtml

      !reset div0 div1

      !!## technical parameters
      !if $class_cas_auth=$empty
        !set m_init_parm=!replace internal & by $ $ in $module_init_parm
        !set class_cas_auth=!getopt class_auth in $m_init_parm
      !endif

      !read themes/_widgets/authlogout.phtml

    !endif

    !!Menu a afficher sur la page d'accueil des visiteurs
    !if $module_path isitemof home and $wims_user=$empty

      !! Teachers Zone
      <li class="menuitem n_supervisor">
        !read ./adm/oneitem.phtml n_supervisor,1,module=adm/class/classes&type=supervisor
      </li>

      !! Help link
      <li class="menuitem help">
        !read ./adm/oneitem.phtml help,4,module=help/main,help
      </li>
    !endif
  </ul><!-- /menuglobal -->

  !read themes/_widgets/ariane.phtml
</div><!-- fin de wimstopbox-->
