
<center><h3>Configurazione dell'accesso alle risorse</h3></center>

!form reply
<input type=hidden name=job value=access>
<center>Definizione dell'accesso alle resorse:
!href cmd=help&special_parm=accessconf [$wims_name_help]
<br>
<textarea name=accessdef cols=70 rows=15>$accessdef</textarea>
<p>
<input type=submit name=save value=OK>
<input type=submit name=abandon value=Annulla>
</center>
</form>

!reset job, accessdef

