
!set classname=<b><font color=green>$wims_classname</font></b>\
 presso <b><font color=green>$wims_institutionname</font></b>
 
!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!set title=Configurazione e gestione
!if $job=arch
 !set title=Backup e ripristino
!endif

!if $job=clean
 !set title=Manutenzione del corso
!endif

!if $job=neighbor
 !set title=Corsi vicini
!endif

!if $job=connect
 !set title=Connessioni ad altri server/piattaforme
!endif

