
!set classname=<b><font color=green>$wims_classname</font></b>\
 presso <b><font color=green>$wims_institutionname</font></b>
 
!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!set title=Configurazione e gestione
!if $job=arch
 !set title=Backup e ripristino
 !goto commun
!endif

!if $job=clean
 !set title=Manutenzione del corso
 !goto commun
!endif

!if $job=neighbor
 !set title=Corsi vicini
 !distribute lines Configurazione<br>di vicinato\
   Condivisione risorse\
   per voi\
   per l'altro corso\
   Condivisione reciproca attiva.\
   Voi condividete le sue risorse.\
   Condividete le vostre risorse.\
   Permesso reciproco di condivisione.\
   Ha il permesso di condividere le vostre risorse.\
   Vi permette di condividere le sue risorse.\
   Interrompere la condivisione\
   Condividere\
   importare tutti\
   Teaching resources\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3,name_stopsharing,name_share,name_everybodyimport,name_teaching
 !goto commun
!endif

!if $job=connect
 !set title=Connessioni ad altri server/piattaforme
 !goto commun
!endif

!if $job=access
 !set title=Configurazione dell'accesso alle risorse
 !goto commun
!endif

!if $job2=addshare
 !set title=Condividere le risorse del corso
 !goto commun
!endif

!if $job=grestrict
 !set title=Limitazione dell'accesso ai punteggi
 !goto commun
!endif

!if $job=present
 !set title=Configurazione dell'aspetto del corso
 !goto commun
!endif

!if $job=oefdefault
 !set title=Parametri di default per moduli di esercizi OEF
 !goto commun
!endif

!if $job=security
 !set title=Configurazioni di sicurezza disponibili
 !goto commun
!endif

!if $job=authtype
 !set title=Autenticazione attraverso un server LDAP
 !set name_intro_authtype=Selezionare <tt>ldap</tt> e compilare con i dati del \
   server ldap che si vuole utilizzare.
 !goto commun
!endif

:commun
!distribute line Autenticazione\
Opzioni\
Accesso agli strumenti\
Parametri di default per esercizi OEF\
Corsi vicini\
Opzioni di sicurezza\
Pulizia selettiva\
Actualiser\
Altri server\
Modifica password\
Zone dipendenti\
Aspetto\
Registrazione dei voti\
Indirizzo di una piattaforma esterna\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items zone,iscritti,esercizi,documenti,docenti\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers


!distribute lines Accesso da IP sicuro\
  Foglio stile (css)		\
   Logo\
   Posizione del logo\
   in alto a sinistra,in alto a destra\
   Tema\
   Set di icone\
   Livello accademico\
   Postazioni abilitate alla registrazione dei voti\
   Password di iscrizione al corso\
   Password di gestione del corso\
   Numero massimo di esercizi e esami salvabili\
   Link verso una piattaforma o una pagina web\
   Colore dello sfondo delle pagine\
   Colore dello sfondo dei menu\
   Colore dei link nei menu\
   Immagine di sfondo delle pagine\
   carica un file css\
   Scala dei colori dei voti (da 0 a 10)\
   into name_secure,name_css,name_logo,name_position_logo,name_logo_side,name_theme,\
   name_theme_icon,name_level,name_security,name_password,name_supass,name_exolog,name_ent,\
  name_background_color,name_menu_color,name_refmenu_color,name_image,name_css_transfer,name_colorscore

!set name_content_style = Contenuto del foglio stile del corso \
<br>(quando <tt>$name_css</tt>  è sulla <tt>class</tt>)&nbsp;:

!set name_content_style2=o copia qui i comandi css delle pagine del corso
