
<center>
!form reply
$table_header
 $table_tr
  <td align=center>Una sessione contiene</td>
  <td>
   !set nw_qnum=$user_qnum
   !formselect nw_qnum from 1 to 9
   esercizi.
  </td>
 </tr>
 $table_tr
  <td align=center>Livello di difficoltà</td>
  <td>
   !set nw_qcmlevel=$user_qcmlevel
   !formselect nw_qcmlevel from 1 to 9
  </td>
 </tr>
 $table_tr
  <td align=center>Limite di tempo </td>
  <td>
   <input size=7 name=nw_scoredelay value="$user_scoredelay"> secondi.
  </td>
 </tr>
 $table_tr
  <td align=center>Numero di risposte multiple da cui scegliere: </td>
  <td>
   !set nw_qcmpresent=$user_qcmpresent
   !formselect nw_qcmpresent list 2,3,4,5,6,7,8 
  </td>
 </tr>
 $table_tr
  <td align=center>Dare la soluzione (se disponibile) ? </td>
  <td>
   !default nw_presentsol=$user_presentsol
   !formselect nw_presentsol list 0,1,2 prompt mai,se il punteggio non è massimo,sempre
  </td>
 </tr>
 $table_tr
  <td rowspan=4>&nbsp;</td><td>
   !set nw_check=$user_check
   !formcheckbox nw_check list 1 prompt Le scelte multiple contengono sempre la risposta giusta.
  </td>
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox nw_check list 2 prompt Le risposte sbagliate nelle scelte multiple sono penalizzate.
  </td>
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox  nw_check list 3 prompt Mostra la risposta giusta.
  </td>
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox nw_check list 4 prompt Mostra suggerimenti (se disponibili).
   !let tmp=!replace word expert by $ in $special_parm2
  </td>
 </tr>
 $table_tr
 <td colspan=2 align=center>
  <input type=submit value="$wims_name_tosave">
  <input type=hidden value="1" name="step">
 </td></tr>
</table>
</form>
</center>
<p><small>Vous pouvez mettre deux nombres dans le chronomètre, une petite
limite suivie d'une plus grande. Dans ce cas, la première limite déclenche 
la réduction du score, qui sera à  0 quand la seconde limite est atteinte.
</small>
