
!if $wims_supertype=2
 !set name_thisclass=del portale
 !set name_subclasses=i corsi coordinati
!else
 !set name_thisclass=della zona attuale
 !set name_subclasses=le zone dipendenti
!endif

!if $confirm!=$empty and $propagate!=$empty
 L'invio della configurazione a $name_subclasses ha avuto successo: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
 Potete scegliere di inviare le configurazioni seguenti $name_thisclass
 a tutti $name_subclasses: <p>

 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="$wims_name_send">
 </form>
!endif
<p>
Si noti che $name_subclasses non riceveranno automaticamente le 
ulteriori modifiche della configurazione $name_thisclass. &Egrave; 
necessario reinviare le modifiche ogni volta che volete trasmettere
le modifiche a $name_subclasses.

