
!read adm/title.phtml 3\
\
Configurazioni di sicurezza disponibili:

<ul>
<li><p>
!href module=adm/class/passwd.$module_language Modificare la password di gestione
.

<li><p>
!href cmd=renew&job=log Visualizzare il log
 dell'attività di gestione del corso. (Si consiglia di verificare che tutte le operazioni
effettuate siano opera vostra, se così non fosse, il faut vérifier s'il n'y a pas une
fuite de votre mot de passe d'docente.)

<li><p>Configurer la
!href cmd=reply&job=grestrict restriction par classe
 des sites ayant accès aux scores.

<li><p>Autres définitions de sécurité dans 
!href cmd=renew&job=list la configuration de la classe
.

</ul>

