!!##language

!set indgood=<span style="color:green;font-weight:bold">bonne réponse</span>
!set indpartial=<span style="color:orange;font-weight:bold">partiellement bonne</span>
!set indbad =<span style="color:red;font-weight:bold">mauvaise réponse</span>
!set indprec=<span style="color:orange;font-weight:bold">mauvaise précision</span>
!set condgood=<span style="color:green;font-weight:bold">OUI</span>
!set condbad =<span style="color:red;font-weight:bold">NON</span>
!set indsee =<small>voir l'analyse</small>
