!!##language

!set indgood=<font color=green><b>bonne réponse</b></font>
!set indpartial=<font color=orange><b>partiellement bonne</b></font>
!set indbad =<font color=red><b>mauvaise réponse</b></font>
!set indprec=<font color=orange><b>mauvaise précision</b></font>
!set condgood=<font color=green><b>OUI</b></font>
!set condbad =<font color=red><b>NON</b></font>
!set indsee =<small>voir l'analyse</small>
