!nocache
!if $oef_test=yes
 !set renewlink=cmd=next&retest=again
 $header_js
 !goto tester
!else
 !set init_parm=!translate + to $ $ in $module_init_parm
 !set renewlink=cmd=renew&worksheet=$worksheet&$init_parm
!endif

!if $printing=yes
 !changeto oef/print.phtml
!endif

!if $title!=$empty
 !set module_title=$title
 !set module_author=$author
 !set module_address=$email
!endif

!if 0$delay2>0 and $status!=$empty
 !set now_=$wims_nowseconds
 !read js/chrono.js $[max(0,$delay1-($now_-$starttime))]
!endif
$header_js
!header

!if $module_checkdata!=yes
 !read oef/fr/nodata.phtml
 !goto end
!endif

!if $title=$empty
 Ce module est un groupement d'exercices. Vous l'avez visiblement demandé sans
 préciser l'exercice du module que vous voulez faire. Vous
 avez peut-être cliqué sur un lien incorrect à moins qu'il ne 
 s'agisse d'une erreur du logiciel.
 <p><center>
 !href module=$module Essayez de refaire votre manipulation
 , ou
 !href $ abandonner
 . </center>
 !goto end
!endif

!if 0$delay1>0 and $status!=$empty
 <p><form target=# name=chrono><center>
 <table border=2 bgcolor=$wims_ref_bgcolor><tr><td>
 &nbsp;<b><font color=red>Attention !</font></b>
 !if $qnum>1
  Cette série est chronométrée.
 !else
  Cet exercice est chronométré.
 !endif
 <input size=4 name=clock readonly onFocus=this.blur();>
 </table>
 </center></form> <p>
!endif

:tester
!read oef/present.phtml

<center><hr width=50%></center>

!if $cmd=hint
 !read oef/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read oef/msg.phtml
  <center><hr width=50%></center>
 !endif
 !read oef/form.phtml
 <p>
 !if $hint!=$empty and $givehint>0
  !href cmd=hint Indication
.
 !endif
 !if $help!=$empty
  !href cmd=help Aide
.
 !endif
 !if $qnum<=1
  !href $renewlink Recommencer l'exercice
.
 !else
  Ceci est l'exercice $[$reply_cnt+1] d'une série qui en compte $qnum.
  !href $renewlink Recommencer la m&ecirc;me série
.
 !endif
!else
 !if $error!=$empty
  !read oef/msg.phtml
  <center><hr width=50%></center>
 !endif
 !read oef/answer.phtml
 <p>
 !if $status!=$empty
  Ceci est l'exercice $reply_cnt d'une série qui en compte $qnum. <p>
  !href cmd=next Continuer la série avec l'exercice suivant
, ou
  !href $renewlink recommencer la m&ecirc;me série
. (Vous devez arriver jusqu'à la fin de la série pour avoir une note.)
 !else
  !if $qnum>1
   Vous avez terminé une série de $qnum exercices, avec une note de
   $module_score sur 10.
   !ifval $module_score>9.8
    Félicitations!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (Vous avez été pénalisé par le dépassement du temps.)
   !endif
   <p>
   !href $renewlink Recommencer la m&ecirc;me série
.
   !if $wims_sheet=$empty
    !href exo_Intro
.
   !endif
  !else
   Vous avez obtenu une note de $module_score sur 10.
   !ifval $module_score>9.8
    Félicitations!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (Vous avez été pénalisé par le dépassement du temps.)
   !endif
   <p>
   !href $renewlink Recommencer le m&ecirc;me exercice
.
   !if $wims_sheet=$empty and $oef_test!=yes
    !href exo_Intro
.
   !endif
  !endif
 !endif
!endif

!if $replydefaulted=yes
 <p> <small>
 Mode de développement :
 !if $oef_default=yes
  les bonnes réponses sont insérées dans les champs 
  de réponse par défaut.
 !else
  !href cmd=config&oef_default=yes insérer les bonnes réponses
  dans les champs.
 !endif
 </small>
!endif

!read ./endhook.phtml
!if $wims_user=supervisor and exam notin $session and \
	..classes/ notin ..$module and ..adm/ notin ..$module and \
	..devel/ notin ..$module and \
	GNU isin $module_copyright and \
	_check notin $session and \
	$class_importation!=no
 <p>
 !href module=adm/createxo&existing=$thisexo&catmodule=$module Importer
 cet exercice dans votre classe pour le modifier.
!endif
:end
!tail

