!read tabletheme
When you work with WIMS, you will often be asked to enter mathematical
expressions.
<p>
Mathematical expressions can be typed in the usual way: <tt>3*x+5</tt> for
!htmlmath 3x+5
, <tt>sin(pi*x)</tt> for
!htmlmath sin(pi*x)
, <tt>y^3+1</tt> for
!htmlmath y^3+1
, <tt>(x+1)/(y-1)</tt> for
!set ins_align=middle
!instex $$$$ {x+1 \over y-1} $$$$
, etc.
<p>
Besides, WIMS contains an intelligent analyzer which can correct common
``errors'' in the mathematical expressions. For example, <tt>3x+5</tt>
will be corrected to <tt>3*x+5</tt>, <tt>sin x</tt> will be corrected to
<tt>sin(x)</tt>, etc. But we do not recommend you to rely too heavily on
this corrector, because sometimes ambiguities in the expressions might lead
to wrong interpretations. It is best to always type mathematical expressions
``correctly'', even if it is sometimes combersome.
<p>
Here is a list of mathematical functions and the (correct) way to enter
them. These functions are recognized by WIMS whenever they make sense. (Some
modules may accept additional functions; please refer to help pages of
the modules.)
<p>
!set x=x
You may replace $x by any sub-expression in the following table.
<p>
$table_header
$table_tr<th>function<th>description<th>how to type
$table_tr<td>$m_pi
    <td>constant known to all<td>
    <tt>pi</tt> or <tt>Pi</tt> or <tt>PI
$table_tr<td><i>e</i><td>base of natural logarithmic<td>
    <tt>e</tt> or <tt>E</tt>
$table_tr<td>|$x|<td>absolute value of $x<td><tt>abs(x)
$table_tr<td>sign($x)<td>sign of $x:
       <br>&nbsp;=-1 if $x&lt;0<br>&nbsp;=0 if $x=0<br>&nbsp;=1 if $x>0
       <td><tt>sign(x)
$table_tr<td>
    !instex $$ \sqrt x $$
    <td>square root of $x
    <td><tt>sqrt(x)</tt> or <tt>x^(1/2)
$table_tr<td>?<td>closest integer to $x<td><tt>rint(x)
$table_tr<td>?<td>largest integer $m_le$x<td><tt>floor(x)
$table_tr<td>?<td>smallest integer $m_ge$x<td><tt>ceil(x)
$table_tr<td><i>e<sup>x</sup><td>exponential<td>
    <tt>exp(x)</tt> or <tt>e^x</tt> or <tt>E^x
$table_tr<td>ln($x)<td>natural logarithmic<td><tt>log(x)</tt> or <tt>ln(x)
$table_tr<td>lg($x)<td>logarithmic of base 10<td><tt>lg(x)</tt> or <tt>log10(x)
$table_tr<td>sin($x)<td>trigonometric sine<td><tt>sin(x)
$table_tr<td>cos($x)<td>trigonometric cosine<td><tt>cos(x)
$table_tr<td>tg($x)<td>trigonometric tangent<td><tt>tan(x)</tt> or <tt>tg(x)
$table_tr<td>ctg($x)<td>trigonometric cotangent<td><tt>cotan(x)</tt> or <tt>ctg(x)
    </tt> <br> or <tt>cot(x)
$table_tr<td>arcsin($x)<td>inverse trigonometric<td><tt>asin(x)</tt> or
    <tt>arcsin(x)
$table_tr<td>arccos($x)<td>inverse trigonometric<td><tt>acos(x)</tt> or
    <tt>arccos(x)
$table_tr<td>arctg($x)<td>inverse trigonometric<td><tt>atan(x)</tt> or
    <tt>arctan(x)</tt> <br>or <tt>arctg(x)
$table_tr<td>sh($x)<td>hyperbolic sine<td><tt>sh(x)</tt> or <tt>sinh(x)
$table_tr<td>ch($x)<td>hyperbolic cosine<td><tt>ch(x)</tt> or <tt>cosh(x)
$table_tr<td>th($x)<td>hyperbolic tangent<td><tt>th(x)</tt> or <tt>tanh(x)
$table_tr<td>Argsh($x)<td>inverse hyperbolic<td><tt>asinh(x)</tt> or <tt>argsh(x)
    <br>or <tt>Argsh(x)
$table_tr<td>Argch($x)<td>inverse hyperbolic<td><tt>acosh(x)</tt> or <tt>argch(x)
    <br>or <tt>Argch(x)
$table_tr<td>Argth($x)<td>inverse hyperbolic<td><tt>atanh(x)</tt> or <tt>argth(x)
    <br>or <tt>Argth(x)
$table_tr<td>max(x,y)<td>Bigger among x and y<td><tt>max(x,y)
$table_tr<td>min(x,y)<td>Smaller among x and y<td><tt>min(x,y)
$table_tr<td>gcd(x,y)<td>Greatest Common Divisor<td><tt>gcd(x,y)
$table_tr<td>lcm(x,y)<td>Least Commun Multiple<td><tt>lcm(x,y)
</table></center>



