!!documentation.proc :
!! Adds documentation links in wims_rm_0 for navigation menus

!!!if $wims_user=$empty
!! open in a new page target=wims_help
 !set wims_rm_0 = $wims_rm_0\
whelp,4,module=help/main,help
!!!endif
!if $lang=fr
    !set wims_rm_0 = $wims_rm_0\
dochelp,1,cmd=new&module=home&search_keywords=wimshelp&search_category=A&search_lang=fr#searchform\
faq,1,module=help/teacher/faq
!endif

!set wims_rm_0 = $wims_rm_0\
doctec,1,module=help/wimsdoc
