!set wims_tail_home=!append line pref,1,module=adm/light&phtml=useropts.phtml.$lang\
forum,1,module=adm/forum/forum\
to $wims_tail_home

!if $wims_theme_icon!= and $wims_theme_icon!=default
   !set  wims_tail_home=$wims_tail_home\
iconabout,1,module=adm/light&phtml=iconabout.phtml
!endif
!set  wims_tail_home=$wims_tail_home\
cgu,1,module=adm/light&phtml=cgu.phtml

!set wims_tail_home_n0=!linecnt $wims_tail_home
