:signification
 Met les champs des types de réponses  <tt class="wims_code_words">dragfill</tt> ou <tt class="wims_code_words">clickfill</tt> dans une grande image. 
 Doit être utilisé dans le <tt class="wims_code_words">statement</tt> d'un exercice OEF. 
 <p>Avec l'option <tt class="wims_code_words">transparent</tt> dans le type de réponse,
 le champ à remplir est transparent et ne cache pas l'image.
 </p>
:example
 <span class="wims_help_example">Exemple</span>
 
 <pre>
\special{imagefill \imagedir/myphoto.jpg,450x350,40x40
reply 1,120x250
reply 3,300x50
reply 4,10x15
}
</pre>
 Dans cet exemple, on affiche une grande image (<tt class="wims_fname">\imagedir/myphoto.jpg</tt>) dans l'énoncé
 de type 450x350, avec 3 champs de réponse de type drag-and-drop de type 40x40. Les trois champs sont
 respectivement les réponses 1, 3 et 4 (qui doivent être de type <tt class="wims_code_words">clickfill</tt> ou
 <tt class="wims_code_words">dragfill</tt>), aux positions respectives 120x250, 300x50, 10x15 dans la grande image.
 
 <p> 
 La grande image sera redimensionnée à la taille spécifiée.
 </p>
 <p> Il est possible d'avoir des réponses multiples. 
 Ajouter un troisième paramètre entier à la taille :
 <tt class="wims_code_words">reply1,120x250x4</tt> montrera un champ de longueur 4 ( x 120).
 </p>