<script type="text/javascript" src="scripts/js/wz_tooltip.js"></script>
:signification
crée une aide popup (tooltip) : le premier paramètre est le texte du lien,
le troisième paramètre est le texte apparaissant dans l'aide popup. 
le second paramètre est l'option entre crochets: 
Entre les crochets, vous pouvez mettre l'option comme dans
la documentation de wz_tooltip.js. 
Par défaut : [FONTSIZE, '12pt', ABOVE, 'true']
Si vous voulez ne charger qu'une seule fois le javascript (une fois est suffisant pour une page
html), ne mettez aucun paramètre.  Si vous ne voulez pas charger le javascript
car il a été déjà chargé dans la page html, ajoutez <tt>nojs</tt>
au second paramètre
Vous pouvez configurer le style css du lien : class <tt> span.tooltip</tt>.


:example
<span class="wims_help_example">Exemple</span>

<pre>
\special{tooltip passer la souris ici, ,le mot a 5 lettres}
\special{tooltip passer la souris ici,[DURATION, 4000, FONTSIZE, '18pt'], le mot a 5 lettres}
\special{tooltip passer la souris ici,[TITLE, 'Some Title', PADDING, 9],un texte}
\special{tooltip }
\special{tooltip\special{tooltip passer la souris ici,nojs [TITLE, 'Some Title', PADDING, 9],un texte}
</pre>

:option
Les options possibles sont (from www.walterzorn.com)
 <embed>
!read js/tooltip_doc.html
</embed>