
Za vstop na desko <b><font
color=green>$mb_title</font></b>
kot <em>registrirani uporabnik</em> vnesite svoje uporabni¹ko ime in geslo.

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.en">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value="$forum">
<center><table border=0>
 <tr><td>Uporabni¹ko ime: <td><input size=20 name=fuser>
 <tr><td>Geslo: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="Potrdi">
</center>
</form>

