!if robot isin $session
 !exit
!endif

!header
!distribute line Seznam desk sporoèil\
	Vstop skrbnika\
	Vstop uporabnika\
	Novi uporabniki\
	into n_list,n_authowner,n_authuser,n_register

<center><h3>--- $(n_$type) ---</h3></center>
!if $error!=$empty
 !read msg.phtml
!else
 !read $type.phtml
!endif
<p><center>
!for t in list
 !if $t!=$type
  !href module=$module&type=$t $(n_$t)
&nbsp;&nbsp;
 !endif
!next t
!!href target=wims_help module=help/main&chapter=3 Pojasnila
</center>

!tail

