
!if $error!=$empty
 !read docu/msg.phtml
 <p><hr> <p>
!endif

!if $doccnt<1
 !if $wims_class!=$empty and $wims_user!=supervisor
  $name_home_warning
 !else
  !if $authoring=$empty
   $name_nodocument1
  !else
   $name_nodocument2
  !endif
 !endif
!else
 !if $ii>0
  !read scripts/table.phtml
 !else
  !if $wims_class!=$empty
   $name_listdoc1
  !else
   $name_listdoc2
  !endif
  <ul>
  !for t=1 to $doccnt
   !set s_=!line $t of $slist
   !set t_=!line $t of $tlist
   !set a_=!line $t of $alist
   !set t_=!trim $t_
   !default t_=$n_notitle
   <li>
   !href module=$module&cmd=reply&job=read&doc=$s_&block=main $t_
   !if $wims_ismanager=2
    &nbsp;
    !href cmd=reply&job=erase&doc=$s_ $wims_name_erase
&nbsp;
   !endif
   <small>$n_by $a_</small>
  !next t
  </ul>
 !endif
!endif

!if $wims_class=$empty and $wims_ismanager<2
 !form reply
 $name_listauthor:
 <input size=20 name=authoring value="$authoring">
 <input type=submit value="$wims_name_tosave">
 </form> <p>
!endif

!if $wims_ismanager<2 and ($wims_class=$empty or $wims_user=supervisor)
  !set wims_menu_items=!append line createdoc,1, cmd=reply&job=creat\
doctry,1,cmd=reply&job=auth2&doc=$draftd&block=main&coder=dddd\
  to $wims_menu_items
!endif

!tail

