
<h1 class="wims_docu_title">$tit
!if $editable=yes
 </b><font size="-1">[
 !if $block=main
  !href cmd=reply&job=prop $n_properties
  ] [
  !href cmd=reply&job=erase $n_erase
 !else
  !href cmd=reply&job=list $n_otherblocks
 !endif
 ]</font>
!endif
</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 Le bloc <tt>$block</tt> de ce document n'est pas encore créé.
 !if $editable=yes
  !href cmd=reply&job=edit&block=$block $n_create2.
.
 !endif
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Cette page n'est pas encore ouverte à la lecture. Revenez plus tard !
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Cette page est périmée. Vous ne pouvez plus la lire. Désolé !
 <p>
 !exit
!endif

<h3>$titb
!if $editable=yes
 </b><font size="-1">[
 !href cmd=reply&job=edit&doc=$doc&block=$block $n_edit
 ]</font>
!endif
</h3>

!read $docdir/$doc/$block.def content


