
Works in virtual classes are organized in worksheets.
<p>
Each virtual class can have up to 64 worksheets, and each worksheet can
contain up to 64 work items. A work item can be any Wims module: exercise,
tool, or other.
<p>
Each worksheet has a status. The status of a newly created worksheet is
<em>under preparation</em>, which allows work items be added and modified.
This is the only status under which the worksheet can be deleted. A
worksheet under preparation is only visible by the supervisor.
<p>
When the supervisor activates a worksheet under preparation, the sheet
becomes <em>active</em>. It can no longer be modified or deleted, and 
participants will be able to work on it.
<p>
Each worksheet has an expiration date. Passing this date, it becomes 
<em>expired</em>, in which case participants will continue to see it and be
able to work on it, but no score will be registered.
<p>
And an expired sheet can become <em>hidden</em>, in which case participants
no longer see it (but it is always visible to the supervisor).
<p>
The supervisor can manually switch a worksheet between <em>active</em>,
<em>expire</em> and <em>hidden</em> (in any direction).

