!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=group of classes
    !set name_sup=teacher
   !else
    !set name_classe=institution
    !set name_sup=supervisor
   !endif
     !set name_classes= the $name_classe
     !set name_classess= a $name_classe
     !set name_classesss= of a $name_classe
     !set name_classessss= The $name_classe
 !else
   !set name_classe=class
   !set name_classes=the $name_classe
   !set name_classess=a $name_classe
   !set name_classesss= of the $name_classe
   !set name_classessss= the $name_classe
   !set name_sup=teacher
 !endif

 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of class,course
   !set Name_level= !item $splevel of Level,Class,Course
   !set Name_levels= !item $splevel of Levels,Classes,Courses
   !set sousclasses_else=!item $splevel of or a class, or a course
   !set name_level_else= !item $splevel of a level,a class,a course
 !else
   !set sousclasses=sub-classes
   !set sousclasses_else=a class or an institution
 !endif
 
!set CL_Name	=Level,Class,Program,Course,Course interclasses,Test Zone
!set Name_program=Programs
!set name_program=program
!set name_portalandgroup=Institutions and class groups
!set name_independantclass=Independant classes

!distribute items Register,Anonymous,open,protected,Year,\
New participant,Registered,Connection Type,Up\
into name_register,name_anonymous,name_open,name_protected,name_year,\
name_new_participant,name_registered,name_connexion,name_up

!distribute line Vous n'avez pas de compte dans d'autres classes.\
  Search for your class\
  No class available.\
No class found corresponding to your search.\
You can directly change to\
into name_noaccount,name_searchclass,name_noavailable,name_nofound,name_direct

!let classification=Ecole,Collège,Lycée,Université,Autre

!set name_text1= Click on the name of a class to enter. Click on the name of the class to go \
to work in it (if you are registered participant of that class).\
<p>Click on the word `$name_register' to register to the class (you will\
need a class password for protected classes, which should be obtained from your teacher).

!set name_text2=To go to another $name_level_else $sousclasses_else, choose its name in the table below.
!set name_text3=Or choose $name_level_else $sousclasses_else name in the table below.

!set name_language=There is no English language classes on this site. Perhaps you are looking\
  for a class of another language
!set name_language2=This site does not yet contain any class in English language.
