
!read search.phtml
!if $clcnt+$sccnt<1 and $keyword!=$empty
 No class corresponds to your search. <p>
!endif

!if $wims_user!=$empty
 !read direct.phtml
 !if $wims_user!=supervisor and $supervisable!=yes
  !exit
 !endif
 <p>
!else
 Virtual classes allow teachers to organize the resources on the WIMS site
 (as well as eventually their own creations of exercise) for the work of
 their students, and to have a control on the progress of students.
 <p>
 If you don't have yet your own class: you may
 !href module=adm/class/regclass click here
 to create one after consulting the
 !href target=wims_help module=help/main&chapter=3 $wims_name_help
, or have a look at the
 !href module=$module&type=example example classes
. <p>
!endif

!if $overflow=yes
 !exit
!endif

!if $clcnt+$sccnt>0
 !if $wims_user=empty
  Otherwise, you may locate your class in the following table, and click on its
  name to get into it as supervisor.
 !endif
 !if $sccnt>0
  <p>
  $table_header
  <caption>Institutions and class groups</caption>
  $table_hdtr<th>Name</th> <th colspan=2>Teacher</th>
  <th colspan=2>Administrator</th> </tr>
  !for i=1 to $sccnt
   !set l=!line $i of $sclasses
   !distribute items $l into code,expire,in,cl,la,ty,lv,pswd
   !set supv=!item 9 of $l
   !default supv=!defof class_supervisor in wimshome/log/classes/$code/.def
   
   $table_tr
   <td align="center">
   $in
   </td>
   <td align=center>
   !href module=$module&type=authparticipant&class=$code $name_enter
   </td> <td align=center>
   !href module=adm/class/reguser&class=$code Register
   </td>
   <td align=center>$supv</td>
   <td align=center>
   !href module=$module&type=authsupervisor&class=$code $name_enter
  </td>
  !next i  
  $table_end
 !endif
 !if $clcnt>0 and $s_prog!=1
  <p>
  $table_header
  !if $superclass=$empty
   <caption>Independent classes</caption>
   $table_hdtr<th>Institution<th>Class<th>Supervisor
  !else
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
    !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
   !endif
    <caption>$Name_levels in $inst
    <small>
    !href cmd=help&special_parm=$module_language/structure [$wims_name_help]
    </small>
    !if $splevel>1
     !href cmd=reply&type=$type&superclass2=$sparent&s_prog=0 Up
    !endif
    </caption>
    $table_hdtr<th>$Name_level</th><th>Teacher</th>
    !if $superclass!=$empty and $stype=4
     <th>+</th>
     !if $ty!=1 and $splevel =1
      <th>+</th>
     !endif
    !endif
   !endif
   !for i=1 to $clcnt
     !set l=!line $i of $classes
     !distribute items $l into code,expire,in,cl,la,ty,lv,pswd
     !set supv=!item 9 of $l
     !default supv=!defof class_supervisor in wimshome/log/classes/$code/.def
   
     $table_tr
     !if $superclass=$empty
      <td align="center">$in<br>$cl</td>
     !else
      <td align="center">
      !href module=$module&type=authsupervisor&class=$code $cl
      </td>
     !endif
     <td align="center">$supv</td>
     !if $superclass!=$empty and $stype=4
      <td>
      !if $ty!=1
       !href cmd=reply&type=$type&superclass2=$code&s_prog=0 $sousclasses
      !else
      -
      !endif
      </td>
      !if $ty!=1 and $splevel =1
       <td>
       !href cmd=reply&type=$type&superclass2=$code&s_prog=1 $name_program
       </td>
      !endif
     !endif
     !if $superclass=$empty
      <td align=center>
      !href module=$module&type=authsupervisor&class=$code $name_enter
      </td>
     !endif   
    !next i
   $table_end
  !else
!!#####################program
   !if $clcnt_pr>0
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
    !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
   !endif
   $table_header
    <caption>$Name_program dans $inst
    !if $splevel>1
     !href cmd=reply&type=$type&superclass2=$sparent&s_prog=0 Up
    !endif
    </caption>
    $table_hdtr<th>$Name_level</th><th>Enseignant</th><th>+</th>
    !for i=1 to $clcnt_pr
     !set l=!line $i of $classes_pr
     !distribute items $l into code,expire,in,cl,la,ty,lv,pswd
     !set supv=!item 9 of $l
     !default supv=!defof class_supervisor in wimshome/log/classes/$code/.def  
     $table_tr
     <td align="center">
     !href module=$module&type=authsupervisor&class=$code $cl
     </td>
     <td align="center">$supv</td>
     !if $superclass!=$empty and $stype=4
      <td>
      !if $ty!=1
       !href cmd=reply&type=$type&superclass2=$code&s_prog=0 $sousclasses
      !else
       -
      !endif
     !endif
    !next i
    $table_end
   !endif
  !endif
!else
 !if $class_type=$empty and $superclass=$empty
  (This site does not yet contain any class in English language.)
 !else
   !if $clcnt=0
    (No class available.)
   !endif
 !endif
!endif
<p>

