!set proc=oef
!header

!if $wims_class=$empty
 Aquest mòdul és un mòdul intern d'una classe virtual. Com que tu no estàs
 connectat com a membre d'aquesta classe, no pots accedir-hi. Ho sento.
 <p><center>
 !href $ Tornar a WIMS
 </center> <p>
 !exit
!endif

Aquest mòdul conté els exercicis interactius corresponents a la classe <font
color=blue>$wims_classname</font> de <font
color=blue>$wims_institutionname</font>.
!if $wims_user=supervisor
 !href module=adm/createxo Clica ací per crear un altre exercici.
!endif

!read oef/intromenu.phtml
!tail

