
!if $class_defined!=yes
 <b>Fout</b>. 
 Je probeert in te loggen in een klas die niet bestaat. Probeer het nog eens een keer...
 !exit
!endif

Om in de klas <b><font color="green">$class_description</font></b> van
<b><font color="green">$class_institution</font></b> als een
geregistreerde deelnemer te komen, vul dan hier je login naam en wachtwoord in.

!!!##language independant 
<p>
!set wims_form_method=post
!form reply
<center><table border="0" summary="">
 <tr><td>$wims_name_Login</td><td><input size=20 name=auth_user value="$auth_user"></td></tr>
 <tr><td>$wims_name_Password</td><td><input type=password size=20 name=auth_password></td></tr>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register
