
!if $class_defined!=yes
 <b>Fout</b>.<br>
 U probeert in te loggen in $name_classes , maar deze klas bestaat helaas niet...<br>
 Controleer uw verzoek.
 !exit
!endif

Om in $name_classes <b><font color="green">$class_description</font></b> van
<b><font color="green">$class_institution</font></b> als de
<em>$name_sup</em> in te loggen, voer hier het $name_sup wachtwoord in.


<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 $wims_name_Password ($name_sup)  <input type=password size=20 name=auth_password>
<p>
<input type=submit value="$wims_name_Enter">
</center>
</form>

