
!if $directcnt>0
 U kunt direct overstappen naar:<ul>
 !for cl in $directlist
  !distribute words $cl into c_,u_
  !set n_=!defof class_institution, class_description in\
	wimshome/log/classes/$c_/.def
  <li>
  !if $u_=supervisor
   !set t_=supervisor
  !else
   !set t_=$type
  !endif
  !href cmd=reply&type=auth$t_&class=$c_&auth_user=$u_ $n_
  (<tt>$u_</tt>)
 !next cl
 </ul>
 <p><hr> <p>
 !if $wims_user=supervisor
  Of kies $name_level_else $sousclasses_else in de onderstaande tabel.
 !endif
!else
 !if $wims_user=supervisor
  Om over te stappen naar $name_level_else $sousclasses_else , kies dan de naam uit de onderstaande tabel .
 !else
 U hebt geen toegangsrechten toT andere afdelingen of klassen.
 !endif
!endif

