!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=groep klassen
    !set name_sup=administrator
    !set name_classes= de $name_classe
    !set name_classesss= van de $name_classe
    !set name_classessss= De $name_classe
   !else
    !set name_classe=instituut
    !set name_sup=administrator
    !set name_classes= het $name_classe
    !set name_classesss= van het $name_classe
    !set name_classessss= Het $name_classe
   !endif
   !set name_classess= een $name_classe
 !else
   !set name_classe=klas
   !set name_classes=de $name_classe
   !set name_classess=een $name_classe
   !set name_classesss= van de $name_classe
   !set name_classessss= De $name_classe
   !set name_sup=docent
 !endif
 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of klas,cursus
   !set Name_level= !item $splevel of Niveau,Klas,Cursus
   !set Name_levels= !item $splevel of Niveaus,Klassen,Cursussen
   !set sousclasses_else=!item $splevel of &bnsp;of een klas,&nbsp;of een cursus
   !set name_level_else= !item $splevel of een niveau,een klas,een cursus
 !else
   !set sousclasses=sub-klassen
   !set sousclasses_else=een klas of een instituut
 !endif

!set CL_Name	=Niveau,Klas,Programma,Cursus,Cursus,Portaal,Test Zone
!set Name_program=Programma
!set name_program=programma
 

