!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=een groep klassen
    !set name_sup=administrator
    !set name_classes= $name_classe
    !set name_classesss= van $name_classe
    !set name_classessss= De $name_classe
   !else
    !set name_classe=instituut
    !set name_sup=administrator
    !set name_classes= van een $name_classe
    !set name_classesss= van de $name_classe
    !set name_classessss= Van de$name_classe
   !endif
   !set name_classess= een $name_classe
 !else
   !set name_classe=klas
   !set name_classes=de $name_classe
   !set name_classess=een $name_classe
   !set name_classesss=van een $name_classe
   !set name_classessss=de $name_classe
   !set name_sup=docent
 !endif
 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of klas,cursus
   !set Name_level= !item $splevel of Niveau,Klas,Cursus
   !set Name_levels= !item $splevel of Niveau's,Klassen,Cursussen
   !set sousclasses_else=!item $splevel of van een klas, van een kursus
   !set name_level_else= !item $splevel of een niveau,een klas,een kursus
 !else
   !set sousclasses=sub-klassen
   !set sousclasses_else=een klas of een instituut 
 !endif
 


