
<center><h3>Stop sharing
</b><small>
!href cmd=help&special_parm=stopshare Help
</small>
</h3></center>

!if $stoprec!=$empty and $(sharing_$stoprec)=$nei and \
	$(me_$(stoprec)cnt)>0 and $me_testcnt>0 and confirm!=yes and \
	$stoprec isitemof $nosharelist
 <b>ATTENTION</b>. Your class has active score register, and the shared
 resources are not empty. If you stop this sharing now, you 
 cannot share them back again later.
 <p>
 Are you sure you want to definitely stop this sharing?
 <p><center><font size="+1"> 
 !href cmd=reply&stoprec=$stoprec&confirm=yes Yes; stop it.
 &nbsp;&nbsp;
 !href cmd=reply&job2=def No; leave it.
 </font></center> <p>
!else
 Manipulation error: You should never land here.
!endif

