
$table_header
<caption>Valid participant data fields</caption>
$table_hdtr<th>Name</th><th>Meaning</th>
$table_tr<td>login</td><td>login name of the participant</td></tr>
!if $special_parm!=upload
$table_tr<td>name</td><td>last name and first name (in that order, two columns)</td></tr>
!endif
$table_tr<td>lastname</td><td>family name</td></tr>
$table_tr<td>firstname</td><td>first (given) name</td></tr>
$table_tr<td>password</td><td>password of the participant, download always in
	special crypted form, but can be uploaded uncrypted.</td></tr>
$table_tr<td>email</td><td>email address</td></tr>
$table_tr<td>regnum</td><td>registration number</td></tr>
$table_tr<td>photourl</td><td>URL d'une photo</td></tr>
$table_tr<td>comments</td><td>comments about the participant</td></tr>
!if $special_parm!=upload
$table_tr<td>allscore</td><td>all scores and averages</td></tr>
$table_tr<td>averages</td><td>average score (server score and manual grades)</td></tr>
$table_tr<td>average1</td><td>average of server-attributed scores</td></tr>
$table_tr<td>average2</td><td>average of teacher-attributed grades</td></tr>
$table_tr<td>sheets</td><td>scores of all worksheets (one by one)</td></tr>
$table_tr<td>sheet1,sheet2,...</td><td>score of worksheet 1, worksheet 2, ...</td></tr>
$table_tr<td>exams</td><td>scores of all exams</td></tr>
$table_tr<td>exam1,exam2,...</td><td>scores of exam 1, exam 2, ...</td></tr>
$table_tr<td>manuals</td><td>all manual grades (one by one)</td></tr>
!else
$table_tr<td>participate (dans le cas du portail d'un établissement uniquement, 
réservé à son administrateur)</td><td>numéro des classes 
auxquelles est inscrit le participant sous la forme abcdefg/1/101
où abcdefg est le numéro du portail. S'il y a plusieurs classes, les séparer par des espaces.</td></tr>
!endif
$table_tr<td>manual1,manual2,...<td>manual grade 1, 2, ...
$table_tr<td>var_xxx</td><td>technical variable <tt>xxx</tt></td></tr>

$table_end <p>

Unrecognized fields will be ignored.  Les variables techniques peuvent être utilisées pour limiter
de manière sélective la durée d'ouverture de feuilles d'exercices ou d'examens.
<p>
!if $special_parm=upload
Dans le cas du champ <tt>participate</tt>, il est possible de rajouter des classes mais pas d'en enlever.
!endif

