
$table_header
<caption>Valid participant data fields</caption>
$table_hdtr<th>Name<th>Meaning
$table_tr<td>login<td>login name of the participant
!if $special_parm!=upload
$table_tr<td>name<td>last name and first name (in that order, two columns)
!endif
$table_tr<td>lastname<td>family name
$table_tr<td>firstname<td>first (given) name
$table_tr<td>password<td>password of the participant, download always in
	special crypted form, but can be uploaded uncrypted.
$table_tr<td>email<td>email address
$table_tr<td>regnum<td>registration number
$table_tr<td>comments<td>comments about the participant
!if $special_parm!=upload
$table_tr<td>allscore<td>all scores and averages
$table_tr<td>averages<td>average score (server score and manual grades)
$table_tr<td>average1<td>average of server-attributed scores
$table_tr<td>average2<td>average of teacher-attributed grades
$table_tr<td>sheets<td>scores of all worksheets (one by one)
$table_tr<td>sheet1,sheet2,...<td>score of worksheet 1, worksheet 2, ...
$table_tr<td>exams<td>scores of all exams
$table_tr<td>exam1,exam2,...<td>scores of exam 1, exam 2, ...
$table_tr<td>manuals<td>all manual grades (one by one)
!endif
$table_tr<td>manual1,manual2,...<td>manual grade 1, 2, ...
$table_tr<td>var_xxx</td><td>technical variable <tt>xxx</tt></td></tr>

$table_end <p>

Unrecognized fields will be ignored.  Les variables techniques peuvent être utilisées pour limiter
de manière sélective la durée d'ouverture de feuilles d'exercices ou d'examens.
