
<center><h3>Upload spreadsheet data</h3></center>

To send data from your spreadsheet into the class, save the data in a text
format (txt, csv, or tsv), then send the file to the server.
<p>
You can either send user information or grades to the class. To send user
information, the data must not contain any grades.
<p>
The first row of the table should be the names of each column. Valid column
names and their meanings are shown below. You may choose any combination of
columns and place them in any order, with the only condition that the field
`login' must be present (WIMS use this field to recognize individual
participant). If you want the server to ignore some rows, put a character
`#' into the `login' field.
<p>
You can use this method to add participants (many at once), but to do so,
your table must contain enough valid data for each participant to be added (first
name, last name, password).
<p>
If you add grade to the class, the latter must contain the corresponding
column. So if the grade column does not exist yet, create it first before
uploading data.
<p>
Un exemple de fichier valable pour l'inscription :
<pre>
login,firstname,lastname,password
toto,Claude,Toto,1234
</pre>
!read help/fieldtab.phtml
