
Il lavoro degli studenti in un corso virtuale è organizzato attraverso
test di autovalutazione.
<p>
Ogni corso virtuale può avere fino a 64 test di autovalutazione, e ogni
test può contenere fino a 64 elementi. Ogni elemento può essere un qualsiasi
modulo WIMS: esercizi, strumenti o altro.
<p>
Ogni test di autovalutazione ha uno `stato'. Un test appena creato è
<em>in preparazione</em>, e in questa fase può essere modificato, possono
essere inseriti elementi. Questo è il solo stato in cui un test può
essere cancellato. Un test in preparazione è visibile solo al docente.
<p>
Quando il docente attiva il test, questo diventa <em>attivo</em>. A questo
punto non può essere più modificato o cancellato, e gli studenti possono
cominciare a lavorarci sopra.
<p>
Per ogni test viene indicata una data entro la quale deve essere completato. 
Dopo tale data il test diventa <em>terminato</em>, resta visibile
agli studenti che possono continuare a lavorarci sopra, ma non
avranno più la possibilità di ottenere un punteggio. 
<p>
Un test `terminato' può essere nascosco, in questo caso non sarà più visibile
agli studenti (ma sarà sempre visibile ai docenti).
<p>
Il docente può cambiare in ogni momento lo stato di un test da <em>attivo</em>
a <em>terminato</em> a <em>terminato+nascosto</em> (in ogni direzione).
<p>
&Egrave; anche possibile `disattivare' un test (ad esempio per poterlo
modificare), ma in questo caso tutti i punteggi ottenuti dagli studenti
vengono cancellati.
<p>I punteggi possono anche essere assegnati attraverso `esami'. A tal fine 
è possibile predisporre dei veri e propri temi d'esame, costituiti da una
selezione degli esercizi presenti nei test di autovalutazione.
