
Free service provided by Wims on the Internet comes 
with no guarantee of whatever kind.

<p>The server program is subjet to
<a href=COPYING target=wims_external>GNU General Public Licence</a>. 
Its source code is available from http download at the address 
<p><center><tt>
<a href=http://wims.unice.fr/download/wims>http://wims.unice.fr/download/wims</a>
</center> <p></tt>
&copy; 1997-2000- Author of the server program:
!mailurl xiao@unice.fr XIAO, Gang\
WIMS
of <a href=http://www.unice.fr>Université de Nice - Sophia Antipolis</a>.
<br>To get the bleeding edge version use:
<tt>svn checkout http://subversion.cru.fr/wimsdev</tt>

<p>Each wims module has its own copyright policy, which may differ
from that of the server program. Please refer to appropriate pages of the
individual module for its policy.

<p>The source code of freely distributable modules are
available at the same ftp address as the server program.

<p>Some modules may use commercial softwares for their functionning. It is the
responsibility of the site maintainer to check with the software vendors
that such a use does not violate the licensing policy of the software, if he
wants to install that module on his server.


