
De belangrijkste activiteit van de WIMS server is: de interactieve oefening. 
<p>
Deze oefeningen zijn er in verschillende stijlen. Bijvoorbeeld,
!href target=wims_demo module=H5/geometry/gravshoot.en Gravity shoot
 vraagt je te klikken op een plaatje en geeft je een cijfer afhankelijk van de
 afstand tussen je click-coordinaten en de door de module berekende goede positie.<br> 
!href target=wims_demo module=H6/geometry/coincfree.en Coincidence Freehand
 geeft je een curve en vraagt je -nadat je diverse tests hebt kunnen uitvoeren,
 het functievoorschrift in te vullen.<br>
!href target=wims_demo module=U1/analysis/graphder.en Graphic derivative
 geeft je de grafiek van een functie en vraagt je de afgeleide van die functie te herkennen.<br>
!href target=wims_demo module=H6/analysis/scenarineq.en Scenario of inequalities 
 presents a step by step commented argument and asks you to find out 
erroneous steps.<br>
!href target=wims_demo module=H6/algebra/decrypt.en Decrypt
 geeft je een decodeerde boodschap, en laat je dit stap voor stap door verschillende 
 tests decoderen; enzovoorts
<p>
Er zijn zeer vele OEF (Open Exercise Format) verzamelingen; elke verzameling behandeld
een aantal meer traditionele oefeningen over een bepaald thema.<br>
U kunt ook een subset uit deze verzamelingen gebruiken om aan te werken.<br>
Docenten kunnen ook hun eigen OEF's direct online
!href module=$module&chapter=4&open=$open,4_oef#oef  maken.
 
<p>
De meeste interactieve oefeningen op de WIMS server zijn uiterst configureerbaar
voor wat betreft aantal opdrachten, moeilijkheidsgraad, beoordings-criteria enz.<br>
De configuratie verloopt via een speciale introductie-pagina, zodat een
eenmaal ingestelde set parameters gedurende de gehele oefening constant blijft. 
<p>
Dit is erg belangrijk omdat digitale WIMS oefeningen erg random zijn. U kunt
keer op keer dezelfde oefening opvragen en toch steeds een som verwachten met andere
getallen of zelfs andere onderwerpen.<br>
Dit betekent enerzijds dat een leerling zeer vaak met een bepaal probleemgebied kan oefenen,
 zonder dat de opdracht erg saai wordt, anderzijds dat leeringen niet bij elkaar op het beeldscherm 
 kunnen spieken; omdat iedereen een andere opdracht krijgt 
<p>

Wanneer een oefening wordt beeindigd, geeft de WIMS server een cijfer.
Afhankelijk van de kwaliteit een 0 voor niets goed, tot een 10 voor alles goed.
Wanneer U bent ingelogd als een leerling van een virtuele klas, dan wordt dit 
cijfer geregistreerd op de server.
De server verwerkt deze cijfers en kan ze op diverse manieren presenteren
<p>
Opmerking: sommige oefeningen bestaan uit bundels van meerdere opdrachten. 
Een cijfer wordt dan pas aan het einde van de totale sessie gegeven, en niet na elke deel-vraag.
Het aantal vragen is instelbaar op de eerder genoemde introductie-pagina.  



