
WIMS (WWW Interactieve Multipurpose Server)
geeft je de mogelijkheid om via het Internet/Intranet interactief aan wiskunde te werken.
<p>
In tegenstelling tot de meeste op Java of Javascript gebaseerde 
interactieve pagina's op het internet, verwerkt WIMS uw opdracten op de server zelf.
Hierdoor kan kan de WIMS server voor jou diverse geavanceerde berekeningen uitvoeren.
<p>
Voor de normale gebruiker is WIMS een gewone web site, waarop je interactief lesmateriaal
kunt bestuderen, oefenen met interactieve opgaven, functieplotters en computeralgebra systemen kan raadplegen 
of zelfs wiskundige spelletjes kan spelen, door op knoppen, plaatjes of hyperlinks te klikken
<p>
Door te klikken met je muis stuur je een "verzoek" naar de server, deze berekend
je opdracht, en stuur je het resultaat terug. 
De berekeningen die WIMS door een simpele muisklik kan uitvoeren kunnen extreem krachig zijn. 
<p>
Soms wordt ook javascript of java applets ingezet.
<p>
De opbouw van WIMS is speciaal geschikt voor het onderwijs.
De server kan alle activiteiten van de individuele leerlingen volgen,
 rapporteren en zelfs op maat gemaakte lesprogramma's aanbieden. 

