Wanneer je met WIMS werkt, wordt je regelmatig verzocht een wiskundige formule in te typen.
<p>
Bij
!href module=H4/algebra/logaritme.nl&subject=11&taal=$lang&total_exos=3&usage=2 sommige modules  
</a>&nbsp;kun je gebruik maken van een speciale wiskunde invoer java-applet [jove-inria].
<p>
Bij andere modules moet de wiskunde via het toetsenbord worden ingevoerd.<br>
Wiskundige vergelijkingen worden op de normale Computer Algebra Systeem (CAS) manier ingevoerd:
zoals :<br>
<tt>3*x+5</tt> voor
!htmlmath 3x+5
, <tt>sin(pi*x)</tt> voor
!htmlmath sin(pi*x)
, <tt>y^3+1</tt> voor
!htmlmath y^3+1
, <tt>(x+1)/(y-1)</tt> voor
!set ins_align=middle
!instex $$$$ {x+1 \over y-1} $$$$
, etc.
<p>
Daarnaast beschikt WIMS over een syntax-checker, die veel gemaakte "fouten
en slordigheidjes" in wiskundige notaties kan corrigeren.<br>
Bijvoorbeeld, <tt>3x+5</tt>
wordt intern gelezen als  <tt>3*x+5</tt>, <tt>sin x</tt> wordt gecorrigererd naar
<tt>sin(x)</tt>, etc. 
We raden natuurlijk aan om gewoon "correcte" wiskunde in te voeren...
<p>
Hieronder staat een lijst van wiskundige functies en de schrijfwijze.
Deze functies worden door WIMS herkend wanneer ze in een zinvolle context staan.
(Sommige modules acepteren ook nog andere functies; raadpleeg de helppagina's van deze modules hiervoor.) 
<p>
!set x=x
U kunt $x vervangen door elke sub-uitdrukking in de volgende tabel. 
<p>
<center><table border=2 cellspacing=1 cellpadding=3 bgcolor="#d0e0c0">
<tr><th>functie<th>omschrijving<th>hoe in te typen
<tr>
<tr><td>$m_pi
    <td>alom bekende constante<td>
    <tt>pi</tt> of <tt>Pi</tt> of <tt>PI
<tr><td><i>e</i><td>basis van de natuurlijke logaritme<td>
    <tt>e</tt> or <tt>E</tt>
<tr>
<tr><td>|$x|<td>absolute waarde van $x<td><tt>abs(x)
<tr><td>sign($x)<td>het teken van $x:
       <br>&nbsp;=-1 als $x&lt;0<br>&nbsp;=0 als $x=0<br>&nbsp;=1 als $x>0
       <td><tt>sign(x)
<tr><td>
    !instex $$ \sqrt x $$
    <td>de vierkantswortel van $x
    <td><tt>sqrt(x)</tt> or <tt>x^(1/2)
<tr><td>?<td>integer het dichtst bij $x<td><tt>rint(x)
<tr><td>?<td>grootste integer $m_le$x<td><tt>floor(x)
<tr><td>?<td>kleinste integer $m_ge$x<td><tt>ceil(x)
<tr>
<tr><td><i>e<sup>x</sup><td>exponentieel<td>
    <tt>exp(x)</tt> of <tt>e^x</tt> of <tt>E^x
<tr><td>ln($x)<td>natuurlijke logaritme<td><tt>log(x)</tt> of<tt>ln(x)
<tr><td>lg($x)<td>logaritme met grondgetal 10<td><tt>lg(x)</tt> of <tt>log10(x)
<tr>
<tr><td>sin($x)<td>goniometrische sinus<td><tt>sin(x)
<tr><td>cos($x)<td>goniometrische cosinus<td><tt>cos(x)
<tr><td>tg($x)<td>goniometrische tangens<td><tt>tan(x)</tt> of <tt>tg(x)
<tr><td>ctg($x)<td>goniometrische cotangens<td><tt>cotan(x)</tt> of <tt>ctg(x)
    </tt> <br> of <tt>cot(x)
<tr><td>arcsin($x)<td>inverse goniometrische<td><tt>asin(x)</tt> of
    <tt>arcsin(x)
<tr><td>arccos($x)<td>inverse goniometrische<td><tt>acos(x)</tt> of
    <tt>arccos(x)
<tr><td>arctg($x)<td>inverse goniometrische<td><tt>atan(x)</tt> of
    <tt>arctan(x)</tt> <br>of <tt>arctg(x)
<tr>
<tr><td>sh($x)<td>sinus hyperbolicus<td><tt>sh(x)</tt> of <tt>sinh(x)
<tr><td>ch($x)<td>cosinus hyperbolicus<td><tt>ch(x)</tt> of <tt>cosh(x)
<tr><td>th($x)<td>tangens hyperbolicus<td><tt>th(x)</tt> of <tt>tanh(x)
<tr><td>Argsh($x)<td>inverse hyperbolische<td><tt>asinh(x)</tt> of <tt>argsh(x)
    <br>of <tt>Argsh(x)
<tr><td>Argch($x)<td>inverse hyperbolische<td><tt>acosh(x)</tt> of <tt>argch(x)
    <br>of <tt>Argch(x)
<tr><td>Argth($x)<td>inverse hyperbolische<td><tt>atanh(x)</tt> of <tt>argth(x)
    <br>of <tt>Argth(x)
<tr><td>max(x,y)<td>Grootste van x en y<td><tt>max(x,y)
<tr><td>min(x,y)<td>Kleinste van x en y<td><tt>min(x,y)
<tr><td>gcd(x,y)<td>Grootste gemene deler<td><tt>gcd(x,y)
<tr><td>lcm(x,y)<td>Least Commun Multiple<td><tt>lcm(x,y)
</table></center>



