WIMS heeft verscheidene online wiskundige tools (berekeningen,grafieken),
voor diverse onderwerpen; van elementaire berekeningen en geanimeerde 2D/3D functieplotters
tot geavanceerde rekenmachines voor zeer speciale onderwerpen.
<p>
U kunt
!href module=home&list=2#list2 hier klikken
 om een komplete lijst te zien an alle online hlpmiddelen op deze site, of 
!href module=home&list=9000 zoeken
 naar een speciaal onderwerp

