Op dit moment ondersteund WIMS een tweetal hoofdcategorien:

<ol>
<li><p>
!href module=$module&chapter=$chapter&open=$open,$(chapter)_exo#exo Interactieve oefeningen
 om, je wiskundige kennis te toetsen. 
 <p>

<li><p>
!href module=$module&chapter=$chapter&open=$open,$(chapter)_tool#tool tools
 om je wiskundige problemen te helpen oplossen

</ol> <p>

Er zijn ook enkele wiskundig georienteerde "spelletjes" beschikbaar.
<p>
Je kunt op deze site
!href module=home&list=9000 zoeken
 naar de onderwerpen die je interesseren.
<p>
Docenten kunnen 
!href module=$module&chapter=3 virtuele klassen
 oprichten om hun leerlingen interactief les- & oefenmateriaal aan te bieden.

