 <b>Ensemble de caractères.</b> (name: <tt class="wims_code_words">chset</tt>) <br>
 C'est une liste de caractères alpha-numériques où l'ordre n'a pas d'importance, ni majuscules-minuscules. <p>
 Il peut être utilisé pour faire des réponses à choix multiples, où le nombre
 de choix présenté doit être fixé, et où il peut y avoir plusieurs bons
 choix que l'utilisateur doit trouver tous.
 <p>
 Si le mot <tt class="wims_code_words">norepeat</tt> est présent dans l'option, la répétition d'un même
 caractère est ignoré par le comparateur.


