<b>Mots croisés.</b>
(nom : <tt class="wims_code_words">crossword</tt>)
<p>
Crée un mot croisé (mots fléchés) à partir d'une matrice de lettres ou de chiffres.
(un slib permettant de créer la matrice à partir des mots est prévu). 
</p>
La bonne réponse est formée de deux items : le premier item est une matrice entre crochets,
les coefficients vides correspondant aux cases noires : 
de la forme 
<pre>[c,i,n,q,,,,
,,,u,n,,,
,,,a,,,s,
,,,t,r,o,i,s
,,,r,,,x,
,,d,e,u,x,,]
</pre> 
Le deuxième item est formé des définitions des mots à chercher (sur chaque ligne, le premier item 
est le mot, le deuxième sa définition). Par exemple
<pre>[un,1 en lettres
deux,2 en lettres
trois,3 en lettres
quatre,4 en lettres
cinq,5 en lettres
six,6 en lettres]
</pre>

Exemple :<pre>\answer{}{[c,i,n,q,,,,
,,,u,n,,,
,,,a,,,s,
,,,t,r,o,i,s
,,,r,,,x,
,,d,e,u,x,,],[un,1 en lettres
deux,2 en lettres
trois,3 en lettres
quatre,4 en lettres
cinq,5 en lettres
six,6 en lettres]}{type=crossword}
</pre>

Les matrices peuvent être écrites avec des points virgules (sans retour à la ligne) :

<pre>
\answer{}{[c,i,n,q,,,,;,,,u,n,,,;,,,a,,,s,;,,,t,r,o,i,s;,,,r,,,x,;,,d,e,u,x,,],[un,1 en lettres;deux,2 en lettres;trois,3 en lettres;quatre,4 en lettres;cinq,5 en lettres;six,6 en lettres]}{type=crossword}</tt>
</pre>

En option, il est possible de préciser les couleurs de fond <tt class="wims_code_words">color=[orange,black,white]</tt> (défaut) : couleur des cases à remplir,
couleur des cases "noires", couleur de fond du numéro du mot, de demander que les définitions soient en popup (option <tt class="wims_code_words">tooltip</tt>),
que toutes les définitions s'affichent en même temps (option <tt class="wims_code_words">allhelp</tt>)

<pre>
\answer{}{....}{type=crossword}{option=color=[orange,black,white] allhelp}
</pre>