<b>Choix multiples contrôlables par l'auteur</b>: (noms : <span class="tt wims_code_words">checkbox</span>,
 <span class="tt wims_code_words">click</span>, <span class="tt wims_code_words">menu</span>, <span class="tt wims_code_words">radio</span>, 
 <span class="tt wims_code_words">mark</span>, <span class="tt wims_code_words">flashcard</span>, <span class="tt wims_code_words">multipleclick</span>)<br/>
 Ils peuvent être utilisés pour remplacer l'entrée standard de choix multiple
 (<span class="tt wims_code_words">\choice</span>), vous donnant plus de contrôle de son apparence. La bonne
 réponse doit contenir deux champs, séparés par un point-virgule
 <span class="tt wims_code_words">;</span>. Le second champ (après le point-virgule) est la liste de
 textes dans le choix, tandis que le premier est une liste de numéros de bons
 choix. 
 <p>
 Dans le cas de <span class="tt wims_code_words">checkbox</span>, <span class="tt wims_code_words">multipleclick</span> et 
 de <span class="tt wims_code_words">flashcard</span>, l'utilisateur doit choisir
 exactement tous les bons choix. Dans les autres cas, le choix de n'importe
 quel bon choix suffira.
 </p>
 Dans le cas de <span class="tt wims_code_words">flashcard</span>, la troisième ligne sera affichée sur chaque face cachée des 
 cartes. Par défaut, des points d'interrogation apparaissent. 
 
 <p>
 Le type <span class="tt wims_code_words">click</span> demande de cliquer sur un objet. Il ne peut 
 être utilisé que dans le cas où il n'y a pas
 d'autres réponses ou choix. 
 </p><p>
 Le type <span class="tt wims_code_words">multipleclick</span> permet de cliquer sur plusieurs objets (il ressemble 
 au type <span class="tt wims_code_words">mark</span>. Il peut donc être utilisé 
 lorsqu'il y a  plusieurs réponses possibles. Il dispose les choix dans un tableau si 
cela est indiqué dans le deuxième item de <span class="tt wims_code_words">\embed{}</span> : la première ligne
doit alors être la dimension du tableau et la deuxième le nombre de colonnes et de lignes : dans l'exemple
ci-dessous, les objets seront disposés dans un tableau ayant 8 colonnes et 3 lignes, les 8 premiers seront
dans l'ordre sur la première ligne, les 8 suivants dans la seconde ligne etc. 
Il est possible de rajouter sur la troisième ligne la liste des en-têtes des lignes et des colonnes du tableau sous la forme
<span class="tt wims_code_words">[nom_des_colonnes;nom_des_lignes]</span>. 
<pre> \embed{r1, 200,200
8 x 3
[a,b,c,d,e,f,g,h;1,2,3]}
</pre>
La classe css du tableau est <span class="tt wims_code_words">ans_multipleclik</span>n (avec <span class="tt">n</span> le numéro de la question)
et peut être configurée pour l'exercice dans le champ <span class="tt wims_code_words">\css{ }</span>. 
 

 <p>
 Pour les types <span class="tt wims_code_words">checkbox</span>, <span class="tt wims_code_words">menu</span>, 
 <span class="tt wims_code_words">radio</span> et <span class="tt wims_code_words">flashcard</span>, une option
 <span class="tt wims_code_words">shuffle</span> peut être ajoutée, qui a pour effet de permuter
 aléatoirement l'ordre des items dans les choix multiples proposés aux élèves.

 La permutation aléatoire automatique n'est pas appliquée en l'absence de l'option
 <span class="tt wims_code_words">shuffle</span> et le nombre de choix n'est pas limité.
 Pour un effet contraire, le mot d'option <span class="tt wims_code_words">sort</span> a pour effet de montrer les choix
dans l'ordre alphabétique.
</p>
 Le type <span class="tt wims_code_words">menu</span> accepte une option <span class="tt wims_code_words">multiple</span> avec valeur. La
 valeur de cette option donne la taille maximale (par défaut 8) de la fenêtre
 de choix. Par exemple, <span class="tt wims_code_words">multiple=5</span> donne une fenêtre de menu multiple
 jusqu'à 5 lignes.
 <p>
 Dans le cas de <span class="tt wims_code_words">mark</span>, l'utilisateur doit choisir
 tous les bons choix  comme <span class="tt wims_code_words">checkbox</span>, avec la différence qu'au
 lieu d'un bouton, c'est l'article choisi qui change la couleur pour indiquer
 le choix. Il est principalement destiné à une utilisation dans le texte de 
 l'énoncé. Ainsi, un même choix peut intervenir plusieurs fois et 
 il est alors tenu compte de sa position dans le texte. Lors de l'analyse de
 la réponse, les bonnes réponses sont coloriées en vert, 
 les mauvaises en rouge et les réponses oubliées en bleu. 
 Un exemple d'utilisation possible : cliquez sur tous les articles 
 définis de la phrase suivante ... 
 <p>
 Dans le cas de <span class="tt wims_code_words">flashcard</span>, les choix (cartes) sont cachés et les bons choix 
 doivent être retournés. L'option <span class="tt wims_code_words">show</span> permet de voir les cartes. Les bons
 choix doivent être retournés (face cachée). 
 Le nombre de clicks sur chaque carte est renvoyé dans 
 la deuxième ligne de la variable <span class="tt wims_code_words">\reply</span>n. 
 
 <p>
 Pour des types qui acceptent la saisie de plusieurs choix (<span class="tt wims_code_words">checkbox</span>,
 <span class="tt wims_code_words">mark</span>, <span class="tt wims_code_words">multipleclick</span> ainsi que <span class="tt wims_code_words">menu</span> 
 avec l'option <span class="tt wims_code_words">multiple</span>),
 par défaut l'élève aura un zéro dès que sa réponse ne s'accorde pas
 exactement à la bonne réponse donnée. Si vous voulez donner une note
 partielle à une réponse partiellement correcte, ajoutez le mot d'option
 <span class="tt wims_code_words">split</span> (synonyme&nbsp;: <span class="tt wims_code_words">partialscore</span>). Dans ce cas, 
 la note partielle sera calculée selon la proportion des bons choix
 repérés par l'élève. Par contre, si de mauvais choix sont aussi
 pris, chaque mauvaise réponse compense deux bons choix jusqu'à ce que
 la note atteigne 0. Une telle politique est nécessaire, entre autres,
 pour dissuader des gens de prendre tous les choix disponibles dans
 le cas où beaucoup d'entre eux sont bons.
Bien que cette formule doit bien fonctionner dans la plupart des situations,
 vous pouvez quand même ajouter un mot d'option <span class="tt wims_code_words">eqweight</span> si ce
 n'est pas votre cas. Ce mot force le calcul à prendre le même poids
 positivement et négativement, c'est-à-dire que tout mauvais choix compense
 un bon choix. Mais vous devez savoir que cette politique en
 apparence juste peut conduire à des effets pervers&nbsp;!

<p>
Dans le cas d'utilisation de la commande <span class="tt wims_code_words">\embed</span>, il est possible de placer
précisément le k-ème item  en écrivant <span class="tt wims_code_words">\embed{r</span>n<span class="tt wims_code_words">,k}</span>
avec <span class="tt wims_code_words">n</span> le numéro de la question (sauf pour <span class="tt wims_code_words">multipleclick</span>). 
<span class="wims_warning">$wims_name_warning</span> : cela est obligatoire dans le cas de 
<span class="tt wims_code_words">flashcard</span> ; on peut alors (pour <span class="tt wims_code_words">flashcard</span>)
préciser sur les deux lignes suivantes le style css des cartes (style associé à la balise div)
(il doit être le même pour chaque carte, dans le cas de style différent, c'est le dernier placé
qui est utilisé dans la réponse).
Par exemple,
<pre>
\embed{r1,4
style="display:inline-block;min-width:30px;min-height:30px;padding-top:10px;padding-bottom:5px;background-color:red;"
style="display:inline-block;min-width:30px;min-height:30px;padding-top:10px;padding-bottom:5px;background-color:blue;"
}
</pre>
