 <b>Nombre.</b> (nom: <tt class="wims_code_words">numeric</tt>)<br>
 Comparaison de nombres réels avec la précision définie par l'auteur.
 
 Si le mot <tt class="wims_code_words">comma</tt> est présent dans l'option, l'écriture 
 des nombres décimaux avec une virgule décimale est acceptée 
 (mais la bonne réponse doit être un nombre avec le point décimal). Si la
 réponse est mauvaise, la bonne réponse est donnée avec le même "séparateur"
 décimal que celui donné par l'élève. 
 
 La précision peut être précisée dans le champ <tt class="wims_code_words">precision</tt>, 
 par défaut 1000.

L'erreur est par défaut relative : la différence doit être inférieure ou égal à
<tt>(good_answer+reply)/precision</tt> (remplacer <tt>precision</tt> by <tt>sqrt(precision)</tt>
pour une réponse partiellement bonne). 

Si le mot <tt class="wims_code_words">absolute</tt> est un mot d'option, la precision est absolue.
La réponse est alors partiellement bonne si la différence est inférieure à 
<tt>10/precision</tt>.


