
 <b>Ensemble fini (textuel, formel et approximatif).</b>
 (names: <span class="tt wims_code_words">set</span>, <span class="tt wims_code_words">fset</span> et <span class="tt wims_code_words">aset</span>)

 C'est une liste d'éléments séparés par des virgules dont l'ordre
 n'a pas d'importance.
 <p>
 Pour <span class="tt wims_code_words">set</span>, aucune évaluation n'est effectuée avant la
 comparaison (donc 2 et 1+1 ne sont pas pareils). Si le mot "repeat" 
 est présent dans l'option, les répétitions des éléments sont
 demandées comme dans la bonne réponse. 
 Sinon, la réponse est considérée comme partiellement bonne.

 <p>
 Pour <span class="tt wims_code_words">fset</span> les éléments sont évalués 
 en tant qu'<em>expressions formelles</em>.
 <p>
 Pour <span class="tt wims_code_words">aset</span>, les éléments sont évalués en tant
 qu'<em>expressions approximatives</em>.

