

!if $wims_read_parm!=badonly 
<p> 
Vous pouvez définir des synonymes dans la bonne réponse. Pour cela,
ajoutez simplement les synonymes derrière la bonne réponse (standard),
précédés de la barre verticale <span class="tt wims_code_words">|</span>. On peut définir un
nombre quelconque de synonymes.
</p>
!endif

<p>
De plus, si vous ne voulez pas que les réponses d'utilisateurs ayant
seulement quelques erreurs de frappe soient considérées comme fausses,
vous pouvez définir une liste de mots `significatifs'. C'est une liste
de mots à mettre dans le champ de `bonne réponse', après la
bonne réponse elle-même et les éventuels synonymes, et précédée d'un
point virgule <span class="tt wims_code_words">;</span>. Les signes de ponctuation seront ignorés
dans cette liste, et les mots sont aussi comparés avec le même niveau
de tolérance que pour les bonnes réponses.
</p><p> 
Lorsque les mots `significatifs' sont définis, les réponses de
l'utilisateur contenant un mot qui n'est pas dans cette liste seront
automatiquement renvoyées pour correction.
</p>
