
<b>Texte (sensible ou non à la casse : majuscules/minuscules).</b>
(noms : <tt class="wims_code_words">case</tt> et <tt class="wims_code_words">nocase</tt>)
<br>
La réponse est comparée comme texte à une bonne réponse donnée. Dans
le cas <tt class="wims_code_words">case</tt> (sensible à la casse), chaque mot de la réponse
doit être exactement le même que le mot correspondant de la bonne
réponse.
Les expressions du type e' sont transformées en é (réaccentuation). 
Pour l'éviter, utiliser l'option <tt class="wims_code_words">noreaccent</tt>. 

!read help/anstype.fr/syno.phtml

