<center>$classname
<h1>$cdt_title</h1>
<font size="+1">Ajouter/Modifier la compétence $comp</font></center> 

<p><hr width="40%"> <p>

!form reply
  <ul>
 <li>Informations sur cette compétence :

  <ul>
   <li>Titre de la compétence : <input size=50 name=cf_title value="$mem_title">.</li>
   <li>Nombre de paliers : 
    <select  name="cf_nbpalier" onchange="submit()">
    !for i=1 to $maxpalier
     !if $i=$mem_nbpalier
      <option value=$i selected>$i</option>
     !else
      <option value=$i>$i</option>
     !endif
    !next i
    </select>
   </li>
  </ul>
  <input type=submit name=cf_set value="Enregistrer le changement">
 </li>
 !for k=1 to $mem_nbpalier
  !let eold=!record $k of wimshome/log/classes/$wims_class/livret/.comp$comp
  !distribute line $eold into name,eold
  <li>Palier $k : <font color=green><b>$name</b></font><small> [
   !href cmd=reply&job=modpalier&comp=$comp&palier=$k Modifier
   ] </small>
   !if $eold!=
   <ul>
    !for l in $eold
     !let t=!replace internal . by , in $l
     <li> $l
      !line $(t[2]) of $(sheet$(t[1]))
     </li>
    !next l    
   </ul>
   !endif
  </li>
 !next k
</ul>
</form>
!set wims_menu_items=!append line back2,1,cmd=reply&job=home\
to $wims_menu_items

!reset cf_nbpalier
