!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$wims_name_config

<p><hr width="40%"> <p>

$name_param_change:

!form reply
<input type="hidden" name="job" value="config">
<ul>
 <li>$wims_name_title&nbsp;:<br>
  <input size="60" name="cf_title" value="$cf_title">
 <li>$wims_name_Description&nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>

 <li>$name_color: <br>
  <table><tr>
   !for k=1 to 11
    <td style="background-color: $(livret_color[$k])">&nbsp;$k&nbsp;</td>
   !next k
  </tr></table>
 !!<language>
  <br>Ces couleurs peuvent être modifiées dans le 
  !href module=adm/class/config&job=present panneau de configuration 
  de la classe.
!!</language>
 </li>
 <li>$name_score_modify: <br>
 !for i in $asheets
   <input type="checkbox" name="cf_nonactivesheet" value="$i"
  !if $i isitemof $cf_nonactivesheet
   checked
  !endif
  >
  !let t=!record $i of  wimshome/log/classes/$wims_class/sheets/.sheets
  $i :
  !line 3 of $t
  <br>
 !next i
 </li>
</ul>
<p><center><input type="submit" name="cf_set" value="$wims_name_tosave">
&nbsp;&nbsp;<input type="submit" name="cf_abandon" value="$wims_name_giveup">
</center></form>


!!set wims_menu_items=!append line cls_livret,1,cmd=reply&job=home\
!! to $wims_menu_items

!reset cf_nonactivesheet,cf_set,cf_title,cf_description
