!!##!! language independant
!if $job2=print and $job isitemof todo,work
 !changeto print$job.phtml
!endif

!header1
<script type="text/javascript" src="scripts/js/wz_tooltip.js" language="Javascript"></script>\


!!if link notin $job
!headmenu
!!endif



!if $error=bad_class
 !read msg.phtml $error
 !tail
 !exit
!endif

!read $job.phtml

!if $wims_user=supervisor
 !if config notin $job
  !set wims_menu_items=!append line config,1,cmd=renew&job=config to $wims_menu_items
 !endif
 !if userlist notin $job
  !set wims_menu_items=!append line cls_livret,1,cmd=renew&job=userlist to $wims_menu_items
 !endif
 !set wims_menu_items=!append line add_competence,1,cmd=renew&job=addcomp&comp=$[$livret_nbcomp+1] to $wims_menu_items
!endif
!set wims_menu_items=!append line refresh,1,cmd=reply\
,0,\
go_userlist,1,cmd=new&module=adm/class/userlist to $wims_menu_items

!endif

!!if link notin $job
!tail
!!endif

