!if $job2=print and $job isitemof todo,work
 !changeto print$job.phtml
!endif

!header1
<script type="text/javascript" src="scripts/js/wz_tooltip.js" language="Javascript"></script>\


!!if link notin $job
!headmenu
!!endif



!if $error=bad_class
 !read msg.phtml $error
 !tail
 !exit
!endif

!read $job.phtml

!if $wims_user=supervisor
!set wims_menu_tail=!append line config,1,cmd=renew&job=config\
add_competence,1,cmd=renew&job=addcomp&comp=$[$livret_nbcomp+1]\
refresh,1,cmd=reply\
to $wims_menu_tail
!! <p>
!! !href cmd=renew&job=config Configuration
!! &nbsp;
!! !href cmd=renew&job=addcomp&comp=$[$livret_nbcomp+1] Ajouter une compétence
!! &nbsp;
!! !href cmd=reply Rafraîchir cette page

!endif

!!if link notin $job
!tail
!!endif

