!!##!! language independant
!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$livret_title\
$name_job

!if $error!=$empty
 !read msg.phtml $error
 !exit
!endif

!if $livret_nbcomp==0
 $name_no_competence
 !exit
!endif
<p>
$table_header
 $table_hdtr
  <th>$name_competences / $name_n_paliers</th>
  !for j=1 to $maxnbpalier
   !let desc=!record $j of wimshome/log/classes/$wims_class/livret/.comps
   !let desc=!line 1 of $desc
   <th valign=middle><a onmouseover="Tip('$desc',$tooltip_parm)">$name_n_palier $j</a></th>
  !next j
 </tr>
 !for k=1 to $livret_nbcomp
  $table_tr
   <td>
    $(title_$k)
   </td>
   !for j=1 to $(nbpalier_$k)
    !let t=!charcnt $(l_$(k)_$(j))
    !if $t>1
     !let note=$[rint($(l_$(k)_$(j)))]
    !else
     !let note=&nbsp;
    !endif 
    <td align="center" style="background-color: $(livret_color[$note+1])">$note</td>
   !next j
  </tr>
 !next k 
$table_end

