
!if $ccnt=0
 !if $parent=class
 $name_course1
 !else
  $name_course2
 !endif
 !href cmd=reply&job=$parent $wims_name_back2
.
 !exit
!endif

!if $parent=class
 $name_course3
 $table_header
 $table_hdtr<th>$wims_name_title<th>$wims_name_comment
 !for p in $clist
  !set i_=!defof class_description in wimshome/log/classes/$p/.def
  $table_tr
  <td>
  !href cmd=reply&confirm=yes&courseclass=$class&courseprog=$p $i_
  <td>-
 !next p
 $table_end
 !exit
!endif

!if $parent=prog
$name_course4
 $table_header
 $table_hdtr<th>$wims_name_title<th>$wims_name_comment
 !for c in $clist
  !set i_=!defof class_description in wimshome/log/classes/$c/.def
  $table_tr
  <td>
  !href cmd=reply&confirm=yes&courseclass=$c&courseprog=$prog $i_
  <td>-
 !next c
 $table_end
 !exit
!endif

