
!set form_OK=发送修改后的属性
!set form_titlename=名称
!set form_caption=班级属性
!set title=$class_description
!set sup=$class_Supervisor
!read scripts/classform.phtml

<p>
!if $coursecnt=0
此班级尚无课程.
 !href cmd=reply&cparent=class&job=addcourse 添加课程
.<sup>
 !href cmd=help&special_parm=structure#course 帮助
</sup>
!else
 $table_header
 <caption>此班内已有课程<sup>
 !href cmd=help&special_parm=structure#course 帮助
 </sup>
 !href cmd=reply&cparent=class&job=addcourse 添加别的课程
 </small></caption>
 $table_hdtr
 <th>代码<th>名称</th><th>-</th><th>负责人</th>
 </tr>
 !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into l_,s_,t_,n_
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=course&cparent=class&course=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=delcourse&cparent=class&del=$l_ 删除
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $s_
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
   不可用
   !endif
 !next i
 $table_end

!endif

!reset title

