
!read adm/title.phtml 3\
$name_delprogram0 <em>$class_description</em>

!if $class_recshare=main
本计划不能删除, 因为它的资源被其它课程共享.
 !href cmd=reply&job=$job $wims_name_giveup
 !exit
!endif

<font color=red><b>警告</b>.</font> 本操作不可逆转!
此计划的<font color=red>所有内容</font>: 课程, 活动, 分数等将被
<font color=red>彻底</font>删除!
<p>
你肯定要删除此班级?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level $wims_name_no
</font></center> <p>

