
<p><center><h3>另一计划的共享资源</h3></center>

你的计划将要共享年级 <em>$other_level</em> 的计划 <em>$other_description</em> 
的所有教学资源(练习, 作业页, 考试, 文件, 投票).
也就是说, 一个计划对资源的修改会引起所有共享计划的相同修改.

<p> <b>警告</b>. 这个实验性的操作将会删除你的计划里所有现存的教学资源,
而且是<b>不可逆转的</b>! 你不能中断资源共享, 资源共享的计划也不能删除!

<p>
你肯定要继续吗?

<p><center><font size=+1>

!href cmd=reply&job=$job&prog=$prog&shareprog=$shareprog&confirm=yes 是
&nbsp;&nbsp;
!href cmd=reply&job=prog&prog=$prog 不

</font></center> <p>



