
<h3><center>Convenio de encaminamiento de los módulos</center></h3>

Los módulos de actividad deben tener una dirección del tipo
<font color=green><tt>Zona/categoría/nombre.lang</tt></font>.
Cuando el módulo está en desarrollo, esta dirección se traduce por
<font color=green><tt>Zona~categoria~nombre.lang</tt></font>
.

<ul>
<li><p>Zona: debe ser una de las zonas declaradas del sistema.
Entre ellas, las con una carta capital seguida de una cifra
corresponden a niveles académicos,
<font color=blue><tt>Lang</tt></font>
contiene módulos de aprendizaje de lenguas,
<font color=blue><tt>tool</tt></font>
contiene herramientas en línea, los módulos de,
<font color=blue><tt>local</tt></font>
se encuentran solamente en el servidor local,
<font color=blue><tt>test</tt></font>
es una zona de prueba de módulos no publicables
en la cual pueden poner lo que quieren.

<li><p>categoría: puede ser una palabra de su elección,
pero cuando publican el módulo, sólo se aceptará
si la categoría es reconocida por el sistema.
<p>
Quiere consultar abajo la lista de las categorías de los módulos existentes.
En caso de duda, escriben al
!mailurl $sysadmin coordinador de la publicación
.

<li><p>name: una palabra de su elección, preferiblemente entre 4 y 12 caracteres
con prefijo obligatorio <tt> oef< /tt> si se trata de un módulo de ejercicios
OEF y <tt> doc.< /tt> si se trata de un documento.

<li><p>lang: El código de lengua del módulo, a dos cartas. Debe ser entre
las lenguas soportadas por el sitio (<font color=blue><tt>$wims_site_languages</tt></font>)
y debe corresponder a la lengua definida en el fichero ÍNDICE del módulo.
<p>

</ul>

<p>
Algunas categorías conocidas: (no exhaustivas)
!read wimshome/public_html/bases/sys/categories.phtml
