
<h3><center>Modificantes autorizados</center></h3>

Dé aquí el nombre de cuenta de las personas que autorizan
a modificar este módulo (fuera de usted).
<b> Atención< /b> ¡el derecho de modificación es eterno, sin posibilidad
de revocación!
<p> Esto afecta solamente a las publicaciones estables. Si transfieren
un módulo de otro autor para la publicación, DEBEN añadir el nombre
de cuenta de este último en este campo.

