
<h3><center>Publicación de un módulo</center></h3>

Si tienen una cuenta en el centro de publicación de los módulos $centralhost,
pueden publicar su módulo allí. Y pueden elegir hacer la publicación
como versión desarrollo o versión estable. En todos los casos,
esta publicación será visible en la dirección de carga a distancia
<a href=$downloadsite>$downloadsite</a>.
<p>
En caso de una publicación estable, va a propagarse automáticamente
a través de los espejos y las actualizaciones automáticas a todos
los servidores WIMS del mundo entero.
<p>
Pues deben tener muy cuidado de no publicar más que módulos bien probados.
Es especialmente el caso cuando modifican un módulo de ejercicios existentes.
<p>
Tenemos todos un deseo constante de mejorar nuestras obras:
una presentación aún más bonita, aún más capacidades
(o en el caso de un ejercicio, más casos), una reorganización del código, etc.
<p>
¡Pero no olvidan PENSAR EN la GENTE QUE UTILIZA SUS EJERCICIOS!
Su módulo quizá ya se inserta en hojas de trabajo activas y/o exámenes importantes.
Sus novedades introducen entonces modificaciones en medio del trabajo de la gente.
Las nuevas capacidades o presentaciones pueden perturbar a los alumnos; al peor,
un examen importante puede ser roto por un error.
Ni que decir que eso no ayudará a su reputación.
<p>
Por regla general, deben ustedes abstener de introducir modificaciones estéticas
o refuerzos a mediados de un año académico sobre los módulos activamente utilizados.
Sólo las correcciones de errores deben publicarse durante este período.
Desarrolle sus novedades en una versión de desarrollo (bajo una dirección prueba
o en una cuenta de desarrollo para este efecto) y no los publica
sino durante las vacaciones escolares.
<p>
Para sus utilizaciones personales o las de sus alumnos, les basta que vincule
sus hojas o exámenes sobre el módulo de su espacio de desarrollo.
Es por otra parte un buen medio de hacer probar los módulos antes de la publicación.
<p>
En todos los casos, sabe que para los módulos estables, pueden solamente
modificar los sobre los cuales tienen derechos. Si quieren añadir un NUEVO módulo estable,
su cuenta debe tener el derecho, o deben enviar el módulo a un
a "<a href=$(downloadsite)parrains>parrain</a>" y pedirle publicarlo para ustedes
(tendrán a continuación el derecho de modificación sobre este módulo).
