!read adm/title.phtml 2\
Búsqueda de los módulos por dirección

Las expresiones regulares se admiten en las búsquedas de módulos por direcciones.
Quiere consultar la página del manual de <tt> grep</tt> para más detalles.
<p>
Caracteres autorizados en las cadenas de investigación: cartas (sin acento), cifras,
más los símbolos siguientes&nbsp;:
<p><center>
	<tt>$searchsymbol</tt>
</center> <p>

Por razones de seguridad, todos los demás caracteres se suprimirán antes de la búsqueda.
