
<h3><center>Versión de WIMS de un módulo</center></h3>

WIMS es un sistema que evoluciona rápidamente. Se introducen algunas novedades
a cada nueva versión.
<p>
Si se desarrolla un módulo bajo una reciente versión de WIMS,
no podrá volver en un servidor de una versión previa,
ya que este último no tendrá las capacidades de hacerlo funcionar correctamente.
<p>
Por esta razón, WIMS se niega ahora a realizar un módulo que pide
un wims_version demasiado reciente.
<p>
Como su módulo $mod se desarrolla bajo WIMS-$wims_version,
está sin peligro declarar que pide la versión $wims_version de WIMS.
A menos que no utilizaron nada de nuevo desde una versión de WIMS más antigua,
en ese caso pueden utilizar esta versión.
¡Dicho esto, si se equivocan, la gente va a descubrir “errores” extraños en su módulo!


