
WIMS在设计时就是支持多语言的. 目前已有多种可用的语言.
<p>
为了使不懂计算机编程的人也能翻译, 已经作了许多努力.
但是由于系统内容庞大并且还在不断发展, 翻译的工作量是很大的.
<p>
另一方面, 由于WIMS的教育使命, 把它翻译成你的母语也是对你的国家年轻一代的贡献.
<p>
如果你对翻译WIMS到你的母语有兴趣, 请
!mailurl xiao@unice.fr 联系我
. 以下是我给`虚拟的'荷兰语翻译者的答复节录:

<pre>
首先我必须在WIMS的内核声明此语言.
此语言的扩展名是什么? (例如英语是'en', 法语是'fr', 中文是`cn',
意大利语是'it'等, 荷兰语是`nl'吗?) 我也需要小的国旗代表它.

为找到需翻译的文件, 有一个很简单的规律. 
凡是名字相同, 但扩展名同时有 .en 与 .fr 的, 就应创建相应的 .nl 的文件或目录.

为了找出应该翻译的行, 可以比较英语版与法语版(可使用diff).

有时法语版的文件只是到英语版的一个链接, 这时你只要把此链接复制到荷兰语版即可.

要翻译的文件都包含在目录 public_html 内. 
需翻译的系统文件主要在以下子目录里:

modules/adm, modules/home, modules/help, modules/template,
modules/classes, bases/sys, html, msg.

还有少数多语言文件需要修改, 增加荷兰语的内容(但这并非绝对必须):

html/module_about
modules/home/languages
modules/home/askcookie.phtml
scripts/about.phtml
scripts/related.phtml
scripts/tool.phtml

除了系统外, 你也可以翻译一些感兴趣的模块.

------------------------

你可以先把法语(或英语)的文件或目录复制改名成荷兰语版,
然后再逐步翻译. 作为例子, 起始页面都在 modules/home 内.

</pre>

