!readproc adm/docsheet.prep
!read $docdef content
<p><center>
El registro de las puntuaciones está
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   abierto, pero puede
   !href cmd=resume&job=suspend suspenderlo
.
  !else
   suspendido por usted mismo.
   !href cmd=resume&job=reopen Reactivarlo
.
  !endif
 !else
  cerrado para su conexión.
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc&job=edit&doc=$d_&block=$b_ $wims_name_Edit
.&nbsp;
 !href cmd=resume $wims_name_refresh
.
!endif
</center>

!tail

