<html><head>
$wims_html_header
</head>
<body $wims_htmlbody>
!headmenu
!read names.phtml

!if $job!=$empty
 !read $job.phtml
 !goto end
!endif

<center>$classname
<p>
<h1>Avviso
</h1></center> <p><hr width=40%> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Torna alla home page del corso
. <p>
 !goto end
!endif

Questa pagina permette di scrivere o modificare l'avviso quotidiano
per gli studenti del corso e/o un avviso personale per ogni studente, avvisi che compaiono nella 
!href style=student home page degli studenti
 del corso.
<br>
Scrivere i mesaggi (sono accettati link e tag html):
<br>
<center><table border=1 width=90%>
 <tr>
  <td>Messaggio del giorno (comune a tutti gli iscritti):</td>
  <td rowspan=2 valign=middle>
    !href cmd=reply&job=modif&user=.CLASS. Modifica
    &nbsp; 
    !href cmd=reply&job=delete&user=.CLASS. Cancella
  </td>
 </tr>
 <tr><td>&nbsp;
 !record 0 of wimshome/log/classes/$wims_class/.motd
 </td></tr>
</table>
<p>
Messaggi personali per i singoli iscritti
$table_header
 $table_hdtr
  <th>Studente</th>
  <th width="75%">Messaggio attuale</th>
  <th>Azione</th>
 </tr>
 !for k=1 to $nbuser
  $table_tr 
   !let don=!record $k of wimshome/log/classes/$wims_class/.userlist
   !distribute item $don into f,l,u
   <td>$l $f</td>
   <td>
    !record 0 of wimshome/log/classes/$wims_class/motd/$u
   </td>
   <td>
    !href cmd=reply&job=modif&user=$u Modifica
    &nbsp; 
    !href cmd=reply&job=delete&user=$u Cancella
   </td>
  </tr>
 !next k
$table_end
</center>
<p>
:end

!if $job!=$empty and $job!=delete
 !href cmd=reply Indietro
!endif

!tail
!reset job
