#! /bin/sh

echo "##generated by src/define.sh"
grep "#define MAX_SHEETS" wimsdef.h | awk -F'#define MAX_SHEETS' ' {print "MAX_SHEETS="$2 ; exit}'
grep "#define MAX_EXOS" wimsdef.h | awk -F'#define MAX_EXOS' ' {print "MAX_EXOS="$2 ; exit}'
grep "#define MAX_REQUIRE" wimsdef.h | awk -F'#define MAX_REQUIRE' ' {print "MAX_REQUIRE="$2 ; exit}'
grep "#define MAX_EXAMS" wimsdef.h | awk -F'#define MAX_EXAMS' ' {print "MAX_EXAMS="$2 ; exit}'
grep "#define MAX_VOTES" wimsdef.h | awk -F'#define MAX_VOTES' ' {print "MAX_VOTES="$2 ; exit}'
grep "#define MAX_OEFCHOICES" wimsdef.h | awk -F'#define MAX_OEFCHOICES' ' {print "MAX_OEFCHOICES="$2 ; exit}'
grep "#define MAX_OEFREPLIES" wimsdef.h | awk -F'#define MAX_OEFREPLIES' ' {print "MAX_OEFREPLIES="$2 ; exit}'
echo "DEBUG_MODULE=qualite@wimsedu.info"
echo "DF_SEVERITY=1 2 1"
