struct {
    char *name;
    char *replace;
    char *replacem;
} hmname[]={
      {"CC",		"", "\\CC"},
      {"Delta",		"", "\\Delta"},
      {"Gamma",		"", "\\Gamma"},
      {"Inf",		"$(m_infty)","\\infty"},
      {"Lambda",	"", "\\Lambda"},
      {"NN",		"", "\\NN"},
      {"Omega",		"", "\\Omega"},
      {"Phi",		"", "\\Phi"},
      {"Pi",		"", "\\Pi"},
      {"Psi",		"", "\\Psi"},
      {"QQ",		"","\\QQ"},
      {"RR",		"","\\RR"},
      {"Sigma",		"","\\Sigma"},
      {"Xi",		"","\\Xi"},
      {"ZZ",		"","\\ZZ"},
      {"alpha",		"", "\\alpha"},
      {"beta",		"", "\\beta"},
      {"cap",		"","\\cap"},
      {"chi",		"","\\chi"},
      {"cup",		"","\\cup"},
      {"delta",		"","\\delta"},
      {"div",		"&divide;", "&divide;"},
      {"divide",	"&divide;","&divide;"},
      {"epsilon",	"$(m_varepsilon)"},
      {"eta",		"","\\eta"},
      {"exist",		"$(m_exists)","\\exists"},
      {"exists",	"", "\\exists"},
      {"forall",	"","\\forall"},
      {"gamma",		"","\\gamma"},
      {"in",		"","\\in"},
      {"inf",		"$(m_infty)","\\infty"},
      {"infinity",	"$(m_infty)","\\infty"},
      {"infty",		"","\\infty"},
      {"intersect",	"$(m_cap)", "\\cap"},
      {"intersection",	"$(m_cap)", "\\cap"},
      {"iota",		"","\\iota"},
      {"kappa",		"","\\kappa"},
      {"lambda",	"", "\\lambda"},
      {"mu",		"","\\mu"},
      {"nabla",		"","\\nabla"},
      {"neq",		"","\\neq"},
      {"nu",		"","\\nu"},
      {"omega",		"","\\omega"},
      {"pi",		"","\\pi"},
      {"pm",		"","\\pm"},
      {"psi",		"","\\psi"},
      {"rho",		"","\\rho"},
      {"sigma",		"","\\sigma"},
/*      {"sqrt",		"$(m_surd)"}, */
      {"subset",	"", "\\subset"},
      {"subseteq",	"","\\subseteq"},
      {"tau",		"","\\tau"},
      {"theta",		"","\\theta"},
      {"times",		"&times;", "\\times"},
      {"union",		"$(m_cup)", "\\cup"},
      {"varepsilon",	"","\\varepsilon"},
      {"varphi",	"", "\\varphi"},
      {"x",		"",""},
      {"xi",	"","\\xi"},
      {"y",		"",""},
      {"z",		"",""},
      {"zeta",	"","\\zeta"},
};
#define hmname_no (sizeof(hmname)/sizeof(hmname[0]))

#define hmsame "\\CC\\Delta\\Gamma\\Lambda\\NN\\Omega\\Phi\\Pi\\Psi\\QQ\\RR\\Sigma\\Xi\\ZZ\\alpha\\beta\\cap\\chi\\cup\\delta\\div\\eta\\exists\\forall\\gamma\\in\\infty\\iota\\kappa\\lambda\\mu\\nabla\\nu\\omega\\pi\\pm\\psi\\rho\\sigma\\subset\\subseteq\\tau\\theta\\times\\varepsilon\\varphi\\xi\\zeta\\"

