struct {
    char *name;
    char *replace;
    char *replacem;
} hmname[]={
      {"CC",		"", ""},
      {"Delta",		"", ""},
      {"Gamma",		"", ""},
      {"Inf",		"$(m_infty)","\\infty"},
      {"Lambda",	"", ""},
      {"NN",		"", ""},
      {"Omega",		"", ""},
      {"Phi",		"", ""},
      {"Pi",		"", ""},
      {"Psi",		"", ""},
      {"QQ",		"",""},
      {"RR",		"",""},
      {"Sigma",		"",""},
      {"Xi",		"",""},
      {"ZZ",		"",""},
      {"alpha",		"", ""},
      {"beta",		"", ""},
      {"cap",		"",""},
      {"chi",		"",""},
      {"cup",		"",""},
      {"delta",		"",""},
      {"div",		"&divide;", "&divide;"},
      {"divide",	"&divide;","&divide;"},
      {"epsilon",	"$(m_varepsilon)","\\varepsilon"},
      {"eta",		"",""},
      {"exist",		"$(m_exists)","\\exists"},
      {"exists",	"", ""},
      {"forall",	"",""},
      {"gamma",		"",""},
      {"in",		"",""},
      {"inf",		"$(m_infty)","\\infty"},
      {"infinity",	"$(m_infty)","\\infty"},
      {"infty",		"",""},
      {"intersect",	"$(m_cap)", "\\cap"},
      {"intersection",	"$(m_cap)", "\\cap"},
      {"iota",		"",""},
      {"kappa",		"",""},
      {"lambda",	"", ""},
      {"mu",		"",""},
      {"nabla",		"",""},
      {"neq",		"",""},
      {"nu",		"",""},
      {"omega",		"",""},
      {"pi",		"",""},
      {"pm",		"",""},
      {"psi",		"",""},
      {"rho",		"",""},
      {"sigma",		"",""},
      {"subset",	"", ""},
      {"subseteq",	"",""},
      {"tau",		"",""},
      {"theta",		"",""},
      {"times",		"&times;", "\\times"},
      {"union",		"$(m_cup)", "\\cup"},
      {"varepsilon",	"",""},
      {"varphi",	"", ""},
      {"x",		"","x"},
      {"xi",	"",""},
      {"y",		"","y"},
      {"z",		"","z"},
      {"zeta",	"",""},
};
#define hmname_no (sizeof(hmname)/sizeof(hmname[0]))

#define hmsame "\\CC\\Delta\\Gamma\\Lambda\\NN\\Omega\\Phi\\Pi\\Psi\\QQ\\RR\\Sigma\\Xi\\ZZ\\alpha\\beta\\cap\\chi\\cup\\delta\\div\\eta\\exists\\forall\\gamma\\in\\infty\\iota\\kappa\\lambda\\mu\\nabla\\nu\\omega\\pi\\pm\\psi\\rho\\sigma\\subset\\subseteq\\tau\\theta\\times\\varepsilon\\varphi\\xi\\zeta\\"

