!reset confirm
<html><head>
$wims_html_header
</head><body $wims_htmlbody>

!read names.phtml

!if $job iswordof student
 !changeto $job.phtml
!endif

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

<center>$classname
<p>
<h1>作業清單 $sheet 的準備：
</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 [
 !href module=home 回課程維護首頁
 ]<p>
 !goto end
!endif

!if $activetest>0
 本作業清單
 !if $activetest=1
  正運作中，所以無法修改。
 !else
  尚未過期。
 !endif
 其內容為：<p>
 標題：$title<p>
 說明： $desc<p>
 到期日期： $expiration 。
 !if $activetest=1
  !href cmd=reply&job=prep_expire 設定為已過期？
  。
 !endif
 <p>
 !goto end1
!endif

!form reply
<input type=hidden name=job value=text>
標題(限制 $title_limit 個字元)：<br>
<input size=65 name=title value="$title"> <p>
說明的內容(限制 $desc_limit 個字元，允許  html 標記及連結)：<br>
<textarea rows=6 cols=65 name=desc>$desc</textarea>

<center><input type=submit value=" 登錄內容 "></center>

<p>作業清單截止日期：
!distribute item $[$expday],$[$expmon] into expday,expmon
!formselect expday from 1 to 31
!formselect expmon from 1 to 12 prompt $months
!formselect expyear from $thisyear to $thisyear+1
&nbsp; <input type=submit value=" 單獨登錄 ">

!ifval $activetest=-1
 <p>本作業清單尚未存在！
 <input type=submit value=" 擬定清單 "> (必須先填寫標題)。
 </form>
 !goto end
!else
 </form>
 !if $exocnt>0
  <p>本作業清單尚未運作！
  !href cmd=reply&job=prep_activate 作業清單運作
  。
  (學生只能看到運作中的作業清單，另一方面，作業清單運作後您無法修改。)
 !endif
!endif

:end1
<p>
!if $exocnt=0
 作業清單尚無內容。
!else
 作業清單的內容為：<ol>
 !for i=1 to $exocnt
  <li>
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sheet
  !distribute lines $ex into di,pa,re,we,ti,de
  !href cmd=new&module=$di&worksheet=$sheet&$pa $ti
  ：計分加權權值為  $we ，點數為 $re 。
  !if $activetest=0
   &nbsp;(
   !href cmd=reply&job=delete&delete=$i 刪除
   )
  !endif
 !next i
 </ol>
!endif

!if $activetest=0
 <p>欲加入作業 (習題、課程或工具等) 到作業清單中，請到課程
 !href $ 首頁
 選取應用程式列表中相應的項目，並設定難度。然後利用本頁最後的連結加到作業清單中。
 !if $erasable=yes
  <p>
  您仍然可以
  !href cmd=reply&job=prep_erase 刪除清單
  。
 !endif
!endif

!if $activetest>=0
 <p>
[
 !href module=adm/sheet&sh=$sheet 給參與者的清單
 ]
!endif
:end

!tail

!set job=

