!set wims_module_log=error: $error

!if not_supervisor=$error
 抱歉，作業清單的準備 / 修改權利保留給課程的管理者。
 !exit
!endif

!if bad_class=$error
 奇怪，我發現您的課程不應當！
 !exit
!endif

!if bad_sheet=$error
 您的作業清單編號不適當，可能是軟體的 bug ？
 !exit
!endif

!if no_title=$error
 您所登錄的作業清單沒有標題，不建議您這麼做。處理時的錯誤？
 !exit
!endif

!if prep_activate=$error
 您要求運作作業清單  $sheet ，亦即讓作業清單被課程參與者存取。<p>
 請注意，一旦作業清單運作後，您就無法再修改清單。您確定要繼續？
 <p><center>
 !href cmd=reply&job=activate  運作清單
 。&nbsp;&nbsp;
 !href cmd=resume  放棄運作
 。</center>
 !exit
!endif

!if prep_erase=$error
 您確定要刪除這個作業清單 #$sheet ($title) 嗎？
 <p><center>
 !href cmd=reply&job=erase  刪除
 。&nbsp;&nbsp;
 !href cmd=resume  放棄刪除
 。</center>
 !exit
!endif

!if prep_expire=$error

 作業清單 #$sheet ($title) 的截止日期為： $expday
 !item $expmon of $months
 $expyear 。您要將清單設定為已過期嗎？
 <p><center>
 !href cmd=reply&job=expire 設定為已過期
 。&nbsp;&nbsp;
 !href cmd=resume 放棄設定
 。 </center>
 <p><b>備註：</b>您的學生無法運作已到期的作業清單
 。但他們原先的成績仍然保留(統計時仍然包含這些成績)，且您仍可以查詢這些成績。
 !exit
!endif

!msg $error
