
!readproc primitives/getlimit.proc parms

!for i=1 to $(choices$parmcnt)
 !reset checked
 !if $i iswordof $(parm$parmcnt)
  !set checked=checked
 !endif
 <input type="radio" name="parm$parmcnt" value="$i" $checked>
 !item $i of $parms
 !set ll=!item $i of $limits
 !if $ll>0
  !set remain=$[max(0,$ll-0$(vcnt_$(parmcnt)_$i))]
!!  ($remain $name_remaining)
 !else
!!  !if $(vcnt_$(parmcnt)_$i)!=$empty and $vshow=1
!!   ($(vcnt_$(parmcnt)_$i))
!!  !endif
 !endif
.&nbsp;
!next i

