!!set already_seen=!record 0 of $forumdir/.users/$forumuser

!read desc.phtml
<p>
!if $tot<=0
 !if $mlist!=.newlist
  $n_nomessage
 !else
  $n_emptyforum
 !endif
!else
 !if $mlist=.newlist
  $n_list, $n_most
 !else
  $n_list_month
  !item $lmon of $monthnames
  $lyear, $n_most
 !endif
 !item $l_order of $n_old
.  &nbsp;
 !set wims_ref_class=wims_button
 !href cmd=reply&l_order=$[$l_order%2+1] $n_reverse
  &nbsp;
   &nbsp;
 !set wims_ref_class=wims_button
!href cmd=reply&job=threadlist& $n_subjectlist
 !if $send_right>0
  &nbsp;
   &nbsp;
 !set wims_ref_class=wims_button
  !href cmd=new&forum=$forum&job=compose $n_new
 !endif

 <ul class="wims_forum_list">
 !if $l_order=1
  !distribute item $tot,1,-1 into start,end,step
 !else
  !distribute item 1,$tot,1 into start,end,step
 !endif
 !for i=$start to $end step $step
  !if $mlist=.newlist
   !set l_=!line $i of $mnew
   !distribute word $l_ into a_,b_
   !set l_=!record $b_ of $forumdir/$a_/.msglist
  !else
   !set l_=!record $i of $forumdir/$mlist/.msglist
  !endif
  !read listone.phtml $l_
  </li>
 !next i
 </ul>
!endif

<p>
!if $mlist!=.newlist
 !href cmd=reply&job=list&mlist=.newlist $n_recent.
 &nbsp;
!endif

!read listarch.phtml

