
!if $error!=$empty
 <p>
 !exit
!endif

 <p class="wimscenter">
 !read readref.phtml
 !if $erased=yes and $forumuser!=supervisor
  </p>
  $n_erasedmsg.
  !exit
 !endif
 <br />$n_follow&nbsp;:
 !href cmd=reply&job=compose&c_prec=$r_month/$r_ident&c_quote=1 $n_with
 $wims_name_or
 !href cmd=reply&job=compose&c_prec=$r_month/$r_ident&c_quote=-1 $n_without
 $n_citation.
 </p>
 <div class="wims_forum_intro">
 <i>
 !if $m_email!=$empty
  !mailurl $m_email $m_from
 !else
  $m_from
 !endif
 </i>
 !set y_=!char 1 to 4 of $m_date
 !set m_=!char 5,6 of $m_date
 !set d_=!char 7,8 of $m_date
 <span class="small"> $m_-$d_-$y_, $m_time</span>:
 <b>$m_subject</b><span class="small">

!if $readtype=html
!set wims_ref_class=wims_button
 !href cmd=reply&readtype=source $n_source
!else
!set wims_ref_class=wims_button
 !href cmd=reply&readtype=html $n_format
!endif
!if $forumuser=supervisor
 &nbsp;
 !set wims_ref_class=wims_button wims_warning
 !href cmd=reply&job=erase $wims_name_erase
!endif

 </span>
 </div>
 <hr />
 <div class="wims_forum_msg">
 !read $msg $readtype
 $tag_escaper
  </div>

<hr />
<div class="wimscenter">
!if $readtype=html
&nbsp;
!set wims_ref_class=wims_button
 !href cmd=reply&readtype=source $n_source

!else
&nbsp;
!set wims_ref_class=wims_button
 !href cmd=reply&readtype=html $n_format
!endif

&nbsp;
!set wims_ref_class=wims_button
!href cmd=reply&job=compose&c_prec=$r_month/$r_ident&c_quote=1 $n_follow_c
&nbsp;
!set wims_ref_class=wims_button
!href cmd=reply&job=compose&c_prec=$r_month/$r_ident&c_quote=-1 $n_follow_nc
<p></p>
!read readref.phtml
</div>

