
!if $s_status=ask
 $n_statusask
 <div class="wimscenter">

 !form reply
 <input type="hidden" name="job" value="send" />
 &nbsp;
 <input size="10" name="s_code" />
 &nbsp;
 <input type="submit" value="$wims_name_send" />

 !set wims_ref_class=wims_button wims_secondary_button
 $
 !href cmd=reply&job=list $wims_name_giveup
 !formend
</div>
 !exit
!endif

!if $error=$empty
 $n_add
!endif

!set wims_menu_items=!append line forum,1,cmd=reply&job=list&mlist=.newlist\
to $wims_menu_items

!read listarch.phtml
