<b>Formule brute d'une molécule</b> (nom : <tt>chembrut</tt>)
permet de vérifier une formule brute. Elle est partiellement bonne si elle n'est pas
écrite dans l'ordre (carbone, hydrogène, puis les autres éléments par ordre alphabétique).
La bonne réponse doit être sous la forme C7H4Cl2O2.

La variable <tt>reply</tt>i contient sur la première ligne la réponse,
puis la réponse formatée sous la forme 
<pre>C,7
H,4
Cl,2
O,2
</pre>
dans l'ordre donné par la réponse.
La variable <tt>sc_reply</tt>i vaut 0.5 si la réponse est correcte à l'ordre près 
des éléments

