<b>Raw formula for a molecule</b> (nom : <tt class="wims_code_words">chembrut</tt>)
checks a raw formula. It is partially good if the answer is not written in the order
(carbon, hydrogen, then the other elements in alphabetical order).
The good answer must be on the form C7H4Cl2O2.

The variable <tt class="wims_code_words">reply</tt>i contains on the first line the answer,
then the formatted answer as
<pre>C,7
H,4
Cl,2
O,2
</pre>
in the order given by the answer.
The variable <tt class="wims_code_words">sc_reply</tt>i is 0.5 if the answer is correct up to the order.

