

 <b>Answer fields to be filled with given objects.</b>
 (name: <tt>clickfill</tt> and <tt>dragfill</tt>)
 <br>
 The answer field, usually embedded in the statement, can be filled by
 clicking or dragging a given object (text, formula or image) from within a list.
 <p>
 The good reply is usually a matrix, where the first row is the good answer,
 while the second row lists items that are bad answers.
 <p>
 The good answer may be a list of several items. In this case the fill field
 will have a length (that is, number of successive objects it can accept)
 greater than 1.
 <p>
 Multiple good answers can be defined in the first row, if they are
 separated by the character '<tt>|</tt>'. And the answer can be analyzed, if
 the first row is a non-defined variable.
 <p>
 This reply field is best used via \embed{}, with a input size field under
 the form <tt>HxVxL</tt>, where H and V are respectively the horizontal and
 vertical sizes (in pixels) of one case, and L is the length of the field.
 <p>
 There may be several clickfill or dragfill replies within one exercise,
 but they must have the same size and of the same type (all clickfill or all
 dragfill), and the objects are mixed.
 <p>
 clickfill and dragfill have very similar user interfaces (both can be clicked
 or dragged). The main difference is that
 in clickfill an object can be used several times, while for dragfill
 each object can be used at most once.
 </p><p>Contents are centered by default. One may align on the left or the right
 by using the option l'option <tt>align=left</tt> or <tt>align=right</tt> 
 (<tt>{option= align=left}</tt>).
<p>With the option <tt>noorder</tt>, the analysis doesn't take in account 
the order in which the objects have been clicked or dragged. This is useful
in exercises asking for classifying according some properties. 
<p>

 Based on DynAPI, may not work under some browsers.

