

 <b>Sentence composed using given constituents.</b>
 (name: <tt>compose</tt>)
 <br>
 The given constituents can be text (words or groups of words), formulas
 (formatted using \(...)), or images. The constituents must be listed as
 comma-separated items
 in the given good answer. Useless constituents can be added in the answer
 after a semi-colon `;'.
 <p>
 You may define synonymes in the good answer. To do this, the synonymes has
 only to be added behind the (standard) good answer, preceeded by the
 vertical bar `|'. An arbitrary number of synonymes can be defined. In such 
 a case, only the first synonyme (before the first `|') should have
 comma-separated itgems. Words not appearing in the first synonyme will not
 be presented, unless added after a semi-colon.
 <p>
 Based on DynAPI, may not work under some browsers.

