

 <b>One-to-one correspondance of objects.</b>
 (name: <tt>correspond</tt>)
 <br>
 Two finite sets of items of the same order will be presented to the user,
 under the form of a table, with shuffled correspondance. The user may click
 on the items to reorder them until he gets a correct correspondance.
 <p>
 The good answer should be given as a matrix of two rows. The first row will
 be objects to the left (a list of items),
 and the second those to the right. The two rows
 should be separated by a semi-colon `;'.
 <p>
 The items may contain text, images (under HTML format), and mathematical
 formulas using <tt>\(...)</tt>.
 <p>
 This reply field is best used via \embed{}, with a input size field under
 the form <tt>VxH1xH2</tt>, where V is the vertical size of the items,
 and H1,H2 are respectively the horizontal sizes of the left and right
 columns.
 <p>
 By default, 0 is attributed to any answer that is not entirely correct.
 If you add the word <tt>split</tt> into the optional "option" field
 of the reply, then the score will be given proportionally with the 
 number of good correspondences.
 <p>
 Based on DynAPI, may not work under some browsers.

