 <b>Mathematical expression.</b>
 (name: <tt>algexp</tt>, <tt>litexp</tt> and <tt>formal</tt>)<br>
 This is a mathematical expression that will be compared with the given good
 reply, according to different criteria of identification.
 One may put several good replies, separated by commas.
 <p>
 
For <tt>algexp</tt> (algebraic expression), there are some limited
algebraic identifications for the comparison. For example, (x+1)(x-1) will
not be accepted when the good reply is x^2-1. Neither for sin(x)^2+cos(x)^2
against 1. On the other hand, x-y*y and -y^2+x will be considered as the
same.
<p>

Four <tt>litexp</tt> (literal expression), the reply will be compared litterally
 with the given good answer, with no algebraic simplification. For example,
 x+y will not be identified with y+x, nor will 3/2 with 6/4. But 2x and 2*x
 will be identified, and spaces will be collapsed before comparison. <p>
 It is useful for forcing students to do expression manipulations.
<p>

The type <tt>formal</tt> (formal expression) is for exact numerical
comparison. It is as the type <tt>numeric</tt>, except that no approximation
is allowed.
