

 <b>Reordering given objects.</b>
 (name: <tt>reorder</tt>)
 <br>
 List given objects according to some good order.
 <br>
 The objects can be text (words or groups of words), formulas
 (formatted using \(...)), or images. The given good answer must list the
 objects as items, in good order. The server will present the items
 with a randomly shuffled order.
 <p>
 Based on DynAPI, may not work under some browsers.


