
!if $wims_read_parm!=badonly
 <p>
 You may define synonymes in the good answer. To do this, the synonymes has
 only to be added behind the (standard) good answer, preceeded by the
 vertical bar ``<tt>|</tt>''. An arbitrary number of synonymes can be defined.
!endif

 <p>
 Furthermore, if you don't want user inputs with just some typing errors to be
 considered as false, you can define a list of `meaningful' words to the
 answer. This is a list of words to be put into the `good answer' field,
 behind the good answer and eventual synonymes, and preceeded by a semicolon
 ``<tt>;</tt>''. Punctuations will be ignored in this list, and the words 
 are also compared with the same level of difference tolerance as for the good
 answers.
 <p>
 When the meaningful words are defined, user inputs containing a word not in
 the meaningful word list will be sent back for correction.
