
<h1 class="wims_docu_title">$tit</h1>

!if $titb=$empty
 <p>
$name_noncreate
 </p>
 !exit
!endif

!if $datetest<0
 <p>
 $name_noread
 </p>
 !exit
!endif

!if $datetest>0
 <p>
 $name_expired
 </p>
 !exit
!endif

<h3>$titb ($n_sourcedoc)
<span class="small">
 [
 !href cmd=reply&job=read $n_formatted
 ]</span>
</h3>

<pre wrap>
!mexec scripts/cat.sh $wims_home/$Docdir/$doc/src/$block
</pre>

<hr />
!if $wims_class!=$empty and $wims_user!=supervisor
 !exit
!endif
<table class="wimsnoborder">
<tr><td align="left" class="small">
!href cmd=reply&job=read $n_formatted
&nbsp; $n_by
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
</td>
!if help notin $wims_session
 <td style="text-align:right" class="small">
 !href module=home WIMS
  @
 <a href="http://$httpd_HTTP_HOST/">$httpd_HTTP_HOST</a>
 </td>
!endif
</tr></table>
<div class="wimstech">
$n_lastmod $datm

</div>
