!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu
!read adm/css.phtml
!header1

!read names.phtml

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
Canvi de contrasenya

!!<center>$classname
!!<p>
!!<h1>Canvi de contrasenya
!!</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Tornar a l'índex de la classe
. <p>
 !goto end
!endif

!form reply

!if $wims_user=supervisor
 Seleccioneu el tipus de contrasenya&nbsp;: <ul>
 !default job=user
 !set ch_$job=checked
 <li><input type=radio name=job $ch_user value=user> Contrasenya
  personal (per tal d'entrar a la classe com a professor)<br>
 !if $part!=$empty and $job=part
  <li><input type=radio name=job $ch_part value=part> Contrasenya de
   participant <tt>$part</tt>. (En aquest cas no es necessari escriure
   la contrasenya actual.)
 !endif
 <li><input type=radio name=job $ch_class value=class> Contrasenya de la classe
  (utilitzada pels participants per inscriure's&nbsp;; no es necessari escriure
   la contrasenya actual).
 </ul>
!else
 <input type=hidden name=job value=user>
!endif
<table>
<tr><td align=right>Escriviu la contrasenya actual&nbsp;:
	<td><input type=password size=16 name=old>
<tr><td align=right>Després, la nova contrasenya&nbsp;:
	<td><input type=password size=42 name=pw1>
<tr><td align=right>La nova contrasenya una altra vegada&nbsp;:
	<td><input type=password size=42 name=pw2>
</table>
<input type=submit value="$wims_name_tosave"> <p>
<small>Per contrasenyes personals&nbsp;: precediu la nova contrasenya
 del signe <tt class="d">+</tt> si voleu afegir
contrasenyes d'un sol ús..
!href target=wims_mhelp cmd=help Detall.
</small>
</form>
La contrasenya ha d'estar composta només de caràcters alfanumèrics,
i de longitud entre 4 i 16.
!if $wims_user=supervisor
 (Una contrasenya de classe buida és acceptada pel programari, però el
 gestor de la web pot prohibir classes sense una contrasenya.) 
!endif

!endif
:end
!tail

!distribute item $ into job,pw1,pw2,old

