
!read lang/names.phtml.$modu_lang enter

!set wims_form_method=post
!form new
<input type="hidden" name="module" value="adm/forum/mboard"/>
<input type="hidden" name="job" value="authuser"/>
<input type="hidden" name="forum" value="$forum"/>
<center><table border="0">
 <tr><td>$wims_name_Login</td><td><input size="20" name="fuser"/></td></tr>
 <tr><td>$wims_name_Password</td><td><input type="password" size="20" name="fpassword"/></td></tr>
 $table_end
 <p class="wimscenter wimsform">
 <input type="submit" value="$wims_name_send"/>
</p>

!formend

