
!readproc adm/docsheet.prep
!read $docdef content
<p><center>
得分纪录
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   是打开的, 但你可以使它
   !href cmd=resume&job=suspend 暂停
.
  !else
   被你自己暂停了.
   !href cmd=resume&job=reopen 打开纪录
.
  !endif
 !else
  对于你的链接是关闭的.
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc.en&job=edit&doc=$d_&block=$b_ 编辑本页
.&nbsp;
 !href cmd=resume 重做
.
!endif
</center>

!tail

