

!! d閒inition des noms pour les liens dans le menubox (d閒inis par wims_menu_items)
!distribute items Ins閞er un fichier source,\
		恢复页面的正常外观,\
		Source of the sheet, \
into wims_name_putsource,wims_name_participantview,wims_name_sheetsource

!set name_student1=本页将于 $expyear 年 $expmon $expday 日到期.
!set name_student2=本页已经过期. 你还可以完成作业, 但是你的分数不会被纪录. 
!set name_student3=  目前你无权接触本页的内容. 请与你的主持教师联系. 
!set name_student4=本页是空的, 没有为你指定任何内容. 也许是你的主持教师操作不当所致.
!set name_score=!nosubst 得到了 $[$require] 分中的 $[$got] 分, 平均
!set name_score2=!nosubst 要求得 $[$require] 分.
!set name_deps=在纪录这个练习的分数前, 
!set name_dep=在纪录这个练习的分数前
!set name_dep2=你必须改进你在练习 $dep 中的得分.
!set name_scoresuspend=得分纪录 被你自己暂停了.
!set name_scoreopen= 得分纪录 是打开的, 但你可以使它
!set name_scoreclose=对于你的链接是关闭的.


!set name_textsource=这是页面的源代码, 你可以用选中与粘贴的方法把它们插入你的班级. 
!set name_answer=Answer to exercise

!set name_title=!nosubst  作业页 #$sh
!set name_empty= 本页是空的! 可能有错误.

!set name_exo=!defof name_exo in wimshome/public_html/scripts/oef/$lang/names
!set name_noprint=!defof name_noprint in oef/$lang/names
!set name_answers=!defof name_answers in oef/$lang/names

!distribute items niveau approximatif,dur閑 \
into name_level,name_duration