!if $module = home
  !set path = ./adm/
!else
  !set path = $empty
!endif

<!-- _widgets/ariane.phtml -->
!set wims_ariane_cnt=!linecnt $wims_ariane

<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
!set 1_=!line 1 of $wims_home_items
 <li class="menuitem $(1_[1])">
     !read $(path)oneitem.phtml $1_
</li>

!! the variable wims_ariane_self must be defined in the var.proc of
!! the module if one does not an ariane thread automatically created
!! should have more parameters, for the moment, just no.

!if $wims_ariane_self!=$empty
 !for i_=1 to $wims_ariane_cnt
  !set 1_=!line $i_ of $wims_ariane
  !set 2_=!word 1 of $1_
   <li class="menuitem $2_">
     !read $(path)oneitem.phtml $1_
   </li>
 !next
 </ul>
 </nav>
 !exit
!endif


!if _ notin $session and $module!=home and adm isin $module_category

  !set mtitle=$(module_title_$lang)
  !default mtitle=$module_title

!! clickable or not ? it depends and the link module=$module
!! is not always pertinent and sometimes repetition with Back
!! the other problem is that some modules
!! rename module_title according to the job.

!! the test is not always OK, how to find if we are not in the homepage
!! of the adm module
  !if $cmd!=$empty and $cmd!=new and adm/light notin $module
    <li>
    !read $(path)oneitem.phtml "$mtitle",1,module=$module
    </li>
    !if $wims_ariane_cnt>0
      !for i_=1 to $wims_ariane_cnt
        !set 1_=!line $i_ of $wims_ariane
        !set 2_=!word 1 of $1_
        <li class="menuitem $2_">
          !read $(path)oneitem.phtml $1_
        </li>
      !next
    !endif
    <li>*<span class="show-for-sr">(Current)</span></li>
  !else
    <li><span class="show-for-sr">Current: </span>
    !read $(path)oneitem.phtml "$mtitle",8
    </li>
  !endif
!endif
  </ul>
</nav>
<!-- _widgets/ariane.phtml -->
