!! options :
!! wims_ariane_home = no ==> don't use $wims_home_items
!! wims_ariane_self = no ==> don't generate automatically : home / module

!read themes/_procs/ariane.proc

<!-- _widgets/ariane.phtml -->
<nav aria-label="You are here:">
  <ul class="breadcrumbs">
  !for i_=1 to $wims_ariane_cnt
   !set 1_=!line $i_ of $wims_ariane_list
   <li class="
     !if $i_=1
       breadcrumb_root
     !else
       menuitem
     !endif
     !if " notin $(1_[1]) and * notin $(1_[1])
       $(1_[1])
     !endif
     ">
     !read $(path)oneitem.phtml $1_
     !if $i_=$wims_ariane_cnt
      <span class="show-for-sr">(Current)</span>
     !endif
   </li>
  !next
  </ul>
 </nav>
 !exit
!endif
<!-- _widgets/ariane.phtml -->
!!reset wims_ariane_home wims_ariane_self
