!if $class_cas_auth!=$empty
 <!-- _widgets/authlogout.phtml -->
   <span class="menuitem">
!!FIXME this line does not work
!! !read adm/class/cas_logout
!!if there is a number session, there is an error message
   !set url = $wims_ref_name?module=home
     <a href="$class_cas_auth/logout?service=$url">$wims_name_cas_logout</a>
   </span><!--menuitem-->
 <!-- end _widgets/authlogout.phtml-->
!endif
