<!-- _widgets/classtools.phtml -->
<div id="classtools">
 !if $wims_supertype!=4 or $class_typename!=class
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml add_sheet,1,module=adm/class/sheet&sheet=$[$sheetcnt+1] 
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml add_exam,1,module=adm/class/exam&exam=$[$examcnt+1] 
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml add_exo,1,module=adm/createxo 
  </$div1>
 !endif
 <$div1 class="menuitem">
  !read ./adm/oneitem.phtml add_doc,1,module=adm/doc&job=creat
 </$div1>
 <$div1 class="menuitem">
  !read ./adm/oneitem.phtml add_vote,1,module=adm/vote&job=creat
 </$div1>
</div><!--end id=classtools-->
<!-- end _widgets/classtools.phtml -->