!if $wims_superclass=$empty or $wims_superclass=$wims_class
  !set tmp_desc=$wims_institutionname\
$wims_classname
!else
  !set tmp_cl=!replace internal / by , in $wims_class
  !set tmp_cl_cnt=!itemcnt $tmp_cl
  !reset C_
  !for j=1 to $tmp_cl_cnt
    !set c_=!item 1 to $j of $tmp_cl
    !set c_=!replace internal , by / in $c_
    !set c_=!nospace $c_
    !set pname=!defof class_description in wimshome/log/classes/$c_/.def
    !set C_=!append item $pname to $C_
    !reset pname
  !next
  !set CC=!replace internal , by / in $(C_[2..-2])
  !if /0// isin $wims_class//
    !set tmp=$CL_Test
    !set tmp_=testclass
  !else
    !set tmp=$(wims_name_$class_typename)
    !set tmp_=$class_typename
  !endif
  !if $CC!=$empty
    !set CC = / $CC
  !endif
  !set tmp_desc=!append line $(C_[1]) ($wims_institutionname) $CC\
<span class="wims_classes_direct_$tmp_">$tmp $wims_classname</span>\
to $tmp_desc
  !reset tmp_ tmp
!endif

!read $(path)title.phtml 1\
$tmp_desc

!reset tmp_desc tmp
