<!-- _widgets/devtools.phtml -->
 <div id="wimsdevtools">
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml createxo,1,module=adm/createxo
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml modtool,1,module=adm/modtool
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml quicktool,1,cmd=new&module=adm/quicktool
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml latex2wims,1,cmd=new&module=adm/latex2wims
  </$div1>
 </div>
<!-- end _widgets/devtools.phtml -->