<!-- _widgets/docheadermenu.phtml -->
<div class="wimsmenu">
 !if _mfeed  isin $wims_session
  <span class="menuitem">
   !set wims_ref_class=doch_class
   <a href="#" onclick="window.close()">$wims_name_back2</a>
  </span><!-- menuitem-->
 !endif
 !if help notin $wims_session and _mfeed notin $wims_session
  !if $wims_class=$empty
   !!<span class="menuitem">
    !!read $oneitem doch_wims,1,module=home
   !!</span><!-- menuitem-->
  !else
   !if _doc isin $wims_session
    <span class="menuitem">
     !set wims_ref_class=doch_class
     <a href="#" onclick="window.close()">$wims_name_doch_class</a>
    </span><!-- menuitem-->
   !else
    <span class="menuitem">
     !!read $oneitem doch_class,1,module=home
    </span><!-- menuitem-->
   !endif
   !if $m_wims_sequence>0
    <span class="menuitem">
     !if $wims_user=supervisor
      !href module=adm/class/sequence&seq=$m_wims_sequence $name
     !else
      !href module=home&seq=$m_wims_sequence $name
     !endif
    </span><!-- menuitem-->
   !else
    !if $wims_sequence>0
     !set ti=!defof sequence_Title in wimshome/log/classes/$wims_class/seq/.def
     <span class="menuitem">
      !if $wims_user=supervisor
       !href module=adm/class/sequence&seq=$wims_sequence $name
      !else
       !read $oneitem sequence,1,module=home&seq=$wims_sequence
      !endif
     </span><!-- menuitem-->
    !endif
   !endif
  !endif
 !endif
 !if ..//adm/doc isin ..//$module and \
    ($wims_class=$empty or $wims_user=supervisor) and _test notin $wims_session
  <span class="menuitem">
   !read $oneitem doch_docs,1,module=$module&cmd=reply&job=home
  </span><!-- menuitem-->
 !endif

 !if $printable!=yes
  !if $job=exosource
   <span class="menuitem">
    !read $oneitem doch_back,1,cmd=reply&job=read
    !reset wims_ref_class
   </span><!-- menuitem-->
  !endif
  !if $doc!=$helpd and $editable=yes and $printable!=yes
   <span class="menuitem">
    !!!ne pas utiliser oneitem, ne fonctionne pas
    !set wims_ref_class=doch_help
    !href target=wims_help module=$module&cmd=new&job=read&doc=$helpd $wims_name_doch_help
    !reset wims_ref_class
   </span><!-- menuitem-->
  !endif
  !if _mfeed notin $wims_session and $printable!=yes
   <span class="menuitem">
    !!!ne pas utiliser oneitem
    !set wims_ref_class=doch_about
    !href target=wims_mhelp module=$module&cmd=help&special_parm=about $wims_name_doch_about
    !reset wims_ref_class
   </span><!-- menuitem-->
  !endif
 !endif
</div> <!--menu -->
<!-- end _widgets/docheadermenu.phtml -->
