<!-- _widgets/documentation.phtml -->
<div id="wimsdocumentation">
<div class="menuitem">
  !read ./adm/oneitem.phtml help,4,module=help/main,help
</div><!--menuitem-->
!if $lang=fr
  <div class="menuitem">
    !read ./adm/oneitem.phtml dochelp,1,cmd=new&module=home&search_keywords=help&search_category=A&search_lang=fr#searchform
  </div>
  <div class="menuitem">
    !read ./adm/oneitem.phtml faq,1,module=help/teacher/faq
  </div>
!endif
<div class="menuitem">
  !read ./adm/oneitem.phtml doctec,1,module=help/wimsdoc
</div>
</div>
<!-- end _widgets/documentation.phtml -->