<!-- _widgets/documentation.phtml -->
<div id="wimsdocumentation">
 <$div1 class="menuitem">
  !read ./adm/oneitem.phtml help,4,module=help/main,help
 </$div1><!--menuitem-->
 !if $lang=fr
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml dochelp,1,cmd=new&module=home&search_keywords=help&search_category=A&search_lang=fr#searchform
  </$div1>
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml faq,1,module=help/teacher/faq
  </$div1>
 !endif
 <$div1 class="menuitem">
  !read ./adm/oneitem.phtml doctec,1,module=help/wimsdoc
 </$div1>
</div> <!--end wimsdocumentation -->
<!-- end _widgets/documentation.phtml -->