
!if $wims_homeref_n0+$wims_homeref_n4 + $wims_homeref_n5 + $wims_homeref_local_n0>0
 <!-- _widgets/menumodubox.phtml -->
 <div id="wimsmenumodubox">

  !if $wims_homeref_n0>0
   !for i_=1 to $wims_homeref_n0
    !set 1_=!line $i_ of $wims_rm_0
    !if $(1_[1])$(1_[2]) != $empty
     !set is_link=!item 2 of $1_
     !if $is_link!=0
      !if $i_=1
       <$div0 class="wimsmenu homeref_n0 $i_">
      !endif
      <$div1 class="menuitem">
       !read oneitem.phtml $1_
      </$div1>
     !else
      !if $i_ != 1
       </$div0>
       <hr class="itemsep"/>
      !endif
      <h2 class="menu_title">
       !read oneitem.phtml $1_
      </h2>
      <$div0 class="wimsmenu homeref_n0">
     !endif
    !endif
   !next i_
   </$div0><!--wimsmenu-->
  !endif wims_homeref_n0
 
  !if $wims_homeref_n5>0
   <$div0 class="wimsmenu homeref_n5">
    !for i_=1 to $wims_homeref_n5
     <$div1 class="menuitem">
      !set 1_=!line $i_ of $wims_rm_5
      !read oneitem.phtml $1_
     </$div1><!-- menuitem-->
    !next i_
   </$div0><!--wimsmenu-->
  !endif wims_homeref_n5
  
  !if $wims_homeref_n4>0
   <$div0 class="wimsmenu homeref_n4">
    !for i_=1 to $wims_homeref_n4
     <$div1 class="menuitem">
      !set 1_=!line $i_ of $wims_rm_4
      !read oneitem.phtml $1_
     </$div1><!--menuitem-->
    !next i_
   </$div0><!--wimsmenu-->
  !endif wims_homeref_n4

  !if $wims_homeref_local_n0>0
   <$div0 class="wimsmenu homeref_local_n0">
    !for i_=1 to $wims_homeref_local_n0
     !set 1_=!line $i_ of $wims_local_menu_items
     !if $(1_[1])=
      <$div1 class="itemsep">&nbsp;</$div1>
     !else
      <$div1 class="menuitem">
       !read oneitem.phtml $1_
      </$div1>
     !endif
    !next i_
   </$div0><!--wimsmenu-->
  !endif wims_homeref_local_n0
 </div> <!--wimsmenumodubox-->
<!-- end _widgets/menumodubox.phtml -->
!endif wims_homeref_n0+wims_homeref_n4+$wims_homeref_n5
