<!-- _widgets/menumodubox.phtml -->
!if $wims_homeref_n0+$wims_homeref_n4 + $wims_homeref_n5 + $wims_homeref_local_n0>0
<div id="wimsmenumodubox">
 !if $wims_homeref_n0>0
  <$div0 class="wimsmenu">
  !for i_=1 to $wims_homeref_n0
   !set 1_=!line $i_ of $wims_rm_0
   !if $(1_[1])=
    <$div1 class="itemsep"></$div1>
   !else
    <$div1 class="menuitem">
     !read oneitem.phtml $1_
    </$div1>
   !endif
  !next i_
  </$div0><!--wimsmenu-->
 !endif wims_homeref_n0
 !if $wims_homeref_n5>0
  <$div0 class="wimsmenu">
   !for i_=1 to $wims_homeref_n5
    <$div1 class="menuitem">
     !set 1_=!line $i_ of $wims_rm_5
     !read oneitem.phtml $1_
    </$div1><!-- menuitem-->
   !next i_
   </$div0><!--wimsmenu-->
 !endif wims_homeref_n5
 !if $wims_homeref_n4>0
  <$div0 class="wimsmenu">
   !for i_=1 to $wims_homeref_n4
    <$div1 class="menuitem">
     !set 1_=!line $i_ of $wims_rm_4
     !read oneitem.phtml $1_
   </$div1><!--menuitem-->
   !next i_
  </$div0><!--wimsmenu-->
 !endif wims_homeref_n4

!if $wims_homeref_local_n0>0
  <$div0 class="wimsmenu">
   !for i_=1 to $wims_homeref_local_n0
    !set 1_=!line $i_ of $wims_local_menu_items
    !if $(1_[1])=
     <$div1 class="itemsep"></$div1>
    !else
     <$div1 class="menuitem">
      !read oneitem.phtml $1_
     </$div1>
    !endif
   !next i_
  </$div0><!--wimsmenu-->
  !endif wims_homeref_local_n0
 </div> <!--wimsmenumodubox-->

!endif wims_homeref_n0+wims_homeref_n4+$wims_homeref_n5
<!-- end _widgets/menumodubox.phtml -->