<!-- _widgets/supervisorscore.phtml -->
!if ($wims_supertype<4 and $wims_typename=class) or ($wims_supertype=4 and $wims_typename iswordof course program)
 <div id="supervisorscore">
 !if ($wims_supertype<4 and $wims_typename=class) or ($wims_supertype=4 and $wims_typename iswordof course)
  <div class="menuitem">
    !read ./adm/oneitem.phtml Score1,1,module=adm/class/userlist
  </div>
 !endif
  <div class="menuitem">
   !read ./adm/oneitem.phtml livret,1,module=adm/class/livret
  </div>
  <div class="itemsep"></div><!--itemsep-->
 </div> <!-- supervisorscore -->
!endif
<!-- _widgets/supervisorscore.phtml -->