!!no more used in standard theme see _procs/userscore.proc

<!-- _widgets/userscore.phtml -->
<$div1 class="menuitem">
 !read ./adm/oneitem.phtml myscore,1,module=adm/class/userscore
</$div1>

!if $wims_showlivret!=no
 !set livret_nbcomp=!recordcnt wimshome/log/classes/$wims_class/livret/.comps
 !if $livret_nbcomp >0
  <$div1 class="menuitem">
   !read ./adm/oneitem.phtml livret,1,module=adm/class/livret
  </$div1><!--end menuitem-->
 !endif
!endif
<!-- _widgets/userscore.phtml -->
