!!## technical parameters

!if $wims_firstname$wims_lastname = $empty
  !exit
!endif

!if $class_cas_auth=$empty
    !set m_init_parm=!replace internal & by $ $ in $module_init_parm
    !set class_cas_auth=!getopt class_auth in $m_init_parm
!endif

<ul class="wimsmenu float_right dropdown menu" data-dropdown-menu>
    <li class="menuitem">
        <a href="#user_account" class="account">
            <span class>$wims_firstname $wims_lastname</span>
        </a>
        <ul id="user_account" class="menu">
            !! BETA : it will be better to call userprop.proc when all is fine !
            !! !read themes/_procs/userprop.proc
            !! # "My account"
            <li class="menuitem">
                !read oneitem.phtml account,1,module=adm/class/usermanage&job=userprop
            </li>
            !if $auth_method notwordof cas ldap php
              <li class="menuitem">
                !! "Change password"
                !read oneitem.phtml passwd,1,module=adm/class/passwd&job=user
              </li>
              <li class="menuitem">
                !! "Display prefs"
                !read oneitem.phtml pref,1,module=adm/light&phtml=useropts.phtml.$lang
              </li>
            !endif
            !! "WIMS logout"
            !read themes/_widgets/logout.phtml
            !! "CAS logout"
            !set div0=li
            !read themes/_widgets/authlogout.phtml
        </ul>
    </li>
</ul>

<!-- Foundation Dropdown Menu -->
<script type="text/javascript" src="html/themes/_inc/foundation_dropdown_menu.js"></script>
<script type="text/javascript" >$$(document).foundation()</script>
