<!-- _widgets/usermenubox.phtml -->
<div id="wimsmenubox" class="footer">
  <$div0 class="wimsmenu">
   <div class="menublock">
    <$div1 class="menuitem">
     !if $wims_superclass!=$wims_class and $wims_superclass!=$empty and $auth_method isitemof $auth_method_list
      !read ./adm/oneitem.phtml U_oclass,1,module=adm/class/classes&type=authparticipant&auth_user=$ext_login&class=$wims_superclass
     !else
      !read ./adm/oneitem.phtml U_oclass,1,module=adm/class/classes&type=participant
     !endif
    </$div1><!-- end menuitem-->
   </div><!--end menublock-->
   <$div0 class="menublock">
    <$div1 class="menuitem">
     $supmail
    </$div1><!-- end menuitem-->
   </div><!--end menublock-->
   <div class="menublock">
    <$div1 class="menuitem">
     !read ./adm/oneitem.phtml pref,1,module=adm/light&phtml=useropts.phtml.$lang 
    </$div1><!-- end menuitem-->
   </div><!--end menublock-->
  </$div0><!--end of wimsmenu-->
 </div><!--end of wimsmenubox-->
<!-- end _widgets/usermenubox.phtml -->