<!-- _widgets/usermenumodubox.phtml -->
<div id="wimsmenumodubox" class="usermenumodubox">

 <$div0 class="wimsmenu">
  !read themes/_widgets/cdt.phtml
  !read themes/_widgets/userforum.phtml
  !read themes/_widgets/userprop.phtml
 </$div0>
 
 !ifval $n+$m>0 and $is_interclass!=yes
  <hr class="itemsep"/>
  <$div0 class="wimsmenu">
   !read themes/_widgets/userscore.phtml 
  </$div0>
 !endif
 
 <$div0 class="wimsmenu">
  !read themes/_widgets/extlink.phtml
 </$div0>
 
 !if $wims_user=supervisor
  <hr class="itemsep"/>
  <$div0 class="wimsmenu">
   <$div1 class="menuitem">
    !read ./adm/oneitem.phtml backteacher,1,$
   </$div1><!--end menuitem-->
  </$div0>
 !endif
 
</div><!--end wimsmenumodubox-->
<!-- end _widgets/usermenumodubox.phtml -->
