
!read themes/_widgets/user_varsheet.phtml

!if $n>0
 <!-- _widgets/usersheet.phtml -->
 <table class="wims_user_sheet_table">
  !for i=1 to $n
   !set se=!item $i of $aclist
   !distribute lines $(s_$se) into ac,t_,ti,de
   <tr class="wims_user_sheet">
    <td class="wims_user_sheet_type">$wims_name_Sheet $se. </td>
    <td class="wims_user_sheet_desc">
     !href module=adm/sheet&sh=$se $ti
    </td>
    <td class="wims_user_sheet_expire">
     !if $ac>=2
      $U_expired
     !else
      !if showshexpire iswordof $class_option
       !read misc/expire.phtml.$lang $t_
      !endif
     !endif
    </td>
    !set pe=!line $se of $percents
    !set p1=!word 1 of $pe
    !set p2=!word 2 of $pe
    <td class="wims_user_sheet_score">
     !if $p1!=$empty
      $p1% $U_done, $U_average $[$p2]/10
     !else
      &nbsp;
     !endif
    </td><td>
     !if showshweight iswordof $class_option
      ($wims_name_coeff
      !line $i of $wlist
      )
     !endif
    </td>
   </tr>
  !next i
 </table>
 <!-- end _widgets/usersheet.phtml -->
!endif
