<!-- _widgets/virtualzone.phtml -->
<span class="menuitem">$V_cls</span>
<span class="menuitem">
 !read ./adm/oneitem.phtml n_participant,1,module=adm/class/classes&type=participant
</span>
<span class="menuitem">
 !read ./adm/oneitem.phtml n_supervisor,1,module=adm/class/classes&type=supervisor
</span>
<span class="menuitem">
 !read ./adm/oneitem.phtml n_example,1,module=adm/class/classes&type=example
</span>
<!-- end _widgets/virtualzone.phtml -->