!if $error!=$empty
 !exit
!endif

!if $condtest1<0
 No! You have made bad manipulations which have led you to a situation
 where the proof of the exercise is no longer possible. The exercise
 is therefore aborted, score=0.
 <p>
 !exit
!endif

!if $cutstop=yes
 No! You have exceeded the limit of allowed steps. The operation is
 aborted, score=0.
 <p>
 !exit
!endif

!if nostatus notwordof $m_options
 !read deduc/$module_language/status.phtml
!endif

!item floor($score/2)+1 of Phew, Well, Yes, Great, Bravo, Congratulations
$ ! You have solved the exercise in $ctstep steps.
!if $ctstep>$m_minsteps
 (It can be done in $m_minsteps steps.)
!endif
Score: $score/10. <small>
($[$ustep-$currstep] stray steps,
$penalty penalties for serious errors)</small>

<p>

