!read adm/title.phtml 3\
$cdt_title\
$wims_name_binfile

!if $error!=$empty
<div class="wims_msg alert">
 !read lang/msg.phtml.$moduclass_lang
 </div>
!endif

!if $erase!=$empty
<p>
$name_erasedfile
 </p>
!endif

!if $quota_free<1
 $name_nodeposit
!else
 !set wims_form_method=file
 !form reply
 <input type="hidden" name="job2" value="deposit" />
 $name_depos:
 <input type="file" size="35" name="wims_deposit" />
 <input type="submit" value="$wims_name_tosave" />

!formend
!endif

!if $flist!=$empty
 <p>$name_available:
 !for f in $flist
  !getfile cdt/$wims_class/$f $f
  $
 !next f
 </p>
 !form reply
 <input type="hidden" name="job2" value="erase" />
 $name_erase:
 !formselect job2 list $flist
 <input type="submit" value="$wims_name_tosave" />

!formend
 <p>
$name_explanation1
</p><p class="wimscenter">
 <span class="tt wims_address">&lt;img src="\filedir/myfile.jpg" alt="myfile"&gt;</span>
</p><p>
$name_explanation2
</p>
!endif

<p>
$(name_availablespace[1]): $quota_total Meg.
$(name_availablespace[2]): $quota_free Meg.
</p>
!!ARIANE already in ariane
!set wims_menu_items=!append line back2,cmd=new&job=home\
to $wims_menu_items

!reset erase,job2
