

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$cdt_title

<center> <b><font size="+1">
 !if $jour_begin!=$empty
  $name_between <font color=green>$name_date</font>
  !if $jour_begin!=$jour_end
   $name_and <font color=green>$name_date2</font>
  !endif
 !endif
 </font></b>
</center> 

!if $cdt_description!=$empty
 <br>$cdt_description
!endif
<p><p>

!if $cdt_nbdate=0
 $name_noinfo1.
 !goto end
!else
 !if $nbligne=0
  !if $jour_begin=$jour_end
   $name_noinfo2.
  !else
   $name_noinfo3.
  !endif
  !goto end
 !endif
!endif

<center>
 $table_header
 $table_hdtr 
  <th>$name_Day</th>
  !if no isin $cdt_supervise
   <th>$name_discipline</th>
  !endif
  <th>$name_inclass</th><th>$name_worktodo</th><th width=30>$name_for</th>
  !if $wims_user=supervisor and yes isin $cdt_supervise
   <th>$wims_name_action</th>
  !endif
 </tr>
 !for i=1 to $nbligne
  !let mem_tr=$table_tr
  !let don=!line $i of $list
  !distribute item $don into jour,file,matiere
  !let m_filedir=$wims_ref_name?session=$wims_session&cmd=getfile&special_parm=cdt/$file
  !let file=wimshome/log/classes/$file/cdt/def/$jour
  !read $file
  !let nbtodo=!itemcnt $date_todo
  $mem_tr
   <td rowspan=$nbtodo>
    !read lang/date.phtml.$moduclass_lang 5,$jour
   </td>
   !if no isin $cdt_supervise
    <td rowspan=$nbtodo>$matiere</td>
   !endif
   <td rowspan=$nbtodo valign="top">
    !read $file content
   </td>
   !if $nbtodo>0
    <td valign="top">
    !read $file todo1
    </td>
    <td>
     !read lang/date.phtml.$moduclass_lang 5,$date_todo
    </td>
   !else
    <td>&nbsp;</td><td>&nbsp;</td>
   !endif
   !if $wims_user=supervisor and yes isin $cdt_supervise
    <td rowspan=$nbtodo>
    !set wims_ref_class=wims_button
    !href cmd=new&job=adddate&filename=$jour $wims_name_change
    &nbsp;
    !set wims_ref_class=wims_button
    !href cmd=new&job=del&filename=$jour $wims_name_erase
   !endif
  </tr>
   !if $nbtodo>1
    !let bgcolor=!positionof char # in $mem_tr
    !let bgcolor=!char $bgcolor to $[$bgcolor+6] of $mem_tr
    !for j=2 to $nbtodo
     <tr bgcolor="$bgcolor">
      <td valign="top">
       !read $file todo$j
      </td>
      <td>
       !let tmp=!item $j of $date_todo
       !read lang/date.phtml.$moduclass_lang 5,$tmp
      </td>
     </tr>
    !next j
   !endif 
 !next i
 $table_end
!if $nbligne>0
 <p>
 !href target=wims_new module=$module&cmd=new&job=work&job2=print&jday=$jday&jmonth=$jmonth&jyear=$jyear&jyear2=$jyear2&jmonth2=$jmonth2&jday2=$jday2 $wims_name_print
!set wims_menu_items=!append line printable,1,module=$module&cmd=new&job=work&job2=print&jday=$jday&jmonth=$jmonth&jyear=$jyear&jyear2=$jyear2&jmonth2=$jmonth2&jday2=$jday2\
  ,0,\
to $wims_menu_items
!endif
 </center>


:end
<p><hr width="40%"> <p>
!read form.phtml 
!tail
