
!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu
!set module_title1=$module_title
!reset module_title
!header
!set module_title=$module_title1

<center>$classname
<h1>$cdt_title</h1>
<font size="+1">Configuratie</font></center> 

<p><hr width="40%"> <p>

De volgende items kunnen worden geconfigureerd :

!form reply
<input type=hidden name=job value=config>
<ul>
 <p><li>Titel &nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <p><li>Omschrijving &nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <p><li>De linknaam op de homepagina &nbsp; : <input size=60 name=cf_link value="$cdt_link"></li> 
 <p><li>
 Laat de
  !href cmd=renew&job=logfile logfile
  </a> van de agenda zien 
  .</li>
</ul>
<p><center><input type=submit name=cf_set value="Opslaan">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Annuleren">
</center> <p></form>
<p>
 !href cmd=reply&job=home Terug
 .
