
!read adm/css.phtml
!read names
!header1

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$cdt_title\
Configuratie

<p><hr width="40%"> <p>

De volgende items kunnen worden geconfigureerd :

!form reply
<input type=hidden name=job value=config>
<ul>
 <li><p>$wims_name_title:<br>
  <input size=60 name=cf_title value="$cf_title">
 <li><p>$wims_name_Description&nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <li><p>De linknaam op de homepagina &nbsp; : <input size=60 name=cf_link value="$cdt_link"></li> 
 <li><p>
 Laat de
  !href cmd=renew&job=logfile logfile
  </a> van de agenda zien 
  .</li>
</ul>
<p><center><input type=submit name=cf_set value="$wims_name_tosave">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="$wims_name_giveup">
</center> <p></form>

!set wims_menu_items=!append line back2,1,cmd=reply&job=home\
to $wims_menu_items
