!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu
!read adm/css.phtml
!header1

<center>$classname
<h1>$cdt_title</h1>
<font size="+1">Configuratie</font></center> 

<p><hr width="40%"> <p>

De volgende items kunnen worden geconfigureerd :

!form reply
<input type=hidden name=job value=config>
<ul>
 <li><p>Titel &nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <li><p>Omschrijving &nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <li><p>De linknaam op de homepagina &nbsp; : <input size=60 name=cf_link value="$cdt_link"></li> 
 <li><p>
 Laat de
  !href cmd=renew&job=logfile logfile
  </a> van de agenda zien 
  .</li>
</ul>
<p><center><input type=submit name=cf_set value="Opslaan">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Annuleren">
</center> <p></form>
!!<p>
!! !href cmd=reply&job=home Terug
!! .
!set wims_menu_items=!append line back2,1,cmd=reply&job=home\
to $wims_menu_items
