!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$cdt_title
<center>
 <font size="+1"><b>Huiswerk
 !if $jour_begin!=$jour_end
  tussen <font color=green>$jyear/$jmonth/$jday</font> en <font color=green>$jyear2/$jmonth2/$jday2</font>
 !else
  voor  <font color=green>
  $jyear/$jmonth/$jday</font>
 !endif
</b></font>
</center> 
<p><p>

!if $nbligne=0
 Er is geen huiswerk opgegeven voor $jyear/$jmonth/$jday.
 <p>
 !goto end
!endif

 !let table_border=1
 $table_header
 $table_hdtr 
  <th>Voor</th>
  !if no isin $cdt_supervise
   <th>Onderwerp</th>
  !endif
  <th>Huiswerk</th><th>te doen</th>
 </tr>
 !for i=1 to $nbligne
  $table_tr
   !let don=!line $i of $list
   !distribute item $don into todo,date,dir,matiere
   !let m_filedir=$wims_ref_name?session=$wims_session&cmd=getfile&special_parm=cdt/$dir
   !read wimshome/log/classes/$dir/cdt/def/$date 
   !let no=!positionof item $todo in $date_todo
   <td>
    !read proc/date.phtml $todo 
   </td>
   !if no isin $cdt_supervise
    <td>$matiere</td>
   !endif
   <td valign=top>
    !read wimshome/log/classes/$dir/cdt/def/$date todo$no
   </td>
   <td>
    !read proc/date.phtml $date
   </td>
  </tr>
 !next i
 $table_end
:end
!!<div class="wims_noprint">
!!<a href="javascript:window.print()">Printen</a> &nbsp; 
!!<a href="javascript:window.close()">Sluit venster</a>
!!</div><!--end of wims_noprint-->
!tail

