
!form reply
<input type="hidden" name="job" value="access" />
$title
 $
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=accessconf $wims_name_help
<div class="wimscenter">
	<textarea name="accessdef" cols="70" rows="15">$accessdef</textarea>
</div>
<div class="wimscenter wimsform">
	<input type="submit" name="save" value="$wims_name_tosave" />
  $
    <input type="submit" name="abandon" value="$wims_name_giveup" class="wims_secondary_button" />
</div>

!formend

!reset job, accessdef
