!if $noarch=yes
 $name_restore5
 !exit
!endif

!if $job2!=first
 !changeto arch/$job2.phtml
!endif

$name_intro

!href cmd=reply&job=arch&job2=download&selection=all&format=zip zip
,
!href cmd=reply&job=arch&job2=download&selection=all&format=tgz tgz
 $wims_name_or
!href cmd=reply&job=arch&job2=download&selection=all&format=tar.gz tar.gz
.
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=download $wims_name_help

<p><hr> <p>

!if $test_sharing!=$empty
 $(name_forbiddenrestore).
 !exit
!endif

!set wims_form_method=file
!form reply
<input type="hidden" name="job" value="arch">
<input type="hidden" name="job2" value="upload">
$name_tosend,
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=upload $wims_name_help
, $name_namefile:
<p>
<input type="file" name="wims_deposit" size="40">

<p> <input type="submit" value="$wims_name_send">
($name_help).
</form> <p>

