
!form reply

$name_intro_authtype
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=authtype $wims_name_help
<p style="text-align:center;">
	!formselect up_authidp list $authidp_method_list prompt $name_method_list
</p>

<input type="hidden" name="up_$job" id="" value="authtype" />

<fieldset>
	<legend>CAS Settings</legend>
	<label for="up_cas_auth">CAS URL</label>
	<input size="30" name="up_cas_auth" id="up_cas_auth" value="$class_cas_auth" />
</fieldset>

<br class="spacer" />

<fieldset>
	<legend>PHP Settings</legend>
	<label for="up_php_auth">PHP</label>
	<input size="30" name="up_php_auth" id="up_php_auth" value="$class_php_auth" />
</fieldset>

<br class="spacer" />

<fieldset>
	<legend>LDAP Settings</legend>
	<ul class="class_settings">
		<li class="setting_item">
			<label for="up_ldap_auth">ldap auth <span class="field_required">*</span></label>
			<input size="30" name="up_ldap_auth" id="up_ldap_auth" value="$class_ldap_auth" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_port">ldap port</label>
			<input size="30" name="up_ldap_port" id="up_ldap_port" value="$class_ldap_port" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_version">ldap version</label>
			<input size="30" name="up_ldap_version" id="up_ldap_version" value="$class_ldap_version" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_base">ldap base <span class="field_required">*</span></label>
			<input size="30" name="up_ldap_base" id="up_ldap_base" value="$class_ldap_base" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_branch">ldap branch <span class="field_required">*</span></label>
			<input size="30" name="up_ldap_branch" id="up_ldap_branch" value="$class_ldap_branch" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_uid">ldap uid</label>
			<input size="30" name="up_ldap_uid" id="up_ldap_uid" value="$class_ldap_uid" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_login">ldap login</label>
			<input size="30" name="up_ldap_login" id="up_ldap_login" value="$class_ldap_login" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_regnum">ldap regnum</label>
			<input size="30" name="up_ldap_regnum" id="up_ldap_regnum" value="$class_ldap_regnum" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_email">ldap email</label>
			<input size="30" name="up_ldap_email" id="up_ldap_email" value="$class_ldap_email" />
		</li>
		<li class="setting_item">
			<label for="up_ldap_photourl">ldap photourl</label>
			<input size="30" name="up_ldap_photourl" id="up_ldap_photourl" value="$class_ldap_photourl" />
		</li>n
	</ul>
</fieldset>

<p class="wimscenter">
	<input type="submit" name="save" id="" value="$wims_name_tosave" />
	&nbsp;
	<input type="submit" name="abandon" id="" value="$wims_name_giveup" />
</p>

!formend

!reset up_authidp up_cas_auth up_php_auth up_ldap_auth up_ldap_port up_ldap_version up_ldap_base up_ldap_branch up_ldap_uid up_ldap_login \
  up_ldap_email up_ldap_regnum up_ldap_photourl
