!form reply
 <input type="hidden" name="job" value="grestrict" />
 <fieldset class="property_fields halfwidth blockcenter">
   <div class="field box">
    <label for="allow">$name_allowedsites</label>
    <input size="35" name="allow" id="allow" value="$allow" />
   </div>
   <div class="field box">
     <label for="except">$name_excepted</label>
     <input size="35" name="except" id="except" value="$except" />
   </div>
   <div class="wimscenter wimsform">
     <input type="submit" name="save" value="$wims_name_tosave" />
     <input type="submit" name="abandon" value="$wims_name_giveup" class="wims_secondary_button" />
   </div>
</fieldset>

!formend
