
!if $save!=$empty
 !read scripts/setdef.proc
 !defread wimshome/log/classes/$wims_class/.def
 wims_class_log=Modify class configuration $wims_realuser
!endif

!read adm/du $wims_home/log/classes/$wims_class

!if $wims_superclass!=$empty
 supertype=!defof class_type in wimshome/log/classes/$wims_superclass/.def
 class_expiration=!defof class_expiration in wimshome/log/classes/$wims_superclass/.def
 classdepth=!translate internal / to , in $wims_class
 classdepth=!itemcnt $classdepth
!endif

