!if $supertype=4 and $classdepth<=3
<p><center>
 !href module=adm/class/gateway $wims_name_struct
</center>
!endif

!form reply
<input type=hidden name=up_job value=list>
$table_header
$table_tr<td align=right>$name_name_institution
<td colspan=3>
!if $supertype notin 24 or $classdepth=1
 <input size=50 name=up_institution value="$class_institution">
!else
 $class_institution
!endif
$table_tr<td align=right>$name_name_class
<td colspan=3>
<input size=50 name=up_description value="$class_description">
$table_tr<td align=right>$name_secure
<small>
!href cmd=help&special_parm=config&special_parm2=secure $wims_name_help
 </small>
<td colspan=3>
<input size=50 name=up_secure value="$class_secure">
$table_tr<td align=right>$wims_name_nameteacher
<small>
!href cmd=help&special_parm=config&special_parm2=supervisor $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_supervisor value="$class_supervisor">
$table_tr<td align=right>$wims_name_email
<small>
!href cmd=help&special_parm=config&special_parm2=email $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_email value="$class_email">
$table_tr<td align=right>$name_optionword
<small>
!href cmd=help&special_parm=config&special_parm2=option $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_option value="$class_option">
</td></tr>
!if $wims_supertype!=4 or $class_typename!=class
$table_tr<td align=right>
$name_devaccount
<small>
!href cmd=help&special_parm=config&special_parm2=modtoolchg $wims_name_help
</small>
</td><td colspan=3>
!set modtoolchg=1
!formcheckbox modtoolchg list 0 prompt $wims_name_change
</td></tr>
!endif
$table_tr<td align=right>
$name_lock_level
<small>
!href cmd=help&special_parm=config&special_parm2=lock $wims_name_help
</small>
</td><td>
!set up_lock=$class_lock
!default up_lock=0
!formselect up_lock list 0,2,3,4,5,6,7
<td align=right>$name_bestscore
<small>
!href cmd=help&special_parm=config&special_parm2=topscores $wims_name_help
 </small>
!default class_topscores=0
!default class_anonymtopscores=yes
!set up_anonymtopscores=$class_anonymtopscores
<td><input size=3 name=up_topscores value="$class_topscores">
/
!formselect up_anonymtopscores list no,yes prompt $wims_name_no,$wims_name_yes
</td></tr>
$table_tr<td align=right>$wims_name_Language
<small>
!href cmd=help&special_parm=config&special_parm2=lang $wims_name_help
 </small>
<td>
!set up_lang=$class_lang
!set langs=!words2items $wims_site_languages
!formselect up_lang list $langs
</td>
<td align=right>
$name_level
<small>
!href cmd=help&special_parm=config&special_parm2=level $wims_name_help
 </small>
<td>
!set up_level=$class_level
!formselect up_level list $levellist
$table_tr<td align=right>$name_limit
<small>
!href cmd=help&special_parm=config&special_parm2=limit $wims_name_help
 </small>
<td><input size=5 name=up_limit value="$class_limit">
<td align=right>$name_expirationdate
<small><b>yyyymmdd</b></small>
<small>
!href cmd=help&special_parm=config&special_parm2=expiration $wims_name_help
 </small>
<td>
!if $class_type notin 13
 <input size=8 maxlength=8 name=up_expiration value="$class_expiration">
!else
 <tt>$class_expiration</tt>
!endif
$table_tr<td align=right>$name_register_exo
<small>
!href cmd=help&special_parm=config&special_parm2=exolog $wims_name_help
 </small>
!default class_exolog=0
<td><input size=3 name=up_exolog value="$class_exolog">
<td align=right>$name_register_exam
<small>
!href cmd=help&special_parm=config&special_parm2=examlog $wims_name_help
 </small>
!default class_examlog=$wims_examlog_limit
<input size=3 name=up_examlog value="$class_examlog">
<td>$name_visible
<small>
!href cmd=help&special_parm=config&special_parm2=examshow $wims_name_help
 </small>
!default class_examshow=yes
!set up_examshow=$class_examshow
!formselect up_examshow list no,yes prompt $wims_name_no,$wims_name_yes
!set up_ent=$class_ent
$table_tr<td align=right>$wims_name_config_ent
<small>
!href cmd=help&special_parm=config&special_parm2=ent $wims_name_help
 </small>
<td colspan=3>
<input size=50 name=up_ent value="$class_ent">
!if $class_type iswordof 0 4
!set up_external_auth=$class_external_auth
$table_tr<td align=right>$wims_name_external_auth
<small>
!href cmd=help&special_parm=config&special_parm2=external_auth $wims_name_help
 </small>
<td colspan=3>
<textarea name=up_external_auth cols=50 rows=6>$class_external_auth</textarea>
!!<input size=50 name=up_external_auth value="$class_external_auth">
!set up_mixed_external_auth=$class_mixed_external_auth
!default up_mixed_external_auth=0
!formradio up_mixed_external_auth list 0,1,2 prompt $wims_name_no, $name_mix_auth, $wims_name_yes
!endif
$table_hdtr<td align=center colspan=4>
<input type=submit name=save value="$wims_name_tosave">
&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
$table_end <p>
</form>

$name_apparence: 
!href module=adm/light&phtml=useropts.phtml.$lang $name_pref 
.
!href cmd=reply&job=present $wims_name_config_present
.
!href cmd=reply&job=oefdefault $wims_name_config_oef
.
<p>
!if $class_type iswordof 2 3 4

 !href cmd=reply&job=propagate $name_dependant_zone
!endif
<p>
!href cmd=reply&job=neighbor&job2=first $name_neigh
,
!href cmd=reply&job=connect&job2=first $name_link
.
<p>
!if $classdepth<=1 

!href cmd=reply&job=authtype $name_useauth
$name_ldap.
 <p>
!endif

$name_index<sup>
!href cmd=help&special_parm=index $wims_name_help
</sup>:
!if $class_type=4
!href cmd=reply&job=index&job2=structure $wims_name_zones
,
!endif
!if $class_type=4 or $class_type=2
!href cmd=reply&job=index&job2=teacherlist $wims_name_teachers
,
!endif
!href cmd=reply&job=index&job2=userlist $wims_name_participants
,
!href cmd=reply&job=index&job2=oef $wims_name_exercises
,
!href cmd=reply&job=index&job2=doc $wims_name_docs
.
<p>
!href cmd=reply&job=security $wims_name_config_secure
  ($name_change
!href module=adm/class/passwd $wims_name_config_passwd
).
<p>
!href cmd=reply&job=arch&job2=first $name_load
, 
!href cmd=reply&job=access $name_restriction1
, 
 !href cmd=reply&job=grestrict $name_restriction2 
$name_score,
!href cmd=reply&job=clean $name_clean
.
<p>
$name_config
!href module=adm/forum/mboard&job=config $name_forum
, 
!href module=adm/class/motd $name_motd
,  
!href module=adm/class/cdt&job=config $name_cdt
,  
!href module=adm/class/livret&job=config $name_livret
,  
!href module=adm/class/sequence&job=config $name_seq
.
<p>
$name_disk: $du MB. ($name_limit2 $wims_class_quota.)


!reset up_institution, up_description, up_supervisor, up_email, \
	up_lang, up_level, up_limit, up_topscores, up_anonymtopscores, up_expiration, up_secure, up_lock,\
	up_option,up_exolog,up_examlog,up_examshow,up_ent,up_external_auth,up_mixed_external_auth,\
	pr_homepage, pr_bgcolor, pr_refcolor, pr_ref_menucolor,pr_bgimg, pr_css, pr_theme, pr_theme_icon

