!read lang/new.phtml.$moduclass_lang

!if $supertype=4 and $classdepth<=3
  <div class="wimscenter">
   !href module=adm/class/gateway $wims_name_struct
  </div>
!endif
<ul class="wims_nopuce"><li>
<ul><li>
!href cmd=reply&job=connectlink $name_connectlink
 ($name_connectlinkhelp)</li><li>
$name_index
 $
!set wims_ref_class=wims_button
!if $class_type=4
!href cmd=reply&job=index&job2=structure $wims_name_zones
 $
!set wims_ref_class=wims_button
!endif
 $
!set wims_ref_class=wims_button
!if $class_type=4 or $class_type=2
!href cmd=reply&job=index&job2=teacherlist $wims_name_teachers
 $
!set wims_ref_class=wims_button
!endif
!href cmd=reply&job=index&job2=userlist $wims_name_participants
 $
!set wims_ref_class=wims_button
!href cmd=reply&job=index&job2=oef $wims_name_exercises
 $
!set wims_ref_class=wims_button
!href cmd=reply&job=index&job2=doc $wims_name_docs
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=index $wims_name_help
</li>
!if $class_type iswordof 2 3 4
<li>
 !href cmd=reply&job=propagate $name_dependant_zone
</li>
!endif
</ul>
</li><li>
 <strong>$name_newrem2</strong>
<ul><li>
$name_config
!href target=wims_help module=adm/forum/mboard&job=config $name_forum
,
!href target=wims_help module=adm/class/motd $name_motd
,
!href target=wims_help module=adm/class/cdt&job=config $name_cdt
,
!href target=wims_help module=adm/class/livret&job=config $name_livret
,
!href target=wims_help module=adm/class/sequence&job=config $name_seq
.
</li><li>
!set t_=!defof module_title in wimshome/public_html/modules/adm/light/pages/useropts.phtml.$lang
!href target=wims_help module=adm/light&phtml=useropts.phtml.$lang $t_
 ($name_pref).
</li></ul></li><li>
<strong>$name_newrem1</strong>
<ul><li>
!href cmd=reply&job=list $wims_name_config_list
,
!href cmd=reply&job=oefdefault $wims_name_config_oef
</li><li>
$name_apparence :
!href cmd=reply&job=present $wims_name_config_present
.
</li>
!if $classdepth<=1
<li>
!href cmd=reply&job=authtype $name_useauth
$name_ldap.
</li>
!endif
<li>
!href cmd=reply&job=security $wims_name_config_secure
  ($name_change
!href module=adm/class/passwd $wims_name_config_passwd
)
</li><li>
!href cmd=reply&job=arch&job2=first $name_load
,
!href cmd=reply&job=clean $name_clean
</li><li>
!href cmd=reply&job=access $name_restriction1
,
 !href cmd=reply&job=grestrict $name_restriction2
$name_score.
</li><li>
!href cmd=reply&job=neighbor&job2=first $name_neigh
,
!href cmd=reply&job=connect&job2=first $name_link
.
</li></ul>
</li></ul>
$name_disk: $du MB. ($name_limit2 $wims_class_quota.)
</p>
