!!!### language independant
!set wims_form_method=file
!form reply
<input type="hidden" name="up_job" value="present">
<p></p>$table_header
$table_tr<td align="right">$name_logo
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=logo $wims_name_help

</td><td><input size="35" name="pr_logo" value="$class_logo">
</td><td align="right">$name_position_logo
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=logo $wims_name_help
</td><td>
!set pr_logoside=$class_logoside
!formselect pr_logoside list left,right prompt $name_logo_side
</td></tr>
$table_tr<td align="right">$wims_name_class_home
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=homepage $wims_name_help
</td><td colspan="3"><input size="35" name="pr_homepage" value="$class_homepage">
</td></tr>
$table_tr<td align="right">$name_background_color
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_bgcolor" value="$class_bgcolor">
</td><td align="right">$name_image
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgimg $wims_name_help

</td><td><input size="35" name="pr_bgimg" value="$class_bgimg">
</td></tr>
$table_tr<td align="right">$name_menu_color
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_refcolor" value="$class_refcolor">
</td><td align="right">$name_refmenu_color
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_ref_menucolor" value="$class_ref_menucolor">
</td></tr>

$table_tr<td align="right">$name_button_bgcolor
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_ref_button_bgcolor" value="$class_ref_button_bgcolor">
</td><td align="right">$name_button_color
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_ref_button_color" value="$class_ref_button_color">
</td></tr>

$table_tr<td align="right">$name_button_help_bgcolor
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_ref_button_help_bgcolor" value="$class_ref_button_help_bgcolor">
</td><td align="right">$name_button_help_color
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
</td><td><input size="10" name="pr_ref_button_help_color" value="$class_ref_button_help_color">
</td></tr>


$table_tr
 <td align="right">$name_colorscore</td>
 <td colspan="3">
  !for col=1 to 11
   &nbsp; <input size="5" name="pr_sccolor$col" value="$(class_scorecolor[$col])">
  !next col
 </td>
</tr>

$table_tr<td align="right">$name_theme
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=theme $wims_name_help
</td><td>
!set pr_theme=$class_theme
!formselect pr_theme list $themelist
</td><td align="right">$name_theme_icon
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=icon $wims_name_help

</td><td>
!set pr_theme_icon=$class_theme_icon
!formselect pr_theme_icon list $iconlist
</td></tr>
$table_tr<td align="right">$name_css (css)
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=config&special_parm2=css $wims_name_help

</td><td>
!set pr_css=$class_css
!formselect pr_css list $csslist

</td><td colspan="2">$table_header
<tr>
<td>$name_css_transfer ($name_content_style)</td>
<td><input type="file" name="wims_deposit">
</td></tr>
<tr>
<td> $name_content_style2
</td><td><textarea rows="6" cols="45" name="pr_cssfile">
$cssfile
</textarea>
</td></tr>
</table></td></tr>

$table_hdtr<td align="center" colspan="4">
<input type="submit" name="save" value="$wims_name_tosave">
&nbsp;
<input type="submit" name="abandon" value="$wims_name_giveup">
</td></tr>
$table_end <p>
</form>


!reset pr_logo, pr_logoside, pr_bgcolor,pr_refcolor, pr_ref_menucolor,\
  pr_ref_button_color,pr_ref_button_bgcolor,pr_ref_button_help_color,pr_ref_button_help_bgcolor, \
  pr_bgimg, pr_theme, pr_css, pr_theme_icon, pr_homepage, pr_cssfile

