
<ul>
<li>
$wims_name_passwd :
!href module=adm/class/passwd&job=class $wims_name_class
,
!if $class_type=4 or $class_type=2
 !let tmp=$wims_name_supervisor
!else
 !let tmp=$wims_name_nameteacher
!endif
!href module=adm/class/passwd&job=user $tmp
</li>
<li>
!href cmd=renew&job=log $name_see_activity1.
($name_see_activity2)
</li>
<li>
!href cmd=reply&job=grestrict $name_restriction1
$name_restriction2
</li>
<li>$name_otherrestriction1
!href cmd=renew&job=list $name_otherrestriction2
.
</li>
</ul>

