!read adm/title.phtml 3\
\
Dipendenza di risorse nel corso

Possono eserci dipendenze anche molto complicate tra diversi tipi di
materiali didattici presenti in un corso, dipendenze di cui probabilmente
il docente medio non è consapevole.
<p>
Per esempio i temi d'esame sono definiti a partire dai test di autovalutazione,
gli ultimi potrebbero utilizzare esercizi definiti nel corso. Se si 
elimina uno di questi esercizi, si potrebbe compromettere il funzionamento
del tema d'esame.
<p>
Inoltre i punteggi degli studenti sono valutati nel momento in cui viene
completato ogni esercizio sulla base dei criteri attivi in quel momento.
Quindi se si modifica un settaggio di un test di autovalutazione attivo
potrebbe non essere più possibile avere un calcolo dei punteggi corretti,
anche se il registo delle attività non è in alcun modo modificato.

