
<b>Permettere agli altri corsi di condividere i tuoi materiali didattici</b>.
<p>
Se vuoi permettere ai
!href cmd=help&special_parm=neighbor corsi Vicini
 di
!href cmd=help&special_parm=share condividere
 i tuoi materiali didattici, tieni presente i rischi che comportano per
 il tuo corso.
</p><p>
Una volta che un certo materiale è stato messo in condivizione, il docente
dell'altro corso può a sua volta renderlo condivisibile a altri corsi.
Significa anche che può modificare tali materiali, non escludendo
la possibilità di danni (involontari).
</p><p>
In particolare è particolarmente rischioso permettere a altri di condividere
l'account docente. Ad esempio se l'altro docente modifica la password di
gestione del corso (o se nell'altro corso si verifica un'intrusione), puoi
correre il rischio di perdere completamente il controllo del corso.
</p><p>
Quando possibile, è meglio invitare l'altro corso a
!href cmd=help&special_parm=import importare
 i materiali didattici, piuttosto che metterli in condivisione.
</p>
<p>
Il y a des dépendances entre les ressources : le partage de certaines vous obligera à en partager d'autres (par exemple les examens sont dépendants des feuilles d'exercices).
</p>
<p>
Les questionnaires ne peuvent pas être partagés si l'un d'entre eux est un modèle préparé utilisant des variables techniques.
</p>
