
<b>Allow other classes to share your teaching materials</b>.
<br>
If you allow the
!href cmd=help&special_parm=neighbor Neighboring class
 to
!href cmd=help&special_parm=share share
 your teaching materials, you should also be aware of the risks this brings to your
class.
<p>
Once you declare a type of teaching materials sharable, the other class may
effectively share them. This means that it may modify your teaching materials,
including damaging it (by a false manoeuvre).
<p>
It is particularly risky to allow others share your supervisor account. If
the other changes the supervisor password (or if there is an intrusion to
the other class), you will lose control of your class.
<p>
Whenever possible, it is preferable to invite the other class to
!href cmd=help&special_parm=import import
 your teaching materials, rather than letting it to share them with you.
 
