
!set classname=<b><font color=green>$wims_classname</font></b>,\
 <b><font color=green>$wims_institutionname</font></b>
 
!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

!set title=配置与维护
!if $job=arch
 !set title=备份与恢复
 !goto commun
!endif

!if $job=clean
 !set title=清除班级
 !goto commun
!endif

!if $job=neighbor
 !set title=相邻班
 !distribute lines 相邻关系<br>声明\
   资源共享\
   被你\
   被他人\
   激活互相共享.\
   你正在共享它的资源.\
   共享你的资源.\
   互相允许共享.\
   允许共享你的资源.\
   允许你共享它的资源.\
   停止此共享\
   共享\
   导入所有的人\
   教学资源\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3,name_stopsharing,name_share,name_everybodyimport,name_teaching
 !goto commun
!endif

!if $job=connect
 !set title=连接到其它服务器/平台
 !goto commun
!endif

!if $job=access
 !set title=资源存取配置
 !goto commun
!endif

!if $job2=addshare
 !set title=分享班级资源
 !goto commun
!endif

!if $job=grestrict
 !set title=得分限制
 !goto commun
!endif

!if $job=present
 !set title=班级外观的配置
 !goto commun
!endif

!if $job=oefdefault
 !set title=OEF 模块的默认设置
 !goto commun
!endif

!if $job=security
 !set title=可用的安全管理活动
 !goto commun
!endif

!if $job=authtype
 !set title=Ldap 身份验证
 !set name_intro_authtype=如果你使用 ldap 验证,\
 请选 <tt>ldap</tt> 并填写此页.
 !goto commun
!endif

:commun
!distribute line 身份验证\
我的个人喜好\
资源限制\
OEF 参数\
相邻班\
安全管理\
选择性清除\
重建索引\
其它服务器\
密码\
传送配置到分班\
外观\
得分限制\
平台地址\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items 分班,参加者,练习,文件,教师\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers


!distribute lines 安全主机\
   格式页\
   班级图标\
   图标位置\
   左上角,右上角\
   班级的格式主题\
   图标\
   程度\
   授权记录分数的主机\
   注册密码\
   教师密码\
   练习与考试的注册限制\
   到平台或网页的连接\
   页的背景色\
   菜单的背景色\
   菜单的链接的颜色\
   背景图像文件\
   下载 css 格式文件\
   分数颜色的变化率 (从 0 至 10)\
   into name_secure,name_css,name_logo,name_position_logo,name_logo_side,name_theme,\
   name_theme_icon,name_level,name_security,name_password,name_supass,name_exolog,name_ent,\
  name_background_color,name_menu_color,name_refmenu_color,name_image,name_css_transfer,name_colorscore

!set name_content_style =你可以在这里定义你的班级范围的格式页\
<br>(当 <tt>$name_css</tt> 是在 <tt>class</tt>)&nbsp;:

!set name_content_style2=或把格式页复制在这里

