
!if $wims_supertype=2
 !set name_thisclass=学区
 !set name_subclasses=分班
!else
 !set name_thisclass=当前区域
 !set name_subclasses=子区域
!endif

!if $confirm!=$empty and $propagate!=$empty
配置已成功地发送到 $name_subclasses: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
你可以选择发送 $name_thisclass 的下列配置到所有的 $name_subclasses: <p>

 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="$wims_name_send">
 </form>
!endif
<p>
请注意
$name_subclasses 不会自动共享 $name_thisclass 以后对设置的修改.
如果你要 $name_subclasses 作同样修改, 你必须发送过去. 

