!set disable_zoom=yes
!! no mathml zooming in dynapi
!if $wims_dynapi=loaded
 !exit
!endif
!set wims_dynapi=loaded

<script type="text/javascript" src="scripts/js/dynapi3x/src/dynapi.js"></script>
<script type="text/javascript">
dynapi.library.setPath('scripts/js/dynapi3x/src/');
dynapi.library.include('dynapi.api');
dynapi.library.include('dynapi.api.ext.DragEvent');
!if $wims_html_onload!=$empty
 dynapi.onLoad(function() {$wims_html_onload});
!endif
</script>

