!if $wims_read_parm!=
 !set wims_html_onload=!append word speckInit(); to $wims_html_onload
 !set wims_html_header= !append line <link href="scripts/js/speck/speck.css" rel="stylesheet" type="text/css">\
 <script type="text/javascript" src="scripts/js/speck/speck.js"></script>\
 <script language="javascript" type="text/javascript">\
  function editthis(){ var input=iEdit['$wims_read_parm'].html();\
  document.getElementById('$wims_read_parm').innerHTML=input;\
 }\
 </script> to $wims_html_header

  !set wims_id=!append word id="$wims_read_parm" class="iEdit" to $wims_id
  !set wims_on_click=!append word onclick="javascript:editthis();" to $wims_on_click
 !endif
 
 !default wims_id=
 !default wims_on_click=



