
!if $remcnt>0
 !set wims_ref_anchor=#infogot
 !form reply
 !if $gotcnt<1
  <br>Om dit probleem op te lossen mag je 
  <input type=submit value="vragen stellen">
 !else
  <br>Je kunt nu door gaan met
  <input type=submit value="vragen stellen">
 !endif
 over $objname:
 !formselect ask list 0,$remlist prompt ?? Kies je vraag ??,$prompts
 !if $comment!=$empty
  <br>$comment
 !endif
 <br></form>
 <small><b>Attentie</b>. Je eindresultaat hangt af van het 
 aantal vragen dat je stelt. Er staat ook "straf" op het stellen van
 onzinnige vragen.</small> <br>
 <hr width="50%"> <br>
!endif

!if $gotcnt<1
 !exit
!endif

!set wims_ref_anchor=#ans
!form reply
 !if $remcnt>0
 Wanneer je denkt genoeg informatie te hebben om het probleem op te lossen,
 !else
 Wacht nu even
 !endif
 <input type=submit value="geef je antwoord">&nbsp;:<br>
 !read $deffile form
</form>


