
!read adm/title.phtml 1\
$classname\
$name_title_examcheck

!if _check isin $session
 !set error=bad_op
 !goto msg
!endif

!if $error!=$empty
 :msg
 <div class="msg">
  !read lang/msg.phtml.$moduclass_lang
 </div>
!else
 !if $checksessions=$empty
  <p class="no_exampart">
   $name_no_exampart
  </p>
 !else
  <p class="exampart">
   $name_exampart
  </p>
  $table_header
  $table_hdtr<th rowspan="2">$name_Session</th><th rowspan="2">$name_Exam</th><th rowspan="2">$name_Score<span class="small">/$scoremax</span></th>
  <th colspan="$maxexo">$name_Exercise </th>
  <th rowspan="2">$name_Start</th>
  <th rowspan="2">$name_Duration</th></tr>
  $table_hdtr
   !for i=1 to $maxexo
    <th>$i</th>
   !next i
  </tr>
  !for ses in $checksessions
   !set pos_ses=!positionof item $ses in $checksessions
   !for x in $(exam_$(pos_ses))
    $table_tr<td class="small">$ses</td>
    <td>$x</td>
    <td>$[rint($(score$(pos_ses)_$x)*$scoremax)/10]</td>
    !let nbx=!recordcnt wimshome/log/classes/$wims_class/exams/.exam$x
    !for i=1 to $nbx
      <td>
      !!calculate in adm/class/userscore
      !if $(Exam_$(x)_$(pos_ses)[$i])!=$empty
        !set s=$(Exam_$(x)_$(pos_ses)[$i])
      !else
        !if $(duree$(pos_ses)_$x)=$empty
         !set s=&dagger;
        !else
         !set s=??
        !endif
      !endif
      !href target=wims_check module=$module&cmd=new&job=examcheck&checkuser=$checkuser&checksession=$ses&checkexo=$x.$i&checkstep=1 $s
     </td>
    !next i
    !if $nbx<$maxexo
     !for i=$[$nbx+1] to $maxexo
      <td style="background-image:url(gifs/bg/crossgrey.gif)">&nbsp;</td>
     !next i
    !endif
   <td class="small">
    !read date.phtml $(start$(pos_ses)_$x)
   </td>
   <td class="small">
    !if $(duree$(pos_ses)_$x)!=$empty
      !set tmp=!exec pari divrem($(duree$(pos_ses)_$x),60)~
      !item 1 of $tmp
$ $
      !char 1 to 3 of $name_minutes
$ $
      !item 2 of $tmp
    !endif
   </td>
  </tr>
    !next x
  !next sess
  $table_end
 !endif
!endif
!if $wims_user!=supervisor
 !set wims_menu_items=!append line myscore,1,cmd=reply&job=getuser&getuser=$checkuser\
to $wims_menu_items
!else
 !set wims_menu_items=!append line scores,1,cmd=reply&job=getuser&getuser=$checkuser\
to $wims_menu_items
 !read adm/class/getnextuser $wims_class,$checkuser,examcheck,checkuser
 !set wims_menu_items=!append line itemsep,0,\
 part_list,1,cmd=resume\
 to $wims_menu_items
!endif
