!nocache
<div class="oefanswer">

!nocache
!if bad_exo iswordof $error
 !exit
!endif
!read ./oef/$module_language/answer.phtml
<div id="answeranalysis">
<div class="legend oefanswername">$name_answeranalysis.</div>
<div class="content">
<table border=0>
!distribute item 1,1 into cntr,cntc
!for t in $ansorder
 !set i=$(cnt$t)
 !if $oefsteps=$empty or $t$i isitemof $gotsteps
  !read oef/answer$t.phtml
 !endif
 !advance cnt$t
!next t

!if $conditioncnt>0
 !if $embedded_bracket!=$empty
  <tr><td align="left" colspan=2 nowrap><small>$embedded_bracket</small></td></tr>
 !endif
!endif
!for i in $condlist
 !if hide notwordof $(condoption$i)
  <tr><td colspan=2><b>$(condname$i)</b>:<td>
  !item $(condtest$i)+1 of $condbad,$condgood
 !endif
!next i

</table>

!if $feedbackcnt>0
 !read $deffile feedback
!endif

!if $solution!=$empty and ($presentsol>1 or ($presentsol=1 and $score<10))
 <p><b>$name_Solution.</b>
 !if $solution!=$executed_str or $oef2wims_version<3.10
  $solution
 !else
  !read $deffile solution
 !endif
!endif

!if $m_reply_err != $empty
 <pre><font color=red>
 $m_reply_err
 </font></pre>
!endif
</div><!--content-->
</div><!--answeranalysis-->
</div><!--oefanswer-->
