!if $wims_read_parm=$empty
 !exit
!endif

!set pp=!trim $wims_read_parm
!set pp=!replace internal \\ by ///?/?/?/// in $pp
!set pp=!replace internal \ by $$m_ in $pp
!set pp=!replace internal ///?/?/?/// by \\ in $pp
!set s_=!line 1 of $pp

!set test=!text remove ,0123456789 in $s_
!set testcnt=!itemcnt $s_
!if $test notsametext $empty or $s_=$empty or $testcnt!=2
  !exit
!endif


!set pp=!line 2 to -1 of $pp
!set pp=!translate internal $	$ to $\
$ in $pp

!if copy isin $pp
  !set line_cnt=!linecnt $pp
  !for l_=1 to $line_cnt
    !set line=!line $l_ of $pp
    !if copy isin $line
      !set im=!item -1 of $line
      !if / notin $im
        !set pp=!replace line number $l_ by $(line[1..-2]),$imagedir/$im in $pp
      !endif
    !endif
   !next
!endif

!set pp=!trim $pp
!!need a space at the end
!set pp=!rows2lines $pp$ $

!set canvasdraw_out=!exec canvasdraw\
size $s_\
$pp

!set $canvasdraw_out= !replace internal , by in $canvasdraw_out

$canvasdraw_out
