
!! Color legend, when good answer is set to be displayed (presentgood), and there is at least 1 answeranalysis

!if $presentgood!=0
  !read ./oef/$module_language/answer.phtml
  <div id="oef_indlegend" class="wims_widget_box float_right small">
    <h3 class="title_box" onclick="jQuery('#oef_indlegend .box_content').slideToggle();" style="cursor:pointer;">$oef_color_legend:</h3>
    <div class="box_content">
        <ul>
          <li class="oef_indgood">$indgood</li>
          <li class="oef_indbad">$indbad</li>
          <li class="oef_indforget">$indforget</li>
        </ul>
    </div>
  </div>
!endif