<div class="oefhint">
!set hh=!trim $hint
!if $hh=$empty or $givehint<1
!!!read oef/$module_language/hint.phtml
 <div class="wimscenter">
!set wims_ref_class=wims_button  
 !href cmd=resume $wims_name_resume
.
 </div>
 !exit
!endif

<b>$name_Hint.</b>
!if $hint!=$executed_str or $oef2wims_version<3.10
 $hint
!else
 !read $deffile hint
!endif
 <div class="wimscenter">
!set wims_ref_class=wims_button 
!href cmd=resume $wims_name_resume
</div>
</div><!--oefhint-->

