!nocache
!if $oef_test=yes
 !set renewlink=cmd=next&retest=again
 !!$header_js
 !goto tester
!else
!if $exocnt=1
   !set exoo=!item 1 of $exolist
   !if $module_init_parm=$empty
    !set module_init_parm=exo=$exoo
   !else
     !if &exo notin &$module_init_parm
       !set module_init_parm=exo=$exoo&$module_init_parm
     !endif
   !endif
!endif
 !set init_parm=!translate + to $ $ in $module_init_parm
 !set init_parm=!replace internal $\
$ by ; in $init_parm
 !set renewlink=cmd=renew&worksheet=$worksheet&$init_parm
!endif

!if $(title_$lang)!=$empty
  !set title=$(title_$lang)
!endif

!if $title!=$empty
 !set module_title=$title
 !set module_author=$author
 !set module_address=$email
!endif
!if $printing=yes
 !changeto oef/print.phtml
!endif

!if 0$delay2>0 and $status!=$empty
 !set now_=$wims_nowseconds
 !read js/chrono.phtml $[max(0,$delay1-($now_-$starttime))]
!endif
!set wims_html_header=!append line $header_js to $wims_html_header
!set wims_html_header=!append line $oefcss to $wims_html_header

!header1
<h1 class="oeftitle">
!!!if $wims_exo!=$empty
!! $wims_name_sheet $wims_sheet - $wims_name_Exercise $wims_exo
!!!else
 $title
!!!endif
</h1>

!if $module_checkdata!=yes
 !read oef/$modu_lang/nodata.phtml
 !goto end
!endif

!if $title=$empty
 $name_emptytitle <p style="text-align:center">
 !set wims_ref_class=wims_button
 !href module=$module $name_restart
  $wims_name_or
 !set wims_ref_class=wims_button
 !href $ $wims_name_giveup
 &nbsp; </p>
 !goto end
!endif

!if 0$delay1>0 and $status!=$empty
 <form target="#" name="chrono">
 <center>
 <table border="1" bgcolor="$wims_ref_bgcolor">
 <tr><td> &nbsp;<span class="wims_warning">$wims_name_warning!</span>
 !if $qnum>1
  $name_serie_limit
 !else
  $name_exo_limit
 !endif
 <input size="4" name="clock" readonly onFocus="this.blur();">
 </td></tr></table>
 </center>
 </form>
!endif

:tester
!read oef/present.phtml

!if $wims_theme_version= or $wims_theme_version<1 
<center><hr width="50%"></center>
!endif

!if $cmd=hint
 !read oef/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read oef/msg.phtml
  !if $wims_theme_version= or $wims_theme_version<1 
   <center><hr width="50%"></center>
  !endif
 !endif
 !read oef/form.phtml
 
 <div id="oef_actions">
 !if $hint!=$empty and $givehint>0
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_hint
  !href cmd=hint $name_Hint
  &nbsp;
 !endif
 !if $help!=$empty
  !set wims_ref_class=wims_button_help
  !set wims_ref_id=oef_help
  !href cmd=help $wims_name_help
  &nbsp;
 !endif

 !if $qnum<=1
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_renew
  !href $renewlink <span class="oef_exo_renew">$name_exo_renew</span>
  &nbsp;
 !else
  <p class="name_serie_exo">$name_serie_exo</p>
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_serie_renew
  !href $renewlink <span class="oef_serie_renew">$name_serie_renew</span>
  &nbsp;
 !endif
 </div> <!-- id oef_action-->
!else
 !if $error!=$empty
  !read oef/msg.phtml
  !if $wims_theme_version= or $wims_theme_version<1 
  <center><hr width="50%"></center>
  !endif
 !endif

 !read oef/answer.phtml

 <div id="oef_actions">
 
 !if $status!=$empty
  <p class="oef_serie_exo2">$name_serie_exo2</p>
  <p class="oef_buttons">
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_serie_nextexo
  !href cmd=next <span class="oef_serie_nextexo">$name_serie_nextexo</span>
 $wims_name_or
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_serie_renew
  !href $renewlink <span class="oef_serie_renew">$name_serie_renew</span>
  </p>
  <p class="oef_serie_new2">$name_serie_new2</p>
  
 !else
  !if $qnum>1
   <span class="oef_modulescore">
     $name_serie_score
   </span>  
   !ifval $module_score>9.8
    <span class="oef_congratulations">$wims_name_Congratulations</span>
   !endif
   !if $toolate!=$empty and $score>$module_score
    <span class="oef_penalty">$name_penalty</span>
   !endif
   <p>
   !set wims_ref_class=wims_button
   !set wims_ref_id=oef_serie_renew
   !href $renewlink <span class="oef_serie_renew">$name_serie_renew</span>
   &nbsp;
   !if $wims_sheet=$empty
    !set wims_ref_class=wims_button
    !set wims_ref_id=oef_exo_intro
    !href <span class="oef_exo_intro">exo_Intro</span>
    &nbsp;
   !endif
   </p>
  !else
   <span class="oef_modulescore">$name_exo_score</span>
   !ifval $module_score>9.8
    <span class="oef_congratulations">$wims_name_Congratulations!</span>
   !endif
   !if $toolate!=$empty and $score>$module_score
    <span class="oef_penalty">$name_penalty</span>
   !endif
   <p class="renew_et_intro">
   !set wims_ref_class=wims_button
   !set wims_ref_id=oef_renew
   !href $renewlink <span class="oef_exo_renew">$name_exo_renew</span>
   &nbsp;
   !if $wims_sheet=$empty and $oef_test!=yes
    !set wims_ref_class=wims_button
    !set wims_ref_id=oef_exo_intro
    !href exo_Intro
    &nbsp;
   !endif
   </p>
  !endif
 !endif
 </div><!-- id oef_action-->
!endif

!if $replydefaulted=yes
 <p id="oef_devel_mode">
 $name_devel_mode:
 !if $oef_default=yes
  $name_devel_warning
 !else
  !set wims_ref_class=wims_button
  !set wims_ref_id=oef_default
  !href cmd=config&oef_default=yes $name_devel_insert
  &nbsp;
 !endif
 </p>
!endif
 <div id="oef_endhook"><!-- id oef_action-->
!read ./endhook.phtml
</div> <!-- id oef_endhook-->
:end
</div> <!--oefform-->
<!--fin oef main.phtml-->
!tail


!if debug iswordof $m_oefenv
 !reset module_score
!endif

