!nocache

!header1
<p><center><h3>
!href module=$module&cmd=intro WIMS
 $module_title<br>
<font size=-1>--- $name_print ---</font></h3></center> <p>


!if $error!=$empty
 !changeto oef/msg.phtml
!endif

!for i=1 to $n
 <p>
 <b>$name_exo</b> $i. (<u><em>$(title_$i)</em></u>)
 !if $(question_$i)=$empty
  ($name_noprint)
 !else
  !if __EXECUTED_ isin $(question_$i) and _EXERCISE__ isin $(question_$i)
   !set thisexo=$(name_$i)
   !readproc oef/imagedir.proc
   !for k=1 to $(varcnt_$i)+5
    !set val$k=!line $k of $(var_$i)
   !next k
   !read $(class_header)def/$(name_$i).def question
  !else
   $(question_$i)
  !endif
  $(chce_$i)
 !endif
!next i

!if $wims_user!=$empty and $wims_user!=supervisor
 !goto noans
!endif

!if $test_print=1
<p><hr> 
<div class="wims_solution">
<center><h3>$name_answers</h3></center>
!for i=1 to $n
 !set t=!linecnt $(ans_$i)
 !if $t>0
  <p><b>$name_answer_i.</b><ul>
  !for k=1 to $t
  !set l__=!line $k of $(ans_$i)
  !if $l__ !=
   <li value=$k>
   !line $k of $(ans_$i)
   </li>
  !reset l__
  !endif
  !next k
  </ul>
 !endif
!next i
</div>
!endif

:noans
</div>

!set wims_menu_items=!append line renew,1,cmd=reply&print=yes\
back2,1,module=$module&cmd=intro\
to $wims_menu_items
!tail


