!if $module_language=fr
 Les étudiants peuvent les utiliser comme un outil d'entrainement pour mieux
 mémoriser le cours, et les enseignants peuvent les mettre dans une feuille
 de travail avec le chronomètre activé, pour exiger de la rapidité des
 réponses.
 !exit
!endif

!if $module_language=nl
Leerlingen kunnen dit gebruiken als een hulpmiddel om de
lesstof beter te onthouden,
terwijl Leraren ze in een werkblad met een geactiveerde
tijdlimiet kunnen verwerken, om zo de reactiesnelheid te testen
!exit
!endif

!if $module_language=es
 Los estudiantes pueden utilizar estos ejercicios como una 
 herramienta de entrenamiento para memorizar mejor el tema, mientras que
 los profesores pueden integrarlos en una hoja de 
 trabajo con el cronómetro activado, para comprobar la rapidez en las 
 respuestas.
 !exit
!endif

!if $module_language=it
 Gli studenti possono utilizzare questi esercizi per allenarsi a
memorizzare meglio la lezione; i docenti possono inserirli in una
esercitazione a tempo, per verificare la prontezza delle risposte.
 !exit
!endif

Students may use them as a training tool for a better memorization of the lesson,
while teachers may put them into a work sheet with activated time limit, so that
proficiency can be tested.
