!read adm/title.phtml 2\
Recherche des modules par adresse

Les expressions régulières sont admises dans les recherches de modules par
adresses. Veuillez consulter la page du manuel de <span class="tt">grep</span> pour
plus de détails.
<p>
Caractères autorisés dans les chaînes de recherche : lettres (sans accent), 
chiffres, plus les symboles suivants&nbsp;:
</p><p class="wimscenter">
	<span class="tt">$searchsymbol</span>
</p>

Pour des raisons de sécurité, tous les autres caractères seront supprimés
avant la recherche.

