!read adm/title.phtml 2\
Convention d'adressage des modules WIMS

Les modules d'activité doivent avoir une adresse du type
<span class="tt wims_fname">Zone/categorie/nom.lang</span>.
Quand le module est en développement, cette adresse est traduite en
<span class="tt wims_fname">Zone~categorie~nom.lang</span>.

<ul>
<li><span class="tt wims_fname">Zone</span> : elle doit être l'une des zones déclarées du système.
Parmi elles, celles avec une lettre majuscule suivie d'un chiffre
correspondent aux niveaux académiques, la zone
<span class="tt wims_fname">Lang</span>
contient des modules d'apprentissage de langues,
<span class="tt wims_fname">tool</span>
contient des outils en ligne, les modules de
<span class="tt wims_fname">local</span>
se trouvent uniquement sur le serveur local,
<span class="tt wims_fname">test</span>
est une zone de test de modules non publiables dans laquelle vous pouvez mettre
ce que vous voulez.
<div>
!read help/$lang/level.phtml
</div>
</li><li><span class="tt wims_fname">categorie</span> : elle peut être un mot de votre choix, mais quand
vous publiez le module, il ne sera accepté que si la
catégorie est reconnue par le système.
<p>
Veuillez consulter ci-dessous la liste des catégories des modules existants.
En cas de doute, écrivez à
!mailurl $sysadmin coordinateur de la publication
.
</p>
</li><li><span class="tt wims_fname">nom</span> : un mot de votre choix, de préférence entre 4 et 12 caractères
avec comme préfixe obligatoire <span class="tt wims_fname">oef</span> s'il s'agit d'un module d'exercices
OEF et <span class="tt wims_fname">doc</span> s'il s'agit d'un document.
</li><li><span class="tt wims_fname">lang</span> : Le code de langue du module, à deux lettres. Il doit être parmi
les langues supportées par le site (<span class="tt wims_fname">$wims_site_languages</span>) et doit
correspondre à la langue définie dans le fichier INDEX du module.
</li></ul>
<div>
Quelques catégories connues : (non-exhaustives)
!read wimshome/public_html/bases/sys/categories.phtml
</div>

