
!if $job2!=first
 !changeto arch/$job2.phtml
!endif

Vous pouvez télécharger une copie de sauvegarde de votre classe, en format
!href cmd=reply&job=arch&job2=download&selection=all&format=zip zip
,
!href cmd=reply&job=arch&job2=download&selection=all&format=tgz tgz
 ou
!href cmd=reply&job=arch&job2=download&selection=all&format=tar.gz tar.gz
.
<small>[
!href cmd=help&special_parm=download aide
 ]</small>
<p><hr> <p>

!set wims_form_method=file
!form reply
<input type=hidden name=job value=arch>
<input type=hidden name=job2 value=upload>
Pour <input type=submit value=envoyer>
une sauvegarde dans votre classe, veuillez donner le nom du fichier de
sauvegarde&nbsp;:
<p>
<input type=file name=wims_deposit size=40>
<small>
!href cmd=help&special_parm=upload Aide
</small>
<p>
(On vous demandera de sélectionner les ressources de la classe à restaurer.)
</form> <p>

