!if $supertype=4 and $classdepth<=3
<p><center>
 !href module=adm/class/gateway Gestion de structure
</center>
!endif

!form reply
<input type=hidden name=up_job value=list>
$table_header
$table_tr<td align=right>Nom d'institution
<td colspan=3>
!if $supertype notin 24 or $classdepth=1
 <input size=50 name=up_institution value="$class_institution">
!else
 $class_institution
!endif
$table_tr<td align=right>Nom de classe
<td colspan=3>
<input size=50 name=up_description value="$class_description">
$table_tr<td align=right>Postes sûrs
<small>
!href cmd=help&special_parm=config&special_parm2=secure aide
 </small>
<td colspan=3>
<input size=50 name=up_secure value="$class_secure">
$table_tr<td align=right>Nom d'enseignant
<small>
!href cmd=help&special_parm=config&special_parm2=supervisor aide
 </small>
<td colspan=3>
<input size=40 name=up_supervisor value="$class_supervisor">
$table_tr<td align=right>Adresse email d'enseignant
<small>
!href cmd=help&special_parm=config&special_parm2=email aide
 </small>
<td colspan=3>
<input size=40 name=up_email value="$class_email">
$table_tr<td align=right>Mots d'option
<small>
!href cmd=help&special_parm=config&special_parm2=option aide
 </small>
<td colspan=3>
<input size=40 name=up_option value="$class_option">
$table_tr<td align=right colspan=2>Verrou de connection
<small>
!href cmd=help&special_parm=config&special_parm2=lock aide
</small>
</td><td colspan=2>
!set up_lock=$class_lock
!default up_lock=0
!formselect up_lock from 0 to 7
</td>
$table_tr<td align=right>Langue de la classe
<small>
!href cmd=help&special_parm=config&special_parm2=lang aide
 </small>
<td>
!set up_lang=$class_lang
!set langs=!words2items $wims_site_languages
!formselect up_lang list $langs
<td align=right>
Niveau académique
<small>
!href cmd=help&special_parm=config&special_parm2=level aide
 </small>
<td>
!set up_level=$class_level
!formselect up_level list $levellist
$table_tr<td align=right>Limite du nombre de participants
<small>
!href cmd=help&special_parm=config&special_parm2=limit aide
 </small>
<td><input size=5 name=up_limit value="$class_limit">
<td align=right>Date d'expiration
<small><b>yyyymmdd</b></small>
<small>
!href cmd=help&special_parm=config&special_parm2=expiration aide
 </small>
<td>
!if $class_type notin 13
 <input size=8 maxlength=8 name=up_expiration value="$class_expiration">
!else
 <tt>$class_expiration</tt>
!endif
$table_tr<td align=right>Enregistrement d'exercices
<small>
!href cmd=help&special_parm=config&special_parm2=exolog aide
 </small>
!default class_exolog=0
<td><input size=3 name=up_exolog value="$class_exolog">
<td align=right>Enregistrement d'examens
<small>
!href cmd=help&special_parm=config&special_parm2=examlog aide
 </small>
!default class_examlog=$wims_examlog_limit
<td><input size=3 name=up_examlog value="$class_examlog">
$table_hdtr<td align=center colspan=4>
<input type=submit name=save value=Sauver>
&nbsp;
<input type=submit name=abandon value=Restaurer>
$table_end <p>
</form>

Autres configurations:
!href cmd=reply&job=present Apparence
.
!href cmd=reply&job=neighbor&job2=first Classes voisines
.
!href cmd=reply&job=connect&job2=first Autres serveurs
.
!href module=adm/class/passwd Mots de passe
.
!href module=adm/forum/mboard&job=config Forum de discussion
.
!href module=adm/doc Documents
.
!href module=adm/class/motd Message du jour
.
!href cmd=reply&job=access Restrictions de ressources
.
!href cmd=reply&job=oefdefault Param&eacute;trage OEF par d&eacute;faut
.
!if $class_type iswordof 2 3 4
 !href cmd=reply&job=propagate Envoyer les configs aux zones inférieures
.
!endif
<p>
!href cmd=reply&job=security Gestion de sécurité
.
!href cmd=reply&job=arch&job2=first Sauvegarde et restauration
.
!href cmd=reply&job=clean Nettoyage sélectif
.
<br>
Actualiser les index<sup>
!href cmd=help&special_parm=index aide
</sup>:
!if $class_type=4
!href cmd=reply&job=index&job2=structure zones
,
!endif
!if $class_type=4 or $class_type=2
!href cmd=reply&job=index&job2=teacherlist enseignants
,
!endif
!href cmd=reply&job=index&job2=userlist participants
,
!href cmd=reply&job=index&job2=oef exercices
,
!href cmd=reply&job=index&job2=doc documents
.
<p>
!href module=adm/light&phtml=useropts.phtml.$lang Préférences personnelles
.
<p>
Utilisation actuelle d'espace disque : $du megaoctets. (La limite est
$wims_class_quota.)

!reset up_institution, up_description, up_supervisor, up_email, \
	up_lang, up_level, up_limit, up_expiration, up_secure, up_lock,\
	up_option,up_exolog,up_examlog,\
	pr_homepage, pr_bgcolor, pr_refcolor, pr_bgimg, pr_css, pr_theme

