
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!set title=Configuration et Maintenance
!if $job=arch
 !set title=Sauvegarde et Restauration
!endif

!if $job=clean
 !set title=Nettoyage de la classe
!endif

!if $job=neighbor
 !set title=Classes voisines
!endif

!if $job=connect
 !set title=Connecter aux autres serveurs / plate-formes
!endif

