
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=Jan,Fév,Mar,Avr,Mai,Jun,Jul,Aoû,Sep,Oct,Nov,Dec

!set title=Configuration et Maintenance
!if $job=arch
 !set title=Sauvegarde et Restauration
 !goto commun
!endif

!if $job=clean
 !set title=Nettoyage de la classe
 !goto commun
!endif

!if $job=neighbor
 !set title=Classes voisines
 !distribute lines Déclaration<br>de voisinage\
   Partage de ressource\
   par vous\
   par l'autre\
   Partages mutuels actifs.\
   Vous partagez ses ressources.\
   Partage vos ressources.\
   Permissions mutuelles de partage.\
   A le droit de partager vos ressources.\
   Vous permet de partager ses ressources.\
   Arrêter le partage\
   Partager\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3,name_stopsharing,name_share
 !goto commun
!endif

!if $job=connect
 !set title=Se connecter aux autres serveurs / plate-formes
 !goto commun
!endif

!if $job=access
 !set title=Configuration de l'accès aux ressources
 !goto commun
!endif

!if $job2=addshare
 !set title=Partager les ressources d'une classe
 !goto commun
!endif

!if $job=grestrict
 !set title=Restriction de l'accès aux scores
 !goto commun
!endif

!if $job=present
 !set title=Configuration de l'apparence de la classe.
 !goto commun
!endif

!if $job=oefdefault
 !set title=Paramétrage par défaut des modules OEF
 !goto commun
!endif

!if $job=security
 !set title=Activités de gestion de sécurité disponibles
 !goto commun
!endif

!if $job=authtype
 !set title=Authentification par un annuaire ldap
 !set name_intro_authtype=Sélectionnez <tt>ldap</tt> et remplissez cette page si \
   vous désirez utiliser une authentification par un annuaire ldap.
 !goto commun
!endif

:commun
!distribute line Authentification\
Préférences\
Restriction d'accès\
Paramétrage OEF\
Classes voisines\
Gestion de sécurité\
Nettoyage sélectif\
Actualiser\
Autres serveurs\
Mots de passe\
Zones dépendantes\
Apparence\
Restriction des scores\
Adresse d'une plateforme\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items zones,participants,exercices,documents,enseignants\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers


!distribute lines Postes sûrs\
   Feuille de style\
   Logo\
   Position du logo\
   en haut à gauche, en haut à droite\
   Thème de style\
   Jeu d'icones\
   Niveau académique\
   Postes autorisés aux notes\
   Mot de passe d'inscription\
   Mot de passe d'enseignant\
   Limites d'enregistrement d'exercices et d'examens\
   Liens sur une plateforme ou une page web\
   Couleur de fond des pages\
   Couleur de fond des menus\
   Image de fond des pages\
   transférer un fichier css\
   Dégradé de couleurs des scores (de 0 à 10)\
   into name_secure,name_css,name_logo,name_position_logo,name_logo_side,name_theme,\
   name_theme_icon,name_level,name_security,name_password,name_supass,name_exolog,name_ent,\
  name_background_color,name_menu_color,name_image,name_css_transfer,name_colorscore

!set name_content_style = Contenu de la feuille de style de la classe \
<br>(lorsque <tt>$name_css</tt>  est sur <tt>class</tt>)&nbsp;:

!set name_content_style2=ou copier ici la feuille de style de la classe
