
<center>
!form reply
$table_header
 $table_tr
  <td align=center>$name_series</td>
  <td>
   !set nw_qnum=$user_qnum
   !formselect nw_qnum from 1 to 9
   $wims_name_exercises.
  </td>
 </tr>
 $table_tr
  <td align=center>$name_severity</td>
  <td>
   !set nw_qcmlevel=$user_qcmlevel
   !formselect nw_qcmlevel from 1 to 9
  </td>
 </tr>
 $table_tr
  <td align=center>$name_chrono </td>
  <td>
   <input size=7 name=nw_scoredelay value="$user_scoredelay"> $name_secondes.
  </td>
 </tr>
 $table_tr
  <td align=center>$name_qcm</td>
  <td>
   !set nw_qcmpresent=$user_qcmpresent
   !formselect nw_qcmpresent list 2,3,4,5,6,7,8 
  </td>
 </tr>
 $table_tr
  <td align=center>$name_solution</td>
  <td>
   !default nw_presentsol=$user_presentsol
   !formselect nw_presentsol list 0,1,2 prompt $name_prompt
  </td>
 </tr>
 $table_tr
  <td rowspan=4>&nbsp;</td><td>
   !set nw_check=$user_check
   !formcheckbox nw_check list 1 prompt $name_prompt1
   une bonne réponse dans les QCM.
  </td>
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox nw_check list 2 prompt $name_prompt2
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox  nw_check list 3 prompt $name_prompt3
  </td>
 </tr>
 $table_tr
  <td align=left>
   !formcheckbox nw_check list 4 prompt $name_prompt4
   !let tmp=!replace word expert by $ in $special_parm2
  </td>
 </tr>
 $table_tr
 <td colspan=2 align=center>
  <input type=submit value="$wims_name_tosave">
  <input type=hidden value="1" name="step">
 </td></tr>
</table>
</form>
</center>
<p><small>$name_warning
</small>
