
!if $confirm!=$empty and $propagate!=$empty
$name_propagate_succes:<p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
  $name_propagate_choose: <p>

 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="$wims_name_send">
 </form>
!endif
<p>
$name_warning
