!set name_secure=Postes sûrs
!set name_colors=Couleurs des pages
!set name_css=Feuille de style
!set name_logo=Logo
!set name_theme=Thème de style
!set name_theme_icon=Jeu d'icones
!set name_level=Niveau académique
!set name_security=Postes autorisés aux notes
!set name_password=Mot de passe d'inscription
!set name_supass=Mot de passe d'enseignant
!set name_exolog=Limites d'enregistrement d'exercices et d'examens
!set name_ent=Liens sur une plateforme ou une page web
!if $wims_supertype=2
 !set name_thisclass=du portail
 !set name_subclasses=sous-classes
!else
 !set name_thisclass=de la zone actuelle
 !set name_subclasses=zones inférieures
!endif

!if $confirm!=$empty and $propagate!=$empty
 Configurations envoyées aux $name_subclasses avec succès&nbsp;: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
 Vous pouvez choisir d'envoyer les configurations suivantes $name_thisclass
 à toutes ses $name_subclasses&nbsp;: <p>

 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="Envoyer">
 </form>
!endif
<p>
Notez que les $name_subclasses ne répercuteront pas les
changements ultérieurs des configurations $name_thisclass. Vous devez
réenvoyer les changements chaque fois que vous voulez les répercuter
dans les $name_subclasses.

