
<ul>
<li><p>
!href module=adm/class/passwd Changer vos mots de passe
.

<li><p>
!href cmd=renew&job=log Voir l'enregistrement
 d'activité de gestion de votre classe. (Vous devez être l'origine de toutes
ces activités&nbsp;; si ce n'est pas le cas, il faut vérifier s'il n'y a pas une
fuite de votre mot de passe d'enseignant.)

<li><p>Configurer la
!href cmd=reply&job=grestrict restriction par classe
 des sites ayant accès aux scores.


<li><p>Autres définitions de sécurité dans 
!href cmd=renew&job=list la configuration de la classe
.

</ul>

