
!if $class_defined!=yes
 <b>错误</b>. 你想进入的班级$name_classess不存在. 请检查你的请求.
 !exit
!endif

为了以<em>$name_sup<em>身份进入
<b><font color=green>$class_institution</font></b> 的
<b><font color=green>$class_description</font></b>
$name_classes, 请给出$name_sup 的个人密码。

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 $wims_name_Password ($name_sup) <input type=password size=20 name=auth_password>
<p>
<input type=submit value="$wims_name_Enter">
</center>
</form>

