
!if $class_defined!=yes
 <b>错误</b>. 你想进入的班级$name_classess是不存在的. 请检查你的请求.
 !exit
!endif

为了以<em>注册学生<em>身份进入
<b><font color=green>$class_institution</font></b>的
<b><font color=green>$class_description</font></b>
班级, 请给出你的注册用名以及个人密码。

!!!##language independant
<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>$wims_name_Login<td><input size=20 name=auth_user value="$auth_user"></td>
 <tr><td>$wims_name_Password<td><input type=password size=20 name=auth_password></td>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register