
!if $class_defined!=yes
 <b>错误</b>. 你想进入的班级$name_classess是不存在的. 请检查你的请求.
 !exit
!endif

为了以<em>注册学生<em>身份进入
<b><font color=green>$class_institution</font></b>的
<b><font color=green>$class_description</font></b>
班级, 请给出你的注册用名以及个人密码。

<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>你的注册用名: <td><input size=20 name=auth_user value="$auth_user">
 <tr><td>你的密码: <td><input type=password size=20 name=auth_password>
 $table_end
 <p><center>
 <input type=submit value="发送">
</center>
</form>

新参加者:
!href module=adm/class/reguser&class=$class&subclass=yes 点击这里
以注册到此班级.

