!if $clcnt<=0
 抱歉, 本站未设有实例用虚拟班.
 !exit
!endif

!if $lacnt<=0
 本站没有中文版实例虚拟班, 仅有 $clcnt 个英语版虚拟班.
!else
 本站设有 $clcnt 个作实例用的中文版虚拟班.
!endif

这些班级是用来向你展示虚拟班的学生界面是如何工作的. 虚拟班的教师界面
比这要复杂不少, 若你想看到教师界面, 你必须
!href module=adm/class/regclass 建立
 一个你自己的班级.

<p>$table_header
$table_hdtr<th>Class name<th>Level<th>connection type<th>Register
!for i=1 to $clcnt
 !set l=!line $i of $classes
 !distribute items $l into code,expire,inst,cl
 !defread wimshome/log/classes/$code/.def
 !distribute char $class_level into l_,y_
 
 $table_tr<td align=center>$inst<br>$cl</td>
 <td align=center>$(n_$l_)<br>year $y_</td>
 <td align=center>
 !href module=home&user=anonymous,$code,anonymous Anonymous
 &nbsp;
 !href module=$module&type=authparticipant&class=$code Registered
 </td><td align=center>
 !href module=adm/class/reguser&class=$code Register
 </td>
!next i
</tr>$table_end <p>
 
<ul>
<li>在 `匿名' 上单击可使你以匿名参观者身份进入班级.
<li><p>在 `已注册' 上单击可使你以注册参加者 (学生) 身份进入班级. (为此
你必须先行注册, 并请注意, 服务站将定期清理实例班级的注册学生名单.)
<li><p>在 '注册' 上单击可使你在该班级注册.
</ul>

