!read search.phtml
!if $overflow=yes
 !exit
!endif

!if $clcnt+$sccnt+$directcnt<1
 !if $keyword=$empty
 本站尚无中文版虚拟班. 可能你想找一个
 !href module=home&list=0 其他文版
的班级?
 !else
  没有班级与你的关键词对应.
 !endif
 !exit
!endif

!if $wims_user!=$empty
 !read direct.phtml
 !if $wims_user!=supervisor and $superclass=$empty
  !exit
 !endif
!else
请选一个班级进入.
!endif

!if $sccnt>0
 <p>$table_header
 <caption>学校与班级组</caption>
 $table_hdtr
 <th>班名<th>教师<th>状态<th>注册
!for i=1 to $sccnt
 !set l=!line $i of $sclasses
 !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !if $superclass=$empty
   !set show=$inst
  !else
   !set show=$cl
  !endif
  !set supv=!item 9 of $l
  !if $supv=$empty
   !reset class_password
   !defread wimshome/log/classes/$code/.def
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif

 $table_tr<td align=center>
 !href module=$module&type=authparticipant&class=$code $show
 </td><td align=center>
  $supv
  </td> <td align=center>
  !if $pswd=$empty
  开放的
 !else
  保护的
 !endif
 </td><td align=center>
  !href module=adm/class/reguser&class=$code&subclass=yes 注册
 </td>
!next i
$table_end <p>

!if $clcnt>0
 <p>$table_header
 !if $superclass=$empty
  <caption>独立班级</caption>
  $table_hdtr<th>班级名<th>教师<th>程度<th>状态<th>注册
 !else
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
    !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
   !endif
   <caption>$Name_levels in $inst 
   !if $splevel>1
    !href cmd=reply&type=$type&superclass2=$sparent 向上
   !endif
   </caption>
   $table_hdtr<th>班级名<th>教师<th>程度<th>状态<th>注册
   !if $superclass!=$empty and $stype=4
    <th>More
   !endif
 !endif
 !for i=1 to $clcnt
  !set l=!line $i of $classes
  !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !set supv=!item 9 of $l
  !if $supv=$empty
   !reset class_password
   !defread wimshome/log/classes/$code/.def
   !set lv=$class_level
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif
  !distribute char $lv into l_,y_
  
  !if $superclass=$empty
   !set show=$inst <br>$cl
  !else
   !set show=$cl
  !endif
  $table_tr<td align=center>
  !href module=$module&type=authparticipant&class=$code $show
  </td><td align=center>
  $supv
  </td><td align=center>$(n_$l_)<br>$y_ 年级</td>
  <td align=center>
  !if $pswd=$empty
   开放的
  !else
   保护的
  !endif
  </td><td align=center>
  !if $splevel=$empty or $splevel=2
   !href module=adm/class/reguser?class=$code 注册
  !else
   <font color=grey>注册</font>
  !endif
  </td>
   !if $superclass!=$empty and $stype=4
    <td>
    !if $ty!=1
     !href cmd=reply&type=$type&superclass2=$code 分班
    !else
    -
    !endif
   !endif
 !next i
 $table_end <p>
!endif

在班名上单击以进入该班 (如果你是这个班级的注册参加者).
<p>
在 `注册' 上单击以在该班注册 (在保护班级注册需要一个班级密码, 该
密码应当在你的教师那里得到).



