
!form reply
<input type="hidden" name="job" value=$job>
$table_header
!if $login=$empty
 <caption>$name_addteacher</caption>
!else
 <caption>$wims_name_modteacher <tt>$login</tt></caption>
!endif
$table_tr<td align="right">$wims_name_Login</td><td>
!if $login=$empty
 <input size="30" name="login" value="">
!else
 <tt>$login</tt>
!endif
</tr>
$table_tr<td align="right">
$wims_name_Password</td>
<td><input type="password" size="30" name="pass" value=""></td></tr>
$table_tr<td align="right">
$wims_name_repeat_pass</td>
<td><input type="password" size="30" name="pass2" value=""></td></tr>
$table_tr<td align="right">
$wims_name_firstname</td>
<td><input size="30" name="firstname" value="$firstname"></td></tr>
$table_tr<td align="right">
$wims_name_lastname</td>
<td><input size="30" name="lastname" value="$lastname"></td></tr>
$table_tr<td align="right">
$wims_name_email</td>
<td><input size="30" name="email" value="$email"></td></tr>
$table_tr<td align="center" colspan="2">
<input type="submit" name="confirm" value="$wims_name_tosave">
&nbsp;
<input type="submit" name="cancel" value="$wims_name_giveup"></td></tr>
$table_end
</form>

