
!form reply
<input type="hidden" name="job" value="$job">
$table_header
!if $auth_method notitemof $auth_method_list
 !if $login=$empty
  <caption>$name_addteacher</caption>
 !else
   <caption>$wims_name_modteacher <tt>$login</tt></caption>
 !endif
  $table_tr<td align="right">$wims_name_Login</td><td>
 !if $login=$empty
  <input size="30" name="login" value="">
 !else
  <tt>$login</tt>
 !endif
</td></tr>
 $table_tr<td align="right">
 $wims_name_Password</td>
 <td><input type="password" size="30" name="pass" value=""></td></tr>
 $table_tr<td align="right">
 $wims_name_repeat_pass</td>
 <td><input type="password" size="30" name="pass2" value=""></td></tr>
 $table_tr<td align="right">
 $wims_name_firstname</td>
 <td><input size="30" name="firstname" value="$firstname"></td></tr>
 $table_tr<td align="right">
 $wims_name_lastname</td>
 <td><input size="30" name="lastname" value="$lastname"></td></tr>
 $table_tr<td align="right">
 $wims_name_email</td>
 <td><input size="30" name="email" value="$email"></td></tr>
!else  external
  !if $login=$empty
     <caption>$name_addteacher</caption>
  !else
    !set user_external_auth=!getdef user_external_auth in wimshome/log/classes/$wims_class/.users/$login
    <caption>$wims_name_modteacher</caption>
  !endif
  !if $login!=$empty
  $table_tr<td align="right">$wims_name_Login ($name_internal)</td><td>
    <tt>$login</tt>
   </td></tr>
  !endif
 $table_tr<td align="right">$wims_name_Login ($name_external)</td><td>
   <input size="30" name="user_auth" value="$user_external_auth">
   <span class="wims_warning"><span class="wims_small_remark">
   $name_login_external 
   !if $idp_method isitemof $idp_method_list
    ($name_idp_external)</span>
   !endif
.</span>
 </td></tr>
!endif

!if $idp_method notitemof $idp_method_list
 $table_tr<td align="right">
 $wims_name_firstname</td>
 <td><input size="30" name="firstname" value="$firstname"></td></tr>
 $table_tr<td align="right">
 $wims_name_lastname</td>
 <td><input size="30" name="lastname" value="$lastname"></td></tr>
 $table_tr<td align="right">
 $wims_name_email</td>
 <td><input size="30" name="email" value="$email"></td></tr>
!endif
  !if $user_participate!=$empty
    $table_tr<td align="right">$name_inscript</th><td><tt>$user_participate</tt></td></tr>
  !endif
  !set user_supervisable=!getdef user_supervisable in wimshome/log/classes/$wims_class/.users/$login
  !if $user_supervisable=yes
  !default user_supervise=!getdef user_supervise in wimshome/log/classes/$wims_class/.users/$login
    $table_tr<td align="right">$name_gestion</th><td>
    <input size="60" name="up_supervise" id="up_supervise" value="$user_supervise">
    </tt></td></tr>
  !endif
$table_tr<td align="center" colspan="2">
<input type="submit" name="confirm" value="$wims_name_tosave">
&nbsp;
<input type="submit" name="cancel" value="$wims_name_giveup"></td></tr>
$table_end
</form>

