
!set ini_color=#0000FF
WIMS (<font color=$ini_color>W</font>ww
   <font color=$ini_color>I</font>nteractive
   <font color=$ini_color>M</font>ultipurpose
   <font color=$ini_color>S</font>erver, 网上互动式多功能服务站)
是以数学教学为目的的因特网服务系统.
<p>

Wims服务器的核心程序是一个cgi(wims.cgi), 再加上称为``模块''的各种活动的单元.
<p>
用户通过对 wims.cgi 的 http 请求进入服务器, 
所请求的模块名、请求类型以及有关模块的参数被一起送到服务器.
wims.cgi根据随请求一起传送的参数对所需模块进行处理, 
然后把模块返回的结果发送给用户.
<p>
一个模块一般是一批脚本文件, 放在同一个目录里. 
这些脚本使用 wims.cgi 能识别的特殊语言写成.
<p>
脚本语言里也含有调用外部程序(特别是各种数学软件)的命令, 
以进行复杂的计算. 这些命令也由 wims.cgi 加以处理,
通过接口程序传送出去, 再送回经过过滤的输出.

