!! This file can contain contents which go to the end of the page.

!if $wims_exec_error!=$empty
<small><pre>*******************************************************
$wims_exec_error
*******************************************************</pre></small>
!reset wims_exec_error
!endif

!set wims_menu_tail=!append line backcreatexo,1,cmd=resume&realtest=no\
to $wims_menu_tail
!if $mode=model
!set wims_menu_tail=!append line modellist,1,cmd=reply&level=1&mode=model\
to $wims_menu_tail
!endif

!!<p><center>
!!!href cmd=resume&realtest=no  返回创建练习页
!!.
!!!if $mode=model
!!&nbsp;
!! !href cmd=reply&level=1&mode=model 模块表
!!.
!!!endif
!!</center> <p>
