欢迎进入本页. 它以指导模式帮你建立你自己
!if $wims_user!=supervisor
!else
班级<font color=blue> $wims_classname</font>, <font color=blue>($wims_institutionname)</font>
!endif
的交互式练习. 这里有
!href cmd=reply&mode=model 做好的模块
.
如果你已经是专家, 或者你有已被保存的练习的源文件,
你可以转到
!href cmd=reply&rawinp=yes 简洁模式
或
!href cmd=reply&mode=file 文件模式
. 
初学者也可以看一下
!href cmd=help&special_parm=examples 范例
.
 
也可参见
!href module=adm/modtool 模块工具
 以了解在线开发具有全部功能的WIMS模块的方法.
