
The exercise <em>$deltitle</em> has been removed from the list of exercises of your
class.
<p>
In case you have made a wrong manoeuvre and would like to recover your error,
here is the source of this exercise which you can save as an emergency
measure, and later copy to 
!href module=adm/createxo&mode=raw Createxo
 to reinstall the exercise.
<p>
<pre>
$deleted
</pre>

<p><center>
!href module=home Home of the class.
</center> <p>

