
!set wims_form_method=file
!form reply
<input type=hidden name=level value=3>

!if $existing=$empty
 You are under the file mode for the creation of exercise.
 Under this mode, you can send a local OEF source file to the server.
 For a first creation of exercise, prefer the
 !href cmd=reply&mode=normal guided mode
. You can also use the
 !href cmd=reply&mode=raw raw mode
 to edit online.
 <p>
 Source file of your exercise:
 <input type=file name=wims_deposit>
 <p><center>
<input type=submit value="Send the file"></center>
</form>

