!if $wims_developer!=$empty and ..devel/ isin ..$catmodule
 !if $reg1=success
  The exercise <tt>$existing.oef</tt> in the module 
  <tt>$catmodule</tt> is successfully updated.
 !else
  Failed to update <tt>$existing</tt> in the module
  <tt>$catmodule</tt>.
  <pre>$wims_exec_error</pre>
 !endif
 <p>
 !href cmd=reply&level=3 Go back to the preceeding stage.
 !exit
!endif

!if $wims_user=$empty
 !read level5.phtml
!else
 !if $already!=yes
  Your exercise has been successfully installed.
 !else
  We have found an identical exercise in your class. The double registration
  is therefore ignored. <p>
 !endif
 This exercise will be accessible only to participants of your class, and 
 this only if you put it into a worksheet.
 <p>
 !if $wims_user!=supervisor
  Now you can
  !href module=classes/$lang&special_parm=.nocache. Consult the exercises of the class.
 !else
  Now you can:
  <ul>
  <li><p>
  !href module=classes/$lang&special_parm=.nocache. Consult the exercises of your class.
  (And eventually put them into your worksheets.)
  <li><p>
  !href cmd=reply&level=3 Go back to the preceeding stage.
  </ul>
 !endif
!endif

