
The software have successfully recognized your exercise, with the following
informations. (Please verify with what you have defined.)
<table bgcolor="#d0d0d0">
<tr><td align=right>Title<td><td>$title
<tr><td align=right>Number of parameters<td><td>$varcnt
<tr><td align=right>Number of freestyle replies<td><td>$replycnt
<tr><td align=right>Number of multiple choices<td><td>$choicecnt
</table>
<ul><li>
Now you can
!href cmd=resume&realtest=yes&retest=again test your exercise
.
!if $mode!=file
<li><p>
!href cmd=reply&level=2 modify the source
.
!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=level value=3>
 <li><p>
 Or modify the source file then
 <input type=submit value="send again">:
 <input type=file name=wims_deposit>
 </form>  
 <li><p>
 !href cmd=reply&level=1&mode=normal Back to the starting menu
.
!endif
!if $wims_user!=$empty
 <li><p>You can also
 !href cmd=reply&level=6 send an image file
 to the exercise.
 !set wims_menu_tail=!append line downloadbinary,1,cmd=reply&level=6\
 to $wims_menu_tail
!endif
!if $wims_user!=$empty or $existing!=$empty
 <li><p>
 Once everything is correct, you can
 !if $existing!=$empty
  !if ..devel/ notin ..$catmodule
   put this exercise into your class, either
   !href cmd=reply&level=4 to replace the old one
   or
   !href cmd=reply&level=4&newone=1 as a new exercise
   !set wims_menu_tail=!append line replace,1,cmd=reply&level=4\
 newversion,1,cmd=reply&level=4&newone=1\
 to $wims_menu_tail
  !else
   !href cmd=reply&level=4 put it to the development module
   !set wims_menu_tail=!append line putmodtool,1,cmd=reply&level=4\
   to $wims_menu_tail
  !endif
 !else
  !href cmd=reply&level=4 put this exercise into your class
   !set wims_menu_tail=!append line putclass,1,cmd=reply&level=4\
 to $wims_menu_tail
 !endif
.
!endif
!if $mode!=file
 <li><p>
 Finally, don't forget to 
 !getfile submit.oef save the source
 of the exercise!
!endif
</ul>
!set wims_menu_tail=!append line testexo,1,cmd=resume&realtest=yes&retest=again\
to $wims_menu_tail

!if $wims_version_theme=0
  !reset wims_menu_tail
!endif
