
!form reply
<input type=hidden name=level value=2>
Give a title to the exercise you want to create:<br>
<input size=40 maxlength=40 name=oef_title value="$oef_title"> <p>
Format of the statement of the problem:
!formselect oef_format list tex,html
 [
 !href target=wims_mhelp cmd=help&special_parm=format $wims_name_help
 ]<p>
This exercise will ask for
!formselect oef_answercnt from 0 to 10
freestyle replies and
!formselect oef_choicecnt from 0 to 10
multiple-choice replies.
Non-computed numerical replies (such as <tt>3*5-sin(pi/3)</tt>) will be
!formselect oef_computeanswer list yes,no prompt accepted,refused
.
!formselect oef_condcnt from 0 to $condlim
conditions will be used to test freestyle replies.
 [
 !href target=wims_mhelp cmd=help&special_parm=reply $wims_name_help
 ]
<p><table border=0><tr><td align=right>
$wims_name_Author<td><input size=30 maxlength=60 name=oef_author value="$oef_author">
<tr><td align=right>
$wims_name_email<td><input size=30 maxlength=80 name=oef_email value="$oef_email">
</table>
<p><center>
<input type=submit value="$name_continue">
</center>
</form>

!if $wims_user=supervisor
 !read wimshome/log/classes/$wims_class/Exindex
 !if $exototal>0
  <p>
  !form new
  <input type=hidden name=module value="$module">
  $name_modify
  !formselect existing list $exolist prompt $titlelist
  <input type=submit value="$wims_name_tosave"></form>
 !endif
!endif

