
!set name_first=Basic exercises
!set name_datalist=Exercises with a data list

!readproc model/makelist.proc

Here are the available exercise models. Choose one, or
!href cmd=reply&level=0 turn back
 to the home page.

<p>
!for t in $types
 !default name_$t=$t
 $table_header
 <caption>$(name_$t)</caption>
 $table_hdtr
 <th>Type</th>
 <th>Action</th>
 <th>Description</th>
 </tr>
 !for f in $(type_$t)
  !set r=!record 1 of model/src/$f.oef
  !set r=!line 1 of $r
  $table_tr
  <td>$(tit_$f)</td>
  <td nowrap>
  !href cmd=resume&level=3&mode=model&model=$f&realtest=yes Demo
&nbsp;
  !href cmd=reply&level=2&mode=model&model=$f Adapt
  </td>
  <td><small>$(desc_$f)
  !href target=wims_mhelp cmd=help&special_parm=model,1,$f &gt;&gt;
  </small></td>
  </tr>
 !next f
 $table_end
 <p>
!next t

<b>Note</b>. These models are prepared to allow people to construct rapidly
their exercises. Hence they are often with a simplified and standardised
structure, and don't offer the full power of the OEF syntax. But you can
always put the exercises in raw mode to add more functionalities or modify
them according to your need.

!reset mode

