!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
 You are under the raw mode for the creation of exercise.
 !if $modeltest=yes
  As this exercise is based on a standard model, try the
  !href cmd=reply&mode=model&level=2 $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !else
  This mode is reserved to experts or for registering an
  exercise for which you have the source file.
  For a first creation of exercise, prefer the
  !href cmd=reply&mode=normal&level=1 guided mode
.
  <p>
  Enter the entire source (
  !href target=wims_mhelp cmd=help&special_parm=oef OEF format
  ) of your exercise:
  (to register an existing source file, copy the file into the text window.)
  !href target=wims_test module=tool/directexec&cmd=new Script tester
 !endif
!else
 !if $catmodule=$empty
 Here is the source of an existing exercise for your class. You can modify it
  in the window below.
 !else
 Here is the source of a public exercise that you have imported.
  You can modify it in the window below, before putting it into the class.
 !endif
 !if $modeltest=yes
  As this exercise is based on a standard model, try the
  !href cmd=reply&mode=model&level=2 $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !endif
!endif

 Vous pouvez tester certains programmes externes avec le
  !href target=wims_test module=tool/directexec&cmd=new testeur de script
.
<p><center>
!mexec textarea.sh

<p><input type=submit value="$name_sendsource"></center>
<center><a name=textarea></a>
[
<a href="#"
onclick="document.forms['replyform'].wims_deposit.value=''">$name_clean</a>
] [
!href cmd=resume $wims_name_giveup
].
</center>
</form>

