!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
$name_brut
 !if $modeltest=yes
 $name_try
  !href cmd=reply&mode=model&level=2 $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !else
 $name_allsource (
  !href target=wims_mhelp cmd=help&special_parm=oef format OEF
  )
  ($name_copy).
 !endif
!else

 !if $catmodule=$empty
  $name_source2
 !else
  $name_modify_window
 !endif
 !if $modeltest=yes
  $name_public
  !href cmd=reply&mode=model&level=2 $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !endif
!endif

 $name_test_extern
  !href target=wims_test module=tool/directexec&cmd=new $name_testerscript
.
<p><center>
!mexec textarea.sh

<p><input type=submit value="$name_sendsource"></center>
<center><a name=textarea></a>
[
<a href="#"
onclick="document.forms['replyform'].wims_deposit.value=''">$name_clean</a>
] [
!href cmd=resume $wims_name_giveup
].
</center>
</form>

