
!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
 You are under the raw mode for the creation of exercise.
 !if $modeltest=yes
  As this exercise is based on a standard model, try the
  !href cmd=reply&mode=model&level=2 guided mode
.
  !href cmd=reply&mode=none&level=1 Abandon
.
 !else
  This mode is reserved to experts or for registering an
  exercise for which you have the source file.
  For a first creation of exercise, prefer the
  !href cmd=reply&mode=normal&level=1 guided mode
.
  <p>
  Enter the entire source (
  !href target=wims_mhelp cmd=help&special_parm=oef OEF format
  ) of your exercise:
  (to register an existing source file, copy the file into the text window.)
  !href target=wims_test module=tool/directexec&cmd=new Script tester
 !endif
!else
 Here is the source of
 !if $catmodule=$empty
  an existing exercise for your class. You can modify it
  in the window below.
 !else
  a public exercise that you have imported.
  You can modify it in the window below, before putting it into the class.
 !endif
 !if $modeltest=yes
  As this exercise is based on a standard model, try the
  !href cmd=reply&mode=model&level=2 guided mode
.
  !href cmd=reply&mode=none&level=1 Abandon
.
 !endif
!endif

<a name=textarea>
<a href=#
onclick=document.forms["replyform"].wims_deposit.value="">[Clear]</a>.
!href cmd=resume [Reinitiate]
.

<p><center>
!mexec textarea.sh
<p><input type=submit value="Register the source"></center>
</form>

