
!if $sstyle=1
 !if $substep=0
  !if $all_steps=0
   !form reply
   Wat is de <em>eerste</em> foute stap in deze reeks?
   !formselect badstep from 0 to $stepcnt
   (0 betekend in dit geval dat alle stappen goed zijn.)
   <div class="wimscenter">
   <input type="submit" value="OK" /></div>
  !else
   Markeer <em>alle</em> foutieve stappen hierboven, en dan
   <input type="submit" value="Klik hier" />.
  !endif
  !formend
 !else
  !if $all_steps=0
   !if $badstep=0
    Inderdaad, alle stappen zijn correct.
   !else
    inderdaad, de eerste slechte stap is $badstep.
   !endif
  !endif
  Je score: $module_score/10.
  !if $expstep!=$empty
   <p>Uitleg.
   </p><ul>
   !for i in $expstep
    <li> Step $i
    !if $i isitemof $badstep
     is correct.
     !line $i of $remarks
    !else
     !set j=!positionof item $i in $bad_steps
     !set e=!item $j of $bad_reasons
     is niet goed.
     !read reasons/$e.det
    !endif
    </li>
   !next i
   </ul>
  !endif
 !endif
!else
 !if $substep=0
  !form reply
  Wat vind je van de <em>laatste</em> stap?
  !formselect ans list --,OK,$bad_reasons prompt I weet het niet,\
  	Ja : deze stap is correct,$bad_rnames
  <input type="submit" value="Sturen" />
  !formend
 !endif

 !if $substep=2
  Je hebt gelijk:
  !if $step_reason=OK
  de laatste stap is correct.
  !else
  de laatste stap was foutief.
   De goede stap moest zijn
   <table class="wimscenter" border=0 bgcolor="#d0c0d0" width="80%"><tr><td>
   !line $step of $good
   </td></tr></table>
  !endif
  <p>
  !if $step<$stepcnt
   !href cmd=reply&ans=next Ga na de volgende stap.
  !else
   Dit is het einde van deze oefening.<br/>Je score: $module_score/10.
  !endif
  </p>
 !endif
!endif

