
Puoi esplorare il sito in vari modi.

<ul>
<p><li>
 !href module=$module&cmd=new&job=type Per tipo di risorsa
$: materiale di riferimento, strumenti grafici e strumenti di calcolo, esercizi, etc (<b>in inglese</b>).

<p><li>
 !href module=$module&cmd=new&job=subject Per argomento
$: algebra, analisi, <em>calculus</em>, geometria, probabilità, etc.

<p><li>
 !href module=$module&cmd=new&job=level Per livello
$: scuola elementare, scuola media, università, etc.

<p><li>
 !href module=$module&cmd=new&job=new Per data
$: ultime acquisizioni del server.

<p><li>
 !href module=$module&cmd=new&job=best Una breve introduzione
 ad alcune delle migliori attività del sito (<b>in inglese</b>).

</ul>

