
<h3><center>Ultime acquisizioni del server</center></h3>
<br><br>

<p><center><table border=0 bgcolor=$table_bgcolor>
<tr><th>Data di<br>creazione<th>Nome<th>Descrizione

!for i=1 to $n
 !set li=!line $i of $list
 !set year	=!char 1 to 4 of $li
 !set month	=!char 6,7 of $li
 !set day	=!char 9,10 of $li
 !set version	=!word -1 of $li
 !set address   =!item $i of $addresses
 !set name=!module title $address
 !set desc=!module description $address
 !default name=??
 !default desc=??
 
 $table_tr<td>$month-$day-$year<td>
 !href module=$address $name
 <td>$desc
!next i
$table_end <p>

