!read adm/css.phtml
!read names.phtml
!if $job=compose
  !read js/speckedit.phtml name_deposit
!endif
!header1
!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$module_title

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
 !if $fatal=yes
  <center>
  !href module=adm/forum/forum Lista de foros de discusión accesibles en este servidor.
  </center>
  !tail
  !exit
 !endif
!endif

!read $job.phtml

!tail

