
<center><h3>Formatos de hojas de cálculo aceptados</h3></center>

Para cargar los datos de una hoja de cálculo en una clase guarde los datos
en un formato de texto (con los valores separados por comas o por tabuladores)
en un fichero de extensión .txt, .csv, o .tsv. La mayoría de las hojas de 
cálculo le permiten guardar los datos en estos formatos.
<p>
Después escriba el nombre del fichero en el campo <tt>Fichero de datos</tt>
y súbalo al servidor WIMS.

