<center>$classname<p>

!if $logname=$empty
 Vous avez soumis une requête illégale.
!else
 <h3>Détail du travail de $lastname, $firstname</h3>
 (en données brutes)
 </center> <p>
<pre>
!set test=$wims_show_ip
!mexec getraw.sh
</pre>
!endif

!!<p><center>
!!!href cmd=reply&job=getuser&getuser=$getraw Données traitées
!! .
!!!href cmd=resume Liste de tous les participants
!! .
!!</center> <p>

!set wims_menu_tail=!append line getraw,1,cmd=reply&job=getuser&getuser=$getraw\
part_list,1,cmd=resume\
to $wims_menu_tail

