
!if $special_parm!=$empty
 !changeto help/$special_parm.phtml
!endif

!read adm/title.phtml 3\
\
Niveaux de sévérité des feuilles de travail
<p>
Le serveur calcule deux moyennes pour le travail de chaque participant sur
chaque feuille&nbsp;: un pourcentage de points obtenus par rapport au nombre
de points demandés et la qualité des points obtenus sur les exercices
de la feuille. Soient x ce pourcentage et y la qualité, tous deux ramenés
par proportionnalité à des valeurs entre 0 et 1. Voici les formules pour
calculer les notes.
<p>$table_header
$table_hdtr<th>Niveau<th>Formule<th>Explication
$table_tr<td align=center>0<td align=center>$scoremax max(x,y)
 <td>Très laxiste&nbsp;: maximum entre pourcentage et qualité.
$table_tr<td align=center>1<td align=center>$scoremax x
 <td>la qualité n'est pas prise en compte. Vous avez la note maximale
 lorsque tous les points demandés sont acquis.
$table_tr<td align=center>2<td align=center>$scoremax x y<sup>0.3</sup>
 <td>La qualité n'a que peu d'effet sur la note.
$table_tr<td align=center>3<td align=center>$scoremax x y<sup>0.5</sup>
 <td>Plus d'effet de la qualité.
$table_tr<td align=center>4<td align=center>$scoremax x y
 <td>Pour avoir une note de $scoremax, il vous faut ramasser tous les points
  demandés (100%) sans faire de faute (qualité=10).
$table_tr<td align=center>5<td align=center>$scoremax x<sup>2</sup> y
 <td>Le pourcentage manquant est sur-puni.
$table_tr<td align=center>6<td align=center>$scoremax x<sup>2</sup> y<sup>2</sup>
 <td>Toute faute est sur-punie.
$table_end <p>

