
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=gener,febrer,març,abril,maig,juny,juliol,agost,setembre,octubre,novembre,desembre

!distribute line Mitjana de la classe\
Mitjana\
Mitjana de notes positives\
Mitjana globale&nbsp;\
into name_classAverage,name_Average,name_posAverage,name_globalaverage

!set name_partdeleted=Participants suprimits
!set wims_name_reg_ex=Llista d'exercicis registrats
!set name_transfer=Transferir les activitats d'altres classes

!set name_thsheet=No,Títol,Punts<br>demanats,Pes,Punts<br>obtinguts,%,Qualitat&nbsp;,Severitat,Nota
!set name_minmax=min/mit/max de la classe&nbsp;

!set name_manualscore=Notes atribuides pel professor
!set name_autoscore=Notes enregistrades pel servidor
!set name_manual_notes=global,prof.,auto
!set name_examnote=Notes d'exàmens

!set name_severitylevels=Nivell de severitat dels fulls de treball
!set name_formula=No,Pes,Nivell
!set name_sheetstatut=prep,actiu,caducat,ocult

!distribute items Examen,Full,Exercici,Inici,Notes,Sessió,Fet&nbsp;,equiv.\
into name_Exam,name_Sheet,name_Exercise,name_Start,name_Score,name_Session,\
name_done,name_equiv

!set name_formula_comment=Podeu definir els nivells de severitat i els pesos dels fulls de \
treball a la taula següent. Les notes seran calculades amb un màxim =
!set name_formula2=Notes calculades sobre un màxim de $scoremax
!set name_pickup=Seleccioneu els fulls per<br>mostrar els resultats per full&nbsp;
!set name_warning= Heu presentat una sol·licitud il·legal.

!set name_click=Cliqueu sobre un nom per veure el detall del seu treball.
!set name_affi=la qualitat,el treball efectuat,les notes
!set name_workdetail=Detall del treball de
!set name_activesession=Aquest participant té una sessió d'examen activa&nbsp;

!distribute items Lloc de connexió, Temps restant, Sessió d'examen de ,minuts\
into name_connecting,name_remaining_time,name_exam_session,name_minutes

!set name_noyetparticipant=Aquesta classe no té encara cap participant.

!if $manual>0
 !set name_manual_explanation=<b>Explicacions.</b> A les columnes <tt>mitjana</tt>, \
 <tt>auto</tt> vol dir mitjana\
 de notes calculades a partir de les puntuacions obtingudes en els fulls de treball,\
  <tt>professor.</tt> vol dir mitjana de notes atribuides manualment pel professor. \
  La note <tt>global</tt> es calcula a partir de les altres dues per la fórmula
!endif

!set name_title_showsheet=!nosubst Detalls del treball en el full $numshowsheet<br>$sh_title
!set name_percentagegot=Percentatge de punts obtinguts
!set name_qualitygot=Qualitat del treball calculat sobre un màxim de 10
!set name_percentagedone=Percentatge de treball efectuat
!set name_post=Afficher

!if $job=userprop
  !distribute items Canviar, Número de registre, Comentaris, URL d'una foto, Variables (tècniques),\
  Contrasenya de la classe,Entreu la contrasenya de registre de participants\
  into name_change,name_regnum,name_comments,name_photourl,name_vars,\
  name_classpassword,name_enterpassword
  !goto end
!endif

!if $job=examcheck
 !set name_title_examcheck=!nosubst Detalls d'exàmens fets per $user_lastname, $user_firstname
 !set name_no_exampart=Aquest participant encora no ha fet cap examen.
 !set name_exampart=Aquestes són les sessions d'examen realitzades per aquest participant. Feu clic a \
  exercici per veure el seu contingut.
 !goto end
!endif
!if $job=getraw
  !set name_title_getraw=!nosubst Detall del treball de $lastname, $firstname<br>(en dades brutes)
  !goto end
!endif

!set name_direct_score=llista i notes directament

!if $job=transfer
   !set name_title_transfer=Transferir les activitats
   !distribute items Adjuntar, Reemplaçar,Examinar\
   into name_merge, name_replace,name_show
!endif
!set name_topten=!nosubst Millor $class_topscores de les mitjanes de la classe 
:end
