
<center><h3>Propriétés du compte de participant</h3></center>
!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!set inplen=40
!form reply
<input type=hidden name=job value=userprop>
<input type=hidden name=getuser value=$getuser>
<p>$table_header
$table_tr<th>Nom de login<td><tt>$getuser</tt>
$table_tr<th>Mot de passe<td>
	!href module=adm/class/passwd&job=part&part=$getuser Changer
$table_tr<th>Nom de famille<td>
	<input size=$inplen name=up_lastname value="$user_lastname">
$table_tr<th>Prénom<td>
	<input size=$inplen name=up_firstname value="$user_firstname">
$table_tr<th>email<td>
	<input size=$inplen name=up_email value="$user_email">
$table_tr<th>Numéro d'inscription<td>
	<input size=$inplen name=up_regnum value="$user_regnum">
!if $wims_user=supervisor
 $table_tr<th>Commentaires<td>
	<input size=$inplen name=up_comments value="$user_comments">
$table_tr<th>URL de la photo<td>
	<input size=$inplen name=up_photourl value="$user_photourl">
$table_tr<th>Variables (techniques)</th><td>
	<textarea wrap="off" cols=$[$inplen-1] rows=4 name=up_vars>$user_vars</textarea>
!else
 $table_tr<th>Mot de passe de la class<td>
	<input size=14 type=password name=passcheck> <br>
	<small>Entrez le mot de passe pour l'inscription de participants</small>
!endif
$table_hdtr<td align=center colspan=2>
<input type=submit name=reg value=Sauver> &nbsp;
<input type=submit name=abandon value=Annuler>
$table_end
</form>
!if $wims_user=supervisor
 <p><center>
 !href cmd=reply&job=getuser&getuser=$getuser Scores du participant
 .
 !href cmd=reply&job=getraw&getraw=$getuser Détail du travail
 .
 <p>
 !href cmd=reply&job=delprep&delprep=$getuser Supprimer le participant
 .
 !href cmd=resume Liste des participants
 .
 </center> <p>
!endif

!reset reg,abandon

