
!if $vote_option=anonymous
 Esta es una encuesta anónima.
!else
 Esta es una votación nominal.
!endif
!if $vote_status=2
 Está cerrada.
!endif

!if $wims_user=supervisor
 ($vcnt votes)
 !href cmd=reply&job=edit Modificar
<p>
!endif

!if $vote_status=2
 !changeto $votedir/$vote.def
!endif

!if $(user_vote_$Vote)!=$empty
 !if $vote_option=anonymous
  Ya ha votado. <p>
 !else
  Ya había hecho su elección, pero está a tiempo de cambiar de opinión.
  <p>
  !goto form
 !endif
!else
 Haga su elección: <p>
 :form
 !form reply
 <input type=hidden name=job value=vote>
 !set m_formed=yes
!endif

!read $votedir/$vote.def

!if $m_formed=yes
 <p><center>
 <input type=submit value="Grabar">
 </center></form>
!endif

!if $wims_user=supervisor and $vote_option=nominative
 <p> Detalle de las votaciones.
 !for i=1 to $parmcnt
  !for c=1 to $(choices$i)
   !if /supervisor/ notin $c/
    <p>
    !item $c of $(chlist$i)
 <br> <tt>
    !for u in $(votes_$(i)_$c)
     !set U=!translate internal / to , in $u
     !readproc adm/class/userdef classes,$U
     !defof user_lastname, user_firstname in $userdef
     ($u)
     <br>
    !endif
   !next u
   </tt>
  !next c
 !next i
!endif

