#! /bin/sh
###############################################################################
# gifs/theme/mkindex
#
# Create an automatic file "icon.css" for each theme icon directory.
# 
###############################################################################

cd `dirname $0`
type_list="png gif"

if [ ! -s wimsedu1/home.png ] ;
 then
    cd wimsedu ;
    for i in `ls *.png 2>/dev/null`; do convert -resize 30 $i ../wimsedu2/$i; done
    for i in `ls *.png 2>/dev/null`; do convert -resize 18 $i ../wimsedu1/$i; done
    cd .. ; 
fi;

for j in `ls` ; do
 if [ -d "$j" ] && [ ! -s "$j/icon_orig.css" ] ; then
	rm $j/icon.css ;
	touch $j/icon.css ;
	w=0; h=0
	for a in $type_list ; do 
	 if [ -s $j/home.$a ]; then 
         w=`identify -format \%w $j/home.$a`;
         h=`identify -format \%h $j/home.$a`;
	 fi;
	done;
	w=`expr $w + 4`
	h=`expr $h + 0`
	echo "#wimsmenumodubox .wimsmenu .menuitem a, .menuitem a, .topmenuitem a{
	background-repeat:no-repeat;
	background-position:0% 50%;
	min-height:"$h"px;
	line-height:"$h"px;
	padding-left:"$w"px;
}
#wimsmenubox .menuitem {background-image:none;}
" > icon.css
	for a in $type_list ; do 
	  for i in `ls $j/*.$a 2>/dev/null` ; do 
		file=`basename $i .$a` ; echo ".$file{background-image:url($file.$a);}" >> icon.css;
	  done
	done
	mv icon.css $j ;
 fi;
done
