!!<html><head>
!!$wims_html_header
!!</head>
!!<body $wims_htmlbody>
!!!headmenu
!read adm/css.phtml
!header1

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
Voti inseriti manualmente
!!<center>$classname
!!<p>
!!<h1>
!!</h1></center> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Torna alla home page del corso
. <p>
 !goto end
!endif

!form reply
<input type=hidden name=method value=percent>
<p>In questa pagina si possono attribuire manualmente voti agli studenti 
(ogni singolo partecipante ha poi la possibilità di visionare i voti
attribuitigli).

<p>Il sistema calcola automaticamente punteggi medi: i voti assegnati
manualmente contribuiscono per il 
<input size=4 name=per value="$percent">%
(<small><input type=submit name=reg value=cambia></small>)
al punteggio medio globale dei partecipanti.
!if $method!=list
<p>
 !href cmd=reply&method=list Annulla le modifiche
.
!set wims_menu_items=!append line back4,1,cmd=reply&method=list\
to $wims_menu_items
!endif
</form> <p>

!read $method.phtml

!!!if $method!=list
!!!href cmd=reply&method=list Annulla le modifiche
!!.
!!!endif

<p>
!if $method=user
!href module=adm/class/userlist&job=getuser&getuser=$un Gli altri voti dello studente $username
.
!endif

!set wims_menu_items=!append line otherscore,1,module=adm/class/userlist\
to $wims_menu_items

:end
!tail

!reset reg

