
!set classname=<b><font color=green>$wims_classname</font></b>\
 presso <b><font color=green>$wims_institutionname</font></b>

!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!set wims_name_otherscore=Gli altri voti
!set wims_name_back4=Torna all'elenco
!set wims_name_addmanual= Aggiungi una colonna
!set wims_name_raw=Modificare direttamente il file dei voti

!distribute  items Peso,Media \
  into name_weight,name_average

!set name_enter=Inserire i voti
!set name_enterof=Inserire i voti di

!set name_manual_title=Voti inseriti manualmente
!set name_explanation=In questa pagina si possono attribuire manualmente voti agli studenti \
(ogni singolo partecipante ha poi la possibilità di visionare i voti attribuitigli).\
<p>Il sistema calcola automaticamente punteggi medi: i voti assegnati\
manualmente contribuiscono al punteggio medio globale dello studente per il 

!set name_nomanual= Non ci sono voti inseriti manulamente
!set name_modify=Selezionare il nome di uno studente per modificarne i voti

!set name_can_also=Si può anche
!set name_can_also2=oppure esportare i
