!read adm/css.phtml
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname
!header1

!read adm/title.phtml 1\
$classname\
$cdt_title\
$cdt_subtitle

!if $error!=$empty
 <div class="wims_msg alert">
 !read lang/msg.phtml.$moduclass_lang
 </div>
!endif

!form reply
<input type="hidden" name="job" value="addtodo" />
<input type="hidden" name="job2" value="save" />
<fieldset class="property_fields halfwidth blockcenter">
	<legend>$name_worktodo</legend>
	<div class="field box">
		$name_session:
		!if $jyear=$empty
			!let jyear=!char 1 to 4 of $wims_now
			!let jmonth=!char 5 to 6 of $wims_now
			!let jday=!char 7 to 8 of $wims_now
		!endif
		!let expyear=!char 1 to 4 of $class_expiration
		!let creyear=!char 1 to 4 of $class_creation
		!distribute item $[$jday],$[$jmonth],$[$jyear] into jday,jmonth,jyear
		!read adm/lang/datemenu.phtml.$moduclass_lang 1,jday,jmonth,jyear
	</div>
	<div class="field box">
		$name_nb_date:
		<select  name="nbredevoir" onchange="submit()">
		!for i=1 to $max_todo
 			!if $i=$nbredevoir
  				<option value="$i" selected="selected">$i</option>
			!else
				<option value="$i">$i</option>
			!endif
		!next i
		</select>
	</div>
 	!for i=1 to $nbredevoir
		<div class="field box">
			$name_workfor
			!if $(dday$i)=$empty
			    !let dday$i=$jday
			    !let dyear$i=$jyear
			    !let dmonth$i=$jmonth
			!endif
			!distribute item $[$(dday$i)],$[$(dmonth$i)],$[$(dyear$i)] into dday$i,dmonth$i,dyear$i
   			!read adm/lang/datemenu.phtml.$moduclass_lang 1,dday$i,dmonth$i,dyear$i
  $
			!set wims_ref_class=wims_button_help
			!href target=wims_help cmd=renew&job=helplink&cible=ddesc$i $name_help_add
   			<br /><textarea $(wims_id$[$i-1]) rows="6" cols="120" name="ddesc$i">
			    !replace internal \( by &#92;( in $(ddesc$i)
			</textarea>
		</div>
	!next i
	<div class="field box">
		<p class="wimscenter">
		<input type="submit" value="$wims_name_tosave" $wims_on_click/>
		</p>
	</div>
</fieldset>

!formend
!!ARIANE already
!set wims_menu_items=!append line back2,1,cmd=new&job=home\
to $wims_menu_items

!tail
