!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$cdt_title

<div class="wimscenter" "style="font-size:large; font-weight:bold;">
 $name_worktodo
 !if $jour_begin!=$jour_end
  $name_between <span class="wims_emph">
    !read date.phtml $jour_begin,notime
  </span>
  $name_and <span class="wims_emph">
    !read date.phtml $jour_end,notime
  </span>
 !else
  $name_for
  <span class="wims_emph">
    !read date.phtml $jour_begin,notime
  </span>
 !endif
</div>

!if $nbligne=0
 <p>
 $name_nowork.
 </p>
 !goto end
!endif

 $table_header
 $table_hdtr
  <th>$name_for</th>
  !if no isin $cdt_supervise
   <th>$name_discipline</th>
  !endif
  <th>$name_work</th><th>$name_giventhe</th>
 </tr>
 !for i=1 to $nbligne
  $table_tr
   !let don=!line $i of $list
   !distribute item $don into todo,date,dir,matiere
   !let m_filedir=$wims_ref_name?session=$wims_session&cmd=getfile&special_parm=cdt/$dir
   !read wimshome/log/classes/$dir/cdt/def/$date
   !let no=!positionof item $todo in $date_todo
   <td>
    !read adm/lang/datemenu.phtml.$moduclass_lang 5,$todo,$dateoption
   </td>
   !if no isin $cdt_supervise
    <td>$matiere</td>
   !endif
   <td valign="top">
    !read wimshome/log/classes/$dir/cdt/def/$date todo$no
   </td>
   <td>
    !read adm/lang/datemenu.phtml.$moduclass_lang 5,$date,$dateoption
   </td>
  </tr>
 !next i
 $table_end
:end
!if _ notin $wims_session
 !set wims_menu_items=!append line back2,1,module=$module \
 to $wims_menu_items
!endif
!tail
