!read adm/title.phtml 1\
$classname\
$name_partdeleted


!if $delcnt<1
 Il n'y a pas de participant supprimé dans cette classe.
 <p>
!else
 Cliquez sur un nom de login pour remettre le participant dans la classe.
 $table_header
 $table_hdtr<th>$wims_name_Login<th>$wims_name_name
 !for i in $deleted
  !set names=!getdef user_lastname, user_firstname in wimshome/$userdir/.$i
  $table_tr<td>
  !href cmd=reply&job=recover&getuser=$i $i
  <td>$names</td>
 !next i
 $table_end <p>
!endif

</center> <p>

!set wims_menu_items=!append line part_list,1,cmd=resume\
to $wims_menu_items
