<center>$classname<p>

<h3>Session d'examen de
 !href cmd=reply&job=userprop&getuser=$getuser $lastname, $firstname
<br><font size=-1>Login name: <tt>$getuser</tt>
!if $user_email!=$empty
 &nbsp;Address: <a href="mailto:$user_email">$user_email</a>
!endif
</font></h3></center> <p>

 $table_header$table_tr<td align=right>Nom de session :</td>
 <td><tt>$esession</tt></td></tr>
 $table_tr<td align=right>Poste de connection :</td>
 <td><tt>$ehost</tt></td></tr>
 $table_tr<td align=right>Temps restant :</td>
 <td>$eremain minutes</td></tr>
 $table_end <p>

<center>
!href cmd=reply&job=userexamclose&getuser=$getuser Fermer cette session d'examen
 de $lastname,$firstname.
 <p>
!href cmd=reply&job=getuser&getuser=$getuser Scores du participant
 .
!href cmd=resume Liste des participants
 .
</center>
