
<center><h3>Propriétés du compte de participant</h3></center>
!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!set inplen=40
!form reply
<input type=hidden name=job value=userprop>
<input type=hidden name=getuser value=$getuser>
<p>$table_header
$table_tr<th>Nom de login<td><tt>$getuser</tt>
$table_tr<th>Mot de passe<td>
	!href module=adm/class/passwd&job=part&part=$getuser Changer
$table_tr<th><label for="up_lastname">Nom de famille</label><td>
	<input size=$inplen name=up_lastname id=up_lastname value="$user_lastname">
$table_tr<th><label for="up_firstname">Prénom</label><td>
	<input size=$inplen name=up_firstname id=up_firstname value="$user_firstname">
$table_tr<th><label for="up_email">email</label><td>
	<input size=$inplen name=up_email id=up_email value="$user_email">
$table_tr<th><label for="up_regnum">Numéro d'inscription</label><td>
	<input size=$inplen name=up_regnum id=up_regnum value="$user_regnum">
!if $wims_user=supervisor
 $table_tr<th><label for="up_comments">Commentaires</label><td>
	<input size=$inplen name=up_comments id=up_comments value="$user_comments">
 $table_tr<th><label for="up_photourl">URL d'une photo</label><td>
	<input size=$inplen name=up_photourl id=up_photourl value="$user_photourl">
 $table_tr<th><label for="up_vars">Variables (techniques)</label></th><td>
	<textarea wrap="off" cols=$[$inplen-1] rows=4 name=up_vars>$user_vars</textarea>
!else
 $table_tr<th><label for="passcheck">Mot de passe de la classe</label><td>
 	<input size=14 type=password name=passcheck id=passcheck> <br>
	<small>Entrez le mot de passe d'inscription de participants</small>
!endif
$table_hdtr<td align=center colspan=2>
<input type=submit name=reg value=Sauver> &nbsp;
<input type=submit name=abandon value=Annuler>
$table_end
</form>
!if $wims_user=supervisor
 <p><center>
 !href cmd=reply&job=getuser&getuser=$getuser Scores du participant
 .
 !href cmd=reply&job=getraw&getraw=$getuser Détail du travail
 .
 <p>
 !href cmd=reply&job=delprep&delprep=$getuser Supprimer le participant
 .
 !href cmd=resume Liste des participants
 .
 </center> <p>
!endif

!reset reg,abandon

