<center>$classname<p>

<h3>$name_exam_session
 !href cmd=reply&job=userprop&getuser=$getuser $lastname, $firstname
<br><font size="-1">Login name: <tt>$getuser</tt>
!if $user_email!=$empty
 &nbsp;$wims_name_email: <a href="mailto:$user_email">$user_email</a>
!endif
</font></h3></center> <p>

 $table_header$table_tr<td align=right>$wims_name_Session :</td>
 <td><tt>$esession</tt></td></tr>
 $table_tr<td align=right>$name_connecting:</td>
 <td><tt>$ehost</tt></td></tr>
 $table_tr<td align=right>$name_remaining_time:</td>
 <td>$eremain $name_minutes</td></tr>
 $table_end <p>

!set wims_menu_items=!append line partexamclose,1,cmd=reply&job=userexamclose&getuser=$getuser\
scores,1,cmd=reply&job=getuser&getuser=$getuser\
part_list,1,cmd=resume\
to $wims_menu_items
