<b>Opciones múltiples controlables por el autor</b>: <span class="tt">checkbox</span>,
 <span class="tt">click</span>, <span class="tt">menu</span>, <span class="tt">radio</span>, <span class="tt">mark</span><br/>.
 Pueden utilizarse para sustituir a la entrada estándar de opción múltiple
 (<span class="tt">\choice</span>), pues proporcionan mayor control sobre la presentación.
 La respuesta correcta debe contener dos campos, separados por un punto y coma
 ``<span class="tt">;</span>''. El segundo campo (tras el punto y coma) es la lista de textos
 de la opción, mientras que el primero es una lista con los números de las opciones 
 correctas. En el caso de la <span class="tt">checkbox</span>, el usuario debe escoger 
 exactamente todas las opciones correctas. En los casos restantes bastará
 escoger cualquier opción correcta.
 <p>
 En estos casos no se aplica ninguna permutación aleatoria automática,
 y el número de opciones no está limitado.
 <p>
 <span class="tt">click</span> debe usarse únicamente en el caso de que no haya más 
 respuestas u opciones.
 <p>
 <span class="tt">mark</span> funciona como <span class="tt">checkbox</span>, con la diferencia de que, en 
 lugar de un botón, es el elemento elegido el que cambia de color para
 indicar la elección. Por tanto es útil principalmente para el texto del
 enunciado.
</ol>
