:signification
Geef "dragfill" of "clickfill" velden aan van een (groot) plaatje.
Moet worden ingezet in het "statement" van een OEF oefening.
 
:example
<span class="wims_help_example">Voorbeeld</span>
 <pre>
\special{imagefill \imagedir/myphoto.jpg,450x350,40x40
reply 1,120x250
reply 3,300x50
reply 4,10x15
}
</pre>
In dit voorbeeld wordt een plaatje van 450&times;350 (<tt class="wims_fname">\imagedir/myphoto.jpg</tt>) in het
 statement verwerkt.
 Er zijn in dit plaatje een 3-tal 'drag &amp; drop' velden aanwezig van 40&times;40 , op
 posities 120x250, 300x50, 10x15 binnen het grote plaatje. 
 Deze 3 velden corresponderen met antwoord 1,3 en 4 (allen van het antwoord model "clickfill" of "dragfill")
 
 <p> 
 Het plaatje wordt aangepast zodat het precies het vereiste formaat heeft.
 </p>
 <p>
 Het is mogelijk meerdere antwoorden te verwerken. Voeg hiertoe een derde integer parameter toe 
 aan de grootte. <tt class="wims_code_words">reply 1,120x250x4</tt> zal een invulveld tonen met lengte 4.