<script type="text/javascript" src="scripts/js/wz_tooltip.js"></script>
:signification
het maken van een tooltip : de eerste parameter is de tekst van de link,
de derde parameter is de tekst zichtbaar in de tooltip,
de tweede parameter is een tekst optie tussen vierkante haken:
de opties zijn in de syntax van "wz_tooltip.js".
Default is : [FONTSIZE, '12pt', ABOVE, 'true']
Om enkel de wz_tooltip.js bibliotheek the laden (1 keer is voldoende voor de gehele pagina)
moeten geen parameters worden gebruikt.
Als de javascript al eens is geladen, voeg dan <tt class="wims_code_words">nojs</tt>
als tweede parameter toe.
De css style class kan worden geconfigureerd voor: <tt class="wims_code_words">span.tooltip</tt>.

:example
<span class="wims_help_example">Example</span>
<pre>
\special{tooltip klik hier, ,Het gezocht woord heeft 5 letters}
\special{tooltip klik hier,[DURATION, 4000, FONTSIZE, '18pt'], Het gezocht woord heeft 5 letters}
\special{tooltip klik hier,[TITLE, "Een title', PADDING, 9],Een tekst}
\special{tooltip }
\special{tooltip klik hier,nojs [TITLE, 'Een title', PADDING, 9],Een tekst}
</pre>
<p>
Mogelijke configuratie opties voor de tooltips  (zie ook: www.walterzorn.com)
 <embed>
!read js/tooltip_doc.html
</embed>