<p><hr> <p>
!read Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=8
!if $qcnt>$exocnt
 !set qcnt=$exocnt
!endif
!if $exocnt<1
 Spiacente, questo modulo non contiene esercizi per ora. 
 Riprova pi&ugrave; tardi
 !exit
!endif
!if $exocnt=1
 Questo modulo al momento contiene un solo esercizio, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Provalo.
 !exit
!endif

!form new
<input type=hidden name=module value=$module>
<center><table border=0><tr>
<td align=center>Seleziona lo scenario:<td>
!if $exocnt>6
 !set selsize=6
!else
 !set selsize=$exocnt
!endif
!set wims_formselect_switch=multiple size=$selsize
!set exo=$special_parm
!if $exo!=$empty
 !set exolist=!listuniq $exo,$exolist
 !set exolist=!replace , by , $ in $exolist
 !set dictionary=$module_dir/Extitles
 !set translator_unknown=leave
 !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
 <tr><td align=center>Stile dell'esercizio:<td>
 !formselect style list 1,2,3,4 prompt \
 	trovare il primo passaggio non corretto,\
	trovare tutti i passaggi non corretti,\
	analisi passo passo senza giustificazioni,\
	analisi passo passo con giustificazioni
 <tr><td align=center>Livello di severit&agrave;:<td>
 !default level=2
 !formselect level from 1 to 5
 </table>
 <p><input type=submit value="Al lavoro">
 </center> <p>
 
