
!if $sstyle=1
 !if $substep=0
  !if $all_steps=0
   !form reply
   Which is the <em>first</em> wrong step of this series?
   !formselect badstep from 0 to $stepcnt
   (0 would mean that every step is correct.)
   <p><center><input type=submit value="Send the reply"></center>
  !else
   Mark <em>all</em> bad steps above, then
   <input type=submit value="click here">.
  !endif
  </form>
 !else
  !if $all_steps=0
   !if $badstep=0
    Indeed, all the steps are correct.
   !else
    Indeed, the first bad step is number $badstep.
   !endif
  !endif
  Your score: $module_score/10.
  !if $expstep!=$empty
   <p>Some explanations.<ul>
   !for i in $expstep
    <p><li> Step $i
    !if $i isitemof $badstep
     is correct.
     !line $i of $remarks
    !else
     !set j=!positionof item $i in $bad_steps
     !set e=!item $j of $bad_reasons
     is not good.
     !read reasons/$e.det
    !endif
   !next i   
   </ul>
  !endif
 !endif
!else
 !if $substep=0
  !form reply
  What do you think of the <em>last</em> step?
  !formselect ans list --,OK,$bad_reasons prompt I don't know,\
  	Yes : this step is correct,$bad_rnames
  <input type=submit value="Send">
  </form>
 !endif
 
 !if $substep=2
  You are right:
  !if $step_reason=OK
   the last step is correct.
  !else
   the last step is wrong.
   The good step will be<p><center>
   <table border=0 bgcolor="#d0c0d0" width="80%"><tr><td align=center>
   !line $step of $good
   </table> </center>
  !endif
  <p>
  !if $step<$stepcnt
   !href cmd=reply&ans=next Pass to the next step.
  !else
   This is the end of the exercise. Your score: $module_score/10.
  !endif
 !endif
!endif

