
<b>Réinstaller une sauvegarde de la classe</b>. <br>
Il y a principalement deux occasions où vous aurez besoin de réinstaller un
fichier de sauvegarde sur le serveur.
<ul><li><b>Votre classe est endommagée par une raison ou une
autre. </b> Dans ce cas, une restauration aussi complète que possible est
recommandée (excepté la configuration de la classe et le compte
d'enseignant s'ils ne sont pas endommagés). A cause des inter-dépendances de
différents types de ressources dans la classe, une restauration partielle
risque de ne pas fonctionner. Et bien entendu vous devez utiliser une
sauvegarde de VOTRE classe, mais pas celle d'une autre.
</li>
<li><b>Vous voulez installer des ressources téléchargées
d'une autre classe sur la vôtre.</b>
Ceci doit être fait seulement quand votre
classe est vide, au début de son installation. Et vous devez respecter les
!href cmd=help&special_parm=dependencies dépendances
 entre les ressources. Les règles de base sont de ne pas restaurer les
registres d'activités de participants et de ne pas restaurer les ressources d'enseignement
interactives (documents, exercices, feuilles de travail et d'examen) 
à partir de sources différentes.
</li>
</ul>

