
One of the main types of activities on WIMS is interactive exercises.
<p>
These exercises may take various styles. For example,
!href target=wims_demo module=H5/geometry/gravshoot.en Gravity shoot
 asks you to click on a picture and gives you a score according to the
distance between your click and the good position;
!href target=wims_demo module=H6/geometry/coincfree.en Coincidence Freehand
 presents you a curve and asks you to enter a function to fit the curve
as precisely as possible, allowing you several tests;
!href target=wims_demo module=U1/analysis/graphder.en Graphic derivative
 gives you the graph of a function and asks you to recognize that of
the derivative of the function;
!href target=wims_demo module=H6/analysis/scenarineq.en Scenario of inequalities
 presents a step by step commented argument and asks you to find out 
erroneous steps;
!href target=wims_demo module=H6/algebra/decrypt.en Decrypt
 shows a crypted message and lets you recover it through step by step 
experiments; etc.
<p>
There are many OEF (Open Exercise Format) exercise packages, each collecting
a number of more traditional exercises on a given theme. You can selectively
choose a subset of the exercises in each package, to work on them. Teachers can
also
!href module=$module&chapter=4&open=$open,4_oef#oef create
 their own OEF exercises directly online.
<p>
Most interactive exercises on WIMS are configurable with different
difficulty levels and styles. Configuration of the exercise is done in an
introduction page, so that once you start to work on the exercise, the
difficulty level will remain stable.
<p>
This is important because WIMS exercises are highly repeatable. You can
ask for the same exercise again and again, and get one with different parameters
each time. On the one hand, this allows you to repeatedly practice on the
exercise until you get a sufficiently good understanding; on the other hand,
when many students are working side by side on a same exercise (in a
computer room), the risk of copying is reduced to the minimum.
<p>
When you finish an exercise, WIMS attributes a score to you according to
your degree of success. The score ranges from 0 (total failure) to 10 (full
success). When you are signed in as a participant of a class and work on the
exercise as one of the assignment of the teacher, this score will be
registered on the server. The server can process the score of each participant
and present them to the teacher in different ways, in real time.
<p>
Note that some exercises can be organized in ``sessions'' composed of a
given number of questions. In this case, a score is attributed only at the
end of the session (but not at the end of each question), which is usually
computed according to your degree successes to all the questions in the
session as a whole. And the number of questions in a session can usually be
configured in the introduction page.



