<p>
!if $module_language=fr
 Si votre clavier n'a pas de lettres avec accent : vous pouvez taper
 <tt>e'</tt> pour é, <tt>a`</tt> pour à, <tt>i"</tt> pour ï, 
 <tt>o^</tt> pour ô, <tt>n~</tt> pour ñ, <tt>c~</tt> pour ç, etc.
 <p>
 !exit
!endif
!if $module_language=nl
Om letters met accenten in te typen op een keyboard zonder deze, kunt U 
 <tt>e'</tt> voor é, <tt>a`</tt> voor à, <tt>i"</tt> voor ï, 
 <tt>o^</tt> voor ô, <tt>n~</tt> voor ñ, <tt>c~</tt> voor ç, enz. gebruiken
 <p>
 !exit
!endif
!if $module_language=es
 Si su teclado no tiene las teclas con los acentos puede teclear
 <tt>e'</tt> para escribir é, <tt>a`</tt> para à, <tt>i"</tt> para ï, 
 <tt>o^</tt> para ô, <tt>n~</tt> para ñ, <tt>c~</tt> para ç, etc.
 <p>
 !exit
!endif

To type accented letters on a keyboard without them: you may enter
<tt>e'</tt> for é, <tt>a`</tt> for à, <tt>i"</tt> for ï, 
<tt>o^</tt> for ô, <tt>n~</tt> for ñ, <tt>c~</tt> for ç, etc.
<p>

