
!if $datacnt<1
 Na tem stre¾niku ¹e niso name¹èeni nobeni novi moduli (avtomatsko bele¾enje nadgradenj deluje ¹ele od razlièice WIMS-3.37f).
 !exit
!endif

!set w_=!replace internal /wims.cgi by in $wims_ref_name

$table_header
<caption>Zadnji moduli, name¹èeni na tem stre¾niku:
<a href="$w_/rss/modif.xml"><img src="gifs/rss.png" border=0 alt=rss></a></caption>
$table_hdtr<th>Datum</th><th>Jezik</th><th>Naslov</th><th>Opis</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_ 
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>$desc</td></tr>
 !reset desc tit
!next i
$table_end
