!!<html><head>
!!$wims_html_header
!!</head>
!!<body $wims_htmlbody>
!!!headmenu
!header1

!if $cmd=help and $special_parm=about
 !read about.phtml
 !goto end
!endif

!if $cmd=help
 !read help.phtml
 !goto end
!endif

<center><h1>WIMS à $httpd_HTTP_HOST
<br>Statistique de fréquentation</h1></center>
<p><hr> <p>

!if $sitestart=$empty
 Le compte de fréquentation n'est pas en place sur ce site. Pas de statistique
 disponible. Désolé. <p>
 !goto end
!endif

!if $show=yes and $total_site>0 and $laps>0
!!if $show=yes
 !href cmd=resume Retour au menu
 <p>
 !read answer.phtml
 !href cmd=resume Retour au menu
 <p>
!else
 !if $usercnt>0
  Il y a $classcnt portails et classes individuelles sur ce serveur, avec
  $usercnt comptes d'utilisateur au total.
  <p>
 !endif
 !read menu.phtml
!endif
:end
!homeref
</body></html>

!set stat_module=
