
!form reply
 !set s_day=jour(s)
 !set s_week=semaine(s)
 !set s_month=mois
 !set s_year=année(s)
 !set s_beginning=le début $start_day/$start_month/$start_year
 !set name2=requêtes
 !set name3=séances
 !set name4=sites visiteurs
 Choisissez une période pour la statistique: depuis
 <select name=cnt>
 !for i=1 to 15
  <option value=$i
  !if $i=$cnt
   selected
  !endif
  >$i
 !next i
 </select><select name=style>
 !for i in day,week,month,year,beginning
  <option value=$i
  !if $i=$style or ($i=week and $style=$empty)
   selected
  !endif
  >$(s_$i)
 !next i
 </select>. <p>
 Type de tracé :
 !for i=2 to 4
  <input type=radio name=plot_type value=$i
  !if $i=$plot_type
   checked
  !endif
  >$(name$i) &nbsp;
 !next i
 <p>
 <input type=checkbox name=modules value=yes
 !if $modules=yes
  checked
 !endif
 > Montrer aussi les détails par module.
 <p>
 <center><input type=submit value="Montrer la statistique"></center>
</form>

!set modules=