:signification
 Put dragfill or clickfill fields into a big image. To be used in the
 statement of an OEF exercise. 
 
:example
<span class="wims_help_example">Example</span>
 <pre>
\special{imagefill \imagedir/myphoto.jpg,450x350,40x40
reply 1,120x250
reply 3,300x50
reply 4,10x15
}
</pre>
 This example puts a big image (<tt class="wims_fname">\imagedir/myphoto.jpg</tt>) in the
 statement, of size
 450x350, with 3 embedded drag-and-drop fields of size 40x40. The 3 fields
 are respectively answers 1,3 and 4 (which must be of clickfill or dragfill
 type), and at respective positions 120x250, 300x50, 10x15 within the big
 image.
 <p> The big image will be stretched to fit exactly the specified size.
 <p> It is possible to have multiple answers. Add a third integer parameter to the size
 <tt class="wims_code_words">reply 1,120x250x4</tt> will show a field of length 4.