<script type="text/javascript" src="scripts/js/wz_tooltip.js"></script>
create a tooltip :  the first parameter is the text of the 
link,
the third parameter is the text which appears in the tooltip. 
the second parameter is text option inside bracket : 
Inside brackets, you must put option as in the wz_tooltip.js documentation. 
Default is : [FONTSIZE, '12pt', ABOVE, 'true']
If you want only to load the javascript (once time is sufficient for one 
html page), don't put any parameter. If you don't want to load the javascript
because you are sure it is already loaded in the html page, add <tt>nojs</tt>
in the second parameter. 
You can configure css style class <tt> span.tooltip</tt>.

<p><b>Example</b> <br>
<pre>
\special{tooltip click here, ,the word has 5 letters}
\special{tooltip click here,[DURATION, 4000, FONTSIZE, '18pt'], the word has 5 letters}
\special{tooltip click here,[TITLE, 'Some Title', PADDING, 9],un texte}
\special{tooltip }
\special{tooltip\special{tooltip click here,nojs [TITLE, 'Some Title', PADDING, 9],un texte}
</pre>
<p>The possible options for tooltips are  (from www.walterzorn.com)
 <embed>
!read js/tooltip_doc.html
</embed>