Servidor remoto: 
<font color=blue>$connident</font>
($ident_desc) localizado en
<a href="http://$site">$site</a>, del tipo
<font color=blue>$ident_type</font>.

!if $cn_status!=OK
 <p><b>Error</b>.
 !if $cn_status=$empty
  El servidor remoto no responde. Por favor informe al
  <a href=mailto:$wims_site_manager>administrador del sitio</a>.
 !else
  La conexión ha sido rechazada por el servidor remoto. Mensaje de error:
<pre>
$cn_data
</pre>
 !endif
 !set error=yes
 !exit
!endif

