!set proc=oef
!header

!if $wims_class=$empty
 This module is an internal module of a virtual class. As you are not
 connected as a member of this class, you don't have the right to access
 it. Sorry.
 <p><center>
 !href $ Back to wims
 </center> <p>
 !exit
!endif

This module gathers interactive exercises for <font
color=blue>$wims_classname</font> of <font
color=blue>$wims_institutionname</font>, which are created in the class.
!if $wims_user=supervisor
 !href module=adm/createxo Click here
 to create another exercise.
!endif

!read oef/intromenu.phtml
!tail

