
!if $fsize=$empty
Helaas, ik kon geen backup-archief maken van deze klas
 !exit
!endif

Hier is de backup file van deze klas:
!getfile $fname.$format $fname.$format
 ($fsize K).
<p>

!if $fsize<50 and all isitemof $selection
 !exit
!endif

!form reply
<input type=hidden name=job value=$job>
<input type=hidden name=job2 value=$job2>
!if $fsize<200
U kunt ook een
!else
Deze backup file is veel te groot om terug te sturen naar de server 
(deze limiet is wel instelbaar door de sitemanager).<br>
Om de backup file grootte te reduceren kunt U ook een
!endif

<input type=submit value="selectieve backup maken">:
<p>
!set selection=$select
!formcheckbox selection list $reclist prompt $tot
<p>
<b>Opmerking</b>. 
Het is vaak erg handig om meerdere kleinere selectieve backups te maken van bijvoorbeeld:
documenten, forum berichten, cijfers enz.

</form>


