
Backup is terug gezet in uw klas: $restored.

!if $user_bad!=$empty
 <p>
 De herstel procedure (met name leeringen-accounts en activiteiten-logs)
   is mislukt omdat er blijkbaar niet genoeg ruimte beschikbaar is voor Uw klas op deze server.
!endif

!if $exp_bad!=$empty
 !distribute items onherkenbaar, te vroeg, te laat into ebad,eearly,elate
 <p>
 De vervaldatum van deze klas is door deze herstelprocedure gemodificeerd 
 omdat de vervaldatum in de upload is $(e$exp_bad). 
!endif

