
<center><h3>Formats tableurs acceptés</h3></center>

Pour charger des données d'un tableur à la classe, sauvez les données sous
un format texte (séparateur virgule ou tab), dans un fichier avec extension
.txt, .csv, ou .tsv. La majorité des logiciels de tableur vous permettent de
sauver les données dans de tels formats.
<p>
Puis, mettez le nom du fichier dans le champ <tt>Fichier de données</tt>, et
envoyez-le au serveur WIMS.
<p>
Si vos données contiennent des lettres avec accent, il faut les encoder dans
l'encodage de WIMS pour le français, qui est $wims_main_font. (Si vous ne
savez pas ce que c'est, renoncez aux accents.)

