
$table_header
<caption>Champs de données valables</caption>
$table_hdtr<th>Nom<th>Signification
$table_tr<td>login<td>nom de login name du participant
!if $special_parm!=upload
$table_tr<td>name<td>nom de famille et prénom (dans cet ordre, deux colonnes)
!endif
$table_tr<td>lastname<td>nom de famille
$table_tr<td>firstname<td>prénom
$table_tr<td>password<td>mot de passe du participant, téléchargé sous forme
	cryptée spécifique, mais peut être envoyé au serveur en clair.
$table_tr<td>email<td>adresse électronique
$table_tr<td>regnum<td>numéro d'inscription
$table_tr<td>comments<td>commentaire concernant le participant
!if $special_parm!=upload
$table_tr<td>allscore<td>l'ensemble de notes et moyennes
$table_tr<td>averages<td>moyennes des notes (du serveur et manuelles)
$table_tr<td>average1<td>moyennes des notes attribuées par le serveur
$table_tr<td>average2<td>moyennes des notes envoyées par l'enseignant
$table_tr<td>sheets<td>notes de toutes les feuilles de travail (l'une après l'autre)
$table_tr<td>sheet1,sheet2,...<td>notes de la feuille 1, feuille 2, ...
$table_tr<td>exams<td>notes de tous les examens
$table_tr<td>exam1,exam2,...<td>notes de examen 1, examen 2, ...
$table_tr<td>manuals<td>toutes les notes de l'enseignant (l'une après l'autre)
!endif
$table_tr<td>manual1,manual2,...<td>notes attribuées par l'enseignant 1, 2, ...

$table_end <p>

Un champ non reconnu est ignoré.

