
!read adm/title.phtml 1\
\
Envoyer les données d'un tableur à la classe

Pour envoyer des données de votre tableur à la classe, sauvez les données
dans un fichier au format texte (txt, csv, ou tsv), puis envoyez le fichier 
au serveur.
<p>
Vous pouvez ainsi envoyer des informations sur les participants ou des notes.
Pour envoyer les informations au moment de l'inscription par exemple,
aucune note ne doit apparaître dans les données.
<p>
La première ligne du tableau doit être formée des noms de chaque colonne
 (par exemple, <tt>login</tt>, <tt>firstname</tt>, ...). Les noms
de colonnes valables et leur signification sont donnés dans le tableau
ci-dessous. Vous pouvez choisir une combinaison arbitraire de ces colonnes
et les placer dans n'importe quel ordre, avec la seule condition que le
champ <tt>login</tt> doit obligatoirement être présent (WIMS utilise ce champ pour
reconnaître les participants). Si vous voulez qu'une ligne soit ignorée,
placez un caractère `#' dans le champ `login'.
<p>
Vous pouvez utiliser cette méthode pour ajouter des participants (beaucoup
d'un seul coup) : dans ce cas le tableau doit contenir suffisamment
d'information valable pour chaque participant à ajouter (nom de famille,
prénom, mot de passe).
<p>
Si vous ajoutez des notes à la classe, la colonne correspondant à ces notes
doit déjà exister dans la classe. Sinon, vous devez la créer avant d'envoyer
les notes.
<p>
Un exemple de fichier valable pour l'inscription :
<pre>
login,firstname,lastname,password
toto,Claude,Toto,1234
</pre>
!read help/fieldtab.phtml
