!!FIXME
(identification : $idp_method, authentification : $auth_method) 
<p>
!if $class_defined!=yes
 <span class="wims_warning">$wims_name_Error</span>. $name_warning
 !exit
!endif
!read adm/class/initclass $class,auth
!if $class_mixed_external_auth>0 and $auth_user !=supervisor
<div class="wims_external_auth">
$(class_external_auth)
</div>
 !if $class_mixed_external_auth=2
  !exit
 !endif
$name_warning_external
<hr>
!endif

!if no_cgu notwordof $error
 !reset user_auth
 !set wims_form_method=post
 !!FIXME
 !if $auth_method notitemof cas
 $name_enter
   !form reply
   !set auth_user=$auth_user_connection
    <center><table border="0">
  <tr><td>$wims_name_Login</td><td><input size="20" name="auth_user" value="$auth_user"></td></tr>
  <tr><td>$wims_name_Password</td><td><input type="password" size="20" name="auth_password"></td></tr>
  $table_end
  <p><center>
  <input type="submit" value="$wims_name_Enter">
  </center>
  </form>
  <p>
  !!FIXME too much !if
   !if $idp_method notwordof ldap
   $name_new_participant:
   !endif
 !else
   !if $idp_method notwordof ldap
    $name_new_participant_external:
   !endif
 !endif
!if $idp_method notwordof ldap
 !if $subclass=yes
   !set tmp_=&subclass=$subclass
 !endif
 !set wims_ref_class=wims_button
 !href module=adm/class/reguser&class=$class$tmp_ $name_register
 </p>
 !endif
!endif
