
!if $class_defined!=yes
 <span class="wims_warning">$wims_name_Error</span>. $name_warning
 !exit
!endif
!if $class_mixed_external_auth>0
<p>
$(class_external_auth)
 <p>
 !if $class_mixed_external_auth=2
  !exit
 !endif
$name_warning_external
<hr>
!endif

$name_enter

<p>
!set wims_form_method=post
!form reply
<center><table border="0">
 <tr><td>$wims_name_Login</td><td><input size="20" name="auth_user" value="$auth_user"></td></tr>
 <tr><td>$wims_name_Password</td><td><input type="password" size="20" name="auth_password"></td></tr>
 $table_end
 <p><center>
 <input type="submit" value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register