!if $clcnt<=0
 $name_example1
 !exit
!endif

!if $lacnt<=0
 $name_example2
 $name_example3b ($listla).
 !exit
!else
  $name_example3
!endif
!if $othercnt>0
$name_example3b ($listla).
!endif
$name_example4
!href module=adm/class/regclass  $wims_name_classcreate
!let nb=!itemcnt $classification
!bound exampletype between 1 and $nb default 3
<p>
<center>
 !for k=1 to $nb
  !let titre=!item $k of $classification
   !if $k!=$exampletype
    !set wims_ref_class=wims_button
    !href cmd=reply&exampletype=$k $titre
    &nbsp;
   !endif
 !next k
 </center>
 $table_header
 <caption>$(classification[$exampletype])</caption>
  $table_hdtr<th>$wims_name_name</th>
  <th>$name_connexion</th><th>$name_register</th></tr>
  !for i=1 to $clcnt
   !set l=!line $i of $classes
   !distribute items $l into code,expire,inst,cl
   !defread wimshome/log/classes/$code/.def
   !distribute char $class_level into l_,y_
   !let clsty=!positionof item $class_level in E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,H7,U1,U2,U3,U4,U5,U6
   !if $clsty!=$empty
    !let clsty=!item $clsty of 1,1,1,1,1,1,2,2,2,2,3,3,3,4,4,4,4,4,4
   !endif
   !if $exampletype=$clsty or ($clsty=$empty and $exampletype=$nb)
    $table_tr
     <td align="center">$cl</td>
     <td align="center">
     !set wims_ref_class=wims_button
      !href module=home&user=anonymous,$code,anonymous $name_anonymous
      &nbsp;
      !set wims_ref_class=wims_button
      !href module=$module&type=authparticipant&class=$code $name_registered
     </td>
     <td align="center">
     !set wims_ref_class=wims_button
      !href module=adm/class/reguser&class=$code $name_register
     </td>
    </tr>
   !endif
  !next i
 $table_end
<p>
 
$name_instruction

$name_sheet_example

!href module=home&search_keywords=&search_category=S $wims_name_sheet

