
   <td align="center" colspan="2">
    !if $class_auth iswordof cas
     !set url = $wims_ref_name?module=adm/class/classes&type=authsupervisor&class=$code
     !read adm/codeurl $url
     <a class="wims_button" href="$class_cas_auth/login?service=$script_out">$wims_name_Enter</a>
     
     !set wims_ref_class=wims_button
     !set url = $wims_ref_name?module=adm/class/reguser&type=authsupervisor&class=$code
     !read adm/codeurl $url
   <a class="wims_button" href="$class_cas_auth/login?service=$script_out"> $name_register</a>

    !endif
    !if $class_auth iswordof php
      <a class="wims_button" href="$class_php_auth?enter=$code">$wims_name_Enter</a>
   !endif
   !if $class_auth iswordof ldap
     !set wims_ref_class=wims_button
     !href module=$module&type=authsupervisor&class=$code $wims_name_Enter
   !endif
   </td>