!if $option iswordof newcase
 !changeto deduc/$module_language/form$option.phtml
!endif

!if $casefinished!=$empty
 Le cas
 !htmlmath $casefinished
 est terminé.
!endif

!if $casecnt>1
 !if $casecnt<3
  !if $casefinished!=$empty
   Il vous reste le
  !else
   C'est votre
  !endif
  dernier cas à traiter&nbsp;:
 !else
  !if $casefinished!=$empty
   Il vous reste
  !else
   Vous avez
  !endif
  !href cmd=reply&opt=newcase $[$casecnt-1] cas
  à traiter. Cas actuel&nbsp;:
 !endif
 !htmlmath $caseid
 <p>
!endif

!form reply
!if $currstep=1
 Vous devez résoudre cet exercice étape par étape, avec les méthodes
 d'étape présentées dans le menu.
 Méthode pour la première étape&nbsp;:
!else
 Méthode pour étape $currstep&nbsp;:
!endif
 <small>[
 !href cmd=help&help_subject=methall&special_parm=$thisexo $wims_name_help
 ]
 !set random1=!randint 1,10^6
 !set random2=!randint 1,10^6
 !set random=$random1.$random2
 [
 !href cmd=help&help_subject=status&special_parm=$random état de l'exercice
 ]</small> <br>
!set n_=!linecnt $m_context
!reset l_,t_
!if $n_>10 and prf/cleanhyp notitemof $mthlist
 !set l_=,prf/cleanhyp
 !set t_=,Effacer des hypothèses inutiles
!endif
!formselect method list -,$mthlist$l_ prompt $ch_choose,$mtitles$t_
<input type="submit" value="Continuer">

</form>
