<p><hr width=35%>

!read Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=8
!if $qcnt>$exocnt
 !set qcnt=$exocnt
!endif
!if $exocnt<1
 Spiacente, questo modulo non contiene ancora esercizi. 
 Riprova pi&ugrave; tardi!
 !exit
!endif
!if $exocnt=1
 Questo modulo al momento contiene un solo esercizio, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Provalo.
 !exit
!endif

!form new
<input type=hidden name=module value=$module>
<center><table border=0><tr>
<td align=center>Scegli l'esercizio:<td>
!if $exocnt>6
 !set selsize=6
!else
 !set selsize=$exocnt
!endif
!set wims_formselect_switch=multiple size=$selsize
!set exo=$special_parm
!if $exo!=$empty
 !set exolist=!listuniq $exo,$exolist
 !set exolist=!replace , by , $ in $exolist
 !set dictionary=$module_dir/Extitles
 !set translator_unknown=leave
 !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
<tr><td align=center>Una sessione contiene<td>
!set qnum=1
!formselect qnum from 1 to $qcnt
esercizi.
<tr><td align=center>Livello di difficolt&agrave;<td>
!set qcmlevel=3
!formselect qcmlevel from 1 to 8
!read introhook.phtml
</table> <p>
<input type=submit value="Al lavoro">
</center>
</form>
<b>Nota</b>. Gli esercizi verranno scelti casualmente tra quelli selezionati
nella lista. Se non si &egrave; selezionato alcun esercizio, la
scelta varier&agrave; tra tutti gli esercizi disponibili.
!if * isin $titlelist
 <p>Gli esercizi contrassegnati da * sono in generale un po' pi&ugrave;
 difficili degli altri.
!endif

