!! This file can contain contents which go to the end of the page.

!if $wims_exec_error!=$empty
<small><pre>*******************************************************
$wims_exec_error
*******************************************************</pre></small>
!reset wims_exec_error
!endif

<p><center>
!href cmd=resume&realtest=no Torna alla pagina di creazione dell'esercizio
.
!if $mode=model
&nbsp;
 !href cmd=reply&level=1&mode=model Elenco dei modelli
.
!endif
</center> <p>
