
!if $realtest=yes
 !changeto oef/help.phtml
!endif

!set helplist=oef,examples,format,parameters,oefparm,reply,embedans,\
	feedback,math,draw,draw_example,oefadv,if,symtext,model,slib

!set s_=!item 1 of $special_parm
!if $s_=all
 !for sj in $helplist
  <p>
  !read help/$sj.phtml
 !next sj
 !exit
!endif
!if $s_!=$empty and $s_ isitemof $helplist
 !read help/$s_.phtml
!! <p><center>
!! !href cmd=help Help on line su altri argomenti
!! &nbsp;&nbsp;
!! !href cmd=resume Torna al lavoro.
!! </center>
 !set wims_menu_tail=!append line back2,1,cmd=help\
 to $wims_menu_tail
 !exit
!endif

Help: indice argomenti disponibili:<ul>
<li><p>
!href cmd=help&special_parm=oef Documentazione del formato OEF.
!!</p></li><li><p>
!!href cmd=help&special_parm=examples Esempi di esercizi.
</p></li><li><p>
!href cmd=help&special_parm=format Formato degli enunciati
 degli esercizi.
</p></li><li><p>
!href cmd=help&special_parm=parameters Parametri `random'
 in un esercizio interattivo
</p></li><li><p>
!href cmd=help&special_parm=math Formule matematiche
 inseribili negli esercizi.
</p></li><li><p>Inclusione di 
!href cmd=help&special_parm=draw disegni dinamici
 negli esercizi.
</p></li><li><p>Tipi di 
!href cmd=help&special_parm=reply risposta
.
</p></li><li><p>
!href cmd=help&special_parm=feedback Commenti
 alle risposte.
</p></li><li><p>
!href cmd=help&special_parm=oefadv Funzioni avanzate
.
</p></li><li><p>
!href cmd=help&special_parm=slib&slib_cmd=help Library of scripts
 (slib).
</p></li><li><p>
!href cmd=help&special_parm=all Tutti gli argomenti
</p></li></ul>

!!!if $modtoolhelp!=yes
!!<center>
!!!href cmd=resume Torna al lavoro.
!!</center>
!!!endif
