Benvenuto/a in questa pagina che permette la creazione di 
!if $wims_user!=supervisor
 esercizi interattivi,
!else
 esercizi interattivi per il corso <font color=blue>
 $wims_classname</font> presso <font color=blue>$wims_institutionname</font>,
!endif
in modo guidato. Sono disponibili
!href cmd=reply&mode=model modelli già pronti
.
Se siete esperti e avete gi&agrave; preparato un file
con il codice sorgente degli esercizi, &egrave; possibile passare al 
!href cmd=reply&rawinp=yes modo `esperti'
 oppure al
!href cmd=reply&mode=file modo `file'
. I non esperti possono anche cominciare da 
!href cmd=help&special_parm=examples esempi gi&agrave; pronti
.

!form reply
<input type=hidden name=level value=2>
Dare un titolo all'esercizio:<br>
<input size=40 maxlength=40 name=oef_title value="$oef_title"> <p>
Enunciato del problema:
!formselect oef_format list tex,html
 [
 !href target=wims_mhelp cmd=help&special_parm=format help on line
 ]<p>
L'esercizio chieder&agrave;
!formselect oef_answercnt from 0 to 10
risposte libere e 
!formselect oef_choicecnt from 0 to 10
risposte a scelta multipla.
Risposte numeriche non calcolate (tipo <tt>3*5-sin(pi/3)</tt>)
!formselect oef_computeanswer list yes,no prompt saranno, non saranno
accettate.
!formselect oef_condcnt from 0 to $condlim
condizioni speciali saranno utilizzate per verificare risposte libere
(numeriche).
 [
 !href target=wims_mhelp cmd=help&special_parm=reply help on line
 ]
<p><table border=0><tr><td align=right>
Nome dell'autore:<td><input size=30 maxlength=60 name=oef_author value="$oef_author">
<tr><td align=right>
Indirizzo e-mail:<td><input size=30 maxlength=80 name=oef_email value="$oef_email">
</table>
<p><center>
<input type=submit value="Continua">
</center>
</form>
!set wims_menu_items=!append line modtool,1,module=adm/modtool\
model,1,cmd=reply&mode=model\
 to $wims_menu_items
 
&Egrave; anche disponibile 
!href module=adm/modtool Modtool
 (in inglese) per la creazione di moduli WIMS completi.

!if $wims_user=supervisor
 !read wimshome/log/classes/$wims_class/Exindex
 !if $exototal>0
  <p>
  !form new
  <input type=hidden name=module value="$module">
  Modifica un esercizio del corso già esistente:
  !formselect existing list $exolist prompt $titlelist
  <input type=submit value=OK></form>
 !endif
!endif

