Benvenuto/a in questa pagina che permette la creazione di 
!if $wims_user!=supervisor
 esercizi interattivi,
!else
 esercizi interattivi per il corso <font color=blue>
 $wims_classname</font> presso <font color=blue>$wims_institutionname</font>,
!endif
in modo guidato. Sono disponibili
!href cmd=reply&mode=model modelli già pronti
.
Se siete esperti e avete gi&agrave; preparato un file
con il codice sorgente degli esercizi, &egrave; possibile passare al 
!href cmd=reply&rawinp=yes modo `esperti'
 oppure al
!href cmd=reply&mode=file modo `file'
. I non esperti possono anche cominciare da 
!href cmd=help&special_parm=examples esempi gi&agrave; pronti
.
 
!!!!!!!!!!!!! début de modifs JY pour le module confia2qcm !!!!!!!!!!!!!

 <table bgcolor="#d0c080">
  <tr>
    <td rowspan=4>
      Sono disponibili<br>anche
    </td>
   <td bgcolor=lemonchiffon>
      !href module=adm/modtool Modtool
        per la creazione di moduli WIMS completi.
    </td>
  </tr>
  <tr>
    <td bgcolor=lemonchiffon>
      !href module=adm/auth/confia2qcm <code style="background-color:azure">Confia2qcm</code>
       ou 
       !href module=adm/auth/createqcm <code style="background-color:azure">Createqcm</code>
        per creare semplici domande a scelta multipla.
    </td>
  </tr>
  <tr>
  <td bgcolor=lemonchiffon>
      !href module=adm/quicktool Quicktool
       per creare esercizi di lingua.
    </td>
    <tr>
    <td bgcolor=lemonchiffon>
      !href module=adm/latex2wims Latex2wims
       per creare documenti a partire da testi in LaTeX.
    </td>
    </tr>
</table>
!!!!!!!!!!!!! fin de modifs JY pour le module confia2qcm !!!!!!!!!!!!!
