!set sizex=65
!set types=!sort nocase lines \
auto,			default\
espressione algebrica,	algexp\
testo approssimativo,	atext\
testo (non dist. M/m),	nocase\
testo (dist. M/m),	case\
raw text,		raw\
characterset di caratteri, 		chset\
equazione,		equation\
insieme (finito),	set\
espressione formale,	formal\
espressione letterale,	litexp\
matrice,		matrix\
numero,			numeric\
numero in un intervallo,	range\
numero con unità di misura,	units\
funzione numerica,	function\
vettore,		vector\
parola in una lista,	wlist

!set types=!nonempty lines $types
!set typelist=!column 2 of $types
!set typenames=!column 1 of $types

Inserire ora il contenuto dell'esercizio
<font color=red><b>$oef_title</b></font>.
!href cmd=reply&level=1 Ricomincia da capo
. <p>

!form reply
<input type=hidden name=level value=3>
Parametri dell'esercizio. Si possono utilizzare parametri 
`random' [
!href target=wims_mhelp cmd=help&special_parm=parameters documentazione
]<br>
!set o_parms=!reinput $oef_parms
<textarea wrap="off" rows=6 cols=$sizex name=oef_parms>$o_parms</textarea>
<p>
Enunciato dell'esercizio (in formato $oef_format): [
!href target=wims_mhelp cmd=help&special_parm=format documentazione
 ]<br>
!set o_statement=!reinput $oef_statement
<textarea wrap="off" rows=6 cols=$sizex name=oef_statement>$o_statement</textarea>
<p>
!if $oef_answercnt>0
 <table border=1>
 <caption>Risposte libere
 <tr><th>Nome<th>Soluzione esatta<th>Tipo <small>
 !href target=wims_mhelp cmd=help&special_parm=reply#freestyle [documentazione]
 !for i=1 to $oef_answercnt
  !default anstype$i=default
  !set p_=!reinput $(ansprompt$i)
  <tr><td> <input size=$[$promptlim-3] maxlength=$promptlim name=ansprompt$i value="$p_">
  !set p_=!reinput $(ansgood$i)
  <td> <input size=30 name=ansgood$i value="$p_">
  <td><small>
  !formselect anstype$i list $typelist prompt $typenames
 !next i
 </table> <p>
 Precisione richiesta nelle risposte numeriche:
 !formselect oef_precision list 100,1000,10000,100000,1000000 prompt 1/100,1/1000,1/10 000,1/100 000,1/1 000 000
 <br>Le funzioni (numeriche) saranno valutate nell'intervallo
 (&nbsp;<input size=6 name=oef_rangel value="$oef_rangel">,<input size=6 name=oef_ranger value="$oef_ranger">&nbsp;).
 <p>
!endif

!if $oef_condcnt>0
 <table border=1>
 <caption>Condizioni di analisi delle risposte (numeriche)
 <tr><th>Nome della condizione<th>Definizione della condizione
 !for i=1 to $oef_condcnt
  !set p_=!reinput $(Condname$i)
  <tr><td><input size=$promptlim maxlength=$promptlim name=Condname$i value="$p_">
  !set p_=!reinput $(Condtest$i)
  <td> <input size=40 name=Condtest$i value="$p_">
 !next i
 </table> <p>
!endif

!if $oef_choicecnt>0
 <table border=1>
 <caption>Scelte multiple
 <tr><th>Nome<th>Risposta esatta<th>Risposte errate
 !for i=1 to $oef_choicecnt
  !set p_=!reinput $(choiprompt$i)
  <tr><td> <input size=$promptlim maxlength=$promptlim name=choiprompt$i value="$p_">
  !set p_=!reinput $(choigood$i)
  <td> <input size=10 name=choigood$i value="$p_">
  !set p_=!reinput $(choibad$i)
  <td> <input size=30 name=choibad$i value="$p_">
 !next i
 </table> <p>
!endif

<p><center>
<input type=submit value="Salva">
</center> <p>
&Egrave; possibile dare un suggerimento o inserire la soluzione:
<table border=0>
<tr><td>Suggerimento<br>(formato html)
!set pp=!reinput $oef_hint
<td><textarea wrap="off" rows=3 cols=$[$sizex-10] name=oef_hint>$pp</textarea>
<tr><td>Soluzione<br>(formato html)
!set pp=!reinput $oef_solution
<td><textarea wrap="off" rows=3 cols=$[$sizex-10] name=oef_solution>$pp</textarea>
</table>
</form>

