
L'esercizio &egrave; stato salvato con successo dal server. Ringraziamo
vivamente per il contributo, in nome di tutti quelli che 
lo potranno cos&igrave; utilizzare.
<p>
L'amministratore del server verificher&agrave; l'esercizio e decider&agrave;
se inserirlo e in quale categoria.
Questo potr&agrave; richiedere qualche giorno.
<p><center>
!href module=incoming Modulo temporaneo contenente l'esercizio.
<p>
!href cmd=reply&level=$[$level-1] Torna al passaggio precedente.
</center>


