
!set name_first=Esercizi di base
!set name_datalist=Esercizi con liste di dati

!readproc model/makelist.proc

Questi sono i modelli di esercizi disponibili. &Egrave; possibile selezionarne
uno oppure 
!href cmd=reply&level=1 tornare
 alla pagina iniziale.

<p>

!for t in $types
 !default name_$t=$t
 $table_header
 <caption>$(name_$t)</caption>
 $table_hdtr
 <th>Tipo</th>
 <th>Azione</th>
 <th>Descrizione</th>
 </tr>
 !for f in $(type_$t)
  !set r=!record 1 of model/src/$f.oef
  !set r=!line 1 of $r
  $table_tr
  <td>$(tit_$f)</td>
  <td nowrap>
  !href cmd=resume&level=3&mode=model&model=$f&realtest=yes Demo
&nbsp;
  !href cmd=reply&level=2&mode=model&model=$f Modifica
  </td>
  <td><small>$(desc_$f)
  !href target=wims_mhelp cmd=help&special_parm=model,1,$f &gt;&gt;
  </small></td>
  </tr>
 !next f
 $table_end
 <p>
!next t

<b>Nota</b>. Questi modelli sono stati preparati per permettere una facile
creazione di nuovi esercizi. Si tratta però di esercizi estremamente 
semplificati e standardizzati e non sono pienamente mostrate le potenzialità 
del linguaggio OEF. Naturalmente è sempre possibile passare al modo esperti 
e aggiungere le funzionalità via via necessarie.

!reset mode

