
!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
 Questo &egrave; il modo `esperti' per la creazione di un esercizio.
 !if $modeltest=yes
  Dal momento che questo esercizio è costruito seguendo un modello standard, 
  si consiglia 
  !href cmd=reply&mode=model&level=2 il modo guidato
.
  !href cmd=reply&mode=none&level=1 Annulla
.
 !else
  Per utilizzarlo occorre avere gi&agrave; a disposizione 
  il file con il codice sorgente dell'esercizio. Per la
  prima creazione di un esercizio &egrave; possibile utilizzare
  !href cmd=reply&mode=normal&level=1 il modo guidato
  .
  <p>
  Inserire il codice sorgente (
  !href target=wims_mhelp cmd=help&special_parm=oef in formato OEF
  ) del vostro esercizio:
  (per inserire il contenuto di un file gi&agrave; esistente, fare un 
  copia&amp;incolla da un editor di testo).
  !href target=wims_test module=tool/directexec&cmd=new Verifica il codice
 !endif
!else
 Questo &egrave; il codice sorgente di 
 !if $catmodule=$empty
  un esercizio gi&agrave; esistente.
  &Egrave; possibile modificarlo nella finestra sottostante.
 !else
  un esercizio <em>pubblico</em> del sito, importabile nel corso.
  &Egrave; possibile modificarlo nella finestra sottostante, prima di inserirlo
  tra gli esercizi privati del corso.
 !endif
 !if $modeltest=yes
  Dal momento che questo esercizio è costruito seguendo un modello standard, 
  si consiglia 
  !href cmd=reply&mode=model&level=2 il modo guidato
.
  !href cmd=reply&mode=none&level=1 Annulla
.
 !endif
!endif

<a name=textarea>
<a href=#
onclick=document.forms["replyform"].wims_deposit.value="">[Annulla]</a>.
!href cmd=resume [Ricomincia]
.

<p><center>
!mexec textarea.sh
<p><input type=submit value="Salva"></center>
</form>

