<html><head>
$wims_html_header
</head><body $wims_htmlbody>
!headmenu

!if $sheet_docpage!=$empty
 !changeto docpage.phtml
!endif
<center><h3>$wims_classname, $wims_institutionname</h3>
<hr> <p><h1>Delovni list #$sh<br>$sheet_title</h1></center> <p>
<div class="wims_sheet_desc">$sheet_desc </div><p>

!if $sheet_expiration!=$empty and $sheet_active=1
 !set expday=!char 7,8 of $sheet_expiration
 !set expmon=!char 5,6 of $sheet_expiration
 !set expyear=!char 1 to 4 of $sheet_expiration
 !set months=januar,februar,marec,april,maj,junij,julij,avgust,september,oktober,november,december
 !set expmon=!item $expmon of $months
 Datum zakljuèka lista: $expday. $expmon $expyear.
!endif
<p>
!if $sheet_active=2
 <blink><b><font color=red>Opozorilo</font></b></blink>
 Ta delovni list je ¾e zakljuèen. Naloge na njem lahko ¹e vedno re¹ujete, toda na novo dose¾eni rezultati ne bodo veè upo¹tevani.
 <p>
!endif

!if $n=0
 !if $sheet_active=$empty
  Urejanje vsebine delovnega lista je dovoljeno le skrbniku.
 !else
  Ta delovni list je prazen. Morda gre za napako skrbnika.
 !endif
!else
 Predpisane naloge: (Bele¾enje rezultatov je
 !set scorestat=!getscorestatus sheet=$sh
 !if $scorestat=yes
  !if $wims_scorereg!=suspend
   vkljuèeno, toda lahko ga
   !href cmd=resume&job=suspend izkljuèite
.)
  !else
   !set scorestat=no
   izkljuèeno na va¹o zahtevo.
   !href cmd=resume&job=reopen Ponoven vklop
.)
  !endif
 !else
  zaprto za va¹o povezavo.)
 !endif
 <p><ul>
 !for i=1 to $n
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sh
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  !set dep=!row $i of $deps
  !set dep=!trim $dep
  <p><li>$i.
  !if $dep=$empty or $scorestat!=yes
   !href module=$di&cmd=new&worksheet=$sh&$pa $ti
, $de
   !if $require>0
    <small>$[$got] toèk (zahtevanih $[$require]), kvaliteta
    $[$mean]/10.</small>
   !endif
  !else
   <font color=red><b>$ti</b></font>, $de 
   !if $require>0 toèk
    <small>($[$require] zahtevanih.)</small>
   !endif
  !endif
  !if $dep!=$empty
   <small>Predno se lotite te vaje, morate izbolj¹ati
   !if , isin $dep
    va¹e rezultate pri vajah $dep.
   !else
    va¹ rezultat pri vaji $dep.
   !endif
   </small>
  !endif
 !next i
 </ul>
!endif

:contentend
!if $wims_user=supervisor
<p>
!href module=adm/class/sheet&sheet=$sh Urejanje lista
 (za skrbnika).&nbsp;
!endif
!href cmd=reply&job=print Razlièica za tiskanje
.
!if $exolog!=$empty
 !href module=adm/class/exolog&job=llist&logsheet=$sh Bele¾enje podrobnosti naloge
.
!endif
<p>

!tail

