
!readproc adm/docsheet.prep
!read $docdef content
<p><center>
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   $name_scoreopen
   !href cmd=resume&job=suspend $wims_name_scoreclose2
.
  !else
  $name_scoresuspend
   !href cmd=resume&job=reopen $wims_name_scorereopen
.
  !endif
 !else
 $name_scoreclose
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc&job=edit&doc=$d_&block=$b_ $wims_name_Edit
.&nbsp;
 !href cmd=resume $wims_name_refresh
.
!endif
</center>

!tail

