!if $job=print
 !changeto print.phtml
!endif

!if $public!=P
 !changeto class.phtml
!endif

!header

!if $error!=$empty
 !read msg.phtml
 !tail
 !exit
!endif

!if $wims_user=supervisor and $job=raw
 Tukaj je izvorna koda va¹ega delovnega lista. Lahko si jo skopirate in uporabite kje drugje.
 <p><hr><pre>
 !sh awk 'BEGIN {a=0};\
	/^:/ {a=1};\
	a==1 {print}' bases/sheet/$sh.def
 </pre><hr>
 <p>
 !href cmd=resume&job=read Nazaj na obièajen pogled.
 !tail
 !exit
!endif

<h3 class="wims_sheet_title">$sheet_title</h3>
<div class="wims_sheet_desc">$sheet_desc</div> <p>

$sheet_remark
<p>

!if $n=0
 Ta delovni list je prazen. Verjetno gre za napako.
!else
 Predpisane naloge:
 <p><ul>
 !for i=1 to $n
  !set ex=!record $i of $data
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  <p><li>$i. 
  !href module=$di&cmd=new&worksheet=$public$shn&$pa $ti
, $de
!!  !if $require>0
!!   <small>$[$got] toèk (zahtevanih $[$require]), kvaliteta
!!   $[$mean]/10.</small>
!!  !endif
 !next i
 </ul>
 !if $wims_user=supervisor
  !href cmd=resly&job=import Uvozi
  ta delovni list v svojo uèilnico, ali
  !href cmd=reply&job=raw poka¾i izvorno kodo.
  <p>
 !endif
!endif
!href cmd=reply&job=print Razlièica za tiskanje
.

!tail

