!!@# translate between !!@#  and !!#@

<div $frame>

!goto $special_parm1

:etape
$hh  maximaal aantal stappen </h2>
!!@#
Als er twee stappen zijn ingesteld, wordt de tweede vraag pas getoond als het eerste antwoord correct is.
Het aantal vragen kan hierboven worden ingesteld.

!!#@
!goto end

:format_click
$hh $name_format</h2>
<ul><li> <dl $tt>case</dl>
!!@#
voer uw tekst hier in

!!#@
</li>
<li><dl $tt>clickfill</dl>
!!@#
een versleepbaar label (elke label kan meerdere keren worden gebuikt)

!!#@
</li>
<li><dl $tt>dragfill</dl>
!!@#
een versleepbaar label (elke label kan aan &eacute;&eacute;n keer worden gebuikt)

!!#@ 
</li>
<li><dl $tt>mark</dl>
!!@#
identificeer het woord (de woorden) door erop te klikken.

!!#@
</li>
<li><dl $tt>menu</dl>
!!@#
drop down menu
!!#@
</li>
</ul>
!goto end

:format_radio
$hh $name_format</h2>
<ul><li> <dl $tt>radio</dl>
!!@#
type antwoord (tik 1 box aan per vraag)
!!#@
</li>
<li><dl $tt>checkbox</dl>
!!@#
type antwoord (tik 1 of meer boxen aan per vraag)
!!#@
!!#@
</li>
</ul>
!goto end

:menu_commun 
$hh Algemeen menu</h2>
<ul><li>
!!@#
Als je <tt>ja</tt> aanvinkt , worden alle woorden tussen ??  ?? opgenomen in de verzamellijst.

!!#@
</li>
<li>
!!@#
Als je  <tt>nee</tt> aanvinkt , moeten er meerdere woorden tussen ?? ?? staan. 
!!#@
</li>
</ul>
!goto end

:data
$hh 
!!@#
Aantal data sets
!!#@
</h2>
!!@#
Het aantal data sets komt overeen met het aantal vragen per stap.
(dus het aantal vragen dat gelijktijdig wordt getoond per stap.)
!!#@

!goto end

:file
$hh  </h2>
!!@#
Het boncode bestand bevat de progamma code.
Dit bestand word automatisch door Quicktool gegenereerd aan de hand  van uw informatie.
Er kan niet zonder deze broncode worden gewerkt.
!!#@
!goto end

:choice
$hh </h2>
!!@#
In het TRUEFALSE type oefening kan men vrij de woorden kiezen voor het antwoord,
bijvoorbeeld <tt>waar, onwaar</tt> or <tt>ja, nee</tt> etc ...
Deze woorden kunnen worden geplaatst aan het begin van het data bestand, of in deze Quicktool interface
(deze heeft de prioriteit).
Let op: deze woorden moeten uiteraard letterlijk overeenkomen met de woorden in de data bestand.
!!#@
!goto end


:choice2
$hh   </h2>
!!@#
Deze lijst woorden is gelijk voor elke blanco veld.
De lijst kan ook worden gedeclareerd in de variabele  <tt>choice=</tt> aan het begin van het data bestand.
De <tt>choice=</tt> variabele kan nuttig zijn bij introduceren van "verstorende woorden" in uw oefening.
!!#@
!goto end

:partialscore
!!@#
Als <tt>ja</tt> wordt aangevinkt, mag de student overstappen naar de volgende vraag (of stap in de oefening) ondanks dat 
alle antwoorden niet volledig correct zijn beantwoord.
Als <tt>nee</tt> wordt aangevinkt, moeten alle woorden correct worden geplaatst voordat de volgende stap van de oefening wordt aangeboden.
!!#@
!goto end

:first_step
$hh Eerste stap</h2>
!!@#
In de eerste stap is meestal het selecteren van een woord (of woorden).
Er kan worden gekozen deze stap niet op te nemen : vink dan <tt>nee</tt> aan.
!!#@
!goto end

:second_step
$hh 
!!@#
Aanvullende vraag
!!#@
</h2>
!!@#
De student een aanvullende vraag worden aangeboden. In dat geval kan er 
<ul>
<li>een specifieke instructie voor deze aanvullende vraag worden gegeven;</li>
<li>voeg een tweede vraag toe in of na de tekst;</li>
<li>kiet het type (formaay) van de aanvullende vraag.</li>
</ul>
!!#@
!goto end

:answer_given
$hh  De antwoorden</h2>
!!@#
Er kan voor worden gekozen de correcte antwoorden te tonen na he be&iuml;ndigen van de oefening.
!!#@
!goto end

:raw
!!@#
Als de optie <tt> tekst in het originele formaat</tt> wordt aangevinkt , de regels eindes (de nieuw regels)
 worden op de zelfde manier getoond als in de door u aangeleverde tekst.
<p>
Als de optie
 <tt>de tekst wordt aangepast aan de venster grootte</tt> wordt aangevinkt ,
 zal de tekst worden aangepast aan de grootte van het browservenster.
 Er kan echter ook html code worden toegevoegd om het begin van een paragraaf aan te geven : <tt>&lt;p&gt;</tt> 
!!#@
!goto end

:taille_corr
$hh    </h2>
V x HG x HD:
!!@#
V (V=vertical) geeft de hoogte van een label, HG en HD geef de linker en rechter kolom (H=horizontal) 
!!#@
!goto end

:taille_compose
$hh    </h2>
!!@#
de hoogte van de blanke velden , waar de woorden moeten worden ingevuld, is standaard afgesteld op 10.
Bij een enkele regel geef 5.
Als deze variabele kleiner is dan 5 , wordt de tekst gecentreerd.
!!#@
!goto end

:taille_case
$hh    </h2>
!!@#
het aantal karakters in het blanke veld.
!!#@
!goto end

:taille_drag
$hh    </h2>
V x H 
!!@#
V is de hoogte wn H is de lengte van de labels 
!!#@
!goto end

:alea
$hh  
!!@#
In willekeurige volgorde
!!#@
</h2>
!!@#
<p> Als <tt>ja</tt> wordt aangevinkt , worden de vragen (of items) in de oefening in willekeurige volgorde getoond.
</p>
<p>Als <tt>nee</tt> wordt aangevinkt , worden de vragen (of items) in de oefening in dezelfde volgorde als in het data bestand getoond/ 
 the questions (or items) in the exercise will appear 
In dat geval moet 
<tt>all</tt> worden aangevinkt voor de parameter  <tt> aantal data sets gebuikt voor een vraag </tt>.
De oefening is dus niet random en kan op den duur voor de student te herkenbaar worden.
!!#@
!goto end

!goto end
:specialhelp
$hh 
!!@#
Special helps
!!#@
</h2>
!!@#
Helps can be provided for each word when the exercise type (format) is <tt>case</tt>. 
The learner can see the helps provided by hovering over the prompt with the mouse (by default the prompt is ++>). 
Three types of help can be provided: the number of letters in each word shown with dashes or three 
letters which are taken randomly from the word (or two letters if the word  has fewer than five letters) 
and an audio recording of the item.
La troisième aide est faite à partir des aides entrées dans le fichier de données 
(voir format du fichier de données). 
<p>
These helps can be chosen for the first four trials;If you do not tick anything, no help is given.
!!#@

!goto end

:percent
$hh  Pourcentage de réussite</h2>
!!@#
If there are at least two steps in an exercise you can decide what minimum success rate you
expect the learner to reach before he/she can move onto the next step. If you select 100% 
the questions in the following step(s) will only be displayed if the learner has provided 
all the answers correctly (100% success). If you select 0% the exercise will continue until
it comes to its end regardless of the correctness of the answers given.
!!#@
!goto end

:supplement
$hh  Réponses</h2>
!!@#
Les réponses peuvent être mises soit à l'intérieur du texte soit après le texte.
!!#@
!goto end


:try
$hh    </h2>
!!@#
Enter the number of trials you allow for the exercise. The score given will depend 
on how many trials were needed to find the correct answers.
!!#@
!goto end

:instruction
$hh  Consigne</h2>

!!@#
Write the instruction of the exercise here. This will be displayed at the beginning of 
the exercise. You can use html codes. If you wish to add hyperlinks to websites, 
it is best to have the linked pages open in a new window - for this you have to 
write the following code 
<br>
<pre>
&lt;a target=wims_external href="http://adresse ..... "&gt;lien&lt;/a&gt;
</pre>
Remember that webpages can sometimes disappear form the Internet.
!!#@
!goto end

:reading
$hh    </h2>
!!@#
If you tick <tt>yes</tt>, you have to write the name of the file that you will 
upload later into your module. The text included in this file will be displayed in a pop up 
window when the learner clicks on the word(s) you have specified (instead of 
[text to read]).
!!@#
!goto end

:audio
$hh    </h2>
!!@#
If you tick  <tt>yes</tt>, you must add the name of an audio file that you will upload to 
your module. Remember to write the full name of the file together with the extension <tt>.mp3</tt>.
!!#@

!goto end


:video
$hh    </h2>

!!@#
If you tick  <tt>yes</tt>, you must add the name of a video file that you will 
upload to the module (unless it is too heavy) or a valid URL address whose format will be <tt>http://xxx </tt>. 
The video will open when the learner clicks on the word you have indicated between square brackets 
(for example [video] or [watch the advertisement]...).

!!#@
!goto end

:image
$hh    </h2>

!!@#
If you tick  <tt>yes</tt>, you must add the name of a picture file that you will 
upload to your module. Remember to write the full name of the file together with 
the extension (for example <tt>.jpg</tt>.  The picture will be displayed when the learner clicks 
on the word you have indicated between square brackets (for example[picture]...). 

If you want the link to the picture to be part of  the instructions tick <tt>no</tt> 
and write the following code where you want the link to be 
<tt> &lt;img src=\imagedir/nom_image&gt></tt>
Give the full name of the file together with the extension.
!!#@

!goto end

:sens
$hh Sens dans $wims_name_quick_QUIFAITQUOI   </h2>
!!@#
You can ask the learner to identify WHO carries out the actions (or WHO says something) 
or WHAT actions  a "character" carries out. The exercise can be configured to choose question type  "WHO does what" or the "WHAT is done by who" randomly.
!!#@
!goto end

:aucune
$hh Word in $wims_name_quick_QUIFAITQUOI   </h2>
!!@#
In your exercise the last question will always be "none of the above". 
This sentence can be changed to something you prefer and to the language you prefer it to be in (for example "aucune de ces  possibilités" in French).
!!#@

!goto end
:nopaste
$hh    </h2>
!!@#
If you tick <tt>yes</tt> the learner will be able to copy and paste the answers. 
If you tick <tt>no</tt>, the learner will have to type the answers in the blanks himself.
!!#@
!goto end

:css
$hh    </h2>
!!@#
The css style of the questions and answers can be specified here.
You can for example change the colour.
!!#@
!goto end


:css1
$hh    </h2>
!!@#
If you use css styles in the "instruction" part you can add them here. 
The default is listing style with capital letters.
!!#@

!goto end


:prompts

$hh    </h2>
!!@#
You can add "prompts" or remarks here that you wish to be displayed 
if the learner provides a correct answer, a wrong answer or an incomplete answer.
!!#@
!goto end

:player
$hh    </h2>
!!@#
Choose a flash audio player from the list.
!!#@
!goto end
:swac
$hh    </h2>

!!@#
If you wish to use words included in the swac audio collection 
(<a target="wims_external" href="http://shtooka.net">http://shtooka.net</a>),
you have to tick the language you are going to use. This function cannot yet be 
used with all the different types of exercises (however, in certain exercise types check the "preferences" 
section to see how words from the audio collection can be included by adding <tt>audio="word"</tt> 
at the beginning of the data set. If the word is to be included from the swac audio collection, 
the extension <tt>.mp3</tt>should not be specified.)

!!#@
!goto end
</div>


!!language independant

:data_fileCORRESP
$hh  $wims_name_quick_CORRESP</h2>
$gen_data
<p>
!set b = !record 1 of lang/help.$modu_lang/CORRESP
!set a = !record 2 to -1 of lang/help.$modu_lang/CORRESP
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileCOMPOSE
$hh2 $wims_name_quick_COMPOSE</h2>
$gen_data
<p>
!set b = !record 1 of lang/help.$modu_lang/COMPOSE
!set a=!record 2 to -1 of  lang/help.$modu_lang/COMPOSE
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileGAP
$hh  $wims_name_quick_GAP</h2>
$gen_data
<p>
!set b = !record 1 of lang/help.$modu_lang/GAP
!set a = !record 2 to -1 of lang/help.$modu_lang/GAP
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileORDONNE
$hh  $wims_name_quick_ORDONNE</h2>
$gen_data

!set b = !record 1 of lang/help.$modu_lang/ORDONNE
!set a = !record 2 to -1 of lang/help.$modu_lang/ORDONNE
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileQCM
$hh  $wims_name_quick_QCM</h2>
$gen_data

!set b = !record 1 of lang/help.$modu_lang/QCM
!set a = !record 2 to -1 of lang/help.$modu_lang/QCM
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileSELECTWORD


$hh  $wims_name_quick_SELECTWORD</h2>
$gen_data
!set b = !record 1 of lang/help.$modu_lang/SELECTWORD
!set a = !record 2 to -1 of lang/help.$modu_lang/SELECTWORD
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileSELECTWORDA

$hh  $wims_name_quick_SELECTWORDA</h2>
$gen_data

!set b = !record 1 of lang/help.$modu_lang/SELECTWORDA
!set a = !record 2 to -1 of lang/help.$modu_lang/SELECTWORDA
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileSELECTWORDB
$hh  $wims_name_quick_SELECTWORDB</h2>
$gen_data
!set b = !record 1 of lang/help.$modu_lang/SELECTWORDB
!set a = !record 2 to -1 of lang/help.$modu_lang/SELECTWORDB
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileQUIFAITQUOI
$hh $wims_name_quick_QUIFAITQUOI</h2>
$gen_data
!set b = !record 1 of lang/help.$modu_lang/QUIFAITQUOI
!set a = !record 2 to -1 of lang/help.$modu_lang/QUIFAITQUOI
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileTONIC
$hh $wims_name_quick_TONIC</h2>
$gen_data
!set b = !record 1 of lang/help.$modu_lang/TONIC
!set a = !record 2 to -1 of lang/help.$modu_lang/TONIC
!set b= !line 2 to -1 of $b
<pre  $pre>
$b
!replace internal : by &#58; in :$a
</pre>
!goto end

:data_fileTRUEFALSE
$hh $wims_name_quick_TRUEFALSE</h2>
$gen_data
!set b = !record 1 of lang/help.$modu_lang/TRUEFALSE
!set a = !record 2 to -1 of lang/help.$modu_lang/TRUEFALSE
!set b= !line 2 to -1 of $b
<pre  $pre>
$b

!replace internal : by &#58; in :$a
</pre>
!goto end

:end