!set name_institution=nom de l'établissement
!set name_description=nom de la classe
!set name_supervisor=nom de l'enseignant
!set name_email=adresse électronique
!set name_password=mot de passe de la classe
!set name_passsup=mot de passe d'enseignant
!set levelid=E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,H7,U1,U2,U3,U4,U5,G,R
!set leveldesc=Maternelle,CP,CE1,CE2,CM1,CM2,Sixième,Cinquième,Quatrième,Troisième,Seconde,Première,Terminale,Licence 1,Licence 2,Licence 3,Master 1,Master 2,Doctorat,Recherche
!set nblevel=!itemcnt $levelid

!set classname=<b><font color=green>$description</font></b>\
 de <b><font color=green>$institution</font></b>

!set months=janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=groupement de classes
    !set name_sup=de l'enseignant-administrateur
   !else
    !set name_classe=portail d'établissement
    !set name_sup=de l'administrateur
   !endif
   !set name_classes= le $name_classe
   !set name_classess= un $name_classe
   !set name_classesss= du $name_classe
   !set name_classessss= Le $name_classe
!else
   !set name_classe=classe
   !set name_classes=la $name_classe
   !set name_classess=une $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=de l'enseignant
!endif

!distribute lines Continuer\
  Recommencer l'opération.\
  Création d'une structure : classe, groupement, établissement\
  Nom de l'établissement\
au plus\
au moins\
  Réservé aux experts\
  caractères\
  Revenir au début de l'opération.\
  Choisissez le type de structure que vous voulez créer.\
 into name_continue,name_again,title,name_Name_portal,name_atmost,name_atleast,name_expert,\
   name_characters,name_comeback,name_choose
   
!if $regpolicy=file
  !set noright=Vous n'avez pas les droits pour cela.
 !else
  !set noright=Seul le gestionnaire du site peut le faire.
 !endif