!form reply
Vous allez ajouter une fois chaque s&eacute;rie d'exercices de la feuille 
!formselect numsheet list $asheets prompt $listname
à la suite des exercices déjà présents.<br>
Chaque exercice aura comme poids 1 et conservera le titre qu'il avait dans la feuille d'exercices si vous ne remplissez pas le champ de saisi ci-dessous.<p>
Titre d'exercice générique <input type=text name=keytitle> (les exercices seront num&eacute;rot&eacute;s).
<center><input type=submit value="Insérer"></center>
<input type=hidden name="job" value="cpsheet">
</form>
<p>
!href cmd=reply Page principale de l'examen
.
!reset numsheet
