!read names.phtml
!read js/examclock1.phtml
!read adm/css.phtml
!header1

!if $job iswordof student score scorereg
 !changeto $job.phtml
!endif

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$name_title $exam

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_back
. <p>
 !goto end
!endif

!if $job=exo or $job=cpsheet
 !read $job.phtml
 !goto end
!endif

!if $activetest>0
 !form reply
 <input type=hidden name=job value=text>
 Ta izpit je
 !if $activetest=1
  active.
  !href cmd=reply&job=expire $name_expire
.
 !else
  !if $activetest=2
   zakljuèen, a ¹e vedno viden uporabnikom.
   !href cmd=reply&job=hide Skrij izpit
  !else
   zakljuèen in uporabnikom skrit.
   !href cmd=reply&job=expire Razkrij izpit
  !endif
  .
  !href cmd=reply&job=reactivate Ponovno aktiviraj izpit
. <p>
 !endif
 !href cmd=reply&job=deactivate Desactive it
 <center><table border=2>
 <tr><td align=right>$wims_name_title:
 <td><input size=40 name=title value="$title">
 <td rowspan=3><input type=submit value="$wims_name_change">
 <tr><td align=right>$wims_name_Description:
 <td><textarea name=desc rows=2 cols=40>$desc</textarea>
 <tr><td align=right>Datum zakljuèka:<td>
 !distribute item $[$expday],$[$expmon] into expday,expmon
 !formselect expday from 1 to 31
 !formselect expmon from 1 to 12 prompt $months
 !formselect expyear from $thisyear to $thisyear+1
 </table></center></form> <p>
 !goto end1
!endif

!form reply
<input type=hidden name=job value=text>
$wims_name_title (najveè $title_limit znakov):<br>
<input size=65 name=title value="$title"> <p>
Besedilo opisa (najveè $desc_limit znakov; dovoljeni so html
ukazi in hiperpovezave):<br>
<textarea rows=6 cols=65 name=desc>$desc</textarea>

<center><input type=submit value="Registracija besedila"></center>

<p>Datum zakljuèka izpita 
!distribute item $[$expday],$[$expmon] into expday,expmon
!formselect expday from 1 to 31
!formselect expmon from 1 to 12 prompt $months
!formselect expyear from $thisyear to $thisyear+1
. Posamezen poskus re¹evanja traja
<input size=5 name=duration value="$duration">
minut. Vsak uporabnik ima na voljo
!default stries=3
<input size=3 name=tries value="$stries"> poskusov re¹evanja.
<input type=submit value="$wims_name_tosave">

!ifval $activetest=-1
 <p>Ta izpit ¹e ne obstaja.
 <input type=submit value="Click to create it"> (but fill in the title first).
 </form>
 !goto end
!else
 </form>
 !if $exocnt>0
  <p>This exam is not yet activated.
  !href cmd=reply&job=prep_activate Click here
  to activate it.
  (Students only see active exams; on the other hand, you can no longuer
  modify the exam once it is activated.)
 !endif
!endif

:end1
<p>
!if $exocnt=0
 This exam has no content yet.
 !href cmd=reply&job=exo&exo=1 Add an exercise
.
!else
 <a name=list>
 $name_content:</a><ol>
 !for i=1 to $exocnt
  <li>
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,ch,ti
  $ti, $name_weight $we.
  !if $activetest=0
   &nbsp;(
   !if $i>1
    !href cmd=reply&job=moveup&moveup=$i#list $wims_name_up
    &nbsp;
   !endif
   !href cmd=reply&job=exo&exo=$i $wims_name_change
   &nbsp;
   !href cmd=reply&job=delete&delete=$i#list $wims_name_erase
   )
  !endif
 !next i
 </ol>
 !if $activetest=0
  !href cmd=reply&job=exo&exo=$[$exocnt+1] Add another exercise
, $wims_name_or
 !href cmd=reply&job=cpsheet add a series of exercises
.
 !endif
!endif

<p>
!if $activetest=0 and $erasable=yes
  You can still
  !href cmd=reply&job=prep_erase erase this exam
.
!endif

!if $activetest>=0
 !href cmd=reply&job=student Participants' view.
 <p>
 !form reply
 <input type=hidden name=allow value=yes>
 This exam is
 !formselect allowtype list all, simulation, none, select prompt\
	open to all, open for simulation,\
	closed to all, open to following hosts (and/or hours):
 <br><input size=50 name=IPlist value="$IPlist"> <br>
 Cut times:
 <input size=50 name=cutt value="$cutt"> <br>
 <input type=submit value="$wims_name_tosave">
 !set allowshare=0
 !if $sharers!=$empty
  ( for all sharing classes:
  !formselect allowshare list 0,1 prompt $wims_name_no,$wims_name_yes
  )
 !else
  <input type=hidden name=allowshare value=0>
 !endif
 </form>
 <small><b>$wims_name_help.</b> In the selective open mode, you can make time
 restrictions for score registrations, by adding words 
 <font color=blue><b>
 <tt>&gt;yyyymmdd.hh:mm</tt></b></font>
 (starting time) and/or
 <font color=blue><b>
 <tt>&lt;yyyymmdd.hh:mm</tt></b></font>
 (ending time). These must be in the
 SERVER's local time, and must be separated from other words by white spaces.
 <br>
 Cut times are used to let people take the exam in different sessions. A
 participant having worked on the exam before a cut time will have no access
 after the cut time.
 <br>
 Format of cut times: <tt>yyyymmdd.hh:mm</tt> (separate several cut times
 by white spaces).
 </small>
!endif
:end
!tail

!reset job,echoose,eweight,ename,edep,eopt,source
