
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,Maj,Jun,Jul,Avg,Sep,Okt,Nov,Dec
!set wims_name_refresh=Osve¾i to stran

!set wims_name_endexam=Konèaj
!set wims_name_scoreexam=Moj rezultat

!set name_mainpage=Main page of the exam
!set name_dependency=Score dependencies
!set name_Options=Options
!set name_All=All
!set name_title=Priprava izpita
!set name_expire=Zakljuèite izpit
!set name_done=done

!distribute items Ute¾,Weight,Rezultat\
into name_weight,name_coeff,name_Score

!distribute lines Zakljuèi ta izpit\
Back to work on the exam\
Skrbnikov pogled izpita.\
Predstavitev za uporabnike\
Current score detail\
Ta izpit ne vsebuje nobene naloge. Morda gre za napako skrbnika uèilnice.\
Trenutni rezultat - podrobnosti\
Z va¹e povezave re¹evanje izpita ni dovoljeno.\
Ta izpit lahko re¹ujete le enkrat.\
zato rezultata zdaj ne morete veè izbolj¹evati.\
To je va¹ zadnji dovoljeni poskus. Bodite uspe¹ni!\
 boste spro¾ili od¹tevanje èasa in poveèali ¹tevec porabljenih poskusov za ena.\
boste spro¾ili od¹tevanje èasa.\
Requires uspeh pri drugih vajah
Rezultat tega izpitnega poskusa\
into name_endexam,name_backexam,name_teacherview,name_presentation,\
name_scoreexam,name_empty,name_content,name_examclosed,name_exam1,name_exam5,\
name_lasttry,name_exam7,name_exam8,name_depend,name_scoreexam2

  
!set name_exam2=!nosubst ©tevilo dovoljenih ponovitev tega izpita je $stries.

!set name_exam3=!nosubst Pisanje izpita ste ¾e zakljuèili, na voljo ste imeli $tried poskusov,
!set name_exam4=!nosubst Izkoristili ste ¾e $tried dovoljenih poskusov,
!set name_exam6=!nosubst Na voljo vam je ¹e $tryremain poskusov.
!set name_exam9=!nosubst    Za re¹evanje izpita imate na voljo $sdure minut.\
   S klikom na zgornjo nalogo 
 
!set name_simulation=Ta izpit deluje v poskusnem naèinu, ki je enak obièajnemu, \
le da se vam poskusi ne ¹tejejo in registracija rezultata ni mo¾na.

  
!set wims_name_examremain=Preostali èas za re¹evanje: $