
<font color=blue><em>$class_institution</em></font>
的虚拟班级 <font color=blue><em>$class_description</em></font> (序列号 $jobclass) 的重要性质
!if $jobclass<10000
本班级来自 WIMS 的发布.
!endif

!form reply
<table border=0>
<tr><td align=right>主持教师密码:<td>
<input type=password size=20 name=clpass>
<tr><td align=right>参加者注册密码:<td>
<input type=password size=20 name=clpass2 value="$class_password">
<br><small>删除此密码会使人人都能进入此班级.</small>
<tr><td align=right>安全主机:<td>
<input size=50 name=clsecure value="$class_secure">
<tr><td align=right>有效日期:<td>
<input size=10 name=clexp value="$class_expiration">
<tr><td><td>
<input type=submit name=save value="$wims_name_tosave">&nbsp;&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
$table_end <p>

</form>

<p><b>附注</b>. 只有当班级的主持教师提出请求时 (他本人失去了控制) 时才能改变上述内容,
而且你应该
<a href="mailto:$class_email?subject=WIMS 班级的变化">通知主持教师</a>.
<p>
<center>
!href cmd=reply&job2=first 其它班级
</center> <p>

