

<b>Correspondencia biyectiva de objetos.</b>
(nombre<tt>correspond</tt>)
<br>
Se presentan dos conjuntos terminados de items,
teniendo el mismo número de elementos, al usuario,
en forma de una tabla a dos columnas, dado que se mezcló su correspondencia.
El usuario puede presionar estos items para reordenarlos hasta obtener la correspondencia correcta.
<p>
La buena respuesta debe darse en forma de matriz a dos líneas.
La primera línea es la de los objetos presentados a la izquierda,
el segundo la de los objetos de derecha.
Deben ser separadas por un punto y coma `;'.
</p><p>
Los items pueden contener del texto, imágenes (al formato HTML),
y fórmulas matemáticas utilizando <tt>\(...)</tt>.
</p><p>
Es preferible utilizar este campo de respuesta mediante \ embed {},
con un tamaño de campo bajo la forma <tt> VxHGxHD< /tt>, donde V
es el tamaño vertical de los items, y HG, HD los tamaños horizontales
de las columnas izquierda y derecha. Por ejemplo,

<tt>\embed{reply1,200 x 100 x 100}</tt>

</p><p>
Por defecto, la nota 0 se asigna a toda respuesta no enteramente
correcta. Si añaden la palabra <tt>split< /tt> en el campo
opcional "opción" de la respuesta, entonces el resultado será proporcional al
número de buenas correspondencias.
</p><p>
Este tipo, basado en DynAPI, puede no funcionar
con algunos navegadores.
</p>

