 <b>Expression mathématique.</b>
 (noms : <tt>algexp</tt>, <tt>litexp</tt> et <tt>formal</tt>)<br>
 Es una expresión matemática formal que se comparará
 con la respuesta correcta dada, según distintos criterios de definición.
 Se pueden poner varias respuestas correctas separadas por comas.
 <p>
  <tt>algexp</tt> : Es una expresión algebraica formal con identificaciones limitadas
 para la comparación. Por ejemplo, no se aceptará (x+1)(x-1)
 cuando la respuesta correcta es x^2-1. Y tampoco sin(x)^2+cos(x)^2 frente a 1.
 Por contra, x-y*y y -y^2+x serán consideradas idénticas. <p>
 Es útil para obligar a los estudiantes a realizar ellos mismos las
 simplificaciones de las expresiones. <p>


  <b>Expresión literal.</b> (nombre: <tt>litexp</tt>)<br>
 Es una expresión matemática formal que se comparará literalmente
 con la respuesta correcta dada, sin ninguna simplificación algebraica. Por
 ejemplo, x+y no se reconocerá como idéntico a y+x, ni 3/2 a 6/4. Sin
 embargo 2x y 2*x serán vistos como idénticos,
 y los espacios se eliminarán antes de la comparación.
 A utilizar con mucha precaución.

 <p>
 <b>Expresión formal.</b> (nombre: <tt>formal</tt>)<br>
 Como las expresiones numéricas, pero no se permite la aproximación. <p>
 Es posible poner varias respuestas correctas separándolas con comas.

