 <b>Numérica con intervalo.</b> (nombre: <tt>range</tt>)<br>
 Comparación de números reales en un intervalo: la respuesta correcta está compuesta
 por dos números, m y n, separados por una coma, siendo m&lt;n. Se aceptará
 cualquier entrada comprendida entre m y n (inclusives).

 Intervalos múltiples pueden darse añadiendo más items en la buena respuesta.

 <p>
 Si la buena respuesta contiene un número impar de items,
el último se utilizará para mostrar la buena respuesta.

 La macro slib <tt>text/approximation</tt> peut être utilisée pour calculer 
 ces trois nombres automatiquement. 