
<b>Conjunto finito.</b> (names: <span class="tt">set</span>, <span class="tt">fset</span> et <span class="tt">aset</span>)<br/>
 Es una lista de elementos (textuales) separados por comas,
 donde el orden no es importante.

 <span class="tt">set</span> : No se hace ninguna evaluación de los elementos antes de la comparación
 (por tanto 2 y 1+1 no son el mismo elemento).

<span class="tt">fset</span> : Como el <em>conjunto finito</em>, pero los elementos son evaluados
 como <em>expresiones formales</em>.

 <span class="tt">aset</span> : Como el <em>conjunto finito</em>, pero los elementos son evaluados
 como <em>expresiones aproximativas</em>.

