 <b>Palabras de una lista.</b> (nombre : <tt>wlist</tt>)<br>
En ese caso, la respuesta del usuario se compara palabra para palabra
con la buena respuesta, sin tener en cuenta el orden.
Y la comparación sólo se hace sobre los elementos esenciales
de las palabras: las diferencias capital/minúsculo, algunas diferencias
singular/plural (s en final de palabra), los acentos sobre las cartas,
las palabras muy comunes en inglés (a, the,…)  se ignoran.
<p>
Si la primera palabra de la buena respuesta dada es un número positivo n,
eso significa que la respuesta del usuario debe tener al menos n palabras
diferentes iguales a los alistados en la buena respuesta dada.
</p>

!read help/anstype.$lang/syno.phtml badonly

