
<h3><center>Adres en Naam conventies voor WIMS modules</center></h3>

Een reguliere module moet een adres hebben van het type:
<font color=green><tt>Zone/categorie/naam.taal</tt></font>.<br>
Een adres is een publiek bereikbare directory op een server.<br>
zoals bijvoorbeeld: http://$wims_ref_name?lang=$lang&+module=Zone/categorie/naam.taal&cmd=intro<br>
Dit wordt voor een module in ontwikkelings-stadium vertaald naar
<font color=green><tt>Zone~categorie~naam.taal</tt></font>.

<ul>
<p>
<li>Zone: dit is beperkt tot de toegestane zones van het systeem.
Waaronder:
<ul>
<li>Een hoofdletter,gevolgd door een getal; corresponerende
met het niveau en jaargang (zoals  E6,H1,H6 of U4) 
<li><font color=blue><tt>lang</tt></font>
betekend lesmateriaal voor het "taal onderwijs",
<li><font color=blue><tt>tool</tt></font>
bevat diverse online tools
<li><font color=blue><tt>local</tt></font>
voor modules die alleen worden gebruikt op een lokale server
<li><font color=blue><tt>test</tt></font>
is een niet publiceerbare testzone, waarin "alles" kan en mag.
</ul>
<p><li>categorie: dit kan in principe elk willekeurig woord zijn, <b>maar</b>
wanneer U besluit de module publiek te maken, en dus te publiceren op WIMS,
moet deze categorie wel bekend zijn bij het systeem; anders wordt de module geweigerd
<p>
Zie hiervoor de categorieen van reeds bestaande modules. Ingeval van twijfel
schrijf naar de
!mailurl $sysadmin publicatie c&ouml;rdinator
.

<p><li>naam: elk woord naar keuze, bijvoorkeur tussen de 4 en 12 karakters (kleine letters).

<p><li>taal:de twee-letterige taal code van de module. 
Deze moet deel uit maken van de door WIMS  ondersteunde talen ($wims_site_languages),
en <b>moet</b> gelijk zijn aan
de taal zoals gedefinieerd in de INDEX file van de module.
<p>

</ul>

<p>
Enkel veel gebruikte categori&euml;en: 
!read wimshome/public_html/bases/sys/categories.phtml
