
<h3><center>Mede auteurs</center></h3>

Geef hier het "mede auteur id" van mensen (afgezien van Uzelf)
 die u hierbij het recht geeft de module te veranderen

<b>Attentie</b>
Een eenmaal vergeven recht tot veranderen/schrijven van uw module ,
kan niet meer worden teruggedraaid !

<p>
Dit is alleen van belang voor stabiele versie publicaties.
Wanneer u deze module namens een andere auteur publiceerd, MOET u hier
de "id" van deze auteur vermelden.

