<p><hr width="35%">

!read Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=8
!if $qcnt>$exocnt
 !set qcnt=$exocnt
!endif
!if $exocnt<1
 Lo sentimos, este módulo no tiene ejercicios disponibles en este momento. 
 ¡Inténtelo más tarde!
 !exit
!endif
!if $exocnt=1
 Este módulo contiene en este momento un único ejercicio, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Inténtelo.
 !exit
!endif

!form new
<input type=hidden name=module value="$module">
<center><table border=0><tr>
<td align=center>Seleccione los ejercicios:<td>
!if $exocnt>6
 !set selsize=6
!else
 !set selsize=$exocnt
!endif
!set wims_formselect_switch=multiple size=$selsize
!set exo=$special_parm
!if $exo!=$empty
 !set exolist=!listuniq $exo,$exolist
 !set exolist=!replace , by , $ in $exolist
 !set dictionary=$module_dir/Extitles
 !set translator_unknown=leave
 !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
<tr><td align=center>Una sesión tendrá<td>
!set qnum=1
!formselect qnum from 1 to $qcnt
ejercicios.
<tr><td align=center>Nivel de severidad<td>
!set qcmlevel=3
!formselect qcmlevel from 1 to 8
!read introhook.phtml
</table> <p>
<input type=submit value="Al trabajo">
</center>
</form>
<b>Nota</b>. Los ejercicios propuestos se tomarán aleatoriamente de entre la
lista que ha generado. Si la lista está vacía, se usarán todos los ejercicios
disponibles.

!if * isin $titlelist
 <p>Los ejercicios marcados con un asterisco `*' son en general más 
 difíciles que los otros.
!endif

