
!set classname=$wims_classname - $wims_institutionname

!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!set wims_name_sheetcheck=provarla
!set wims_name_moduback=torna al modulo

!set wims_name_sheetcheck=Vérifier la feuille
!set wims_name_moduback=Retour au module

!set name_choose=Selezionare il test di autovalutazione in cui si vuole inserire il modulo
!set name_title=Inserire un modulo in un test di autovalutazione

!set name_insert=Stai per inserire l'esercizio
!set name_parm=con parametri di configurazione
!set name_modifytitle=&Egrave; possibile modificare il titolo e/o la descrizione.

!set name_required=Punteggio richiesto per completare questo test di autovalutazione\
!set name_repeat=un esercizio completato correttamente assegna 10 punti; se si richiedono \
pi&ugrave; di 10 punti si fa ripetere l'esercizio.
   
!set name_weight=Peso dei punti ottenuti per questo test (per il calcolo della media)
!set name_end=!nosubst Il modulo ``<tt>$title</tt>'' &egrave; stato inserito nel test di autovalutazione numero