
!set field=!item 2 of $special_parm

!if $field=$empty
 !exit
!endif

!set embraced_randitem=<p> \
Ce texte accepte la mise en aléatoire par des accolades emboitables.\
<p>\
Si vous mettez plusieurs mots (ou groupes de mots), séparés par des\
virgules, dans une paire d'accolades, ces mots seront tirés au hasard\
au moment où le texte est présenté aux élèves. Ce qui rendra le texte\
aléatoire. <p>\
Par exemple, si vous rentrez le texte <p>\
<font color=blue><tt>Je suis allé \
{à l'école,au cinéma,chez mes grand parents} {hier,la semaine dernière}</tt></font>,\
<p>vous aurez comme résultat l'une des phrases suivantes, aléatoirement&nbsp;:\
<pre>\
Je suis allé à l'école hier\
Je suis allé au cinéma hier\
Je suis allé chez mes grand parents hier\
Je suis allé à l'école la semaine dernière\
Je suis allé au cinéma la semaine dernière\
Je suis allé chez mes grand parents la semaine dernière\
</pre>

!if $(special_parm[3])!=$empty
 !readproc model/cut.proc model/src/$(special_parm[3]).oef
 !set title$field=$model_title
!else
 !readproc model/cut.proc
 !set title1=$model_title
!endif

<center><h2>$(title$field)</h2></center>

!if $field=1
 <center><b>$desc</b></center> <p>
!endif

$(help$field)

!if $(name$field) iswordof $model_random
 <p>
 Quelques exemples de génération de paramètre aléatoire : <ul>
 <li>Pour un entier compris entre 10 et 100 (inclusif) :
	 <tt>randint(10..100)</tt>
 <li>Pour un entier multiple de 10 compris entre 10 et 1000 (inclusif) :
	<tt>randint(1..100)*10</tt>
 <li>Pour un nombre décimal compris entre 0 et 2 :
	<tt>random(0..2)</tt>
 <li>Pour un objet tiré au hasard parmi une liste :
	<tt>randitem(a,b,c,10,100,mot,une phrase)</tt>
 </ul> <p>
!endif

!if $(name$field) iswordof $model_computed $model_random
 <p>
 !href cmd=help&special_parm=parameters Cliquez ici
 pour plus de détail sur le calcul des paramètres.
!endif

