
The virtual class <font color=blue><em>
$class_description</em></font>
of
<font color=blue><em>$class_institution</em></font>
!if $class_creation!=$empty
 is created on $class_creation and
!endif
 expires on $class_expiration.
!if $jobclass<10000
 This class comes with WIMS distribution.
!endif
<p><center><table border=0>
<tr><td align=right>Serial number:<td>$jobclass
<tr><td align=right>Supervisor:<td>
<a href="mailto:$class_email?subject=Your WIMS virtual
class">$class_supervisor</a>.
<tr><td align=right>$wims_name_Language:<td>$class_lang.
<tr><td align=right>$wims_name_level:<td>$class_level.
<tr><td align=right>Limit of participants:<td>$class_limit.
!default class_password=<font color=red>-- none --</font>
<tr><td align=right>$wims_name_Password for <br>participant subscription:<td>$class_password
$table_end <p>

Are you sure you want to erase this class?

<p><center><font size=+1>
 !href cmd=reply&job2=erase2&jobclass=$jobclass $wims_name_yes
&nbsp;&nbsp;&nbsp;
 !href cmd=reply&job2=first $wims_name_no
 
</font></center> <p>


