
Important properties of the virtual class <font color=blue><em>
$class_description</em></font>
of
<font color=blue><em>$class_institution</em></font> (serial number $jobclass).
!if $jobclass<10000
 This class comes with WIMS distribution.
!endif

!form reply
<table border=0>
<tr><td align=right>Supervisor password:<td>
<input type=password size=20 name=clpass>
<tr><td align=right>Password for participant registration:<td>
<input type=password size=20 name=clpass2 value="$class_password">
<br><small>Erasing this password makes the class
world-accessible.</small>
<tr><td align=right>Secure hosts:<td>
<input size=50 name=clsecure value="$class_secure">
<tr><td align=right>Expiration date:<td>
<input size=10 name=clexp value="$class_expiration">
<tr><td><td>
<input type=submit name=save value="$wims_name_tosave">&nbsp;&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
$table_end <p>

</form>

<p><b>Remark</b>. Changes to these fields only make sense when asked for by
the supervisor of the class (who has lost the control of the class). And you
should probably
<a href="mailto:$class_email?subject=WIMS class modification">notify the
supervisor</a> of the class of your changes.
<p>
<center>
!href cmd=reply&job2=first Other classes
</center> <p>

