
WIMS és un sistema obert, lliure i que accepta contribucions de tothom.
 Espero que les contribucions dels usuaris enriquiran considerablement
 el sistema i que finalment es convertirà en una eina important per la
 comunitat matemàtica.
<p>
Utilitzant WIMS en el mode avançat següent, t'ajudaràs a tu mateix i al
 mateix temps contribuiràs al desenvolupament del sistema (per tant
 ajudaràs a altres).

