!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.

<b>Erreur.</b>

!if $error iswordof file_error bad_image
 Votre fichier <font color=red><em>$fnamet</em></font>
 n'est pas reconnu comme une image !
 Utilisez uniquement les fichiers
 de format gif, jpg ou png.
 !exit
!endif

!if $error=bad_size
 L'image est d'une taille trop grande ou trop petite. 
 Elle doit être comprise entre $(sizemin)x$(sizemin) et
 $(sizemax)x$(sizemax).
 !exit
!endif

!if $error=unknown_size
 La taille de l'image est incompréhensible.
 !exit
!endif

!if bad_data=$error
 Je n'ai pas pu évaluer les valeurs que vous avez soumises. Erreur de frappe?
 !exit
!endif

!msg $error

