与此班级相应的链接是:<ul>
 <li>链接
  <a href="http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/classes&type=authsupervisor&class=$code"
  >http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/classes&type=authsupervisor&class=$code</a>
  能使你进入班级的维护页 (布置作业, 察看参加者以及他们的进展情况表等). <p>
 <li>链接
  <a href="http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/reguser&subclass=yes&class=$code"
  >http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/reguser&class=$code</a>
  使你的学生能注册到此班级 (或由你为你的学生注册)
   !if $Cltype>=2
    当你创建了名为$name_classe的班级.
   !endif
  !if $password!=$empty
   (注册时需要班级密码.)
  !endif
   !if $Cltype>=2
  <p>
  <li>链接
   <a href="http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/reguser&class=$code"
  >http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/reguser&class=$code</a>
  使主持教师能注册到班级 $name_classe (或你为它们注册).
  !if $password!=$empty
    (They will need the class password for the registration.)
   !endif
  !endif
  <p>
 <li>链接
  <a href="http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/classes&type=authparticipant&class=$code"
  >http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?lang=cn&module=adm/class/classes&type=authparticipant&class=$code</a>
  能使你的已注册的学生进入班级的主页. 并由此进入你为他们准备好的作业页.
  <p>
 </ul>
 <p><b><font color=red>注意.</font></b> 在离开此页时请把这些链接记录下来.
你也应该记住班级的数字.
