!bound adresse2 within $regpassmail default $empty
!if $adresse2=$empty or $adresse1=$empty
 wims_module_log=sendpwd error $adresse1@$adresse2
 !reset adresse1,adresse2
 !exit
!endif

sendmail=$adresse1@$adresse2
!reset adresse1,adresse2,regpass
wims_module_log=sendpwd $sendmail
!mailto $sendmail\
在WIMS服务器上创建班级用的密码\
\
以下创建班级的密码 :\
\
		$regpasswd\
\
请把这个密码复制到班级创建网页内.\
\
\
如果你看到此信感到莫名其妙, \
那一定是有人错误地把你的电邮地址给了自动软件. \
你完全可以忽略此信.\



