!set name_institution=学校名称
!set name_description=班级名称
!set name_supervisor=主持教师名
!set name_email=电邮地址
!set name_password=班级密码
!set name_passsup=主持教师密码
!set lev_E=小学
!set lev_H=中学
!set lev_U=大学
!set lv1=!char 1 of $ilevel
!set lv2=!char 2 of $ilevel
!set name_level=$(lev_$lv1), $lv2 年级

!set classname=<b><font color=green>$description</font></b>\
 <b><font color=green>($institution)</font></b>

!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=班级组
    !set name_sup=教师-主持教师
   !else
    !set name_classe=入口
    !set name_sup=主持教师
   !endif
     !set name_classes=$name_classe
     !set name_classess=$name_classe
     !set name_classesss=$name_classe
     !set name_classessss=$name_classe
 !else
   !set name_classe=班级
   !set name_classes=$name_classe
   !set name_classess=$name_classe
   !set name_classesss=$name_classe
   !set name_classessss=$name_classe
   !set name_sup=教师
 !endif

