!set wims_name_examremain=这次考试的剩余时间: $
!read js/examclock.phtml
<html><head>
$wims_html_header
</head><body $wims_htmlbody onload=$wims_html_onload>
!headmenu

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!if $job iswordof student score scorereg
 !changeto $job.phtml
!endif

<center>$classname
<p>
<h1>准备试卷 $exam
</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home 返回主页
. <p>
 !goto end
!endif

!if $job=exo
 !read $job.phtml
 !goto end
!endif

!if $activetest>0
 !form reply
 <input type=hidden name=job value=text>
 本试卷
 !if $activetest=1
  已被激活.
  !href cmd=reply&job=expire 请使其失效
.
 !else
  !if $activetest=2
   已过期, 但仍能被参加者看到.
   !href cmd=reply&job=hide 隐藏
  !else
   已过期且被隐藏.
   !href cmd=reply&job=expire 使其显示
  !endif
  .
  !href cmd=reply&job=reactivate 重新激活
. <p>
 !endif
!href cmd=reply&job=deactivate Desactive it
<p><center><table border=2>
 <tr><td align=right>标题:
 <td><input size=40 name=title value="$title">
 <td rowspan=3><input type=submit value=修改>
 <tr><td align=right>描述:
 <td><textarea name=desc rows=2 cols=40>$desc</textarea>
 <tr><td align=right>失效日期:<td>
 !distribute item $[$expday],$[$expmon] into expday,expmon
 !formselect expday from 1 to 31
 !formselect expmon from 1 to 12 prompt $months
 !formselect expyear from $thisyear to $thisyear+1
 </table></center></form> <p>
 !goto end1
!endif

!form reply
<input type=hidden name=job value=text>
标题 (限$title_limit个字符):<br>
<input size=65 name=title value="$title"> <p>
说明文字 (限$desc_limit个字符; 允许应用html tags或链接):<br>
<textarea rows=6 cols=65 name=desc>$desc</textarea>

<center><input type=submit value="注册此内容"></center>

<p>考试有效期至
!distribute item $[$expday],$[$expmon] into expday,expmon
!formselect expday from 1 to 31
!formselect expmon from 1 to 12 prompt $months
!formselect expyear from $thisyear to $thisyear+1
. 一场考试持续
<input size=5 name=duration value="$duration">
分钟. 每个参加者可以考
!default stries=3
<input size=3 name=tries value="$stries">次.
<input type=submit value="注册">

!ifval $activetest=-1
 <p>此试卷不存在.
 <input type=submit value="点击这里创建"> (请先填好标题).
 </form>
 !goto end
!else
 </form>
 !if $exocnt>0
  <p>此试卷尚未激活.
  !href cmd=reply&job=prep_activate 点击这里
以激活之.
  (学生只能看到激活了的试卷; 另一方面, 一旦激活后, 你也不能再改动了.)
 !endif
!endif

:end1
<p>
!if $exocnt=0
本试卷尚无内容.
 !href cmd=reply&job=exo&exo=1 添加练习
.
!else
 <a name=list>
 试卷内容:</a><ol>
 !for i=1 to $exocnt
  <li>
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,ch,ti
  $ti, weight $we.
  !if $activetest=0
   &nbsp;(
   !if $i>1
    !href cmd=reply&job=moveup&moveup=$i#list 上移
    &nbsp;
   !endif
   !href cmd=reply&job=exo&exo=$i 修改
   &nbsp;
   !href cmd=reply&job=delete&delete=$i#list 删除
   )
  !endif
 !next i
 </ol>
 !if $activetest=0
  !href cmd=reply&job=exo&exo=$[$exocnt+1] 加入别的练习
.
 !endif
!endif

<p>
!if $activetest=0 and $erasable=yes
  你仍可以
  !href cmd=reply&job=prep_erase 删除此试卷
.
!endif

!if $activetest>=0
 !href cmd=reply&job=考生所见.
 <p>
 !form reply
 <input type=hidden name=allow value=yes>
 本试卷
 !formselect allowtype list all, simulation, none, select prompt\
    对所有人开放, 仅用于模拟,\
    对所有人关闭, 仅对以下用户(或以下时段)开放:
 <br><input size=50 name=IPlist value="$IPlist"> <br>
 时间分割:
 <input size=50 name=cutt value="$cutt"> <br>
 <input type=submit value="纪录所作的修改">
 !set allowshare=0
 !if $sharers!=$empty
  (对所有共享的班级:
  !formselect allowshare list 0,1 prompt 否,是
  )
 !else
  <input type=hidden name=allowshare value=0>
 !endif
 </form>
  <small><b>提示.</b> 在选取开放模式时, 你可以为得分的录入设立
时间限制, 只要加入
 <font color=blue><b>
 <tt>&gt;yyyymmdd.hh:mm</tt></b></font>
 (起始时间) 与/或
 <font color=blue><b>
 <tt>&lt;yyyymmdd.hh:mm</tt></b></font>
 (结束时间). 它们都是服务器的当地时间, 而且要用空格前后隔开.
 <br>
时间分割使得学生可以参加不同场次的考试.
在分割时间点前已经参加过考试的参加者将不再能参加时间点以后的考试.
 <br>
 分割时间的格式: <tt>yyyymmdd.hh:mm</tt> (用空格分隔各时间点).
 </small>
!endif
:end
!tail

!reset job,echoose,eweight,ename,edep,eopt,source
