
!set classname=<b><font color=green>$wims_classname</font></b>,\
  <b><font color=green>$wims_institutionname</font></b>

!set months=一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月

!set wims_name_endexam=结束 本次考试
!set wims_name_scoreexam=我的得分

!set name_mainpage=考试的主页
!set name_dependency=得分相关性&nbsp;
!set name_Options=选项
!set name_All=所有
!set name_title=准备考试
!set name_expire=现在就使其失效
!set name_done=完成

!distribute items 权重,权重,得分\
into name_weight,name_coeff,name_Score

!distribute lines 结束这场考试\
返回继续考试\
主持教师所见的试卷.\
参加者看到的试卷\
当前得分的详情\
此考试是空的! 没有指定任何内容. 可能是主持教师的操作错误.\
给考试指定内容\
这次考试关于你的连接是关闭的.\
这个考试你只能考一次.\
所以你不能再改进你的分数.\
这是你的最后一次有效的尝试. 请小心!\
倒数计时将启动, 并且尝试次数增加 1.\
倒数计时将启动.\
要求成功完成其它练习\
本场考试的得分\
into wims_name_endexam,wims_name_backexam,wims_name_teacherview,name_presentation,\
name_scoreexam,name_empty,name_content,name_examclosed,name_exam1,name_exam5,\
name_lasttry,name_exam7,name_exam8,name_depend,name_scoreexam2

!set name_exam2=!nosubst 这个考试可以尝试至多 $stries 次.

!set name_exam3=!nosubst 你已经用 $tried 次尝试结束你的考试会话,
!set name_exam4=!nosubst  你已经作了 $tried 次尝试, 
!set name_exam6=!nosubst 你还可以作 $tryremain 次新尝试.
!set name_exam9=!nosubst 你有 $sdure 分钟可用于这个考试.\
   当你点击上列练习时, 
 
!set name_simulation=这个考试处于模拟状态. 它和正式考试一样,\
  只是不会记录你的得分, 并且你的尝试也不会计数.
  
!set wims_name_examremain=这个考试的剩余时间: $

!distribute lines 还不能算出\
  你还没有动手答题.\
  开始答题.\
  当前的得分不被记录, 因为考试处于模拟状态.\
into name_pending,name_begin1,name_begin2,name_simulation2

!set name_timeleft=!nosubst 时间到! 你已经用完了分配给这个考试的 $sdure 分钟.
!set name_realscore=!nosubst 你的这个考试页的实际得分是 $lastscore.
!set name_bestscore =!nosubst 你在这个考试的最佳得分是 $lastscore. (这是被记录的得分中的最高分.)
