
 <b>Click su un'immagine.</b>
 (nome: <tt>coord</tt>)
 <br>
 Questo tipo di risposta permette all'utente di cliccare su una data immagine
 e analizza la posizione del punto su cui l'utente ha cliccato con vari criteri
 di posizionamento.
 <p>
 La risposta corretta deve essere date come matrice (utilizzando un punto e virgola
 `;' come separatore tra le righe). La prima riga è l'URL dell'immagine. L'immagine
 deve essere in formato gif.
 <p>
 La seconda riga è la posizione ovvero il criterio perché le coordinate del click
 siano considerate corrette. Le righe seguenti (dalla terza in poi) contengono altri
 criteri (per risposte non corrette).
 <p>
 Quindi la risposta dell'utente è considerata corretta quando il punto su cui l'utente
 ha cliccato soddisfa le condizioni indicate nella seconda riga della matrice. 
 Altrimenti, se esistono le righe successive, la risposta è considerata sbagliata se
 soddisfa la condizione indicata nelle righe dalla terza in poi; infine è considerata
 ambigua se non soddisfa alcuna condizione (in quest'ultimo caso l'utente sarà invitato
 a riprovare). Se non ci sono righe indicanti posizioni non corrette, qualsiasi risposta 
 che non soddisfa la condizione della seconda riga della matrice sarà considerata un
 errore.
 <p>
 Il numero della riga corrispondente alla richiesta soddisfatta dalla risposta 
 dell'utente meno uno sarà salvato nella variabile <tt>\result</tt><em>n</em> 
 dove <em>n</em> è il numero del campo di risposta, variabile che può essere utilizzata
 in un \feedback.

 <p>
 Più condizioni possono essere combinate in una stessa riga, utilizzando i connettivi
 `&' (e/intersezione), `|' (o/unione), `^' (complementare), e le partentesi.
 </p><p>
 Si raccomanda che questo campo di risposta sia inserito nell'enunciato con un comando
 <tt>embed</tt>. Non può essere utilizzato insieme ad altri campi di risposta per l'ovvio
 motivo che il click dell'utente invia immediatamente l'esercizio al server per la 
 verifica della correttezza.
</p>

!set p=anstype.$lang/coord
!readproc tabletheme
$table_header
!set caption=!record 1 of help/$p
  <caption>$caption</caption>
  !set header=!record 2 of help/$p
  $table_tr<th>$(header[1])</th><th>$(header[2])</th></tr>
  !set cnt_record=!recordcnt help/$p
  !for u= 3 to $cnt_record
    !set l_=!record $u of help/$p
    $table_tr<td><tt>
!line 1 of $l_
    </tt></td><td>
!line 2 to -1 of $l_
   </td>
  !next
$table_end
