
 <b>Corrispondenza uno-a-uno di oggetti.</b>
 (nome: <tt>correspond</tt>)
 <br>
 Viene mostrata all'utente una tabella in cui le due colonne sono gli elementi
 di due insiemi finiti con lo stesso numero di elementi disposti in modo casuale.
 L'utente deve cliccare sugli oggetti in modo da meterli in ordine e da ottenere 
 la corretta corrispondenza tra gli elementi dell'uno e dell'altro.
 <p>
 La risposta corretta deve essere data come matrice di due right. La prima riga
 contiene gli oggetti del primo insieme, la colonna di sinistra, (una lista), e la
 seconda gli oggetti del secondo insieme, la colonna di destra. Le due righe della
 matrice devono essere separate da un punto e virgola `;'.
 <p>
 Gli oggetti delle due liste possono essere di tipo testo, immagini (in formato HTML),
 o formule matematiche, utilizzando il comando <tt>\(...)</tt>.
 <p>
 &Egrave; meglio inserire questo tipo di risposta nell'enunciato con un comando 
 \embed{}, inserendo le dimensioni del campo di input come opzione di tale comando 
 nella forma <tt>VxH1xH2</tt>, dove V è la dimensione verticale degli elementi della lista,
 e H1,H2 sono rispettivamente le larghezze delle due colonne della tabella.
 <p>
 Di default, viene assegnato un voto 0 alle risposte in cui non sono indicate correttamente
 tutti gli accoppiamenti. &Egrave; possibile utilizzare l'opzione <tt>split</tt> 
 per assegnare invece un punteggio proporzionale al numero di coppie corrette indicate.
 <p>
 Basato su DynAPI, potrebbe non funzionare con alcuni browser.

