 <b>Numero.</b> (nome: <tt>numeric</tt>)<br>
 Confronto di numeri reali fino alla precisione stabilita dall'autore.
 
 Se è presente l'opzione <tt>comma</tt>, i numeri reali possono essere
 inseriti dall'utente con una virgola come separatore dei decimali (ma
 in fase di programmazione dell'esercizio occorre utilizzare il
 punto). In questo caso, se l'utente iserisce una risposta errata,
 l'eventuale risposta corretta viene proposta con lo stesso separatore
 per i decimali utilizzato dall'utente.
