
!read adm/title.phtml 3\
$wims_name_account_property\
($wims_class)
!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$moduclass_lang
 </div>
<hr/>
!endif

!read adm/class/initclass $wims_class
!set inplen=40
!form reply
<input type="hidden" name="job" value="userprop"/>
<input type="hidden" name="getuser" value="$getuser"/>
$table_header
$table_tr
 <th>$wims_name_Login</th>
 <td><span class="tt">$getuser</span>
  !if $getuser isitemof $wims_connectedlogin and $wims_user=supervisor
    <img src="gifs/themes/$wims_theme_icon/connected.png" width="15px" />
   !endif
 </td>
</tr>
!if $type_class iswordof 2 4 or ($class_Supervisor=$wims_realuser and $wims_class!=$wims_superclass and $wims_realuser!=$getuser)
  !if $user_participate!=$empty and $type_class iswordof 2 4
    $table_tr<th>$name_inscript</th><td><span class="tt">$user_participate</span></td></tr>
  !endif
  !if $user_supervisable=yes
    $table_tr<th>$name_gestion</th><td>
    !if $type_class iswordof 2 4
     <input size="$inplen" name="up_supervise" id="up_supervise" value="$user_supervise"/>
     <span class="tt">$wims_class/1, ... </span></td></tr>
    !else
      !if $wims_class isitemof $user_supervise
        !set superv=yes
      !else
        !set superv=no
      !endif
     !formradio superv list yes,no prompt $wims_name_yes, $wims_name_no
     !set up_firstname=$user_firstname
     !set up_lastname=$user_lastname
    !endif 
  !endif
!endif
!if $user_supervisable=yes and $getuser!=$wims_realuser and $type_class notwordof 2 4 
 !goto end
 !exit
!endif
!if $class_auth=$empty or $wims_user=supervisor
$table_tr<th>$wims_name_Password</th><td>
	!href module=adm/class/passwd&job=part&part=$getuser $name_change
</td></tr>
!endif
$table_tr<th><label for="up_lastname">$wims_name_lastname</label></th><td>
	<input size="$inplen" name="up_lastname" id="up_lastname" value="$user_lastname"/></tr></tr>
$table_tr<th><label for="up_firstname">$wims_name_firstname</label></th><td>
	<input size="$inplen" name="up_firstname" id="up_firstname" value="$user_firstname"/></td></tr>
$table_tr<th><label for="up_email">$wims_name_email</label></th><td>
	<input size="$inplen" name="up_email" id="up_email" value="$user_email"/></td></tr>
$table_tr<th><label for="up_regnum">$name_regnum</label></th><td>
	<input size="$inplen" name="up_regnum" id="up_regnum" value="$user_regnum"/></td></tr>
$table_tr<th><label for="up_photourl">$name_photourl</label></th><td>
	<input size="$inplen" name="up_photourl" id="up_photourl" value="$user_photourl"/></td></tr>
!if $wims_user=supervisor
 $table_tr<th><label for="up_comments">$name_comments</label></th><td>
	<input size="$inplen" name="up_comments" id="up_comments" value="$user_comments"/></td></tr>
 $table_tr<th><label for="up_vars">$name_vars</label></th><td>
	<textarea wrap="off" cols="$[$inplen-1]" rows="4" name="up_vars" id="up_vars">$user_vars</textarea></td></tr>
  $table_tr<th><label for="up_external_auth">$name_external_auth</label></th><td>
	<input size="$inplen" name="up_external_auth" id="up_external_auth" value="$user_external_auth"/>
	!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=authentification $wims_name_help
</td></tr>
!else
 $table_tr<th><label for="passcheck">$name_classpassword</label></th><td>
 	<input size="14" type="password" name="passcheck" id="passcheck"/> <br/>
	<small>$name_enterpassword</small></td>
!endif
:end
$table_end
<div class="wimscenter wimsform">
<input type="submit" name="reg" value="$wims_name_tosave"/> &nbsp;
<input type="submit" name="abandon" value="$wims_name_giveup"/>
</div>


!formend


!if $wims_user=supervisor
 !set wims_menu_items=!append line Score1,1,cmd=reply&job=getuser&getuser=$getuser\
to $wims_menu_items
 !set wims_menu_items=!append line workdetail,1,cmd=reply&job=getraw&getraw=$getuser\
 delprep,1,cmd=reply&job=delprep&delprep=$getuser\
 part_list,1,cmd=resume\
to $wims_menu_items
!else
 !set wims_menu_items=!append line class_home,1,module=home\
to $wims_menu_items
!endif

!reset reg,abandon

