
$title
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=share $wims_name_help

<p>

!if $sharing_all=$empty
 $name_noresource
!else
!read themetable
 $name_resource 
 $table_header
 $table_hdtr <th>$wims_name_Type</th><th>$wims_name_class</th><th>$wims_name_Supervisor</th><th>$wims_name_action</th>
 !for rec in $sharelist
  !if $(sharing_$rec)!=$empty
   $table_tr
 !!  $name_sharelist
   !set D_=!defof class_institution\
class_description\
class_supervisor in wimshome/log/classes/$(sharing_$rec)/.def
   !distribute lines $D_ into i_,d_,s_
   <td align="center">$(name_$rec)<td align="center">$d_ <br>$i_</td> <td align="center">$s_
   <td align="center">
   !href cmd=reply&job2=stopshare&nei=$(sharing_$rec)&stoprec=$rec $name_stopsharing
. &nbsp;
!set wims_ref_class=wims_button_help
   !href cmd=help&special_parm=stopshare $wims_name_help
   </td>
  !endif
 !next rec
$table_end
!endif
!if $sharable_all!=$empty
 <p>$table_header
 <caption>$name_classsharing</caption>
 $table_hdtr<th>$wims_name_Type<th>$wims_name_class<th>$wims_name_Supervisor<th>$wims_name_Status
 !for r in $sharable
  !for cl in $(sharable_$r)
   $table_tr<td align="center">$(name_$r)
   !set D_=!defof class_institution\
class_description\
class_supervisor in wimshome/log/classes/$cl/.def
   !distribute lines $D_ into i_,d_,s_
   <td align="center">
   !href cmd=reply&job2=def&nei=$cl $i_<br>$d_
   <td align="center">$s_</td>
   !set s_=!defof $(sharing_$r) in wimshome/log/classes/$cl/neighbors
   <td align="center">
   !if $s_=$wims_class
    $name_active
   !else
    ---
   !endif
  !next cl
 !next r
 $table_end <p>
!endif
