!default target1=$o1
!default target4=$o4
<table border=0 cellpadding=0 cellspacing=0>
<tr><td align="center"><small>$name_zone</small></td>
<td></td><td align="center"><small>$name_category</small></td>
<td></td><td align="center"><small>$wims_name_name</small></td>
<td></td><td align="center"><small>$wims_name_Language</small></td>
</tr><tr>
<td align="center">
!formselect target1 list $zonelist
</td><td>~</td><td align="center">
<input type=text size=12 name="target2" value="$o2">
</td><td>~</td><td align="center">
<input type=text size=12 name="target3" value="$o3">
</td><td>.</td><td align="center">
!formselect target4 list $langlist
</td><td>
!set wims_ref_class=wims_button_help
!href cmd=help&special_parm=addressing $wims_name_help
!if nook notwordof $wims_read_parm
 &nbsp;<input type=submit value="$wims_name_tosave">
!endif
</td></tr></table>
