<center><h3>Insérer des champs de réponse dans l'énoncé</h3></center>

:signification
Il est possible d'inclure des champs de réponse dans l'énoncé de vos exercices
sous format html. Les réponses et choix doivent être définis de façon
habituelle.
<p>

:example
 <span class="wims_help_example">Exemple</span>
<ul>
<li><tt>\embed{choice 1}</tt> insérer le premier <i>choix multiple</i> dans le texte.</li>
<li><tt>\embed{reply 2}</tt> insérer la deuxième <i>réponse libre</i>
dans le texte.</li>
<li><tt>\embed{reply 1,5}</tt> peut avoir plusieurs significations 
suivant le type de réponse. En général, cela signifie :
insérer la première <i>réponse libre </i> avec la
taille du champ de réponse égale à 5.
Par contre, si le type de <tt>reply 1</tt> est parmi <tt>checkbox</tt>,
<tt>click</tt>, <tt>radio</tt>, <tt>\embed{reply 1,5}</tt>
insère seulement l'un des choix (le numéro 5 dans ce cas) dans le format correspondant
au type. Cela permet l'insertion de choix dans différentes structures de texte
(en liste, dans un tableau, ...). 
</li>
<li><tt>\embed{reply 1,AxBxC}</tt> peut avoir plusieurs significations
selon le type : 
<ul><li>dans le cas où le type est <tt>clickfill</tt> ou <tt>dragfill</tt>, 
A et B sont les tailles horizontale et verticale (en pixels) d'une case, 
et C est le nombre de cases que contient le champ de réponses.
</li><li> dans le cas où le type est <tt>correspond</tt>,
A est la taille verticale des items,  
B et C sont respectivement la taille horizontale des colonnes de 
gauche et de droite.
  </li>
  <li>
  Dans le cas de réponses de type texte libre, d'autres lignes peuvent être ajoutées
  permettant de personnaliser le style du champ de réponses. De plus, si la première ligne supplémentaire 
  est le mot <tt>default</tt>, le champ aura la classe
 de style css <tt>wims_oef_input</tt> : le gestionnaire du site ou l'enseignant peuvent alors
 le configurer de manière générale. Par exemple,
  pour le type "numeric"
<pre>
  \embed{reply 1,12
  style="font-size:18px;background-color:#e8ffff;border:1px solid #3333CC;"
  autocomplete=off }
 </pre>
 </li></ul>
 
  
  
