
Si vous avez défini des variables techniques associées aux participants
(par exemple leur groupe), ce qui peut se faire
<ul><li>
à l'aide de la liaison tableur,
</li><li>
directement dans les propriétés du compte des participants
</li><li>
par le biais d'un questionnaire non anonyme
</li></ul>
(voir les documentations correspondantes), vous pouvez filtrer
les participants relativement à ces variables.
Ecrivez sur une même ligne les conditions qui doivent être remplies
simultanément en les séparant par des espaces.
Les participants sélectionnés sont ceux satisfaisant au moins une
des lignes de conditions.
<p>Par exemple,
<pre>
groupe=1 langue=2
groupe=3
</pre>
sélectionnera les participants qui appartiennent au groupe 1 et dont la langue est 2 ou
qui appartiennent au groupe 3.
