
<p>
La définition de poste de connexion dans WIMS peut se faire soit par nom de
machine soit par numéro IP. Mais nous recommandons fortement l'utilisation de
numéros IP. Les noms de machine ne sont pas aussi sûrs.
<p>
Vous pouvez aussi définir les postes de façon globale, comme d'habitude&nbsp;:
<tt>127.0.0.</tt> (mais pas <tt>127.0.0</tt>)
correspond à 127.0.0.1 jusqu'à 127.0.0.255, et <tt>.unice.fr</tt>
(mais pas <tt>unice.fr</tt>) correspond à n'importe quel poste du domaine
<em>unice.fr</em>.
<p>
Enfin, le mot <tt>all</tt> donne l'accès à tout le monde. Il détruit
totalement la barrière de protection offerte par ce champ, mais si vous
faites ce choix, c'est votre problème.
<p>
Ne vous fiez pas à votre numéro IP actuel si vous avez une ligne de connexion
avec numéro IP dynamique&nbsp;! Ce numéro changera d'une connexion à l'autre.
