
<h3>Le format OEF</h3>
<p>

OEF veut dire ``online exercise format'', un format pour des exercices
mathématiques destinés aux systèmes d'enseignement assisté par ordinateur.
Le but de la création de ce format est de favoriser les échanges de contenu
entre différents systèmes. Ce format contient donc uniquement des
informations mathématiques de l'exercice.
</p><p>
L'avantage du format OEF est que les exercices sous ce format sont très
faciles à créer. Mais 
il faut savoir que ces exercices, en particulier
ceux créés par $module_title, ne sont pas aussi performants que des
exercices propres à un système comme WIMS. Il est difficile d'imaginer,
du moins pour l'instant, que les
exercices WIMS tels que Q-Puzzle, la série Coïncidence, ou encore 
la série Tir, puissent être transformés en format oef.
</p><p>
Vous pouvez aussi consulter
!href cmd=help&special_parm=examples les exemples
 pour avoir une idée de la structure d'un fichier OEF. 
 </p>
<h4>Syntaxe de base</h4>
<p>
Le format d'un fichier OEF est très similaire à LaTeX. Il est composé d'instructions 
suivies d'un ou plusieurs paramètres. Une instruction est un mot
précédé du caractère <tt class="wims_code_words">\</tt>, et
les paramètres sont fermés dans des accolades.
Par exemple, dans la phrase suivante
</p>
<pre>
   \answer{La réponse}{1; oui,non}{type=radio}
</pre>
il y a une instruction ayant le nom <tt class="wims_code_words">answer</tt>, 
qui a 3 paramètres&nbsp;:<tt class="wims_code_words">La réponse</tt>, <tt class="wims_code_words">1; oui,non</tt>
et <tt class="wims_code_words">type=radio</tt>.
Dans
<pre>
   \choice{La réponse}{oui}{non}
</pre>
il y a une instruction ayant le nom <tt class="wims_code_words">choice</tt>, 
qui a 3 paramètres&nbsp;:<tt class="wims_code_words">La réponse</tt>, <tt class="wims_code_words">oui</tt>
et <tt class="wims_code_words">non</tt>.


<h4>Liste d'instructions</h4> <p>
Voici une liste brève d'instructions reconnues par le gestionnaire OEF de
WIMS. Voir aussi
!href cmd=help&special_parm=parameters aide sur paramètres
 pour la syntaxe de définition de paramètres.
</p>