
:Fonctions aléatoires
:Fonction,Exemple,Signification
:random
random(-5..5)
un nombre au hasard entre -5 et 5.

:randint
randint(-5..5)
un entier au hasard entre  -5 et 5 (bornes comprises).

:randitem
randitem(+,-)
un signe aléatoire: + ou -

:random
random(1,2,3,a,b,c)
un item au hasard parmi {1,2,3,a,b,c}

:shuffle
shuffle(6)
une liste de 6 entiers 1,2,...,6, dans un ordre aléatoire.

:shuffle
shuffle(a,b,c,d,e)
la liste des lettres {a,b,c,d,e}, dans un ordre aléatoire.

:randomitem
randomitem(\list)
un item au hasard de la liste  \list (items séparés par des virgules).

:randitem
randitem(\list)
un item au hasard de la liste  \list (items séparés par des virgules).

:randomrow
randomrow(\mat)
une ligne au hasard de la matrice  \mat.



