
<h3 class="wimscenter">Paramètres aléatoires dans un exercice interactif</h3> <p>

L'utilisation de paramètres aléatoires rendra votre exercice beaucoup
plus intéressant, car ce sera un exercice différent chaque fois qu'il est
redemandé.
</p><p>
Par exemple, la ligne suivante définit un paramètre sous le nom de
<font color=blue><b>x1</b></font>, dont la valeur sera un entier aléatoire entre
-10 et 10 (inclusif)&nbsp;:
<pre>
\integer{x1=random(-10..10)}
</pre>
Ce paramètre aléatoire peut ensuite être invoqué par le mot
<b><span class="tt wims_code_variable">\x1</span></b>, dans l'énoncé, les réponses, l'indication et la solution.
C'est-à-dire, chaque mot <span class="tt wims_code_variable">\x1</span> dans ces textes 
sera remplacé par la valeur aléatoire
du paramètre. Cette substitution prend aussi effet dans les définitions
d'autres paramètres qui suivent celle de <span class="tt wims_code_words">x1</span>.
<p>
Supposons maintenant que vous avez entré
<pre>
\integer{x1=random(-10..10)}
\integer{y1=\x1+3}
</pre>
dans le champ de la définition de paramètre, et la question
<pre>
Calculez la multiplication de \x1 par \y1.
</pre>
dans l'énoncé de l'exercice. Supposons que sur une demande de l'exercice,
une valeur aléatoire <font color=red>-7</font> est attribuée à \x1. Alors
le paramètre suivant \y1 prendra la valeur -4, et l'énoncé de l'exercice
sera présenté sous la forme <p class="wimscenter">Calculez la multiplication de -7 par -4.
</p>
Vous pouvez ensuite définir une réponse numérique au nom de <span class="tt">Le
produit</span>, ayant pour bonne solution <span class="tt">(\x1)*(\y1)</span>. (Remarquez
qu'ici les parenthèses sont nécessaires car la substitution se fera de façon
littérale.)
<a id="list"></a>
!if oefparm isitemof $special_parm
 !changeto help/oefparm.phtml
!endif
<p>$table_header
<caption>Quelques autres exemples de paramètres
!href cmd=help&special_parm=$special_parm,oefparm#list [liste complète]
</caption>
$table_hdtr<th>Définition</th><th>Effet</th></tr>
$table_tr<td><span class="tt wims_code_words">\real{x=random(-5..5)}</span>
    </td><td>\x sera un nombre réel aléatoire<br/>entre -5 et 5
$table_tr<td><span class="tt wims_code_words">\real{a=random(-5,-3,0.3,4)}</span>
    </td><td>\a sera un nombre réel pris aléatoirement<br/>parmi -5,-3,0.3 et 4
$table_tr<td><span class="tt wims_code_words">\complex{z=(1+2*i)^3}</span>
    </td><td>\z sera le nombre complexe z=(1+2*i)^3
$table_tr<td><span class="tt wims_code_words">\text{sign=random(+,-)}</span>
    </td><td>\sign sera un signe aléatoire: + ou -
$table_tr<td><span class="tt wims_code_words">\integer{n=3*exp(\a)}</span>
    </td><td>\n sera l'entier le plus proche de 3*e<sup>\a</sup> <br/>(il dépend de la
    valeur de \a)
$table_tr<td><tt class="wims_code_words">\function{f=random<br/>(x^2+1,sin(x),log(x))}</tt>
    </td><td>\f sera une fonction aléatoire: soit x^2+1,<br/>soit sin(x), soit
    log(x)
$table_tr<td><span class="tt wims_code_words">\real{a=evalue(x^2+sin(y),x=3,y=4)}</span>
    </td><td>Evaluation de la fonction x^2+sin(y),<br/>
    pour x=3, y=4
$table_tr<td><span class="tt wims_code_words">\real{r=solve(x^3-3*x+1,x=0..1)}</span>
    </td><td>\r sera la racine simple de x^3-3x+1 entre 0 et 1
$table_tr<td><span class="tt wims_code_words">\function{h=simplify(x^5*y^3*x^2/y)}</span>
    </td><td>Expression simplifiée : x<sup>7</sup>y<sup>2</sup>
$table_tr<td><span class="tt wims_code_words">\function{g=diff(sin(x)+cos(y),x)}</span>
    </td><td>\g sera la dérivée de sin(x)+cos(y) par rapport à x
$table_tr<td><span class="tt wims_code_words">\function{F=int(x^2+3*x+1,x)}</span>
    </td><td>\F sera une primitive de x^2+3*x+1,<br/>
     le terme constant n'étant pas garanti d'être toujours le même
!!$table_tr<td><tt class="wims_code_words">\function{F=int(t^2+3*t+1,t=1..x)}
!!    <td>\F sera la primitive x^2+3*x+1 telle que g(1)=0
$table_tr<td><span class="tt wims_code_words">\real{a=int(t^2+3*t+1,t=0..1)}</span>
    </td><td>\a sera l'intégrale numérique de x^2+3*x+1, de 0 à 1
$table_tr<td><span class="tt wims_code_words">\text{f=htmlmath(2*x^2+3*x)}</span>
    </td><td>\f sera rendu en html comme: 2x<sup>2</sup>+3x
$table_tr<td><span class="tt wims_code_words">\text{f=texmath(2*x^2+3*x)}</span>
    </td><td>\f sera le source TeX de l'expression.
$table_tr<td><span class="tt wims_code_words">\integer{n=items(a,b,c,d,e,f)}</span>
    </td><td>\n sera le nombre d'articles (ici c'est 6) dans la liste
     {a,b,c,d,e,f}
$table_tr<td><span class="tt wims_code_words">\text{i=item(3,a,b,c,d,e,f)}</span>
    </td><td>\i sera l'article numéro 3 de la liste
     {a,b,c,d,e,f} (donc c).
$table_tr<td><span class="tt wims_code_words">\text{s=shuffle(6)}</span>
    </td><td>\s sera la liste des 6 entiers 1,2,...,6, dans un ordre aléatoire.
$table_tr<td><span class="tt wims_code_words">\text{s=shuffle(a,b,c,d,e)}</span>
    </td><td>\s sera les lettres {a,b,c,d,e} dans un ordre aléatoire.
$table_tr<td><tt class="wims_code_words">\matrix{m=1,2,3<br/>4,5,6<br/>7,8,9}</tt>
    </td><td>\m sera la matrice de 3 lignes et 3 colonnes.
$table_tr<td><span class="tt wims_code_words">\text{t=asis(Comment ça va ? matrix(1,2,3))}</span>
    </td><td>\t est la chaîne comme elle est écrite, <br/>sans transformation ni conditionalité.</td>
</tr>
$table_end <p>

Paramètres conditionnels&nbsp;: vous pouvez écrire<p>
<pre>
\text{ttt=_condition?_def1}
\text{ttt=_condition?_def1:_def2}
</pre>
<p>
Dans ce cas, <span class="tt wims_code_words">ttt</span> aura la valeur <span class="tt wims_code_words">_def1</span> si
<span class="tt wims_code_words">_condition</span> s'avère vraie, ou <span class="tt wims_code_words">_def2</span> sinon (dans la seconde
syntaxe).
!href target=wims_mhelp cmd=help&special_parm=if Liste de conditions
</p><p>
La position relative d'une définition par rapport à l'énoncé est
importante&nbsp;: si une variable est définie APRÈS l'énoncé, l'évaluation
de la variable aura lieu uniquement APRÈS que l'utilisateur ait répondu à
la question. Dans ce cas, la définition peut utiliser les réponses données
par l'utilisateur, via <span class="tt wims_code_variable">\reply1</span>, <span class="tt wims_code_variable">\reply2</span>, etc. Et la
variable ainsi définie peut être utilisée dans les conditions
de test ou les feedbacks.

