!!Don't translate yet. 
!read adm/title.phtml 1\
Publication and Download centers


Deux serveurs officiels <tt>unice</tt> et <tt>wimsedu</tt> sont proposés pour la publication de modules
et leur téléchargement. Ils sont synchronisés dans la mesure où leur version
est compatible avec la version de wims requise des modules publiés. Dans le cas où un module
publié sur un des serveurs de publication n'est pas compatible avec la version wims d'un serveur,
le serveur en question garde en mémoire l'adresse du module de manière à éviter qu'un 
autre auteur en publie un du même nom. 

<p>
Les auteurs doivent être enregistrés dans un des centres de publication pour pouvoir
publier. Dans le cas contraire ou pour les premiers modules, ils doivent passer par
un "parrain" qui validera leur module.
</p>

<p>
Le gestionnaire d'un serveur wims choisit les centres de publication
qu'il propose à ses auteurs. Les auteurs sont enregistrés indépendamment
sur l'un ou/et l'autre serveurs de publication.
</p>
<p>
L'auteur qui publie un module sur un des serveurs de publication n'a le droit de modification
que sur ce serveur. Si pour une raison valable (version plus récente de WIMS par exemple), 
l'auteur veut changer de centre de publication pour ce module, il doit le demander 
aux gestionnaires de serveurs de publication.
</p>

<p>Le gestionnaire d'un serveur wims choisit les centres de téléchargement qu'il désire utiliser.
</p>
<p>
La possibilité d'ajouter d'autres centres de téléchargement ou de publication existe pour le futur.
</p>