
<H3><center>Utiliser un document pour faire une présentation de la feuille de travail</center></H3>

Vous pouvez mettre l'adresse d'un bloc de document
(comme <tt>c1/main</tt>). Celui-ci sera alors utilisé comme page de présentation de la feuille de travail.
Le document lui-même doit ne pas être lisible par les participants.
<p>
Laissez ce champ vide si vous désirez utiliser la page de présentation standard.
<p>
Les liens sur les exercices individuels sont à définir en utilisant la commande
<tt>\exercise</tt>.
Vous pouvez aussi utiliser les variables suivantes qui sont prédéfinies :<ul>
 <li><tt>\scorerequire</tt> Nombre de points requis pour chaque exercice. 
 <li><tt>\scoregot</tt> Nombre points demandés au participant pour chaque exercice.
 <li><tt>\scoremean</tt> Score moyen pour chaque exercice
 <li><tt>\expiration</tt> Date d'expiration de la feuille dans le format yyyymmdd (aaaammjj)
 <li><tt>\today</tt> Date du jour dans le format yyyymmdd (aaaammjj)
</ul>
Tous les paramètres des variables de score sont des listes de nombres, chacun des items
correspondant au nombre demandé pour un exercice de la feuille de même position.