
!if $module_language notwordof fr es
<p>
Definition of hosts in WIMS can be made either through host name or IP
number. But we highly recomment that you use IP numbers whenever possible.
Host names are not as secure.
<p>
You can also define global host names in the usual way: <tt>127.0.0.</tt>
(but not <tt>127.0.0</tt>)
matches 127.0.0.1 to 127.0.0.255, and <tt>.unice.fr</tt>
(but not <tt>unice.fr</tt>) matches any host in the domain <em>unice.fr</em>.
<p>
Finaly, the word <tt>all</tt> matches every host in the world. This is hugely
insecure, but if you choose it, that is your problem.
<p>
Don't trust your current IP number if you are on a subscription line
with dynamic IP! That will change from one connection to the other.
!endif

!if $module_language=fr
<p>
La définition de poste de connexion dans WIMS peut se faire soit par nom de
machine soit par numéro IP. Mais nous recommandons fortement l'utilisation de
numéros IP. Les noms de machine ne sont pas aussi sûrs.
<p>
Vous pouvez aussi définir les postes de façon globale, comme d'habitude&nbsp;:
<tt>127.0.0.</tt> (mais pas <tt>127.0.0</tt>)
correspond à 127.0.0.1 jusqu'à 127.0.0.255, et <tt>.unice.fr</tt>
(mais pas <tt>unice.fr</tt>) correspond à n'importe quel poste du domaine
<em>unice.fr</em>.
<p>
Enfin, le mot <tt>all</tt> donne l'accès à tout le monde. Il détruit
totalement la barrière de protection offerte par ce champ, mais si vous
choisissez ainsi, c'est votre problème.
<p>
Ne vous fiez pas à votre numéro IP actuel si vous avez une ligne de connexion
avec numéro IP dynamique&nbsp! Ce numéro changera d'une connexion à l'autre.
!endif

!if $module_language=es
<p>
La definición del servidor en WIMS puede hacerse por el nombre de la máquina
o por su IP. Sin embargo recomendamos encarecidamente el uso de
números IP, los nombres de máquina pueden dar pie a problemas de seguridad.
<p>
También se pueden definir los servidores de forma global, como de costumbre:
<tt>127.0.0.</tt> (pero no <tt>127.0.0</tt>)
corresponde a las IP del 127.0.0.1 al 127.0.0.255, y <tt>.unice.fr</tt>
(no <tt>unice.fr</tt>) corresponde a cualquier servidor del dominio
<em>unice.fr</em>.
<p>
<p>Por último, la palabra <tt>all</tt> abre acceso a todo el mundo. Esto
destruye totalmente la seguridad de su sistema; si elige esta opción
es problema suyo.
<p>
No podrá confiar en su IP actual si su conexión se establece
mediante IP dinámica: la IP cambiará de una conexión a otra.
!endif

