!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.

<b>Fout.</b>

!if $error iswordof file_error bad_image
 Het bestand <font color=red><em>$fnamet</em></font>
 wordt niet herkend als een plaatje !
 Gebruik uitsluitend bestanden van het mimetype gif,jpg of png 
 !exit
!endif

!if $error=bad_size
 Het plaatje is te groot of te klein.<br>
 Kies het formaat tussen  $(sizemin)x$(sizemin) en $(sizemax)x$(sizemax).
 !exit
!endif

!if $error=unknown_size
    Het formaat van het plaatje is onbekend .
 !exit
!endif

!if bad_data=$error
    Ik kan de opgestuurde waarden niet evalueren...tiep foutje?
 !exit
!endif

!msg $error

