#! /bin/sh

cd `dirname $0`

echo "<p>
!! This file is automatically generated! Do not edit by hand.
Each command takes one line.<p>
In the following table, <tt>[color]</tt>
may be either a color name, or 3 integers between 0 and 255, separated by commas,
for the values of red,green,blue.
<p>\$table_header
<caption>Drawing commands</caption>
\$table_hdtr<th colspan=5>Name and syntax
\$table_hdtr<th colspan=2>Synonymes
<th colspan=3>Meaning</th></tr><tr><td><td colspan=5>
"

awk 'BEGIN {a=10}
	substr($0,1,1)==":" {a=0}
	{a++}
	a==1 {print "$table_tr<td colspan=5 nowrap><tt>"substr($0,2)"</tt></td></tr>"}
	a==2 {print "$table_tr<td colspan=2><tt>"$0"&nbsp;</tt></td>"}
	a==3 {print "<td colspan=3>"$0"</td></tr><tr><td colspan=5>"}
	' commands

echo "\$table_end<p>"

