#!/bin/sh
check(){
    cmp --quiet $f.gif targets/$f.gif
    case "$?" in
	0) echo "OK, test $f passed."
	   ok=$((ok+1))
	   ;;
	1) echo "FAIL: images differ with test $f"
	   nok=$((nok+1))
	   ;;
	2) echo "FAIL: something is wrong with $f, maybe some missing file?"
	   exit 1
	   ;;
	*) echo "BAAAD! this should never happen!"
	   exit2
	   ;;
    esac
}

#----------------- INITIALISATIONS ------------------------
ok=0
nok=0

rm *.gif

#------------------- TESTS ---------------------------------
echo "---------- TESTING FLYDRAW --------------"

f=straightLine
cat << EOF | ../flydraw $f.gif
new 100,100
linewidth 3
line 0,0,99,99,red
EOF
check

f=dashedLine
cat << EOF | ../flydraw $f.gif
new 100,100
linewidth 3
dline 0,0,99,99,red
EOF
check

f=markeyDiffraction
cat << EOF | ../flydraw $f.gif
new 500,300
fpoly grey, 360,10,490,30,490,290,360,270
fpoly grey, 200,10,270,20,270,290,200,280
fpoly white, 232,45,238,49,238,249,232,245

frect 10,115,70,155,skyblue
fellipse 10,135,20,40,skyblue
arc 10,135,20,40,270,90,black
frect 70,125,90,145,skyblue
fellipse 88,135,10,20,skyblue
arc 88,135,10,20,270,90,black
line 70,125,90,125,black
line 70,145,90,145,black
line 70,125,70,145,black
line 90,125,90,145,black
fellipse 70,135,20,40,skyblue
arc 70,135,20,40,270,90,black
line 10,115,70,115,black
line 10,155,70,155,black

dline 420,130,420,100,black
dline 440,139,440,109,black
dline 236,135,415,130,green
dline 236,135,445,139,green
arrow 430,115,420,113,6,black
arrow 430,115,440,117,6,black
text black,430,100,medium,d
arrow 300,100,333,130,10,black
text black,295,95,medium, angle u
arc 336,132,12,12,0,60,black
fellipse 425,135,25,8,green
fellipse 445,137,10,6,green
fellipse 455,139,10,5,green
fellipse 465,141,10,4,green
fellipse 475,143,10,3,green
fellipse 405,133,10,6,green
fellipse 395,131,10,5,green
fellipse 385,129,10,4,green
fellipse 375,127,10,3,green

arrow 210,60,232,70,10,black
arrow 260,85,237,75,10,black
text black,220,45,medium, a
text black,25,130,medium, laser
text black,150,20,medium, fente
text black,400,20,medium, ecran
text black,350,265, medium, D
linewidth 3
arrow 90,135,170,135,15, green
line 169,135,236,135,green
arrow 340,270,270,270,15, black
arrow 360,270,490,270,15, black
EOF
check

    
#---------------------- SUMMARY -----------------------
echo "------- END OF TEST FOR FLYDRAW ---------"
echo "Tests passed: $ok"
echo "Tests failed: $nok"
echo "-----------------------------------------"

#------------- Return non-zero value if failed --------
if [ "$nok" -gt 0 ]; then
    exit 1
fi

