!! ----------------------------------------     ce fichier est une copie intégrale du fichier form.phtml du module home.
!! ---------

<p>
<a name="searchform" id="searchform"></a>
!set wims_ref_anchor=#searchform
!form new
<input type=hidden name=module value=home>

$wims_accessright
!if $wims_accessright!=$empty
 <table border=0 cellpadding=0 cellspacing=0 bgcolor="$bgcolor2">
 !set bgcolort=#808080
 <tr>
 !if $search_package=bases/site
  <td bgcolor="$bgcolort"> <small>$search_package&nbsp;</small></td>
 !else
  <td><small>
  !href cmd=new&search_package=bases/site bases/site
  &nbsp;</small></td>
 !endif
 !set acr=!words2items $wims_accessright
 !for d_ in $acr
  !if $search_package=$d_
   <td bgcolor="$bgcolort"> <small>$d_&nbsp;</small> </td>
  !else
   <td><small>
   !href cmd=new&search_package=$d_ $d_
   &nbsp;</small></td>
  !endif
 !next d 
 </tr></table>
!endif
 <div style="background-color:$wims_ref_bgcolor;" class="wims_search_engine" >
 <input type=submit value=$N_Search class="wims_home_button">
 <input size=20 name=search_keywords value="$search_keywords" class="wims_home_form">
 $N_within
!formselect search_category list $slist prompt $plist
!if $s_keywords!=$empty or $gotcnt>0
 !href session=$wims_session.1&list=clear $N_clear
 !if $has_browse=yes

 !endif
!endif
!if $has_browse=yes and $wims_theme_version=0
 !href module=adm/browse&$browse_parm $N_browse
!endif
</div></form> <p>

!set srchl=$search_keywords
!reset search_category, search_keywords

