<!-- adm/search_engine/form.phtml -->

!default search_lang=$lang
!set wims_ref_anchor=#searchform

!read adm/search_engine/completion.phtml

<div class="wims_search_engine" id="searchform">

!set wims_form_method=post
!form new
<input type="hidden" name="module" value="home" />

!if $wims_accessright!=$empty
!read adm/search_engine/search_accessright.phtml
!endif

 <div class="wimscenter wims_search_engine">
  <ul class="inline">
  <li>
   $name_search_engine
  </li><li>
 !set wims_ref_class=wims_button_help
!href module=adm/light&phtml=search_engine.phtml.$lang $name_search_help
  </li></ul>
 <ul class="inline">
 <li>
 <input type="submit" value="$N_Search" />
 <br />
  <input size="20" name="search_keywords" value="$search_keywords" class="wims_home_form multicomplete" />
 </li>
 <li>
 !formselect search_category list $slist prompt $plist
 <br />
!!-- choice -->  
!default search_and=no
!formselect search_and list yes,no prompt $name_search_and
!!-- choice -->
</li>
<li>
 !!-- language -->  
!set L_language=!words2items $wims_site_languages
!formselect search_lang list $L_language
  !!-- end language -->
 </li>
</ul>
</div>

!formend

</div> 
<!-- end adm/search_engine/form.phtml -->
!set srchl=$search_keywords
!reset search_category, search_keywords
