!!# Si les librairies Jquery sont chargees, on affiche un double curseur.
!default search_level_from=1
!default search_level_to=$levelcnt

!!<fieldset class="property_fields blockcenter">
 !! <legend>name_bounded_search$name_bounded_search</legend>
<div class="field box">
      <label>$wims_name_level</label>
      <input type="hidden" id="search_level_from" name="search_level_from" value="$search_level_from" />
      <input type="hidden" id="search_level_to" name="search_level_to" value="$search_level_to" />
      <div class="slider" id="slider_level" style="width:70%;margin-right:auto;margin-left:auto"></div>
</div>

!!</fieldset>
<script type="text/javascript" src="scripts/js/bower_components/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.js"></script>
<link rel="stylesheet" href="scripts/js/bower_components/jquery-ui-slider-pips/dist/jquery-ui-slider-pips.min.css" />
<link rel="stylesheet" href="themes/_css/jquery-ui-slider-pips.custom.css" />
<style type="text/css">
 #slider_level .ui-slider-range {background: $wims_ref_bgcolor;}
 .ui-slider-pips .ui-slider-pip-selected-1, .ui-slider-pips .ui-slider-pip-selected-2
  {color: $wims_ref_bgcolor;}
</style>
<script type="text/javascript">
/*<![CDATA[*/ jQuery(function(jq){
var niveaux = new Array($levelcnt);
!set levelcnt=!itemcnt $levels
!for i=1 to $levelcnt
  !ifval $(levels[$i+1])-$(levels[$i])>1
niveaux[$(levels[$i])]='$(name_wims_levels[$i])&rarr;';
  !else
niveaux[$(levels[$i])]='$(name_wims_levels[$i])';
  !endif
!next
jq('#slider_level')
    .slider({min: 1,
             max: niveaux.length-1,
             range: true,
             values: [ jq( "#search_level_from" ).val(), jq( "#search_level_to" ).val() ],
             slide: function( event, ui ) {
        jq( "#search_level_from" ).val(ui.values[0]);
        jq( "#search_level_to" ).val(ui.values[1]);
      }
    })
    .slider('pips',
           {rest: "label",
           labels: niveaux});
});/*]]>*/
</script>
