!set name_institution=naam van het instituut
!set name_description=naam van de klas
!set name_supervisor=naam van de supervisor
!set name_email=emailadres
!set name_password=aanmeldings wachtwoord
!set name_passsup=supervisor's wachtwoord
!set levelid=E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,U1,U2,U3,U4,U5,G,R
!set leveldesc=Lagere school klas 1,Lagere school klas 2,Lagere school klas 3,Lagere school klas 4,Lagere school klas 5,Lagere school klas 6,Middelbare school klas 1,Middelbare school klas 2,Middelbare school klas 3,Middelbare school klas 4,Middelbare school klas 5,Middelbare school klas 6,Universiteit jaar 1,Universiteit jaar 2,Universiteit jaar 3,Universiteit jaar 4,Universiteit jaar 5,Graduate,Research

!set nblevel=19
!! !itemcnt $levelid
!set classname=<b><font color=green>$description</font></b> van <b><font color=green>$institution</font></b>

!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!if $Cltype iswordof 2 4
    !if $Cltype=2
	!set name_classe=een groep klassen
	!set name_sup=van de docent/administateur
	!else
	!set name_classe=een portaal
	!set name_sup=van de administateur
    !endif
    !set name_classes=de $name_classe
    !set name_classess=een $name_classe
    !set name_classesss=van de $name_classe
    !set name_classessss=De $name_classe
!else
    !set name_classe=klas
    !set name_classes=de $name_classe
    !set name_classess=een $name_classe
    !set name_classesss=van de $name_classe
    !set name_classessss=De $name_classe
    !set name_sup=van de docent
!endif

!distribute lines Doorgaan\
  Herhaal deze procedure.\
  Oprichten van een virtuele klas, groep klassen, school of  instituut\
  Nom de l'établissement\
au plus\
au moins\
  uitsluitend voor experts\
  caractères\
  Revenir au début de l'opération.\
  Kies hier het soort virtuele_ruimte dat U wilt aanmaken\
  entre 4 et 16 caractères, chiffres ou lettres sans accent\
 into name_continue,name_again,title,name_Name_portal,name_atmost,name_atleast,name_expert,\
   name_characters,name_comeback,name_choose,name_warningpass
   
!if $regpolicy=file
    !set noright=(U bent hiertoe niet bevoegd.)
 !else
    !set noright=(alleen de sitemanager is hiertoe bevoegd.)
 !endif
 
!set name_regpolicy=!nosubst L'opération de création $name_classesss ne peut aboutir que \
   si vous fournissez une adresse électronique correcte et accessible en ce moment même.
   
!set name_help1=Ce mot de passe vous permettra d'accéder à votre $name_classe en tant\
  que responsable. Vous devez être le seul à le connaître.

!set name_help2=Le mot de passe $name_classesss sera exigé lors de l'inscription\
 des participants de la classe ; vous pouvez donc le diffuser auprès\
  de vos étudiants/élèves. 
  
!set name_help3=Le mot de passe $name_classesss sera exigé lors de l'inscription\
 des enseignants $name_classesss ; vous ne devez pas le diffuser auprès de vos étudiants/élèves. 

!distribute lines C'est la date à laquelle votre classe sera automatiquement archivée.\
  Limite du nombre de participants de votre $name_classe\
  Accès sécurisé\
  Facultatif\
  Noms des postes à partir desquels vous effectuerez les opérations sensibles sur votre $name_classe.\
  Dit is een &eacute;&eacute;nmalige code, en is nergens anders voor te gebruiken !\
  Code van $name_classe\
  into name_help_date,name_help_limit,name_secure,name_optional,name_host,name_warning_code,name_code

 !exit
