<p><center><h1>Helaas</h1></center> <p>
Het aantal klassen op deze WIMS-server <font color=red>$httpd_HTTP_HOST</font>
heeft zijn maximum reeds bereikt.
<br> 
Hierdoor is het aanmaken van een nieuwe virtuele ruimte geweigerd<p>

U kunt een email sturen naar de
!mailurl $wims_site_manager site manager\
WIMS@$httpd_HTTP_HOST aanmaken van klassen
 en deze vragen om handmatig een klas voor U te maken.
 <p>

U kunt natuurlijk op elke andere WIMS server ,die U als docent accepteerd, een klas aanmaken.
<br>
Verder kun U de 
<a href="http://wims.unice.fr/download/wims"> WIMS software</a> downloaden en gewoon zelf een server installeren.

