!! This file can contain contents which go to the end of the page.

!if $wims_user=supervisor
!! <p>
!! Vous pouvez
!! !href module=adm/createxo&existing=$thisexo modifier
!! ou
!! !href module=adm/createxo&delete=$thisexo&deltitle=$title effacer
!! cet exercice de votre classe.
!!<p>
 !set wims_menu_items=!append line exomodify,1,module=adm/createxo&existing=$thisexo\
 exoerase,1,module=adm/createxo&delete=$thisexo&deltitle=$title\
 to $wims_menu_items
!else
 !if ..*/$wims_user. isin ..*/$thisexo
 !! Vous pouvez
 !! !href module=adm/createxo&existing=$thisexo modifier
 !! cet exercice.
  !set wims_menu_items=!append line exomodify,1,module=adm/createxo&existing=$thisexo\
  to $wims_menu_items
 !endif
!endif

