!set proc=oef
!header

!if $wims_class=$empty
 Ce module est un module interne à une classe virtuelle. Comme vous n'êtes
 pas connecté en tant qu'un membre de cette classe, vous n'avez
 pas le droit d'y accéder. Désolé.
 <p><center>
 !href $ Retour à wims
 </center> <p>
 !exit
!endif

Ce module recueille les exercices interactifs
de <font color=blue>$wims_classname</font>
de <font color=blue>$wims_institutionname</font>, qui sont créés dans la
classe.
!if $wims_user=supervisor
 !href module=adm/createxo Cliquez ici
 pour en créer un autre.
!endif

!read oef/intromenu.phtml
!tail

