!set email=!trim $email
!set author=!trim $author

!if $author!=$empty
 Autor d'aquest exercici:
 !if $email!=$empty
  !mailurl $email $author
.
 !else
  $author.
 !endif
!endif
!if $solution!=$empty and $hint!=$empty
 Aquest exercici conté un consell i una explicació de la solució.
!endif
!if $solution!=$empty and $hint=$empty
 Aquest exercici té una explicació de la solució però no consell..
!endif
!if $solution=$empty and $hint!=$empty
 Aquest exercici conté un consell però no una explicació de la solució.
!endif
!if $solution$hint=$empty
 Aquest exercici no té ni explicació de la solució ni consell.
!endif
Enllaç per aquest exercici: <br>
!set exolink=$wims_ref_name?module=$module&+cmd=new&+exo=$thisexo
<a href="$exolink">$exolink</a> <br>
Enllaç per la configuració actual: <br>
!if $module_init_parm!=$empty
 !set exolink=$wims_ref_name?module=$module&+cmd=new&+$module_init_parm
!else
 !set exolink=$wims_ref_name?module=$module&+cmd=new
!endif
<a href="$exolink">$exolink</a>
<p>
Informació sobre aquesta col·lecció d'exercicis. <p>
$module_about
<p>
El copyright d'aquests exercicis pertany als seus respectius autors.

!changeto NEWS.phtml
