!nocache
!if $oef_test=yes
 !set renewlink=cmd=next&retest=again
 !!$header_js
 !goto tester
!else
 !set init_parm=!translate + to $ $ in $module_init_parm
 !set init_parm=!replace internal $\
$ by ; in $init_parm
 !set renewlink=cmd=renew&worksheet=$worksheet&$init_parm
!endif

!if $printing=yes
 !changeto oef/print.phtml
!endif

!if $title!=$empty
 !set module_title=$title
 !set module_author=$author
 !set module_address=$email
!endif

!if 0$delay2>0 and $status!=$empty
 !set now_=$wims_nowseconds
 !read js/chrono.phtml $[max(0,$delay1-($now_-$starttime))]
!endif
!set wims_html_header=!append line $header_js to $wims_html_header
!set wims_html_header=$oefcss\
$wims_html_header

!header1
<h1 class="oeftitle">$title</h1>

!if $module_checkdata!=yes
 !read oef/$module_language/nodata.phtml
 !goto end
!endif

!if $title=$empty
 Aquest mòdul és un agrupament d'exercicis. Aparentment l'has demanat
 sense precisar quin exercici vàlid vols fer. Pot ser que hagis clicat
 sobre un enllaç incorrecte, o per un error al software.
 <p><center>
 !href module=$module Intenta tornar a començar
 , or
 !href $ abandonar
 . </center>
 !goto end
!endif

!if 0$delay1>0 and $status!=$empty
 <p><form target="#" name=chrono><center>
 <table border=2 bgcolor="$wims_ref_bgcolor"><tr><td>
 &nbsp;<b><font color=red>Atenció!</font></b>
 !if $qnum>1
  Aquestes sèries d'exercicis tenen un temps limitat.
 !else
  Aquest exercici té el temps limitat.
 !endif
 <input size=4 name=clock readonly onFocus="this.blur()";>
 </table>
 </center></form> <p>
!endif

:tester
!read oef/present.phtml
<center><hr width="50%"></center>

!if $cmd=hint
 !read oef/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read oef/msg.phtml
  <center><hr width="50%"></center>
 !endif
 !read oef/form.phtml
 <p>
 !if $hint!=$empty and $givehint>0
  !href cmd=hint Consell
.
 !endif
 !if $help!=$empty
  !href cmd=help Ajuda
.
 !endif
 !if $qnum<=1
  !href $renewlink Renova l'exercici
.
 !else
  Aquest és l'exercici número $[$reply_cnt+1] d'una sèrie de $qnum exercicis.
  !href $renewlink Abandonar la sèrie
.
 !endif
!else
 !if $error!=$empty
  !read oef/msg.phtml
  <center><hr width="50%"></center>
 !endif
 !read oef/answer.phtml
 <p>
 !if $status!=$empty
  Aquest és l'exercici número $reply_cnt d'una sèrie de $qnum exercicis. <p>
  !href cmd=next Continuar la sèrie amb el següent exercici
, o
  !href $renewlink abandonar la sèrie i demanar-ne una de nova
. (Has d'arribar al final de la sèrie si vols obtenir una nota.)
 !else
  !if $qnum>1
   Has acabat una sèrie de $qnum exercicis, amb una nota de
   $module_score sobre 10.
   !ifval $module_score>9.8
    Enhorabona!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (Has estat penelitzat per excedir-te del temps límit.)
   !endif
   <p>
   !href $renewlink Un altre
.
   !if $wims_sheet=$empty
    !href exo_Intro
.
   !endif
  !else
   Has obtingut una nota de $module_score sobre 10.
   !ifval $module_score>9.8
    Enhorabona!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (Has estat penalitzat per excedir-te del temps límit.)
   !endif
   <p>
   !href $renewlink Un altre
.
   !if $wims_sheet=$empty and $oef_test!=yes
    !href exo_Intro
.
   !endif
  !endif
 !endif
!endif

!if $replydefaulted=yes
 <p> <small>
 En el mode d'elaboració s'inclouen per defecte les respostes correctes en els camps de resposta.
 </small>
!endif

!read ./endhook.phtml
!!!if $wims_user=supervisor and exam notin $session and \
!!	..classes/ notin ..$module and ..adm/ notin ..$module and \
!!	..devel/ notin ..$module and \
!!	GNU isin $module_copyright and \
!!	_check notin $session and \
!!	$class_importation!=no
!! <p>
!! !href module=adm/createxo&existing=$thisexo&catmodule=$module Importar
!! aquest exercici a la teua classe (on tu pots modificar-lo).
!!!endif
:end

!tail

