
!if empty_out iswordof $error
 Your code did not give any output. Please correct it.
 !if $m_reply_err!=$empty
  <pre><span class="wims_warning">$m_reply_err</span></pre>
 !endif
 !exit
!endif

!! empty_data bad_data double_reply  are in html/msg.phtml.fr - suppress on test

!if bad_answer iswordof $error
 !if illegalname iswordof $test
  Your code contains illegal name <span class="tt">$illegal_name</span>. Please correct.
  !exit
 !endif
 !if lengthoverflow iswordof $test
  Your code has exceeded the length limit. Please rewrite it.
  !exit
 !endif
 Your reply
 <span span class="tt">$bad_value</span>
 !if unknownword iswordof $test
  !set w=!word 3 of $test
  is not understandable: the word <span class="tt">$w</span>
  is unrelated to this problem or is not allowed.
  Please correct or choose a simpler sentence.
  !exit
 !endif
 !if nocompute iswordof $test
  is not allowed: please carry out the computation yourself, and
  submit the resulting value.
  !exit
 !endif
 !if nocomputecomplex iswordof $test
   is not allowed.
   Please give the complex number in standard rectangular form
   <span class="tt"> a + b i </span>
   where
   <span class="tt">a</span>
   and
   <span class="tt">b</span>
   are computed, and submit the resulting value (for example,
    <span class="tt"> -1 + 2 i</span> or <span class="tt"> 1 - 2 i</span>).
   !exit
 !endif
 !if badform iswordof $test
  is not written as required. Please rewrite it in the correct form.
  !exit
 !endif
 !if notunit iswordof $test
  is only a number: please precise the unit in your answer.
  !exit
 !endif
 !if bad_variable iswordof $test
   is not understandable. It should contain extra variables.
   !exit
 !endif
 is not understandable.
 Please correct the error and resubmit your reply.
 !exit
!endif

!if bad_exo iswordof $error
 !for j=1 to 50
   !if bad_exo $j isin $error
     !set whichexo=!nosubst (the good answer for the question $j\
     <span class="tt">$(replyname$j)</span>\
     is invalid)
     !!goto end_bad
     !break
   !endif
 !next
:end_bad
 Due to an error in this exercise $whichexo, it is impossible to test the
 correctness of your answer. The only solution for you is to change the
 exercise; sorry.
 <p>
 Please
 !if $email!=$empty
  !mailurl $email contact the author
 !else
  contact the author
 !endif
 of the exercise if you want to report the error.
 </p>
 !exit
!endif

!if too_many_print iswordof $error
 Your requests for printable versions are excessive.
 !exit
!endif

!if chemclick_empty_data iswordof $error
 You have selected no atom or bond. Look at the help.
 !exit
!endif

!if chemdraw_empty_data iswordof $error
 You have not modify the applet. Please complete it.
 !exit
!endif

!msg $error
