
!form reply
<input type=hidden name=job value=$job>
$table_header
!if $login=$empty
 <caption>新的$wims_read_parm</caption>
!else
 <caption>$wims_read_parm 帐户属性 <tt>$login</tt></caption>
!endif
$table_tr<td align=right>登录名:</td><td>
!if $login=$empty
 <input size=30 name=login value="">
!else
 <tt>$login</tt>
!endif
$table_tr<td align=right>
密码:
<td><input type=password size=30 name=pass value="">
$table_tr<td align=right>
重复密码:
<td><input type=password size=30 name=pass2 value="">
$table_tr<td align=right>
名:</td>
<td><input size=30 name=firstname value="$firstname">
$table_tr<td align=right>
姓:</td>
<td><input size=30 name=lastname value="$lastname">
$table_tr<td align=right>
电邮地址:</td>
<td><input size=30 name=email value="$email">
$table_tr<td align=center colspan=2>
<input type="submit" name="confirm" value="提交">
&nbsp;
<input type="submit" name="cancel" value="取消">
$table_end
</form>

