!if $wims_read_parm=help
!if $lang=cn
 \special 方法 "help" 接受两个参数.
第一个参数是关键词, 被放在帮助文本的变量 \help_subject 里.
第二个是显示在链接点的文字.
 
如果 \special{help} 被放在练习的陈述或反馈中,
帮助将使用弹出的形式, 与模块中通常的帮助链接不同.

所有的帮助内容应该被放在oef的源码中.
不存在模块水平的帮助, 否则oef文件的独立性会由于帮助而被破坏.
如果你有几个练习共享同一个帮助文本, 你可以考虑使用 cpp.
<p>

<b>例:</b>
 <pre>
 \title{猜猜看}
 \statement{ 猜一个英文词 :  
   \special{help test1,第一个提示}
 }
 \answer{1}{Monk}
 \help{
   这里是帮助: 帮助主题=\help_subject
   <p>
   \if{\help_subject issametext or \help_subject issametext none}{
     \special{help test0,这里}
   }
   \if{\help_subject issametext test1}{
     第一个字母是 <b>M</b>. 你可以看到另一个提示
     \special{help test2,在这里}
   }
  \if{\help_subject issametext test2}{这是第二个提示. 
    第二个字母是 <b>o</b>
   }
  \if{\help_subject issametext test0}{这里是  
    \special{help test1,第一个提示}, \special{help test2,第二个提示}
   }
 }
 </pre>

 !exit
!endif
 The \special method "help" accepts two parameters. The first is a key 
 which will be put to the variable \help_subject within the help text, 
 and the second is the text of the link.
 
 If the \special{help} is put into statement or feedback of an exercise, 
 the help will use popup mode, unlike the usual "help" link in the module.

 All the help content should be put into the oef source. No facility is 
 planned for module-level help, as the principle is that the independency 
 of oef files should not be destroyed by helps. However, if you have 
 several exercises sharing the same help texts, you may consider using cpp.
<p>

<b>Example:</b>
 <pre>
 \title{Guess}
 \statement{ Guess a word :  
   \special{help test1,First clue}
 }
 \answer{1}{Monk}
 \help{
   This is the help: help subject=\help_subject
   <p>
   \if{\help_subject issametext or \help_subject issametext none}{
     \special{help test0,here}
   }
   \if{\help_subject issametext test1}{
     The first letter is <b>M</b>. You can find another clue
     \special{help test2,here}
   }
  \if{\help_subject issametext test2}{Here is the second clue. 
    The second letter is <b>o</b>
   }
  \if{\help_subject issametext test0}{Here is the  
    \special{help test1,clue 1}, \special{help test2,clue 2}
   }
 }
 </pre>

 !exit
!endif
!set prompt=!item 2 to -1 of $wims_read_parm
!default prompt=$wims_read_parm
!if $prompt != $empty
 !if $cmd=help
  !href cmd=help&special_parm=$(wims_read_parm[1]) $prompt
 !else
  !href target=wims_mhelp cmd=help&special_parm=$(wims_read_parm[1]) $prompt
 !endif
!endif

