
!if $job2!=first
 !changeto arch/$job2.phtml
!endif

U kunt een backup van een klas maken in de volgende formaten:
!href cmd=reply&job=arch&job2=download&selection=all&format=zip zip
,
!href cmd=reply&job=arch&job2=download&selection=all&format=tgz tgz
 of
!href cmd=reply&job=arch&job2=download&selection=all&format=tar.gz tar.gz
 formaat.
<small>[
!href cmd=help&special_parm=download help
 ]</small>
<p><hr> <p>

!set wims_form_method=file
!form reply
<input type=hidden name=job value=arch>
<input type=hidden name=job2 value=upload>
Teneinde een klas te herstellen met een <input type=submit value=upload>
backup-archief, geef daarvoor hier de backup-archief naam:
<p>
<input type=file name=wims_deposit size=50>
<small>
!href cmd=help&special_parm=upload Help
</small>
<p>
(U wordt bij het daadwerkelijk terugzeten verzocht het een en ander te bevestigen)
</form> <p>

