
!if $job2!=first
 !changeto arch/$job2.phtml
!endif

U kunt een backup van een klas maken in de volgende formaten:
!href cmd=reply&job=arch&job2=download&selection=all&format=zip zip
,
!href cmd=reply&job=arch&job2=download&selection=all&format=tgz tgz
  $wims_name_or
!href cmd=reply&job=arch&job2=download&selection=all&format=tar.gz tar.gz
 .
<small>[
!href cmd=help&special_parm=download $wims_name_help
 ]</small>
<p><hr> <p>

!set wims_form_method=file
!form reply
<input type=hidden name=job value=arch>
<input type=hidden name=job2 value=upload>
Teneinde <input type=submit value=upload> 
een klas te herstellen met een backup-archief, geef daarvoor hier de 
backup-archief naam&nbsp;:
<p>
<input type=file name=wims_deposit size=40>
<small>
!href cmd=help&special_parm=upload $wims_name_help
</small>
<p>
(U wordt bij het daadwerkelijk terugzeten verzocht het een en ander te bevestigen)
</form> <p>

