
Dit configuratie hulpmiddel is alleen beschikbaar voor een "secure host"

<p>
Omdat er nog geen "secure hosts" voor deze klas zijn gedefinieerd, moeten we Uw identiteit
controleren door <b>nu</b> een geheime code te sturten naar het opgegeven emailadres.<br>
Kontroleer dus Uw email, en type de code in:
<p>
!form reply
<center><input size=12 name=repcode>
<input type=submit value=OK>
</form></center> <p>

<b>Opmerking</b>
Het verdient aanbeveling om "secure hosts" te definieren
 

