
!form renew
 <input type=hidden name=job value=grestrict>
 Hier kunt aangeven welke (netwerk)computer-adressen
 mee mogen doen aan Uw virtuele klas en met het behalen van cijfers. 
 Deze instellingen blijven van kracht, en hebben een hogere prioriteit dan
  de instellingen van de individuele werkbladen
 <p>
 <table border=0>
 <tr><td align=right>Toegestane Adressen:
 <td><input size=35 name=allow value="$allow">
 <tr><td align=right>Uitgezonderd:
 <td><input size=35 name=except value="$except">
 </table> <p>
 <input type=submit name=save value=Save>&nbsp;&nbsp;&nbsp;
 <input type=submit name=abandon value=Abandon>
</form>

<p>
Je kunt een of meerdere woorden intypen in het invulveld.
De server zal elk ingevuld adres controleren op hostname en ipadres.
Zelfs al is de ingevulde naam een "sub-string" van de hostname of ip-adres
<p>
<small><b>Hint.</b> In het "Toegestane Adressen" veld, kun je ook tijd-restricties aanbrengen
voor het behalen van cijfers, door de woorden: 
<font color=blue><b>
<tt>&gt;yyyymmdd.hh:mm</tt></b></font>
(begin tijd) en/of
<font color=blue><b>
<tt>&lt;yyyymmdd.hh:mm</tt></b></font>
(eind tijd). <br>
De genoemde tijden moeten natuurlijk wel worden genoteerd in de <em>locale tijd van de Server</em> en moeten worden gescheiden van de andere "woorden" door spaties

</small>


