!if $supertype=4 and $classdepth<=3
<p><center>
 !href module=adm/class/gateway Instituut administratie
</center>
!set wims_menu_items=!append line struct,1,adm/class/gateway\
to $wims_menu_items
!endif

!form reply
<input type=hidden name=up_job value=list>
$table_header
$table_tr<td align=right>Naam van dit instituut
<td colspan=3>
!if $supertype notin 24 or $classdepth=1
 <input size=50 name=up_institution value="$class_institution">
!else
 $class_institution
!endif
$table_tr<td align=right>Naam van de klas
<td colspan=3>
<input size=50 name=up_description value="$class_description">
$table_tr<td align=right>Toegestane netwerkadressen
<small>
!href cmd=help&special_parm=config&special_parm2=secure help
 </small>
<td colspan=3>
<input size=50 name=up_secure value="$class_secure">
$table_tr<td align=right>Docent
<small>
!href cmd=help&special_parm=config&special_parm2=supervisor help
 </small>
<td colspan=3>
<input size=40 name=up_supervisor value="$class_supervisor">
$table_tr<td align=right>Email docent
<small>
!href cmd=help&special_parm=config&special_parm2=email help
 </small>
<td colspan=3>
<input size=40 name=up_email value="$class_email">
$table_tr<td align=right>Optioneel
<small>
!href cmd=help&special_parm=config&special_parm2=option help
 </small>
<td colspan=3>
<input size=40 name=up_option value="$class_option">
!if $wims_supertype!=4 or $class_typename!=class
$table_tr<td align=right>
Modtool Account
<small>
!href cmd=help&special_parm=config&special_parm2=modtoolchg help
</small>
</td><td colspan=3>
!set modtoolchg=1
!formcheckbox modtoolchg list 0 prompt Change
</td></tr>
!endif
$table_tr<td align=right colspan=2>Netwerk security niveau
<small>
!href cmd=help&special_parm=config&special_parm2=lock help
</small>
</td><td colspan=3>
!set up_lock=$class_lock
!default up_lock=0
!formselect up_lock list 0,2,3,4,5,6,7
</td>
$table_tr<td align=right>Taal van de klas
<small>
!href cmd=help&special_parm=config&special_parm2=lang help
 </small>
<td>
!set up_lang=$class_lang
!set langs=!words2items $wims_site_languages
!formselect up_lang list $langs
<td align=right>
Les niveau
<small>
!href cmd=help&special_parm=config&special_parm2=level help
 </small>
<td>
!set up_level=$class_level
!formselect up_level list $levellist
$table_tr<td align=right>Maximum aantal deelnemers
<small>
!href cmd=help&special_parm=config&special_parm2=limit help
 </small>
<td><input size=5 name=up_limit value="$class_limit">
<td align=right>Verloop datum
<small><b>yyyymmdd</b></small>
<small>
!href cmd=help&special_parm=config&special_parm2=expiration help
 </small>
<td>
!if $class_type notin 13
 <input size=8 maxlength=8 name=up_expiration value="$class_expiration">
!else
 <tt>$class_expiration</tt>
!endif
$table_tr<td align=right>Aantal bewaarde oefeningen

<small>
!href cmd=help&special_parm=config&special_parm2=exolog help
 </small>
!default class_exolog=0
<td><input size=3 name=up_exolog value="$class_exolog">
<td align=right>Aantal bewaarde digi-toetsen
<small>
!href cmd=help&special_parm=config&special_parm2=examlog help
 </small>
!default class_examlog=$wims_examlog_limit
<input size=3 name=up_examlog value="$class_examlog">
<td>zichtbaar voor studenten
<small>
!href cmd=help&special_parm=config&special_parm2=examshow help
 </small>
!default class_examshow=yes
!set up_examshow=$class_examshow
!formselect up_examshow list no,yes prompt No,Yes
!set up_ent=$class_ent
$table_tr<td align=right>Other platform link
<small>
!href cmd=help&special_parm=config&special_parm2=ent help
 </small>
<td colspan=3>
<input size=50 name=up_ent value="$class_ent">
$table_hdtr<td align=center colspan=4>
<input type=submit name=save value=Opslaan>
&nbsp;
<input type=submit name=abandon value=Annuleren>
$table_end <p>
</form>

Andere configuraties:
!href cmd=reply&job=present uiterlijk
.
!href cmd=reply&job=neighbor&job2=first "buurklassen"
.
!href cmd=reply&job=connect&job2=first andere ELO's
.
!href module=adm/class/passwd wachtwoorden
.
!if $classdepth<=1 
 !href cmd=reply&job=authtype Type d'authentification
.
!endif
!href module=adm/forum/mboard&job=config discussie forum
.
!href module=adm/doc documenten
.
!href module=adm/class/motd bericht van de dag
.
!href cmd=reply&job=access toegangsbeleid
.
!href cmd=reply&job=oefdefault OEF default configuratie
.
!if $class_type iswordof 2 3 4
 !href cmd=reply&job=propagate stuur template_setup naar andere klassen
.
!endif
<p>
!href cmd=reply&job=security security management
.
!href cmd=reply&job=arch&job2=first backup en herstel
.
!href cmd=reply&job=clean selectieve opschoning
.
<br>
Actualiseer de index<sup>
!href cmd=help&special_parm=index help
</sup>:
!if $class_type=4
!href cmd=reply&job=index&job2=structure subklassen
,
!endif
!if $class_type=4 or $class_type=2
!href cmd=reply&job=index&job2=teacherlist docenten
,
!endif
!href cmd=reply&job=index&job2=userlist deelnemers
,
!href cmd=reply&job=index&job2=oef oefeningen
,
!href cmd=reply&job=index&job2=doc documenten
.
<p>
!href module=adm/light&phtml=useropts.phtml.$lang Mijn persoonlijke instellingen
.
<p>
Huidige klasse grootte: $du megabytes. (het ingestelde maximum is
$wims_class_quota.)

!reset up_institution, up_description, up_supervisor, up_email, \
	up_lang, up_level, up_limit, up_expiration, up_secure, up_lock,\
	up_option,up_exolog,up_examlog,up_examshow,\
	pr_homepage, pr_bgcolor, pr_refcolor, pr_bgimg, pr_css, pr_theme, pr_theme_icon

