
!set classname=<b><font color=green>$wims_classname</font></b>\
 van <b><font color=green>$wims_institutionname</font></b>
 
!set months=Januari,Februari,Maart,April,Mei,Juni,Juli,Augustus,September,Oktober,November,December

!set title=Configuratie en Onderhoud
!if $job=arch
 !set title=Backup en Herstel
 !goto commun
!endif

!if $job=clean
 !set title=Opschonen van een klas
 !goto commun
!endif

!if $job=neighbor
 !set title=Buurklassen
 !distribute lines Buurklassen<br>definieren\
   Delen van materiaal\
   door u\
   door een ander\
   Wederzijds gedeeld.\
   U deelt.\
   U leent.\
   Wederzijds goedkeuring.\
   Geeft U permissie om te lenen.\
   U heeft permissie om te lenen.\
   Stop de deling\
   Delen\
   Importeer alle deelnemers\
   Lesmateriaal\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3,name_stopsharing,name_share,name_everybodyimport,name_teaching
 !goto commun
!endif

!if $job=connect
 !set title=Verbinding met andere servers / platformen
 !goto commun
!endif

!if $job=access
 !set title=Configuratie toegangsbeleid
 !goto commun
!endif

!if $job2=addshare
 !set title=Delen van lesmateriaal met andere klassen
 !goto commun
!endif

!if $job=grestrict
 !set title=Score restricties
 !goto commun
!endif

!if $job=present
 !set title=Configuratie van het uiterlijk van de virtuele klas
 !goto commun
!endif

!if $job=oefdefault
 !set title=Configuratie voor OEF modules<br>[Online Exercise Format] 
 !goto commun
!endif

!if $job=security
 !set title=Beschikbare beveiligings instellingen voor virtuele Klassen
 !goto commun
!endif

!if $job=authtype
 !set title=Ldap authentification
  !set name_intro_authtype=Kies <tt>ldap</tt> en vul dit formulier in \
  als u een ldap server gebruikt voor authentificatie.
 !goto commun
!endif

:commun
!distribute line Authentificatie\
Persoonlijke instellingen\
Toegangsbeleid\
OEF configuratie\
Buur klassen\
Security management\
Selectieve opschoning\
Actualiseer de index\
Andere servers\
Wachtwoorden\
Andere zones\
Uiterlijk\
Score instellingen,\
Platform adressen,\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items subklassen,deelnemers,oefeningen,documenten,docenten\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers


!distribute lines Toegestane adressen\
   Style sheet\
   Het logo van de klas\
   Positie van het logo\
   links boven, rechts boven
   Style thema van de klas\
   Iconen\
   Lesniveau\
   Toegangsbeleid voor registeren van cijfers\
   Inschrijvings wachtwoord (klasse wachtwoord)\
   Wachtwoord docent\
   Configureer de opslag van toetsresultaten\
   Links naar andere leerplatformen of webpagina's\
   Pagina achtergrond kleur\
   Menu achtergrond kleur\
   Menu link kleur\
   Achtergrond plaatje\
   download een css-style bestand\
   kleuren voor de cijfers (van 0 tot 10)\
   into name_secure,name_css,name_logo,name_position_logo,name_logo_side,name_theme,\
   name_theme_icon,name_level,name_security,name_password,name_supass,name_exolog,name_ent,\
  name_background_color,name_menu_color,name_refmenu_color,name_image,name_css_transfer,name_colorscore

!set name_content_style = U kunt een algemeen stylesheet definieren\
<br>(als <tt>$name_css</tt> op <tt>klas</tt> is gezet)&nbsp;:

!set name_content_style2=of kopieer een stylesheet











