
Configuratie van het uiterlijk van de virtuele klas:
!set wims_form_method=file
!form reply
<input type=hidden name=up_job value=present>
<p>$table_header
$table_tr<td align=right>Het logo van de klas
<small>
!href cmd=help&special_parm=config&special_parm2=logo help
 </small>
<td><input size=45 name=pr_logo value="$class_logo">
$table_tr<td align=right>Positie van het logo
<small>
!href cmd=help&special_parm=config&special_parm2=logo help
 </small>
<td>
!set pr_logoside=$class_logoside
!formselect pr_logoside list left,right prompt links boven, rechts boven
 op de klasse pagina.
$table_tr<td align=right>Homepagina voor leerlingen
<small>
!href cmd=help&special_parm=config&special_parm2=homepage help
 </small>
<td><input size=45 name=pr_homepage value="$class_homepage">
$table_tr<td align=right>Pagina achtergrond kleur
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_bgcolor value="$class_bgcolor">
$table_tr<td align=right>Menu achtergrond kleur 
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_refcolor value="$class_refcolor">
$table_tr<td align=right>Achtergrond plaatje
<small>
!href cmd=help&special_parm=config&special_parm2=bgimg help
 </small>
<td><input size=45 name=pr_bgimg value="$class_bgimg">
$table_tr<td align=right>Styl_thema van de klas
<small>
!href cmd=help&special_parm=config&special_parm2=theme help
 </small>
<td>
!set pr_theme=$class_theme
!formselect pr_theme list $themelist
$table_tr<td align=right>Icones de la classe
<small>
!href cmd=help&special_parm=config&special_parm2=icon $wims_name_help
 </small>
</td><td>
!set pr_theme_icon=$class_theme_icon
!formselect pr_theme_icon list $iconlist
</td></tr>
$table_tr<td align=right>Stylesheet (css) van de pagina's
<small>
!href cmd=help&special_parm=config&special_parm2=css help
 </small>
<td>
!set pr_css=$class_css
!formselect pr_css list $csslist
$table_tr<td align=right valign=middle>Bepaal een klasse stylesheet (css) :
<small>
!href cmd=help&special_parm=config&special_parm2=css help
</small>
<td valign=middle>
stuur het css-style bestand.
<input type=file name=wims_deposit>
<br>
<textarea rows=6 cols=45 name=pr_cssfile>$cssfile</textarea>
$table_tr<td align=center colspan=2>
<input type=submit name=save value=Opslaan>
&nbsp;
<input type=submit name=abandon value=Annuleren>
$table_end <p>
</form>

!reset pr_logo, pr_logoside, pr_bgcolor, pr_refcolor, \
	pr_bgimg, pr_theme, pr_theme_icon, pr_css, pr_homepage, pr_cssfile

