Configuratie van het uiterlijk van Uw Virtuele Klas:

!form reply
<input type=hidden name=up_job value=present>
<p>$table_header
$table_tr<td align=right>Het Klasse-logo
<small>
!href cmd=help&special_parm=config&special_parm2=logo help
 </small>
<td><input size=45 name=pr_logo value="$class_logo">
$table_tr<td align=right>Positie van het Klasse-logo
<small>
!href cmd=help&special_parm=config&special_parm2=algemene logo help
 </small>
<td>
!set pr_logoside=$class_logoside
!formselect pr_logoside list left,right prompt links boven, rechts boven
 op  de klasse homepagina.
$table_tr<td align=right>Homepagina van de leerlingen
<small>
!href cmd=help&special_parm=config&special_parm2=homepagina help
 </small>
<td><input size=45 name=pr_homepage value="$class_homepage">
$table_tr<td align=right>Pagina achtergrond kleur
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_bgcolor value="$class_bgcolor">
$table_tr<td align=right>Menu achtergrond kleur 
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_refcolor value="$class_refcolor">
$table_tr<td align=right>Achtergrond plaatje
<small>
!href cmd=help&special_parm=config&special_parm2=bgimg help
 </small>
<td><input size=45 name=pr_bgimg value="$class_bgimg">
$table_tr<td align=right>Style theme of the class
<small>
!href cmd=help&special_parm=config&special_parm2=theme help
 </small>
<td>
!set pr_theme=$class_theme
!formselect pr_theme list $themelist
$table_tr<td align=right>Style sheet (css) van de  pagina's
<small>
!href cmd=help&special_parm=config&special_parm2=css help
 </small>
<td>
!set pr_css=$class_css
!formselect pr_css list $csslist
$table_tr<td align=right valign=middle>Hier kunt U een klasse stylesheet(css) bepalen:
<small>
!href cmd=help&special_parm=config&special_parm2=css help
</small>
<td valign=middle>
<textarea rows=6 cols=45 name=pr_cssfile>$cssfile</textarea>
$table_tr<td align=center colspan=2>
<input type=submit name=save value=Bewaren>
&nbsp;
<input type=submit name=abandon value=Herstellen>
$table_end <p>
</form>

!reset pr_logo, pr_logoside, pr_bgcolor, pr_refcolor, \
	pr_bgimg, pr_theme, pr_css, pr_homepage, pr_cssfile

