
!if $wims_supertype=2
 !set name_thisclass=het portaal
 !set name_subclasses=subklassen
!else
 !set name_thisclass=de huidige zone
 !set name_subclasses=andere zones
!endif

!if $confirm!=$empty and $propagate!=$empty
 De configuratie is geinstalleerd in de $name_subclasses: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
 U kunt de onderstaande instellingen van 
 $name_thisclass naar alle $name_subclasses sturen: <p>
 
 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="$wims_name_send">
 </form>
!endif
<p>
Attentie: $name_subclasses worden niet 
automatisch veranderd, als de configuratie
van $name_thisclass veranderd.
Deze handeling moet dan herhaald worden.

