!set name_secure=Secure hosts
!set name_colors=Pagina kleuren
!set name_css=Style sheet (css)
!set name_logo=Logo
!set name_theme=Style thema
!set name_level=Lesniveau
!set name_security=Toegestane ipadressen 
!set name_password=Klasse wachtwoord
!set name_supass=Supervisor wachtwoord
!set name_exolog=Opslag limiet voor resultaten van werkbladen en toetsen
!set name_theme_icon=Jeu d'icones
!set name_ent=Links on another plateform
!if $wims_supertype=2
 !set name_thisclass=het protaal
 !set name_subclasses=subklassen
!else
 !set name_thisclass=de huidige zone
 !set name_subclasses=andere zones
!endif

!if $confirm!=$empty and $propagate!=$empty
 De configuratie is geinstalleerd in de $name_subclasses: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
 U kunt de onderstaande instellingen van $name_thisclass naar alle $name_subclasses sturen: <p>
 !for s in $propall
  !if $(name_$s)!=$empty
   !set name_=!replace internal $ $ by &nbsp; in $(name_$s)
   <input type="checkbox" name="propagate" value="$s">$name_&nbsp;
  !endif
 !next s
 <p>
 <input type="submit" name="confirm" value="$wims_name_send">
 </form>
!endif
<p>
Attentie:
$name_subclasses worden niet automatisch veranderd, als de configuratie
van $name_thisclass veranderd.
Deze handeling moet dan herhaald worden.

