
Beschikbare Beveiligings instellingen voor Virtuele Klassen:

<ul>
<p><li>
!href module=adm/class/passwd.$module_language Verander je Wachtwoorden

.

<p><li>Bekijk de 
!href cmd=renew&job=log logfile
&nbsp;van alle onderhoudsactiviteiten van je klas.<br>
Ze moeten natuurlijk allemaal afkomstig zijn van de supervisor van deze klas,
 of de administrator van het portaal

<p><li>Hier kun je een  
!href cmd=renew&job=grestrict restrictie
&nbsp;beleid opzetten, d.m.v. een lijst ip-adressen die toegang hebben tot het cijfer/score-systeem.


<p><li>Andere voor het onderhoud van klassen belangrijke 
!href cmd=renew&job=list Beveiligings 
 instellingen.

</ul>

