!set renewlink=cmd=renew&worksheet=$worksheet&$module_init_parm
!set module_title=$module_title: $title

!header

!if $title=$empty
 Ce module est un groupement d'exercices. Vous l'avez visiblement demandé sans
 préciser un exercice valable que vous voulez faire. C'est soit parce que vous
 avez cliqué sur un lien incorrect, soit à cause d'une erreur du logiciel.
 <p><center>
 !href module=$module Essayez de refaire votre manipulation
 , ou
 !href $ abandonner
 . </center>
 !goto end
!endif

:tester
!read proc/present.phtml

<p><hr width=50%> <p>

!if $cmd=hint
 !read proc/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read proc/msg.phtml
  <p><hr width=50%> <p>
 !endif
 !read proc/form.phtml
 <p>
 !if $hint!=$empty and $givehint>0
  !href cmd=hint Indication
.
 !endif
 !if $qnum<=1
  !href $renewlink Renouveler l'exercice
.
 !else
  Ceci est l'exercice $[$reply_cnt+1] dans une séance qui en compte $qnum.
  !href $renewlink Abandonner la séance
.
 !endif
!else
 !if $error!=$empty
  !read proc/msg.phtml
  <p><hr width=50%> <p>
 !endif
 !read proc/answer.phtml
 <p>
 !if $status!=$empty
  Ceci est l'exercice $reply_cnt dans une séance qui en compte $qnum. <p>
  !href cmd=next Continuer la séance avec l'exercice suivant
, ou
  !href $renewlink abandonner la séance en demandant une autre
. (Vous devez arriver jusqu'à la fin de la séance pour avoir une note.)
 !else
  !if $qnum>1
   Vous avez terminé une séance de $qnum exercices, avec une note de
   $score sur 10.
   !ifval $score>9.8
    Félicitations!
   !endif
   <p>
   !href exo_Again
.
   !if $wims_sheet=$empty
    !href exo_Intro
.
   !endif
  !else
   Vous avez obtenu une note de $score sur 10.
   !ifval $score>9.8
    Félicitations!
   !endif
   <p>
   !href exo_Again
.
   !if $wims_sheet=$empty and $oef_test!=yes
    !href exo_Intro
.
   !endif
  !endif
 !endif
!endif

!read endhook.phtml
:end

!tail

