
$name_h_browse
<ul class="wims_browse_list">
<li>
<div class="wims_widget_box medium_size">

 !href module=$module&cmd=new&job=subject $name_by_subject

<ul class="box_content inline">
!for dom in $Tot_dom
  !set dom_n=!lookup $dom in $dir_lang
  !default dom_n=$dom
  <li>
  !set wims_ref_class=wims_button
  !href module=$module&cmd=new&job=subject&parm=$dom $dom_n
  </li>
!next
</ul>
</div>
</li>
<li>
 !href module=$module&cmd=new&job=level $name_by_level
$ : $name_by_level2
</li>
<li>
 !href module=adm/new&cmd=new&job=new $name_by_date
$ : $name_news
</li>
</ul>
$name_selected
<ul class="wims_browse_list">
 <li>
 !href module=$module&cmd=new&job=type $name_by_type
$ : $name_by_type2
 </li>
<li>
 !href module=$module&cmd=new&job=best $name_introduction
 $ $name_thebest
</li>
!if $lang iswordof fr
<li>
!href module=help/teacher/program $name_french1
$ $name_french2
 </li>
!endif

</ul>
