!if robot isin $session
 <html><body $wims_htmlbody>
 This page is not accessible to robots.
 </body></html>
 !exit
!endif

!set wims_html_onload=!append word window.focus(); to $wims_html_onload
!header1

<div id="wims_title"><h1 class="wims_title">
WWW
Interactive
Multipurpose
Server
</h1>
<h2 class="wims_subtitle">
@ <a href="/">$httpd_HTTP_HOST</a>
</h2>
</div>
!read $job.phtml

!if $job!=home
 <p>
!set wims_menu_items=!append line browse,1,module=$module&cmd=new&job=home\
to $wims_menu_items

!endif

!tail

