
<center><h3>$title</h3></center>

!if $parm=$empty
 $name_domain
$table_header
 !for t in $Tot_dom
 $table_tr  <th colspan=2>$(name_$t)</th>
  !for d in $(tot_dom_$t)
  $table_tr<td>
   !set l_=$(dom_$d)
    !href module=$module&cmd=new&job=$job&parm=$d <b>$(name_$d)</b>
   !if $l_=$empty
    <td>
   !else
    <td>
    !for v in $l_
     !href module=$module&cmd=new&job=$job&parm=$v $(name_$v)
     &nbsp;
    !next v
   !endif
   </tr>
  !next d
 
 !next $t
 $table_end
!else
 $name_available
!set wims_menu_items=!append line other,1,module=$module&cmd=new&job=subject\
  to $wims_menu_items
 <p>$table_header
 !for t in $list
  $table_tr
  <td align=left nowrap><b>$t</b></td>
  !if $has_enc=yes
   <td nowrap><small>
   !href target=wims_ref module=adm/enc&dom=math&job=search&search=$t $name_L
   </small></td>
  !endif
  !set key=$t
  !for i in A,T,P,X,S
   !set cat=$i
   <td nowrap>
   !if $i!=A
   <small>
   !href $search_addr $(name_$i)
   </small>
   !else
   !href $search_addr $(name_$i)
   !endif
  </td>
  !next i

  !next t
 </table> <p>
!endif

