!read adm/title.phtml 3\
$title

!if $parm=$empty
 $name_domain
$table_header
 !for t in $Tot_dom
 $table_tr <th colspan="2">
 !set td=!lookup $t in $dir_lang
 !default td=$t
 $td
 !reset td
 </th></tr>
  !for d in $(tot_dom_$t)
  $table_tr<th>
   !set l_=$(dom_$d)
   !set t_=!lookup $d in $dir_lang
   !default t_=$d
    !href module=$module&cmd=new&job=$job&parm=$d $t_
    </th>
   !if $l_=$empty
    <td>
    !href module=$module&cmd=new&job=$job&parm=$d $t_
   !else
    <td>
    !for v in $l_
    !set t_=!lookup $v in $dir_lang
    !default t_=$v
     !href module=$module&cmd=new&job=$job&parm=$v $t_
     &nbsp;
    !next v
   !endif
   </td>
   </tr>
  !next d
 
 !next $t
 </tr>
 $table_end
 !read graph.phtml $Tot_dom
!else
 $name_available
!set wims_menu_items=!append line other,1,module=$module&cmd=new&job=subject\
  to $wims_menu_items
 $table_header
 !for t in $list
  $table_tr
  !!keep key - use in search_addr.
  !reset key
    !set key=!lookup $t in $dir
    !default key=$t
    !set key_l=!lookup $t in $dir_lang
    !set name_$t=!lookup $t in $dir_lang
    !default name_$t=$t
    !set key=!replace internal _ by $ $  in $t
    !set key=$key,$key_l
    !set more=!lookup $t in $dir
    <th>
    !if $more!=$empty
      !href module=$module&cmd=new&job=$job&parm=$t $(name_$t)
    !else
      $(name_$t)
    !endif
    </th>
  !for i in A,T,P,X,S
   !set cat=$i
   <td >
   !if $i!=A
   <span class="small">
   !href $search_addr $(name_$i)
   </span>
   !else
   !href $search_addr $(name_$i)
   !endif
  </td>
  !next i
 </tr>
  !next t
 </table>
 !read graph.phtml $parm
!endif


