!form reply
Stai per aggiungere tutti gli esercizi del test di autovalutazione
!formselect numsheet list $asheets prompt $listname
in fondo all'esame.<br>
Ogno esercizio sarà aggiunto con peso 1 e avrà come titolo il titolo che ha
nel test.
<center><input type=submit value="Insert"></center>
<input type=hidden name="job" value="cpsheet">
</form>
<p>
!href cmd=reply Torna al tema d'esame
.
!reset numsheet