!if $activetest>0
 Spiacente, questo esame è attivo, quindi non è pi&ugrave; 
 modificabile. Non è possibile cambiare gli esercizi.
 !exit
!endif

!form reply
<input type=hidden name=job value=exo>
<input type=hidden name=exo value=$exo>
<p>$wims_name_Exercise $exo: peso=<input size=5 name=eweight value="$eweight">,
  $wims_name_title: <input size=20 name=ename value="$ename">
<p>
Questo esercizio sar&agrave; scelto (casualmente) in una lista di esercizi
contenuti nei test periodici. Selezionare nella lista che segue i test di
autovalutazione da cui estrarre gli esercizi da inserire in questo tema 
d'esame.
<p>
mostra solo esercizi del test
 <select name="ltsheets" onchange="submit()" value="$ltsheets">
  !if $ltsheets=$asheets
   <option value="$asheets" selected>$name_All</option>
  !else
   <option value="$asheets">$name_All</option>  
  !endif
  !for k in $asheets
   !if $ltsheets=$k
    <option value="$k" selected>
   !else
    <option value="$k">   
   !endif
    !let t=!record $k of  wimshome/log/classes/$wims_class/sheets/.sheets
    $k :
    !line 3 of $t
   </option>
  !next k
 </select>
<p>
!for i in $ltsheets
 !set t=!recordcnt wimshome/log/classes/$wims_class/sheets/.sheet$i
 !for j=1 to $t
  !set r=!record $j of wimshome/log/classes/$wims_class/sheets/.sheet$i
  !distribute line $r into r1,r2,r3,r4,r5,r6
  <input type=checkbox name=echoose value=$i.$j
  !if $i.$j isitemof $echoose
   checked
  !endif
  > $i.$j <b>$r5</b> <small>$r6</small> <br>
 !next j
!next i
<p>
$name_dependency: <input size=40 name=edep value="$edep"> <br>
$name_Options:
!formcheckbox eopt list $optionlist
<br>
<input type=submit value="$wims_name_tosave">
</form>
<p>
!href cmd=reply $name_mainpage
.<p><small>
<b>$wims_name_help</b>. Punteggi "con dipendenza" significa che un candidato deve
  ottenere un determinato punteggio in altri esercizi dell'esame prima di 
  poter affrontare questo. Per esempio,
  <font color=blue><tt>1:50,2:30,3+4+5:60</tt></font>
  significa che il candidato deve ottenere un 50% nell'esercizio 1, un 30%
  nell'esercizio 2, e una media del 60% negli esercizi 3,4,5.
  Opzioni: <ul>
  <li><em>autogen</em> significa che l'esercizio viene generato automaticamente
  anche se l'untente non ci clicca sopra. In questo modo può consultare 
  l'esercizio anche a sessione chiusa. Non raccomandato se non per gli esercizi
  che prevedono una valutazione da parte del docente (cioè che <b>non</b>
  prevedono una valutazione automatica).
  </ul>
</small>


