<b>ATTENZIONE</b>!<p>

Non hai svolto tutti gli esercizi richiesti. Terminare la sessione ora
significa salvare questo punteggio e perdere una delle possibilità
di sostenere l'esame, la prossima volta dovrai infatti
ricominciare da capo.
<p>
Sei sicuro/a di voler smettere ora?
<p><center><font size="+1">
!href cmd=reply&job=scorereg&confirm_end=yes SI
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score NO
</font></center> <p>

!tail
!reset job
