!if $(module_title_$modu_lang)!=
  !set module_title=$(module_title_$modu_lang)
!endif
!!read lang/names.phtml.$modu_lang

!header1

!read adm/title.phtml 1\
WIMS $httpd_HTTP_HOST\
$title


!if $error!=$empty

 <div class="wims_alertmsg">
 !read lang/msg.phtml.$modu_lang 
 </div>

 !goto end1
!endif

!if $forumcnt=0
  $name_noforum
 !goto end
!endif

!set forumname=<span class="wims_emph">$title</span>

!if $password!=$empty and $passverify=$empty and $mailverif=$empty
 $forumname
 $name_passw
 !form reply
 <input type="hidden" name="step" value="1"/>
 <div class="wimscenter">$wims_name_Password
 <input type="password" name="forumpass"/>
 </div>
 <div class="wimscenter">
 <input type="submit" value="$wims_name_send"/>
 </div></form> <p>
$name_obtain_passw
 (
 !mailurl $smail $name_write_owner
 )
 </p>
 !goto end1
!endif

!if $step=$empty or $step<2
$name_inscription
!form reply
 <input type="hidden" name="step" value="2"/>
 <ul>
 <li>
 $wims_name_lastname <input size="20" name="lastn" value="$lastn"/>
  $wims_name_firstname <input size="20" name="firstn" value="$firstn"/>
  
</li><li>
$wims_name_Login
  <input size="16" name="login" value="$login"/> <br/>
  $name_password1
  
</li><li>
$wims_name_Password
  <input type="password" size="16" name="pass"/> <br/>
  $name_password2
  !if $mailverif=$empty
   <li>$wims_name_email ($name_optional)&nbsp;:<br/>
  !else
   <li>$wims_name_email<br/>
  !endif
  <input size="60" name="email" value="$email"/>
  </li>
  </ul>
 <div class="wimscenter wimsform"><input type="submit" value="$wims_name_tosave"/></div>
 </form>
 !goto end1
!endif
!default name_student=$firstn $lastn
!if $step=2
 $name_hello, $name_student!<p>
 $name_inscription2
 <tt class="wims_login">$login</tt>. <p>
 !if $email=$empty
  $name_email1 </p>
 !else
  $name_email2: <tt>$email</tt> </p>
 !endif
 $name_email3
 !form reply
 <input type="hidden" name="step" value="3"/>
 <div class="wimscenter"><input type="password" size="16" name="pass2"/>
<br/><input type="submit" value="$wims_name_send"/></div>
 </form>
 !goto end1
!endif

!if $step=3
 $name_hello, $name_student!<p>
 !if $mailverif=yes
  !set mailverif=next
  !read lang/names.phtml.$modu_lang code
  <div class="wimscenter">
  !form reply
  <input type="hidden" name="step" value="3"/>
  <input size="10" name="vericode"/>
  <input type="submit" value="$wims_name_tosave"/>
  </form>
 &nbsp;
 !set wims_ref_class=wims_button
  !href module=adm/forum/forum $wims_name_giveup
  </div>
  !goto end1
 !else
 !read lang/names.phtml.$modu_lang welcome
  !goto end
 !endif
!endif

:end1

 &nbsp;
 !set wims_ref_class=wims_button
!href module=adm/forum/forum&type=list $name_forumlist
:end
!tail

!set step=

