
!set wims_form_method=post
!if $error iswordof not_secure not_superclass
  !exit
!endif
<h3>$title_data</h3>
<p>
 <p><hr> <p>

!if $outfile!=$empty
 $name_csv1:
 !getfile $outfile $outfile
 <p><hr> <p>
!endif

!form reply
<input type=hidden name=job value=csv>
<input type=hidden name=csvtype value=download>
$name_csv2: <font color=green>$vote_title</font>
<ul><li>
$name_format
!formselect csvformat list csv,tsv
<small>
!href module=$module&cmd=help&special_parm=csvformats $wims_name_help
</small>
</li>
!if $vote_option!=anonymous
<li> $name_data
!formradio csvoption list global,detail prompt $name_global,$name_detail
<small>
!href module=$module&cmd=help&special_parm=csvvotes $wims_name_help
</small>
</li>
!endif
</ul>
<center><input type=submit value="$wims_name_download"></center>

!readproc csv.proc
</form>
