
!if $vote_option=anonymous
 Ce questionnaire est anonyme.
!else
 !if $vote_option=trace
   Ce questionnaire est anonyme et tracé.
 !else
   Cet enregistrement est nominatif.
 !endif
!endif
!if $vote_status=2
 Il est fermé.
!endif

!if $wims_user=supervisor
 ($vcnt votes)
 !href cmd=reply&job=edit Modifier
 
 !href cmd=reply&job=csv Données tableur
<p>
!endif

!if $vote_status=2
 !changeto $votedir/$vote.def
!endif

!if $(user_vote_$Vote)!=$empty
 !if $vote_option!=nominative
  Vous avez déjà voté. <p>
 !else
  Vous avez déjà exprimé votre choix, mais vous pouvez encore changer d'avis.
  <p>
  !goto form
 !endif
!else
 Exprimez votre choix : <p>
 :form
 !form reply
 <input type=hidden name=job value=vote>
 !set m_formed=yes
!endif

!read $votedir/$vote.def

!if $m_formed=yes
 <p><center>
 <input type=submit value="Enregistrer">
 </center></form>
!endif
!readdef $votedir/$vote.comments 
!if $wims_user=supervisor and $test_comment=1 and $vote_option!=nominative
<p><b>Textes des commentaires</b> : 
</p><p> 
!for i=1 to $parmcnt
 !if $(type_comment$i)=yes
  !set comment_$i = !replace internal --- by $\
 $<br>- in $(comment_$i)

<pre>
 $i : 
 $(comment_$i)
 </pre>
</p><p>
 !endif
 </p>
!next
!endif
!if $wims_user=supervisor and $vote_option!=anonymous
 <p> Détail des enregistrements.
 !for i=1 to $parmcnt
  !for c=1 to $(choices$i)
   !if /supervisor/ notin $c/
    <p>$i-
    !item $c of $(chlist$i)
 <br> <tt>
    !for u in $(votes_$(i)_$c)
     !if $vote_option=nominative
      !set U=!translate internal / to , in $u
      !readproc adm/class/userdef classes,$U
      !defof user_lastname, user_firstname in $userdef
       ($u)
       <br>
      !else 
       ($u) 
      !endif
    !next u
   </tt>
   !endif
  !next c
 !next i
!endif

