!set week_min=3
!set month_min=20
!set year_min=200

!set n=!linecnt $ref

$name_list1
!read adm/date.phtml date,$year1,$month1,$day1
$s_date_out
$name_to
!read adm/date.phtml date,$year2,$month2,$day2
$s_date_out
($name_sum).
<br>$name_list2
<p>
<table border=0 cellspacing=1>
!set total=0
!set totall=0
!for i=1 to $n
 !set l=!line $i of $ref
 !set w=!wordcnt $l
 !set a=!word 1 of $l
 !set b=!word 2 of $l
 !if $w=2 and ($search = yes or (search notin $b and query notin $b and cgi notin $b))
  !set totall=$[$totall+1]
  <tr><td align=right>$a<td>&nbsp;&nbsp;
  <td><a href="http://$b">$b</a>
  !set total=$[$total+$a]
 !endif
!next i
<tr><td align=right>$total<td>&nbsp;&nbsp;
<td>$name_visit1 $totall $(names_$type).
</table> <p>

!if $auto>0
 $name_visit2.
 <p>
!endif

