DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(ID BIGINT NOT NULL PRIMARY KEY,NAME VARCHAR,DESCRIPTION VARCHAR,PRICE FLOAT);

INSERT INTO PRODUCT VALUES (1, 'Plier', NULL, 3.5);
INSERT INTO PRODUCT VALUES (2, 'Hammer', NULL, 7.76);
INSERT INTO PRODUCT VALUES (3, 'Saw', NULL, 17.35);
INSERT INTO PRODUCT VALUES (4, 'Clamp', NULL, 4.37);

DROP TABLE ACCOUNTS;
CREATE TABLE ACCOUNTS(ID INTEGER NOT NULL IDENTITY PRIMARY KEY,OWNERNAME VARCHAR,BALANCE DOUBLE);

DROP TABLE USERS;
CREATE TABLE USERS(USERID VARCHAR NOT NULL PRIMARY KEY,FIRSTNAME VARCHAR,LASTNAME VARCHAR,EMAIL VARCHAR);
