
!if $class_defined!=yes
 <b>Errore</b>. Hai cercato di fare il login in $name_classess che non esiste.
 Verifica la tua richiesta.
 !exit
!endif

Per accedere alle opzioni di amministrazione $name_classesss <b><font
color=green>$class_description</font></b> presso
<b><font color=green>$class_institution</font></b>
occorre la password di amministrazione del corso.

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 Password di amministrazione: <input type=password size=20 name=auth_password>
<p>
<input type=submit value="Invia">
</center>
</form>

