
!if $class_defined!=yes
 <b>Errore</b>. Hai cercato di fare il login in $name_classess che non esiste.
 Verifica la tua richiesta.
 !exit
!endif

Per accedere al $name_classesss <b><font
color=green>$class_description</font></b> presso
<b><font color=green>$class_institution</font></b> con funzione di
<em>$name_sup</em> occorre la password $name_sup.

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 $wims_name_Password ($name_sup) <input type=password size=20 name=auth_password>
<p>
<input type=submit value="$wims_name_Enter">
</center>
</form>

