
!if $directcnt>0
 Puoi passare direttamente a:
 <table class="wims_classes_direct">
 !for cl in $directlist
  !distribute words $cl into c_,u_
  !set n_=!defof class_institution, class_description in\
	wimshome/log/classes/$c_/.def
	!set ntype_=!defof class_typename in\
	wimshome/log/classes/$c_/.def
	!set nstyle=wims_classes_direct_$ntype_
	!set ntype_ = !replace internal program by $(CL_Name[3]) in $ntype_
	!set ntype_ = !replace internal level by $(CL_Name[1])  in $ntype_
	!set ntype_ = !replace internal class by $(CL_Name[2])  in $ntype_
	!set ntype_ = !replace internal course by $(CL_Name[4]) in $ntype_
	!set ntype_ = !replace internal portal by $(CL_Name[6]) in $ntype_
	!set ntype_ = !replace internal group by $(CL_Name[6]) in $ntype_
  !if $u_=supervisor
   !set t_=supervisor
  !else
   !set t_=$type
  !endif
  <tr class="$nstyle"><td class="wims_classes_direct_type">$ntype_</td><td class="wims_classes_direct_name">
  !href cmd=reply&type=auth$t_&class=$c_&auth_user=$u_ $n_
  </td><td><tt>$u_</tt></td>
  </tr>
 !next cl
 </table>
 <p><hr> <p>
 !if $wims_user=supervisor
  O scegli $name_level_else $sousclasses_else nella tabella.
 !endif
!else
 !if $wims_user=supervisor
  Puoi passare direttamente a $name_level_else $sousclasses_else selezionandone il nome nella tabella seguente
 !else
  Non puoi accedere a nessun altro corso.
 !endif
!endif

