!if $clcnt<=0
 Spiacente, questo sito non contiene esempi predisposti.
 !exit
!endif

!if $lacnt<=0
 Non ci sono esempi in italiano su questo sito, è però possibile consultare $clcnt esempi in inglese.
 !exit
!else
 Su questo sito sono disponibili $clcnt esempi in lingua italiana.  
!endif

 Su questo sito sono disponibili $clcnt esempi in lingua italiana. 
Gli esempi mostrano come un corso interattivo virtuale appare agli studenti.
&Egrave; possibile
!href module=adm/class/regclass creare
 il proprio corso interattivo e accedere al men&ugrave; docenti
ricco di molte funzioni pi&ugrave; sofisticate.

!let classification=Scuola,College,Liceo,Università,Altro
!let nb=!itemcnt $classification
!bound exampletype between 1 and $nb default 3
<p>
<center><table>
<tbody><tr>
 !for k=1 to $nb
  !let titre=!item $k of $classification
  <th>
   !if $k=$exampletype
    $titre
   !else
    !href cmd=reply&exampletype=$k $titre
   !endif
  </th>
 !next k
 </tr>
 <tr><td colspan=$nb>
 $table_header
  $table_hdtr<th>Nome del corso</th>
!!  <th>Livello</th>
<th>tipo di accesso</th><th>Registrazione</th></tr>
!for i=1 to $clcnt
 !set l=!line $i of $classes
 !distribute items $l into code,expire,inst,cl
 !defread wimshome/log/classes/$code/.def
 !distribute char $class_level into l_,y_
   !let clsty=!positionof item $class_level in E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,H7,U1,U2,U3,U4,U5,U6
   !if $clsty!=$empty
    !let clsty=!item $clsty of 1,1,1,1,1,1,2,2,2,2,3,3,3,4,4,4,4,4,4
   !endif
   !if $exampletype=$clsty or ($clsty=$empty and $exampletype=$nb)
    $table_tr
     <td align=center>$cl</td>
!!     <td align=center>$(n_$l_)<br>anno $y_</td>
 <td align=center>
 !href module=home&user=anonymous,$code,anonymous anonimo
 &nbsp;
 !href module=$module&type=authparticipant&class=$code iscritto
 </td>
     <td align=center>
      !href module=adm/class/reguser&class=$code Registrazione
     </td>
    </tr>
   !endif
!next i
 $table_end
</tbody></table></center><p>
 
<ul>
<li>Selezionare <tt class="d">anonimo</tt> per accedere al corso senza iscrizione
(come studente non iscritto).

<li><p>Selezionare <tt class="d">iscritto</tt> per accedere al corso come utente
registrato con proprio login e password. (Dovete aver gi&agrave;
provveduto alla registrazione.)(Se la registrazione fosse stata
fatta molto tempo fa, potrebbe essere stata cancellata: questi corsi
sono solo a titolo di esempio e le registrazioni delle attività
degli utenti non vengono conservate.)

<li><p>Selezionare <tt class="d">Registrazione</tt> per iscriversi al corso interattivo.
</ul>

Sono disponibili
!href module=home&search_keywords=&search_category=S qui
 test di autovalutazione già pronti che possono essere importati nel vostro
 corso e quindi modificati.

