!if $clcnt<=0
 Spiacente, questo sito non contiene esempi predisposti.
 !exit
!endif

!if $lacnt<=0
 Non ci sono esempi in italiano su questo sito.
!endif

 Su questo sito sono disponibili $clcnt esempi in lingua italiana. 
Gli esempi mostrano come un corso interattivo virtuale appare agli studenti.
&Egrave; possibile
!href module=adm/class/regclass creare
 il proprio corso interattivo e accedere al men&ugrave; docenti
ricco di molte funzioni pi&ugrave; sofisticate.

<p>$table_header
$table_hdtr<th>Nome del corso</th><th>Livello</th><th>tipo di accesso</th><th>Registrazione</th>
!for i=1 to $clcnt
 !set l=!line $i of $classes
 !distribute items $l into code,expire,inst,cl
 !defread wimshome/log/classes/$code/.def
 !distribute char $class_level into l_,y_
 
 $table_tr<td align=center>$inst<br>$cl</td>
 <td align=center>$(n_$l_)<br>anno $y_</td>
 <td align=center>
 !href module=home&user=anonymous,$code,anonymous anonimo
 &nbsp;
 !href module=$module&type=authparticipant&class=$code iscritto
 </td><td align=center>
 !href module=adm/class/reguser&class=$code Registrazione
 </td>
!next i
</tr>$table_end <p>
 
<ul>
<li>Selezionare `anonimo' per accedere al corso senza iscrizione
(come studente non iscritto).

<p><li>Selezionare `iscritto' per accedere al corso come utente
registrato con proprio login e password. (Dovete aver gi&agrave;
provveduto alla registrazione.)(Se la registrazione fosse stata
fatta molto tempo fa, potrebbe essere stata cancellata: questi corsi
sono solo a titolo di esempio e le registrazioni delle attività
degli utenti non vengono conservate.)

<p><li>Selezionare `Registrazione' per iscriversi al corso interattivo.
</ul>

