!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=coordinamento di corsi
    !set name_sup=docente coordinatore
   !else
    !set name_classe=portale di sede
    !set name_sup=docente supervisore
   !endif
    !set name_classes= il $name_classe
    !set name_classess= un $name_classe
    !set name_classesss= del $name_classe
    !set name_classessss= Il $name_classe
 !else 
   !set name_classe=corso
   !set name_classes=il $name_classe
   !set name_classess=un $name_classe
   !set name_classesss= del $name_classe
   !set name_classessss= Il $name_classe
   !set name_sup=docente
 !endif

 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of corso,insegnamento
   !set Name_level= !item $splevel of Livello,Corso,Insegnamento
   !set Name_levels= !item $splevel of Livelli,Corsi,Insegnamenti
   !set sousclasses_else=!item $splevel of or a class, or a course
   !set name_level_else= !item $splevel of a level,a class,a course
 !else
   !set sousclasses=sottocorso
   !set sousclasses_else=a class or an institution
 !endif
 
!set CL_Name	=Livello,Corso,Programma,Insegnamento,Insegnamento opzionale
!set Name_program=Programmi
!set name_program=programma
