
!read search.phtml
!if $overflow=yes
 !exit
!endif

!if $clcnt+$sccnt+$directcnt<1
 !if $keyword=$empty
 Non ci sono corsi in lingua italiana su questo server. Forse stai cercando
 un corso in 
 !href module=home&list=0 un'altra lingua
?
 !else
  Non ci sono corsi corrispondenti alla tua richiesta.
 !endif
 !exit
!endif

!if $wims_user!=$empty
 !read direct.phtml
 !if $wims_user!=supervisor and $superclass=$empty
  !exit
 !endif
!else
Scegliete la riga corrispondente al corso o all'istituzione 
che vi interessa.
 <p>
Se non siete ancora iscritti, cliccate su <tt>$name_register</tt> 
(se il corso è <tt>riservato</tt>, avrete bisogno della password
che vi ha fornito il vostro docente).

  <p>Altrimente, cliccate semplicemente su <tt>$name_enter</tt> per accedere. 
!endif

!if $sccnt>0
<p>$table_header
 <caption>Sedi e gruppi di corsi coordinati</caption>
 $table_hdtr
 <th>Nome</th><th colspan=2>Studente</th><th>Gestore</th><th>Tipo di accesso</th>
!for i=1 to $sccnt
 !set l=!line $i of $sclasses
  !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !if $superclass=$empty
   !set show=$inst<br>$cl
  !else
   show=$inst
  !endif
  !set supv=!item 9 of $l
  !if $supv=$empty
   !reset class_password
  !defread wimshome/log/classes/$code/.def
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif
  
  $table_tr<td align=center>
  !!!href module=$module&type=authparticipant&class=$code 
  $show
  </td> <td align=center>
  !href module=$module&type=authparticipant&class=$code $name_enter
  </td> <td align=center>
  !href module=adm/class/reguser&class=$code&subclass=yes $name_register
  </td>  <td align=center>
  $supv
  </td> <td align=center>
  !if $pswd=$empty
   aperto
 !else
  riservato
 !endif
!next i
 $table_end <p>
!endif

!if $clcnt>0
<p>$table_header
 !if $superclass=$empty
  <caption>Corsi autonomi</caption>
 $table_hdtr<th>Nome corso</th><th colspan=2>Studente</th>
 <th>Docente</th><th>Livello</th><th>Tipo di accesso</th>
 !else
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
  !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
 !endif
  <caption>$Name_levels in $inst
   !if $splevel>1
    !href cmd=reply&type=$type&superclass2=$sparent Torna su
   !endif
   </caption>
   $table_hdtr
   <th>Nome corso</th><th colspan=2>Studente</th>
   <th>Docente</th><th>Livello</th><th>Tipo di accesso</th>
   !if $superclass!=$empty and $stype=4
    <th>+</th>
   !endif
 !endif
!for i=1 to $clcnt
 !set l=!line $i of $classes
  !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !set supv=!item 9 of $l
  !if $supv=$empty
   !reset class_password
  !defread wimshome/log/classes/$code/.def
   !set lv=$class_level
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif
  !distribute char $lv into l_,y_
  
  !if $superclass=$empty
   !set show=$inst <br>$cl
  !else
   !set show=$cl
  !endif
  $table_tr<td align=center>
    $show
  </td><td align=center> 
  !href module=$module&type=authparticipant&class=$code $name_enter
  </td> <td align=center> 
  !if $splevel=$empty or $splevel=2
   !href module=adm/class/reguser&class=$code $name_register
  !else
   <font color=grey>$name_register</font>
  !endif
  </td><td align=center>
  $supv
  </td><td align=center>$(n_$l_)<br>anno $y_</td>
 <td align=center>
  !if $pswd=$empty
   aperto
 !else
   riservato
  !endif
 </td>
   !if $superclass!=$empty and $stype=4
    <td>
    !if $ty!=1
     !href cmd=reply&type=$type&superclass2=$code $sousclasses
    !else
    -
    !endif
   !endif
!next i
 $table_end <p>
!endif


