<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm1name= '随机化';
 var oefparm1= [ 'random( .. )', 'randint( .. )', 'random( )', 'shuffle( )', 'shuffle( , )', 'randomitem( )', 'randomrow( )' ];
function oefparm1fun(instruction){
    switch(instruction)
	{
	case 'random( .. )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>random(-5..5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>-5 与 5 之间的随机数</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randint( .. )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randint(-5..5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>-5 与 5 之间的随机整数(包括两端)</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'random( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>random(1,2,3,a,b,c)</code></div>'+
'<div class="explication"><div class="title">Explication</div>{1,2,3,a,b,c} 里随机选一项</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'shuffle( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>shuffle(6)</code></div>'+
'<div class="explication"><div class="title">Explication</div>6 个整数 1,2,...,6, 的随机排列</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'shuffle( , )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>shuffle(a,b,c,d,e)</code></div>'+
'<div class="explication"><div class="title">Explication</div>字母 {a,b,c,d,e} 的随机排列</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randomitem( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randomitem(\\list)</code></div>'+
'<div class="explication"><div class="title">Explication</div>在(逗号分隔的)表 \\list 内随机选一项</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'randomrow( )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>randomrow(\\mat)</code></div>'+
'<div class="explication"><div class="title">Explication</div>矩阵 \\mat 内随机选一行</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}