<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm5name= '预定义的变量';
 var oefparm5= [ '\\reply ', '\\choice ', '\\step ', '\\sc_reply ', '\\help_subject ' ];
function oefparm5fun(instruction){
    switch(instruction)
	{
	case '\\reply ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>reply1 reply2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>含有学生对类型为 <tt>reply</tt> 的问题的回答的变量</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\choice ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>choice1 choice2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>含有学生对类型为 <tt>choice</tt> 的问题的回答的变量</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\step ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>step</code></div>'+
'<div class="explication"><div class="title">Explication</div>给出步数的变量 (当使用命令 <tt>\\steps</tt> 或 <tt>\\nextstep</tt> 时).</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\sc_reply ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>sc_reply1 sc_reply2 ...</code></div>'+
'<div class="explication"><div class="title">Explication</div>反映回答的优劣程度的变量, 取值可以是 0 和 1 或者其间的数.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\help_subject ' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>help_subject</code></div>'+
'<div class="explication"><div class="title">Explication</div>variable contenant l\'identificateur de l\'aide introduite par la m閠hode sp閏iale <tt>help</tt>.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}