<!-- Automatically generated by bin/oefdoc.pl -->
var oefparm4name= '高级功能';
 var oefparm4= [ 'pari(  )', 'maxima(  )', 'yacas(  )', 'wims(  )', 'draw(  )', 'slib(  )', 'teximg(  )' ];
function oefparm4fun(instruction){
    switch(instruction)
	{
	case 'pari(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>pari(factor(2^101-1))</code></div>'+
'<div class="explication"><div class="title">Explication</div>调用 PARI/GP: 这里是分解整数</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'maxima(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>maxima(integrate(x^2+1,x);)</code></div>'+
'<div class="explication"><div class="title">Explication</div>调用 Maxima: 这里是积分一个函数</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'yacas(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>yacas(Taylor(x,0,10) cos(x^2+x+1))</code></div>'+
'<div class="explication"><div class="title">Explication</div>调用 Yacas: 这里是计算Taylor展开式</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'wims(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>wims(sort items \\list)</code></div>'+
'<div class="explication"><div class="title">Explication</div>调用 wims 的 !sort 命令对表 \\list 的项排序</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	'<div class="syntax"><div class="title">Syntaxe</div><code>wims(listintersect \\list1 and \\list2)</code></div>'+
'<div class="explication"><div class="title">Explication</div>调用 wims 的 !listintersect 命令得到 \\list1 与 \\list2 的公共项</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'draw(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>draw(绘图源码 ...)</code></div>'+
'<div class="explication"><div class="title">Explication</div>画一个图, 绘图源码同 <tt>\\draw</tt>, 第 1 行是图形大小. 输出是图形的 URL.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'slib(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>slib(matrix/invertible 3,5)</code></div>'+
'<div class="explication"><div class="title">Explication</div>读入 WIMS slib, 的 matrix/invertible 以生成一个可逆 3x3 矩阵, 元素取值范围 5.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case 'teximg(  )' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>teximg( \\(\\displaystyle{\\frac{3}{4}}\\) )</code></div>'+
'<div class="explication"><div class="title">Explication</div>创建由 tex 产生图像. 输出是这个图像的地址 URL. 它可以复制到由 draw 建立的图像内.</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}