<!-- Automatically generated by bin/oefdoc.pl -->
var specialname= 'M閠hodes sp閏iales';
var special= [ '\\special{expandlines }', '\\special{imagefill }', '\\special{help }', '\\special{tabs2lines }', '\\special{rename }', '\\special{tooltip }' ];
function specialfun(instruction){
    switch(instruction)
	{
	case '\\special{expandlines }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{expandlines }</code></div>'+
'<div class="explication"><div class="title">Explication</div>写入预格式的参数时不执行赋值. \n \n</div>'+
'<div class="exemple"><div class="title">Exemple</div><span class="wims_help_example">例</span> \n<pre>\\text{texte= \nfor a in \\B \n   a = a + 1 \nendfor \n} \n\\statement{ \\special{expandlines \\texte}} \n</pre>\n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\special{imagefill }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{imagefill }</code></div>'+
'<div class="explication"><div class="title">Explication</div>把拖拉填充(<tt>dragfill</tt>)或点击填充(<tt>clickfill</tt>)的栏放进一个大的图形里. \n 用于OEF练习的陈述.  \n  \n :example \n<span class="wims_help_example">例如</span> \n \n  <pre> \n \\special{imagefill \\imagedir/myphoto.jpg,450x350,40x40 \n reply 1,120x250 \n reply 3,300x50 \n reply 4,10x15 \n } \n </pre> \n这个例子把一个大的图形(<tt>\\imagedir/myphoto.jpg</tt>)放在陈述里, \n大小是 450x350, 有 3 个 40x40 的拖拉-放置栏. \n3个栏的正确答案分别是 1,3,4(必须是点击填充或拖拉填充类型的), \n它们在大图中的位置分别是 120x250, 300x50, 10x15. \n <p> 大图会自动伸展以填满指定的区域. \n <p> 可以有多重回答. 在命令中加入第 3 个参数 \n <tt>reply 1,120x250x4</tt> 后, 会显示长度等于 4 的放置栏.\n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\special{help }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{help }</code></div>'+
'<div class="explication"><div class="title">Explication</div>\\special 方法 "help" 接受两个参数. \n第一个参数是关键词, 被放在帮助文本的变量 \\help_subject 里. \n第二个是显示在链接点的文字. \n  \n如果 \\special{help} 被放在练习的陈述或反馈中, \n帮助将使用弹出的形式, 与模块中通常的帮助链接不同. \n \n所有的帮助内容应该被放在oef的源码中. \n不存在模块水平的帮助, 否则oef文件的独立性会由于帮助而被破坏. \n如果你有几个练习共享同一个帮助文本, 你可以考虑使用 cpp. \n<p> \n \n</div>'+
'<div class="exemple"><div class="title">Exemple</div><span class="wims_help_example">例:</span> \n <pre> \n \\title{猜猜看} \n \\statement{ 猜一个英文词 :   \n   \\special{help test1,第一个提示} \n } \n \\answer{1}{Monk} \n \\help{ \n   这里是帮助: 帮助主题=\\help_subject \n   <p> \n   \\if{\\help_subject issametext or \\help_subject issametext none}{ \n     \\special{help test0,这里} \n   } \n   \\if{\\help_subject issametext test1}{ \n     第一个字母是 <b>M</b>. 你可以看到另一个提示 \n     \\special{help test2,在这里} \n   } \n  \\if{\\help_subject issametext test2}{这是第二个提示.  \n    第二个字母是 <b>o</b> \n   } \n  \\if{\\help_subject issametext test0}{这里是   \n    \\special{help test1,第一个提示}, \\special{help test2,第二个提示} \n   } \n } \n </pre>\n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\special{tabs2lines }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{tabs2lines }</code></div>'+
'<div class="explication"><div class="title">Explication</div>把制表符替换成换行符. 必要时可用于 applet. \n \n</div>'+
'<div class="exemple"><div class="title">Exemple</div><span class="wims_help_example">例</span> \n \n<pre> \n\\statement{  \n  \\special{tabs2lines \\texte	\\texte} \n} \n</pre>\n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\special{rename }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{rename }</code></div>'+
'<div class="explication"><div class="title">Explication</div> \n给文件重新命名. \n</div>'+
'<div class="exemple"><div class="title">Exemple</div> \n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	case '\\special{tooltip }' :
chaine_aide='<div class="syntax"><div class="title">Syntaxe</div><code>\\special{tooltip }</code></div>'+
'<div class="explication"><div class="title">Explication</div><script type="text/javascript" src="scripts/js/wz_tooltip.js"></script> \n创建一个提示工具 <tt>tooltip</tt> :  第一个参数是链接的文字, 第三个参数是出现在提示里的文字, \n第二个参数是放在方括号里面的文字选项 : \n在方括号内部你必须按 wz_tooltip.js 里的说明设置选项. \n默认选项是 : [FONTSIZE, \'12pt\', ABOVE, \'true\'] \n如果你要装载 javascript (对一个 html 页只需一次), \n就不必放任何参数. 如果你肯定此 html 页已经装入了 javascript, \n因而不需再装载时, 可以在第二个参数里加入 <tt>nojs</tt>. \n你也可以设置 css 格式类 <tt> span.tooltip</tt>. \n \n</div>'+
'<div class="exemple"><div class="title">Exemple</div><span class="wims_help_example">例</span> \n \n<pre> \n\\special{tooltip 点击这里, ,此词有5个字母} \n\\special{tooltip 点击这里,[DURATION, 4000, FONTSIZE, \'18pt\'], 此词有5个字母} \n\\special{tooltip 点击这里,[TITLE, \'某标题\', PADDING, 9],一段文字} \n\\special{tooltip } \n\\special{tooltip\\special{tooltip 点击这里,nojs [TITLE, \'某标题\', PADDING, 9],一段文字} \n</pre> \n<p>tooltip 的可能选项是  (根据 www.walterzorn.com) \n <embed> \n!read js/cn/tooltip_doc.html \n</embed> \n</div>'+
'' ; return chaine_aide;
	   break;
	////******************** 

	
	}
}