# red, green, blue, magenta,   brown, cyan, grey, orange, yellow, black
color_1=ff0000
color_2=00a000
color_3=0000ff
color_4=a000a0
color_5=a0a000
color_6=00a0a0
color_7=808080
color_8=ff8000
color_9=ffff00
color_10=000000
colcnt=10
# bg, border, axis, c1, c2,...
insplot_colors= xffffff x000000 x404040 \
 x$color_1 x$color_2 x$color_3 x$color_4 x$color_5 x$color_6 x$color_7 x$color_8 x$color_9 x$color_10

insplot_size=$[$picx/500],$[$picy/400]
