!!<html><head>
!!!if $cmd=reply
!! !set wims_expire=
!! $wims_html_header
!! <meta http-equiv="expires" content="
!! !date -d '1 day'
!! ">
!!!else
!! $wims_html_header
!!!endif
!!</head><body $wims_htmlbody>
!!!headmenu

!header1
!if $cmd=help and $special_parm=about
 !read about.phtml
 !goto end
!endif

!if $cmd=help
 !read help.phtml
 !goto end
!endif

!read adm/title.phtml 1\
WIMS @ $httpd_HTTP_HOST\
$(module_title_$lang)

!if $sitestart=$empty
$name_warning
 !goto end
!endif

!if $show=yes and $ref!=$empty and $laps>0
!!if $show=yes
 <p class="wimscenter">
 !set wims_ref_class=wims_button
 !href cmd=resume $wims_name_menuback
 !set wims_ref_class=wims_button
 !href module=home WIMS home
 </p>
 !read answer.phtml
 !href cmd=resume $wims_name_menuback

!else
 !read menu.phtml
!endif
:end
!tail
