
!read themes/$wims_theme/table.proc
!if $special_parm=flydraw
 <p><center><h3>Flydraw commands</h3></center><p>
 !read help/flydraw.phtml
 !exit
!endif

<form action="http://www.google.com/search">
<input type=submit value="Search Google"> for documentation of
<select name=q>
!for sw in $swname
 <option value="$sw documentation">$sw
!next sw
</select></form>

<p>
!href cmd=help&special_parm=flydraw Flydraw documentation
.
<p>
Input and output of any execution is limited to 16K. For obvious security
reasons, there is no network access, file writing is limited to the current
directory if not downright denied, and execution time is limited to a few seconds.

<p>
Special note for C interface: the entry point is <tt>int test(void)</tt>,
but not <tt>main()</tt>!

