!set sw1= $sw
!if $sw=pari
  !set sw1=gp
!endif
!if $sw=draw
  !set sw1=flydraw
!endif
!default sw1=flydraw
!read js/edit_area.phtml wims_deposit $sw1 $swlistjs

!header

!if $compute=yes
 !if $swout=$empty
  Your code did not give any output from <em>$SW</em>.
 !else
  Answer by <em>$SW</em> :
  !if $sw=draw
   <img align="middle" src="$swout">
   !goto after
  !endif
  !if $sw=povray
   <img align="middle" src="$swout">
   !goto after
  !endif
<pre style="font-weight:bold;font-family:Courier New,Courier,mono;overflow:auto;color:blue;">
$swout
</pre>
 !endif
!else
 This tool allows you to run most WIMS-interfaced software or
 computer languages directly online. Just type in your code and get the
 result!
 !href cmd=help Click here
 for software documentation.
 <p>
 WIMS developers can also use this as a testing tool, to check the behavior of
 various software under WIMS.
 <p>
 For security reasons, code length is limited to 16K, and access to system
 resources is strictly controled. Note also that some software may be missing on
 a given server. Please check with the webmaster.
!endif

:after
!if $msg!=$empty
 <p><hr> <p>
 Error message from <em>$SW</em> :
<pre style="color:red;font-size:80%">
$msg
</pre>
!endif

<p><hr> <p>
!form reply
<input type="submit" value="Execute">
the following lines by
!default sw=sh
!formselect sw list $swlist prompt $swname
$ : 
 &nbsp;
 !set wims_ref_class=wims_button
!href cmd=renew Clean up
 &nbsp;
 !set wims_ref_class=wims_button_help
!href cmd=help $wims_name_help
&nbsp;
<br>
!set src=!reinput $src
!set src=!replace internal &amp;#36; by &#36; in $src
!set src=!replace internal &amp; by & in $src
<textarea id="wims_deposit" rows="25" name="src">
$src
</textarea>
</form>

!tail

!reset src sw
