<!-- begin of $wims_theme/tail.phtml -->
!! Tail menu theme.
!nocache
!set wims_theme_tail=yes
   <br class="clearall" />
!read themes/_widgets/nextinsheet.phtml
  </div><!--end of wimsbody-->
 <br class="clearall spacer" />
</div><!--end of wimspagebox-->
!read themes/_widgets/topback.phtml

!if $slib_geogebra_exists=yes
 !read themes/_widgets/tailgeogebra.phtml
!endif
!if $wims_homeref_special!=$empty
!!    </div><!--end of wimspagebox -->
    <div class="wimsmenu">
     <div class="tailitem">$wims_homeref_special</div><!--tailitem-->
    </div><!--wimsmenu-->
  </div><!--wimsbodybox-->
!!!FIXME wims_homeref_special is non empty only in exam case ????
</div><!--id wimsexam-->
 !exit
!endif

!distribute items div,div into div0,div1
!read themes/_widgets/menumodubox.phtml
!reset div0 div1

!distribute items div,span into div0,div1
!!read themes/_widgets/menubox.phtml
!reset div0 div1

</div><!--wimsbodybox-->

!!read themes/_widgets/about.phtml

<!--FIN BAS DE PAGE-->

!if help isin $wims_session
</div><!--wims_mhelp-->
!endif
!if $wims_lightpopup=yes
 </div> <!--wimslightpopup-->
 </div>
!endif

<!-- end of $wims_theme/tail.phtml -->
