
<b>Sharing supervisor account</b>.
<br>
If you prepare to 
!href cmd=help&special_parm=neighbor share
 the supervisor account with other classes, please be aware that the
security risks are also shared.
<p>
If all the classes belong to the same teacher (you), sharing supervisor
account represents the advantage that to change your supervisor password,
you have only to change it once (in any of the sharing class). This allows
you to change password more frequently, making your classes more secure.
You should however be aware that multiple classes with the same supervisor
password multiplies the security risk by the number of classes. An
intrusion to one of the classes can bring damage to all the sharing classes,
a situation that has already occured in a teaching environment.
<p>
On the other hand, if the classes belong to different physical teachers,
sharing supervisor account (of course putting a common password neither) is
not recommended. Just think of the case where one teacher changes the
password by one reason or the other, without correctly notifying the others.

