!read names.phtml.$lang
!header

!if $error!=$empty
 !read msg.phtml
 <p><hr><p>
!endif
$fx $fy
!if $fname=$empty

!set wims_form_method=file
!form reply
<input type=file name=wims_deposit>
<input type=submit value="OK">
<p>
$name_size
<input name=size size=12>
</form>

!else

 <p><center>
 <img width=$fx height=$fy src="$imgsrc" alt=image>
 </center>
 !href cmd=new&module=$module $name_change.
!endif

<p>
:end
!tail

!reset wims_deposit

