!read adm/title.phtml 3\
Relations avec la classe <em><font color=blue>$nei_description</font></em> de <em><font color=blue>$nei_institution</font></em>\
(Enseignant&nbsp;:<a href="mailto:$nei_email?subject=Class neighboring relations">$nei_supervisor</a>)
<p>
<b>Relation de voisinage. </b> <small>[
!href cmd=help&special_parm=neibordecl $wims_name_help
 ]</small> 
 <p>La classe <em><font color=blue>
$nei_description</font></em>
!if $wims_class notitemof $nei_sup,$nei_part
 n'a pas déclaré la vôtre comme voisine.
!else
 vous accepte comme voisine,
 !if $wims_class isitemof $nei_sup and $wims_class isitemof $nei_part
  pour enseignant et participants.
 !else
  !if $wims_class isitemof $nei_sup
   pour enseignant.
  !else
   pour participants.
  !endif
 !endif
!endif
<p>
!form reply
Acceptez-vous la classe <em><font color=blue>
$nei_description</font></em> comme votre voisine&nbsp;?
!formselect nlevel from 0 to 3 prompt Non, Pour enseignant,\
	Pour participants, Pour enseignant et participants
<input type=submit value=Sauver> 
</form> <p>


!if ($nei isitemof $n_sup,$n_part and $wims_class isitemof $nei_sup,$nei_part) or \
   all isitemof $nei_sup,$nei_part
 <p><b>Importation de ressources. </b> <small>[
 !href cmd=help&special_parm=import $wims_name_help
 ]</small>
 <p>Vous pouvez
 !href cmd=reply&job2=import importer des ressources
 de la classe <em><font color=blue>
$nei_description</font></em>.
 <p>
!endif

!if  $nei isitemof $n_sup
<p>
<b>Partage de ressources.</b> 
<small>[
!href cmd=help&special_parm=share $wims_name_help
]</small>
<ul>
!endif

!if $wims_class isitemof $nei_sup and $nei isitemof $n_sup
 <li>
 !if $nsharable=$empty
  Il n'y a aucun (nouveau) type de ressources dans la classe 
  <em><font color=blue>
$nei_description</font></em> qu'elle vous autorise à partager. 
 !else
 La classe <em><font color=blue>
$nei_description</font></em> vous <b>autorise</b> à partager ses
  !set names=!replace , by , $$name_ in $$name_$nsharable
  <em>$names</em>.
  !href cmd=reply&job2=addshare Cliquez ici pour accepter
.
 !endif
 <p>
!endif

!if $nei isitemof $sharing_all
 Vous partagez déjà les ressources suivantes de la classe <em><font color=blue>
$nei_description</font></em>&nbsp;:<ul>
 !for r in $sharelist
  !if $(sharing_$r)=$nei
   <li><b><em>$(name_$r)</em></b>. 
   !href cmd=reply&job2=stopshare&stoprec=$r Arrêter ce partage
. <small>[
   !href cmd=help&special_parm=stopshare $wims_name_help
   ]</small>
  !endif
 !next r 
 </ul>
 <p>
!endif
 </li>
!if $nei isitemof $n_sup and $sharablelist!=$empty
<li>
 !form reply
 <input type=hidden name=changeshare value=yes>
 Choisissez les ressources que vous <b>autorisez</b> la classe <em><font color=blue>
$nei_description</font></em> à partager&nbsp; (<i>sélectionnez puis cliquez sur <tt>Sauver</tt></i>): <small>[
 !href cmd=help&special_parm=sharable $wims_name_help
 ]</small>
<p>
 !set sh=!nospace $sharablelist
 !set sh=!replace , by , $$name_ in $$name_$sharablelist
 !formcheckbox mksharable list $sharablelist prompt $sh
 <input type=submit value=Sauver>
 </form> <p>
!if $nsharable!=$empty
<p><b>ATTENTION</b> La classe <em><font color=blue>
$nei_description</font></em>
vous autorise à partager certaines ressources. 
Vous ne devez pas l'autoriser à partager les mêmes ressources sous peine de confusion. 
Commencez par vous entendre avec elle et avec toutes les classes avec lesquelles vous
voulez partager des ressources. 
!endif
 </li>
!endif

</ul>

!reset stoprec
