
<center>$classname
<p>
<h1>Exam details by $user_lastname, $user_firstname
</font>
</h1></center>

!if _check isin $session
 !set error=bad_op
 !goto msg
!endif

!if $error!=$empty
 :msg
 <p>
 !read msg.phtml
 <p>
!else
 !if $checksessions=$empty
  This participant has not yet done any exam.
  <p>
 !else
  Here are the exam sessions made by this participant. Click on an exercise
  to see its content.
  <p>
  $table_header
  $table_hdtr<th>Session</th><th>Exam</th><th>Score<small>/10</small></th>
  <th>Exercise</th><th>Start</th></tr>
  !for ses in $checksessions
   !for x in $(exam$ses)
    $table_tr<td><small>$ses</small></td>
    <td align=center>$x</td>
    <td align=center>$(score$(ses)$x)</td><td>
    !for i in $(exo$(ses)$x)
     &nbsp;
     !href target=wims_check module=$module&cmd=new&job=examcheck&checkuser=$checkuser&checksession=$ses&checkexo=$x.$i&checkstep=1 $i
    !next i
   !next x
   </td><td><small>$(start$(ses)$x)</small></td>
  !next t
  $table_end <p>
 !endif
!endif

<center>
!href cmd=reply&job=getuser&getuser=$checkuser Other scores
&nbsp;
!href cmd=resume List of participants
</center>

