<center>$classname<p>

<h3>Exam session of 
 !href cmd=reply&job=userprop&getuser=$getuser $lastname, $firstname
<br><font size=-1>Login name: <tt>$getuser</tt>
!if $user_email!=$empty
 &nbsp;Address: <a href="mailto:$user_email">$user_email</a>
!endif
</font></h3> <p>
</center>

 $table_header$table_tr<td align=right>Session name:</td>
 <td><tt>$esession</tt></td></tr>
 $table_tr<td align=right>Connecting host:</td>
 <td><tt>$ehost</tt></td></tr>
 $table_tr<td align=right>Remaining time:</td>
 <td>$eremain minutes</td></tr>
 $table_end <p>

<center>
!href cmd=reply&job=userexamclose&getuser=$getuser Close this exam session
 of $lastname,$firstname.
 <p>
!href cmd=reply&job=getuser&getuser=$getuser Scores of the user.
 .
!href cmd=resume List of all participants
 .
</center>
