
<center><h3>Properties of participant account</h3></center>
!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!set inplen=40
!form reply
<input type=hidden name=job value=userprop>
<input type=hidden name=getuser value=$getuser>
<p>$table_header
$table_tr<th>Login name<td><tt>$getuser</tt>
$table_tr<th>Password<td>
	!href module=adm/class/passwd&job=part&part=$getuser Change
$table_tr<th><label for="up_lastname">Last name</label><td>
	<input size=$inplen name=up_lastname id=up_lastname value="$user_lastname">
$table_tr<th><label for="up_firstname">First name</label><td>
	<input size=$inplen name=up_firstname id=up_firstname value="$user_firstname">
$table_tr<th><label for="up_email">email</label><td>
	<input size=$inplen name=up_email id=up_email value="$user_email">
$table_tr<th><label for="up_regnum">Registration number</label><td>
	<input size=$inplen name=up_regnum id=up_regnum value="$user_regnum">
!if $wims_user=supervisor
 $table_tr<th><label for="up_comments">Comments</label><td>
	<input size=$inplen name=up_comments id=up_comments value="$user_comments">
 $table_tr<th><label for="up_vars">Variables (technical)</label></th><td>
	<textarea wrap="off" cols=$[$inplen-1] rows=4 name=up_vars id=up_vars>$user_vars</textarea>
!else
 $table_tr<th><label for="passcheck">Class password</label><td>
	<input size=14 type=password name=passcheck id=passcheck> <br>
	<small>Enter the password for participant registration</small>
!endif
$table_hdtr<td align=center colspan=2>
<input type=submit name=reg value=Save> &nbsp;
<input type=submit name=abandon value=Cancel>
</td></tr>
$table_end <p>
</form>
!if $wims_user=supervisor
 <p><center>
 !href cmd=reply&job=getuser&getuser=$getuser Scores of this participant
 .
 !href cmd=reply&job=getraw&getraw=$getuser Raw work detail
 .
 <p>
 !href cmd=reply&job=delprep&delprep=$getuser Delete this participant
 .
 !href cmd=resume List of all participants
 .
 </center> <p>
!endif

!reset reg,abandon

