
Se sei un docente e vuoi creare un corso virtuale per i tuoi studenti
!href module=adm/class/regclass clicca qui
. &Egrave; anche possibile 
!href module=adm/class/classes&type=example cliccare qui
 per vedere se su questo sito sono disponibili esempi di corsi (ovvero 
corsi accessibili senza bisogno di una password). In questo modo
è possibile registrarsi e provare come funziona il sistema (dal punto
di vista di uno studente).
<p>
Ogni sito WIMS ha le sue regole per la creazione di nuovi corsi. Alcuni
accettano la creazione di nuovi corsi da parte di chiunque, altri
potrebbero richiedere un pagamento o imporre limitazioni. &Egrave; 
necessario verificare di volta in volta con il gestore del sito.
<p>
Per ragioni di sicurezza, per la creazione di un corso è richiesto un 
indirizzo email funzionante. Al momento della creazione l'indirizzo
email viene verificato; dopo aver compilato una pagina con i dati necessari, 
il server genera un codice casuale che identifica il corso e lo invia
per email. Questo codice deve quindi essere reinserito in una pagina apposita, 
altrimenti la creazione del corso viene annullata.
<p>
Questo indirizzo email viene anche reso disponibile agli iscritti (studenti)
al corso in modo che possano contattarti. In ogni caso l'indirizzo 
compare mascherato nelle pagine, in modo da ridurre il più possibile 
l'invio di posta indesiderata.
<p>
Una volta che la procedura di creazione del corso è terminata, ne diventi 
`il docente' e accedendo alle pagine del corso tramite la relativa
password puoi accedere alle funzioni di gestione (creazione di test di
autovalutazione, inserimento di esercizi nei test, creazione di documenti, 
questionari, temi d'esame, scadenze in agenda, monitoraggio dei progressi
degli studenti, ecc.).
<p>
Ci sono diversi modi per permette agli studenti di iscriversi al corso,
principalmente tramite l'utilizzo della <em>password del corso</em>
inserita in fase di creazione:<ul>
 <li>&Egrave; possibile (anche se sconsigliato) creare un corso aperto, non 
 inserendo alcuna <em>password del corso</em> in fase di creazione. Questo
 permette a chiunque di iscriversi. Questa modalità è da evitare perché
 finisce per far perdere completamente il controllo del corso. Molti siti
 WIMS non danno questa possibilità, se non per gli esempi disponibili 
 sul sito. 
 <li>&Egrave; possibile impostare la password del corso, ma tenerla segreta.
 In questo caso solo il docente può inserire nuovi studenti nel corso. &Egrave;
 possible inserire nuovi studenti anche attraverso l'upload sul server di 
 dati in forma di foglio elettronico (csv).
 <li>&Egrave; possibile impostare la password del corso e comunicarla agli 
 studenti. In questo modo gli studenti che conoscono la password possono 
 iscriversi autonomamente, ma gli estranei restano esclusi. 
</ul> <p>
