!! addshare_..., stopshare_..., addcourse_..., delprog_..., stopshare_,...
<p>
<b>Error</b>. 
!goto $error

:addcourse_already
 El curso que quiere añadir ya existe.
 !exit

:bad_access
 No tiene derecho a acceder a este módulo.
 !exit

:bad_password
 Mala contraseña: demasiado corta, demasiado larga o con caracteres
 incorrectos.
 <p>
 Pruebe otra vez.
 !exit

:bad_user
 Este usuario no existe.
 !exit

:class_full
 El nivel está lleno: ¡ya no queda espacio para añadir más clases!
 <p>
 ¿Está usted seguro de necesitar más de 99 clases en un mismo nivel?
 Por favor borre algunas clases innecesarias.
 !exit

:course_full
 ¡No queda espacio para añadir más cursos!
 <p>
 ¿Está usted seguro de necesitar más de 10 cursos de un mismo programa
 en una misma clase?
 !exit

:del_not_exist
 El nivel/clase/programa/curso que desea borrar no existe.
 !exit

:empty
 La estructura está vacía.
 !exit

:icourse_full
 El programa está lleno: ¡no queda espacio para añadir más cursos interclases!
 <p>
 ¿Está usted seguro de necesitar más de 99 cursos interclases en un mismo programa?
 Por favor borre algunos cursos innecesarios.
 !exit

:level_full
 El centro educativo está al completo: ¡no queda espacio para añadir
 más niveles!
 <p>
 ¿Está usted seguro de necesitar más de 99 niveles?
 Por favor borre algunos niveles innecesarios.
 !exit

:mod_not_exist
 El nivel/clase/programa/curso que desea borrar no existe.
 !exit

:not_secure:
 !goto unsecure

:not_supervisable
 El participante $name no es un profesor. No tiene permisos para administrar
 una zona.
 !exit

:pass_discord
 Las contraseñas no coinciden.
 !exit

:prog_full
 El nivel está lleno: ¡o queda sitio para añadir otros programas!
 <p>
 ¿Está seguro de necesitar másde 99 programas en un solo nivel?
 Por favor borre algunos programas innecesarios.
 !exit

:unsecure
 Sólo se puede acceder a este módulo desde una estación de trabajo segura.
 !exit

:user_exists
 El participante ya existe.
 !exit

:*
!msg $error

