
Le service gratuit fourni par WIMS sur l'internet est sans aucune garantie.

<p>Le programme du serveur est sujet à
<a href=COPYING target=wims_external>GNU General Public Licence</a>. 
Son code source est téléchargeable à
<p><center><tt>
<a href=http://wims.unice.fr/download/wims>http://wims.unice.fr/download/wims</a>
</center> <p></tt>
&copy; 1997-2000- Auteur du programme de serveur&nbsp;:
!mailurl xiao@unice.fr XIAO, Gang\
WIMS
de
<a href=http://www.unice.fr>Université de Nice - Sophia Antipolis</a>.

<p>Une traduction en version chinoise Big5 (serveur et modules) a été réalisée
par
!mailurl ychuang@cc.cktc.edu.tw Y. C. Huang
 (travail interrompu depuis).

<p>Les traductions en version chinoise continentale (serveur et modules) sont
effectuées par une équipe dirigée par
!mailurl zjchen@math.ecnu.edu.cn CHEN, Zhijie
.

<p>Les traductions en version italienne (serveur et modules) sont effectuées par
!mailurl marina.cazzola@unimib.it Marina Cazzola
.

<p>Chaque module sous Wims a sa propre politique de droit d'auteur, qui
peut être différente de celle du serveur. Veuillez consulter les pages
appropriées du module en question pour voir cette politique.

<p>Le code source des modules librement distribuables est disponible à la
même adresse ftp que le programme du serveur.

<p>Certains modules peuvent utiliser des logiciels commerciaux pour leur
fonctionnement. C'est la responsabilité du gestionnaire du site de s'assurer
avec le vendeur du logiciel qu'une telle utilisation est conforme à la
politique de licence du logiciel, s'il veut installer le module sur son site.


