
Un des types principaux d'activités sur WIMS est les exercices interactifs.
<p>
Ces exercices peuvent prendre des styles variés. Par exemple,
!href target=wims_demo module=H5/geometry/gravshoot Tir de gravité
 vous demande de cliquer sur un dessin et donne une note selon la distance
entre votre clic et la bonne position&nbsp;;
!href target=wims_demo module=H6/geometry/coincfree Coincidence Libre
 présente une courbe et vous demande d'entrer une fonction dont la courbe
 est aussi proche que possible, vous autorisant plusieurs essais&nbsp;;
!href target=wims_demo module=U1/analysis/graphder Dérivée Graphique
 donne le graphe d'une fonction et vous demande de reconnaître celui de
la dérivée de cette fonction&nbsp;;
!href target=wims_demo module=H6/analysis/scenarineq Scénario d'inégalités
 présente un argument commenté étape par étape et vous demande de repérer
des étapes erronées&nbsp;;
!href target=wims_demo module=H6/algebra/decrypt Décrypt
 montre un message crypté et vous laisse le reconstituer par des 
expériences étape par étape&nbsp;; etc.
<p>
Il y a aussi beaucoup de collections d'exercices OEF (Open Exercise Format),
chacun collectionnant un nombre d'exercices plus traditionnels sur un thème
donné. Vous pouvez sélectionner un sous-ensemble des exercices de chaque
paquet pour travailler dessus. Les enseignants peuvent aussi 
!href module=$module&chapter=4&open=$open,4_oef#oef créer
 leurs propres exercices OEF directement en ligne.
<p>
La plupart des exercices interactifs sur WIMS sont configurables avec
différents niveaux de difficulté et styles. La configuration de l'exercice est
faite dans une page d'introduction, de sorte qu'une fois que vous avez commencé
à travailler sur l'exercice, le niveau de difficulté va rester stable.
<p>
Ceci est important parce que les exercices WIMS sont faits pour être répétés.
Vous pouvez redemander le même exercice encore et encore, et chaque fois en
obtenir un avec des paramètres différents. D'un côté, ceci vous permet de
vous exercer sur cet exercice jusqu'à ce que vous obteniez la bonne
connaissance&nbsp;; d'un autre côté, quand les étudiants travaillent côte à
côte sur un même exercice (dans une salle informatique),
le risque de copie est réduit au minimum.
<p>
Quand vous finissez un exercice, WIMS vous attribue une note selon votre
degré de succès. La note va de 0 (échec total) à 10 (réussite complète).
Quand vous vous êtes loggé en tant que participant dans une classe et
travaillez sur un exercice désigné par l'enseignant, cette note sera
enregistrée par le serveur. Le serveur peut analyser les notes de chaque
participant et les présente à l'enseignant de différentes façons, en temps
réel.
<p>
Notez que certains exercices peuvent être organisés en ``séances'' composées
d'un nombre donné de questions. Dans ce cas, la note est attribuée
uniquement à la fin de la séance (mais pas à la fin de chaque question), et
sera normalement calculée selon votre degré de réussite à toutes les
questions dans la séance dans son ensemble. Et le nombre de questions dans
une séance est normalement configurable dans la page d'introduction de
l'exercice.

