
WIMS (WWW Interactive Multipurpose Server)
vous permet de faire du travail interactif sur Internet dans de nombreux domaines.
<p>
Contrairement à la plupart des activités interactives sur l'Internet qui font appel
à java ou javascript, WIMS traite vos requêtes interactivement sur le site 
serveur. Ce qui lui donne l'avantage de pouvoir faire des calculs hautement
sophistiqués pour vous.
<p>
Pour un utilisateur ordinaire, WIMS est un site web comme tout autre site web.
Sur ce site, vous pouvez consulter cours interactifs, répondre aux exercices
mathématiques, faire des calculs et tracer courbes ou surfaces, ou jouer aux
jeux mathématiques, en cliquant sur des boutons ou des dessins comme sur
toute autre page web.
<p>
En cliquant sur des boutons ou des dessins, vous envoyez une ``requête'' au
serveur, qui calcule votre requête et vous retourne le résultat. Les calculs
sont souvent si puissants et si sophistiqués que vous ne les avez peut-être
jamais imaginés possibles via quelques simples clics.
<p>
Quelquefois, javascript et/ou des applets java sont aussi utilisés pour
renforcer cette interactivité.
<p>
La structure de WIMS est particulièrement intéressante pour les activités
d'enseignement, dans lesquelles le serveur peut analyser individuellement le
comportement d'étudiants/élèves, et proposer des activités à chacun d'eux
suivant son besoin d'apprentissage.

