!read tabletheme
Quand vous travaillez avec WIMS, vous aurez souvent besoin d'entrer des
expressions mathématiques.
<p>
Ces expressions mathématiques peuvent être tapées de façon habituelle&nbsp;:
<span class="tt">3*x+5</span> pour
!htmlmath 3x+5
, <span class="tt">sin(pi*x)</span> pour
!htmlmath sin(pi*x)
, <span class="tt">y^3+1</span> pour
!htmlmath y^3+1
, <span class="tt">(x+1)/(y-1)</span> pour
!set ins_align=middle
!insmath {x+1 \over y-1}
, etc.
</p><p>
De plus, WIMS contient un analyseur intelligent capable de corriger des
``erreurs'' communes dans les expressions mathématiques. Par exemple,
<span class="tt">3x+5</span>
sera corrigé en <span class="tt">3*x+5</span>, <span class="tt">sin x</span> corrigé en
<span class="tt">sin(x)</span>, etc. Mais nous ne vous conseillons pas de vous appuyer trop
fort sur ce correcteur, car des ambiguïtés dans les expressions
peuvent conduire parfois à des interprétations erronées. Il sera toujours mieux
de taper les expressions de façon ``correcte'', même si cela est parfois un
peu gênant.
</p><p>
Voici une liste de fonctions mathématiques et la façon (correcte) de les
entrer. Ces fonctions sont reconnues par WIMS partout où elles ont un sens.
(Certains modules peuvent accepter des fonctions supplémentaires&nbsp;;
veuillez consulter les pages d'aide de ces modules.)
</p><p>
!set x=x
Vous pouvez remplacer $x par toute sous-expression dans le tableau ci-dessous.
</p>
$table_header
$table_tr<th>fonction</th><th>description</th><th>comment taper</th></tr>
$table_tr<td>$m_pi</td>
    <td>constante bien-connue</td><td>
    <span class="tt">pi</span> ou <span class="tt">Pi</span> ou <span class="tt">PI
    </span></td></tr>
$table_tr<td><i>e</i></td><td>base de log naturelle</td><td>
    <span class="tt">e</span> ou <span class="tt">E</span></td></tr>
$table_tr<td>|$x|</td><td>valeur absolue de $x</td><td><span class="tt">abs(x)</span></td></tr>
$table_tr<td>sign($x)</td><td>signe de $x:
       <br/>&nbsp;=-1 si $x&lt;0<br/>&nbsp;=0 si $x=0<br/>&nbsp;=1 si $x>0
       </td><td><span class="tt">sign(x)</span></td></tr>
$table_tr<td>
    !instex $$ \sqrt x $$
    </td><td>racine carrée de $x</td>
    <td><span class="tt">sqrt(x)</span> ou <span class="tt">x^(1/2)</span></td></tr>
$table_tr<td>
!instex $$ [ x ] $$
</td><td>l'entier le plus proche de $x</td><td><span class="tt">rint(x)</span></td></tr>
$table_tr<td>
!instex $$ \lfloor  x \rfloor $$
</td><td>le plus grand entier $m_le$x</td><td><span class="tt">floor(x)</span></td></tr>
$table_tr<td>
!instex $$ \lceil  x \rceil $$
</td><td>le plus petit entier $m_ge$x</td><td><span class="tt">ceil(x)</span></td></tr>
$table_tr<td>e<sup>x</sup></td><td>exponentiel</td><td>
    <span class="tt">exp(x)</span> ou <span class="tt">e^x</span> ou <span class="tt">E^x</span></td></tr>
$table_tr<td>ln($x)</td><td>log naturel</td><td><span class="tt">log(x)</span> ou <span class="tt">ln(x)</span></td></tr>
$table_tr<td>lg($x)</td><td>log de base 10</td><td><span class="tt">lg(x)</span> ou <span class="tt">log10(x)</span></td></tr>
$table_tr<td>sin($x)</td><td>sinus trigonométrique</td><td><span class="tt">sin(x)</span></td></tr>
$table_tr<td>cos($x)</td><td>cosinus trigonométrique</td><td><span class="tt">cos(x)</span></td></tr>
$table_tr<td>tg($x)</td><td>tangente trigonométrique</td><td><span class="tt">tan(x)</span> ou <span class="tt">tg(x)</span></td></tr>
$table_tr<td>ctg($x)</td><td>cotangente trigonométrique</td><td><span class="tt">cotan(x)</span> ou <span class="tt">ctg(x)
    </span> ou <span class="tt">cot(x)</span></td></tr>
$table_tr<td>arcsin($x)</td><td>inverse trigonométrique</td><td><span class="tt">asin(x)</span> or
    <span class="tt">arcsin(x)</span></td></tr>
$table_tr<td>arccos($x)</td><td>inverse trigonométrique</td><td><span class="tt">acos(x)</span> or
    <span class="tt">arccos(x)</span></td></tr>
$table_tr<td>arctg($x)</td><td>inverse trigonométrique</td><td><span class="tt">atan(x)</span> or
    <span class="tt">arctan(x)</span> ou <span class="tt">arctg(x)</span></td></tr>
$table_tr<td>sh($x)</td><td>sinus hyperbolique</td><td><span class="tt">sh(x)</span> ou <span class="tt">sinh(x)</span></td></tr>
$table_tr<td>ch($x)</td><td>cosinus hyperbolique</td><td><span class="tt">ch(x)</span> ou <span class="tt">cosh(x)</span></td></tr>
$table_tr<td>th($x)</td><td>tangente hyperbolique</td><td><span class="tt">th(x)</span> ou <span class="tt">tanh(x)</span></td></tr>
$table_tr<td>Argsh($x)</td><td>inverse hyperbolique</td><td><span class="tt">asinh(x)</span> ou <span class="tt">argsh(x)</span> ou <span class="tt">Argsh(x)</span></td></tr>
$table_tr<td>Argch($x)</td><td>inverse hyperbolique</td><td><span class="tt">acosh(x)</span> ou <span class="tt">argch(x)</span>
    ou <span class="tt">Argch(x)</span></td></tr>
$table_tr<td>Argth($x)</td><td>inverse hyperbolique</td><td><span class="tt">atanh(x)</span> ou <span class="tt">argth(x)</span>
    ou <span class="tt">Argth(x)</span></td></tr>
$table_tr<td>max(x,y)</td><td>le plus grand entre x et y</td><td><span class="tt">max(x,y)</span></td></tr>
$table_tr<td>min(x,y)</td><td>le plus petit entre x et y</td><td><span class="tt">min(x,y)</span></td></tr>
$table_tr<td>gcd(x,y)</td><td>pgcd</td><td><span class="tt">gcd(x,y)</span></td></tr>
$table_tr<td>lcm(x,y)</td><td>ppcm</td><td><span class="tt">lcm(x,y)</span></td></tr>
</table>


