
WIMS contient divers outils mathématiques en ligne (calculatrices, traceuses),
pour des sujets allant des calculs numériques élémentaires à des traceuses
animées et à des calculatrices avancées sur des sujets spéciaux.
<p>
Vous pouvez
!href module=home&list=2#list2 cliquer ici
 pour la liste complète d'outils en ligne sur ce site, ou
!href module=home&list=9000 rechercher
 un outil particulier.

