
Pour l'instant, WIMS soutient deux principales catégories d'activités&nbsp;:

<ol>
<li><p>
!href module=$module&chapter=$chapter&open=$open,$(chapter)_exo#exo Exercices interactifs
 vous permettant de pratiquer vos connaissances.
 <p>

<li><p>
!href module=$module&chapter=$chapter&open=$open,$(chapter)_tool#tool Outils de calcul ou de graphisme
 pour vous aider à résoudre vos problèmes.

</ol> <p>

Il y a aussi quelques pièces de récréation de différents styles.
<p>
Vous pouvez
!href module=home&list=9000 faire une recherche
 sur ce site pour des activités qui vous intéressent.
<p>
Des enseignants peuvent installer des
!href module=$module&chapter=3 classes virtuelles
 et sélectionner des activités pour mettre dans la classe, afin que leurs
étudiants/élèves puissent se logger dans la classe, travailler sur
les activités désignées par l'enseignant et obtenir des notes qui seront
ensuite contrôlées par l'enseignant.

