
!set wims_form_method=post
!form reply
 Dit hulpprogramma is bedoeld voor het online ontwikkelen van speciale WIMS modules,
 en is alleen toegankelijk voor mensen met een <b>ontwikkelaar-account</b> op deze server.
 <p>
 Geef hier s.v.p. uw "ontwikkelaars authentificatie".
 <small>(
 !mailurl $wims_site_manager stuur een email naar de systeembeheerder\
$module password
 als u het wachtwoord vergeten bent.)</small>
 <p><center><table border=0>
 <tr><td align=right>Login naam: <td><input size=20 name=login value="$auth_login">
 <tr><td align=right>Wachtwoord: <td><input type=password size=20 name=passwd>
 $table_end
 <p><center>
 <input type=submit value="OK en Versturen">
 </center>
</form>

<b>Opmerking.</b> Bent U geinteresseerd in het maken van WIMS modules, 
!mailurl $wims_site_manager schrijf dan naar de systeembeheerder\
WIMS new developer
 voor een account (login naam en wachtwoord).
<p>
 U kunt altjd vrijblijvend en <em>zonder</em> speciaal account
!href module=adm/createxo Createxo
 gebruiken om zeer snel interactieve WIMS oefeningen te maken. 

<p>
!set wims_menu_items=!append line createxo,1,module=adm/createxo\
to $wims_menu_items

