
Weet U zeker dat deze module verwijderd moet worden?
<em><font color=blue>
!module title devel/$auth_login/$mod
</em></font> (<tt>$modreq</tt>)?
<p>
<big><center>
!href cmd=reply&jobreq=del&confirm=yes Ja
&nbsp;&nbsp;
!href cmd=reply&jobreq=flist Nee
</center></big>
<p>
<b><font color=red>WAARSCHUWING!</font></b> Verwijderde modules zijn definitief weg !
Maak dus eerst een
!href cmd=reply&jobreq=backup  backup
!
<p>
<b>Attentie</b>: wanneer deze module nog in gebruik is in <em>werkbladen, repetities of documenten</em>
 wordt dit lesmateriaal dus <font color="red">onbruikbaar</font> !

