
<p>
!if $totalcnt>0
 !if $totalcnt>=$sellist
  U hebt $totalcnt modules in bewerking.
  !href cmd=reply&jobreq=prop <small>Eigenschappen van mijn account</small>
  <p>
  !form reply
  Laat alleen modules zien waarvan het adres bevat
  <input type=text size=30 name=selectshow value="$selectshow">
  <input type=submit value=OK>
  !href cmd=help&special_parm=regex <sup>help</sup>
  </form> <p>
 !endif
 $table_header
 <caption>Klik op de titel van een module, om deze te gaan bewerken.
 !if $totalcnt>=$maxlist and $existcnt>=$maxlist
  <br>(lijst beperkt tot $maxlist items)
 !endif
 </caption>
 $table_hdtr<th>Adres<th>Titel<th>Actie<th>Omschrijving
 </tr>
 !for n in $existing
  !readdef wimshome/public_html/modules/devel/$auth_login/$n/INDEX
  $table_tr<td><small>
  !replace internal ~ by ~ $ in $n $
  !if ~ notin $n
   !href cmd=reply&jobreq=move&original=devel/$auth_login/$n [hernoemen]
  !endif
  </small></td><td>
  !href cmd=reply&jobreq=flist&modreq=$n $title
  <td align=center><small>
  !href cmd=reply&jobreq=index&modreq=$n eigenschappen

  !href cmd=reply&jobreq=del&modreq=$n verwijderen
  </small></td><td><small>$description</small></td>
  </td></tr>
 !next n
 $table_end <p>
 !href cmd=reply&jobreq=create Maak een nieuwe module
 .&nbsp;
 !href cmd=reply&jobreq=restore Zet een backup-file terug
 .&nbsp;gebruik&nbsp;
 !href cmd=new&module=adm/quicktool Quicktool
 .&nbsp;gebruik&nbsp;
 !href cmd=new&module=adm/latex2wims Latex2wims                                                                                    
 .                                                       
!else
U hebt nog geen modules onder ontwikkeling.
S.v.p.
 !href cmd=reply&jobreq=create klik hier
 om een nieuwe module te maken, of
 !href cmd=reply&jobreq=restore zet een backup-file terug
.
!endif

!reset target target1 target2 target3 target4 selectshow

