
!set sp2=$special_parm2
!bound sp2 within secure,supervisor,email,lang,level,limit,expiration,modtoolchg,\
	bgcolor,homepage,bgimg,theme,css,theme_icon,logo,lock,exolog,examlog,examshow,ent,option,authtype,topscores\
    default $

!if $sp2=$empty
 !exit
!endif

!goto $sp2

:secure
<b>安全主机</b>.
你的主持教师的密码完全有可能泄漏: 当你在教室里以主持教师的身份连接班级时,
学生可能从你后面窥探, 甚至安装一个键盘扫描软件以记录你的击键动作.
请相信我, 如果你的班级里有成绩记录的话, 主持教师密码就是引人注意的目标. 
<p>
泄漏的后果是灾难性的: 数据可能破坏, 分数被修改, 甚至当有人修改你的密码后,
你再也无法进入班级.
<p>
定义安全主机可以增加额外的屏障: 敏感的操作如班级的配置、密码修改、
分数修改等都必须从预先定义的<em>安全主机</em>发出,
只要学生无法接近这些主机, 即使他们知道了密码, 也干不了大事.
<p>
!read help/hosts.phtml
<p>
此外, 如果你需要在非常不安全的环境里(例如使用学生的计算机)输入密码,
你应该考虑使用一次性密码(参见有关网页).
!exit

:supervisor
 <b>主持教师姓名</b>. 输入(你喜欢的)名字.
!exit

:email
 <b>主持教师电邮地址</b>.
重要的通知(密码, 过期通知等)都将发到此地址.
这也是学生向你发信的地址. 因此必须是有效地址, 否则你可能失去对班级的控制.
!exit

:option
 <b>班级的选项词</b>. 可使用的选项词为:
 <ul>
 <li><tt>showshexpire</tt>. 在参加者主页上显示作业页的有效期.
 <li><tt>showexexpire</tt>. 在参加者主页上显示考试页的有效期.
 <li><tt>showshweight</tt>. 在参加者主页上显示作业页的权重.
 </ul> 
!exit

:lang
You may choose the class language among those supported 
by your wims site. Your class will then appear in the corresponding list of classes 
of the student's and teacher's areas.<br>
Abbreviations used : <ul>
 <li>ca (Catalan)
 <li>cn (简体中文)
 <li>de (German)
 <li>en (英语)
 <li>es (西班牙语)
 <li>fr (法语)
 <li>it (意大利语)
 <li>nl (荷兰语)
 <li>si (Slovenian)
 <li>tw (Chinese big5)
</ul>
!exit

:level
程度: <ul>
 <li>E1 - E6: 小学1至6年级.
 <li>H1 - H6: 中学1至6年级.
 <li>U1 - U5: 大学1至5年级.
 <li>G: 大学, 研究生
 <li>R: 研究工作
</ul>
!exit

:limit
 <b>参加者人数限制</b>. 达到这个限制后, 新参加者将被拒绝注册.
本网站已经定义了一个不能超过的硬性上限($wims_class_user_limit).
!exit

:expiration
 <b>有效期</b>. 过了有效期后班级就会关闭. 任何时候你都可以延长有效期,
不过不能超过一年后的今天.
<p>
如果你想规定一年以上的有效期, 你可以分几次延长, 或者
 <a href="mailto:$wims_site_manager?subject=虚拟班级延长请求">要求网站管理员</a>帮你做.
 <p>
日期表示成8位数字的形式 (yyyymmdd).
例如: 20120523 意为2012年5月23日.
!exit

:bgcolor
 <b>网页背景色及菜单颜色</b>. 这两种颜色可以使你轻易地在虚拟班里认出网页来.
它们按照 html 的规定取值.
 <p>
 <b>Link color in menus and tables</b>. You may adapt the link color to the
    menu background color. If you choose this option, it is wise to fill in explicitely 
    the table background color even if it is the same as the default one (in case the 
default would change).
 <p>
 Default values are those defined for the general site pages.
!exit

:homepage
 <b>参加者主页</b>. 你可以把文件块的地址(例如 <tt>c1/main</tt>)置为参加者班级的主页.
参加者不一定能阅读此文件.
 <p>
如果你使用标准主页, 则可将此栏留空.
 <p>
块内所有链接都应该用命令 <tt>\adm</tt> 定义.
你可以使用下列预定义的变量:<ul>
 <li><tt>\firstname</tt> 参加者的名</li>
 <li><tt>\lastname</tt> 参加者的姓</li>
 <li><tt>\scores</tt> 参加者的分数信息. 这是一个数表, 每一页对应一对数:
得分百分比及质量.</li>
 <li><tt>\newmsgcnt</tt> 班级论坛内未阅读信息.</li>
 <li><tt>\today</tt> 今天日期, yyyymmdd.</li>
 <li><tt>\sheets</tt> 作业页数.</li>
 <li><tt>\exams</tt> 考试页数.</li>
 <li><tt>\expiration1</tt>, <tt>\expiration2</tt>, <tt>\expirationE1</tt>, ...
第1页, 第2页, 考试第1页, ... 的有效日期, yyyymmdd.</li>
 <li><tt>\status1</tt>, <tt>\status2</tt>, <tt>\statusE1</tt>, ...
第1页, 第2页, 考试第1页, ... 的状态, 这是一个非负整数: 
0 = 准备中, 1 = 激活, 2 = 过期, 3= 隐藏.</li>
 <li><tt>\daymessage</tt> : 班级的每日信息.</li>
 <li><tt>\userdaymessage</tt> : 每个参加者的个人每日信息.</li>
 </ul>
!goto end

:bgimg
班级网页的背景图像文件(平铺式). 你可以使用任何有效的 URL.
也有已做好的背景图像文件, 使用时不必加任何地址前缀:<p>
 <tt>$bgimgs</tt>
!exit

:theme
你的班级的格式主题.
!exit

:theme_icon
出现在菜单上的图标.
!exit

:css
格式页(css)几乎对班级的所有网页都起作用.
<p>
选择 `<tt>----</tt>' 不使用格式页.
<p>
选择 `<tt>-theme-</tt>' 使用与你选取的主题相应的格式页.
<p>
选择 `<tt>class</tt>' 使用自定义的格式页. 请参看 css 文件的语法.
<p><b>说明</b>. 如果你自定义 css, 请对学生使用的各种浏览器一一测试,
以避免出现不兼容情况.
你可以使用自己的格式页. 
以下改变格式的格式页可被重新定义 :
<pre>
!read  wimshome/public_html/bases/sys/css_classes
</pre>
<p>
其余选择对应于此 WIMS 站预定义的格式.
!exit

:logo
班级的图标是显示在班级主页的左或右上角的图形. 
<p>
如不想显示图标, 则选择 `<tt>none</tt>'.
<p>
如果选择空串或 `<tt>wims</tt>', 将使用WIMS图标.
<p>
否则你也可以使用有效图形文件的 URL.
!exit

:lock
连接锁定可帮助追踪用户以及反作弊. 共有8个等级.<ul>
<p><li>0: 不使用连接锁定.

<p><li>1: 激活 cookie 追踪. 没有返回正确 cookie 的连接将被拒绝.

<p><li>2: 要求使用安全连接(https). 通常的 http 请求将被拒绝.
首先你要从网站管理员那里确认此WIMS站能接受 https 连接.

<p><li>3: 激活主机地址锁定. 在一次对话中参加者不能改变主机地址.
当连接来自动态分配的IP地址时, 这样做有困难.

<p><li>4: Cookie 追踪 + https.
<p><li>5: Cookie 追踪 + 主机锁定.
<p><li>6: 激活上述所有方法.
<p><li>7: 关闭班级. 不接受参加者的连接.
</ul> <p>
!exit

:exolog
练习记录数(不超过$wims_exolog_limit)
<p>
这是能对每个参加者的细节都加以记录的练习数上限.
<p>
这些细节使得参加者与主持教师能够回放解题活动并作评论.
<p>
仅当参加者给出命令时练习的细节才被记录. 当超过上限时,
最早的记录将被删除.
!goto logs

:examlog
考试记录数(不超过$wims_examlog_limit)
<p>
这是能对每个参加者的细节都加以记录的考试对话上限.
<p>
这些细节使得参加者与主持教师能够对逐个练习回放解题活动.
<p>
考试对话的记录是自动的. 当超过上限时,
最早的记录将被删除.
!exit

:logs
<p>
当这个数等于 0 时, 将不作记录.
<b>注意</b> 练习和考试的纪录会耗用大量空间!
如果这个界限取得太大, 将会造成班级的盘空间超限.
!exit

:examshow
如果把这个选项设置为 <tt>否</tt>, 学生将不能看到
考试成绩. 只有教师能看到.
!exit

:authtype
<b>身份验证的类型</b> : 
你可以通过 ldap 或 wims 作身份验证.
当 ldap 验证失败时, 就尝试通过 wims 内部过程作验证.
<p>
ldap 验证的参数的例 :
<pre>
ldap_host=ldap.u-psud.fr
ldap_port=389
ldap_version=3
ldap_base=ou=people,dc=u-psud,dc=fr
ldap_branch=ou=people,dc=u-psud,dc=fr
ldap_uid=uid
ldap_login=supannAliasLogin
</pre>
!exit

:modtoolchg
<b>模块开发工具(Modtool)的帐户</b> : 
当你通过班级进入模块开发工具后, 也就注册了你的模块开发工具帐户.
如果你需要使用另一个模块开发工具帐户, 你可以在这里注销此注册.
然后你应该通过主页内的 <tt>模块开发工具(Modtool)</tt> 链接以进入此工具.

!exit

:ent
<b>平台上或网页上的连接</b> :
你可以用以下形式指示平台上或网页上的连接
<pre>连接的标题,连接的地址</pre>
例如,
<pre>Dokeos,http://----</pre>
如果你要放几个连接, 请用分号作分隔.

!exit

:topscores
<center><b>Best scores, number and anonymity</b></center>
<p> If this number n is at least 1, then  when a participant asks for 
its score, he will see also the list of n participants having the best scores
(with their names if anonymity=yes, with numbers only if anonymity=no).<p>
These means do not take into account the manual scores, hence leave n=0 if there are manual 
scores.
<p>
Default=0/$wims_name_yes

!exit

:end

