!! Permalien / lecteur exportable : ces lignes permettent d'integrer facilement la page courante a un autre site :

!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module
!if $module_path notitemof home,adm,classes and _exam notin $session and $wims_lightpopup!=yes and ($wims_user=supervisor or $wims_user=$empty) and ($cmd=intro or $cmd=$empty)
 !set permalien=$wims_ref_name?module=$module

!!# Si les librairies Jquery sont chargées, on fait un "slide".
!if $jquery_defined=yes
 !set js_show_export = jQuery('#export_media').toggle();
 !set js_hide_export = jQuery('#export_media').slideUp();
!else
 !set js_show_export = document.getElementById('export_media').style.display = 'block';document.getElementById('lien_export_media').style.display = 'none';
 !set js_hide_export = document.getElementById('export_media').style.display = 'none';document.getElementById('lien_export_media').style.display = 'block';
!endif

 <!-- _widgets/permalink.phtml -->
 <$div0 class="menuitem share" id="header_export">
  <a href="#wimstopbox" class="about" id="lien_export_media" onclick="$js_show_export">$wims_name_display1</a>
 </$div0>

 <div id="export_media" style="display:none;position:absolute;">
 <fieldset  class="property_fields">
    <a href="#wimstopbox" onclick="$js_hide_export" class="wims_button icon_button small"><span class="back">$wims_name_Close</span></a>

   <legend>$wims_name_display1</legend>

   <div class="field">
    <label for="wims_permalink">$wims_name_permalink1</label>
    <div class="formHelp">$wims_name_display2</div>
    <input id="wims_permalink" name="wims_permalink" value="$permalien" size="70"/>
   </div>

   <hr/>

   <div class="field">
    <label for="wims_embed_textarea">$wims_name_embeddable</label>
    <div class="formHelp">$wims_name_display3</div>
    <textarea style="vertical-align:middle" rows="3" cols="50" readonly="readonly" id="wims_embed_textarea" name="wims_embed_textarea" >&lt;iframe src="$permalien&+embededwindow=true" title="WIMS embeddable" frameborder="0" class="wims_embed" style="width:100%;height:100%;min-height:800px;" allowfullscreen>&lt;/iframe></textarea>
   </div>

 </fieldset>
</div><!--export_media-->


<!-- end _widgets/permalink.phtml -->
!endif
