
$table_hdtr<th rowspan=2>Class name
<th colspan=2>Neighborhood<br>declaration</b><small>
!href cmd=help&special_parm=neibordecl help
</small>
<th rowspan=2>Resource sharing</b><small>
!href cmd=help&special_parm=share $wims_name_help
</small>
<th rowspan=2>Supervisor
<th rowspan=2>$wims_name_language
$table_hdtr<td align=center><small>by you</small>
<td align=center><small>by the other</small>
!for i in $clst
 !set D_=!defof class_institution\
class_description\
class_lang\
class_supervisor in wimshome/log/classes/$i/.def
 !distribute lines $D_ into i_,d_,l_,s_
 !set t_=0
 !if $i isitemof $n_sup
  !advance t_
 !endif
 !if $i isitemof $n_part
  !set t_=$[$t_+2]
 !endif
 $table_tr
 <td align=center>
  !href cmd=reply&job2=def&nei=$i&nlevel=$t_ $i_<br>$d_
 </td>
 <td align=center>$(n_n$t_)</td>
  !set t_=0
  !set D_=!defof n_sup\
n_part\
sharable_all\
sharing_all in wimshome/log/classes/$i/neighbors
  !distribute line $D_ into sup,part,nsharable,nsharing
  !if $wims_class isitemof $sup or all isitemof $sup
   !advance t_
  !endif
  !if $wims_class isitemof $part or all isitemof $part
   !set t_=$[$t_+2]
  !endif
  <td align=center>$(n_n$t_)</td>
  !if $i notitemof $sharable_all,$sharing_all and\
	$wims_class notitemof $nsharable,$nsharing
  <td align=center>---</td>
 !else
  <td>
  !if $i isitemof $sharing_all or $wims_class isitemof $nsharing
   !if $i isitemof $sharing_all and $wims_class isitemof $nsharing
    Active mutually sharing.
   !else
    !if $i isitemof $sharing_all
     You are sharing its resources.
    !else
     Sharing your resources.
    !endif
   !endif
  !else
   !if $i isitemof $sharable_all and $wims_class isitemof $nsharable
    Mutually allowing sharings.
   !else
    !if $i isitemof $sharable_all
     Allowed to share your resources.
    !else
     Allows you to share its resources.
    !endif
   !endif
  </td>
 !endif
 <td align=center><small>$s_</small></td>
 <td align=center>$l_</td>
</tr>
!next i

