
<p>所有的比较都在串上进行: <tt>string1 rel string2</tt>.
可以利用 <tt>and</tt> 与 <tt>or</tt> 把比较结合起来. 
还可以利用括号以构成复杂的比较式.<p>
有效的关系 <tt>rel</tt>:
  <p>$table_header
   $table_tr<td align=center>关系<td align=center>条件
   $table_tr<td align=center><tt> = </tt> 或 <tt>==</tt><td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 完全相同.
   $table_tr<td align=center><tt> != </tt> 或 <tt>&lt;&gt;</tt>
    <td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 不相同.
   $table_tr<td align=center><tt> < </tt><td>true(真), 如果两个串的数值
       <tt> string1 </tt> < <tt> string2 </tt>.
   $table_tr<td align=center><tt> <= </tt><td>true(真), 如果两个串的数值
       <tt> string1 </tt> $m_le <tt> string2 </tt>.
   $table_tr<td align=center><tt> > </tt><td>true(真), 如果两个串的数值
       <tt> string1 </tt> > <tt> string2 </tt>.
   $table_tr<td align=center><tt> >= </tt><td>true(真), 如果两个串的数值
       <tt> string1 </tt> $m_ge <tt> string2 </tt>.
   $table_tr<td align=center><tt> isin </tt><td>true(真), 若 <tt> string1
       </tt> 是 <tt> string2 </tt> 的子串.
   $table_tr<td align=center><tt> notin </tt><td>true(真), 若 <tt> string1
       </tt> 不是 <tt> string2 </tt> 的子串.
   $table_tr<td align=center><tt> iswordof </tt><td>true(真), 若 <tt> string1
       </tt> 是 <tt> string2 </tt> 的一个词.
   $table_tr<td align=center><tt> notwordof </tt><td>true(真), 若 <tt> string1
       </tt> 不是 <tt> string2 </tt> 的一个词.
   $table_tr<td align=center><tt> isvarof </tt><td>true(真), 若 <tt> string1
       </tt> 是表达式 <tt> string2 </tt> 的一个(数学)变量.
   $table_tr<td align=center><tt> notvarof </tt><td>true(真), 若 <tt> string1
       </tt> 不是表达式 <tt> string2 </tt> 的一个(数学)变量.
   $table_tr<td align=center><tt> isvariableof </tt><td>true(真), 若 <tt> string1
       </tt> 是表达式 <tt> string2 </tt> 的一个(数学)变量.
   $table_tr<td align=center><tt> notvariableof </tt><td>true(真), 若 <tt> string1
       </tt> 不是表达式 <tt> string2 </tt> 的一个(数学)变量.
   $table_tr<td align=center><tt> isitemof </tt><td>true(真), 若 <tt> string1
       </tt> 是表 <tt> string2 </tt> 的一项.
   $table_tr<td align=center><tt> notitemdof </tt><td>true(真), 若 <tt> string1
       </tt> 不是表 <tt> string2 </tt> 的一项.
   $table_tr<td align=center><tt> islineof </tt><td>true(真), 若 <tt> string1
       </tt> 是表 <tt> string2 </tt> 的一行.
   $table_tr<td align=center><tt> notlinedof </tt><td>true(真), 若 <tt> string1
       </tt> 不是表 <tt> string2 </tt> 的一行.
   $table_tr<td align=center><tt> issamecase </tt><td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 有相同的文字, 比较时不考虑多余的空格, 但是区别大小写字母.
   $table_tr<td align=center><tt> notsamecase </tt><td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 有不相同的文字, 比较时不考虑多余的空格, 但是区别大小写字母.
   $table_tr<td align=center><tt> issametext </tt><td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 有相同的文字, 比较时不考虑多余的空格、大小写字母及有重音号的字母.
   $table_tr<td align=center><tt> notsametext </tt><td>true(真), 若 <tt> string1
       </tt> 与 <tt> string2 </tt> 有不相同的文字, 比较时不考虑多余的空格、大小写字母及有重音号的字母.
  
  $table_end<p>

