
<p><center><h2>参数函数表</h2></center>

<p>$table_header
<caption>随机化</caption>
$table_tr<th>函数</th><th>效果</th></tr>
$table_tr<td><tt>random(-5..5)</tt>
    </td><td>-5 与 5 之间的随机数</td></tr>
$table_tr<td><tt>randint(-5..5)</tt>
    </td><td>-5 与 5 之间的随机整数(包括两端)</td></tr>
$table_tr<td><tt>random(1,2,3,a,b,c)</tt>
    </td><td>{1,2,3,a,b,c} 里随机选一项</td></tr>
$table_tr<td><tt>shuffle(6)</tt>
    </td><td>6 个整数 1,2,...,6, 的随机排列</td></tr>
$table_tr<td><tt>shuffle(a,b,c,d,e)</tt>
    </td><td>字母 {a,b,c,d,e} 的随机排列</td></tr>
$table_tr<td><tt>randomitem(\list)</tt>
    </td><td>在(逗号分隔的)表 \list 内随机选一项</td></tr>
$table_tr<td><tt>randomrow(\mat)</tt>
    </td><td>矩阵 \mat 内随机选一行</td></tr>
$table_end
<p>$table_header
<caption>数据与表的操作</caption>
$table_tr<td><tt>items(a,b,c,d,e,f)</tt>
    </td><td>表 {a,b,c,d,e,f} 的项数(这里是 6)</td></tr>    
$table_tr<td><tt>item(3,a,b,c,d,e,f)</tt>
    </td><td>表 {a,b,c,d,e,f} 的第 3 项(这里是 c)</td></tr>
$table_tr<td><tt>item(3,\ll)</tt>
    </td><td>表 \ll 的第 3 项(同 <tt>\ll[3]</tt>)</td></tr>
$table_tr<td><tt>item(2..5,a,b,c,d,e,f)</tt>
    </td><td>表 {a,b,c,d,e,f} 的第 2 至 5 项(这里是 b,c,d,e)</td></tr>
$table_tr<td><tt>item([2,4],\ll)</tt>
    </td><td>表 \ll 的第 2 及第 4 项(同 <tt>\ll[2,4]</tt>)</td></tr>
$table_tr<td><tt>position(make,do,go,make,take)</tt>
    </td><td>项 `make' 在表 {do,go,make,take} 里的位置(这里是 3)</td></tr>
$table_tr<td><tt>rows(\m)</tt>
    </td><td>矩阵 \m 的行数</td></tr>
$table_tr<td><tt>row(2,\m)</tt>
    </td><td>矩阵 \m 的第 2 行(同 <tt>\m[2;]</tt>)</td></tr>
$table_tr<td><tt>row(2..5,\m)</tt>
    </td><td>矩阵 \m 的第 2 至 5 行构成的子矩阵(同 <tt>\m[2..5;]</tt>)</td></tr>
$table_tr<td><tt>row([1,3],1,2,3<br>3,4,5<br>5,6,7)</tt>
    </td><td>由 3&times;3 矩阵的第 1, 3 行构成的子矩阵</td></tr>
$table_tr<td><tt>row(column 1 > 1 and column 2 = good,\mat)</tt>
    </td><td>\mat 的子矩阵, 其中每行的第 1 列 > 1, 第 2 列是词 `good'</td></tr>
$table_tr<td><tt>randomitem(\list)</tt>
    </td><td>(用逗号分隔的)表 \list 的随机项</td></tr>
$table_tr<td><tt>randomrow(\mat)</tt>
    </td><td>矩阵 \mat 的随机行</td></tr>
$table_tr<td><tt>column(2,\m)</tt>
    </td><td>矩阵 \m 的第 2 列元素, 作为用逗号分隔的表(同 <tt>\m[;2]</tt>)</td></tr>
$table_tr<td><tt>column(2..5,\m)</tt>
    </td><td>\m 的第 2 至 5 列构成的子矩阵(同 <tt>\m[;2..5]</tt>)</td></tr>
$table_tr<td><tt>column([1,3],1,2,3<br>3,4,5<br>5,6,7)</tt>
    </td><td>由 3&times;3 矩阵的 1, 3 列构成的子矩阵</td></tr>
$table_tr<td><tt>asis(How do you do? item(1,2,3))</tt>
    </td><td>按原样构成字符串, 不作任何替换或解释</td></tr>

$table_end<p>$table_header
<caption>数学函数</caption>
$table_tr<td><tt>evalue(x^2+sin(y),x=3,y=4)</tt>
    </td><td>函数 x^2+sin(y)在 x=3, y=4 处赋值</td></tr>
$table_tr<td><tt>solve(x^3-3*x+1,x=0..1)</tt>
    </td><td>x^3-3x+1 在 0 与 1 间的单根</td></tr>
$table_tr<td><tt>simplify(x^5*y^3/x^2/y)</tt>
    </td><td>化简: x<sup>3</sup>y<sup>2</sup></td></tr>
$table_tr<td><tt>diff(sin(x)+cos(y),x)</tt>
    </td><td>sin(x)+cos(y) 关于 x 的导数</td></tr>
$table_tr<td><tt>int(x^2+3*x+1,x)</tt>
    </td><td>x^2+3*x+1 的原函数, 常数项不定</td></tr>
!!$table_tr<td><tt>int(t^2+3*t+1,t=1..x)</tt>
!!    </td><td>x^2+3*x+1 的原函数 g, 满足 g(1)=0</td></tr>
$table_tr<td><tt>int(t^2+3*t+1,t=0..1)</tt>
    </td><td>x^2+3*x+1 从 0 到 1 的数值积分</td></tr>
$table_tr<td><tt>det(\mat)</tt>
    </td><td>矩阵 \mat 的行列式</td></tr>
$table_tr<td><tt>htmlmath(2*x^2+3*x)</tt>
    </td><td>html 格式下此公式的最佳形式: 2x<sup>2</sup>+3x</td></tr>
$table_tr<td><tt>texmath(2*x^2+3*x)</tt>
    </td><td>表达式的TeX源码</td></tr>

$table_end<p>$table_header
<caption>高级功能</caption>
$table_tr<td><tt>pari(factor(2^101-1))</tt>
    </td><td>调用 PARI/GP: 这里是分解整数</td></tr>
$table_tr<td><tt>maxima(integrate(x^2+1,x);)</tt>
    </td><td>调用 Maxima: 这里是积分一个函数</td></tr>
$table_tr<td><tt>yacas(Taylor(x,0,10) cos(x^2+x+1))</tt>
    </td><td>调用 Yacas: 这里是计算Taylor展开式</td></tr>
$table_tr<td><tt>wims(sort items \list)</tt>
    </td><td>调用 wims 的 !sort 命令对表 \list 的项排序</td></tr>
$table_tr<td><tt>wims(listintersect \list1 and \list2)</tt>
    </td><td>调用 wims 的 !listintersect 命令得到 \list1 与 \list2 的公共项</td></tr>
$table_tr<td><tt>draw(绘图源码 ...)</tt>
    </td><td>画一个图, 绘图源码同 <tt>\draw</tt>,
    第 1 行是图形大小. 输出是图形的 URL.</td></tr>
$table_tr<td><tt>slib(matrix/invertible 3,5)</tt>
    </td><td>读入
    !href module=help/wimsdoc&subject=slib#slib WIMS slib
   的 matrix/invertible 以生成一个可逆 3x3 矩阵, 元素取值范围 5.</td></tr>
$table_end

<p>
可用的参数类型: integer(整数), real(实数), complex(复数), function(函数), text(文字), matrix(矩阵).
<p>
!exit

