
!read adm/title.phtml 1\
下载与发布服务器

!!publishname=Nice 大学发布中心
!!downloadname=Nice 大学下载中心
!set subject=Publication
!set unice=!defof publishname,sysadmin in
wimshome/public_html/bases/sys/publishcenter/unice
!set wimsedu=!defof publishname,sysadmin in
wimshome/public_html/bases/sys/publishcenter/wimsedu

如果你想下载或发布模块, 有两个 WIMS 服务站 $(unice[1]) (<tt>unice</tt> 
<a href="mailto:$(unice[2])?subject=$subject">$(unice[2])</a>) 及
$(wimsedu[1]) (<tt>wimsedu</tt> <a href="mailto:$(wimsedu[2])?subject=$subject">$(wimsedu[2])</a>)
可供使用.
如果已知模块发布所需的 WIMS 版本与服务器的版本相容,
服务器会做相应的同步更新.
如果在服务器发布的模块与服务器的 WIMS 版本不相容,
则会把模块的地址保存, 以避免其它模块用同样的地址发布.

<p>
作者必须先注册才能在发布中心发布模块.
否则只能通过已注册的作者才能使模块的发布生效.
</p>

<p>
WIMS 服务器的管理员会决定使用哪个发布中心,
并通知在他的服务器上开发模块的作者.
</p>
<p>
当模块在服务器上发布后,
它的作者有权在发布的服务器上作修改.
如果由于某种合理的原因 (例如为使用更新的 WIMS 版本)
作者想要改变模块的发布中心, 那么作者应该与发布中心的管理员联系获得授权.
</p>

<p>WIMS 服务器的管理员可以选择下载模块的服务器.
</p>
<p>
将来会增加其它下载或发布服务器.
发布中心也是下载中心, 但反之不然.
</p>