
<H3><center>在作业页展示中使用文件块</center></H3>

你可以把文件块的地址
(例如 <tt>c1/main</tt>)作为作业页的展示页.
文件本身对于参加者而言不必是可读的.
<p>
如果你要使用标准的展示页, 可把这一栏留空.
<p>
对个别练习的链接应该使用命令
<tt>\exercise</tt> 定义.
你可以使用以下预定义的变量:<ul>
 <li><tt>\scorerequire</tt> 每个练习需要的分数
 <li><tt>\scoregot</tt> 每个练习中参加者得到的分数
 <li><tt>\scoremean</tt> 每个练习的参加者的平均分
 <li><tt>\expiration</tt> 作业页的有效期, yyyymmdd
 <li><tt>\today</tt> 今天的日期, yyyymmdd
</ul>
所有的得分参数都是数字的表, 
表的每个项对应于作业页的练习数.

