 <b>Equazione formale.</b> (nome: <span class="tt wims_code_words">equation</span>)<br/>
 La risposta deve essere valutata come equazione e il confronto viene effettuato
 per valori compresi in un intervallo definito dall'autore, con la 
 precisioe definita dall'autore.
 
 La risposta <span class="tt">a = 0</span> viene consierata equivalente alla risposta <span class="tt">a</span>. Con l'opzione
 <span class="tt wims_code_words">eqsign=yes</span> è invece necessario scrivere <span class="tt"> a = 0</span>. 
!changeto  help/anstype.fr/equation.phtml
