<b>Espressioni matematiche.</b>
 (nomi: <span class="tt wims_code_words">algexp</span>, <span class="tt wims_code_words">litexp</span> et <span class="tt wims_code_words">formal</span>)<br/>
 Si tratta di una espressione matematiche che viene confrontata con
 la risposta corretta secondo differenti criteri.
Si possono inserire più risposte corrette separate da virgole.
 <p>
 Per il tipo <span class="tt wims_code_words">algexp</span> (espressione algebrica), le espressioni equivalenti sono minime. Per esempio (x+1)(x-1) non è accettata 
 se la risposta corretta è x^2-1, sin(x)^2+cos(x)^2 non è equivalente alla risposta corretta 1.
 Invece  x-y*y et -y^2+x sono considerate equivalenti.
 </p><p>
 Questo tipo di risposta è utile per portare gli studenti a fare manipolazioni
 di espressioni equivalenti.
 </p><p>
 Per <span class="tt wims_code_words">litexp</span> (espressione letterale), il confronto è letterale senza alcuna espressione algebrica. Per esempio
 x+y non è equivalente a y+x, come 3/2 non è equivalente a 6/4. Ma 2x e 2*x
 sono identificati, gli spazi sono esclusi dal confronto. Utilizzare con cautela.
 </p><p>
 Il tipo <span class="tt wims_code_words">formal</span> (espressione formale) permette il confronto
 numerico esatto. Tutto ciò che è uguale numericamente alla risposta corretta
 è accettato, senza approssimazioi.
 </p>
