 <b>Numero.</b> (nome: <span class="tt wims_code_words">numeric</span>)<br/>
 Confronto di numeri reali fino alla precisione stabilita dall'autore.

 Se è presente l'opzione <span class="tt wims_code_words">comma</span>, i numeri reali possono essere
 inseriti dall'utente con una virgola come separatore dei decimali (ma
 in fase di programmazione dell'esercizio occorre utilizzare il
 punto). In questo caso, se l'utente iserisce una risposta errata,
 l'eventuale risposta corretta viene proposta con lo stesso separatore
 per i decimali utilizzato dall'utente.

La precisione viene stabilita attraverso il parametro <span class="tt wims_code_words">precision</span>, impostato di default a 1000.

L'errore è normalizzato: la differenza deve essere inferiore a qualcosa tipo
<span class="tt">(|risposta_corretta|+|risposta_utente|)/precision</span> (la risposta è considerata parzialmente
corretta se si rispetta una formula analoga con al denominatore <span class="tt">sqrt(precision)</span>
invece di <span class="tt">precision</span>).

Se è presente l'opzione <span class="tt wims_code_words">absolute</span>, la precisione è assoluta.
La risposta è considerata parzialmente corretta se la differenza è inferiore a 10/precision.
