
Podeu explorar el contingut d'aquest lloc per diferents mètodes.

<ul>
<p><li>
 !href module=$module&cmd=new&job=type Per tipus de recurs
$ : referències, calculadors i graficadors, exercicis, etc.

<p><li>
 !href module=$module&cmd=new&job=subject Per tema
$ : àlgebra, càlcul, geometria, probabilitat, etc.

<p><li>
 !href module=$module&cmd=new&job=level Per nivell educatiu
$ : educació primària, educació secundària, universitat, etc.

<p><li>
 !href module=$module&cmd=new&job=new Per data
$ : les darreres incorporacions al servidor.

<p><li>
 !href module=$module&cmd=new&job=best Una breu introducció
 d'alguna de les millors activitats del servidor.

</ul>

