
<center><h3>$title</h3></center>

!form new
<input type=hidden name=module value=home>
<input type=hidden name=browse_job value=level>

$table_header
$table_tr
<th>$wims_name_level</th>
!for i=1 to 6
  <th align=center>$name_year $i
 !next i
<th>$name_category</th>
 $table_tr
<th>$name_primary
 !for i=1 to 6
  <td align=center>
  <input type=checkbox name=search_keywords value=levelE$i
  !if E$i=$thislevel
   checked
  !endif
  >
 !next i
 <td>
 !formradio search_category list A prompt \
		$name_A	
 $table_tr<th>$name_secondary
 !for i=1 to 6
  <td align=center>
  <input type=checkbox name=search_keywords value=levelH$i
  !if H$i=$thislevel
   checked
  !endif
  >
 !next i
 <td>
 !formradio search_category list X prompt $name_X		
$table_tr<th>$name_university
 !for i=1 to 5
  <td align=center>
  <input type=checkbox name=search_keywords value=levelU$i
  !if U$i=$thislevel
   checked
  !endif
  >
 !next i
 <td align="center">-</td>
  <td>
 !formradio search_category list T prompt $name_T		
 $table_tr<th>$name_graduate
  <td nowrap colspan=6 align=center>
  --- <input type=checkbox name=search_keywords value=levelG
  !if G=$thislevel
   checked
  !endif
  > ---
  <td>
  <br>
!formradio search_category list R prompt $name_R
$table_tr<th>$name_research
  <td nowrap colspan=6 align=center>
  --- <input type=checkbox name=search_keywords value=levelR
  !if R=$thislevel
   checked
  !endif
  > ---
  <td>
  <br>
!formradio search_category list S prompt $name_S
$table_tr
<td colspan=8 align=center bgcolor="$wims_ref_bgcolor">
<input type=submit value="$wims_name_search">
$table_end</form>

