!set wims_name_examremain=Time left for this exam: $
!read js/examclock.phtml
<html><head>
$wims_html_header
</head><body $wims_htmlbody onload=$wims_html_onload>
!headmenu

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!if $job iswordof student score scorereg
 !changeto $job.phtml
!endif

<center>$classname
<p>
<h1>Preparation of exam $exam
</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Back to home page
. <p>
 !goto end
!endif

!if $job=exo or $job=cpsheet
 !read $job.phtml
 !goto end
!endif

!if $activetest>0
 !form reply
 <input type=hidden name=job value=text>
 This exam is
 !if $activetest=1
  active.
  !href cmd=reply&job=expire Expire it
.
 !else
  !if $activetest=2
   expired but still visible by participants.
   !href cmd=reply&job=hide Hide it
  !else
   expired and hidden from participants.
   !href cmd=reply&job=expire Make it reappear
  !endif
  .
  !href cmd=reply&job=reactivate Reactivate it
. <p>
 !endif
!href cmd=reply&job=deactivate Desactive it
<p><center><table border=2>
 <tr><td align=right>Title:
 <td><input size=40 name=title value="$title">
 <td rowspan=3><input type=submit value=Modify>
 <tr><td align=right>Description:
 <td><textarea name=desc rows=2 cols=40>$desc</textarea>
 <tr><td align=right>Expiration date:<td>
 !distribute item $[$expday],$[$expmon] into expday,expmon
 !formselect expday from 1 to 31
 !formselect expmon from 1 to 12 prompt $months
 !formselect expyear from $thisyear to $thisyear+1
 </table></form></center> <p>
 !goto end1
!endif

!form reply
<input type=hidden name=job value=text>
Title (limited to $title_limit characters):<br>
<input size=65 name=title value="$title"> <p>
And a text of explanation (limited to $desc_limit characters; html
tags and links are allowed):<br>
<textarea rows=6 cols=65 name=desc>$desc</textarea>

<center><input type=submit value="Register the texts"></center>

<p>The exam expires on
!distribute item $[$expday],$[$expmon] into expday,expmon
!formselect expday from 1 to 31
!formselect expmon from 1 to 12 prompt $months
!formselect expyear from $thisyear to $thisyear+1
. A session of exam lasts up to
<input size=5 name=duration value="$duration">
minutes. Each participant can take the exam up to
!default stries=3
<input size=3 name=tries value="$stries"> times.
<input type=submit value="Register">

!ifval $activetest=-1
 <p>This exam does not exist yet.
 <input type=submit value="Click to create it"> (but fill in the title first).
 </form>
 !goto end
!else
 </form>
 !if $exocnt>0
  <p>This exam is not yet activated.
  !href cmd=reply&job=prep_activate Click here
  to activate it.
  (Students only see active exams; on the other hand, you can no longuer
  modify the exam once it is activated.)
 !endif
!endif

:end1
<p>
!if $exocnt=0
 This exam has no content yet.
 !href cmd=reply&job=exo&exo=1 Add an exercise
, or
 !href cmd=reply&job=cpsheet add a series of exercises
.
!else
 <a name=list>
 Content of the exam:</a><ol>
 !for i=1 to $exocnt
  <li>
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,ch,ti
  $ti, weight $we.
  !if $activetest=0
   &nbsp;(
   !if $i>1
    !href cmd=reply&job=moveup&moveup=$i#list Move&nbsp;up
    &nbsp;
   !endif
   !href cmd=reply&job=exo&exo=$i Modify
   &nbsp;
   !href cmd=reply&job=delete&delete=$i#list Delete
   )
  !endif
 !next i
 </ol>
 !if $activetest=0
  !href cmd=reply&job=exo&exo=$[$exocnt+1] Add another exercise
, or
 !href cmd=reply&job=cpsheet add a series of exercises
.
 !endif
!endif

<p>
!if $activetest=0 and $erasable=yes
  You can still
  !href cmd=reply&job=prep_erase erase this exam
.
!endif

!if $activetest>=0
 !href cmd=reply&job=student Participants' view.
 <p>
 !form reply
 <input type=hidden name=allow value=yes>
 This exam is
 !formselect allowtype list all, simulation, none, select prompt\
	open to all, open for simulation,\
	closed to all, open to following hosts (and/or hours):
 <br><input size=50 name=IPlist value="$IPlist"> <br>
 Cut times:
 <input size=50 name=cutt value="$cutt"> <br>
 <input type=submit value="Register the change">
 !set allowshare=0
 !if $sharers!=$empty
  ( for all sharing classes:
  !formselect allowshare list 0,1 prompt no,yes
  )
 !else
  <input type=hidden name=allowshare value=0>
 !endif
 </form>
 <small><b>Hint.</b> In the selective open mode, you can make time
 restrictions for score registrations, by adding words 
 <font color=blue><b>
 <tt>&gt;yyyymmdd.hh:mm</tt></b></font>
 (starting time) and/or
 <font color=blue><b>
 <tt>&lt;yyyymmdd.hh:mm</tt></b></font>
 (ending time). These must be in the
 SERVER's local time, and must be separated from other words by white spaces.
 <p>
 Cut times are used to let people take the exam in different sessions. A
 participant having worked on the exam before a cut time will have no access
 after the cut time.
 <p>
 Format of cut times: <tt>yyyymmdd.hh:mm</tt> (separate several cut times
 by white spaces).
 </small>
!endif
:end
!tail

!reset job,echoose,eweight,ename,edep,eopt,source
