
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!set wims_name_end=Finish this exam session
!set wims_name_scoreexam=My score

!set name_mainpage=Main page of the exam
!set name_dependency=Score dependencies
!set name_Options=Options
!set name_All=All
!set name_title=Preparation of exam
!set name_expire=Expire the examen