<b>Warning</b>!<p>

You haven't yet done all the exercises in this exam. Finishing now will
freeze the score and consume one try of the exam,
and you will have to start from the beginning the next time.
<p>
Are you sure you want to finish?
<p><center><font size="+1">
!href cmd=reply&job=scorereg&confirm_end=yes YES
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score NO
</font></center> <p>

!tail
!reset job
