
!read adm/title.phtml 1\
$wims_classname, $wims_institutionname\
$title

!if $wims_user=supervisor
 <center>($name_presentation)</center>
!endif
 <p>
$desc<p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_back
. <p>
 !exit
!endif

!if $registered<0 or ($registered>0 and $timeleft<=0)
 !changeto score.phtml
!endif

!if $exocnt=0
 $name_empty
!else
 $name_content:
 !set activeexo=0
 <p>
 !let maxcol=$[min(ceil(($exocnt+3)/10),5)]
 !let maxlig=$[ceil($exocnt/$maxcol)]
 !if $maxcol>1
  <center>
 !endif
 <table border=0 class="wims_exam">
  !for lig=1 to $maxlig
   <tr>
    !for col=1 to $maxcol
     !let i=$[$col*$maxlig+$lig-$maxlig]
      !if $i<=$exocnt
!! -------------------------- debut de la ligne correspondant р un exercice de l'examen
 !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
 !distribute lines $ex into we,li,ti,de,op
 !set de=!trim $de
 <td>$i.</td> 
 !if $t_=yes and ($allowtype=simulation or $tryremain>0 or \
   ($tryremain=0 and $registered!=$empty))
   !if $(replied$i)>0
    <td>$ti </td><td>$name_done</td>
   !else
    !if $de!=$empty
     !set dt=!examdep $exam $de
    !else
     !set dt=yes
    !endif
    !if $dt=yes
     !advance activeexo
     <td>
     !href target=wims_exam cmd=new&worksheet=$exam.$i $ti
</td><td class="empty">&nbsp;</td>
     !if autogen iswordof $op and $wims_exam_remain!=$empty
      !set ss=$(wims_session)t$(exam)t$i
      !set test=!defof w_cmd in wimshome/sessions/$ss/var
      !if $test=$empty
       !set test=$wims_ref_name?wims_window=new&+session=$(wims_session)_exam&+cmd=new&+worksheet=$exam.$i
       <img src="$test" height=1 width=1 border=0>
      !endif
     !endif
    !else
     <td><b><font color=red>$ti</font></b> </td><td>
     !href cmd=reply&job=student $name_depend
.</td>
    !endif
   !endif
  !else
   <td>$ti.</td><td class="empty"></td>
  !endif
!! -------fin d'affichage de la ligne correspondant ра un exercice
      !endif
    !next col
   </tr>
  !next lig
 </table>
 !if $maxcol>1
  </center>
 !endif
 !if $t_=no
  $name_examclosed
  !href cmd=reply&job=student $wims_name_refresh
 !else
  !if $stries=1
   $name_exam1
  !else
   $name_exam2
  !endif
  !if $tryremain<0 or ($tryremain=0 and ($registered=$empty or $allowtype=simulation))
   !if $trcut=0
    $name_exam3
   !else
   $name_exam4
   !endif
   $name_exam5
   !set exhausted=yes
  !endif
  !if $tryremain>0
   $name_exam6
  !endif
  !if $registered=$empty and $exhausted!=yes
   $name_exam9
   !if $allowtype!=simulation
    $name_exam7
   !else
    $name_exam8
   !endif
  !else
   !if $allowtype!=simulation and $tryremain=0 and $exhausted!=yes
    $name_lasttry
   !endif
  !endif
  !set wims_menu_items=!append line refresh,1,cmd=reply&job=student\
scoreexam,1,cmd=reply&job=score \
to $wims_menu_items
  !if $activeexo<1
!set wims_menu_items=!append line endexam,1,cmd=reply&job=scorereg\
to $wims_menu_items
  !endif
 !endif
!endif

!if $t_=yes
 !if $allowtype=simulation
  <p>$name_simulation
 !endif
!endif

!if $wims_user=supervisor
!set wims_menu_items=!append line backteacher,1,cmd=resume\
 to $wims_menu_items
!endif

!tail

!reset job


