!!classdevtools.proc :
!! Adds Classes devtools links in wims_rm_0 for navigation menus

!if $wims_supertype!=4 or $class_typename!=class
    !set wims_rm_0 = $wims_rm_0\
classexo,1,module=classes/$lang&special_parm=.nocache.\
createxo,1,module=adm/createxo\
modtool,1,module=adm/modtool

!read themes/_procs/exolog.proc

  !if $class_type=2
      !set wims_rm_0 = $wims_rm_0\
add_class,1,module=adm/class/regclass\
cloneclass,1,module=adm/class/regclass&job=cloneexemple\

  !endif
!endif
