
!if $class_defined!=yes
 <b>Error</b>. Ha pedido conectarse a una clase que no existe.
 Por favor compruebe su petición.
 !exit
!endif

Para entrar en la clase <b><font color=green>$class_description</font></b> de
<b><font color=green>$class_institution</font></b> como su
<em>$name_sup</em>, por favor introduzca la contraseña del $name_sup.

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 $wims_name_Password ($name_sup) <input type=password size=20 name=auth_password>
<p>
<input type=submit value="$wims_name_Enter">
</center>
</form>

