!if robot isin $session or _ isin $session
 !exit
!endif
!if $error issametext bad_password
 !read js/chrono.js 5
!endif

!read names.phtml
!header
!distribute line Área de los profesores\
	Área de los estudiantes\
	Clases de ejemplo\
	Autentificación del profesor\
	Autentificación de los participantes\
	Enseñanza primaria\
	Enseñanza secundaria\
	Universidad\
	into n_supervisor,n_participant,n_example,\
	n_authsupervisor,n_authparticipant,n_E,n_H,n_U

<center><h3>--- $(n_$type) ---</h3></center>
!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!read $type.phtml
!if $wims_user=$empty or $wims_user=supervisor
 <p><center>
 !for t in participant,supervisor,example
  !if $t!=$type or $superclass!=$empty
   !href module=$module&type=$t $(n_$t)
&nbsp;&nbsp;
  !endif
 !next t
 !href target=wims_help module=help/main&chapter=3 Explicaciones
 </center>
!endif

!tail

!reset auth_user,auth_password,superclass

