!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=agrupación de clases
    !set name_sup=profesor
   !else
    !set name_classe=centro educativo
    !set name_sup=administrador
   !endif
     !set name_classes= el $name_classe
     !set name_classess= un $name_classe
     !set name_classesss= del $name_classe
     !set name_classessss= El $name_classe
 !else
   !set name_classe=clase
   !set name_classes=la $name_classe
   !set name_classess=una $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=profesor
 !endif
 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of clase,curso
   !set Name_level= !item $splevel of Nivel,Clase,Curso
   !set Name_levels= !item $splevel of Niveles,Clases,Cursos
   !set sousclasses_else=!item $splevel of o una clase, o un curso
   !set name_level_else= !item $splevel of un nivel,una clase,un curso
 !else
   !set sousclasses=subclases
   !set sousclasses_else=una clase o un centro educativo
 !endif
 
 !set CL_Name	=Level,Class,Program,Course,Course interclasses,Test Zone
!set Name_program=Programs
!set name_program=program

!set name_portalandgroup=Centros educativos y agrupamientos de clases
!set name_independantclass=Clases independientes

!distribute items Inscribirse,anónimo,abierta,protegida,Année,\
Nuevo participante,inscritoi,Tipo de conexión,Up\
into name_register,name_anonymous,name_open,name_protected,name_year,\
name_new_participant,name_registered,name_connexion,name_up

!distribute line  No tiene cuenta en otras clases.\
Rechercher votre classe\
no hay ninguna clase disponible\
Aucune classe ne correspond à votre recherche.\
Puede cambiar directamente a las siguientes clases:\
into name_noaccount,name_searchclass,name_noavailable,name_nofound,name_direct

!let classification=Ecole,Collège,Lycée,Université,Autre

!set name_text1=Elija la línea correspondiente a la clase o al centro educativo que le corresponda. \
 <p>
Si aún no se ha inscrito, pulse en <tt>Inscribirse</tt> (si la clase tiene el status de\
<tt>protegida</tt>, necesita que el profesor o el administrador le proporcione la contraseña).

 <p>De lo contrario pulse en el nombre de la izquierda para entrar. 

!set name_text2=Para pasar a $name_level_else $sousclasses_else, elija el nombre de la clase de la tabla de abajo.
!set name_text3=O elegir $name_level_else $sousclasses_else de la tabla de abajo.
!set name_language=No hay clases en español en este sitio. ¿Quizás esté buscando una clase en otro idioma ?
!set name_language2=este sitio no contiene ninguna clase en español.

