!set name_title=naam van het message board
!set name_description=beschrijving van het message board
!set name_supervisor=naam van de eigenaar
!set name_email=emailadres
!set name_password=deelnemers wachtwoord van het message board
!set name_passsup=wachtwoord van de message board eigenaar

!set forumname=<b><font color=green>$title</font></b>

!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

