

<center><table border=1 bgcolor="$wims_ref_bgcolor">
<caption>文件 <b>$doc</b></caption>
<tr><th>标题<td>$tit
<tr><th>作者<td>$author
!if @ isin $email
 <tr><th>email<td>
 !mailurl $email
!endif
!if class != $doctype
 <tr><th>版权<td>
 !if $copyright iswordof gnu opl
  !if $copyright=gnu
   <a href=fdl.txt>GNU自由文件许可(GNU Free Documentation License)</a>
  !endif
  !if $copyright=opl
   <a href=opl.html>公开发表许可(Open Publication License)</a>
  !endif
 !else
  作者保留所有权利
 !endif
!endif
$table_end</div>

