
!!<html><head>
!!
!!set wims_html_header=!append line $header to $wims_html_header
!if $job iswordof read print
 !set wims_html_header=!append line $header to $wims_html_header
!endif
!read adm/css.phtml
!!</head>
!if $job=help
!!<html><head>
!!$wims_html_header
!!</head>
!header1
 !changeto help.phtml
!endif

!if help isin $wims_session and $doc!=$helpd
!!<html><head>
!!$wims_html_header
!set wims_html_onload=!append word window.close(); to $wims_html_onload
 !!<body $wims_htmlbody onload="window.close();">
 !header1
 现在你可以关闭这个帮助窗口.
 </body></html>
 !exit
!endif
!!<body $wims_htmlbody><div class=wimsmenu>
!if $cmd=help and $special_parm=about
 !changeto about.phtml
!endif

!if $job notwordof home
 !read menu.phtml
!else
 !header
!endif
!!</div><div class=wimsbody>
!read $job.phtml

!reset rEg,preview,abandon,Titb,Keyw,Next,Prev,Upbl,currcont,\
       titr,authorr,emailr,coder,coder1,coder2,copyrightr,docopenr,dlangr,\
       foldin,foldout,readcntadv,job2

!for i=1 to 20
 !reset parm$i
!next i

!if $job notwordof home
</div>
</body></html>
!endif
