!if $error!=$empty
 !read msg.phtml
 <p>
 !exit
!endif

<center><h1>$tit</h1></center>

!if $titb=$empty
 <p>
 块<tt>$block</tt>尚未创建.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
本页尚未开放阅读. 请以后再来!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
本页已过期, 你不能再阅读. 抱歉!
 <p>
 !exit
!endif

:newblock
<a name=$block>
<h3>$titb</h3>

!read $wims_priv_thisdoc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $wims_priv_thisdoc/$block.def
 <p>
 !goto newblock
!endif

</div><div class=wimstail>
<p><hr>
<table width=100% border=0 cellspan=0 cellpadding=1>
<tr><td align=left nowrap><small>
By
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
<td align=right><small>
!href cmd=reply&job=read&doc=$doc&block=$startblock 互动版本
!if $wims_user=supervisor and $sheetdata!=$empty
 <tr><td align=left nowrap>
 <small>Last modified $datm
 <td align=right><small>
 !href cmd=reply&job=exosource&block=$startblock 本页练习的源码
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>最新修改: $datm
!endif
</table>

