
<center><h1>$tit
!if $editable=yes
 </b><font size="-1">[
 !if $block=main
  !href cmd=reply&job=prop 性质
  ] [
  !href cmd=reply&job=erase 删除
 !else
  !href cmd=reply&job=list 其它块
 !endif
 ]</font>
!endif
</h1></center>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 块 <tt>$block</tt> 尚未创建.
 !if $editable=yes
  !href cmd=reply&job=edit&block=$block 创建
.
 !endif
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 本页尚未开放阅览. 请以后再来!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 本页已过期, 你不再能阅读. 抱歉!
 <p>
 !exit
!endif

<h3>$titb
!if $editable=yes
 </b><font size="-1">[
 !href cmd=reply&job=edit&doc=$doc&block=$block 编辑
 ]</font>
!endif
</h3>

!!detrust
!read $docdir/$doc/$block.def content

</div><div class=wimstail>
<p><hr>
!if ($wims_class!=$empty and $wims_user!=supervisor)
 !exit
!endif
!if help isin $wims_session
 <small>
 !href cmd=reply&job=source 源文件
 &nbsp; 作者
 !if $email=$empty
  $author
 !else
  !mailurl $email $author
 !endif
 最后修改日期 $datm</small>
 !exit
!endif
<table width="100%" border=0 cellspan=0 cellpadding=1>
<tr><td align=left nowrap><small>
!if $editable=yes
 !href cmd=reply&job=prop 性质
&nbsp;
!endif
!href cmd=reply&job=source 源文件
&nbsp; 作者
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
<td align=right><small>
!href module=home WIMS
 @
<a href="http://$httpd_HTTP_HOST/">$httpd_HTTP_HOST</a>
!if $wims_user=supervisor and $sheetdata!=$empty
 <tr><td align=left nowrap>
 <small>最后修改日期 $datm
 <td align=right><small>
 !href cmd=reply&job=exosource 本页练习的源码
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>最后修改日期 $datm
!endif
</table>


