
<center><h1>$tit<p>
改变密码
</h1>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!set wims_form_method=post
!form reply
<table border=0 cellspacing=5>
<tr><td nowrap align=right>输入现行密码:
<td align=left><input type=password size=20 name=coder1>
<tr><td nowrap align=right>新密码:
<td align=left><input type=password size=20 name=coder>
<tr><td nowrap align=right>重复新密码:
<td align=left><input type=password size=20 name=coder2>

<tr><td colspan=2 align=center>
<input type=submit value="纪录">
<input type=submit name=abandon value="放弃">
</table></form></center>

<p><b>提醒</b>. 密码给你修改文件的权力.
它必须由 $codemin 至 $codemax 个字母或数字组成.

