
<center><h3>Delete the level <em>$class_description</em></h3></center>

<font color=red><b>WARNING</b>.</font> This operation is not recoverable!
And <font color=red>EVERYTHING</font>
under this level will be <font color=red>DEFINITELY</font>
deleted: classes, programs, courses, participant accounts, activities, scores!
<p>
Are you sure to delete this level?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes Yes
&nbsp;&nbsp;
!href cmd=reply&job=first No

</font></center> <p>

