
<center><h3>Delete the test zone <em>$class_description</em></h3></center>

<blink><b>WARNING</b>.</blink> This operation is not recoverable!
And <font color=red>EVERYTHING</font>
in this test zone will be <font color=red>DEFINITELY</font>
deleted!
<p>
Are you sure to delete the test zone?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent Yes
&nbsp;&nbsp;
!href cmd=reply&job=$parent No

</font></center> <p>

