!exit
$table_header
<caption>Student accounts
!href cmd=reply&job=addstudent add&nbsp;student
</caption>
$table_hdtr
<th>Account</th>
<th>Name</th>
<th>-</th>
!for i=1 to $studentcnt
 !set l=!record $i of $classdir1/.studentlist
 !distribute items $l into l_,f_,c_
 $table_tr
 <td><tt>$c_</tt></td>
 <td>
 !href cmd=reply&job=modstudent&student=$c_ $l_, $f_
 </td>
 <td>
 !href cmd=reply&job=delstudent&student=$c_ delete
 </td>
!next i
$table_end

