!! addshare_..., stopshare_..., addcourse_..., delprog_..., stopshare_,...
<p>
<b>Error</b>. 
!goto $error

:addcourse_already
 The course you wanted to add already exists.
 !exit

:bad_access
 You have no right to access this module.
 !exit

:bad_password
 Bad password: too short, too long, or contains bad characters.
 <p>
 Try another one.
 !exit

:bad_user
 The user does not exist.
 !exit

:class_full
 The teaching level is full: there is no space left for adding more classes!
 <p>
 Do you really need more than 99 classes in one teaching level?
 Erase some useless classes please.
 !exit

:course_full
 There is no space for adding more courses!
 <p>
 Do you really need more than 10 courses of a same program in the same class?
 !exit

:del_not_exist
 The level/class/program/course you want to delete does not exist.
 !exit

:empty
 The structure is empty.
 !exit

:icourse_full
 The program is full: there is no space left for adding more interclass
 courses!
 <p>
 Do you really need more than 99 interclass courses in one program?
 Erase some useless courses please.
 !exit

:level_full
 The institution is full: there is no space left for adding more teaching level!
 <p>
 Do you really need more than 99 teaching levels?
 Erase some useless levels please.
 !exit

:mod_not_exist
 The level/class/program/course you want to modify does not exist.
 !exit

:not_secure:
 !goto unsecure

:not_supervisable
 The user $name is not a teacher. He/She has no right to supervise a level or
 a class.
 !exit

:pass_discord
 The passwords didn't match.
 !exit

:prog_full
 The teaching level is full: there is no space left for adding more programs!
 <p>
 Do you really need more than 99 programs in one teaching level?
 Erase some useless programs please.
 !exit

:unsecure
 This module must be accessed from a secure host.
 !exit

:user_exists
 This user already exists.
 !exit

:*
!msg $error

