!read adm/title.phtml 3\
\
Manage a connected class

!read connect/remote.phtml

<p>
Remote class: $connclass.

!if $error=$empty
 (<font color=blue>$description</font> of 
 <font color=blue>$institution</font>)
 <p>
 !form reply
 <input type=hidden name=job2 value=sync>
 Synchronize
 !formselect connclasstype list local,remote prompt\
	local class, remote class
 (with the other one) for
 !formselect connsync list def,user,avg,score,rec prompt\
	class definition, user list, score averages, score details,\
	all but class definition
 <input type=submit value=OK>
 </form> <p>
!else


!endif


