
!readproc adm/docsheet.prep
!read $docdef content
<p><center>
De cijfer registratie is
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   open, maar je kunt het
   !href cmd=resume&job=suspend opschorten
.
  !else
   door jezelf opgeschort.
   !href cmd=resume&job=reopen Reactiveren
.
  !endif
 !else
 niet beschikbaar vanaf jouw netwerkadres.
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh Werkblad Startpagina
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc.en&job=edit&doc=$d_&block=$b_ Bewerk deze pagina
.&nbsp;
 !href cmd=resume Opnieuw laden
.
!endif
</center>

!tail

