!if $job=print
 !changeto print.phtml
!endif

!if $public!=P
 !changeto class.phtml
!endif

!header

!if $error!=$empty
 !read msg.phtml
 !tail
 !exit
!endif

!if $wims_user=supervisor and $job=raw
Hier staat de broncode van het werkblad.
 U kunt deze importeren in Uw klas door te "knippen & plakken".
 <p><hr><pre>
 !sh awk 'BEGIN {a=0};\
	/^:/ {a=1};\
	a==1 {print}' bases/sheet/$sh.def
 </pre><hr>
 <p>
 !href cmd=resume&job=read Terug naar het normale werkblad.
 !tail
 !exit
!endif

<h3 class="wims_sheet_title">$sheet_title</h3>
<div class="wims_sheet_desc">$sheet_desc</div> <p>

$sheet_remark
<p>

!if $n=0
 Het werkblad is leeg, dit is waarschijnlijk een fout.

!else
 Het oefenmateriaal in dit werkblad:

 <p><ul>
 !for i=1 to $n
  !set ex=!record $i of $data
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  <li><p>$i. 
  !href module=$di&cmd=new&worksheet=$public$shn&$pa $ti
, $de
!!  !if $require>0
!!   <small>$[$got] uit $[$require] punten behaald, gemiddelde score
!!   $[$mean]/10.</small>
!!  !endif
 !next i
 </ul>
 !if $wims_user=supervisor
  !href cmd=resume&job=raw Klik hier
  om de broncode van dit werkblad te zien, zo dat deze geimporteerd kan worden in Uw eigen klas. 
 !endif
!endif
!!!href cmd=reply&job=print Printbare versie
!!.

!set wims_menu_tail=!append line printable,1,cmd=reply&job=print\
to $wims_menu_tail
!tail

