!if $job=print
 !changeto print.phtml
!endif

!if $public!=P
 !changeto class.phtml
!endif

!header

!if $error!=$empty
 !read msg.phtml
 !tail
 !exit
!endif

!if $wims_user=supervisor and $job=raw
Hier staat de broncode van het werkblad.
 U kunt deze importeren in Uw klas door te "knippen & plakken".
 <p><hr><pre>
 !sh awk 'BEGIN {a=0};\
	/^:/ {a=1};\
	a==1 {print}' bases/sheet/$sh.def
 </pre><hr>
 <p>
 !href cmd=resume&job=read Terug naar het werkblad.
 !tail
 !exit
!endif

<h3 class="wims_sheet_title">$sheet_title</h3>
<div class="wims_sheet_desc">$sheet_desc</div> <p>

$sheet_remark
<p>

!if $n=0
 Het werkblad is leeg, dit is waarschijnlijk een fout.
!else
 Het oefenmateriaal in dit werkblad:
 <div class="wims_sheet">
 <p><ul class="wims_sheet_list">
 !for i=1 to $n
  !set ex=!record $i of $data
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  <li class="wims_sheet_list"><p>$i. 
  !href module=$di&cmd=new&worksheet=$public$shn&$pa $ti
, $de
!!  !if $require>0
!!   <small>$[$got] uit $[$require] punten behaald, gemiddelde score
!!   $[$mean]/10.</small>
!!  !endif
 </li>
 !next i
 </ul>
 </div>
  !if $wims_user=supervisor
    !href cmd=reply&job=import Importeer                                                                                                      
  dit werkblad in uw klas , of
  !href cmd=reply&job=raw bekijke de boroncode
  van het werkblad
  <p>                                                                                                                                      
 !endif
!endif

!set wims_menu_items=!append line printable,1,cmd=reply&job=print\
to $wims_menu_items

!tail

