
$table_header
<caption>有效的参加者数据栏目</caption>
$table_hdtr<th>名称</th><th>意义</th></tr>
$table_tr<td>login</td><td>$wims_name_Login</td></tr>
!if $special_parm!=upload
$table_tr<td>name</td><td>姓名(分两栏)</td></tr>
!endif
$table_tr<td>lastname</td><td>姓</td></tr>
$table_tr<td>firstname</td><td>名</td></tr>
$table_tr<td>password</td><td>参加者口令, 总是用特殊加密形式下载,
  但可以用不加密的形式上传.</td></tr>
$table_tr<td>email</td><td>电邮地址</td></tr>
$table_tr<td>regnum</td><td>注册号</td></tr>
$table_tr<td>photourl</td><td>照片的URL</td></tr>
$table_tr<td>comments</td><td>关于参加者的附注</td></tr>
!if $special_parm!=upload
$table_tr<td>allscore</td><td>所有得分与平均</td></tr>
$table_tr<td>averages</td><td>平均分(服务器分数与教师评分)</td></tr>
$table_tr<td>average1</td><td>服务器分数的平均</td></tr>
$table_tr<td>average2</td><td>教师评分的平均</td></tr>
$table_tr<td>sheets</td><td>所有作业页的得分(一个接一个)</td></tr>
$table_tr<td>sheet1,sheet2,...</td><td>作业第1页, 第2页, ...的分数</td></tr>
$table_tr<td>exams</td><td>所有考试的分数</td></tr>
$table_tr<td>exam1,exam2,...</td><td>考试第1页, 第2页, ...的分数</td></tr>
$table_tr<td>manuals</td><td>所有教师评分(一个接一个)</td></tr>
!else
$table_tr<td>参加者 (只用于 gateway 情形, 保留给管理者)</td><td>班级号, 
表成 abcdefg/1/101
其中 abcdefg 是 gateway 号码. 如果有几个班级,
则用空格分隔.</td></tr>
!endif

$table_tr<td>manual1,manual2,...</td><td>教师评分 1, 2, ...
$table_tr<td>var_xxx</td><td>技术变量 <tt>xxx</tt></td></tr>

$table_end <p>

不能识别的栏目不予考虑. 可以使用技术变量
对练习页和考试作选择性限制.
<p>
!if $special_parm=upload
在 <tt>参加者</tt> 栏目的情形, 可以添加班级, 但不能取消.
!endif
