
<center><h3>Upload spreadsheet data</h3></center>
Om data te versturen naar Uw klas op de server, bewaart U deze data in een tekst-formaat 
(txt, csv, of tsv),vervolgens stuurt U deze file naar de server.
<p>
U kunt leerling info opsturen.
De opgestuurde leerling info mag <em><b>geen</b></em> cijfers bevatten.
<p>
De eerste rij van de tabel moeten de namen zijn van de kolommen.
De geldige kolom-namen en hun betekenis staat hieronder vermeld.<br>
U kunt elke kombinatie van kolommen maken en in elke gewenste volgorde,
met als enige voorwaarde dat de `login' aanwezig moet zijn.
 (Het WIMS-systeem  gebruikt dit veld namenlijk om de individuele leerling te herkennen.)
 Als  U wilt dat sommige rijen niet worden ingelezen, kunt U deze aangeven met een `#' 
 in het `login' veld
<p>
U kunt deze methode gebruiken om een hele klas in 1 keer te "bevolken".
Hiervoor moet Uw tabel ten minste de volgende data bevatten:voornaam ,achternaam ,wachtwoord
<p>
Wilt U cijfers opsturen naar de server, komen deze in de corresponderende kolom.
Dus als de kolom "cijfers" nog niet bestaat, moet U deze eerst aanmaken voor dat U 
cijfers kunt uploaden.
<p>
!read help/fieldtab.phtml
