
Free service provided by Wims on the Internet comes 
with no guarantee of whatever kind.

<p>Il <em>core system</em> del sever è soggetto alla
<a href=COPYING target=wims_external>GNU General Public Licence</a>. 
Il codice sorgente è disponibile all'indirizzo
<p><center><tt>
<a href=http://wims.unice.fr/download/wims>http://wims.unice.fr/download/wims</a>
</tt></center> <p>
&copy; 1997-2000- Autore del sistema:
!mailurl xiao@unice.fr XIAO, Gang\
WIMS
 di <a href=http://www.unice.fr>Université de Nice - Sophia Antipolis</a>.

<p>Un traduzione in Cinese (Big5) (<em>core system</em> e moduli) è stata resa disponibile da 
!mailurl ychuang@cc.cktc.edu.tw Y. C. Huang
 (non più aggiornata).

<p>Traduzioni in Cinese semplificato (<em>core system</em> e moduli) sono realizzate da un gruppo coordinato da 
!mailurl zjchen@math.ecnu.edu.cn CHEN, Zhijie
.

<p>Traduzioni in Italiano (<em>core system</em> e moduli) sono realizzate da
!mailurl marina.cazzola@unimib.it Marina Cazzola
.

<p>Ogni singolo modulo WIMS ha un suo copyright (riportato in una apposita
pagina) che può essere diverso da quello del <em>core system</em>. 

<p>Il codice sorgente dei moduli di pubblico dominio è disponibile 
attraveso lo stesso sito in cui è disponibile il software del sistema.

<p>Alcuni moduli utilizzano software commerciale. &Egrave; responsabilità
del gestore di ogni sito WIMS verificare con i proprietari del software che 
l'installazione di tali moduli e l'utilizzo di tale software sul proprio
server non ne violi la licenza.


