
Uno dei principali punti di forza di WIMS sono i suoi esercizi interattivi.
<p>
Questi esercizi possono essere di vario tipo. Per esempio,
!href target=wims_demo module=H5/geometry/gravshoot.en Gravity shoot
 chiede di rispondere con un click su una immagine e assegna un punteggio 
valutando la distanza tra il punto di click e la posizione corretta;
!href target=wims_demo module=H6/geometry/coincfree.en Coincidence Freehand
 mostra l'immagine di una curva e chiede di inserire l'espressione
analitica di una funzione che meglio approssimi la curva, permettendo
approssimazioni successive;
!href target=wims_demo module=U1/analysis/graphder.en Graphic derivative
 mostra il grafico di una funzione e chiede di identificare, tra vari 
grafici mostrati, il grafico della sua derivata;
!href target=wims_demo module=H6/analysis/scenarineq.en Scenario of inequalities
 propone una serie di passaggi logici di una dimostrazione e chiede di 
individuare i passaggi errati;
!href target=wims_demo module=H6/algebra/decrypt.en Decrypt
 propone un messaggio criptato e chiede di ricostruire il messaggio
originale, anche attraverso tentativi successivi; etc.
<p>
Molti esercizi OEF (Open Exercise Format) sono già disponibili nella
distribuzione standard di WIMS, ogni pacchetto raccoglie una serie di
esercizi tradizionali su un determinato tema. &Egrave; possibile selezionare
un sottoinsieme degli esercizi proposti, per lavorarci sopra. I docenti
possono anche 
!href module=$module&chapter=4&open=$open,4_oef#oef creare
 online i loro esercizi in formato OEF.
<p>
La maggior parte degli esercizi interattivi di WIMS sono configurabili
a livelli di difficoltà diversi e con stili diversi. La configurazione
degli esercizi viene fatta in una pagina apposita, in modo che, una volta 
iniziato a lavorare su un esercizi, il livello di difficoltà resta
sempre lo stesso.
<p>
Questo è importante perché gli esercizi costruiti tramite WIMS sono 
ripetibili. Si può richiedere lo stesso esercizio più e più volte 
perché questo ogni volta sarà proposto con parametri diversi.
Questo, ovviamente, permette di fare pratica sull'esercizio avendo a
disposizione ogni volta una versione diversa e permettendo quindi di 
arrivare ad una migliore comprensione dell'argomento; allo stesso tempo
permette che studenti che lavorino l'uno di fianco all'altro (ad 
esempio in un'aula informatica), non siano portati a copiare.
<p>
Quando un esercizio viene completato, WIMS attribuisce automaticamente
un punteggio a seconda della correttezza della soluzione dell'esercizio.
Il punteggio varia da 0 (competo insuccesso) a 10 (esercizio completato 
correttamente). Quando ci si trova all'interno di un <em>corso virtuale</em>
e si lavora sugli esercizi assegnati dal docente, questo punteggio viene
registrato dal server. Il server elabora i punteggi di tutti gli iscritti
al corso e ne permette al docente la visualizzazione in tempo reale e
in diversi formati.
<p>
Alcuni esercizi possono essere raccolti in ``serie'' composte da più 
domande. In questo caso il punteggio viene assegnato solo al termine della
serie (e non al termine di ogni domanda), e tiene conto della correttezza
in ognuna delle domande. Il numero di domande è in generale selezionabile
nella pagina introduttiva del gruppo di esercizi.



