
Lavorando in WIMS capiterà spesso di dover inserire formule o espressioni
matematiche.
<p>
Le formule matematiche possono essere inserite nel modo usuale: <tt>3*x+5</tt> per
!htmlmath 3x+5
, <tt>sin(pi*x)</tt> per
!htmlmath sin(pi*x)
, <tt>y^3+1</tt> per
!htmlmath y^3+1
, <tt>(x+1)/(y-1)</tt> per
!set ins_align=middle
!instex $$$$ {x+1 \over y-1} $$$$
, e così via.
<p>
Oltre a ciò, WIMS contiene un sistema di analisi che permette di correggere
``errori'' comuni nelle espressioni matematiche. Per esempio, <tt>3x+5</tt>
viene automaticamente trasformato in <tt>3*x+5</tt>, <tt>sin x</tt> viene
trasformato in <tt>sin(x)</tt>, e così via. Naturalmente raccomandiamo di non 
affidarsi ciecamente a questa correzione automatica, perché a volte 
le scritture possono essere ambigue. &Egrave; opportuno vercare sempre di 
introdurre le formule matematiche in maniera ``corretta'', anche se a volte
può sembrare inutile.
<p>
Segue una lista di funzioni matematiche e del modo (corretto) per inserirle.
Queste funzioni sono automaticamente riconosciute da WIMS nei contesti
in cui hanno senso. (Alcuni moduli possono accettare altre funzioni, 
verificare le pagine di help relative al singolo modulo.)
<p>
!set x=x
L'espressione $x può essere sostituita con una qualsiasi delle espressioni
contenute nella tabella seguente.
<p>
<center><table border=2 cellspacing=1 cellpadding=3 bgcolor="#d0e0c0">
<tr><th>funzione</th><th>descrizione</th><th>cosa digitare</th></tr>
<tr>
<tr><td>$m_pi
    <td>la ben nota costante<td>
    <tt>pi</tt> o <tt>Pi</tt> oppure <tt>PI
<tr><td><i>e</i><td>base del logaritmo naturale<td>
    <tt>e</tt> o <tt>E</tt>
<tr>
<tr><td>|$x|<td>valore assoluto di $x<td><tt>abs(x)
<tr><td>sign($x)<td>segno di $x:
       <br>&nbsp;=-1 se $x&lt;0<br>&nbsp;=0 se $x=0<br>&nbsp;=1 se $x>0
       <td><tt>sign(x)
<tr><td>
    !instex $$ \sqrt x $$
    <td>radice quadrata di $x
    <td><tt>sqrt(x)</tt> o <tt>x^(1/2)
<tr><td>?<td>intero più vicino a $x<td><tt>rint(x)
<tr><td>?<td>più grande intero $m_le$x<td><tt>floor(x)
<tr><td>?<td>più piccolo intero $m_ge$x<td><tt>ceil(x)
<tr>
<tr><td><i>e<sup>x</sup><td>esponenziale<td>
    <tt>exp(x)</tt> o <tt>e^x</tt> o <tt>E^x
<tr><td>ln($x)<td>logaritmo naturale<td><tt>log(x)</tt> o <tt>ln(x)
<tr><td>lg($x)<td>logaritmo in base 10<td><tt>lg(x)</tt> o <tt>log10(x)
<tr>
<tr><td>sin($x)<td>funzione trigonometrica seno<td><tt>sin(x)
<tr><td>cos($x)<td>funzione trigonometrica coseno<td><tt>cos(x)
<tr><td>tg($x)<td>funzione trigonometrica tangente<td><tt>tan(x)</tt> o <tt>tg(x)
<tr><td>ctg($x)<td>funzione trigonometrica cotangente<td><tt>cotan(x)</tt> o <tt>ctg(x)
    </tt> <br> o <tt>cot(x)
<tr><td>arcsin($x)<td>funzione inversa del seno<td><tt>asin(x)</tt> o
    <tt>arcsin(x)
<tr><td>arccos($x)<td>funzione inversa del coseno<td><tt>acos(x)</tt> o
    <tt>arccos(x)
<tr><td>arctg($x)<td>funzione inversa della tangente<td><tt>atan(x)</tt> o
    <tt>arctan(x)</tt> <br>o <tt>arctg(x)
<tr>
<tr><td>sh($x)<td>seno iperbolico<td><tt>sh(x)</tt> o <tt>sinh(x)
<tr><td>ch($x)<td>coseno iperbolico<td><tt>ch(x)</tt> o <tt>cosh(x)
<tr><td>th($x)<td>tangente iperbolica<td><tt>th(x)</tt> o <tt>tanh(x)
<tr><td>Argsh($x)<td>inversa del seno iperbolico<td><tt>asinh(x)</tt> o <tt>argsh(x)
    <br>o <tt>Argsh(x)
<tr><td>Argch($x)<td>inversa del coseno iperbolico<td><tt>acosh(x)</tt> o <tt>argch(x)
    <br>o <tt>Argch(x)
<tr><td>Argth($x)<td>inversa della tangente iperbolica<td><tt>atanh(x)</tt> o <tt>argth(x)
    <br>o <tt>Argth(x)
<tr><td>max(x,y)<td>maggiore tra x e y<td><tt>max(x,y)
<tr><td>min(x,y)<td>minore tra x e y<td><tt>min(x,y)
<tr><td>gcd(x,y)<td>Massimo Comune Divisore<td><tt>gcd(x,y)
<tr><td>lcm(x,y)<td>minimo comune multiplo<td><tt>lcm(x,y)
</table></center>



