
WIMS contiene vari strumenti matematici online (strumenti di calcolo, 
strumenti grafici, &hellip;), utilizzabili per argomenti che variano 
dal calcolo 
numerico elementare al disegno animato a calcoli avanzati su particolari
strutture.
<p>
&Egrave; possibile
!href module=home&list=2#list2 cliccare qui
 per avere una lista completa degli strumenti disponibili su questo sito, oppure
 !href module=home&list=9000 fare una ricerca
 per uno strumento specifico.

