
!read adm/title.phtml 3\
$name_delcourse0<em> $class_description</em>

<font color=red><b>WARNING</b>.</font> This operation is not recoverable!
And <font color=red>EVERYTHING</font>
under this course will be <font color=red>DEFINITELY</font>
deleted: participant accounts, activities, scores!
<p>
Are you sure to delete this course?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=$parent $wims_name_no

</font></center> <p>

