
<center><h3>Delete the program <em>$class_description</em></h3></center>

!if $class_recshare=main
 This program cannot be deleted because its resources are shared by other
 programs.
 !href cmd=reply&job=$job Cancel
 !exit
!endif

<blink><b>WARNING</b>.</blink> This operation is not recoverable!
And <font color=red>EVERYTHING</font>
under this program will be <font color=red>DEFINITELY</font>
deleted: courses, activities, scores!
<p>
Are you sure to delete this program?
<p><center><font size=+1>

!href cmd=reply&job=$job&del=$del&confirm=yes Yes
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level No

</font></center> <p>

