<!-- begin of $wims_theme/header.phtml -->

!! Header menu bar definition.
!nocache
!set wims_theme_header=yes

!set jquery_defined=yes

!default wims_theme_icon=$class_theme_icon
!default wims_theme_icon=standard

!if _tool isin $wims_session
    <!-- end of $wims_theme/header.phtml -->
    !changeto themes/$wims_theme/toolheader.phtml
!endif

!if _help isin $wims_session
  <div id="wimsmhelp">
!endif

!if _exam isin $wims_session
  <div id="wimsexam">
!endif

!if $wims_lightpopup=yes
  <!--<div id="wimslightpopup">-->
   <link rel="stylesheet" href="html/themes/$wims_theme/css_theme/light.css" type="text/css">
!endif

!set wims_theme_version=1
!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module

!if $wims_hm_cnt!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
 <div id="wimstopbox">

  !!Site Title
  !read themes/_widgets/site_title.phtml

  !!Institution logo
  !set positionlogo=right
  !read themes/_widgets/institution_logo.phtml

  <br class="clearall"/>

  <ul class="wimsmenu menuglobal">
   !distribute items li into div1

   !read themes/_widgets/headmenu.phtml
   !reset div0 div1

   !distribute items li,div into div0,div1
   !read themes/_widgets/permalink.phtml
   !reset div0 div1

   !!## technical parameters
   !if $class_cas_auth=$empty
     !set m_init_parm=!replace internal & by $ $ in $module_init_parm
     !set class_cas_auth=!getopt class_auth in $m_init_parm
   !endif

   !if $class_cas_auth!=$empty
    !!## it is better that the cas logout appears too much ... 
    !!## can be useless in the case of a supervisor so the next line is commented
    !!!!!!and $wims_user!=supervisor and ($wims_realuser=$empty or $wims_realuser!=supervisor)
    <li class="topmenuitem">
     !read adm/class/logout_cas
    </li><!--topmenuitem-->
   !endif
  </ul><!--wimsmenu-->
 </div><!--wimstopbox-->
!endif


!if $module!=home or $wims_user!=
 <div id="wimsbodybox">

  <!--Ajout du menu de la zone enseignant-->
  !if $module = adm/class/classes or $module = adm/class/regclass or $module = adm/createxo or $module = adm/createxo or $module = adm/modtool or $module = adm/quicktool or $module = adm/latex2wims
   !set wims_zone=zone_prof
   !read themes/$wims_theme/widgets/menuprof.phtml
  !else
   !set wims_zone=zone_etu
  !endif
 
  <div id="wimspagebox" class="$wims_zone">
  !!! ICI, impossible de placer menumodubox : les variables qu'il utilise ne sont pas encore instanciées
  !! read themes/_widgets/menumodubox.phtml

  !!chat
  !read themes/_widgets/alertchat.phtml
!endif

<!-- end of $wims_theme/header.phtml -->
