<!--begin of $wims_theme/htmlheader.phtml-->
<meta http-equiv="Content-Type" content="text/html; charset=$wims_main_font">
<title>$module_title2</title>
<meta name="GENERATOR" content="wims [$module_language]">
<meta name="description" content="$module_description $wims_site_description">
<meta name="keywords" content="$wims_site_keywords, $module_domain, $module_keywords">
<meta name="Author" content="$module_author">
<meta http-equiv="Content-Style-Type" content="text/css">


$wims_expire
$wims_CSS
<link rel="stylesheet" href="html/themes/$wims_theme/css_theme/css_nikaia.css" type="text/css">

<!-- METAS iOS : -->
<link rel="apple-touch-icon" href="gifs/wims_logo.png" />
<meta name="apple-mobile-web-app-capable" content="yes">
<!-- prevents links from apps from oppening in mobile safari -->
<script type="application/javascript" src="scripts/js/safari_mobile_links.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>

<!--end $wims_theme/htmlheader.phtml-->
