<!--begin of $wims_theme/htmlheader.phtml-->
<meta http-equiv="Content-Type" content="text/html; charset=$wims_main_font"/>
<title>$module_title2</title>
<meta name="GENERATOR" content="wims [$module_language]"/>
<meta name="description" content="$module_description $wims_site_description"/>
<meta name="keywords" content="$wims_site_keywords, $module_domain, $module_keywords"/>
<meta name="Author" content="$module_author"/>
<meta http-equiv="Content-Style-Type" content="text/css"/>


$wims_expire
$wims_CSS
<link rel="stylesheet" href="html/themes/$wims_theme/css_theme/css_nikaia.css" type="text/css"/>

<!-- METAS iOS : -->
<link rel="apple-touch-icon" href="gifs/wims_logo.png" />
<meta name="apple-mobile-web-app-capable" content="yes"/>
<!-- prevents links from apps from oppening in mobile safari -->
<script type="application/javascript" src="scripts/js/safari_mobile_links.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>


<style type="text/css">
/* Images du theme*/
body {
    background-color: $wims_ref_bgcolor;
    background-image: url("gifs/themes/$wims_theme/portal-header.png");
}

/* Couleurs CSS configurables depuis la configuration du site */

#wimsbodybox div#wimsmenubox.footer {
    background-color: $wims_ref_bgcolor;
    color: $wims_ref_button_color;
}

div#wimstailbox {
    background-color: $wims_ref_bgcolor;
}
/*#wimstopbox,#wimsmenubox,#wimsmenumodubox { color: $wims_ref_menucolor; background-color: $wims_ref_bgcolor;}

.container h4{	background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_pendant,#menu_html { background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_avant,#menu_apres {  background-color:$wims_ref_button_bgcolor;	color:$wims_ref_button_color;}*/
.infobulle{ background-color: $wims_ref_button_bgcolor;  color: $wims_ref_button_color;}

/*.topmenuitem a { color: $wims_ref_menucolor;}
.menuitem a { color: $wims_ref_menucolor;}*/

/*table.wimstable th {background-color: $wims_ref_bgcolor; color:$wims_ref_menucolor;}
table.wimstable th a {color: $wims_ref_menucolor;}
table.wimstable caption {background-color: $wims_ref_bgcolor;color: $wims_ref_menucolor;}
table.wimstable caption a {color: $wims_ref_menucolor;}
table.wimstable caption a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}
table.wimstable th a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}*/

input[type="submit"],input[type="button"],.wims_button{ background-color:$wims_ref_button_bgcolor;color:$wims_ref_button_color;}
.wims_button_help{ background-color:$wims_ref_button_help_bgcolor;color:$wims_ref_button_help_color;}

/*.legend {background-color: $wims_ref_bgcolor;color:$wims_ref_menucolor;}*/

</style>

<!--end $wims_theme/htmlheader.phtml-->
