<!--!if $overflow=yes-->

 !if $keyword = $empty
  $name_research1
  !else
  $name_research2
 !endif

	 <div class="wims_search_classe">
		  <div class="titre_recherche">
		  	<h2>Rechercher une classe</h2>
		  	<div class="aide_recherche">	  	
				 !set wims_ref_class=wims_button_help
				 !href module=adm/class/classes&type=example Exemple
		  	</div>
		  	<div class="spacer"></div>
		  </div>
		 <form>
		 <ul class="recherche">
		 	<input type="hidden" name="module" value="adm/class/classes"/>
		 	<input type="hidden" name="type" value="participant"/>
			<li><input size="20" name="keyword" value="$keyword"/></li>
			<li><input type="submit" value="$wims_name_tosave"/></li>
		</ul>

		 !formend
	</div>

 
!else
 !if ($sccnt + $clcnt > 20 and $wims_user = $empty) or $keyword!=$empty
	<div class="wims_search_classe">	  
	  <div class="titre_recherche"><h2>Rechercher une classe</h2></div>
	  <form>
		  $name_searchclass:
		  <ul class="recherche">
		  		<input type="hidden" name="module" value="adm/class/classes"/>
			  <li><input size="20" name="keyword" value="$keyword"/></li>
			  <li><input type="submit" value="$wims_name_tosave"/></li>
		</ul>

		
	  !formend
	 </div>
 !endif
 
<!--!endif-->





