!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_class_home 
. <p>
 !goto end
!endif

!default name_student=!nosubst $lastname, $firstname  
!readproc var.activity.proc
!if $showsheet=$empty
$name_showsheet
!form reply
  <input type=hidden name=job value=select>
  !set wims_formselect_switch=multiple size=$[min($activelist_cnt,7)]
  !formselect showsheet list $activlist prompt $(shs_title[$(activlist)])
  <input type=submit value="$wims_name_Show">
  </form>
!else
!if $usercnt==0
$name_noparticipant
!else
 <p>$table_header
 $table_hdtr<th>$wims_name_lastname, $wims_name_firstname</th>
 <th>$name_lastconnexion</th><th>$name_nbsessions</th><th><small>$name_cnt_exo 
 <br> ($nbexototal $name_exo)</small></th><th>$name_total</th>
 !for j in $showsheet
 !if $(activ[$j])>0
  <th colspan=2><small>$wims_name_Sheet $j <br>$(shs_title[$j])<br>($(nbexo$j) $name_exo)</small></th>
 !endif
 !next j
 </tr>
 $table_hdtr
 <th></th><th></th><th></th><th></th><th></th>
 !for j in $showsheet
 !if $(activ[$j])>0 
  <th><small>$name_cnt_exo</small></th><th><small>$name_time</small></th>
 !endif
 !next j
  </tr>
 !for m=1 to $usercnt
  !set uu=!record $m of wimshome/log/classes/$wims_class/.userlist
  !distribute items $uu into lastname,firstname,uu
  !set getraw=$uu
  !readproc raw.proc
  $table_tr
  <td>
   !href module=adm/class/userlist&job=getuser&getuser=$uu $name_student
  </td>
  !for h = 1 to 2*$sheetcnt + 4
    !set h1=$[($h+$h%2)/2-2]
 !if $h <=4 or ($h>4 and $(activ[$h1])>0) and $h1 isin $showsheet
  <td align="center">$(data[$h])</td>
!endif
  !next
  </tr>
!next
$table_end
 <p>$name_click
!endif
!set wims_menu_items=!append line refresh,1,cmd=reply\
back2,1,cmd=new\
Score1,1,module=adm/class/userlist&job_affi=notes\
to $wims_menu_items

:end
!tail
