!read adm/class/classlang names.phtml
!read adm/css.phtml
!if $cmd=help
 !header
 !changeto help.phtml
!endif
!header1

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$name_title

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $name_homeback
. <p>
!set wims_menu_items=!append line back,1,module=home\
to $wims_menu_items
 !goto end
!endif

!read activity.phtml

:end
!tail

!reset show

