
!read lang/names.phtml.$moduclass_lang
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/css.phtml
!if $cmd=help
 !header
 !changeto help.phtml
!endif
!set js=!record 0 of js/chooselist.js
!set wims_html_header=!append line $js to $wims_html_header
!set wims_html_header=!append line \
<style type="text/css">\
.activity_title { text-align:left; font-weight:bold; font-style:italic;}\
</style>\
to $wims_html_header
!header1
!read adm/title.phtml 1\
$classname\
$name_title
!default job=activity
!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$moduclass_lang
 </div>
<p>
 !href module=home $name_homeback
</p>
!set wims_menu_items=!append line back,1,module=home\
to $wims_menu_items
 !goto end
!endif

!read activity.phtml
!goto end

:end
!reset parmuser1 parmuser2
!if $user!=$empty
 !set parmuser1=&job=getuser&getuser=$user
 !set parmuser2=&job=user&user=$user
 !set sc=scores
 !set li=livret1
!else
 !set sc=Score1
 !set li=livret
!endif

!set wims_menu_items=!append line $sc,1,module=adm/class/userscore$parmuser1\
$li,1,module=adm/class/livret$parmuser2\
back2,1,\
 to $wims_menu_items
!tail

!reset show
