limitpart=10
!default maxday=365
!read adm/class/classlang names.phtml

wims_prefix=class user tmp n sharing sharable
!read tabletheme
!if $wims_user!=supervisor
 error=not_supervisor
 !!user=$wims_user
 !exit
!endif

!read adm/vfilter/listvarfilter.proc
!read adm/vfilter/varfilter proc
!if $varfilterclear!=$empty
    !reset varfilterclear,status
!endif

!default choice=all
!default graphics=0
!if $choice=all
 !reset loginlist
!endif
