
$table_header
<caption>有效的参加者数据栏目</caption>
$table_hdtr<th>名称<th>意义
$table_tr<td>login<td>参加者登录名
!if $special_parm!=upload
$table_tr<td>name<td>姓名(分两栏)
!endif
$table_tr<td>lastname<td>姓
$table_tr<td>firstname<td>名
$table_tr<td>password<td>参加者口令, 总是用特殊加密形式下载,
  但可以用不加密的形式上传.
$table_tr<td>email<td>电邮地址
$table_tr<td>regnum<td>注册号
$table_tr<td>comments<td>关于参加者的附注
!if $special_parm!=upload
$table_tr<td>allscore<td>所有得分与平均
$table_tr<td>averages<td>平均分(服务器分数与教师评分)
$table_tr<td>average1<td>服务器分数的平均
$table_tr<td>average2<td>教师评分的平均
$table_tr<td>sheets<td>所有作业页的得分(一个接一个)
$table_tr<td>sheet1,sheet2,...<td>作业第1页, 第2页, ...的分数
$table_tr<td>exams<td>所有考试的分数
$table_tr<td>exam1,exam2,...<td>考试第1页, 第2页, ...的分数
$table_tr<td>manuals<td>所有教师评分(一个接一个)
!endif
$table_tr<td>manual1,manual2,...<td>教师评分 1, 2, ...

$table_end <p>

不能识别的栏目不予考虑.
