
!read lang/names.phtml.$modu_lang owner


!set wims_form_method=post
!form new
<input type="hidden" name="module" value="adm/forum/mboard" />
<input type="hidden" name="job" value="authuser" />
<input type="hidden" name="forum" value="$forum" />
<input type="hidden" name="fuser" value="supervisor" />
<table class="wimscenter wimsnoborder">
 <tr><td>$name_pass_owner</td><td><input type="password" size="20" name="fpassword" /></td></tr>
</table>
 <p class="wimscenter wimsform">
 <input type="submit" value="$wims_name_send" />
</p>

!formend

