!set header_js_editor=\
<link type="text/css" rel="stylesheet" href="html/css/editor/style.css" />\
<link type="text/css" rel="stylesheet" href="html/css/editor/infobulle.css"  />\
<link type="text/css" rel="stylesheet" href="html/css/editor/jalonStylesHUD.css"/>\
<script type="text/javascript">	var version ="$lang";</script>\
<script type="text/javascript" src="scripts/js/editor/JSeditor1.js"></script>\
