
<h1 class="wims_docu_title">$tit<br />
$n_codechange
</h1>

!if $error!=$empty
 <div class="wims_alertmsg">
 !read docu/$modu_lang/msg.phtml
 </div>
 <hr />
!endif

!set wims_form_method=post
!form reply
<table class="wimscenter wimsnoborder wimsform">
<tr>
    <td nowrap="nowrap" align="right">$name_code1</td>
    <td align="left"><input type="password" size="20" name="coder1" /></td>
</tr><tr>
    <td nowrap="nowrap" align="right">$name_code2</td>
    <td align="left"><input type="password" size="20" name="coder" /></td>
</tr><tr>
    <td nowrap="nowrap" align="right">$name_code3</td>
    <td align="left"><input type="password" size="20" name="coder2" /></td>
</tr>
<tr>
    <td colspan="2">
    <input type="submit" value="$wims_name_tosave" />
    <input type="submit" name="abandon" value="$wims_name_giveup" class="wims_secondary_button" />
    </td>
</tr>
</table>
!formend

$name_code4
