

<center><table border=1 bgcolor=$wims_ref_bgcolor>
<caption>Dokument <b>$doc</b></caption>
<tr><th>Naslov<td>$tit
<tr><th>Avtor<td>$author
!if @ isin $email
 <tr><th>email<td>
 !mailurl $email
!endif
!if class != $doctype
 <tr><th>Avtorske pravice<td>
 !if $copyright iswordof gnu opl
  !if $copyright=gnu
   <a href=fdl.txt>GNU Free Documentation License</a>
  !endif
  !if $copyright=opl
   <a href=opl.html>Open Publication License</a>
  !endif
 !else
  All rights reserved by the author
 !endif
!endif
$table_end</div>

