<h1 class="wims_docu_title">$tit</h1>

AAvtor tega dokumenta je
!if $email!=$empty
 !mailurl $email $author
.
!else
 $author.
!endif
!if $readauth=yes
 Ta dokument ni odprt za vse uporabnike. Za branje morate vnesti za¹èitno geslo.
!else
 Za spreminjanje tega dokumenta je potrebno vnesti za¹èitno geslo.
!endif
<p>
!form reply
<input type=hidden name=job value=auth2>
!if $readauth=yes
 <input type=hidden name=noedit value=yes>
!endif
<center>
Za¹èitno geslo: <input type=password size=16 name=coder>
<input type=submit value=OK>
</center></form>
<p>
!if $readauth=yes
 Èe ste avtor tega dokumenta, ne pozabite, da potrebujete dovoljenje 
 !mailurl $wims_site_manager skrbnika stre¾nika\
Ask to open WIMS document $doc
 da bi omogoèili javen dostop do dokumenta.
 <p>
!endif
