<h1 class="wims_docu_title">$tit</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!if $erase!=$empty
 Datoteka <b>$erase</b> je bila izbrisana.
 <p>
!endif

!if $quota_free<1
 V ta dokument ne morete veè dodajati datotek, saj ste dosegli mejo dovoljenega prostora na stre¾niku.
!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=job2 value=deposit>
 V ta dokument lahko dodate datoteko:
 <input type=file size=35 name=wims_deposit>
 <input type=submit value=OK>
 </form>
!endif

!if $flist!=$empty
 <p>V tem dokumentu so na voljo naslednje datoteke:
 !for f in $flist
  !getfile doc/$f $f
  &nbsp;
 !next f
 <p>
 !form reply
 <input type=hidden name=job2 value=erase>
 Izbri¹ite datoteko:
 !formselect job2 list $flist
 <input type=submit value=OK>
 </form>
 <p>
 Na datoteke v dokumentu se lahko sklicujete z uporabo spremenljivke <tt>\filedir</tt>
v dokumentu. Primer: 
<p><center>
 <tt>&lt;a href="\filedir/$f1"&gt;$f1&lt;/a&gt;</tt>
</center> <p>
 ustvari povezavo na datoteko <a href="$m_filedir/$f1">$f1</a>.
 Zapi¹ete lahko tudi
<center><p>
 <tt>&lt;img src="\filedir/myfile.jpg" alt="myfile"&gt;</tt>
</p></center> <p>
in tako na stran dodate slikovno datoteko <tt>myfile.jpg</tt>.
 <p>
 Datoteke, ki jih dodate dokumentu, so dosegljive le uporabnikom s pravico do branja tega dokumenta.
!endif

<p>
$n_freespace1 $quota_total Meg.
$n_freespace2 $quota_free Meg.

<p><center>
!href cmd=reply&job=prop $n_properties
&nbsp;&nbsp;
!href cmd=reply&job=list $n_blocklist
&nbsp;&nbsp;
!href cmd=reply&job=read&block=main $wims_name_doch_main
!if $(readhist[-1;2])!=main
&nbsp;&nbsp;
!href cmd=reply&job=read&block=$(readhist[-1;2]) $n_lastpage
 (<tt>$(readhist[-1;2])</tt>)
!endif
</center> <p>

