
!if $error!=$empty
 !read docu/msg.phtml
 <p><hr> <p>
!endif

!if $doccnt<1
 !if $wims_class!=$empty and $wims_user!=supervisor
  V tej uèilnici ni na razpolago nobenega dokumenta. Obrnite se na skrbnika.
 !else
  !if $authoring=$empty
  V tej uèilnici noben dokument ni na voljo uporabnikom.
  !else
  V tej uèilnici ni nobenega dokumenta izbranega avtorja.
  !endif
 !endif
!else
 !if $ii>0
  !read scripts/table.phtml
 !else
  !if $wims_class!=$empty
   Tukaj so dokumenti va¹e uèilnice.
  !else
   Tukaj so dokumenti, do katerih lahko dostopate s te strani.
  !endif
  <ul>
  !for t=1 to $doccnt
   !set s_=!line $t of $slist
   !set t_=!line $t of $tlist
   !set a_=!line $t of $alist
   !set t_=!trim $t_
   !default t_=$n_notitle
   <li>
   !href module=$module&cmd=reply&job=read&doc=$s_&block=main $t_
   !if $wims_ismanager=2
    &nbsp;
    !href cmd=reply&job=erase&doc=$s_ $wims_name_erase
&nbsp;
   !endif
   <small>$n_by $a_</small>
  !next t
  </ul>
 !endif
!endif

!if $wims_class=$empty and $wims_ismanager<2
 !form reply
 Za va¹e lastne dokumente, vpi¹ite ime avtorja.
 <input size=20 name=authoring value="$authoring">
 <input type=submit value=OK>
 </form> <p>
!endif

!if $wims_ismanager<2 and ($wims_class=$empty or $wims_user=supervisor)
  !set wims_menu_items=!append line createdoc,1, cmd=reply&job=creat\
doctry,1,cmd=reply&job=auth2&doc=$draftd&block=main&coder=dddd\
  to $wims_menu_items
!endif

!tail

