!if $error!=$empty
 !read msg.phtml
 <p>
 !exit
!endif

<center><h1>$tit</h1></center>

!if $titb=$empty
 <p>
 Blok <tt>$block</tt> ¹e ni ustvarjen.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Ta stran ¹e ni odprta za branje. Vrnite se kasneje.
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Ta stran je zakljuèena in branje ni veè mogoèe.
 <p>
 !exit
!endif

:newblock
<a name=$block>
<h3>$titb</h3>

!read $wims_priv_thisdoc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $wims_priv_thisdoc/$block.def
 <p>
 !goto newblock
!endif

</div><div class=wimstail>
<p><hr>
<table width="100%" border=0 cellspacing=0 cellpadding=1>
<tr><td align=left nowrap><small>
Avtor
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
</small>
<td align=right><small>
!href cmd=reply&job=read&doc=$doc&block=$startblock Interaktivna razlièica
!if $wims_user=supervisor and $sheetdata!=$empty
 </small>
 <tr><td align=left nowrap>
 <small>Zadnja sprememba: $datm
 </small>
 <td align=right><small>
 !href cmd=reply&job=exosource&block=$startblock Koda za vaje na tej strani
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>Zadnja sprememba: $datm</small>
!endif
</table>

