
<h1 class="wims_docu_title">$tit<br>
$n_codechange
</h1>

!if $error!=$empty
 !read docu/msg.phtml
 <p><hr> <p>
!endif

!set wims_form_method=post
!form reply
<center><table border=0 cellspacing=5>
<tr><td nowrap align=right>Vpi¹ite trenutno geslo:
<td align=left><input type=password size=20 name=coder1>
<tr><td nowrap align=right>Vpi¹ite novo geslo:
<td align=left><input type=password size=20 name=coder>
<tr><td nowrap align=right>Ponovno vpi¹ite novo geslo:
<td align=left><input type=password size=20 name=coder2>

<tr><td colspan=2 align=center>
<input type=submit value="$wims_name_tosave">
<input type=submit name=abandon value="$wims_name_giveup">
</table></center></form>

<p><b>Opomba</b>. Za¹èitno geslo omogoèa spreminjanje za¹èitenega dokumenta. 
Vsebovati mora najmanj 
$codemin in najveè $codemax alfanumeriènih simbolov.

