!! fichier de modification des informations sur les exercices d'une feuille
!!
!distribute lines $wims_read_parm into directory_,parm_,require_,weight_,title_,desc_,dep_,comment_,feedback_
!! !set orgtit_=!module title $directory_
!read adm/title.phtml 1\
\
$name_titlemodif $modif
!form reply
   $table_header
   <input type="hidden" name="modif" value="$ex_">
   <input type="hidden" name="job" value="modify">
   $table_tr
    <td>$wims_name_title</td>
!!<small>($name_oldtitle <em>$orgtit</em>)</small></td>
    <td><input size="50" name="mod_title" value="$title_"></td>
   </tr>
   $table_tr
    <td>$wims_name_Description</td>
    <td><textarea name="mod_desc" rows="3" cols="60">$desc_</textarea></td>
   </tr>
   $table_tr
    <td>$(name_shtab[7]) <small>($name_desc_comment)</small></td>
    <td><textarea name="mod_comment" rows="3" cols="60">$comment_</textarea></td>
   </tr>
   $table_tr
    <td>$name_pointsasked</td>
    <td><input size="4" name="mod_require" value="$require_"></td>
   </tr>
   $table_tr
    <td>$name_weight</td>
    <td><input size="4" name="mod_weight" value="$weight_"></td>
   </tr>
   $table_tr
    <td>$(name_shtab[6])
    &nbsp;
    !set wims_ref_class=wims_button_help
     !href target=wims_mhelp cmd=help&special_parm=dependancies $wims_name_help
    </td>
    <td><input size="40" name="mod_dep" value="$dep_"></td>
    !reset mod_dep
   </tr>
   $table_tr
    <td>$(name_shtab[10])
    &nbsp;
    !set wims_ref_class=wims_button_help
     !href target=wims_mhelp cmd=help&special_parm=feedback $wims_name_help
    </td>
    <td><textarea name="mod_feedback" rows="1" cols="60" wrap="off">$feedback_</textarea></td>
   </tr>
   
   !let oef=!defof category in wimshome/public_html/modules/$directory_/INDEX
   !if oef isitemof $oef
    $table_tr
     <td>
      $(name_shtab[9])
      !let parm_=!replace internal & by ; in $parm_
      !let parm_=!replace internal scoredelay=; by scoredelay=0; in $parm_
      !let parm_=!replace internal exo=; by exo=0; in $parm_
      !let tmp_=!replace internal = by , in $parm_
      !let tmp2_=!column 1 of $tmp_
      !let tmp2_=!positionof item exo in $tmp2_
      !let tmp_=!column 2 of $tmp_
      !let tmp_=!item $tmp2_ of $tmp_
      !let tmp_=!nospace $tmp_
      !set wims_ref_class=wims_button
      !href target=wims_oef cmd=intro&module=$directory_&special_parm=&special_parm2=&special_parm3=exo=$tmp_;$parm_&special_parm4=$sheet,$modif $(seriesaction[1])
     </td>
     <td>$directory_ <br> $parm_ </td>
    </tr>
   !endif
   $table_tr
    <td colspan="2"><center>
     <input type="submit" value="$wims_name_tosave"> &nbsp;
     !set wims_ref_class=wims_button
     !href cmd=resume $wims_name_giveup
    </center></td>
   </tr>
  $table_end
</form>
