<table>
Utilisez pour :
    <td>
	Multiplications:
    </td>
    <td>
	<input size=20 value="5*x" readonly>
    </td>
    <tr>
    <td>
	Division: 
    </td>
    <td>
	<input size=20 value="5/x" readonly>
    </td>
    <tr>
    <td>
	Fractions: 
    </td>
    <td>
	<input size=20 value="2/3" readonly>
    </td>
    <tr>
    <td>
	Puissances:
    </td>
    <td>
	<input size=20 value="2^3" readonly><br>
	<input size=20 value="sin(x)^2" readonly>
    </td>
    <tr>
    <td>
	Nombre décimal:
    </td>
    <td>
	<input size=20 value="5.2" readonly> et non pas 5,2
    </td>
    <tr>
    <td>
	Coordonnées:
    </td>
    <td>
	<input size=20 value="(10:3)" readonly>
    </td>
    <tr>
    <td>
	Attention aux fractions: 
    </td>
    <td>
	<input size=20 value="5/3" readonly>  et non pas 1 2/3

    </td>
    <tr>
    <td>
	Parenthèses
    </td>
    <td>
	<input size=20 value="2/(3x)" readonly>
    </td>
    <tr>
    <td>
	Parenthèses
    </td>
    <td>
	<input size=20 value="sin(3x)" readonly><br>
	<input size=20 value="log(3x)" readonly>
    </td>
    <tr>
    <td>
	&radic;x: 
    </td>
    <td>
	<input size=20 value="sqrt(x)" readonly>
    </td>
    <tr>
    <td>
	<sup>n</sup>&radic;x: 
    </td>
    <td>
	<input size=20 value="sqrt[n](x)" readonly>
    </td>
    <tr>
    <td>
	log(x): 
    </td>
    <td>
	<input size=20 value="log[n](x)" readonly>
    </td>
    <tr>
    <td>
	&pi;: 
    </td>
    <td>
	<input size=20 value="pi" readonly>
    </td>
</table>
