!if $activetest>0
 Désolé, cet examen est activé, donc non modifiable. On ne peut plus changer
 les exercices dedans.
 !exit
!endif

!form reply
<input type=hidden name=job value=exo>
<input type=hidden name=exo value=$exo>
<p>Exercice $exo : poids=<input size=5 name=eweight value="$eweight">,
titre=<input size=20 name=ename value="$ename">
<p>
Cet exercice peut être pris (aléatoirement) dans une liste d'exercices
existants dans des feuilles de travail. Veuillez marquer parmi les exercices des
feuilles de la liste suivante ceux que vous voulez prendre pour cet exercice d'examen.
<p>
Afficher seulement les exercices de la feuille 
 <select name="ltsheets" onchange="submit()" value="$ltsheets">
  !if $ltsheets=$asheets
   <option value="$asheets" selected>Toutes</option>
  !else
   <option value="$asheets">Toutes</option>  
  !endif
  !for k in $asheets
   !if $ltsheets=$k
    <option value="$k" selected>
   !else
    <option value="$k">   
   !endif
    !let t=!record $k of  wimshome/log/classes/$wims_class/sheets/.sheets
    $k :
    !line 3 of $t
   </option>
  !next k
 </select>
<p>
!for i in $ltsheets
 !set t=!recordcnt wimshome/log/classes/$wims_class/sheets/.sheet$i
 !for j=1 to $t
  !set r=!record $j of wimshome/log/classes/$wims_class/sheets/.sheet$i
  !distribute line $r into r1,r2,r3,r4,r5,r6
  <input type=checkbox name=echoose value=$i.$j
  !if $i.$j isitemof $echoose
   checked
  !endif
  > $i.$j <b>$r5</b> <small>$r6</small> <br>
 !next j
!next i
<p>
Dépendances des scores&nbsp;: <input size=40 name=edep value="$edep"> <br>
Options:
!formcheckbox eopt list $optionlist
<br>
<input type=submit value="Enregistrer">
</form>
<p>
!href cmd=reply Page principale de l'examen
. <p><small>
<b>Aide</b>. Dépendances des scores veulent dire qu'un participant doit
  d'abord acquérir des points dans d'autres exercices de la feuille, avant
  de pouvoir travailler sur celui-ci. Par exemple,
  <font color=blue><tt>1:50,2:30,3+4+5:60</tt></font>
  signifie que le participant doit avoir un succès de 50% sur l'exercice 1,
  30% sur l'exercice 2, et une moyenne de succès de 60% sur les exercices
  3,4,5.
  <p>
  Pour les options : <ul>
  <li><em>autogen</em> veut dire que l'exercice est généré automatiquement
  même si l'utilisateur ne clique pas dessus. Pour qu'il puisse consulter
  l'exercice enregistré quand la session est fermée. Formellement déconseillé
  sauf pour exercices à correction manuelle.
  </ul>
</small>


