
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre

!set wims_name_endexam=Terminer la session d'examen
!set wims_name_scoreexam=Mon score

!set name_mainpage=Page principale de l'examen
!set name_dependency=Dépendances des scores&nbsp;
!set name_Options=Options
!set name_All=Toutes
!set name_title=Préparation de l'examen
!set name_expire=Expirer maintenant l'examen