
!if $job=score
 !read adm/title.phtml 1\
 $wims_classname, $wims_institutionname\
 $title
 
 !if $wims_user=supervisor
  <center>($name_presentation)</center>
 !endif
  <p>$desc<p>
!endif

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_back
. <p>
 !goto end
!endif

!if $exocnt=0
 $name_empty
!else
 <p><center><table border=1 bgcolor=bisque>
 <caption>$name_scoreexam</caption>
 <tr><th>$wims_name_Exercise<th>$wims_name_title</th><th>$name_coeff<th>$name_Score
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,li,ti
  <tr><td align=center>$i
  <td align=center>$ti
  <td align=center>$we<td align=center>
  !if $(replied$i)>0
   $(got$i)
  !else
   <small>en attente</small>
  !endif
 !next i
 <tr><td align=center colspan=4>
 !default score=$sprime
$name_scoreexam2: <b>$score</b> <small>/ 10</small>.
 $table_end
!endif
<p>

!if $registered=$empty
 Vous n'avez pas encore commencé votre travail sur l'examen.
 !href cmd=reply&job=student Commencer à travailler.
!else
 !if $timeleft<=0
   Le délai s'est écoulé&nbsp;!<p>
   Vous avez utilisé les $sdure minutes allouées pour cet examen.
   <p>
 !endif
 !if $allowtype=simulation
  Le score actuel n'est pas pris en compte, car l'examen est en mode
  simulation.
  !if $lastscore>0
   (Votre score réel pour cette feuille d'examen est $lastscore.)
  !endif
 !else
  Votre meilleur score pour cet examen est $lastscore. (C'est le meilleur
  score qui sera pris en compte.)
 !endif
 <p>
!set test=!recordcnt wimshome/$wims_sesdir/examscore.$exam
!if $test>=2
 !href cmd=reply&job=scorereg $name_endexam.
&nbsp;&nbsp;
!endif
 !href cmd=reply&job=student $name_backexam.
!endif

!if $wims_user=supervisor
 <p><center>
 !href cmd=resume $name_teacherview.
 </center>
!endif

:end
!tail

!reset job

