!set email=!trim $email
!set author=!trim $author

!if $author!=$empty
 Autor de este ejercicio:
 !if $email!=$empty
  !mailurl $email $author
.
 !else
  $author.
 !endif
!endif
!if $solution!=$empty and $hint!=$empty
 Este ejercicio contiene solución explicada y pista.
!endif
!if $solution!=$empty and $hint=$empty
 Este ejercicio tiene solución explicada, pero no pista.
!endif
!if $solution=$empty and $hint!=$empty
 Este ejercicio contiene pista, pero no solución explicada.
!endif
!if $solution$hint=$empty
 Este ejercicio no tiene solución explicada ni pista.
!endif
Enlace para este ejercicio: <br>
!set exolink=$wims_ref_name?module=$module&cmd=new&exo=$thisexo
<a href=$exolink>$exolink</a> <br>
Enlace para la configuración actual: <br>
!if $module_init_parm!=$empty
 !set exolink=$wims_ref_name?module=$module&cmd=new&$module_init_parm
!else
 !set exolink=$wims_ref_name?module=$module&cmd=new
!endif
<a href=$exolink>$exolink</a>
<p>
Información sobre esta colección de ejercicios. <p>
$module_about
<p>
El copyright de los ejercicios pertenece a sus respectivos autores.

!changeto NEWS.phtml
