!read adm/title.phtml 1\
$classname\
$wims_name_regmanage

!reset table_center
!set typen=!defof class_typename in wimshome/log/classes/$wims_class/.def
!if $usercnt=0
    <div class="wimscenter">
    $name_noyetparticipant
    !if $typen!=level
        &nbsp;
     !set wims_ref_class=wims_button
    !href module=adm/class/reguser&step=1 $wims_name_addstudent
&nbsp;
    !endif
    </div>
!else

!form reply
<fieldset class="property_fields blockcenter">
 <legend>$name_grpaction</legend>
 <p>$name_expert0</p>
  <div class="field box">

    <ul>
      !set wims_html_mode= li
      !set wims_ref_class=wims_formradio
      !set wims_ref_id=motd_type
      !set listuserchoices=__ALL__,__CHECK__
      !!,__FILTER__
      !set listusernchoices=$name_all,$name_checked
      !!,$name_filter
      !formradio listuserchoice list $listuserchoices prompt $listusernchoices
    </ul>
    <div style="margin-left:4.5em;" id="tech_var">
      !set wims_ref_class=wims_button_help float_right
      !href cmd=help&special_parm=filter $wims_name_help
      <label for="varfilter">$name_technical_var:</label>
      <textarea name="varfilter" id="varfilter">$varfilter</textarea>
    </div>

    !!# Avec JQuery, Le champ "variable technique" n'apparait que lorsqu'il est necessaire.
    !if $jquery_defined=yes
      <script type="text/javascript">
        /*<![CDATA[*/ jQuery(function(jq) {
          jq( "#tech_var" ).hide();
          jq( "#motd_type3" ).click(function() {
            jq( "#tech_var" ).slideDown();
          });
          jq( "#motd_type1, #motd_type2" ).click(function() {
            jq( "#tech_var" ).slideUp();
          });
        }); /*]]>*/
      </script>
    !endif

  </div>
  <div>
    <p>$name_expert1</p>
    !set wims_html_mode= li
    !set wims_ref_class=wims_formcheck
    !set wims_ref_id=motd_class
    !for k=1 to $nbsubclasses
              <input type="checkbox" name="listsclassch" id="listsclassch$k" value="$(ltsubclasses[$k])"/> <label for="listsclassch$k">$(ltnamesubclasses[$k])</label>
    !next k
  </div>

 <div class="wimscenter">
  <input type="hidden" name="job" value="regmanage" />
  <input type="submit" name="action" value="$name_reguser" $wims_on_click/>
  <input type="submit" name="action" value="$name_unreguser" $wims_on_click/>
 </div>
</fieldset>

!! ----- displaying table of participant
    $table_header
    $table_hdtr
        <th>&nbsp;</th>
        <th>$name_studentglo</th>
       !for l=1 to $nbsubclasses
            <th>$(ltnamesubclasses[$l]) ($(ltsupsubclasses[$l])) </th>
       !next l
   </tr>
    !readproc adm/class/mkcomment name
    !let namecomment=$scriptout
    !for i=1 to $usercnt
	!set uu=!record $i of wimshome/log/classes/$wims_class/.userlist
	!distribute items $uu into bl,bl,uu
	!if $varfilter_!=$empty
    	    !read adm/class/testfilter $uu\
$varfilter_
	!endif
	!if $(var_filter_test)=1 or $varfilter_=$empty
!!        !set UU=!hex $uu
          !reset user_exists,user_email,user_regnum,user_external_auth,user_vars,user_comments$namecomment,user_comments,user_participate
          !readproc adm/class/userdef classes,$wims_class,$uu
          !readdef $userdef
          !set user_vars=!sh grep -E '^!set user__' $Userdef | sed 's/^!set user__//g'
    	  $table_tr
            <td><input type="checkbox" name="listuser" id="listuser$k" value="$uu"/> <label for="listuser$k"></label></td>
            <td>
        	!href cmd=reply&job=userprop&getuser=$uu $name_studentloc
        	!if $uu isitemof $wims_connectedlogin
        	    <img src="gifs/themes/$wims_theme_icon/connected.png" width="15px" alt="connected" />
        	!endif
    	    </td>
            !for k in $ltsubclasses
                 <td>
                    !if $k isitemof $user_participate
                	c
            	    !else
            	        &nbsp;
            	    !endif
                 </td>
            !next k
    	  </tr>
	!endif
    !next i
    </table>
    !formend
!endif

!! define wims_menu_items
!set wims_menu_items=!append line back2,1,module=adm/class/usermanage&job=userlist to $wims_menu_items
