!read adm/title.phtml 1\
$classname\
$wims_name_regmanage

!reset table_center
!set typen=!defof class_typename in wimshome/log/classes/$wims_class/.def
!if $usercnt=0
    <div class="wimscenter">
    $name_noyetparticipant
    !if $typen!=level
        &nbsp;
      !set wims_ref_class=wims_button
      !href module=adm/class/reguser&step=1 $wims_name_addstudent
&nbsp;
    !endif
    </div>
!else
 !form reply
 <fieldset class="property_fields blockcenter">
  <legend>$name_grpaction</legend>
  <div class="field box">
    <p>$name_expert0</p>
    <ul>
      !set wims_html_mode=li
      !set wims_ref_class=wims_formradio
      !set wims_ref_id=motd_type
      !if $tv_listtechvar!=$empty
       !set listuserchoices=__ALL__,__CHECK__,__FILTER__
       !set listusernchoices=$name_all,$name_checked,$name_filter
      !else
       !set listuserchoices=__ALL__,__CHECK__
       !set listusernchoices=$name_all,$name_checked,
      !endif
      !formradio listuserchoice list $listuserchoices prompt $listusernchoices
    </ul>
    !if $tv_listtechvar!=$empty
    <div style="margin-left:4.5em;" id="tech_var">
      !read adm/vfilter/varfilter htmldiv
    </div>
!! DON'T WORK : WHY ? (FG)
!!    !!# Avec JQuery, Le champ "variable technique" n'apparait que lorsqu'il est necessaire.
!!    !if $jquery_defined=yes
!!      <script type="text/javascript">
!!        /*<![CDATA[*/ jQuery(function(jq) {
!!          jq( "#tech_var" ).hide();
!!          jq( "#motd_type3" ).click(function() {
!!            jq( "#tech_var" ).slideDown();
!!          });
!!          jq( "#motd_type1, #motd_type2" ).click(function() {
!!            jq( "#tech_var" ).slideUp();
!!          });
!!        }); /*]]>*/
!!      </script>
!!    !endif
   !endif
  </div>
  <div class="field box">
  <p>$name_expert1</p>
  !set wims_html_mode=li
  !set wims_ref_class=wims_formcheck
  !set wims_ref_id=motd_class
  !for k=1 to $nbsubclasses
    !set k_=!replace internal / by _ in $k
     <input type="checkbox" name="listsclassch" id="listsclassch$k_" value="$(ltsubclasses[$k])"/><label for="listsclassch$k_">$(ltnamesubclasses[$k])</label>
  !next k
  </div>
 <div class="wimscenter">
  <input type="hidden" name="job" value="regmanage" />
  <input type="submit" name="action" value="$name_reguser" $wims_on_click/>
  <input type="submit" name="action" value="$name_unreguser" $wims_on_click/>
 </div>
</fieldset>

!! ----- displaying table of participant
    $table_header
    $table_hdtr
        <th></th>
        <th>$name_studentglo</th>
       !for l=1 to $nbsubclasses
            <th>$(ltnamesubclasses[$l])<br/> ($(ltsupsubclasses[$l]))</th>
       !next l
   </tr>
    !readproc adm/class/mkcomment name
    !let namecomment=$scriptout
    !for i=1 to $usercnt
     !set uu=!record $i of wimshome/log/classes/$wims_class/.userlist
     !distribute items $uu into bl,bl,uu
     !if $varfilter_!=$empty
        !read adm/vfilter/testfilter $uu\
$varfilter_
     !endif
     !if $(var_filter_test)=1 or $varfilter_=$empty
!!        !set UU=!hex $uu
          !reset user_exists,user_email,user_regnum,user_external_auth,user_vars,user_comments$namecomment,user_comments,user_participate
          !readproc adm/class/userdef classes,$wims_class,$uu
          !readdef $userdef
          !set user_vars=!sh grep -E '^!set user__' $Userdef | sed 's/^!set user__//g'
          $table_tr
            <td><input type="checkbox" name="listuser" value="$uu"/></td>
            !reset css_connected
            !if $uu isitemof $wims_connectedlogin
              !set css_connected=class="wims_connected"
              !set wims_ref_title=connected
            !endif
            <td><span $css_connected>
            !href cmd=reply&job=userprop&getuser=$uu $name_studentloc
            </span></td>
            !for k in $ltsubclasses
              <td class="wimscenter">
              !if $k isitemof $user_participate
                &#x2705;
              !endif
               </td>
            !next k
          </tr>
    !endif
    !next i
    </table>
    !formend
!endif

!! define wims_menu_items
!set wims_menu_items=!append line back2,1,module=adm/class/usermanage&job=userlist to $wims_menu_items
