!! display list of participant
!! work to do

!!exit

!reset table_center

!! display table of participant with usual information

!!ATTENTION : fichier de langue touche . Seul le français est touche il faudra repercuter.
!!ATTENTION : il faut faire un tableau different en fonction du niveau de structure de la classe d'appel (portail, superclass, etc...) reflechir à ce que l'on affiche.

!if $usercnt=0
    <div class="wimscenter">
    !set typen=!defof class_typename in wimshome/log/classes/$wims_class/.def
    $name_noyetparticipant
    !if $typen!=level
        &nbsp;
	!set wims_ref_class=wims_button
	!href module=adm/class/reguser&step=1 $wims_name_addstudent
	&nbsp;
    !endif
!!    20141016 : deconnecte pour l'instant, attente d'organisation.
!!    !set wims_ref_class=wims_button
!!    !href cmd=reply&job=csv $wims_name_csv
    </div>
!else
!! ------ manage ask for technical variable selection.
    !form reply
	<p>
 		$name_filter
		<textarea name="varfilter">$varfilter</textarea>
 		!set wims_ref_class=wims_button_help float_right
 		!href cmd=help&special_parm=filter $wims_name_help
  	</p>
	<div class="wimsform wimscenter">
  		<input type="submit" value="$wims_name_Show" />
  	</div>
    !formend
!! ----- displaying table of participant
    $table_header
	$table_hdtr
	    !for k in $name_studentglo,$wims_name_Login,$wims_name_email,$name_regnum,$name_external_auth,$name_comments
		<th>$k</th>
	    !next k
	</tr>
    !for i=1 to $usercnt
	!set uu=!record $i of wimshome/log/classes/$wims_class/.userlist
	!distribute items $uu into bl,bl,uu
	!if $varfilter_!=$empty
	    !read adm/class/testfilter $uu\
$varfilter_
	!endif
	!if $(var_filter_test)=1 or $varfilter_=$empty
          !set UU=!hex $uu
          !reset user_exists,user_email,user_regnum,user_external_auth,user_comments
          !readproc wimshome/log/classes/$wims_superclass/.users/$uu
	  $table_tr
             <td>
		!href cmd=reply&job=userprop&getuser=$uu $name_studentloc
	        !if $uu isitemof $wims_connectedlogin
		    <img src="gifs/themes/$wims_theme_icon/connected.png" width="15px" alt="connected" />
	        !endif
	     </td>
	     <td>$uu</td>
             !for k in email,regnum,external_auth,comments
                 <td> $(user_$(k)) </td>
             !next k
          </tr>
	!endif
    !next i
    </table>
!endif


!! menu_items 
!! define wims_menu_items for all job

!set wims_menu_items=!append line sendmail,1,module=adm/class/sendmail\
photoboard,1,module=adm/class/photoboard\
Score1,1,module=adm/class/userscore\
,0,\
to $wims_menu_items
!if $typen!=level
 !set wims_menu_items=!append line addstudent,1,module=adm/class/reguser&step=1\
to $wims_menu_items
!endif

!! disconnected for a few time 
!!!set wims_menu_items=!append line csv,1,cmd=reply&job=csv\
!! ,0,\
!!to $wims_menu_items
