<center>$classname<p>

!if $logname=$empty
 La richiesta non &egrave; valida.
!else
 <h3>Dettagli del lavoro svolto da $firstname $lastname</h3>
 (dati non elaborati)
 </center> <p>
<pre>
!set test=$wims_show_ip
!mexec getraw.sh
</pre>
!endif

!!<p><center>
!!!href cmd=reply&job=getuser&getuser=$getraw Elabora i dati
!! .
!!!href cmd=resume Elenco iscritti
!! .
!!</center> <p>

!set wims_menu_tail=!append line getraw,1,cmd=reply&job=getuser&getuser=$getraw\
part_list,1,cmd=resume\
to $wims_menu_tail
