
!set classname=$wims_classname - $wims_institutionname

!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!distribute line Moyenne de la classe\
Moyenne\
Moyenne des notes positives\
into name_classAverage,name_Average,name_posAverage

!set name_partdeleted=Participants supprimés
!set name_reg_ex=Liste des exercices enregistrés
!set name_transfer=Transférer ses activités d'autres classes

!set name_thsheet=No,titre,points<br>requis,poids,points<br>obtenus,%,qualité,sévérité,note
!set name_minmax=min/moyen/max de la classe&nbsp;

!set name_manualscore=Notes attribuées par l'enseignant
!set name_examnote=Notes d'examens

!set name_severitylevels=Niveaux de sévérité des feuilles de travail
