!exit
!set renewlink=cmd=renew&worksheet=$worksheet&$module_init_parm
!set module_title=$module_title: $title

!header

!if $title=$empty
 Ta modul zdru¾uje veè vaj. Ka¾e, da niste pravilno izbrali posamezne vaje. Morda ste kliknili na napaèno povezavo ali pa gre za napako v programu.
 <p><center>
 !href module=$module Poskusite znova
  ali
 !href $ opustite zahtevo
 . </center>
 !goto end
!endif

:tester
!read proc/present.phtml

<p><hr width="50%"> <p>

!if $cmd=hint
 !read proc/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read proc/msg.phtml
  <p><hr width="50%"> <p>
 !endif
 !read proc/form.phtml
 <p>
 !if $hint!=$empty and $givehint>0
  !href cmd=hint Namig
.
 !endif
 !if $qnum<=1
  !href $renewlink Obnovi vajo
.
 !else
  To je vaja ¹tevilka $[$reply_cnt+1] v nizu. ©tevilo vseh vaj v nizu je $qnum.
  !href $renewlink Opusti re¹evanje niza
.
 !endif
!else
 !if $error!=$empty
  !read proc/msg.phtml
  <p><hr width="50%"> <p>
 !endif
 !read proc/answer.phtml
 <p>
 !if $status!=$empty
  To je vaja ¹tevilka $reply_cnt v nizu. ©tevilo vseh vaj v nizu je $qnum. <p>
  !href cmd=next Nadaljuj niz z naslednjo vajo
, ali
  !href $renewlink opusti niz in zaèni od zaèetka
. (Va¹e delo se toèkuje le, èe zakljuèite celoten niz.)
 !else
  !if $qnum>1
   Zakljuèili ste z re¹evanjem niza vaj s skupno oceno
   $score od 10.
   !ifval $score>9.8
    Èestitke!
   !endif
   <p>
   !href $renewlink Nov niz
.
   !if $wims_sheet=$empty
    !href module=$module&cmd=intro&special_parm=$wims_intro_parm Spremeni stopnjo zahtevnosti
.
   !endif
  !else
   Dobili ste oceno $score od 10.
   !ifval $score>9.8
    Èestitke!
   !endif
   <p>
   !href $renewlink ©e enkrat
.
   !if $wims_sheet=$empty and $oef_test!=yes
    !href exo_Intro
.
   !endif
  !endif
 !endif
!endif

!read endhook.phtml
:end

!tail

