
<span class="wims_warning">$wims_name_warning</span>.

!read lang/names.phtml.$modu_lang del

<span class="wims_mod_title">
!module title devel/$auth_login/$mod
</span> (<span class="tt wims_fname">$modreq</span>)?
!!open in names.phtml.$modu_lang del
</p>

<div class="wimscenter">
!href cmd=reply&jobreq=del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&jobreq=flist $wims_name_no
</div>
