
!read adm/title.phtml 3\
\
$title

!if $bad$writable$execable$baduser$bad_wrapexec$bad_chroot$bad_wimsd$noexec=$empty
 $name_attrib1
 !sh rm -f $wims_home/log/unsecure
!else
 <b><font color="red">$wims_name_warning</font></b><p>
 !if $bad!=$empty
  $name_attrib2
<pre>
!words2lines $bad
</pre> <p>
 !endif
 !if $writable!=$empty
  !if $writcnt>=50
   $name_attrib3<p>
   $name_attrib4
   !href cmd=reply $name_repeat
   ($name_attrib5).
   <p>$name_attrib6
<pre>
!words2lines $writable

......
</pre>
  !else
   $name_attrib7
<pre>
!words2lines $writable
</pre>
  !endif
  <p>
 !endif
 !if $execable!=$empty
  !if $execnt>=50
   $name_attrib8<p>
   $name_attrib4
   !href cmd=reply $name_repeat
   ($name_attrib5).
   <p>$name_attrib6:
<pre>
!words2lines $execable

......
</pre>
  !else
   $name_attrib8
<pre>
!words2lines $execable
</pre>
  !endif
  <p>
 !endif
 !if $baduser!=$empty
  !if $usercnt>=50
   $name_attrib9
<pre>
!words2lines $baduser

......
</pre>
  !else
   $name_attrib10
<pre>
!words2lines $baduser
</pre>
  !endif
  <p>
  $name_warning1
  <p>
 !endif
 !if $bad_wrapexec=yes
    $name_warning_wrapexec
    <p>
 !endif
 !if $baduser!=$empty
     $name_warning2
 !endif
 !if $bad_chroot=true
    $name_warning_chroot
    <p>
 !endif
 !if $bad_wimsd=true
    $name_warning_wimsd
    <p>
 !endif
 !if $noexec!=$empty
  $name_attrib11
  <pre>
!words2lines $noexec
</pre>
  <p>
 !endif
 !if $writcnt<50 and $execnt<50 and $usercnt<1 and $bad_wrapexec=$empty and $writcnt>0 and $execnt>0
  $name_warning3
 !endif
!endif

