
!if $test=$empty or $nlist=$empty
 $name_backup
 !href cmd=reply&job=conf&confcat=6 $name_click
$name_daily
 !goto end
!endif

<p class="wimstech">
$name_last: $test.
$name_download: </p>
!for f in $nlist
 !getfile $f $f
 <br />
!next f

:end

!set wims_form_method=file
!form reply
<input type="hidden" name="job" value="restore" />
<input type="hidden" name="job2" value="restore" />
$name_restore: <br />
<input type="file" name="wims_deposit" size="50" />
<input type="submit" value="$wims_name_tosave" />

!formend
<p class="small">
$name_fast
</p>

!reset job2

