
<p>
!href cmd=reply&job=conf&confcat=2 $name_click
 $name_config

!if $sccnt+$clcnt<1
 <p>
 $name_noclass
 !reset keyword
 <p>
 !href cmd=reply&job=class $name_listclass
 .
 !exit
!endif

<br>$name_total
<p> <center>
 !form reply
  !default bst_num=10
  !let tmp=!date -d '1 month ago' '+%Y%m%d'
  !default bst_since=$tmp
  <input type="text" name="bst_num" value="$bst_num" size="4">$name_bestcumul 
  <input type="text" name="bst_since" value="$bst_since" size="7">
  <small>$name_format <tt class="wims_">yyyymmdd</tt>.
  <input type="hidden" name="job" value="bestclass">
  <input type="submit" value="$wims_name_refresh">
 </form>
 </center> 
<p>

!if $sccnt>0
<p>$table_header
<caption>$name_list</caption>
$table_hdtr
<th>$wims_name_name</th><th>$wims_name_action</th><th>$wims_name_Language</th><th>$wims_name_supervisor</th>
<th>$name_created<br><tt class="wims_code_words">yyyymmdd</tt></th>
<th>$name_expire<br><tt class="wims_code_words">yyyymmdd</tt></th>
<th>$name_load<sup>[1]</sup></th>
<th>$name_part</th></tr>
!for i=1 to $sccnt
 !set l=!line $i of $sclasses
 !distribute items $l into c_,l_,s_,m_,f_,e_,d_,t_,load_,u_
 !default f_=--
 $table_tr
 <td align="center"><small>$t_<br>$d_</small></td>
 <td>
 !set wims_ref_class=wims_button
 !href cmd=reply&job2=erase&jobclass=$c_ $wims_name_erase
&nbsp;
!set wims_ref_class=wims_button
 !href cmd=reply&job2=modify&jobclass=$c_ $wims_name_change
&nbsp;
!set wims_ref_class=wims_button
 !href module=adm/class/classes&type=authsupervisor&class=$c_&auth_user=supervisor&auth_password=*wims_site_manager $name_visit
 </td>
 <td align="center">$l_</td>
 <td align="center"><small>
 <a href="mailto:$m_?subject=$name_yourclass">$s_</a></small>
 </td>
 <td align="center">$f_<td align="center">$e_</td>
 <td align="center">$load_</td>
 <td align="center">$u_</td>
 </tr>
!next i
$table_end
!endif

!if $clcnt>0
<p>$table_header
<caption>$name_listindependant</caption>
$table_hdtr
<th>$wims_name_name</th><th>$wims_name_action</th><th>$wims_name_Language</th><th>$wims_name_Supervisor</th>
<th>$name_created<br><tt class="wims_code_words">yyyymmdd</tt></th>
<th>$name_expire<br><tt class="wims_code_words">yyyymmdd</tt></th>
<th>$name_load<sup>[1]</sup></th>
<th>$name_part</th> 
!for i=1 to $clcnt
 !set l=!line $i of $classes
 !distribute items $l into c_,l_,s_,m_,f_,e_,d_,t_,load_,u_
 !default f_=--
 $table_tr
 <td align="center"><small>$t_<br>$d_</small></td>
 <td>
 !set wims_ref_class=wims_button
 !href cmd=reply&job2=erase&jobclass=$c_ $wims_name_erase
&nbsp;
!set wims_ref_class=wims_button
 !href cmd=reply&job2=modify&jobclass=$c_ $wims_name_change
&nbsp;
!set wims_ref_class=wims_button
 !href module=adm/class/classes&type=authsupervisor&class=$c_&auth_user=supervisor&auth_password=*wims_site_manager $name_visit
</td>
<td align="center">$l_</td>
 <td align="center"><small>
 <a href="mailto:$m_?subject=$name_yourclass">$s_</a></small></td>
 <td align="center">$f_<td align="center">$e_</td>
 <td align="center">$load_</td>
 <td align="center">$u_</td>
 </tr>
!next i
$table_end
!endif
<center><b>[1]</b> <i>"$name_load" $name_cumul_student 
!read date.phtml $bst_since,notime
.</i></center>
<center>
!set wims_ref_class=wims_button
!href cmd=reply&job=class $wims_name_back2
</center>

