!if $error!=$empty
  <div class="wims_msg alert">
  !read lang/msg.phtml.$modu_lang
  !reset error
  !set wims_ref_class=wims_button
  !href cmd=new&job=classrestore $wims_name_back2
  </div>
  !exit
  !reset error
!endif

!if $stepcl=$empty or $stepcl<1
  !if $cnt>0
   $name_restore_choose
!form reply
   <ul>
  !for y in $listyear
    <li>
     !if $(listclass$y)!=toomuch
       $y.
       <ul>
       !for cl in $(listclass$y)
       <li>
       !formradio clrestore list $(y)_$cl prompt $cl
       </li>
       !next
       </ul>
     !else
       !formradio clrestore list $(y)
. $name_toomuchbackup
      <div class="wimscenter wims_form">
      <input type="text" name="clrestore1" value="" />
      </div>
     !endif
  </li>
  !next
 </ul>
     <div class="wimscenter wimsform">
     <input type="hidden" name="stepcl" value="1" />
     <input type="submit" name="" value="$wims_name_tosave" />
     </div>
!formend
  !else
    $name_restore_noclass
    !reset stepcl
  !endif
 !else
   !if $test!=$empty
     !exit
   !endif
<div class="msg info">
  $name_restore_done
</div>
 !reset stepcl clrestore clrestore1
 !endif



