
!if $job2!=first
 !changeto class/$job2.phtml
!endif
<p>
!href cmd=reply&job=conf&confcat=2 $name_click
 $name_config

!read class/search.phtml
!if $overflow=yes
 !exit
!endif

!if $sccnt+$clcnt<1
 <p>
 $name_noclass
 !reset keyword
 !exit
!endif

!if $sccnt>0
<p>$table_header
<caption>$name_list</caption>
$table_hdtr
<th>$wims_name_name<th>$wims_name_action<th><small>$wims_name_Language</small><th>$wims_name_Supervisor
<th>$name_created<br><small>yyyymmdd</small>
<th>$name_expire<br><small>yyyymmdd</small>
!if $actives=yes
 <th>load<sup>[1]</sup></th>
!endif
!for i=1 to $sccnt
 !set l=!line $i of $sclasses
 !distribute items $l into c_,e_,t_,d_
 !set l=!defof class_lang\
class_supervisor\
class_email\
class_creation in wimshome/log/classes/$c_/.def
 !distribute lines $l into l_,s_,m_,f_
 !default f_=--
 $table_tr
 <td align="center"><small>$t_<br>$d_</small>
 <td>
 !href cmd=reply&job2=erase&jobclass=$c_ $wims_name_erase
&nbsp;
 !href cmd=reply&job2=modify&jobclass=$c_ $wims_name_change
&nbsp;
 !href module=adm/class/classes&type=authsupervisor&class=$c_&auth_user=supervisor&auth_password=*wims_site_manager $name_visit
 <td align="center">$l_</td>
 <td align="center"><small>
 <a href="mailto:$m_?subject=$name_yourclass">$s_</a></small>
 <td align="center">$f_<td align="center">$e_
 !if $actives=yes
  !default activ_$c_=-
  <td align="center">$(activ_$c_)</td>
 !endif
!next i
$table_end
!endif

!if $clcnt>0
<p>$table_header
<caption>$name_listindependant</caption>
$table_hdtr
<th>$wims_name_name<th>$wims_name_action<th><small>$wims_name_Language</small><th>$wims_name_Supervisor
<th>$name_created<br><small>yyyymmdd</small>
<th>$name_expire<br><small>yyyymmdd</small>
!if $actives=yes
 <th>load<sup>[1]</sup></th>
!endif
!for i=1 to $clcnt
 !set l=!line $i of $classes
 !distribute items $l into c_,e_,t_,d_
 !set l=!defof class_lang\
class_supervisor\
class_email\
class_creation in wimshome/log/classes/$c_/.def
 !distribute lines $l into l_,s_,m_,f_
 !default f_=--
 $table_tr
 <td align="center"><small>$t_<br>$d_</small>
 <td>
 !href cmd=reply&job2=erase&jobclass=$c_ $wims_name_erase
&nbsp;
 !href cmd=reply&job2=modify&jobclass=$c_ $wims_name_change
&nbsp;
 !href module=adm/class/classes&type=authsupervisor&class=$c_&auth_user=supervisor&auth_password=*wims_site_manager $name_visit
 <td align="center">$l_</td>
 <td align="center"><small>
 <a href="mailto:$m_?subject=Your WIMS virtual class">$s_</a></small>
 <td align="center">$f_<td align="center">$e_
 !if $actives=yes
  !default activ_$c_=-
  <td align="center">$(activ_$c_)</td>
 !endif
!next i
$table_end
!endif

!if $actives=yes
 <p> <center>
 !form reply 
 <small><b>[1]</b>. ``<em>load</em>'' 
$name_cumul
 <input type=text name="bst_since" value="$bst_since" onchange="submit()">$name_format <font color=blue>yyyymmdd</font></small>.
 <input type=hidden name="keyword" value="$keyword">
 </form>
 !href cmd=reply&job=bestclass&keyword=$keyword $wims_name_Show
 !default bst_num=10
 $bst_num $name_best.
 </center> <p>
!endif

!reset keyword
