!read adm/title.phtml 3\
\
$title

!if $error!=$empty
 !if $error=manual
  $name_manually
  <p>
  <font color="red"><b>$name_warning</b></font>
 !endif
 !if $error=bad_base
 $name_strange
 !endif
 !goto end
!endif

!form reply
<input type=hidden name="job2" value=second>
$name_available
<ul>
<li><p>$name_daily
!set crontab_backup_h=$oldbackup_h
!formselect crontab_backup_h from -1 to 23 prompt\
	none,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
H.
<input size=2 name="crontab_backup_m" value="$oldbackup_m"> Min.
($name_notbusy)
<li><p>$name_accounting 
!formradio crontab_account list yes,no prompt $wims_name_yes,$wims_name_no
</ul>
<center><input type=submit name="confirm" value="$wims_name_tosave">
<input type=submit name="abandon" value="$wims_name_giveup">
</center>
</form> <p>

:end
!reset job2 abandon
