
!if $job2=one
 !read mu/one.phtml
 !reset auto muauto
 !exit
!endif

!if $job2=all
 $name_scheduled
 <p> <hr width="70%"> <p>
 !set job2=first
 !reset auto muauto
!endif

!form reply
<input type=hidden name="muauto" value=check>
$table_header
 <tr>
  <td align="right"><input type=submit value="$wims_name_search"> $name_mod</td>
  <td>
   !let nb=!itemcnt $mu_download_site
   !if $nb>1
    <ul>
    !for k in $mu_download_site
     <li>$(depotname_$k) ($k)</li>
    !next depot
   </ul>
  !else
   $(depotname_$(mu_download_site)) ($mu_download_site)
  !endif
  </td>
 </tr>
 <tr>
  <td align="right">$name_zone</td>
  <td><input size=40 name="muzone" value="$muzone"></td>
 </tr>
 <tr>
  <td align="right">$name_cat</td>
  <td><input size=40 name="mucat" value="$mucat"> </td>
 </tr>
 <tr>
  <td align="right">$name_change</td>
  <td><input size=4 name="mudelay" value="$mudelay"> $name_ago</td>
 </tr>
$table_end
</form>

<p> <hr width="70%"> <p>

$name_youneed
!href cmd=reply&job=mkindex $name_rebuild
 $name_after.
!href cmd=reply&job=conf&confcat=6 $name_click
 $name_automatic

$name_rss
!href cmd=reply&job=rss RSS. 
!if $auto=check
 !read mu/$auto.phtml
!endif

!reset muauto
