!if $error!=$empty
  <div class="wims_alertmsg">
  !read lang/msg.phtml.en
  </div>
!endif

!if $step=$empty
 !form reply
  $table_header
   $table_tr
    <td>$name_subject</td>
    <td><input name="sendmail_subject" size="45" value="$sendmail_subject"/></td>
   </tr>
   $table_tr
    <td>$name_message</td>
    <td><textarea name="sendmail_msg" cols="80" rows="10">$sendmail_msg</textarea></td>
   </tr>
   $table_tr
    <td>$(name_dest[1])</td>
    <td>
     !for k=1 to $nbcheck_list
      <input type="checkbox" name="sendmail_dest" value="$k"/>$(check_list[$k]) ($(cnt_list[$k]))<br/>
     !next k
    </td></tr>
   $table_tr
    <td colspan="2" align="center">
     <input type="hidden" name="step" value="1"/>
     <input type="submit" name="sendmail_reg" value="$wims_name_tosave"/>
     !set wims_ref_class=wims_button
     !href cmd=renew $wims_name_giveup
    </td>
   </tr>
  $table_end
 
!formend
!else
  $table_header
   $table_tr
    <td>$name_subject</td>
    <td>$save_subject</td>
   </tr>
   $table_tr
    <td>$name_message</td>
    <td>$save_msg</td>
   </tr>
   $table_tr
    <td>$(name_dest[1])</td>
    <td>
     !replace internal , by <br/> in $save_list
    </td>
   </tr>
   $table_tr
    <td colspan="2" align="center">
    !if $step=1
     !form reply
      <input type="hidden" name="step" value="2"/>
      <input type="submit" name="sendmail_reg" value="$wims_name_send"/> &nbsp;
      !set wims_ref_class=wims_button
      !href cmd=renew $wims_name_giveup

     !formend
    !else
     $name_sending
     !reset step
    !endif
    </td>
   </tr>
  $table_end
!endif
!reset sendmail_subject,sendmail_dest,sendmail_reg,sendmail_msg