
!read adm/title.phtml 3\
\
$title

$name_content_s <tt>$checkses</tt>: <small>[
!href cmd=reply $wims_name_refresh
 ]</small> <p>
<small><pre>----------------------------------------------------------------
$content
----------------------------------------------------------------</pre></small>
<p>

$name_content_v <tt>var</tt>:<p>
<small><pre>----------------------------------------------------------------
!sh cat $wims_home/sessions/$checkses/var
----------------------------------------------------------------</pre></small>
<p>

!if $varstat!=$empty
$name_content_f <tt>var.stat</tt>:<p>
<small><pre>----------------------------------------------------------------
$varstat
----------------------------------------------------------------</pre></small>
<p>
!endif

<center>
!href cmd=reply&job=activ $name_listsessions
</center>

