
!read adm/title.phtml 3\
\
$title
<p>
$name_content_s <span class="tt">$checkses</span>: <span class="small">[
!href cmd=reply $wims_name_refresh
 ]</span> </p>
<small><pre>----------------------------------------------------------------
$content
----------------------------------------------------------------</pre></small>
</p><p>

$name_content_v <span class="tt">var</span>:<p>
<small><pre>----------------------------------------------------------------
!sh cat $wims_home/sessions/$checkses/var
----------------------------------------------------------------</pre></small>
</p><p>

!if $varstat!=$empty
$name_content_f <span class="tt">var.stat</span>:<p>
<small><pre>----------------------------------------------------------------
$varstat
----------------------------------------------------------------</pre></small>
</p>
!endif

<div class="wimscenter">
!href cmd=reply&job=activ $name_listsessions
</div>

