!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.

!if dontknow iswordof $error
 En fait, la dernière étape
 !if $step_reason=OK
  est correcte. $step_remark
 !else
  n'est pas correcte. $step_remark 
  <p>
  !read reasons/$step_reason.det
  <p>
  Une version correcte de la dernière étape sera<p><center>
  <table border=0 bgcolor=#d0c0d0 width=80%><tr><td align=center>
  !line $step of $good
  </table> </center>
 !endif
 <p>Dommage que tu n'as pas pu voir tout ça.
 !goto gnext
!endif

<b>Erreur.</b>

!if step_error iswordof $error
 !if $step_reason=OK
  Mais si, cette étape est parfaitement correcte&nbsp;!
  $step_remark
 !else
  !if $ask_reason>0 and $step_reason!=$ans
   Non, la dernière étape est bien erronée, mais pas à cause de ce que tu penses.
  !else
   Mais non, il y a bien une erreur dans la dernière étape.
  !endif
  $step_remark
  <p>
  !read reasons/$step_reason.det
  <p>
  Une version correcte de la dernière étape sera<p><center>
  <table border=0 bgcolor=#d0c0d0 width=80%><tr><td align=center>
  !line $step of $good
  </table> </center> <p>
 !endif
 :gnext
 <p>
 !if $step<$stepcnt
  !href cmd=reply&ans=next Passer à l'étape suivante.
 !else
  Cet exercice est terminé. Ta note&nbsp;: $module_score/10.
 !endif
 !exit
!endif

!if bad_step iswordof $error
 !if $badstep=0
  Tu penses que toutes les étapes sont correctes.
 !else
  Tu penses que la première mauvaise étape est le numéro $badstep.
 !endif
 !if $bad_steps=$empty
  Tu as tort&nbsp;: toutes les étapes sont correctes.
  <p>
  !line $badstep of $remarks
 !else
  Non, la <em>première</em> mauvaise étape est le numéro $sss. <p>
  !if $badstep>0
   !if $badstep isitemof $bad_steps
    L'étape $badstep est bien erronée, mais elle n'est pas la première
    mauvaise étape.
   !else
    Par contre, l'étape $badstep est tout à fait juste.
   !endif
  !else
   $bad_reason <p>
   !set rrr=!item 1 of $bad_reasons
   !read reasons/$rrr.det
  !endif
 !endif
 <p>Ta note&nbsp;: $module_score/10.
 !exit
!endif

!if double_reply=$error
 Tu as déjà soumis une réponse à ce problème qui a été analysée et notée.
 Les réponses répétitives sont ignorées. (N'utilise pas le bouton
 `recharger' de ton navigateur pour reposter les réponses!)
 !exit
!endif

