!header1

!if $cmd=help and $special_parm=about
 !read about.phtml
 !goto end
!endif

!if $cmd=help
 !read help.phtml
 !goto end
!endif

<h1 class="wims_title">WIMS @ $httpd_HTTP_HOST
<br>$title</h1>
<p><hr> <p>

!if $sitestart=$empty
$name_warning
<p>
 !goto end
!endif
!if $show=yes and $total_site>0 and $laps>0
 !if $wims_theme_version=
   !href cmd=resume $wims_name_menuback
 !endif
 <p>
 !read answer.phtml
 !set wims_menu_items=!append line back2,1,cmd=resume\
 to $wims_menu_items
 <p>
!else
 !if $usercnt>0
  $name_numberclass
  <p>
 !endif
 !read menu.phtml
!endif
:end
!homeref
!tail

!set stat_module=
