2_shape:
2d_arrays:
3_shape:
abelian_group:
absolute_frequency:
absolute_value:
abstract_algebra:álgebra abstracta
acceleration:
actions:
active_site:
adaptative_immunity:
addition:
affine_function:
affine_geometry:geometría afín
algebra:álgebra
algebra_geometry:
algebraic_fraction:
algebraic_geometry:
algorithmics:
altitude:
american_civilisation:
amino_acid:
analysis:análisis
analytic_geometry:geometría analítica
ancient_greek:
anesthetic_drug:
angle_bisector:
angles:ángulos
animal_cell:
antibody:
antibody_diversity:
antigen:
antiseptic_drug:
area:
arithmetic:aritmética
arithmetic_sequence:
arrays:
arts:
association_rate:
asymptote:
atom:
bacteria:
barycenter:
basis:
basis_change:
between_variance:
bezout_algorithm:relación de Bezout
bilinear_algebra:
binomial:
binomial_distribution:
binomial_test:
biochemistry:
biology:
body_system:
bonds:
botany:
bound:
boxplot:
business_english:
butterfly:
calculation:
calculus:cálculo
calendar:
canonical_form:
capacitor:
catalysis:
cell_biology:
cell_cycle:
cell_death:
cell_differentiation:
cell_division:
cercl_a1:
cercl_a2:
cercl_b1:
cercl_b2:
cercl_c1:
cercl_c2:
characteristic_polynomial:
chemical_equilibrium:
chemical_reaction:
chemical_synthesis:
chemistry:
chisquare_test:
chromosome:
cinematics:
circle:círculos
circle_equation:
circles:círculo
circuit_law:
circulation:
civic_education:
class_i:
class_ii:
classical_antiquity:
clock:
clonal_selection:
clthm:
clustering:
code:teoría de la encriptación
coding:teoría de la encriptación
collections:
color:
combination:combinación
combinatorics:combinatoria
combustion:
common_ancestor:
complement_system:
complementary_subspace:
complex_analysis:
complex_number:números complejos
complex_plane:
complexity:
composite_types:
cond_instruction:
conditional_frequency:
conditional_probability:
cone:
confidence_interval:
congruence:congruencia
conics:cónicas
contingency_table:
continued_fraction:fracción continua
continuity:continuidad
continuous_probability_distribution:
contraposition:
contrast_agent:
contribution_variance:
convergence:
conversion:
cooperativity:
coordinates:coordenada
corporate_finance:
correlation:
covariance:
cram:
critical_point:
cross_product:
cryptology:criptología
crystallography:
cube:
cubic_crystal_system:
cumulative_distribution:
cumulative_frequency:
curl:
curve_fitting:
curves:curvas
cyclic_code:
cyclic_group:
cylinder:
cytokine:
data_analysis:datos estadísticos
data_gestion:
data_structures:
decile:
decimals:decimales
definite_integral:integrales definidas
dendritic_cell:
density:
derivative:derivadas
descriptive_statistics:
determinant:determinante
development_of_lymphocytes:
diabete_drug:
diacritical_mark:
diagonalization:
differentiability:derivabilidad
differential_equation:
differential_equations:ecuaciones diferenciales
differential_geometry:
differential_system:
dimension:
dimensional_analysis:
diophantine_equations:ecuaciones diofantinas
dirac_delta_function:
direction:
discrete_logarithm:
discrete_mathematics:
discrete_probability_distribution:
distance:
distance_method:
divergence:
diversity:
divisibility:
division:división
domain:
dynamic_system:
dynamics:
earth_sciences:Sciences de la terre
ecology:Ecologie
economics:
electrical_engineering:
electricity:Electricité
electronics:Electronique
electrostatics:Electrostatique
elementary_algebra:álgebra elemental
elementary_calculus:
elementary_geometry:
elementary_mathematics:
ellipse:elipse
emphasis:
encryption:
endomorphism_reduction:
energy:
english:
english_vocabulary:
enthalpy:
entropy:entropía
enzyme:
equation_systems:
equations:ecuaciones
error_correcting_codes:código corrector de errores
error_detection:detección de errores
estimation:
etymology:
eucaryote:
euclidean_algorithm:división euclidea
euclidean_cloud:
euclidean_geometry:geometría euclídea
eulerian_graph:
events:
evolution:
expectation:
exponent:
exponential:
extremum:
factorial:factorial
factorization:factorización
fc_receptor:
field:cuerpos
financial_analysis:
financial_market:
financial_mathematics:
finite_field:
finite_group:
finnish:
flow_cytometry:
fluid_mechanics:
fourier_series:series de Fourier
fourier_transform:transformaciones de Fourier
fraction:fracciones
french:
french_conjugation:
french_grammar:
french_reading:
french_spelling:
french_vocabulary:
frieze:
function_variation:
functional_group:
functions:funciones
gas_mechanics:
gauss_algorithm:
gaz_mechanics:
gcd_lcm:pgcd ppcm
gene_rearrangement:
genetics:
geography:
geometric_sequence:
geometry:geometría
german:
goldbach:Goldbach
gradient:
grammar:
graph:
graph_coloring:
graphing:grafo
greek:
group:grupos
group_action:
group_theory:
hamming:distancia de Hamming
hematopoiesis:
hierarchical_cluster_analysis:
histocompatibility:
histogram:
histology:
history:
homography:
homonymy:
homothety:
hyperbola:hipérbole
hyperplane:hiperplanos
ideal_gas:
image:
immunoglobulines:
immunology:
imperative_programming:
implication:
independent_events:
independent_random_variables:
inductance:
inequalities:desigualdades
inequations:
infection:
inferential_statistics:
infonet:
informatics:
information_theory:
inhibitor:
injectivity:
innate_immunity:
inorganic_chemistry:
integers:enteros
integral:integrales
interferon:
intervals:intervalos
inverse_function:
ionisation:
ioput:
irreducible_fraction:
isometries:
kinetics:
language:
laplace_transforms:transformaciones de Laplace
latin:
length:
leucocyte:
level_set:
lewis:
lexical_field:
limit:límites
line:líneas
line_equation:
line_integral:
linear_algebra:álgebra lineal
linear_differential_equation:
linear_function:
linear_maps:alicaciones lineales
linear_optimisation:
linear_system:
linear_systems:sistemas lineales
lines:líneas
linguistics:
lissajous:Lissajous
listening:
literal_calculation:
literature:
logarithm:
logic:lógica
logic_recreation:
loops:
lymphocyte:
lymphoid_organ:
macrophage:
magnetism:
management:
maps:aplicaciones
markov:
markov_chains:
masse:
math_symbols:
mathematics:
matrix:matrices
maximum_flow:
maximum_parsimony:
mean:medias
measurement:
mechanics:
medecine:
median:
median_line:
medicinal_chemistry:
mental_calculation:
methodical_calculation:
methodology:
mhc:
microbe:
midpoint:
misc:miscelánea
mitosis:
modelling:
modular_arithmetic:aritmética modular
module:
molecular_biology:
molecule:
monophyletic_group:
month_week:
multiplication:multiplicación
multivariable_function:
music:
mycology:
negation:
neutrophil:
nk_cell:
normal_distribution:
normal_vector:
nsaids:
number:números
number_line:
number_theory:
number_writing:
numbering_system:sistemas de numeración
numeration:
numerical_analysis:
numerical_integration:
numerical_method:
ode:ODE
ohm_law:
oper_prec:
operation:
operational_research:
optics:
order:
organelle:
organic_chemistry:
oscillators:
pain_drug:
parabola:parábola
parallel:
parallelogram:
parametric_curves:curvas paramétricas
parametric_surfaces:
partial_derivative:
past_tenses:
pbsolving:
peptide:
percentage:porcentajes
percents:
perimeter:
periodic_table:
permutation:permutación
perpendicular_bisector:
pert:
phagocytosis:
pharmocophore:
phase_changes:
phi2:
phonetics:
phylo_homology:
phylogenetic_tree:
phylogenetics:
physical_education:
physics:
plane:planos
plane_equation:
plane_section:
plant:
plant_cell:
poisson_distribution:
polar_curves:curvas polares
polygons:polígonos
polyhedron:
polynomials:polinomios
potential:
power:
power_series:
prealg:pre-álgebra
precalc:pre-cálculo
prediction_interval:
preimage:
pression:
primes:números primos
primitive:primitivas
priority_rule:
prism:
prob_graph:
probability:probabilidad
probability_distribution:distribuciones
probability_generating_function:
probability_space:
probability_statistics:probabilidad-estadística
procedures:
process_engineering:
prog_functions:
programming:
pronunciation:
proportionality:proporcionalidad
protein:
protractor:
pyramid:
quadratic_form:
quadrilateral:
quantifier:
quantile:
quartile:
quotient_group:
random:
random_variable:
random_vector:
range_kernel:
rank:
rational_number:
ray_optics:
reading:
real_function:
real_number:números reales
reasoning:
receptor:
rectangles:rectángulos
recurrence_relation:
recursive_functions:
reference_function:
regression:
relative_number:
resistance:
ring:anillos
riskreturn:
road_traffic_safety:
root_tree:
roots:raíces
rotation:
ruler_and_compass:regla y compás
rv_convergence:
sampling:
sampling_distribution:
scalar_product:
scheduling:
sciences:
scientific_notation:
selection_of_lymphocytes:
sense:
sentence_stress:
sequence:secuencias
series:series
set_theory:
sets:conjuntos
signal_processing:
signaling_pathway:
signdigits:
similarities:
simplex_method:
simulation:
spatial_skill:
speaking:
specificity:
spelling:
sphere:
sports:
spreadsheet:
squareroot:
standard_deviation:
static_register:
statistical_test:
statistics:estadística
steroid:
stokes_thm:
struct:
student_test:
subst_integral:
subtraction:
surfaces:superficies
surjectivity:
sustainable_dev:
symmetric_group:
symmetry:
t_cell_receptor:
tangent:
tangent_plane:
taylor_expansion:expansión de Taylor
taylor_series:series de Taylor
technical_language:
thales:
thermochemistry:
thermodynamics:
tiling:
time:
timeline:
titration:
topology:
toxin:
trajectory:
transformation_group:
transition_matrix:
translation:
tree_topology:
triangles:triángulos
trigonometric_circle:
trigonometric_functions:
trigonometry:trigonometría
trinomial:
truth_table:
uniform_distribution:
units_tests:
unroot_tree:
upper_bound:
vaccine:
variables:
variance:
variation_coefficient:
vector_space:espacios vectoriales
vectorial_analysis:
vectorial_field:
vectorial_geometry:
vectors:vectores
velocity:
vibration:
virus:
vocabulary:
voltage:
volume:
ward_method:
weaver:
within_variance:
written_english:
zdomain: Other domains
zoology:
