2_shape:2D
3_shape:3D
abelian_group:Abelse groep
absolute_frequency:absolute frequentie
absolute_value:absolute waarde
abstract_algebra:Abstracte algebra
actions:akties
adaptative_immunity:adaptief imuunsysteem
addition:optellen
affine_function:lineaire vergelijking
affine_geometry:lineaire geometrie
algebra:Algebra
algebra_geometry:Algebra geometrie
algebraic_geometry:Algebraische geometrie
algorithmics:Algoritme
altitude:hoogte
american_civilisation:Amerikaanse cultuur
amino_acid:aminozuur
analysis:Analyse
analytic_geometry:Analytische geometrie
anesthetic_drug:verdovingsmiddel
angle_bisector:bisectrice
angles:Hoeken
animal_cell:dierlijke cel
antibody:antilichaam
antibody_diversity:
antigen:antigeen
antiseptic_drug:antisceptisch middel
area:Oppervlak
arithmetic:Rekenkunde
arithmetic_sequence:rekenkundige rij
arts:Kunst
asymptote:asymptoot
bacteria:bacterien
barycenter:baycentrum
basis:basis
basis_change:basis verandering
bezout_algorithm:Bezout algoritme
bilinear_algebra:bilineaire algebra
binomial_distribution:binomiale verdeling
biochemistry:Biochemie
biology:Biologie
body_system:Lichaam
bonds:bindingen
botanics:Plantkunde
botany:plantenkunde
business_english:Technisch engels
calc:Rekenen
calculation:berekening
calculus:Rekenkunde
cell_biology:Celbiologie
cell_cycle:cel cyclus
cell_death:cel dood
cell_differentiation:cel differentiatie
cell_division:celdeling
characteristic_polynomial:veelterm karakteristiek
chemical_synthesis:chemische synthese
chemistry:Chemie
chromosome:chromosoom
cinematics:Bewegingsleer
circle:Cirkel
circle_equation:cirkel vergelijking
circles:Cirkels
civic_education:algemene ontwikkeling
class_i:
class_ii:
classical_antiquity:Klasieke oudheid
clonal_selection:
clthm:
code:Code
coding:Programmeren
combi:Combi
combination:Combinaties
combinatorics:Combinatioriek
common_ancestor:gemeenschappelijke voorouder
complement_system:
complementary_subspace:
complex_analysis:Complexe analyse
complex_number:Complexe getallen
complex_plane:Complexe vlak
complexity:complexiteit
conditional_probability:Conditionel kansrekening
cone:conus
confidence_interval:Betrouwbaarheids interval
congruence:Congruentie
conics:Kegelsneden
continued_fraction:Rationale getallen
continuity:Continuiteit
continuous_probability_distribution:
contrast_agent:contrast vloeistof
convergence:convergentie
coordinates:coordinaten
corporate_finance:bedrijfseconomie
covariance:covariantie
critical_point:kritieke punt
cryptology:Cryptologie
crystallography:Kristallografie
cubic_crystal_system:
cumulative_distribution:cumulatieve distributie
cumulative_frequency:cimulatieve frequentie
curve_fitting:curve fitting
curves:curves
cyclic_code:cyclische code
cyclic_group:Cyclische groep
cytokine:cytokinase
data_analysis:Data analyse
data_gestion:Gegevensbeheer
decimals:Decimalen
definite_integral:Eindige integralen
dendritic_cell:dendritische cel
density:dichtheid
derivative:Afgeleide
descriptive_statistics:Beschrijvende statistiek
determinant:Determinant
development_of_lymphocytes:
diabete_drug:diabetes medicijn
diacritical_mark:
diagonalization:
differentiability:Differentieerbaarheid
differential_equation:Differentiaal vergelijkingen
differential_geometry:Differentiaal meetkunde
differential_system:Differentiaal systeem
dimension:dimensie
dimensional_analysis:dimensie analyse
diophantine_equations:Diophantische vergelijkingen
dirac_delta_function:dirac delta functie
direction:richting
discrete_mathematics:Discrete wiskunde
discrete_probability_distribution:discrete waarschijnlijkheidsverdeling
distance:afstand
distance_method:
diversity:diversiteit
division:deling
domain:Domein
dynamic_system:dynamisch systeem
dynamics:Dynamica
earth_sciences:Geografie
ecology:Ecologie
economics:economie
electrical_engineering:
electricity:Electriciteit
electronics:Electronica
electrostatics:Electrostatica
elementary_algebra:Elementaire algebra
elementary_calculus:Elementaire calculus
elementary_geometry:Elementaire geometrie
elementary_mathematics:Elementaire wiskunde
ellipse:Ellips
encryption:encryptie
endomorphism_reduction:
energy:energie
english:Engels
english_vocabulary:Engelse uitspraak
entropy:Entropie
equation_systems:vergelijkings systeem
equations:Vergelijkingen
error_correcting_codes:Fout correctie codes
error_detection:Fouten signalering
estimation:Schatten
etymology:Etymologie
eucaryote:
euclidean_algorithm:Euclidisch algoritme
euclidean_geometry:Euclidische geometrie
events:Event
evolution:evolutie
expectation:verwachting
exponent:Exponent
exponential:Exponentieel
extremum:extreme waarde
factorial:faculteit
factorization:Ontleden
fc_receptor:
field:Velden
financial_analysis:financiele analyse
financial_market:financiele markt
financial_mathematics:Financiele wiskunde
finite_field:eindige velden
finite_group:Eindige groepen
finnish:fins
flow_cytometry:
fluid_mechanics:Stromingsleer
fourier_series:Fourier series
fourier_transform:Fourier transformatie
fourier_transforms:Fourier transformaties
fraction:Breuk
french:Frans
french_conjugation:franse vervoegingen
french_grammar:Franse grammatica
french_reading:Frans lezen
french_spelling:Franse spelling
french_vocabulary:Franse uitspraak
function_variation:functie variatie
functions:Functies
gas_mechanics:Gas mechanica
gauss_algorithm:algorithme van Gauss
gaz_mechanics:gas mechanica
gcd_lcm:Gcd
gene_rearrangement:
genetics:Genetica
geography:Geografie
geology:Geologie
geom:Geometrie
geometric_sequence:geometrisch rij
geometry:Geometrie
german:Duits
goldbach:Goldbach
grammar:Grammatica
graph:Grafiek
graphing:Grafieken
group:Groepen
group_action:Groep aktie
group_theory:Groep theorie
hamming:Hamming afstand
hematopoiesis:
histocompatibility:
histogram:Histogram
histology:Histologie
history:Geschiedenis
homography:homografie
homology:homologie
hyperbola:Hyperbolen
hyperplane:Hypervlakken
immunoglobulines:
immunology:Immunologie
independent_events:onafhankelijke gebeurtenissen
independent_random_variables:onafhankelijke random variabelen
inequalities:Ongelijkheden
inequations:ongelijkheden
infection:infectie
inferential_statistics:
infonet:infonet
informatics:Informatica
information_theory:Informatie theorie
innate_immunity:
inorganic_chemistry:anorganische chemie
inorganics_chemistry:Anorganische chemie
integers:Integers
integral:Integraal
interferon:interferon
intervals:Intervallen
ionisation:ionisatie
isometries:Isometrie
language:Taal
laplace_transforms:Laplace transformaties
leucocyte:
limit:Limiet
line:Lijn
line_equation:lijn vergelijking
line_integral:lijn integraal
linear_algebra:Lineaire algebra
linear_differential_equation:
linear_function:lineaire functie
linear_maps:Lineaire velden
linear_optimisation:Lineaire optimalisatie
linear_system:Lineaire systemen
lines:Lijnen
linguistics:Taalwetenschap
lissajous:Lissajous
listening:Luisteren
literal_calculation:literaal
literature:literatuur
logarithm:Logaritme
logic:Logica
lymphocyte:
lymphoid_organ:
macrophage:macrofaag
magnetism:Magnetisme
management:management
maps:Mappen
markov_chains:Markov chains
math_symbols:wiskundige symbolen
mathematics:Wiskunde
matrix:Matrix
maximum_parsimony:
mean:Gemiddelde
measurement:Meting
mechanics:Mechanica
medecine:Medicijn
median:mediaan
median_line:mediaan lijn
medicinal_chemistry:pharmacologie
methodical_calculation:Hoofdrekenen
methodology:methodologie
mhc:
microbe:
misc:Diversen
mitosis:
modelling:modellering
modular_arithmetic:Modulaire rekenkunde
molecular_biology:moleculaire biologie
monophyletic_group:
multiplication:vermenigvuldigen
multivariable_function:multivariabele functie
music:Muziek
mycology:Mycologie
neutrophil:
nk_cell:
normal_distribution:normale verdeling
normal_vector:normaal vector
nsaids:
number:Getal
number_theory:Getal theory
numbering_system:Getallen stelsel
numeration:talstelsel
numerical_analysis:numerieke analyse
numerical_method:numerieke methode
ode:Ode
operation:Operatie
operational_research:Operatie onderzoek
optics:Optica
order:voglorde
organelle:
organic_chemistry:organische chemie
organics_chemistry:Organische chemie
oscillators:oscillatoren
pain_drug:pijnstiller
parabola:Parabolen
parallelogram:parallelogram
parametric_curves:Parametrische curves
parametric_surfaces:parametrische oppervlakken
pbsolving:
peptide:
percentage:Percentages
percents:Procent
perimeter:omtrek
permutation:Permutaties
perpendicular_bisector:middelloodlijn
pert:
phagocytosis:
pharmocophore:
phonetics:Fonetisch
phylogenetic_tree:
phylogenetics:Plantengenetica
physical_education:natuurkunde onderwijs
physics:Natuurkunde
plane:Vlak
plane_equation:vlakvergelijking
plant_cell:planten cel
poisson_distribution:poisson verdeling
polar_curves:Polaire kurves
polygons:Polygonen
polynomials:Polynomen
prealg:Pre-algebra
precalc:Pre-calculus
prediction_interval:voorspellings interval
pression:
primes:Priemgetallen
primitive:Primitieve
priority_rule:voorrangsregel
prob_graph:
proba:Kansrekening
probability:Waarschijnlijkheid
probability_distribution:Kansverdelingen
probability_generating_function:
probability_space:Kansdichtheid
probability_statistics:Waarschijlijkheids rekening
process_engineering:procestechnologie
programming:Programmeren
pronunciation:Uitspraak
proportionality:Proportionaliteit
pyramid:pyramide
quadratic_form:kwadratische vorm
quantile:kwantiel
quartile:kwartiel
quotient_group:quotient groep
random:Willekeurig
random_variable:Willekeurige variabele
random_vector:willekeurige vector
range_kernel:
rank:plaats
rational_number:Rationeel getal
reading:Lezen
real_function:Reeele functie
real_number:Reeele getallen
reasoning:redenering
receptor:ontvanger
rectangles:Vierkanten
recurrence_relation:
regression:regressie
relative_number:Relatief getal
ring:Ringen
riskreturn:
root_tree:
roots:Wortels
rotation:rotatie
ruler_and_compass:Passer en lineaal
rv_convergence:
sampling:monstername
scalar_product:inwendig product
scheduling:roosteren
sciences:Wetenschappen
scientific_notation:Wetenschappelijke notatie
selection_of_lymphocytes:
sequence:Rijen
series:Reeksen
set_theory:Verzamelingenleer
signal_processing:signaalverwerking
signaling_pathway:
signdigits:
similarities:Overeenkomsten
simplex_method:simplex methode
simulation:Simulatie
spatial_skill:
speaking:Praten
spelling:Spelling
sports:sport
spreadsheet:spreadsheet
standard_deviation:standaard deviatie
statistical_test:Statistische test
statistics:Statistiek
steroid:steroide
stokes_thm:
subst_integral:
subtraction:aftrekken
surfaces:Oppervlakken
symmetric_group:Symmetrie groep
symmetry:symmetrie
t_cell_receptor:
tangent:Tangent
tangent_plane:
taylor_expansion:Taylor expansie
taylor_series:Taylor reeks
technical_language:Technische taal
thermodynamics:Thermodynamica
time:Tijd
titration:titratie
topology:topologie
toxin:gifstof
transformation_group:Transformatie groep
transition_matrix:transitie matrix
translation:translatie
triangles:Driehoeken
trigonometric_circle:trigonometrische cirkel
trigonometric_functions:trigonometrische functies
trigonometry:Trigoniometrie
truth_table:waarheidstabel
uniform_distribution:uniforme distributie
unroot_tree:
vaccine:
variance:variantie
vector_space:Vector ruimte
vectorial_analysis:Vector analyse
vectorial_geometry:vector geometrie
vectors:Vectoren
vibration:Vibratie
virus:virus
vocabulary:Vocabulaire
volume:Volume
weaver:Weven
written_english:Geschreven engels
zdomain: Other domains
