2_shape:2D
3_shape:3D
Bezout_algorithm:Bezout algoritme
Fourier_series:Fourier reeksen
Fourier_transforms:Fourier transformaties
Goldbach:Goldbach
abelian_group:Abelse groep
abstract_algebra:Abstracte algebra
affine_geometry:Affiene geometrie
algebra:Algebra
algebra_geometry:Algebra geometrie
algebraic_geometry:Algebraische geometrie
algorithmics:Algoritmeleer
american_civilisation:Amerikaanse civilisatie
analysis:Analyse
analytic_geometry:Analytische geometrie
angles:Hoeken
area:Oppervlak
arithmetic:Rekenkunde
arts:Kunst
bilinear_algebra:
biochemistry:Biochemie
biology:Biologie
body_system:Lichaam
botanics:Plantkunde
business_english:Technisch engels
calc:Rekenen
calculus:Rekenkunde
cell_biology:Celbiologie
chemistry:Chemie
cinematics:Bewegingsleer
circle:Cirkel
circles:Cirkel
civic_education:
classical_antiquity:Klasieke oudheid
code:Code
coding:Programmeren
combi:Combi
combination:Combinaties
combinatorics:Combinatioriek
complex_analysis:Complexe analyse
complex_number:Complexe getallen
complex_plane:Complexe vlak
conditional_probability:Conditionel kansrekening
confidence_interval:Betrouwbaarheids interval
congruence:Congruentie
conics:Kegelsneden
continued_fraction:Rationale getallen
continuity:Continuiteit
cristallography:Kristallografie
cryptology:Cryptologie
curves:Kurves
cyclic_group:Cyclische groep
data_analysis:Data analyse
data_gestion:Gegevensbeheer
decimals:Decimalen
definite_integral:Eindige integralen
derivative:Afgeleide
descriptive_statistics:Beschrijvende statistiek
determinant:Determinant
differentiability:Differentieerbaarheid
differential_equation:Differentiaal vergelijkingen
differential_geometry:Differentiaal meetkunde
differential_system:Differentiaal systeem
diophantine_equations:Diophantische vergelijkingen
discrete_mathematics:Discrete wiskunde
domain:Domein
dynamics:Dynamica
earth_sciences:Geografie
ecology:Ecologie
electricity:Electriciteit
electronics:Electronica
electrostatics:Electrostatica
elementary_algebra:Elementaire algebra
elementary_calculus:Elementaire calculus
elementary_geometry:Elementaire geometrie
elementary_mathematics:Elementaire wiskunde
ellipse:Ellips
endomorphism_reduction:
english:Engels
english_vocabulary:Engelse uitspraak
entropy:Entropie
equations:Vergelijkingen
error_correcting_codes:Fout correctie codes
error_detection:Fouten signalering
estimation:Schatten
etymology:Etymologie
euclidean_algorithm:Euclidisch algoritme
euclidean_geometry:Euclidische geometrie
events:Event
exponent:Exponent
exponential:Exponentieel
factorial:Factorisaties
factorization:Ontleden
field:Velden
financial_mathematics:Financiele wiskunde
finite_group:Eindige groepen
fluid_mechanics:Stromingsleer
fourier_series:Fourier series
fourier_transform:Fourier transformatie
fraction:Breuk
french:Frans
french_conjugation:
french_grammar:Franse grammatica
french_reading:Frans lezen
french_spelling:Franse spelling
french_vocabulary:Franse uitspraak
functions:Functies
gas_mechanics:Gas mechanica
gcd_lcm:Gcd
genetics:Genetica
geography:Geografie
geology:Geologie
geom:Geometrie
geometry:Geometrie
german:Duits
goldbach:Goldbach
grammar:Grammatica
graph:Grafiek
graphing:Grafieken
group:Groepen
group_action:Groep aktie
group_theory:Groep theorie
hamming:Hamming afstand
histogram:Histogram
histology:Histologie
history:Geschiedenis
homography:
hyperbola:Hyperbolen
hyperplane:Hypervlakken
immunology:Immunologie
inequalities:Ongelijkheden
informatics:Informatica
information_theory:Informatie theorie
inorganics_chemistry:Anorganische chemie
integers:Integers
integral:Integraal
intervals:Intervallen
isometries:Isometrie
language:Taal
laplace_transforms:Laplace transformaties
limit:Limiet
line:Lijn
linear_algebra:Lineaire algebra
linear_maps:Lineaire velden
linear_optimisation:Lineaire optimalisatie
linear_systems:Lineaire systemen
lines:Lijnen
linguistics:Taalwetenschap
lissajous:Lissajous
listening:Luisteren
logarithm:Logaritme
logic:Logica
magnetism:Magnetisme
maps:Mappen
markov_chains:Markov chains
mathematics:Wiskunde
matrix:Matrix
mean:Gemiddelde
measurement:Meting
mechanics:Mechanica
medecine:Medicijn
methodical_calculation:Hoofdrekenen
misc:Diversen
modular_arithmetic:Modulaire rekenkunde
music:Muziek
mycology:Mycologie
number:Getal
number_theory:Getal theory
numbering_system:Getallen stelsel
ode:Ode
operation:Operatie
operational_research:Operatie onderzoek
optics:Optica
organics_chemistry:Organische chemie
parabola:Parabolen
parametric_curves:Parametrische kurves
pbsolving:
percentage:Percentages
percents:Procent
permutation:Permutaties
phonetics:Fonetisch
phylogenetics:Plantengenetica
physics:Natuurkunde
plane:Vlak
polar_curves:Polaire kurves
polygons:Polygonen
polynomials:Polynomen
prealg:Pre-algebra
precalc:Pre-calculus
primes:Priemgetallen
primitive:Primitieve
proba:Kansrekening
probability:Waarschijnlijkheid
probability_distribution:Kansverdelingen
probability_space:Kansdichtheid
probability_statistics:Waarschijlijkheids rekening
programming:Programmeren
pronunciation:Uitspraak
proportionality:Proportionaliteit
quotient_group:quotient groep
random:Willekeurig
random_variable:Willekeurige variabele
rational_number:Rationeel getal
reading:Lezen
real_function:Reeele functie
real_number:Reeele getallen
rectangles:Vierkanten
relative_number:Relatief getal
ring:Ringen
roots:Wortels
ruler_and_compass:Passer en lineaal
sciences:Wetenschappen
scientific_notation:Wetenschappelijke notatie
sequence:Rijen
series:Reeksen
set_theory:Verzamelingenleer
similarities:Overeenkomsten
simulation:Simulatie
speaking:Praten
spelling:Spelling
statistical_test:Statistische test
statistics:Statistiek
surfaces:Oppervlakken
symmetric_group:Symmetrie groep
symmetry::Symmetrie
tangent:Tangent
taylor_expansion:Taylor expansie
taylor_series:Taylor reeks
technical_language:Technische taal
thermodynamics:Thermodynamica
time:Tijd
transformation_group:Transformatie groep
triangles:Driehoeken
trigonometry:Trigoniometrie
vector_space:Vector ruimte
vectorial_analysis:Vector analyse
vectors:Vectoren
vibration:Vibratie
vocabulary:Vocabulaire
volume:Volume
weaver:Weven
written_english:Geschreven engels
