一般说来, 把许多访问者带到我们这里的网页也是我们的其它访问者感兴趣的.
因此当你搜寻与此服务器有关的网络资源时, 这样的网页表正是你需要的.
<p>
另一方面, 如果你是包含有到我们这里的链接的网页作者,
这样的表也能衡量你的链接的有效性. 这也是感谢你的链接的一种方式.
<p>
我们的反向链接表是动态生成的, 根据下列菜单选择参数.

!form reply
 !set s_day=天
 !set s_week=周
 !set s_month=月
 !set s_year=年
 !set s_beginning=起始 $start_month-$start_day-$start_year
列举周期: 从
 <select name=cnt>
 !for i=1 to 15
  <option value=$i
  !if $i=$cnt
   selected
  !endif
  >$i
 !next i
 </select><select name=style>
 !for i in day,week,month,year,beginning
  <option value=$i
  !if $i=$style or ($i=month and $style=$empty)
   selected
  !endif
  >$(s_$i)
 !next i
 </select>. <p>
链接可根据网页的 
 !set i_site=网站名,
 !set i_stem=基础目录, 或 
 !set i_uniq=完整地址
 !for i in site,stem,uniq
  <input type=radio name=type value=$i
  !if $type=$i
   checked
  !endif
  > $(i_$i)
 !next i
列举, 表格限于前 <select name=reflim>
 !for i in 10,20,30,50,70,100,150,200
  <option value=$i
  !if $i=$reflim
   selected
  !endif
  >$i
 !next i
 </select> 个地址. 搜索引擎的地址可被
 <input type=radio name=search value=yes
 !if $search=yes
  checked
 !endif
 > 包含在内或 <input type=radio name=search value=no
 !if $search=no
  checked
 !endif
 >排除在外.
 <p>作为选项, 你可以把表格限于包含以下关键词的网站/网页:
 <input size=15 name=key value="$key">
 <p><center><input type=submit value="显示表格"></center>
</form>

!set key=

