
Wanneer U een Docent bent en u wilt WIMS regelmatig gaan gebruiken in Uw lessen,
is het verstandig om een lokale installatie te overwegen.
Dit heeft het voordeel van de hoger intranet snelheden, gecombineerd met een
hogere betrouwbaarheid en onderhoudsgemak.
<p>
WIMS is software onder GNU licensie. 
Het mag gratis worden
<a href="http://wims.unice.fr/download/wims/">gedownload</a>,
en kan worden geinstalleerd op o.a. het Linux besturingssyteem.
Raadpleeg de 
<a href="http://wims.unice.fr/download/wims/README">README</a>
file in de download directory voor meer
details over de installatie van WIMS.
<p>
U kunt ook 
!mailurl xiao@unice.fr de maker van WIMS
 emailen over het opzetten van  mirror websites
 <br>
!href module=adm/light&phtml=mirror.phtml.$lang Klik hier
 voor de lijst van WIMS-servers open voor  publiek.
<p>
Het heeft geen zin deze pagina's op te halen met een "robot".
