!! WIMS main entrance page theme.
!nocache
!if $module!=home
 !exit
!endif

!set home_theme=yes
!set table_colors=$wims_ref_bgcolor,$wims_ref_bgcolor

<table border=0 width="100%" cellpadding=0 cellspacing=0>
<tr><td width="12%" bgcolor="$wims_ref_bgcolor" align=center valign=top>
<div class=wimsmenu>
<small>
!href module=home&special_parm=logo <IMG SRC=gifs/logo.gif border=0 width=60 alt="WIMS logo">
<p>
!href module=adm/new $N_new
<br>
!href module=adm/forum/forum $N_forum
<br>
!href module=adm/light&phtml=mirror.phtml.$lang $N_mirror
<br>
!href module=adm/light&phtml=useropts.phtml.$lang $N_pref
<br>
!href module=help/main $N_help
<p><hr><p>
$V_cls
<br>
!href module=adm/class/classes&type=participant $V_stu
<br>
!href module=adm/class/classes&type=supervisor $V_sup
<br>
!href module=adm/class/classes&type=example $V_ex
<br>
!href module=help/main&chapter=3 $N_help
<p><hr><p>
$CR_1
<br>
!href module=adm/createxo $CR_OEF
<br>$N_or<br>
!href module=adm/modtool $CR_mod
<p>
!href module=help/wimsdoc.en $E_doc
<br>
<a href="http://wims.unice.fr/download/wims/">$E_src</a>
<br>
!href module=adm/stat/referer $E_ref
<br>
!href module=adm/stat/stat $E_stat

</small></div></td><td valign=top>
<div class=wimsbody>
<table border=0 cellspacing=0 cellpadding=0 width="100%">
<tr>
<td align=center valign=bottom nowrap>
  <h1>$V_title<br><font size="+0">
  <br><font size="-1">(WIMS) $N_at <a href="/">$httpd_HTTP_HOST</a></font></h1>
!set wims_headmenu_colcnt=5
!for i=1 to $wims_language_cnt
 !set l=!word $i of $wims_site_languages
 !if $l!=$lang
  !if $wims_language_cnt>2 and $wims_language_cnt<6
   !set l_=<small>$(lang_name_$l)</small>
  !else
   !if $wims_language_cnt<6
    !set l_=$(lang_name_$l)
   !else
    !reset l_
   !endif
  !endif
  !href lang=$l&session=$wims_session.1&module=$module <img src=gifs/$l.gif alt="$(Lang_name_$l)" height=16 border=0>$l_
   <!-- don't remove this empty line or leading whitespace. Flag spacing depends on it. -->
 !endif
!next i
</td></tr></table>

<p>

!if $wims_ismanager!=0
<center>
 !href module=adm/manage $N_manage
</center> <p>
!endif

!read ./form.phtml
!read ./result.phtml
</div>
</td></tr></table>

<div class=wimstail><center>

<small>
WIMS-$wims_version $E_comp $wims_version_date.
$E_manager
!mailurl $wims_site_manager\
WIMS: $httpd_HTTP_HOST
.
</small>
!robottrap
</div></BODY></HTML>

