
!read adm/title.phtml 1\
\
Format pour tableur

csv (comma-separated values) et tsv (tab-separated values) sont des formats
textes pour des données de tableurs. La majorité des tableurs
reconnaissent les deux.
!! <p>
!! ods est le format de tableur défini par le standard ISO OpenDocument. Il est supporté par LibreOffice et OpenOffice, et il devrait l'être par tout programme de tableur loyal.
!! </p>
