
!if $job2!=first
 !changeto arch/$job2.phtml
!endif

You can download a backup copy of your class, in the following format
!href cmd=reply&job=arch&job2=download&selection=all&format=zip zip
,
!href cmd=reply&job=arch&job2=download&selection=all&format=tgz tgz
 $wims_name_or
!href cmd=reply&job=arch&job2=download&selection=all&format=tar.gz tar.gz
.
<small>[
!href cmd=help&special_parm=download $wims_name_help
 ]</small>
<p><hr> <p>

!set wims_form_method=file
!form reply
<input type=hidden name=job value=arch>
<input type=hidden name=job2 value=upload>
To <input type=submit value=upload>
backup archives into your class, please give the backup file name:
<p>
<input type=file name=wims_deposit size=40>
<small>
!href cmd=help&special_parm=upload $wims_name_help
</small>
<p>
(You will be prompted for the selection of resources to restore to your
class.)
</form> <p>

