!if $supertype=4 and $classdepth<=3
<p><center>
 !href module=adm/class/gateway Urejanje strukture
</center>
!endif

!form reply
<input type=hidden name=up_job value=list>
$table_header
$table_tr<td align=right>Ime ustanove
<td colspan=3>
!if $supertype notin 24 or $classdepth=1
 <input size=50 name=up_institution value="$class_institution">
!else
 $class_institution
!endif
$table_tr<td align=right>Ime uèilnice
<td colspan=3>
<input size=50 name=up_description value="$class_description">
$table_tr<td align=right>Varne povezave
<small>
!href cmd=help&special_parm=config&special_parm2=secure $wims_name_help
 </small>
<td colspan=3>
<input size=50 name=up_secure value="$class_secure">
$table_tr<td align=right>Ime skrbnika
<small>
!href cmd=help&special_parm=config&special_parm2=supervisor $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_supervisor value="$class_supervisor">
$table_tr<td align=right>E-naslov skrbnika
<small>
!href cmd=help&special_parm=config&special_parm2=email $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_email value="$class_email">
$table_tr<td align=right>Option words
<small>
!href cmd=help&special_parm=config&special_parm2=option $wims_name_help
 </small>
<td colspan=3>
<input size=40 name=up_option value="$class_option">
</td></tr>
!if $wims_supertype!=4 or $class_typename!=class
$table_tr<td align=right>
 Modtool Account
<small>
!href cmd=help&special_parm=config&special_parm2=modtoolchg $wims_name_help
</small>
</td><td colspan=3>
!set modtoolchg=1
!formcheckbox modtoolchg list 0 prompt Change
</td></tr>
!endif
$table_tr<td align=right colspan=2>Stopnja zaklepa povezave
<small>
!href cmd=help&special_parm=config&special_parm2=lock $wims_name_help
</small>
</td><td>
!set up_lock=$class_lock
!default up_lock=0
!formselect up_lock list 0,2,3,4,5,6,7
</td>
<td align=right>Number of the best scores
<small>
!href cmd=help&special_parm=config&special_parm2=topscores $wims_name_help
 </small>
!default class_topscores=0
<td><input size=3 name=up_topscores value="$class_topscores">
</td></tr>
$table_tr<td align=right>Jezik uèilnice
<small>
!href cmd=help&special_parm=config&special_parm2=lang $wims_name_help
 </small>
<td>
!set up_lang=$class_lang
!set langs=!words2items $wims_site_languages
!formselect up_lang list $langs
</td>
<td align=right>
Akademska stopnja
<small>
!href cmd=help&special_parm=config&special_parm2=level $wims_name_help
 </small>
<td>
!set up_level=$class_level
!formselect up_level list $levellist
$table_tr<td align=right>Maks. ¹tevilo uporabnikov
<small>
!href cmd=help&special_parm=config&special_parm2=limit $wims_name_help
 </small>
<td><input size=5 name=up_limit value="$class_limit">
<td align=right>Datum zakljuèka
<small><b>llllmmdd</b></small>
<small>
!href cmd=help&special_parm=config&special_parm2=expiration $wims_name_help
 </small>
<td>
!if $class_type notin 13
 <input size=8 maxlength=8 name=up_expiration value="$class_expiration">
!else
 <tt>$class_expiration</tt>
!endif
$table_tr<td align=right>Registracija vaj
<small>
!href cmd=help&special_parm=config&special_parm2=exolog $wims_name_help
 </small>
!default class_exolog=0
<td><input size=3 name=up_exolog value="$class_exolog">
<td align=right>Registracija izpitov
<small>
!href cmd=help&special_parm=config&special_parm2=examlog $wims_name_help
 </small>
!default class_examlog=$wims_examlog_limit
<input size=3 name=up_examlog value="$class_examlog">
<td>visible by students
<small>
!href cmd=help&special_parm=config&special_parm2=examshow $wims_name_help
 </small>
!default class_examshow=yes
!set up_examshow=$class_examshow
!formselect up_examshow list no,yes prompt $wims_name_no,$wims_name_yes
!set up_ent=$class_ent
$table_tr<td align=right>Other platform link
<small>
!href cmd=help&special_parm=config&special_parm2=ent $wims_name_help
 </small>
<td colspan=3>
<input size=50 name=up_ent value="$class_ent">
$table_hdtr<td align=center colspan=4>
<input type=submit name=save value="$wims_name_tosave">
&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
$table_end <p>
</form>

Other configurations:
!href cmd=reply&job=present Podoba
.
!href cmd=reply&job=neighbor&job2=first Sosednje uèilnice
.
!href cmd=reply&job=connect&job2=first Drugi stre¾niki
.
!href module=adm/class/passwd Gesla
.
!if $classdepth<=1 
 !href cmd=reply&job=authtype Authentification type
.
!endif
!href module=adm/forum/mboard&job=config Deska za sporoèila
.
!href module=adm/doc Dokumenti
.
!href module=adm/class/motd Sporoèilo dneva
.
!href cmd=reply&job=access Omejitve virov
.
!href cmd=reply&job=oefdefault OEF default configuration
.
!if $class_type iswordof 2 3 4
 !href cmd=reply&job=propagate Send setups to subclasses
.
!endif
<p>
!href cmd=reply&job=security Nastavitve varnosti
.
!href cmd=reply&job=arch&job2=first Shranjevanje in obnova
.
!href cmd=reply&job=clean Selektivno èi¹èenje
.
<p>
!href module=adm/light&phtml=useropts.phtml.$lang Osebne nastavitve
.
<br>
Rebuild indices<sup>
!href cmd=help&special_parm=index $wims_name_help
</sup>:
!if $class_type=4
!href cmd=reply&job=index&job2=structure subclasses
,
!endif
!if $class_type=4 or $class_type=2
!href cmd=reply&job=index&job2=teacherlist teachers
,
!endif
!href cmd=reply&job=index&job2=userlist participants
,
!href cmd=reply&job=index&job2=oef exercises
,
!href cmd=reply&job=index&job2=doc documents
.
<p>
!href module=adm/light&phtml=useropts.phtml.$lang My personal preferences
.

<p>
Trenutna porabljen prostor v uèilnici: $du megabytes. (The allowance is
$wims_class_quota.)

!reset up_institution, up_description, up_supervisor, up_email, \
	up_lang, up_level, up_limit, up_topscores, up_expiration, up_secure, up_lock,\
	up_option,up_exolog,up_examlog,up_examshow,up_ent\
	pr_homepage, pr_bgcolor, pr_refcolor, pr_ref_menucolor,pr_bgimg, pr_css, pr_theme, pr_theme_icon

