
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,Maj,Jun,Jul,Avg,Sep,Okt,Nov,Dec

!set title=Nastavitve in vzdr¾evanje
!if $job=arch
 !set title=Shranjevanje in obnova
 !goto commun
!endif

!if $job=clean
 !set title=Èi¹èenje uèilnice
 !goto commun
!endif

!if $job=neighbor
 !set title=Sosednje uèilnice
 !distribute lines Neighborhood<br>declaration\
   Resource sharing\
   by you\
   by the other\
   Active mutually sharing.\
   You are sharing its resources.\
   Sharing your resources.\
   Mutually allowing sharings.\
   Allowed to share your resources.\
   Allows you to share its resources.\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3
 !goto commun
!endif

!if $job=connect
 !set title=Povezava z drugimi stre¾niki
 !goto commun
!endif

!if $job=access
 !set title=Resource access configuration
 !goto commun
!endif

!if $job2=addshare
 !set title=Share resources on class 
 !goto commun
!endif

!if $job=grestrict
 !set title=Score restriction
 !goto commun
!endif

!if $job=present
 !set title=Nastavitve uèilnice
 !goto commun
!endif

!if $job=oefdefault
 !set title=Default configuration for OEF modules
 !goto commun
!endif

!if $job=security
 !set title=Na voljo so vam naslednje varnostne aktivnosti
 !goto commun
!endif

!if $job=authtype
 !set title=Ldap authentification
 !goto commun
!endif

:commun
!distribute line Authentification\
Osebne nastavitve\
Omejitve virov\
Paramétrage OEF\
Sosednje uèilnice\
Nastavitve varnosti\
Selektivno èi¹èenje\
Actualiser\
Drugi stre¾niki\
Gesla\
Send setups to subclasses\
Podoba\
Score restriction\
Platform address\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items subclasses,participants,exercises,documents,teachers\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers
