
Nastavitve uèilnice.

!form reply
<input type=hidden name=up_job value=present>
<p>$table_header
$table_tr<td align=right>Logotip uèilnice
<small>
!href cmd=help&special_parm=config&special_parm2=logo help
 </small>
<td><input size=45 name=pr_logo value="$class_logo">
$table_tr<td align=right>Polo¾aj logotipa
<small>
!href cmd=help&special_parm=config&special_parm2=logo help
 </small>
<td>
!set pr_logoside=$class_logoside
!formselect pr_logoside list left,right prompt top left, top right
 corner of the home pages.
$table_tr<td align=right>Domaèa stran uporabnikov
<small>
!href cmd=help&special_parm=config&special_parm2=homepage help
 </small>
<td><input size=45 name=pr_homepage value="$class_homepage">
$table_tr<td align=right>Page background color
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_bgcolor value="$class_bgcolor">
$table_tr<td align=right>Menu background color
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor help
 </small>
<td><input size=10 name=pr_refcolor value="$class_refcolor">
$table_tr<td align=right>Background image file
<small>
!href cmd=help&special_parm=config&special_parm2=bgimg help
 </small>
<td><input size=45 name=pr_bgimg value="$class_bgimg">
$table_tr<td align=right>Style theme of the class
<small>
!href cmd=help&special_parm=config&special_parm2=theme help
 </small>
<td>
!set pr_theme=$class_theme
!formselect pr_theme list $themelist
$table_tr<td align=right>Style sheet (css) of pages
<small>
!href cmd=help&special_parm=config&special_parm2=css help
 </small>
<td>
!set pr_css=$class_css
!formselect pr_css list $csslist
$table_tr<td align=right valign=middle>You can define your class-wide
stylesheet here:
<small>
!href cmd=help&special_parm=config&special_parm2=css help
</small>
<td valign=middle>
<textarea rows=6 cols=45 name=pr_cssfile>$cssfile</textarea>
$table_hdtr<td align=center colspan=2>
<input type=submit name=save value=Save>
&nbsp;
<input type=submit name=abandon value=Restore>
$table_end <p>
</form>

!reset pr_logo, pr_logoside, pr_bgcolor, pr_refcolor, \
	pr_bgimg, pr_css, pr_theme, pr_homepage, pr_cssfile

