
!read adm/title.phtml 3\
\
Na voljo so vam naslednje varnostne aktivnosti:

<ul>
<li><p>
!href module=adm/class/passwd.$module_language Zamenjava gesla
.

<li><p>
!href cmd=renew&job=log Ogled zapisa vseh skrbni¹kih aktivnosti v uèilnici. Vi bi morali biti edini vir teh aktivnosti, sicer je najbr¾ pri¹lo do zlorabe gesla.

<li><p>Nastavite
!href cmd=renew&job=grestrict omejitve
 spletnih mest, s katerih je dovoljeno re¹evanje nalog za toèke.

<li><p>Druge varnostne nastavitve so v
!href cmd=renew&job=list nastavitvah uèilnice
.

</ul>

