<!-- begin of $wims_theme/docheader.phtml -->

!! document menu
!nocache
!set wims_theme_docheader=yes
!if $wims_class=$empty or adm/doc notin $module
  !set oneitem=oneitem.phtml
!else
  !set oneitem=./adm/oneitem.phtml
!endif
<!-- begin of docheader.phtml -->

!if $job iswordof read print
 <div id="wimsdoc">
!endif

!if $wims_lightpopup=yes
  !goto end1
!endif
<div id="wimstopbox">
!distribute items span into div1
 <div class="wimsmenu float_left">
    !read themes/_widgets/headhome.phtml
    !read themes/_widgets/ariane.phtml
 </div>
 !read themes/_widgets/docnavigation.phtml
 !read themes/_widgets/docheadermenu.phtml
</div><!--end of wimstopbox  -->
:end1
!if $wims_lightpopup=yes
  <div id="wimslightpopup">
   <div id="wimsbodybox">
    <div id="wimspagebox">
  !exit
!endif
 <div id="wimsbodybox">
  <div id="wimspagebox">

!read themes/_widgets/docsidemenu.phtml
!read themes/_widgets/alertchat.phtml

<!-- end of docheader.phtml -->
