
!! document menu
!nocache
!set wims_theme_docheader=yes
<!-- begin of docheader.phtml -->

!!!if $wims_developer= and $wims_user!=supervisor
 <div id=wimsdoc>
!!!endif
<div id="wimstopbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
!if help notin $wims_session
 !if $wims_class=$empty
  <span class="menuitem">
  !href module=home $wims_name_doch_wims
  </span><!-- menuitem-->
 !else
  !if _doc isin $wims_session
  <span class="menuitem">
   <a href="#" onclick="window.close()">$wims_name_doch_class</a>
  </span><!-- menuitem-->
  !else 
  <span class="menuitem">
   !href module=home $wims_name_doch_class
  </span><!-- menuitem-->
  !endif
  !if $m_wims_sequence>0
    <span class="menuitem">
    !if $wims_user=supervisor
     !href module=adm/class/sequence&seq=$m_wims_sequence $name
    !else
     !href module=home&seq=$m_wims_sequence $name
    !endif
    </span><!-- menuitem-->
  !else
   !if $wims_sequence>0
    !set ti=!defof sequence_Title in wimshome/log/classes/$wims_class/seq/.def
    <span class="menuitem">
     !if $wims_user=supervisor
       !href module=adm/class/sequence&seq=$wims_sequence
     !else
       !href module=home&seq=$wims_sequence $wims_name_sequence
     !endif
    </span><!-- menuitem-->
   !endif
  !endif
 !endif
!endif
 !if ..//adm/doc isin ..//$module and \
    ($wims_class=$empty or $wims_user=supervisor)
  <span class="menuitem">
  !href module=$module&cmd=reply&job=home $wims_name_doch_docs
  </span><!-- menuitem-->
 !endif
!endif
!default upbl=main
!if $block!=main and $job=read
  <span class="menuitem">
 !href cmd=reply&doc=$doc&block=$upbl $wims_name_doch_up
  </span><!-- menuitem-->
 !! <img src="gifs/arrows/up2.32.gif" alt=up>
 !if $prev!=$empty and $prev!=$upbl
  <span class="menuitem">
  !href cmd=reply&doc=$doc&block=$prev $wims_name_doch_prev
  </span><!-- menuitem-->
 !endif
 !if $next!=$empty and $next!=$upbl
  <span class="menuitem">
  !href cmd=reply&doc=$doc&block=$next $wims_name_doch_next
  </span><!-- menuitem-->
 !endif
!endif
!if $job=read
 !if $blocklast$blocknext!=$empty
  <span class="menuitem">
  [
  !if $blocklast!=$empty
   !href cmd=reply&doc=$doclast&block=$blocklast&readcntadv=-1 &lt;&lt;
  !endif
   &nbsp;$wims_name_doch_hist
  !if $blocknext!=$empty
   &nbsp;
   !href cmd=reply&doc=$docnext&block=$blocknext&readcntadv=1 &gt;&gt;
  !endif
  ]
  </span><!-- menuitem-->
 !endif
!! !href cmd=reply&job=read $wims_name_doch_reload
!endif
!if $printable=yes
  <span class="menuitem">
 !href cmd=reply&job=read&doc=$doc&block=$startblock $wims_name_doch_interactive
  </span><!-- menuitem-->
!else
 !if $job=read
  <span class="menuitem">
  !href cmd=reply&job=print&doc=$doc $wims_name_doch_printable
  </span><!-- menuitem-->
 !endif
 !if $job=exosource
  <span class="menuitem">
  !href cmd=reply&job=read $wims_name_doch_back
  </span><!-- menuitem-->
 !endif
 !if $doc!=$helpd and $editable=yes
  <span class="menuitem">
  !href target=wims_help module=$module&cmd=new&job=read&doc=$helpd $wims_name_doch_help
  </span><!-- menuitem-->
 !endif
  <span class="menuitem">
 !href target=wims_mhelp module=$module&cmd=help&special_parm=about $wims_name_doch_about
  </span><!-- menuitem-->
!endif
</div><!--end of wimsmenu  -->
</div><!--end of wimstopbox  -->

 <div id="wimsbodybox">
 <div id="wimspagebox">
<!-- end of docheader.phtml -->
