
!! document menu
!nocache
!set wims_theme_docheader=yes
<!-- begin of docheader.phtml -->

!!!if $wims_developer= and $wims_user!=supervisor
 <div id=wimsdoc>
!!!endif
<div id="wimstopbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
!if help notin $wims_session
 !if $wims_class=$empty
  <div class="menuitem">
  !href module=home $wims_name_doch_wims
  </div>
 !else
  !if _doc isin $wims_session
  <div class="menuitem">
   <a href="#" onclick="window.close()">$wims_name_doch_class</a>
  </div>
  !else 
  <div class="menuitem">
   !href module=home $wims_name_doch_class
  </div>
  !endif
 !endif
 !if ..//adm/doc isin ..//$module and \
    ($wims_class=$empty or $wims_user=supervisor)
  <div class="menuitem">
  !href module=$module&cmd=reply&job=home $wims_name_doch_docs
  </div>
 !endif
!endif
!default upbl=main
!if $block!=main and $job=read
  <div class="menuitem">
 !href cmd=reply&doc=$doc&block=$upbl $wims_name_doch_up
  </div>
 !! <img src="gifs/arrows/up2.32.gif" alt=up>
 !if $prev!=$empty and $prev!=$upbl
  <div class="menuitem">
  !href cmd=reply&doc=$doc&block=$prev $wims_name_doch_prev
  </div>
 !endif
 !if $next!=$empty and $next!=$upbl
  <div class="menuitem">
  !href cmd=reply&doc=$doc&block=$next $wims_name_doch_next
  </div>
 !endif
!endif
!if $job=read
 !if $blocklast$blocknext!=$empty
  <div class="menuitem">
  [
  !if $blocklast!=$empty
   !href cmd=reply&doc=$doclast&block=$blocklast&readcntadv=-1 &lt;&lt;
  !endif
   &nbsp;$wims_name_doch_hist
  !if $blocknext!=$empty
   &nbsp;
   !href cmd=reply&doc=$docnext&block=$blocknext&readcntadv=1 &gt;&gt;
  !endif
  ]
  </div>
 !endif
!! !href cmd=reply&job=read $wims_name_doch_reload
!endif
<div class="menuitem"></div>
!if $printable=yes
  <div class="menuitem">
 !href cmd=reply&job=read&doc=$doc&block=$startblock $wims_name_doch_interactive
  </div>
!else
 !if $job=read
  <div class="menuitem">
  !href cmd=reply&job=print&doc=$doc $wims_name_doch_printable
  </div>
 !endif
 !if $job=exosource
  <div class="menuitem">
  !href cmd=reply&job=read $wims_name_doch_back
  </div>
 !endif
 !if $doc!=$helpd and $editable=yes
  <div class="menuitem">
  !href target=wims_help module=$module&cmd=new&job=read&doc=$helpd $wims_name_doch_help
  </div>
 !endif
  <div class="menuitem">
 !href target=wims_mhelp module=$module&cmd=help&special_parm=about $wims_name_doch_about
  </div>
!endif
</div><!--end of wimsmenu  -->
</div><!--end of wimstopbox  -->

 <div id="wimsbodybox">
 <div id="wimspagebox">
<!-- end of docheader.phtml -->
