<!-- begin of header.phtml -->
!! Header menu bar definition.
!nocache
!set wims_theme_header=yes

!default wims_theme_icon=$class_theme_icon
!default wims_theme_icon=standard
!if _help isin $wims_session
 <div id="wimsmhelp">
!endif
!if _exam isin $wims_session
 <div id="wimsexam">
!endif
!if $wims_lightpopup=yes
 <div id="wimslightpopup">
!endif
!set wims_theme_version=1
!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module
!if $wims_hm_cnt!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
<div id="wimstopbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
!for i_=1 to $wims_hm_cnt
 <span class="topmenuitem">
 !set 1_=!line $i_ of $wims_hm
 !read oneitem.phtml $1_
 </span> <!--topmenuitem-->
!next i_

!! -----------------------Insert "Permalien" --------------------------------
!! Permalien / lecteur exportable : ces lignes permettent d'integrer facilement la page courante a un autre site :

!set current_module=!replace / by , in $module

!set module_path= !item 1 of $current_module	
!if $module_path notitemof home,adm,classes and _exam notin $session and $wims_lightpopup!=yes and ($wims_user=supervisor or $wims_user=$empty)
	!set permalien=$wims_ref_name?module=$module

<div class="topmenuitem" id="header_export">
<div id="lien_export_media" style="display:block">
	<a href="#" class="about" onclick="document.getElementById('export_media').style.display = 'block';document.getElementById('lien_export_media').style.display = 'none';">$wims_name_display1</a>
</div><!--lien_export_media-->
<div id="export_media" style="display:none" align="left">
<div align="center"> -- <strong>$wims_name_display1</strong> 
-- &nbsp; <a href="#" onclick="document.getElementById('export_media').style.display = 'none';document.getElementById('lien_export_media').style.display = 'block';">
($wims_name_mask_this)</a></div><!--wimstail-->
<hr>
	<strong>$wims_name_permalink1</strong> 
	 <small>($wims_name_display2)</small> :
	<a href="$permalien">$permalien</a>
	<hr>
	<b>$wims_name_embeddable</b>
	<small> ($wims_name_display3) :
	</small>
	<textarea  style="vertical-align:middle" rows="3" cols="50" readonly="readonly" id="wims_embed_textarea" >&lt;iframe src="$permalien&+embededwindow=true" title="WIMS embeddable" frameborder="0" class="wims_embed" style="width:100%;height:100%;min-height:800px;" allowfullscreen>&lt;/iframe></textarea>
</div><!--export_media-->
</div><!--topmenuitem-->

!endif
!!------------------------------------Fin de l'insert "Permalien" --------------------------


</div><!--wimsmenu-->
</div><!--wimstopbox-->
!endif
!if $module!=home or $wims_user!=
<div id="wimsbodybox">
!if $wims_homeref_n3>0
  <div id="wimsmenutab">
  <div class="wimsmenu"> 
  !for i_=1 to $wims_homeref_n3
    !set 1_=!line $i_ of $wims_rm_3
    !if $(1_[1])!=
      <div class="itemsep">toto</div>
    !else
     <div class="menuitem">
     toto
     !read oneitem.phtml $1_
     </div>
    !endif
  !next i_
  </div><!--wimsmenu-->
  </div><!--wimsmenutab-->
!endif

<div id="wimspagebox">
!endif
<!-- end of header.phtml -->
