<!-- begin of standard/header.phtml -->

!! Header menu bar definition.
!nocache
!set wims_theme_header=yes
!set jquery_defined=yes

!default wims_theme_icon=$class_theme_icon
!default wims_theme_icon=wimsedu

!if _help isin $wims_session
  <div id="wimsmhelp">
!endif

!if _exam isin $wims_session
  <div id="wimsexam">
!endif

!if $wims_lightpopup=yes
  <div id="wimslightpopup">
   <link rel="stylesheet" href="html/themes/_css/light.css" type="text/css">
!endif

!set wims_theme_version=1
!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module

!if $[$wims_home_items_cnt + $wims_hm_cnt + $wims_link_close_cnt]!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
 <div id="wimstopbox">

  !distribute items li into div1
  !read themes/_widgets/user_links.phtml
  !distribute items span into div1
  <div class="wimsmenu float_left">
   !read themes/_widgets/headhome.phtml
  </div>
  <div class="wimsmenu">
    !read themes/_widgets/headmenu.phtml
    !read themes/_widgets/about.phtml
    !!if _help notin $wims_session
      !!read themes/_widgets/permalink.phtml
    !!endif
  </div><!--wimsmenu-->

  !read themes/_widgets/ariane.phtml
  !reset div1
 </div><!--wimstopbox-->
!endif

!if $module!=home or $wims_user!=
  <div id="wimsbodybox">
    <div id="wimspagebox">
!endif

!read themes/_widgets/alertchat.phtml

<!-- end of standard/header.phtml -->
