<!--begin of $wims_theme/htmlheader.phtml-->
<meta http-equiv="Content-Type" content="text/html; charset=$wims_main_font">
<title>$module_title2</title>
<meta name="GENERATOR" content="wims [$module_language]">
<meta name="description" content="$module_description $wims_site_description">
<meta name="keywords" content="$wims_site_keywords, $module_domain, $module_keywords">
<meta name="Author" content="$module_author">
<meta http-equiv="Content-Style-Type" content="text/css">

$wims_expire
$wims_CSS

<!-- Styles pour iphone -->
<link rel="stylesheet" media="screen and (max-device-width: 480px)" href="html/css/mobile.css" type="text/css"> 

<!-- Styles pour ipad (portrait) -->
<link rel="stylesheet" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" href="html/css/ipad-portrait.css" type="text/css"> 

<!-- Styles pour ipad (landscape) -->
<link rel="stylesheet" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" href="html/css/ipad-landscape.css" type="text/css"> 

<!-- Style pour impression -->
<link rel="stylesheet" media="print" href="html/themes/$wims_theme/print.css" type="text/css">

<style type="text/css">
#wimsmenumodubox .wimsmenu .menuitem a { color: $wims_ref_menucolor;}
#wimsmenumodubox .wimstail { background-color: $wims_bgcolor;}
#wimsmenubox .wimsmenu .menuitem a { color: $wims_ref_menucolor;}
#wimsmenubox .wimstail { background-color: $wims_bgcolor;}
#wimsmenubox { background-color: $wims_bgcolor;}
#wimstopbox { color: $wims_ref_menucolor;}

.container h4{	background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_pendant,#menu_html {	background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_avant,#menu_apres {	background-color:$wims_ref_button_bgcolor;	color:$wims_ref_button_color;}
.infobulle{  background-color: $wims_ref_button_bgcolor;  color: $wims_ref_button_color;}

.topmenuitem a { color: $wims_ref_menucolor;}
.menuitem a { color: $wims_ref_menucolor;}

table.wimstable th {background-color: $wims_ref_bgcolor; color:$wims_ref_menucolor;}
table.wimstable th a {color: $wims_ref_menucolor;}
table.wimstable caption {background-color: $wims_ref_bgcolor;color: $wims_ref_menucolor;}
table.wimstable caption a {color: $wims_ref_menucolor;}
table.wimstable caption a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}
table.wimstable th a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}

input[type="submit"],input[type="button"],.wims_button{ background-color:$wims_ref_button_bgcolor;color:$wims_ref_button_color;}
.wims_button_help{ background-color:$wims_ref_button_help_bgcolor;color:$wims_ref_button_help_color;}

.legend {background-color: $wims_ref_bgcolor;color:$wims_ref_menucolor;}
</style>
<!--end $wims_theme/htmlheader.phtml-->