!set wims_theme_mhelptail=yes
<!-- begin of mhelptail.phtml -->
</div> <!--wimsbody-->
</div> <!--wimspagebox-->

<div id="wimsmenubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menuitem">
<a href="#" onclick="window.close()">$wims_name_back2</a>
</div><!--menuitem-->
</div><!--wimsmenu-->
</div><!--wimsmenubox-->
</div><!--wimsbodybox-->
</div><!--wimsmhelp-->

<!-- end of mhelptail.phtml -->
