<!-- begin of tail.phtml -->
!! Tail menu theme.
!nocache
!set wims_theme_tail=yes
</div><!--end of wimspagebox-->
<div id="wimsmenubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
!if $wims_homeref_special!=$empty
 <div class="tailitem">$wims_homeref_special</div><!--tailitem-->
 !exit
!endif
!for i_=1 to $wims_homeref_n1
 <div class="menuitem">
 !set 1_=!line $i_ of $wims_rm_1
 !read oneitem.phtml $1_
 </div><!--menuitem-->
!next i_
</div><!--wimsmenu-->
</div><!--wimsmenubox-->
</div><!--wimsbodybox-->

<div id="wimstailbox">
<div class="wimstail">
!for i_=1 to $wims_homeref_n2
 <div class="tailitem">
 !set 1_=!line $i_ of $wims_rm_2
 !read oneitem.phtml $1_
 </div><!--tailitem-->
!next i_
</div><!--wimstail-->
</div><!--wimstailbox-->
<!-- end of tail.phtml -->
