<!-- begin of $wims_theme/tail.phtml -->
!! Tail menu theme.
!nocache
!set wims_theme_tail=yes

   <br class="spacer"/>
  </div><!--end of wimsbody-->
 <br class="spacer"/>
</div><!--end of wimspagebox-->
!if $wims_homeref_special!=$empty
    </div><!--end of wimspagebox -->
   <div class="wimsmenu"> 
    <div class="tailitem">$wims_homeref_special</div><!--tailitem-->
   </div><!--wimsmenu-->
 </div><!--wimsbodybox-->
</div><!--id wimsexam-->
 !exit
!endif

!read themes/_widgets/menumodubox.phtml

!read themes/_widgets/menubox.phtml

<div class="spacer"></div>
</div><!--wimsbodybox-->

!read themes/_widgets/about.phtml

!endif

<!--FIN BAS DE PAGE-->

!if help isin $wims_session
</div><!--wims_mhelp-->
!endif
!if $wims_lightpopup=yes
 </div> <!--wimslightpopup-->
 </div>
!endif

<!-- end of $wims_theme/tail.phtml -->
