<!-- begin of user.phtml -->
!! Class participant page theme.
!nocache
!if $module!=home
 !exit
!endif

!set home_theme=yes
!set im=<img border=0 src=
!set percents=!getscorepercent
!set class_homepage=!getdef class_homepage in wimshome/log/classes/$wims_class/.def
!set etest=!record 0 of wimshome/log/classes/$wims_class/.parmreg/$wims_user.exam
!set n_=!wordcnt $etest

!if / isin $class_homepage and _tool notin $wims_session
 !set deffile=wimshome/log/classes/$wims_class/doc/$class_homepage.def
 !set t_=!getdef titb in $deffile
 !if $t_=$empty or $n_>=4
  !goto normal
 !endif
 !read ./userhome.phtml
 !goto end
!endif

:normal
!read classlogo.phtml
<center>
<br> <br>
<b><font size="+2">$wims_classname</font></b>
<br>
<small>($(wims_name_$class_typename))</small>
!if $wims_superclass=$empty or $wims_superclass=$wims_class
 $wims_institutionname
!else
 !href module=adm/class/classes&type=authparticipant&class=$wims_superclass&auth_user=$wims_user $wims_institutionname
  !if / isin $class_parent and $class_type=1
  !set pname=!defof class_description in wimshome/log/classes/$class_parent/.def
  / 
  !href module=adm/class/classes&type=authparticipant&class=$class_parent&auth_user=$wims_user $pname
 !endif
!endif
</center>
<br clear=all> <br></div><div class=wimsbody>

!if _tool isin $wims_session
 !read ./tools.phtml
 !goto end
!endif

!set supmail=!mailurl $wims_supervisormail $wims_supervisor

!if $n_>=4
 !distribute words $etest into h_,s_,t_,n_
 !set r_=!record 0 of wimshome/sessions/$s_/examreg.$n_
 !set now=$wims_nowseconds
 !set ws=!translate _ to $ $ in $wims_session
 !set ws=!word 1 of $ws
 !set sm=!record 0 of wimshome/log/classes/$wims_class/.E$n_
 !if $r_!=$empty and $s_!=$ws and $t_>$now and $sm!=#
  $U_examworking
  !if $h_=$httpd_REMOTE_ADDR
   !href session=$s_&module=adm/class/exam.$lang&job=student&exam=$n_ $U_examcont
  !else
   $U_examdouble
   !sh rm -f ../sessions/$ws/var.stat >/dev/null
  !endif
  !goto end
 !endif
 !if $t_<$now or $r_=$empty
  !writefile wimshome/log/classes/$wims_class/.parmreg/$wims_user.exam
 !endif
!endif

$U_greet
<small>
!if $class_type isin 234
 !href module=adm/class/userlist&job=userprop $U_account
 &nbsp;
!endif
!!!href target=wims_help module=help/main&chapter=3 $N_help
</small>

!if & isin $newmsgcnt or $newmsgcnt>0
 <br>
 !href module=adm/forum/mboard $U_newmsg
!endif

<p>
<div class="wims_class_motd">
!read ./wimshome/log/classes/$wims_class/.motd
</div>
!let test=!record 0 of wimshome/log/classes/$wims_class/motd/.$wims_user
!if $test!=$empty
 <div class="wims_class_pmotd">
 !read ./wimshome/log/classes/$wims_class/motd/$wims_user
 &nbsp; [
 !href module=adm/class/motd $N_hide
] </div>
!endif

<p>
!if $class_type>=2
 !read ./subclasses.phtml
 !set is_interclass=yes
!endif

!set dcnt=!recordcnt wimshome/log/classes/$wims_class/doc/.index
!for i=1 to $dcnt
 !set d_=!record $i of wimshome/log/classes/$wims_class/doc/.index
 !distribute lines $d_ into s_,t_,a_,e_,c_,o_
 !if $o_>0
  !set ds_list=!append line $s_ to $ds_list
  !set dt_list=!append line $t_ to $dt_list
 !endif
!next i
!set dcnt=!linecnt $ds_list
!set t=!recordcnt wimshome/log/classes/$wims_class/sheets/.sheets
!set wlist=!record 0 of wimshome/log/classes/$wims_class/sheets/.weight
!set aclist=
!for i=1 to $t
 !set s_$i=!record $i of wimshome/log/classes/$wims_class/sheets/.sheets
 !set a_=!line 1 of $(s_$i)
 !if $a_>=1 and $a_<=2
  !set aclist=!append item $i to $aclist
 !endif
!next i
!set n=!itemcnt $aclist
!set t=!recordcnt wimshome/log/classes/$wims_class/exams/.exams
!set aelist=
!for i=1 to $t
 !set e_$i=!record $i of wimshome/log/classes/$wims_class/exams/.exams
 !set a_=!line 1 of $(e_$i)
 !if $a_>=1 and $a_<=2
  !set aelist=!append item $i to $aelist
 !endif
!next i
!set m=!itemcnt $aelist
!set t=!recordcnt wimshome/log/classes/$wims_class/vote/.votes
!set avlist=
!for i=1 to $t
 !set v_$i=!record $i of wimshome/log/classes/$wims_class/vote/.votes
 !set a_=!line 1 of $(v_$i)
 !if $a_>=1 and $a_<=2
  !set avlist=!append item $i to $avlist
 !endif
!next i
!set v=!itemcnt $avlist

!ifval $dcnt+$n+$m+$v=0
 !if $is_interclass!=yes
 $U_nosheet
 !endif
!else
 !if $is_interclass!=yes
 !!$U_assign
 !!<div class="wims_user_myscore">
!! !href module=adm/class/userlist.$lang $U_myscore
!!</div>
 !endif
 !if $dcnt>0
  <table class="wims_user_doc_table">
  !for i=1 to $dcnt
   !set s_=!line $i of $ds_list
   !set t_=!line $i of $dt_list
   <tr class="wims_user_doc"><td class="wims_user_doc_type">$U_Doc</td><td colspan=3>
   !href module=adm/doc.$lang?job=read&doc=$s_&block=main $t_
   </td></tr>
  !next i
  </table>
  <p>
 !endif
 !if $n >0
  <table class="wims_user_sheet_table">
  !for i=1 to $n
   !set se=!item $i of $aclist
   !distribute lines $(s_$se) into ac,t_,ti,de
   <tr class="wims_user_sheet"><td class="wims_user_sheet_type">$U_Sheet $se. <td class="wims_user_sheet_desc">
  !href module=adm/sheet&sh=$se $ti
  </td><td class="wims_user_sheet_expire">
   !if $ac>=2
    $U_expired
   !else
    !if showshexpire iswordof $class_option
     !read misc/expire.phtml.$lang $t_
    !endif
   !endif
   </td>
   !set pe=!line $se of $percents
   !set p1=!word 1 of $pe
   !set p2=!word 2 of $pe
   <td class="wims_user_sheet_score">
   !if $p1!=$empty
    $p1% $U_done, $U_average $[$p2]/10
   !else
    &nbsp;
   !endif
   </td><td>
   !if showshweight iswordof $class_option
    ($U_weight
     !line $i of $wlist
    )
   !endif
   </td>
   </tr>
  !next i
  </table><p>
 !endif
 !if $m>0
 <table class="wims_user_exam_table">
 !for i=1 to $m
  !set se=!item $i of $aelist
  !distribute lines $(e_$se) into ac,t_,s_,ti,de
  <tr class="wims_user_exam"><td class="wims_user_exam_type">$U_Exam $se. </td>
  <td class="wims_user_exam_desc">
  !href module=adm/class/exam&job=student&exam=$se $ti
  </td><td class="wims_user_exam_expire">
  !if $ac>=2
   $U_expired
  !else
   !if showexexpire iswordof $class_option
    !read misc/expire.phtml.$lang $t_
   !else
    &nbsp;
   !endif
  !endif
  </td></tr>
 !next i
 </table>
 <p>
 !endif
 !if $v>0
 <table class="wims_user_vote_table">
 !for i=1 to $v
  !set sv=!item $i of $avlist
  !distribute lines $(v_$sv) into ac,ti
  <tr class="wims_user_vote"><td class="wims_user_vote_type">$U_Vote $i</td><td class="wims_user_vote_desc">
  !href module=adm/vote&job=read&vote=$sv $ti
  </td><td class="wims_user_vote_expire">
  !if $ac>=2
   $U_expired
  !else
   &nbsp;
  !endif
  </td>
 !next i
 </table><p>
!endif
!endif

:endbar
</div><!--wimsbody-->
</div>
<div id="wimsmenumodbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
!if $exist_cdt=yes
<div class="menuitem">
  !href module=adm/class/cdt $U_cdt
</div><!--menuitem-->
!endif
<div class="menuitem">
!href module=adm/forum/mboard $im "gifs/themes/$wims_theme/forum.gif" alt="forum" title=forum"> $N_Mboard
</div><!--menuitem-->
!ifval $dcnt+$n+$m+$v>0 and $is_interclass!=yes
<div class="menuitem"><hr></div><!--menuitem-->
<div class="menuitem">
!href module=adm/class/userlist.$lang $im "gifs/themes/$wims_theme/myscore.gif" alt="myscore" title=myscore"> $U_myscore
</div><!--menuitem-->
!endif
!if $class_type isin 234
<div class="menuitem">
 !href module=adm/class/userlist&job=userprop $im "gifs/themes/$wims_theme/account.gif" alt="account" title="account"> $U_account
</div><!--menuitem-->
!endif
<div class="menuitem"><hr></div><!--menuitem-->
!set class_ent1=!rows2lines $class_ent
!set class_ent_n0=!linecnt $class_ent1
!for i_=1 to $class_ent_n0
  !set 1_=!line $i_ of $class_ent1
   <div class="menuitem">
     <a href="$(1_[2])" target=wims_external>$im "gifs/themes/$wims_theme/ent.gif" alt="ent" title="ent"> $(1_[1])</a>
   </div><!--menuitem-->
!next i_
</div><!--wimsmenu-->
</div><!--wimsmenumodbox-->
<div id="wimsmenubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menublock">
<div class="menuitem">
!href module=adm/class/classes&type=participant $U_oclass
</div><!--menuitem-->
!!<div class="menuitem">
!!!href cmd=close&module=home $V_Quit
!!</div>
<div class="menuitem">
!mailurl $wims_supervisormail $V_Wsup
</div><!--menuitem-->
</div><!--end menublock-->
<div class="menublock">
<div class="menuitem">
!href module=adm/light&phtml=useropts.phtml.$lang $V_Chpref
</div><!--menuitem-->
<div class="menuitem">
!href module=adm/class/passwd $V_Chpass
</div><!--menuitem-->
</div><!--end menublock-->
</div><!--wimsmenu-->
</div><!--wimsmenubox-->
</div>
<div id="wimstailbox">
<div class="wimstail">
<div class="tailitem">
WIMS-$wims_version@$httpd_HTTP_HOST
</div><!--tailitem-->
:end
!if $wims_user=supervisor
 <div class="tailitem">
 !href $ $SU_Bhome
 </div>
!endif
</div><!--wimstail-->
</div><!--wimstailbox-->
</body>
</html>
<!-- end of user.phtml -->

