<!-- begin of visitor.phtml -->
!! WIMS main entrance page theme.
!nocache
!if $module!=home
 !exit
!endif
!!!!! provisoire

!set wims_name_n_participant=$V_stu
!set wims_name_n_supervisor=$V_sup
!set wims_name_n_example=$V_ex
!set wims_name_mod_new=$N_New
!set wims_name_browse=$N_browse2
!set wims_name_sheet=$V_sh
!set wims_name_dochelp=$E_dochelp
!set wims_name_faq=$E_faq
!set wims_name_doctec=$E_doc
!set wims_name_download=$E_src
!set wims_name_stat=$E_stat
!set wims_name_ref=$E_ref
!set wims_name_pref=$N_Pref
!set wims_name_mirror=$N_Mirror
!set wims_name_forum=$N_Forum
!!!!

!set home_theme=yes
!set table_colors=$wims_ref_bgcolor,$wims_ref_bgcolor
</div>
!!!set wims_headmenu_colcnt=5
<div id="wimstopbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menuitem">
<div id="wimslogo">
!href module=home&special_parm=logo <img src="gifs/logo.gif" border=0 alt="WIMS logo">
</div><!--wimslogo-->
</div><!--menuitem-->
!for i=1 to $wims_language_cnt
 !set l=!word $i of $wims_site_languages
 !if $l!=$lang
  !if $wims_language_cnt>2 and $wims_language_cnt<6
   !set l_=<small>$(lang_name_$l)</small>
  !else
   !if $wims_language_cnt<6
    !set l_=$(lang_name_$l)
   !else
    !reset l_
   !endif
  !endif
<div class="menuitem">
  !href lang=$l&session=$wims_session.1&module=$module <img src="gifs/$l.gif" alt="$(Lang_name_$l)" height=16 border=0>$l_
   <!-- don't remove this empty line or leading whitespace. Flag spacing depends on it. -->
</div><!--menuitem-->
!endif
!next i
<div class="itemsep"></div><!--itemsep-->
</div><!--wimsmenu-->
<div class="wimsmenu">
!!!if $gotcnt<=0 and $s_keywords=$empty
<div class="menuitem">$V_cls</div><!--menuitem-->
<div class="menuitem">
!read ./adm/oneitem.phtml n_participant,1,module=adm/class/classes&type=participant
 !!!href module=adm/class/classes&type=participant $im "gifs/themes/$wims_theme_image/n_participant.gif" alt="V_stu" title="V_stu"> $V_stu
</div><!--menuitem-->
<div class="menuitem">
!read ./adm/oneitem.phtml n_supervisor,1,module=adm/class/classes&type=supervisor
!! !href module=adm/class/classes&type=supervisor $im "gifs/themes/$wims_theme_image/n_supervisor.gif" alt="V_sup" title="V_sup"> $V_sup
</div><!--menuitem-->
<div class="menuitem">
!read ./adm/oneitem.phtml n_example,1,module=adm/class/classes&type=example
!! !href module=adm/class/classes&type=example $im "gifs/themes/$wims_theme_image/n_example.gif" alt="n_example" title="n_example"> $V_ex
</div><!--menuitem-->
!!<div class="menuitem">
!! !href module=help/main&chapter=3 $N_help
!!</div><!--menuitem-->
!!!endif
</div><!--wimsmenu-->
</div>
<div id="wimsbodybox">
<div id="wimspagebox">
<div class=wimsbody>
<h1 class="wims_title">
  <font size="+2"><b>$V_title</b></font>
  <br><font size="-1">(WIMS) $N_at <a href="/">$httpd_HTTP_HOST</a></font>
</h1>

!if $wims_ismanager!=0
<center>
 !href module=adm/manage $N_manage
</center> <p>
!endif

!read ./form.phtml
!read ./result.phtml

</div>
!set wims_show_stat=!tolower $wims_show_stat
!!!if yes isin $wims_show_stat
!! !set span=4
!!!else
!! !set span=2
!!!endif
</div><!--wimspagebox-->
<div id="wimsmenumodubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menuitem">
!read ./adm/oneitem.phtml mod_new,1,module=adm/new
!!!href module=adm/new $im "gifs/themes/$wims_theme_image/mod_new.gif" alt="new" title="new"> $N_New
</div><!--menuitem-->
 !if $has_browse=yes
 <div class="menuitem">
 !read ./adm/oneitem.phtml browse,1,module=adm/browse.$lang&$browse_parm
 !!!href module=adm/browse.$lang&$browse_parm $im "gifs/themes/$wims_theme_image/browse.gif" alt="browse" title="browse"> $N_browse2
 </div><!--menuitem-->
!endif
<div class="menuitem">
!read ./adm/oneitem.phtml sheet,cmd=new&module=home&search_keywords=&search_category=S#searchform
!!!href cmd=new&module=home&search_keywords=&search_category=S#searchform $im "gifs/themes/$wims_theme_image/sheet.gif" alt="sheet" title="sheet"> $V_sh
</div><!--menuitem-->
<div class="menuitem">
 !read ./adm/oneitem.phtml n_example,1,module=adm/class/classes&type=example
 !!!href module=adm/class/classes&type=example $im "gifs/themes/$wims_theme_image/n_example.gif" alt="n_example" title="n_example"> $V_ex
</div><!--menuitem-->
 <div class="itemsep"></div>
<div class="menuitem">
!read ./adm/oneitem.phtml help,4,module=help/main
!!!href module=help/main target=wims_help $im "gifs/themes/$wims_theme_image/help.gif" alt="help" title="help"> $N_Help
</div><!--menuitem-->
!!!if $gotcnt<=0 and $s_keywords=$empty
 !if $lang=fr
<div class="menuitem">
!read ./adm/oneitem.phtml dochelp,1,module=adm/doc
!!!href module=adm/doc $im "gifs/themes/$wims_theme_image/dochelp.gif" alt="dochelp" title="dochelp"> $E_dochelp
</div>
<div class="menuitem">
!read ./adm/oneitem.phtml faq,1,module=help/teacher/faq.fr
!!!href module=help/teacher/faq.fr target=wims_help $im "gifs/themes/$wims_theme_image/faq.gif" alt="faq" title="faq"> $E_faq
</div>
!endif
<div class="menuitem">
!read ./adm/oneitem.phtml doctec,1,module=help/wimsdoc.en
!!!href module=help/wimsdoc.en target=wims_help $im "gifs/themes/$wims_theme_image/doctec.gif" alt="doctec" title="doctec"> $E_doc
 </div>
 <div class="itemsep">$CR_1</div>
<div class="menuitem">
!read ./adm/oneitem.phtml createxo,1,module=adm/createxo
!!!href module=adm/createxo $im "gifs/themes/$wims_theme_image/createxo.gif" alt="createxo" title="createxo"> $CR_OEF
</div><div class="menuitem">
!read ./adm/oneitem.phtml modtool,1,module=adm/modtool
!!!href  $im "gifs/themes/$wims_theme_image/modtool.gif" alt="modtool" title="modtool"> $CR_mod
</div>
!set test_quicktool=!defof exists in wimshome/public_html/modules/adm/quicktool.$lang/version
!if $test_quicktool=yes
<div class="menuitem">
 !read ./adm/oneitem.phtml quicktool,1,cmd=new&module=adm/quicktool
 !!!href cmd=new&module=adm/quicktool $im "gifs/themes/$wims_theme_image/quicktool.gif" alt="quicktool" title="quicktool"> Quicktool
 </div>
 !endif
!set test_latex2wims=!defof title in wimshome/public_html/modules/adm/latex2wims.$lang/INDEX
!if $test_latex2wims!=
<div class="menuitem">
 !read ./adm/oneitem.phtml latex2wims,1,cmd=new&module=adm/latex2wims
 !!!href cmd=new&module=adm/latex2wims $im "gifs/themes/$wims_theme_image/latex2wims.gif" alt="latex2wims" title="latex2wims"> Latex2wims
 </div>
!endif

 <div class="itemsep"></div>
 <div class="menuitem"> 
!read ./adm/oneitem.phtml download,1,module=home&special_parm=download
!!!href module=home&special_parm=download $im "gifs/themes/$wims_theme_image/download.gif" alt="download" title="download"> $E_src
 </div>  
 !if yes isin $wims_show_stat
  <div class="menuitem">
 !read ./adm/oneitem.phtml stat,1,module=adm/stat/stat
!!!href module=adm/stat/stat $im "gifs/themes/$wims_theme_image/stat.gif" alt="stat" title="stat"> $E_stat
  </div>
  <div class="menuitem">
  !read ./adm/oneitem.phtml ref,1,module=adm/stat/referer
  !!!href module=adm/stat/referer $im "gifs/themes/$wims_theme_image/ref.gif" alt="ref" title="ref"> $E_ref
  </div>
 !endif
 <div class="itemsep"></div>
 
!!!endif
</div><!--wimsmenu-->
</div><!--wimsmenumodubox-->
<div id="wimsmenubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menuitem">
!read ./adm/oneitem.phtml pref,1,module=adm/light&phtml=useropts.phtml.$lang
!!!href module=adm/light&phtml=useropts.phtml.$lang $im "gifs/themes/$wims_theme_image/pref.gif" alt="pref" title="pref"> $N_Pref
</div><!--menuitem-->
<div class="menuitem">
!read ./adm/oneitem.phtml mirror,1,module=adm/light&phtml=mirror.phtml.$lang
!!!href module=adm/light&phtml=mirror.phtml.$lang $im "gifs/themes/$wims_theme_image/mirror.gif" alt="mirror" title="mirror"> $N_Mirror
</div><!--menuitem-->
<div class="menuitem">
!read ./adm/oneitem.phtml forum,1,module=adm/forum/forum
!!!href module=adm/forum/forum $im "gifs/themes/$wims_theme_image/forum.gif" alt="forum" title="forum"> $N_Forum
</div><!--menuitem-->
</div><!--wimsmenu-->
</div><!--wimsmenubox-->
</div><!--wimsbodybox-->
<div id="wimstailbox">
<div class="wimstail">
<div class="tailitem">WIMS-$wims_version $E_comp $wims_version_date.</div>
<div class="tailitem">$E_manager
!mailurl $wims_site_manager\
WIMS: $httpd_HTTP_HOST
.</div><!--tailitem-->
!robottrap
</div><!--wimstail-->
</div><!--wimstailbox-->
</body></html>
<!-- end of visitor.phtml -->
