<!-- begin of visitor.phtml -->
!! WIMS main entrance page theme.
!nocache
!if $module!=home
 !exit
!endif

!set home_theme=yes
!set table_colors=$wims_ref_bgcolor,$wims_ref_bgcolor
</div>
!!!set wims_headmenu_colcnt=5
<div id="wimstopbox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
<div class="menuitem">
!for i=1 to $wims_language_cnt
 !set l=!word $i of $wims_site_languages
 !if $l!=$lang
  !if $wims_language_cnt>2 and $wims_language_cnt<6
   !set l_=<small>$(lang_name_$l)</small>
  !else
   !if $wims_language_cnt<6
    !set l_=$(lang_name_$l)
   !else
    !reset l_
   !endif
  !endif

  !href lang=$l&session=$wims_session.1&module=$module <img src="gifs/$l.gif" alt="$(Lang_name_$l)" height=16 border=0>$l_
   <!-- don't remove this empty line or leading whitespace. Flag spacing depends on it. -->

!endif
!next i
</div>
</div>
<div class="tailsep"></div>

<div class="wimsmenu">
<div class="menuitem">
!href module=adm/new $N_new
</div><div class="menuitem">
!href module=adm/forum/forum $N_forum
</div><div class="menuitem">
!href module=adm/light&phtml=mirror.phtml.$lang $N_mirror
</div><div class="menuitem">
!href module=adm/light&phtml=useropts.phtml.$lang $N_pref
</div><div class="menuitem">
!href module=help/main $N_help
</div><div class="tailsep"></div>

</div>
<div class="wimsmenu">
<div class="menuitem">$V_cls</div>
</div>
<div class="tailsep"></div>
<div class="wimsmenu">
!if $gotcnt<=0 and $s_keywords=$empty

<div class="menuitem">
 !href module=adm/class/classes&type=participant $V_stu
</div><div class="menuitem">
 !href module=adm/class/classes&type=supervisor $V_sup
</div><div class="menuitem">
 !href module=adm/class/classes&type=example $V_ex
</div><div class="menuitem">
 !href module=help/main&chapter=3 $N_help
</div>
!endif
</div>
</div>

<div class=wimsbody>
<div id="wimsbodybox">
<div id="wimspagebox">

<h1> 
  !href module=home&special_parm=logo <img src="gifs/logo.gif" border=0 alt="WIMS logo" align=left>
  <font size="+2"><b>$V_title</b></font>
  <br><font size="-1">(WIMS) $N_at <a href="/">$httpd_HTTP_HOST</a></font>
</h1>

!if $wims_ismanager!=0
<center>
 !href module=adm/manage $N_manage
</center> <p>
!endif

!read ./form.phtml
!read ./result.phtml

</div>
!set wims_show_stat=!tolower $wims_show_stat
!!!if yes isin $wims_show_stat
!! !set span=4
!!!else
!! !set span=2
!!!endif
<div id="wimsmenubox" style="background-color:$wims_ref_bgcolor;">
<div class="wimsmenu">
$CR_1
<div class="menuitem">

!href module=adm/createxo $CR_OEF
</div><div class="menuitem">
!href module=adm/modtool $CR_mod
</div>
<div class="tailsep"></div>
!if $gotcnt<=0 and $s_keywords=$empty
<div class="menuitem">
 !href module=help/wimsdoc.en $E_doc
 </div>
 <div class="menuitem"> 
 !href module=home&special_parm=download $E_src
 </div>
 
 !if yes isin $wims_show_stat
 <div class="menuitem">
  !href module=adm/stat/referer $E_ref
  </div>
  <div class="menuitem">
  !href module=adm/stat/stat $E_stat
  </div>
 !endif
!endif
</div>
</div>
</div>
</div>
<div id="wimstailbox">
<div class="wimstail">
<div class="tailitem">WIMS-$wims_version $E_comp $wims_version_date.</div>
<div class="tailitem">$E_manager
!mailurl $wims_site_manager\
WIMS: $httpd_HTTP_HOST
.</div>
!robottrap
</div>
</div>
</body></html>
<!-- end of visitor.phtml -->
