<!-- begin of $wims_theme/visitor.phtml -->
!! WIMS main entrance page theme.
!nocache
!if $module!=home
 !exit
!endif

!set home_theme=yes
!set table_colors=$wims_ref_bgcolor,$wims_ref_bgcolor
</div>

<div id="wimsfrontpage">

   <div id="wimstopbox">
!set positionlogo=left
 !read themes/_widgets/institution_logo.phtml

  <div class="wimsmenu">
    !!Language Selector
	!read themes/_widgets/language_selector.phtml
  </div><!--wimsmenu-->
  <div class="wimsmenu">
   !read themes/_widgets/virtualzone.phtml
   !read themes/_widgets/authlogout.phtml
  </div><!--wimsmenu-->

 <br class="clearall"/>
</div>
<div id="wimsbodybox">
  <div id="wimspagebox">
   <div class="wimsbody">

!read themes/_widgets/site_title.phtml
!read themes/_widgets/manager.phtml

!read ./form.phtml
!if $s_category=V
 !read ./front.phtml
!else
 !read ./result.phtml
!endif

   </div><!--end wimsbody-->
  </div><!--wimspagebox-->
!distribute items div,div into div0,div1
 <div id="wimsmenumodubox">
   <$div0 class="wimsmenu">
     <$div1 class="itemsep"></$div1>
!read themes/_widgets/browsesite.phtml
     <$div1 class="itemsep"></$div1>
!read themes/_widgets/documentation.phtml
     <$div1 class="itemsep">$CR_1</$div1>
!read themes/_widgets/devtools.phtml
    <$div1 class="itemsep"></$div1>
!read themes/_widgets/site.phtml
    <$div1 class="itemsep"></$div1>
   </$div0><!--wimsmenu-->
!reset div0 div1
 </div><!--wimsmenumodubox-->

!!! changer le style
!read themes/_widgets/visitormenubox.phtml

 </div><!--wimsbodybox-->

 !read themes/_widgets/tailbox.phtml
 </div><!--wimsfrontpage-->


 </body>
</html>
<!-- end of $wims_theme/visitor.phtml -->
