
Uno dei punti di forza di WIMS è la possibilità per chiunque di creare
esercizi interattivi direttamente via web.
<p>
Tali esercizi possono essere creati online utilizzando il formato OEF
(OEF: Online Exercise Format). Questo formato non è proprietario e può
essere utilizzato su qualsiasi sistema che lo accetti.
<p>
Sebbene gli esercizi in formato OEF non siano in grado di sfruttare le piene
potenzialità di WIMS, in molti casi sono sufficientemente versatili: è 
possibile inserire parametri random (generazione casuale di nimeri, funzioni, 
testi, ...) negli esercizi, e eseguire calcoli non banali (derivazione, 
integrazione di funzioni, ...). Le risposte possono essere a scelta multipla
con una o più risposte corrette, oppure di tipo numerico o funzionale, o
un insieme di questi tipi. Le risposte possono venire analizzate al volo
attraverso condizioni ad hoc, e non semplicemente confrontate con `la risposta
giusta' (in altre parole si possono creare esercizi con infinite risposte 
corrette).
<p>
Se avete creto un 
!href module=$module&chapter=3 corso virtuale
potete creare esercizi all'interno del corso e inserirli nei
!href module=$module&chapter=3&open=$open,3_sheet#sheet test di autovalutazione
 in modo tale che gli studenti ci lavorino sopra e ottengano un 
!href module=$module&chapter=1&open=$open,1_exo#exo punteggio
 dandovi la possibilità di monitorare i loro progressi.
<p>
La creazione online di esercizi è fatta utilizzando il modulo 
!href module=adm/createxo Createxo
, che contiene pagine di help dettagliate sulla sintassi del linguaggio
OEF.

