
WIMS è progettato per essere tradotto in più lingue. Sono già disponibili
versioni in diverse lingue, in particolare inglese, francese, cinese e molte 
altre.
<p>
Sono stati fatti (e si stanno ancora facendo) sforzi per facilitare l'opera
di traduzione anche a persone che non siano programmatori esperti. Ma
l'immenso numero di informazioni contenute nel sistema e il suo 
continuo sviluppo rende la traduzione di WIMS in una nuova lingua un 
grosso lavoro.
<p>
D'altro canto, la mancanza di una traduzione può rendere impossibile
l'utilizzo effettivo di WIMS, e quindi cimentarsi nell'impresa di tradurlo
può costituire un servizio per le future generazioni del proprio paese.
<p>
Se sei interessato a tradurre WIMS nella tua lingua, contatta il team
di sviluppo di WIMS all'indirizzo
!mailurl wimsdev@cru.fr wimsdev@cru.fr
. 

<p>
Il nous faudra convenir de l'extension à deux lettres qui va représenter le langage 
(comme 'en' pour anglais, 'fr' pour francais, 'it' pour italien, etc.).
Il faudra aussi avoir une petite image du drapeau national pour le représenter.

<p>Il faut aussi choisir le codage des fichiers html (à déclarer dans src/wims.h par les développeurs).
Malheureusement, nous ne gérons pas pour l'instant l'unicode. 
Comme exemple, actuellement, <tt>en</tt>, <tt>fr</tt>, <tt>es</tt>, <tt>de</tt>, <tt>it</tt>, 
<tt>nl</tt> sont déclarés <tt>iso-8859-1</tt>,
<tt>si</tt> est déclaré <tt>iso-8859-2</tt>, <tt>ru</tt> pourrait être déclaré <tt>iso-8859-5</tt>. 

<p>
Nous allons appeler la nouvelle langue <tt>xx</tt>.

<p>
Les premiers modules à traduire sont <tt>public_html/modules/home</tt>, 
 <tt>public_html/html</tt> et <tt>public_html/msg</tt>.
Dans chacun de ces modules, il faut créer des fichiers correspondant aux fichiers ayant une extension
<tt>.en</tt> avec l'extension <tt>.xx</tt> choisie.
Actuellement, il s'agit des fichiers suivants : 
<ul><li>dans le répertoire <tt>public_html/html/</tt>, les fichiers
<tt>href.xx ,mirrors.xx, msg.phtml.xx, name.phtml.xx, robot.phtml.xx</tt> (ce
dernier doit exister mais n'a pas forcément besoin d'être traduit) ;
<li>dans le répertoire <tt>public_html/modules/home/</tt>, les fichiers
<tt>front.phtml.xx, names.xx</tt> ;
<li>dans le répertoire <tt>public_html/msg/</tt>, les fichiers
<tt>module_error.msg.xx, user_error.phtml.xx, warn_rawmath.phtml.xx, warn_rawmatrix.phtml.xx</tt>.
</ul>
<p>
A l'intérieur de <tt>public_html/modules/</tt>, on doit créer des répertoires <tt>template/doc.xx, 
  template/exercise.xx, template/oef.xx, template/tool.xx, classes/xx</tt>.
<p>
Il faut ensuite traduire les modules du répertoire <tt>public_html/modules/adm</tt>. 
Pour chacun d'eux, les fichiers à traduire se trouvent dans le sous-répertoire
<tt>lang</tt>. Copiez tous les fichiers ayant l'extension <tt>.en</tt>
en leur donnant l'extension <tt>.xx</tt> et traduisez ces copies. 
Mais, tant que vous ne les avez pas traduits, c'est la version anglaise qui apparaîtra.
Afin de faciliter les modifications éventuelles, ne recopiez le fichier <tt>names.phtml.xx</tt> que
lorsque vous l'avez traduit. Par contre, dès que celui-ci existe, il est nécessaire de créer aussi les
autres fichiers du répertoire <tt>lang</tt> avec l'extension <tt>.xx</tt>.
  Voici la liste des modules actuels (on omet la partie <tt>public_html/adm/</tt> du chemin)

<pre>browse
class/activity
class/adddoc
class/addmodule
class/cdt
class/classes
class/config
class/exam
class/exolog
class/gateway
class/grades
class/livret
class/motd
class/passwd
class/photoboard
class/regclass
class/reguser
class/sendmail
class/sequence
class/sheet
class/stat
class/userlist
createxo
doc
forum/forum
forum/mboard
forum/regforum
forum/reguser
latex2wims
manage
modtool
new
publish
quicktool
sheet
stat/referer
stat/stat
vote
</pre>

A l'intérieur de <tt>public_html/scripts/</tt>, créez aussi les répertoires <tt>
oef/xx, docu/xx</tt> et <tt>help/xx</tt>, ainsi que (mais de façon beaucoup moins essentielle)
<tt>scenario/xx, dialog/xx</tt> et <tt>deduc/xx</tt>.

<p>
Si vous ne traduisez pas tout de suite les fichiers de <tt>help/xx</tt>, il est conseillé de créer les fichiers 
et d'écrire à l'intérieur, en première ligne
<pre>!changeto help/en/yyy.phtml</pre>
si <tt>yyy.phtml</tt> est le nom du fichier. Ainsi, en attendant votre traduction,
la documentation sera présente en anglais.

Le fichier <tt>public_html/scripts/adm/lang/date.phtml.xx</tt>
 vous permet de choisir le format
de la date. Quelques petites choses à traduire dans <tt>public_html/scripts/lang</tt>.

Il est conseillé de créer 
<pre>public_html/scripts/help/anstype.xx</pre>
à moins que vous n'ayez pas traduit le fichier <tt>public_html/scripts/help/xx/reply.phtml
</tt>. Vous pouvez toujours faire comme précédement et écrire momentanément
<pre>!changeto help/anstype/yyy.phtml</pre>
pour avoir la version anglaise.


Il y a aussi quelques fichiers multi-language à modifier (mais ce n'est pas indispensable): 

<pre>
public_html/modules/home/askcookie.phtml
</pre>

<p>Et bien sûr, vous pouvez aussi traduire les modules de ressources qui vous intéressent.

<p>Per quel che riguarda la traduzione 
!! del <em>core system</em> 
di WIMS in italiano contatta
!mailurl wims@unimib.it WIMS@unimib 
.
!! ...., per la traduzione di singoli moduli .... 
!! inserire indirizzo della mailing list.
</p>

<h3>Quelques indications ou conseils</h3>

