#! /bin/sh

for i in src/*.src
do
 cp $i $i.tmp
done
for i in src/words.*.src
do
 cat src/table_domain >> $i.tmp
done

for i in src/*.tmp
do
 ##j=`echo $i | sed 's!^src/!!g;s/\.src//g'`
 j=`basename $i .src.tmp`
 if [ ! -e $j ] || [ $i -nt $j ]; then
  ../../../bin/dicsort $i 2>&1 
  mv $i.sorted $j 
  #  cp $j $i
 fi
done
rm src/*.tmp

./wgrp.pl


