
!form reply
 !set s_day=dag
 !set s_week=week
 !set s_month=maand
 !set s_year=jaar
 !set s_beginning=het begin $start_month-$start_day-$start_year
 !set name2=aanvragen
 !set name3=sessies
 !set name4=afkomstig van website
 
 Kies een periode waarover U de gegevens wilt zien: sinds

 <select name=cnt>
 !for i=1 to 15
  <option value=$i
  !if $i=$cnt
   selected
  !endif
  >$i
 !next i
 </select><select name=style>
 !for i in day,week,month,year,beginning
  <option value=$i
  !if $i=$style or ($i=week and $style=$empty)
   selected
  !endif
  >$(s_$i)
 !next i
 </select>. <p>
 De grafiek van :
 !for i=2 to 4
  <input type=radio name=plot_type value=$i
  !if $i=$plot_type
   checked
  !endif
  >$(name$i) &nbsp;
 !next i
 <p>
 <input type=checkbox name=modules value=yes
 !if $modules=yes
  checked
 !endif
 > Laat ook de statisische gegevens van de individuele modules zien.
 <p>
 <center><input type=submit value="Laat zien"></center>
</form>

!set modules=

