!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

<center>
<table border="4">
  <tr>
  <td bgcolor="bisque" nowrap="nowrap">
     <span class="tt"> Vous en avez terminé </span>
     <td>
     <table>
	<tr><td align="center" bgcolor="white"><font color="red">$auteur</font></td>
	</tr>
     </table>
	<font color="green">Bonne continuation!</font>
     </td>
  </td>
  </tr>
</table>
</center>
