
!header1
<h1 class="wims_title">$module_title
<br><font size="+0">$httpd_HTTP_HOST</font>
</h1>

<center>
!for j in $joblist
 &nbsp;
 !if $j=$job
  <u><b>$(wims_name_mod_$j)</b></u>
 !else
  !href cmd=reply&job=$j $(wims_name_mod_$j)
  !set wims_menu_items=!append line mod_$j,1,cmd=reply&job=$j \
  to $wims_menu_items
 !endif
 &nbsp;
!next j
</center><p>

!read $job.phtml
!set wims_menu_items=!append line rss_new,2,$w_/rss/new.xml,wims_internal\
rss_modif,2,$w_/rss/modif.xml,wims_internal\
to $wims_menu_items

!tail

