
!if $datacnt<1
 Aucun nouveau module n'est encore enregistré dans le système de
 publication et mise à jour des modules introduit dans
 WIMS-3.37f.
 !exit
!endif

$table_header
<caption>Nouveaux modules installés sur le serveur</caption>
$table_hdtr<th>Date</th><th>Lang</th><th>Titre</th><th>Description</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!char -2,-1 of $a_
 !set tit=!module title $a_
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>
 !module description $a_
 </td></tr>
!next i
$table_end

