
<!-- IMPORT JS :: onglet-part2.js -->
<script type="text/javascript" src="$dirjs/scripts/onglet-part2.js"></script>
<!-- IMPORT JS :: quill.min.js & quill-init.js -->
<script type="text/javascript" src="$dirjs/scripts/quill.js"></script>
<script type="text/javascript" src="$dirjs/scripts/quill-init.js"></script>

<!-- IMPORT JS :: les classes -->
<script type="text/javascript" src="$dirjs/scripts/classes/editeur.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/entete.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/ruche.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/blocProgramme.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/variable.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/reponse.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeReponse/typeReponse.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeBlocPrepa/condition.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeBlocPrepa/boucleFor.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeBlocPrepa/codeLibrePrepa.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/composant.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/Composants/coInclusionImage.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/essaim.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeEssaim/essaimQCM.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeEssaim/essaimDessinFlydraw.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeEssaim/essaimDessinJSXGraph.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/typeVariable.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/autre.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/float.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/matrix.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/complex.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/text.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/function.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/integer.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/dessinFlydraw.js"></script>
<script type="text/javascript" src="$dirjs/scripts/classes/TypeVariable/dessinJSXGraph.js"></script>
<script type="text/javascript" src="$dirjs/jsxgraph/jsxgraphcore.js"></script>

<script type="text/javascript" src="$dirjs/scripts/classes/blocFocus.js"></script>
<script src="$dirjs/libs/store.js"></script>

<script type="text/javascript">
    $$(document).ready(function () {
      rucheSys = new Ruche();
      rucheSys.dossier_images = "scripts/js/laruche/";
      rucheSys.initClasseEssaim(EssaimQCM);
      rucheSys.initClasseEssaim(EssaimFlydraw);
      rucheSys.initClasseEssaim(EssaimJSXGraph);
      rucheSys.initClasseTypeVariable(DessinFlydraw);
      // rucheSys.initClasseTypeVariable(TypeVariable);
      // rucheSys.initClasseTypeVariable(DessinJSXGraph);
    });
</script>
