
 <font color=blue><em>
$class_description</em></font>
$name_of
<font color=blue><em>$class_institution</em></font>
!if $class_creation!=$empty
 $name_creation
!endif
 $name_expires
!if $jobclass<10000
 $name_distrib
!endif
<p><center>$table_header
$table_tr<th  width=100>$name_serial<td width=200>$jobclass
$table_tr<th>$wims_name_Supervisor<td>
<a href="mailto:$class_email?subject=$name_yourclass">$class_supervisor</a>.
$table_tr<th>$wims_name_Language<td>$class_lang.
$table_tr<th>$wims_name_level<td>$class_level.
$table_tr<th>$name_limit<td>$class_limit.
!default class_password=<font color=red>-- none --</font>
$table_tr<th>$name_supervisor_r<td>$class_password
$table_end <p>

$name_erase

<p><center><font size=+1>
 !href cmd=reply&job2=erase2&jobclass=$jobclass $wims_name_yes
&nbsp;&nbsp;&nbsp;
 !href cmd=reply&job2=first $wims_name_no
 
</font></center> <p>


