
$name_prop <font color=blue><em>
$class_description</em></font>
$name_of
<font color=blue><em>$class_institution</em></font> ($name_serial $jobclass).
!if $jobclass<10000
 $name_distrib
!endif

!form reply
<table border=0>
<tr><td align=right>$name_supervisor_p:<td>
<input type=password size=20 name=clpass>
<tr><td align=right>$name_supervisor_r<td>
<input type=password size=20 name=clpass2 value="$class_password">
<br><small>$name_warning</small>
<tr><td align=right>$name_secure<td>
<input size=50 name=clsecure value="$class_secure">
<tr><td align=right>$name_expire<td>
<input size=10 name=clexp value="$class_expiration">
<tr><td><td>
<input type=submit name=save value="$wims_name_tosave">&nbsp;&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
$table_end <p>

</form>

<p>$name_remark
<a href="mailto:$class_email?subject=name_yourclassmod">$name_notify</a>
$name_change
<p>
<center>
!href cmd=reply&job2=first $name_other
</center> <p>
!set wims_menu_items=!append line classlist,1,cmd=reply&job2=first\
  ,0,\
  to $wims_menu_items

