!reset confirm
!read adm/css.phtml
!header1

!read names.phtml

!if $job iswordof student
 !changeto $job.phtml
!endif

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!!<center>$classname
!!<p>
!!<h1>Preparación de la hoja de trabajo $sheet
!!</h1></center> <p><hr width="40%">

!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$name_title

<p>
!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !goto end
!endif

!if $job=getsource
 !read getsource.phtml
 !goto end
!endif

!if $activetest>-1
 <b>Informaciones generales :</b>
!endif
!read adm/sheet/sheetinfo.phtml

!ifval $activetest=-1
 !goto end
!endif

:end1
!!<p><hr width="40%"> <p>

<a name=list></a>
<b>Contenido de la hoja de trabajo :</b>
!if $exocnt=0
 <p>Esta hoja de trabajo no tiene aún contenido. 
!else
 <small>[
 !href module=adm/sheet&sh=$sheet&job=print $wims_name_printable
 ]</small>
 !read adm/sheet/sheetcontent.phtml
!endif

!if $activetest=0
 <p>Para añadir una tarea (ejercicio, curso, herramienta, etc.) a una
 hoja de trabajo,
  !read adm/search_engine/form.phtml
 , tome el elemento correspondiente de la lista de aplicaciones,
 y decida su nivel de dificultad. Use entonces el enlace que se encuentra
 al pie de la página del ejercicio para añadirlo a la hoja de trabajo.
!endif

:end
!if $activetest>=0
 !if $activetest=0
  !let wims_menu_items=!append line putsource,1,cmd=reply&job=prep_putsource to $wims_menu_items
 !endif
 !if $job!=getsource
  !let wims_menu_items=!append line sheetsource,1,cmd=reply&job=getsource to $wims_menu_items
 !endif
 !let wims_menu_items=!append line ,0,\
printable,1,module=adm/sheet&sh=$sheet&job=print\
participantview,1,module=adm/sheet&sh=$sheet to $wims_menu_items
!endif

!tail

!distribute item ,, into job,source,title,desc,prpage

