<b>Variables d'inscription</b>
<p>
Il est possible de prévoir des champs supplémentaires à remplir
à l'inscription (au plus 10). Pour cela, vous devez donner les noms qui apparaitront
dans le formulaire d'inscription (séparés par des virgules).
Ces variables seront stockées comme variable d'inscription du participant sous
le nom de <span class="tt">regprop1</span>, <span class="tt">regprop2</span>, ...
Vous pourrez les récupérer par liaison tableur, mais pas les utiliser comme filtre.
</p>
