<b>Klik op atomen van een molecuul [2D vereist java]</b> (naam : <tt class="wims_code_words">chemclick</tt>)

Een molecuul wordt getoond in een java applet [WIMSChem] en kan worden gevraagd specifieke
atomen of bindingen te markeren met de muis. 

Dit antwoord model; moet worden gebruikt in combinatie met het commando <tt class="wims_code_words">\embed{}</tt>. 
De eerste regel van het commando <tt class="wims_code_words">\embed</tt> is de grootte in pixels van de applet in X&times;Y.
De tweede regel is te gebruien voor speciale opties: zie hievoor het <tt class="wims_code_words">chemdraw</tt> antwoord model.

Het correcte antwoord is
 <ul>
 <li>
 Eerste regel. De lijst met nummers van atomen of bindingen zoals aangegeven in het corresponderende MDMol bestand.
 Zoals bijvoorbeeld <tt class="wims_code_words">atoms:1,5 bonds:4,7</tt>
 </li>
 <li>
 Tweede regel. Het adres van de MDMol file (extensie <tt>.mol</tt>) dat het getoonde molecull beschrijft.
 Dit bestand moet aanwezig zijn in de directory <tt class="wims_fname">\data</tt> van uw module, 
 of in de algemene data directory van de wims distributie (adres <tt class="wims_fname">\data/xxx</tt>) , 
 of in een directory "modules/data" op een wims server (het adres is in dit geval datamodule/xxx) of
 in de module directory  <tt class="wims_fname">\images</tt>  (adres <tt class="wims_fname">\\imagedir/xxx</tt>).
 </li>
</ul>


De atomen of bindingen worden gemarkeerd met een rechter muis klik.
De kleur van de geselecteerde items zal veranderen.
Een herhaalde rechter muisklik op een gemarkeerd item deselecteerd.

De variabele <tt class="wims_code_variable">\reply</tt>n kan iets zijn als: <tt>atoms:1,2 bonds:2</tt>

<p>
The option <tt class="wims_code_words">help</tt> is avalaible, help on the applet is added automatically
(for the moment, only for the selection image).
</p>

<pre>
\answer{}{atoms:1,2 bonds:1;data/file.mol}{type=chemclick}
</pre>