 <b>Set karakters.</b> (naam: <tt class="wims_code_words">chset</tt>) <br>
 Dit is een lijst met alfa_numerieke karakters.<br>
 De volgorde is niet van belang.<br>
 Er wordt hoofdletter ongevoelig nagekeken.<br>
 De toepassing kan zijn een multiplechoice vraagtype, 
 waarin meerdere goede keuzes kunnen bestaan.
 <p>
 Wanneer het woord "norepeat" als optie (option=norepeat) wordt vermeld, 
 worden meerdere gelijke karakters in het leerling antwoord genegeerd.

