
<b>Klik op gekleurde tegels (vereist Java).</b>
(naam : <tt>clicktile</tt>)
<br>

Een Java applet laat een vooraf bepaald aantal gekleurde vierkantjes zien ["tegels"].
En er kunnen ook punten , lijnstukken ,lijnen of polygonen worden getoond.
De door de opdracht bepaalde "voorstelling" van vierkantjes etc kan niet door de leerling worden "weg geklikt".
De leerling kan de resterende vierkantjes van kleur doen veranderen door er op te klikken.
De rechter/middelste muis knop veranderd de kleur.

<p>Het sleutelwoord <tt>\embed</tt> moet worden gebuikt. 
Elke tegel wordt gedefinieerd door de coordinaten van de links-boven hoek , zoals <tt>integer:integer</tt>.
De eerste regel in het kommando <tt>\embed</tt> is de pixel grootte van de applet : X &times;  Y in pixels.
<br>
De tweede regel binnen vierkante haken <tt>[</tt> <tt>]</tt> bevatten de commando's voor de "voorstelling".
Deze voorstelling kan dus niet worden veranderd door de leerling.
<br>
Bij voorbeeld:<br>
<pre>
\embed{r1, 200 x 200
[xrange -5,5
yrange -5,5
background_color yellow
square blue,1:1,1:2,1:3
square green,2:3,2:4
point red,0:0]}
</pre>
De waarden voor(<tt>xrange</tt> en <tt>yrange</tt>) moeten integers zijn. 
Het correcte antwoord wordt gedefinieerd door regels als:
<tt>color,a:b,c:d</tt>
<br>
Alle coordinaten moeten in de vorm <tt>a:b</tt> zijn, waarbij <tt>a</tt> en <tt>b</tt> integers zijn.
<br>
Voor de achtergrond tekening is ook het volgende mogelijk:<br>
<pre>
polygon white,0:0,0:1,1:1
point red,0:0
line white,-5:0,5:0
</pre>
<br>
Ook kan een plaatjes als achtergrond dienen:
<pre>copy,x,y,url</pre>.
Wanneer hiervoor "flydraw" word gebruikt, is de url gelijk aan de functie <tt>draw()</tt>. 
Het wordt aangeraden de gelijke <tt>xrange</tt> en <tt>yrange</tt> voor plaatje en applet te gebuiken. 
<br>

De variabele <tt>reply</tt>n is de matrix van de aangeklikte vierkantjes (elke kleur heeft een regel).
<br>
Als de regel <pre>return_all_objects yes </pre>
de tweede regel is in het commando <tt>\embed</tt>,wordt de complete voorstelling geretourneerd als <tt>reply</tt>n.
<br>
De variabele <tt>sc_reply</tt>n is gelijk aan 0.5 als alle vierkantjes correct zijn aangeklikt, maar ze niet in de correcte kleur zijn.
<p>
Het correcte antwoord kan ook een lege variabele zijn: in dat geval moet de analyse van het leerling antwoord via "condities" verlopen.
</p>
<p>
<b>Voorbeeld</b> : 
<pre>
\statement{
  \embed{r1,200 x 200
  [xrange -5,5
   yrange -5,5
   background_color yellow
   square blue,1:1,1:2,1:3
   square green,2:3,2:4
   line white,-5:0,5:0
  ]}
}
\answer{}{blue,1:0,1:-1,1:-2; green,2:-2,2:-3}{type=clicktile}
</pre>
$table_header
$table_hdtr<th></th><th>Uitleg</th></tr>
$table_tr<td>xrange x1,x2</td><td></td></tr>
$table_tr<td>yrange y1,y2</td><td></td></tr>
$table_tr<td>background_color [color]</td><td></td></tr>
$table_tr<td>square [color],x1:y1,x2:y2,...</td><td></td></tr>
$table_tr<td>segment [color],x1:y1,x2:y2</td><td></td></tr>
$table_tr<td>polygon [color],x1:y1,x2:y2,x2:y2,...</td><td></td></tr>
$table_tr<td>return_all_objects yes/no</td><td></td></tr>

</table>
</center>

De toegestane kleuren zijn:
<tt>white,red, green, blue, orange, yellow, purple, lightgreen, lightblue, cyan,
brown, salmon, pink</tt>.


