 <b>Vergelijking.</b> (naam: <tt class="wims_code_words">equation</tt>)<br>
 Het antwoord wordt vergeleken met de correcte vergelijking binnen de getalsmatige grenzen en precisie, zoals deze
 zijn aan aangegeven door de schrijver van de oefening.
 
 Het antwoord <tt>a = 0</tt> wordt geinterpreteerd als <tt>a</tt>. 
 Met de optie <tt class="wims_code_words">eqsign=yes</tt> is de student verplicht <tt> a = 0</tt> te noteren. 
