 <b>Wiskundige uitdrukking.</b>(naam: <tt>algexp</tt>, <tt>litexp</tt> en <tt>formal</tt>)<br>
Het leerling antwoord is een wiskundige uitdrukking en zal worden vergeleken met het correcte antwoord
aan de hand van verscheidene kriteria.
<br>Meerdere goede antwoorden kunnen worden gedeklareerd: gescheiden door komma's.
 <p>
 
Bij het type <tt>algexp</tt> (algebra&iuml;sche expressie), 
gelden bijvoorbeeld de volgende beperkingen:<br>
(x+1)(x-1) wordt niet geaccepteerd als goed, als het goede antwoord x^2-1 is.<br>
sin(x)^2+cos(x)^2 wordt niet geaccepteerd als correct, als het goede antwoord 1 is<br>
Wel wordt x-y*y en -y^2+x als gelijkwaardig beschouwd.
<p>

Bij het type <tt>litexp</tt> (letterlijke expressie), 
wordt het leerling antwoord letterlijk vergeleken met het correcte antwoord.
Er wordt geen algebra&iuml;sche "versimpeling" toegepast. Bijvoorbeeld:<br>
3/2 is niet gelijk aan 6/4.<br>
echter 2x en 2*x zijn wel gelijk.<br>
Spaties tellen niet mee bij het vergelijken.
<p>
Bij het type <tt>formal</tt> (formal expression) is geschikt voor het exact numerieke vergelijk.<br>
Dit antwoordtype is gelijk aan <tt>numeric</tt> , met als verschil dat er geen "afrondingen" worden getollereerd.

