
<li><b>Multiple choice variaties</b>: 
<tt>checkbox</tt>,
<tt>click</tt>, 
<tt>menu</tt>, 
<tt>radio</tt>, 
<tt>mark</tt>
<br>
Deze antwoordtypes kunnen worden gebruikt om het standaard multiple choice wat
meer variatie in uiterlijk te geven.<br>
Het goede antwoord moet bestaan uit een tweetal velden, gescheiden door een
``<tt>;</tt>''. 
Het eerste veld is een lijst van de goede antwoorden, 
het tweede veld (na de puntkomma) is de lijst met keuzes.
<p>
In het geval van een <tt>checkbox</tt> moet de leerling alle goede antwoorden aanvinken.
Bij alle andere antwoordtypes is een enkel goed antwoord afdoende.
 <p>
Een andere mogelijkheid in OEF is <tt>shuffle</tt>, welke zorg draagt voor het
 random presenteren aan de leerling van de multiple choices.
 <br>
 Zonder deze optie <tt>shuffle</tt>, wordt dus niet random gepresenteerd en het aantal mogelijke keuzes wordt 
 ook niet automatisch beperkt.
 <p>
 <tt>click</tt> moet alleen gebruikt worden als er geen andere antwoord modellen mogelijk zijn.
 <p>
 <tt>mark</tt> werkt precies als <tt>checkbox</tt>, 
  met als enige verschil dat er geen drukknop wordt gebruikt.
  Het geklikte en gekozen item verandert alleen van kleur.
  Dit antwoordtype kan ingezet worden voor 'inline' gebruik.
