<b>Maak een puzzel van een plaatje</b> (naam: <tt>puzzle</tt>)<br>

<p> 
Het correcte antwoord bevat een tweetal velden, gescheiden door een punt-komma
 ``<tt>;</tt>''.
In't algemeen is het eerste veld bevoeld voor de naam van het plaatje.
Het plaatje dient aanwezig te zijn in een directory, bepaald door de variabele <tt>common_images</tt>), 
het tweede veld <tt>N1 x N2 x W</tt> bepaald dat het plaatje wordt opgedeeld in N1 rijes en N2 kolommen en 
dat de breedte van een puzzel stukje <tt>W</tt> is. 

De grootte van het plaatje (breedte x hoogte) moet worden vermeld in het eerste parameter veld van <tt>\embed</tt> :
<tt>\embed{r1, L x H}</tt>.
</p>
<p>
Het is ook mogelijk van te voren opgeknipte plaatjes te gebruiken.
In dat geval is het tweede veld wederom <tt>N1 x N2 x W</tt>, 
en moet het eerste veld een lijst van adressen van plaatjes zijn, in de volgorde:
eerste rij van links naar rechts, tweede rij van links naar rechts etc.
(dus N1*N2 adressen van plaatjes moet worden vermeld). 
If the field <tt>option</tt>contains the word <tt>text</tt>, it is possible in this case
 to replace all the images by text (without commas or semi-colons).
</p>
<p>
D variabele <tt>reply</tt> i bevat een lijst met 0 en 1, afhankelijk of het puzzel stukje goed of slecht is geplaatst 
</p>
Let op dat er geen identieke plaatjes kunnen worden gebruikt of geknipt !

