
 <b>Ruwe tekst.</b>
 (naam: <tt>raw</tt>)
 <br>
 Het leerling antwoord is een tekst.
Dit wordt vergeleken met het correcte antwoord, onder bepaalde sub-voorwaarden.<br>
Wanneer er geen "option=" is gedeklareerd , geldt de default instelling:
slechts de spaties aan begin en eind van het leerling antwoord worden verwijdert.
<br>
Een leerling antwoord met 1 spatie te veel -ergens in een zin/woord- is dan dus fout !
<br>
Dit antwoord type is vooral geschikt voor auteurs die zelf het leerling antwoord willen vergelijken.<br>  
De volgende opties kunnen worden gedeclareerd:<br>
<ul>
 <li><tt>noaccent</tt>: verwijder accenten van letters.
 <li><tt>nocase</tt>: transformeert het antwoord naar kleine letters.
 <li><tt>nodigit</tt>: vervang de cijfers 1234567890 door spaties.
 <li><tt>nomathop</tt>: vervan wiskunde operatoren */+- door spaties.
 <li><tt>noparentheses</tt>: vervang haakjes door spaties.
 <li><tt>nopunct</tt>: vervang punctuatie door spaties.
 <li><tt>noquote</tt>: vervang aanhalingtekens (enkel en dubbel) door spaties.
 <li><tt>nospace</tt>: verwijder alle spaties.
 <li><tt>reaccent</tt>: sta "escaped" karakters met accenten toe.
 <li><tt>singlespace</tt>: vervang multiple spacties door 1 spatie.
 </ul>

