
 <b>Ruwe tekst.</b>
 (naam: <tt>raw</tt>)
 <br>
 Het leerling antwoord is een tekst.
 Deze wordt vergeleken met het correcte antwoord, onder bepaalde sub-voorwaarden.<br>
 Wanneer er geen "option=" is gedeklareerd , gelden de default instellingen:
 slechts de spaties aan begin en eind van het leerling antwoord worden verwijdert.
<br>
Een leerling antwoord met 1 spatie te veel -ergens in een zin- is dan dus fout !
<br>
Dit antwoord type is vooral geschikt voor auteurs die zelf het leerling antwoord verder willen beoordelen.<br>  
De volgende opties kunnen worden ingezet:<br>
<ul>
 <li><tt>noaccent</tt>: verwijder accenten van letters.
 <li><tt>nocase</tt>: transformeer het antwoord naar kleine letters.
 <li><tt>nodigit</tt>: vervang de cijfers 1234567890 door spaties.
 <li><tt>nomathop</tt>: vervang wiskunde operatoren *,/,+,- door spaties.
 <li><tt>noparentheses</tt>: vervang haakjes door spaties.
 <li><tt>nopunct</tt>: vervang punctuatie door spaties.
 <li><tt>noquote</tt>: vervang aanhalingtekens (enkel en dubbel) door spaties.
 <li><tt>nospace</tt>: verwijder alle spaties.
 <li><tt>reaccent</tt>: sta "escaped" karakters met accenten toe.
 <li><tt>singlespace</tt>: vervang meerdere spaties door 1 spatie.
 </ul>

