 <b>Rangschikken van gegeven objecten.</b>
 (naam: <tt>reorder</tt>)
 <br>
 De leerling moet een lijst gegeven objecten plaatsen in de goede volgorde.
 <br>
 De objecten kunnen zijn: tekst (woorden of groepen woorden), formules geformateerd met \(...) of plaatjes.
Het correcte antwoord is een lijst op gewenste volgorde met deze objecten als items (gescheiden door komma's).
De WIMS server zal deze lijst presenteren als een random gemixte lijst.
 <p>
 Gebaseerd op DynAPI, mogelijk dat sommige browsers dit niet ondersteunen.


