 <b>Eindige Set (letterlijk, formeel en afgerond).</b>
 (namen: <span class="tt wims_code_words">set</span>, <span class="tt wims_code_words">fset</span> and <span class="tt wims_code_words">aset</span>) <br/>
Het goede antwoord is een lijst van elementen, gescheiden door kommas.
De volgorde is onbelangrijk.
 <p>
 
 Bij <span class="tt wims_code_words">set</span>, worden de elementen niet geevalueerd: en dus is "2" niet gelijk aan "1+1"

 <p>
 Bij <span class="tt wims_code_words">fset</span>, worden alle elementen behandeld als
 <em>formele expressies</em>.

 <p>
 Bij <span class="tt wims_code_words">aset</span>, worden alle elementen behandeld als
 <em>approximatieve expressies</em>.

