

 <b>Woorden in een lijst.</b> (naam: <tt>wlist</tt>)<br>
 In dit geval wordt het leerling antwoord woord voor woord vergeleken met het
 goede antwoord. <br>
 De volgorde van de woorden en hoofdletters,accenten enz. zijn niet belangrijk.
 Er wordt alleen gekeken naar de hoofdpunten in deze woorden.
 <p>
Als het eerste woord in het goede antwoord een positieve integer n is,
moet het antwoord van de leerling tenminste n verschillende woorden bevatten die ook in het goede antwoord voorkomen.

 !read help/anstype/syno.phtml badonly

