!if $wimsHttpRequest issametext true
  !changeto msg.phtml
!endif

!set dirjs=scripts/js/laruche

!set wims_html_header=!append line \
    <!-- IMPORT JS :: zTree -->\
    <script type="text/javascript" src="$dirjs/scripts/jquery.ztree.all-3.5.min.js"></script>\
    <!-- IMPORT JS :: onglet-part1.js -->\
    <script type="text/javascript" src="$dirjs/scripts/onglet-part1.js"></script>\
    <!-- IMPORT JS :: JSXGraph.js -->\
    <script type="text/javascript" src="$dirjs/jsxgraph/jsxgraphcore.js"></script>\
    <!-- IMPORT CSS :: reset.css & skeleton1200.css -->\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/reset.css" />\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/skeleton1200.css" />\
    <!-- IMPORT CSS :: quill.css -->\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/quill.base.css"/>\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/quill.css" />\
    <!-- IMPORT CSS :: style.css -->\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/style.css" />\
    <!-- IMPORT CSS :: zTree.css -->\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/zTree/zTreeStyle/zTreeStyle.css">\
    <link rel="stylesheet" type="text/css" href="$dirjs/styles/zTree/zTreeLaRuche.css">\
to $wims_html_header

!header

!! Contenu du module par ici. Ce qui suit est un modele d'organisation de ce
!! fichier.

!if $compute=yes
 !if $error!=$empty
  <div class="wims_alertmsg">
  !read msg.phtml
  </div>
  !read menu.phtml
  !goto end
 !else
  !read answer.phtml
 !endif
!else
 !! put some explanations here.
 !read menu.phtml
!endif compute=yes?


:end

!read footer.phtml

!set wims_menu_items=!append line modtool,1,module=adm/modtool\
  to $wims_menu_items

!tail
