
Si vous êtes un enseignant et si vous voulez utiliser WIMS régulièrement
dans votre enseignement, vous pouvez installer WIMS localement dans votre
institution. Vous aurez ainsi une réponse plus rapide du serveur, et vous
serez à l'abri d'éventuelles interruptions du réseau.
<p>
WIMS est un logiciel sous license GNU. Il peut être 
!href module=adm/light&phtml=download.phtml.$lang téléchargé
 gratuitement
et être installé sur un système d'exploitation Linux.
Veuillez voir le fichier
<a href="./README">README</a>
 pour plus de détails sur comment
installer WIMS.
<p>
Vous pouvez aussi écrire à l'équipe qui maintient le logiciel
(
!mailurl wimsdev@cru.fr wimsdev@cru.fr
) pour des questions sur l'installation de sites miroirs. Veuillez
!href module=adm/light&phtml=mirror.phtml.$lang cliquer ici
 pour une liste de sites miroirs de WIMS accessibles au grand public.
<p>
Par contre, évitez d'utiliser des programmes de robot internet pour
collecter des pages sur ce site&nbsp;! Un site WIMS peut être consulté
uniquement EN LIGNE de façon interactive et les pages collectées par un robot
sont absolument inutiles.

