
WIMS is designed with multi-language support. Several languages are currently
available, including English, French and Chinese.
<p>
Efforts have been made in order to make translation possible even by people
not knowing much of computer programming. But due to the huge amount of
content in the system as well as its constant development, translating WIMS
into a new language means a big amount of work.
<p>
On the other hand, because of the educational vocation of WIMS, translating
it to your native language may represent an important service for the younger
generation of your country.
<p>
If you are interested in translating WIMS into your native language, please
!mailurl wimsdev@cru.fr contact us
. 

<p>
Vous devez d'abord choisir l'extension qui va représenter le langage 
(comme 'en' pour Anglais, 'fr' pour Francais, 'it' pour Italien, etc.)
Il faudra aussi avoir un petit drapeau national pour le représenter.

<p>Il faut aussi choisir le codage des fichiers html et le déclarer dans src/wims.h.
Malheureusement, nous ne gérons pas pour l'instant l'unicode. 
Comme exemple, actuellement, en, fr, es, de, it, nl sont déclarés "iso-8859-1",
si est déclaré "iso-8859-2", ru pourrait être déclarer iso-8859-5. 

<p>
Nous allons appeler la nouvelle langue <tt>xx</tt>.

<p>
Les premiers modules à traduire sont <tt>public_html/modules/home</tt>, 
 <tt>public_html/html</tt> et <tt>public_html/msg</tt>.
Dans chacun de ces modules, il faut créer des fichiers correspondant aux fichiers ayant une extension
<tt>.en</tt> avec l'extension choisie.
Actuellement, il s'agit des fichiers
<pre>
public_html/html/href.xx html/mirrors.xx 
public_html/html/msg.phtml.xx 
public_html/html/name.phtml.xx 
public_html/html/robot.phtml.xx
</pre>
(le dernier doit exister mais n'a pas besoin d'être traduit forcément)
<pre>
public_html/modules/home/front.phtml.xx 
public_html/modules/home/names.xx
</pre>

<pre>public_html/msg/module_error.msg.en
public_html/msg/user_error.phtml.en
public_html/msg/warn_rawmath.phtml.en
public_html/msg/warn_rawmatrix.phtml.en
</pre>
Les dossiers <tt>public_html/modules/template/doc.xx</tt>, <tt>public_html/modules/template/exercise.xx</tt>
<tt>public_html/modules/template/oef.xx</tt>, <tt>public_html/modules/template/tool.xx</tt>,
public_html/modules/classes/xx</tt>
doivent être créés.
<p>

Dans chaque module du répertoire  <tt>public_html/modules/adm</tt>, les fichiers à traduire se
trouvent dans le répertoire lang. Copiez tous les fichiers ayant l'extension <tt>.en</tt>
en leur donnant l'extension <tt>.xx</tt> et traduisez-les. 
Mais, tant que vous ne les avez pas traduits, c'est la version anglaise qui apparaîtra.
Afin de faciliter les modifications éventuelles, ne recopiez le fichier <tt>names.phtml.xx</tt> que
lorsque vous l'avez traduit. Par contre, dès que celui-ci existe, il est nécessaire de créer aussi les
autres fichiers du répertoire <tt>lang</tt> avec l'extension <tt>.xx</tt>.
<pre>public_html/adm/browse
public_html/adm/class/activity
public_html/adm/class/adddoc
public_html/adm/class/addmodule
public_html/adm/class/cdt
public_html/adm/class/classes
public_html/adm/class/config
public_html/adm/class/exam
public_html/adm/class/exolog
public_html/adm/class/gateway
public_html/adm/class/grades
public_html/adm/class/livret
public_html/adm/class/motd
public_html/adm/class/passwd
public_html/adm/class/photoboard
public_html/adm/class/regclass
public_html/adm/class/reguser
public_html/adm/class/sendmail
public_html/adm/class/sequence
public_html/adm/class/sheet
public_html/adm/class/stat
public_html/adm/class/userlist
public_html/adm/createxo
public_html/adm/doc
public_html/adm/forum/forum
public_html/adm/forum/mboard
public_html/adm/forum/regforum
public_html/adm/forum/reguser
public_html/adm/latex2wims
public_html/adm/manage
public_html/adm/modtool
public_html/adm/new
public_html/adm/publish
public_html/adm/quicktool
public_html/adm/sheet
public_html/adm/stat/referer
public_html/adm/stat/stat
public_html/adm/vote
</pre>

Créez aussi les répertoires <pre>
public_html/scripts/oef/xx
public_html/scripts/docu/xx
</pre>
Beaucoup moins essentiels sont les répertoires 
<tt>public_html/scripts/scenario/xx</tt>, <tt>public_html/scripts/scenario/xx</tt>,
<tt>public_html/scripts/dialog/xx</tt> et <tt>public_html/scripts/deduc/xx</tt>.

Voir aussi 
<pre>public_html/scripts/help/xx
public_html/scripts/help/anstype.xx
public_html/scripts/adm/lang/date.phtml.xx
</pre>
qui vous permettront de choisir le format
de la date.

There are also a small number of multi-language files that should be
modified, (but it is not absolutely necessary):

<pre>
modules/home/askcookie.phtml
scripts/about.phtml
scripts/related.phtml
scripts/tool.phtml
</pre>


<p>And apart from the system, you can translate some resource modules that
interest you.

</pre>


