!nocache
!if $error!=$empty
 !read docu/es/msg.phtml
 <p>
 !exit
!endif

<center><h1>$tit</h1></center>

!if $titb=$empty
 <p>
 El bloque <tt>$block</tt> todavía no ha sido creado.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Esta página todavía no está lista para su lectura. ¡Por favor vuelva más tarde!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Esta página ha expirado, ya no le es posible leerla. ¡Lo sentimos!
 <p>
 !exit
!endif

:newblock
<a name=$block></a>
<h3>$titb</h3>

!read $docdir/$doc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $docdir/$doc/$block.def
 <p>
 !goto newblock
!endif

</div><div class=wimstail>
<p><hr>
<table width="100%" border=0 cellspacing=0 cellpadding=1>
<tr><td align=left nowrap><small>
By
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
</small><td align=right><small>
!href cmd=reply&job=read&doc=$doc&block=$startblock Versión interactiva
!if $wims_user=supervisor and $sheetdata!=$empty
 </small><tr><td align=left nowrap>
 <small>Última modificación $datm</small>
 <td align=right><small>
 !href cmd=reply&job=exosource&block=$startblock Fuente de los ejercicios de la página
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>Última modificación $datm</small>
!endif
</table>

