!nocache
<center><h1>$tit</h1></center>

!if $error!=$empty
 !read docu/en/msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 El bloque <tt>$block</tt> no ha sido creado todavía.
 <p>
 !exit
!endif

<h3>$titb</h3>

!read $docdir/$doc/$block.def content

</div><div class=wimstail>
<p><hr>
<table width=100% border=0 cellspan=0 cellpadding=1>
<tr><td align=left nowrap><small>
By
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
<td align=right><small>
!href module=home WIMS
 @
<a href=http://$httpd_HTTP_HOST/>$httpd_HTTP_HOST</a>
<tr><td align=left nowrap>
<small>Última modificación $datm
!if $wims_developer!=$empty and COPYING isin $module_copyright
  !set V_=!char 1 of $module
  !set M_=!translate internal / to , in $module
  !set M_=!item 1 of $M_
  !if $V_ isin ABCDEFGHIJKLMNOPQRSTUVWXYZ of $M_ iswordof local contrib tool
    <td align=right nowrap><small>
    !href module=adm/modtool&original=$module Copiar a Modtool
    </small>
  !endif
!endif
</table>

