!nocache
<center><h1>$tit
</h1></center>

!if $titb=$empty
 <p>
 El bloque <tt>$titb</tt> de este documento no ha sido creado todavía.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Este bloque no está listo para su lectura aún. ¡Vuelva más tarde!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Este bloque ha expirado, ya no se encuentra disponible. ¡Lo sentimos!
 <p>
 !exit
!endif

<h3>$titb (Fuente del documento)
</b><font size=-1>
 [
 !href cmd=reply&job=read Formateado
 ]</font>
</h3>

<pre wrap>
!mexec scripts/cat.sh $module_dir/$docdir/$doc/src/$block
</pre>

<p><hr>
!if $wims_class!=$empty and $wims_user!=supervisor
 !exit
!endif
<table width="100%" border=0>
<tr><td align=left><small>
!href cmd=reply&job=read Formateado
&nbsp; by
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
!if help notin $wims_session
 <td align=right><small>
 !href module=home WIMS
  @
 <a href=http://$httpd_HTTP_HOST/>$httpd_HTTP_HOST</a>
!endif
<tr><td align=left colspan=2 nowrap>
<small>Última modificación $datm
</table>

