
WIMS est un système ouvert, qui est libre d'utilisation par tous et qui
accepte les contributions de tous. Il est mon souhait que des contributions venant
d'utilisateurs enrichissent considérablement le système et à la fin l'aident
à devenir un outil important pour la communauté mathématique.
<p>
En utilisant WIMS d'une manière avancée comme ci-dessous, vous rendez
service à vous-même et en même temps au développement du
système (donc aux autres).

