
!for chapter=1 to $chaptercnt
 !set a=!line 1 of $(chapter$chapter)
 <h2>
 !word $chapter of I. II. III. IV. V. VI. VII. VIII. IX. X.
 $a </h2>
 !read chapter$chapter.phtml
!if $chapter!=2
 <ol>
 !set n=!linecnt $(chapter$chapter)
 !for i=2 to $n
  !set l=!line $i of $(chapter$chapter)
  !set t=!item 1 of $l
  !set s=!item 2 to -1 of $l
  <li id="$t"><strong>$s</strong>
  !read $chapter/$t.phtml
  </li>
 !next i
 </ol>
!endif
!next chapter

!tail
!reset style

