
<center>$classname
<p>
<h1>$user_lastname $user_firstname的考试详情
</font>
</h1></center>

!if _check isin $session
 !set error=bad_op
 !goto msg
!endif

!if $error!=$empty
 :msg
 <p>
 !read msg.phtml
 <p>
!else
 !if $checksessions=$empty
此参加者没有参加任何考试.
  <p>
 !else
这里是此参加者的考试对话. 在练习上点击以看它的内容.
  <p>
  $table_header
  $table_hdtr<th>会话</th><th>考试</th><th>得分<small>/10</small></th>
  <th>练习</th><th>开始</th></tr>
  !for ses in $checksessions
   !for x in $(exam$ses)
    $table_tr<td><small>$ses</small></td>
    <td align=center>$x</td>
    <td align=center>$(score$(ses)$x)</td><td>
    !for i in $(exo$(ses)$x)
     &nbsp;
     !href target=wims_check module=$module&cmd=new&job=examcheck&checkuser=$checkuser&checksession=$ses&checkexo=$x.$i&checkstep=1 $i
    !next i
   !next x
   </td><td><small>$(start$(ses)$x)</small></td>
  !next t
  $table_end <p>
 !endif
!endif

<center>
!href cmd=reply&job=getuser&getuser=$checkuser 其它得分
&nbsp;
!href cmd=resume 参加者表
</center>

