#! /bin/sh
#
#	This script indexes shtooka resources which are in data/shtooka directories
#	It should be run each time a shtooka package is added or modified.
# use index.xml in the future
# Bernadette Perrin-Riou
cd `dirname $0`
file=index.xml;
#
list=`ls -d */$file | sort` ;
for i in $list ; do
   i=`dirname $i`
   echo "reading $file : $i" ;
   cd $i ; ../swac.pl --prefix=$i;
   cd .. ; 
done;
list_lang=`grep --no-filename swac_lang= $list | sed 's/^.*=//' | sed 's/\"//g' | sort -u`;

for j in $list_lang ; do 
   echo "index $j" ; 
   ./swac.pl --lang=$j;
done;
