
Voici les paramètres de ce forum que vous pouvez changer.

!form reply
<input type=hidden name=job value=config>
<input type=hidden name=cf_set value=yes>
<ul>
<li><p>Titre du forum&nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <li><p>$wims_name_Description:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea>
 <li><p>Qui peut lire les messages&nbsp;?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_readpolicy list alluser,owner prompt \
	tout participant, seulement vous-même
 !else
  !formselect cf_readpolicy list open,alluser,owner prompt \
	tout le monde (inscrits ou non), utilisateurs inscrits seulement,\
	personne à part vous
 !endif
 <li><p>Qui peut envoyer des messages dans le forum&nbsp;?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_sendpolicy list alluser,mailuser,owner prompt \
	tout participant,\
	participants avec vérification d'email,\
	seulement vous-même
 !else
  !formselect cf_sendpolicy list mail,alluser,mailuser,owner prompt \
	visiteurs avec adresse email ou inscrits,\
	utilisateurs inscrits seulement,\
	inscrits avec vérification d'email,\
	personne à part vous
 !endif
</ul>
<p><center><input type=submit name=cf_set value="$wims_name_tosave">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="$wims_name_giveup">
</center> <p></form>

