
!if $s_status=ask
 Ce forum n'accepte pas les messages anonymes. Il utilise votre adresse
 électronique actuelle pour garder votre identité, dans un but d'éviter des
 abus.
 <p>
 Afin de vérifier la validité de votre adresse électronique, le serveur vous
 a envoyé un code secret par email. Veuillez lire ce mail, et copier ce code
 ici&nbsp;:
 !form reply
 <input type=hidden name=job value=send>
 <p><center><input size=10 name=s_code>
 <input type=submit value=OK></form>
 <p>
 !href cmd=reply&job=list Abandonner l'opération
 </center> <p>
 !exit
!endif

!if $error=$empty
 Votre message a été ajouté à ce forum.
!endif

<p><center>
!href cmd=reply&job=list Liste de messages
</center> <p>
