
<b>画直线、多边形、点、线段、向量、矩形.</b>
(名称: <tt>javacurve</tt>)
<br>
这种回答类型允许用户在一个图形上画直线、多边形、线段、向量、矩形
或点.

<p>
标准答案用矩阵形式给出 (行分隔符是分号 `;').
第一行是图形的 URL(所在地址).
第二行是对用户图形的测试条件, 见下表:

!set p=anstype.$lang/javacurve
!readproc tabletheme
$table_header
!set caption=!record 1 of help/$p
  <caption>$caption</caption>
  !set header=!record 2 of help/$p
  $table_tr<th>$(header[1])</th><th>$(header[2])</th></tr>
  !set cnt_record=!recordcnt help/$p
  !for u= 3 to $cnt_record
    !set l_=!record $u of help/$p
    $table_tr<td><tt>
!line 1 of $l_
    </tt></td><td>
!line 2 to -1 of $l_
   </td>
  !next
$table_end

<p>
建议把输入栏嵌入陈述中. 它不能与其它输入栏共存.

</p>
一般说来, 变量
<tt>\reply</tt><em>n</em> 被用于 \feedback 记录了回答时的点击 (x1,...),
其中 <em>n</em> 是输入栏的号码.
不过以下情形是例外:
<ul><li>
在 <tt>points</tt> 的情形,
第一行是点击坐标(以点素pixel为单位)的表,
第二行是 <tt>n1,n2,n3</tt>, 其中
<tt>n1</tt> 正确点的个数, <tt>n2</tt> 是散失点的个数,
<tt>n3</tt> 是错误点的个数. 第三行是找对的点的个数表.
</li><li>
在 <tt>circle</tt> 的情形, 第一行是点击坐标以及半径的表,
第二行是 <tt>n1,n2</tt>, 
当中心正确时 <tt>n1</tt> 取 1, 否则取 0,
当半径正确时 <tt>n2</tt> 取 1, 否则取 0.
</li>
<li>
在 <tt>sline</tt> 的情形, 第一行是点击坐标表,
第二行是 <tt>n1,n2,n3</tt>, 
当起点正确时 <tt>n1</tt> 取 1, 否则取 0,
当斜率正确时 <tt>n2</tt> 取 1, 否则取 0,
当指向正确时 <tt>n3</tt> 取 1, 否则取 0.
</li>
</ul>
