 <b>矩阵.</b> (名称: <span class="tt">matrix</span>)<br/>
 和向量回答一样, 每个元素求值后与正确答案的对应元素比较.

 <p>
 Three option words are available:
 <span class="tt wims_code_words">split_coeff</span>,
 <span class="tt wims_code_words">split_row</span>,
 <span class="tt wims_code_words">split_column</span>.
 The answer is partially good if a percentage (50 %) of good coefficients 
 or rows or columns is correct.
 </p><p>
 If <span class="tt wims_code_words">n</span> is the number of the question,
 the variables <span class="tt wims_code_words">result</span>n contains
 a matrix with 1 and 0 according to the position of the good and bad 
 coefficients (or 0.5 if the precision is not sufficient).
</p>
