 <b>数.</b> (名称: <tt>numeric</tt>)<br>
实数间的比较, 精确到作者设定的精度.
 
如果选项中含有 <tt class="wims_code_words">comma</tt>, 那么表示实数的时候可以使用逗号作为小数点
(但正确的回答必须使用小数点). 
在这种情形当回答出错时, 
正确答案将使用与学生相同的 "小数点".

精度由 <tt class="wims_code_words">precision</tt> 栏确定, 默认值是 1000.

判定是否正确的标准是相对的 : 其相差必须小于
<tt>(good_answer+reply)/precision</tt> 
(在判定部分正确的回答时把 <tt>precision</tt> 放松为 <tt>sqrt(precision)</tt> ). 

如果选项中含有 <tt class="wims_code_words">absolute</tt> , 那么精度就是绝对的.
当相差小于 10/precision 时判为部分正确的回答.