

 <b>纯文本.</b>
 (名称: <tt>raw</tt>)
 <br>
用于与正确答案比较的文本. 下面的选项决定了在进行比较前需要作怎样的变换.
如果没有给出选项, 则只除去首尾的空格. 使用这个格式要小心, 在默认情形,
多一个空格就被认为不同的! 这主要用于作者手工打分.
 <p>
 选项: <ul>
 <li><tt>noaccent</tt>: 除去字母的重音号.
 <li><tt>nocase</tt>: 全部转化成小写字母.
 <li><tt>nodigit</tt>: 把数字用空格代替.
 <li><tt>nomathop</tt>: 把数学符号用空格代替.
 <li><tt>noparentheses</tt>: 把括号用空格代替.
 <li><tt>nopunct</tt>: 把标点用空格代替.
 <li><tt>noquote</tt>: 把引号(单或双)用空格代替.
 <li><tt>nospace</tt>: 除去所有空格(包括其它字符转换过来的空格).
 <li><tt>reaccent</tt>: 允许 escaped 重音字母.
 <li><tt>singlespace</tt>: 把连续的空格看作一个空格.
 </ul>

