
!if $prelogcnt<1
 Non ci sono esercizi salvabili.
 !exit
!endif

Esercizi del test di autovalutazione $logsheet la cui risoluzione può essere salvata:

!read tabletheme

<p>$table_header
$table_hdtr
<th><small>Numero</small></th>
<th><small>Passaggi</small></th>
<th>Punteggio</th>
<th></th>
<th>Titolo esercizio</th></tr>
!for i=1 to $prelogcnt
 !set l=!word $i of $prelog3
 !set e=!item -1 of $l
 !set c=!recordcnt wimshome/$wims_sesdir/exolog.$logsheet.$e
 !set s=!getdef w_module_score in wimshome/$wims_sesdir/exolog.$logsheet.$e
 !default s=-
 !set V_=!record $e of wimshome/log/classes/$wims_class/sheets/.sheet$logsheet
 !distribute lines $V_ into a,a,a,a,T_,D_
 $table_tr<td align=center>$e</td>
 <td align=center>$c</td>
 <td align=center>$s</td>
 <td><small>
 !href cmd=reply&job=log&logsheet=$logsheet&logexo=$e&checkuser=$wims_user Salva dettagli
 </small></td>
 <td>$T_ <small>$D_</small></td>
 </tr>
!next i
$table_end
<p>

