!set wims_module_log=$operation error: $error

<b>Error.</b>
!goto $error

:bad_formula
 Your data contain errors or are incompatible with the operation
 <em>$operation</em>. Please verify your request.
!goto end

:bad_option
 Your request option is not valid. Please verify it.
!goto end

:bad_range
 Your variable ranges are not valid. Please correct them.
!goto end

:empty_data
 Please complete data for your computation request.
!goto end

:fail
 Sorry, Wcalc is unable to complete your requested computation. Please verify 
 your data.
!goto end

:incompatible_sides
 There is no triangle with three sides $formula.
!goto end

:not_square_matrix
 Please enter a square matrix for the computation of
 <font color=red><b>$operation</b></font>.
!goto end 

:solve_fail
 No solution has been found.
!goto end

:unknown_operation
 The operation <font color=red><b>$operation</b></font> is not (yet)
 understood by this calculator. Sorry.
!goto end

:end

