
!read adm/title.phtml 3\
\
Configuration de l'accès aux ressources

!form reply
<input type=hidden name=job value=access>
<center>Définition de l'accès aux ressources : 
!href cmd=help&special_parm=accessconf [$wims_name_help]
<br>
<textarea name=accessdef cols=70 rows=15>$accessdef</textarea>
<p>
<input type=submit name=save value="$wims_name_tosave">
<input type=submit name=abandon value="$wims_name_giveup">
</center>
</form>

!reset job, accessdef

