
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>
 
!set months=Gen,Feb,Mar,Abr,Mai,Jun,Jul,Ago,Set,Oct,Nov,Des

!set title=Configuració i Manteniment
!if $job=arch
 !set title=Còpia de seguretat i Restauració
!endif

!if $job=clean
 !set title=Manteniment de la classe
!endif

!if $job=neighbor
 !set title=Classes veïnes
!endif

!if $job=connect
 !set title=Connectar a altres servidors / plataformes
!endif

!distribute line Autentificació\
Preferències\
Restriccions d'accés\
Configuració OEF\
Classes veïnes\
Gestió de seguretat\
Manteniment\
Actualitzar\
Altres servidors\
Contrasenyes\
Enviar les configuracions a les subclasses\
Aspecte\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present

!distribute items subclasses,participants,exercicis,documents,professors\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers
