
Activités de gestion de sécurité disponibles&nbsp;:

<ul>
<p><li>
!href module=adm/class/passwd.$module_language Changer vos mots de passe
.

<p><li>
!href cmd=renew&job=log Voir l'enregistrement
 d'activité de gestion de votre classe. (Vous devez être l'origine de toutes
ces activités&nbsp;; si ce n'est pas le cas, il faut vérifier s'il n'y a pas une
fuite de votre mot de passe d'enseignant.)

<p><li>Configurer la
!href cmd=reply&job=grestrict restriction par classe
 des sites ayant accès aux scores.

<p><li>Autres définitions de sécurité dans 
!href cmd=renew&job=list la configuration de la classe
.

</ul>

