!set wims_module_log=ERROR $error

<b>Erreur</b>.

!if $error=bad_password
 Mot de passe non reconnu. Veuillez réessayer après quelques secondes.
 <form action=# name=chrono>
 <b><blink>Attention</blink></b> ! Tout mot de passe envoyé dans les 5 secondes
 qui suivent sera rejeté&nbsp;!
 <input size=1 name=clock> </form>
 !exit
!endif

!if $error=in_exam
 Vous ne pouvez pas changer de classe quand vous êtes en train de passer
 un examen.
 !exit
!endif

!if $error=recent_rafale
 Ce compte est bloqué pendant 10 minutes à cause d'activités irrégulières.
 !exit
!endif

!msg $error

