!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=groupement de classes
    !set name_sup=administrateur
    !set name_classes= le $name_classe
    !set name_classesss= du $name_classe
    !set name_classessss= Le $name_classe
   !else
    !set name_classe=établissement
    !set name_sup=administrateur
    !set name_classes= l'$name_classe
    !set name_classesss= de l'$name_classe
    !set name_classessss= L'$name_classe
   !endif
   !set name_classess= un $name_classe
 !else
   !set name_classe=classe
   !set name_classes=la $name_classe
   !set name_classess=une $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=enseignant
 !endif
 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of classe,cours
   !set Name_level= !item $splevel of Niveau,Classe,Cours
   !set Name_levels= !item $splevel of Niveaux,Classes,Cours
   !set sousclasses_else=!item $splevel of ou une classe, ou un cours
   !set name_level_else= !item $splevel of un niveau,une classe,un cours
 !else
   !set sousclasses=sous-classes
   !set sousclasses_else=une classe ou un établissement
 !endif
 


