
!if $overflow=yes
 !if $keyword = $empty
  Il y a beaucoup de classes virtuelles sur ce site. Pour retrouver la vôtre,
  tapez une partie d'un mot se trouvant dans son titre ou dans le nom de l'enseignant.
 !else
  Il y a encore trop de classes correspondant à votre mot de recherche. Veuillez
  donner un mot plus précis.
 !endif
 <p><center>
 !form reply
 <input size=20 name=keyword value="$keyword">
 <input type=submit value=OK>
 </form></center> <p>
!else
 !if ($sccnt + $clcnt > 20 and $wims_user = $empty) or $keyword!=$empty
  !form reply
  Rechercher votre classe :
  <input size=20 name=keyword value="$keyword">
  <input type=submit value=OK>
  </form>
 !endif
!endif

