
!read adm/css.phtml
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname
!set module_title_lang=!module title_$lang
!default module_title_lang=$module_title

!!read js/speckedit.phtml name_deposit
!header1
!set name_userlist=$(wims_name_part_list)

!read adm/title.phtml 1\
$classname\
$(name_$job)\
$(module_title_lang)


<div class="wims_content">

!if $error!=$empty
 <div class="wims_msg alert">
   !read lang/msg.phtml.$moduclass_lang
 </div>
!endif

!if $msg_info!=$empty
 <div class="wims_msg info">
   !set error=$msg_info
   !read lang/msg.phtml.$moduclass_lang
 </div>
!endif
!if $job!=$empty
 !read $job.phtml
!endif

!set wims_menu_items=$empty
!if $job=userprop
!!classe, student login, job, name of the variable used for the login
  !read adm/class/getnextuser $wims_class,$user,userprop,user
!endif
!if $job!=userlist
 !set wims_menu_items=!append line part_list,1,cmd=reply&job=userlist\
to $wims_menu_items
!endif
!if $job!=addvar or $job!=oldvar or $job!=listvar
 !set wims_menu_items=!append line itemsep,0, to $wims_menu_items
!endif
!if $job!=listvar
!!ARIANE already in ariane thread
    !set wims_menu_items=!append line listvar,1,cmd=reply&job=listvar to $wims_menu_items
!endif
!if $job!=addvar
  !set wims_menu_items=!append line add_techvar,1,cmd=reply&job=addvar to $wims_menu_items
!endif
!if $job!=oldvar and $version_class < 5
 !set wims_menu_items=!append line oldvar,1,cmd=reply&job=oldvar to $wims_menu_items
!endif
</div>
!tail
!reset job
