
!read adm/css.phtml
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!!read js/speckedit.phtml name_deposit
!header1

!read adm/title.phtml 1\
$classname\
$name_title

<div class="wimsalertmsg"> WARNING : work in progress. (job : $job)
!!<br/>
!!listname : $tv_listname<br/>
!!indexlocal : $tv_listlocal<br/>
!!listallname : $tv_listallname<br/>
!!varfilter : $varfilter <br/>
!!varfilter_ : $varfilter_ <br/>
!!tc_listtechvar : $tv_listtechvar
</div>
<div class="wims_content">
!if $error!=$empty
 <div class="wims_alertmsg">
   !read lang/msg.phtml.$moduclass_lang
 </div>
!endif

!if $job!=$empty
 !read $job.phtml
!endif

!set wims_menu_items=$empty
!if $job!=listvar
 !if $job!=userprop
     !set wims_menu_items=!append line back2 ARIANE,1,cmd=reply to $wims_menu_items
 !else
     !set wims_menu_items=!append line back2,1,cmd=reply&job=userlist to $wims_menu_items
 !endif
!endif

!if $job!=userlist
 !set wims_menu_items=!append line part_list,1,cmd=reply&job=userlist\
 itemsep, 0, to $wims_menu_items
!endif

!if $job!=addvar
  !set wims_menu_items=!append line add_techvar,1,cmd=reply&job=addvar to $wims_menu_items
!endif
!if $job!=oldvar
 !set wims_menu_items=!append line oldvar,1,cmd=reply&job=oldvar to $wims_menu_items
!endif
</div>
!tail
!reset job
