<div class="wims_content">
  !form reply
  <input type="hidden" name="job" value="modifvar" />
  <fieldset class="property_fields halfwidth blockcenter">
      <legend>$name_modiftechvar</legend>
      <div class="field box">
       <label for="tc_name">$name_name</label><br/>
       <input size="10" name="tc_name" value="$tc_name" id="tc_name" />
      </div>
      <div class="field box">
       <label for="tc_val">$name_ltvalue</label>
       <input size="60" name="tc_value" value="$tc_value" id="tc_value" />
      </div>

  <div class="wimscenter wimsform">
    <input type="submit" name="tc_set" value="$wims_name_tosave" />
 $
    <input type="submit" name="tc_abandon" value="$wims_name_giveup" class="wims_secondary_button" />
   </div>
  </fieldset>
  !formend
</div>
