!read names.phtml
!form reply
 !set s_day=$name_day
 !set s_week=$name_week
 !set s_month=$name_month
 !set s_year=$name_year
 !read adm/date.phtml date,$start_year,$start_month,$start_day
 !set s_beginning=$name_beginning $c_date_out
 !set name2=$name_requests
 !set name3=$name_sessions
 !set name4=$name_visitors
$name_choose
 <select name=cnt>
 !for i=1 to 15
  <option value=$i
  !if $i=$cnt
   selected
  !endif
  >$i
 !next i
 </select><select name=style>
 !for i in day,week,month,year,beginning
  <option value=$i
  !if $i=$style or ($i=week and $style=$empty)
   selected
  !endif
  >$(s_$i)
 !next i
 </select>. <p>
 $name_plot
 !for i=2 to 4
  <input type=radio name=plot_type value=$i
  !if $i=$plot_type
   checked
  !endif
  >$(name$i) &nbsp;
 !next i
 <p>
 <input type=checkbox name=modules value=yes
 !if $modules=yes
  checked
 !endif
 >$name_details.
 <p>
 <center><input type=submit value="$name_showstat"></center>
</form>

!set modules=