
!if $error!=$empty
 !exit
!endif

!if $no_selection!=$empty
 <b>Attention</b>. Aucune ressource à restaurer n'est sélectionnée.
 <p>
!endif

!if $serial!=$wims_class and $old_testcnt>0
 !set test=bad
!endif
!if $test=bad
 <font color=red><b>AVERTISSEMENT!!!</b></font>
 Vous avez envoyé des ressources sauvegardées à partir d'une autre classe.
 Si vous restaurez des ressources incompatibles avec votre classe, elle va
 être simplement détruite.
 !href cmd=help&special_parm=dependencies Pourquoi&nbsp;?
 <p>
 !href cmd=reply&job=list Arrêtez
 si vous n'êtes pas complètement sûr de ce que vous faites. (Dans tous les
 cas, gardez une sauvegarde de l'état actuel avant de continuer.)
 <p><hr> <p> 
!endif

!set no_restore=Impossible de restaurer car vous partagez les ressources d'une autre\
	classe. La restauration ne peut être faite que par la classe maître du partage.
!form reply
<input type=hidden name=job value=$job>
<input type=hidden name=job2 value=restore>
Votre fichier de sauvegarde <tt>$wims_deposit</tt> contient les ressources
suivantes. Marquez ce que vous voulez restaurer dans votre classe.
<ul>
 <li><input type=checkbox name=selection value=all>
 Restaurer tout sauf la configuration de la classe et le compte d'enseignant.
!if $new_defcnt>0
 <li><input type=checkbox name=selection value=def>
 Configuration de la classe.
 <font color=red>Danger!</font> <small>Voir ci-dessous.</small>
!endif
!if $new_supcnt>0
 <li>
 !if $sharing_sup=$empty
  <input type=checkbox name=selection value=sup>
 !endif
 Compte d'enseignant (y compris votre mot de passe).
 !if $sharing_sup!=$empty
  $no_restore
 !else
  <font color=red>Danger!</font> <small>Voir ci-dessous.</small>
 !endif
!endif
!if $new_usercnt>0
 <li>
 !if $sharing_user=$empty
  <input type=checkbox name=selection value=user>
 !endif
 $new_usercnt comptes de participants.
 !if $sharing_user!=$empty
  $no_restore
 !else
  <small>(Comptes existants&nbsp;: $old_usercnt.)</small>
 !endif
 </li>
!endif
!if $new_doccnt>0
 <li>
 !if $sharing_doc=$empty
  <input type=checkbox name=selection value=doc>
 !endif
 $new_doccnt documents. 
 !if $sharing_doc!=$empty
  $no_restore
 !else
  <small>(Documents existants&nbsp;: $old_doccnt.)</small>
 !endif
 </li>
!endif
!if $new_exocnt>0
 <li>
 !if $sharing_exo=$empty
  <input type=checkbox name=selection value=exo>
 !endif
 $new_exocnt exercices.
 !if $sharing_exo!=$empty
  $no_restore
 !else
  <small>(Exercices existants: $old_exocnt.)</small>
 !endif
 </li>
!endif
!if $new_sheetcnt>0
 <li>
 !if $sharing_sheet=$empty
  <input type=checkbox name=selection value=sheet>
 !endif
 $new_sheetcnt feuilles de travail.
 !if $sharing_sheet!=$empty
  $no_restore
 !else
  Implique la restauration des exercices.
  <small>(Feuilles existantes: $old_sheetcnt.)</small>
 !endif
 </li>
!endif
!if $new_examcnt>0
 <li>
 !if $sharing_exam=$empty
  <input type=checkbox name=selection value=exam>
 !endif
 $new_examcnt feuilles d'examen.
 !if $sharing_exam!=$empty
  $no_restore
 !else
  Implique la restauration de feuilles de travail et d'exercices.
  <small>(Examens existants: $old_examcnt.)</small>
 !endif
 </li>
!endif
!if $new_forumcnt>0
 <li>
 !if $sharing_forum=$empty
  <input type=checkbox name=selection value=forum>
 !endif
 $new_forumcnt messages de discussion.
 !if $sharing_forum!=$empty
  $no_restore
 !else
  <small>(Messages existants: $old_forumcnt.)</small>
 !endif
 </li>
!endif
!if $new_scorecnt>0
 <li><input type=checkbox name=selection value=score>
 Registre d'activités de participants et scores automatiques. Implique la
 restauration de comptes de participants.
 </li>
!endif
!if $new_manualcnt>0
 <li><input type=checkbox name=selection value=manual>
 $new_manualcnt Notes entrées par l'enseignant. <small>(Notes existantes&nbsp;:
 $old_manualcnt.)</small>
 </li>
!endif
</ul>
Méthode de restauration&nbsp;:<ul>
<li><input type=radio name=restore value=replace checked>
 Remplacement&nbsp;: remplacer les ressources existantes par les ressources restaurées.</li>
<li><input type=radio name=restore value=merge>
 Fusion&nbsp;: remplacer les ressources existantes excepté les comptes de
 participants et les exercices de la classe. Pour ces derniers, ceux ayant
 mêmes noms seront remplacés par les données restaurées et les autres seront
 gardés.</li>
</ul>
<input type=submit value="Restaurer les ressources sélectionnées">
!href cmd=reply&job=list Abandonner la restauration
.
</form>

<p><b>IMPORTANT</b>. 1. Il n'y a pas de vérification des données que vous avez
envoyées et le système n'autorise pas la modification manuelle des archives
de sauvegarde. Les erreurs introduites par une modification manuelle des
archives peuvent entraîner des comportements imprévisibles de votre classe.
<p>
2. Sauf dans des cas d'absolue nécessité, évitez de restaurer
<font color=red>la configuration de la classe</font> et
<font color=red>le compte d'enseignant</font>.
Les erreurs dans les données envoyées pour ces deux champs peuvent vous faire
perdre complètement le contrôle de votre classe.
<p>
3. Vous pouvez utiliser la sauvegarde d'une classe pour en installer une
nouvelle. Dans ce cas, évitez de restaurer les registres d'activités et les
notes (manuelles et automatiques). Ces deux types de ressources ne peuvent
pas être effacés une fois installés (mesure de sécurité). Et beaucoup
d'opérations de maintenance de la classe sont impossibles quand la
classe contient des notes.

