!! This file can contain contents which go to the end of the page.

!if $wims_exec_error!=$empty
<small><pre>*******************************************************
$wims_exec_error
*******************************************************</pre></small>
!reset wims_exec_error
!endif

<p><center>
!href cmd=resume&realtest=no Terug
 naar de Createxo startpagina.
!if $mode=model
&nbsp;Hier staat een
 !href cmd=reply&level=1&mode=model Lijst
  met voorbeeld oefeningen.
!endif
</center> <p>
