
!if $realtest=yes
 !changeto oef/help.phtml
!endif

!set helplist=oef,examples,format,parameters,oefparm,reply,embedans,\
	feedback,math,draw,draw_example,oefadv,if,symtext,model,slib

!set s_=!item 1 of $special_parm
!if $s_=all
 !for sj in $helplist
  <p>
  !read help/$sj.phtml
 !next sj
 !exit
!endif
!if $s_!=$empty and $s_ isitemof $helplist
 !read help/$s_.phtml
 !!<p><center>
!! !href cmd=help Andere help onderwerpen.
 !!&nbsp;&nbsp;
!! !href cmd=resume Terug 
!! naar het werk
!!. </center>
!set wims_menu_tail=!append line back2,1,cmd=help\
 to $wims_menu_tail
 !exit
!endif

Help onderwerpen:<ul>
<li><p>
!href cmd=help&special_parm=oef Uitleg over het OEF bestandsformaat.
!!<li><p>
!!href cmd=help&special_parm=examples Examples of exercises.
</p></li><li><p>
!href cmd=help&special_parm=format Beschrijving van het "statement"
 van OEF.
</p></li><li><p>
!href cmd=help&special_parm=parameters Random parameters
 in interactieve oefeningen.
</p></li><li><p>
!href cmd=help&special_parm=math Wiskundige formules
 in oefeningen.
</p></li><li><p>Het invoegen van
!href cmd=help&special_parm=draw dynamische gegenereerde plaatjes
 in de oefeningen.
</p></li><li><p>Op welke manieren kan de gebruiker/leerling
!href cmd=help&special_parm=reply antwoord geven op een 
interactieve vraag?
</p></li><li><p>Hoe geef ik interactieve
!href cmd=help&special_parm=feedback feedbacks
 op de antwoorden.
</p></li><li><p>
!href cmd=help&special_parm=oefadv speciale effecten
.
<li><p>
!href cmd=help&special_parm=slib&slib_cmd=help Library of scripts
 (slib).
</p></li><li><p>Geef me
!href cmd=help&special_parm=all alle 
help paginas
</p></li>
</ul>

!!!if $modtoolhelp!=yes
!!<center>
!!!href cmd=resume Terug 
!!naar het werk.
!!</center>
!!!endif

