
!form reply
<input type=hidden name=level value=2>
De titel van de nieuwe oefening:<br>
<input size=40 maxlength=40 name=oef_title value="$oef_title"> <p>
Het statement wordt geschreven in:
!formselect oef_format list tex,html
 [
 !href target=wims_mhelp cmd=help&special_parm=format help
 ]<p>
 Deze oefening heeft
!formselect oef_answercnt from 0 to 10
open antwoorden en<br>
!formselect oef_choicecnt from 0 to 10
multiple-choice antwoorden.
<br>Antwoorden zoals <tt>3*5-sin(pi/3)</tt> worden
!formselect oef_computeanswer list yes,no prompt geaccepteerd,niet geaccepteerd
.<br>
!formselect oef_condcnt from 0 to $condlim
 testcondities worden gebruikt voor het beoordelen van de open antwoorden.
 [
 !href target=wims_mhelp cmd=help&special_parm=reply help
 ]
<p><table border=0><tr><td align=right>
Naam van de auteur:<td><input size=30 maxlength=60 name=oef_author value="$oef_author">
<tr><td align=right>
Emailadres:<td><input size=30 maxlength=80 name=oef_email value="$oef_email">
</table>
<p><center>
<input type=submit value="OK en ga verder">
</center>
</form>

!if $wims_user=supervisor
 !read wimshome/log/classes/$wims_class/Exindex
 !if $exototal>0
 <p>
 !form new
 <input type=hidden name=module value=$module>
 Verander een bestaande oefening uit mijn klas:
 !formselect existing list $exolist prompt $titlelist
 <input type=submit value=OK></form>
 !endif
!endif

