
De software heeft uw oefening zonder problemen gecompileerd.<br>
Hieronder staat een samenvatting (s.v.p. controleren)
<table bgcolor="#d0d0d0">
<tr><td align=right>Titel<td><td>$title
<tr><td align=right>Aantal parameters<td><td>$varcnt
<tr><td align=right>Aantal open antwoorden<td><td>$replycnt
<tr><td align=right>Aantal meerkeuzevragen<td><td>$choicecnt
</table>
<ul><li>
Klik 
!href cmd=resume&realtest=yes&retest=again hier
 om deze oefening uit te testen.
!if $mode!=file
    <li><p>
	Als u deze oefening nog wilt veranderen, ga dan 
!!!!!!!!!!!!! début de modifs JY pour le module confia2qcm !!!!!!!!!!!!!
	!if $to_ia_qcm=-1
	    !href module=adm/auth/confia2qcm&cmd=new&chexo=2&exo=1&to_ia_qcm=1 terug naar confia2qcm
	!endif
	!if $to_ia_qcm=-2
	    !href module=adm/auth/createqcm&cmd=new&chexo=2&exo=1&to_ia_qcm=2 terug naar 2createqcm
	!endif
	!if ($to_ia_qcm!=-2 and $to_ia_qcm!=-1)
	    !href cmd=reply&level=2 terug naar het menu
	!endif
!!!!!!!!!!!!! fin de modifs JY pour le module confia2qcm !!!!!!!!!!!!!              
.
!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=level value=3>
 <li><p>
 Of verander de de broncode en stuur deze
 <input type=submit value="opnieuw naar de server">:
 <input type=file name=wims_deposit>
 </form>  
 <li><p>
 Terug naar het
 !href cmd=reply&level=1&mode=normal startmenu
.
!endif
!if $wims_user!=$empty
 <li><p>
 Het is natuurlijk ook mogelijk een 
 !href cmd=reply&level=6 plaatje
 in te binden.
 !set wims_menu_items=!append line downloadbinary,1,cmd=reply&level=6\
 to $wims_menu_items
!endif
!if $wims_user!=$empty or $existing!=$empty
  !if $success!=1 and $regout!=fail
 <li><p>
 Wanneer alles inorde is, kunt u
 !if $existing!=$empty
  !if ..devel/ notin ..$catmodule
   deze oefening toevoegen aan uw klas, of als 
   !href cmd=reply&level=4 vervanging
   van een reeds bestaande oefening,<br>
   of als een
   !href cmd=reply&level=4&newone=1 nieuwe oefening
   !set wims_menu_items=!append line replace,1,cmd=reply&level=4\
  newversion,1,cmd=reply&level=4&newone=1\
    to $wims_menu_items
  !else
  deze module toevoegen aan uw "werk in uitvoering" 
   !href cmd=reply&level=4 modules
   !set wims_menu_items=!append line putclass,1,cmd=reply&level=4\
   to $wims_menu_items
  !endif
 !else
    deze module 
  !href cmd=reply&level=4 toevoegen
   aan uw klas
   !set wims_menu_items=!append line putclass,1,cmd=reply&level=4\
   to $wims_menu_items
 !endif
.
 !endif
 !reset success
!endif
!if $mode!=file
 <li><p>
 Als laatste: vergeet niet de
 !getfile submit.oef broncode
 van deze oefening te bewaren op uw eigen computer !
!endif
</ul>
!set wims_menu_items=!append line testexo,1,cmd=resume&realtest=yes&retest=again\
to $wims_menu_items

!if $to_ia_qcm=-1
!set wims_menu_items=!append line backconfia2qcm,1,module=adm/auth/confia2qcm&cmd=new&chexo=2&exo=1&to_ia_qcm=1\
 to $wims_menu_items
 !endif
 !if $to_ia_qcm=-2
!set wims_menu_items=!append line backcreateqcm,1,module=adm/auth/createqcm&cmd=new&chexo=2&exo=1&to_ia_qcm=2\
 to $wims_menu_items
 !endif
 !if ($to_ia_qcm!=-2 and $to_ia_qcm!=-1)
!set wims_menu_items=!append line exomodify,1,cmd=reply&level=2\
 to $wims_menu_items
 !endif
!set wims_menu_items=!append line testexo,1,cmd=resume&realtest=yes&retest=again\
to $wims_menu_items

!if $wims_version_theme=0 or $wims_version_theme=
  !reset wims_menu_items
!endif

