
Uw oefening is met succes opgenomen door deze server.
Wij danken U voor deze bijdrage aan onze WIMS server.

<p>
De administrator van deze server zal deze module nog verder controleren, en bepaalt dan 
tot welke categorie deze behoort.<br>Dit kan enkele dagen in beslag nemen. 

<p><center>
!href module=incoming Tijdelijke locatie van deze module.
<p>
!href cmd=reply&level=$[$level-1] Terug naar het vorige menu.
</center>


