!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
 U bent nu in de "expert mode" voor het maken van OEF oefeningen.
 !if $modeltest=yes
 Als deze oefening is gebaseerd op een standaard model, probeer eerst de
  !href cmd=reply&mode=model&level=2 $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !else
!! Deze mode is bedoeld voor gevorderden of voor het rechtstreeks invoeren van een OEF broncode.
!! Bent u onervaren in het maken van dit type interactieve oefeningen, probeer dan eerst
!!  !href cmd=reply&mode=normal&level=1 $name_normal
!!.
!!

  Geef de broncode (
  !href target=wims_mhelp cmd=help&special_parm=oef OEF formaat
  ) van uw oefening&nbsp;:
  (voeg een bestaande broncode toe door knippen en plakken in 
  het venster.) 
 !endif
!else
 Hier is de broncode
 !if $catmodule=$empty
  van een oefening uit uw klas. U kunt deze bewerken in het onderstaande venster.
 !else
    van uw geimporteerde publieke oefening.
    U kunt deze bewerken en aanpassen in het onderstaande venster.
 !endif
 !if $modeltest=yes
 Deze oefening is gebaseerd op een "standaard model" oefening, 
 en klan worden bewerkt met
  !href cmd=reply&mode=model&level=2  $name_normal
.
  !href cmd=reply&mode=none&level=0 $wims_name_giveup
.
 !endif
!endif

U kunt het gebruik van de hulpsoftware testen met  
  !href target=wims_test module=tool/directexec&cmd=new de script tester

<p><center>
!mexec textarea.sh

<p><input type=submit value="Registreer de code"></center>
<center><a name=textarea></a>
[
<a href="#"
onclick="document.forms['replyform'].wims_deposit.value=''">Wissen</a>
] [
!href cmd=resume $wims_name_giveup
].
</center>
</form>

