!set wims_name_examremain=Resterende tijd voor dit proefwerk : $
!read js/examclock.phtml
<html><head>
$wims_html_header
</head><body $wims_htmlbody onload=$wims_html_onload>
!headmenu

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!if $job iswordof student score scorereg
 !changeto $job.phtml
!endif

<center>$classname
<p>
<h1>Het samenstellen van proefwerk $exam
</h1></center> <p><hr width=40%> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Terug naar de homepagina
. <p>
 !goto end
!endif

!if $job=exo or $job=cpsheet
 !read $job.phtml
 !goto end
!endif

!if $activetest>0
 !form reply
 <input type=hidden name=job value=text>
 Dit proefwerk is
 !if $activetest=1
  geactiveerd
  !href cmd=reply&job=expire Laat het verlopen
.
 !else
  !if $activetest=2
  is verlopen maar nog wel zichtbaar voor uw leerlingen.
   !href cmd=reply&job=hide Maak het onzichtbaar.
  !else
   is verlopen en onzichtbaar voor uw leerlingen.
   Maak het proefwerk weer 
   !href cmd=reply&job=expire zichtbaar
   </a>.
  !endif
  .
  !href cmd=reply&job=reactivate Reactiveer
!href cmd=reply&job=deactivate Desactive it
</a> het proefwerk
. <p>
 !endif
 <p><center><table border=2>
 <tr><td align=right>Titel:
 <td><input size=40 name=title value="$title">
 <td rowspan=3><input type=submit value=Modify>
 <tr><td align=right>Omschrijving:
 <td><textarea name=desc rows=2 cols=40>$desc</textarea>
 <tr><td align=right>Verloop datum:<td>
 !distribute item $[$expday],$[$expmon] into expday,expmon
 !formselect expday from 1 to 31
 !formselect expmon from 1 to 12 prompt $months
 !formselect expyear from $thisyear to $thisyear+1
 </table></form></center> <p>
 !goto end1
!endif

!form reply
<input type=hidden name=job value=text>
Titel (maximaal $title_limit karacters):<br>
<input size=65 name=title value="$title"> <p>
en een verklarende tekst (beperkt tot $desc_limit karacters; html
tags en hyperlinks zijn toegestaan):<br>
<textarea rows=6 cols=65 name=desc>$desc</textarea>

<center><input type=submit value="Stuur deze tekst op"></center>

<p>Dit proefwerk verloopt op
!distribute item $[$expday],$[$expmon] into expday,expmon
!formselect expday from 1 to 31
!formselect expmon from 1 to 12 prompt $months
!formselect expyear from $thisyear to $thisyear+1
. 
Een enkele proefwerksessie kan
<input size=5 name=duration value="$duration">
minuten duren<br>Elke deelnemer mag dit proefwerk tot
!default stries=3
<input size=3 name=tries value="$stries"> keer overdoen.
<input type=submit value="OK en versturen">

!ifval $activetest=-1
 <p>Dit proefwerk bestaat nog niet.<input type=submit value="Klik hier om een nieuw proefwerk te maken"> <small>Maar geef dit proefwerk eerst even een titel</small>
 </form>
 !goto end
!else
 </form>
 !if $exocnt>0
  <p>
  Dit proefwerk is <b>nog niet</b> geactiveerd.
  !href cmd=reply&job=prep_activate klik hier 
  </a> om dit proefwerk te activeren.
  Studenten, leerlingen zien alleen de actieve proefwerks.<br>
  Echter: een proefwerk eenmaal geactiveerd , kan <b>niet</b> meer inhoudelijk worden veranderd. 
  
 !endif
!endif

:end1
<p>
!if $exocnt=0
 Dit proefwerk bevat nog <b>geen</b> opgaven.
 !href cmd=reply&job=exo&exo=1 Voeg een opgave
 </a> toe , of voeg in &eacute;&eacute;n keer een 
 !href cmd=reply&job=cpsheet serie opgaven
 </a> toe.
!else
 <a name=list>
 De opgaven in dit proefwerk:</a><ol>
 !for i=1 to $exocnt
  <li>
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,ch,ti
  !if $we=0
    $ti, <font color=red><b>gewicht 0</b></font>
  !else
    $ti, gewicht $we
  !endif
  !if $activetest=0
   &nbsp;(
   !if $i>1
    !href cmd=reply&job=moveup&moveup=$i#list Verplaats&nbsp;naar&nbsp;boven
    </a>&nbsp;
   !endif
   !href cmd=reply&job=exo&exo=$i Veranderen
   </a> &nbsp;
   !href cmd=reply&job=delete&delete=$i#list Verwijderen
   )</a>
  !endif
 !next i
 </ol>
 !if $activetest=0
 Voeg nog
  !href cmd=reply&job=exo&exo=$[$exocnt+1]  een opgave 
  </a> toe, of voeg een hele
 !href cmd=reply&job=cpsheet serie
 </a> opdrachten toe
 .
 !endif
!endif

<p>
!if $activetest=0 and $erasable=yes
  U kunt dit proefwerk nog steeds
  !href cmd=reply&job=prep_erase wissen
.
!endif

!if $activetest>=0
Zo zien Uw 
 !href cmd=reply&job=student <b>leerlingen</b>
 </a> deze pagina.
 <p>
 !form reply
 <input type=hidden name=allow value=yes>
 Dit proefwerk is
 !formselect allowtype list all, simulation, none, select prompt\
	open voor iedereen, open voor simulatie,\
	gesloten voor iedereen, open voor de volgende netwerk adressen (en/of tijdstippen):
 <br><input size=50 name=IPlist value="$IPlist"> <br>
 Cut times:
 <input size=50 name=cutt value="$cutt"> <br>
 <input type=submit value="Veranderingen opslaan">
  !if $sharers!=$empty                                                                                                                      
  ( ook voor alle klassen die dit proefwerk delen ? :                                                                                          
  !formselect allowshare list 0,1 prompt nee,ja
  )
  !else
 <input type=hidden name=allowshare value=0>
 !endif
 </form>
 <small><b>Hint.</b> In the selective open mode, you can make time
 restrictions for score registrations, by adding words 
 <font color=blue><b>
 <tt>&gt;yyyymmdd.hh:mm</tt></b></font>
 (starting time) and/or
 <font color=blue><b>
 <tt>&lt;yyyymmdd.hh:mm</tt></b></font>
 (ending time). These must be in the
 SERVER's local time, and must be separated from other words by white spaces.
 <p>
 Cut times are used to let people take the exam in different sessions. A
 participant having worked on the exam before a cut time will have no access
 after the cut time.
 <p>
 Format of cut times: <tt>yyyymmdd.hh:mm</tt> (separate several cut times
 by white spaces).
 </small>
!endif
:end
!tail

!reset job,echoose,eweight,ename,edep,eopt,source
