
!set classname=<b><font color=green>$wims_classname</font></b>\
 van <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,Mei,Jun,Jul,Aug,Sept,Okt,Nov,Dec

!set wims_name_endexam=Be&euml;indig de proefwerk sessie
!set wims_name_scoreexam=Mijn cijfers

!set name_mainpage=Hoofdpagina van het proefwerk
!set name_dependency=Cijfer afhankelijkheden&nbsp;
!set name_Options=Opties
!set name_All=Alles
!set name_title=Aanmaken van een proefwerk
!set name_expire=Laat het proefwerk nu verlopen
!set name_done=klaar

!distribute items Gewicht,Co&euml;fficient,Cijfer\
into name_weight,name_coeff,name_Score

!distribute lines Be&euml;indig deze proefwerksessie\
Terug naar het proefwerk\
Zo zien docenten dit proefwerk\
Zo zien studenten dit proefwerk\
Details van de score\
Dit proefwerk is leeg&nbsp;! Dit zal een foutje zijn van de docent.\
Inhoudsopgave van dit proefwerk&nbsp;\
Dit proefwerk is niet bereikbaar voor computers met uw IP adres.\
U mag dit proefwerk nog &eacute;&eactue;n keer maken.\
Dus het cijfer voor dit proefwerk kan niet meer worden verbeterd.\
Opgelet : dit is de laatste proefwerk poging.\
het aftellen begint en het aantal beschikbare proefwerk pogingen wordt met 1 verminderd.\
begin het aftellen .\
Vereist een goed cijfer bij de vorige opgaven\
Cijfer voor deze proefwerk sessie&nbsp;\
into wims_name_endexam,wims_name_backexam,name_teacherview,name_presentation,\
name_scoreexam,name_empty,name_content,name_examclosed,name_exam1,name_exam5,\
name_lasttry,name_exam7,name_exam8,name_depend,name_scoreexam2

!set name_exam2=!nosubst Er zijn in't totaal $stries proefwerk pogingen beschikbaar.

!set name_exam3=!nosubst Deze proefwerk sessie is be&euml;indigd met $tried pogingen,
!set name_exam4=!nosubst Dit was proefwerk poging nummer $tried ,
!set name_exam6=!nosubst En er zijn nu nog $tryremain poging(en) beschikbaar.

!set name_exam9=!nosubst Dit proefwerk mag maximaal $sdure min. in beslag nemen.\
Wanneer een opgave wordt aangeklikt,
 
!set name_simulation=Dit proefwerk verloopt in simulatie mode. Het werkt precies zo als het echte proefwerk, \
alleen worden nu de cijfers -en andere data- natuurlijk niet opgeslagen.
  
!set wims_name_examremain=Resterende tijd voor dit proefwerk : $

!distribute lines bezig...\
  U bent nog niet begonnen met dit proefwerk.\
  Start dit proefwerk.\
  Uw score wordt niet geregistreerd, omdat dit proefwerk in simulatie mode loopt.\
  into name_pending,name_begin1,name_begin2,name_simulation2

!set name_timeleft=!nosubst De beschikbare tijd is verlopen! Je hebt de toegestane $sdure minuten verbruikt.
!set name_realscore=!nosubst De echte score voor deze proefwerk-sessie is $lastscore.
!set name_bestscore =!nosubst De score voor dit proefwerk is $lastscore. (En de beste score telt !)
