
!if $job=score
 !read adm/title.phtml 1\
 $wims_classname, $wims_institutionname\
 $title

 !if $wims_user=supervisor
  <center>($name_presentation)</center>
 !endif
  <p>$desc<p>
!endif

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home $wims_name_back
. <p>
 !goto end
!endif

!if $exocnt=0
    $name_empty
!else
 <p><center><table border=1 bgcolor=bisque>
 <caption>$name_scoreexam</caption>
 <tr><th>$wims_name_Exercise</th><th>$wims_name_title</th><th>$name_coeff</th><th>$name_Score</th>
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/exams/.exam$exam
  !distribute lines $ex into we,li,ti
  <tr><td align=center>$i
  <td align=center>$ti
  <td align=center>$we<td align=center>
  !if $(replied$i)>0
   $(got$i)
  !else
   <small>bezig...</small>
  !endif
 !next i
 <tr><td align=center colspan=4>
 !default score=$sprime
 $name_scoreexam2: <b>$score</b> <small>/ 10</small>.
 $table_end
!endif
<p>

!if $registered=$empty
 U bent nog niet begonnen met dit proefwerk.
 !href cmd=reply&job=student Start dit proefwerk.
!else
 !if $timeleft<=0
   De beschikbare tijd is verlopen!
   Je hebt de toegestane $sdure minuten verbruikt.
   <p>
 !endif
 !if $allowtype=simulation
  Uw score wordt niet geregistreerd, 
  omdat dit proefwerk in simulatie mode loopt.
  !if $lastscore>0
   (De echte score voor deze proefwerk-sessie is $lastscore.)
  !endif
 !else
  De score voor dit proefwerk is $lastscore. 
  (En de beste score telt !)
 !endif
 <p>
!set test=!recordcnt wimshome/$wims_sesdir/examscore.$exam
!if $test>=2
 !href cmd=reply&job=scorereg $name_endexam .
 &nbsp;&nbsp;
!endif
 !href cmd=reply&job=student $name_backexam .
!endif

!if $wims_user=supervisor
 <p><center>
 !href cmd=resume $name_teacherview.
 </center>
!endif

:end
!tail

!reset job

