<b>WAARSCHUWING</b>!<p>
Je hebt nog niet alle opgaven uit dit tentamen gemaakt.<br>
Wanneer je er <b>nu</b> mee stopt, wordt je cijfer bevroren en ben je
dus een <em>volle tentamen poging</em> kwijt.<br>
Bij een eventuele volgende poging om dit tentamen te maken, moet je wel weer <em>alle</em>
random (!) sommen opnieuw doen...
 
<p>
Weet je zeker dat je er mee wilt stoppen?

<p><center><font size=+1>
!href cmd=reply&job=scorereg&confirm_end=yes JA, ik kap ermee
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score  NEE, ik heb me bedacht
</font></center> <p>

!tail
!reset job
