<b>Waarschuwing</b>!<p>

Je hebt nog niet alle opgaven uit dit proefwerk gemaakt. Wanneer je er nu mee stopt, wordt je cijfer bevroren en ben je dus een volle proefwerk poging kwijt.
Bij een eventuele volgende poging om dit proefwerk te maken, moet je wel weer alle
random (!) sommen opnieuw doen...
<p>
Weet je zeker dat je er mee wilt stoppen?
<p><center><font size="+1">
!href cmd=reply&job=scorereg&confirm_end=yes $wims_name_yes
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score $wims_name_no
</font></center> <p>

!tail
!reset job
