!set levelE=educación primaria
!set levelH=educación secundaria
!set levelU=universidad

!set lang_fr=français
!set lang_en=English
!set lang_es=español

!if $cltype iswordof 2 4
   !if $cltype=2
    !set name_classe=agrupación de clases
    !set name_sup=del profesor-administrador
    !set name_classes= el $name_classe
    !set name_classess= un $name_classe
    !set name_classesss= del $name_classe
    !set name_classessss= El $name_classe
   !else
    !set name_classe=centro educativo
    !set name_sup=del administrador
    !set name_classes= el $name_classe
    !set name_classess= un $name_classe
    !set name_classesss= del $name_classe
    !set name_classessss= El $name_classe
    !endif
 !else 
   !set name_classe=clase
   !set name_classes=la clase
   !set name_classess=una clase
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=del profesor
 !endif


 
