<p>
Quicktool is an administrative module which can be used by Modtool developpers to create 
language exercises. It is not in the standard distribution.
The exercises which are created with are completely compatible with current
stable version of wims.
<p>


!form reply

!formcheckbox job2 list 1 prompt Download Quicktool
<p><small> 
 If you want to download the developpement version, download it by command lines :
 <pre>
 cd public_html/modules/adm
 svn co https://subversion.cru.fr/wimsmodules/trunk/modules/adm/quicktool.fr ; 
 find quicktool.fr -name .svn -exec rm -rf '{}' \;
</pre>
 </small>
<center> <input type=submit value=OK></center>
</form>
