!if $job2=1
adresse=sourcesup.cru.fr/frs/download.php
file=quicktool.fr-1.50.tgz
file_stable=quicktool.fr.tgz
!sh cd modules/adm ; wget http://$adresse/2169/$file_stable ; tar xzf $file_stable ;\
  rm $file_stable;
!endif
!if $job2=2
adresse=https://subversion.cru.fr/wimsmodules/trunk/modules/adm/quicktool.fr
!sh cd modules/adm ; svn co $adresse ; find quicktool.fr -name .svn -exec rm -rf '{}' \;
!endif

!reset job2
