
<center><h2>Options d'un programme</h2></center>

Si un programme est <em>obligatoire</em>, tous les élèves d'une classe ayant
un cours dépendant du programme sont automatiquement inscrits dans ce cours.
Autrement dit, tous les cours du programme sont obligatoires pour les classes
correspondantes.
<p>
Par contre, pour un cours <em>optionnel</em>, les élèves doivent
spécifiquement s'inscrire à ces cours. C'est utile quand le programme est une
option de l'enseignement.
<p>
Si l'installation automatique des cours du programme est mise à "oui", un
cours sera créé pour chaque classe du niveau, au moment de la création du
programme. De plus, un cours du programme sera automatiquement créé 
dès qu'une nouvelle classe
sera créée dans le niveau.
<p>
Si l'installation automatique des cours est mise à "non", les enseignants
des classes doivent manuellement créer les cours correspondant au programme.
