
!if equalities iswordof $m_options or $laststep<1
 !exit
!endif

!readproc tabletheme
<p>$table_header
<caption>History of steps</caption>
$table_hdtr<th>Step</th>
!if $casecnt>1
 <th>Case</th>
!endif
<th>Result</th><th></th>
<th>Method</th>
<th>Remarks</th></tr>
!reset light1,light2
!set hstart=$[max(1,$currstep-10)]
!set hstop=$[min($laststep,$currstep+8)]
!for i=$hstart to $hstop
 !if $i=$currstep
  !distribute item <font color="#9090C0">,</font> into light1,light2
 !endif
 $table_tr<td align="center" nowrap>$light1
 $i
 !if $status=waiting
  <small>
  !if $i<$currstep
   !href cmd=reply&opt=newstep&gotostep=$i undo
  !else
   !href cmd=reply&opt=newstep&gotostep=$[$i+1] redo
  !endif
  </small>
 !endif
$light2</td>
 !if $casecnt>1
 !set c_=!item $i of $stepcases
  <td align="center">$light1 \($c_) $light2</td>
 !endif
 <td align="center">$light1
 !read deduc/putobject.phtml $i
$light2</td><td></td><td>$light1
 !line $i of $methods
$light2</td>
<td>$light1
!reset R_
!if $objisgoal=yes
 Goal change.
!endif
!set t_=!char $i of $stepcounting
!if $t_=0
 Not counted for score.
 !set R_=1
!endif
!if $R_!=1
 &nbsp;
!endif
$light2</td>
</tr>
!next i
$table_end<a name="last"></a>
<p>

