
<center><h2>Options of a program</h2></center>

If a program is <em>mandatory</em>, all students of a class having a course
corresponding to it will be automatically registered to the course. That is,
all its courses are mandatory for the corresponding classes.
<p>
On the other hand, for an <em>optional</em> program, students must
specifically register to its courses. This is useful when the program is an
option.
<p>
If the automatic course installation of the program is set to "yes", a course will
be created for each class of the level at the creation of the program. A
course for the program will also be created when a new class is created in
the level.
<p>
If automatic course installation is set to "no", supervisors of classes must
manually create courses corresponding to the program.
