!set proc=oef
!header

!if $wims_class=$empty
 Deze module hoort bij een virtuele klas<br>.
 En U staat niet geregistreerd als deelnemer, dus kunt deze module niet opvragen, 
 <p><center>
 !href $ $wims_name_home
 </center> <p>
 !exit
!endif
Deze module bevat de interactieve oefeningen voor
<font color="blue">$wims_classname</font> van 
<font color="blue">$wims_institutionname</font>, en zijn speciaal gemaakt voor deze klas.
!if $wims_user=supervisor
 !href module=adm/createxo Klik hier
 om een nieuwe oefening te maken.
!endif

!if $wims_user=supervisor
 !set wims_menu_items=!append line add_exo,1,module=adm/createxo to $wims_menu_items
!endif

!read oef/intromenu.phtml
!tail

