
如果你是教师并且在教学中经常使用WIMS,
你一定想在学校里建立一个本地WIMS网站. 这样相应速度会更快,
也不怕外面网络的中断.
<p>
WIMS是GNU版权下的软件. 它可被自由
<a href="http://wims.unice.fr/download/wims/">下载</a>,
并被安装在Linux系统里.
关于安装WIMS的更多细节可参看
<a href="http://wims.unice.fr/download/wims/README">README</a>
文件.
<p>
你也可联系
!mailurl xiao@unice.fr 作者
以询问建立镜像站的事宜. 请
!href module=adm/light&phtml=mirror.phtml.$lang 点击这里
以得到面向公众的WIMS镜像站表.
<p>
另一方面, 请勿使用互联网的自动程序收集本站的网页!
WIMS网站只能在线互动地询问, 自动程序收集的网页都是无用的.

