!set week_min=3
!set month_min=20
!set year_min=200

!set n=!linecnt $ref
!set name_site=el sitio
!set name_stem=una página en la dirección
!set name_uniq=la página
!set names_site=sitios
!set names_stem=directorio de sitios
!set names_uniq=páginas
Lista de web $(names_$type) que dirigen a visitantes hacia nosotros, en el periodo de  
$day1-$month1-$year1 a $day2-$month2-$year2 (en total $laps días).
<br>La primera columna muestra el número de visitantes que siguieron
un enlace en $(name_$type) de la segunda columna.
<p>
<table border=0 cellspacing=1>
!set total=0
!set totall=0
!for i=1 to $n
 !set l=!line $i of $ref
 !set w=!wordcnt $l
 !set a=!word 1 of $l
 !set b=!word 2 of $l
 !if $w=2 and ($search = yes or (search notin $b and query notin $b and cgi notin $b))
  !set totall=$[$totall+1]
  <tr><td align=right>$a<td>&nbsp;&nbsp;
  <td><a href="http://$b">$b</a> 
  !set total=$[$total+$a]
 !endif
!next i
<tr><td align=right>$total<td>&nbsp;&nbsp;
<td>personas que nos han visitado a través de enlaces de $totall 
 $(names_$type).
</table> <p>

!if $auto>0
 Al menos $auto otras visitas no especificaron referencias a páginas 
 públicas. Las páginas que tienen como referencia $httpd_HTTP_HOST no se han contado.
 <p>
!endif

