!if _exam isin $session
 !set wims_nextmodule=$cookie_module
!endif

<br> <br><br>
!if $lang=cn
Çë¼¤»îÄãµÄä¯ÀÀÆ÷µÄcookies, È»ºó
 !href cmd=$cookie_cmd&module=$cookie_module µã»÷ÕâÀï
.
 !exit
!endif

!if $lang=fr
 Veuillez activer les cookies de votre navigateur, puis
 !href cmd=$cookie_cmd&module=$cookie_module cliquer ici
.
 !exit
!endif

!if $lang=si
 Vkljuèite pi¹kotke na svojem brskalniku, nato
 !href cmd=$cookie_cmd&module=$cookie_module kliknite tukaj
.
 !exit
!endif

!if $lang=it
 &Egrave; necessario attivare i cookie del browser, dopo di che
 !href cmd=$cookie_cmd&module=$cookie_module cliccate qui
.
 !exit
!endif

!if $lang=es
 Es necesario tener activadas las cookies en su navegador, a continuación
 !href cmd=$cookie_cmd&module=$cookie_module haga click aquí
.
 !exit
!endif

Please activate cookies of your browser, then
!href cmd=$cookie_cmd&module=$cookie_module click here
.

