!set class_logo=!defof class_logo in wimshome/log/classes/$wims_class/.def
!if $class_logo issametext none
 class_logo=
 !exit
!endif
!if $class_logo issametext wims
 !set class_logo=gifs/logo.gif
!endif
!default class_logo=gifs/logo.gif
!bound class_logoside within left,right default left
!! transfer in themes
!!<table border=0 cellspacing=0 cellpadding=8 align=$class_logoside>
!!<tr><td align=center valign=middle>
!!<img src="$class_logo" border=0 alt="logo" align=left>
!!</td></tr></table>

