<h1 class="wimscenter">WIMS: WWW Interactive Multipurpose Server</h1>
$wims_site_description
<p>
Keywords: $wims_site_keywords
</p>
!! This is the specific identifier word.
wimshomeabcd $wims_version

!read wimshome/log/motd.phtml.$lang
<p>
!href module=adm/doc Documents
 Other languages:
!set ls=!words2items $wims_site_languages
!for l in $ls
 !if $l!=$lang
  !href lang=$l $l

 !endif
!next l
</p>
!set n=!recordcnt wimshome/public_html/html/mirrors.$lang
!if $n>0
 <p><big><center>Mirrors</center></big><img src="gifs/logoupsud.png" border="0" alt="logo"/><p>
 <A HREF="http://wims.unice.fr/">WIMS Home page</A> <br/>
 !for i=1 to $n
  !set l=!record $i of wimshome/public_html/html/mirrors.$lang
  !distribute lines $l into h_,n_
  !if :// notin $h_
   !set h_=http://$h_
  !endif
  <a href="$h_">$n_</a> <br/>
 !next i
!endif

<p>WIMS Home Site:
<a href=http://wims.unice.fr/>http://wims.unice.fr/</a>
<a href=http://wims.unice.fr/download/>Source codes</a>
</p>
<p><big><center>Activities</center></big><p>
<p>
!read wimshome/public_html/bases/site/lists/robot-$lang.phtml
</p>
!homeref
