
!if $wims_superclass=$empty
  !let wims_superclass=$wims_class
!endif
!set wims_realuser=!defof wims_realuser in wimshome/$wims_sesdir/var.stat
!set user_supervise=!defof user_supervise in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!set levels=!record 0 of wimshome/log/classes/$wims_class/levels
!set levelcnt=!linecnt $levels
!set classes=!record 0 of wimshome/log/classes/$wims_class/classes
!set classcnt=!linecnt $classes
!set progs=!record 0 of wimshome/log/classes/$wims_class/programs
!set progcnt=!linecnt $progs

!!if $classcnt+$progcnt>=1
 !set courses=!record 0 of wimshome/log/classes/$wims_class/courses
 !set coursecnt=!linecnt $courses
!!endif
!set icourses=!record 0 of wimshome/log/classes/$wims_class/icourses
!set icoursecnt=!linecnt $icourses

!let user_supervise=!defof user_supervise in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!if $wims_user=supervisor and $wims_realuser=supervisor
  !set user_supervise=!column 1 of $levels\
$classes\
$progs\
$courses
  !set user_supervise=!makelist $wims_superclass/x for x in $user_supervise
!endif

!! ----------- definition des droits de connexion supervisor

!reset compsup
!for cls in $user_supervise
  !let tmp=!replace internal / by , in $cls
  !let compsup=!append line $tmp to $compsup
!next cls

!let compsup=!sh echo "$compsup" | sort | uniq;
$U_gotoclass3
!read classgraph.phtml supervise\
$compsup

!let user_particpate=!defof user_particpate in wimshome/log/classes/$wims_superclass/.users/$wims_realuser

!reset compsup
$U_gotoclass1

!for cls in $user_participate
  !let tmp=!replace internal / by , in $cls
  !let compsup=!append line $tmp to $compsup
!next cls

!let compsup=!sh echo "$compsup" | sort | uniq;

!read classgraph.phtml participate\
$compsup

