
!set wims_realuser=!defof wims_realuser in wimshome/$wims_sesdir/var.stat
!set user_supervise=!defof user_supervise in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!set classes=!record 0 of wimshome/log/classes/$wims_class/classes
!set classcnt=!linecnt $classes
!if $classcnt>0
 <p>
 $(CL_Names[2]):</p>
 !reset compt
 !for i=1 to $classcnt
  !set l=!line $i of $classes
  !distribute items $l into c_,s_,t_
  <span class="wims_classes_direct_class">
  !if $c_ isitemof $user_supervise
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_&auth_user=supervisor $t_
   !else
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_ $t_
   !endif
  </span>
  !if $compt=9
    !set compt=0
     <p class="emptyline"></p>
  !else
    !increase compt
  !endif
 !next i
!endif
!set progs=!record 0 of wimshome/log/classes/$wims_class/programs
!set progcnt=!linecnt $progs

!if $progcnt>0
 <p>
 $(CL_Names[3]):</p>
 !reset compt
 !for i=1 to $progcnt
  !set l=!line $i of $progs
  !distribute items $l into c_,s_,t_
  <span class="wims_classes_direct_program">
  !if $c_ isitemof $user_supervise
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_&auth_user=supervisor $t_
   !else
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_ $t_
   !endif
  </span>
  !if $compt=5
    !set compt=0
     <p class="emptyline"></p>
  !else
    !increase compt
  !endif
 !next i
!endif

!if $classcnt+$progcnt<1
 !set courses=!record 0 of wimshome/log/classes/$wims_class/courses
 !set coursecnt=!linecnt $courses
 
 !if $coursecnt>0
  <p>
  $(CL_Names[4]):</p>
  !reset compt
  !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into c_,s_,t_
   <span class="wims_classes_direct_course">
   !if $c_ isitemof $user_supervise
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_&auth_user=supervisor $t_
   !else
    !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_ $t_
   !endif
   </span>
   !if $compt=5
    !set compt=0
    <p class="emptyline"></p>
   !else
    !increase compt
   !endif
  !next i
 !endif
 !set courses=!record 0 of wimshome/log/classes/$wims_class/icourses
 !set coursecnt=!linecnt $courses
 !if $coursecnt>0
  <p>
  $(CL_Names[5]):</p>
  !reset compt
  !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into c_,s_,t_
   <span class="wims_classes_direct_course">
   !if $c_ isitemof $user_supervise
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_&auth_user=supervisor $t_
   !else
     !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$c_ $t_
   !endif
   </span>
   !if $compt=5
    !set compt=0
     <p class="emptyline"></p>
   !else
    !increase compt
   !endif
  !next i
 !endif
!endif

!if $class_typename=program
 !set test=!defof class_defined in wimshome/log/classes/$wims_class/0/.def
 !if $test=yes
  <div>
  !set wims_ref_class=wims_button
  !href module=adm/class/classes&type=authsupervisor&class=$wims_class/0 $N_go
  &nbsp;
!set wims_ref_class=wims_button
  !href module=adm/class/config&job=neighbor&job2=import&nei=$wims_class/0 $wims_name_import
  ($CL_Test)
  !set wims_menu_items=!append line testgo,1,module=adm/class/classes&type=authsupervisor&class=$wims_class/0 \
  import,1,adm/class/config&job=neighbor&job2=import&nei=$wims_class/0\
  to $wims_menu_items
  </div>
 !endif
!endif
