!if $wims_superclass=$empty
  !let wims_superclass=$wims_class
!endif
!set wims_realuser=!defof wims_realuser in wimshome/$wims_sesdir/var.stat
!set user_supervise=!defof user_supervise in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!set levels=!record 0 of wimshome/log/classes/$wims_class/levels
!set levelcnt=!linecnt $levels
!set classes=!record 0 of wimshome/log/classes/$wims_class/classes
!set classcnt=!linecnt $classes
!set progs=!record 0 of wimshome/log/classes/$wims_class/programs
!set progcnt=!linecnt $progs

!!if $classcnt+$progcnt>=1
 !set courses=!record 0 of wimshome/log/classes/$wims_class/courses
 !set coursecnt=!linecnt $courses
!!endif
!set icourses=!record 0 of wimshome/log/classes/$wims_class/icourses
!set icoursecnt=!linecnt $icourses

!let user_supervise=!defof user_supervise in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!if $wims_user=supervisor and $wims_realuser=supervisor
  !set user_supervise=!column 1 of $levels\
$classes\
$progs\
$courses\
$icourses
  !set user_supervise=!nonempty items $user_supervise
  !set user_supervise=!makelist $wims_superclass/x for x in $user_supervise
!endif

!! ----------- definition des droits de connexion supervisor
!reset compsup
!for cls in $user_supervise
  !if $wims_class isin $cls
    !let tmp=!replace internal / by , in $cls
    !if $tmp!=$empty
      !let compsup=!append line $tmp to $compsup
    !endif
  !endif
!next cls
!let compsup=!sh echo "$compsup" | sort | uniq;
!if $user_participate!=$empty
  $U_gotoclass3
!endif
!let user_supervise_=$user_supervise
!read adm/class/graphclass supervise\
$compsup

!let user_participate=!defof user_participate in wimshome/log/classes/$wims_superclass/.users/$wims_realuser
!if $user_participate=$empty
  !exit
!endif
!reset compsup
$U_gotoclass1

!for cls in $user_participate
  !if $wims_class isin $cls
    !let tmp=!replace internal / by , in $cls
    !if $tmp!=$empty
      !let compsup=!append line $tmp to $compsup
    !endif
  !endif
!next cls

!let compsup=!sh echo "$compsup" | sort | uniq;
!let user_participate_=$user_participate
!read adm/class/graphclass participate\
$compsup
