
!if $title=$empty
 Error fetching the module <tt><b>$addr</b></tt>.
 !href cmd=reply&job2=first Back
.
 !exit
!endif

!if $muauto iswordof update install
 !if $output!=ok
  Error installing/updating <tt><b>$addr</b></tt>.
 !else
  Installing/updating <tt><b>$addr</b></tt>: successful.
  !href target=wims_test module=$addr test it
.
  You will need to
  !href cmd=reply&job=mkindex rebuild module index
.
 !endif
 !href cmd=reply&job2=first Back to module management
.
 !reset muauto
 !exit
!endif

$table_header
<caption>
!if $vtest=$empty
 New module <tt><b>$addr</b></tt> <br>
 !href cmd=reply&job2=one&muauto=install Install
!else
 New version of <tt><b>$addr</b></tt> <br>
 !href cmd=reply&job2=one&muauto=update Update
!endif
&nbsp;&nbsp;&nbsp;
!href cmd=reply&job2=first Cancel
</caption>
$table_tr<th align=right bgcolor=$table_bgcolor>Title:<td>$title
$table_tr<th align=right bgcolor=$table_bgcolor>Description:<td>$description
$table_tr<th align=right bgcolor=$table_bgcolor>Type:<td>$category
$table_tr<th align=right bgcolor=$table_bgcolor>Version:<td>$version
!if $vtest!=$empty
 (versus $vtest)
!endif
$table_tr<th align=right bgcolor=$table_bgcolor>Language:<td>$language
$table_tr<th align=right bgcolor=$table_bgcolor>Author:<td>
  <a href="mailto:$address">$author</a>
!if $translator!=$empty
 $table_tr<th align=right bgcolor=$table_bgcolor>Translator:<td>
  <a href="mailto:$translator_address">$translator</a>
 
!endif
$table_tr<th align=right bgcolor=$table_bgcolor>Require:<td>$require
!if $news!=$empty
 $table_tr<th align=right bgcolor=$table_bgcolor>Changes:<td>
 <small><pre>$news</pre></small>
!endif
$table_end <p>

