!set proc=oef
<p><center><hr width="35%"></center> <p>

!if robot isin $session
 !changeto content.html
!endif

!if $wims_class!=$empty and $wims_user=supervisor
 !distribute line $wims_oefdefault_qnum\
$wims_oefdefault_qcmlevel\
$wims_oefdefault_scoredelay\
$wims_oefdefault_qcmpresent\
$wims_oefdefault_presentsol\
$wims_oefdefault_check into qnum,qcmlevel,scoredelay,intro_qcmpresent,intro_presentsol,intro_check
 !let special_parm2=expert
!endif

!if ////classes/ isin ////$module
 !set class_header=wimshome/log/classes/$wims_class/
!endif

!read $(class_header)Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=$[min($exocnt,8)]
!if $exocnt<1
 !if $wims_user=supervisor and #classes/ isin #$module
  !!!href module=adm/createxo Click here
  !!to create your exercises.
  !set wims_menu_items=!append line add_exo,1,module=adm/createxo\
  to $wims_menu_items
 !else
  Sorry, this module has no available exercise for the time being. Come back
  later!
 !endif
 !exit
!endif
!if $exocnt=1
 This module contains actually only one exercise, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Try it.
 !exit
!endif

!form new
<input type=hidden name=module value="$module">
<center><table border=0><tr>
!set special_parm=!trim $special_parm
!if select iswordof $special_parm2 and $special_parm!=$empty
 <td align=center>Exercises containing<br>
 <em><font color=blue>$special_parm</font></em>&nbsp;:<td>
!else
 <td align=center>Choose the exercises:<td>
!endif
!read oef/select.phtml
<tr><td align=center>One series will have<td>
!default qnum=1
!formselect qnum from 1 to 9
exercises.
<tr><td align=center>Level of severity <td>
!default qcmlevel=3
!formselect qcmlevel from 1 to 9
<tr><td align=center>Time limit <td>
<input size=7 name=scoredelay value="$scoredelay"> seconds.
!read introhook.phtml
!if expert iswordof $special_parm2
   <tr><td align=center>
   Number of items shown in multiple choices: <td></td>
   !default intro_qcmpresent=4
   !formselect intro_qcmpresent list 2,3,4,5,6,7,8 
   </td></tr>
   <tr><td align=center>Give solution (if available)? <td>
   !default intro_presentsol=1
   !formselect intro_presentsol list 0,1,2 prompt never,if the score is not maximal,always
   </td></tr>
   <tr><td align=right>
   !default intro_check=1,2,3,4
   Multiple choices</td><td>
   !formcheckbox intro_check list 1 prompt Always contain
   good reply.
   </td></tr>
   <tr><td rowspan=3>&nbsp;</td><td align=left>
   !formcheckbox intro_check list 2 prompt Penalty for bad replies in multiple choices.
   </td></tr>
   <tr><td align=left>
   !formcheckbox  intro_check list 3 prompt Show good reply.
   </td></tr>
   <tr><td align=left>
   !formcheckbox intro_check list 4 prompt Allow hint (when available).
   !let tmp=!replace word expert by $ in $special_parm2
   </td></tr>
  !if $wims_class=$empty or $wims_user!=supervisor
   <tr><td colspan=2 align=center>
   !href module=$module&special_parm=$special_parm&special_parm2=$tmp Simplified menu
   <input type=hidden name=intro_expert value=yes>
  !endif
!else
   <tr><td colspan=2 align=center>
   !let tmp=$special_parm2 expert
   !href module=$module&special_parm=$special_parm&special_parm2=$tmp Expert menu
!endif
</table></center> <p><center>
<input type=submit value="Go to work">&nbsp;
<input type=submit name=print value="Printable version">
</center>
</form>

!if $exocnt>10
 !form intro
 <input type=hidden name=special_parm2 value=select>
 <input type=hidden name=module value="$module">
 Select titles containing word
 <input size=12 maxlength=12 name=special_parm value="$oldparm">
 <input type=submit value=OK>
 </form>
!endif

<b>Remarks</b>. The exercises will be randomly taken among your choice
(or among all the available exercises if your choice is empty).

!if * isin $titlelist
 <p>Exercises marked by a * are in general harder than the others.
!endif

<p><small>You can put two numbers into the time limit, a smaller limit followed
by a bigger one. In this case, the first limit starts score reduction, which
will go to 0 if the second limit is reached.
</small>
