
<html><head>
$wims_html_header
</head><body $wims_htmlbody>
!headmenu

<center>$classname
<h1>$cdt_title</h1>
<font size=+1>Configurer</font></center> 

<p><hr width=40%> <p>

Voici les paramètres que vous pouvez changer :

!form reply
<input type=hidden name=job value=config>
<ul>
 <p><li>Titre &nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <p><li>Description&nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <p><li>Nom du lien sur la page d'accueil &nbsp; : <input size=60 name=cf_link value="$cdt_link"></li> 
 <p><li>
  !href cmd=renew&job=logfile Voir
  le fichier de connexion au cahier de texte de la classe.</li>
</ul>
<p><center><input type=submit name=cf_set value="Enregistrer le changement">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Abandonner">
</center> <p></form>
<p>
 !href cmd=reply&job=home Retour
 .
