!!!Don't translate for the moment

<b>Mouvement dans un jeu d'échecs</b> (nom : <tt class="wims_code_words">chessboard</tt>)

La première ligne de la bonne réponse est la position des pièces présentée (entre crochets) :
<tt>position des blancs ; position des noirs</tt>.
La seconde ligne de la bonne réponse est formée des mouvements de pièces demandés (entre crochets).

La notation choisie est la notation algébrique internationale anglaise abrégée : 
<tt>K</tt> pour roi, <tt>Q</tt> pour reine, <tt>R</tt> pour tour, \
<tt>B</tt> pour fou, <tt>N</tt> pour cavalier et <tt>P</tt> pour pion.

Aucune vérification de règles n'est faite. Il s'agit simplement de mouvements de pièces.
Pour préciser la couleur (par défaut grise), mettre <tt class="wims_code_words">color=nom_couleur</tt>.
dans le champ <tt class="wims_code_words">option</tt>.
<pre>
\answer{}{[Kg1,g2,c3,f4,Rg8,Qh8;Qc7,f7,Rd6,c5,Kf5],[h8,e5;c3,c6]}{type=chessboard}{option=color=brown}
</pre>