
<b>Champs à remplir avec glisser-déposer.</b>
(noms : <tt>clickfill</tt> et <tt>dragfill</tt>)
<br>
Le champ de réponse, habituellement inséré dans l'énoncé, peut être
rempli en cliquant sur l'objet donné (texte, formule ou image) ou en le
glissant à la souris depuis une liste d'objets.

<p>
La réponse est habituellement une matrice dont la première ligne est
la bonne réponse et la deuxième est une liste d'items qui sont les
mauvaises réponses.
</p><p> 
La bonne réponse peut être une liste de plusieurs items. Dans ce
cas, le champ à remplir aura une longueur L (le nombre d'objets qu'il
peut contenir) plus grande que 1.
</p><p>
On peut définir des bonnes réponses multiples dans la première ligne,
en les séparant par le caractère '<tt>|</tt>'. Et la réponse
peut être analysée si la première ligne est une variable non définie.
</p><p>
Le mieux est d'utiliser ce champ de réponse via \embed{}, avec une
taille de champ de réponse sous la forme <tt>HxVxL</tt>, où H et V
sont respectivement les tailles horizontale et verticale (en pixels)
d'une case, et L la longueur du champ.
</p><p>
Il peut y avoir plusieurs réponses de type clickfill ou dragfill dans
un exercice, mais elles doivent avoir la même taille et le même type
(toutes clickfill ou toutes dragfill), et les objets sont alors mélangés.
</p><p>
clickfill et dragfill ont des interfaces utilisateur très semblables
(les deux peuvent être cliquées et glissées). La différence principale
est qu'un objet de type clickfill peut être utilisé plusieurs fois,
au plus une pour dragfill.
</p><p>Le contenu des étiquettes est par défaut centré. Il est possible
d'aligner le contenu sur la gauche ou sur la droite en utilisant 
l'option <tt>align=left</tt> ou <tt>align=right</tt> (<tt>{option= align=left}</tt>).
</p><p>
Ces types, fondés sur DynAPI, peuvent ne pas fonctionner avec
certains navigateurs.

