
<b>Champs à remplir avec glisser-déposer.</b>
(noms : <span class="tt wims_code_words">clickfill</span> et <span class="tt wims_code_words">dragfill</span>)
<br/>
Le champ de réponse, habituellement inséré dans l'énoncé, peut être
rempli en cliquant sur l'objet donné (texte, formule ou image) ou en le
glissant à la souris depuis une liste d'objets.

<p>
La réponse est habituellement une matrice dont la première ligne est
la bonne réponse et la deuxième est une liste d'items qui sont les
mauvaises réponses.
</p><p>
La bonne réponse peut être une liste de plusieurs items. Dans ce
cas, le champ à remplir aura une longueur L (le nombre d'objets qu'il
peut contenir) plus grande que 1.
</p><p>
On peut définir des bonnes réponses multiples dans la première ligne,
en les séparant par le caractère <span class="tt wims_code_words">|</span>. Et la réponse
peut être analysée si la première ligne est une variable non définie.
</p><p>
Le mieux est d'utiliser ce champ de réponse via <span class="tt wims_code_words">\embed{}</span>, avec une
taille de champ de réponse sous la forme <span class="tt wims_code_words">HxVxL</span>, où <span class="tt">H</span> et <span class="tt">V</span>
sont respectivement les tailles horizontale et verticale (en pixels)
d'une case et où <span class="tt">L</span> est la longueur du champ.
</p><p>
Il peut y avoir plusieurs réponses de type <span class="tt wims_code_words">clickfill</span> ou <span class="tt wims_code_words">dragfill</span> dans
un exercice, mais elles doivent avoir la même taille et le même type
(toutes <span class="tt wims_code_words">clickfill</span> ou toutes <span class="tt wims_code_words">dragfill</span>), et les objets sont alors mélangés.
</p><p>
Les types <span class="tt wims_code_words">clickfill</span> et <span class="tt wims_code_words">dragfill</span> ont des interfaces utilisateur très semblables
(les deux peuvent être cliquées et glissées). La différence principale
est qu'un objet peut être utilisé plusieurs fois pour le type <span class="tt wims_code_words">clickfill</span>
et au plus une fois pour le type <span class="tt wims_code_words">dragfill</span>.
</p><p>
Le contenu des étiquettes est par défaut centré. Il est possible
d'aligner le contenu sur la gauche ou sur la droite en utilisant
l'option <span class="tt wims_code_words">align=left</span> ou <span class="tt wims_code_words">align=right</span>
(<span class="tt wims_code_words">{option= align=left}</span>).
</p><p>
Si on utilise l'option <span class="tt wims_code_words">noorder</span>, l'analyse de la réponse ne tient pas compte
de l'ordre dans lequel les étiquettes ont été déposées. Cela permet des exercices du
type <i>classer par propriétés</i>.
</p><p>
Avec l'option <span class="tt wims_code_words">transparent</span>, le champ à remplir est transparent (peut être utile
avec la méthode spéciale <span class="tt wims_code_words">imagefill</span>).
</p>
<p>
Avec l'option <span class="tt wims_code_words">keeporder</span>, les étiquettes sont présentées
dans l'ordre de la liste.
</p>
<p>
Ces types, fondés sur DynAPI, peuvent ne pas fonctionner avec
certains navigateurs.
</p>

