 <strong>Nombre complexe.</strong> (nom: <span class="tt wims_code_words">complex</span>)<br/>
 Comparaison de nombres complexes à la précision définie par l'auteur.
!!option=comma precision absolute j
 <ul><li>
 Si le mot <span class="tt wims_code_words">comma</span> est présent dans l'option, l'écriture
 des nombres décimaux avec une virgule décimale est acceptée
 (mais la bonne réponse doit être un nombre avec le point décimal). Si la
 réponse est mauvaise, la bonne réponse est donnée avec le même "séparateur"
 décimal que celui donné par l'élève.
</li><li>
 La précision peut être précisée dans le champ <span class="tt wims_code_words">precision</span>,
 par défaut 1000.
 <p>
L'erreur est par défaut relative : la différence doit être de module inférieur ou égal à
<span class="tt">(good_answer+reply)/precision</span> (remplacer
<span class="tt">precision</span> par <span class="tt">sqrt(precision)</span>
pour une réponse partiellement bonne).
</p><p>
Si le mot <span class="tt wims_code_words">absolute</span> est un mot d'option,
la precision est absolue.
La réponse est alors partiellement bonne si la différence est inférieure à
<span class="tt">10/precision</span>.
</p>
</li><li>
Si la lettre <span class="tt wims_code_words">j</span> est présente dans l'option, les
réponses du type <span class="tt">2+7*j</span> seront acceptées en même temps que les
réponses du type <span class="tt">2+7*j</span>. Si la réponse est mauvaise, la bonne réponse
est donnée avec la même lettre que celle donnée par l'élève. Par contre, il est conseillé
au programmeur d'utiliser la lettre <span class="tt">i</span> pour la bonne réponse.
</li></ul>
