
<b>Phrase composée d'éléments donnés.</b>
(nom : <span class="tt wims_code_words">compose</span>)
<p>
Les éléments donnés peuvent être du texte (mots ou groupes de mots),
des formules (formatées par \(...)), ou des images. Ils doivent être
listés en items dans la bonne réponse fournie. Des éléments inutiles
peuvent être ajoutés dans la réponse après un point-virgule `;'.
</p><p>
 You may define synonymes in the good answer. To do this, the synonymes has
 only to be added behind the (standard) good answer, preceeded by the
 vertical bar `|'. An arbitrary number of synonymes can be defined. In such
 a case, only the first synonyme (before the first `|') should have
 comma-separated items. Words not appearing in the first synonyme will not
 be presented, unless added after a semi-colon.
 </p><p>
 On peut mettre en option le séparateur qui apparaitra
entre les textes : linkword="mot de liaison". Par défaut, il s'agit d'un
espace.
</p><p>
Ce type, fondé sur DynAPI, peut ne pas fonctionner avec certains
navigateurs.
</p>

