 <b>Equation formelle.</b> (nom: <tt class="wims_code_words">equation</tt>)<br>
 La réponse va être évaluée en tant qu'équation et la comparaison est 
 effectuée pour des valeurs de variable dans une zone définie par l'auteur,
 jusqu'à la précision définie par l'auteur.
 
 La réponse <tt>a = 0</tt> est traitée comme la réponse <tt>a</tt>. L'option 
 <tt class="wims_code_words">eqsign=yes</tt> oblige à écrire <tt> a = 0</tt>. 
