<b>Géométrie dynamique</b>
(nom : <tt>geogebra</tt>)

Une applet de géométrie dynamique GeoGebra est affichée. L'utilisateur  
peut construire un certain nombre d'objets (points, droites, cercles, etc.). 
Ce type doit obligatoirement être utilisé avec la commande <tt>\embed</tt>
<p>
La bonne réponse doit être donnée sous la forme d'une matrice. 
Chaque ligne contient des instructions d'une des formes suivantes 
(f pour formal, n pour numeric)
<pre>
n,"condition numérique", texte
f,"condition formelle",texte
n,"condition numérique-formelle",texte
</pre>
Le texte est un texte qui apparaît dans l'analyse de réponse. 
Si aucun texte n'est mis, un texte par défaut est construit à partir 
de la condition ; si le texte est le mot <tt>hiden</tt>, 
la condition n'apparaît pas dans l'analyse de la réponse.

<ul><li><tt>"condition formelle"</tt> : les objets exigés, dans la langue de 
l'exercice et dans la syntaxe de GeoGebra (voir http://www.geogebra.org/help/docufr/ )
avec leur nom s'il est imposé (en cas de mauvais nom, l'objet sera reconnu quand même 
mais une pénalité est donnée).
Il est cependant recommandé de mettre le nom dans le cas de nombreuses conditions.
L'analyse de la réponse vérifie que la condition est bien réalisée sans remplacement.
Quelques tests supplémentaires sont ajoutés. Par exemple, si la condition
est <tt>A=Centre[c]</tt>, on vérifiera aussi si l'utilisateur a répondu 
quelque chose comme <tt>c=Cercle[A,B]</tt>.

<p>Exemples : 
<pre>
A=Point -> A doit être un point
=Cercle[D,E] -> Il doit y avoir un cercle de centre D passant par E (le nom n'a pas d'importance)
c=Cercle[,B] -> Il doit y avoir un cercle c passant par B
d2=Perpendiculaire[A,d1] -> d2 doit être la perpendiculaire à d1 passant par A
</pre>
</li>
<li><tt>"condition numérique"</tt> :
les conditions numériques doivent être construites à partir
des coordonnées des points ou des vecteurs ou des équations des droites, des cercles, etc. On peut utiliser :
<ul><li><tt>x_A, y_A</tt> : 
coordonnées d'un point <tt>A</tt> ou d'un vecteur <tt>A</tt>.</li>
<li><tt>R_c,x_c,y_c</tt> : 
carré du rayon d'un cercle <tt>c</tt>, coordonnées de son centre.</li>
<li><tt>a_d, b_d, c_d, p_d, m_d</tt> : 
coefficients d'une équation de la droite <tt>d</tt> du type <tt>ax + by = c</tt>, 
ordonnée à l'origine et coefficient directeur.
</li>
<li><tt>v_ob</tt> : valeur d'un objet (nommé "ob") qui peut être du type <tt>segment,function,angle,numeric,text</tt>
.</li>
<li>
<tt>x2_c,y2_c,xy_c,x_c,y_c,cst_c</tt> : coefficients de <tt>x^2, y^2, x*y, x,y, 1</tt> d'une conique
<tt>c</tt>.
</li>
</ul>
On peut aussi tester des équations par exemple, <tt>eq_a:2x+y=3</tt> (ou <tt>eq_:2x+y=3</tt>
si on ne désire pas donner d'importance au nom de la droite) teste si 2x+y=3 est une équation de la droite <tt>a</tt>.
<p>
<b>Exemple</b> : <tt>x_c>0 && y_c>0 & R_c<4</tt> demande de tester si le cercle <tt>c</tt>
a un centre dont les coordonnées sont positives et un rayon inférieur à 2.
(L'utilisation des noms des objets pour formuler les "tests numériques" est
obligatoire.) Dans le cas d'égalité, utiliser le test <tt>==</tt>. Il est recommandé
de faire des tests d'inégalité plutôt que des égalités :<tt> abs(x_c-1.2)<10^(-6)</tt>
par exemple, plutôt que <tt>x_c==1.2</tt>. 
</li>
<li><tt>"condition numérique-formelle"</tt>La syntaxe est la même que pour les
conditions formelles mais l'analyse est faite numériquement avec une 
très grande précision (par défaut 10^(-18)). Les noms des objets à 
l'intérieur des commandes doivent être donnés.
Le remplacement numérique est fait à l'aide des données numériques 
de la réponse de l'utilisateur.
<p>
Exemple :
<pre>
n,a=Droite[A,B] -> a doit être la droite passant par A et B (vérification numérique)
</pre>
</li>
</ul>


<p>Une seule réponse du type <tt>geogebra</tt> est possible pour l'instant.
On doit obligatoirement utiliser la commande <tt>embed</tt> pour l'utiliser :
<p>
<tt>\embed{reply1,\option}</tt>
<p>
où </tt>\option</tt> a comme première ligne la taille de l'applet en pixels (Largeur x Hauteur). 
Les lignes suivantes sont formées d'options de l'applet ou de commandes 
(objets prédéfinis). Par exemple :
<pre>
showToolBar=true
customToolBar=0|40|2|10
A = (1,2)
B = (-1,2)
a = Droite[A,B]
setFixed('A',true)
setFixed('B',true)
setAxesVisible(false,false)
</pre>
Les options possibles sont :
<pre>
showToolBar (default : true)
showMenuBar (default : false)
showResetIcon(default : true)
showToolBarHelp(default : true)
enableRightClick(default : true)
showAlgebraInput(default : false)
customToolBar
file
</pre>
Les commandes possibles sont :
<pre>
evalCommand setValue setCoords setColor setVisible setLabelVisible setLabelStyle 
setFixed setTrace setAxesVisible setGridVisible setCoordSystem
</pre>
Pour plus de détails, voir l'aide de GeoGebra sur les méthodes javascript disponibles :<br>
http://www.geogebra.org/source/program/applet/geogebra_applet_javascript.html
<p>
La variable <tt>\reply</tt><i>n</i> où <i>n</i> est le numéro du champ de réponse est formée
de plusieurs lignes. La première ligne donne le nombre d'objets. Les lignes suivantes
contiennent la définition de chaque objet (une ligne par objet), d'abord formellement
si cela est possible, puis numériquement.
</p>

<p>La variable <tt>\sc_reply</tt><i>n</i> contient sur la première ligne : 0 (mauvaise réponse),
0.5 (erreur de nom seulement) ou 1 (bonne réponse);
sur les lignes suivantes, le même détail (0, 0.5 ou 1) pour chaque ligne de la bonne réponse
</p>

<p><b>Options</b> :
<ul>
<li><tt>max</tt> nombre maximum d'objets qui peuvent être construits dans l'applet
(par défaut : 10).
</li><li><tt>precision</tt> : précision absolue (nombre de décimales prises en compte pour
les comparaisons numériques, défaut : 18).
</li><li><tt>idontknow</tt> (<tt>yes</tt> or <tt>no</tt>, par défaut : <tt>no</tt>) : 
fait apparaître un bouton "Je ne sais pas" à côté du bouton "Valider". 
</li><li><tt>extra</tt> (<tt>yes</tt> or <tt>no</tt>, par défaut : <tt>no</tt>) : 
autorise les objets supplémentaires (si l'option <tt>extra</tt> n'est pas égale à "yes", 
le score est diminué dans le cas où il y a plus 
d'<i>objets construits par l'étudiant</i> 
qu'il n'y avait de <i>conditions formelles</i> données dans la bonne réponse par
l'auteur de l'exercice.)
</li><li><tt>output</tt> : les valeurs possibles sont <tt>coord</tt> (défaut), 
<tt>formal</tt>, <tt>nothing</tt>.
La différence se trouve dans la manière dont les objets construits par l'utilisateur
sont réaffichés dans l'analyse de la réponse :
<ul><li><tt>coord</tt> : les coordonnées des objets sont affichés</li>
<li><tt>formal</tt> : les relations formelles sont affichées si elles existent</li>
<li><tt>nothing</tt> : aucun affichage</li>
</ul>
</li><li><tt>weights</tt> (par défaut, 1&0.2&1) le score final de la construction est
la moyenne pondérée de 3 scores dont on peut ici préciser les coefficients
(séparés par des "&"). Ces 3 scores sont respectivement le score des "tests formels" (f),
le score des noms des objets demandés, le score des "tests numériques"  (n).
</li></ul>

<p><b>Remarques générales</b> :
<ul>
<li>L'applet GeoGebra doit se trouver dans le répertoire 
<tt>public_html/java/geogebra3</tt>.
Elle nécessite l'installation de Java sur l'ordinateur local et 
l'utilisation du type de réponse <tt>geogebra</tt> risque de ralentir 
le chargement des pages : il ne faut l'utiliser que si le recours 
à la géométrie dynamique est utile.
</li>
<li>Les objets dont le nom commence par "My_" ne seront pas reconnus par wims et ne seront pas réaffichés lors de l'analyse de la réponse.
</li>
<li>
Les mesures des angles sont toujours en degrés. 
</li><li>
Une fonction <tt>f</tt> a pour nom 
<tt>f(x)</tt>. 
Il faut donc écrire quelque chose du type <tt>f(x)=sin(x)</tt>.
</li>
</ul>

