!!!Don't translate for the moment

<b>Clic sur des atomes d'une molécule en 3D</b> (nécessite java) (nom : <tt>jmolclick</tt>)

Une molécule est présentée dans l'applet jmol et on doit cliquer sur certains des atomes. 
Ce type de réponse doit être utilisé avec la commande <tt>\embed{}</tt>. 
La première ligne de la commande <tt>\embed</tt> est formée de la taille en pixels de l'applet
X x Y. Sur la deuxième ligne, des mots d'option peuvent être mis. Pour l'instant seulement,
<tt>file=adresse</tt> où <tt>adress</tt> est l'adresse du fichier décrivant la molécule de format
pouvant être lu par l'applet jmol. Ce fichier doit être dans un répertoire <tt>data</tt> du module, 
dans le répertoire data de la distribution wims (adresse <tt>data/xxx</tt>) ou 
dans un module de données dans modules/data (dans ce cas, l'adresse est de la forme 
datamodule/xxx).

La bonne réponse est donnée par la liste des numéros des atomes dans le fichier.