
<b>Surligner au marqueur</b> (nom : <span class="tt wims_code_words">mark</span>)
<br />
:option:split eqweight color=" "
Le type <span class="tt wims_code_words">mark</span> compare les mots ou expressions
cliqués par l'utilisateur avec une liste de bonnes réponses définies par l'enseignant.
Il est principalement destiné à une utilisation dans le texte de l'énoncé.
Le ou les mots changent de couleur lorsque l'utilisateur clique dessus,
pour indiquer ses choix. Par défaut l'analyse est réalisée de manière stricte.
Pour écrire les énoncés, il faut séparer chaque terme à analyser par une virgule.
Par conséquent, remplacer les virgules du texte par le code html
&amp;#44; ou par \(,). En procédant ainsi la virgule n'interfére pas
avec l'analyse de la réponse.

<pre>
\text{enonce=Pour, commercialiser,et, donc, vendre, ses, produits\(,), il, a, besoin, d'un, véhicule, de, fonction.}
</pre>
Dans l'exemple précédent, on a donc 14 items.
<br />
La syntaxe générale de ce type de réponse est :
<pre>
\answer{Commentaire}{7,10;\enonce}{type=mark}
\answer{question 3}{1,4,7;juste1,faux1,très faux,juste2,faux2,faux3,juste3}{type=mark}{option=split}
\answer{question 4}{1,4,7;juste1,faux1,très faux,juste2,faux2,faux3,juste3}{type=mark}{option=split eqweight color=#754595}
</pre>
Les options possibles proposent donc plusieurs notations :
<ul>
<li><span class="tt wims_code_words">color</span> : Cette option permet
de spécifier la couleur du surligneur avec un code html ou les couleurs
standard définies en html5.
</li>
 !read help/anstype.fr/spliteqweight.phtml
</ul>
