 <b>Nombre.</b> (nom: <tt class="wims_code_words">numeric</tt>)<br>
 Comparaison de nombres réels avec la précision définie par l'auteur.
 
 Si le mot <tt class="wims_code_words">comma</tt> est présent dans l'option, l'écriture 
 des nombres décimaux avec une virgule décimale est acceptée 
 (mais la bonne réponse doit être un nombre avec le point décimal). Si la
 réponse est mauvaise, la bonne réponse est donnée avec le même "séparateur"
 décimal que celui donné par l'élève. 