<b>Cocher une ou des cases</b> (noms : <span class="tt wims_code_words">radio</span>
et <span class="tt wims_code_words">checkbox</span>)
:option:sort split eqweight shuffle sort
<br />
Le type <span class="tt wims_code_words">radio</span> (resp.
<span class="tt wims_code_words">checkbox</span>) analyse la case cochée
(resp. les cases cochées) par l'élève et compare à la bonne réponse.
Par défaut la note est 0 dès que sa réponse ne s'accorde pas exactement à
la réponse attendue dans le cas <span class="tt wims_code_words">radio</span>
et si sa réponse n'est pas une des bonnes réponses dans le cas
<span class="tt wims_code_words">checkbox</span> (sauf avec l'option
<span class="tt wims_code_words">split</span>).
<br />
La syntaxe générale est :
<pre>
\answer{Commentaire}{1,4;juste1,faux1,très faux,juste2,faux2,faux3}{type=radio}
\answer{question 2}{1,4;juste1,faux1,très faux,juste2,faux2,faux3}{type=radio}{option=shuffle}
\answer{question 1}{1,4;juste1,faux1,très faux,juste2,faux2,faux3}{type=checkbox}
\answer{question 3}{1,4,7;juste1,faux1,très faux,juste2,faux2,faux3,juste3}{type=checkbox}{option=sort split}
\answer{question 4}{1,4,7;juste1,faux1,très faux,juste2,faux2,faux3,juste3}{type=checkbox}{option=sort eqweight}
</pre>
<ul><li><span class="tt wims_code_words">radio</span> :
L'élève ne peut sélectionner qu'une réponse et les options possibles sont uniquement
<span class="tt wims_code_words">shuffle</span> ou <span class="tt wims_code_words">sort</span>.
</li><li><span class="tt wims_code_words">checkbox</span>:
L'élève peut sélectionner une ou plusieurs réponses. Les options possibles sont plus variées :
<ul><li> <span class="tt wims_code_words">shuffle</span>:
Ordre des réponses aléatoires
</li><li><span class="tt wims_code_words">sort</span>:
Réponses dans l'ordre alphabétique
</li>
 !read help/anstype.fr/spliteqweight.phtml
 </ul>
</li></ul>
