 <b>Nombre avec zone.</b> (nom: <span class="tt wims_code_words">range</span>)<br/>
 Comparaison de nombres réels dans une zone : la bonne réponse est composée
 de deux nombres, m et n, séparés par une virgule, avec m&lt;n. Toute entrée
 comprise entre m et n (inclusive) sera acceptée.
 <p>
 Des intervalles multiples peuvent être donnés en ajoutant plus
 d'items dans la bonne réponse.
</p><p>
 Si la bonne réponse contient un nombre impair d'items,
le dernier sera utilisé pour montrer la bonne réponse.
</p>
La macro slib <span class="tt wims_code_words">text/approximation</span> peut être utilisée pour calculer
 ces trois nombres automatiquement.
