 <b>Raw text.</b>
 (nom: <tt>raw</tt>)
 <br> Un texte à comparer avec la bonne réponse donnée. 
  Les options suivantes permettent de contrôler comment le texte
 doit être transformé avant d'être comparé. 
Si aucune option n'est indiquée, seuls les espaces en début et 
 en fin du texte sont enlevés avant comparaison. 
Il faut donc faire très attention en utilisant ce type de réponses : 
par défaut, la réponse est considérée comme fausse même s'il y a 
un espace de différence. Ce type est destiné aux auteurs désirant
analyser eux-même la réponse. 
<p>
 Options: <ul>
 <li><tt>noaccent</tt>: enlève les accents sur les lettres.</li>
 <li><tt>nocase</tt>: transforme les lettres en minuscule.</li>
 <li><tt>nodigit</tt>: remplace les chiffres par des espaces.</li>
 <li><tt>nomathop</tt>: remplace les opérateurs mathématiques par 
des espaces</li>
 <li><tt>noparenthesis</tt>: remplace les parenthèses par des espaces.</li>
 <li><tt>nopunct</tt>: remplace les ponctuations par des espaces.</li>
 <li><tt>noquote</tt>: remplace les apostrophes ou guillemets
 (simple et double)  par des espaces.</li>
 <li><tt>nospace</tt>: enlève tous les caractères d'espace 
 (y compris ceux provenant de remplacement d'autres caractères). </li>
 <li><tt>reaccent</tt>: permet les lettres accentuées précédées de \</li>
 <li><tt>singlespace</tt>:  traite toutes les chaînes de caractères
 d'espaces comme un seul espace. </li>
 </ul>
