
 <b>Ensemble fini (textuel, formel et approximatif).</b>
 (names: <tt>set</tt>, <tt>fset</tt> et <tt>aset</tt>)

 C'est une liste d'éléments séparés par des virgules dont l'ordre
 n'a pas d'importance.
 <p>
 Pour <tt>set</tt>, aucune évaluation n'est effectuée avant la
 comparaison (donc 2 et 1+1 ne sont pas pareils). Si le mot "repeat" 
 est présent dans l'option, les répétitions des éléments sont
 demandées comme dans la bonne réponse. 
 Sinon, la réponse est considérée comme partiellement bonne.

 <p>
 Pour <tt>fset</tt> les éléments sont évalués 
 en tant qu'<em>expressions formelles</em>.
 <p>
 Pour <tt>aset</tt>, les éléments sont évalués en tant
 qu'<em>expressions approximatives</em>.

