
<b>Données physiques avec nombre précis de chiffres significatifs.</b> 
(nom : <tt>sigunits</tt>)<br>
La réponse de type texte est comparée à une bonne réponse donnée. La
syntaxe est&lt;nombre&gt; [&lt;unité physique&gt;] 
[#&lt;nombre prescrit de chiffres significatifs&gt;]
[,&lt;unit&eacute; physique souhait&eacute; &agrave; l'affichage&gt;]
<p>
Exemple:
<ul>
<li><b>1m#3</b> signifie 1 mètre avec 3 chiffres significatifs. Synonymes:
   <i>1.00m</i>, <i>0.00100 km</i>.</li>
<li><b>100.0 N</b> a la même signification que <i>1e2N#3</i>: 100
newtons avec 3 chiffres significatifs.</li>
<li><b>0.50A.h</b> donnerait "1.8e+02 C" &agrave; l'affichage. Utiliser
    <b>0.50A.h</b> pour avoir "5.0e-01 A.h".
</ul> 
</p>

