!if $wims_read_parm=synonym
<p>
Vous pouvez définir des synonymes dans la bonne réponse. Pour cela,
ajoutez simplement les synonymes après la bonne réponse (standard),
précédés de la barre verticale (tube) <span class="tt wims_code_words">|</span>.
On peut définir un nombre quelconque de synonymes.
</p>
!endif

!if $wims_read_parm=badonly
<p>
Pour que la réponse de l'élève soit obligatoirement contenue dans un champ lexical donné,
 on peut définir des mauvaises réponses en utilisant le point virgule
 <span class="tt wims_code_words">;</span> comme séparateur puis le tube
 <span class="tt wims_code_words">|</span> pour mettre plusieurs mauvaises réponses.
 Si la réponse donnée par l'élève n'est pas incluse dans ce champ lexical,
 il est demandé à l'élève de compléter à nouveau la réponse pour forcer
 l'utilisation d'un des mots du champ lexical.
Les signes de ponctuation seront ignorés dans cette liste et les mots
sont comparés avec le même niveau de tolérance que pour les bonnes réponses.
</p>
!endif
