
<b>Texte (sensible ou non à la casse : majuscules/minuscules).</b>
(noms : <span class="tt wims_code_words">case</span> et <span class="tt wims_code_words">nocase</span>)
<br/>
La réponse est comparée comme texte à une bonne réponse donnée. Dans
le cas <span class="tt wims_code_words">case</span> (sensible à la casse), chaque mot de la réponse
doit être exactement le même que le mot correspondant de la bonne
réponse.
Les expressions du type e' sont transformées en é (réaccentuation). 
Pour l'éviter, utiliser l'option <span class="tt wims_code_words">noreaccent</span>. 

!read help/anstype.fr/syno.phtml

