
<b>Texte (sensible ou non à la casse : majuscules/minuscules).</b>
(noms : <tt>case</tt> et <tt>nocase</tt>)
<br>
La réponse est comparée comme texte à une bonne réponse donnée. Dans
le cas <tt>case</tt> (sensible à la casse), chaque mot de la réponse
doit être exactement le même que le mot correspondant de la bonne
réponse.
Les expressions du type e' sont transformées en é (reaccentuation). 
Pour l'éviter, utiliser l'option <tt>noreaccent</tt>. 

!read help/anstype.fr/syno.phtml

