 <b>Mots d'une liste.</b> (nom : <tt>wlist</tt>)<br>
Dans ce cas, la réponse de l'utilisateur est comparée mot pour mot
avec la bonne réponse, sans tenir compte de l'ordre. Et la comparaison
n'est faite que sur les éléments essentiels des mots : les différences
majuscule/minuscule, certaines différences singulier/pluriel (s en fin
de mot), les accents sur les lettres, les mots très communs en anglais
(a, the, ...)  sont ignorés.
<p>
Si le premier mot de la bonne réponse donnée est un nombre positif n,
cela signifie que la réponse de l'utilisateur doit avoir au moins n
mots différents égaux à ceux listés dans la bonne réponse donnée.
</p>

!read help/anstype.fr/syno.phtml badonly

