!set proc=oef
<p><center><hr width="35%"></center> <p>

!if ////classes/ isin ////$module
 !set class_header=wimshome/log/classes/$wims_class/
!endif

!read $(class_header)Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=$[min($exocnt,8)]
!if $exocnt<1
 !if $wims_user=supervisor and #classes/ isin #$module
  !href module=adm/createxo Kliknite tukaj
  za ustvarjanje vaj.
 !else
 Oprostite, ta modul trenutno ne vsebuje nobene dostopne vaje. Poskusite kdaj drugiè.
 !endif
 !exit
!endif
!if $exocnt=1
 Ta modul trenutno vsebuje eno samo vajo, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Preizkusite jo.
 !exit
!endif

!form new
<input type=hidden name=module value="$module">
<center><table border=0><tr>
!set special_parm=!trim $special_parm
!if select iswordof $special_parm2 and $special_parm!=$empty
 <td align=center>Exercises containing<br>
 <em><font color=blue>$special_parm</font></em>&nbsp;:<td>
!else
 <td align=center>Izberite vaje:<td>
!endif
!read oef/select.phtml
<tr><td align=center>©tevilo vaj v posameznem nizu naj bo<td>
!set qnum=1
!formselect qnum from 1 to 9
.
<tr><td align=center>Stopnja zahtevnosti <td>
!set qcmlevel=3
!formselect qcmlevel from 1 to 9
<tr><td align=center>Èasovna omejitev: <td>
<input size=7 name=scoredelay value="$scoredelay"> sekund.
!read introhook.phtml
!if expert iswordof $special_parm2
   <tr><td align=center>
   ©tevilo mo¾nih odgovorov pri vpra¹anjih izbirnega tipa: <td>
   !default intro_qcmpresent=4
   !formselect intro_qcmpresent list 2,3,4,5,6,7,8 
   <tr><td align=center>Vrni pravilno re¹itev (èe je na voljo)? <td>
   !default intro_presentsol=1
   !formselect intro_presentsol list 0,1,2 prompt nikoli,èe rezultat ni maksimalen,vedno
   <tr><td align=right>
   !default intro_check=1,2,3,4
   Vpra¹anja izbirnega tipa</td><td>
   !formcheckbox intro_check list 1 prompt Vedno je podan
   pravilen odgovor.
   <tr><td rowspan=3>&nbsp;</td><td align=left>
   !formcheckbox intro_check list 2 prompt Kazen za izbiro napaènih odgovorov.
   <tr><td align=left>
   !formcheckbox  intro_check list 3 prompt Poka¾i pravilen odgovor.
   <tr><td align=left>
   !formcheckbox intro_check list 4 prompt Dovoli namig (èe je pripravljen).
   !let tmp=!replace word expert by $ in $special_parm2
   <tr><td colspan=2 align=center>
   !href module=$module&special_parm=$special_parm&special_parm2=$tmp Osnovni meni
   <input type=hidden name=intro_expert value=yes>
!else
   <tr><td colspan=2 align=center>
   !let tmp=$special_parm2 expert
   !href module=$module&special_parm=$special_parm&special_parm2=$tmp Raz¹irjeni meni
!endif
</table></center> <p><center>
<input type=submit value="Zaèni z delom">&nbsp;
<input type=submit name=print value="Razlièica za tiskanje">
</center>
</form>

!if $exocnt>10
 !form intro
 <input type=hidden name=special_parm2 value=select>
 <input type=hidden name=module value="$module">
 Izberi naslove, ki vsebujejo besedo
 <input size=12 maxlength=12 name=special_parm value="$oldparm">
 <input type=submit value=OK>
 </form>
!endif

<b>Opomba</b>. Niz bo sestavljen iz nakljuènega zaporedja vaj, ki ste jih oznaèili, ali med vsemi vajami, èe niste oznaèili nobene.

!if * isin $titlelist
 <p>Vaje oznaèene z * so obièajno zahtevnej¹e od ostalih.
!endif

<p><small>Za èasovno omejitev lahko predpi¹ete tudi dve razlièni vrednosti: najprej manj¹o, nato veèjo. V tem primeru bo prva spro¾ila le odbijanje toèk, èe pa je prese¾ena tudi druga, bo rezultat naloge avtomatsko 0 toèk.
</small>
