
$wims_html_header
<body $wims_htmlbody>

<p><center><h3>
!href module=$module&cmd=intro WIMS
 $module_title<br>
<font size=-1>--- Razlièica za tiskanje ---</font></h3></center> <p>
<div class=wimsbody>

!if $error!=$empty
 !changeto oef/msg.phtml
!endif

!for i=1 to $n
 <p>
 <b>Vaja</b> $i. (<u><em>$(title_$i)</em></u>)
 !if $(question_$i)=$empty
  Te vaje ni moè natisniti.
 !else
  !if __EXECUTED_ isin $(question_$i) and _EXERCISE__ isin $(question_$i)
   !set thisexo=$(name_$i)
   !readproc oef/imagedir.proc
   !for k=1 to $(varcnt_$i)+5
    !set val$k=!line $k of $(var_$i)
   !next k
   !read $(class_header)def/$(name_$i).def question
  !else
   $(question_$i)
  !endif
  </a></tt></font></center>
  </h1></h2></h3></h4></b></i></em>
  $(chce_$i)
 !endif
!next i

!if $wims_user!=$empty and $wims_user!=supervisor
 !goto noans
!endif

<p><hr> <p>
<center><h3>Odgovori:</h3></center> <p>
!for i=1 to $n
 !set t=!linecnt $(ans_$i)
 !if $t>0
  <p><b>Re¹itve vaje $i.</b><ul>
  !for k=1 to $t
   <li>
   !line $k of $(ans_$i)
  !next k
  </ul>
 !endif
!next i

:noans
</div> <hr> <p>
<center>
!href cmd=reply&print=yes Ponovno
&nbsp;&nbsp;
!href module=$module&cmd=intro Nazaj
</center>

