!set job2=first

De server / platform verbinding geeft Uw klas de mogelijkheid om rechtstreeks
met een andere WIMS server of zelfs met een ander netwerkgebaseerde ELO
(Electronische Leer Omgeving) te communiceren.
De leerlingen kunnen zonder problemen door de klassen op beide servers navigeren.  
<p>
In het bijzonder, kunt U uw klas "spiegelen" op een andere WIMS server,
zodat er continuiteit kan onstaan in het aanbod van lesmateriaal.
De behaalde Cijfers kunnen later ook worden samengevoegd 
<p>
!if $ccnt<1
Deze WIMS server heeft nog geen remote server gedeclareerd.
Om deze geavanceerde mogelijkheid te gebruiken, schrijf naar de 
 <a href="mailto:$wims_site_manager?subject=server connection">site
 manager</a> om een dergelijke voorziening te treffen, natuurlijk
 moet de remote WIMS server deze WIMS server wel erkennen...
 !set basedir=!sh cd ..; pwd
 (De site manager kan hier leren hoe het een en ander  
 <tt>$basedir/log/classes/.connections/myself</tt> administratief geregeld moet worden
 
 !exit
!endif
Deze WIMS server heeft de volgende <em>remote servers</em> gedeclareerd:.
<p>$table_header
$table_hdtr<th>Naam
<th>Beschrijving<th>Adres<th>Type<th>Actie
!for s in $Clist
 $table_tr
 <td>$s
 <td align=center>$(desc_$s)
 <td align=center><a href=$(url_$s)>$(site_$s)</a>
 <td align=center>$(type_$s)
 <td align=center nowrap><small>
 !href cmd=reply&job2=testserver&connident=$s Test
 &nbsp;
 !href cmd=reply&job2=add1&connident=$s Voeg een verbinding toe
 </small>
!next s
$table_end <p>

!if $clcnt<1
Deze klas heeft geen verbinding met andere servers
 
 !exit
!endif
U hebt de volgende verbindingen met andere <em>remote servers</em> gedeclareerd:
<p>$table_header
!distribute items yes,no into io1,io0
$table_hdtr<th>Server<th>klas
<th>-<th>-<th>-<th>-
!for clc in $cllist
 !distribute words $clc into n_,c_,o_,i_
 $table_tr
 <td>$n_<td align=center>$c_
 <td>
 !href cmd=reply&job2=testclass&connident=$n_&connclass=$c_ Testen
 <td>
 !href cmd=reply&job2=mod1&connident=$n_&connclass=$c_ Configureren
 <td>
 !href cmd=reply&job2=del1&connident=$n_&connclass=$c_ Verwijderen
 <td>
 !href cmd=reply&job2=del1&connident=$n_&connclass=$c_&connopt=destroy Verwijder de klas op de andere server
!next clc
$table_end <p>

