
Si vous êtes un enseignant, et si vous voulez créer une classe virtuelle sur
ce site pour le travail de vos élèves, essayez  
!href module=adm/class/regclass cliquer ici
. Vous pouvez aussi
!href module=adm/class/classes&type=example cliquer ici
 pour voir si ce site contient une classe d'exemple (ou une classe qui n'est
pas protégée par un mot de passe). Si oui, vous pouvez vous y inscrire pour
voir comment elle fonctionne (en tant qu'élève).
<p>
Chaque site WIMS peut avoir sa propre politique sur l'hébergement de classes.
Certains acceptent librement des classes virtuelles créées par n'importe
qui, d'autres pourraient demander des frais de maintenance ou poser d'autres
restrictions. Veuillez vérifier auprès du gestionnaire du site pour les
conditions.
<p>
Par raison de sécurité, vous devez avoir une adresse électronique qui
fonctionne au moment de la création de votre classe. Quand vous aurez rempli
le formulaire pour les informations nécessaires concernant votre classe, un
code aléatoire est généré par le serveur. Ce code est envoyé à votre adresse
électronique, et vous pouvez l'avoir uniquement en lisant votre message
électronique. Vous devez ensuite resoumettre ce code dans un formulaire html
pour authentification, sinon votre création de classe sera refusée.
<p>
Cette adresse électronique sera aussi visible par les participants (élèves) 
inscrits dans votre classe, leur permettant de vous envoyer des messages.
<p>

Après qu'une classe est créée, vous devenez l'enseignant de la classe, et
vous pouvez vous y connecter en tant que tel, pour gérer la classe (création
de feuilles de travail, mise en place de devoirs dans les feuilles, contrôle
de progrès de participants, etc.).
<p>
Il y a plusieurs façons de permettre les inscriptions de
vos élèves dans votre classe, via l'utilisation d'un <em>`mot de passe de
classe'</em> que vous devez définir quand vous créez votre classe&nbsp;:<ul>
 <li>Vous créez votre classe `grande ouverte', en mettant un mot de passe de
 classe vide, permettant ainsi à n'importe qui de s'y s'inscrire comme participant.
 Ce mode est déconseillé car vous perdriez le contrôle de votre classe.
 Beaucoup de sites interdiront aussi ce genre de classes (vous verrez votre
 classe fermée immédiatement par le gestionnaire du site), sauf les classes
 d'exemple mises en place par le gestionnaire du site lui-même.
 <li>Vous désignez un mot de passe de classe et le gardez secret. De cette
 façon vous serez la seule personne pouvant y inscrire des participants.
 <li>Vous désignez un mot de passe de classe et le communiquez à vos élèves.
 En utilisant ce mot de passe, vos élèves seront en mesure de s'y inscrire
 eux-mêmes, mais les personnes extérieures ne peuvent pas y entrer.
</ul> <p>

