<p>Un groupement de classes est un ensemble de classes virtuelles (appelées sous-classes) 
accessibles par un seul point d'entrée sur le serveur (appelé le portail du groupement).
</p>
<p>
L'enseignant qui créé le groupement de classes a un statut différent des enseignants
qui gèrent une sous-classe : il a le statut d'administrateur (il ne dispose pas de login 
mais seulement d'un mot-de-passe). 
</p>
<h2 class="wimscenter"> Particularités</h2>
Les particularités d'une groupement de classes par rapport à un ensemble de classes individuelles 
créées sur le serveur sont les suivantes :
<ul><li>
 Un participant qui a accès à plusieurs classes wims dans un groupement de classes, 
 n'aura qu'un login et un mot-de-passe.
</li><li> 
Une classe à l'intérieur d'un groupement peut avoir plusieurs enseignants.
</li><li> 
Le portail dispose  d'un forum visible par tous les participants du groupement, 
 qui est configurable par l'adminstrateur. L'adminstrateur
a la possibilité d'écrire un texte visible par tous au niveau du portail
(équivalent du mot-du-jour dans une classe individuelle).
</li>
<li> Le partage de ressources est possible uniquement entre sous-classes du même groupement 
(il est aussi possible de récupérer des ressources des classes ouvertes).
</li></ul>
Toutes les fonctionnalités d'une classe indépendante existent dans une sous-classe. 
Il n'y a pas de sauvegarde au niveau du portail du groupement : 
les sauvegardes des sous-classes se font au niveau de chaque sous-classe.
<p>
<h2 class="wimscenter">Configuration du portail du groupement</h2> 
 Lors de la création du portail, 
l'adminstrateur choisit un mot-de-passe qui sert aux enseignants pour s'inscrire 
et créer leur classe à l'intérieur du groupement. Il choisit la façon dont les 
participants et enseignants seront  authentifier dans le groupement
de classes. Il peut inscrire les enseignants et les participants à partir du 
portail manuellement ou en utilisant
la liaison tableur. Il peut lui-même créer les sous-classes 
(il sera alors aussi l'administrateur des sous-classes).
Il a accès aux différentes sous-classes du groupement. 
</p>
<h2 class="wimscenter">L'administrateur d'une sous-classe</h2>
L'enseignant qui a créé une sous-classe  est considéré comme l'administrateur de 
cette sous-classe et a un statut un peu différent des autres enseignants de la sous-classe : 
il peut donner un accès de gestion à d'autres enseignants inscrits dans le groupement de classes. 
<h2 class="wimscenter"> Inscription des participants dans une sous-classe</h2>
N'importe quel enseignant d'une sous-classe peut inscrire un élève dans la 
sous-classe, qu'il soit on non déjà inscrit dans le groupement de classes. 
Un élève inscrit dans une sous-classe est automatiquement inscrit dans le groupement
de classes.
<p>
Un élève peut aussi s'inscrire lui-même dans une sous-classe si on lui a donné le mot-de-passe
d'inscription choisi par  l'enseignant qui a créé la sous-classe.
</p>