Un établissement est un rassemblement multi-niveaux de classes virtuelles,
capable de gérer le besoin d'un établissement d'enseignement. Différentes zones permettent
aux enseignants de mettre les mêmes ressources à la disposition de différents groupes d'élèves.
Les élèves accèdent aux ressources proposées par différents enseignants à partir
d'un même point d'entrée (appelé le portail de l'établissement).

L'enseignant qui crée l'établissement a un statut différent des enseignants
qui proposent des ressources pour un groupe d'élèves au sein de l'établissement :
il a le statut d'adminstrateur (il ne dispose pas de login mais seulement d'un mot de passe). 
<h2 class="wimscenter">Particularités</h2>
Les particularités d'un établissement par rapport à un ensemble de classes individuelles
créées sur le serveur sont les suivantes :
<ul><li>
  Un élève n'a qu'un login et un mot-de-passe pour accéder aux différentes
 ressources correspondant aux cours auxquels il est inscrit.
</li><li> Les élèves peuvent être divisés en groupes gérés séparément grâce aux zones appelées
 <em>`classes de l'établissement'.</em>
</li><li>  Un établissement peut être divisé en <em>`niveaux'</em> pour séparer les groupes d'élèves
 n'ayant aucun cours en commun, chaque niveau peut être géré par un enseignant différent.
</li><li>  Un enseignant dispose d'une <em>`zone programme'</em> pour mettre à disposition des ressources
 à un ou plusieurs groupes d'élèves et peut disposer d'une zone <em>`test'</em> associée à la
 <em>`zone programme'</em> pour préparer ses ressources et faire des tests.
</li><li>  Les enseignants voient le travail des élèves d'un groupe particulier et peuvent interagir
 avec eux via une zone appelée <em>`cours</em>.
</li><li>  Plusieurs enseignants peuvent avoir un accès de gestion à une même zone.
</li><li>  Le portail dispose d'un forum visible par tous les élèves de l'établissement,
 qui est configurable par l'adminstrateur. L'adminstrateur
a la possibilité d'écrire un texte visible par tous au niveau du portail
(équivalent du mot-du-jour dans une classe individuelle).
</li><li> Les zones <em>`classes'</em> et <em>`cours'</em> disposent aussi d'un forum et d'un emplacement
pour faire une annonce que les enseignants de ces zones peuvent configurer indépendamment.
</li><li> Le partage de ressources est possible entre zones <em>`programmes'</em> d'un même
niveau.
</li></ul>
Toutes les fonctionnalités d'une classe virtuelle individuelle existent dans la zone <em>`cours'</em>. 
<p>
Les principales particularités d'un établissement par rapport à un groupement de classes
sont les suivantes :
<ul><li>
Dans un établissement, les ressources pédagogiques et les groupes d'élèves sont séparés
et sont structurés par niveaux alors qu'un groupement de classes est un ensemble de
classes virtuelles individuelles auxquelles on accède par un seul login et mot de passe.
</li><li> Les zones <em>`test'</em>, permettant de restaurer d'une année sur l'autre les ressources et
de les modifier, n'existent que dans les établissements. Elles sont associées à un programme.
</li></ul>

<h2 class="wimscenter"> Les fonctions de chaque zone</h2>
<h3>Ce qu'un enseignant peut faire dans chacune des quatre zones (classe, test, programme, cours)</h3>
 <h4>Zone classe</h4>
 <ul><li>
 Il inscrit les élèves.
</li><li>
 Il met une annonce visible par tous les élèves inscrits dans cette classe.
 </li><li>
 Il configure le forum de cette zone~(il choisit qui peut voir et écrire sur ce forum).
</li></ul>
<h4>Zone test</h4>
 <ul><li>
 Il peut restaurer, à l'aide d'un fichier de sauvegarde, les ressources d'une ancienne classe individuelle ou d'une ancienne zone
 <em>`programme'</em> pour les modifier.
</li><li> 
Il prépare ses ressources pédagogiques : feuilles d'exercices, documents, questionnaires.
</li></ul> 
<h4>Zone programme</h4> 
<ul><li>
Il importe de la zone test les ressources pédagogiques terminées.
</li><li>
 Il choisit les différentes ressources pédagogiques (feuilles d'exercices, documents, questionnaires) que peuvent voir les élèves.
</li><li>
 Il crée les examens.
 </li></ul>
  <h4>Zone cours</h4>
<ul><li>
 Il fixe les paramètres qui gèrent la façon dont les élèves travailleront dans la classe (il
 autorise ou non la suspension de l'enregistrement des notes sur une feuille, fixe le nombre d'exercices
 que l'élève peut enregistrer ...).
 </li><li>
 Il peut modifier le barême des différentes feuilles (modifications qui se répercutent dans tous les
 cours associés au même programme).
 </li><li>
 Il peut fixer une plage horaire pendant laquelle les notes obtenues  sur une feuille seront
 enregistrées (paramétrage propre à chaque cours).
 </li><li>
 Il voit le travail effectué par les élèves sur les feuilles et examens, peut récupérer les notes
 de ses élèves, ajouter des notes pour des devoirs faits à l'extérieur de WIMS.
 </li><li>
 Il peut communiquer avec ses élèves en utilisant le forum, en mettant une
  annonce à tous les élèves ou une annonce personnelle à un élève, ou en envoyant un mail.
</li></ul>
<h3>Et un élève</h3>
<ul><li>
 En entrant dans l'établissement, il a une liste de liens vers
la classe (ou les classes) dans lesquelles il est inscrit ainsi que les cours 
auxquels il a accès.
</li><li>Il travaille dans les cours auxquels il a accès. 
</li></ul>
<h2 class="wimscenter">Création de la structure et inscription des participants
</h2>
Lors de la création du portail, l'administrateur choisit la façon dont les 
participants et enseignants vont s'authentifier. Il inscrit les enseignants. 
 Il crée les différents niveaux de l'établissement
 et à la demande des enseignants, crée les différentes zones (classes, programmes et cours)
 et leur donne des accès de gestion à ces zones (la gestion d'un niveau peut être 
 déléguée à un enseignant autre que l'administrateur; cet enseignant pourra alors créer
  lui-même les zones de son niveau).
<p>
N'importe quel enseignant gérant une zone <em>`classe'</em> peut inscrire un élève
 dans cette zone, qu'il soit ou non déjà inscrit dans l'établissement. Un élève 
 inscrit dans une zone <em>`classe'</em> est automatiquement inscrit dans l'établissement
  et a accès à toutes les zones <em>`cours'</em> associées à cette <em>`classe'</em>.
</p>
Il n'y a pas de sauvegarde
au niveau du portail de l'établissement : les sauvegardes
se font au niveau des zones <em>`programme'</em> et <em>`cours'</em> par les enseignants les utilisant.