
Les travaux dans une classe virtuelle sont organisés dans des feuilles de
travail.
<p>
Chaque classe virtuelle peut avoir jusqu'à 64 feuilles de travail, et chaque
feuille peut contenir jusqu'à 64 articles. Un article peut être n'importe
quel module de Wims&nbsp;: exercice, outil, ou autre.
<p>
Chaque feuille a un statut. Le statut d'une feuille nouvellement créée est
<em>en préparation</em>, ce qui permet aux articles de travail d'être
ajoutés et modifiés. C'est aussi le seul statut sous lequel la feuille peut
être effacée. Une feuille en préparation est visible uniquement par
l'enseignant.
<p>
Quand l'enseignant active une feuille en préparation, celle-ci devient
<em>active</em>. Elle n'est plus modifiable ni effaçable, et les participants
pourront travailler dessus.
<p>
Chaque feuille a une date d'expiration. Passée cette date, elle devient
<em>périmée</em>, dans ce cas les participants continuent à la voir et peuvent
travailler dessus, mais les notes ne seront plus enregistrées.
<p>
Et une feuille périmée peut devenir <em>cachée</em>, dans ce cas les 
participants ne la voient plus (mais elle est toujours visible par
l'enseignant).
<p>
L'enseignant peut manuellement basculer le statut d'une feuille entre
<em>active</em>, <em>périmée</em> et <em>cachée</em> (dans n'importe
quel sens).

