!default target1=$o1
!default target4=$o4
<table border=0 cellpadding=0 cellspacing=0>
<tr><td align=center><small>Zone</small></td>
<td></td><td align=center><small>catégorie</small></td>
<td></td><td align=center><small>nom</small></td>
<td></td><td align=center><small>lang</small></td>
</tr><tr>
<td align=center>
!formselect target1 list $zonelist
</td><td>~</td><td align=center>
<input type=text size=12 name=target2 value=$o2>
</td><td>~</td><td align=center>
<input type=text size=12 name=target3 value=$o3>
</td><td>.</td><td align=center>
!formselect target4 list $langlist
</td><td>
!href cmd=help&special_parm=addressing <sup>aide</sup>
!if nook notwordof $wims_read_parm
 &nbsp;<input type=submit value=OK>
!endif
</td></tr></table>
