!distribute items nuovi moduli, aggiornamento moduli, recenti modifiche del sistema into \
	name_new, name_modif, name_sys

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!header1
<h1 class="wims_title">$module_title
<br><font size="+0">$httpd_HTTP_HOST</font>
</h1>

<center>
!for j in $joblist
 &nbsp;
 !if $j=$job
  <u><b>$(name_$j)</b></u>
 !else
  !href cmd=reply&job=$j $(name_$j)
 !endif
 &nbsp;
!next j
</center><p>

!read $job.phtml

!tail

