
!if $datacnt<1
 Non sono stati registrati aggiornamenti del server. Questo meccanismo
 di registrazione degli aggiornamenti del server è stato introdotto
 con il modulo di inserimento e aggiornamento del sistema disponibile
 dalla versione 3.37f di WIMS.
 !exit
!endif

$table_header
<caption>Moduli recentemente aggiornati sul server</caption>
$table_hdtr<th>Data</th><th>Lingua</th><th>Titolo</th><th>Descrizione</th>
<th>Nuova<br>versione</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>
 $desc
 </td><td align=center>$v_</td></tr>
 !reset desc tit
!next i
$table_end
