!set name_warning_new=Non sono stati aggiunti moduli a questo server. Questo meccanismo\
 di registrazione degli aggiornamenti del server è stato introdotto\
 con il modulo di inserimento e aggiornamento del sistema disponibile\
 dalla versione 3.37f di WIMS.
 
!set name_warning_update=Non sono stati registrati aggiornamenti del server. Questo meccanismo\
 di registrazione degli aggiornamenti del server è stato introdotto\
 con il modulo di inserimento e aggiornamento del sistema disponibile\
 dalla versione 3.37f di WIMS.
!distribute line Nuovi moduli installati sul server\
  Moduli recentemente aggiornati sul server\
  Nuova<br>versione\
into name_newmodule,name_updatemodule,name_new