
!if $datacnt<1
 Non sono stati aggiunti moduli a questo server. Questo meccanismo
 di registrazione degli aggiornamenti del server è stato introdotto
 con il modulo di inserimento e aggiornamento del sistema disponibile
 dalla versione 3.37f di WIMS.
 !exit
!endif

!set w_=!replace internal /wims.cgi by in $wims_ref_name

$table_header
<caption>Nuovi moduli installati sul server
<a href="$w_/rss/new.xml"><img src="gifs/rss.png" border=0 alt=rss></a></caption>
$table_hdtr<th>Data</th><th>Lingua</th><th>Titolo</th><th>Descrizione</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_ 
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>$desc</td></tr>
 !reset desc tit
!next i
$table_end
