!! +exec+ +vardef+
$lst_tit bound$lst_titend$type_exec
  $(lst_syntax)bound $emph vname$emphend between [integer]
  $emph v1$emphend and $emph v2$emphend [default $emph defaultvalue$emphend]
  </tt> <br>或<br><tt>
  $!bound $emph vname$emphend within $emph list$emphend [default
  $emph defaultvalue$emphend]</tt>
  $lst_mean 把变量 $emph vname$emphend 限制在指定范围内. 
  通常用于用户提交的变量. <br>
  第一个用法是针对数值变量的(整数或实数, 默认实数).
  在这种情形, $emph v1$emphend 与 $emph v2$emphend 
  提供了变量 $emph vname$emphend 值的下界及上界. <br>
  在第二个用法, $emph vname $emphend 的值与 $emph list$emphend 的每一项比较.
  如果找不到匹配, 则当 $emph defaultvalue$emphend 给出时,
  $emph vname$emphend 取值 $emph defaultvalue$emphend, 否则,
  取 $emph list$emphend 的第一项. <br>
  不论何种情形, $emph defaultvalue$emphend 都是可选的.

