!! +exec+ +html+
$lst_tit formcheckbox$lst_titend$type_exec
  $lst_alias htmlcheckbox<br>
  $(lst_syntax)formcheckbox $emph name$emphend from $emph n1$emphend
    to $emph n2$emphend prompt $emph promptlist $emphend<br>
    </tt>或<tt> <br>
    $!formcheckbox $emph name$emphend list 
    $emph selectlist$emphend prompt $emph promptlist$emphend
    </tt> <br>
  $lst_mean 在前面定义的html表单下创建一个复选框菜单.<br>
  这个命令能加速复选框菜单的创建, 也能简化源文件.
  在参数中, $emph name$emphend 定义了菜单的名称,
  对第一句的格式, 菜单的值是从 $emph n1$emphend 到 $emph n2$emphend 的整数,
  对第二句的格式, 菜单的值是表 $emph selectlist$emphend 里的项. <br>
  可选参数 $emph promptlist$emphend 用于生成每个选框的提示.
  当 $emph promptlist$emphend 为空或少于 $emph selectlist$emphend 时, 
  未定义的提示将用值来代替. 如果太长, 则超过部分被舍弃. <br>
  菜单的默认值是变量 $emph $$name$emphend 的当前值.
  
  


