!! +exec+ +html+
$lst_tit form$lst_titend$type_exec
  $(lst_syntax)form $emph cmdvar$emphend</tt> <br>
  $lst_mean 创建指向wims服务器的html表单. <br>
  只有有可能, 请尽量使用这个命令代替
  html tag $emph&lt;form>$emphend. <br>
  此命令将创建一个指向wims服务器的 &lt;form> 标记, 增加
  &lt;input> 域以传送对话编号(以及保留在将来使用的其他内容).
  在以后的行里将添加其它输入(或选择)域到表单里.
  最后的 &lt;/form> 标记也应由编程者加进去. <br>
  $emph cmdvar$emphend 是可选参数. 它的值应该是变量 $emph cmd$emphend 的有效取值.
  在这种情形, $emph cmdvar$emphend 的值会自动送交给变量 $emph cmd$emphend.
  如果这个参数没有加或者无效, 那么编程者应该在最后的 &lt;/form> 前加上
  标记 &lt;input type=hidden name=cmd value=...>. <p>
  变量 $emph wims_ref_target$emphend 可以控制表单的目标. 这也可以通过选项词
  $emph target=...$emphend 实现. 请注意这时的目标必须以
  $emph wims_$emphend 起首.
  <p>
  变量 $emph wims_form_method $emphend 必须或者是 `get' 或者是
  `post', 以控制表单的方法.
  对工具模块来说, 这方法的默认值是 `post', 而对其它模块来说, 默认值是 `get'.


