!! +var+ +string+
$lst_tit getopt$lst_titend$type_both
  $(lst_syntax)getopt $emph name$emphend in $emph string$emphend</tt> <br>
  $lst_mean 本命令允许从以 $emph name=value$emphend 形式出现的
$emph string$emphend 中提取单词作为参数.
  <p>
它返回串内被定义的 $emph value$emphend；
如果串内出现 $emph name$emphend 但后面没有 $emph =$emphend 号,
则返回 $emph name$emphend 本身;
如果 $emph string$emphend 内找不到 $emph name$emphend, 则返回空串. 
  <p>
  $emph value$emphend 可以是多个词组成的串, 只要它们被一对圆括号, 方括号, 花括号
或双引号括起来. 在输出时, 这些定界符被抛弃.
  <p>
  $emph =$emphend 符号前后允许有空格.
  

