!! +exec+ +ins+
$lst_tit instex$lst_titend$type_pexec
  $(lst_syntax)instex $emph texsource $emphend</tt> <br>
  $lst_mean 服务器将调用TeX以处理(plain)TeX源码 $emph texsource$emphend (先作变量替换),
  把结果转换成图像, 在插到页面内命令所在的位置. <br>
  提示: 尽可能避免在 $emph texsource$emphend 内使用变量替换.
  这样wims将使用静态 instex, 效率远比动态 instex 高. <br>
  为控制插入内容的颜色, 可使用变量
  $emph instex_color$emphend, 或在 $emph texsource$emphend 内使用 <tt>\special{color=...}</tt>.
  
