!! +var+ +exec+ +string+
$lst_tit leveldata$lst_titend$type_both
  $lst_alias levelpoints
  $(lst_syntax)leveldata size $emph xsize,ysize$emphend
  ranges $emph x1,x2,y1,y2$emphend function $emph f(x,y)$emphend
  [levels $emph l1,l2,...$emphend]</tt>
  $lst_mean 计算 $emph f(x,y)$emphend 在水平 $emph l1,l2,...$emphend 
  (默认值是一个水平 0) 处的水平曲线上的点的坐标. <p>
  计算范围从 $emph (x1,y1)$emphend 至 $emph (x2,y2)$emphend, 
  计算图形内关于 $emph xsize,ysize$emphend 的整数位置的点. <p>
  参数区段的次序不重要, 但除了水平外都是必须的.
 

