!! +var+ +exec+ +string+
$lst_tit makelist$lst_titend$type_both
  $(lst_syntax)makelist $emph templ$emphend for $emph v$emphend=$emph v1$emphend
  to $emph v2$emphend [step $emph st $emphend], 或 <br>
$ !makelist $emph templ$emphend for $emph v$emphend in 
  $emph v1,v2,v3,...$emphend</tt> <br>
  $lst_mean 输出由 $emph templ$emphend 构成的表, $emph templ$emphend 是由变量
  $emph v $emphend 被值 $emph v1$emphend ..., $emph v2$emphend 逐个替换而得到的. <p>
  在第二句格式里, 替换成表 $emph v1,v2,...$emphend 里的各项. <p>
  变量 $emph v $emphend 应该作为数学变量出现在 $emph templ $emphend  里,
  (也就是说, 没有前置字符). <p>
  例如, 命令
<pre>!makelist [x;x+1;xx] for x in a,x and y,1,(2,3)</pre>
  的结果是
  <pre>
  !makelist [x;x+1;xx] for x in a,x and y,1,(2,3)
  </pre>

