!! +exec+ +var+ +string+
$lst_tit mathsubst$lst_titend$type_both
  $lst_alias mathsubstit, mathsubstitute
  $(lst_syntax)mathsubst $emph name="val" $emphend in $emph
  expr$emphend</tt>
  $lst_mean 数学式的操作: 把 $emph expr$emphend 里的变量
  $emph name$emphend 替换成 $emph val$emphend. <br>
  $emph name$emphend 里不准使用正则表达式. <br>
  参见
  $(ref1)cmdlist_evalsubst_&cmd_choose=all$(ref2)cmdlist_evalsubst_>!evalsubst</a>,
  $(ref1)cmdlist_replace_&cmd_choose=all$(ref2)cmdlist_replace_>!replace</a>.



