!! +exec+ +html+ +variable+
$lst_tit pedia$lst_titend$type_both
  $lst_alias encyclopedia, encyclo<br>
  $(lst_syntax)pedia $emph keyword$emphend,$emph name$emphend</tt> <br>
  $lst_mean 创建指向在线百科全书的超文本链接. <br>
  $emph keyword$emphend 是用于查找的关键词, 应该是由一个或几个由空格分隔的词.
  例如: $emph finite field$emphend 或 $emph linear transformation$emphend.
  <br>
  $emph name$emphend 是链接的名称(也就是人们在页面看到的可以点击链接名).
  <p>
  目前wims使用
  <a href=www.wikipedia.org>Wikipedia</a>
  作为标准参考百科全书.
