!! +var+ +random+
$lst_tit randint$lst_titend$type_var
  $(lst_syntax)randint $emph n1$emphend ,$emph n2$emphend</tt>
  $lst_mean 返回 $emph n1 $emphend 与 $emph n2 $emphend 之间随机选取的整数(包括两端). <br>
  先对 $emph n1 $emphend 和 $emph n2$emphend 作替换与赋值, 然后再作随机运算. <br>
  如果没有 $emph n2 $emphend, 则返回的整数位于 $(m_pm)1 与
  $emph n1 $emphend 之间(包括两端). <br>
  如果 $emph n1 $emphend 和 $emph n2 $emphend 都没有, 返回 0.
  <br>
  你也可以用 <tt>!randint n1,n2 repeat i</tt> 重复生成
  $emph i$emphend 个随机数.

