!! +var+ +exec+ +string+
$lst_tit recursion$lst_titend$type_both
  $(lst_syntax)recursion $emph fn$emphend for $emph v$emphend=$emph v1$emphend
  to $emph v2$emphend [step $emph st $emphend], 或 <br>
$ !recursion $emph fn$emphend for $emph v$emphend in 
  $emph v1,v2,v3,...$emphend</tt>
  $lst_mean 让变量 $emph v $emphend 逐次取从 $emph v1$emphend 到
  $emph v2$emphend 的值, 递归地计算函数 $emph fn$emphend 的值. <p>
  如果是第二句的形式, 变量依次取表 $emph v1,v2,...$emphend 里的值. <p>
  函数 $emph fn$emphend 内应使用变量 $emph last$emphend
  表示上一次计算得到的值. 初始值可以放在WIMS变量 <tt>$$recursion_start</tt> 内.

