!! +var+ +random+ +string+

$lst_tit shuffle$lst_titend$type_var
  $lst_alias randperm, randpermute
  $(lst_syntax)shuffle [even|odd] $emph n $emphend</tt>, 或<br>
  <tt>!shuffle [even|odd] $emph list $emphend</tt>
  $lst_mean 对 $emph n $emphend 个元素的集合作随机置换. 在第一种用法里,
  $emph n$emphend 必须是不超过 1024 的正整数,
  在第二种用法里, $emph n $emphend 是表 $emph list $emphend 的项数. <br>
  对第一种用法, 命令返回一个逗号分隔的表 $emph i<sub>1</sub>, i<sub>2</sub>, ...,
  i<sub>n</sub>$emphend, 其中的项 $emph i<sub>k</sub>$emphend 是集合
  $emph {1,2,...,n}$emphend 中随机排序的元素. <br>
  本命令可与以下命令连用
  $(ref1)cmdlist_item_&cmd_choose=all$(ref2)cmdlist_item_>!item</a>,
  $(ref1)cmdlist_line_&cmd_choose=all$(ref2)cmdlist_line_>!line</a>,
  $(ref1)cmdlist_word_&cmd_choose=all$(ref2)cmdlist_word_>!word</a>,
  $(ref1)cmdlist_char_&cmd_choose=all$(ref2)cmdlist_char_>!char</a>,
  以对一个串的项、行、词或字符作随机置换. <br>
  对第二种用法, 返回对表 $emph list $emphend 里的项作随机置换的结果. <br>
  不论何种情况, 变量 $emph wims_shuffle_order $emphend 都被赋值为表
  $emph i<sub>1</sub>, i<sub>2</sub>, ..., i<sub>n</sub>$emphend. <br>
  如果出现选项词 $emph even$emphend 或
  $emph odd$emphend, 意指只做偶/奇置换.

