!! +exec+ +jump+
$lst_tit while$lst_titend$type_exec
  $(lst_syntax)while $emph string1 relation string2 $emphend<br></tt>
  ... (多行的内容)<br>
 $ <tt>!endwhile</tt>
  $lst_mean 条件分叉: 执行
  $emph!while$emphend 行与 $emph!endwhile$emphend 行之间的多行内容,
  直至 $emph relation$emphend 不再被满足.
  在作比较前, 先除去 $emph string1$emphend 与 $emph
  string2$emphend 两端的空格.
  <p>
  其语法同
  $(ref1)cmdlist_if_$(ref2)cmdlist_if_>if</a>.
