!! This file can contain contents which go to the end of the page.

!if $wims_user=supervisor
!! <p>
!! Puede
!! !href module=adm/createxo&existing=$thisexo modificar
!! o
!! !href module=adm/createxo&delete=$thisexo&deltitle=$title eliminar
!! este ejercicio.
!! <p>
 !set wims_menu_items=!append line exomodify,1,module=adm/createxo&existing=$thisexo\
 exoerase,1,module=adm/createxo&delete=$thisexo&deltitle=$title\
 to $wims_menu_items
!else
 !if ..*/$wims_user. isin ..*/$thisexo
  Puede
  !href module=adm/createxo&existing=$thisexo modificar
  este ejercicio.
  !set wims_menu_items=!append line exomodify,1,module=adm/createxo&existing=$thisexo\
  to $wims_menu_items
 !endif
!endif

