
!read adm/title.phtml 3\
$name_delcourse0<em> $class_description</em>

<font color=red><b>AVERTISSEMENT</b>.</font> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans ce cours sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;: comptes d'élèves, activités, notes&nbsp;!
<p>
Etes-vous sûr de vouloir effacer ce cours&nbsp;?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=$parent $wims_name_no

</font></center> <p>

