
!read adm/title.phtml 3\
\
Effacer le niveau <em>$class_description</em>

<font color=red><b>AVERTISSEMENT</b>.</font> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans ce niveau sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;: classes, programmes, cours, comptes d'élèves, activités, notes&nbsp;!
<p>
Etes-vous sûr de vouloir effacer ce niveau&nbsp;?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=first $wims_name_no

</font></center> <p>

