
<center><h3>Effacer la zone de test <em>$class_description</em></h3></center>

<font color=red><b>AVERTISSEMENT</b>.</font> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans cette zone de test sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;!
<p>
Etes-vous sûr de vouloir effacer la zone de test&nbsp;?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent Oui
&nbsp;&nbsp;
!href cmd=reply&job=$parent Non

</font></center> <p>

