!distribute words $wims_read_parm into css_file
!default module_title2=$module_title
!if $wims_css=----
  !set css_file=$wims_theme/css.css
!else
  !set css_file=html/css/$lang/$(wims_css)_color.css
!endif
!default css_file=$wims_theme/css.css
!set css_file=!record 0 of wimshome/public_html/$css_file
!set css_file=!replace internal $$$wims_bgcolor by $$wims_bgcolor in $css_file
!set css_file=!replace internal $$$wims_ref_bgcolor by $$wims_ref_bgcolor in $css_file
!writefile getfile/css.css $css_file

!set wims_html_header=!append line <link href="$wims_ref_name?session=$session&+cmd=getfile&+special_parm=css.css" rel="stylesheet" title="$module_title2" type="text/css">\
to $wims_html_header
