!if $wims_theme_image=yes
  !set  wims_theme_image=$wims_theme
!endif
!distribute items $wims_read_parm into 1_,2_,3_,4_
!reset w_image
!if " isin $1_
  !set w_name=!replace internal " by in $1_
!else
  !set w_name1=!word 1 of $1_
  !set w_name2=!word 2 to -1 of $1_
  !set w_name=$(wims_name_$(w_name1)) $w_name2
  !if $wims_theme_image!=$empty
    !set w_image=<img border=0 src="gifs/themes/$wims_theme_image/$w_name1.gif" alt="$1_" title="$_">
  !endif
!endif
!goto $2_
:0
 $(wims_read_parm[3..-1])
 !exit
:1
 !set 3_=!item 3 to -1 of $wims_read_parm
 !set 3_=!nospace $3_
 !href $3_ $w_image $w_name
 !exit
:2
 !if $4_ notsametext
  <a href="$3_" target="wims_$4_">$w_image $w_name</a>
 !else
  <a href="$3_">$w_image $w_name</a>
 !endif
 !exit
:3
 <a href="#" onclick="$3_">$w_image $w_name</a>
 !exit
:4
 !href target=wims_$4_ $3_ $w_image $w_name
 !exit
:*
