!! This file can contain contents which go to the end of the page.

!if $wims_exec_error!=$empty
<small><pre>*******************************************************
$wims_exec_error
*******************************************************</pre></small>
!reset wims_exec_error
!endif

!set wims_menu_tail=!append line backcreatexo,1,cmd=resume&realtest=no\
to $wims_menu_tail
!if $mode=model
!set wims_menu_tail=!append line modellist,1,cmd=reply&level=1&mode=model\
to $wims_menu_tail
!endif

!!<p><center>
!!!href cmd=resume&realtest=no Volver a la página de creación de ejercicios
!!.</center> <p>
