
!set wims_form_method=file
!form reply
<input type=hidden name=level value=3>

!if $existing=$empty
 Está en modo fichero para la creación de ejercicios.
 Bajo este modo puede enviar un fichero fuente OEF local al servidor.
 Para crear un ejercicio desde cero preferirá el
 !href cmd=reply&mode=normal modo guiado
. También tiene a su disposición el
 !href cmd=reply&mode=raw modo en bruto
 para editarlo en línea.
 <p>
 Fichero fuente de su ejercicio:
 <input type=file name=wims_deposit>
 <p><center>
<input type=submit value="Enviar el fichero"></center>
</form>

