
<center><h3>Ficheros de imagen para el ejercicio</h3></center>

!if $quota=yes
 <b>Error</b>. No puede añadir más ficheros a su clase porque su contendido 
 ha igualado o superado el espacio de disco autorizado.
 Lo sentimos.
 <p>
 !goto sendend
!endif

!set wims_form_method=file
!form reply
Fichero de imagen que se va a enviar en el ejercicio:
<input type=file name=wims_deposit>
<input type=submit value=OK>
</form>

:sendend
!if $imglist=$empty
 Ete ejercicio no tiene aún ningún fichero de imagen.
!else
 Lista de ficheros de imagen del ejercicio:
 <p><center><table border=2>
 <th>Nombre del fichero<th>Vista<th>-
 !for i in $imglist
  <tr><td valign=middle align=center>$i
  <td valign=middle align=center>
  <img src="$wims_ref_name?cmd=getfile&+session=$wims_session&+special_parm=oefimg/$i" alt=""
   height=40 width=50>
  <td valign=middle align=center>
  !href cmd=reply&delfile=$i Borrar
 !next i
 $table_end <p>
 !set example=!item 1 of $imglist
 Se puede acceder a estos ficheros de imagen en el enunciado del ejercicio
 mediante el parámetro interno \imagedir. Por ejemplo puede escribir
 <center><pre>
 &lt;img src=\imagedir/$example&gt;
 </pre></center>
 Puede también escribir simplemente <tt>\img{\imagedir/$example}</tt>, o
 <tt>\img{\imagedir/$example}{opciones html}</tt>. La ventaja de este segundo método
 es que los estudiantes no verán el nombre del fichero. A causa de su coste
 en consumo de recursos, no utilice este método más que cuando sea necesario.
!endif
<p><center>
!href cmd=resume&level=3&realtest=yes&retest=again Probar el ejercicio
.&nbsp;
!href cmd=reply&level=3 Volver al menú
.
</center>

