
Su ejercicio se ha registrado con éxito en este servidor. Le agradecemos 
sinceramente su contribución, en nombre de todos aquellos que se 
beneficiarán de él.
<p>
El administrador de este sitio verificará su ejercicio, y decidirá si ponerlo
o no en una categoría apropiada. Esto podría tardar algún tiempo.
<p><center>
!href module=incoming Módulo que contiene temporalmente su ejercicio.
<p>
!href cmd=reply&level=$[$level-1] Volver a la etapa precedente.
</center>


