!if $wims_read_parm!=
  !goto $wims_read_parm
!endif

!distribute lines Método guiado\
  Método bruto\
  Método fichero\
  Otros métodos\
  modelos preparados\
  Enviar el fichero\
  Fichero fuente de su ejercicio\
  Volver al menú inicial\
  Continuar al contenido del ejercicio\
  Modificar un ejercicio existente de la clase\
   Volver a la etapa precedente\
  Envoyer le source\
  Vider\
  Démo\
  Adapter\
  Tester l'exercice\
  Corregir el error\
  Volver a\
  La realización de su ejercicio será como sigue.\
  Voici les modèles d'exercices disponibles. Choisissez-un.\
 Módulo que contiene temporalmente su ejercicio\
into wims_name_normalmode, wims_name_rawmode,wims_name_filemode,wims_name_othermethods,\
  name_model,name_sendfile,name_source,name_menuback,name_continue,name_modify,\
  name_prevstep,name_sendsource,name_clean,name_demo,name_adapt,name_testexo,\
  name_correction,name_backmodule,name_realisation,name_availablemodels,name_temp_module

!set name_normal=!lowercase $wims_name_normalmode
!set name_raw=!lowercase $wims_name_rawmode
!set name_file=!lowercase $wims_name_filemode

!set name_modefile1=Está en modo fichero para la creación de ejercicios.\
  Bajo este modo puede enviar un fichero fuente OEF local al servidor.\
 Para crear un ejercicio desde cero preferirá el
 !set name_modefile2=Pour éditer en ligne, vous pouvez aussi utiliser le

!set name_first=Exercices basiques
!set name_datalist=Exercices avec une liste de données

!set name_save=!nosubst  Aquí está el código fuente de su ejercicio\
 <font color=red><b>$oef_title</font></b>, en formato OEF (Open Exercice Format).\
 Para guardarlo, corte el texto situado entre las dos líneas horizontales, y \
 péguelo en un archivo.

!distribute lines Número de parámetros\
  Número de respuestas\
  También puede enviar un fichero de imagen\
  O modificar el fichero fuente y después\
  añadir este ejercicio a su clase, bien\
  para sustituir al antiguo\
  para hacer de él uno nuevo\
  reenviarlo\
  Le mettre dans le module de développement\
  hacer una copia \
  de seguridad del código fuente !\
into name_parameter_cnt,name_answer_cnt,name_deposit,name_modify,name_putinclass,\
name_replace,name_new,name_sendagain,name_developer,name_savesource,name_download
 
!set name_success=El software ha reconocido su ejercicio como válido

!if $level=1
!distribute lines Dele un título al ejercicio que quiere crear\
  Formato del enunciado del problema\
  Este ejercicio pedirá\
  respuestas libres y \
  respuestas de opciones múltiples\
  Las respuestas numéricas no calculadas (como <tt>3*5-sin(pi/3)</tt>) serán\
  aceptadas,rechazadas\
  condiciones especiales para corregir las respuestas libres\
into name_givetitle,name_giveformat,name_exo,name_answer1,name_answer2,\
name_nonnumeric,name_prompt,name_condition
!endif

!if $level=2
 !set types=!sort nocase lines \
auto,			default\
expression littérale,	litexp\
expression algébrique,	algexp\
expression formelle,	formal\
texte approximatif,	atext\
texte converti en minuscules,nocase\
texte exact,		case\
texte brut,		raw\
equation,		equation\
ensemble fini,		set\
matrice,		matrix\
nombre,			numeric\
nombre avec zone,	range\
nombre avec unité,	units\
fonction numérique,	function\
vecteur,		vector\
mots dans une liste,	wlist

!distribute lines Ahora, por favor, introduce el contenido de tu ejercicio \
 Puedes definir los parámetros aleatorios aquí\
 La explicación del ejercicio \
 Respuestas libres\
 Solución correcta\
 Precisión requerida para respuestas numericas\
 Las funciones (numericas) serán comparadas en el intervalo\
 Condiciones para el análisis de respuestas (numéricas)\
 Nombre de la condición\
 Definición de la condición\
 Elecciones \
 Elecciones correctas\
 Elecciones incorrectas\
 Puedes dar opcionalemente una nota y/o solución\
 Hint<br>(Formato html)\
 Solution<br>(Formato html)\
into name_content,name_alea,name_statement,name_free,name_goodsol,name_precision,name_function,\
 name_condition_numeric,name_name_condition,name_definition,name_multiple,name_goodchoice,name_badchoice,\
 name_option,name_indication,name_solution

!endif

!if $level=4
  !set name_update1=!nosubst L'exercice <tt>$existing.oef</tt> est bien mis à jour avec succès dans le module
  !set name_update2=Echec de mise a jour de l'exercice <tt>$existing</tt> dans le module 
  !set name_update3=Su ejercicio se ha instalado con éxito.
   !set name_update4= Hemos encontrado un ejercicio idéntico en su clase. Se ignoran los registros   dobles.\
  !set name_update5=Este ejercicio será accesible únicamente a los participantes de su clase, \
    y solamente si lo pone en una hoja de trabajo.
  !distribute lines Ahora puede\
    Consultar los ejercicios de clase\
    y eventualmente añadirlos a las hojas de trabajo\
 into name_youcan, name_consult,name_sheet
!endif

!distribute lines Vous êtes en mode brut de création d'exercices.\
  Puisque cet exercice est basé sur un modèle standard, essayez le\
  Entrez le source entier\
  pour enregistrer un fichier source existant, copiez le fichier dans la fenêtre.\
  Voici le source d'un exercice existant de votre classe.\
  Vous pouvez le modifier dans la fenêtre ci-dessous.\
  Voici le source d'un exercice public que vous voulez importer. Vous pouvez le modifier dans la fenêtre ci-dessous avant de le mettre dans la classe.\
  Vous pouvez tester certains programmes externes avec le\
  testeur de script\
 into name_brut,name_try,name_allsource,name_copy,name_source2,name_modify_window,name_public,name_test_extern,name_testerscript
 
!exit
:delete
El ejercicio <em>$deltitle</em> se ha eliminado de la lista de ejercicios de la
clase.
<p>
En el caso en que haya sido un error y desee repararlo, aquí tiene
el código fuente del ejercicio, que puede guardar como medida de seguridad,
y copiarlo posteriormente en 

!exit
:model
<b>Note</b>. Ces modèles ont pour but de permettre aux plus pressés de
construire rapidement leurs exercices. Ils ont donc souvent une structure
simplifiée et standardisée, et n'offrent pas la pleine puissance de la
syntaxe OEF. Mais vous pouvez toujours mettre les exercices en mode brut
pour y ajouter plus de fonctionnalités ou les modifier selon votre goût.
!exit

:register
Su ejercicio se ha registrado con éxito en este servidor. Le agradecemos 
sinceramente su contribución, en nombre de todos aquellos que se 
beneficiarán de él.
<p>
El administrador de este sitio verificará su ejercicio, y decidirá si ponerlo
o no en una categoría apropiada. Esto podría tardar algún tiempo.
!exit