!! Placez ici le code pour montrer le résultat de l'analyse de réponse.

<center>
<table  border="4">
  <tr>
  <td bgcolor="bisque" nowrap="nowrap">
     <em> Ya ha terminado </em>
     <td>
     <table>
	<tr><td align="center" bgcolor="white"><span class="wims_emph">$auteur</span>
	</tr>
     </table>
	<span class="wims_emph">¡Buena continuación!</span>
     </td>
  </td>
  </tr>
</table>
</center>
