!header

!! La présentation de l'exercice.
!read present.phtml

 <hr/>

!if $status=waiting
 !if $error!=$empty
  !read msg.phtml
  <hr width="50%"/>
 !endif
 !! La forme de réponse
 !!!read form.phtml
 <p>
 !href exo_Renew
.
</p>
!else
 !if $error!=$empty
  !read msg.phtml
  <hr width="50%"/>
 !endif
 !! L'analyse de réponse
 !read answer.phtml
 <p>
 !href exo_Again
.
 !if $worksheet=$empty
  !href exo_Intro
.
</p>
 !endif
!endif

:end
!tail
