
!if $class_defined!=yes
 <b>Fehler:</b> Sie möchten sich bei $name_classess
 anmelden, diese Klasse existiert jedoch nicht.
 Überprüfen Sie bitte Ihre Anmeldeaufforderung.
 !exit
!endif

Um $name_classes <b><font 
color=green>$class_description</font></b> /
<b><font color=green>$class_institution</font></b> als
<em>$name_sup</em> aufrufen zu können, müssen Sie das zugehörige
Kennwort eingeben.

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 $name_sup-Kennwort: <input type=password size=20 name=auth_password>
<p>
<input type=submit value="OK">
</center>
</form>