
!if $class_defined!=yes
 <b>Fehler:</b> Sie möchten sich bei $name_classess anmelden, diese Klasse existiert jedoch nicht.
 Überprüfen Sie bitte Ihre Anmeldeanforderung.
 !exit
!endif

Um <b><font color=green>$class_description</font></b> / 
<b><font color=green>$class_institution</font></b> 
aufrufen zu können, müssen Sie Ihren Benutzernamen 
und Ihr Kennwort eingeben.

!!!##language independant
<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>$wims_name_Login<td><input size=20 name=auth_user value="$auth_user"></td>
 <tr><td>$wims_name_Password<td><input type=password size=20 name=auth_password></td>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register