!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=Bildungseinheit
    !set name_sup=Administrator
    !set name_classes= $name_classe
    !set name_classesss= von $name_classe
    !set name_classessss= $name_classe
   !else
    !set name_classe=Bildungsstruktur
    !set name_sup=Administrator
    !set name_classes= $name_classe
    !set name_classesss= von $name_classe
    !set name_classessss= $name_classe
   !endif
   !set name_classess= $name_classe
 !else
   !set name_classe=classe
   !set name_classes=$name_classe
   !set name_classess=$name_classe
   !set name_classesss= von $name_classe
   !set name_classessss= $name_classe
   !set name_sup=Lehrer/Dozent
 !endif
 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of Klasse,Kurs
   !set Name_level= !item $splevel of Niveau,Klasse,Kurs
   !set Name_levels= !item $splevel of Niveaus,Klassen,Kurse
   !set sousclasses_else=!item $splevel of entweder eine Klasse oder ein Kurs
   !set name_level_else= !item $splevel of ein Niveau,eine Klasse,ein Kurs
 !else
   !set sousclasses=Teilklassen
   !set sousclasses_else=Klasse oder Bildungsstruktur
 !endif

!set CL_Name	=Niveau,Klasse,Programm,Kurs,Klassenübergreifende Kurse,Portal,Test Zone
!set Name_program=Programme
!set name_program=Programm

