
!read search.phtml
!if $overflow=yes
 !exit
!endif

!if $clcnt+$sccnt+$directcnt<1
 !if $keyword=$empty
  Auf dieser Website ist keine Klasse in deutscher Sprache
  verfügbar. Möchten Sie eine Klasse 
  !href module=home&list=0 in einer anderen Sprache
 auswählen?
 !else
  Keine Klasse entspricht Ihrer Suche.
 !endif
 !exit
!endif

!if $wims_user!=$empty
 !read direct.phtml
 !if $wims_user!=supervisor and $superclass=$empty
  !exit
 !endif
!else
Wählen Sie die Zeile der Sie betreffenden Klasse
 bzw. Bildungsstruktur aus.
 <p>
Wenn Sie noch nicht eingeschrieben sind, klicken Sie auf <tt>Einschreiben</tt> 
(liegt der Status <tt>Geschützt</tt> vor, dann müssen Sie ein Kennwort eingeben. 
Sie erhalten dieses vom Lehrer/Dozenten bzw. Administrator).

 <p>Andernfalls klicken Sie auf <tt>Öffnen</tt>, um die gewünschte Seite 
aufzurufen. 
!endif

!if $sccnt>0
 <p>$table_header
 <caption>Bildungsstrukturen und -einheiten</caption>
 $table_hdtr
 <th>Nom<th colspan=2>Schüler/Student</th><th>Administrator</th><th>Status</th>
 !for i=1 to $sccnt
  !set l=!line $i of $sclasses
  !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !if $superclass=$empty
   !set show=$inst
  !else
   !set show=$cl
  !endif
  !set supv=!item 9 to -1 of $l
  !if $supv=$empty
   !reset class_password
   !defread wimshome/log/classes/$code/.def
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif
  
  $table_tr<td align=center>
  !!!href module=$module&type=authparticipant&class=$code 
  $show
  </td> <td align=center>
  !href module=$module&type=authparticipant&class=$code Öffnen
  </td> <td align=center>
  !href module=adm/class/reguser&class=$code&subclass=yes Einschreiben
  </td> <td align=center>
  $supv
  </td> <td align=center>
  !if $pswd=$empty
   Geöffnet
  !else
   Geschützt
  !endif
 !next i
 $table_end <p>
!endif

!if $clcnt>0
 <p>$table_header
 !if $superclass=$empty
  <caption>Unabhängige Klassen</caption>
  $table_hdtr	
  <th>Name der Klasse</th><th colspan=2>Schüler/Student</th>
  <th>Leiter</th><th>Niveau</th><th>Status</th>
 !else
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
    !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
   !endif
   <caption>$Name_levels in $inst
   !if $splevel>1
    !href cmd=reply&type=$type&superclass2=$sparent Up
   !endif
   </caption>
   $table_hdtr
   <th>Name der Klasse</th><th colspan=2>Schüler/Student</th>
   <th>Leiter</th><th>Niveau</th><th>Status</th>
   !if $superclass!=$empty and $stype=4
    <th>+</th>
   !endif
 !endif
 !for i=1 to $clcnt
  !set l=!line $i of $classes
  !distribute items $l into code,expire,inst,cl,la,ty,lv,pswd
  !set supv=!item 9 to -1 of $l
  !if $supv=$empty
   !reset class_password
   !defread wimshome/log/classes/$code/.def
   !set lv=$class_level
   !set supv=$class_supervisor
   !set pswd=$class_password
  !endif
  !distribute char $lv into l_,y_
  
  !if $superclass=$empty
   !set show=$inst <br>$cl
  !else
   !set show=$cl
  !endif
  $table_tr<td align=center>
    $show
  </td><td align=center> 
  !href module=$module&type=authparticipant&class=$code Öffnen
  </td> <td align=center> 
  !if $splevel=$empty or $splevel=2
   !href module=adm/class/reguser&class=$code Einschreiben
  !else
   <font color=grey>Einschreiben</font>
  !endif
  </td><td align=center>
  $supv
  </td><td align=center>$(n_$l_)<br>Jahr $y_</td>
  <td align=center>
  !if $pswd=$empty
   Geöffnet
  !else
   Geschützt
  !endif
  </td>
   !if $superclass!=$empty and $stype=4
    <td>
    !if $ty!=1
     !href cmd=reply&type=$type&superclass2=$code $sousclasses
    !else
    -
    !endif
   !endif
 !next i
 $table_end <p>
!endif

