
!read adm/css.phtml
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read js/speckedit.phtml name_deposit
!header1


!read adm/title.phtml 1\
$classname\
$name_title

!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$moduclass_lang 
 </div>
 <p>
 !href module=home $wims_name_class_home
. </p>
 !goto end
!endif

!if $job!=$empty
 !read $job.phtml
 !goto end
!endif

$name_Intro
!href style=student $name_home
.
<br />
<table class="wimscenter wimsborder" border="1" width="90%">
 <tr>
  <td>$name_commun :</td>
  <td rowspan="2" valign="middle">
  !set wims_ref_class=wims_button
    !href cmd=reply&job=modif&user=.CLASS. $wims_name_change
    &nbsp;
  !set wims_ref_class=wims_button
    !href cmd=reply&job=delete&user=.CLASS. $wims_name_erase
  </td>
 </tr>
 <tr><td>&nbsp;
 !record 0 of wimshome/log/classes/$wims_class/.motd
 </td></tr>
</table>

$name_motd
$table_header
 $table_hdtr
  <th>$name_participant</th>
  <th width="50%">$name_actualmotd</th>
  <th>$wims_name_Status</th>
  <th>$name_alertmsg</th>
  <th>$wims_name_action</th>
 </tr>
 !for k=1 to $nbuser
  $table_tr 
   !let don=!record $k of wimshome/log/classes/$wims_class/.userlist
   !distribute item $don into f,l,u
   <td>
    $l $f
    !if $u isitemof $wims_connectedlogin
     <img src="gifs/themes/$wims_theme_icon/connected.png" width="15px" />
    !endif
   </td>
   <td>
    !record 0 of wimshome/log/classes/$wims_class/motd/$u
   </td>
   <td>
    !let test=!record 0 of wimshome/log/classes/$wims_class/motd/.$u
    !if $test=$empty
     $(name_status[1])
    !else
     $(name_status[2])
     !href cmd=reply&job=reactivate&user=$u $name_reactive
    !endif
   </td>
   <td>
    !let p=!positionof item $u in $wims_connectedlogin
    !if $p!=$empty
     !let n=!itemcnt $(wims_whoconnect[$p;])
     !if $n>4
      $name_usermultisession
     !else
      !defof wims_alertmsg in wimshome/sessions/$(wims_whoconnect[$p;4])/var.stat
     !endif
    !endif
   </td>
   <td>
   !set wims_ref_class=wims_button
    !href cmd=reply&job=modif&user=$u $wims_name_change
    &nbsp;
    !set wims_ref_class=wims_button
    !href cmd=reply&job=delete&user=$u $wims_name_erase
    !if $n<5 and $p!=$empty
     &nbsp;
     !set wims_ref_class=wims_button
     !href cmd=reply&job=write&user=$u $name_walertmsg
    !endif
   </td>
  </tr>
 !next k
$table_end

:end

!if $job!=$empty and $job!=delete
  !set wims_menu_items=!append line back2,1,cmd=reply\
 to $wims_menu_items
!endif

!tail
!reset job
