!read adm/class/classlang names.phtml

wims_prefix=class user tmp n sharing sharable

test=!defof class_defined in wimshome/log/classes/$wims_class/.def
!if $test!=yes
 error=bad_class
 !reset job
 !exit
!endif

!readproc tabletheme

!if $wims_user!=supervisor
 job=hide
!else
 !bound job within modif,delete,reactivate default $empty
 !if $user=.CLASS.
  !reset user
 !endif
!endif

!if $job!=$empty
 !read $job.proc
!endif




