!read adm/lang/date.phtml.$moduclass_lang

<b>
$name_guidedtitle
</b>
!set wims_ref_class=wims_button_help
!href cmd=help&helpname=guidedmode $wims_name_help
<br>

!default gstep=0
!goto $gstep

:0
!if $vote_status=0
<p>$name_introguided</p>
!form reply
$table_header
 $table_tr
<td>$name_howmany ($name_atmost 10)</td>
<td>
!formselect numsess from 1 to 10
</td>
</tr>
$table_tr
<td>$name_nameexvar</td>
<td>
<input size=12 name="nameexvar" id="nameexvar">
</td>
</tr>
!! qui non funziona perché non ho il reload della pagina
!! !read models/$vmodel.phtml
$table_tr
  <td>$name_textconnip</td>
<td>
<input size=12 name="defconnip" id="defconnip">
</td>
</tr>
$table_tr
  <td>Vote model $name_vmodel</td>
<td>
!! vmodellist_names should be defined in lang files
!set vmodellist_names=$vmodellist
!formselect vmodel list $vmodellist prompt $vmodellist_names
</td>
</tr>
$table_tr
<td colspan="2" align="center">
<input type=hidden name="gstep" value="1">
<input type="hidden" name="job" value="guided">
<input type=submit value="$wims_name_send">
</td>
</tr>
$table_end
</form>
!else
<p>$name_noguided</p>
!endif
!goto end


:1

!form reply
!if $vote_status=0
<p>$name_numsess_pre
<select  name="numsess" onchange="submit()">
!for i=1 to 10
 !if $i=$numsess
  <option value="$i" selected>$i</option>
 !else
  <option value="$i">$i</option>
 !endif
!next i
</select>
$name_numsess_post</p>
!else
<p>$name_numsess</p>
!endif
</form>

!form reply
!if $vote_status=0
<p>Vote models
<select  name="vmodel" onchange="submit()">
!for i in $vmodellist
 !if $i=$vmodel
  <option value="$i" selected>$i</option>
 !else
  <option value="$i">$i</option>
 !endif
!next i
</select>
</p>
!else
<p>Model $vmodel</p>
!endif
</form>

!form reply
<p>$name_introtext</p>
!! FIXME: only text in this textarea, no vote primitives: need to chech user input. also can use editor??
<center>
<textarea $wims_id rows=10 cols=65 name="testointro" wrap>
!replace internal \( by &#92;( in $testointro
</textarea>
</center>



<p>$name_numsess_pre $numsess $name_numsess_post</p>

$table_header
$table_hdtr
!read models/$vmodel.phtml
$table_end
<div align="center">
!! FIXME: wims_name_doch_reload ??
<input type="submit" value="$wims_name_doch_reload" $wims_on_click>
</div>
 <input type="hidden" name="reg_title" value="$vote_title">
 <input type="hidden" name="nameexvar" value="$nameexvar">
 <input type="hidden" name="gstep" value="2">
</form>

!goto end

:2

!if $gstep>1 and $cmd=reply
 !set wims_menu_items=!append line back2,1,module=$module&job=guided&vote=$vote\
 to $wims_menu_items
!endif

!! !set gstep=1

!sh mkdir -p $wims_home/log/$Votedir
!writefile $votedir/$vote.data

!appendfile $votedir/$vote.data gstep=1

!for dato in numsess,nameexvar,defconnip,vmodel
 !appendfile $votedir/$vote.data $dato=$($dato)
!next

!read models/$vmodel.phtml

!set wims_form_method=post
!form reply
$table_header
!read votesetup.phtml
$table_end

<p>$name_describesource</p>

!if $vmodel=exams
<p>$name_examinstr</p>
!endif

<pre>
$reg_src
</pre>

<center><hr width="30%">
<br><br><hr>
 <input type="submit" name="rEg" value="$wims_name_tosave" $wims_on_click>
 <input type="submit" name="abandon" value="$wims_name_giveup">
 <input type="hidden" name="reg_src" value="$reg_src">
 <input type="hidden" name="job" value="guided">
<hr>
</center>
</form>

!! !set gstep=1
!reset gstep
!goto end

:vars
!! just for testing, to be deleted

!for i in testointro,defconnip,exconnip1,exconnip2,vote_title,Votedir,votedir,class_expiration,class_creation,jday,jmonth,jyear,gstep, \
numsess,inizio,wims_now,wims_class,today,expyear,creyear,\
moduclass_lang,ddesc,dday,dmonth,dyear,\
  bmonth1,bmonth2,bmonth3,nstud1,nstud2,nstud3,reg_src
$i: $($i) <br>
!next
  
:end

!set wims_menu_items=!append line Show,1,cmd=reply&job=read\
 to $wims_menu_items

