
!if $job!=home and $vote_title!=$empty
 !set module_title=$vote_title
!else
  !if $(module_title_$moduclass_lang)!=
   !set module_title=$(module_title_$moduclass_lang)
  !endif
!endif
!if $job=edit
  !if $vote_model=free
    !read js/speckedit.phtml src
  !else
    !read js/speckedit.phtml testointro
  !endif
!endif
!read adm/css.phtml
!header

!if $error!=$empty
 <div class="wims_msg alert">
 !read lang/msg.phtml.$moduclass_lang
 </div>
!endif
!read $job.phtml
!if $wims_user=supervisor and $job notwordof home
  !if $job!=getsource
    !if $job=creat
     !set wims_menu_items=!append line vote,1,cmd=renew&job=home\
to $wims_menu_items
    !else
     !set wims_menu_items=!append line vote $wims_user ARIANE,1,cmd=renew&job=home\
to $wims_menu_items
    !endif
  !if $vote_src!=$empty
    !set wims_menu_items=!append line source,1,cmd=renew&job=getsource&vote=$vote\
   to $wims_menu_items
  !endif
 !else
   !set wims_menu_items=!append line back2 $vote,1,cmd=resume&job=edit&vote=$vote\
   to $wims_menu_items
 !endif
 !if $job notwordof read creat getsource showresult csv and $reg_title$vote_title!=$empty and $reg_src$vote_src!=$empty
   !set wims_menu_items=!append line test,1,cmd=reply&job=read\
   to $wims_menu_items
 !endif
!endif

!tail
