
!if $job!=home and $vote_title!=$empty
 !set module_title=$vote_title
!else
  !if $(module_title_$moduclass_lang)!=
   !set module_title=$(module_title_$moduclass_lang)
  !endif
!endif
!if $job=edit
  !if $vote_model=free
 !read js/speckedit.phtml src
  !else
   !read js/speckedit.phtml testointro
!endif
!endif
!read adm/css.phtml
!header

!if $error!=$empty
 !read lang/msg.phtml.$moduclass_lang
 <p>
!endif

!read $job.phtml
!if $job!=home
 !set wims_menu_items=!append line vote,1,cmd=renew&job=home\
 to $wims_menu_items
 !if $job notwordof read creat and $reg_title$vote_title!=$empty and $reg_src$vote_src!=$empty
   !set wims_menu_items=!append line test,1,cmd=reply&job=read\
   to $wims_menu_items
 !endif
!endif
 
!tail

