!! might want to share code with edit.phtml
 $table_hdtr
  <th>$name_option</th><th>$name_value</th>
 </tr>
 $table_tr<td>$wims_name_title</td><td><input size="50" name="reg_title" value="$vote_title"> </td></tr>
 $table_tr<td>$wims_name_Type</td>
  !default vote_status=0
  !set reg_status=$vote_status
  !set reg_option=$vote_option
  !set reg_show=$vote_show
  !set reg_whovoteshow=$vote_whovoteshow
  <td>
  !if $vote_status=0
    !formselect reg_option list anonymous,trace,nominative prompt $name_anonymous,$name_trace,$name_nominative
  !else
    $(name_$(vote_option))
  !endif
  </td>
 </tr>
 $table_tr
  <td>$wims_name_Status</td>
  <td>
  !if $vote_status=0 or $vcnt=0 or $vcnt=$empty or $vote_src$reg_src=$empty
   !formselect reg_status from 0 to 3 prompt $name_0,$name_1,$name_2,$name_3
  !else
   !formselect reg_status from 1 to 3 prompt $name_1,$name_2,$name_3
  !endif
  </td>
 </tr>
 $table_tr
  <td>$name_result</td>
  <td>
   !formselect reg_show list 1,0 prompt $name_publish,$name_hide
  </td>
 </tr>
 $table_tr
  <td>$name_whovote</td>
  <td>
   !formselect reg_whovoteshow list 1,0 prompt $name_publish2,$name_hide2
  </td>
 </tr>
