!!##language independant
!if $wims_read_parm!=$empty
 !set parms=$wims_read_parm
 !set parms=!replace internal $	$ by $\
$ in $parms
 !set size=!line 1 of $parms
 !distribute items $size into sx,sy
 !set ppm=!line 2 to -1 of $parms
!else
 !if $parms=$empty
  !exit
 !endif
 !distribute items $parms into sx,sy
 !set ppm=!item 3 to -1 of $parms
!endif

!set ppm=!replace internal \filedir/ by $ in $ppm
!for pm in ppm, sx, sy
 !set $pm=!slashsubst $($pm)
!next pp
!set ppm=!replace internal $	$ by $\
$ in $ppm
!set pp=!trim $ppm

!set a=!word 1 of $pp
!if $a=animate
 !set a=!line 1 of $pp
 !set a=!word 2 to -1 of $a
 !set pp=!line 2 to -1 of $pp
 !if $printable!=yes
  !set ins_anim_frames=!item 1 of $a
  !set ins_anim_delay =!item 2 of $a
  !set ins_anim_loop  =!item 3 of $a
 !endif
!endif

!!!set insdraw_filebase=!replace internal wimshome/ by $wims_home/ in $docdir/$doc/files
!set insdraw_filebase=$docdir/$doc/files
!set insdraw_size=$sx,$sy
!set ins_align=middle
!insdraw $pp

