
Here are the parameters of this message board which you can change.

!form reply
<input type=hidden name=job value=config>
<input type=hidden name=cf_set value=yes>
<ul>
 <li><p>Title of the message board:<br>
  <input size=60 name=cf_title value="$cf_title">
 <li><p>Description:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea>
 <li><p>Who can read the messages?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_readpolicy list alluser,owner prompt \
	every participant, only yourself
 !else
  !formselect cf_readpolicy list open,alluser,owner prompt \
 	everybody (user or not), registered users only, nobody except yourself
 !endif
 <li><p>Who can send messages to it?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_sendpolicy list alluser,mailuser,owner prompt \
	every participant, participants with email check, only yourself
 !else
  !formselect cf_sendpolicy list mail,alluser,mailuser,owner prompt \
	visitors with email address and users,\
	registered users only, users with email check,\
	nobody except yourself
 !endif

</ul>
<p><center><input type=submit name=cf_set value="$wims_name_tosave">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="$wims_name_giveup">
</center> <p></form>

