
!set monthnames=Jan,Feb,Mar,Apr,May,June,July,Aug,Sep,Oct,Nov,Dec
!set name_wroteon=wrote on

!distribute item <i>Subject:</i> <b>,</b> into subj1,subj2
!distribute item <hr>,<hr> into body1,body2

!distribute line List of messages by date\
	Threaded message list\
	Read a message\
	Compose a new message\
	Preview your message\
	Post a message\
	Configure the message board\
	into n_list,n_thread,n_read,n_compose,n_preview,n_send,n_config

!if $job=compose and $c_prec!=$empty
 !set n_compose=Compose a followup
!endif

!if $job notwordof read list
 !set nextline=</b> <br><font size=+0>--- $(n_$job) ---</font>
!endif

!set module_title=$module_title$nextline
