
!if +$error iswordof +no_send_right
 !exit
!endif

!if $srclen=$empty or $srclen=0 or $msglen=$empty or $msglen=0
 Your message is empty!
 !goto end
!endif

$subj1 $c_subject $subj2 $body1
!read wimshome/$wims_sesdir/message.wims
$body2
$tag_escaper</table></ul></ol></dl></form><font size=+0>

:end
<p><center>
!href cmd=reply&job=compose Back to edit
&nbsp;&nbsp;
!href cmd=reply&job=send Send the message
&nbsp;&nbsp;
!href cmd=reply&job=list Abandon it
</center> <p>

