 <small>
 !if $dcnt>1
  [
  !if $dlast!=$empty
   !href cmd=reply&job=read&r_msg=$dlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=list By date
  !if $dnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$dnext &gt;&gt;
  !endif
  ]
 !endif
 !if $r_prec!=$empty
  &nbsp;
  !set t_=!translate / to , in $r_prec
  !href cmd=reply&job=read&r_msg=$r_prec Previous
 !endif
 !if $repcnt>0
  &nbsp;
  !href cmd=reply&job=read&r_msg=$r_rep1 First followup
  &nbsp;
  !href cmd=reply&job=thread&th_orig=$l_thread&th_start=$r_msg All followups
 !endif
 !if $thtcnt>1
  &nbsp;&nbsp;[
  !if $tlast!=$empty
   !href cmd=reply&job=read&r_msg=$tlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=thread&th_orig=$l_thread&th_start=$l_thread Thread
  !if $tnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$tnext &gt;&gt;
  !endif
  ]
 !endif
 </small>
 