!read adm/css.phtml
!if $cmd=help
 !header
 !changeto help.phtml
!endif

!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu

!header1

!read names.phtml

!read names.phtml
!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
Statistische gegevens

!!<center>$classname
!!<p>
!!<h1>Statistische gegevens
!!</h1></center> <p>

!if $error!=$empty
 <p>
 !read msg.phtml

!set wims_menu_items=!append line class_home,1,module=home\
 to $wims_menu_items

 !goto end
!endif

!read table.phtml

<hr>

!read form.phtml

:end
!tail

!reset show

