!read adm/css.phtml
!read js/speckedit.phtml name_deposit
!header1

!read names.phtml

!if $job!=$empty
 !read $job.phtml
 !goto end
!endif


!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
Message de la classe
!!<center>$classname
!!<p>
!!<h1>Message de la classe
!!</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Retourner à la page d'accueil
. <p>
 !goto end
!endif

Cette page permet d'écrire ou de modifier un message destiné à tous les participants de la classe 
ou des messages personnalisés pour chaque élève.
Ces messages apparaîtront sur 
!href style=student la page d'accueil des participants
.
<br>
<center><table border=1 width="90%">
 <tr>
  <td>Message de la classe (commun à tous les participants) :</td>
  <td rowspan=2 valign=middle>
    !href cmd=reply&job=modif&user=.CLASS. Modifier
    &nbsp; 
    !href cmd=reply&job=delete&user=.CLASS. Effacer
  </td>
 </tr>
 <tr><td>&nbsp;
 !record 0 of wimshome/log/classes/$wims_class/.motd
 </td></tr>
</table>
<p>
Message personnalisé des participants
$table_header
 $table_hdtr
  <th>Elève</th>
  <th width="65%">Message actuel</th>
  <th>statut</th>
  <th>Action</th>
 </tr>
 !for k=1 to $nbuser
  $table_tr 
   !let don=!record $k of wimshome/log/classes/$wims_class/.userlist
   !distribute item $don into f,l,u
   <td>$l $f</td>
   <td>
    !record 0 of wimshome/log/classes/$wims_class/motd/$u
   </td>
   <td>
    !let test=!record 0 of wimshome/log/classes/$wims_class/motd/.$u
    !if $test=$empty
     Actif
    !else
     Caché &nbsp;
     !href cmd=reply&job=reactivate&user=$u Réactiver
    !endif
   </td>
   <td>
    !href cmd=reply&job=modif&user=$u Modifier
    &nbsp; 
    !href cmd=reply&job=delete&user=$u Effacer
   </td>
  </tr>
 !next k
$table_end
</center>
<p>
:end

!if $job!=$empty and $job!=delete
!set wims_menu_items=!append line back2,1,cmd=reply\
to $wims_menu_items
 !!!href cmd=reply Retour
!endif

!tail
!reset job
