<html><head>
$wims_html_header
</head>
<body $wims_htmlbody>
!headmenu
!read names.phtml

!if $job!=$empty
 !read $job.phtml
 !goto end
!endif

<center>$classname
<p>
<h1>Message de la classe
</h1></center> <p><hr width=40%> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Retourner à la page d'accueil
. <p>
 !goto end
!endif

Cette page permet d'écrire ou de modifier un message destiné à tous les participants de la classe ou des messages personnalis&eacute; pour chaque &eacute;l&egrave;ve.
Ces messages appara&icirc;tront sur 
!href style=student la page sommaire de la classe pour les participants
.
<br>
<center><table border=1 width=90%>
 <tr>
  <td>Message de la classe (commun &agrave; tous les participants) :</td>
  <td rowspan=2 valign=middle>
    !href cmd=reply&job=modif&user=$empty Modifier
    &nbsp; 
    !href cmd=reply&job=delete&user=$empty Effacer
  </td>
 </tr>
 <tr><td>&nbsp;
 !record 0 of wimshome/log/classes/$wims_class/.motd
 </td></tr>
</table>
<p>
Message personnalis&eacute; des participants
$table_header
 $table_hdtr
  <th>El&egrave;ve</th>
  <th width="75%">Message actuel</th>
  <th>Action</th>
 </tr>
 !for k=1 to $nbuser
  $table_tr 
   !let don=!record $k of wimshome/log/classes/$wims_class/.userlist
   !distribute item $don into f,l,u
   <td>$l $f</td>
   <td>
    !record 0 of wimshome/log/classes/$wims_class/motd/$u
   </td>
   <td>
    !href cmd=reply&job=modif&user=$u Modifier
    &nbsp; 
    !href cmd=reply&job=delete&user=$u Effacer
   </td>
  </tr>
 !next k
$table_end
</center>
<p>
:end

!if $job!=$empty and $job!=delete
 !href cmd=reply Retour
!endif

!tail
!reset job
