!! Ce fichier présente la question à résoudre.

$presentation
<$ltype>
!if $all_steps=0
 !for i=1 to $step
  <li>
  !line $i of $picked
 !next i
!else
 !if $status=waiting
  !form reply
  !for i=1 to $step
   <li>
   <input type=checkbox name=badstep value=$i>
   !line $i of $picked
  !next i
 !else
  !for i=1 to $step
   <li>
   !if $i isitemof $badstep
    <img src=gifs/blueball.gif>
   !endif
   !if $i isitemof $bad_steps
    <img src=gifs/redball.gif>
   !endif
   !line $i of $picked
  !next i
  !set explain=yes
 !endif
!endif
</$ltype>
!if $step>=$stepcnt
 (Fin)<p>
!endif

!if $explain=yes
 (<img src=gifs/blueball.gif>&nbsp;: étape marquée&nbsp;;&nbsp;&nbsp;
 <img src=gifs/redball.gif>&nbsp;: mauvaise étape.)
 <p>
!endif

