!if $tv_listtechvar=$empty
	No technical variable define.
	<br/>
	<ul>
		<li>use the link to the spreadsheet (not available for the moment)</li>
		<li>or do this directly in the attributes of the participants' accounts</li>
		<li>via a non anonymous questionnaire (not available for the moment)</li>
	</ul>
	(check the help pages for further instructions)
!else
	List of available technical variable :
	!read adm/vfilter/listvar.phtml
	you can filter participants according to these variables. All the conditions on the same line should be met and in case of several lines at least one condition per line should be fullfilled.
	<p>For example,
	<pre>
	group=1 language=2
	group=3
	</pre>
	will select students belonging to group 1 and in language 1 or to group 3.
!endif

