
!if $fsize=$empty
  Spiacente, il salvataggio del vostro corso non è andato a buon fine. Errore interno.
 !exit
!endif

  Ecco il file di backup del vostro corso:
!getfile $fname.$format $fname.$format
 ($fsize K).
 Cliccare qui sopra per salvare il backup sul vostro computer.<p>

!if $fsize<50 and all isitemof $selection
 !exit
!endif

!form reply
<input type=hidden name=job value=$job>
<input type=hidden name=job2 value=$job2>
!if $fsize<500
  &Egrave; anche possibile fare una selezione delle risorse da salvare:
!else
 Questo file di backup è troppo grande e supera il limite per un ripristino sul
 server. &Egrave; necessario ridurre le dimensioni del file, per fare ciò è
 possibile fare un
!endif


<p>
!set selection=$select
!formcheckbox selection list $reclist prompt $tot
<p>
Cliccare su <input type=submit value="Backup selettivo">
per modificare le risorse salvate nel file di backup di cui sopra. 

<p><b>Atenzione</b>. Si solito le parti che occupano più spazio sono l'attività
degli iscritti, i messaggi del forum e i documetni del corso. &egrave; possibile
fare più backup diversi per ognuna di queste risorse.
</form>


