<br>
<div align="center">
<H2>ALGEMENE HELPPAGINA</H2>
<table border=1 cellspacing=1 cellpadding=1  width="100%">
	<th><font size=+1>
	    De syntax (de schrijfwijze) voor wiskunde (zoals je antwoorden), 
	    in een computer (maar ook in de rekenmachine)
	    is als volgt<br>
	    </font>
	</th>
	<tr>
	<th>
	    <ul><div align="left">
		<li>Gebruik <b>&lowast;</b> als je wilt vermenigvuldigen<br>
		dus jij moet 5*6 intypen voor 5&sdot;6 of 5&times;6 <br>
		IN*UIT  , INVOER*UITVOER enz enz 
		<li>Gebruik <b>^</b> of <b>**</b> voor machtsverheffen<br>
		dus jij mag intypen 5^6 voor <b>5<sup><small>6</small></sup><br>
		dus jij mag intypen 5**6 voor <b>5<sup><small>6</small></sup>
		<li>Gebruik een <b>/</b> als je een breuk wilt noteren<br>
		dus jij moet 5/6 intypen voor 5&divide;6 
		<li>Het gebruik van haken is heel verstandig bij delen en vermenigvuldigen<br>
		5/6*2 =10/6=5/3 en <em><font size=+1 color=red>niet</font></em> 5/12 <br>
		Wanneer je onzeker bent moet je <font color=red>gewoon haken gebruiken</font><br>
		5/(6*2) = 5/12 <br> (5/6)*2 = 5/3 <br>
		Dus er geldt ook: 5/2*x =(5/2)*x en geen 5/(2*x) !!
		<li>Vereenvoudig <em>altijd</em> de breuken<br>
		dus 6/10 &rArr 3/5
		<li>Haal <b>NOOIT<b> de helen uit een breuk<br>
		Een komputer kan niet overweg met 2&nbsp;&nbsp;1/2<br>
		2&nbsp;&nbsp;1/2 &rarr; 21/2 =10.5 en <b>geen</b> 2.5 <br>
		Typ dus in 5/2 (of 2.5) <br>
		
		<li>
		Kies zoveel mogelijk voor een exacte oplossing <br>
		dus 1/3 is altijd te verkiezen boven 0.333333333333333333333333333333333
		<li>Noteer sqrt(x) voor <font size=+1><b>&radic;</b></font><em>x</em>
		<li>Noteer co&ouml;rdinaten van een punt bijvoorkeur als: <b><em>(x:y)</em></b>
		<li>Noteer meerdere co&ouml;rdinaten als: <b><em>(1:4) en (3:7) en ook (5:7) </em></b> 
		<li>Noteer oplossingen van vergelijkingen <b>altijd</b> in <em>nette</em> wiskunde notatie...<br>
		dus bijvoorbeeld:de oplossing is x=3 en x=5
		<li>Noteer sin(x) , cos(x) , tan(x) , log(x) voor <br>
		<b>sin</b><em>x</em> , <b>cos</b><em>x</em> , <b>tan</b><em>x</em> , <b>log</b><em>x</em>
		<li>bij ongelijkheden
		<ul>
		<li>noteer x&gt;=10 voor  x&ge;10 of andersom 10&lt;=x voor 10&le;x 
		<li>noteer x&lt;=10 voor x&le;10 of anderom  10&gt;=10 voor 10&ge;x
		<li>noteer x&lt;10 en x&gt;20 of andersom 10&gt;x en 20&lt;x
		<li>noteer 10&lt;x&lt;20 of x&gt;10 en x&lt;20 
		<li>en nog wat meer permutaties
		</ul>
		<li>Gebruik de term <b>pi</b> voor &pi;<br>Dus 6&sdot;&pi; &rarr 6*pi
		<li>Pas op met speciale toetsen (zoals<font size=+1> &euro;</font>) op Microsoft keyboards.<br>
		Ook kunnen sommige wiskunde unicode symbolen niet goed door internet exploder worden weergegeven.<br>
		(Microsoft heeft de arrogante gewoonte zich niets van gestandardiseerde industrie-normen aan te trekken)<br>
		In dergelijke gevallen is het goed aan te dringen op het installeren van Mozilla (Netscape/Fire Bird)
		<li>Bedenk goed dat een gebroken getal ingetypt moet worden
		met een <span style="color:blue"><b>punt</b></span> en <span style="color:red"><b>geen komma</b></span>
	        <br>
	        Dus <span style="color:blue"><b>5.5</b></span> en  geen <b>5<span style="color:red">,</span>5</b>

	    </ul>
	</th>
	<tr>
	<th><div align="left">
	Bij sommige sommen is het niet "wenselijk" een grafische of symbolische rekenmachine
	te gebruiken...klik dan voor een toegestane rekenmachine op dit icoontje<br>
	<div align="center">
		    !read $authordir/rekenmachine2.nl
	</div>
	</th>
	<tr>
	<th>
<ul><div align="left">
    <li>Wees geduldig als de pagina zich aan't laden is.
    <li>Je moet nooit dubbelklikken op hyperlinks -1 keer is genoeg
    <li>Jullie komputers ;-) kunnen vastlopen als je te wild zit te klikken<br>
	Als dit tijdens een repetitie gebeurt hebben we een echt probleem...<br>
	alhoewel deze server alle activiteiten logt ,en ik de mogelijkheid<br>
	heb de zaak "terug-te-spelen", kunnen we het er beter niet op aanlaten komen...
    <li>Onderaan bijvoorbeeld  de "$module_title "-pagina zit een knop<br> 
	<input type=submit value="OK en VERSTUREN"><br>
	<b>Deze</b> zou ik gebruiken om ALLE ingevulde antwoorden in te leveren.<br>
    <li>Helaas doet de <b>ENTER-toets</b> het vaak ook prima.<br>
	Druk je deze in als je nog niet klaar bent met invullen, is dat
	wel jouw pech !!!(oversteken zonder te kijken ook...)<br>
    <li>Sommige oefeningen/sommen houden rekening het kleine ongelukjes...<br>
	Dan stuur ik de niet geheel (goed) ingevulde pagina terug ter verdere invulling...
    <li>Ook wordt er af en toe -maar het is wel een enorme bult werk voor mij- rekening
	gehouden met typ/syntax fouten. Dan probeer ik toch nog het goede te vinden in een verkeerd
	antwoord. Beter is gewoon geen fouten te maken...
    <li>Dus <b>nooit</b> de enter knop indrukken als je niet <b> zeker weet</b> dat alles ingevuld is. <br>
	Wen je aan alleen  <input type=submit value="OK en VERSTUREN"> te gebruiken...
    <li>Het is erg handig de <b>TAB-toets</b>  te gebruiken om <br>
	<input size="18" name="" value="langs "><br>
	<input size="10" name="" value="de"><br>
	<input size="22" name="" value="invulvelden"><br>
	<input size="10" name="" value="te "><br>
	<input size="18" name="" value="browsen"><br>
	En met <b>Shift TAB</b> ga je weer terug
    <li>Voer je berekeningen eerst uit op papier en noteer je antwoord...<br>
	Typ het daarna pas in het invoerveld...<br>
	<textarea cols="40" rows="4">Som staat er een echt invoerveld geschikt voor meerdere antwoorden
	
	
	
	
	
	
	
	
	
	
	
	
	</textarea> 	
    <li>Verder is het zo dat elke sessie  een individueel nummer krijgt.
	Hierdoor kun je de <b>TERUG</b>-knop van je browser<span style="color:red"> <b>NIET</b></span> gebruikten.
	Omdat je dan eigenlijk een nieuwe sessie aanvraagt...de oude kun je zo wel kwijt raken 
    <li>Gebruik dus alleen de op de webpagina zelf
	aanwezige  mogelijkheden <a href>hyperlinks</a> om terug te gaan, naar je klas te gaan enz enz
    <li>Voor sommige oefeningen is <span style="color:red"><b>zeer</b></span> veel rekenkracht noodzakelijk<br>
	Hierdoor kan het soms wat langer duren voor de pagina in beeld komt. Wees daarom
	geduldig als de browser aangeeft dat ie communiceert met de server...<br>
	Besef goed dat iedereen een andere som krijgt en dat alle plaatjes/berekeningen uniek zijn<br>
	dus ook speciaal voor jou, $wims_firstname worden aangemaakt.
    <li>Soms maakt een opgave gebruik van een <i>Java Applet</i>.<br>
	Java is een door <b>Sun Microsystems</b> ontwikkeld gratis/vrijelijk beschikbaar programmeersysteem, 
	dat draait op bijna alle hardware (!) en alle echte besturingssystemen :
	
	<ul><div align="left">
	    <li>alle <b>Unix's</b> smaken 
		<ul><div align="left">
		    <li>Unix (SunOS,HP-UX,AIX,Solaris,RiscOS,IRIX,NeXT,SCO,VMS enz enz)
		    <li>GNU/Linux=UNIX voor de gewone intel-PC <img src=gifs/Penguin.gif height=40 >
			de computer waar je deze webpagina's vandaan haalt loopt op GNU/Linux
		    <li>BSD-familie (BSDi,OpenBSD,FreeBSD,NetBSD) 
		    <li>Apple Mac OSX (ach, had ik die maar...)
		</ul>
	    <li>BeOS
	    <li>Apple oudere OS'es
	<li>Microsoft windows  (gatver..)   
	</ul>
    <li>Een applet is een klein en veilig Java-bytecode programmaatje,<br>
	dat via internet kan worden verstuurd en runtime wordt uitgevoerd in een
	browser venster.
    <li>Dus zorg dat je browser (iexplorer,netscape,opera enz) de java heeft
	"aanstaan" en dat je uiteraard een <i>Java Virtuele Machine</i> aanboord hebt...
    <li>Sommige van de <i>Applets</i> praten met de WIMS-server, dat wil zeggen ze sturen
	jouw "antwoord" terug. 
    <li>In dat geval staat onderaan de <i>Applet</i> staan de knopjes <b>[Alles Wissen]</b> en <b>[OK en Versturen]</b><br>
	De laatste dus gebruiken als je vindt dat je antwoord <span style="color:green">goed is...</span>
    <li>Deze WWW Interactive Wiskunde Server "hangt" ook aan internet,<br>
	Zodat buiten de reguliere schooltijd, je oefeningen, lesmateriaal & uitwerkingen enz kunt bestuderen
    <li>Omdat dit voor jullie -maar ook voor mij- behoorlijk nieuw is,
	kunnen er dingen nog onduidelijk (behalve de wiskunde, natuurlijk) zijn.<br>
	Email of trek me aan m'n jas, als je iets niet snapt...
</ul>
</th>
<tr>
<th>
<h3>
<p align="center">HUISREGELS</h3>
<ul type="square"><div align="left">
    <li>Deze <span style="color:green">WWW Interactieve Wiskunde Server</span> <span style="color:red">WIMS</span> kijkt je antwoorden gelijk na, en geeft direct een cijfer.<br>
	Over dit cijfer is <b> geen discussie</b> mogelijk !!!<br>
	De wiskunde software heeft -helaas voor jullie- <b> altijd</b> gelijk...tenzij ik natuurlijk een
	programeer-foutje heb gemaakt.<br>
	In dat geval moet je dit zo snel mogelijk melden!!!
    <li>Verder wordt alle dataverkeer tussen jullie komputers gelogd,
	zodat met elkaar <b>chatten</b> of <b>emailen</b> tijdens een repetitie onheroepelijk een <b>onvoldoende</b> tot gevolg heeft...
    <li>Zorg ervoor dat je <b>wachtwoord</b> "geheim" blijft...Desnoods verander je dat regelmatig.<br>
	Mocht je het vergeten zijn,niks aan de hand, ik kan dat zo voor je opzoeken...
    <li>$voornaam, inloggen als iemand anders is <b>altijd</b> te achterhalen door
	de unieke combinatie van het fysieke netwerkadres (de computer op jouw werkplek... $httpd_REMOTE_ADDR ) en je <span style="color:red">WIMS</span>-inlogsessienummer<b> $session </b>,en is uiteraard verboden.
    <li>Er zijn mechanismen in deze server ingebouwd om <span style=color:red>servertje-pesten</span>
	ondervangen.
    <li>Het kan zelfs zo zijn dat jij er afgegooid wordt als je de zaak loopt te verstieren...
	en je account wordt dan gewoon geblokkeerd.
    <li>Mocht je er inslagen de zaak te hacken en <b>root</b> te worden op deze server
	krijg je van mij een dikke voldoende !!<br>
	<small>als je mij vertelt hoe je dit voor mekaar hebt gekregen</small> 
</ul>
</th>
<tr>
<th>
<b>Veel sterkte</b>,<br>

Mevr. Evers
</table>
