
<center><h3>Examples of interactive exercises under OEF format</h3></center> <p>

Here are some exampls of interactive exercises one can create by Createxo.
<ol>
<p><hr width=50%> <p>
<li> <b>Length of vector 2D</b>, a simple computation of the length of
a vector in the plane. Here is the complete source of this exercise.

<p><pre>
\title{Norm of vector 2D}
\language{en}
\computeanswer{no}
\format{html}

\integer{x=random(-10..10)}
\integer{y=random(-10..10)}
\real{norm=sqrt((\x)^2+(\y)^2)}
\statement{What is the length of the vector (\x,\y) in R<sup>2</sup>?}

\hint{The length of a vector  (x,y) is equal to 
sqrt(x^2+y^2).}
\answer{The length}{\norm}
</pre> <p>

In this exercise, one has defined 2 random integers, x et y, who are the
coordinates of the vector. Then a third parameter, this time real, is defined
by the formula of the length. The exercise takes a freestyle reply under the
name of ``the length'', and the good reply should be the value of the third
parameter``norm''. A hint is prepared in the exercise, which recalls the
formula of the length. <p>
You can
!set parm=oef_answercnt=1&oef_choicecnt=0&oef_title=Norm of vector 2D&oef_format=html&oef_computeanswer=no&level=2&oef_parms=%5Cinteger%7Bx%3Drandom%28-10..10%29%7D%0D%0A%5Cinteger%7By%3Drandom%28-10..10%29%7D%0D%0A%5Creal%7Bnorm%3Dsqrt%28%28%5Cx%29%5E2%2B%28%5Cy%29%5E2%29%7D&oef_statement=What is the length of the vector %28%5Cx%2C%5Cy%29 in R%3Csup%3E2%3C%2Fsup%3E%3F&ansprompt1=The length&ansgood1=%5Cnorm&oef_hint=The length f a vector %28x%2Cy%29 is equal to %0D%0Asqrt%28x%5E2%2By%5E2%29.&oef_solution= $
!href cmd=reply&mode=guided&$parm load this example into the menu
 to test it. (You can also copy the source into the menu under raw mode.)

<p><hr width=50%> <p>
<li> <b>Trace of matrix 2x2</b>, computes the trace of a matrix. The question
 is formatted by TeX, for a better presentation of the matrix. Here is 
 the complete source of the exercise.
<p><pre>
\title{Trace of matrix 2x2}
\language{en}
\computeanswer{yes}
\format{tex}

\integer{range=20}
\integer{a=random(-\range..\range)}
\integer{b=random(-\range..\range)}
\integer{c=random(-\range..\range)}
\integer{d=random(-\range..\range)}
\integer{trace=(\a)+(\d)}
\statement{Compute the trace of the matrix
$$\pmatrix{\a&\b\cr \c&\d}$$.}

\answer{The trace}{\trace}
</pre> <p>
We have first defined an integer ``range'', to be used to bound the
random values a,b,c,d which are the elements of the matrix. And the trace is
of course defined by the sum of the elements on the diagonal. Please take
care to the definition <tt>trace=(\a)+(\d)</tt>: the pairs of parentheses
are necessary, for the substitution is literary. If you define
<tt>trace=\a+\d</tt> and if a and d take the values of 3 and -15 respectively, 
you woule have <tt>trace=3+-15</tt>, a bad mathematical expression. <p>
Remark that in this exercise, the non-computed replies are admitted
(such as 2+15 or 3*105). <p>
You can
!set parm=oef_answercnt=1&oef_choicecnt=0&oef_title=Trace of matrix 2x2&oef_format=tex&oef_computeanswer=yes&level=2&oef_parms=%5Cinteger%7Brange%3D20%7D%0D%0A%5Cinteger%7Ba%3Drandom%28-%5Crange..%5Crange%29%7D%0D%0A%5Cinteger%7Bb%3Drandom%28-%5Crange..%5Crange%29%7D%0D%0A%5Cinteger%7Bc%3Drandom%28-%5Crange..%5Crange%29%7D%0D%0A%5Cinteger%7Bd%3Drandom%28-%5Crange..%5Crange%29%7D%0D%0A%5Cinteger%7Btrace%3D%28%5Ca%29%2B%28%5Cd%29%7D&oef_statement=Compute the trace of the matrix%0D%0A%24%5Cpmatrix%7B%5Ca%26%5Cb%5Ccr %5Cc%26%5Cd%7D%24.&ansprompt1=The trace&ansgood1=%5Ctrace&oef_hint= &oef_solution= $
!href cmd=reply&mode=guided&$parm load this example into the menu
 to test it. (You can also copy the source into the menu under raw mode.)


</ol>

