
!set field=!item 2 of $special_parm

!if $field=$empty
 !exit
!endif

!set embraced_randitem=<p> \
Questo campo accetta liste di parametri (tra parentesi graffe) tra cui \
scegliere casualmente.\
<p>\
Se si mettono più parole (o frasi) separate da virgole tra parentesi graffe, \
il sistema sceglierà casualmente una parola (o frase) da inserire nel testo \
per gli studenti, permettendo così di avere variazioni sul testo. <p>\
Ad esempio, se si inserisce il codice <p>\
<font color=blue><tt>I will go to {Paris, New York, London} \
{tomorrow, the next week}</tt></font>,\
<p>il risultato sarà una scelta casuale tra le seguenti frasi:\
<pre>\
I will go to Paris tomorrow\
I will go to New York tomorrow\
I will go to London tomorrow\
I will go to Paris the next week\
I will go to New York the next week\
I will go to London the next week\
</pre>

!if $(special_parm[3])!=$empty
 !readproc model/cut.proc model/src/$(special_parm[3]).oef
 !set title$field=$model_title
!else
 !readproc model/cut.proc
 !set title1=$model_title
!endif

<center><h2>$(title$field)</h2></center>

!if $field=1
 <center><b>$desc</b></center> <p>
!endif

$(help$field)

!if $(name$field) iswordof $model_random
 <p>
 Esempi di parametri generati in modo casuale: <ul>
 <li>Per un numero intero tra 10 e 100 (inclusi):
	 <tt>randint(10..100)</tt>
 <li>Per un intero multiplo di 10 tra 10 e 1000 (inclusi):
	<tt>randint(1..100)*10</tt>
 <li>Per un numero decimale tra 0 e 2:
	<tt>random(0..2)</tt>
 <li>Per un elemento casuale di un alista:
	<tt>randitem(a,b,c,10,100,parola,una frase)</tt>
 </ul> <p>
!endif

!if $(name$field) iswordof $model_computed $model_random
 <p>
 !href cmd=help&special_parm=parameters Clicca qui
 per maggiori informazioni sui parametri random.
!endif

