!set size=50

!if $title=$empty or $modreq=.new
 !set this=de votre nouveau module
!else
 !set this=du module actuellement en développement
!endif
!form reply
<input type=hidden name=jobreq value=flist>
$table_header
<caption>Propriétés $this:</caption>

$table_tr<td align=right nowrap>Adresse
 <td>
 !if $title!=$empty and $modreq!=.new
  <tt>$modreq</tt>&nbsp;
  !href cmd=reply&jobreq=move&original=devel/$auth_login/$modreq renommer
&nbsp;
  !href cmd=reply&jobreq=copy&original=devel/$auth_login/$modreq dupliquer
 !else
  !set modreq=.new
  !read scripts/addressform.phtml nook
 !endif
$table_tr<td align=right nowrap><label for="i_title">Titre</label>
 <td><input size=$size name=i_title id="i_title" value="$i_title">

$table_tr<td align=right nowrap><label for="i_description">Description</label>
 <td><input size=$size name=i_description id="i_description" value="$i_description">

$table_tr<td align=right nowrap><label for="i_language">Langue</label>
 <td>
 !default i_language=$module_language
 !formselect i_language list $langlist prompt $langname

$table_tr<td align=right nowrap><label for="i_label">Type</label>
 <td nowrap>
 !set wims_formselect_switch=multiple
 !formcheckbox i_category list exercise,tool,document,recreation,oef,deductio\
   prompt exercice, outil, document, récréation, OEF, Deductio

$table_tr<td align=right nowrap><label for="i_domain">Domaine</label>

 <td>
 <input size=$size name=i_domain id="i_domain" value="$i_domain">
<small>
!href cmd=help&special_parm=domain aide
</small>
$table_tr<td align=right nowrap><label for="i_level">Niveau(x)</label>
 <td>
 !formcheckbox i_level list $levellist
 <br><small>E: école primaire; H: école secondaire; U: université;
 <br>G: étude doctorale; R: recherche</small>

$table_tr<td align=right nowrap><label for="i_scoring">Mécanisme de score</label><br>
 <small>(exercice / récréation)</small>
 <td>
 !default i_scoring=no
 !formradio i_scoring list yes,no prompt Oui, Non

$table_tr<td align=right nowrap><label for="i_version">Version</label>
 <td>
 !default i_version=1.00
 <input type=text size=6 name=i_version id="i_version" value="$i_version">
 <small>N'oubliez pas de l'incrémenter quand vous publiez une nouvelle
 version !</small>
$table_tr<td align=right nowrap><label for="i_wims_version">wims_version</label>
 <td>
 !default i_wims_version=$wims_version
 <input type=text size=6 name=i_wims_version id="i_wims_version" value="$i_wims_version">&nbsp;
 !href cmd=help&special_parm=wimsversion aide

$table_tr<td align=right nowrap><label for="i_author">Auteur</label>
 <td>
 !default i_author=$auth_name
 <input type=text size=$size name=i_author id="i_author" value="$i_author">

$table_tr<td align=right nowrap><label for="i_adress">Email de l'auteur</label>
 <td>
 !default i_address=$auth_email
 <input type=text size=$size name=i_address id="i_address" value="$i_address">

$table_tr<td align=right nowrap><label for="i_translator">Traducteur</label>
 <td>
 <input type=text size=$size name=i_translator id="i_translator" value="$i_translator">

$table_tr<td align=right nowrap><label for="i_translator_address">Email du traducteur</label>
 <td>
 <input type=text size=$size name=i_translator_address id="i_translator_address" value="$i_translator_address">

$table_tr<td align=right nowrap><label for="i_soutien">Logiciels de soutien<br>nécessaires</label>
 <td>
 !formcheckbox i_require list $swlist prompt $swname

$table_tr<td align=right nowrap><label for="i_keywords">Mots clés</label>
 <td><input size=$size name=i_keywords id="i_keywords" value="$i_keywords">

$table_tr<td align=right <label for="i_copyright">Droit d'auteur</label>
 <td>
 !set wims_formselect_switch=
 !formselect i_copyright list gnu prompt GNU General Public License

$table_hdtr<td align=center nowrap colspan=2>
<input type=submit name=inddef id="inddef" value="$wims_name_tosave">
&nbsp;&nbsp;
<input type=submit value="$wims_name_giveup">
$table_end
</form>

