!set size=50

!if $title=$empty or $modreq=.new
 !set this=de votre nouveau module
!else
 !set this=du module actuellement en développement
!endif
!form reply
<input type=hidden name=jobreq value=flist>
$table_header
<caption>Propriétés $this:</caption>

$table_tr<td align=right nowrap>Adresse
 <td>
 !if $title!=$empty and $modreq!=.new
  <tt>$modreq</tt>&nbsp;
  !href cmd=reply&jobreq=move&original=devel/$auth_login/$modreq renommer
&nbsp;
  !href cmd=reply&jobreq=copy&original=devel/$auth_login/$modreq dupliquer
 !else
  !set modreq=.new
  !read scripts/addressform.phtml nook
 !endif
$table_tr<td align=right nowrap>Titre
 <td><input size=$size name=i_title value="$i_title">

$table_tr<td align=right nowrap>Description
 <td><input size=$size name=i_description value="$i_description">

$table_tr<td align=right nowrap>Langue
 <td>
 !default i_language=$module_language
 !formselect i_language list $langlist prompt $langname

$table_tr<td align=right nowrap>Type
 <td nowrap>
 !set wims_formselect_switch=multiple
 !formcheckbox i_category list exercise,tool,document,recreation,oef,deductio\
   prompt exercice, outil, document, récréation, OEF, Deductio

$table_tr<td align=right nowrap>Domaine

 <td>
 <input size=$size name=i_domain value="$i_domain">
<small>
!href cmd=help&special_parm=domain aide
</small>
$table_tr<td align=right nowrap>Niveau(x)
 <td>
 !formcheckbox i_level list $levellist
 <br><small>E: école primaire; H: école secondaire; U: université;
 <br>G: étude doctorale; R: recherche</small>

$table_tr<td align=right nowrap>Mécanisme de score<br>
 <small>(exercice / récréation)</small>
 <td>
 !default i_scoring=no
 !formradio i_scoring list yes,no prompt Oui, Non

$table_tr<td align=right nowrap>Version
 <td>
 !default i_version=1.00
 <input type=text size=6 name=i_version value="$i_version">
 <small>N'oubliez pas de l'incrémenter quand vous publiez une nouvelle
 version !</small>
$table_tr<td align=right nowrap>wims_version
 <td>
 !default i_wims_version=$wims_version
 <input type=text size=6 name=i_wims_version value="$i_wims_version">&nbsp;
 !href cmd=help&special_parm=wimsversion aide

$table_tr<td align=right nowrap>Auteur
 <td>
 !default i_author=$auth_name
 <input type=text size=$size name=i_author value="$i_author">

$table_tr<td align=right nowrap>Email de l'auteur
 <td>
 !default i_address=$auth_email
 <input type=text size=$size name=i_address value="$i_address">

$table_tr<td align=right nowrap>Traducteur
 <td>
 <input type=text size=$size name=i_translator value="$i_translator">

$table_tr<td align=right nowrap>Email du traducteur
 <td>
 <input type=text size=$size name=i_translator_address value="$i_translator_address">

$table_tr<td align=right nowrap>Logiciels de soutien<br>nécessaires
 <td>
 !formcheckbox i_require list $swlist prompt $swname

$table_tr<td align=right nowrap>Mots clés
 <td><input size=$size name=i_keywords value="$i_keywords">

$table_tr<td align=right nowrap>Droit d'auteur
 <td>
 !set wims_formselect_switch=
 !formselect i_copyright list gnu prompt GNU General Public License

$table_hdtr<td align=center nowrap colspan=2>
<input type=submit name=inddef value="Enregistrer les changements">
&nbsp;&nbsp;
<input type=submit value="Annuler">
$table_end
</form>

