
!if $passchange!=yes
 Changer les propriétés de votre compte de développement
 <font color=blue><tt><b>$auth_login</b></tt></font>
 sur <font color=blue><tt>$httpd_SERVER_NAME</tt></font> :
 <small>(laissez le champ "<tt>mot de passe</tt>" vide si vous voulez
 conserver l'ancien)</small>
!else
 Le mot de passe de votre compte a été changé.
!endif
<p>

!form reply
<center><table border=0>
<tr><td align=right nowrap>Nom: </td>
<td><input type=text size=40 name=p_name value="$auth_name">
</td></tr>
<tr><td align=right nowrap>Adresse email: </td>
<td><input type=text size=40 name=p_email value="$auth_email">
</td></tr>
<tr><td align=right nowrap>Mot de passe: </td>
<td><input type=password size=20 name=p_pass1>
</td></tr>
<tr><td align=right nowrap>Mot de passe encore: </td>
<td><input type=password size=20 name=p_pass2>
</td></tr>
<tr><td align=center colspan=2 nowrap>
<input type=submit name=confirm value="Sauver">
<input type=submit value="Annuler">
</td></tr></table> </center> <p>
</form>
