
Lijst van de meest gebruikte modules op deze website.
<ul class="wims_browse_list">
 <li class="wims_browse_list">
  !href module=tool/geometry/animtrace bewegende curves
  ,een online functie-plotter die bewegende curves en oppervlakten kan 
  tekenen.
  Voer de gewenste vergelijking in (met bijhorende parameters) en je krijgt
  de bijhorende curve (die ook nog eens kan draaien, inzoomen, vervormen enz...)
  Bevat ook een demopagina met verschillende voorbeelden.
  <p>
  De module
  !href module=tool/geometry/polyray Polyray
  zorgt voor een "ray-traced" oppervlak van een vergelijking.
  Ook hier zijn animaties van het oppervlak mogelijk...bedenk wel dat 
  ingewikkelde oppervlakken behoorlijk veel processortijd vergen...  
  
 
</li><li class="wims_browse_list">
  !href module=tool/analysis/function Grafische "rekenmachine":
  Voer je vergelijking in en klik op de diverse eigenschappen die je wilt weten van 
  de functie, zoals de integraal, de afgeleide, de limieten , de wortels
  de maxima en minima, de grafiek enz enz<p>
  Iets soortgelijks is de
  !href module=tool/linear/matrix Matrix "rekenmachine" die je inzicht verschaft 
  over alles wat je zou kunnen willen weten over je matrices:
  determinant,inverse,karakteristieke polynoom, eigen-waarde ,eigen-vectoren enz...

 
</li><li class="wims_browse_list">
  !href module=tool/geometry/rulecomp Passer &amp; Lineaal
  geeft je het gereedschap om geometrische constructies te maken.

</li><li class="wims_browse_list">
  !href module=tool/algebra/factor Ontbinden in factoren
  
  van integers en polynomen, krachtig en gemakkelijk in gebruik.
  It factors integers of around 50 digits within seconds. 
  You may also choose the base field
  for your factorization of polynomials: $m_QQ, $m_RR, $m_CC, or even prime
  finite fields.
  
</li><li class="wims_browse_list">
  Enkel online wiskunde spelletjes:
  !href module=H2/algebra/bargame Bar game
  ,
  !href module=H6/algebra/decrypt Ontsleutelen
  ,
  !href module=H3/algebra/spuzzle Schuifpuzzel 
  .  
</li><li class="wims_browse_list">
  !href module=H5/geometry/gravshoot Gravity shoot
  is another graphical exercise which gives you some points and asks you
  to click on the gravity center of the points. Your score depends on the
  precision of your clicks, as in a shooting gallery.
  <p><small>
  Other exercises in the same series:
  !href module=H4/geometry/trishoot Triangular shoot
  ,
  !href module=U1/algebra/vecshoot Vector shoot
  ,
  !href module=H6/algebra/compshoot Complex shoot
  ,
  !href module=U1/algebra/linshoot Linear shoot
  .</small>

</li><li class="wims_browse_list">
  !href module=H6/geometry/coincfree Coincidence freehand
  , a visual exercise which gives you a curve and asks you to find
  a function whose curve is as close to the given one as possible.
  <p><small>
  Other exercises in the same series:
  !href module=U1/algebra/coincpoly Coincidence polynomial
  ,
  !href module=U1/analysis/coincdev Coincidence dev
  ,
  !href module=U1/analysis/coinc_eqdif Coincidence EqDiff
  .</small>
  
</li></ul>

