!if robot isin $session
 <html><body $wims_htmlbody>
 This page is not accessible to robots.

 </body></html>
 !exit
!endif

!set wims_html_onload=!append word window.focus(); to $wims_html_onload
!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody onload=window.focus();>
!!headmenu
!header1

<center><h1>
<font color=red>W</font>WW
<font color=red>I</font>nteractieve
<font color=red>M</font>ultipurpose
<font color=red>S</font>erver<br>
<font size="-1">op <a href="/">$httpd_HTTP_HOST</a></font>
</h1></center>

!read $job.phtml

!if $job!=home
 <p>
 !href module=$module&cmd=new&job=home Andere 
 "browse" methodes
.
!endif

!tail

