
!if $class_defined!=yes
 <b>Error</b>. Demaneu entrar a $name_classess i no existeix.
 Sisplau, comproveu la vostra demanda.
 !exit
!endif

Per tal d'entrar a la classe <b><font
color=green>$class_description</font></b> de
<b><font color=green>$class_institution</font></b> com a
<em>participant registrat</em>, sisplau dóna el nom d'usuari i la contrasenya personal.

<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>Nom d'usuari: <td><input size=20 name=auth_user value="$auth_user">
 <tr><td>Contrasenya: <td><input type=password size=20 name=auth_password>
 $table_end
 <p><center>
 <input type=submit value="Acceptar">
</center>
</form> <p>

Nou participant:
!href module=adm/class/reguser&class=$class&subclass=yes clica ací
 per registrar-te a aquesta classe.

