
!if $class_defined!=yes
 <b>Error</b>. Demaneu entrar a $name_classess i no existeix.
 Sisplau, comproveu la vostra demanda.
 !exit
!endif

Per tal d'entrar a la classe <b><font
color=green>$class_description</font></b> de
<b><font color=green>$class_institution</font></b> com a
<em>participant registrat</em>, sisplau dóna el nom d'usuari i la contrasenya personal.

!!!##language independant
<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>$wims_name_Login<td><input size=20 name=auth_user value="$auth_user"></td>
 <tr><td>$wims_name_Password<td><input type=password size=20 name=auth_password></td>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register