!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=grup de classes
    !set name_sup=professor
   !else
    !set name_classe=institució
    !set name_sup=supervisor
   !endif
     !set name_classes= la $name_classe
     !set name_classess= una $name_classe
     !set name_classesss= d'una $name_classe
     !set name_classessss= La $name_classe
 !else
   !set name_classe=class
   !set name_classes=la $name_classe
   !set name_classess=una $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= la $name_classe
   !set name_sup=professor
 !endif

 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel de classe,curs
   !set Name_level= !item $splevel of Nivell,Classe,Curs
   !set Name_levels= !item $splevel of Nivells,Classes,Cursos
   !set sousclasses_else=!item $splevel of o una class, o un curs
   !set name_level_else= !item $splevel of un nivell,una classe,un curs
 !else
   !set sousclasses=sub-classes
   !set sousclasses_else=una classe o una institució
 !endif
 
!set CL_Name	=Nivell,Classe,Programa,Curs,Curs interclasses,Test Zone
!set Name_program=Programes
!set name_program=programa
!set name_portalandgroup=Institucions i grups de classes
!set name_independantclass=Classes independents

!distribute items Registrar,anònim,oberta,protegida,curs,\
Nou participant,registrat,Tipus de connexió,Up\
into name_register,name_anonymous,name_open,name_protected,name_year,\
name_new_participant,name_registered,name_connexion,name_up

!distribute line No tens compte en altres classes.\
Cerca la teva classe\
No hi ha classes disponibles.\
Aucune classe ne correspond à votre recherche.\
Pots canviar directament a\
into name_noaccount,name_searchclass,name_noavailable,name_nofound,name_direct

!let classification=Ecole,Collège,Lycée,Université,Autre

!set name_text1=Clica al nom de la classe per entrar. Clica sobre el nom de la classe per \
anar a treballar-hi (cal que estiguis registrat com a participant de la classe).\
<p>\
Clica sobre `$name_register' per registrar-te a la classe (necessites la contrasenya de la classe,\
ha de donar-te-la el teu professor).


!set name_text2= Per anar a una altra $name_level_else $sousclasses_else, tria el seu nom a\
 la taula següent.
!set name_text3=O triar el nom $name_level_else $sousclasses_else a la taula següent.
!set name_language=No hi ha classes en català en aquest lloc. Potser estàs buscant classes en \
 una altra llengua ?
!set name_language2=Aquest lloc encara no conté cap classe en Català.
