
!if $overflow=yes
 !if $keyword = $empty
  Hi ha massa classes virtuals. Per veure la teva classe, sisplau fes alguna cerca.
 !else
  Encara hi ha massa classes corresponents a la teva cerca. Sisplau fes una cerca més precisa.
 !endif
 <p><center>
 !form reply
 <input size=20 name=keyword value="$keyword">
 <input type=submit value=OK>
 </form></center> <p>
!else
 !if ($sccnt + $clcnt > 20 and $wims_user = $empty) or $keyword!=$empty
  !form reply
  Cerca la teva classe:
  <input size=20 name=keyword value="$keyword">
  <input type=submit value=OK>
  </form>
 !endif
!endif

