
!if $wims_user!=$empty
 !read direct.phtml
 !if $wims_user!=supervisor and $supervisable!=yes
  !exit
 !endif
 <p>
!else
 Les classes virtuals permeten als professors organitzar els recurssos a WIMS
 (eventualment també crear els seus propis exercicis) pel treball dels seus
 estudiants, i tenir el control del seu progres.
 <p>
 Si encara no tens la teva pròpia classe: pots
 !href module=adm/class/regclass clicar ací
 per crear-ne una després de consultar les
 !href target=wims_help module=help/main&chapter=3 pàgines d'ajuda
, o donar una ullada a les
 !href module=$module&type=example classes d'exemple
. <p>
!endif

!if $clcnt+$sccnt>0
 !if $wims_user=empty
  En altre cas, pots localitzar la teva classe a la taula següent, i clicar
 sbre el seu nom per entrar com a supervisor.
 !endif
 !if $sccnt>0
  <p>
  $table_header
  <caption>Institucions i grups de classes</caption>
  $table_hdtr<th>Name</th><th>Administrador</th>
  <th>-</th>
  </tr>
  !for i=1 to $sccnt
   !set l=!line $i of $sclasses
   !distribute items $l into code,expire,in,cl,la,ty,lv,pswd
   !set supv=!item 9 of $l
   !default supv=!defof class_supervisor in wimshome/log/classes/$code/.def
   
   $table_tr
   <td align=center>
   !href module=$module&type=authparticipant&class=$code $in
   </td>
   </td><td align=center>$supv</td>
   <td align=center>
   !href module=adm/class/reguser&class=$code Register
&nbsp;
   !href module=$module&type=authsupervisor&class=$code Admin
   </td>
  !next i  
  $table_end
 !endif
 !if $clcnt>0
  <p>
  $table_header
  !if $superclass=$empty
   <caption>Classes independents</caption>
   $table_hdtr<th>Institució<th>Classe<th>Supervisor
  !else
   !if $splevel>1
    !set inst=!defof class_description in wimshome/log/classes/$superclass2/.def
   !else
    !set inst=!defof class_institution in wimshome/log/classes/$superclass/.def
   !endif
   <caption>$Name_levels in $inst 
   !if $splevel>1
    !href cmd=reply&type=$type&superclass2=$sparent Up
   !endif
   </caption>
   $table_hdtr<th>$Name_level<th>Supervisor
   !if $superclass!=$empty and $stype=4
    <th>More
   !endif
  !endif
  !for i=1 to $clcnt
   !set l=!line $i of $classes
   !distribute items $l into code,expire,in,cl,la,ty,lv,pswd
   !set supv=!item 9 of $l
   !default supv=!defof class_supervisor in wimshome/log/classes/$code/.def
   
   $table_tr
   !if $superclass=$empty
    <td align=center>$in</td>
   !endif
   <td align=center>
   !href module=$module&type=authsupervisor&class=$code $cl
   </td><td align=center>$supv</td>
   !if $superclass!=$empty and $stype=4
    <td>
    !if $ty!=1
     !href cmd=reply&type=$type&superclass2=$code subclasses
    !else
    -
    !endif
   !endif
  !next i
 !endif
 $table_end
!else
 !if $class_type=$empty and $superclass=$empty
  (Aquest lloc encara no conté cap classe en Català.)
 !else
  (No hi ha classes disponibles.)
 !endif
!endif
<p>

