
!read adm/title.phtml 1\
\
Formati foglio elettronico

csv (campi separati da virgole) e tsv (campi separati da tab) sono file
in formato testo utilizzati per esportare dati da un foglio elettronico.
La maggior parte dei programmi riconoscono entrambi i formati.
<p>
ods is the spreadsheet format defined by the OpenDocument ISO standard. It is supported by LibreOffice and OpenOffice, and it should be supported by any fair spreadsheet program.
</p>

