
!read adm/title.phtml 1\
\
Formati foglio elettronico

csv (campi separati da virgole) e tsv (campi separati da tab) sono file
in formato testo utilizzati per esportare dati da un foglio elettronico.
La maggior parte dei programmi riconoscono entrambi i formati.
<p>
ods è il formato di foglio elettronico definito dagli standard ISO OpenDocument. È utilizzato da LibreOffice e OpenOffice, e in prospettiva sarà utilizzato da ogni programma onesto di gestione di fogli elettronici.
</p>

