
<center><h3>Explorar por niveles</h3></center>

!form new
<input type=hidden name=module value=home>
<input type=hidden name=browse_job value=level>
<center><table border=0 cellpadding=0 cellspacing=0>
<tr><td><tr><td>
<tr><td align=center bgcolor=$bgcolor1><b>Categoría</b>
<td colspan=7 bgcolor=$bgcolor3>
!formradio search_category list A,X,T,R prompt \
		$name_A,$name_X,$name_T,$name_R
<tr><td><tr><td>
<tr><td align=center rowspan=6 bgcolor=$bgcolor1><b>Nivel</b>
 <th bgcolor=$bgcolor2>Curso
 !for i=1 to 6
  <td align=center bgcolor=$bgcolor2>$i
 !next i
 <tr><th bgcolor=$bgcolor2>Escuela primaria
 !for i=1 to 6
  <td align=center bgcolor=$bgcolor3>
  <input type=checkbox name=search_keywords value=levelE$i
  !if E$i=$thislevel
   checked
  !endif
  >
 !next i
 <tr><th bgcolor=$bgcolor2>Secundaria y Bachillerato
 !for i=1 to 6
  <td align=center bgcolor=$bgcolor3>
  <input type=checkbox name=search_keywords value=levelH$i
  !if H$i=$thislevel
   checked
  !endif
  >
 !next i
 <tr><th bgcolor=$bgcolor2>Universidad
 !for i=1 to 5
  <td align=center bgcolor=$bgcolor3>
  <input type=checkbox name=search_keywords value=levelU$i
  !if U$i=$thislevel
   checked
  !endif
  >
 !next i
  <td align=center bgcolor=$bgcolor3>-
 <tr><th bgcolor=$bgcolor2>Estudios de Licenciatura
  <td nowrap colspan=6 align=center bgcolor=$bgcolor3>
  --- <input type=checkbox name=search_keywords value=levelG
  !if G=$thislevel
   checked
  !endif
  > ---
 <tr><th bgcolor=$bgcolor2>Investigación
  <td nowrap colspan=6 align=center bgcolor=$bgcolor3>
  --- <input type=checkbox name=search_keywords value=levelR
  !if R=$thislevel
   checked
  !endif
  > ---
<tr><td><tr><td>
<tr><td colspan=8 align=center bgcolor=$wims_ref_bgcolor>
<input type=submit value="ADELANTE">
$table_end</form>

