!if $exocnt<=0
 Aquest full no conté cap exercici, de manera que el codi està buit.
 !goto end
!endif

Aquest és el codi d'aquest full. Podeu copiar aquest codi
(entre les dues línies formades per '*', utilitzant el portapapers)
en un arxiu, que és el que us permetra més endavant
reutilitzar el seu contingut en un altre full. 


<p>
******************************************************************
!read wimshome/$wims_sesdir/home_sheet.src
******************************************************************

:end
<p>
 !let wims_menu_items=!append line sheetadmin,1,cmd=resume to $wims_menu_items

