!set levelE=elementary school
!set levelH=secondary school
!set levelU=university

!set lang_fr=français
!set lang_en=English

!if $cltype iswordof 2 4
   !if $cltype=2
    !set name_classe=group of classes
    !set name_sup=of the teacher-supervisor
    !set name_classes= the $name_classe
    !set name_classess= a $name_classe
    !set name_classesss= of the $name_classe
    !set name_classessss= The $name_classe
   !else
    !set name_classe=institution
    !set name_sup=of the supervisor
    !set name_classes= the $name_classe
    !set name_classess= a $name_classe
    !set name_classesss= of the $name_classe
    !set name_classessss= The $name_classe
    !endif
 !else 
   !set name_classe=class
   !set name_classes=the $name_classe
   !set name_classess=a $name_classe
   !set name_classesss= of a $name_classe
   !set name_classessss= The $name_classe
   !set name_sup=of the teacher
 !endif

!distribute lines places<br>disponibles\
année\
ouverte,protégée\
into name_remainig, name_year,name_statut

