!distribute items nuevos módulos, actualizaciones de módulos, últimos cambios del sistema into \
	name_new, name_modif, name_sys

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!set module_title1=$module_title
!set module_title=$module_title<br><font size="+0">$httpd_HTTP_HOST</font>
!header
!set module_title=$module_title1

<center>
!for j in $joblist
 &nbsp;
 !if $j=$job
  <u><b>$(name_$j)</b></u>
 !else
  !href cmd=reply&job=$j $(name_$j)
 !endif
 &nbsp;
!next j
</center><p>

!read $job.phtml

!tail

