!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody>
!!!headmenu

!header1

!if $sheet_docpage!=$empty
 !changeto docpage.phtml
!endif
<h2>$wims_classname, $wims_institutionname</h2>
<hr><h3 class="wims_sheet_title">Work sheet #$sh<br>$sheet_title</h3>
<div class="wims_sheet_desc">$sheet_desc</div><p>

!if $sheet_expiration!=$empty and $sheet_active=1
 !set expday=!char 7,8 of $sheet_expiration
 !set expmon=!char 5,6 of $sheet_expiration
 !set expyear=!char 1 to 4 of $sheet_expiration
 !set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec
 !set expmon=!item $expmon of $months
 You can work on this sheet up to $expday $expmon $expyear.
!endif

!if $sheet_active=2
 <b><font color=red>Warning</font></b>
 This sheet has expired. You can still
 work on it, but your scores will no longuer be taken into account.
 <p>
!endif

!if $n=0
 !if $sheet_active=$empty
  You have no right to consult the content of this sheet for the time being.
  Please contact your supervisor.
 !else
  The sheet is empty! Nothing is assigned for you in it. Possibly an 
  error in the manipulation by your supervisor.
 !endif
!else
 Assigned works in this sheet: (Score registration is
 !set scorestat=!getscorestatus sheet=$sh
 !if $scorestat=yes
  !if $wims_scorereg!=suspend
   open, but you can
   !href cmd=resume&job=suspend suspend it
.)
  !else
   !set scorestat=no
   suspended by yourself.
   !href cmd=resume&job=reopen Reactivate it
.)
  !endif
 !else
  closed for your connection.)
 !endif
 <div class="wims_sheet">
 <p><ul class="wims_sheet_list">
 !for i=1 to $n
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sh
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  !set dep=!row $i of $deps
  !set dep=!trim $dep
  <li class="wims_sheet_list"><p>$i. 
  !if $dep=$empty or $scorestat!=yes
   !href module=$di&cmd=new&worksheet=$sh&$pa $ti
, $de
   !if $require>0
    <small>$[$got] out of $[$require] points obtained, quality
    $[$mean]/10.</small>
   !endif
  !else
   <font color=red><b>$ti</b></font>, $de 
   !if $require>0
    <small>($[$require] points required.)</small>
   !endif
  !endif
  !if $dep!=$empty
   <small>You must improve
   !if , isin $dep
    your scores on exercises $dep
   !else
    your score on exercise $dep
   !endif
   before scoring on this one.
   </small>
  !endif
 </li>
 !next i
 </ul>
 </div>
!endif

:contentend
!!!if $wims_user=supervisor
!!<p>
!!!href module=adm/class/sheet&sheet=$sh Sheet management page
!! (for supervisor).&nbsp;
!!!endif
!!!if $n>0
!! !href cmd=reply&job=print Printable version
!!.
!! !if $exolog!=$empty
!!  !href module=adm/class/exolog&job=llist&logsheet=$sh Register details of an exercise
!!.
!! !endif
!!!endif
!!<p>

!if $wims_user=supervisor
!set wims_menu_items=!append line sheetmanagement,1,module=adm/class/sheet&sheet=$sh\
to $wims_menu_items
!endif
!if $n>0
!set wims_menu_items=!append line printable,1,cmd=reply&job=print\
to $wims_menu_items
 !if $exolog!=$empty
  !set wims_menu_items=!append line exolog,1, module=adm/class/exolog&job=llist&logsheet=$sh \
to $wims_menu_items 
 !endif
!endif
!tail
