
!readproc adm/docsheet.prep
!read $docdef content
<p><center>
Score registration is
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   open, but you can
   !href cmd=resume&job=suspend suspend it
.
  !else
   suspended by yourself.
   !href cmd=resume&job=reopen Reactivate it
.
  !endif
 !else
  closed for your connection.
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc.en&job=edit&doc=$d_&block=$b_ Edit this page
.&nbsp;
 !href cmd=resume Reload
.
!endif
</center>

!tail

