!read adm/language names.phtml

!read lang/names.phtml.$modu_lang
!set wims_menu_items=!append line modtool,1,module=adm/modtool\
to $wims_menu_items
!if robot isin $session
  !exit
!endif
!header

<div $frame>
!if $wims_developer=$empty
<b>$module_title</b> 
!read lang/names.phtml.$modu_lang 1
!href cmd=help&special_parm=doc $name_documentation
 $wims_name_or 
 !getfile latex2wimsdoc.pdf $name_pdf
.
<p>

!read lang/names.phtml.$modu_lang 2


 !form reply
 $name_modtool

<p>
<table align="center"> 
<tr><td>$wims_name_Login</td><td><input type=login name=login></td></tr>
<tr><td>$wims_name_Password</td><td>
  <input type=password name=passwd>
</td></tr></table>
 <center> <input type=submit value="$wims_name_tosave"></center>
  </form>
  !tail
  !exit
!endif

!if $error!=$empty
  !read msg.phtml
!endif

<p>
<b>$module_title</b>
!read lang/names.phtml.$modu_lang 3

!href cmd=help&special_parm=doc $name_documentation
.
  
!set wims_form_method=file
!default !set execut=0
!form reply
!if $execut!=3
$name_select_example
(fichier latex, fichier de style latex et css) 
  !getfile fichier_test.tex $name_latex
,
  !getfile style.css $name_css
, 
  !getfile wims.sty $name_latex2wims
, 
  !getfile latex2wimsdoc.pdf $name_pdf
.
 !if $exemple!=1
    $name_example
      !formradio exemple list 1,2 prompt $wims_name_yes,$wims_name_no
  !endif
!endif 

<p>
!if $execut=0
  $hh $name_step 1</h2>
  $name_transfer_wims
  <input type=file name=wims_deposit>
  <p>
!if $test!=$empty and ($execut=0 or $cnt_fichier=1)
  $name_filet:
  <pre $pre>
  !for i = 1 to $cnt_fichier
    $(fichiers[$i]) ($(date[$i]))
   !next
   </pre>
!endif
  <p>
  <ul>
    <li>

   !formradio execut list 0 prompt $name_newtransfer
   </li><li>
   !formradio execut list 1 prompt $name_newstep
   </li>
   </ul>
!endif



!if $execut=1

$hh $name_step 1</h2>
!if $cnt_fichier >0 
   $name_youcan
    !formcheckbox execut list 0 prompt $name_newtransfer
 !else
   $name_youmust
   !default !set execut=0
   !formradio execut list 0 prompt $name_atleast
   
   <center>
<input type=submit value="$wims_name_tosave">
</center>
</form>
   !exit
 !endif
$hh $name_step 2</h2>
  $name_selectmain
  <ul>
    !for i = 1 to $cnt_fichier
      !set l=!item $i of $fichiers
      <li>
        !formradio principal list $i prompt $(fichiers[$i]) ($name_transferdate $(date[$i]))
      </li>
   !next 
  </ul>
  $name_sheet
  !formradio wksheet list 1,2,3,4,5,6,7,8,9
 $hh $name_step 3</h2>

!if $list_module!=$empty
   $name_namedocument:  
           <p align=center>
           !formselect document list $choix,$list_module    
         </p>
       $name_newmodule
!else
<i>$name_createfirst</i>
!endif
     !href target=wims_test module=adm/modtool&cmd=reply&jobreq=create Modtool

!if $document notsametext $choix
<p> <b>$wims_name_warning</b> : $name_warning
!else
<p> <b>$wims_name_warning</b> : $name_select_warning.
!endif
  $hh $name_step 4</h2>
     !formradio execut list 2 prompt $name_exec
  
!endif

!if $execut=3 
  !if $confirm=
   <p>
   !read lang/names.phtml.$modu_lang 4
   !formradio confirm list 0,1 prompt $wims_name_yes,$wims_name_no
    <ul>
  !else
    !if $confirm=0
 !reset confirm
 <ul><li>
     !href target=wims_internal module=devel/$wims_developer/$document $name_test
 (<i> $name_gotomodtool
!href target=wims_internal module=adm/modtool&jobreq=flist&modreq=$document $wims_name_modtool
</i>)
  </li>
   !endif
  !endif
   <li>
    !formradio execut list 1 prompt $name_comeback
  </li>
  <li>
    !formradio execut list 0 prompt $name_transfer
  </li>
  </ul>
!endif
<center>
<input type=submit value="$wims_name_tosave">
</center>
   
</form>

!if $wims_exec_error!=$empty
 <font color=red><pre>$wims_exec_error</pre></font>
!endif

</div>
!tail

!reset wims_exec_error wims_deposit

