
!if $wims_user!=supervisor
 Helaas, er is geen hulp voor leerlingen.
 !tail
 !exit
!endif
De inhoud van de stemming kan HTML-text zijn, met dezelfde uitbreidingen als geldig is voor de "forum-berichten", 
plus de volgende commando's <dl>
<p><dt><tt>\menu{JA,NEE}</tt>
	<dd>Menu Keuze.

<p><dt><tt>\list{A,B,C,D}</tt>
	<dd>Een keuze d.m.v. een rij verticale drukkopjes

<p><dt><tt>\radio{zeer slecht, slecht,redelijk, prima}</tt>
	<dd>Een keuze d.m.v. een rij horizontale drukkopjes

<p><dt><tt>\uservar{vname,val0,val1,...}</tt>
	<dd>
	Register the immediately preceding choice in an individual
	variable for the participant, under the name <tt>vname</tt>. This
	variable will take the value <tt>val0</tt> by default, <tt>val1</tt>
	if the participant chooses the first option, etc. <p>
	This variable may then be used to define individualized access to
	sheets or exams, by putting the word <tt>\vname</tt> among the
	restrictions of the sheet or exam.

</dl>
Uw stembillet mag tot 64 keuzevelden bevatten,

!tail

