<center><h3>Materiaal afhankelijkheden in een klas</h3></center>
<p>
Er zijn zeer vele ingewikkelde verbanden tussen de diverse soorten materiaal
in een virtuele klas.
<br>
Bijvoorbeeld, tentamens/proefwerken worden gedefinieerd aan de hand van werkbladen.
Werkbladen kunnen op hun beurt gebruik maken van 1 of meerdere oefeningen,
 komplete lesmodules als dan niet samen met calculaters, plotters enz. enz.
 Worden deze verbanden verbroken zal het lesmateriaal niet meer correct kunnen functioneren. 
<p>
Verder worden de cijfers "on the fly" berekend aan de hand van diverse instellingen.
Dus als er veranderingen in aktieve werkbladen worden aangebracht, wordt ook het cijfer adminitratie systeem
ontregeld .
