
<b>Importeren uit een a "buurt-klas"</b>.
<br>
U kunt lesmateriaal of leerling-acounts importeren van een 
!href cmd=help&special_parm=neighbor "buur-klas".
<p>
Om iets te importeren uit een andere klas, kies de "klas-naam" in de lijst van beschikbare virtuele
klassen op deze server.
 Wanneer U toestemming hebt om te importeren uit een klas, ziet u een link
naar de pagina met importeerbare bronnen uit deze klas.
 Alleen items die U niet in Uw eigen klas hebt , staan in deze lijst vermeld. 

<p>
Wanneer U iets importeert , heeft dit geen gevolgen voor de exporterende klas.
Veranderd U het geimporteerde materiaal heeft dit dus geen effect op het origineel. 
 Dit in tegenstelling met een andere manier om (les)materiaal van anderen te gebruiken
zoals het "delen" ofwel
!href cmd=help&special_parm=share "sharing"
 van materiaal.
<p>
Alleen actieve of verlopen werkbladen en tentamens/proefwerken zijn importeerbaar. 
 Een actief werkblad of proefwerk wordt zodra deze in Uw klas is geimporteers <b>inactief</b>.
 Dit geeft U de mogelijkheid het materiaal eers te bestuderen en/of naar Uw hand te zetten.
 Hierna moet U zelf dit materiaal activeren ,om het ter beschikking van Uw leerlingen te stellen.
<p>
Voor wat betreft het importeren van leerling-account gegevens, geldt dat
U geen leerling account kunt importeren als deze loginnaam reeds in Uw klas aanwezig is, 
zelfs als U deze leerling hebt verwijderd. 

