
<b>Een andere klas als "buur-klas" benoemen</b>.
<br>
Een 
!href cmd=help&special_parm=neighbor "buur-relatie"
</a> tussen twee klassen is alleen mogelijk met instemming van beide supervisors.
<p>
Alhoewel in principe collega's van een "buur-klas" nooit Uw klas kunnen veranderen
 (tenzij ze 
!href cmd=help&special_parm=share materiaal delen ("sharing")
 met uw klas), is het toch verstandig alleen buren te worden met
 klassen binnen een zelfde instituut.
<p>
Wanneer U buur-relaties aan gaat op "supervisor niveau" geeft U de andere
klas de mogelijkheid om lesmateriaal te
!href cmd=help&special_parm=import importeren 
. Dit betekend wel dat ook eventuele gevoelige data uit uw klas worden geimporteerd.
<p>
Verder wordt op "leerling niveau" ook de persoonlijke wachtwoorden van uw leerlingen
naar de "buur-klas" geexporteerd. 
<p>
Om het beveiligings niveau van een WIMS server zo hoog mogelijk te houden, moet U alleen
overgaan tot exporteren of zelfs delen, als dit echt noodzakelijk en handiger is.<br>
U verliest ook een flink deel autonomie bij het delen van bestanden en lesmateriaal.

