
<b>Een andere klas als "buur-klas" benoemen</b>.
<br>
Een 
!href cmd=help&special_parm=neighbor buur-relatie
 tussen twee klassen is alleen mogelijk met instemming van beide supervisors;
 of op leerling-nivo, of op supervisor-nivo  of beide.
<p>
Alhoewel in principe collega's van een "buur-klas" nooit Uw klas kunnen veranderen
 (tenzij ze 
!href cmd=help&special_parm=share materiaal delen ("sharing")
 met uw klas), is het toch verstandig alleen buren te worden met
 klassen die te vertrouwen zijn... 
<p>
Wanneer U buur-relaties aan gaat op supervisor-nivo geeft U de andere
klas de mogelijkheid om Uw lesmateriaal te
!href cmd=help&special_parm=import importeren 
. Dit betekend wel dat ook eventuele gevoelige data uit uw klas worden geimporteerd.
<p>
Verder wordt op leerling-nivo ook de persoonlijke wachtwoorden van uw leerlingen
naar de "buur-klas" geexporteerd. 
<p>
Om het beveiligingsnivo van een WIMS server zo hoog mogelijk te houden, moet U alleen
overgaan tot lenen/exporteren  of zelfs delen/sharing, als dit echt noodzakelijk is.

