
<b>"Buur klassen"</b>.
<br>
"Buur relaties" tussen klassen op de zelfde server zijn mogelijk.
Twee klassen worden "buur-klassen" wanneer de supervisors van beide klassen
!href cmd=help&special_parm=neibordecl elkaar erkend
 hebben als "buren".
 Lesmateriaal (documenten,werkbladen,oefeningen) als ook leerling informatie
 kan worden
!href cmd=help&special_parm=import uitgewisseld
 of
!href cmd=help&special_parm=share gedeeld
Leerlingen met een acount in buur-klassen kunnen ongemerkt van de ene klas naar de andere 
(dus zonder uit te loggen). 
<br>
Een klas kan een onbeperkt aantal buur-klassen hebben.  
<p>
Enkele voorbeelden van buur-klas configuraties 
!href cmd=help&special_parm=neiexample staan hier
.
