
<b>Stop een deling van lesmateriaal</b>.
<br>

Alleen de klas die leent kan een deling/lening van materiaal beeindigen, zie ook 
!href cmd=help&special_parm=share deling van lesmateriaal
 onder
!href cmd=help&special_parm=neighbor "buur-klassen"
.
<p>
Wanneer U stop met een lesmateriaal deling, blijft in Uw klas een kopie
van het gedeelde materiaal achter.
Hierdoor heeft het stoppen van delen/lenen niet ogenblikkelijk gevolgen voor uw klas.
Uw materiaal wordt nu dus ook niet meer via de deling/lening aangepast/verbeterd.
 <p>
In sommige gevallen wordt bij een beindiging van een delen  <b>geen kopie</b> in uw klas
achtergelaten. 
In een dergelijk geval krijgt u eerst een waarschuwing, voor dat U de deling kunt beeindigen. 

