
<b>Delen van het supervisor account</b>.
<br>
Wanneer U van plan bent het supervisor account
!href cmd=help&special_parm=neighbor te delen
met andere klassen, besef dan dat eventuele beveiligingsproblemen  ook worden geimporteerd.
<p>
Als alle klassen boren bij een zelfde docent (U dus), is het delen van een
supervisor account ginstig in verband met wachtwoorden (verandert U het wachtwoord
voor de ene klas, geldt dit door deling automatisch ook voor de andere klassen)
Hierdoor kunt U regelmatig gemakkelijk het wachtwoord veranderen.
Echter een gelijk wachtwoord voor al Uw klassen verhoogt ook risico bij 
uitlekken van dit wachtwoord.
Een dergelijke situatie heeft zich inmiddels ook daadwerkelijk voorgedaan.

