!read adm/title.phtml 2\
Dépendance à un module de données

Si votre module dépend d'un autre module qui contient des données comme des audio,
des vidéos, des images, celui-ci doit avoir une adresse du type
<span class="tt wims_fname">data/xxx/xxx.xx</span>.
Indiquez-la ici. Si le module de données n'est pas sur un serveur wims,
un message d'erreur s'affichera à l'entrée de votre module conseillant de demander
au gestionnaire du site de le télécharger.

