L'encodage des fichiers doit être isolatin.
<h3> Ajout d'un exercice programmé en format oef</h3>
<p>
Pour ajouter le source d'un exercice oef, utiliser le champ
<span class="wims_code_words">Ajouter un autre fichier</span> en bas de la page
en donnant le nom du fichier; il
doit être de la forme <span class="wims_fname">src/name_file.oef</span> ; cela
signifie qu'il doit se trouver dans le sous-répertoire <span class="wims_fname">src</span> du module et
que le nom du fichier doit se terminer par <span class="wims_fname">.oef</span> et ne contenir que des
caractères alphanumériques sans espace ni accents.
</p><p>
Une partie du texte d'un exercice peut être écrite en dehors du source
d'un exercice oef (par exemple une aide ou des données communes à
plusieurs exercices). Le nom d'un tel fichier doit être de la forme
<span class="wims_fname">name_file</span>
(son nom ne doit contenir que des caractères alphanumériques
sans espace ni accents).
</p><p>
Utiliser le menu <span class="text_icon binfile">$wims_name_binfile</span>
pour déposer les fichiers des images utilisées dans un exercice.
</p>
<h3>Fichiers à compléter/modifier avant la publication d'un module</h3>
<ul><li> pour la page d'introduction du module
<ul><li>
<span class="wims_fname">intro.phtml</span> : compléter la phrase
apparaissant dans la page d'introduction du module en précisant
le contenu des exercices, leur niveau ...
</li><li>
<span class="wims_fname">introhook.phtml</span> (dans le cas où certains exercices
utilisent des paramètres configurables par l'utilisateur
du module, paramètres dont le nom est imposé : <span class="wims_code_words">confparm1</span>,
<span class="wims_code_words">confparm2</span>, ..., <span class="wims_code_words">confparm5</span>).
</li></ul><li>
pour ajouter un texte en dessous des énoncés de tous les exercices du module
(par exemple, un lien vers un outil de wims)
<ul><li>
<span class="wims_fname">endhook.phtml</span>
</li></ul>
<li>pour modifier certains paramètres du module
<ul><li><span class="wims_fname">var.proc</span></li>
</ul></li></ul>
<h3>Fichier à modifier avant la republication d'un module</h3>
<span class="wims_fname">NEWS</span> pour indiquer les modifications
faites à chaque republication du module
</li>
L'incrémentation du numéro de la version du module et la modification des méta-données du module se fait
se fait dans la page de propriétés du module.
(pour l'obtenir cliquer sur le lien <span class="text_icon properties">Propriétés</span>).
D'autres méta-données du module comme la version du module, les mots clés sont à remplir là.
<h3>Pour plus d'informations</h3>
Pour plus de détails sur l'utilisation de ces fichiers, voir le document
<a target=wims_external href="wims.cgi?module=help/developer/docmodtooloef.fr">DocAide Modules d'exercices OEF.</a>
