
<h3><center>Publication d'un module</center></h3>

Si vous avez un compte dans le centre de publication des modules $centralhost,
vous pouvez y publier votre module. Et vous pouvez choisir de faire la
publication en tant que version développement ou version stable. Dans tous
les cas, cette publication sera visible dans l'adresse de téléchargement
<a href=$downloadsite>$downloadsite</a>.
<p>
En cas d'une publication stable, elle va se propager automatiquement à travers
les miroirs et les mises à jour automatiques à tous les serveurs WIMS du
monde entier.
<p>
Donc vous devez faire très attention de ne publier que des modules bien testés.
C'est particulièrement le cas quand vous modifiez un module d'exercices
existants.
<p>
Nous avons tous un désir constant d'améliorer nos oeuvres : une présentation
encore plus jolie, encore plus de capacités (ou dans le cas d'un exercice,
plus de cas), une réorganisation du code, etc.
<p>
Mais n'oubliez pas de PENSER AUX GENS QUI UTILISENT VOS EXERCICES ! Votre
module est peut-être déjà inséré dans des feuilles de travail actives ou/et
des examens importants. Vos nouveautés apportent alors des changements au
milieu du travail des gens. Les nouvelles capacités ou présentations
peuvent troubler les élèves ; au pire, un examen important peut être
cassé par un bogue. Il va sans dire que cela n'aidera pas à votre réputation.
<p>
En règle générale, vous devez vous abstenir d'introduire des modifications
esthétiques ou des renforcements au milieu d'une année académique sur les
modules activement utilisés. Seules les corrections de bogues doivent être
publiées pendant cette période. Développez vos nouveautés dans une version
de développement (sous une adresse test ou dans un compte de développement
pour cet effet) et ne les publiez que pendant les vacances scolaires.
<p>
Pour vos utilisations personnelles ou celles de vos élèves, il vous suffit
de pointer vos feuilles ou examens sur le module de votre espace de
développement. C'est d'ailleurs un bon moyen de faire tester les modules
avant la publication.
<p>
Dans tous les cas, sachez que pour les modules stables, vous pouvez
seulement modifier ceux sur lesquels vous avez des droits. Si vous voulez ajouter un
NOUVEAU module stable, votre compte doit en avoir le droit, ou vous devez
envoyer le module à un
"<a href=$(downloadsite)parrains>parrain</a>" et lui demander de le publier
pour vous (vous aurez ensuite le droit de modification sur ce module).
