!read adm/title.phtml 2\
Version d'un module

La version d'un module doit être de la forme <span class="tt">d.dd</span>
où les <span class="tt">d</span> sont des chiffres. Par exemple, <span class="tt">1.00</span>
ou <span class="tt">1.10</span>.
Réservez le changement du chiffre de droite pour les changements
mineurs, le chiffre du milieu aux changements plus importants et
le chiffre de gauche aux modifications importantes.
