
<h3><center>Version de WIMS d'un module</center></h3>

<p>WIMS est un système qui évolue rapidement. Des nouveautés sont introduites à
chaque nouvelle version.
</p><p>
Si un module est développé sous une version récente de WIMS, il ne pourra
pas tourner sur un serveur d'une version antérieure, car ce dernier n'aura
pas les capacités de le faire fonctionner correctement.
</p><p>
Pour cette raison, un serveur WIMS maintenant refuse d'exécuter un module qui
demande une wims_version trop récente.
</p><p>
Comme votre module $mod est développé sous WIMS-$wims_version, il est sans
danger de déclarer qu'il demande la version $wims_version de WIMS. A moins que
vous n'avez rien utilisé de nouveau depuis une version de WIMS plus ancienne,
dans ce cas-là vous pouvez utiliser cette version. Ceci dit,
si vous vous trompez,
les gens vont découvrir des "bogues" étranges dans votre module !
</p><p>
La version de WIMS doit être de la forme  <tt>d.dd</tt> ou <tt>d.dda</tt>
où les <tt>d</tt> sont des chiffres et <tt>a</tt> une lettre correspondant bien 
sûr à une version réelle de WIMS.
</p>
