
Se sei un docente e vuoi utilizzare WIMS regolarmente, potrebbe essere utile
installare il software su un server locale di istituto. In questo modo 
l'interazione sarà più veloce e si eviteranno interruzioni del servizio
dovute a problemi di rete.
<p>
WIMS è distribuito con licenza GNU. Può essere 
<a href="http://wims.unice.fr/download/wims/">scaricato</a>,
e installato su un sistema operativo Linux.
Maggiori dettagli sono disponibili nel file
<a href="http://wims.unice.fr/download/wims/README">README</a>
.
<p>
&Egrave; anche possibile contattare 
!mailurl xiao@unice.fr l'autore
 per domande su come installare un sito mirror, oppure 
!href module=adm/light&phtml=mirror.phtml.$lang cliccare qui
 per una lista di siti mirror di WIMS accessibili liberamente.
<p>
&Egrave; altamente sconsigliato l'utilizzo di un programma automatico
per scaricare le pagine di questo sito! Il sito WIMS va consultato 
in maniera interattiva ONLINE, le pagine scaricate da programmi automatici
sono inutilizzabili.

