!if $save!=$empty and $changed>0
 !href cmd=reply#check Pulse aquí
 para comprobar los efectos de la nueva configuración.
 <p>
 !exit
!endif

<p><hr> <p>
<a name=check>
Compruebe las aplicaciones de cálculo utilizadas por numerosos
módulos de WIMS (
!href cmd=reply&confcat=5#check puse aquí
 si quiere comprobar las aplicaciones gráficas).

<p>$table_header
$table_hdtr
<th>Nombre<th>orden<th><small>importancia</small><th>.<th>disponibilidad

!distribute items PARI/GP,Maxima,MuPAD,GAP,Octave,\
	Macaulay 2,Yacas\
	into n_pari,n_maxima,n_mupad,n_gap,n_octave,\
	n_m2,n_yacas
!distribute items 100,80,0,10,0,\
	5,20\
	into i_pari,i_maxima,i_mupad,i_gap,i_octave,\
	i_m2,i_yacas
!distribute items 2^17-1,2^17-1;,2^17-1;,2^17-1;,2^17-1,\
	2^17-1,2^17-1\
	into t_pari,t_maxima,t_mupad,t_gap,t_octave,\
	t_m2,t_yacas
!set res=131071

!for sw in pari,maxima,yacas,gap,m2,octave
 
 $table_tr<td align=center>$(n_$sw)<td align=center>$sw
 <td align=center>$(i_$sw)%
 <td align=center><small>
 !href cmd=help&help_subject=soft&help_conf=$sw ayuda
 !set av=!exec $sw about
 !set av=!trim $av
 !set r_=!exec $sw $(t_$sw)
 !set r_=!trim $r_
 !if $sw=m2
  !set r_=!word 3 of $r_
 !endif
 <td>
 !if $av!=$empty and $res=$r_
  Sí: $av
 !else
  No disponible.
 !endif
!next sw

$table_end <p>

!if $othermiss!=$empty
 WIMS no ha podido encontrar los siguientes programas que usan algunos de sus
 módulos. Estas aplicaciones o bien no están instaladas en el sistema
 (en cuyo caso por favor instálelas) o bien están instaladas en un directorio
 que no está incluido en el parámetro PATH (ruta) en
 !href cmd=reply&job=conf&confcat=12 temas técnicos
).
 <p>$table_header
 $table_hdtr<th>Name<th>Ejemplo de módulos que dependen de él
 !for other in $othermiss
  
  !set o=!replace internal units-filter by units in $other
  $table_tr<td><tt>$other</tt>
  <td>
  !if $(mod_$o)!=$empty
   !set mn=!module título $(mod_$o)
   !if $mn!=$empty
    !href module=$(mod_$o) $mn
   !endif
  !else
   Numerosos módulos
  !endif
  !if $other iswordof chemeq units-filter
   <small>Este software va normalmente incluido en la distribución de WIMS. Quizás
   haya fallado su compilación o usted la ha excluido deliberadamente.</small>
  !endif
  </td></tr>
 !next other
 $table_end <p>
!endif

