<center><h1>$tit</h1></center>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!if $erase!=$empty
 De file <b>$erase</b> is gewist
 <p>
!endif

!if $quota_free<1
 U kunt geen bestanden meer toevoegen aan dit document: de grens van de maximale filegrootte op deze server is bereikt.

!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=job2 value=deposit>
 U kunt een bestand invoeren in dit document:
 <input type=file size=35 name=wims_deposit>
 <input type=submit value=OK>
 </form>
!endif

!if $flist!=$empty
 <p>Beschikbare files in dit document:
 !for f in $flist
  !getfile doc/$f $f
  &nbsp;
 !next f
 <p>
 !form reply
 <input type=hidden name=job2 value=erase>
 Verwijder een bestand:
 !formselect job2 list $flist
 <input type=submit value=OK>
 </form>
 <p>
 De bestanden in dit document kunnen worden aangeroepen met de variabele <tt>\filedir</tt>
 Bijvoorbeeld, 
<p><center>
 <tt>&lt;a&nbsp;href="\filedir/$f1"&gt;$f1&lt;/a&gt;</tt>
</center> <p>
 geeft een link naar de file <a href="$m_filedir/$f1">$f1</a>.
 U kunt ook schrijven:
<p><center>
 <tt>&lt;img src="\filedir/myfile.jpg" alt="myfile"&gt;</tt>
</center> <p>
om het plaatje <tt>myfile.jpg</tt> aan deze pagina toe te voegen.
 <p>
 De gedeponeerde bestanden in dit document zijn alleen bereikbaar voor mensen
 met <em>lees_rechten</em>.
!endif

<p>
$n_freespace1 $quota_total Meg.
$n_freespace2 $quota_free Meg.

<p><center>
!href cmd=reply&job=prop $n_properties
&nbsp;&nbsp;
!href cmd=reply&job=list $n_blocklist
&nbsp;&nbsp;
!href cmd=reply&job=read&block=main $n_main
!if $(readhist[-1;2])!=main
&nbsp;&nbsp;
!href cmd=reply&job=read&block=$(readhist[-1;2]) $n_lastpage
 (<tt>$(readhist[-1;2])</tt>)
!endif
</center> <p>

