!if $error!=$empty
 !read msg.phtml
 <p>
 !exit
!endif

<center><h1>$tit</h1></center>

!if $titb=$empty
 <p>
 Het blok <tt>$block</tt> is nog niet aangemaakt.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Deze pagina is nog niet klaar. Kom later maar eens terug ! 
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Deze pagina is verlopen. Sorry!
 <p>
 !exit
!endif

:newblock
<a name=$block>
<h3>$titb</h3>

!!detrust
!read $wims_priv_thisdoc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $wims_priv_thisdoc/$block.def
 <p>
 !goto newblock
!endif

</div><div class=wimstail>
<p><hr>
<table width=100% border=0 cellspan=0 cellpadding=1>
<tr><td align=left nowrap><small>
By
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
<td align=right><small>
!href cmd=reply&job=read&doc=$doc&block=$startblock Interactieve versie
!if $wims_user=supervisor and $sheetdata!=$empty
 <tr><td align=left nowrap>
 <small>Last modified $datm
 <td align=right><small>
 !href cmd=reply&job=exosource&block=$startblock het startblok van dit document
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>Laatste verandering op $datm
!endif
</table>

