!if class = $doctype
 !defread wimshome/log/classes/$wims_class/.def
 !default author=$class_supervisor
 !default email=$class_email
!endif

!set wims_form_method=post
!form reply
<center><table border=0>
<tr><td align=right>$wims_name_title</td>
<td><input type=text size=40 name=titr value="$tit"></td></tr>
<tr><td align=right>$wims_name_Description</td>
<td><input type=text size=40 name=descr value="$desc"></td></tr>
<tr><td align=right>$wims_name_author</td>
<td><input type=text size=40 name=authorr value="$author"></td></tr>
<tr><td align=right>$wims_name_email</td>
<td><input type=text size=40 name=emailr value="$email"></td></tr>
<tr><td align=right>$n_header<br>
<small>(css, js, etc.)</small>
!set header=!translate internal $	$ to $\
$ in $header
!set hl=!linecnt $header
!set hr=$[max(3,min($hl+2,10))]
!set header=!reinput $header
<td><textarea cols=40 rows=$hr name=headerr>$header</textarea>
!reset headerr
!set docopenr=$docopen
!default docopenr=0
!if class != $doctype
 <tr><td align=right>$wims_name_Copyright:</td><td>
 !set copyrightr=$copyright
 !default copyrightr=gnu
 !formselect copyrightr list gnu,opl,private prompt\
	GNU Free Documentation License,\
	Open Publication License,\
	$n_copyright2
 </td></tr><tr><td align=right>Ouvert au public :</td><td>
 !formselect docopenr list yes,no prompt $wims_name_yes, $wims_name_no
 </td></tr><tr><td align=right>$wims_name_Language:</td><td>
 !default dlang=all
 <input size=14 name=dlangr value="$dlang"> <br><small>
 bijvoorbeeld: all en fr es it de cn ca nl</small>
 !if $job=creat
  <tr><td align=right>$n_codedoc:</td><td nowrap>
  <input type=password size=$codemax maxlength=$codemax name=coder> nog een keer:
  <input type=password size=$codemax maxlength=$codemax name=coder2>
  </td></tr><tr><td colspan=2><small>
  De geheime code geeft U het recht om een document te veranderen.
  Deze code moet tussen de $codemin en $codemax karakters bevatten.
  </small>
 !endif
!else
 !set U_Docstatus=!defof U_Docstatus in wimshome/public_html/modules/home/names.$lang
 <tr><td align=right> Deelnemers mogen dit document <td>
 !formselect docopenr list 0,1,2 prompt \
	$U_Docstatus

!endif

</table>
<p>
 <input type=submit name=rEg value="$wims_name_tosave">&nbsp;
 <input type=submit name=abandon value="$wims_name_giveup">
</center>
</form>

<p>
!if class != $doctype
 <b>Opmerking</b>. U moet wel toestemming vragen aan de 
 !mailurl $wims_site_manager systeembeheerder/site-manager\
 om dit WIMS 
 document $doc publiek te maken.
 <p>
!else
Dit document is alleen beschikbaar voor deze virtuele klas.
!endif

