
!read adm/title.phtml 1\
\
Formatos para las hojas de cálculo

csv (siglas de `valores separados por comas' en inglés) y tsv (`valores separados
por tabuladores') son formatos de texto para los datos de las hojas de cálculo. 
La mayoría de las hojas de cálculo reconocen los dos formatos.
<p>
ods is the spreadsheet format defined by the OpenDocument ISO standard. It is supported by LibreOffice and OpenOffice, and it should be supported by any fair spreadsheet program.
</p>

