!set lan=en
<HTML><HEAD>$wims_html_header
</HEAD>
!if $wims_window=new
 !set w_resize=onload="self.resizeTo(550,550);self.moveTo(30,50);"
!endif
<BODY $wims_htmlbody $w_resize>
!robottrap

<DIV CLASS=wimsmenu>
<CENTER><TABLE border=0 cellspacing=0 cellpadding=5 bgcolor=$wims_ref_bgcolor
>
<tr><td align=center>
!if _ isin $wims_subsession
 <a href=# onclick="window.close()">Close help window</a>
!else
 !href session=$wims_session.1 WIMS home
!endif
!if $style=print
 &nbsp;
 !href module=$module&chapter=0 Interactive version
 !set chapter=-1
 !goto tabend
!endif
!if $chapter>0
 <td align=center>
 !href module=$module&chapter=0 Help index
&nbsp;
!endif
<td align=center>
!href module=$module&style=print Printable version
&nbsp;
!if $chapter>1
 <td align=center>
 !href module=$module&chapter=$[$chapter-1] Preceding chapter
!endif
!if $chapter<$chaptercnt
 <td align=center>
 !href module=$module&chapter=$[$chapter+1] Next chapter
!endif

:tabend
</TABLE></CENTER></DIV><DIV CLASS=wimsbody>

!if $chapter>0
 !set l=!line 1 of $(chapter$chapter)
 !set ll=!word $chapter of I II III IV V VI VII IIIV IX X
 !set l=Chapter $ll. $l
!else
 !if $chapter<0
  !set l=Printable version
 !else
  !set l=General index
 !endif
!endif

<P><CENTER><H1>WIMS help<br><font size=+1><b>
---- $l ----</b></font>
</H1></CENTER> <P>

