!set lan=en
!read tabletheme
!header1

<div id="wimsmhelp">

<div class=wimsmenu>
!robottrap
<center>
$table_header
 $table_tr<th>
!if _ isin $wims_subsession
 <a href="#" onclick="window.close()">Close help window</a>
!else
 !href session=$wims_session.1 WIMS home
!endif
!if $style=print
 &nbsp;
 !href module=$module&chapter=0 Interactive version
 !set chapter=-1
 !goto tabend
!endif
!if $chapter>0
 <th>
 !href module=$module&chapter=0 Help index
</th>
!endif
<th>
!href module=$module&style=print Printable version
</th>
!if $chapter>1
 <th>
 !href module=$module&chapter=$[$chapter-1] Preceding chapter
!endif
!if $chapter<$chaptercnt
 <th>
 !href module=$module&chapter=$[$chapter+1] Next chapter
!endif

:tabend
</table></center>
</div><!--wimsmenu-->
<div id="wimsbodybox">
<div id="wimspagebox">
<div class=wimsbody>

!if $chapter>0
 !set l=!line 1 of $(chapter$chapter)
 !set ll=!word $chapter of I II III IV V VI VII IIIV IX X
 !set l=Chapter $ll. $l
!else
 !if $chapter<0
  !set l=Printable version
 !else
  !set l=General index
 !endif
!endif

<p><h1 class="wims_title">WIMS help<br><font size="+1"><b>
$l</b></font>
</h1> <p>

