!if robot isin $session
 <html><body $wims_htmlbody>
 Ta stran ni dostopna robotom.
 </body></html>
 !exit
!endif

!set wims_html_onload=!append word window.focus(); to $wims_html_onload
!header1

<h1 class="wims_title">
<font color=red>W</font>WW
<font color=red>I</font>nteraktivni
<font color=red>M</font>nogonamenski
<font color=red>S</font>tre¾nik<br>
<font size="-1">na <a href="/">$httpd_HTTP_HOST</a></font>
</h1>

!read $job.phtml

!if $job!=home
 <p>
 !href module=$module&cmd=new&job=home Druge metode brskanja
.
!endif

!tail

