
<center><h3>Exemples d'exercices interactifs sous le format OEF</h3></center> <p>

Voici quelques exemples d'exercices interactifs qu'on peut créer par Createxo.
<ol>
<p><hr width=50%> <p>
<li> <b>Longueur de vecteur 2D</b>, un simple calcul de longueur
d'un vecteur dans le plan. Voici la source complète de cet exercice.

<p><pre>
\title{Norme de vecteur 2D}
\language{fr}
\computeanswer{no}
\format{html}

\integer{x=random(-10..10)}
\integer{y=random(-10..10)}
\real{norm=sqrt((\x)^2+(\y)^2)}
\statement{Quelle est la longueur du vecteur (\x,\y) dans R<sup>2</sup>?}

\hint{La longueur d'un vecteur (x,y) est égale à 
sqrt(x^2+y^2).}
\answer{La longueur}{\norm}
</pre> <p>

Dans cet exercice, on a défini 2 entiers aléatoires, x et y, qui sont les
coordonnées du vecteur. Ensuite un troisième paramètre, cette fois réel, est
défini par la formule de longueur. L'exercice prend une réponse libre sous le 
nom de ``La longueur'', et la bonne réponse doit être la valeur du troisième
paramètre ``norm''. Une indication est préparée dans l'exercice, qui rappelle
la formule de longueur. <p>
Vous pouvez
!set parm=oef_answercnt=1&oef_choicecnt=0&oef_title=Norme de vecteur 2D&oef_format=html&oef_computeanswer=no&level=2&oef_parms=%5Cinteger%7Bx%3Drandom(-10..10)%7D%0D%0A%5Cinteger%7By%3Drandom(-10..10)%7D%0D%0A%5Creal%7Bnorm%3Dsqrt%28%28%5Cx%29%5E2%2B%28%5Cy%29%5E2%29%7D&oef_statement=Quelle est la longueur du vecteur %28%5Cx%2C%5Cy%29 dans R%3Csup%3E2%3C%2Fsup%3E%3F&ansprompt1=La longueur&ansgood1=%5Cnorm&oef_hint=La longueur d%27un vecteur %28x%2Cy%29 est %E9gale %E0 %0D%0Asqrt%28x%5E2%2By%5E2%29.&oef_solution= $
!href cmd=reply&mode=guided&$parm charger cet exemple dans le menu
 pour le tester. (Vous pouvez aussi copier la source dans le menu en mode brut.)

<p><hr width=50%> <p>
<li> <b>Trace de matrice 2x2</b>, calcul de trace d'une matrice. La question 
 est formatée par TeX, pour une meilleure présentation de la matrice. Voici
 la source complète de l'exercice.
<p><pre>
\title{Trace de matrice 2x2}
\language{fr}
\computeanswer{yes}
\format{tex}

\integer{range=20}
\integer{a=random(-\range..\range)}
\integer{b=random(-\range..\range)}
\integer{c=random(-\range..\range)}
\integer{d=random(-\range..\range)}
\integer{trace=(\a)+(\d)}
\statement{Calculer la trace de la matrice
$$\pmatrix{\a&\b\cr \c&\d}$$.}

\answer{La trace}{\trace}
</pre> <p>
On a défini d'abord un entier ``range'', pour l'utiliser à encadrer les
valeurs aléatoires a,b,c,d qui sont les éléments de la matrice. Et la trace
est bien entendue définie par la somme des éléments sur la diagonale. Faites
attention à la définition <tt>trace=(\a)+(\d)</tt>: les paires de parenthèses
sont nécessaires, car la substitution est littérale. Si on définit <tt>trace=\a+\d</tt>
et si a et d prennent les valeurs de 3 et -15 respectivement, on aurait
<tt>trace=3+-15</tt>, une mauvaise expression mathématique. <p>
Remarquons que dans cet exercice, les réponses non calculées sont admises 
(telles 2+15 ou 3*105). <p>
Vous pouvez
!set parm=oef_answercnt=1&oef_choicecnt=0&oef_title=Trace de matrice 2x2&oef_format=tex&oef_computeanswer=yes&level=2&oef_parms=%5Cinteger%7Brange%3D20%7D%0D%0A%5Cinteger%7Ba%3Drandom(-%5Crange..%5Crange)%7D%0D%0A%5Cinteger%7Bb%3Drandom(-%5Crange..%5Crange)%7D%0D%0A%5Cinteger%7Bc%3Drandom(-%5Crange..%5Crange)%7D%0D%0A%5Cinteger%7Bd%3Drandom(-%5Crange..%5Crange)%7D%0D%0A%5Cinteger%7Btrace%3D%28%5Ca%29%2B%28%5Cd%29%7D&oef_statement=Calculer la trace de la matrice%0D%0A%24%5Cpmatrix%7B%5Ca%26%5Cb%5Ccr %5Cc%26%5Cd%7D%24.&ansprompt1=La trace&ansgood1=%5Ctrace&oef_hint= &oef_solution= $
!href cmd=reply&mode=guided&$parm charger cet exemple dans le menu
 pour le tester. (Vous pouvez aussi copier la source dans le menu en mode brut.)


</ol>

