
<center><h3>Le format OEF</h3></center> <p>

OEF veut dire ``online exercise format'', un format pour des exercices
mathématiques déstinés aux systèmes d'enseignement assisté par ordinateur.
Le but de la création de ce format est de favoriser les échanges de contenu
entre différents systèmes. Ce format contient donc uniquement des
informations mathématiques de l'exercice.
<p>
L'avantage du format OEF est que les exercices sous ce format sont très
faciles à créer. Mais 
il faut savoir que ces exercices, en particulier
ceux créés par $module_title, ne sont pas aussi performants que des
exercices propres à un système comme WIMS. Il est difficile d'imaginer,
du moins pour l'instant, que les
exercices WIMS tels que Q-Puzzle, la série Coincidence, ou encore 
la série Tir, puissent être transformés en format oef.
<p>
Veuillez consulter aussi
!href cmd=help&special_parm=examples les exemples
 pour avoir une idée de la structure d'un fichier OEF. <p>
<h4>Syntaxe de base</h4> <p>
Le format d'un fichier OEF est très similaire à LaTeX. Il est composé d'instructions suivies d'un ou plusieurs paramètres. Une instruction est un mot
précédé du caractère <tt><b><font color=green>\</font></b></tt>, et
les paramètres sont fermés dans des accolades.
Par exemple, dans la phrase suivante
<pre>
   \choice{La réponse}{oui}{non}
</pre>
il y a une instruction ayant le nom <tt>choice</tt>, 
qui a 3 paramètres&nbsp;:<tt>La réponse</tt>, <tt>oui</tt>
et <tt>non</tt>.
<p><h4>Liste d'instructions</h4> <p>
Voici une liste brève d'instructions reconnues par le gestionnaire OEF de
WIMS. Voir aussi
!href cmd=help&special_parm=parameters aide sur paramètres
 pour la syntaxe de définition de paramètres.
<p>$table_header
$table_hdtr<th>instruction</th><th>nombre de<br>paramètres</th><th>description</th></tr>
$table_tr<td>title</td><td align=center>1</td><td>définit le titre de l'exercice</td></tr>
$table_tr<td>language</td><td align=center>1</td><td>la langue de l'exercice, comme
<tt>en</tt> ou <tt>fr</tt></td></tr>
$table_tr<td>author</td><td align=center>1</td><td>définit l'auteur de l'exercice</td></tr>
$table_tr<td>email</td><td align=center>1</td><td>définit l'adresse électronique de l'auteur</td></tr>
$table_tr<td>format</td><td align=center>1</td><td>format de l'énoncé&nbsp;: voir
!href cmd=help&special_parm=format aide sur formats
.</td></tr>
$table_tr<td>precision</td><td align=center>1</td><td>précision en comparant la réponse de
l'utilisateur avec la solution. Donnez un nombre positif n ici&nbsp;: la 
comparaison sera effectuée avec une tolérance de 1/n.</td></tr>
$table_tr<td>range</td><td align=center>1</td><td>zone de variables pour l'évaluation de 
fonction fournie par l'utilisateur. Doit être donnée sous forme
<tt>n1..n2</tt>, où n1 est le point de départ, n2 le point d'arrivée.
</td></tr>
$table_tr<td>statement</td><td align=center>1</td><td>le paramètre est l'énoncé de
l'exercice
</td></tr>
!!$table_tr<td>plot</td><td align=center>?</td><td>une tracée dynamique. (Encore en construction.)</td></tr>
$table_tr<td>answer</td><td align=center>2-5</td><td>définit une réponse libre. Le premier
paramètre est le message pour la réponse, et le second est la bonne réponse.
La réponse sera analysée selon des types (nombre, fonction, texte, etc).
!href cmd=help&special_parm=reply Détail
.
<p>
Paramètres optionnels : <tt>type</tt>, <tt>option</tt>, <tt>weight</tt>.
<p>
Mots d'option reconnus : <tt>reorder</tt>, <tt>shuffle</tt>, <tt>nonstop</tt> .</td></tr>
$table_tr<td>choice</td><td align=center>3-5</td><td>définit un choix multiple. Le premier
paramètre est le message pour le choix, le second les bons choix, et le
troisième les mauvais choix. Les deux derniers paramètres peuveut (doivent)
être une liste d'objets séparés par des virgules. Il est permis d'avoir
plusieurs bons choix. Si un choix apparait à la fois comme bon et mauvais,
il est pris pour bon.
<p>
Paramètres optionnels : <tt>option</tt>, <tt>weight</tt>.
<p>
Mots d'option reconnus : <tt>noidontknow</tt>, <tt>shuffle</tt>.</td></tr>
$table_tr<td>condition</td><td align=center>2-4</td><td>définit une condition spéciale pour 
l'évaluation de réponses libres. Voir
!href cmd=help&special_parm=reply aide sur les réponses
 pour les détails.
<p>
Paramètres optionnels : <tt>option</tt>, <tt>weight</tt>.
$table_tr<td>solution</td><td align=center>1</td><td>donne une solution expliquée de
l'exercice. Le gestionnaire OEF peut décider de montrer la solution ou pas à
l'utilisateur, suivant le choix du niveau de difficulté pris par
l'utilisateur.</td></tr>
$table_tr<td>hint</td><td align=center>1</td><td>donne une indication de l'exercice.
Le gestionnaire OEF peut décider de montrer l'indication ou non, suivant le
niveau de difficulté.</td></tr>
$table_tr<td>help</td><td align=center>1</td><td>donne une aide à l'exercice.
Cette aide sera toujours accessible à l'utilisateur, dans une fenêtre `popup'.</td></tr>
$table_tr<td>feedback</td><td align=center>2</td><td>afficher un commentaire
quand la réponse tombe sous une certaine condition. Peut
normalement être utilisé pour avertir d'une erreur typique.
!href cmd=help&special_parm=feedback Détail
.
$table_end


