!header

!read comsDir/exosDescription
<div class="intro_confia2qcm">
       Ce module ("<code><b>conf</b>ection <b>i</b>nter <b>a</b>ctive <b>de</b>
       <b>qcm</b></code>") est juste un outil pour vous aider à confectionner le
       fichier source d'un exercice simple de type QCM, au format OEF sous WIMS.
       Pour une documentation sur l'architecture d'un exercice OEF, suivre
       par exemple
       !href target=wims_internal module=help/teacher/docexooef ce lien.
</div>
<hr />
<div class="intro2_confia2qcm">
	<p>
		Si vous êtes novice, je vous conseille de sélectionner la
		<span class="demo_confia2qcm">démo</span> afin de vous faire une idée sur un exemple.
		Vous pourrez alors modifier les données de la <b>démo</b> pour produire au final
		votre QCM.
	</p>
</div>
<hr />
!form new
<input type="hidden" name="module" value="$module" />
<table class="table1_confia2qcm">
  <tr>
    <td class="center white">
      <input type="radio" name="chexo" value="1" checked="checked" />
    </td>
    <td>
      <p>
      Aller directement à la confection de votre exercice ou suivre pas
      à pas la <span class="demo_confia2qcm">démo</span>,
      <select name="exo">
        <option value="demo"
	  selected="selected"
>$(exosdesc[1;])
	</option><option value="1">$(exosdesc[2;])
      </option></select>
       </p>
    </td>
    <td class="center" rowspan="3">
      <input type="submit" value="Au travail" />
    </td>
  </tr>
  <tr>
    <td class="center white">
      <input type="radio" name="chexo" value="2" />
    </td>
    <td class="white">
      <p>
        ou modifier en <b>mode brut</b> un code source (au format <span class="tt">confia2qcm</span>)
       </p>
    </td>
  </tr>
  <tr>
    <td class="center white">
      <input type="radio" name="chexo" value="3" />
    </td>
    <td class="white">
      <p>
        ou encore <b>soumettre un fichier</b> (au format <span class="tt">confia2qcm</span>) existant
       </p>
    </td>
  </tr>
</table>

!formend

!tail

