!nocache
!! useful when one comes from modtool
!set wims_backslash_insmath=yes
!set proc=oef
!if robot isin $session
 !changeto content.html
!endif

!set test_data=!replace internal data/ by in $module_data
!set test_data=!defof title in datamodule/$test_data/INDEX
!if $test_data= and $module_data!=
   <p class="name_datamodule"><i>
   $name_datamodule
   </i></p>
!endif
<hr style="width:35%" />


!! ------------------------------------- saisie des paramètres
!if $step=1
 $name_insert <span class="tt wims_fname">$smodule</span>

 <p>
 $name_choose_allexo
 </p>
 !form reply
<fieldset class="property_fields halfwidth blockcenter">
 <legend>$name_title</legend>
 <div class="field box">
  <label for="picksheet">$name_choose</label>
  <select name="picksheet" id="picksheet">
 !for i=1 to $sheetcnt
  !set sh=!line $i of $sheets
  !set se=!item 1 of $sh
  !set ti=!item 2 to -1 of $sh
  !if $se=$sheetcnt
   <option value="$se" selected="selected">$wims_name_Sheet $se: $ti</option>
  !else
   <option value="$se">$wims_name_Sheet $se: $ti</option>
  !endif
 !next i
  </select>
  </div>
 !if $scoring=yes
  <div class="field box">
   <label for="require">$name_required</label>
    <select name="require" id="require">
    <option value="0">0</option>
    <option value="10" selected>10</option>
   !for i=2 to $require_limit
     <option value="$[10*$i]">$[10*$i]</option>
   !next
    </select>
   <div class="formHelp">$name_repeat</div>
  </div>
  <div class="field box">
   <label for="weight">$name_weight</label>
   <input size="6" name="weight" value="$weight" id="weight" />
   <div class="formHelp">$name_weight_hint</div>
  </div>
 !endif
</fieldset>

!!debut du menu voir intromenu.phtml
<div id="oef_intro_params">
<h2 class="legend oef_name_menu">$name_menu</h2>
<fieldset class="oef_expert">
<legend>$name_general_setup</legend>
<div class="field">
 <label for="qnum">$name_oneserie
 !default qnum=1
 !formselect qnum from 1 to 9
 $name_exercises.</label>
</div>
<div class="field">
 <label for="scoredelay">$name_chrono:</label>
 <input size="7" id="scoredelay" name="scoredelay" value="$scoredelay" /> $name_secondes.
</div>
!set translation_language=!getdef translation_language in INDEX
!if $translation_language!=$empty
  !set translation_language=$module_language,$translation_language
  !set translation_language=!words2items $translation_language
  !set translation_language=!sort items $translation_language
  <div class="field">
   <label for="lang_choice">$wims_name_Language:</label>
   !formradio lang_choice list $translation_language
  </div>
!endif
</fieldset>
<fieldset class="oef_expert">
<legend>$name_simplifiedmenu</legend>
<div class="field">
 <label for="qcmlevel">$name_levelseverity:</label>
 !default qcmlevel=3
 !formselect qcmlevel from 1 to 9
</div>
</fieldset>
!default intro_check=1,2,3,4
<fieldset class="oef_expert">
  <legend>$name_expertmenu</legend>
    <div class="field">
     <label for="intro_presentsol">$name_solutiongiven? </label>
     !default intro_presentsol=1
     !formselect intro_presentsol list 0,1,2 prompt $name_choice
    </div>
    <div class="field">
     <label>
      !formcheckbox  intro_check list 3 prompt $(name_choice_check[3])
     </label>
    </div>
    <div class="field">
     <label>
      !formcheckbox intro_check list 4 prompt $(name_choice_check[4])
     </label>
    </div>
    <div class="field">
     <label>
      !formcheckbox random list 0 prompt $name_aleaseries
     </label>
    </div>
<hr />
$name_qcm
    <div class="field">
     <label for="intro_qcmpresent">$name_qcmanswer: </label>
     !default intro_qcmpresent=4
     !formselect intro_qcmpresent list 2,3,4,5,6,7,8
    </div>
    <div class="field">
     <label>
      !formcheckbox intro_check list 1 prompt $(name_choice_check[1])
     </label>
    </div>
    <div class="field">
     <label>
      !formcheckbox intro_check list 2 prompt $(name_choice_check[2])
     </label>
    </div>
    !let tmp=!replace word expert by $ in $special_parm2
    !set tmp3=!replace internal intro_expert=yes by in $special_parm3
    <input type="hidden" name="intro_expert" value="yes" />

   </fieldset>
</div>
 <div class="wimscenter wimsform">
   <input type="submit" value="$wims_name_Insert" />
   <input type="hidden" name="step" value="2" />
   <input type="hidden" name="job" value="$job" />
 </div>
!formend

<div class="wims_smallremark">
$name_remarkintro3
</div>
!endif

!! ---------------------------------------- écriture du bilan
!if $step=2
 !if $addexo>0
	<p>$name_endallexo.</p>
 !endif
 !if $notadd>0
  	<p>$name_endallexo2
        <ul>
	!for exo in $listalready
		!let num=!positionof item $exo in $exolist
		<li>$(exotitle[$num])</li>
	!next exo
	</ul></p>
 !endif
 !set wims_menu_items=!append line sheetcheck,1, module=adm/class/sheet&sheet=$picksheet\
to $wims_menu_items
!endif

