
!read adm/css.phtml
!read adm/lang/class_title.phtml.$moduclass_lang $wims_classname\
$wims_institutionname

!header1

!read adm/title.phtml 1\
$classname\
$name_title

!if $error!=$empty
 <p>
 !read lang/msg.phtml.$moduclass_lang
 <p>
 !goto end1
!endif

!if $cmd=new or $cmd=resume
 $name_insert <tt class="wims_fname">$dir</tt>
 !if $iniparm!=$empty
  $name_parm 
 <p>
 <tt class="wims_parm">
  !replace internal & by &amp; in $iniparm
  </tt>
 </p> 
 !endif
<p>
 
 !form reply
 $name_choose:
 <select name="picksheet">
 !for i=1 to $sheetcnt
  !set sh=!line $i of $sheets
  !set se=!item 1 of $sh
  !set ti=!item 2 to -1 of $sh
  !if $se=$sheetcnt
   <option value="$se" selected>$wims_name_Sheet $se: $ti</option>
  !else
   <option value="$se">$wims_name_Sheet $se: $ti</option>
  !endif
 !next i
 </select>
 <p>$name_modifytitle
 <p>
 !set iniparm1=!replace internal & by $ $ in $iniparm
 !set exo=!getopt exo in $iniparm1
 !set title1=!lookup $exo in wimshome/public_html/modules/$dir/Extitles
 !if $title1!=$empty
   !set title=$title1
 !endif
 !set title=!trim $title
 !default title=$wims_name_Exercise
 $wims_name_title: <input size="50" name="title" value="$title"> <p>
 $wims_name_Description: <textarea name="new_desc" rows="5" cols="50">$desc</textarea>
 !if $scoring=yes
  <p>$name_required:
  <input size="4" name="require" value="$require">
  <small>
  ($name_repeat)
  </small><p>
 $name_weight:
  <input size="6" name="weight" value="$weight">.
 !endif
 <p><center><input type="submit" value="$wims_name_Insert"></center>
 </form>
 !goto end
!endif

!if $cmd=reply
 $name_end
 $picksheet.

!endif
:end1
!set wims_menu_items=!append line sheetcheck,1, module=adm/class/sheet&sheet=$picksheet\
to $wims_menu_items

:end
!set wims_menu_items=!append line moduback,1,module=$dir\
to $wims_menu_items

!tail

!set job=

