
!read desc.phtml
<p>
!if $tot<=0
 !if $mlist!=.newlist
  Tukaj ni nobenega ustreznega sporoèila. 
 !else
  Na tem forumu ni nobenega sporoèila.
 !endif
!else
 !if $mlist=.newlist
  Seznam zadnjih sporoèil, najprej
 !else
  Seznam sporoèil za obdobje
  !item $lmon of $monthnames
  $lyear, najprej
 !endif
 !item $l_order of novej¹a, starej¹a
. <small>
 !href cmd=reply&l_order=$[$l_order%2+1] [Zamenjaj vrstni red]
 !if $send_right>0
  &nbsp;
  !href cmd=new&forum=$forum&job=compose [Novo sporoèilo]
 !endif
</small>
 <ul>
 !set lh=<li>
 !if $l_order=1
  !distribute item $tot,1,-1 into start,end,step
 !else
  !distribute item 1,$tot,1 into start,end,step
 !endif
 !for i=$start to $end step $step
  !if $mlist=.newlist
   !set l_=!line $i of $mnew
   !distribute word $l_ into a_,b_
   !set l_=!record $b_ of $forumdir/$a_/.msglist
  !else
   !set l_=!record $i of $forumdir/$mlist/.msglist
  !endif
  !read listone.phtml $l_
 !next i
 </ul>
!endif

<p>
!if $mlist!=.newlist
 !href cmd=reply&job=list&mlist=.newlist Zadnja sporoèila.
 &nbsp;
!endif

!read listarch.phtml

