 <small>
 !if $dcnt>1
  [
  !if $dlast!=$empty
   !href cmd=reply&job=read&r_msg=$dlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=list $n_bydate
  !if $dnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$dnext &gt;&gt;
  !endif
  ]
 !endif
 [
 !href cmd=reply&job=threadlist $n_bysubject
 ]
 !!if $r_prec!=$empty
 !! &nbsp;
 !! !set t_=!translate / to , in $r_prec
 !! !href cmd=reply&job=read&r_msg=$r_prec $n_prec
 !!!endif
 !!if $repcnt>0
 !! &nbsp;
  !!!href cmd=reply&job=read&r_msg=$r_rep1 $n_first
 !! &nbsp;
 !!!href cmd=reply&job=thread&th_orig=$l_thread&th_start=$r_msg $n_allfollowing
 !!!endif

!if $thtcnt>1 or $r_prec!=$empty or $repcnt>0
  &nbsp;&nbsp;[
  !if $tlast!=$empty
   !href cmd=reply&job=read&r_msg=$tlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=thread&th_orig=$l_thread&th_start=$l_thread $n_thread
  !if $tnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$tnext &gt;&gt;
  !endif
  ]
 !endif
 </small>

