 <small>
 !if $dcnt>1
  [
  !if $dlast!=$empty
   !href cmd=reply&job=read&r_msg=$dlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=list Po datumu
  !if $dnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$dnext &gt;&gt;
  !endif
  ]
 !endif
 !if $r_prec!=$empty
  &nbsp;
  !set t_=!translate / to , in $r_prec
  !href cmd=reply&job=read&r_msg=$r_prec Prej¹nje sporoèilo v nizu
 !endif
 !if $repcnt>0
  &nbsp;
  !href cmd=reply&job=read&r_msg=$r_rep1 Naslednje sporoèilo v nizu
  &nbsp;
  !href cmd=reply&job=thread&th_orig=$l_thread&th_start=$r_msg Vsa naslednja sporoèila
 !endif
 !if $thtcnt>1
  &nbsp;&nbsp;[
  !if $tlast!=$empty
   !href cmd=reply&job=read&r_msg=$tlast &lt;&lt;
   &nbsp;
  !endif
  !href cmd=reply&job=thread&th_orig=$l_thread&th_start=$l_thread Nanizaj
  !if $tnext!=$empty
   &nbsp;
   !href cmd=reply&job=read&r_msg=$tnext &gt;&gt;
  !endif
  ]
 !endif
 </small>
 
