

<center><table border=1 bgcolor=$wims_ref_bgcolor>
<caption>Document <b>$doc</b></caption>
<tr><th>Titre<td>$tit
<tr><th>Auteur<td>$author
!if @ isin $email
 <tr><th>email<td>
 !mailurl $email
!endif
!if class != $doctype
 <tr><th>Droit d'auteur<td>
 !if $copyright iswordof gnu opl
  !if $copyright=gnu
   <a href=fdl.txt>GNU Free Documentation License</a>
  !endif
  !if $copyright=opl
   <a href=opl.html>Open Publication License</a>
  !endif
 !else
  Tout droit réservé par l'auteur
 !endif
!endif
$table_end</div>

