!!##language independant

<center><table border=1 bgcolor="$wims_ref_bgcolor">
<caption>$wims_name_doc <b>$doc</b></caption>
<tr><th>$wims_name_title<td>$tit
<tr><th>$wims_name_Author<td>$author
!if @ isin $email
 <tr><th>email<td>
 !mailurl $email
!endif
!if class != $doctype
 <tr><th>$wims_name_Copyright<td>
 !if $copyright iswordof gnu opl
  !if $copyright=gnu
   <a href=fdl.txt>GNU Free Documentation License</a>
  !endif
  !if $copyright=opl
   <a href=opl.html>Open Publication License</a>
  !endif
 !else
  $n_copyright2
 !endif
!endif
$table_end</div>

