!if class != $doctype and $wims_ismanager<2 and $doc iswordof $openlist
 <p>
 Pour des raisons de sécurité, seul le gestionnaire du site peut effacer les
 documents publics.
 <p>
 Veuillez
 !mailurl $wims_site_manager demander le gestionnaire du site
 d'effacer votre document pour vous.
 !exit
!endif

<p>
<blink><b>ATTENTION</b>!!</blink> Un document effacé ne peut pas être
récupéré&nbsp;!
<p>
Etes-vous sûr de vouloir effacer le document <font color=red><b>$tit</b></font>&nbsp;?
<p><center>
!href cmd=reply&rEg=yes Oui
 &nbsp; &nbsp;
!href cmd=new&job=home Non
</center> <p>

