!if class = $doctype
 !defread wimshome/log/classes/$wims_class/.def
 !default author=$class_supervisor
 !default email=$class_email
!endif

!set wims_form_method=post
!form reply
<center><table border=0>
<tr><td align=right>$n_title</td>
<td><input type=text size=40 name=titr value="$tit"></td></tr>
<tr><td align=right>$wims_name_Description</td>
<td><input type=text size=40 name=descr value="$desc"></td></tr>
<tr><td align=right>$n_author</td>
<td><input type=text size=40 name=authorr value="$author"></td></tr>
<tr><td align=right>$n_email</td>
<td><input type=text size=40 name=emailr value="$email"></td></tr>
<tr><td align=right>$n_header<br>
<small>(css, js, etc.)</small>
!set header=!translate internal $	$ to $\
$ in $header
!set hl=!linecnt $header
!set hr=$[max(3,min($hl+2,10))]
!set header=!reinput $header
<td><textarea cols=40 rows=$hr name=headerr>$header</textarea>
!reset headerr
!set docopenr=$docopen
!default docopenr=0
!if class != $doctype
 <tr><td align=right>$n_copyright:</td><td>
 !set copyrightr=$copyright
 !default copyrightr=gnu
 !formselect copyrightr list gnu,opl,private prompt\
	GNU Free Documentation License,\
	Open Publication License,\
	$n_copyright2
 </td></tr><tr><td align=right>Ouvert au public :</td><td>
 !formselect docopenr list yes,no prompt $n_yes, $n_no
 </td></tr><tr><td align=right>Langue(s):</td><td>
 !default dlang=all
 <input size=14 name=dlangr value="$dlang"> <br><small>
 Exemples: all en fr es it de cn</small>
 !if $job=creat
  <tr><td align=right>$n_codedoc:</td><td nowrap>
  <input type=password size=$codemax maxlength=$codemax name=coder> et répétez :
  <input type=password size=$codemax maxlength=$codemax name=coder2>
  </td></tr><tr><td colspan=2><small>
  Le code secret donne droit à la
  modification du document. Il doit être composé de $codemin à $codemax lettres
  alpha-numériques.</small>
 !endif
!else
 <tr><td align=right> Les participants peuvent<td>
 !formselect docopenr list 0,1,2 prompt \
	ni lire ni écrire,\
	lire mais pas écrire,\
	lire et écrire
 ce document.
!endif

</table>
<p>
 <input type=submit name=rEg value="Enregistrer">&nbsp;
 <input type=submit name=abandon value="Abandonner">
</center>
</form>

<p>
!if class != $doctype
 <b>Remarque</b>. Vous devez demander l'approbation du
 !mailurl $wims_site_manager gestionnaire du site\
Ask to open WIMS document $doc
 pour rendre le document accessible au public.
 <p>
!else
 Ce document est uniquement visible à l'intérieur de votre classe virtuelle.
!endif

