!!<html><head>
!!$wims_html_header
!!</head>
!!<body $wims_htmlbody>
!!!headmenu
!header1

!if $cmd=help and $special_parm=about
 !read about.phtml
 !goto end
!endif

!if $cmd=help
 !read help.phtml
 !goto end
!endif

<h1 class="wims_title">WIMS 位于 $httpd_HTTP_HOST
<br>使用统计</h1>
<p><hr> <p>

!if $sitestart=$empty
本站的使用统计未被激活. 无统计数据可用. 抱歉. <p>
 !goto end
!endif

!if $show=yes and $total_site>0 and $laps>0
!!if $show=yes
 !href cmd=resume 返回菜单
 <p>
 !read answer.phtml
 !href cmd=resume 返回菜单
 <p>
!else
 !if $usercnt>0
  本服务器有 $classcnt 个入口和不同班级, 总共 $usercnt 个用户帐户.
  <p>
 !endif
 !read menu.phtml
!endif
:end
!homeref
!tail

!set stat_module=
