!reset confirm
!!<html><head>
!!$wims_html_header
!!</head><body $wims_htmlbody onload=$wims_html_onload>
!!headmenu

!read adm/css.phtml
!header1

!read names.phtml

!if $job iswordof student
 !changeto $job.phtml
!endif

!if $cmd=help
 !read help/$special_parm.phtml
 !goto end
!endif

<center>$classname
<p>
<h1>
!if $activetest=0
 Préparation 
!else
 Gestion
!endif
de la  feuille $sheet</h1></center> 

<p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !href module=home Retourner à la page d'accueil
. <p>
 !goto end
!endif

!if $job=getsource
 !read getsource.phtml
 !goto end
!endif

!if $activetest>-1
 <b>Informations générales :</b>
!endif
!read adm/sheet/sheetinfo.phtml

!ifval $activetest=-1
 !goto end
!endif

:end1
<p><hr width="40%"> <p>

<a name=list></a>
<b>Contenu de la feuille : </b>
!if $exocnt=0
 <p>Cette feuille n'a pas encore de contenu. 
!else
 <small>[
 !href module=adm/sheet&sh=$sheet&job=print Version imprimable
 ]</small>
 !read adm/sheet/sheetcontent.phtml
!endif

!if $activetest=0
 <p>Pour ajouter un travail (exercice, cours, outil, etc.) à la feuille, vous devez d'abord choisir l'objet correspondant (voir ci-dessous) ; réglez les différents paramètres proposés et lancez l'exercice.
 Ensuite, utilisez  le lien en bas de la page de l'exercice pour l'ajouter dans la feuille.
 Pour choisir votre travail, vous pouvez
  <ul>
   <li> passer par le moteur de recherche :
	!read adm/search_engine/form.phtml
   </li>
   <li> ou vous aider de cette 
    !href module=help/teacher/program correspondance indicative
    entre programmes de l'enseignement français et exercices WIMS.
   </li>
   <li> vous pouvez également 
    !href cmd=reply&job=prep_putsource $wims_name_putsource
   </li>
  </ul>
!endif

:end
!if $activetest>=0
 !if $activetest=0
  !let wims_menu_items=!append line putsource,1,cmd=reply&job=putsource to $wims_menu_items
 !endif
 !if $job!=getsource
  !let wims_menu_items=!append line sheetsource,1,cmd=reply&job=getsource to $wims_menu_items
 !endif
 !let wims_menu_items=!append line ,0,\
printable,1,module=adm/sheet&sh=$sheet&job=print\
,0,\
participantview,1,module=adm/sheet&sh=$sheet to $wims_menu_items
!endif

 !let wims_menu_items=!append line ,0,\
class_home,1,module=home to $wims_menu_items

!tail

!distribute item ,, into job,source,title,desc,prpage

