
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre

!set statutname=!defof SU_Uprep,SU_Uprep,SU_Ac,SU_Ex,SU_Hi in wimshome/public_html/modules/home/names.$lang
!set statutaction=Activer,Expirer,Désactiver,Cacher,Montrer,$wims_name_erase
!set seriesaction=$wims_name_change,$wims_name_erase,$wims_name_up

!! définition des noms pour les liens dans le menubox (définis par wims_menu_items)
!distribute items Insérer un fichier source,\
		Vue des participants,\
		Source de la feuille \
into wims_name_putsource,wims_name_participantview,wims_name_sheetsource

!let name_shtab=No,$wims_name_title,$wims_name_Description,Points,Poids,Dépendances,$wims_name_action

!if $activetest<=0
 !let wims_name_sheetadmin=Page de préparation
 !set name_title=!nosubst Préparation de la feuille $sheet
!else
 !let wims_name_sheetadmin=Page de gestion
 !set name_title=!nosubst Gestion de la feuille $sheet
!endif

!let name_shinfo=!nosubst $wims_name_title <small>(limité à $title_limit caractères)</small>,$wims_name_status,\
Texte d'explication <br></small>(limité à $desc_limit caractères; les tags et liens html sont admis)</small>,\
Date d'expiration,Page de présentation,Enregistrement des notes,pour toutes les classes partageant la feuille :
!let name_allowtype=ouvert pour tous, fermé pour tous, ouvert pour postes (et/ou heures) suivants :
!let name_mksheet=Créer la feuille

!distribute lines Informations générales&nbsp;\
Contenu de la feuille&nbsp;\
Cette feuille n'a pas encore de contenu.\
into name_info,name_content,name_warning

!set name_text1=Pour ajouter un travail (exercice, outil, etc.) à la feuille, vous devez d'abord choisir\
 l'objet correspondant (voir ci-dessous) ; réglez les différents paramètres proposés et lancez l'exercice.\
 Ensuite, utilisez le lien sur le bord de l'exercice pour l'ajouter à la feuille.\
 Pour choisir votre travail, vous avez une des possibilités suivantes
 
!set name_text2=Passer par le moteur de recherche
!set name_text3=Chercher un exercice parmi les 
!set name_text4=Chercher un exercice de votre compte

!if $job=student
  !set name_title=Feuille de travail numéro $sheet<br>$title (Présentation pour participants)
  !set name_sheetempty=Cette feuille est vide! Peut-être une erreur de manipulation de votre enseignant.
  !set name_assignedwork=Devoirs dans cette feuille&nbsp;
  !set name_quality=0 des $[$re] points obtenus, qualité
!endif

