
A esta herramienta de configuración sólo puede accederse desde las 
estaciones de trabajo seguras.
<p>
Como no ha definido ninguna estación de trabajo segura, vamos a
realizar la autentificación enviándole un código secreto a su dirección 
de correo electrónico.
Por favor lea el correo, busque el código y tecléelo debajo:
<p>
!form reply
<center><input size=12 name=repcode>
<input type=submit value=OK>
</form></center> <p>

<b>Notas</b>. Esta autentificación sirve para asegurarse de que aunque
se perdiera o robaran su contraseña, los daños a su clase serían limitados.
El proceso de autentificación es mucho más sencillo si define estaciones
de trabajo seguras de forma correcta, conservando un alto nivel de seguridad.
