
!if $cl_reccnt<1
 ¡Su clase está vacía!
 <p>
 No hay recursos en su clase que puedan borrarse.
 !exit
!endif

!if $cl_testcnt>0
 <b>ATENCIÓN</b>. No puede borrar recursos de la clase
 cuando ya han comenzado las actividades de los participantes.
 <p>
 Esta es una medida de seguridad importante. Si no le gusta
 esta limitación, piense en los dos siguientes aspectos:
 <p>
 Por un lado supongamos que un estudiante le roba la contraseña. Si entra
 en esta página para borrarlo todo, los otros estudiantes que no tienen
 culpa de nada lo van a pasar mal, y las actividades pedagógicas que había
 preparado usted resultarán muy perjudicadas.
 <p>
 Por otro lado, los diferentes recursos de la clase son interdependientes.
 Si borra ciertos recursos sin borrar los que dependen de ellos, la
 clase ya no funcionará.
 !href cmd=help&special_parm=dependencies Ejemplos.
 <p>
 De todas formas, si quiere hacer desaparecer de verdad esta clase, siempre puede
 borrarla (poniendo como fecha de expiración la de hoy la clase desaparecerá
 mañana por la mañana), o
 <a href="mailto:$wims_site_manager?subject=Por favor borre mi clase">pedir
 al administrador del sitio</a> que la borre por usted.
 !exit
!endif

!set no_erase=No se pueden eliminar porque usted está compartiendo los de otra clase.
<b>ATENCIÓN</b>. ¡Los recursos borrados desde esta página no se pueden 
 recuperar!
!href cmd=reply&job=arch&job2=first Hacer una copia de seguridad de la clase
 antes de borrar nada.
<p>
Recursos actuales de su clase:
<ul>
 <li>
 !href cmd=reply&job=clean&clean=all Eliminar todo lo que se pueda eliminar
.
!if $cl_usercnt>0
 <li>$cl_usercnt cuentas de participante.
 !if $sharing_user!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=user Borrar.
  !if $cl_scorecnt>0
   (También se borrarán los registros de actividad).
  !endif
 !endif
!endif
!if $cl_doccnt>0
 <li>$cl_doccnt documentos.
 !if $sharing_doc!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=doc Borrar.
 !endif
!endif
!if $cl_exocnt>0
 <li>$cl_exocnt ejercicios.
 !if $sharing_exo!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=exo Borrar.
 !endif
!endif
!if $cl_sheetcnt>0
 <li>$cl_sheetcnt hojas de trabajo.
 !if $sharing_sheet!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=sheet Borrar.
  !if $cl_examcnt>0
   (También se borrarán las hojas de examen).
  !endif
 !endif
!endif
!if $cl_examcnt>0
 <li>$cl_examcnt hojas de examen.
 !if $sharing_exam!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=exam Borrar.
 !endif
!endif
!if $cl_forumcnt>0
 <li>$cl_forumcnt mensajes del foro.
 !if $sharing_forum!=$empty
  $no_erase
 !else
  !href cmd=reply&job=clean&clean=forum Borrar.
 !endif
!endif
!if $cl_scorecnt>0
 <li>$cl_scorecnt líneas en los registros de actividad de participantes.
 !href cmd=reply&job=clean&clean=score Borrar.
!endif
</ul>

<p><b>Observaciones</b>. 1. Sólo se puede acceder a esta página mientras 
la página está en preparación. Una vez que han comenzado las actividades de 
los participantes, ya no es posible borrar los recursos.
<p>
2. Los recursos compartidos por varias clases sólo pueden borrarse
desde la clase maestra que comparte. Las otras clases deben
primero
!href cmd=reply&job=neighbor&job2=sharelist dejar de compartir
 los recursos antes de borrarlos.
