
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>

!set months=En,Feb,Mar,Abr,May,Jun,Jul,Ag,Sept,Oct,Nov,Dic

!set title=Configuración y Administración
!if $job=arch
 !set title=Copias de seguridad y Recuperación
 !goto commun
!endif

!if $job=clean
 !set title=Eliminación de la clase
 !goto commun
!endif

!if $job=neighbor
 !set title=Clases vecinas
 !goto commun
!endif

!if $job=connect
 !set title=Conectar a otros servidores / plataformas
 !goto commun
!endif

!if $job=access
 !set title=Configuración del acceso a los recursos
 !goto commun
!endif

!if $job2=addshare
 !set title=Compartir los recursos de una clase
 !goto commun
!endif

!if $job=grestrict
 !set title=Restricción del acceso a la puntuación
 !goto commun
!endif

!if $job=present
 !set title=Configuración de la apariencia de la clase
 !goto commun
!endif

!if $job=oefdefault
 !set title=Parametrización por defecto de los módulos OEF
 !goto commun
!endif

!if $job=security
 !set title=Actividades de gestión de seguridad disponibles
 !goto commun
!endif

!if $job=authtype
 !set title=Autenticación por un anuario ldap
!goto commun
!endif

:commun
!distribute line Autenticación\
Preferencias\
Restricción de acceso\
Parametrización OEF\
Clases vecinas\
Gestión de la seguridad\
Eliminación selectiva\
Actualisar\
Otros servidores\
Contraseñas\
zonas inferiores\
Apariencia\
Restricción de la puntuación\
Dirección de una plataforma\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items zonas,participantes,ejercicios, documentos, profesores\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers
