
!set classname=<b><font color=green>$wims_classname</font></b>\
 de <b><font color=green>$wims_institutionname</font></b>
 
!set months=En,Feb,Mar,Abr,May,Jun,Jul,Ag,Sept,Oct,Nov,Dic

!set title=Configuración y Administración
!if $job=arch
 !set title=Copias de seguridad y Recuperación
!endif

!if $job=clean
 !set title=Eliminación de la clase
!endif

!if $job=neighbor
 !set title=Clases vecinas
!endif

!if $job=connect
 !set title=Conectar a otros servidores / plataformas
!endif

