!set name_secure=Estaciones de trabajo seguras
!set name_colors=Colores de las páginas
!set name_css=Hoja de estilo
!set name_logo=Logo
!set name_theme=Tema de estilo
!set name_theme_icon=Jeu d'icones
!set name_ent=Links on another plateform
!if $wims_supertype=2
 !set name_thisclass=de la plataforma
 !set name_subclasses=subclases
!else
 !set name_thisclass=de la zona actual
 !set name_subclasses=zonas inferiores
!endif

!if $confirm!=$empty and $propagate!=$empty
 Las configuraciones han sido enviadas a las $name_subclasses con éxito: <p><b>
 !for s in $propagate
  $(name_$s).
 !next s
 </b>
!else
 !form reply
 Puede elegir enviar las configuraciones siguientes $name_thisclass
 a todas sus $name_subclasses: <p>

 !for s in $propall
  <input type="checkbox" name="propagate" value="$s">$(name_$s)&nbsp;
 !next s
 <p>
 <input type="submit" name="confirm" value="Enviar">
 </form>
!endif
<p>
Note que las $name_subclasses no repercutirán los
cambios posteriores de las configuraciones $name_thisclass. Debe
volver a enviar los cambios cada vez que quiera que se apliquen a
las $name_subclasses.

