
!if +$error iswordof +no_send_right
 !exit
!endif

!if $srclen=$empty or $srclen=0 or $msglen=$empty or $msglen=0
你的信息是空的!
 !goto end
!endif

$subj1 $c_subject $subj2 $body1
!read wimshome/$wims_sesdir/message.wims
$body2
$tag_escaper</table></ul></ol></dl></form><font size="+0">

:end
<p><center>
!href cmd=reply&job=compose 返回编辑
&nbsp;&nbsp;
!href cmd=reply&job=send 发送信息
&nbsp;&nbsp;
!href cmd=reply&job=list 放弃
</center> <p>

