<html><head>
$wims_html_header
</head>
<body $wims_htmlbody>

!read names.phtml

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

<center>$classname
<p>
<h1>參與者列表
</h1></center> <p><hr width="40%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 [
 !href module=home 回首頁
 ] <p>
 !goto end
!endif

!if $usercnt==0
 本課程尚未有參與者。
!else
 <center><table border=0 cellspacing=1 bgcolor=bisque>
 <tr><td><th rowspan=2>姓名<td><th colspan=2>全部課程<td>
 !for j in $showsheet
  <th colspan=2>清單 $j<td>
 !next j
 <tr><td><td>
 !for j=1 to $sheetcnt+1
  <th>已完成<th>平均成績<td>
 !next j
 <tr>
 !for i=1 to $usercnt
  !set uu=!record $i of wimshome/log/classes/$wims_class/.userlist
  !distribute items $uu into lastname,firstname,uu
  <tr><td><td> $lastname $firstname<td>
  !read userscore
  <td align=right>$per%<td align=right>$av/10<td>
  !set mean_per=$[$mean_per+$per]
  !set mean_av=$[$mean_av+$av]
  !for j in $showsheet
	!set pp=!line $j of $percents
	!set p1=!word 1 of $pp
	!set p2=!word 2 of $pp
	<td align=right>$p1%<td align=right>$p2/10<td>
	!set per_$j=$[$(per_$j)+$p1]
	!set av_$j=$[$(av_$j)+$p2]
  !next j
 !next i
 !set mean_per=$[rint($mean_per/$usercnt)]
 !set mean_av=$[rint(100*$mean_av/$usercnt)/100]
 <tr><tr><td><td align=center><b>本課程參與者</b><td>
 <td align=right>$mean_per%<td align=right>$mean_av/10<td>
 !for j in $showsheet
  !set per_$j=$[rint($(per_$j)/$usercnt)]
  !set av_$j =$[rint(100*$(av_$j)/$usercnt)/100]
  <td align=right>$(per_$j)%<td align=right>$(av_$j)/10<td>
 !next j
 </table></center>
 <p>點選姓名查看其作業詳細情形(未來計劃加入的功能)。
 !if $activecnt>1
  <p>
  !form reply
  您也可以選擇清單數以展示個別清單的平均：<p>
  !for i=1 to $activecnt
   !set sh=!line $i of $activesheets
   !set se=!item 1 of $sh
   !set ti=!item 2 to -1 of $sh
   <input type=checkbox name=showsheet value=$se
   !if $se iswordof $show
	checked
   !endif
   > 清單 $i : $ti. <br>
  !next i
  <p><center><input type=submit value=" 展示 "></center>
  </form>
 !endif
!endif (usercnt=0?)

:end
<p><hr width="30%"> <p>
!homeref
</body></html>

!set job=
!set showsheet=
