Une feuille d'exercices est une collection d'exercices sur un sujet donné.
Elle correspond à un certain but d'enseignement, et peut être utilisée dans
un environnement de classes virtuelles pour le but de controler le progrès
des élèves.
<p>
Cette base de données contient un ensemble de feuilles d'exercices accessibles
par le grand public. Vous pouvez librement tester votre connaissance sur
l'une d'elles, ou si vous êtes enseignant d'une classe virtuelle, en insérer
dans votre classe.

