Une feuille d'exercices est une collection d'exercices sur un sujet donné.
Elle correspond à un certain but d'enseignement et peut être utilisée dans
un environnement de classes virtuelles afin de contrôler le progrès
des élèves.
<p>
Cette base de données contient un ensemble de feuilles d'exercices accessibles
au grand public. Vous pouvez librement tester vos connaissances sur
l'une d'elles, ou si vous êtes enseignant d'une classe virtuelle, en insérer une
dans votre classe.

<p>
Par exemple,
<table align="center"><tr><td width="40%">
<ul><li>
!href module=home&search_keywords=math&search_category=S Mathématiques
</li><li>
!href module=home&search_keywords=physique&search_category=S Physique
</li><li>
!href module=home&search_keywords=chimie&search_category=S Chimie
</li>
</ul>
</td><td>
<ul><li>
!href module=home&search_keywords=ecole+levelE1+levelE2+levelE3+levelE4+levelE5+levelE6+levelH1&search_category=S École primaire
</li>
<li>
!href module=home&search_keywords=level6+levelE6+levelH1&search_category=S Sixième
</li><li>
!href module=home&search_keywords=level5+levelH1+levelH2&search_category=S Cinquième
</li><li>
!href module=home&search_keywords=level4+levelH2+levelH3&search_category=S Quatrième
</li>
<li>
!href module=home&search_keywords=level3+levelH3&search_category=S Troisième
</li>
</ul>
</td>
<td>
<ul><li>
!href module=home&search_keywords=level2+levelH4&search_category=S Seconde
</li><li>
!href module=home&search_keywords=level1+levelH5&search_category=S Première
</li>
<li>
!href module=home&search_keywords=levelT+levelH6&search_category=S Terminale
</li>
<li>
!href module=home&search_keywords=levelU+levelU1+levelU2+levelU3+levelU4&search_category=S Université
</li>
</ul>
</td></tr></table>
<p>
