
!if $phtml != $empty
 !changeto pages/$phtml
!endif

!header

!if $lang=cn
 本模块供放置 light phtml 之用. 
 如果你不指明 phtml 文件名而调用它, 它将什么事也不干.
!endif

!if $lang iswordof en fr tw
 This is a module housing light phtml files. If you call it without
 specifying the name of the phtml file, it does nothing.
!endif
!if $lang=nl
    Deze module bevat light phtml file. 
    Wanneer deze module wordt opgeroepen zonder de naam van de phtml file, doet deze module niets.     
!endif


!if $lang iswordof es
 Este m骴ulo es un almacen de archivos phtml. Si lo llamas sin
 especificar el nombre del archivo phtml, no hace nada. 
!endif

:end
!tail

