
!set form_OK=Envoyer la modification
!set form_titlename=Titre
!set form_caption=Propriétés de la classe
!set title=$class_description
!set sup=$class_Supervisor
!read scripts/classform.phtml

<p>
!if $coursecnt=0
 Cette classe n'a pas encore de cours.
 !href cmd=reply&cparent=class&job=addcourse Ajouter un cours
.<sup>
 !href cmd=help&special_parm=structure#course aide
</sup>
!else
 $table_header
 <caption>Cours existants<sup>
 !href cmd=help&special_parm=structure#course aide
 </sup> dans cette classe
 !href cmd=reply&cparent=class&job=addcourse Ajouter&nbsp;un&nbsp;autre&nbsp;cours
 </small></caption>
 $table_hdtr
 <th>Code<th>Nom</th><th>-</th><th>Responsable</th>
 </tr>
 !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into l_,s_,t_,n_
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=course&cparent=class&course=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=delcourse&cparent=class&del=$l_ $wims_name_erase
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $s_
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
    Non disponible
   !endif
 !next i
 $table_end

!endif
!set wims_menu_items=!append line "Ajouter un cours",1,cmd=reply&cparent=class&job=addcourse\
to $wims_menu_items
!reset title

