
!read adm/title.phtml 3\
$name_delclass0 <em>$class_description</em>

<font color=red><b>AVERTISSEMENT</b>.</font> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans cette classe sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;: cours, comptes d'élèves, activités, notes&nbsp;!
<p>
Etes-vous sûr de vouloir effacer cette classe&nbsp;?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level $wims_name_no

</font></center> <p>

