
<center><h3>Effacer la classe <em>$class_description</em></h3></center>

<blink><b>AVERTISSEMENT</b>.</blink> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans cette classe sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;: cours, comptes d'élèves, activités, notes&nbsp;!
<p>
Etes-vous sûr de vouloir effacer cette classe&nbsp;?
<p><center><font size=+1>

!href cmd=reply&job=$job&del=$del&confirm=yes Oui
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level Non

</font></center> <p>

