
<center><h3>Effacer le programme <em>$class_description</em></h3></center>

!if $class_recshare=main
 Vous ne pouvez pas effacer ce programme car ses ressources pédagogiques sont
 partagées par d'autres programmes.
 !href cmd=reply&job=$job Annuler
 !exit
!endif

<blink><b>AVERTISSEMENT</b>.</blink> Cette opération est irréversible&nbsp;!
Et <font color=red>TOUT</font>
dans ce programme sera <font color=red>DEFINITIVEMENT</font>
effacé&nbsp;: cours, activités, notes&nbsp;!
<p>
Etes-vous sûr de vouloir effacer ce programme&nbsp;?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes Oui
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level Non

</font></center> <p>

