<center>
!if $teachercnt=0
 Il n'y a pas encore de compte d'enseignants.
 !href cmd=reply&job=addteacher $wims_name_addteacher
. <p>
!else
 Il y a
 !href cmd=reply&job=teacher $teachercnt $wims_name_teacher
.
!endif
!set wims_menu_items=!append line addteacher,1,cmd=reply&job=addteacher \
to $wims_menu_items
!goto nopart
!if $studentcnt=0
 <p>
 Il n'y a pas encore de compte d'élèves.
 !href cmd=reply&job=addstudent $wims_name_addstudent
.
!else
!set wims_menu_items=!append line student,1,cmd=reply&job=student\
to $wims_menu_items
 !href cmd=reply&job=student $studentcnt $wims_name_student
.
!endif
!set wims_menu_items=!append line addstudent,1,cmd=reply&job=addstudent\
to $wims_menu_items

:nopart
</center>
<p>
!if $levelcnt=0
  Aucun niveau d'enseignement n'est encore installé.
  !href cmd=reply&job=addlevel $wims_name_addlevel
  !set wims_menu_items=!append line addlevel,1,cmd=reply&job=addlevel\
to $wims_menu_items
.<sup>
  !href cmd=help&special_parm=structure#level $wims_name_help
</sup>
!else
 $table_header
 <caption>Niveaux d'enseignement disponibles<sup>
 !href cmd=help&special_parm=structure#level $wims_name_help
 </sup><br><small>
 !href cmd=reply&job=addlevel $wims_name_addlevel
 &nbsp; 
 !href cmd=reply&job=backstruct $wims_name_backstruct
 !set wims_menu_items=!append line addlevel,1,cmd=reply&job=addlevel\
 backstruct,1,cmd=reply&job=backstruct\
to $wims_menu_items
 </small></caption>
 $table_hdtr
 <th>Code<th>Nom</th><th>-</th><th>Responsable</th>
 <th><small>Classes</small></th>
 <th><small>Programmes</small></th>
 </tr>
 !for i=1 to $levelcnt
   !set l=!line $i of $leveldata
   !distribute items $l into l_,s_,t_,n_
   !set c=!positionof item $l_ in $classl
   !set c=!itemcnt $c
   !set p=!positionof item $l_ in $progl
   !set p=!itemcnt $p
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=level&level=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=dellevel&del=$l_ $wims_name_erase
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $name_supervisor
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
    Non disponible
   !endif
   </td><td align=center>$c
   </td><td align=center>$p
 !next i
 $table_end
!endif

