
<b>Importing resources from a neighboring class</b>.
<br>
You can import resources or participant accounts from an effective
!href cmd=help&special_parm=neighbor neighboring class
 for supervisor.
<p>
To import something from a class, choose the class name in the list of other
classes. If you are allowed to import from it, a link will lead you to a page
with a list of importable resources. Only items that you do not have in
your own class will be listed.
<p>
Importation of an item does not affect that item in the exporting class. If
you modify the imported item in your class, its origin in the exporting
class will not be modified, and vice versa. If you want to share
modifications with the other class, you should consider 
!href cmd=help&special_parm=share sharing resources
 with it.
<p>
For worksheets and exam sheets, only active (or expired) worksheets are
importable. Once installed in your class, the imported worksheet will become
inactive. This allows you to verify the imported material, eventually modify
it, before activating it.
<p>
For participant accounts, please note that you cannot import a participant
if its login name is in use in your class, even if you have erased the latter.

