!read adm/css.phtml
!read lang/names.phtml.$moduclass_lang

!header1
!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$module_title

!set wims_menu_items=!append line part_list,1,module=adm/class/userlist\
 to $wims_menu_items
!if $cmd!=reply
$name_intro
 !form reply
 
<input type="hidden" name="job" value="all">  
<center><input type="submit" name="reg" value="$wims_name_tosave"></center>
<p>

<fieldset>
<legend>$name_menu
</legend>
$name_expert
&nbsp;
&nbsp;
!set wims_ref_class=wims_button_help
!href cmd=help $wims_name_help


<center><table>
<tr><td>
!default job=$job
!formcheckbox job list filter prompt $name_filter
</td><td><textarea name="variable" cols="20" rows="3">$variable</textarea>
</td></tr>
<tr><td>
!formcheckbox job list login prompt $name_loginlist
 </td><td>  
   <textarea name="loginlist" cols="20" rows="5">$loginlist</textarea>
   </td></tr>
   </table>
<center>
</fieldset>  
</form>
!goto end
!endif 

!if $photourl_exists=0
 <center> $name_nophoto</center>
 !goto end
!endif
!set cmp=0
!set cmp_tr=0
<table><tr>
!for l_ =1 to $cnt 
  !set u=!line $l_ of $list_user
  <td width="120"><span>
  !if $(u[4])!=
    !href module=adm/class/userlist&job=getuser&getuser=$(u[1]) <img border="0" width="120" src="$(u[4])" alt="$(u[2]) $(u[3])">
    <br>$(u[2]) $(u[3]) 
  !else
     !href module=adm/class/userlist&job=getuser&getuser=$(u[1]) $(u[2]) $(u[3])
  !endif
  </span></td>
  !increase cmp_tr
  !increase cmp
  !if $cmp_tr=6
  </tr>
  !reset cmp_tr
  <tr>
  !endif
  !reset u
!next 
</table>

!if $cmd=reply
 !set wims_menu_items=!append line back2,1,cmd=resume\
 to $wims_menu_items
!endif
:end
!tail
