<h1 class="wims_docu_title">$tit</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!if $erase!=$empty
 Se ha borrado el fichero <b>$erase</b>.
 <p>
!endif

!if $quota_free<1
 Ya no puede incorporar más ficheros a este documento porque su contenido
 está muy cerca (o lo ha superado) del límite de espacio de disco permitido.
 Los sentimos.
!else
 !set wims_form_method=file
 !form reply
 <input type=hidden name=job2 value=deposit>
 Puede añadir un fichero a este documento:
 <input type=file size=35 name=wims_deposit>
 <input type=submit value=OK>
 </form>
!endif

!if $flist!=$empty
 <p>Ficheros disponibles en este documento:
 !for f in $flist
  !getfile doc/$f $f
  &nbsp;
 !next f
 <p>
 !form reply
 <input type=hidden name=job2 value=erase>
 Borrar un fichero:
 !formselect job2 list $flist
 <input type=submit value=OK>
 </form>
 <p>
 Se puede acceder a los ficheros del documento usando la 
variable <tt>\filedir</tt> en el documento. Por ejemplo
<p><center>
 <tt>&lt;a&nbsp;href="\filedir/$f1"&gt;$f1&lt;/a&gt;</tt>
</center> <p>
 proporciona un enlace al fichero <a href="$m_filedir/$f1">$f1</a>.
 También puede escribir
<p><center>
 <tt>&lt;img src="\filedir/myfile.jpg" alt="myfile"&gt;</tt>
</center> <p>
para incluir un fichero de imagen <tt>myfile.jpg</tt> en la página.
 <p>
 Los ficheros incorporados en el documento sólo serán accesibles
 a quienes estén autorizados a leer el documento.
!endif

<p>
$n_freespace1 $quota_total Meg.
$n_freespace2 $quota_free Meg.
!set wims_menu_items=!append line properties,1,cmd=reply&job=prop\
  blocklist,1,cmd=reply&job=list\
  doch_main,1,cmd=reply&job=read&block=main\
to $wims_menu_items

!if $(readhist[-1;2])!=main
 !set wims_menu_items=!append line "<tt>$(readhist[-1;2])</tt>",1,cmd=reply&job=read&block=$(readhist[-1;2])\
to $wims_menu_items 
!endif

<p>

