!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p>
 !exit
!endif

<h1 class="wims_docu_title">$tit</h1>

!if $titb=$empty
 <p>
 El bloque <tt>$block</tt> no ha sido creado aún.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Esta página todavía no está abierta para su lectura. ¡Vuelva más adelante!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Esta página ha expirado, ya no es posible leerla. ¡Lo sentimos!
 <p>
 !exit
!endif

:newblock
<a name=$block></a>
<h3>$titb</h3>

!read $wims_priv_thisdoc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $wims_priv_thisdoc/$block.def
 <p>
 !goto newblock
!endif
