
<h1 class="wims_docu_title">$tit
!if $editable=yes
 </b><font size="-1">[
 !if $block=main
  !href cmd=reply&job=prop Propiedades
  ] [
  !href cmd=reply&job=erase Borrar
 !else
  !href cmd=reply&job=list Otros bloques
 !endif
 ]</font>
!endif
</h1>

!if $error!=$empty
 !read docu/$lang/msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 El bloque <tt>$block</tt> no ha sido creado aún.
 !if $editable=yes
  !href cmd=reply&job=edit&block=$block Crearlo
.
 !endif
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Esta página todavía no está abierta para su lectura. ¡Vuelva más adelante!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Esta página ha expirado, ya no es posible leerla. ¡Lo sentimos!
 <p>
 !exit
!endif

<h3>$titb
!if $editable=yes
 </b><font size="-1">[
 !href cmd=reply&job=edit&doc=$doc&block=$block Editar
 ]</font>
!endif
</h3></div>

!!detrust
!read $docdir/$doc/$block.def content


