
!read adm/title.phtml 1\
$wims_classname, $wims_institutionname
Delovni list #$sheet<br>$title
(Prikaz za uporabnike)

!!<hr width=1>
!!<center><h3>$wims_classname, $wims_institutionname</h3>
!!<hr> <p><h1>Delovni list #$sheet<br>$title</h1>
!!</center> <p>

<div class="wims_sheet_desc">$desc</div><p>

!if $exocnt=0
 Ta delovni list je prazen. Morda gre za napako skrbnika.
!else
 Zahtevane naloge na tem listu:<p><ul>
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sheet
  !distribute lines $ex into di,pa,re,we,ti,de,dep
  <li><p>$i. 
  !href module=$di&cmd=new&worksheet=$parm1&$pa $ti
, $de
  !if $re>0
   <small>0 toèk (zahtevanih $[$re]), kvaliteta
   0/10. </small>
  !endif
 !next i
 </ul>
!endif
<p>
!homeref
!set wims_menu_items=!append line ,0,\
backteacher,1,cmd=resume\
to $wims_menu_items
!!<p><hr> <p>
!!<center>
!!!href cmd=resume Nazaj na skrbni¹ke strani.
!!</center>

!tail

!set job=

