
!if $datacnt<1
 No module updates have yet been recorded to this server. This record 
 starts to work with the module publication and updating system
 introduced in WIMS-3.37f.
 !exit
!endif

!set w_=!replace internal /wims.cgi by in $wims_ref_name

$table_header
<caption>Recent module updates on the server</caption>
$table_hdtr<th>Date</th><th>Lang</th><th>Title</th><th>Description</th>
<th>New<br>version
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>
 $desc
 </td><td align=center>$v_</td></tr>
 !reset desc tit
!next i
$table_end
