
!distribute items $wims_debug_info into v_1,v_2,v_3,cpu_1,cpu_2,c_,f_,e_
<p align="center"><small>
The server is under debug mode. Your session: $wims_session. <br>
Variable buffer: $v_1 bytes used by $v_2 variables + $v_3 freed chunks. <br>
$f_ files read, $c_ cached, $e_ cmds executed. <br>
Processing time $cpu_1 seconds, CPU usage $cpu_2 seconds. <br>

!if $wims_exec_error!=$empty
<pre>$wims_exec_error</pre>
!endif
</small></p>