<title>$module_title2</title>
<meta http-equiv="Content-Type" content="text/html; charset=$wims_main_font">
<meta name="GENERATOR" content="wims [$module_language]">
<meta name="description" content="$module_description $wims_site_description">
<meta name="keywords" content="$wims_site_keywords, $module_domain, $module_keywords">
<meta name="Author" content="$module_author">
<meta http-equiv="Content-Style-Type" content="text/css">
$wims_expire
$wims_CSS
