!nocache
!if $oef_test=yes
 !set renewlink=cmd=next&retest=again
 !!$header_js
 !goto tester
!else
 !set init_parm=!translate + to $ $ in $module_init_parm
 !set init_parm=!replace internal $\
$ by ; in $init_parm
 !set renewlink=cmd=renew&worksheet=$worksheet&$init_parm
!endif

!if $printing=yes
 !changeto oef/print.phtml
!endif

!if $title!=$empty
 !set module_title=$title
 !set module_author=$author
 !set module_address=$email
!endif

!if 0$delay2>0 and $status!=$empty
 !set now_=$wims_nowseconds
 !read js/chrono.phtml $[max(0,$delay1-($now_-$starttime))]
!endif
!set wims_html_header=!append line $header_js to $wims_html_header
!set wims_html_header=$oefcss\
$wims_html_header

!header1
<h1 class="oeftitle">$title</h1>

!if $module_checkdata!=yes
 !read oef/$module_language/nodata.phtml
 !goto end
!endif

!if $title=$empty
本模块是一组练习. 你想做练习, 但又没有指出你想做哪个练习.
可能是由于你点击了一个错误的链接, 也可能是软件的错误.
 <p><center>
 !href module=$module 重新操作
 , 或
 !href $ 放弃
 . </center>
 !goto end
!endif

!if 0$delay1>0 and $status!=$empty
 <p><form target="#" name=chrono><center>
 <table border=2 bgcolor="$wims_ref_bgcolor"><tr><td>
 &nbsp;<b><font color=red>注意!</font></b>
 !if $qnum>1
  本组练习有时间限制.
 !else
  本练习有时间限制.
 !endif
 <input size=4 name=clock readonly onFocus="this.blur();">
 </table>
 </center></form> <p>
!endif

:tester
!read oef/present.phtml

!if $wims_theme_version= or $wims_theme_version<1 
<center><hr width="50%"></center>
!endif

!if $cmd=hint
 !read oef/hint.phtml
 !goto end
!endif

!if $status=waiting
 !if $error!=$empty
  !read oef/msg.phtml
 !if $wims_theme_version= or $wims_theme_version<1 
  <center><hr width="50%"></center>
 !endif
 !endif
 !read oef/form.phtml
 <p>
 !if $hint!=$empty and $givehint>0
  !href cmd=hint 提示
.
 !endif
 !if $help!=$empty
  !href cmd=help 帮助
.
 !endif
 !if $qnum<=1
  !href $renewlink 换一个练习
.
 !else
这是本组 $qnum 个习题中的第 $[$reply_cnt+1] 个习题.
  !href $renewlink 放弃本组练习
.
 !endif
!else
 !if $error!=$empty
  !read oef/msg.phtml
  !if $wims_theme_version= or $wims_theme_version<1 
  <center><hr width="50%"></center>
  !endif
 !endif
 !read oef/answer.phtml
 <p>
 !if $status!=$empty
这是本组 $qnum 个习题中的第 $reply_cnt 个习题. <p>
  !href cmd=next 继续下一个习题
, 或
  !href $renewlink 放弃本组练习, 要求一组新的练习
. (如果你需要成绩的话, 你必须做完本组练习的所有习题.)
 !else
  !if $qnum>1
你已做完了一组 $qnum 个习题, 成绩是
   $module_score/10.
   !ifval $module_score>9.8
    祝贺你!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (你已因超时而被扣分.)
   !endif
   <p>
   !href $renewlink 再来一次
.
   !if $wims_sheet=$empty
    !href exo_Intro
.
   !endif
  !else
你的成绩是 $module_score/10.
   !ifval $module_score>9.8
    祝贺你!
   !endif
   !if $toolate!=$empty and $score>$module_score
    (你已因超时而被扣分.)
   !endif
   <p>
   !href $renewlink 再来一次
.
   !if $wims_sheet=$empty and $oef_test!=yes
    !href exo_Intro
.
   !endif
  !endif
 !endif
!endif

!if $replydefaulted=yes
 <p> <small>
开发模式: 默认情形下正确答案被插入选择区域内.
 </small>
!endif

!read ./endhook.phtml
!!!if $wims_user=supervisor and exam notin $session and \
!!    ..classes/ notin ..$module and ..adm/ notin ..$module and \
!!    ..devel/ notin ..$module and \
!!    GNU isin $module_copyright and \
!!   _check notin $session and \
!!    $class_importation!=no
!! <p>
!! !href module=adm/createxo&existing=$thisexo&catmodule=$module 插入
!!本练习到你的班级 (你可以在那里修改它).
!!!endif
:end
!tail

