!! This file contains error messages. It will be processed
!! whenever the variable `error' is not empty.
!set wims_module_error=error: $error

<b>错误.</b>

!if empty_out iswordof $error
 Your code did not give any output. Please correct it.
 !if $m_reply_err!=$empty
  <pre><font color=red>$m_reply_err</font></pre>
 !endif
 !exit
!endif

!if empty_data iswordof $error
你发回的答案不完整, 请完成它.
 !exit
!endif

!if bad_data iswordof $error
我不能理解你发来的数值, 是打字错误吗?
 !exit
!endif

!if double_reply iswordof $error
你已经送来过这个练习的回答, 并已被分析与纪录. 
重复回答将不被考虑. (不要使用浏览器的 `reload' 按钮重复回答!)
 !exit
!endif

!if bad_answer iswordof $error
 !if illegalname iswordof $test
  Your code contains illegal name <tt>$illegal_name</tt>. Please correct.
  !exit
 !endif
 !if lengthoverflow iswordof $test
  Your code has exceeded the length limit. Please rewrite it.
  !exit
 !endif
你的回答 <p><center>
 <b>$bad_name</b> = <tt>$bad_value</tt> <p></center>
 !if nocompute isin $test
是不允许的&nbsp;: 请你自己计算出答数, 再将其送回.
 !else
无法理解. 请订正后再发送一次.
 !endif
 !exit
!endif

!if bad_exo iswordof $error
 由于本练习有错，无法检测您的回答的正确性. 您现在唯一的解决办法是换一个
 练习, 非常抱歉.
 <p>
 如果您要报告本练习的错误,
 !if $email!=$empty
  请
  !mailurl $email 与作者联系
.
 !else
  请与作者联系.
 !endif
 !exit
!endif

!if too_many_print iswordof $error
 你对可打印版本的请求超过了限制.
 !exit
!endif

