!! Give answers in this file.
!if $step >= $limit
  $name_limit
!endif
<ul>
<li>
$name_copy
</li>
<li>
$name_createxo
!href module=adm/createxo&mode=model&+level=2 $wims_name_createxo
. $name_createxo2

</li>
</ul>
<center>
<table><tr><td style="width:100px; height-min:50px;text-align:top;">
!set insdraw_filebase=!append word $wims_home/sessions/$wims_session/$sesdir to $insdraw_filebase
      !insdraw copy 0,0,-1,-1,-1,-1,$wims_deposit\
     $dessin
</td><td>
  <pre>
$data
</pre>
</td></tr></table>
</center>

