!header

!if $step=1
 !set wims_menu_items=!append line createxo,1,module=adm/createxo\
 to $wims_menu_items
!else
!set wims_name_renew1=$wims_name_renew
!set wims_name_renew=$name_empty
  !set wims_menu_items=!append line renew,1,cmd=renew\
to $wims_menu_items
!endif

!if $end!=0 and $end!=$empty
 !if $error!=$empty
  <div class="wims_msg alert">
  !read msg.phtml
  </div>
  !read menu.phtml
  !goto end
 !else
  !read answer.phtml
  !set wims_menu_items=!append line resume,1,cmd=resume\
  createxo,1,module=adm/createxo&rawinp=yes&+level=1\
to $wims_menu_items
  !reset end
 !endif
!else
 !! put some explanations here.
 !read menu.phtml
!endif compute=yes?
!if $wims_theme=default
 !set wims_menu_items=!append line modtool,1,module=adm/modtool\
   to $wims_menu_items
!endif
:end
!tail
