!goto $gstep

:0

!! setup variables on the first page ??

!goto end

:1

!default creyear=!char 1 to 4 of $class_creation
!default expyear=!char 1 to 4 of $class_expiration

!if $jyear=$empty
 !let jyear=!char 1 to 4 of $wims_now
 !let jmonth=!char 5 to 6 of $wims_now
 !let jday=!char 7 to 8 of $wims_now
!endif

  <th>$name_numstud</th><th>$name_examdate</th><th>$name_begintime</th><th>$name_endtime</th><th>$name_connip</th><th>$name_extra</th>
 </tr>
 !for i=1 to $numsess
$table_tr
  <td>
  <input size=4 name="nstud$i" id="nstud$i" value="$(nstud$i)">
  </td>
  <td>
   !default bday$i=$jday
   !default byear$i=$jyear
   !default bmonth$i=$jmonth
   !distribute item $[$(bday$i)],$[$(bmonth$i)],$[$(byear$i)] into bday$i,bmonth$i,byear$i
!if $vote_status=0
   !read adm/lang/datemenu.phtml.$moduclass_lang 1, bday$i,bmonth$i,byear$i
!else
  $(bday$i) $(months[$(bmonth$i)]) $(byear$i)
!endif
  </td>
  <td>
!if $vote_status=0
   !read adm/lang/datemenu.phtml.$moduclass_lang 6,bhour$i,bmin$i
!else
   $(bhour$i):$(bmin$i)
!endif
  </td>
  <td>
!if $vote_status=0
   !read adm/lang/datemenu.phtml.$moduclass_lang 6,ehour$i,emin$i
!else
   $(ehour$i):$(emin$i)
!endif
  <td>
!if $vote_status=0
   !default exconnip$i=$defconnip
   <input size=10 name="exconnip$i" id="exconnip$i" value="$(exconnip$i)">
!else
   $(exconnip$i)
!endif
  </td>
  <td>
   <input size=10 name="testoextra$i" id="testoextra$i" value="$(testoextra$i)">
  </td>
 </tr>
 !next i

!goto end

:2

!for i=1 to $numsess
!for dato in nstud$i,bday$i,mese$i,byear$i,bhour$i,bmin$i,testoextra$i,\
 bmonth$i,ehour$i,emin$i,exconnip$i
 !appendfile $votedir/$vote.data $dato=$($dato)
!next dato
!next i

!appendfile $votedir/$vote.data \
:$testointro

!set reg_src=<div>\
$testointro\
</div>\
\list{

!set reg_src1=$reg_src
!set reg_src2=\uservar{$nameexvar,>20081105.17:30 <20081105.15:30,

!for i=1 to $numsess
!set mese$i=!item $(bmonth$i) of $months
!set bmonth$i=!char 2,3 of $[abs(floor($(bmonth$i)))+100]
!set byear$i=!char -4 to -1 of $[abs(floor($(byear$i)))+100000]
!set bmin$i=!char 2,3 of $[abs(floor($(bmin$i)))+100]
!set emin$i=!char 2,3 of $[abs(floor($(emin$i)))+100]
!set bday$i=!char 2,3 of $[abs(floor($(bday$i)))+100]
!set bhour$i=!char 2,3 of $[abs(floor($(bhour$i)))+100]
!set ehour$i=!char 2,3 of $[abs(floor($(ehour$i)))+100]

!set reg_src1=$reg_src1\
$(nstud$i): $(bday$i) $(mese$i) $(byear$i) - $(bhour$i).$(bmin$i) / $(ehour$i).$(emin$i)$ $(testoextra$i),
!set reg_src2=$reg_src2\
 >$(byear$i)$(bmonth$i)$(bday$i).$(bhour$i):$(bmin$i) <$(byear$i)$(bmonth$i)$(bday$i).$(ehour$i):$(emin$i) $(exconnip$i),

!next i
!set reg_src=$reg_src1\
$name_cancellation\
}\
$reg_src2\
 >20081105.17:30 <20081105.15:30\
}


:end