<p><b> $name_content </b>:

!if $vote_status>0
  <br/>$name_nowritable
<pre>
!record 0 of $votedir/$vote.src
</pre>
!else
 &nbsp;
 !set wims_ref_class=wims_button_help
 !href cmd=help $wims_name_help
 </p>
 <center>(
 !if $speckedit=no
    !set msgsrc1=<textarea id="src" name="reg_src" cols="80" rows="20">$src</textarea>
    !href cmd=reply&job=edit&speckedit=yes  $wims_name_active
 !else
   !set msgsrc1=<textarea class="iEdit" id="src" name="reg_src" cols="80" rows="20">$src</textarea>
   !href cmd=reply&job=edit&speckedit=no $wims_name_desactive
 !endif
 - <small>$wims_name_speck_warning</small>)
 
 $msgsrc1
!endif
