!goto $gstep

!! FIXME: which variables should be set in the form? in this file we use both
!!        exconnip$i and testoextra$i so that we can switch from exams to
!!        groups and backwards, but does it make sense?

:0

!! setup variables on the first page ??

!goto end

:1

<p>$name_introtext</p>
!! FIXME: only text in this textarea, no vote primitives: need to chech user input. also can use editor??
<center>
<textarea class="iEdit" id="testointro" rows="10" cols="80" name="testointro">
!replace internal \( by &#92;( in $testointro
</textarea>
</center>

<p>$name_numsess_pre $numsess $name_numsess_post</p>

$table_header
$table_hdtr

  <th>$name_numstud</th><th>Group $name_group</th><th>$name_extra</th>
 </tr>
 !for i=1 to $numsess
$table_tr
  <td>
  <input size=4 name="nstud$i" id="nstud$i" value="$(nstud$i)">
  </td>
  <td>
!! need a variable, using exconnip
!default exconnip$i=gruppo $i
!if $vote_status=0
   <input size=20 name="exconnip$i" id="exconnip$i" value="$(exconnip$i)">
!else
  $(exconnip$i)
!endif
  </td>
  <td>
   <input size=10 name="testoextra$i" id="testoextra$i" value="$(testoextra$i)">
  </td>
 </tr>
 !next i

!goto end

:2

!! need to check $testointro contains no vote primitives
!for i in uservar,menu,list,radio,checkbox,textarea
!set testointro=!replace internal \$i by INVALID in $testointro
!next i

!for i=1 to $numsess
!! need to check no "," in exconnip/testoextra
!set exconnip$i=!replace internal , by . in $(exconnip$i)
!set testoextra$i=!replace internal , by . in $(testoextra$i)
!for dato in nstud$i,testoextra$i,exconnip$i
 !appendfile $votedir/$vote.data $dato=$($dato)
!next dato
!next i

!appendfile $votedir/$vote.data \
:$testointro

!set reg_src=<div>\
$testointro\
</div>\
\list{

!set reg_src1=$reg_src
!set reg_src2=\uservar{$nameexvar,nogroup,

!for i=1 to $numsess

!set reg_src1=$reg_src1\
$(nstud$i): $(exconnip$i) $(testoextra$i),
!set reg_src2=$reg_src2\
$i,

!next i
!set reg_src=$reg_src1\
$name_cancellation\
}\
$reg_src2\
nogroup\
}


:end