
!goto $gstep

:1

$table_header
$table_tr
<td>$name_howmany ($name_atmost 10)</td>
<td>
!if $vote_status>0
$numsess
!else
!formselect mod_numsess from 1 to 10
!endif
</td>
</tr>
$table_tr
<td>$name_namevar <span class="field_required">*</span></td>
<td>
!if $vote_status>0
$namevar
!else
<input size=12 name="up_namevar" id="namevar" value="$namevar"><small>$(name_$(reg_model)_help)</small>
!else
</td>
</tr>
$table_end
<input type="hidden" name="gstep" value="2">

!exit
:2
<p>$name_introtext</p>
<center>
<textarea class="iEdit" id="testointro" rows="10" cols="80" name="up_testointro">
!replace internal \( by &#92;( in $testointro
</textarea>
</center>

<p>$name_session_select</p>

$table_header
$table_hdtr

  <th>$name_numstud</th><th>$name_group1</th><th>$name_extra</th>
 </tr>
 !for i=1 to $numsess
$table_tr
  <td>
  <input size=4 name="up_nstud$i" id="nstud$i" value="$(nstud$i)">
  </td>
  <td>
!! need a variable, using exconnip
!default exconnip$i= $i
!if $vote_status=0
   <input size=20 name="up_exconnip$i" id="exconnip$i" value="$(exconnip$i)">
!else
   $(exconnip$i)
!endif
  </td>
  <td>
   <input size=10 name="up_testoextra$i" id="testoextra$i" value="$(testoextra$i)">
  </td>
 </tr>
 !next i
 $table_end
<input type="hidden" name="gstep" value="3">
!goto end

:3

!!## need to check $testointro contains no vote primitives
!for i in uservar,menu,list,radio,checkbox,textarea
  !set testointro=!replace internal \$i by INVALID in $testointro
!next i
!writefile $votedir/$vote.data

!!## with writefile we are loosing these variables at gstep=3
!for dato in numsess,namevar,defconnip
  !appendfile $votedir/$vote.data $dato=$($dato)
!next dato
!!## NOTE: the above list should be setup at model level 
!##! (e.g. defconnip is not needed for vote_model=groups)

!for i=1 to $numsess
!!## need to check no "," in exconnip/testoextra
  !set exconnip$i=!replace internal , by . in $(exconnip$i)
  !set testoextra$i=!replace internal , by . in $(testoextra$i)
  !for dato in nstud$i,testoextra$i,exconnip$i
   !appendfile $votedir/$vote.data $dato=$($dato)
  !next dato
!next i

!appendfile $votedir/$vote.data \
:$testointro
!set reg_src=<div>\
$testointro\
</div>\
\list{

!set reg_src1=$reg_src
!set reg_src2=\uservar{$namevar,nogroup,

!for i=1 to $numsess

!set reg_src1=$reg_src1\
$(nstud$i): $(exconnip$i) $(testoextra$i),
!set reg_src2=$reg_src2\
$i,

!next i
!set reg_src=$reg_src1\
$name_cancellation\
}\
$reg_src2\
nogroup\
}
$name_describesource
<p>$name_yourvariable.</p>
<pre>
$reg_src
</pre>
$(name_$(reg_model)_instr)
<input type="hidden" name="gstep" value="0">

:end