
This configuration tool is only accessible to secure hosts.
<p>
As you haven't defined any secure hosts, we are checking your authentification
by sending a secret code to your email address. Please check your mail, pick
the code, and type it below:
<p>
!form reply
<center><input size=12 name=repcode>
<input type=submit value="$wims_name_tosave">
</form></center> <p>

<b>Note</b>. This authentification is to ensure that even if your password
is stolen or leaked, damages to your class will be limited.
Defining correct secure hosts will simplify the class
configuration procedure, while keeping a high security level.

