
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>

!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!set title=Configuration and Maintenance
!if $job=arch
 !set title=Backup and Restoration
 !goto commun
!endif

!if $job=clean
 !set title=Clean up the class
 !goto commun
!endif

!if $job=neighbor
 !set title=Class neighbors
 !distribute lines Neighborhood<br>declaration\
   Resource sharing\
   by you\
   by the other\
   Active mutually sharing.\
   You are sharing its resources.\
   Sharing your resources.\
   Mutually allowing sharings.\
   Allowed to share your resources.\
   Allows you to share its resources.\
   Stop this sharing\
   Share\
 into name_declaration,name_sharing,name_byyou,name_other,name_actif,name_share1,name_share2,\
 name_permit1,name_permit2,name_permit3,name_stopsharing,name_share
 !goto commun
!endif

!if $job=connect
 !set title=Connect to other servers / platforms
 !goto commun
!endif

!if $job=access
 !set title=Resource access configuration
 !goto commun
!endif

!if $job2=addshare
 !set title=Share resources on class 
 !goto commun
!endif

!if $job=grestrict
 !set title=Score restriction
 !goto commun
!endif

!if $job=present
 !set title=Configuration of appearances of the class.
 !goto commun
!endif

!if $job=oefdefault
 !set title=Default configuration for OEF modules
 !goto commun
!endif

!if $job=security
 !set title=Available security management activities
 !goto commun
!endif

!if $job=authtype
 !set title=Ldap authentification
 !goto commun
!endif

:commun
!distribute line Authentification\
My personal preferences\
Resource restrictions\
OEF configuration\
Class neighbors\
Security management\
Selective cleanup\
Rebuild\
Other servers\
Passwords\
Send setups to subclasses\
Appearances\
Score restriction\
Platform address\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present,\
wims_name_config_score,wims_name_config_ent

!distribute items subclasses,participants,exercises,documents,teachers\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers


!distribute lines Postes sûrs\
   Style sheet\
   Logo of the class\
   Position of the logo\
   top left corner, top right corner
   Style theme of the class\
   Icones\
   Niveau académique\
   Postes autorisés aux notes\
   Mot de passe d'inscription\
   Mot de passe d'enseignant\
   Limites d'enregistrement d'exercices et d'examens\
   Liens sur une plateforme ou une page web\
   Page background color\
   Menu background color\
   Background image file\
   download a css-style file\
   Dégradé de couleurs des scores (de 0 à 10)\
   into name_secure,name_css,name_logo,name_position_logo,name_logo_side,name_theme,\
   name_theme_icon,name_level,name_security,name_password,name_supass,name_exolog,name_ent,\
  name_background_color,name_menu_color,name_image,name_css_transfer,name_colorscore

!set name_content_style = You can define your class-wide stylesheet here\
<br>(when <tt>$name_css</tt> is on <tt>class</tt>)&nbsp;:

!set name_content_style2=or copy here the css stylesheet

