
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!set title=Configuration and Maintenance
!if $job=arch
 !set title=Backup and Restoration
!endif

!if $job=clean
 !set title=Clean up the class
!endif

!if $job=neighbor
 !set title=Class neighbors
!endif

!if $job=connect
 !set title=Connect to other servers / platforms
!endif

