
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!set title=Configuration and Maintenance
!if $job=arch
 !set title=Backup and Restoration
!endif

!if $job=clean
 !set title=Clean up the class
!endif

!if $job=neighbor
 !set title=Class neighbors
!endif

!if $job=connect
 !set title=Connect to other servers / platforms
!endif

!distribute line Authentification\
My personal preferences\
Resource restrictions\
OEF configuration\
Class neighbors\
Security management\
Selective cleanup\
Rebuild\
Other servers\
Passwords\
Send setups to subclasses\
Appearances\
into wims_name_config_auth,wims_name_config_pref,wims_name_config_restr,wims_name_config_oef,\
wims_name_config_neigh,wims_name_config_secure,wims_name_config_clean,wims_config_refresh,\
wims_name_config_otherserver,wims_name_config_passwd,wims_name_config_propagate,wims_name_config_present

!distribute items subclasses,participants,exercises,documents,teachers\
into wims_name_zones,wims_name_participants,wims_name_exercises,wims_name_docs,wims_name_teachers
