
!set wims_form_method=file
!form reply
<input type=hidden name=up_job value=present>
<p>$table_header
$table_tr<td align=right>Logo of the class
<small>
!href cmd=help&special_parm=config&special_parm2=logo $wims_name_help
 </small>
</td><td><input size=45 name=pr_logo value="$class_logo">
</td></tr>
$table_tr<td align=right>Position of the logo
<small>
!href cmd=help&special_parm=config&special_parm2=logo $wims_name_help
 </small>
</td><td>
!set pr_logoside=$class_logoside
!formselect pr_logoside list left,right prompt top left, top right
 corner of the home pages.
</td></tr>
$table_tr<td align=right>Homepage of participants
<small>
!href cmd=help&special_parm=config&special_parm2=homepage $wims_name_help
 </small>
</td></tr><input size=45 name=pr_homepage value="$class_homepage">
</td></tr>
$table_tr<td align=right>Page background color
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
 </small>
</td></tr><input size=10 name=pr_bgcolor value="$class_bgcolor">
$table_tr<td align=right>Menu background color
<small>
!href cmd=help&special_parm=config&special_parm2=bgcolor $wims_name_help
 </small>
</td></tr><input size=10 name=pr_refcolor value="$class_refcolor">
$table_tr<td align=right>Background image file
<small>
!href cmd=help&special_parm=config&special_parm2=bgimg $wims_name_help
 </small>
</td><td><td><input size=45 name=pr_bgimg value="$class_bgimg">
</td></tr>
$table_tr<td align=right>Style theme of the class
<small>
!href cmd=help&special_parm=config&special_parm2=theme $wims_name_help
 </small>
</td><td>
!set pr_theme=$class_theme
!formselect pr_theme list $themelist
</td></tr>
$table_tr<td align=right>Icones de la classe
<small>
!href cmd=help&special_parm=config&special_parm2=icon $wims_name_help
 </small>
</td><td>
!set pr_theme_icon=$class_theme_icon
!formselect pr_theme_icon list $iconlist
</td></tr>
$table_tr<td align=right>Style sheet (css) of pages
<small>
!href cmd=help&special_parm=config&special_parm2=css $wims_name_help
 </small>
</td><td>
!set pr_css=$class_css
!formselect pr_css list $csslist
$table_tr
<td align=right valign=middle>You can define your class-wide
stylesheet here:
<small>
!href cmd=help&special_parm=config&special_parm2=css $wims_name_help
</small>
<td valign=middle>
download a css-style file
<input type=file name=wims_deposit>
<br>
ou copier ici la feuille de style de la classe&nbsp;<br>
<textarea rows=6 cols=45 name=pr_cssfile>
$cssfile
</textarea>
</td></tr>
$table_hdtr<td align=center colspan=2>
<input type=submit name=save value="$wims_name_tosave">
&nbsp;
<input type=submit name=abandon value="$wims_name_giveup">
</td></tr>
$table_end <p>
</form>


!reset pr_logo, pr_logoside, pr_bgcolor,\
	pr_refcolor, pr_bgimg, pr_theme, pr_css, pr_theme_icon, pr_homepage, pr_cssfile

