
!if $prelogcnt<1
你没有练习要记录.
 !exit
!endif

作业页$logsheet可记录的练习;
!read tabletheme

<p>$table_header
$table_hdtr
<th><small>个数</small></th>
<th><small>步骤</small></th>
<th>分数</th>
<th></th>
<th>标题</th></tr>
!for i=1 to $prelogcnt
 !set l=!word $i of $prelog3
 !set e=!item -1 of $l
 !set c=!recordcnt wimshome/$wims_sesdir/exolog.$logsheet.$e
 !set s=!getdef w_module_score in wimshome/$wims_sesdir/exolog.$logsheet.$e
 !default s=-
 !set V_=!record $e of wimshome/log/classes/$wims_class/sheets/.sheet$logsheet
 !distribute lines $V_ into a,a,a,a,T_,D_
 $table_tr<td align=center>$e</td>
 <td align=center>$c</td>
 <td align=center>$s</td>
 <td><small>
 !href cmd=reply&job=log&logsheet=$logsheet&logexo=$e&checkuser=$wims_user 记录
 </small></td>
 <td>$T_ <small>$D_</small></td>
 </tr>
!next i
$table_end
<p>

