

<center><table border=1 bgcolor=$wims_ref_bgcolor>
<caption>Documento <b>$doc</b></caption>
<tr><th>Titolo<td>$tit
<tr><th>Autore<td>$author
!if @ isin $email
 <tr><th>email<td>
 !mailurl $email
!endif
!if class != $doctype
 <tr><th>Copyright<td>
 !if $copyright iswordof gnu opl
  !if $copyright=gnu
   <a href=fdl.txt>Licenza <em>GNU Free Documentation</em></a>
  !endif
  !if $copyright=opl
   <a href=opl.html>Licenza <em>Open Publication</em></a>
  !endif
 !else
  Tutti i diritti riservati dall'autore
 !endif
!endif
$table_end</div>

