!set wims_module_log=error: $error

<b>Errore!</b>.

!if $error = doc_not_exist
 Il documento richiesto non esiste pi&ugrave;.
 !exit
!endif

!if $error = abuse
 Il documento ha un titolo un po' strano! Sei sicuro?
 <p>
 <b>Attenzione</b>! Potremmo decidere di rifiutarti l'accesso
    al sito.
 !exit
!endif

!if $error = quota
 Non &egrave; pi&ugrave; possibile modificare questo documento perch&eacute;
 si sta raggiungendo il limite di spazio disco.
 !exit
!endif

!if $error = quota_file
 Non &egrave; possibile allegare un file perch&eacute; lo spazio disco
 non &egrave; sufficiente.
 !exit
!endif

!if $error = no_tit
 &Egrave; necessario inserire un titolo!
 !exit
!endif

!if $error = no_author
 &Egrave; necessario inserire un autore!
 !exit
!endif

!if $error = bad_email
 L'indirizzo e-mail inserito non sembrerebbe valido! &Egrave; necessario
 verificarlo.
 !exit
!endif

!if $error = bad_code
 Spiacente, il codice di accesso non &egrave; valido. Non &egrave; 
 possibile leggere/modificare il documento richiesto.
 <p>
 &Egrave; possibile 
 !mailurl $wims_site_manager scrivere al <em>site manager</em>\
Codice di accesso dimenticato
 se si &egrave; dimenticato il codice.
 !exit
!endif

!if $error = unauthorized
 Non &egrave; possibile leggere/modificare il documento richiesto.
 !exit
!endif

!if $error = bad_data
 I dati inseriti non sono corretti. &Egrave; necessario
 verificarli.
 !exit
!endif

!if $error = class_no_right
 Spiacente, la richiesta non &egrave; valida. &Egrave; necessario
 consultare il docente.
 !exit
!endif

!if $error = small_code
 Il codice di accesso &egrave; troppo corto.
 !exit
!endif

!if $error = big_code
 Il codice di accesso &egrave; troppo lungo.
 !exit
!endif

!if $error = code_discord
 <b>Attenzione</b>. I due codici inseriti non corrispondono. 
 Riprova.
 !exit
!endif

!if $error = bad_newcode
 Il codice di accesso contiene caratteri proibiti. &Egrave; necessario
 utilizzare solo caratteri alfanumerici.
 !exit
!endif

!if $error = bad_oldcode
 Il <em>vecchio codice</em> &egrave; errato. Riprova.
 !exit
!endif

!if $error = deposit_fail
 Spiacente, il nome file non &egrave; valido. &Egrave; necessario 
 verificare.
 !exit
!endif

!if $error = deposit_binary
 Il file <tt>$wims_deposit</tt> &egrave; un file binario!
 &Egrave; possibile inserire solo file di testo.
 !exit
!endif

!if $error = src_too_long
 Il blocco <tt>$block</tt> non pu&ograve; essere accettato perch&eacute; 
 supera il limite di $max_blocklen byte. &Egrave; necessario spezzarlo
 in pi&ugrave; blocchi.
 !exit
!endif

!if $error = file_too_long
 Il file LaTeX non pu&ograve; essere accettato perch&eacute; supera
 il limite di $max_texlen byte. &Egrave; necessario spezzarlo
 in pi&ugrave; blocchi.
 !exit
!endif

!if $error = no_latex2html
 Spiacente, non &egrave; possibile inserire file LaTeX perch&egrave;
 questo server non dispone del software necessario (LaTeX2HTML).
 &Egrave; possibile eseguire LaTeX2HTML sul proprio computer locale
 e inserire in questo server il file html risultante.
 !exit
!endif

!msg $error

