!!##language independant
<h1 class="wims_docu_title">$n_properties<br>
--- $tit ---</h1>

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif

!read propform.phtml

!if class != $doctype
 !href cmd=reply&job=recode $n_codechange
.&nbsp;
!endif

!href cmd=reply&job=list $n_blocklist
.
!!!href cmd=reply&job=file $n_file
!!.
 <p>
$n_codedoc: $doc.
$n_freespace1 $quota_total Mega. $n_freespace2 $quota_free Mega.
<p>

