!read adm/title.phtml 2\
Autorizzati alla modifica

Inserire i dati identificativi (id modtool) delle persone cui
date i permessi per modificare questo modulo (oltre a voi stessi).
<b>ATTENZIONE</b> il permesso di modifica è valido per sempre,
non è previsto alcun modo di revocarlo!
<p>
Questo vale solo per moduli pubblicati come "stabili". Se state 
trasferendo il modulo di un altro autore, DOVRESTE inserire qui
l'identificativo di tale autore.

