!read adm/title.phtml 2\
Publication of a module

If you have an account on the module publication center $centralhost,
you can publish your module there. And you can choose to publish it
under development version or under stable version. Your publication will be
visible under the download address
<a href=$downloadsite>$downloadsite</a>.
<p>
In case of stable version, the publication will
automatically propagate through mirrors and
automatic updates to all the WIMS servers over the world.
<p>
Therefore care must be taken to send only well-tested modules for publication.
This is particularly the case when you modify an existing exercise module.
<p>
We all have constant desires to improve our existing works: a more beautiful
presentation page, more features (or in the case of exercises, more cases),
code reorganization, etc.
<p>
However, THINK OF PEOPLE WHO ARE USING YOUR EXERCISES! Your module may
already be inserted into active worksheets and/or important exams. So your new
changes may bring modifications in the middle of the work of the people. At
best, students may be confused by your new features; at worst, an
important exam could be completely broken down by a bug. Needless to say
that your reputation will then take a big hit.
<p>
As a general rule, you should not introduce esthetic modifications or
feature enhancements in the middle of an academic year. Only bug fixes
should be published during that period. Write your enhancements in a
development version of the exercise module (under a test address or in a
different development account), and publish it only during the summer
vacations.
<p>
For your own use or for the use of your own students, you can simply
link your worksheets or exams to the module in your development space.
This moreover offers you a good way to test it before publishing.
<p>
In any case, please remember that for stable modules, you can only
modify those that belong to you. If you want to add a NEW stable module, your
account must have the right to do so, or you should send the module to 
a "<a href=$(downloadsite)parrains>parrain</a>" and ask him/her to
publish it for you (you will then have the right to modify it).
