
Hier kan het forum worden afgesteld.

!form reply
<input type=hidden name=job value=config>
<input type=hidden name=cf_set value=yes>
<ul>
 <p><li>Naam van dit forum&nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <p><li>Omschrijving &nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea>
 <p><li>Wie mag deze berichten lezen&nbsp;?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_readpolicy list alluser,owner prompt \
	alle deelnemers, alleen ikzelf
 !else
  !formselect cf_readpolicy list open,alluser,owner prompt \
	iedereen,deelnemers,\
	alleen ikzelf
 !endif
 <p><li>Wie mag berichten schrijven&nbsp;?
 !if classes/ isin $forum or $forum>9999
  !formselect cf_sendpolicy list alluser,mailuser,owner prompt \
	alle deelnemers,\
	alle deelnemers met een geldig emailadres,\
	alleen ikzelf
 !else
  !formselect cf_sendpolicy list mail,alluser,mailuser,owner prompt \
	iedereen met een geldig emailadres,\
	alle deelnemers,\
	alle deelnemers met een geldig emailadres,\
	alleen ikzelf
 !endif

</ul>
<p><center><input type=submit name=cf_set value="Opslaan">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Annuleren">
</center> <p></form>

