
El servicio gratuito que proporciona WIMS en Internet no va
acompañado por garantía alguna de ninguna clase.
<p>El programa servidor está sujeto a la
<a href=COPYING target=wims_external>GNU General Public Licence</a>. 
El código fuente está disponible para su descarga http en la dirección
<p><center><tt>
<a href=http://wims.unice.fr/download/wims>http://wims.unice.fr/download/wims</a>
</center> <p></tt>
&copy; 1997-2000- Autor del programa servidor:
<a href=mailto:xiao@unice.fr?subject=wims>XIAO, Gang</a> de la
<a href=http://www.unice.fr>Universidad de Niza - Sophia Antipolis</a>.

<p><a href=mailto:ychuang@cc.cktc.edu.tw>Y. C. Huang</a> ha realizado una
traducción al chino en versión Big5 (servidor y módulos) (el
trabajo ha quedado interrumpido).

<p>Un equipo dirigido por 
<a href=mailto:zjchen@math.ecnu.edu.cn>CHEN, Zhijie</a> está efectuando
traducciones al chino en versión simplificada (servidor y módulos).

<p><a href=mailto:marina.cazzola@unimib.it>Marina Cazzola</a> realiza
las traducciones al italiano (de servidor y módulos).

<p>Cada módulo de WIMS tiene su copyright propio, que puede diferir
del copyright del programa servidor. Por favor consulte las páginas
de cada módulo individual para conocer su licencia.

<p>El código fuente de los módulos distribuibles libremente está
disponible en la misma dirección ftp que el programa servidor.

<p>Algunos módulos pueden requerir software comercial para su funcionamiento.
Es responsabilidad del administrador del sitio web comprobar ante los
propietarios de los derechos del software que dicho uso no viola la
política de licencias del software, en caso de que desee instalar ese 
módulo en su servidor.

