
Cuando trabaje con WIMS, a menudo se le pedirá que introduzca expresiones
matemáticas.
<p>
Las expresiones matemáticas pueden teclearse del modo 
habitual: <tt>3*x+5</tt> para escribir
!htmlmath 3x+5
, <tt>sin(pi*x)</tt> para
!htmlmath sin(pi*x)
, <tt>y^3+1</tt> para
!htmlmath y^3+1
, <tt>(x+1)/(y-1)</tt> para
!set ins_align=middle
!instex $$$$ {x+1 \over y-1} $$$$
, etc.
<p>
Además, WIMS contiene un analizador inteligente que puede corregir
``errores'' comunes en las expresiones matemáticas. Por ejemplo, <tt>3x+5</tt>
será corregido como <tt>3*x+5</tt>, <tt>sin x</tt> será corregido a
<tt>sin(x)</tt>, etc. Pero no le recomendamos que confíe demasiado en este
corrector, porque en ocasiones las ambigüedades de las expresiones pueden
llevar a interpretaciones erróneas. Siempre es mejor teclear las expresiones
matemáticas ``correctamente'', aunque sea a menudo laborioso.
<p>
Aquí presentamos una lista de funciones matemáticas y el modo (correcto) 
de introducirlas. WIMS reconoce estas funciones siempre que tengan sentido.
(Algunos módulos pueden aceptar funciones adicionales; por favor consulte
las páginas de ayuda de los módulos.)
<p>
!set x=x
Puede sustituir $x por cualquier subexpresión de la tabla siguiente.
<p>
<center><table border=2 cellspacing=1 cellpadding=3 bgcolor=#d0e0c0>
<tr><th>función<th>descripción<th>cómo teclearla
<tr>
<tr><td>$m_pi
    <td>constante bien conocida<td>
    <tt>pi</tt> ó <tt>Pi</tt> ó <tt>PI
<tr><td><i>e</i><td>base del logaritmo natural<td>
    <tt>e</tt> ó <tt>E</tt>
<tr>
<tr><td>|$x|<td>valor absoluto de $x<td><tt>abs(x)
<tr><td>sign($x)<td>signo de $x:
       <br>&nbsp;=-1 if $x&lt;0<br>&nbsp;=0 if $x=0<br>&nbsp;=1 if $x>0
       <td><tt>sign(x)
<tr><td>
    !instex $$ \sqrt x $$
    <td>raíz cuadrada de $x
    <td><tt>sqrt(x)</tt> ó <tt>x^(1/2)
<tr><td>?<td>el entero más próximo a $x<td><tt>rint(x)
<tr><td>?<td>el entero mayor $m_le$x<td><tt>floor(x)
<tr><td>?<td>el entero menor $m_ge$x<td><tt>ceil(x)
<tr>
<tr><td><i>e<sup>x</sup><td>exponencial<td>
    <tt>exp(x)</tt> o <tt>e^x</tt> o <tt>E^x
<tr><td>ln($x)<td>logaritmo natural<td><tt>log(x)</tt> ó <tt>ln(x)
<tr><td>lg($x)<td>logaritmo de base 10<td><tt>lg(x)</tt> ó <tt>log10(x)
<tr>
<tr><td>sin($x)<td>seno trigonométrico<td><tt>sin(x)
<tr><td>cos($x)<td>coseno trigonométrico<td><tt>cos(x)
<tr><td>tg($x)<td>tangente trigonométrica<td><tt>tan(x)</tt> ó <tt>tg(x)
<tr><td>ctg($x)<td>cotangente trigonométrica<td><tt>cotan(x)</tt> ó <tt>ctg(x)
    </tt> <br> ó <tt>cot(x)
<tr><td>arcsin($x)<td>inversa trigonométrica<td><tt>asin(x)</tt> ó
    <tt>arcsin(x)
<tr><td>arccos($x)<td>inversa trigonométrica<td><tt>acos(x)</tt> ó
    <tt>arccos(x)
<tr><td>arctg($x)<td>inversa trigonométrica<td><tt>atan(x)</tt> ó
    <tt>arctan(x)</tt> <br>ó <tt>arctg(x)
<tr>
<tr><td>sh($x)<td>seno hiperbólico<td><tt>sh(x)</tt> ó <tt>sinh(x)
<tr><td>ch($x)<td>coseno hiperbólico<td><tt>ch(x)</tt> ó <tt>cosh(x)
<tr><td>th($x)<td>tangente hiperbólica<td><tt>th(x)</tt> ó <tt>tanh(x)
<tr><td>Argsh($x)<td>inversa hiperbólica<td><tt>asinh(x)</tt> ó <tt>argsh(x)
    <br>ó <tt>Argsh(x)
<tr><td>Argch($x)<td>inversa hiperbólica<td><tt>acosh(x)</tt> ó <tt>argch(x)
    <br>ó <tt>Argch(x)
<tr><td>Argth($x)<td>inversa hiperbólica<td><tt>atanh(x)</tt> ó <tt>argth(x)
    <br>ó <tt>Argth(x)
<tr><td>max(x,y)<td>El mayor de x e y<td><tt>max(x,y)
<tr><td>min(x,y)<td>El menor de x e y<td><tt>min(x,y)
<tr><td>gcd(x,y)<td>Máximo Común Divisor<td><tt>gcd(x,y)
<tr><td>lcm(x,y)<td>Mínimo Común Múltiplo<td><tt>lcm(x,y)
</table></center>

