2_shape:
3_shape:
abelian_group:
absolute_frequency:
absolute_value:
abstract_algebra:álgebra abstracta
actions:
adaptative_immunity:
addition:
affine_function:
affine_geometry:geometría afín
algebra:álgebra
algebra_geometry:
algebraic_geometry:
algorithmics:
altitude:
american_civilisation:
amino_acid:
analysis:análisis
analytic_geometry:geometría analítica
anesthetic_drug:
angle_bisector:
angles:ángulos
animal_cell:
antibody:
antibody_diversity:
antigen:
antiseptic_drug:
area:
arithmetic:aritmética
arithmetic_sequence:
arts:
asymptote:
bacteria:
barycenter:
basis:
basis_change:
bezout_algorithm:relación de Bezout
bilinear_algebra:
binomial_distribution:
biochemistry:
biology:
body_system:
bonds:
botany:
business_english:
calculation:
calculus:cálculo
cell_biology:
cell_cycle:
cell_death:
cell_differentiation:
cell_division:
characteristic_polynomial:
chemical_synthesis:
chemistry:
chromosome:
cinematics:
circle:círculos
circle_equation:
circles:círculo
civic_education:
class_i:
class_ii:
classical_antiquity:
clonal_selection:
clthm:
code:teoría de la encriptación
coding:teoría de la encriptación
combination:combinación
combinatorics:combinatoria
common_ancestor:
complement_system:
complementary_subspace:
complex_analysis:
complex_number:números complejos
complex_plane:
complexity:
conditional_probability:
cone:
confidence_interval:
congruence:congruencia
conics:cónicas
continued_fraction:fracción continua
continuity:continuidad
continuous_probability_distribution:
contrast_agent:
convergence:
coordinates:coordenada
corporate_finance:
covariance:
critical_point:
cryptology:criptología
crystallography:
cubic_crystal_system:
cumulative_distribution:
cumulative_frequency:
curve_fitting:
curves:curvas
cyclic_code:
cyclic_group:
cytokine:
data_analysis:datos estadísticos
data_gestion:
decimals:decimales
definite_integral:integrales definidas
dendritic_cell:
density:
derivative:derivadas
descriptive_statistics:
determinant:determinante
development_of_lymphocytes:
diabete_drug:
diacritical_mark:
diagonalization:
differentiability:derivabilidad
differential_equation:
differential_equations:ecuaciones diferenciales
differential_geometry:
differential_system:
dimension:
dimensional_analysis:
diophantine_equations:ecuaciones diofantinas
dirac_delta_function:
direction:
discrete_mathematics:
discrete_probability_distribution:
distance:
distance_method:
diversity:
division:división
domain:
dynamic_system:
dynamics:
earth_sciences:Sciences de la terre
ecology:Ecologie
economics:
electrical_engineering:
electricity:Electricité
electronics:Electronique
electrostatics:Electrostatique
elementary_algebra:álgebra elemental
elementary_calculus:
elementary_geometry:
elementary_mathematics:
ellipse:elipse
encryption:
endomorphism_reduction:
energy:
english:
english_vocabulary:
entropy:entropía
equation_systems:
equations:ecuaciones
error_correcting_codes:código corrector de errores
error_detection:detección de errores
estimation:
etymology:
eucaryote:
euclidean_algorithm:división euclidea
euclidean_geometry:geometría euclídea
events:
evolution:
expectation:
exponent:
exponential:
extremum:
factorial:factorial
factorization:factorización
fc_receptor:
field:cuerpos
financial_analysis:
financial_market:
financial_mathematics:
finite_field:
finite_group:
finnish:
flow_cytometry:
fluid_mechanics:
fourier_series:series de Fourier
fourier_transform:transformaciones de Fourier
fraction:fracciones
french:
french_conjugation:
french_grammar:
french_reading:
french_spelling:
french_vocabulary:
function_variation:
functions:funciones
gas_mechanics:
gauss_algorithm:
gaz_mechanics:
gcd_lcm:pgcd ppcm
gene_rearrangement:
genetics:
geography:
geometric_sequence:
geometry:geometría
german:
goldbach:Goldbach
grammar:
graph:
graphing:grafo
group:grupos
group_action:
group_theory:
hamming:distancia de Hamming
hematopoiesis:
histocompatibility:
histogram:
histology:
history:
homography:
homology:
hyperbola:hipérbole
hyperplane:hiperplanos
immunoglobulines:
immunology:
independent_events:
independent_random_variables:
inequalities:desigualdades
inequations:
infection:
inferential_statistics:
infonet:
informatics:
information_theory:
innate_immunity:
inorganic_chemistry:
integers:enteros
integral:integrales
interferon:
intervals:intervalos
ionisation:
isometries:
language:
laplace_transforms:transformaciones de Laplace
leucocyte:
limit:límites
line:líneas
line_equation:
line_integral:
linear_algebra:álgebra lineal
linear_differential_equation:
linear_function:
linear_maps:alicaciones lineales
linear_optimisation:
linear_system:
linear_systems:sistemas lineales
lines:líneas
linguistics:
lissajous:Lissajous
listening:
literal_calculation:
literature:
logarithm:
logic:lógica
lymphocyte:
lymphoid_organ:
macrophage:
magnetism:
management:
maps:aplicaciones
markov:
markov_chains:
math_symbols:
mathematics:
matrix:matrices
maximum_parsimony:
mean:medias
measurement:
mechanics:
medecine:
median:
median_line:
medicinal_chemistry:
methodical_calculation:
methodology:
mhc:
microbe:
misc:miscelánea
mitosis:
modelling:
modular_arithmetic:aritmética modular
molecular_biology:
monophyletic_group:
multiplication:multiplicación
multivariable_function:
music:
mycology:
neutrophil:
nk_cell:
normal_distribution:
normal_vector:
nsaids:
number:números
number_theory:
numbering_system:sistemas de numeración
numeration:
numerical_analysis:
numerical_method:
ode:ODE
operation:
operational_research:
optics:
order:
organelle:
organic_chemistry:
oscillators:
pain_drug:
parabola:parábola
parallelogram:
parametric_curves:curvas paramétricas
parametric_surfaces:
pbsolving:
peptide:
percentage:porcentajes
percents:
perimeter:
permutation:permutación
perpendicular_bisector:
pert:
phagocytosis:
pharmocophore:
phonetics:
phylogenetic_tree:
phylogenetics:
physical_education:
physics:
plane:planos
plane_equation:
plant_cell:
poisson_distribution:
polar_curves:curvas polares
polygons:polígonos
polynomials:polinomios
prealg:pre-álgebra
precalc:pre-cálculo
prediction_interval:
pression:
primes:números primos
primitive:primitivas
priority_rule:
prob_graph:
probability:probabilidad
probability_distribution:distribuciones
probability_generating_function:
probability_space:
probability_statistics:probabilidad-estadística
process_engineering:
programming:
pronunciation:
proportionality:proporcionalidad
pyramid:
quadratic_form:
quantile:
quartile:
quotient_group:
random:
random_variable:
random_vector:
range_kernel:
rank:
rational_number:
reading:
real_function:
real_number:números reales
reasoning:
receptor:
rectangles:rectángulos
recurrence_relation:
regression:
relative_number:
ring:anillos
riskreturn:
root_tree:
roots:raíces
rotation:
ruler_and_compass:regla y compás
rv_convergence:
sampling:
scalar_product:
scheduling:
sciences:
scientific_notation:
selection_of_lymphocytes:
sequence:secuencias
series:series
set_theory:
sets:conjuntos
signal_processing:
signaling_pathway:
signdigits:
similarities:
simplex_method:
simulation:
spatial_skill:
speaking:
spelling:
sports:
spreadsheet:
standard_deviation:
statistical_test:
statistics:estadística
steroid:
stokes_thm:
subst_integral:
subtraction:
surfaces:superficies
symmetric_group:
symmetry:
t_cell_receptor:
tangent:
tangent_plane:
taylor_expansion:expansión de Taylor
taylor_series:series de Taylor
technical_language:
thermodynamics:
time:
titration:
topology:
toxin:
transformation_group:
transition_matrix:
translation:
triangles:triángulos
trigonometric_circle:
trigonometric_functions:
trigonometry:trigonometría
truth_table:
uniform_distribution:
unroot_tree:
vaccine:
variance:
vector_space:espacios vectoriales
vectorial_analysis:
vectorial_geometry:
vectors:vectores
vibration:
virus:
vocabulary:
volume:
weaver:
written_english:
zdomain: Other domains
