
!set wims_form_method=post
!form reply
  $name_intro
 <small>(
 !mailurl $wims_site_manager $name_manager\
$module password
 $name_forget).</small>
 <p><center><table border=0>
 <tr><td align=right>$wims_name_Login: <td><input size=20 name=login value="$auth_login">
 <tr><td align=right>$wims_name_Password: <td><input type=password size=20 name=passwd>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_send">
 </center>
</form>

$name_developer
!mailurl $wims_site_manager $name_manager\
WIMS new developer
$name_identification
<p>
$name_createxo1
!href module=adm/createxo $wims_name_createxo
$name_createxo2.
<p>

!set wims_menu_items=!append line createxo,1,module=adm/createxo\
to $wims_menu_items
