<center>--- $title ---</center>
<p>

!set wims_form_method=file
!form reply
<input type=hidden name=bin_job value=deposit>
Déposer un fichier dans un des répertoires suivants&nbsp;:
!formselect bin_dir list $dir
 / <input type=file name=wims_deposit size=30>
<input type=submit value=Envoyer>
</form> <p>

!if $bcnt>0
 $table_header
 <caption>Fichiers existants</caption>
 $table_hdtr<th>Nom</th><th>&nbsp;</th><th>&nbsp;&nbsp;taille&nbsp;&nbsp;</th></tr>
 !for i=1 to $bcnt
  !set l=!line $i of $bfiles
  !distribute items $l into n_,s_
  $table_tr
  <td><tt>$n_</tt></td> <td>&nbsp;<small>
  <a target=wims_extern href="$devdir/$mod/$n_">Voir</a>&nbsp;
  !href cmd=reply&bin_job=erase&fname=$n_ Effacer
  </small>&nbsp;</td>
  <td align=center>$s_</td>
  </tr>
 !next i
 $table_end
!else
 Aucun fichier déposé dans le module.
!endif

<p>

!reset bin_job

