
<b><font color=red>$wims_name_warning !</font></b> Un module effacé l'est
définitivement. 
!href cmd=reply&jobreq=backup $wims_name_modsave

<p>
<b>Et n'oubliez pas</b> : Une classe virtuelle ou une feuille de
travail qui référencent votre module ne fonctionneront plus si ce
module est effacé.

Etes-vous sûr de vouloir effacer le module
<em><font color=blue>
!module title devel/$auth_login/$mod
</font></em> (<tt>$modreq</tt>)?
<p>
<big><center>
!href cmd=reply&jobreq=del&confirm=yes $wims_name_yes
&nbsp;&nbsp;
!href cmd=reply&jobreq=flist $wims_name_no
</center></big>
