
$title (<tt>$mod</tt>)
<p>
!if $diff=$empty
 Aucune différence n'est trouvée entre la version de développement et la
 version publique du serveur.
!else
 !if $diff=MANY
  Trop de différences existe entre la version de développement et la version
  publique du serveur.
 !else
  Differences entre la version de développement et la version
  publique du serveur&nbsp;:
  <pre>$diff</pre>
 !endif
!endif
<p><hr> <p>

