
<center><h2>Opties voor een lesprogramma</h2></center>
Als een programma <em>verplicht</em> is , worden alle leerlingen in een klas die deze
kursus moeten volgen, automatisch geregistreerd bij deze kursus.
Dus alle cursussen zijn verplicht in alle corresponderende klassen.
<p>
Aan de andere kant, voor een <em>optioneel</em> programma , moeten de studenten
zichzelf aanmelden voor de kursussen. 
<p>
Als de automatische cursusinstallatie van het lesprogramma op "ja" staat, wordt
voor elke klas op dit niveau, de kursus aangemaakt.
Een kursus van dit lesprogramma wordt ook -automatisch- voor elke nieuwe klas op dit niveau aangemaakt. 
<p>
Wanneer de automatische cursusinstallatie van het lesprogramma op "nee" staat, moeten
de cursussen bij dit programma -op dit niveau- handmatig worden aangemaakt. 
