<div class="wims_content">
!set wims_form_method=post
!form reply
  $name_intro
 <span class="small">(
 !mailurl $wims_site_manager $name_manager\
$module password
 $name_forget).</span>
 <fieldset class="property_fields halfwidth blockcenter">
  <div class="field box">
   <label for="login">$wims_name_Login</label>
   <input size="20" name="login" value="$auth_login" id="login" />
  </div>
  <div class="field box">
   <label for="passwd">$wims_name_Password</label>
   <input type="password" size="20" name="passwd" id="passwd" />
  </div>
  <div class="field box">
   <input type="submit" value="$wims_name_send" />
  </div>
 </fieldset>

!formend

<p>
$name_developer
!mailurl $wims_site_manager $name_manager\
WIMS new developer
$name_identification
</p><p>
$name_createxo1
!href module=adm/createxo $wims_name_createxo
$name_createxo2
</p>

!set wims_menu_items=!append line createxo,1,module=adm/createxo\
to $wims_menu_items

</div>
