<div class="wims_content">
!set wims_form_method=post
!form reply
  $name_intro
 <span class="small">(
 !mailurl $wims_site_manager $name_manager\
$module password
 $name_forget).</span>
 <table class="wimsnoborder wimscenter wimsform">
 <tr><td align="right">$wims_name_Login: </td><td><input size="20" name="login" value="$auth_login"/></td></tr>
 <tr><td align="right">$wims_name_Password: </td><td><input type="password" size="20" name="passwd"/></td></tr>
 $table_end
 <p class="wimscenter">
 <input type="submit" value="$wims_name_send"/>
 </p>
!formend

<p>
$name_developer
!mailurl $wims_site_manager $name_manager\
WIMS new developer
$name_identification
</p><p>
$name_createxo1
!href module=adm/createxo $wims_name_createxo
$name_createxo2
</p>

!set wims_menu_items=!append line createxo,1,module=adm/createxo\
to $wims_menu_items

</div>