
!read scripts/getindex $mod
!if $title=$empty
 job=modname
 !changeto modname.proc
!endif

allowchar=/.-_$alnum
fname=!word 1 of $fname
fname=!text select $allowchar in $fname
c=!char 1 of $fname
!if $c=. or $c=/ or .. isin $fname
 !goto badname
!endif
!read files
!if $fname notitemof $files
 :badname
 error=bad_fname
 lastfname=$fname
 job=flist
 !changeto flist.proc
!endif

!if $fname=$empty
 job=flist
 !changeto $job.proc
!endif

