!set size=50
!set swlist=coq, gap, graphviz, m2, maxima, octave, pari, povray, geogebra
!set swname=COQ, Gap, Graphviz, Macaulay 2, Maxima, Octave, PARI/GP, Povray, GeoGebra
!set year=!char 1 to 4 of $wims_now

!if $title=$empty or $modreq=.new
 !set this=$name_this1
!else
 !set this=$name_this2
!endif
!form reply
<input type="hidden" name="jobreq" value="flist" />
<fieldset class="property_fields blockcenter">
      <legend>$name_prop $this</legend>
     <div class="field box">
       <label for="">$wims_name_Address</label>
       <div class="wims_fname">
 !if $title!=$empty and $modreq!=.new
  $modreq&nbsp;
  !set wims_ref_class=wims_button
  !href cmd=reply&jobreq=move&original=devel/$auth_login/$modreq $name_rename
&nbsp;
!set wims_ref_class=wims_button
  !href cmd=reply&jobreq=copy&original=devel/$auth_login/$modreq $name_duplicate
 !else
  !set modreq=.new
  !read scripts/addressform.phtml nook
 !endif
       </div>
     </div>
     <div class="field box">
       <label for="i_title">$wims_name_title</label>
       <input size="$size" name="i_title" id="i_title" value="$i_title" />
     </div>
     <div class="field box">
       <label for="i_description">$wims_name_Description</label>
       <input size="$size" name="i_description" id="i_description" value="$i_description" />
     </div>
     <div class="field box">
       <label for="i_language">$wims_name_Language</label>
 !default i_language=$module_language
      !formselect i_language list $langlist prompt $langname
     </div>
     <div class="field box">
     <label for="i_label">$wims_name_Type</label>
 !set wims_formselect_switch=multiple
 !formcheckbox i_category list exercise,tool,document,recreation,oef,deductio\
   prompt $name_type
     </div>
     <div class="field box">
       <label for="i_domain">$wims_name_Domain</label>
       !set wims_ref_class=wims_button_help float_right
!href cmd=help&special_parm=domain $wims_name_help
       <input size="$size" name="i_domain" id="i_domain" class="multicomplete" value="$i_domain" />
 <script type="text/javascript">
/*<![CDATA[*/
     var tags = 
     !record 0 of wimshome/public_html/bases/sys/domain/domain.json
      ;
      set_multicomplete(tags);
 /*]]>*/
</script>
     </div>
     <div class="field box">
       <label for="i_level">$wims_name_Levels</label>
 !formcheckbox i_level list $levellist
     <br /><span class="small">$name_levellist</span>
     </div>
     <div class="field box">
       <label for="i_scoring">$wims_name_Scoring</label>
 !default i_scoring=no
     !formradio i_scoring list yes,no prompt $wims_name_yes, $wims_name_no
     </div>
     <div class="field box">
       <label for="i_version">$wims_name_Version</label>
       !set wims_ref_class=wims_button_help float_right
 !href cmd=help&special_parm=version $wims_name_help
 !default i_version=1.00
      <input type="text" size="6" name="i_version" id="i_version" value="$i_version" />
       <div class="formHelp">$name_increment</div>
     </div>
     <div class="field box">
       <label for="i_wims_version">$wims_name_Required_WIMS_version</label>
         !set wims_ref_class=wims_button_help float_right
        !href cmd=help&special_parm=wimsversion $wims_name_help
 !default i_wims_version=$wims_version
       <input type="text" size="6" name="i_wims_version" id="i_wims_version" value="$i_wims_version" />&nbsp;

     </div>
     <div class="field box">
       <label for="i_author">$wims_name_Author</label>
       !set wims_ref_class=wims_button_help float_right
    !href cmd=help&special_parm=namewriting $wims_name_help 
 !default i_author=!words2items $auth_name
 !set i_author=!nonempty items $i_author
       <input type="text" size="$size" name="i_author" id="i_author" value="$i_author" />
        <div class="formHelp">
           <span class="tt">$wims_name_firstname,$wims_name_lastname</span>
         </div>
       </div>
     <div class="field box">
       <label for="i_address">$wims_name_auth_email</label>
 !default i_address=$auth_email
       <input type="text" size="$size" name="i_address" id="i_address" value="$i_address" />
     </div>
     <div class="field box">
        <label for="i_maintainer">$wims_name_Maintainer</label>
        !set wims_ref_class=wims_button_help float_right
        !href cmd=help&special_parm=maintainer $wims_name_help
        <input type="text" size="$size" name="i_maintainer" id="i_maintainer" value="$i_maintainer" />
        <div class="formHelp">$wims_name_firstname, $wims_name_lastname</div>
    
     </div>
     <div class="field box">
       <label for="i_maintainer_address">$wims_name_email <br />($wims_name_Maintainer)</label>
       <input type="text" size="$size" name="i_maintainer_address" id="i_maintainer_address" value="$i_maintainer_address" />
     </div>
     <div class="field box">
       <label for="i_translator">$wims_name_Translator</label>
       <input type="text" size="$size" name="i_translator" id="i_translator" value="$i_translator" />
     </div>
     <div class="field box">
       <label for="i_translator_address">$wims_name_tr_email</label>
       <input type="text" size="$size" name="i_translator_address" id="i_translator_address" value="$i_translator_address" />
     </div>
     <div class="field box">
       <label for="i_require">$wims_name_require</label>
 !formcheckbox i_require list $swlist prompt $swname
      </div>
      <div class="field box">
        <label for="i_data">$wims_name_datamodule</label>
        <input size="$size" name="i_data" id="i_data" value="$i_data" />
!set wims_ref_class=wims_button_help float_right
       !href cmd=help&special_parm=datamodule $wims_name_help
      </div>
      <div class="field box">
       <label for="i_keywords">$wims_name_Keywords</label>
!set wims_ref_class=wims_button_help float_right
        !href cmd=help&special_parm=keywords $wims_name_help
       <input size="$size" name="i_keywords" id="i_keywords" value="$i_keywords" />
      </div>
     <div class="field box">
       <label for="i_copyright">$wims_name_Copyright</label>
 !set wims_formselect_switch=
      !formselect i_copyright list gnu prompt GNU General Public License
     </div>
     <div class="field box">
       <label for="i_translation_language">$name_translation_language</label>
       <input size="30px" name="i_translation_language" 
   id="i_translation_language" value="$i_translation_language" /><br />
   !set translation_language=!words2items $i_translation_language
   !set translation_language=!listintersect $translation_language and $langlist
   !if $translation_language !=
     !read translationindex.phtml
   !endif
    </div>
   <div class="wimscenter wimsform">
     <input type="submit" name="inddef" value="$wims_name_tosave" />
&nbsp;&nbsp;
     <input type="submit" value="$wims_name_giveup" />
   </div>
 </fieldset>  
!formend

