!set tr=!words2items $i_translation_language
<script type="text/javascript">
/*<![CDATA[*/
 !for l_ in $tr
  !if $l_ isitemof $langlist
   $$(document).ready(function(){
    $$("#contenu_$l_").hide();
    $$("#button_$l_").click(function () {
        $$("#contenu_$l_").slideToggle("slow");
        $$(this).toggleClass("hiden_$l_"); return false;
    });
  });
  !endif
 !next
/*]]>*/
</script>
<script type="text/css">
/*<![CDATA[*/
!for l_ in $tr
 !if $l_ isitemof $langlist
 .visible_$l_ { display:block; background-color:red;}
 .hide_$l_ {display:none;visibility:hidden;background-color:green;}
 !endif
 !next
/*]]>*/
</script>

!for l_ in $tr
 !if $l_ isitemof $langlist
   <a id="button_$l_" class="visible_$l_ wims_button">$name_prop ($(l_$l_))</a>
   <div id="contenu_$l_" href="#">
    $table_header
     $table_tr
      <th><label for="i_title_$l_">$wims_name_title ($(l_$l_))</label></th>
      <td>
        <input size="$size" name="i_title_$l_" id="i_title_$l_" value="$(i_title_$l_)" />
      </td>
     </tr>
     $table_tr
      <th style="white-space: nowrap"><label for="i_keywords_$l_">$wims_name_Keywords ($(l_$l_))</label></th>
      <td><input size="$size" name="i_keywords_$l_" id="i_keywords_$l_" value="$(i_keywords_$l_)" />
      </td>
     </tr>
     $table_tr<th style="white-space: nowrap"><label for="i_description">$wims_name_Description ($(l_$l_))</label></th>
     <td><input size="$size" name="i_description_$l_" id="i_description_$l_" value="$(i_description_$l_)" />
     </td>
    </tr>
     $table_tr
       <th style="white-space: nowrap"><label for="i_translator_$l_">$wims_name_Translator ($(l_$l_))</label></th>
      <td><input type="text" size="$size" name="i_translator_$l_" id="i_translator_$l_" value="$(i_translator_$l_)" />
      </td>
      </tr>
      $table_tr
        <th style="white-space: nowrap"><label for="i_translator_address_$l_">$wims_name_tr_email ($(l_$l_))</label></th>
        <td><input type="text" size="$size" name="i_translator_address_$l_" id="i_ranslator_address_$l_" value="$(i_translator_address_$l_)" />
        </td>
      </tr>
     </table>
    </div>
  !endif
!next
