
!read adm/css.phtml
!read tabletheme

!header1
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$module_title

!if $error!=$empty
 <div class="wims_alertmsg">
  !read lang/msg.phtml.$moduclass_lang
 </div>
 !goto end
!else
 !if $message!=$empty
  <div class="wims_stdmsg">
   $message
  </div>
 !endif
!endif

!if $job isitemof prop,proc or $job=$empty
 !read prop.phtml
!else
 !read $job.phtml
!endif

:end

!set wims_menu_items=!append line class_home,1,module=home\
to $wims_menu_items

!tail

!reset job
