
!read adm/css.phtml
!read tabletheme

!header1
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$module_title
!if $error!=$empty
 <div>
 !read lang/msg.phtml.$moduclass_lang
 </div>
 !goto end
!endif
 $name_intro.
 !form reply

 !set iniparm1=!replace internal & by $ $ in $iniparm
 !set block=!getopt block in $iniparm1
 <fieldset class="property_fields halfwidth blockcenter">
    <legend>$module_title</legend>
    <div class="field box">
      <label for="title">$wims_name_title</label>
      <input size="50" name="title" value="$title" id="title" />
    </div>
    <div class="field box">
      <label for="status">$wims_name_Status</label>
     !formselect status list 0,1 prompt $wims_name_status
     <input type="hidden" name="job" value="$job" />
  !if $doc>0
   !formcheckbox update list 0 prompt $wims_name_erase
 !endif
    </div>
    <div class="field box">
      <label for="wksheet">$name_wksheet</label>
       !formselect wksheet from 0 to 64
    </div>
    <div class="field box">
      <label for="desc">$wims_name_Description</label>
     <textarea name="desc" rows="5" cols="50" id="desc">$desc</textarea>
    </div>
    <div class="field box">
     <label>Code</label>
      <code>
!replace internal & by &amp; in $dir
 !if $iniparm!=$empty
!replace internal & by &amp; in &$iniparm
 !endif
     </code>
    </div>
  <div class="wimscenter wimsform"><input type="submit" value="$wims_name_tosave" /></div>
  </fieldset>

!formend
!endif

:end

!set wims_menu_items=!append line class_home,1,module=home\
to $wims_menu_items

!tail

!set job=

