!set wims_module_log=error: $error

!if has_empty=$error
 No ha proporcionado toda la información necesaria para la creación de un
 foro de discusión. Por favor, complete sus datos antes de enviarlos.
 !exit
!endif

!if too_short=$error
 El campo de datos ``$(name_$error_subject)'' parece demasiado corto.
 !exit
!endif

!if bad_date=$error
 La fecha de expiración no es correcta.
 !exit
!endif

!if bad_email=$error
 Su dirección de correo electrónico parece no ser válida.
 <p>
 Por favor, tenga en cuenta que la creación del foro de discusión no se
 podrá completar, a menos que envíe SU VERDADERA dirección de correo.
 !exit
!endif

!if anti_date=$error
 El foro de discusión tiene una fecha de expiración anterior a la de hoy. 
 ¡Expirará antes de haber sido creada!
 !exit
!endif

!if existing=$error
 El foro de discusión $forumname parece que ya existe. No puede volver a crear
 el mismo foro.
 !exit
!endif

!if pass_discord=$error
 La contraseña que ha reescrito no se corresponde con la primera. Por
 lo tanto, no se llevará a cabo la creación del foro de discusión; inténtelo
 de nuevo.
 !exit
!endif

!if apparent_password=$error
 ¡Su contraseña aparece entre los campos de título/descripción/propietario del
 foro de discusión!
 Por favor, elija otra contraseña.
 !exit
!endif

!if bad_pass=$error
 Su $(name_$error_subject) contiene caracteres ilegales. <p>
 Por favor, use una contraseña que contenga únicamente dígitos o letras
 sin acentuar, y sin espacios.
 !exit
!endif

!if bad_code=$error
 No introdujo la clave correcta para la creación del foro de discusión. ¿Ha dado
 su dirección de correo correctamente?<p>
 Si quiere jugar con este sitio, tenga en cuenta que sus actividades se
 registran en el servidor.
 !exit
!endif

!if define_fail=$error
 El servidor no ha podido incluir su foro de discusión en la base de datos. Este
 es un error interno del software.
 <p>
 Por favor, informe del problema al
 !mailurl $wims_site_manager administrador del sitio\
[wims] user registration failure
. ¡Gracias!
 !exit
!endif

!if duplicate=$error
 Ha intentado volver a crear un foro de discusión ya existente. ¿Quizás porque ha
 pulsado el botón `Actualizar' de su navegador? En ese caso, su foro de discusión
 $forumname ya se ha creado, y la segunda tentativa de creación se ignorará.
 !exit
!endif

