!set name_title=nombre del foro de discusión
!set name_description=descripción del foro de discusión
!set name_supervisor=nombre del propietario
!set name_email=dirección de correo electrónico
!set name_password=contraseña del foro de discusión
!set name_passsup=contraseña del propietario

!set forumname=<b><font color=green>$title</font></b>

!set months=enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre

