<h3>交互式练习中的随机参数</h3>
<p>
使用随机参数可以使您的练习更加吸引人,
因为每次出来的都是不同的练习.
<p>
例如以下一行命令定义了名为 <font color=blue><b>x1</b></font> 的参数,
它的值是 -10 与 10 间的随机整数 (包括 -10 与 10):
</p>
<pre>
\integer{x1=random(-10..10)}
</pre>
以后在陈述, 回答, 提示与解中都可以用 <b><span class="tt">\x1</span></b> 来调用此随机参数.
也就是说文本中的 <span class="tt">\x1</span> 每次都被不同的随机值所取代. 
这种取代也发生在依赖于 x1 的其他参数的定义中.
<p>
现在假设您在参数定义的栏目中输入了
</p>
<pre>
\integer{x1=random(-10..10)}
\integer{y1=\x1+3}
</pre>
练习的陈述为
<pre>
计算 \x1 与 \y1 的乘积.
</pre>
假定在练习的某个请求中 \x1 被分配一个随机值 <span class="wims_emph">-7</font>.
后一个参数 \y1 将取值 -4, 而且此练习将具有形式 <div class="wimscenter">计算 -7 与 -4 乘积.
</div>
您然后可以定义名为<b>乘积</b>的数值回答的正确解是 
<span class="tt">(\x1)*(\y1)</span>. (注意这里的括号是必要的, 因为替代完全是按字面意义执行的.)
<a id="list"></a>
!if oefparm isitemof $special_parm
 !changeto help/oefparm.phtml
!endif
$table_header
<caption>参数的一些别的例子
!href cmd=help&special_parm=$special_parm,oefparm#list [完整表格]
</caption>
$table_hdtr<th>定义</th><th>效果</th></tr>
$table_tr<td class="tt">\real{x=random(-5..5)}</td>
    <td>\x 是 -5 与 5 间的随机实数</td></tr>
</td></tr>
$table_tr<td class="tt">\real{a=random(-5,-3,0.3,4)}</td>
    <td>\a 是在 -5,-3,0.3,4 之中随机选取的实数</td></tr>
</td></tr>
$table_tr<td class="tt">\complex{z=(1+2*i)^3}</td>
    <td>\z 是复数 (1+2*i)^3</td></tr>
</td></tr>
$table_tr<td class="tt">\text{sign=random(+,-)}</td>
    <td>\sign 是随机符号: + 或 -</td></tr>
</td></tr>
$table_tr<td class="tt">\integer{n=3*exp(\a)}</td>
    <td>\n 是与 3*e<sup>\a</sup> 最接近的整数 (它依赖于 \a 的值)</td></tr>
</td></tr>
$table_tr<td class="tt">\function{f=random<br/> (x^2+1,sin(x),log(x))}</td>
    <td>\f 是 x^2+1, sin(x), 或 log(x) 中随机选取的函数</td></tr>
</td></tr>
$table_tr<td class="tt">\real{a=evalue(x^2+sin(y),x=3,y=4)}</td>
    <td>函数 x^2+sin(y) 对 x=3, y=4 赋值</td></tr>
</td></tr>
$table_tr<td class="tt">\real{r=solve(x^3-3*x+1,x=0..1)}</td>
    <td>\r 是 x^3-3x+1 在 0 与 1 之间的单根</td></tr>
</td></tr>
$table_tr<td class="tt">\function{h=simplify(x^5*y^3*x^2/y)}</td>
    <td>化简表达式: x<sup>7</sup>y<sup>2</sup></td></tr>
</td></tr>
$table_tr<td class="tt">\function{g=diff(sin(x)+cos(y),x)}</td>
    <td>\g 是 sin(x)+cos(y) 关于 x 的导数</td></tr>
</td></tr>
$table_tr<td class="tt">\function{F=int(x^2+3*x+1,x)}</td>
    <td>\F 是 x^2+3*x+1 的不定积分,<br/>
     不保证常数项始终相同</td></tr>
!!</td></tr>
$table_tr<td class="tt">\function{F=int(t^2+3*t+1,t=1..x)}</td>
!!    <td>\F 是 x^2+3*x+1 满足 g(1)=0 的原函数</td></tr>
</td></tr>
$table_tr<td class="tt">\real{a=int(t^2+3*t+1,t=0..1)}</td>
    <td>\a 是 x^2+3*x+1 从 0 到 1 的数值积分</td></tr>
</td></tr>
$table_tr<td class="tt">\text{f=htmlmath(2*x^2+3*x)}</td>
    <td>\f 表示成 html 格式, 如: 2x<sup>2</sup>+3x</td></tr>
</td></tr>
$table_tr<td class="tt">\text{f=texmath(2*x^2+3*x)}</td>
    <td>\f 表示成 TeX 格式.</td></tr>
</td></tr>
$table_tr<td class="tt">\integer{n=items(a,b,c,d,e,f)}</td>
    <td>\n 是表 {a,b,c,d,e,f} 中的元素个数 (这里是 6)</td></tr>
</td></tr>
$table_tr<td class="tt">\text{i=item(3,a,b,c,d,e,f)}</td>
    <td>\i 是表 {a,b,c,d,e,f} 中第 3 个元素 (这里是 c).</td></tr>
</td></tr>
$table_tr<td class="tt">\text{s=shuffle(6)}</td>
    <td>\s 是 6 个整数 1,2,...,6 的表, 次序是随机的.</td></tr>
</td></tr>
$table_tr<td class="tt">\text{s=shuffle(a,b,c,d,e)}</td>
    <td>\s 是字母表 {a,b,c,d,e}, 次序是随机的.</td></tr>
</td></tr>
$table_tr<td class="tt">\matrix{m=1,2,3<br/>4,5,6<br/>7,8,9}</td>
    <td>\m 是 3 行 3 列的矩阵.</td></tr>
</td></tr>
$table_tr<td class="tt">\text{t=asis(How do you do? matrix(1,2,3))}</td>
    <td>保持串的原始形式, 不做变换, 不加条件.</td></tr>

$table_end

条件参数: 您可以写<p>
<span class="tt">\text{ttt=_condition?_def1}</span>或<br/>
<span class="tt">\text{ttt=_condition?_def1:_def2}</span>
<p>
在这个情形, 当条件 <span class="tt">_condition</span> 为真时, <span class="tt">ttt</span> 取值 <span class="tt">_def1</span>.
如果是第二句, 否则取 <span class="tt">_def2</span>.
!href target=wims_mhelp cmd=help&special_parm=if 条件表
<p>
定义与陈述的相对位置是很重要的:
如果变量定义在陈述之后, 那么仅当用户回答了问题后才会给变量赋值.
在这种情形, 定义中可以通过 <span class="tt">\reply1</span>, 
<span class="tt">\reply2</span> 等引用用户的答案. 此变量可用于解答中, 以测试条件或反馈.
</p>


