<center><h3>把答案嵌入陈述中</h3></center>

在html格式下有可能把答案嵌入练习的陈述中.
被嵌入的回答或选择应按通常方式定义.
<p>

例:<ul>
<li><tt>\embed{reply 1}</tt>把第一个自由格式回答插入正文.
<li><tt>\embed{reply 2,10}</tt>把第二个自由格式回答插入正文, 其输入域长度等于10.
<li><tt>\embed{choice 1}</tt>把第一个多重选择插入正文.
</ul>

特殊情形. 如果<tt>reply 1</tt>的类型是<tt>checkbox</tt>,
<tt>click</tt>, <tt>radio</tt>中的一种,
<tt>\embed{reply 1,2}</tt>只插入其中之一(这里是第2个),
或者允许(<tt>点击</tt>), 或者有一个按钮对其标注.
这使得选择的插入具有灵活的结构.
