
<h3>如何在你的练习里写数学公式.</h3>

在html格式里你也可以嵌入数学符号及公式, 以下是提示及解决方法.
<p>
如果你只是插入几个数学符号或希腊字母,
你只要输入 <tt>\</tt>后接符号或希腊字母的英文名(假定你没有在参数定义里使用过这些名字).
例如输入<tt>\pi</tt>可以得到$m_pi,
输入<tt>\le</tt>得到$m_le, <tt>\pm</tt>得到$m_pm, <tt>\rightarrow</tt>得到$m_rightarrow, 等等.
符号名字都采用标准的TeX命令. 下面是
!href target=wims_help module=help/wimsdoc.en&subject=mathfonts#mathfonts 数学符号及其名称表
 (在名称内把<tt>$$m_</tt>换成<tt>\</tt>).
<p>
为插入一个完整的数学公式, 你可以采用一般数学软件的输入方法,
或按WIMS的计算工具里的输入方法. 为使公式显得更漂亮,
你只要把它们用 \( 及 ) 括起来. 例如输入
<tt>\(x^3-3x+cos(2pi*x)^5)</tt>可得到
!insmath x^3-3*x+cos(2pi*x)^5
, 或输入<tt>\(sqrt(x^2+y^2))</tt>可得
!insmath sqrt(x^2+y^2)
. 也可输入<tt>\(integrate(x^2+1)dx)</tt>得 
!insmath integrate(x^2+1)*dx
, 或<tt>\(integrate(exp(x^2+1),x=1..infinity))</tt>得
!insmath integrate(exp(x^2+1),x=1..infinity)
. 为得到和式
!insmath sum(1/n^2,n=1..infinity)
可使用<tt>\(sum(1/n^2,n=1..infinity))</tt>, 乘积式
!insmath product(n/(n+1),n=1..infinity)
 可使用<tt>\(product(n/(n+1),n=1..infinity))</tt>.
<p>
如何输入数学公式的更多信息可见
!href target=wims_help module=help/main&chapter=1&open=1_math#math 这一页
.
<p>
为显示矩阵
!insmath [1,2,3;4,5,6;7,8,9]
, 你应该输入<tt>\([1,2,3;4,5,6;7,8,9])</tt>. 矩阵命令也可以嵌套.
<p>
对于TeX或LaTeX的专家而言, 请注意当软件看到 <tt>\</tt>后接括号时,
它就把后面内容看成TeX的源代码, 并且尝试用TeX来编译. 因此你可以用TeX的方式得到相当复杂的公式.
<p>
如果要在练习里全部使用TeX, 则可选择
!href cmd=help&special_parm=format TeX格式
 (只能用在练习的陈述部分).
