
<b>Esempi di relazioni di vicinato</b>.
<p>
Alcuni esempi tipici di situazioni in cui è utile definire
!href cmd=help&special_parm=neighbor corsi vicini
.
</p><ul>
<li>
Tu (un docente) insegni lo stesso corso a diversi gruppi di studenti.
<br />
È possibile creare un corso virtuale per ogni gruppo e quindi configurano
un rapporto di vicinato per il docente tra ogni coppia di tali corsi. Si
sceglie uno dei corsi come corso &lqduo;principale&rdquo: (questa
distinzione non appare agli studenti) e fare in modo che gli altri
!href cmd=help&special_parm=share condividano
 i materiali didattici da tale corso. In questo modo ogni modifica
effettuata sui materiali in uno qualsiasi dei corsi sarà automaticamente
e immediatamente visibile in tutti gli altri corsi.
</li><li>
Diversi docenti tengono diversi corsi per lo stesso gruppo di studenti.
<br />
Ogni docente crea un corso e tutti i corsi configurano un rapporto di
vicinato per gli studenti. Possono inoltre mettere in condivisione gli
account studenti (tecnicamente, in questo caso occorre configurare il
rapporto di vicinato anche per il docente). Gli studenti si iscrivono
a uno qualsiasi dei corsi e tale registrazione diventa immediatamente
attiva per tutti gli altri corsi. Inoltre, una volta che lo studente
effettua il login in uno dei corsi può passare da un corso all'altro
senza reinserire le credenziali di accesso.
</li><li>
Diversi corsi opzionali a scelta per uno stesso gruppo di studenti.
<br />
Ogni corso ha il suo corrispondente corso virtuale. Si configura un
rapporto di vicinato tra tali corsi, senza la condivisione degli
account studenti. Lo stutende che seleziona i corsi opzionali
iscrivendosi ai corsi virtuali corrispondenti, utilizzando però lo
stesso login e password. Può quindi effettuare il login in uno
qualsiasi dei corsi e passare da un corso all'altro senza dover
reinserire la password.
</li></ul>
