
<center><h3>Verwijder het lesprogramma <em>$class_description</em></h3></center>

<blink><b>WAARSCHUWING</b>.</blink>Deze handeling is niet omkeerbaar! 
En <font color=red><b>alles</b></font>
onder dit programma wordt <font color=red><b>definitief</b></font>
verwijderd : <em>cursussen, activiteiten, cijfers</em>!
<p>
Weet U zeker dat dit programma verwijderd moet worden?
<p><center><font size=+1>

!href cmd=reply&job=$job&del=$del&confirm=yes Ja
&nbsp;&nbsp;
!href cmd=reply&job=level&level=$level Nee

</font></center> <p>

