
<center><h3>Verwijder de test-zone <em>$class_description</em></h3></center>

<font color=red><b>WAARSCHUWING</b>.</font> 
Deze actie is niet reversibel !
En <font color=red><b>alles</b></font>
in de test-zone wordt <font color=red><b>definitief</b></font>
verwijderd!
<p>
Weet U zeker dat deze test-zone verwijderd moet worden?
<p><center><font size="+1">

!href cmd=reply&job=$job&del=$del&confirm=yes&cparent=$parent Ja
&nbsp;&nbsp;
!href cmd=reply&job=$parent Nee

</font></center> <p>

