
!set form_OK=Ok en versturen
!set form_titlename=Titel
!set form_caption=Eigenschappen of het programma
!set title=$class_description
!set sup=$class_Supervisor
!read scripts/progform.phtml
<p><center>
!if $hastest=yes
 Test zone<sup>
 !href cmd=help&special_parm=structure#test help
 </sup>:
 !href module=adm/class/classes&type=authsupervisor&class=$wims_superclass/$prog/0 bezoek
. 
 !href cmd=reply&job=deltest verwijderen
.
!else
 Dit programma heeft nog geen <em>test zone</em><sup>
 !href cmd=help&special_parm=structure#test help
 </sup>.
 !href cmd=reply&job=addtest Installeer een test zone
.
!endif
</center> <p>
!if $coursecnt=0
    Dit programma heeft nog geen cursussen.
 !href cmd=reply&cparent=prog&job=addcourse Voeg&nbsp;een&nbsp;cursus&nbsp;toe
.<sup>
 !href cmd=help&special_parm=structure#course help
 </sup>
!else
 $table_header
 <caption>Geistalleerde cursussen<sup>
 !href cmd=help&special_parm=structure#course help
 </sup> in dit programma
 !href cmd=reply&cparent=prog&job=addcourse Voeg&nbsp;nog&nbsp;een&nbsp;cursus&nbsp;toe
 </small></caption>
 $table_hdtr
 <th>Code</th><th>Naam</th><th>-</th><th>Verantwoordelijke</th>
 <th><small>Deelnemers</small></th>
 </tr>
 !for i=1 to $coursecnt
   !set l=!line $i of $courses
   !distribute items $l into l_,s_,t_,n_
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=course&cparent=prog&course=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=delcourse&cparent=prog&del=$l_ verwijder
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $s_
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
    Niet beschikbaar
   !endif
   !set c=!recordcnt $classdir1/$l_/.userlist
   </td><td align=center>$c</td>
 !next i
 $table_end
!endif
<p>

!if $icoursecnt=0
    Dit programma heeft geen <b>"interklas cursussen"</b>.
 !href cmd=reply&cparent=prog&job=addicourse Maken
.<sup>
 !href cmd=help&special_parm=structure#icourse help
 </sup>
!else
 $table_header
 <caption>Interklas cursussen<sup>
 !href cmd=help&special_parm=structure#icourse help
 </sup> in dit programma
 !href cmd=reply&cparent=prog&job=addicourse Voeg&nbsp;toe
 </small></caption>
 $table_hdtr
 <th>Code</th><th>Naam</th><th>-</th><th>Verantwoordelijke</th>
 <th><small>Deelnemers</small></th>
 </tr>
 !for i=1 to $icoursecnt
   !set l=!line $i of $icourses
   !distribute items $l into l_,s_,t_,n_
   $table_tr<td align=center>$l_</td>
   <td align=center>
   !href cmd=reply&job=icourse&cparent=prog&course=$l_ $t_
   </td><td align=center><small>
    !href cmd=reply&job=delcourse&cparent=prog&del=$l_ verwijder
   </small>
   </td><td align=center>
   !if $s_!=$empty
    !if $s_=supervisor
     $s_
    !else
     !default n_=$s_
     !href cmd=reply&job=modteacher&teacher=$s_ $n_
    !endif
   !else
    Niet beschikbaar
   !endif
   !set c=!recordcnt $classdir1/$l_/.userlist
   </td><td align=center>$c</td>
 !next i
 $table_end
!endif

!if $class_recshare!=$empty
 <p>
 !if $class_recshare=main
 Het lesmateriaal van dit lesprogramma wordt gedeeld door andere lesprogramma's in dit instituut.
 !else
  !set l_=!translate / to , in $class_recshare
  !set shareprog=!defof class_description in $classdir1/$class_recshare/.def
  !set sharelevel=!defof class_description in $classdir1/$(l_[1])/.def
  Dit lesprogramma deelt lesmateriaal van het programma
  <em>$shareprog</em> uit leerniveau <em>$sharelevel</em>
 !endif
!endif


!reset title

