
!set monthnames=gen,feb,mar,abr,mai,jun,jul,ago,set,oct,nov,des
!set name_wroteon=escriure el

!distribute item <i>tema:</i> <b>,</b> into subj1,subj2
!distribute item <hr>,<hr> into body1,body2

!distribute line Llista de missatges per data\
	Llista de missatges per fil\
	Llegir un missatge\
	Escriure un missatge nou\
	Respondre\
	Previsualització del missatge\
	Enviar el missatge\
	Configurar el fòrum\
	Llista per temes\
	into n_list,n_thread,n_read,n_compose,n_follow,n_preview,n_send,n_config,n_subjectlist

!set n_otherforums=Altres fòrums
!set n_welcome=Benvingut
!set n_list_subject_month = Llista de temes del mes de
!set n_email=email
!set n_list_month = Llista de missatges del mes de
!set n_most=el més
!set n_old=recent primer,antic primer
!set n_new=Nou missatge
!set n_archives=Arxius mensuals
!set n_following=Respostes al missatge
!set n_reverse=Invertir l'ordre
!set n_recent=Missatges recents
!set n_erased=suprimit
!set n_send=Enviar el missatge
!set n_edit=Tornar a editar
!set n_emptymsg=El vostre missatge està buit
!set n_listforum=Llista de fòrums en aquest servidor.
!set n_by=per
!set n_newfollow=Nova resposta a
!set n_subject=Tema
!set n_content=Contingut del missatge
!set n_preview=Previsualitzar
!set n_send0=Enviar
!set n_origin=Missatge original
!set n_help=Ajuda
!set n_mathhelp=per escriure fórmules matemàtiques en el vostre missatge.
!set n_yourname=El vostre nom
!set n_cautious=<b>Atenció.</b> No s'acceptarà el vostre missatge si no doneu\
  una adreça electrònica vàlida.
!set n_anonymous=Visitant anònim.
!set n_emptyforum=Aquest fòrum encara està buit.
!set n_nomessage=Cap missatge respon a la seva sol·licitud. Ho sento.
!set n_erasedmsg=Missatge esborrat
!set n_with=amb
!set n_or=o
!set n_without=sense
!set n_citation=citació
!set n_source=Sense format
!set n_format=Amb format
!set n_follow_c=Respondre citant
!set n_follow_nc=Respondre sense citar
!set n_add=El vostre missatge s'ha afegit al fòrum.
!set n_bydate=Per data
!set n_bysubject=Per tema
!set n_prec=Precedent
!set n_first=1ra resposta
!set n_allfollowing=Totes les respostes
!set n_statusask=Aquest fòrum no accepta missatges anònims. El sistema registra l'adreça \
 de correu electrònic per tal d'evitar abusos. <p> \
 Per tal de verificar la validesa de l'adreça de correu electrònic, el servidor us \
 ha enviat una contrasenya a través del correu electrònic. Si us plau, llegiu aquest correu, i copieu el\
 codi aquí:
 !set n_warning=Un missatge ha estat afegit al fòrum. Sisplau, no respongueu aquest correu electrònic.
 !set n_thread=Tot el fil
 !set n_forum=Fòrum
!if $job=compose and $c_prec!=$empty
 !set n_compose=Respondre
!endif

!if $job notwordof read list config
 !set nextline=</b> <br>--- $(n_$job) ---
!endif

!set module_title=$module_title$nextline
!set name_prompt=Unknown activity