
!distribute items $sw,$sw into  sw_1,sw_2

!if $sw=pari
  !set sw_1=gp
!endif
!if $sw=draw
  !set sw_1=flydraw
  !set sw_2=flydraw
!endif
!if $sw=jsxgraph
  !set sw_1=js
!endif

!! a modifier quand il y aura d'autres styles
!default sw_1=flydraw
!read js/edit_area.phtml wims_deposit $sw_1 $swlistjs,js
!if $sw=jsxgraph
 !read js/jsxgraph.phtml
!endif

!header

!if $compute=yes
 !if $swout=$empty
  <em>$SW</em> $name_non_execute.
 !else
  <center>$SW</center> :
  !if $sw=draw
   <img align="middle" src="$swout">
   !goto after
  !endif
  !if $sw=povray
   <img align="middle" src="$swout">
   !goto after
  !endif
  !if $sw=graphviz
   !set swout=!line 1 of $swout
   <img align="middle" src="$swout">
   !goto after
  !endif
  !if $sw=jsxgraph
  <div id="jsxbox" class="box" style="width:400px; height:400px;text-align:center;"></div>
  <script type="text/javascript">
  $swout</script>
    !goto after
   !endif
<pre style="font-weight:bold;font-family:Courier New,Courier,mono;overflow:auto;color:blue;">
$swout
</pre>
 !endif
!else
!read lang/intro.phtml.fr
!endif

:after
!if $msg!=$empty
 <p><hr> <p>
 $name_msg <em>$SW</em> :
<pre style="color:red;font-size:80%">
$msg
</pre>
!endif

<p><hr> <p>
!form reply
<input type="submit" value="$name_execute">

!default sw=sh
!formselect sw list $swlist prompt $swname
$ : 
 &nbsp;
 !set wims_ref_class=wims_button
!href cmd=renew $name_empty
 &nbsp;
 !set wims_ref_class=wims_button_help
!href cmd=help&special_parm=$sw_2 $wims_name_help
&nbsp;
!set src=!reinput $src
!set src=!replace internal &amp;#36; by &#36; in $src
!set src=!replace internal &amp; by & in $src
<textarea id="wims_deposit" wrap="off" name="src">
$src
</textarea>
$(name_remark_$sw)
</form>

!tail

!reset src sw
