!set wims_module_log=error: $error
<b>Erreur : </b>
!goto $error
!exit

:not_supervisor
 Désolé, mais l'opération de préparation / modification du cahier de texte est r&eacute;serv&eacute;e &agrave; l'enseignant de la classe.
!exit

:bad_class
 Etrange, mais je trouve que votre classe n'est pas valide!
!exit

:bad_day
 La date que vous avez saisie n'est pas valide.
!exit

:bad_jday
 La date pour les devoirs n'est pas valide.
!exit

:bad_date
 La date que vous voulez modifier n'existe pas.
!exit

:day_exists
 La date que vous avez saisie existe d&eacute;j&agrave; dans le cahier de texte.
!exit

:same_devoir
 Vous ne pouvez pas saisir deux dates de devoirs identiques.
!exit

:same_devoir2
 Vous ne pouvez pas, &agrave; partir du m&ecirc;me jour, saisir deux fois la m&ecirc;me date de devoir.<br>
 Utiliser plut&ocirc;t le lien 
 !href cmd=new&job=adddate&filename=$jyear$jmonth$jday modifier une date
 .
!exit

:toomany_todo
 Vous avez d&eacute;j&agrave; atteint le nombre maximum de devoirs que l'on peut donner &agrave; cette date.
!exit

:day_dontexist
 La date que vous avez saisie n'est pas valide
!exit