
!if $datacnt<1
这个服务器上没有模块更新的纪录.
此记录从模块公布时开始工作, 并且更新WIMS-3.37f的系统.
 !exit
!endif

$table_header
<caption>服务器的最近模块更新
<a href="$w_/rss/modif.xml"><img src="gifs/rss.png" border=0 alt=rss></a></caption>
$table_hdtr<th>日期</th><th>语言</th><th>标题</th><th>描述</th>
<th>新版本</th>
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!module language $a_
 !set tit=!module title_$lang $a_
 !set desc=!module description_$lang $a_ 
 !if $tit=
  !set tit=!module title $a_
 !endif
 !if $desc=
  !set desc=!module description $a_ 
 !endif
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>
 $desc
 </td><td align=center>$v_</td></tr>
 !reset desc tit
!next i
$table_end
