
!if $datacnt<1
这个服务器上没有模块更新的纪录.
此记录从模块公布时开始工作, 并且更新WIMS-3.37f的系统.
 !exit
!endif

$table_header
<caption>服务器已安装的新模块</caption>
$table_hdtr<th>日期<th>语言<th>标题<th>描述
</tr>
!for i=1 to $datacnt
 !set l=!line $i of $data
 !distribute words $l into d_,a_,v_
 !set la=!char -2,-1 of $a_
 !set tit=!module title $a_
 $table_tr
 <td align=center><small>
 !char 1 to 8 of $d_
 </small></td><td align=center>$la</td><td>
 !href target=wims_test module=$a_ $tit
 </td><td>
 !module description $a_
 </td></th>
!next i
$table_end
