
<html><head>
$wims_html_header
</head><body $wims_htmlbody>
!headmenu

<center>$classname
<h1>$cdt_title</h1>
<font size=+1>Configuration panel</font></center> 

<p><hr width=40%> <p>

Here the parameters you can change :

!form reply
<input type=hidden name=job value=config>
<ul>
 <p><li>Title &nbsp;:<br>
  <input size=60 name=cf_title value="$cf_title">
 <p><li>Description&nbsp;:<br>
  <textarea wrap name=cf_description cols=60 rows=5>$cf_description</textarea></li>
 <p><li>Name of the link in Home page &nbsp; : <input size=60 name=cf_link value="$cdt_link"></li> 
 <p><li>
  !href cmd=renew&job=logfile View 
  the log file of the agenda.</li>
</ul>
<p><center><input type=submit name=cf_set value="Save">
&nbsp;&nbsp;<input type=submit name=cf_abandon value="Cancel">
</center> <p></form>
<p>
 !href cmd=reply&job=home Back
 .
