!read adm/levelname.phtml
!read adm/css.phtml
!read tabletheme
!header1

<!-- Begin regclass/main.phtml -->

<!--!read adm/title.phtml 3\-->
<div class="title_box">
	<h1 class="wims_title">
		<!--WIMS $httpd_HTTP_HOST\-->
		$title
	</h1>
</div>

!if $toomany=yes
 !read lang/toomany.phtml.$modu_lang
 !goto end
!endif

!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$modu_lang
 </div>
 !if $restart!=no
  <p>
   !href module=$module&cmd=reply&step=0 $name_again
  </p>
 !endif
 !goto end
!endif

!if $step=$empty or $step=pre

!!read local.phtml
<div class="wims_content">
 $name_choose

  <p>
   !href cmd=reply&step=0&cltype=0 $wims_name_create_class
  </p>

  !set wims_menu_items=!append line create_class,1,cmd=reply&step=0&cltype=0\
  to $wims_menu_items

  <p>
   !if 2 isitemof $alltypes
    !href cmd=reply&step=0&cltype=2 $wims_name_create_superclass
    !set wims_menu_items=!append line create_superclass,1,cmd=reply&step=0&cltype=2\
    to $wims_menu_items
   !else
    <span class="wims_emph"><strike>$wims_name_create_superclass</strike></span> ($noright).
   !endif
  </p>

  <p>
   !if 4 isitemof $alltypes
    !href cmd=reply&step=0&cltype=4 $wims_name_create_portal
    ($name_expert)
    !set wims_menu_items=!append line create_portal,1,cmd=reply&step=0&cltype=4\
    to $wims_menu_items
   !else
    <span class="wims_emph"><strike>$wims_name_create_portal</strike></span> ($noright).
   !endif
  </p>

  <span class="wims_warning">$wims_name_help</span>:
  !read lang/help.phtml.$modu_lang 1
 </div>
 !goto end

!endif

!if $step=0
 !read lang/help.phtml.$modu_lang 2

 !form reply
 <input type="hidden" name="step" value="1" />

<fieldset class="property_fields">
    <legend></legend>
    <div class="field box">
     <label for="institution">$name_Name_portal</label>
      <div class="formHelp">$name_atmost $instlim $name_characters</div>
  !if $Cltype isin 13
   !let institution=$wims_institutionname
   $institution
  !else
   <input size="$instlim" name="institution" value="$institution" id="institution" maxlength="$instlim" />
  !endif
   </div>

   <div class="field box">
    <label for="description">$wims_name_name $name_classesss</label>
    <div class="formHelp">$name_atmost $desclim $name_characters</div>
    <input size="$desclim" name="description" value="$description" id="description" maxlength="$desclim" />
  </div>
  !if $Cltype notin 24
   !set nblevel=!itemcnt $wims_listlevel
   <div class="field box">
    <label for="level">$wims_name_level $name_classesss</label>
     <select name="level" id="level">
   !for k=1 to $nblevel
    !if $(wims_listlevel[$k])=$level
     <option selected="selected" value="$(wims_listlevel[$k])">$(name_wims_listlevel[$k])</option>
    !else
     <option value="$(wims_listlevel[$k])">$(name_wims_listlevel[$k])</option>
    !endif
    !next k
   </select>
   </div>
 !endif

  !set suplim2 =$[rint($suplim/3)]
  !set emaillim2= $[rint(2*$emaillim/3)]
  <div class="field box">
 !if $Cltype=1
  !let firstname=$wims_firstname
  !let lastname=$wims_lastname
  $wims_name_Supervisor: $wims_firstname $wims_lastname
 !else
  $wims_name_Supervisor
  <label for="firstname">$wims_name_firstname</label>
  <input size="$suplim2" name="firstname" value="$firstname" id="firstname" />
  <label for="lastname">$wims_name_lastname</label>
  <input size="$suplim2" name="lastname" value="$lastname" id="lastname" maxlength="$suplim2" />
 !endif
 </div>

   <div class="field box">
     <label for="email">$wims_name_email</label>
     !if $regpolicy=email
     <div class="formHelp">$name_regpolicy</div>
     !endif
    !if $Cltype=1 and $email!=$empty
      !default email=$email
      $email
    !else
     <input size="$emaillim2" name="email" value="$email" id="email" maxlength="$emaillim2" />
    !endif
   </div>
   !if $Cltype!=1
    <div class="field box">
    <label for="passsup">$wims_name_Password ($name_sup)</label>
    <div class="formHelp">$name_warningpass  $name_help1</div>
    <input size="16" type="password" name="passsup" id="passsup" maxlength="16" />
    </div>
   !endif

   <div class="field box">
     <label for="password">$wims_name_Password ($name_classesss)</label>
     <div class="formHelp">$name_warningpass
      !if $Cltype<2
       $name_help2
     !else
       $name_help3
     !endif
     </div>
    <input size="16" type="password" name="password" id="password" maxlength="16" />
   </div>
   <div class="field box">
   <label for="exp_day">$wims_name_expiration</label>
   <div class="formHelp">$name_help_date</div>
    <select name="exp_day" id="exp_day">
  !for i=1 to 31
   <option value="$i"
   !ifval $i=$exp_day
    selected="selected"
   !endif
   >$i
   </option>
  !next i
  </select>
  <select name="exp_month" id="exp_month">
  !for i=1 to 12
   <option value="$i"
   !ifval $i=$exp_month
    selected="selected"
   !endif
   >
   !item $i of $months
   </option>
  !next i
  </select>
  <select name="exp_year" id="exp_year">
  !for i=$thisyear to $thisyear+1
   <option value="$i"
   !ifval $i=$exp_year
    selected="selected"
   !endif
   >$i
   </option>
  !next i
  </select>
  </div>
   <div class="field box">
     <label for="limit">$name_help_limit</label>
     <div class="formHelp">&lt; $wims_class_user_limit</div>
    !let num=!charcnt $wims_class_user_limit
    <input size="3" name="limit" value="$limit" id="limit" maxlength="$num" />
  </div>

   <div class="field box">
     <label for="secure">$name_secure ($name_sup)</label>
     <div class="formHelp"> $name_host</div>
     !!!default secure=all
     <input size="30" name="secure" value="$secure" id="secure" />
    !reset secure
  !!!if $Cltype<3
  !! $name_optional.
  !!!endif
  </div>
   !if $cltype isin 024
   <div class="field box">
   <label for="cas_auth">$name_cas ($name_optional)</label>
   <div class="formHelp">$name_cas_help</div>
   <input size="30" name="cas_auth" value="$cas_auth" id="cas_auth" />
  !endif
</fieldset>
<div class="wimscenter wimsform">
 <input type="submit" value="$name_continue" />
</div>


!formend

 !goto end
!endif

!if $step=1
!read lang/help.phtml.$modu_lang step1

 !form reply
 <input type="hidden" name="step" value="2" />
 <div class="wimsform">
  !if $Cltype!=1
   <label for="passsup"> $wims_name_Password ($name_sup)</label>
   <input type="password" name="passsup" id="passsup" maxlength="16" />
    <br />
  !endif
  !if $pword!=$empty
   <label for="password">$wims_name_Password ($name_classesss)</label>
   <input type="password" name="password" id="password" maxlength="16" />
   <br />
  !endif
  <p class="wimscenter"><input type="submit" value="$name_continue" /></p>
 </div>

!formend
 !goto end1
!endif

!if $step=2
 !read lang/help.phtml.$modu_lang step2
 !form reply
<div class="wimsform">
 <input type="hidden" name="step" value="3" />
 <p class="wimscenter">
  <label for="typecode">$name_code</label> <input size="12" name="typecode" id="typecode" />
 </p>
 <p><input type="submit" value="$name_continue" /></p>
</div>

!formend
 <span class="wims_warning">$wims_name_warning</span>: <span class="warning_code">$name_warning_code</span>
 !goto end1
!endif

!if $step=3
 !read lang/help.phtml.$modu_lang step3
 !if $Cltype iswordof 0 1
  !let tmp=!positionof item $ilevel in $wims_listlevel
  ($wims_name_level <span class="wims_emph">$(name_wims_listlevel[$tmp])</span>).
 !endif
 !read adm/class/initclass $code,auth
 !if $(class_authidp[1;])=cas
   !set link_=$host_auth/login?service=
 !else
   !set link_=http://$httpd_HTTP_HOST$httpd_SCRIPT_NAME?
 !endif
 <br class="spacer" />
 !read adm/class/links.phtml $code
 !goto end
!endif

:end1

:end
!if $step>=0 and $cmd=reply
 !set wims_menu_items=!append line back2,1,module=$module\
 to $wims_menu_items
!endif

!tail

!set step=

