
<b>Sauvegarder votre classe</b>.
<p>
Vous pouvez télécharger une copie de sauvegarde de la classe dans un fichier
compressé. Si votre classe est très active, vous pouvez aussi faire des
sauvegardes sélectives. Le fichier de sauvegarde peut plus tard être renvoyé
au serveur pour restaurer votre classe ou pour copier certaines ressources
dans une nouvelle classe.
</p><p>
Tous les sources de la classe sont écrits dans des fichiers textes, donc
vous pouvez aussi les lire et les éditer sur votre ordinateur local.
</p><p>
Formats disponibles de fichier compressé&nbsp;:
</p><ul><li><span class="wims_code_words">zip</span>
 qui peut être décompressé et lu sur pratiquement tous les
 systèmes (Windows, Mac, Linux/BSD, etc.), mais la compression n'est pas
 toujours très efficace&nbsp;;
 </li><li><span class="wims_code_words">tgz</span>
 qui peut être décompressé et lu seulement sur les systèmes de
 type Unix (Linux, BSD, Sun OS, etc.), mais a un taux de compression plus
 élevé&nbsp;;
 </li><li><span class="wims_code_words">tar.gz</span>
 qui n'est qu'un synonyme de tgz.
 </li></ul>
<p>
Bien sûr, tous les formats ci-dessus sont acceptés par WIMS pour restauration.
</p>
