<html><head>
!if $cmd=reply
 !set wims_expire=
 $wims_html_header
 <meta http-equiv="expires" content="
 !date -d '1 day'
 ">
!else
 $wims_html_header
!endif
</head><body $wims_htmlbody>
!headmenu

!if $cmd=help and $special_parm=about
 !read about.phtml
 !goto end
!endif

!if $cmd=help
 !read help.phtml
 !goto end
!endif

<h1 class="wims_title">WIMS @ $httpd_HTTP_HOST
<p>$title</h1>
<p><hr> <p>

!if $sitestart=$empty
$name_warning
<p>
 !goto end
!endif

!if $show=yes and $ref!=$empty and $laps>0
!!if $show=yes
 <center>
 !href cmd=resume $wims_name_menuback
 &nbsp;&nbsp;
 !href module=home WIMS home
 </center> <p>
 !read answer.phtml
 !href cmd=resume $wims_name_menuback
 <p>
!else
 !read menu.phtml
!endif
:end
!tail

