!!##language

!set indgood=<font color="green"><b>risposta esatta</b></font>
!set indpartial=<font color="orange"><b>parzialmente corretta</b></font>
!set indbad =<font color="red"><b>risposta errata</b></font>
!set indprec=<font color="orange"><b>risposta imprecisa</b></font>
!set condgood=<font color="green"><b>SI</b></font>
!set condbad =<font color="red"><b>NO</b></font>
!set indsee =<small>si veda più sotto</small>
