
!if empty_out iswordof $error
 Il codice inserito non ha prodotto output. Correggere.
 !if $m_reply_err!=$empty
  <pre><span class="wims_warning">$m_reply_err</span></pre>
 !endif
 !exit
!endif

!! empty_data bad_data double_reply  are in html/msg.phtml.fr - suppress on test

!if bad_answer iswordof $error
 !if illegalname iswordof $test
  Your code contains illegal name <span class="wims_msg alert tt">$illegal_name</span>. Please correct.
  !exit
 !endif
 !if lengthoverflow iswordof $test
  Il codice inserito supera la lunghezza massima inseribile. È
  necessario riscriverlo.
  !exit
 !endif
 La risposta
 <span span class="wims_msg alert tt">$bad_value</span>
 !if unknownword iswordof $test
  !set w=!word 3 of $test
  non è comprensibile: la parola <span class="wims_msg alert tt">$w</span>
  contenuta nella risposta data non ha nulla a che fare con il
  problema posto. Correggere e riproporre la risposta.
  !exit
 !endif
 !if nocompute iswordof $test
  non è accettata: occorre svolgere i conti e
  dare solo il risultato finale.
  !exit
 !endif
 !if nocomputecomplex iswordof $test
   non è accettata.
   Per favore inserisci il numero complesso nella forma cartesiana standard
   <span class="wims_msg alert tt"> a + b i </span>
   dove
   <span class="wims_msg alert tt">a</span>
   e
   <span class="wims_msg alert tt">b</span>
    sono i risultati dei calcoli richiesti (per esempio,
    <span class="wims_msg alert tt"> -1 + 2 i</span> o <span class="wims_msg alert tt"> 1 - 2 i</span>).
   !exit
 !endif
 !if badform iswordof $test
  !if noreduced iswordof $test
   non è una scrittura irriducibile. Riscrivete la frazione ridotta ai minimi termini.
   !exit
  !endif
  non è scritta come richiesto. Riscriverla nella forma corretta.
  !exit
 !endif
 !if notunit iswordof $test
  è solo un numero: occorre specificare l'unità di misura.
  !exit
 !endif
 !if variable iswordof $test
   is not understandable. It should contain extra variables.
   !exit
 !endif
  non è comprensibile. Correggere e riproporre la risposta.
 !exit
!endif

!if bad_exo iswordof $error

 !for j=1 to 50
   !if bad_exo $j isin $error
     !set whichexo=!nosubst (la risposta corretta per la domanda $j \
     <span class="wims_msg alert tt">$(replyname$j)</span>
     non è valida)
     !!goto end_bad
     !break
   !endif
 !next
:end_bad
 A causa di un errore in questo esercizio, è impossibile analizzare
 l'esattezza della risposta data. Spiacente, ma è necessario cambiare
 esercizio.
 <p>
 Per segnalare l'errore è necessario
 !if $email!=$empty
  !mailurl $email contattare direttamente l'autore
 !else
  contattare l'autore
 !endif
 dell'esercizio.
 </p>
 !exit
!endif

!if too_many_print iswordof $error
 Hai richiesto troppe versioni stampabili.
 !exit
!endif

!if chemclick_empty_data iswordof $error
 Non è stato selezionato alcun atomo o legame. Consulta le istruzioni.
 !exit
!endif

!if chemdraw_empty_data iswordof $error
 Non è stata modificata l'applet. Completare la risposta.
 !exit
!endif

!msg $error
