!!##language

 Questo esercizio non prevede una correzione automatica. Se il docente
 ha richiesto di consegnare una risposta per iscritto, ricordatevi di
 stampare questa pagina e di consegnarla assieme allo svolgimento
 dell'esercizio.
!! # La risposta a questo esercizio non va data al computer. Potete 
!! # stampare questa pagina e restituirla al vostro docente assieme alla 
!! # risoluzione dell'esercizio.
