!set name_institution=nombre del centro educativo
!set name_description=nombre de la clase
!set name_supervisor=nombre del profesor
!set name_email=dirección de correo electrónico
!set name_password=contraseña de la clase
!set name_passsup=contraseña del profesor
!set lev_E=educación primaria
!set lev_H=educación secundaria
!set lev_U=universidad
!set lv1=!char 1 of $ilevel
!set lv2=!char 2 of $ilevel
!set name_level=$(lev_$lv1), año $lv2
!set levelid=E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,H7,U1,U2,U3,U4,U5,G,R
!set leveldesc=$levelid
!set nblevel=!itemcnt $levelid

!set classname=<b><font color=green>$description</font></b>\
 de <b><font color=green>$institution</font></b>

!set months=enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=agrupación de clases
    !set name_sup=del profesor-administrador
   !else
    !set name_classe=portal de centro educativo
    !set name_sup=del administrador
   !endif
     !set name_classes= el $name_classe
     !set name_classess= un $name_classe
     !set name_classesss= del $name_classe
     !set name_classessss= El $name_classe
 !else
   !set name_classe=clase
   !set name_classes=la $name_classe
   !set name_classess=una $name_classe
   !set name_classesss= de la $name_classe
   !set name_classessss= La $name_classe
   !set name_sup=del profesor
 !endif

