
!read adm/css.phtml
!header1

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!read names.phtml
!read adm/title.phtml 3\
WIMS à $httpd_HTTP_HOST\
$title

!if $toomany=yes
 !read toomany.phtml
 !goto end
!endif

!if $error!=$empty
 <p>
 !read msg.phtml
 !if $restart!=no
  <p>
  !href module=$module&cmd=reply&step=0 $name_again
 !endif
 <p>
 !goto end
!endif

!if $step=$empty or $step=pre
 $name_choose
 <p>
 !href cmd=reply&step=0&cltype=0 $wims_name_create_class
 !set wims_menu_items=!append line create_class,1,cmd=reply&step=0&cltype=0\
 to $wims_menu_items
 <p>
 !if 2 isitemof $alltypes
  !href cmd=reply&step=0&cltype=2 $wims_name_create_superclass
  !set wims_menu_items=!append line create_superclass,1,cmd=reply&step=0&cltype=2\
 to $wims_menu_items
 !else
  <font color=blue><strike>$wims_name_create_superclass</strike></font> ($noright).
 !endif
 <p>
 !if 4 isitemof $alltypes
  !href cmd=reply&step=0&cltype=4 $wims_name_create_portal
  ($name_expert)
  !set wims_menu_items=!append line create_portal,1,cmd=reply&step=0&cltype=4\
 to $wims_menu_items
 !else
  <font color=blue><strike>$wims_name_create_portal</strike></font> ($noright).
 !endif
 <p>
 !read help.phtml.$lang 1
 !goto end
!endif

!if $step=0
 !read help.phtml.$lang 2
 !form reply
 <input type=hidden name=step value=1>
 <ul>
 <li><label for="institution">$name_Name_portal ($name_atmost $instlim $name_characters) :</label>
 !if $Cltype isin 13
  !default institution=$wims_institutionname
 !endif
  <input size=$instlim name=institution value="$institution" id="institution">
 </li>
 <li><label for="description">$wims_name_name $name_classesss ($name_atmost $desclim $name_characters) :</label>
  <input size=$desclim name=description value="$description" id="description">
 </li>
 
 !if $Cltype notin 24
 <li><label for="level">$wims_name_level $name_classesss </label>
  <select name=level id="level">
   !for k=1 to $nblevel
    !if $(levelid[$k])=$level
     <option selected value=$(levelid[$k])>$(leveldesc[$k])</option>
    !else
     <option value=$(levelid[$k])>$(leveldesc[$k])</option>    
    !endif   
   !next k
  </select>
 </li>
 !endif

 <li><label for="supervisor">$wims_name_firstname  $wims_name_firstname $name_sup $name_classesss</label>
  <input size=$suplim name=supervisor value="$supervisor" id="supervisor">
 </li>

 <li><label for="email">$wims_name_email</label>
  <input size=$emaillim name=email value="$email" id="email">
  !if $regpolicy=email
   <br>(The operation of creation of $name_classesss will not succeed unless you give
   your email address which works right now.)
  !endif
  <p>
 <li><label for="passsup">Choose $name_sup's password:</label>
  <input size=16 type=password name=passsup id="passsup"> <br>
  (between 4 and 16 characters, digits or letters without accent). <br>
  <small>This password will allow you to access the $name_classe as its $name_sup.
  You should be the only person to know it.</small> <p>
 <li><label for="password">Choose password of the $name_classesss:</label>
  <input size=16 type=password name=password id="password"> <br>
  (between 4 and 16 characters, digits or letters without accent). <br>
  <small>The password of the $name_classesss will be required for the register of
    !if $Cltype<2
  participants of the class; you can therefore diffuse it to your
  students. 
    !else
  teachers of the $name_classesss ;
 you must not diffuse it to your students. 
 !endif
 <br>
  A $name_classe without password will be of free access to everybody,
  which is not allowed without the authorization of the site manager.</small> <p>
 <li><label for="exp_day">Expiration date</label>
  <select name=exp_day id="exp_day">
  !for i=1 to 31
   <option value=$i
   !ifval $i=$exp_day
    selected
   !endif
   >$i
  !next i
  </select> <select name=exp_month id="exp_month">
  !for i=1 to 12
   <option value=$i
   !ifval $i=$exp_month
    selected
   !endif
   >
   !item $i of $months
  !next i
  </select> <select name=exp_year id="exp_year">
  !for i=$thisyear to $thisyear+1
   <option value=$i
   !ifval $i=$exp_year
    selected
   !endif
   >$i
  !next i
  </select> <p>
 <li><label for="limit">Limit of the number of participants of the $name_classe:</label>
  <input size=3 name=limit value="$limit" id="limit">
  (The maximum is $wims_class_user_limit.) <p>
 <li><label for="secure">Secured access of the $name_sup:</label>
  !default secure=all
  <input size=30 name=secure value="$secure" id="secure"> <br>
  !reset secure
  <small>Names of hosts from which you will perform sensitive operations on
  the $name_classe. 
  !if $Cltype<3
    Optional.
  !endif 
  </small> <br>
 </li>
 </ul>
 <center><input type=submit value="$name_continue"></center>
 </form>

 !goto end
!endif

!if $step=1
 Hello, $supervisor!<p>
 You are creating a  $name_classe $classname on the WIMS site $httpd_HTTP_HOST,
 !if $Cltype iswordof 0 1
 of level 
 ``<b><font color=green>$name_level</font></b>'',
 !endif
 limited to $ilimit participants. Registration to this class is
 !if $pword!=$empty
  protected by the password of the $name_classesss.
 !else
  open to everybody on the internet (are you sure? Please notice that
  the site manager may refuse and destroy unauthorized open classes!).
 !endif
 This class will expire on $exp_month-$exp_day-$exp_year. <p>
 If you find an error in the above informations, please
 !href module=$module&cmd=reply&step=0 correct it.
 <p>Otherwise, in order to verify the exactness of your passwords,
 please type them again. <p>
 !form reply
 <input type=hidden name=step value=2>
<label for="passsup"> $wims_name_Password ($name_sup) :</label>
 <input type=password name=passsup id=passsup> <p>
 !if $pword!=$empty
 <label for="password">$wims_name_Password ($name_classesss)</label>
  <input type=password name=password id=password> <p>
 !endif
 <center><input type=submit value="$name_continue"></center>
 </form>
 !goto end1
!endif

!if $step=2
 !read help.phtml.$lang step2
 !form reply
 <input type=hidden name=step value=3>
 <center><label for="typecode">Code of the class: <input size=12 name=typecode id="typecode"></label>
 <p><input type=submit value="$name_continue"></center>
 </form>
 <b>Attention</b> This code is only used once here. It cannot be used to
 connect to the $name_classe!
 <p>
 !goto end1
!endif

!if $step=3
 Hello, $supervisor!<p>
 Your $name_classe $classname is now created. Congratulations, and enjoy!<p>
 The number of participants is limited to $ilimit participants (including you)
  !if $Cltype iswordof 0 1
  , of level <font color=green>$name_level</font>.
 !endif
 <p>
 !read links.phtml
 !goto end
!endif

:end1
<p>
!href module=$module&cmd=reply&step=0 $name_comeback
:end
!tail

!set step=

