!set name_institution=name of the institution
!set name_description=name of the class
!set name_supervisor=name of the supervisor
!set name_email=email address
!set name_password=password of the class
!set name_passsup=supervisor's password
!set lev_E=elementary school
!set lev_H=high school
!set lev_U=university
!set lv1=!char 1 of $ilevel
!set lv2=!char 2 of $ilevel
!set name_level=$(lev_$lv1), year $lv2

!set classname=<b><font color=green>$description</font></b>\
 of <b><font color=green>$institution</font></b>

!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=group of classes
    !set name_sup=teacher-supervisor
   !else
    !set name_classe=portal 
    !set name_sup=supervisor
   !endif
     !set name_classes= the $name_classe
     !set name_classess= a $name_classe
     !set name_classesss= $name_classe
     !set name_classessss= The $name_classe
 !else
   !set name_classe=class
   !set name_classes=the $name_classe
   !set name_classess=a $name_classe
   !set name_classesss= $name_classe
   !set name_classessss= The $name_classe
   !set name_sup=teacher
 !endif


