!set name_institution=name of the institution
!set name_description=name of the class
!set name_supervisor=name of the supervisor
!set name_email=email address
!set name_password=password of the class
!set name_passsup=supervisor's password
!set lev_E=elementary school
!set lev_H=high school
!set lev_U=university
!set lv1=!char 1 of $ilevel
!set lv2=!char 2 of $ilevel
!set name_level=$(lev_$lv1), year $lv2
!set levelid=E1 E2 E3 E4 E5 E6 H1 H2 H3 H4 H5 H6 U1 U2 U3 U4 U5 G R
!set leveldesc=$levelid
!set nblevel=!itemcnt $levelid

!set classname=<b><font color=green>$description</font></b>\
 of <b><font color=green>$institution</font></b>

!set months=Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec

!if $Cltype iswordof 2 4
   !if $Cltype=2
    !set name_classe=group of classes
    !set name_sup=teacher-supervisor
   !else
    !set name_classe=portal 
    !set name_sup=supervisor
   !endif
     !set name_classes= the $name_classe
     !set name_classess= a $name_classe
     !set name_classesss= $name_classe
     !set name_classessss= The $name_classe
 !else
   !set name_classe=class
   !set name_classes=the $name_classe
   !set name_classess=a $name_classe
   !set name_classesss= $name_classe
   !set name_classessss= The $name_classe
   !set name_sup=teacher
 !endif

!distribute lines Continue\
  Restart the operation.\
  Creation of $name_classess\
  Nom de l'établissement\
  at most\
  at least\
  For experts\
  characters\
  Back to the beginning of the operation.\
  Choose the type of virtual class you want to create.\
 into name_continue,name_again,title,name_Name_portal,name_atmost,name_atleast,name_expert,\
   name_characters,name_comeback,name_choose

!if $regpolicy=file
  !set noright=You don't have the right to do so.
 !else
  !set noright=Only the site manager can do it.
 !endif