
L'exercici <em>$deltitle</em> ha estat esborrat de la llista d'exercicis de la
teva classe.
<p>
En cas que ho hagis esborrat per error i vulguis recuperar-ho, aquí tens el
codi de l'exercici, desa'l com a mesura de seguretat i si més endavant vols
 reinstalar-lo copia'l a 
!href module=adm/createxo&mode=raw Createxo.
<p>
<pre>
$deleted
</pre>

<p><center>
!href module=home Inici de la classe.
</center> <p>

