
!set wims_form_method=file
!form reply
<input type=hidden name=level value=3>

!if $existing=$empty
 Estàs al mode fitxer per crear un exercici.
 En aquest mode, pots enviar un fitxer local de codi OEF al servidor.
 Per la creació del primer exercici, és preferible el
 !href cmd=reply&mode=normal mode guiat
. També pots utilitzar el
 !href cmd=reply&mode=raw mode pur
 per editar en línia.
 <p>
 Fitxer de codi del teu exercici:
 <input type=file name=wims_deposit>
 <p><center>
<input type=submit value="Envia el fitxer"></center>
</form>

