
!set wims_form_method=file
!form reply
<input type=hidden name=level value=3>

!if $existing=$empty
 Esteu al mode fitxer per crear un exercici.
 En aquest mode, podeu enviar al servidor el codi OEF d'un fitxer local.
 Per la creació del primer exercici, és preferible el
 !href cmd=reply&mode=normal mode guiat
. També podeu utilitzar el
 !href cmd=reply&mode=raw mode pur
 per editar en línia.
 <p>
 Codi del vostre exercici :
 <input type=file name=wims_deposit>
 <p><center>
<input type=submit value="Enviar el fitxer"></center>
</form>

