!if $wims_developer!=$empty and ..devel/ isin ..$catmodule
 !if $reg1=success
  L'exercici <tt>$existing.oef</tt> s'ha actualitzat al mòdul 
  <tt>$catmodule</tt>
  amb èxit.
 !else
  Ha fallat l'actualització de l'exercici <tt>$existing</tt> al mòdul 
  <tt>$catmodule</tt>.
  <pre>$wims_exec_error</pre>
 !endif
 <p>
 !href cmd=reply&level=3 Tornar a l'etapa precedent.
 !exit
!endif

!if $wims_user=$empty
 !read level5.phtml
!else
 !if $already!=yes
  L'exercici s'ha instal·lat amb èxit.
 !else
  Hem trobat un exercici idèntic a la vostra classe. Així doncs, aquest segon enregistrament s'ignora. <p>
 !endif
 Aquest exercici serà accessible
 únicament als participants de la vostra classe i només si el poses en un full de treball.
 <p>
 !if $wims_user!=supervisor
  Ara podeu
  !href module=classes/$lang&special_parm=.nocache. consultar els exercicis de la classe.
 !else
  Ara podeu&nbsp;:
  <ul>
  <li><p>
  !href module=classes/$lang&special_parm=.nocache. consultar els exercicis de la classe.
  (i eventualment posar-los als vostres fulls de treball.)
  <li><p>
  !href cmd=reply&level=3&success=1 Tornar a l'etapa precedent.
  </ul>
 !endif
!endif

