
El teu exercici ha estat registrat satisfactòriment en aquest servidor. Agraïm
la teua contribució, en el nom de tots aquells que en trauran profit.
<p>
L'administrador d'aquest lloc verificarà el teu exercici, i decidirà si
posar-lo o no a la categoria corresponent.
Calen uns dies.
<p><center>
!href module=incoming Mòdul que conté temporalment el teu exercici.
<p>
!href cmd=reply&level=$[$level-1] Tornar a l'estat anterior.
</center>


