
Benvingut a aquesta pàgina que t'ajudarà a crear en mode guiat els teus
!if $wims_user!=supervisor
 exercicis interactius.
!else
 exercicis interactius per la classe <font color=blue>
 $wims_classname</font> de <font color=blue>$wims_institutionname</font>.
!endif

A Createxo tens a la teua disposició diferents eines de creació.
Et permetran crear exercicis en format 
!href cmd=help&special_parm=oef OEF
.
<ol>
<li>Diferents modes guiats per crear un exercici amb l'ajuda d'un formulari : 
   <ul><li>
      exercicis lliures en 
     !href cmd=reply&mode=normal&level=1 $name_normal
 ;</li><li>
    diferents models d'exercices que es poden modificar estan disponibles a
    !href cmd=reply&mode=model&level=1 $name_model
.</li>
   </ul>
<li> Un mode lliure (no guiat) de crear exercicis amb dues possibilitats :
<ul><li>
!href cmd=reply&rawinp=yes&level=1 $name_raw
, per escriure el  codi font d'un exercici 
directament en línia ;
</li><li>
!href cmd=reply&mode=file&level=1 $name_file
, per enviar un fitxer amb el codi font de l'exercici que prèviament 
has creat amb l'editor de text del teu ordinador.
</li>
</ul>
</ol>

Altres eines disponibles.
<ul><li>Eines com
  !href module=adm/auth/confia2qcm Confia2qcm
, 
!href module=adm/auth/createqcm Createqcm
 ajuden a la creació de dos tipus de QCM (Qüestionaris de múltiples opcions) preformatats.
<li>    
!href module=adm/modtool $wims_name_modtool 
 permet crear exercicis amb molta llibertat però també organitzar 
els vostres exercicis OEF o els vostres documents (cal un compte de desenvolupador).
 Aquesta eina és el mitjà per publicar més endavant els vostres exercicis o documents i que es puguin utilitzar fora de la vostra classe.
<li>
!href module=adm/quicktool $wims_name_quicktool
 és una eina per crear exercicis per l'aprenentatge de llengües i literatura. Pot ser usat per crear diferents exercicis de tipus OEF  (GAP, QCM, SELECTWORD, ...) en mode guiat; 
admet exercicis per etapes, exercicis on l'alumne pot fer diferents intents, rebre ajudes progressives.
Es permet utilitzar els bancs d'enregistrament d'audio del projecte 
<a target="wims_external" href="http://shtooka.net">Shtooka</a>.
L'utilització de Quicktool exigeix de moment tenir un compte de desenvolupador.
<li>     
!href module=adm/latex2wims $wims_name_latex2wims
 permet traduir al format WIMS els documents escrits en latex. Té en  compte
 les parts interactives fetes en l'entorn <tt>wims</tt>. 
 Requereix un compte de desenvolupador. 
</li></ul>
