!form reply name=replyform id=replyform
<input type=hidden name=level value=3>

!if $existing=$empty
 Esteu al mode pur de creació d'exercicis.
 !if $modeltest=yes
  Atès que aquest exercici està basat en un mòdel estàndard, proveu el
  !href cmd=reply&mode=model&level=2 mode guiat
.
  !href cmd=reply&mode=none&level=0 Abandonar
.
 !else
  Aquest mode està reservat als experts, o per enregistrar un exercici del qual tingueu el fitxer de codi. Utilitzeu preferiblement el
  !href cmd=reply&mode=normal&level=1 mode guiat
  per crear els vostres primers exercicis.
 <p>
  Entreu el codi sencer (
  !href target=wims_mhelp cmd=help&special_parm=oef format OEF
  ) de l'exercici&nbsp;:
  (per enregistrar un fitxer de codi existent, copieu el fitxer a la finestra.)
  !href target=wims_test module=tool/directexec&cmd=new Provar el script
.
 !endif
!else
 Aquest és el codi d'un exercici
 !if $catmodule=$empty
  existent a la vostra classe.
  Podeu modificar-lo a la finestra d'aquí baix.
 !else
  públic que voleu importar.
  Podeu modificar-lo a la finestra d'aquí baix, abans de posar-lo a la classe.
 !endif
 !if $modeltest=yes
  Atès que aquest exercici està basat en un mòdel estàndard, proveu el
  !href cmd=reply&mode=model&level=2 mode guiat
.
  !href cmd=reply&mode=none&level=0 Abandonar
.
 !endif
!endif

<a name=textarea></a>
[
<a href="#"
onclick="document.forms['replyform'].wims_deposit.value=''">Buidar</a>
] [
!href cmd=resume Reiniciar
].

<p><center>
!mexec textarea.sh
<p><input type=submit value="Enviar el codi"></center>
</form>

