<html><head>
$wims_html_header
</head><body $wims_htmlbody>
!headmenu

!!if $cmd=help
 !!read help.phtml
 !!goto end
!!endif

!read names.phtml
<center><h1>WIMS 位于 $httpd_HTTP_HOST
<p>
信息板用户注册
</h1></center> <p><hr width="50%"> <p>

!if $error!=$empty
 <p>
 !read msg.phtml
 <p>
 !goto end1
!endif

!if $forumcnt=0
本站目前没有信息板. 对不起, 请以后再来!
 !goto end
!endif

!set forumname=<b><font color=green>$title</font></b>

!if $password!=$empty and $passverify=$empty and $mailverif=$empty
 $forumname 是受密码保护的. 你需要输入密码才能注册.
 !form reply
 <input type=hidden name=step value=1>
 <center> <p>密码:
 <input type=password name=forumpass>
 <p>
 <input type=submit value="发送密码">
 </center></form> <p>
 <b>说明</b>. 如果此信息板的板主($supervisor)允许你进入,
你应该能从他那里得到密码.
 (
 !mailurl $smail 写信给板主
 )
 !goto end1
!endif

!if $step=$empty or $step<2
为了注册到$forumname,
请填写以下信息.
 <ul>
 !form reply
 <input type=hidden name=step value=2>
 <li>你的姓 <input size=20 name=lastn value="$lastn">
  和名 <input size=20 name=firstn value="$firstn">
  <p>
 <li>选取登录名:
  <input size=16 name=login value="$login"> <br>
这是你以后登录信息板的名字. 请选择4至16个字符的词(数字及英文字母).
  <p>
 <li>密码:
  <input type=password size=16 name=pass> <br>
密码必须含4至16个字符(数字及英文字母).
  <p>
 !if $mailverif=$empty
  <li>你的电邮地址(可选):<br>
 !else
  <li>你的电邮地址:<br>
 !endif
  <input size=60 name=email value="$email">
  <p>
 <center><input type=submit value="注册"></center>
 </form></ul>
 !goto end1
!endif

!if $step=2
你好, $lastn$firstn!<p>
你已经注册成为 $forumname 的参加者,
登录名为&nbsp;
 ``<tt><b><font color=green>$login</font></b></tt>''. <p>
 !if $email=$empty
你没有给出有效的电邮地址. <p>
 !else
你的电邮地址: <tt>$email</tt> <p>
 !endif
为了检验你的密码的精确性, 请再输入一次:
 !form reply
 <input type=hidden name=step value=3>
 <p><center><input type=password size=16 name=pass2>
 <p><input type=submit value="发送密码"></center>
 </form> <p>
 !goto end1
!endif

!if $step=3
你好,  $lastn$firstn!<p>
 !if $mailverif=yes
  !set mailverif=next
  $forumname 不允许匿名注册. 它用你的电邮地址证实你的身份(以防止滥用).
  <p>
为了验证你的电邮地址的有效性, 服务器将用电邮发送一个密码.
请读取此密码, 并把它输入在下面:
  !form reply
  <input type=hidden name=step value=3>
  <p><center><input size=10 name=vericode>
  <input type=submit value=发送></form>
  <p>
  !href module=adm/forum/forum 放弃操作
  </center> <p>
  !goto end1
 !else
欢迎来到$forumname.
你现在是本信息板的参加者, 登录名为
  ``<b><font color=green>$login</font></b>''. <p>
你现在可以
  !href module=adm/forum/forum&forum=$forum&type=authuser 登录
到信息板.
  !goto end
 !endif
!endif

:end1
<p>
!href module=adm/forum/forum&type=list 信息板表
:end
!tail

!set step=

