!if robot isin $session
 !exit
!endif

!distribute item WIMS,Corso,Documenti,Livello superiore,Prec.,Succ,History,Aggiorna,\
	Versione interattiva,Versione stampabile,\
	Torna indietro,Help on line,Informazioni\
	into doch_wims,doch_class,doch_docs,doch_up,\
	doch_prev,doch_next,doch_hist,doch_reload,\
	doch_interactive,doch_printable,\
	doch_back,doch_help,doch_about

!set wims_headertype=doc
!headmenu
