!nocache
!if $error!=$empty
 !read docu/$en/msg.phtml
 <p>
 !exit
!endif

<center><h1>$tit</h1></center>

!if $titb=$empty
 <p>
 Il blocco <tt>$block</tt> non è ancora stato creato.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Questa pagina non è ancora pronta per la pubblicazione. Riprova più
 tardi!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Questa pagina non è più disponibile. Spiacente!
 <p>
 !exit
!endif

:newblock
<a name=$block>
<h3>$titb</h3>

!read $docdir/$doc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $docdir/$doc/$block.def
 <p>
 !goto newblock
!endif

</div><div class=wimstail>
<p><hr>
<table width=100% border=0 cellspan=0 cellpadding=1>
<tr><td align=left nowrap><small>
A cura di
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
<td align=right><small>
!href cmd=reply&job=read&doc=$doc&block=$startblock Versione interattiva
!if $wims_user=supervisor and $sheetdata!=$empty
 <tr><td align=left nowrap>
 <small>Ultima modifica: $datm
 <td align=right><small>
 !href cmd=reply&job=exosource&block=$startblock Codice sorgente degli esercizi contenuti nella pagina
 </small>
!else
 <tr><td align=left colspan=2 nowrap>
 <small>Ultima modifica: $datm
!endif
</table>

