!nocache
!if $error!=$empty
 !read docu/it/msg.phtml
 <p>
 !exit
!endif

<h1 class="wims_docu_title">$tit</h1>

!if $titb=$empty
 <p>
 Il blocco <tt>$block</tt> non è ancora stato creato.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Questa pagina non è ancora pronta per la pubblicazione. Riprova più
 tardi!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 Questa pagina non è più disponibile. Spiacente!
 <p>
 !exit
!endif

:newblock
<a name=$block></a>
<h3>$titb</h3>

!read $docdir/$doc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $docdir/$doc/$block.def
 <p>
 !goto newblock
!endif

