
<a name=ans>
!if $badask=yes
 !if $comment!=$empty
 Je verzoek om $basname is incorrect: 
  $comment 
 !else
  Je verzoek om $basname is incorrect, omdat deze informatie nergens op slaat..
 !endif
 <p>
 Je activiteiten m.b.t. deze module worden hierdoor beindigd.
 !exit
!endif

!if $speculate=yes
Je hebt niet genoeg informatie om dit probleem op te lossen.
Hierdoor kan je antwoord niet geldig zijn en dus onjuist.
 !exit
!else
 !read $deffile ans
!endif

!if $solution!=$empty and ($presentsol>1 or ($presentsol=1 and $thisscore<0.7))
 <p><b>Oplossing.</b> $solution
!endif

<p>
!if $gotcnt>$minask
Je zou deze som kunnen hebben opgelost door maar  $minask
 !if $minask>1
  vragen te stellen.
 !else
  vraag te stellen.
 !endif
!endif

!if $uselesscnt>0
De volgende info is onbruikbaar: <b>$useless</b>.
!endif

