!!##!! language independant
!if $job2=print and $job isitemof todo,work
 !changeto print$job.phtml
!endif
!if $job=modpalier
 !let js=!record 0 of js/chooselist.js
 !let wims_html_header=!append line $js to $wims_html_header
!endif
!header1
<script type="text/javascript" src="scripts/js/wz_tooltip.js" language="Javascript"></script>\

!if $cmd=help
 !changeto help.phtml
!endif

!headmenu

!if $error=bad_class
 !read lang/msg.phtml.$moduclass_lang $error
 !tail
 !exit
!endif

!read $job.phtml

!if $wims_user=supervisor
 !if config notin $job
  !set wims_menu_items=!append line config,1,cmd=renew&job=config to $wims_menu_items
 !endif
 !if userlist notin $job
  !set wims_menu_items=!append line cls_livret,1,cmd=renew&job=userlist to $wims_menu_items
 !endif
 !set wims_menu_items=!append line add_competence,1,cmd=renew&job=addcomp&comp=$[$livret_nbcomp+1] to $wims_menu_items
!endif
!set wims_menu_items=!append line refresh,1,cmd=reply\
,0,\
to $wims_menu_items
!if $wims_user=supervisor
  !set wims_menu_items=!append line part_list,1,cmd=new&module=adm/class/userlist\
to $wims_menu_items
!else
  !set wims_menu_items=!append line myscore,1,cmd=new&module=adm/class/userlist\
to $wims_menu_items
!endif


!endif

!tail

