!read adm/class/classname.phtmlw $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$livret_title\
$name_job


!form reply
<p>
$name_title_palier : <input type="text" name="cf_title" value="$name_palier" size="40" /><br />
$name_cocher
</p>
 !let echoose=$eold
 !read adm/class/transfertexo.phtml
 <div class="wimscenter wimsform"><input type=submit value="$wims_name_tosave" name="cf_set" /></div>

!formend

!set wims_menu_items=!append line back2,1,cmd=reply&job=home\
to $wims_menu_items
!reset eold,echoose