!!##!! language independant
!read adm/title.phtml 1\
$wims_classname - $wims_institutionname\
$livret_title

!if $usercnt==0
 $name_noyetparticipant
!! !exit
!endif
!if $livret_nbcomp==0
 $name_no_competence
 !exit
!endif
!default note=0
<p>
$table_header
 $table_hdtr
   <th rowspan=2>$wims_name_lastname, $wims_name_firstname</th>
   !for k=1 to $livret_nbcomp
    <th valign="middle" colspan=$(nbpalier_$k)>
     !set wims_ref_title=$(title_$k)
     !href cmd=renew&job=addcomp&comp=$k $(name_icompetence)$k
    </th>
    !if $k<$livret_nbcomp
     <td width="3" rowspan="$[2+$usercnt]"></td>
    !endif
   !next k
 </tr>
 $table_hdtr
  !for k=1 to $livret_nbcomp
   !for j=1 to $(nbpalier_$k)
    !let desc=!record $j of $livret_dir/.comp$k
    !let desc=!line 1 of $desc
    !let desc=!replace internal ' by \' in $desc
    <th valign="middle">
    <a onmouseover="Tip('$desc',$tooltip_parm)">$(name_ipalier)$j</a></th>
   !next j
  !next k
 </tr>    
 !for i=1 to $usercnt
  !set uu=!line $i of $userlist
  $table_tr
   <td>
    !href cmd=reply&job=user&user=$(uu[1]) $(uu[2])
   </td>
   !for k=1 to $livret_nbcomp
    !for j=1 to $(nbpalier_$k)
     !read adm/class/colors $(l_$(i)_$(k)_$(j))
    !next j
   !next k
  </tr>
 !next i
$table_end
<p>

