!read adm/title.phtml 3\
Relaties met klas  <em><font color=blue>$nei_description</font></em> van <em><font color=blue>$nei_institution</font></em>\
($wims_name_nameteacher: <a href="mailto:$nei_email?subject=Class neighboring relations">$nei_supervisor</a>)
<p>
<b>Relaties met andere klassen. </b> <small>[
!href cmd=help&special_parm=neibordecl $wims_name_help
 ]</small> 
 <p>La classe <em><font color=blue>
$nei_description</font></em>
!if $wims_class notitemof $nei_sup,$nei_part
 er zijn geen buurklassen gedefinieerd.
!else
 er zijn buur relaties ,
 !if $wims_class isitemof $nei_sup and $wims_class isitemof $nei_part
  voor docenten en studenten.
 !else
  !if $wims_class isitemof $nei_sup
   voor docenten.
  !else
   voor studenten.
  !endif
 !endif
!endif
<p>
!form reply
Accepteerd U klas  <em><font color=blue>
$nei_description</font></em> als partner&nbsp;?
!formselect nlevel from 0 to 3 prompt Nee, Voor docenten,\
	Voor studenten, Voor docenten en studenten
<input type=submit value=Sauver> 
</form> <p>


!if ($nei isitemof $n_sup,$n_part and $wims_class isitemof $nei_sup,$nei_part) or \
   all isitemof $nei_sup,$nei_part
 <p><b>Importeren van lesmateriaal. </b> <small>[
 !href cmd=help&special_parm=import $wims_name_help
 ]</small>
 <p>U kunt
 !href cmd=reply&job2=import lesmateriaal importeren  
 uit klas <em><font color=blue>
$nei_description</font></em>.
 <p>
!endif

!if  $nei isitemof $n_sup
<p>
<b>Delen van lesmateriaal.</b> 
<small>[
!href cmd=help&special_parm=share $wims_name_help
]</small>
<ul>
!endif

!if $wims_class isitemof $nei_sup and $nei isitemof $n_sup
 <li>
 !if $nsharable=$empty
    Er is geen (nieuw) deelbaar lesmateriaal aanwezig in klas
  <em><font color=blue>
$nei_description</font></em> dat gedeeld kan worden. 
 !else
 De klas <em><font color=blue>
$nei_description</font></em> geeft U <b>toestemming</b> te gebruiken: 
  !set names=!replace , by , $$name_ in $$name_$nsharable
  <em>$names</em>.
  !href cmd=reply&job2=addshare Klik hier voor acceptatie
.
 !endif
 <p>
!endif

!if $nei isitemof $sharing_all
    U gebruikt het onderstaande lesmateriaal uit klas <em><font color=blue>
$nei_description</font></em>&nbsp;:<ul>
 !for r in $sharelist
  !if $(sharing_$r)=$nei
   <li><b><em>$(name_$r)</em></b>. 
   !href cmd=reply&job2=stopshare&stoprec=$r Stop het gebruik
. <small>[
   !href cmd=help&special_parm=stopshare $wims_name_help
   ]</small>
  !endif
 !next r 
 </ul>
 <p>
!endif
 </li>
!if $nei isitemof $n_sup and $sharablelist!=$empty
<li>
 !form reply
 <input type=hidden name=changeshare value=yes>
 Kies het lesmateriaal waarvoor u klas <em><font color=blue>
$nei_description</font></em> <b>toestemming</b> geeft (<i>sélectionnez puis cliquez sur <tt>Sauver</tt></i>): <small>[
 !href cmd=help&special_parm=sharable $wims_name_help
 ]</small>
<p>
 !set sh=!nospace $sharablelist
 !set sh=!replace , by , $$name_ in $$name_$sharablelist
 !formcheckbox mksharable list $sharablelist prompt $sh
 <input type=submit value="$wims_name_tosave">
 </form> <p>
!if $nsharable!=$empty
<p><b>$wims_name_warning</b> De klas <em><font color=blue>
$nei_description</font></em>
vous autorise à partager certaines ressources. 
Vous ne devez pas l'autoriser à partager les mêmes ressources sous peine de confusion. 
Commencez par vous entendre avec elle et avec toutes les classes avec lesquelles vous
voulez partager des ressources. 
!endif
 </li>
!endif

</ul>

!reset stoprec
