
Buur relaties met klas  <em><font color=blue>
$nei_description</font></em> van
<em><font color=blue>$nei_institution</font></em>.
(Supervisor:
<a href="mailto:$nei_email?subject=Buren
relations">$nei_supervisor</a>) Deze klas
!if $wims_class notitemof $nei_sup,$nei_part
 heeft Uw klas nog niet als "buur" erkent.
!else
heeft Uw klas als "buur" erkent
 !if $wims_class isitemof $nei_sup and $wims_class isitemof $nei_part
 voor zowel supervisor  als ook het leerlingen accounts 

 !else
  !if $wims_class isitemof $nei_sup
  voor alleen het supervisor account 
  !else
  voor alleen het leerlingen account.
  !endif
 !endif
!endif
<p>
!form reply
Accepteert U deze klas als "buur"?
!formselect nlevel from 0 to 3 prompt Nee,Ja voor supervisor,\
	Ja voor deelnemers,Ja voor supervisor en deelnemers
<input type=submit value=Opslaan> <small>[
!href cmd=help&special_parm=neibordecl $wims_name_help
]</small>
</form> <p>

!if ($nei isitemof $n_sup,$n_part and $wims_class isitemof $nei_sup,$nei_part) or \
   all isitemof $nei_sup,$nei_part
 You can
 !href cmd=reply&job2=import importeer het materiaal 
 van deze klas
 <small>
 !href cmd=help&special_parm=import Help
 </small>
 <p>
!endif

!if $nei isitemof $n_sup and $sharablelist!=$empty
 !form reply
 <input type=hidden name=changeshare value=yes>
 Selecteer hier het materiaal dat u wilt uitlenen/delen:
 !set sh=!nospace $sharablelist
 !set sh=!replace , by , $$name_ in $$name_$sharablelist
 !formcheckbox mksharable list $sharablelist prompt $sh
 <input type=submit value=Change>
 <small>[
 !href cmd=help&special_parm=sharable help
 ]</small>
 </form> <p>
!endif

!if $wims_class isitemof $nei_sup and $nei isitemof $n_sup
 !if $nsharable=$empty
 Er is geen nieuw deelbaar/leenbaar lesmaterial gevonden in deze klas.
 !else
 Deze "buur" klas staat U toe te lenen,
  !set names=!replace , by , $$name_ in $$name_$nsharable
  <em>$names</em>.
  !href cmd=reply&job2=addshare Detail
. <small>
  !href cmd=help&special_parm=share Help
  </small>
 !endif
 <p>
!endif

!if $nei isitemof $sharing_all
U deelt het volgende materiaal van deze klas:<ul>
 !for r in $sharelist
  !if $(sharing_$r)=$nei
   <li><b><em>$(name_$r)</em></b>. 
   !href cmd=reply&job2=stopshare&stoprec=$r Stoppen met delen
. <small>
   !href cmd=help&special_parm=stopshare Help
   </small>
  !endif
 !next r 
 </ul>
 <p>
!endif

!reset stoprec
