!! Header menu bar definition.
!nocache
!set wims_theme_header=yes
!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module
!if $wims_hm_cnt!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
<div class=wimsmenu>
<center><table border=0 cellspacing=0 cellpadding=2 bgcolor="$wims_name_bgcolor"
width="100%"><tr><td><tr>
!for i_=1 to $wims_hm_cnt
 <td align=center>
 !set 1_=!line $i_ of $wims_hm
 !read oneitem.phtml $1_
 </td>
!next i_

!! -----------------------Insert "Permalien" --------------------------------
!! Permalien / lecteur exportable : ces lignes permettent d'integrer facilement la page courante a un autre site :

!set current_module=!replace / by , in $module
!set module_path= !item 1 of $current_module

!if $module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty
	!set export_name=$wims_name_this_module
	!set permalien=$wims_ref_name?module=$module

<td align="center" class="wims_header" id="header_export">
<div id="lien_export_media" style="display:block">
	<a href="#" onclick="document.getElementById('export_media').style.display = 'block';document.getElementById('lien_export_media').style.display = 'none';">$wims_name_display $export_name $wims_name_on_your_site</a>
</div>
<div id="export_media" style="display:none" align="left">
<div align="center"> -- <strong>$wims_name_display $export_name $wims_name_on_your_site</strong> 
-- &nbsp; <a href="#" onclick="document.getElementById('export_media').style.display = 'none';document.getElementById('lien_export_media').style.display = 'block';">
($wims_name_mask_this)</a></div><hr>

	<strong>$wims_name_permalink :</strong> ($wims_name_copy_and_paste $wims_name_the_link $wims_name_on_your_site $wims_name_or $wims_name_in_a_mail)
	<br>$wims_name_permalink $wims_name_for $export_name : <a href="$permalien">$permalien</a>
	<hr>
	<b>$wims_name_embeddable :</b> ($wims_name_copy_and_paste $wims_name_the_link $wims_name_on_your_site)<br>
	<small>$wims_name_display <strong>$export_name</strong> $wims_name_on_your_site ($wims_name_copy_and_paste $wims_name_the_code $wims_name_on_your_site) :
	</small>
	<textarea  style="vertical-align:middle" rows="3" cols="50" readonly="readonly" nowrap="hard" id="wims_embed_textarea" >&lt;iframe src="$permalien&+embededwindow=true" width="100%" height="100%">&lt;/iframe></textarea>
</div>
</td>

!endif
!!------------------------------------Fin de l'insert "Permalien" --------------------------


</tr></table></center>
</div>
!endif
