<!--begin of $wims_theme/htmlheader.phtml-->
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=$wims_main_font" />
<title>$module_title2</title>
<meta name="GENERATOR" content="wims [$module_language]" />
<meta name="description" content="$module_description $wims_site_description" />
<meta name="keywords" content="$wims_site_keywords, $module_domain, $module_keywords" />
<meta name="Author" content="$module_author" />
<meta http-equiv="Content-Style-Type" content="text/css" />

$wims_expire
$wims_CSS

<!-- Librairies JQUERY -->
    <script type="text/javascript" src="scripts/js/jquery/jquery.min.js"></script>
    <link rel="stylesheet" href="scripts/js/jquery/themes/smoothness/jquery-ui.min.css" />
    <script type="text/javascript" src="scripts/js/jquery/jquery-ui.min.js"></script>

<!-- JQUERY pour autocompletion -->
	<script type="text/javascript" src="scripts/js/interface/autocomplete.js"></script>


<!-- Style pour impression -->
<link rel="stylesheet" media="print" href="html/themes/_css/print.css" type="text/css" />
<!-- Style pour document latex2wims -->
<link rel="stylesheet" href="html/themes/_css/l2w.css" type="text/css" />
<!-- Style pour createQCM et confia2qcm par exemple -->
<link rel="stylesheet" href="html/themes/_css/createqcm.css" type="text/css" />

<style type="text/css">
body.main_body {
    background-color: $wims_bgcolor;
    $wims_bodyimg
    $wims_special_font
}

a:link {color:$wims_link_color;text-decoration:none;cursor:pointer;}
a:hover {color:$wims_ref_button_help_bgcolor;}
a:visited {color:$wims_vlink_color;}
.wimsmanager a {color:$wims_ref_menucolor;text-decoration:none;cursor:pointer;}

#wimstopbox,#wimsmenubox,#wimsmenumodubox { color: $wims_ref_menucolor; background-color: $wims_ref_bgcolor;}

.container h4{	background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_pendant,#menu_html { background-color:$wims_ref_bgcolor;	color:$wims_ref_button_color;}
#menu_avant,#menu_apres {  background-color:$wims_ref_button_bgcolor; color:$wims_ref_button_color;}
.infobulle{ background-color: $wims_ref_button_bgcolor;  color: $wims_ref_button_color;}

table.wimstable th {background-color: $wims_ref_bgcolor; color:$wims_ref_menucolor;}
table.wimstable th a {color: $wims_ref_menucolor;}
table.wimstable caption {background-color: $wims_ref_bgcolor;color: $wims_ref_menucolor;}
table.wimstable caption a {color: $wims_ref_menucolor;}
table.wimstable caption a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}
table.wimstable th a.wims_button{background-color: $wims_ref_button_bgcolor;color: $wims_ref_button_color;}
.legend {background-color: $wims_ref_bgcolor;color:$wims_ref_menucolor;}

</style>

<!--end $wims_theme/htmlheader.phtml-->
