!! Tail menu theme.
!nocache
!set wims_theme_tail=yes
<div class="wimscenter">
!for i_=1 to $wims_homeref_n0
 !set 1_=!line $i_ of $wims_rm_0
 !if $(1_[2])=0 and $(1_[1])=$empty
  <p></p>
 !endif
 !read oneitem.phtml $1_
 &nbsp;
!next i_
</div>
<div class="wimscenter wimstail">
<hr width="35%"/>
!if $wims_homeref_special!=$empty
 <small>$wims_homeref_special</small>
 </div>
 !exit
</div>
!endif

<table class="wimscenter wimstail wimsnoborder" bgcolor="$wims_homeref_bgcolor">
<tr>
!for i_=1 to $wims_homeref_n1
 <td><small>
 !set 1_=!line $i_ of $wims_rm_1
 !read oneitem.phtml $1_
 </small></td>
!next i_
</tr>
!!<tr><td colspan="$wims_homeref_n1"> </td></tr>

!for i_=1 to $wims_homeref_n4
 <tr><td colspan=""$wims_homeref_n1><small>
 !set 1_=!line $i_ of $wims_rm_4
 !read oneitem.phtml $1_
 </small></td></tr>
!next i_
!for i_=1 to $wims_homeref_n2
 <tr><td colspan="$wims_homeref_n1"><small>
 !set 1_=!line $i_ of $wims_rm_2
 !read oneitem.phtml $1_
 </small></td></tr>
!next i_

</table>
</div>
