
为以<em>注册用户</em>身份进入<b><font color=green>$mb_title</font></b>,
请输入登录名与个人密码.

<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.cn">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value="$forum">
<center><table border=0>
 <tr><td>你的登录名: <td><input size=20 name=fuser>
 <tr><td>你的密码: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="提交">
</center>
</form>

