!if $wims_read_parm!=$empty
 !set parms=$wims_read_parm
 !set parms=!replace internal $	$ by $\
$ in $parms
 !set size=!line 1 of $parms
 !distribute items $size into sx,sy
 !set ppm=!line 2 to -1 of $parms
!else
 !if $parms=$empty
  !exit
 !endif
 !distribute items $parms into sx,sy
 !set ppm=!item 3 to -1 of $parms
!endif

!set ppm=!replace internal $	$ by $\
$ in $ppm
!if copy isin $ppm or imagefill isin $ppm or bgimage isin $ppm
  !set line_cnt=!linecnt $ppm
  !for l_=1 to $line_cnt
    !set line=!line $l_ of $ppm
    !if copy isin $line or imagefill isin $line or bgimage isin $line
      !set im=!item -1 of $line
      !if bgimage isin $line
        !set im=!word -1 of $im
        !set line=bgimage \filedir/$im
      !else
         line=$(line[1..-2]),\filedir/$im
      !endif
      !if / notin $im
        !set ppm=!replace line number $l_ by $line in $ppm
      !endif
    !endif
  !next
!endif

!for pm in ppm, sx, sy
 !set $pm=!slashsubst $($pm)
!next pp

!set pp=!trim $ppm

!set pp=!line 1 to -1 of $pp
!set pp=!translate internal $	$ to $\
$ in $pp
!set pp=!trim $pp

!set canvasdraw_out=!exec canvasdraw\
size $sx,$sy\
$pp

$canvasdraw_out
