!!##language independant
 !if $parm1=$empty
  !exit
 !endif
!if \ isin $parm1$parm2$parm3$parm4
 !for p in 1,2,3,4
  !set parm$p=!slashsubst $(parm$p)
 !next p
!endif
!if / isin $parm1
 <iframe src="wims.cgi?module=adm/raw&amp;job=lightpopup&amp;noabout=yes&amp;emod=$parm1&amp;parm=$parm3&amp;option=noabout" 
width="100%" height="100%"></iframe>
!exit
!endif
 !reset titb
 !read $docdir/$doc/$parm1.def
 !set prompt=!item 2 to -1 of $parms
 !default prompt=$titb
 !if $titb=$empty
  !default prompt=<tt>$parm1</tt>
  $prompt
  <small>$n_nonavailable</small>
 !else
  <a name="$parm1"></a>
  $prompt
  !read $docdir/$doc/$parm1.def content
  !set gotblock=!append item $parm1 to $gotblock
 !endif

