Un document est constitué d'un ensemble de pages auxquelles on accède par des
liens proposés dans le document ou en utilisant les flèches.
Le document peut contenir des exemples dont le contenu change lorsque
l'on clique sur <span class="text_icon doch_reload">$wims_name_doch_reload</span>
<h2>Navigation</h2>
La navigation dans le document peut se faire
<ul>
    <li>en utilisant les liens présents dans les pages du document
ou dans le sommaire du document ;</li>
    <li>en suivant l'ordre de lecture proposé par l'auteur grâce à
        <ul>
            <li><span class="text_icon doch_prev">$wims_name_doch_prev</span> pour aller à la page précédente,</li>
            <li><span class="text_icon doch_next">$wims_name_doch_next</span> pour lire la page suivante,</li>
            <li><span class="text_icon doch_up">$wims_name_doch_up</span> pour remonter à la page "parent" de la page actuelle.</li>
        </ul>
    </li>
</ul>
Les pages du document que l'on parcourt constituent l'historique de sa lecture :
on peut se déplacer dans cet historique en utilisant les flèches
<span class="text_icon backhist">&lt;&lt;</span> Hist <span class="text_icon nexthist">&gt;&gt;</span>.
qui apparaitront au fur et à mesure de la navigation.
<h2>Faire une recherche dans le document</h2>
Pour rechercher un mot dans le document, on peut se placer sur la première page et cliquer
    sur le bouton  <span class="wims_button icon_button disabled"><span class="doch_printable">$wims_name_doch_printable</span></span>.
