<h2 class="wimscenter">Imágenes dinámicas</h2>

<p>Es posible incluir imágenes en 2D en sus documentos. Estas imágenes son
dinámicas, es decir que puede utilizar variables en sus instrucciones de diseño,
y el resultado variará con los valores de las variables. Es incluso posible generar animaciones.
</p><p>
Vea también
!href cmd=help&special_parm=canvasdraw canvasdraw
para más posibilidades de interactividad.
</p><p>
Sintaxis&#58; 
<pre>\draw{xsize,ysize}{instrucción...}</pre>
donde <span class="tt">xsize, ysize</span> son respectivamente la longitud y la altura del
dibujo (en pixels) e <span class="tt">instrucción...</span> es el contenido de las instrucciones.
Este es un texto compuesto por varias líneas, en las que cada 
línea es una instrucción.
<p>
!href cmd=help&special_parm=draw_example Ejemplo.
</p>
<hr/>

!changeto help/flydraw.phtml
