<h4>Incluir las respuestas en el enunciado de las preguntas</h4>

:signification
Es posible incluir campos de texto para las respuestas en el enunciado de los 
ejercicios en formato html. Las respuestas y opciones deben ser definidas de la forma
habitual.


:example
 <span class="wims_help_example">Ejemplos</span>
<ul>
<li><tt class="wims_code_words">\embed{reply 1}</tt> insertar la primera respuesta libre
en el texto.</li>
<li><tt class="wims_code_words">\embed{reply 2,10}</tt> insertar la segunda respuesta libre con un 
campo de texto para la respuesta de tamaño 10.</li>
<li><tt class="wims_code_words">\embed{choice 1}</tt> insertar la primera respuesta múltiple en el texto.</li>
</ul>

Caso particular. Si el tipo de <tt class="wims_code_words">reply 1</tt> es <tt class="wims_code_words">checkbox</tt>,
<tt class="wims_code_words">click</tt> o <tt class="wims_code_words">radio</tt>, entonces <tt class="wims_code_words">\embed{reply 1,2}</tt>
inserta únicamente la primera de las opciones (la número 2 en este caso),
sea para pulsar con el ratón (<tt class="wims_code_words">click</tt>) sea para marcar un botón. Esto
permite la inserción de opciones en diferentes estructuras de texto.

