
<center><h3>Los formatos del enunciado de los ejercicios</h3></center> <p>

Puede escribir el enunciado del ejercicio en uno de estos dos formatos: TeX o
html. <b>A causa del desarrollo de las potencialidades del formato html (ver más
adelante) ya no es indispensable el formato TeX, y deberá ser evitado
en adelante</b>.
<p>
Si el ejercicio no contiene fórmulas matemáticas complicadas (por ejemplo
matrices), es altamente recomendado usar el formato html. La ejecución
será más rápida, y habrá menos problemas de compatibilidad, particularmente
en el futuro.
<p>
Puede usar el formato html si el enunciado del ejercicio únicamente
contiene texto simple. Deberá preocuparse sobre todo de cambiar todos los
signos `<tt>&lt;</tt>' por la cadena `<tt>&#38;lt;</tt>', para evitar que se 
interpreten como la apertura de una etiqueta html. Dejando aparte lo anterior, 
puede usar etiquetas html en el texto, especialmente las usadas para poner 
subíndices (<tt>&lt;sub&gt;</tt>  <tt>&lt;/sub&gt;</tt>)
y superíndices (<tt>&lt;sup&gt;</tt> y <tt>&lt;/sup&gt;</tt>).
<p>
En particular, puede insertar enlaces http en el enunciado. Por ejemplo
puede incluir dibujos en el ejercicio, sin que estos dibujos tengan que haber
sido subidos al servidor (únicamente tiene que declarar la fuente de la imagen 
mediante la dirección web completa).
<p>
También puede incluir símbolos y fórmulas matemáticas
!href cmd=help&special_parm=math con mucha facilidad
 en su ejercicio aunque estén en formato html. Si esto no le basta tiene
disponible el formato TeX.
Para utilizarlo debe conocer la sintaxis de TeX.
<p>
En formato html también puede incluir
!href cmd=help&special_parm=embedans campos de texto para la respuesta
 y
!href cmd=help&special_parm=draw dibujos
 en el enunciado que escriba.
<p>
Observe también que los otros campos del ejercicio (la pregunta,
la pista y la solución) únicamente aceptan formato html, para
simplificar el tratamiento. No obstante pueden insertarse símbolos y
fórmulas matemáticas en la pista y en la solución.

