
<p>
La definición del servidor en WIMS puede hacerse por el nombre de la máquina
o por su IP. Sin embargo recomendamos encarecidamente el uso de
números IP, los nombres de máquina pueden dar pie a problemas de seguridad.
<p>
También se pueden definir los servidores de forma global, como de costumbre:
<span class="tt">127.0.0.</span> (pero no <span class="tt">127.0.0</span>)
corresponde a las IP del 127.0.0.1 al 127.0.0.255, y <span class="tt">.unice.fr</span>
(no <span class="tt">unice.fr</span>) corresponde a cualquier servidor del dominio
<em>unice.fr</em>.
<p>
<p>Por último, la palabra <span class="tt">all</span> abre acceso a todo el mundo. Esto
destruye totalmente la seguridad de su sistema; si elige esta opción
es problema suyo.
<p>
No podrá confiar en su IP actual si su conexión se establece
mediante IP dinámica: la IP cambiará de una conexión a otra.

