
<h3>Cómo escribir matemáticas en su ejercicio.</h3>

Puede incluir símbolos y fórmulas matemáticas en el enunciado (cuando
está en formato html), la pista y la solución.
<p>
Si lo único que quiere es insertar símbolos matemáticos o caracteres
griegos, no tiene más que teclear un
<tt class="wims_code_variable">\</tt> seguido del nombre del símbolo o caracter griego. Por ejemplo,
<tt class="wims_code_variable">\pi</tt> le devuelve $m_pi, <tt class="wims_code_variable">\le</tt> devuelve $m_le,
<tt class="wims_code_variable">\pm</tt> devuelve $m_pm, <tt class="wims_code_variable">\rightarrow</tt> devuelve
$m_rightarrow, etc. Los nombres de los símbolos siguen la convención estándar 
de TeX. Aquí tiene una
!href target=wims_help module=help/wimsdoc.en&subject=mathfonts#mathfonts lista
 (sustituya <tt class="wims_code_words">$$m_</tt> por <tt class="wims_code_variable">\</tt> en los nombres).
<p>
En términos más generales, para insertar una fórmula matemática entera
puede teclear la fórmula de la forma habitual, como si la escribiera en un
programa matemático o una página de una herramienta de cálculo de WIMS.
Para que fórmula sea formateada y mostrada adecuadamente no tiene más que
encerrarla entre un par de paréntesis precedidos por el carácter \. Por
ejemplo, <tt class="wims_code_words">\(x^3-3x+cos(2pi*x)^5)</tt> le devuelve
!insmath x^3-3*x+cos(2pi*x)^5
, o <tt class="wims_code_words">\(sqrt(x^2+y^2))</tt> le devuelve
!insmath sqrt(x^2+y^2)
. Puede teclear <tt class="wims_code_words">\(integrate(x^2+1)dx)</tt> para escribir
!insmath integrate(x^2+1)*dx
, o <tt class="wims_code_words">\(integrate(exp(x^2+1),x=1..infinity))</tt> para
!insmath integrate(exp(x^2+1),x=1..infinity)
. Puede también escribir la suma
!insmath sum(1/n^2,n=1..infinity)
 como <tt class="wims_code_words">\(sum(1/n^2,n=1..infinity)</tt>, o el producto
!insmath product(n/(n+1),n=1..infinity)
 por medio de <tt class="wims_code_words">\(product(n/(n+1),n=1..infinity)</tt>.
<p>
Encontrará más ayuda sobre la manera de escribir expresiones matemáticas en
!href target=wims_help module=help/main&chapter=1&open=1_math#math esta página
.
<p>
Para mostrar una matriz
!insmath [1,2,3;4,5,6;7,8,9]
, debe teclear <tt class="wims_code_words">\([1,2,3;4,5,6;7,8,9])</tt>. Son posibles las matrices dentro de
matrices (y se mostrarán correctamente).
<p>
Para los expertos de TeX o LaTeX, noten que cuando el software ve una fórmula
encerrada entre dos paréntesis precedidos por <tt class="wims_code_words">\</tt> que incluya caracteres
`\', va a interpretarla como una fuente TeX y por tanto la va a enviar 
directamente a TeX para que la formatee. Esto le permite escribir fórmulas
sumamente complicadas si sabe escribirlas en TeX.
<p>
Y por supuesto la forma más completa de utilizar TeX en sus ejercicios es elegir
!href cmd=help&special_parm=format el formato TeX
 (únicamente para el enunciado).

