!set typelist1=!trim\
default,Auto,détermination automatique de certains types de base\
raw,Texte brut,contrôle de comparaison par options\
numeric,Nombre,nombre avec tolérance de précision\
function,Fonction numérique,fonction avec test numérique\
equation,Equation numérique,equation avec test numérique\
exp,Expression mathématique,comparaison formelle\
text,Texte,des mots ou des phrases\
multiple,Choix multiples contrôlables,boutons ou menus\


!set typelist2=!trim\
atext,Texte approximatif,avec identification de singulier et pluriel etc.\
chembrut,Formule brute d'une molécule,en chimie\
chemdraw,Dessiner une molécule,avec une aplet Java\
chemclick,Sélectionner des atomes ou des liaisons d'une molécule,avec une aplet Java\
chemeq,Equation chimique,avec analyse d'équilibre\
clickfill,Objets à glisser-déposer,texte et image\
clicktile,Mettre en couleur des pavés, nécessite java\
compose,Composer,en utilisant des composantes fournies\
coord,Clic sur image,reconnaissance de coordonnées et régions diverses\
correspond,Correspondance,établir la correspondance de paires d'objets\
chset,Ensemble de caractères,\
geogebra,Géométrie dynamique,utilisation de l'applet GeoGebra\
javacurve,Dessin Java, possibilité de dessins soit libres soit avec des formes prédéfinies\
jmolclick,Clic sur des atomes en 3D, nécessite l'applet Jmol\
keyboard,Texte, avec clavier adapté\
matrix,Matrix, mathématique\
numexp,Nombre rationnel, écriture fractionnaire\
range,Nombres dans une zone,tout ce qui est dans la zone est accepté\
reorder,Mise en ordre, d'une liste d'objets\
set,Ensemble fini,textuel, formel ou approximatif\
sigunits,Sigunits,nombre avec unité et chiffre significatif\
symtext,Symtext,outil avancé d'identification de textes\
units,Nombre avec unité, pour la physique\
vector,Vecteur,comparaison formelle des composantes\
wlist,Liste de mots,\


!set namelist=Types de base,Types spécifiques ou avancés
!set symtextlist=text atext raw compose

<center><h3>Respuestas de los usuarios a un ejercicio</h3></center> <p>

Hay dos maneras básicas en las que un ejercicio OEF acepta respuestas
del usuario: opciones múltiples y respuestas libres.
La respuesta que dé el usuario será analizada según su tipo.
También es posible añadir
!href cmd=help&special_parm=feedback comentarios de retroalimentación
 cuando la respuesta cumpla determinada condición (por ejemplo
para advertir de un error típico).

<p><h4>Opciones múltiples</h4> <p>
Una opción múltiple se define dando una lista de opciones correctas
(una o varias) y otra lista con todas las opciones (las opciones correctas
se añaden de forma automática). <p>
Se pueden pedir hasta $choicelim opciones múltiples simultáneas en un
ejercicio, con la implementación actual. El número de opciones correctas
y erróneas en una opción múltiple no tiene límite (excepto la limitación de
la longitud del texto que impone WIMS).
<p>
Ver la
!href cmd=help&special_parm=oef help ayuda sobre el formato OEF
 acerca de la sintaxis para definir una opción múltiple.

<a name=freestyle></a>
<p><h4>Respuestas de estilo libre</h4> <p>
Una respuesta de estilo libre es la que la tiene que escribir el usuario.
Se pueden pedir hasta $answerlim respuestas libres simultáneamente en el 
mismo ejercicio con la implementación actual. <p>
La sintaxis es la siguiente:
<tt>\answer{Texto}{\respuesta}{type=...}{option=...}{weight=...}</tt>
<br>
(Los 3 últimos campos son opcionales).
<p>
Cada respuesta libre puede tomar independientemente uno de los siguientes
tipos:
<ol>
!for i=1 to 2
 <p><b>$(namelist[$i])</b>
 !set n=!linecnt $(typelist$i)
 <ul>
 !for j=1 to $n
  !set l=!line $j of $(typelist$i)
  !distribute item $l into name,title
  !set desc=!item 3 to -1 of $l
  !if $name isitemof $special_parm or all isitemof $special_parm
   <li><p><a name="_$name"></a>
   !read help/anstype.$lang/$name.phtml
   !if $name iswordof $symtextlist
    <p>
    <b>Remarque</b>.
    Ce type de réponse accepte l'option symtext. Si le mot <tt>symtext</tt> est
    déclaré dans l'option de la réponse, l'analyse de la réponse sera exactement
    comme pour
    !href cmd=help&special_parm=reply,symtext#_symtext symtext
, en particulier sans aucun traitement préalable des textes. Et toutes les
    options symtext seront comprises dans ce cas.
   !endif
   <p>
  !else
   <li>
   !href cmd=help&special_parm=reply,$name#_$name $title
   (<tt>$name</tt>) $desc.
  !endif
 !next j
 </ul>
!next i
<p>
Option commune à toutes les réponses libres : <tt>default</tt> Cette option
peut prendre la forme <tt><font color=green>default="valeur_par_défaut"</font>
</tt>. Si l'utilisateur donne une réponse vide, c'est la valeur_par_défaut
qui remplace.

<p>
Pour insérer les champs de réponses dans le texte par la commande <tt>embed</tt>, 
!href cmd=help&special_parm=embedans voir ici. 

 
<p><h4>Condiciones de comprobación</h4> <p>
Bajo ciertas circunstancias, es deseable que las respuestas de estilo libre
se corrijan según condiciones especiales (preguntas con múltiples respuestas
correctas, ejercicios que pidan ejemplos, respuestas determinadas por 
desigualdades, etc). Puede hacerse de la siguiente manera: 
<p>
Si la respuesta correcta a una pregunta libre es una variable indefinida
hasta ahora,
la respuesta a esta cuestión se asignará en esa variable. La variable
puede usarse en adelante para implementar las condiciones de comprobación. La
puntuación dada al ejercicio se determinará por el número de condiciones
de comprobación que se satisfagan, en lugar del número de respuestas que 
coincidan con la respuesta correcta.
<p>
Se pueden definir hasta $condlim condiciones simultáneas para un ejercicio,
con la implementación actual. Únicamente las respuestas numéricas
pueden ser corregidas así. La sintaxis es
<p><tt>
\condition{texto de la pregunta}{condiciones de comprobación}{weight=...}
</tt>
<br>
(el último campo es optional).
 <p>

A continuación presentamos algunos ejemplos de condiciones de comprobación 
(<tt>\ans1</tt> y <tt>\ans2</tt> son dos variables indefinidas que aparecen 
en las  definiciones de las respuestas libres, como se describe antes).
<small>
!href target=wims_mhelp cmd=help&special_parm=if Lista completa de las relaciones
</small>
<p>
$table_header
$table_hdtr<th>Condición<th>significado
$table_tr<td><tt>\ans1>=0 and \ans1<=1</tt>
    <td>Correcta si <tt>ans1</tt> está en el intervalo [0,1].
$table_tr<td><tt>\ans1=1 or \ans1=3 or \ans1=5</tt>
    <td>Correcta si <tt>ans1</tt> es 1, 3 o 5.
$table_tr<td><tt>(\ans1)*(\ans2)=6 and (\ans1)+(\ans2)=5</tt>
    <td>Correcta si <tt>ans1</tt> y <tt>ans2</tt> son las dos 
    raíces del polinomio x<sup>2</sup>-5x+6.
$table_tr<td><tt>sin(\ans1)=0</tt>
    <td>Correcta si <tt>ans1</tt> es un múltiplo de $m_pi.
$table_end <p>
Ver la
!href cmd=help&special_parm=oef ayuda sobre el formato OEF
 para ver la sintaxis de la definición de las respuestas.

<h4>Le paramètre optionnel <tt>weight</tt></h4>
<a name=weight></a> Il permet d'imposer un poids aux questions posées.
<p>
Exemple : 
<pre>\answer{}{1}{type=numeric}{weight=8}
\answer{}{1}{type=numeric}{weight=2}
</pre>

Le niveau de sévérité  sera aussi pris en compte lors du 
calcul fait et le pourcentage sera pris sur un pourcentage fixé
par le niveau de sévérité. 

Il est possible de mettre des variables dans <tt>weight</tt>. 
<p>
Exemple :
<pre>
\text{w = \t = 1 ? 1 : 2}
\answer{}{1}{type=numeric}{weight=\t}
\answer{}{1}{type=numeric}{weight=3}
</pre>

<h4>Le paramètre optionnel <tt>option</tt></h4>
 <a name=option></a>
Les options possibles à la suite d'une instruction <tt>\answer</tt>
ou <tt>\condition</tt> sont
<ul>
<li>
<tt>option=split</tt> : Dans le cas d'une réponse dont
le type est <tt>correspond</tt>, <tt>checkbox</tt> ou <tt>mark</tt>, la notation
tient compte des réponses justes, même si elles ne le sont pas toutes. 
</li>
<li>
<tt>option=nonstop</tt> : Dans le cas d'un exercice à étapes, les questions
suivantes sont posées même en cas de réponses fausses.
</li>
<li><tt>option=noanalyzeprint</tt> : Le texte automatique d'analyse de réponses n'est
pas affiché. C'est donc à l'auteur de l'exercice de fournir un feedback convenable. 
Cela est utile dans certains types comme le type <tt>mark</tt> où le texte automatique
est souvent inadéquat. Attention, l'analyse des conditions n'est pas non plus affichée. 
Seul le score subsiste.</li>
<li>A la suite d'une instruction <tt>condition</tt>, 
<tt>option=hide</tt> : La condition sera utilisée pour l'analyse
de la réponse mais ne sera pas  affichée. 
</li>

</ul>

