<h3><center>Utilizar un bloque de documento para la presentación de una hoja de trabajo</center></h3>

Pueden poner la dirección de un bloque de documento (como <tt>c1/main</tt>)
para la página de presentación de una hoja de trabajo.
El propio documento no tiene necesidad de ser legible de los participantes.
<p>
Dejar este campo vacio si desean utilizar la página de presentación normal.
<p>
Los vínculos a los ejercicios individuales deben ser definidos por el pedido
<tt> \exercise</tt>.
Pueden utilizar las variables siguientes predefinidas: <ul>
<li><tt> \scorerequire</tt> Puntos requeridos por cada ejercicio
</li><li><tt>\scoregot</tt> Trabajo del participante por cada ejercicio
</li><li><tt>\scoremean</tt> Resultado medio del participante por cada ejercicio
</li><li><tt>\expiration</tt> fecha de expiración de la hoja, aaaammdd
</li><li><tt>\today</tt> Fecha del día, aaaammdd
</li>
</ul>

La valeur des variables de score est une liste de nombres, chacun des items
correspond au nombre demandé pour un exercice de la feuille de même position.

<p>
<b>Un exemple</b> : vous êtes en train de créer la feuille d'exercices numéro 5.
Dans le bloc du document </tt>c1/main</tt>, écrivez par exemple
<pre>
\exercise{5/1} : Points à obtenir : \scorerequire[1] 
                 Points déjà obtenus : \scoregot[1]

\exercise{5/2} : Points à obtenir  : \scorerequire[2]
                 Points déjà obtenus : \scoregot[2]

\exercise{5/3}{Un autre titre} : Points à obtenir \scorerequire[3] ; 
                Points déjà obtenus \scoregot[3]
</pre>
