
<center><h2>La estructura de una interfaz de centro educativo</h2></center>

<a name=institution>
Una estructura de centro educativo es una red, a varios niveles, de un grupo
de clases virtuales. Toda clase virtual de la red se llama
<em>zona de trabajo</em> o simplemente <em>zona</em>.
<p>
<a name=portal>
La estructura del centro educativo está construida sobre una única zona
llamada <em><b>portal</b></em>. Este sirve de punto de entrada
además de utilizarse para la gestión global del centro. El verdadero trabajo 
de enseñanza no debe tener lugar en esta zona.
<p>
<a name=level>
Las zonas inmediatamente por debajo del portal son los <em>niveles</em>. Un
nivel corresponde a un conjunto de alumnos que comparten los mismos programas
de enseñanza anuales.
<p>
El objeto de los niveles es esencialmente compartimentar el centro. Para los
niveles no se aceptan inscripciones de alumnos ni el trabajo de
enseñanza.
<p>
<a name=class>
Las <em><b>clases</b></em> están inmediatamente por debajo de los niveles.
Una clase debe corresponder a un grupo de alumnos que comparten el mismo
empleo del tiempo.
<p>
Las clases son los puntos de inscripción de los alumnos. Cada alumno puede
inscribirse en una o varias clases.
<p>
<a name=program>
Al lado de las clases existen los <em><b>programas</b></em>, también 
inmediatamente por debajo de un nivel. Cada programa unifica los recursos
pedagógicos que pueden ser compartidos por una o varias clases del nivel.
<p>
Los alumnos no pueden inscribirse en los programas. Únicamente los
profesores pueden inscribirse en los programas para preparar los
recursos pedagógicos.
<p>
<a name=course>
Los <em><b>cursos</b></em> son zonas en el punto más bajo de la escala. 
Cada curso pertenece a la vez a un programa y a una clase. Cada par
{programa,clase} puede corresponder a un curso.
<p>
Los recursos pedagógicos de un programa son compartidos por todos sus cursos.
Y un alumno de una clase puede navegar entre los cursos de la clase.
El trabajo de los alumnos tiene lugar en los cursos.
<p>
Un curso tiene un conjunto único de recursos pedagógicos (el del programa
del que depende) y un empleo del tiempo único.
<p>
<a name=icourse>
Un programa puede tener también <em><b>cursos interclases</b></em>. Un curso de
este tipo sólo depende del programa, y los alumnos de todas las clases pueden
inscribirse en un curso interclases. Está previsto para los programas de
enseñanza optativos.
<p>
<a name=test>
Cada programa puede tener también un curso especial, llamado
<em>zona de pruebas</em>. Esta zona permite a los profesores preparar y 
probar los recursos pedagógicos experimentales, antes de exportarlos al
programa. Todo lo que pasa en una zona de pruebas es invisible a los alumnos.

