
<b>Hacer copias de seguridad de su clase</b>. <br>
Puede realizar una copia de seguridad de la clase en un fichero comprimido.
Si su clase es muy activa, puede también hacer copias selectivas.
El fichero de seguridad puede enviarse más tarde al servidor para recuperar
su clase o para copiar determinados recursos en una clase nueva.
<p>
Todas las fuentes de la clase están escritas en ficheros de texto, y por
tanto también puede leerlas y editarlas en su ordenador local.
<p>
Formatos de fichero comprimido disponibles: <ul>
 <li><em>zip</em>, puede descomprimirse y leerse en prácticamente todos 
 los sistemas (Windows, Mac, Linux/BSD, etc.), pero la compresión no es 
 siempre muy eficaz;
 
 <li><em>tgz</em>, puede descomprimirse y leerse únicamente en sistemas
 de tipo Unix (Linux, BSD, Sun OS, etc.), pero tiene una ratio de compresión
 más elevada;
 
 <li><em>tar.gz</em>, un sinónimo de tgz.
</ul>
<p>
Ni que decir tiene, WIMS acepta todos los formatos anteriores para la
recuperación de clases.

