
<b>Importar recursos de una clase vecina</b>.
<br>
Puede importar recursos o cuentas de participantes de una
!href cmd=help&special_parm=neighbor clase vecina
 efectiva para el profesor.
<p>
Para importar algo de una clase, seleccione el nombre de la clase
de la lista de las otras clases. Si tiene permiso para importar de ella,
un enlace le conducirá a una página que le proporcionará la lista de
recursos importables. Sólo aparecerán listados los artículos que usted
no tiene en su propia clase.
<p>
La importación de un artículo no afecta a este artículo en la clase 
exportadora. Si modifica el artículo importado en su clase, su original
en la clase exportadora no será modificado, y viceversa. Si quiere compartir
las modificaciones con otras clases, plantéese utilizar
!href cmd=help&special_parm=share compartir recursos
 con ellas.
<p>
Por lo que respecta a las hojas de trabajo y de examen, sólo son importables
las hojas activas (o caducadas). Una vez instaladas en su clase, las
hojas importadas se vuelven inactivas. Esto le permitirá verificar el material
importado, y modificarlo eventualmente, antes de activarlo.
<p>
Por lo que respecta a las cuentas de los participantes, advierta que no
puede importar a un participante si el nombre de usuario ya está en uso
en su clase (por la misma persona o por otra) aunque haya borrado a este
último.
