
<b>Permiso para compartir sus recursos</b>.
<p>
Si permite que la
!href cmd=help&special_parm=neighbor clase vecina
!href cmd=help&special_parm=share comparta
 los recursos de su clase, debe ser consciente del riesgo que implica
 para su clase.
</p><p>
Una vez que ha declarado compartible un tipo de recurso, la otra clase
puede efectivamente compartirla. Esto significa que la gente puede
modificar sus recursos, incluso dañarlos (por algún error).
</p><p>
Es particularmente arriesgado permitir compartir su cuenta de profesor.
Si el otro cambia la contraseña de profesor (o si hay una intrusión en la
ota clase), perderá el acceso a su clase.
</p><p>
Si es posible, es preferible invitar a la otra clase a
!href cmd=help&special_parm=import importar
 sus recursos, en lugar de permitirle compartirlos.
</p>
<p>
Il y a des dépendances entre les ressources : le partage de certaines vous obligera à en partager d'autres (par exemple les examens sont dépendants des feuilles d'exercices).
</p>
<p>
Les questionnaires ne peuvent pas être partagés si l'un d'entre eux est un modèle préparé utilisant des variables techniques.
</p>
