
!if $class_defined!=yes
 <b>Napaka!</b>. Poskusili ste se prijaviti v uèilnico $name_classess, ki ne obstaja. Prosim, preverite svojo zahtevo.
 !exit
!endif

Vnesite geslo za prijavo <em>skrbnika</em> uèilnice <b><font
color=green>$class_description</font></b> ustanove
<b><font color=green>$class_institution</font></b>.

<p>
!set wims_form_method=post
!form reply
<input type=hidden name=auth_user value=supervisor>
<center>
 Skrbni¹ko geslo: <input type=password size=20 name=auth_password>
<p>
<input type=submit value="Po¹lji">
</center>
</form>

