
!if $class_defined!=yes
 <b>Napaka</b>. Posku¹ate se prijaviti v uèilnico $name_classess
, ki ne obstaja. Prosim, preverite svojo zahtevo.
 !exit
!endif

Vnesite svoje uporabni¹ko ime in osebno geslo za uporabo uèilnice <b><font
color=green>$class_description</font></b> ustanove
<b><font color=green>$class_institution</font></b>.

<p>
!set wims_form_method=post
!form reply
<center><table border=0>
 <tr><td>$wims_name_Login<td><input size=20 name=auth_user value="$auth_user"></td>
 <tr><td>$wims_name_Password<td><input type=password size=20 name=auth_password></td>
 $table_end
 <p><center>
 <input type=submit value="$wims_name_Enter">
</center>
</form> <p>

$name_new_participant:
!href module=adm/class/reguser&class=$class&subclass=yes $name_register