
!if $directcnt>0
 Neposredno lahko prestopite v:<ul>
 !for cl in $directlist
  !distribute words $cl into c_,u_
  !set n_=!defof class_institution, class_description in\
	wimshome/log/classes/$c_/.def
  <li>
  !if $u_=supervisor
   !set t_=supervisor
  !else
   !set t_=$type
  !endif
  !href cmd=reply&type=auth$t_&class=$c_&auth_user=$u_ $n_
  (<tt>$u_</tt>)
 !next cl
 </ul>
 <p><hr> <p>
 !if $wims_user=supervisor
  Ali: $name_level_else $sousclasses_else v spodnjem seznamu.
 !endif
!else
 !if $wims_user=supervisor
  Za obisk druge $name_level_else $sousclasses_else, jo izberite iz seznama.
 !else
  V drugih uèilnicah nimate uporabni¹kega raèuna.
 !endif
!endif

