!if $clcnt<=0
 $name_example1
 !exit
!endif

!if $lacnt<=0
 $name_example2
 !exit
!else
  $name_example3
!endif

$name_example4
!href module=adm/class/regclass $wims_name_classcreate
!let nb=!itemcnt $classification
!bound exampletype between 1 and $nb default 3
<p>
<center><table summary="">
<tbody><tr>
 !for k=1 to $nb
  !let titre=!item $k of $classification
  <th>
   !if $k=$exampletype
    $titre
   !else
    !href cmd=reply&exampletype=$k $titre
   !endif
  </th>
 !next k
 </tr>
 <tr><td colspan=$nb>
 $table_header
  $table_hdtr<th>$wims_name_name</th>
  <th>$name_connexion</th><th>$name_register</th></tr>
  !for i=1 to $clcnt
   !set l=!line $i of $classes
   !distribute items $l into code,expire,inst,cl
   !defread wimshome/log/classes/$code/.def
   !distribute char $class_level into l_,y_
   !let clsty=!positionof item $class_level in E1,E2,E3,E4,E5,E6,H1,H2,H3,H4,H5,H6,H7,U1,U2,U3,U4,U5,U6
   !if $clsty!=$empty
    !let clsty=!item $clsty of 1,1,1,1,1,1,2,2,2,2,3,3,3,4,4,4,4,4,4
   !endif
   !if $exampletype=$clsty or ($clsty=$empty and $exampletype=$nb)
    $table_tr
     <td align=center>$cl</td>
     <td align=center>
      !href module=home&user=anonymous,$code,anonymous $name_anonymous
      &nbsp;
      !href module=$module&type=authparticipant&class=$code $name_registered
     </td>
     <td align=center>
      !href module=adm/class/reguser&class=$code $name_register
     </td>
    </tr>
   !endif
  !next i
 $table_end
</tbody></table></center><p>
 
$name_instruction

$name_sheet_example

!href module=home&search_keywords=&search_category=S $wims_name_sheet

