!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=skupina uèilnic
    !set name_sup=uèitelj
   !else
    !set name_classe=ustanova
    !set name_sup=skrbnik
   !endif
     !set name_classes= $name_classe
     !set name_classess=$name_classe
     !set name_classesss= skupine uèilnic
     !set name_classessss= Skupina uèilnic
 !else
   !set name_classe=uèilnica
   !set name_classes=$name_classe
   !set name_classess=$name_classe
   !set name_classesss= uèilnice
   !set name_classessss= uèilnice
   !set name_sup=uèitelj
 !endif

 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of uèilnica,teèaj
   !set Name_level= !item $splevel of Stopnja,Uèilnica,Teèaj
   !set Name_levels= !item $splevel of Stopnje,Uèilnice,Teèaji
   !set sousclasses_else=!item $splevel of ali uèilnice, ali teèaja
   !set name_level_else= !item $splevel of stopnja,uèilnica,teèaj
 !else
   !set sousclasses=pod-uèilnice
   !set sousclasses_else=uèilnica ali ustanova
 !endif
 
 !set CL_Name	=Level,Class,Program,Course,Course interclasses,Test Zone
!set Name_program=Programs
!set name_program=program
!set name_portalandgroup=Ustanove in skupine uèilnic
!set name_independantclass=Samostojne uèilnice

!distribute items Registracija,Anonyme,javno,za¹èiteno,Leto,\
Nov uporabnik,inscrit,Type de connexion,Up\
into name_register,name_anonymous,name_open,name_protected,name_year,\
name_new_participant,name_registered,name_connexion,name_up

!distribute line V drugih uèilnicah nimate uporabni¹kega raèuna.\
Rechercher votre classe\
Na tem stre¾niku trenutno ni nobene virtualne uèilnice.\
Aucune classe ne correspond à votre recherche.\
 Neposredno lahko prestopite v\
into name_noaccount,name_searchclass,name_noavailable,name_nofound,name_direct

!let classification=Ecole,Collège,Lycée,Université,Autre

!set name_text1=S klikom na ime lahko vstopite v virtualno uèilnico. \
Novi uporabniki se s klikom na besedo '$name_register' registrirate za uporabo uèilnice\
(èe je uèilnica za¹èitena z geslom, potrebujete skupno geslo, ki vam ga posreduje va¹ skrbnik).\
<p>\
Èe ste se ¾e registrirali, pa se s klikom na ime uèilnice prijavite za delo v njej \
(potrebujete uporabni¹ko ime in osebno geslo, ki ste ju izbrali ob registraciji).



!set name_text2=Za obisk druge $name_level_else $sousclasses_else, jo izberite iz seznama.
!set name_text3=Ali: $name_level_else $sousclasses_else v spodnjem seznamu.

!set name_language=Na tem stre¾niku trenutno ni nobene virtualne uèilnice v slovenskem jeziku. \
Morda i¹èete uèilnico v kak¹nem drugem jeziku ?
!set name_language2=Na tem stre¾niku trenutno ni nobene virtualne uèilnice v slovenskem jeziku.



