!if $class_type iswordof 2 4
   !if $class_type=2
    !set name_classe=skupina uèilnic
    !set name_sup=uèitelj
   !else
    !set name_classe=ustanova
    !set name_sup=skrbnik
   !endif
     !set name_classes= $name_classe
     !set name_classess=$name_classe
     !set name_classesss= skupine uèilnic
     !set name_classessss= Skupina uèilnic
 !else
   !set name_classe=uèilnica
   !set name_classes=$name_classe
   !set name_classess=$name_classe
   !set name_classesss= uèilnice
   !set name_classessss= uèilnice
   !set name_sup=uèitelj
 !endif

 !if $splevel iswordof 1 2 3
   !set sousclasses=!item $splevel of uèilnica,teèaj
   !set Name_level= !item $splevel of Stopnja,Uèilnica,Teèaj
   !set Name_levels= !item $splevel of Stopnje,Uèilnice,Teèaji
   !set sousclasses_else=!item $splevel of ali uèilnice, ali teèaja
   !set name_level_else= !item $splevel of stopnja,uèilnica,teèaj
 !else
   !set sousclasses=pod-uèilnice
   !set sousclasses_else=uèilnica ali ustanova
 !endif
 
 !set CL_Name	=Level,Class,Program,Course,Course interclasses,Test Zone
!set Name_program=Programs
!set name_program=program
!set name_portalandgroup=Ustanove in skupine uèilnic
!set name_independantclass=Samostojne uèilnice

!distribute items Registracija,Anonyme,javno,za¹èiteno,Leto,\
Nov uporabnik,inscrit,Type de connexion,Up\
into name_register,name_anonymous,name_open,name_protected,name_year,\
name_new_participant,name_registered,name_connexion,name_up

!distribute line V drugih uèilnicah nimate uporabni¹kega raèuna.\
Recherchez votre classe\
Na tem stre¾niku trenutno ni nobene virtualne uèilnice.\
Aucune classe ne correspond à votre recherche.\
 Neposredno lahko prestopite v\
into name_noaccount,name_searchclass,name_noavailable,name_nofound,name_direct

!let classification=Ecole,Collège,Lycée,Université,Autre

!set name_text1=S klikom na ime lahko vstopite v virtualno uèilnico. \
Novi uporabniki se s klikom na besedo '$name_register' registrirate za uporabo uèilnice\
(èe je uèilnica za¹èitena z geslom, potrebujete skupno geslo, ki vam ga posreduje va¹ skrbnik).\
<p>\
Èe ste se ¾e registrirali, pa se s klikom na ime uèilnice prijavite za delo v njej \
(potrebujete uporabni¹ko ime in osebno geslo, ki ste ju izbrali ob registraciji).


!set name_text2=Za obisk druge $name_level_else $sousclasses_else, jo izberite iz seznama.
!set name_text3=Ali: $name_level_else $sousclasses_else v spodnjem seznamu.

!set name_language=Na tem stre¾niku trenutno ni nobene virtualne uèilnice v slovenskem jeziku. \
Morda i¹èete uèilnico v kak¹nem drugem jeziku ?
!set name_language2=Na tem stre¾niku trenutno ni nobene virtualne uèilnice v slovenskem jeziku.

!set name_warning= <b>Napaka</b>. Posku¹ate se prijaviti v uèilnico $name_classess, \
  ki ne obstaja. Prosim, preverite svojo zahtevo.

!set name_enter=!nosubst nesite svoje uporabni¹ko ime in osebno geslo za uporabo uèilnice \
  <b><font color=green>$class_description</font></b> ustanove \
  <b><font color=green>$class_institution</font></b>.

!set name_entersup=!nosubst Vnesite geslo za prijavo <em>skrbnika</em> uèilnice \
  <b><font color=green>$class_description</font></b> ustanove\
  <b><font color=green>$class_institution</font></b>.
 
 !set name_research1=There are many virtual classes on this site. To find your class, please type\
  a search keyword.
!set name_research2=There are still too many classes corresponding to your search word. Please\
  give a more precise word.

!set name_supervisor_text=V nasprotnem primeru pa na seznamu izberite svojo uèilnico in se prijavite kot skrbnik.

!if $type=example
   !set name_example1=Na tem stre¾niku trenutno ni pripravljenih primerov virtualnih uèilnic.
   !set name_example2=Na tem stre¾niku trenutno ni pripravljenih primerov virtualnih uèilnic v slovenskem jeziku.
   !set name_example3=!nosubst There is $clcnt example classes of English language on this site.
   !set name_example4=They intend to show you how virtual classes work from a students'side.\
     If you want to experiment  with a virtual class as a supervisor, you will first have to create\
      one. Click on the link and follow the instructions
   !set name_instruction=<ul>\
  <li>Kliknite na `Osebna prijava' za prijavo z lastnim uporabni¹kim imenom.\
  Pred tem morate opraviti postopek registracije (stre¾nik lahko obèasno tudi izbri¹e ¾e \
  obstojeèe registracije v preizkusnih uèilnicah).
  <li><p>Kliknite na `Anonimna prijava' za anonimno prijavo v uèilnico, èe nimate ali \
  si ne ¾elite uporabiti lastnega uporabni¹kega imena.\
  <li><p>Kliknite na `Registracija' za pridobitev uporabni¹kega imena.\
</ul>

!set name_sheet_example=Vous trouverez aussi des feuilles d'exercices que vous pourrez ensuite importer \
    dans votre classe et modifier.
!endif
 

