!read adm/title.phtml 3\
\
Actualisation des index

Cet outil est réservé aux utilisateurs experts qui font des
modifications manuelles au contenu de la classe. Après ces modifications,
vous pouvez cliquer sur le lien correspondant pour actualiser l'index.
<p>
Vous aurez probablement besoin d'étudier le code source du logiciel pour les
détails sur la manière de  modifier manuellement le contenu de la classe.
<p>
Ce n'est pas grave si vous cliquez sur l'un des lien par mégarde.

