
<b>Permission de partage de vos ressources</b>.
<p>
Si vous permettez à la
!href cmd=help&special_parm=neighbor classe voisine
 de
!href cmd=help&special_parm=share partager
 vos ressources, vous devez être conscient du risque que cela amène à votre
classe.
</p><p>
Une fois que vous avez déclaré un type de ressource partageable, l'autre classe
peut effectivement le partager. Cela signifie que des gens peuvent modifier
vos ressources, y compris les endommager (par une fausse manoeuvre).
</p><p>
Il est particulièrement risqué de permettre de partager votre
compte d'enseignant. Si un autre change le mot de passe d'enseignant (ou s'il
y a une intrusion à l'autre classe), vous perdrez l'accès à votre classe.
</p><p>
Si possible, il est préférable d'inviter l'autre classe à
!href cmd=help&special_parm=import importer
 vos ressources, au lieu de lui permettre de les partager.
</p>
<p>
Il y a des dépendances entre les ressources : le partage de certaines vous obligera à en partager d'autres (par exemple les examens sont dépendants des feuilles d'exercices).
</p>
<p>
Les questionnaires ne peuvent pas être partagés si l'un d'entre eux est un modèle préparé utilisant des variables techniques.
</p>
