
<b>Arrêter un partage de ressources</b>.
<br>
Seules les classes secondaires dans un
!href cmd=help&special_parm=share partage de ressources
 peuvent arrêter le partage entre
!href cmd=help&special_parm=neighbor classes voisines
.
<p>
Si vous arrêtez le partage, votre classe en sortira avec une copie des
ressources partagées en l'état actuel. Donc arrêter un partage n'aura aucun
effet immédiat sur votre classe. La seule différence est que les
modifications futures sur ces ressources, que ce soit par vous ou par
d'autres classes, n'auront plus de répercussions mutuelles.
<p>
Dans certains cas, si vous arrêtez une relation de partage, il vous sera
impossible de recommencer le partage. Si c'est le cas, le serveur vous
donnera un avertissement avant que l'opération d'arrêt de partage ne soit
définitive.

