
<b>Partage du compte d'enseignant</b>.
<br>
Si vous vous préparez à 
!href cmd=help&special_parm=neighbor partager
 le compte d'enseignant avec d'autres classes, veuillez tenir compte que
les risques de sécurité seront aussi partagés.
<p>
Si toutes les classes appartiennent à un même enseignant physique (vous),
partager le compte d'enseignant représente l'avantage que pour changer votre
mot de passe d'enseignant, il vous suffit de le changer une fois (dans
n'importe quelle classe du partage). Ceci vous permettra de changer le mot
de passe plus souvent, donc vos classes seront plus sûres. Vous devez quand
même avoir la conscience que des classes multiples avec le même mot de passe
d'enseignant multiplient le risque de sécurité par le nombre de classes. Une
intrusion dans l'une des classes peut endommager toutes les classes dans le
partage, une situation qui s'est déjà produite dans un environnement
d'enseignement.
<p>
D'un autre côté, si les classes appartiennent à des enseignants physiques
différents, le partage du compte d'enseignant est déconseillé, de même que
d'utiliser un mot de passe commun. Pensez au cas où un enseignant change le
mot de passe porr une raison ou pour une autre, sans notifier correctement et
à temps les autres.

