 <b>Vergelijking.</b> (naam: <span class="tt wims_code_words">equation</span>)<br/>
 Het antwoord wordt vergeleken met de correcte vergelijking binnen de getalsmatige grenzen en precisie, zoals deze
 zijn aan aangegeven door de schrijver van de oefening.
 
 Het antwoord <span class="tt">a = 0</span> wordt geinterpreteerd als <span class="tt">a</span>. 
 Met de optie <span class="tt wims_code_words">eqsign=yes</span> is de student verplicht <span class="tt"> a = 0</span> te noteren. 
