!if $wims_read_parm=synonym
 <p>
U mag hier synoniemen definieren in het goede antwoord.
Deze synoniemen moeten worden genoteerd <b>na</b> het standaard goede antwoord, en voorafgegaan door een
 ``<span class="tt wims_code_words">|</span>'' symbool.
 Een willekeurig aantal synoniemen mag worden opgenomen.
 </p>
!endif
!endif

!if $wims_read_parm=badonly
 <p>
 Verder kunt U nog betekenisvolle "kernbegrippen" definieren.
Dit is dus een lijst met woorden die opgenomen kan worden in het goede antwoord veld,
achter het goede antwoord en de eventuele synoniemen en voorafgegaan door een puntcomma ``<span class="tt wims_code_words">;</span>''.
Interpunctie in de kernbegrippen lijst wordt verwaarloosd
 </p><p>
Wanneer er kernbegrippen zijn gedefinieerd en het leerling antwoord bevat geen van deze woorden,
wordt de vraag ter correctie terug gestuurd.
</p>
!endif
