
!if $exologcnt<1
 $name_noexercise2 $(names[1]) $(names[2]).
 !exit
!endif

$name_click

!read tabletheme

<p>$table_header
$table_hdtr
<th><small>$wims_name_date</small></th>
<th><small>$wims_name_Sheet</small></th>
<th><small>$wims_name_Exercise</small></th>
<th><small>$name_Step</small></th>
<th><small>$wims_name_Score1</small></th>
<th>$wims_name_title</th>
!for i=1 to $exologcnt
 !set l=!line $i of $exolog2
 !set l_=!line $i of $exologs
 !distribute item $l into d_,s_,n_
 !set n_=!translate . to , in $n_
 !distribute item $n_ into S_,E_
 !set s_=!getdef w_module_score in wimshome/log/classes/$wims_class/exolog/$checkuser/$l_
 !default s_=-
 !set p_=!recordcnt wimshome/log/classes/$wims_class/exolog/$checkuser/$l_
 !set V_=!record $E_ of wimshome/log/classes/$wims_class/sheets/.sheet$S_
 !distribute lines $V_ into a,a,a,a,T_,D_
 !if $D_!=$empty
  $table_tr<td align=center>
  !href target=wims_check module=$module&job=check&checkuser=$checkuser&logcheck=$l_&checkstep=1 $d_
  </td>
  <td align=center>$S_</td><td align=center>$E_</td>
  <td align=center>$p_</td>
  <td align=center>$s_</td>
  <td>$T_ <small>$D_
  !if $wims_user=supervisor
   !getfile exolog/$l_ source
  !endif
  </small></td></tr>
 !endif
!next i
$table_end

!set wims_menu_items=!append line Score1,1,module=adm/class/userlist&job=getuser&getuser=$checkuser\
to $wims_menu_items