!!###language independant
!read adm/css.phtml
!header

!if $error!=$empty
 !read msg.phtml
 <p><hr> <p>
!endif
!read $job.phtml

!if $auth_login!=$empty and $job!=modname
 <p>
 !if $job iswordof flist edfile showfile binfile
 !set wims_menu_items=!append line test,4,module=devel/$auth_login/$mod,test\
 to $wims_menu_items
  !set doctest=!module category devel/$auth_login/$mod
  !if document isin $doctest
    !set wims_menu_items=!append line docgestion,4,module=adm/doc.$module_language&devdoc=$mod&doc=1&job=read,test\
     to $wims_menu_items
  !endif
 !endif
 !if $job iswordof flist index publish prop diff binfile
  !if $job iswordof index publish diff
   !set wims_menu_items=!append line modcontent,1,cmd=reply&jobreq=flist\
   binfile,1,cmd=reply&jobreq=binfile\
   to $wims_menu_items
  !endif
  !if $job iswordof flist
    !set wims_menu_items=!append line binfile,1,cmd=reply&jobreq=binfile\
   scripttest,1,module=tool/directexec&cmd=new\
to $wims_menu_items
  !endif
  !if $job iswordof binfile
   !set wims_menu_items=!append line otherfiles,1,cmd=reply&jobreq=flist\
     to $wims_menu_items
  !endif
  !set wims_menu_items=!append line ,0,\
   docoef,4,module=adm/createxo&modtoolhelp=yes,help\
   docslib,4, module=help/wimsdoc&subject=slib#slib,help\
   docanswer,4,module=adm/createxo&modtoolhelp=yes&special_parm=reply,help\
   doctec,4,module=help/wimsdoc.en,help\
   ,0,\
  to $wims_menu_items
  !if $job iswordof flist publish diff binfile
  !set wims_menu_items=!append line properties,1,cmd=reply&jobreq=index\
  to $wims_menu_items
  !endif
  !if $job notwordof publish prop diff
  !set wims_menu_items=!append line modsave,1,cmd=reply&jobreq=backup\
  to $wims_menu_items
   !if $pubtit!=$empty
   !set wims_menu_items=!append line checkdiff,1,cmd=reply&jobreq=diff\
    to $wims_menu_items
   !endif
   !set wims_menu_items=!append line publish,1,cmd=reply&jobreq=publish\
   to $wims_menu_items
  !endif
 !endif
 !set wims_menu_items=!append line modlist,1,cmd=reply&jobreq=modname\
 to $wims_menu_items
!endif

!tail

!reset confirm target1 target2 target3 target4 vcheat \
      i_translator i_translator_address, modifiers \
      p_name p_email p_pass1 p_pass2 bin_job
