
!if $passchange!=yes
 Change properties of your developer's account 
 <font color=blue><tt><b>$auth_login</b></tt></font>
 on <font color=blue><tt>$httpd_SERVER_NAME</tt></font>:
 <small>(leave the password field empty if you don't want to change 
 it)</small>
!else
 Your account password has been changed.
!endif
<p>

!form reply
<center><table border=0>
<tr><td align=right nowrap><label for="p_name">Name:</label> </td>
<td><input type=text size=40 name=p_name id="p_name" value="$auth_name">
</td></tr>
<tr><td align=right nowrap><label for="p_email">email address:</label> </td>
<td><input type=text size=40 name=p_email id="p_email" value="$auth_email">
</td></tr>
<tr><td align=right nowrap><label for="p_pass1">Password:</label> </td>
<td><input type=password size=20 name=p_pass1 id="p_pass1">
</td></tr>
<tr><td align=right nowrap><label for="p_pass2">Repeat password:</label> </td>
<td><input type=password size=20 name=p_pass2 id="p_pass2">
</td></tr>
<tr><td align=center colspan=2 nowrap>
<input type=submit name=confirm value="Save">
<input type=submit value="Cancel">
</td></tr></table> </center> <p>
</form>
