!read adm/title.phtml 2\
WIMS version of a module

<p>
WIMS is a system that evolves rapidly. New features are introduced to 
each new release.
</p><p>
If a module is developed under a recent version of WIMS, it may not be able
to run under a server of earlier version, because the latter does not have
the features needed to make it work correctly.
</p><p>
For this reason, WIMS now refuses to execute a module which requires a newer
wims_version.
</p><p>
As your module $mod is developed under WIMS-$wims_version, it is safe if you
declare it requiring wims_version $wims_version. Unless you are sure that
you haven't used any new feature since an earlier wims_version, in which
case you can use version_cheat. But you are warned that if you make it
wrong, people may start discovering weird "bugs" in your module!

</p><p>
WIMS version must be written like <tt>d.dd</tt> or <tt>d.dda</tt>
where the <tt>d</tt>'s are fingers and the <tt>a</tt> is a letter, the whole word beeing
of course a real version of WIMS.
</p>