
$title (<tt>$mod</tt>)
<p>
!if $diff=$empty
 No difference found between the development version and the public version on this
 server.
!else
 !if $diff=MANY
  Too many differences exist between the development version and the public version on this
  server.
 !else
  Differences between the development version and the public version on this
  server:
  <pre>$diff</pre>
 !endif
!endif
<p><hr> <p>

