!if $special_parm!=$empty
 !read help/$special_parm.phtml
 !goto end
!endif

!if $login=$empty
 This tool is for online creation and 
 development of free style WIMS activity modules.
 <p>
 Such a module may be a full-power exercise (compared with OEF exercises
 which are easier to develop but have limited capacities; see
 !href module=adm/createxo Createxo
 ) or a sophisticated computational tool. It should be written in the WIMS
 interpreted language as explained in
 !href target=wims_help module=help/wimsdoc WIMS technical documentation
.
 <p>
 If you are interested, you can ask
 !mailurl $wims_site_manager the manager of this WIMS site\
WIMS Modtool id
 for a developper's login/password pair to get the
 authentification for working with this tool.
 !exit
!endif

!if $mod=$empty
 In order to work on a module, you should first create it. To create a
 new module, please click on the appropriate links and fill-in the forms
 for this purpose.
 <p>
!endif

Please refer to
 !href target=wims_help module=help/wimsdoc WIMS technical documentation
 for the structure of a WIMS module and the syntax and format of its content.

<p>
You will find here 
href target=wims_help module=adm/createxo $wims_name_docoef

<p>
Special hints:
<ol>
<li><p>In order to debug a file, you can place a line
<pre>
$!debug ...
</pre>
in that file, where ... can be any text string. When you test your module, the
execution will stop at this line, with the content of ... shown to you. If
... includes variables, the latter will be substituted according to the usual
WIMS variable substitution rules.

</ol>

:end

