
<p>
!if $totalcnt>0
 !if $totalcnt>=$sellist
  You have $totalcnt modules under development.
  !href cmd=reply&jobreq=prop <small>Properties of my account</small>
  <p>
  !form reply
  Show only modules with address containing 
  <input type=text size=30 name=selectshow value="$selectshow">
  <input type=submit value=OK>
  !href cmd=help&special_parm=regex <sup>help</sup>
  </form> <p>
 !endif
 $table_header
 <caption>Click on the title of a module to work on it.
 !if $totalcnt>=$maxlist and $existcnt>=$maxlist
  <br>(list limited to $maxlist items)
 !endif
 </caption>
 $table_hdtr<th>Address<th>Title<th>Action<th>Description
 </tr>
 !for n in $existing
  !readdef wimshome/public_html/modules/devel/$auth_login/$n/INDEX
  $table_tr<td><small>
  !replace internal ~ by ~ $ in $n $
  !if ~ notin $n
   !href cmd=reply&jobreq=move&original=devel/$auth_login/$n [rename]
  !endif
  </small></td><td>
  !href cmd=reply&jobreq=flist&modreq=$n $title
  <td align=center><small>
  !href cmd=reply&jobreq=index&modreq=$n properties

  !href cmd=reply&jobreq=del&modreq=$n delete
  </small></td><td><small>$description</small></td>
  </tr>
 !next n
 $table_end
 !!!href cmd=reply&jobreq=create Create a new module
!!.&nbsp;
!! !href cmd=reply&jobreq=restore Restore a backup file
!!.
!set wims_menu_tail=!append line createnew,1,cmd=reply&jobreq=create\
 restore,1,cmd=reply&jobreq=restore\
 latex2wims,1,cmd=new&module=adm/latex2wims\
 to $wims_menu_tail
!set test_quicktool=!defof exists in wimshome/public_html/modules/adm/quicktool.fr/version
!if $test_quicktool=yes
 !set wims_menu_tail=!append line quicktool,1,cmd=new&module=adm/quicktool\
 to $wims_menu_tail
!else
 !set wims_menu_tail=!append line ,0,$name_noquicktool\
 to $wims_menu_tail
!endif
!else
 You have no module under development yet. Please
 !href cmd=reply&jobreq=create click here
 to create one, or
 !href cmd=reply&jobreq=restore restore a backup file
.
!endif

!set wims_menu_tail=!append line \
,0,\
account_property,1,cmd=reply&jobreq=prop\
to $wims_menu_tail

!reset target target1 target2 target3 target4 selectshow

