!! +exec+ +vardef+
tit:bound
type:$type_exec
syntax:!bound `vname' between [integer]`v1' and `v2' [default `defaultvalue']\
  !bound `vname' within `list' [default `defaultvalue']
mean:bound the range of the variable `vname'. Usually this is used on user-submitted variables.\
<br/>The first syntax is usually for numerical variables (integer or real,\
  defaults to real). In this case `v1' and `v2' supplies the lower and \
  upper bounds for the value of `vname'. <br/>\
  In the second syntax, the value of `vname ' is compared with\
  each item of `list'. If no occurrence is found, the value of\
  `vname' is replaced either by `defaultvalue' or the first item of `list',\
  according to whether `defaultvalue' is defined. <br/>\
  In any case, `defaultvalue' is optional.
