!! +exec+ +jump+
$lst_tit changeto $lst_titend$type_exec
  $(lst_syntax)changeto $emph file$emphend [$emph parm$emphend]</tt> <br>
  $lst_mean Abandon the current file, changing processing to $emph
  file$emphend. $emph file$emphend is as in $emph read$emphend.
  <br>And the parameter $emph parm$emphend can be accessed from within
  the new $emph file$emphend under the variable name $emph
  wims_read_parm$emphend.
