!! +var+ +exec+ +string+
tit:column
type:$type_both
alias:!columns
syntax:!column `numlist' of `string'
mean:Outputs selected (comma-separated) columns of a matrix `string',\
  according to `numlist'. Rows of the matrix can be separated either \
  by new lines or by semi-colon ``;''.

numlist:The output is separated by commas if only one column is selected, or\
  separated in the same way as the matrix `string' otherwise.
