!! +exec+ +var+ +string+
tit:embraced
type:$type_both
syntax:!embraced `opword string'
mean:executes an operation `opword' in each substring of `string' enclosed in a pair \
  of curly braces.\
  <p>\
  The curly braces in `string' can be nested, but the execution runs from outmost pair \
  to innermost pair.\
  </p><p>\
  Available `opword':\
  </p><ul>\
  <li><span class="tt">randitem</span>. Random item in every embraced text.</li>\
  <li><span class="tt">extract</span>. Extracts the first (outmost) embraced text.</li>\
  <li><span class="tt">delete</span>. Deletes all embraced contents (encluding the curly braces).</li>\
  </ul>
