!! +exec+ +var+ +string+
$lst_tit embraced$lst_titend$type_both<br>
  $(lst_syntax)embraced $emph opword string$emphend</tt> <br>
  $lst_mean executes an operation $emph opword$emphend in each
  substring of $emph string$emphend enclosed in a pair of curly braces.
  <p>
  The curly braces in $emph string$emphend can be nested, but
  the execution runs from outmost pair to innermost pair.
  <p>
  Available $emph opword$emphend: <ul>
  <li><tt>randitem</tt>. Random item in every embraced text.</li>
  <li><tt>extract</tt>. Extracts the first (outmost) embraced text.</li>
  <li><tt>delete</tt>. Deletes all embraced contents (encluding the
  curly braces).</li>
  </ul>

