!! +exec+ +var+ +string+
tit:evalsubst
type:$type_both
alias:evalsubstit, evalsubstitute, evaluesubst, evaluesubstit, evaluesubstitute
syntax:!evalsubst `name'=`val' in `expr'
mean:Manipulation of mathematical expressions: substitute variable `name' by `val' in `expr', \
  then evaluate the expression to a real number.  No regular expression is allowed in `name'. <br/>\
  See also the commands\
  $(ref1)cmdlist_mathsubst_&+cmd_choose=all$(ref2)cmdlist_mathsubst_">!mathsubst</a>,\
  $(ref1)cmdlist_replace_&+cmd_choose=all$(ref2)cmdlist_replace_">!replace</a>.
