!! +exec+ +var+
$lst_tit exec$lst_titend$type_both
  $lst_alias execute, run, call
  $(lst_syntax)exec $emph command parms$emphend</tt>
  $lst_mean execute external command $emph command$emphend with optional
  parameters $emph parms$emphend. $emph command$emphend must be a valid
  program name in the wims-public directory $emph bin$emphend. <br>
  When used as variable command, returns the output of the called program.
