!! +exec+ +file+
$lst_tit fileappend$lst_titend$type_exec
  $lst_alias appendfile<br>
  $(lst_syntax)fileappend $emph fname content$emphend</tt> <br>
  $lst_mean Append $emph content$emphend to file $emph fname$emphend.
  $emph fname$emphend is a file residing in the module's directory, under the 
  subdirectory $emph writable$emphend. <br>
  A new line will be added at the end of the $emph content$emphend.
  <p>
  Special case: if the file name starts with $emph getfile/$emphend, the file
  is written to the getfile subdirectory of the session. This file is then
  accessible via the command
  <pre>!href cmd=getfile&special_parm=fname_without_getfile_prefix</pre>,
  or a complete url
<pre>$$wims_ref_name?session=$$session&cmd=getfile&special_parm=fname_without_getfile_prefix</pre>

