!! +exec+ +loop+ +jump+
$lst_tit for$lst_titend$type_exec
  $(lst_syntax)for $emph var $emphend = $emph start $emphend to $emph end
  $emphend [step $emph st $emphend ]</span> <br/>or<span class="tt">
 $ !for $emph var $emphend from $emph start $emphend to $emph end $emphend
  [step $emph st $emphend ]</span> <br/>or<span class="tt">
 $ !for $emph var $emphend in $emph list$emphend<br/></span>
  ... (multi-line content)<br/>
  <span class="tt">!next</span>
  $lst_mean For loop. In the first two forms, $emph var $emphend goes from
  $emph start$emphend to $emph end$emphend, with optional step $emph
  st$emphend. <br/>
  In the last form, $emph var$emphend takes successively items in the list
  $emph list$emphend. $emph list$emphend is a list of items separated by
  commas. <br/>
  The command
  <pre>!break</pre>
  within the for loop breaks it. $emph continue $emphend is not yet
  implemented in this version. <br/>
  It is recommended that the variable name $emph var$emphend be added to the 
  <span class="tt">!next </span> line. This has no effect for the time being, but may be
  used in future versions of wims.
