!! +exec+ +html+
tit:formbar
type:$type_exec
alias:formradiobar, htmlbar, htmlradiobar
syntax:!formbar `name' from `n1' to `n2'\
!formradio `name' list selectlist'
mean:Creates a bar of radio buttons under a previously defined html form. <br/>\
  This bar should be arranged to represent values from small to big. No prompt is given \
  to the user, except the indication that left is smaller. In the parameters, `name' defines the\
  name field of the menu, and the values of the menu are either integers going from `n1' to `n2'\
  (in the first syntax), or items in the list `selectlist'. <br/>\
  The default of the menu will be the current value of the variable `&#36;name'.
