!! +exec+ +html+
$lst_tit formradio$lst_titend$type_exec
  $lst_alias htmlradio<br>
  $(lst_syntax)formradio $emph name$emphend from $emph n1$emphend
    to $emph n2$emphend prompt $emph promptlist $emphend<br>
    </tt>or<tt> <br>
    $!formradio $emph name$emphend list 
    $emph selectlist$emphend prompt $emph promptlist$emphend
    </tt> <br>
  $lst_mean Creates a radio button list menu under a previously defined html form. <br>
  This command speeds up the creation of radio buttoned menus, as well as simplifies
  the source files. In the parameters, $emph name$emphend defines the
  name field of the menu, and the values of the menu are either integers
  going from $emph n1$emphend to $emph n2$emphend (in the first syntax), or 
  items in the list $emph selectlist$emphend. <br>
  The optional parameter $emph promptlist$emphend can be used to generate
  user prompts for each items in the list. If $emph promptlist$emphend is
  empty or is shorter than $emph selectlist$emphend, the undefined prompts
  will be replaced by the value. If it is longer, the rest will be ignored.
  <br>
  The default of the menu will be the current value of the variable 
  $emph $$name$emphend.
  
  


