!! +exec+ +html+
tit:form
type:$type_exec
syntax:!form `cmdvar'
mean:Creates a html form pointing to the wims server. <br/>\
  Whenever possible, this command should be used instead of a direct use of\
  html tag `&lt;form>'. <br/>\
  This command will create a &lt;form> tag pointing to the wims server, adding\
  &lt;input> fields to pass session number (and other reserved things in the\
  future). In lines which follow, other input (or select) fields may be\
  added to the form. A final `!formend' must also be added by the\
  programmer. <br/> `cmdvar' is an optional parameter. Its value should be a valid\
  value for the variable `cmd'. In this case the value `cmdvar' will \
  be automatically submitted to the variable `cmd'. If this parameter is missing \
  or is invalid, then the programmer should add a `&lt;input type="hidden" name="cmd" value="...">' tag before the\
  final &lt;/form>. <p>\
  The target of the form can be controlled by the variable `wims_ref_target'. \
  It can also be defined via an optional word `target=...'. Note that in this case \
  the target must start with `wims_'.\
  </p><p>\
  The variable `wims_form_method' which must be either `get' or `post' controls the method \
  of the form. This method defaults to `post' for tool modules, and to `get' for all\
  other modules.\
  </p>
