!! +exec+ +html+
$lst_tit href$lst_titend$type_exec
  $(lst_syntax)href $emph parms text$emphend</tt>
  $lst_mean Creates a hypertext reference pointing to the wims server. <br>
  Whenever possible, this command should be used instead of a direct use of
  html tag $emph&lt;a href="...">$emphend. <br>
  $emph parms$emphend is the string of parameters to the call to wims server,
  which should not contain white spaces.
  Usually a $emph cmd=... $emphend pair should be at least present; on the
  other hand, the session number and prefered language will be directly
  added by the server. <br>
  $emph text$emphend is the text on which the hypertext link sits. It can be
  any text or a &lt;IMG ...> tag, but dynamic insertions are not accepted yet.
  <br>There is no need to add the end tag $emph &lt;/a>$emphend.
  <p>The target of the reference can be controlled via the variable 
  $emph wims_ref_target$emphend. It can also be defined via an optional word
  $emph target=...$emphend. Note that in this case the target must start with 
  $emph wims_$emphend.
  
