!! +exec+ +jump+
$lst_tit ifval$lst_titend$type_exec
  $(lst_syntax)if $emph string1 relation string2 $emphend<br/></span>
  ... (multi-line content)<br/>
 $ <span class="tt">!endif</span>
  $lst_mean Same as $(ref1)cmdlist_if_$(ref2)cmdlist_if_">if</a>,
  but $emph =$emphend ($emph==$emphend),
  $emph!= $emphend compares the
  numerical values of $emph string1$emphend and $emph string2$emphend
  rather than the strings themselves.
