!! +exec+ +ins+ +var+
$lst_tit instexstatic$lst_titend$type_pexec
  $lst_alias instexst, staticinstex, stinstex<br>
  $(lst_syntax)instexstatic $emph gifname texsource $emphend</tt> <br>
  $lst_mean This command is obsolete, and will be dropped in future versions.
  Use 
  $(ref1)cmdlist_instex_&+cmd_choose=all$(ref2)cmdlist_instex_">!instex</a>
  instead.

!exit

  $lst_mean This is similar to 
  $(ref1)cmdlist_instex_&+cmd_choose=all$(ref2)cmdlist_instex_">!instex</a>,
  to the difference that no variable substitution is performed on 
  $emph texsource$emphend, and that the name of the gif file
  $emph gifname$emphend shoule be given (together with the extension 
  $emph .gif$emphend). $emph gifname$emphend should be the name of a file in
  the module's home directory. <br>
  Wims will produce the gif file if it does not exist, or if the file
  containing the command is newer than the gif file. No TeX is called in the
  subsequent requests, thus greatly improving performance. <br>
  When $emph instexstatic$emphend is used as a variable command, it returns
  the tag string $emph &lt;IMG SRC=...>$emphend, which can be inserted
  elsewhere in the document.
  <p>
  <b><font color=red>Important</font></b>.
  Since version 0.11.5, $emph gifname$emphend is optional, and
  <tt>!instex</tt> will automatically use static insertion whenever there is
  no real variable substitution in $emph texsource$emphend. Therefore
  <tt>!instexstatic</tt> is no longuer really necessary, and is provided only
  for backward compatibility. so <font color=red><b>avoid using
  it!</b></font> Use <tt>!instex</tt> instead.

