!! +var+ +exec+ +string+
tit:leveldata
type:$type_both
alias:levelpoints
syntax:!leveldata size `xsize,ysize' ranges `x1,x2,y1,y2' function `f(x,y)' [levels `l1,l2,...']
mean:Computes coordinates of points on the level curve of `f(x,y)', at levels `l1,l2,...'\
 (defaults to one level 0). <p>\
  The computation is made from `(x1,y1)' to `(x2,y2)', and points are computed as integer\
  positions in a picture with size `xsize,ysize'. </p><p>\
  Order of the fields is not important. All the fields except levels are mandatory.\
  </p>
