!! +exec+ +var+ +vardef+
$lst_tit module$lst_titend$type_both
  $(lst_syntax)module $emph defname$emphend $emph modname$emphend</tt>
  $lst_mean Returns the definition for $emph defname$emphend of the module
  $emph modname$emphend. The most common use of this command is to get the
  title of a module ($emph defname$emphend is then <tt>title</tt>). <br>
  The INDEX file of the module $emph modname$emphend will be parsed to look
  for the definition of $emph defname$emphend.


