!! +var+ +exec+ +string+
tit:product
type:$type_both
alias:!prod, !multiply
syntax:!product `fn' for `v'=`v1' to `v2' [step `st']\
$ !product `fn' for `v' in `v1,v2,v3,...'
mean:Computes the product of a function `fn(v)' with variable `v' replaced \
  successively by values `v1', ..., `v2'. <p>\
  In the second syntax, the values are given with respect to each item in the list `v1,v2,...'.\
  </p>
