!! +var+ +random+
$lst_tit randint$lst_titend$type_var
  $(lst_syntax)randint $emph n1$emphend ,$emph n2$emphend</tt> <br>
  $lst_mean Returns a random integer between $emph n1 $emphend and $emph
  n2 $emphend (inclusive). <br>
  Substitution and evaluation are done on $emph n1 $emphend and $emph n2
  $emphend before applying random. <br>
  If $emph n2 $emphend is missing, returns random integer between $(m_pm)1 and
  $emph n1 $emphend (inclusive). <br>
  If both $emph n1 $emphend and $emph n2 $emphend are missing, returns 0.
  <br>
  You can also type <tt>!random n1,n2 repeat i</tt> to repeatedly generate
  $emph i$emphend random numbers.

