!! +exec+ +var+ +string+
$lst_tit rawmath$lst_titend$type_both
  $(lst_syntax)rawmath $emph expr$emphend</tt> <br>
  $lst_mean Translate the mathematical expression $emph expr$emphend,
  possibly with common user errors, into a machine-understandable
  mathematical expression. <br>
  It will replace $emph (x+1)(x-1)$emphend into $emph (x+1)*(x-1)$emphend,
  $emph 5x^3$emphend into $emph 5*x^3$emphend, etc.


