!! +exec+ +var+ +string+
tit:rawmath
type:$type_both
syntax:!rawmath `expr'
mean:Translate the mathematical expression `expr', possibly with common user errors, \
  into a machine-understandable mathematical expression. <br/>\
  It will replace `(x+1)(x-1)' into `(x+1)*(x-1)', `5x^3' into `5*x^3', etc.\
  More precisely,\
 <ul><li>\
  Replace some badcharacters as **, ², ³.\
   </li><li>translate ++, +-, -+, ... into one sign\
   </li><li>\
   translate | | in abs\
   </li><li>\
   replace new lines or tabs by spaces\
   </li><li>\
   add zero in case of decimal digits if necessary: for example, replace 4. by 4.0  and .5 -> 0.5\
   </li><li>\
   replace justapositions by multiplications if rawmatheasy=yes\
   </li></ul>
