!! +exec+ +var+ +string+
$lst_tit reaccent$lst_titend$type_both
  $(lst_syntax)reaccent $emph string$emphend</tt>
  $lst_mean Replace accented letter compositions in $emph string$emphend
  by accented letters (replacing <tt>e'</tt> by é, <tt>a`</tt> by à, 
  <tt>i"</tt> by ï, <tt>o^</tt> by ô, etc.)
  The only exception is that ç and Ç are composed from <tt>c~</tt>
  and <tt>C~</tt> respectivement.

