!! +exec+ +var+ +string+
$lst_tit reinput$lst_titend$type_both<br>
  $(lst_syntax)reinput $emph string$emphend</tt> <br>
  $lst_mean Prepares $emph string$emphend to be inserted into a form input
  or textarea.
  <p>
  Browsers translate &amp; primitives into corresponding (special) characters
  even when these primitives occur in input or textarea fields. Also, if 
  $emph string$emphend contains html tags, they may confuse browsers. You can
  use this command on the string (usually derived from an earlier user input)
  before inserting them back into a input or textarea, to avoid the above
  problems.
  

