!! +exec+ +var+ +string+
tit:reinput
type:$type_both
syntax:!reinput `string'
mean:Prepares `string' to be inserted into a form input or textarea.\
  <p>\
  Browsers translate &amp; primitives into corresponding (special) characters\
  even when these primitives occur in input or textarea fields. Also, if\
  `string' contains html tags, they may confuse browsers. You can\
  use this command on the string (usually derived from an earlier user input)\
  before inserting them back into a input or textarea, to avoid the above problems.\
  </p>
