!! +var+ +string+
$lst_tit rename$lst_titend$type_both
  $(lst_syntax)rename $emph f$emphend</span>
  $lst_mean Changes the reference to a file $emph f$emphend, such as a
  graphics file reachable by direct http, into one with a different name using
  the method <span class="tt">!getfile</span>.
  <p>
  This command is useful with exercises where important information is carried
  by multimedia files (pictures, audios, movies). It can be used to hide the
  name of the multimedia file that otherwise would give clues to the solution
  of the problem.
  </p><p>The renamed file must be located within the module, and the 
  filename $emph f$emphend should start with $emph$$module_dir$emphend</span>.
  </p><p>
  The command returns a string which is the new URL. The file is not
  effectively copied or renamed on the server.
  </p>
