!! +var+ +exec+ +string+
tit:select
type:$type_both
syntax:!select `data' where `condition'
mean:Outputs rows of a matrix `data', according to `condition'. \
  Rows of the matrix can be separated either by new lines or by semi-colon `;'. <p>\
  The condition can use words <span class="tt">column 1</span>, <span class="tt">column 2</span>, etc. to\
  designate comma-separated columns in each row.\
  </p>
