!! +exec+ +var+ +string+
$lst_tit singlespace$lst_titend$type_both
  $(lst_syntax)singlespace $emph string$emphend</tt> <br>
  $lst_mean Returns $emph string$emphend with all space characters (space, 
  tab, newline) replaced by ' ', and multiple occurrences of space characters
  collapsed into single one. <br>
  Leading and ending spaces are not removed. You can use this command in 
  conjunction with
  $(ref1)cmdlist_trim_$(ref2)cmdlist_trim_>trim</a> if you want also to
  remove leading and ending spaces. <br>
  This command is especially useful for comparisons between multi-word
  strings.

