!! +var+ +exec+ +string+
$lst_tit solve$lst_titend$type_both
  $lst_alias rootof
  $(lst_syntax)solve $emph fn$emphend for $emph v$emphend=$emph v1$emphend
  to $emph v2$emphend</tt>
  $lst_mean Find out (real simple) roots of the function/equation
  $emph fn$emphend
  for the variable $emph v$emphend between $emph v1$emphend and
  $emph v2$emphend. <p>
  $emph fn$emphend may have several roots in the interval [v1,v2], but
  roots too close to each other may be overlooked.

