!! +var+ +exec+ +string+
tit:values
type:$type_both
syntax:!values `fns' for `v'=`v1' to `v2' [step `st']\
$ !values `fns' for `v' in `v1,v2,v3,...'
mean:Outputs a list of values of `fns' with variable `v' replaced successively by values \
  `v1', ..., `v2'. <p>In the second syntax, the values are given with respect \
  to each item in the list `v1,v2,...'. </p><p>\
  `fns' may be a comma-separated list of functions. </p><p>\
  This command can also be used to make recursions. If the functions\
  `fns' contain a variable named `last', this variable\
  will take the value of the last step each time. And the starting value\
  can be put into the WIMS variable <span class="tt">&#36;recursion_start</span>.\
  </p>
