!! +exec+ +jump+
tit:while
type:$type_exec
syntax:!while `string1 relation string2'<br/>
  ... (multi-line content)<br/>
 !endwhile
mean:Conditional branching: execute the multi-line content between\
  `!while' line and `!endwhile' line, until `relation' is no longer verified.\
  The leading and trailing spaces of `string1' and `string2' will be stripped\
  before making comparisons.\
  <p>\
  The syntax is the same as for\
  $(ref1)cmdlist_if_$(ref2)cmdlist_if_">if</a>.\
  </p>
