!! +exec+ +jump+
$lst_tit while$lst_titend$type_exec
  $(lst_syntax)while $emph string1 relation string2 $emphend<br></tt>
  ... (multi-line content)<br>
 $ <tt>!endwhile</tt> <br>
  $lst_mean Conditional branching: execute the multi-line content between
  $emph!while$emphend line and $emph!endwhile$emphend line, until $emph
  relation$emphend is no longer verified.
  The leading and trailing spaces of $emph string1$emphend and $emph
  string2$emphend will be stripped before making comparisons.
  <p>
  The syntax is the same as for
  $(ref1)cmdlist_if_$(ref2)cmdlist_if_>if</a>.
