
$table_header
<caption>Valid participant data fields</caption>
$table_hdtr<th>$wims_name_name</th><th><th>Meaning</th></tr>
$table_tr<td><tt class="wims_code_variable">login</tt></td><td>$wims_name_Login</td></tr>
!if $special_parm!=upload
$table_tr<td><tt class="wims_code_variable">name</tt></td><td>last name and first name (in that order, two columns)</td></tr>
!endif
$table_tr<td><tt class="wims_code_variable">lastname</tt></td><td>family name</td></tr>
$table_tr<td><tt class="wims_code_variable">firstname</tt></td><td>first (given) name</td></tr>
$table_tr<td><tt class="wims_code_variable">password</tt></td><td>password of the participant, download always in
	special crypted form, but can be uploaded uncrypted.</td></tr>
$table_tr<td><tt class="wims_code_variable">email</tt></td><td>email address</td></tr>
$table_tr<td><tt class="wims_code_variable">regnum</tt></td><td>registration number</td></tr>
$table_tr<td><tt class="wims_code_variable">photourl</tt></td><td>Photo URL</td></tr>
$table_tr<td><tt class="wims_code_variable">comments</tt></td><td>comments about the participant</td></tr>

!if $special_parm!=upload
$table_tr<td><tt class="wims_code_variable">allscore</tt></td><td>all scores and averages</td></tr>
$table_tr<td><tt class="wims_code_variable">averages</tt></td><td>average score (server score and manual grades)</td></tr>
$table_tr<td><tt class="wims_code_variable">average1</tt></td><td>average of server-attributed scores</td></tr>
$table_tr<td><tt class="wims_code_variable">average2</tt></td><td>average of teacher-attributed grades</td></tr>
$table_tr<td><tt class="wims_code_variable">sheets</tt></td><td>scores of all worksheets (one by one)</td></tr>
$table_tr<td><tt class="wims_code_variable">sheet1,sheet2,...</tt></td><td>score of worksheet 1, worksheet 2, ...</td></tr>
$table_tr<td><tt class="wims_code_variable">exams</tt></td><td>scores of all exams</td></tr>
$table_tr<td><tt class="wims_code_variable">exam1,exam2,...</tt></td><td>scores of exam 1, exam 2, ...</td></tr>
$table_tr<td><tt class="wims_code_variable">manuals</tt></td><td>all manual grades (one by one)</td></tr>
!else
$table_tr<td><tt class="wims_code_variable">participate (in case of gateways only, reserved to the administrator)</tt></td></td><td>number of classes 
as abcdefg/1/101
wher rabcdefg is the number of the gateway. If there is several classes,
seperate them by spaces.</td></tr>
!endif

$table_tr<td>manual1,manual2,...</td><td>manual grade 1, 2, ...</td></tr>
$table_tr<td><tt class="wims_code_variable">var_xxx</tt></td><td>technical variable <tt>xxx</tt></td></tr>

$table_end <p>

Unrecognized fields will be ignored.Technical variables can be used to make 
selective restrictions on worksheets and exams.
<p>
!if $special_parm=upload
In case of the field <tt class="wims_code_words">participate</tt>, one may add classes but not suppress them.
!endif

