
$table_header
<caption>Valid participant data fields</caption>
$table_hdtr<th>$wims_name_name</th><th><th>Meaning</th></tr>
$table_tr<td><span class="tt wims_code_variable">login</span></td><td>$wims_name_Login</td></tr>
!if $special_parm!=upload
$table_tr<td><span class="tt wims_code_variable">name</span></td><td>last name and first name (in that order, two columns)</td></tr>
!endif
$table_tr<td><span class="tt wims_code_variable">lastname</span></td><td>family name</td></tr>
$table_tr<td><span class="tt wims_code_variable">firstname</span></td><td>first (given) name</td></tr>
$table_tr<td><span class="tt wims_code_variable">password</span></td><td>password of the participant, download always in
	special crypted form, but can be uploaded uncrypted.</td></tr>
$table_tr<td><span class="tt wims_code_variable">email</span></td><td>email address</td></tr>
$table_tr<td><span class="tt wims_code_variable">regnum</span></td><td>registration number</td></tr>
$table_tr<td><span class="tt wims_code_variable">photourl</span></td><td>Photo URL</td></tr>
$table_tr<td><span class="tt wims_code_variable">comments</span></td><td>comments about the participant</td></tr>
$table_tr<td><span class="tt wims_code_variable">external_auth</span></td><td>login for an external authentification</td></tr>

!if $special_parm!=upload
$table_tr<td><span class="tt wims_code_variable">allscore</span></td><td>all scores and averages</td></tr>
$table_tr<td><span class="tt wims_code_variable">averages</span></td><td>average score (server score and manual grades)</td></tr>
$table_tr<td><span class="tt wims_code_variable">average1</span></td><td>average of server-attributed scores</td></tr>
$table_tr<td><span class="tt wims_code_variable">average2</span></td><td>average of teacher-attributed grades</td></tr>
$table_tr<td><span class="tt wims_code_variable">sheets</span></td><td>scores of all worksheets (one by one)</td></tr>
$table_tr<td><span class="tt wims_code_variable">sheet1,sheet2,...</span></td><td>score of worksheet 1, worksheet 2, ...</td></tr>
$table_tr<td><span class="tt wims_code_variable">exams</span></td><td>scores of all exams</td></tr>
$table_tr<td><span class="tt wims_code_variable">exam1,exam2,...</span></td><td>scores of exam 1, exam 2, ...</td></tr>
$table_tr<td><span class="tt wims_code_variable">manuals</span></td><td>all manual grades (one by one)</td></tr>
!else
$table_tr<td><span class="tt wims_code_variable">participate (in case of gateways only, reserved to the administrator)</span></td></td><td>number of classes 
as abcdefg/1/101
wher rabcdefg is the number of the gateway. If there is several classes,
seperate them by spaces.</td></tr>
!endif

$table_tr<td>manual1,manual2,...</td><td>manual grade 1, 2, ...</td></tr>
$table_tr<td><span class="tt wims_code_variable">var_xxx</span></td><td>technical variable <tt>xxx</tt></td></tr>

$table_end

Unrecognized fields will be ignored.Technical variables can be used to make 
selective restrictions on worksheets and exams.

!if $special_parm=upload
<p>
In case of the field <span class="tt wims_code_variable">participate</span>, one may add classes but not suppress them.
</p>
!endif

