
<center><font size="+1"><b>Relaciones con la clase <em><font color=blue>
$nei_description</font></em> de
<em><font color=blue>$nei_institution</font></em>.</b>
</font><center>
</center>(Profesor:
<a href="mailto:$nei_email?subject=Vecindad de clase
relations">$nei_supervisor</a>)</center>
<p>
<b>Relación de vecindad. </b> <small>[
!href cmd=help&special_parm=neibordecl Ayuda
 ]</small> 
 <p>La clase <em><font color=blue>
$nei_description</font></em>
!if $wims_class notitemof $nei_sup,$nei_part
 no ha declarado la suya como vecina.
!else
 le acepta como vecina,
 !if $wims_class isitemof $nei_sup and $wims_class isitemof $nei_part
  para profesor y participantes.
 !else
  !if $wims_class isitemof $nei_sup
   para el profesor.
  !else
   para los participantes.
  !endif
 !endif
!endif
<p>
!form reply
¿Acepta usted la clase <em><font color=blue>
$nei_description</font></em> como vecina suya?
!formselect nlevel from 0 to 3 prompt No, Para el profesor,\
	Para los participantes, Para profesor y participantes
<input type=submit value=Guardar> 
</form> <p>


!if ($nei isitemof $n_sup,$n_part and $wims_class isitemof $nei_sup,$nei_part) or \
   all isitemof $nei_sup,$nei_part
 <p><b>Importación de recursos. </b> <small>[
 !href cmd=help&special_parm=import Ayuda
 ]</small>
 <p>Puede
 !href cmd=reply&job2=import importar recursos
 de la clase <em><font color=blue>
$nei_description</font></em>.
 <p>
!endif

!if  $nei isitemof $n_sup
<p>
<b>Compartir recursos.</b> 
<small>[
!href cmd=help&special_parm=share Ayuda
]</small>
<ul>
!endif

!if $wims_class isitemof $nei_sup and $nei isitemof $n_sup
 <li>
 !if $nsharable=$empty
  No hay ningún tipo (nuevo) de recursos en la clase
  <em><font color=blue>
$nei_description</font></em> que le autorice a compartir. 
 !else
 La clase <em><font color=blue>
$nei_description</font></em> le <b>autoriza</b> a compartir sus
  !set names=!replace , by , $$name_ in $$name_$nsharable
  <em>$names</em>.
  !href cmd=reply&job2=addshare Haga click aquí para aceptar
.
 !endif
 <p>
!endif

!if $nei isitemof $sharing_all
 Comparte ya los recursos siguientes de la clase <em><font color=blue>
$nei_description</font></em>:<ul>
 !for r in $sharelist
  !if $(sharing_$r)=$nei
   <li><b><em>$(name_$r)</em></b>. 
   !href cmd=reply&job2=stopshare&stoprec=$r Poner fin a la relación de compartir
. <small>[
   !href cmd=help&special_parm=stopshare Ayuda
   ]</small>
  !endif
 !next r 
 </ul>
 <p>
!endif
 </li>
!if $nei isitemof $n_sup and $sharablelist!=$empty
<li>
 !form reply
 <input type=hidden name=changeshare value=yes>
 Elija los recursos que <b>autoriza</b> a compartir a la clase <em><font color=blue>
$nei_description</font></em> (<i>seleccione y después pulse en <tt>Guardar</tt></i>): <small>[
 !href cmd=help&special_parm=sharable Ayuda
 ]</small>
<p>
 !set sh=!nospace $sharablelist
 !set sh=!replace , by , $$name_ in $$name_$sharablelist
 !formcheckbox mksharable list $sharablelist prompt $sh
 <input type=submit value=Guardar>
 </form> <p>
!if $nsharable!=$empty
<p><b>ATTENTION</b> La clase <em><font color=blue>
$nei_description</font></em>
le autoriza a compartir ciertos recursos. 
No debe autorizarle a compartir los mismos recursos para no causar confusión. 
Comience por entenderse con ella y con todas las clases con las que usted 
quiera compartir recursos.
!endif
 </li>
!endif

</ul>

!reset stoprec
