
<center><h3>Dejar de compartir un recurso
</b><small>
!href cmd=help&special_parm=stopshare Ayuda
</small>
</h3></center>

!if $stoprec!=$empty and $(sharing_$stoprec)=$nei and \
	$(me_$(stoprec)cnt)>0 and $me_testcnt>0 and confirm!=yes and \
	$stoprec isitemof $nosharelist
 <b>ATENCIÓN</b>. Su clase tiene un registro de actividades activo y los
 recursos compartidos no están vacíos. Si deja de compartir este recurso
 ahora, ya no podrá volver a compartirlo más tarde.
 <p>
 ¿Está seguro de querer dejar de compartir definitivamente este recurso?
 <p><center><font size=+1> 
 !href cmd=reply&stoprec=$stoprec&confirm=yes Sí; dejar de compartirlo.
 &nbsp;&nbsp;
 !href cmd=reply&job2=def No; dejarlo en su estado actual.
 </font></center> <p>
!else
 Manipulation error: You should never land here.
!endif

