
!if $title=$empty
 $name_error1 <tt><b>$addr</b></tt>.
 !href cmd=reply&job2=first $wims_name_back2
.
 !exit
!endif

!if $muauto iswordof update install
 !if $output!=ok
  $name_error2 <tt><b>$addr</b></tt>.
 !else
  $name_install <tt><b>$addr</b></tt>: $name_successful.
  !href target=wims_test module=$addr $name_test
.
  $name_need
  !href cmd=reply&job=mkindex $name_rebuild
.
 !endif
 !href cmd=reply&job2=first $wims_name_sitegestion
.
 !reset muauto
 !exit
!endif

$table_header
<caption>
!if $vtest=$empty
 $name_newmodule <tt><b>$addr</b></tt> <br>
 !href cmd=reply&job2=one&muauto=install $name_Install
!else
 $name_version <tt><b>$addr</b></tt> <br>
!set wims_ref_class=wims_button
 !href cmd=reply&job2=one&muauto=update $name_Update
!endif
&nbsp;&nbsp;&nbsp;
!set wims_ref_class=wims_button
!href cmd=reply&job2=first $wims_name_giveup
</caption>
$table_tr<th align="right">$wims_name_publish_center</th><td>$mu_name</td></tr>
$table_tr<th align="right">$wims_name_title</th><td>$title</td></tr>
$table_tr<th align="right">$wims_name_Description</th><td>$description</td></tr>
$table_tr<th align="right">$wims_name_Type</th><td>$category</td></tr>
$table_tr<th align="right">$wims_name_Version</th><td>$version</td></tr>
!if $vtest!=$empty
 ($name_versus $vtest)
!endif
$table_tr<th align="right">$wims_name_Language</th><td>$language</td></tr>
$table_tr<th align="right">$wims_name_Author</th><td>
  <a href="mailto:$address">$author</a></td></tr>
!if $translator!=$empty
 $table_tr<th align="right">$wims_name_Translator</th><td>
  <a href="mailto:$translator_address">$translator</a>
 </td></tr>
!endif
$table_tr<th align="right">$wims_name_require</th><td>$require</td></tr>
!if $news!=$empty
 $table_tr<th align="right">$name_Changes</th><td>
 <small><pre>$news</pre></small></td></tr>
!endif
$table_end <p>

