
<center><h2>The structure of an institution interface</h2></center>

<a name=institution>
An institutional structure is a multi-level lattice of a group of virtual
classes. Each virtual class in the lattice is called a <em>work zone</em>,
or <em>zone</em>.
<p>
<a name=portal>
The structure of an institution is built below a unique zone called
<em>portal</em>. This is the common entrance point, it serves also for
global management for the institution. No real teaching work should take
place in this zone.
<p>
<a name=level>
Zones immediately below the portal are <em>levels</em>. A level corresponds to
a set of students sharing the same annual programs. 
<p>
The role of levels is essentially to separate things that have no relation
between them.
Student logins are not
accepted for levels, nor teaching works.
<p>
<a name=class>
<em>Classes</em> are immediately below each level. A class is a group of
students sharing the same teaching time table. 
<p>
Students should log in to classes. Each student may have one or more classes.
<p>
<a name=program>
Immediately below a level are also <em>programs</em>. Each program is a
gathering point of teaching resources shared by one or several classes in
the level.
<p>
Students cannot log in to programs. Teachers can log to programs (as
supervisors) in order to prepare teaching materials.
<p>
<a name=course>
<em>Courses</em> are zones of lowerest level. Each course belongs to a
program, as well as to a class. One can think that to every pair
{program,class} may correspond a course.
<p>
Teaching resources of a program are shared by all its courses. A student in
a class can navigate between the courses of the class. Daily student works
are done in courses.
<p>
A course has a unique set of teaching resources, and a unique time table.
<p>
<a name=icourse>
A program can also have <em>Interclass courses</em>. Such a course only
belongs to a program, and students from any class can register to an
interclass course. This can be used for optional teaching programs.
<p>
<a name=test>
Each program can also have a special course, called <em>test zone</em>.
Teachers can prepare experimental teaching resources in the text zone, then
export them to the program when finished. Everything in the test zone is
invisible to the students.

