
<center><h3>验证文件的准许权限</h3></center>

!if $bad$writable$execable$baduser$bad_wrapper$noexec=$empty
 WIMS是按安全的模式设置文件的准入权限.
 !sh rm -f $wims_home/log/unsecure
!else
 <b><blink>警告!</blink></b>
 !if $bad!=$empty
  下列文件或目录可被他人读取, 而它们应该是不可读取的:
<pre>
!words2lines $bad
</pre> <p>
 !endif
 !if $writable!=$empty
  !if $writcnt>=50
<pre>
!words2lines $writable

......
</pre>
  !else
  下列文件或目录可被他人写入, 而它们应该是不可写入的:
<pre>
!words2lines $writable
</pre>
  !endif
  <p>
 !endif
 !if $execable!=$empty
  !if $execnt>=50
   有大量文件或目录可被他人执行, 而它们应该是不可执行的. <p>
   此问题只是部分被纠正. 请
   !href cmd=reply 重复此过程
   (直至不再有文件或目录具有错误的准入权限).
   <p>本次被改正的准许权限表:
<pre>
!words2lines $execable

......
</pre>
  !else
  下列文件或目录可被他人执行, 而它们应该是不可执行的:
<pre>
!words2lines $execable
</pre>
  !endif
  <p>
 !endif
 !if $baduser!=$empty
  !if $usercnt>=50
   有大量文件或目录不是WIMS拥有的.
   <p>下面列举了一部分.
<pre>
!words2lines $baduser

......
</pre>
  !else
   以下文件或目录不是WIMS拥有的.
<pre>
!words2lines $baduser
</pre>
  !endif
  <p>
  WIMS目录内不能有属于其他人的文件.
  你必须检查这些文件的来源, 然后删除它们或改变它们的拥有者.
  <p>
 !endif
 !if $bad_wrapper=true
  重要安全提示: 请给文件<tt>public_html/bin/ch..root</tt>,
  <tt>public_html/bin/wrap..exec</tt>, <tt>bin/wimsd</tt>以正确的拥有者. 
  这对安全性十分重要. 为此你应该作为root执行 bin/wrapuid.
  <p>
  !writefile wimshome/log/unsecure yes
 !else
  !sh rm -f $wims_home/log/unsecure
 !endif
 !if $noexec!=$empty
  以下的文件或目录可被任何人执行, 这是不可以的.
  <pre>
!words2lines $noexec
</pre>
  <p>
 !endif
 !if $writcnt<50 and $execnt<50 and $usercnt<1 and $bad_wrapper=$empty
  这些错误的权限使你的机器有安全隐患. 目前这些问题已被纠正, 然而你仍需经常检查准入权限.
  如果同类问题再次出现, 你应该检查你的系统是否被入侵过, 服务器的数据是否被做了手脚.
 !endif
!endif

