
<center>
!form reply
请输入服务器管理员的密码:<p>
<input size=24 type=password name=auth>
<input type=submit value=提交>
</form></center>

!if $passone!=$empty
 由于你没有定义管理员的密码, 服务器生成了仅供本次使用的一次性密码.
 你可在WIMS服务器的文件<tt>$wims_home/$oncename</tt>里找到这个密码.
 请把你在这个文件里读到的密码输入上面框内.
 <p>
 如果你要定义一个永久性的密码 (其安全性不及一次性密码),
 你可将此密码存入<tt>$wims_home/log/.wimspass</tt>. 但是你<b>必须</b>使这个文件只能由你一个人读取!
!else
 你已经定义了一个永久性的服务器管理员密码. 请注意, 你也可以使用一次性密码, 且后者更安全.
 <p>
 为了切换到一次性密码, 你只要删除服务器里的文件<tt>$wims_home/log/.wimspass</tt>.
!endif

<p>
请你在操作管理员密码时要非常小心. 以管理员身份的入侵可以破坏你的服务器的所有数据!

