!set wims_name_adddevel=加入一个新开发者
!set wims_name_develaccount=开发者表

!if $job2 iswordof mod1 mod2 del1
 !read developer/$job2.phtml
 !set wims_menu_items=!append line develaccount,1,cmd=reply&job2=first\
to $wims_menu_items
 !exit
!endif

<p>$table_header
<caption>本服务器上注册的模块开发者</caption>
$table_hdtr
<th>$wims_name_Login<th>$wims_name_name<th>$wims_name_Action
!for d=1 to $devcnt
 !distribute lines $(drec$d) into login,passwd,name,email
 $table_tr
 <td align=center>$login
 <td align=center>
 <a href="mailto:$email">$name</a>
 <td nowrap><small>
 !href cmd=reply&job2=del1&devno=$d $wims_name_erase
&nbsp;
 !href cmd=reply&job2=mod1&devno=$d $wims_name_properties
&nbsp;
 !href module=adm/modtool&login=$login&passwd=$passwd&jobreq=modname 访问
</small>
!next d
$table_end <p>

!set wims_menu_items=!append line adddevel,1,cmd=reply&job2=mod1&devno=0\
to $wims_menu_items

!form reply
<input type=hidden name=job2 value=pub>
允许在服务器的本地子目录里建立模块的开发者:
(输入登录名) <br>
<input size=50 name=devpublisher value="$devpublisher">
<input type=submit value="$wims_name_tosave">
</form>

!reset job2,devno,devlogin,devpasswd,devname,devemail,devpublisher

