<p>
Quicktool 是一个管理模块. 可供 Modtool 的开发者用来创建语言练习.
它并非标准的发布版.
但利用它创建的练习完全与 WIMS 的稳定版相容.

<p>


!form reply

!formcheckbox job2 list 1 prompt 下载 Quicktool
以后可使用 <a href="http://download.wimsedu.info">http://download.wimsedu.info</a>

或 <a href="http://sourcesup.cru.fr/frs/?group_id=410">http://sourcesup.cru.fr/frs/?group_id=410</a>

<p> 
 如果你要下载开发版, 请用命令行下载 :
 <pre>
 cd public_html/modules/adm
 svn co https://subversion.cru.fr/wimsmodules/trunk/modules/adm/quicktool.fr ; 
 find quicktool.fr -name .svn -exec rm -rf '{}' \;
</pre>

!!<center> <input type=submit value=OK></center>
</form>
