<p>你可以下载 Shtooka 项目的某些包的 mp3 文件.
<p>
如果需要调用它们的模块在 WIMS 服务器中被频繁使用, 你就应该下载它们.
否则的话, 这些模块要到网站 http://shtooka.net 去搜索 mp3

!form reply
 <input type=hidden name=job2 value=添加>

!!!formradio packs list $swac_list
<center> <input type=submit value="生成索引">
</center>
</form>

为了下载它们, 最好是执行脚本文件
<tt>$wimshome/bin/swac </tt> 里的命令行. 它会把一些 swac 包安装在合适的地方. 
<p>
<small>由于 WIMS 的文件是使用 iso-latin 编码的, 
因此还不能使用西里尔文包.</small>

