
<center><h3>WIMS服务器软件更新</h3></center>

!if $error!=$empty
 !if $error=no_script
  对不起, 从<tt>$download</tt>下载新版WIMS失败.
  请以后再试.
 !endif
 
 !goto end
!endif

!if true iswordof $testing
<font color=red><em>测试模式.
只写到测试目录.</font></em>
<p>
!endif

!if $lockcheck != $empty
 WIMS的系统更新正在进行. 这是当前的脚本输出概要.
 <small><pre>
 !sh cat ../log/update.log
 </pre></small>
 <a name=updateend></a>
 !href cmd=resume#updateend 更新输出
.
 !goto end
!endif

!if $job2=check
 最近更新概要:
 (出错时请将它发送给$wims_maintainer.)
 <small><pre>
 !sh cat ../log/update.log
 </pre></small>
 !goto check
!endif

!if $job2=check2
 最近更新的详细输出: 
 (出错时请将它发送给$wims_maintainer.)
 <small><pre>
 !mexec scripts/cat_update2.sh
 </pre></small>
 !goto check
!endif

!if $pubversion=$empty
 对不起, WIMS下载网站<tt>$download</tt>连接不上.
 !goto end
!endif

本WIMS站目前版本号是$wims_version.

!if $pubversion=$wims_version
这是软件的最新版本. 你不需更新.
 update.
 !goto check
!endif

最新的公开版本是$pubversion.
!if $recentversion<$thisversion
 你比公开版还要新! 不需更新.
 !goto check
!endif

<p>
!href cmd=reply&job=update&job2=confirm 点击这里
 以从<tt>$download</tt>下载WIMS $pubversion更新服务器.
<p><b><font color=red>警告!</font></b>这会使服务器暂时不能用.
<em>当服务器忙碌时不要更新.</em>
<p>
<b>注意</b>. 更新服务器不会影响你的本地资源
(班级, 练习, 文件, 开发中的模块).
<p>
<b><font color=red>重要</font></b>. 在软件更新后, 你需要检查文件的准入权限.

:check
!if $logcheck!=$empty
<p>
 最近更新的输出:
 !href cmd=resume&job2=check 概要
,
 !href cmd=resume&job2=check2 详情
.
!endif
:end
!reset job2

