
Om naar binnen te gaan als <b><font
color=green>$mb_title</font></b> 
<em>beheerder</em>,geef het wachtwoord van de beheerder
<p>
!set wims_form_method=post
!form new
<input type=hidden name=module value="adm/forum/mboard.en">
<input type=hidden name=job value="authuser">
<input type=hidden name=forum value=$forum>
<input type=hidden name=fuser value=supervisor>
<center><table border=0>
 <tr><td>Wachtwoord van de beheerder: <td><input type=password size=20 name=fpassword>
 $table_end
 <p><center>
 <input type=submit value="Opsturen">
</center>
</form>

