
<h1 class="wims_docu_title">$tit</h1>

!if $error!=$empty
 !read docu/nl/msg.phtml
 <br><hr> <br>
!endif

!if $titb=$empty
 <br>
 Het blok <tt>$block</tt> is nog  niet aangemaakt.
 <br>
 !exit
!endif

!if $datetest<0
 <br>
 Deze pagina is nog niet publiek beschikbaar. Kom later maar eens terug ! 
 <br>
 !exit
!endif

!if $datetest>0
 <br>
 Deze pagina is verlopen en is dus helaas niet meer beschikbaar !
 <br>
 !exit
!endif

<h3>$titb</h3>

!if $sheetdata=$empty
 <br>
 Er staan geen opdrachten [werkbladen] in deze pagina.
 <br>
 !exit
!endif
Hier staan de opdrachten in werkblad formaat. 
Ze kunnen via "cut & paste" worden ingevoerd
!if $wims_user=supervisor
 in een werkblad naar keuze uit uw klas.
!else
 in een werkblad van een virtuele klas onder uw verantwoording.
!endif

<pre>
$sheetdata
</pre>

