<center><h1>$tit</h1></center>

!if $fcnt<1
    Dit document heeft nog geen inhoud.
    Maak de
 !href cmd=reply&job=edit&block=main eerste pagina
 .
 <br>
 !exit
!endif

<br>$table_header
<caption>Lijst van blokken in dit document</caption>
$table_hdtr
<th>Naam<th>Titel<th>Actie
!for i=1 to $fcnt
 !set s_=!line $i of $slist
 !set t_=!line $i of $tlist
 !set t_=!trim $t_
 !default t_=No title
 $table_tr
 <td><tt>$s_</tt></td>
 <td>$t_</td>
 <td align=center>
 !href cmd=reply&job=read&block=$s_ Lezen
&nbsp;
 !if $editable=yes
  !href cmd=reply&job=edit&block=$s_ Bewerken
 !endif
</td>
!next i
$table_end <br>

<center>
Totaal beschikbare schijfruimte: $quota_total Meg. 
<br>Beschikbare vrije ruimte: $quota_free Meg.
<br>
Bestand
!href cmd=reply&job=file invoegen
&nbsp;&nbsp;
!href cmd=reply&job=read&block=main Hoofdpagina 
</a> van dit document

</center> <br>


