!nocache
<center><h1>$tit
</h1></center>

!if $titb=$empty
 <p>
 Het blok <tt>$titb</tt> van dit document is nog niet aangemaakt
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 Dit blok is nog niet leesbaar, kom later maar eens terug.
 <p>
 !exit
!endif

!if $datetest>0
 <p>
Helaas, dit blok is verlopen, en dus niet meer beschikbaar.
 <p>
 !exit
!endif

<h3>$titb (Document broncode)
</b><font size=-1>
 [
 !href cmd=reply&job=read geformatteerd
 ]</font>
</h3>

<pre wrap>
!mexec scripts/cat.sh $module_dir/$docdir/$doc/src/$block
</pre>

<p><hr>
!if $wims_class!=$empty and $wims_user!=supervisor
 !exit
!endif
<table width=100% border=0>
<tr><td align=left><small>
!href cmd=reply&job=read Geformatteerd
&nbsp; door
!if $email=$empty
 $author
!else
 !mailurl $email $author
!endif
!! &copy;
!if help notin $wims_session
 <td align=right><small>
 !href module=home WIMS
  @
 <a href=http://$httpd_HTTP_HOST/>$httpd_HTTP_HOST</a>
!endif
<tr><td align=left colspan=2 nowrap>
<small>Laatste modificatie op: $datm
</table>


