
<h3><center>Mede auteurs</center></h3>

Geef hier het "mede auteur id" van collega's
die het recht hebben deze module te veranderen

<b>Attentie</b>
Een eenmaal vergeven recht tot veranderen van deze module ,
kan niet meer worden teruggedraaid !

<p>
Dit is alleen van belang voor stabiele versie publicaties.
Wanneer u deze module namens een andere auteur publiceerd, <b>MOET</b> u hier
de "id" van deze auteur vermelden.

