
<h3><center>Publicatie van een module</center></h3>

Wanneer U een account heeft op het de central publicatie server $centralhost ,
kunt U daar een module installeren.<br>
U kunt deze als stabiele versie of als ontwikkelingsversie publiceren.
De module zal dan beschikbaar zijn op het adres
<a href=$downloadsite>$downloadsite</a>.
<p>
In het geval van een stabiele versie, wordt de module automatisch
beschikbaar gesteld aan <b>alle</b> WIMS servers over de gehele wereld.
<p>
Er is dus enige voorzichtigheid geboden; alleen goed geteste modules gebruiken voor
de "stabiele versie publicatie".<br>
Dit is vooral van belang bij het veranderen/verbeteren van bestaande modules.
<p>
We hebben natuurlijk allemaal de behoefte om ons bestaande werk te verbeteren,
mooier te maken, meer knoppen, meer mogelijkheden, betere antwoordherkenning enz enz.
<p>
Maar bedenk goed, ER ZIJN ANDEREN DIE UW MODULES GEBRUIKEN !.
Uw module kan reeds in gebruik zijn; in werkbladen, documenten of zelfs
in belangrijke tentamens !<br>
De kans is groot dat als dit werk instabiel wordt en zich onvoorspelbaar gedraagt.
De schade aan onze reputatie aanzienlijk zal zijn !
<p>
Als een algemene regel geldt; nooit veranderingen, anders dan bugfixes
<b>gedurende</b> het schooljaar doorvoeren.
Installeer uw verbeterde module eerst in de testzone, en publiceer pas
na een grondige testperiode , het liefst in de zomervakantie.  
<p>
Voor eigen gebruik of voor gebruik door uw eigen studenten,
linkt u de werkbladen,oefeningen en repetities gewoon door naar de development
directory. 
Op deze manier kan de module goed uitgetest worden voor
de eigenlijke publicatie.
<p>
In elk geval, besef goed dat voor stabiele modules geldt dat deze
alleen te veranderen zijn met de juiste rechten (auteur of mede-auteur).
Wilt u een NIEUWE stabiele module aan ons WIMS systeem toevoegen, moet
u over het juiste account beschikken.
Een andere mogelijkheid is dat U de module stuurt naar een 
"<a href=$(downloadsite)parrains>wims sitemanager</a>" 
en vraagt deze module te publiceren 
(daarna hebt U natuurlijk het recht de module zelf te veranderen)
