<h3><center>Publicatie van een module</center></h3>

Wanneer U een account heeft op het "publicatie centrum $centralhost ",
kunt U daar een module installeren.<br>
U kunt deze als stabiele versie of als ontwikkelingsversie publiceren.
De module zal dan beschikbaar zijn op het adres
<a href=$downloadsite>$downloadsite</a>.
<p>
In het geval van een stabiele versie, wordt de module automatisch
doorgegeven aan <b>alle</b> mirror-sites over de gehele wereld.
<p>
Er is dus enige voorzichtigheid geboden; alleen goed geteste modules gebruiken voor
de "stabiele versie publicatie".<br>
Dit is vooral van belang bij het veranderen/verbeteren van bestaande modules.
<p>
We hebben natuurlijk allemaal de behoefte om ons bestaande werk te verbeteren,
mooier te maken, meer knoppen, meer mogenlijkheden, betere antwoordherkenning enz enz.
<p>
Maar bedenk goed, ER ZIJN ANDEREN DIE UW MODULES GEBRUIKEN !.
Uw module kan reeds in gebruik zijn; in werkbladen, documenten of zelfs
in belangrijke tentamens !<br>
De kans is groot dat als dit werk instabiel wordt en zich onvoorspelbaar gedraagt.
De schade aan onze reputatie zal aanzienlijk zijn !
<p>
Als een algemene regel geldt; nooit veranderingen, anders dan bugfixes
<b>gedurende</b> het schooljaar doorvoeren.
Installeer uw verbeterde module eerst in de testzone, en publiceer pas
na een grondige testperiode , het liefst in de zomervakantie.  
<p>
Voor eigengebruik of voor gebruik door uw eigen studenten/leerlingen,
linkt u de werkbladen,oefeningen en repetities gewoon door naar de development
directory. 
Op deze manier kunt U de module ook goed uit laten testen voor
de eigenlijke publicatie.
<p>
In elk geval, onthoud goed dat voor stabiele modules geldt dat U ze
alleen kan veranderen als U de juiste rechten daartoe hebt (auteur of mede-auteur)
Wilt U een NIEUWE stabiele module aan ons WIMS systeem toevoegen, moet
U over het juiste account beschikken, of U stuurt de module naar een 
"<a href=$(downloadsite)parrains>wims sitemanager</a>" 
en vraagt hem/haar deze module te publiceren (daarna hebt U natuurlijk het recht deze module
te veranderen)
