
<ul>
 <p><li><b>Vraag</b><i> Ik ben mijn wachtwoord vergeten!</i> <p>
 <b>Antwoord</b> Je kunt je docent vragen om een nieuw wachtwoord.
 Je moet dit wachtwoord, na inloggen, veranderen in een eigen, persoonlijk wachtwoord. 
 <p><li><b>Vraag</b><i> Ik heb een oefening gemaak, maak geen cijfer gekregen...</i> <p>
 <b>Antwoord</b>Sommige oefenigen zijn bundels van meerdere opdrachten. 
 Dit soort oefeningen kent dan geen "tussenscores". 
 Je moet dan dus de <b>gehele sessie afmaken</b> voor dat je een cijfer krijgt .
 <p><li><b>Vraag</b><i> De server weigert mijn cijfers te registreren.</i> <p>
 <b>Antwoord</b> Er zijn meerdere mogelijkheden:<ul>
  <li>Wanneer een docent oefenmateriaal maakt met een in "tijd beperkte score-registratie",
  kan dit materiaal na afloop van deze geldigheids-periode nog steeds zichtbaar 
  zijn voor de leerlingen, en dus ook nog gewoon gebruikt worden om mee te oefenen...
  aleen dan niet meer voor een cijfer.
  Je ziet dan bijvoorbeeld de mededeling <em>`the registration of score is closed for your connection'</em> 
 onderaan de pagina.
  <li>
  Haal je meer dan de vereiste aantal cijfers voor een oefening, dan worden ze onzichtbaar. 
  Maar gelukkig wordt de gemiddelde score wel berekend met deze extra cijfers ;-)
  <li>
  Verander je als leerling eigenhandig de configuratie van een oefening (zoals aantal sommen,moeilijkheidsgraad enz),
  dan worden deze cijfers niet meegerekend. Je kunt dit zien aan het verdwijnen
  van de link "<b>werkblad / worksheet</b>" onderaan en bovenaan de som-pagina.
 </ul>
 <p><li><b>Vraag</b><i> 
 Mag ik de zelfde oefening meerdere keren proberen?
</i> <p>
 <b>Antwoord</b> 
 Je kunt dit zonder strafpunten een x-aantal keer doen 
 (het exacte aantal keer waarin dit is toegestaan krijg je niet te zien)
 Verder moet je beseffen dat wanneer je "per ongeluk" een 0 krijgt voor een oefening, 
 dit wel erg zwaar drukt op je gemiddelde cijfer...
 Wel kun je natuurlijk de losse sommen gewoon maken, 
 zonder dat deze in een proefwerk of werkblad staan.
 (zoek gewoon op de naam/trefwoorden naar de som op je server) 
  <p><li><b>Vraag</b><i> 
  Kan ik nog meer punten krijgen dan de docent heeft ingesteld voor een oefening?
   </i> <p>
 <b>Antwoord</b> 
 Je kun sommen net zo vaak maken als je wilt, en zoveel punten verzamelen als je kan.
 Maar de extra punten boven het door je docent ingestelde aantal,
  worden niet mee gerekend door de server.
 Ook kun je in overleg met je leraar speciale regelingen treffen, 
 voor het "belonen" van je extra werk.
 <p><li><b>Vraag</b><i> 
 Hoe beinvloeden de twee getallen (het percentage afgerond werk en de gemiddelde score) mijn algehele cijfer?
  </i> <p>
 <b>Antwoord.</b> 
 De server berekend de cijfers volgens een formule die afhangt van de ingestelde moeilijkheidsgraad van het werkblad.
 Deze moeilijkheidsgraad wordt bepaald door je docent ;  de formule staat op de help-pagina voor cijfers
(klik op de link "help" van die pagina).

</ul>
