Het werk in virtuele klassen kan worden georganiseerd in:
<ul>
<li>Interactieve Lesdocumenten
<li>Werkbladen 
<li>Proefwerken 
</ul>

<H2>Werkbladen</H2>
<p>
Elke virtuele klas kan tot 64 werkbladen beheren.
elk werkblad kan tot 64 items bevatten.
Items kunnen zijn:
<ul>
<li>modules (fullpower modules/modtool)
<li>oefeningen (oef-formaat/createxo)
<li>hulpmiddelen (tools:calculators,plotters enz)
</ul>
<p>
Elk werkblad heeft een status code. 
<ul>
<li><b>in bewerking </b>(under preparation)<br>
Elk nieuwe werkblad heeft vanzelf de status: <b>in bewerking </b>(under preparation)
Alleen in deze fase kan een werkblad worden verwijderd !
Een werkblad in bewerking is alleen zichtbaar voor de supervisor/docent
<li><b>actief</b><br>
Een werkblad kan worden geactiveerd: hierdoor wordt het werkblad zichtbaar 
en kunnen leerlingen met dit werkblad aan de slag.
Elk werkblad heeft een <b>"houdbaarheid datum"</b>. 
Na deze datum wordt het werkblad inactief.
Leerlingen zien dit werkblad dan nog wel, ze kunnen er ook nog steeds mee werken, maar de behaalde cijfers worden niet geregistreerd.
<li><b>verlopen en onzichtbaar</b><br>
Een werkbladstatus kan ook op <em>verlopen</em> <b>en</b> <em>onzichtbaar</em> worden gezet.
De leerlingen zien het werkblad dan dus niet meer. De supervisor kan dit werkblad nog wel zien. 
De Docent (supervisor) kan ten allen tijde kiezen tussen <em>actief</em> en <em>verlopen</em> of <em>onzichtbaar</em>. 
</ul>
<p>

