Een virtuele klas is een ruimte (een directory op de WIMS server) waar de leerling
onder begeleiding van een docent (ook wel genoemd supervisor,leraar) interactief
lesmateriaal kan bestuderen, werkbladen kan maken voor een cijfer of een proefwerk kan 
maken. 
<p>
Dit alles speelt zich af in het venster van een -willekeurige- internetbrowser.
Afhankelijk van Uw netwerk, op het internet of op een lokaal (school) intranetwerk.
Voor sommige oefeningen/modules is javascript en/of java vereist. Dit kan voor problemen
met Uw browser zorgen. Neem in deze gevallen kontact op met uw systeembeheerder.   

<p>
Wanneer een virtuele klas is
!href module=$module&chapter=$chapter&open=$open,$(chapter)_creat#creat aangemaakt/opgericht
 door een docent, wordt deze "benoemd" tot supervisor van deze klas, en kan nu lesmateriaal
 verwerken in zijn/haar klas. 
<p>
Het -interactieve- lesmateriaal kan van diverse oorsprong zijn, bijvoorbeeld
!href module=$module&chapter=1&open=$open,1_exo#exo de creactexo oefening 
(het online exercise format) eventeel geheel
!href module=$module&chapter=4&open=$open,4_oef#oef zelfgemaakt
 om daarna in werkbladen en of tentamens te worden verwerkt.
<p>
WIMS kiest random uit het door U geselecteerde materiaal 
<p>
Een klas kan ook gebruik maken van een "message board".
 Deze voorziening heeft -net als alle ander WIMS hulpmiddelen- ook de mogelijkheid tot
  het invoeren van correct getypsette wiskundige formules! en heeft ook een zekere interactiviteit.
<p>
Planned for the future:
test sheets with sophisticated random exercise generation and work time 
limitation will also be available. Software to analyze student performance
based on registered data on his/her work is under study.

