editAreaLoader.lang["fr"]={
new_document: "nouveau document (efface le contenu)",
search_button: "Rechercher / Remplacer",
search_command: "Rechercher suivant / ouvrir la fen&ecirc;tre de recherche",
search: "Rechercher",
replace: "Remplacer",
replace_command: "Remplacer / ouvrir la fen&ecirc;tre de recherche",
find_next: "Rechercher",
replace_all: "Tout remplacer",
reg_exp: "Expr. r&eacute;guli&egrave;re",
match_case: "Respecter la casse",
not_found: "non trouv&eacute;.",
occurrence_replaced: "Remplacements &eacute;ffectu&eacute;s.",
search_field_empty: "Le champ de recherche est vide.",
restart_search_at_begin: "Fin du texte atteint, poursuite au d&eacute;but.",
move_popup: "D&eacute;placer la fen&ecirc;tre de recherche",
font_size: "--Taille police--",
go_to_line: "aller &agrave; la ligne",
go_to_line_prompt: "Ligne No:",
undo: "annuler",
redo: "refaire",
change_smooth_selection: "Activer/D&eacute;sactiver des fonctions d'affichage (meilleur affichage mais plus de charge processeur)",
highlight: "Activer/D&eacute;sactiver la coloration syntaxique",
reset_highlight: "R&eacute;initialiser la coloration syntaxique (si d&eacute;syncronis&eacute;e du texte)",
word_wrap: "Activer/D&eacute;sactiver les retours &agrave; la ligne automatiques",
help: "&agrave; propos",
save: "Sauvegarder",
load: "Charger",
line_abbr: "Ln",
char_abbr: "Car",
position: "Position",
total: "Total",
close_popup: "fermer le popup",
shortcuts: "Racourcis clavier",
add_tab: "ajouter une tabulation dans le texte",
remove_tab: "retirer une tabulation dans le texte",
about_notice: "Note: la coloration syntaxique n'est pr&eacute;vue que pour de courts textes.",
toggle: "basculer l'&eacute;diteur",
accesskey: "Accesskey",
tab: "Tab",
shift: "Maj",
ctrl: "Ctrl",
esc: "Esc",
processing: "chargement...",
fullscreen: "plein &eacute;cran",
syntax_selection: "--Syntaxe--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
syntax_java: "Java",
close_tab: "Fermer le fichier",
syntax_wimsoef: "OEF",
syntax_wims: "WIMS",
syntax_wimsdata: "WIMS data",
syntax_gp: "Pari/GP",
};
