
<script type="text/javascript">
  /*<![CDATA[*/
  !set tmp=!declosing $(slib_geogebrawindow1)

  slib_geogebrawindow1 = function(){$tmp};

  if(window.addEventListener){
    window.addEventListener('load', slib_geogebrawindow1)
  }else{
    window.attachEvent('onload', slib_geogebrawindow1)
  }

  !set tmp=!declosing $(slib_geogebrawindow2)
     function ggbOnInit(){$tmp};
  /*]]>*/
</script>

!!do not reset slib_geogebrawindow1 slib_geogebrawindow2
!! except in very particular cases -- to check !
!! creation of an exercise in createxo
!if $cmd=reply
  !reset slib_geogebrawindow1 slib_geogebrawindow2
!endif
