
!set classname=<b><font color=green>$wims_classname</font></b>\
 of <b><font color=green>$wims_institutionname</font></b>
 
!set months=gennaio,febbraio,marzo,aprile,maggio,giugno,luglio,agosto,settembre,ottobre,novembre,dicembre

!distribute items Esame, Test into name_E, name_S

!set name_title=Statistiche dell'attività
!distribute items Statistica generale,punteggio<br>richiesto,peso,indice di<br>difficoltà,\
media/a punti,media/studente,deviazione standard,tempo,a punti\
tempo teorico,Somma,min.,min,max\
into name_totals,name_required,_points,name_coeff,name_index,\
name_avg_score,name_avg_participant,name_deviation,name_duration,name_score,\
name_theoric,name_sum,name_minute,name_min,name_max

!distribute line Mostra le statistiche\
Tipo di dati\
attività registrate, attività non registrate, tutte le attività\
Tenendo conto delle attività dei corsi<br>che condividono i test con questo corso\
into name_showstat,name_data,name_typ_activities,name_shareclass

!set name_prompt= punteggio richesto, pesi,\
        indice di difficoltà, totali,\
	media per punteggio, media per studente,\
	minimo e massimo, deviazione standard

