
L'exercice <em>$deltitle</em> a été retiré de la liste d'exercices de votre
classe.
<p>
Si vous avez fait une mauvaise manoeuvre et voulez réparer votre
erreur, voici le source de cet exercice que vous pouvez sauvegarder comme mesure d'urgence, et plus tard copier dans
!href module=adm/createxo&mode=raw Createxo
 pour réinstaller l'exercice.
<p>
<pre>
$deleted
</pre>

<p><center>
!href module=home Sommaire de la classe.
</center> <p>

