
!set name_first=Exercices basiques
!set name_datalist=Exercices avec une liste de données

!readproc model/makelist.proc

Voici les modèles d'exercice disponibles. Choisissez-un, ou
!href cmd=reply&level=1 retournez
 à la page d'accueil.

<p>
!for t in $types
 !default name_$t=$t
 $table_header
 <caption>$(name_$t)</caption>
 $table_hdtr
 <th>Type</th>
 <th>Action</th>
 <th>Description</th>
 </tr>
 !for f in $(type_$t)
  !set r=!record 1 of model/src/$f.oef
  !set r=!line 1 of $r
  $table_tr
  <td>$(tit_$f)</td>
  <td nowrap>
  !href cmd=resume&level=3&mode=model&model=$f&realtest=yes Démo
&nbsp;
  !href cmd=reply&level=2&mode=model&model=$f Adapter
  </td>
  <td><small>$(desc_$f)
  !href target=wims_mhelp cmd=help&special_parm=model,1,$f &gt;&gt;
  </small></td>
  </tr>
 !next f
 $table_end
 <p>
!next t

<b>Note</b>. Ces modèles ont pour but de permettre aux plus pressés de
construire rapidement leurs exercices. Ils ont donc souvent une structure
simplifiée et standardisée, et n'offrent pas la pleine puissance de la
syntaxe OEF. Mais vous pouvez toujours mettre les exercices en mode brut
pour y ajouter plus de fonctionnalités ou les modifier selon votre goût.

!set wims_menu_tail=!append line back2,1,cmd=reply&level=1 \
to $wims_menu_tail
!reset mode

