
!if $vote_option=anonymous
 Questo è un questionario $name_anonymous.
!else
 !if $vote_option=trace
   Questo è un questionario $name_trace.
 !else
   Questo è un questionario $name_nominative.
 !endif
!endif
!if $vote_status=2
 &Egrave; $name_2.
!endif

!if $wims_user=supervisor
 ($vcnt risposte)
 !href cmd=reply&job=edit Modifica
 
 !href cmd=reply&job=csv Esporta i dati
<p>
!endif

!if $vote_status=2
 !read $votedir/$vote.def
 !goto comments
!endif

!if $(user_vote_$Vote)!=$empty
 !if $vote_option!=nominative
  Hai già risposto al questionario.<p>
 !else
  Hai già risposto al questionario, ma puoi modificare le tue risposte.
  <p>
  !goto form
 !endif
!else
 Fai le tue scelte: <p>
 :form
 !form reply
 <input type=hidden name=job value=vote>
 !set m_formed=yes
!endif

!read $votedir/$vote.def

!if $m_formed=yes
 <p><center>
 <input type=submit value="Salva">
 </center></form>
!endif

:comments
!readdef $votedir/$vote.comments 
!if $wims_user=supervisor and $test_comment=1 and $vote_option!=nominative
<p><b>Commenti</b> : 
</p><p> 
!for i=1 to $parmcnt
 !if $(type_comment$i)=yes
  !set comment_$i = !replace internal --- by $\
 $<br>- in $(comment_$i)

 $i : 
 $(comment_$i)
 !set rcnt=!recordcnt $votedir/$(vote)_$i.comments
 !for r_j=1 to $rcnt
 <br>-
  !record $r_j of $votedir/$(vote)_$i.comments
 !next
</p><p>
 !endif
 </p>
!next
!endif
!if $wims_user=supervisor and $vote_option!=anonymous
 <p> Dettagli delle risposte.
 !for i=1 to $parmcnt
  !for c=1 to $(choices$i)
   !if /supervisor/ notin $c/
    <p>$i-
    !item $c of $(chlist$i)
 <br> <tt>
    !for u in $(votes_$(i)_$c)
     !if $vote_option=nominative
      !set U=!translate internal / to , in $u
      !readproc adm/class/userdef classes,$U
      !defof user_lastname, user_firstname in $userdef
       ($u)
       <br>
     !else 
       ($u) 
     !endif
    !next u
   </tt>
   !endif
  !next c
 !next i
!endif
