!!!### language independant
!!
!! Tableau d'information générale de la feuille d'examen
!if $activetest>0
 !set readonly=disabled="disabled"
!else
 !set readonly=
!endif
!form reply
 <input type="hidden" name="job" value="text" />

 <fieldset class="property_fields blockcenter">

   <legend>$name_info
   !if $jquery_defined!=yes and $exam<=$scnt
   [
    !href cmd=resume&infoshow=no $wims_name_hide
    ]
   !endif
   </legend>

  !!Title
  <div class="field box fullwidth">
    <label for="title">$(name_shinfo[1])</label>
    <input size="65" name="title" id="title" value="$title" required="required" />
    <div class="formHelp">$name_desc_title</div>
  </div>

  !!Status
  !if $activetest>-1
    <div class="field box">
     $(name_shinfo[2])
     $(wims_name_shstatus[$activetest+1]) &nbsp;
      !read adm/sheet/sheetaction.phtml exam,$exam,$activetest,0
    </div>
  !endif
  !!Description
  <div class="field box fullwidth">
   <label for="desc">$(name_shinfo[3])</label>
   <div class="formHelp">$name_desc_desc</div>
   <textarea id="desc" class="iEdit" rows="6" cols="65" name="desc">$desc</textarea>
  </div>

  !!Comments
  <div class="field box fullwidth">
   <label for="comment">$(name_shinfo[8])</label>
   <div class="formHelp">$name_desc_comment</div>
   <textarea id="comment" class="iEdit" rows="6" cols="65" name="comment">$comment</textarea>
  </div>
  !!Expiration Date
  <div class="field box halfwidth">
       <label for="expday">$(name_shinfo[4])</label>
        !distribute item $[$expday],$[$expmon] into expday,expmon
        !formselect expday from 1 to 31
        !formselect expmon from 1 to 12 prompt $months
        !formselect expyear from $thisyear to $thisyear+1
        <div class="formHelp">$name_desc_expday</div>
  </div>

  !!Duration
  <div class="field box halfwidth">
       <label for="duration">$(name_shinfo[9])</label>
       !set wims_ref_class=wims_button_help float_right
       !href target=wims_mhelp cmd=help&special_parm=session $wims_name_help
       <input type="number" min="$duration_min" max="$duration_max" size="5" name="duration" id="duration" value="$duration" style="text-align:right;" $readonly /> <span class="units">$name_units_duration</span>
       <div class="formHelp">$name_desc_duration</div>
  </div>

  !! Tries
  <div class="field box halfwidth">
       <label for="tries">$(name_shinfo[10])</label>
        !set wims_ref_class=wims_button_help float_right
       !href target=wims_mhelp cmd=help&special_parm=session $wims_name_help
       <input type="number" min="$tries_min" max="$tries_max" size="5" name="tries" id="tries" value="$stries" $readonly/>
       <div class="formHelp">$name_desc_tries &nbsp;</div>
  </div>

  !if $activetest>=0
    !!Allow Type
    !!Cut Hours
    <div class="field box halfwidth">
      <label for="cutt">$name_shinfo_cutt</label>
      !set wims_ref_class=wims_button_help float_right
       !href target=wims_mhelp cmd=help&special_parm=cutt $wims_name_help
      <input name="cutt" id="cutt" value="$cutt" />
    </div>

    <div class="field box">
     <input type="hidden" name="allow" value="yes" />
     <label for="allowtype">$(name_shinfo[6])</label>
      !set wims_ref_class=wims_button_help float_right
      !href target=wims_mhelp cmd=help&special_parm=allowtype $wims_name_help
     <br class="clearall" />
      <select id="allowtype" name="allowtype" onchange="submit()">
        !if $tv_listname=$empty
		!set list_allowtype=all,simulation,none,select
	!else
		!set list_allowtype=all,simulation,none,select,techvar
	!endif
	!let nboption=!itemcnt $list_allowtype
        !for i=1 to $nboption
         !if $(list_allowtype[$i])=$allowtype
          <option value="$(list_allowtype[$i])" selected="selected">$(name_allowtype[$i])</option>
         !else
          <option value="$(list_allowtype[$i])">$(name_allowtype[$i])</option>
         !endif
        !next i
       </select>
       !if $allowtype=select
	 <br /><input size="50" name="IPlist" value="$IPlist" />
       !endif
       !if $allowtype=techvar
	 !read adm/vfilter/scoreregform.phtml
       !endif
     !!formselect allowtype list all, simulation, none, select prompt $name_allowtype
     !!<input size="50" name="IPlist" value="$IPlist" />




     !default allowshare=0

     !if $sharers!=$empty
      ( $(name_shinfo[7])
      !formselect allowshare list 0,1 prompt $wims_name_no,$wims_name_yes
      )
     !else
      <input type="hidden" name="allowshare" value="0" />
     !endif
    </div>


  !endif
  </fieldset>

  <div class="wimscenter wimsform">
    !ifval $activetest=-1
     <input type="submit" name="save" value="$name_mkexam" />
    !else
     <input type="submit" name="save" value="$wims_name_tosave" />
    !endif
  </div>

!formend
