!!!### language independant
!!
!! Tableau d'information générale de la feuille d'exos

!form reply
 <input type="hidden" name="job" value="text" />
 
 <fieldset class="property_fields">

   <legend>$name_info :</legend>
  
  !!Title
  <div class="field box fullwidth">
    <label for="title">$(name_shinfo[1])</label>
    <div class="formHelp">$name_desc_title</div>
    <input size="65" name="title" id="title" value="$title" />
  </div>
  
  !!Status
  <div class="field  box">
   <label for="">$(name_shinfo[2]) </label>
   <div>
     $(statutname[$activetest+2]) &nbsp;
     !ifval $activetest>-1
      !read adm/sheet/sheetaction.phtml exam,$exam,$activetest,0
     !endif
   </div>
  </div>

  !!Description
  <div class="field box fullwidth">
   <label for="desc">$(name_shinfo[3])</label>
   <div class="formHelp">$name_desc_desc</div>
   <textarea id="desc" class="iEdit" rows="6" cols="65" name="desc">$desc</textarea>
  </div>

  !!Comments
  <div class="field box fullwidth">
   <label for="comment">$(name_shinfo[8])</label>
   <div class="formHelp">$name_desc_comment</div>
   <textarea id="comment" class="iEdit" rows="6" cols="65" name="comment">$comment</textarea> </div>

  !!Expiration Date
  <div class="field halfwidth float_left">
      <div class="box">
       <label for="expday">$(name_shinfo[4])</label>
       <div class="formHelp">$name_desc_expday &nbsp;</div>
        !distribute item $[$expday],$[$expmon] into expday,expmon
        !formselect expday from 1 to 31
        !formselect expmon from 1 to 12 prompt $months
        !formselect expyear from $thisyear to $thisyear+1
      </div>
  </div>
   
  !!Duration
  <div class="field halfwidth float_left">
      <div class="box">
       <label for="duration">$(name_shinfo[9])</label>
       <div class="formHelp">$name_desc_duration</div>
       <input size="5" name="duration" id="duration" value="$duration" style="text-align:right;"/> <span class="units">$name_units_duration</span>
      </div>
  </div>

  !! Tries
  <div class="field halfwidth float_left">
      <div class="box">
       <label for="tries">$(name_shinfo[10])</label>
       <div class="formHelp">$name_desc_tries &nbsp;</div>
       <input size="5" name="tries" id="tries" value="$stries" />
      </div>
  </div>

  !if $activetest>0
    !!Allow Type
    <div class="field halfwidth float_left">
    <div class="box">
     <input type="hidden" name="allow" value="yes" />
     <label for="allowtype">$(name_shinfo[6])</label>
     <div class="formHelp float_right">
      !set wims_ref_class=wims_button_help
      !href target=wims_mhelp cmd=help&special_parm=allowtype $wims_name_help
     </div>
     <br class="clearall"/>
     !formselect allowtype list all, simulation, none, select prompt $name_allowtype
     <input size="50" name="IPlist" value="$IPlist" />
     !set allowshare=0
     
     !if $sharers!=$empty
      ( $(name_shinfo[7])
      !formselect allowshare list 0,1 prompt $wims_name_no,$wims_name_yes
      )
     !else
      <input type="hidden" name="allowshare" value="0" />
     !endif
    </div>
    </div>
    
    !!Cut Hours
    <div class="field box fullwidth">
      <label for="cutt">$name_shinfo_cutt</label>
      <input name="cutt" id="cutt" value="$cutt" />
    </div>
  !endif
  
  </fieldset>
  
  <div class="wimscenter wimsform">
  
    !ifval $activetest=-1
     <input type="submit" value="$name_mkexam" />
    !else
     <input type="submit" value="$wims_name_tosave" />
    !endif
 </div>

!formend
