!!!### langage independant
!!
<br>
!form reply
<input type=hidden name=job value=exo>
<input type=hidden name=exo value=$exo>

$table_header
 $table_tr
  <td>$wims_name_Exercise</td><td>$exo</td> 
 </tr>
 $table_tr
  <td>$name_weight</td><td><input size="5" name="eweight" value="$eweight"></td>
 </tr>
 $table_tr
  <td>$wims_name_title</td><td><input size="20" name="ename" value="$ename"></td>
 </tr>
 $table_tr
  <td>$name_dependency [
   !href target=wims_mhelp cmd=help&special_parm=dependency $wims_name_help
  ]</td>
  <td><input size="40" name="edep" value="$edep"></td>
 </tr>
 $table_tr
  <td>$name_Options [
   !href target=wims_mhelp cmd=help&special_parm=options $wims_name_help
  ]</td>
  <td>
   !formcheckbox eopt list $optionlist
  </td>
 </tr>
 $table_tr
  <td>$wims_name_comment <small>($name_desc_comment)</small></td>
  <td><textarea name="ecomment" rows="3" cols="60">$ecomment</textarea></td>
 </tr>
 $table_tr
  <td>$name_contenu [
   !href target=wims_mhelp cmd=help&special_parm=contenu $wims_name_help
  ]</td>
  <td>
   !read adm/class/transfertexo.phtml
  </td>
 $table_tr
  <td colspan="2" align="center"> 
   <input type=submit value="$wims_name_tosave" name="save">
   &nbsp;
   !if $exo>$exocnt
  !set wims_menu_items=!append line mainpage,1, cmd=reply \
    to $wims_menu_times
  !href cmd=reply $wims_name_mainpage
   !else
    !href cmd=reply $wims_name_giveup
   !endif
  </td>
 </tr>
$table_end
</form>
!reset save