
!read js/examclock1.phtml
!if $job=exo
 !set js=!record 0 of js/chooselist.js
 !set wims_html_header=!append line $js to $wims_html_header
!endif
!read adm/css.phtml
!header1

!if $job iswordof student score scorereg
 !changeto $job.phtml
!endif
!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$name_title $exam

!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$moduclass_lang
 </div>

 !if $error iswordof prep_noexercise
  !set wims_menu_items=!append line back2,1,cmd=resume&error=$empty \
   to $wims_menu_items
   !reset save
 !else
  !set wims_menu_items=!append line back2,1,module=home \
   to $wims_menu_items
 !endif
 !goto end
!endif

!if $job=exo or $job=cpsheet or $job=cpexam
 !read $job.phtml
 !goto end
!endif

!read examinfo.phtml

!ifval $activetest=-1
 !goto end
!endif

:end1
!if $exocnt=0
 <p>$name_warning
 !set nex=!itemcnt $aexams
 !if $nex > 0
  !set wims_ref_class=wims_button_help
  !href cmd=reply&job=cpexam $wims_name_cpexam
 !endif
 </p>

!else
 !read examcontent.phtml

!endif

!if $activetest=0
 !let wims_menu_items=!append line addexo,1,cmd=reply&job=exo&exo=$[$exocnt+1]\
addsexo,1,cmd=reply&job=cpsheet to $wims_menu_items
!endif

!if $activetest>=0
 !let wims_menu_items=!append line ,0,\
participantview,1,cmd=reply&job=student to $wims_menu_items
!endif

:end
!tail

!reset job,echoose,eweight,ename,edep,eopt,source

