<b>Attention</b> !<p>

Vous n'avez pas encore fait tous les exercices de cet examen. Terminer
maintenant va geler le score et consommer un essai de l'examen,
et vous serez obligé de recommencer au début la prochaine fois.
<p>
Voulez-vous vraiment terminer ?
<p><center><font size="+1">
!href cmd=reply&job=scorereg&confirm_end=yes $wims_name_yes
&nbsp;&nbsp;&nbsp;&nbsp;
!href cmd=reply&job=score $wims_name_no
</font></center> <p>

!tail
!reset job
