
!set embraced_randitem=<p> \
<b>Ce texte accepte la mise en aléatoire par des accolades emboitables</b> :\
si vous mettez plusieurs mots (ou groupes de mots), séparés par des\
virgules, dans une paire d'accolades, ces mots seront tirés au hasard\
au moment où le texte est présenté aux élèves. Ce qui rendra le texte\
aléatoire. </p><p>\
Par exemple, si vous rentrez le texte </p>\
<pre>Je suis allé {à l'école,au cinéma,chez mes grand parents} {hier,la semaine dernière}</pre>\
vous aurez comme résultat l'une des phrases suivantes, aléatoirement&nbsp;:\
<pre>\
Je suis allé à l'école hier\
Je suis allé au cinéma hier\
Je suis allé chez mes grand parents hier\
Je suis allé à l'école la semaine dernière\
Je suis allé au cinéma la semaine dernière\
Je suis allé chez mes grand parents la semaine dernière\
</pre>\
Il y aura donc six textes différents pouvant être présentés aux élèves.\
<br />Si vous désirez entrer des formules mathématiques, il est conseillé de\
désactiver cette possibilité en mettant le bouton <span class="wims_code_words">\
Mise en aléatoire par des accolades emboitables</span> \
sur <span class="tt">$wims_name_no</span>.

!set name_random=Quelques exemples de génération de paramètres aléatoires : <ul>\
 <li>un entier compris entre 10 et 100 (inclusif) :\
	 <span class="tt wims_code_words">randint(10..100)</span>\
 </li><li>un entier multiple de 10 compris entre 10 et 1000 (inclusif) :\
	<span class="tt wims_code_words">randint(1..100)*10</span>\
  </li><li>un nombre décimal compris entre 0 et 2 :\
	<span class="tt wims_code_words">random(0..2)</span>\
  </li><li>un objet tiré au hasard parmi une liste :\
	<span class="tt wims_code_words">randitem(a,b,c,10,100,mot,une phrase)</span>\
  </li></ul>

!set name_detail_parm=Pour plus de détail sur le calcul des paramètres.

!set image_help=<div class="wims_smallremark"><b>Insertion d'images</b>:\
Pour insérer des images dans votre exercice, il faut d'une part charger les images\
dans le module d'exercices de votre classe et d'autre part mettre le code html qui \
permet d'afficher l'image. Le code d'insertion est\
<pre>&lt;img src="\imagedir/nom_image"/></pre> et\
où <span class="tt">nom_image</span> est le nom de l'image (y compris l'extension <span class="tt">.jpg</span>, <span class="tt">.png</span>,\
...) et <span class="tt wims_code_variable">\imagedir</span> représente le nom de code du répertoire où se trouve l'image.\
Vous pouvez le mettre dans la plupart des textes des modèles préparés (y compris dans la consigne).\
Vous pouvez commencer votre exercice même si les images ne sont pas encore chargées.\
Une fois l'exercice mis dans la classe, suivez le lien \
<span class="tt">Déposer un fichier</span> dans l'exercice ou <span class="tt">$wims_name_downloadbinary</span>\
et chargez toutes les images dont vous avez besoin. Testez. Ajustez les tailles des images.\
Il est recommandé de ne pas prendre des images trop grandes car plus longues à charger\
lors de l'exécution de l'exercice et de les réduire avant de les mettre dans le module de la classe.\
</div>

!set math_help= <div class="wims_smallremark"><b>Insertion de formules mathématiques</b>:\
Pour entrer des formules de mathématiques dans le texte, encadrez le code tex par \
<span class="tt wims_code_variable">\(</span>\
et\
<span class="tt wims_code_variable">\)</span>.\
Par exemple,\
<pre>\( x^2+\frac{3}{2} \)</pre>

!set oef_help= <div class="wims_small_remark"><b>Pour les plus avancés</b> :\
il est possible dans la définition des paramètres d'utiliser \
la plupart des fonctions des exercices OEF.\
</div>

!set credits_help=Vous pouvez utiliser le champ <span class="tt wims_code_words">$wims_name_credits</span> pour mettre\
de brèves références, par exemple des images insérées dans l'exercice.
