!if $exocnt<=0
 Questo test di autovalutazione non contiene alcun esercizio: il file sorgente &egrave; vuoto.
 !goto end
!endif

Questo &egrave; il file sorgente del test. &Egrave; possibile copiare
le istruzioni Wims (comprese tra le due righe di `*') in un file
per poi riutilizzarle in futuro per preparare
un nuovo test di autovalutazione. <br>
!href cmd=resume Pagina di gestione dei test.

<p>
******************************************************************
!read wimshome/$wims_sesdir/home_sheet.src
******************************************************************

:end

<p><center>
!href cmd=resume Pagina di gestione dei test.
</center> <p>

