!if $exocnt<=0
 Questa verifica non contiene alcun esercizio: il file sorgente &egrave; vuoto.
 !goto end
!endif

Questo &egrave; il file sorgente della verifica. &Egrave; possibile copiare
le istruzioni Wims (comprese tra le due righe di `*') in un file
per poi riutilizzarle in futuro per preparare
una nuova verifica. <br>
!href cmd=resume Pagina di gestione delle verifiche.

<p>
******************************************************************
!read wimshome/$wims_sesdir/home_sheet.src
******************************************************************

:end

<p><center>
!href cmd=resume Pagina di gestione delle verifiche
</center> <p>

