
<hr width=1>
<center><h3>$wims_classname, $wims_institutionname</h3>
<hr> <p><h1>Verifica numero $sheet<br>$title</h1>
(Pagina pubblica della verifica)
</center> <p>
<div class="wims_sheet_desc">$desc</div><p>

!if $exocnt=0
 Questa verifica &egrave; vuota! Si tratta probabilmente di un 
 errore del docente.
!else
 Questa verifica contiene i seguenti esercizi :<p><ul>
 !for i=1 to $exocnt
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sheet
  !distribute lines $ex into di,pa,re,we,ti,de,dep
  <p><li>$i. 
  !href module=$di&cmd=new&worksheet=$parm1&$pa $ti
, $de
  !if $re>0
   <small>0 su $[$re] punti ottenuti, punteggio medio
   0/10. </small>
  !endif
 !next i
 </ul>
!endif
<p>
!homeref
<p><hr> <p>
<center>
!href cmd=resume Torna alla pagina del docente
</center>

</body></html>

!set job=

