<center>$classname<p>

!if $logname=$empty
 Va¹a zahteva ni dovoljena.
!else
 <h3>Podrobnosti dela uporabnika z imenom $firstname, $lastname</h3>
 (neobdelani podatki)
 </center> <p>
<pre>
!set test=$wims_show_ip
!mexec getraw.sh
</pre>
!endif

!!<p><center>
!!!href cmd=reply&job=getuser&getuser=$getraw Obdelani podatki
!! .
!!!href cmd=resume Seznam uporabnikov
!! .
!!</center> <p>

!set wims_menu_tail=!append line getraw,1,cmd=reply&job=getuser&getuser=$getraw\
part_list,1,cmd=resume\
to $wims_menu_tail
