<center>$classname<p>

<h3>Izpitno delo uporabnika
 !href cmd=reply&job=userprop&getuser=$getuser $lastname, $firstname
<br><font size="-1">Uporabni¹ko ime: <tt>$getuser</tt>
!if $user_email!=$empty
 &nbsp;E-naslov: <a href="mailto:$user_email">$user_email</a>
!endif
</font></h3> <p>
</center>

 $table_header$table_tr<td align=right>Ime seanse:</td>
 <td><tt>$esession</tt></td></tr>
 $table_tr<td align=right>Naslov povezave:</td>
 <td><tt>$ehost</tt></td></tr>
 $table_tr<td align=right>Preostali èas:</td>
 <td>$eremain minutes</td></tr>
 $table_end <p>

!!<center>
!!!href cmd=reply&job=userexamclose&getuser=$getuser Zakljuèi izpitno delo 
!! uporabnika $lastname,$firstname.
!! <p>
!!!href cmd=reply&job=getuser&getuser=$getuser Rezultati uporabnika
!!.
!!!href cmd=resume Seznam vseh uporabnikov
!!.
!!</center>

!set wims_menu_tail=!append line partexamclose,1,cmd=reply&job=userexamclose&getuser=$getuser\
scores,1,cmd=reply&job=getuser&getuser=$getuser\
part_list,1,cmd=resume\
to $wims_menu_tail
