
<center>$classname
<p>
<h1>Tentamen details voor $user_lastname, $user_firstname
</font>
</h1></center>

!if _check isin $session
 !set error=bad_op
 !goto msg
!endif

!if $error!=$empty
 :msg
 <p>
 !read msg.phtml
 <p>
!else
 !if $checksessions=$empty
  Deze leerling heeft nog steeds geen proefwerk/tentamen gemaakt.
  <p>
 !else
 Hier staan de proefwerk/tentamen sessies van deze leerling.
 Klik op een oefening om de inhoud te bekijken. 
  <p><center>
  <table border=1>
  <tr><th>Sessie</th><th>Proefwerk/tentamen</th><th>Resultaat<small>/$scoremax</small></th>
  <th>Oefening</th><th>Start</th></tr>
  !for ses in $checksessions
   !for x in $(exam$ses)
    <tr><td><small>$ses</small></td>
    <td align=center>$x</td>
    <td align=center>$[rint($(score$(ses)$x)*$scoremax)/10]</td><td>
    !for i in $(exo$(ses)$x)
     &nbsp;
     !href target=wims_check module=$module&cmd=new&job=examcheck&checkuser=$checkuser&checksession=$ses&checkexo=$x.$i&checkstep=1 $i
    !next i
   !next x
   </td><td><small>
    !read date.phtml $(start$(ses)$x)
   </small></td>
  !next t
  </table></center> <p>
 !endif
!endif

<center>
!href cmd=reply&job=getuser&getuser=$checkuser Andere Resultaten
&nbsp;
!href cmd=resume Leerlingen lijst

