<center>$classname<p>

!if $logname=$empty
    Deze handeling is ongeldige.
!else
 <h3>Gedetailleerde resultaten van $lastname, $firstname</h3>
 [in ruwe serverlog data]
 </center> <p>
<pre>
!set test=$wims_show_ip
!mexec getraw.sh
</pre>
!endif

!!<p><center>
!!!href cmd=reply&job=getuser&getuser=$getraw Verwerkte data
!! .
!! Lijst van&nbsp;
!!!href cmd=resume alle leerlingen
!! .
!!</center> <p>


!set wims_menu_tail=!append line getraw,1,cmd=reply&job=getuser&getuser=$getraw\
part_list,1,cmd=resume\
to $wims_menu_tail
