
!set classname=$wims_classname - $wims_institutionname
 
!set months=Jan,Feb,Mar,Apr,Mei,Jun,Jul,Aug,Sept,Okt,Nov,Dec

!distribute line Gemiddelde van deze klas\
Gemiddelde\
Gemiddelde van alle positieve cijfers\
Totaal gemiddelde\
into name_classAverage,name_Average,name_posAverage,name_globalaverage

!set name_partdeleted=Verwijderde studenten
!set wims_name_reg_ex=Lijst van oefeningen
!set name_transfer=Breng zijn/haar activiteiten over uit andere klassen

!set name_thsheet=No,Titel,Vereist,Weging,Punten<br>verkregen,%,Kwaliteit,Moeilijkheidsgraad,Cijfer
!set name_minmax=min/gem/max van deze klas

!set name_manualscore=Handmatig ingevoerde cijfers
!set name_autoscore=Behaalde cijfers
!set name_manual_notes=globaal,docent,auto
!set name_examnote=Proefwerk cijfers

!set name_severitylevels=Moeilijkheidsgraad van Werkbladen
!set name_formula=No,Gewicht,niveau
!set name_sheetstatut=in bewerking,actief,verlopen,onzichtbaar

!distribute items Proefwerk,Werkblad,Oefening,Start,Cijfer,Sessie,Klaar,equiv.\
into name_Exam,name_Sheet,name_Exercise,name_Start,name_Score,name_Session,\
name_done,name_equiv

!set name_formula_comment=U kunt de moelijkheidsgraad en weging van de werkbladen vastleggen in de onderstaande tabel.\
De cijfers worden berekend met maximum = 
!set name_formula2=Cijfers berekenen met als maximum $scoremax
!set name_pickup=Kies een werkblad<br>om het gemiddelde cijfer per<br>werkblad te laten zien: 
!set name_warning=U opdracht voor de server is ongeldig en kan niet worden uitgevoerd.

!set name_click=Klik op de naam van een student om zijn/haar werk gedetailleerd te bestuderen. 
!set name_affi=kwaliteit,uitgevoerde opdrachten,cijfers
!set name_workdetail=Detail van het werk van
!set name_activesession=Deze student heeft een nog actieve proefwerk [exam] sessie

!distribute items Verbonden server,Resterende tijd,Proefwerk sessie,minuten\
into name_connecting,name_remaining_time,name_exam_session,name_minutes

!set name_noyetparticipant=Deze klas heeft nog geen studenten.

!if $manual>0
!set name_manual_explanation=<b>Uitleg.</b> In de kolom <tt>Gemiddelde</tt> , <tt>auto</tt> \
betekend het gemiddelde cijfer voor de server geregistreerde oefeningen en opdrachten in werkbladen,\
<tt>Docent</tt> betekend het gemiddelde cijfer over de handmatig ingevoerde scores door de docent/supervisor,\
en <tt>globaal</tt> wordt berekend aan de hand van de formule

!endif

!set name_title_showsheet=!nosubst details van werkblad $numshowsheet<br>$sh_title
!set name_percentagegot=Percentage van de verkregen punten
!set name_qualitygot=Kwaliteit berekend over een maximum van 10
!set name_percentagedone=Percentage van het afgeronde werk
!set name_post=Laat zien&nbsp;:
  
!if $job=userprop
  !distribute items Verander,Registratie nummer,Opmerkingen,Foto url, (technische) Variabelen,\
   Klasse wachtwoord,Geef het klasse wachtwoord\
   into name_change,name_regnum,name_comments,name_photourl,name_vars,\
  name_classpassword,name_enterpassword
  !goto end
!endif

!if $job=examcheck
 !set name_title_examcheck=!nosubst Proefwerk details van $user_lastname, $user_firstname
 !set name_no_exampart=Deze student heeft nog geen volledig proefwerk gemaakt.
 !set name_no_exampart=Hier staan alle proefwerk sessies van deze student.\
 Klik op een oefening om de inhoud te bekijken.
 !goto end
!endif
!if $job=getraw
  !set name_title_getraw=!nosubst Alle details van $lastname, $firstname <br>(in onbewerkte data)  
  !goto end
!endif

!set name_direct_score=ruwe cijfer lijst

!if $job=transfer
   !set name_title_transfer=Verplaatsen van activiteiten
   !distribute items Samenvoegen, Vervangen,Bekijken\
   into name_merge, name_replace,name_show
!endif
!set name_topten=!nosubst Top $class_topscores van deze clas
:end
