<p><hr width=35%>

!read Exindex
!set exocnt=!itemcnt $exolist
!set qcnt=8
!if $qcnt>$exocnt
 !set qcnt=$exocnt
!endif
!if $exocnt<1
 Désolé, aucun exercice n'est disponible sous ce module pour l'instant. 
 Revenez plus tard!
 !exit
!endif
!if $exocnt=1
 Ce module contient en ce moment un seul exercice, <b>
 !item 1 of $titlelist
 </b>.
 !set exoo=!item 1 of $exolist
 !href cmd=new&module=$module&exo=$exoo Essayez-le.
 !exit
!endif

!form new
<input type=hidden name=module value=$module>
<center><table border=0><tr>
<td align=center>Choisissez les exercices&nbsp;:<td>
!if $exocnt>6
 !set selsize=6
!else
 !set selsize=$exocnt
!endif
!set wims_formselect_switch=multiple size=$selsize
!set exo=$special_parm
!if $exo!=$empty
 !set exolist=!listuniq $exo,$exolist
 !set exolist=!replace , by , $ in $exolist
 !set dictionary=$module_dir/Extitles
 !set translator_unknown=leave
 !set titlelist=!exec translator $exolist
!endif
!formselect exo list $exolist prompt $titlelist
!set wims_formselect_switch=
<tr><td align=center>Une séance aura<td>
!set qnum=1
!formselect qnum from 1 to $qcnt
exercices.
<tr><td align=center>Niveau de sévérité<td>
!set qcmlevel=3
!formselect qcmlevel from 1 to 8
!read introhook.phtml
</table> <p>
<input type=submit value="Au travail">
</center>
</form>
<b>Remarques</b>. Les exercices proposés seront pris aléatoirement dans la
liste de votre choix. Si votre choix est vide, tous les exercices 
disponibles seront considérés.
!if * isin $titlelist
 <p>Les exercices marqués par un * sont en général plus difficiles que les
 autres.
!endif

