
<h3><center>WIMS模块的地址约定</center></h3>

激活的模块有一个形如
<font color=green><tt>区域/范畴/名称.语言</tt></font>
的地址. 对于正在开发中的模块, 上述地址转换成
<font color=green><tt>区域~范畴~名称.语言</tt></font>.

<ul>
<li>区域: 受限于系统允许的区域. 
其中以一个大写英文字母后接一个数字的是与学校的年级对应的区域.
<font color=blue><tt>Lang</tt></font>对应于语言学习材料,
<font color=blue><tt>tool</tt></font>是各种在线工具,
<font color=blue><tt>local</tt></font>是仅在本地服务站内使用的模块,
<font color=blue><tt>test</tt></font>是未发布的测试区域,
这里面可以放任何东西.

</li><li>范畴: 这可以是你选取的任何词语, 不过当你提交模块供发布时,
它必须是系统能识别的范畴.
<p>
请看以下已有模块的范畴. 有疑问时可以写信给
!mailurl $sysadmin 发布协调员
.

</li><li>名称: 你喜欢的任何(英语)字母串, 最好是4至12个小写英文字母.

</li><li>语言: 两个英文字母的代码, 必须是网站支持的语言($wims_site_languages),
例如中文为 cn, 英文为 en. 必须与模块中的 INDEX 文件里定义的语言一致.

</li></ul>

<p>
一些已知的范畴: (不全)
!read wimshome/public_html/bases/sys/categories.phtml
