
<h3><center>模块的WIMS版本(wims_version)</center></h3>

<p>
WIMS是迅速发展的系统. 每个新版本都会增加新的功能.
</p><p>
在新版WIMS里开发的模块不一定能在旧版的服务器里运行,
因为它可能缺少某些必须的功能.
</p><p>
因此WIMS拒绝执行需要更加新的WIMS版本的模块.

</p><p>
若你的模块是在WIMS-$wims_version下开发的, 
为安全起见你应该宣布它的WIMS版本是$wims_version.
除非你能肯定它没有用到新的功能, 从而你宣布一个旧的WIMS版本.
但是一旦你的判断错误, 使用者会在做你的模块时遇到无数的毛病!

</p><p>
WIMS version must be written like <tt>d.dd</tt> or <tt>d.dda</tt>
where the <tt>d</tt>'s are fingers and the <tt>a</tt> is a letter, the whole word beeing
of course a real version of WIMS.
</p>