// This file is automatically generated by the build.py script. Do not edit!

/*
 * Copyright (C) 2008 Mihai Preda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.javia.arity;

class VM {

public static final byte
RESERVED = 0,
CONST = 1,
CALL = 2,
ADD = 3,
SUB = 4,
MUL = 5,
DIV = 6,
MOD = 7,
RND = 8,
UMIN = 9,
POWER = 10,
FACT = 11,
SQRT = 12,
CBRT = 13,
EXP = 14,
LOG = 15,
SIN = 16,
COS = 17,
TAN = 18,
ASIN = 19,
ACOS = 20,
ATAN = 21,
SINH = 22,
COSH = 23,
TANH = 24,
ASINH = 25,
ACOSH = 26,
ATANH = 27,
ABS = 28,
FLOOR = 29,
CEIL = 30,
SIGN = 31,
MIN = 32,
MAX = 33,
GCD = 34,
COMB = 35,
PERM = 36,
LOAD0 = 37,
LOAD1 = 38,
LOAD2 = 39,
LOAD3 = 40,
LOAD4 = 41,
BYTECODE_END = 42;

public static final String[] opcodeName = {
"reserved",
"const",
"call",
"add",
"sub",
"mul",
"div",
"mod",
"rnd",
"umin",
"power",
"fact",
"sqrt",
"cbrt",
"exp",
"log",
"sin",
"cos",
"tan",
"asin",
"acos",
"atan",
"sinh",
"cosh",
"tanh",
"asinh",
"acosh",
"atanh",
"abs",
"floor",
"ceil",
"sign",
"min",
"max",
"gcd",
"comb",
"perm",
"load0",
"load1",
"load2",
"load3",
"load4",
"bytecode_end"
};

public static final byte[] builtinArity = 
{-1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, -1, -1, -1, -1, -1, -1};

}
