<html><head>
$wims_html_header
</head><body $wims_htmlbody>
!headmenu

!if $sheet_docpage!=$empty
 !changeto docpage.phtml
!endif
<center><h3>$wims_classname, $wims_institutionname</h3>
<hr> <p><h1>Feuille de travail numéro $sh<br>$sheet_title</h1></center> <p>
$sheet_desc <p>

!if $sheet_expiration!=$empty and $sheet_active=1
 !set expday=!char 7,8 of $sheet_expiration
 !set expmon=!char 5,6 of $sheet_expiration
 !set expyear=!char 1 to 4 of $sheet_expiration
 !set months=janvier,février,mars,avril,mai,juin,juillet,août,septembre,octobre,novembre,décembre
 !set expmon=!item $expmon of $months
 Vous pouvez travailler sur cette feuille jusqu'au
 $expday $expmon $expyear.
 <p>
!endif

!if $sheet_active=2
 <blink><b><font color=red>Warning</font></b></blink>
 Cette feuille est périmée. Vous pouvez
 encore travailler dessus mais vos notes ne seront plus prises en compte.
 <p>
!endif

!if $n=0
 !if $sheet_active=$empty
  Vous n'êtes pas autorisé à consulter le contenu de cette feuille pour
  l'instant. Veuillez contacter votre enseignant.
 !else
  Cette feuille est vide! Rien n'est écrit pour vous dedans. Peut-être
  une erreur de manipulation de la part de votre enseignant.
 !endif
!else
 Devoirs dans cette feuille&nbsp;: (L'enregistrement de notes est
 !set scorestat=!getscorestatus sheet=$sh
 !if $scorestat=yes
  !if $wims_scorereg!=suspend
   ouvert, mais vous pouvez
   !href cmd=resume&job=suspend le suspendre
.)
  !else
   !set scorestat=no
   suspendu par vous-même.
   !href cmd=resume&job=reopen Le réactiver
.)
  !endif
 !else
  fermé pour votre connexion.)
 !endif
 <div class="wims_sheet">
 <p><ul class="wims_sheet_list">
 !for i=1 to $n
  !set ex=!record $i of wimshome/log/classes/$wims_class/sheets/.sheet$sh
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  !set dep=!row $i of $deps
  !set dep=!trim $dep
  <li class="wims_sheet_list"><p>$i. 
  !if $dep=$empty or $scorestat!=yes
   !href module=$di&cmd=new&worksheet=$sh&$pa $ti
, $de
   !if $require>0
    <small>$[$got] des $[$require] points requis, qualité
    $[$mean]/10. </small>
   !endif
  !else
   <font color=red><b>$ti</b></font>, $de
   !if $require>0
    <small>($[$require] points requis.)</small>
   !endif
  !endif
  !if $dep!=$empty
   <small>Vous devez améliorer
   vos notes sur
   !if , isin $dep
    les exercices $dep
   !else
    l'exercice $dep
   !endif
   avant d'avoir des notes sur celui-ci.
   </small>
  !endif
 </li>
 !next i
 </ul>
 </div>
!endif

!if $wims_user=supervisor
<p>
!href module=adm/class/sheet&sheet=$sh Page de gestion de la feuille
 (pour enseignant).
!endif
!if $n>0
 !href cmd=reply&job=print Version imprimable
.
 !if $exolog!=$empty
  !href module=adm/class/exolog&job=llist&logsheet=$sh Enregistrer les détails d'un exercice
.
 !endif
!endif
<p>

!tail

