

!! définition des noms pour les liens dans le menubox (définis par wims_menu_items)
!distribute items Insérer un fichier source,\
		Vue des participants,\
		Source de la feuille, \
into wims_name_putsource,wims_name_participantview,wims_name_sheetsource

!set name_student1=!nosubst Vous pouvez travailler sur cette feuille jusqu'au $expday $expmon $expyear.
!set name_student2=Cette feuille est périmée. Vous pouvez\
 encore travailler dessus mais vos notes ne seront plus prises en compte.
!set name_student3= Vous n'êtes pas autorisé à consulter le contenu de cette feuille pour\
  l'instant. Veuillez contacter votre enseignant.
!set name_student4=Cette feuille est vide! Peut-être\
  une erreur de manipulation de la part de votre enseignant.
!set name_score=!nosubst $[$got] des $[$require] points requis, qualité
!set name_score2=!nosubst ($[$require] points requis.
!set name_deps=Vous devez améliorer vos notes sur les exercices
!set name_dep=Vous devez améliorer vos notes sur l'exercice
!set name_dep2=avant d'avoir des notes sur celui-ci.
!set name_scoresuspend=L'enregistrement des notes est suspendu.
!set name_scoreopen=L'enregistrement des notes est ouvert.
!set name_scoreclose=L'enregistrement des notes est fermé pour cette connexion.


!set name_textsource=Voici le fichier source de cette feuille. Vous pouvez l'importer \
  dans votre classe en utilisant un copier-coller.
!set name_answer=Réponse à l'exercice

!set name_title=!nosubst Feuille de travail numéro $sh
!set name_empty=La feuille est vide&nbsp;! Il y a probablement une erreur.

!set name_exo=!defof name_exo in wimshome/public_html/scripts/oef/$lang/names
!set name_noprint=!defof name_noprint in oef/$lang/names
!set name_answers=!defof name_answers in oef/$lang/names

!distribute items niveau approximatif,durée \
into name_level,name_duration