!set wims_texsize=$mytexsize
!set n=$counter
!if $showanswer=0
    $finalresult
    !! to ensure playback of the exam is possible
    !if $wims_user=supervisor
	    <span class="schaersvoorde_alarm">Alert: these results are only visible for the supervisor</span>
	    <table summary="" bgcolor="$bgcolor2" cellpadding="10" cellspacing="$cellspacing" border="1">
		!for n=1 to $total_exos
		    <tr>
		    <td valign="top" nowrap="nowrap">
			    !if $total_exos >1
				$questionnumber <b>$n</b>)
			        <br />
			    !endif
			    $(question$n)
			    !if $(formula$n) !=$empty
				<br />
				!insmath $(formula$n) 
			    !endif
			    !if $(texanswer$n) != $empty
				<hr />
				!insmath $(texanswer$n)
			    !endif
			    !if $(textanswer$n) != $empty
				<br />
				<hr />
			        <span style="color:green">$(textanswer$n)</span>
        		    !endif
			</small>
		    </td>
		    <td  valign="top" nowrap="nowrap">
		    <strong>$youranswer</strong>
			!if $(reply$n) != $empty
			    <br />
			    !if $multiimage=1
			    	!if $(reply$n) = ?
			    	    $dontknow
			    	!else
				    !if $plot=1
					!insplot $(reply$n)
				    !else
					!if $draw=1
					    !insdraw $(reply$n)
					!endif
				    !endif
				!endif
			    !else	
				!if $math=1
				    !insmath $(reply$n)
				!else
				    <kbd>$(reply$n)</kbd>
				!endif
			    !endif
			!else
			    <strong>$dontknow</strong>
			!endif
		    </td>
		    </tr>
		!next n
	    </table>
    !endif
!else
    <table summary="" bgcolor="$bgcolor2" cellpadding="10" cellspacing="$cellspacing" border="1">
    !for n=1 to $total_exos
	<tr>
	<td valign="top" nowrap="nowrap">
	!if $total_exos >1
	    $questionnumber <b>$n</b>)<br />
	!endif
	$(question$n)
	!if $(formula$n) !=$empty
	    <br />
	    !insmath $(formula$n) 
	!endif
	!if $(texanswer$n) != $empty
	    <hr />
	    !insmath $(texanswer$n)
	!endif
	!if $(textanswer$n) != $empty
	    <br />
	    <hr width="50%">
	    <span style="color:green">$(textanswer$n)</span>
    	!endif
	</td>
	!if $(image$n) != $empty
	    <td valign="top" nowrap="nowrap">
		!if $plot=1
		    !set insplot_set=$(image_settings$n) ; size 0.5,0.5;
		    !insplot $(image$n)
		!else
		    !if $draw=1
			!set insdraw_size=$(image_settings$n)
			!insdraw $(image$n)
		    !endif
		!endif
	    </td>
	!endif
	!if $(object$n)!= $empty
	    <td valign="top" nowrap="nowrap">
		$(object$n)
	    </td>
	!endif
	<td valign="top" nowrap="nowrap">
	    <strong>
		$youranswer
	    </strong>
	!if $(reply$n) != $empty
	    <br />
	    !if $multiimage=1
		!if $(reply$n) = ?
		    $dontknow
		!else
		    !if $plot=1
			!insplot $(reply$n)
		    !else
			!if $draw=1
			    !insdraw $(reply$n)
			!endif
		    !endif
		!endif
	    !else
		!if $math=1
		    !insmath $(reply$n)
		!else
		    <kbd>
			$(reply$n)
		    </kbd>
		!endif
	    !endif
	!else
	    <strong>$dontknow</strong>
	!endif
	<hr />
	!if $goodbadsign>0
	    <strong>
		$(remark$n)
	    </strong>
	!endif
	</td>
	</tr>
    !next n
    </table>
    $finalresult
!endif

!ifval $try >0
    <p align="left">
    !set s=!record 87 of $remarkdir/commonremarks.$taal
	<span class="schaersvoorde_alarm">
	    $s
	</span>
    </p>
!endif
!exit










