!set n=$counter
<!-- begin myheader.phtml -->
!read $phtmldir/myheader.phtml
<!-- end myheader.phtml -->
!if $mathview=5
<!-- begin mymathinput.phtml mathview=5 questiontype=10 -->
    !read $phtmldir/mymathinput.phtml
<!-- end mymathinput.phtml mathview=5 questiontype=10 -->
 !exit
!endif

!if $questiontype=0
<!-- begin myfreestyle.phtml questiontype=0 -->
    !read $phtmldir/myfreestyle.phtml
<!-- end myfreestyle.phtml questiontype=0 -->
 !exit
!endif

!if $questiontype=1
<!-- begin mymultiplechoice.phtml questiontype=1 -->
    !read $phtmldir/mymultiplechoice.phtml
<!-- end mymultiplechoice.phtml questiontype=1 -->
 !exit
!endif

!if $questiontype=2
<!-- begin mydragdrop.phtml questiontype=2 -->
    !read $phtmldir/mydragdrop.phtml
<!-- end mydragdrop.phtml questiontype=2 -->
 !exit
!endif

!if $questiontype=2B
<!-- begin mydragdrop2.phtml questiontype=2B -->
    !read $phtmldir/mydragdrop2.phtml
<!-- end mydragdrop2.phtml questiontype=2B -->
 !exit
!endif

!if $questiontype=3
<!-- begin myhotspot.phtml questiontype=3 -->
    !read $phtmldir/myhotspot.phtml
<!-- end myhotspot.phtml questiontype=3 -->
 !exit
!endif

!if $questiontype=4
<!-- begin mygeogebra.phtml questiontype=4 -->
    !read $phtmldir/mygeogebra.phtml
<!-- end mygeogebra.phtml questiontype=4 -->
 !exit
!endif

!if $questiontype=5
<!-- begin myzirkel.phtml questiontype=5 -->
    !read $phtmldir/myzirkel.phtml
<!-- end myzirkel.phtml questiontype=5 -->
 !exit
!endif

!if $questiontype=7
<!-- begin myjavascript.phtml questiontype=7 -->
    !read $phtmldir/myjavascript.phtml
<!-- end myjavascript.phtml questiontype=7 -->
 !exit
!endif

!if $questiontype=8
<!-- begin myhotspot2.phtml questiontype=8 -->
    !read $phtmldir/myhotspot2.phtml
<!-- end myhotspot2.phtml questiontype=8 -->
 !exit
!endif

!if $questiontype=9
<!-- begin mytexinput.phtml questiontype=9 -->
    !read $phtmldir/mytexinput.phtml
<!-- end mytexinput.phtml questiontype=9 -->
 !exit
!endif

!if $questiontype=10
<!-- begin mymathinput.phtml questiontype=10 -->
    !read $phtmldir/mymathinput.phtml
<!-- end mymathinput.phtml questiontype=10 -->
 !exit
!endif

!if $questiontype=11
<!-- begin myrooster.phtml questiontype=11 -->
    !read $phtmldir/myrooster.phtml
<!-- end myclicktile.phtml questiontype=11 -->
 !exit
!endif

!! emergency
!if $questiontype notin 01234789
<!-- begin questiontype != 012345789 ERROR -->
    !read $phtmldir/myfreestyle.phtml
<!-- begin questiontype != 012345789 ERROR -->
 !exit
!endif
