!! item_list : lines
!! item_type : items
!set DHTML=$empty
!set n=$counter
!if $dragcolors=$empty
    !set unused_color=#ff0000
    !set pick_color=#639bff
    !set drop_color=#00fc96
    !set blue_layer=#b2d1ff
!else
    !set unused_color=!item 1 of $dragcolors
    !set pick_color=!item 2 of $dragcolors
    !set drop_color=!item 3 of $dragcolors
    !set blue_layer=!item 4 of $dragcolors
!endif
!set c=0
!set f=0
!set total_objects=!itemcnt $item_type
!set break=0
<center>
 <table summary="" border="0" bgcolor="$bgcolor1" cellpadding="$cellpadding" cellspacing="$cellspacing">
    <tr>
    <td>
	$(question$n)
	!if $exotext!=$empty
	    <br>	
	    <small>
		<em>
		    $exotext
		</em>
	    </small>
	!endif	
    </td>
    </tr><tr>
    <td align="center">
	<table summary="draggable items">
	    <tr>
	    !for p=1 to $total_objects
		!increase break
		!set thing=!line $p of $item_list
		!set type=$(item_type[$p])
		<td style="text-align:center;background-color:$blue_layer;vertical-align:middle;">
		    <div id="mydiv$c" style="width:$xsize;height:$ysize;text-align:center;background-color:$unused_color;position:relative;border:2px solid red;">
			!if $type=0
			    $thing
			!else
			    !if $type=1
				!if $tex_adjust=1
				    !set ins_attr=width="$xsize"
				!endif
				!insmath $thing
			    !else
				!if $type=2
				    !set ins_attr=width="$xsize" height="$ysize"
				    !insdraw $thing
				!else
				    !if $type=3
					!set ins_attr=width="$xsize" height="$ysize"
					!insplot $thing
				    !else
					error: no type definitionlist $$item_type[$p]
				    !endif
				!endif
			    !endif
			!endif
			!set DHTML=!append item "mydiv$c" to $DHTML
		    </div>
		</td>
		!if $break=1
		<td style="background-color:$blue_layer;text-align:center;vertical-align:middle;height:$ysize;width:$xsize">
		    <center>
			<img src="$gifdir/blank.gif" style="display:block" id="blank$c" alt="" width="$xsize">
			<img src="$gifdir/leftright.gif" style="display:none" id="leftright$c" alt="" width="$xsize">
		    </center>
		</td>
		!endif
		!if $break = 2
		    !set break=0
		    </tr>
		    <tr>
		!endif
		!increase c
	    !next p
	    </tr>
	</table>
    </td>
    </tr>
    <tr>
    <td align="center">
	<table summary="send buttons">
	    <tr>
	    <th>
    		<input type=button style="$mybuttonstyle" onclick="sendanswer();" value="$send">
    	    </th>
	    <th>
		!if $wims_user = supervisor
    		    <input type="button" style="$mybuttonstyle" onclick="showanswer();" value="show correct answer">		
		!else
		    !set clear=!record 67 of $remarkdir/commonremarks.$taal
    		    <input type=button style="$mybuttonstyle" onclick="resetall();" value="$clear">
    		!endif
	    </th>
	    <th>
		<input type=button style="$mybuttonstyle" onclick="dontknow();" name="but2" value="$dontknow">
	    </th>
	    </tr>
	</table>
    </td>
    </tr>
 </table>
</center>
 
<script type="text/javascript" src="$jsdir/wz_dragdrop.js"></script>

<script type="text/javascript">
    SET_DHTML( CURSOR_MOVE , $DHTML);	
    var orgx = 0;
    var orgy = 0;
    var pick_id = 0;
    var size=dd.elements.length;
    var reply = new Array();
    for(var p = 0;p < size; p++){
	reply[p] = p;
    }
    
    function resetall(){
	document.location.reload();
    }
    
    function my_PickFunc(){
	orgx = dd.obj.x;
	orgy = dd.obj.y;
	pick_id=dd.obj.id;
	document.getElementById(dd.obj.id).style.backgroundColor = "$pick_color";
    }
    
    function setVisible(n){
	document.getElementById("leftright"+n).style.display = "block";
	document.getElementById("blank"+n).style.display = "none";
	return;
    }
    
    !if $wims_user=supervisor
	var only_once = 0;
	function showanswer(){
	    if(only_once == 0 ){
		!set r=0
		x_original = new Array();
		y_original = new Array()
		!for p in $(answer$n)
		    reply[$r] = "$p";
		    x_original[$r] = dd.elements["mydiv$r"].x;
		    y_original[$r] = dd.elements["mydiv$r"].y;
		    !increase r
		!next p
		!set r=0
		!for p in $(answer$n)
		    dd.elements["mydiv$p"].moveTo(x_original[$r],y_original[$r]);
		    try{setVisible($p);}catch(e){}
		    document.getElementById("mydiv$p").style.backgroundColor = "$drop_color";
		    !increase r
		!next p
	    only_once=1;
	    }
	    return;
	}
    !endif
    
    function my_DropFunc(){
	var marge=10;var x=dd.obj.x;var y=dd.obj.y;var found=0;var tmp;var idx;var id;
	if( dd.obj.id == pick_id ){
	    id = pick_id.replace("mydiv","");
	    for(var p = 0; p < size  ; p++){
		if(reply[p] == id){
		    idx = p; // dus sleepplaatje heeft rangvolgorde idx
		}
	    }
	    for(var p = 0; p < size  ; p++){
		if(found == 0 && reply[p] != id){
		    if( y > dd.elements["mydiv"+reply[p]].y - marge && y < dd.elements["mydiv"+reply[p]].y + marge){
			if( x > dd.elements["mydiv"+reply[p]].x - marge && x < dd.elements["mydiv"+reply[p]].x + marge){
			    dd.obj.moveTo(dd.elements["mydiv"+reply[p]].x,dd.elements["mydiv"+reply[p]].y);
		    	    dd.elements["mydiv"+reply[p]].moveTo(orgx,orgy);
			    found = 1;
			    tmp = reply[p];
			    try{setVisible(p);}catch(e){}
			    try{setVisible(idx);}catch(e){}
			    reply[p] = reply[idx];
			    reply[idx] = tmp;
			    document.getElementById("mydiv"+reply[p]).style.backgroundColor = "$drop_color";
			    document.getElementById("mydiv"+reply[idx]).style.backgroundColor = "$drop_color";
			}
		    }
		}
	    }
	}
	if(found == 0){ dd.obj.moveTo(orgx,orgy);
	document.getElementById(dd.obj.id).style.backgroundColor = "$unused_color";}
	dd.obj='null';
    }
    
    function sendanswer(){
	if(confirm(r0+"\n"+reply)){
	    reply=encodeURIComponent(reply + "\n" + connect);
	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+reply ;
	    document.location.href = URL;
	}
    }
</script>
