!! 4 types of input are possible with this page , single or in any combination
!! 1) mathview inputapplet via "id" ; 
!! 2) inputfields via normal "mydefaultform"  ; 
!! 3) mathml inputfields via "id"
!! 4) svg answer (via draw or inputfields/textarea [ read_svg();]

!if $my_arrows=$empty
    !set my_arrows=2
!endif

<script type="text/javascript">
//<![CDATA[
    var URL;

    function dontknow(){
	t = confirm(r0+"\n$dontknow ?");
	if( t == true){
	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=%3F' ;
	    document.location.href = URL;if(document.getElementById("MathView")){document.getElementById("MathView").destroy();}
	}
    }

    function sendanswer(){
	var input;
	var show="";
	var reply = new Array;
	var applet = 0;
	var inputfieldnumber = 0;
	var input;
	if(document.getElementById("MathView")){
	    input=document.getElementById("MathView").getLinear();input = input+'';
	    if( input.length == 0){setAlarm(r1+"\ 1");return;}
	    if( input.length > 100){setAlarm(r2); return;}
	    if(input.indexOf('error')!=-1){setAlarm(input);return;}
	    input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
	    input = nthroot(input);if(input ==" error"){return;}
	    if(input.indexOf(',') != -1){setAlarm(r4);return;}
	    if(check_f(input) == 0){return;}if(check_o(input) == 0){return;}
	    if(check_log_NaN(input) == 0){return;}if(check_sqrt_NaN(input) == 0){return;}
	    input = science(input);if(input == "error"){return;}
	    if(check_x(input) == 0){return;}
	    show=input+"\n";
	    if(input.indexOf("[") !=- 1){
		if(input.indexOf("sqrt[")!=-1){input=specialroot(input);if(input=="error"){return;}}
		if(input.indexOf("log[")!=-1){input=speciallog(input);if(input=="error"){return;}}
		if( input.indexOf("[") !=-1){setAlarm(r13);return;}
	    }
	    input = input.replace(/#/g,' ');
	    reply[0] = input;
	    applet=1;
	    inputfieldnumber = 1;
	}
	
	if(document.mydefaultform){
	    var ml=document.mydefaultform.elements.length;
	    for(var z = 0 ; z < ml; z++){
		input = document.mydefaultform[z].value;
		if(input.length == 0){var qu = z+1; setAlarm(r1+"\ "+qu);return;}
		input = nthroot(input);if(input == "error"){return;}
		if(input.indexOf(',') != -1){setAlarm(r4);return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}
		if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}
		if(check_sqrt_NaN(input)==0){return;}
		input = science(input);if(input == "error"){return;}
		if(check_x(input) == 0){return;}
		show=show+input+"\n";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[")!=-1){input=specialroot(input);if(input=="error"){return;}}
		    if(input.indexOf("log[")!=-1){input=speciallog(input);if(input=="error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input=input.replace(/#/g,' ');
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
	    }
	}
	
	if(document.getElementById("mathml0")){
	    var p=0;
	    while(document.getElementById("mathml"+p)){
		input = document.getElementById("mathml"+p).value;
		if (input.length == 0){setAlarm(r1+" "+parseInt(p+1));return;}
		input = nthroot(input);if(input == "error"){return;}
		if(input.indexOf(',') != -1){setAlarm(r4);return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}if(check_sqrt_NaN(input) == 0){return;}
		input=science(input);if(input == "error"){return;}
		if(check_x(input) == 0){return;}
		show=show+input+"\n";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[") != -1){input = specialroot(input);if(input == "error"){return;}}
		    if(input.indexOf("log[") != -1){input = speciallog(input);if(input == "error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input = input.replace(/#/g,' ');
		if(p>99){break;}
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
		p++;
	    }
	}
	
	try{
	    var svg_reply = read_svg();
	    for( var p = 0 ; p < svg_reply.length ; p++){
		input = svg_reply[p];
		if (input.length == 0){setAlarm(r1+" "+parseInt(p+1));return;}
		input = nthroot(input);if( input == "error"){return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}
		if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}
		if(check_sqrt_NaN(input) == 0){return;}
		input = science(input);if(input == "error"){return;}
		show=show+input+"\n";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[") != -1){input = specialroot(input);if(input == "error"){return;}}
		    if(input.indexOf("log[") != -1){input = speciallog(input);if(input == "error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input = input.replace(/#/g,' ');
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
	    }	
	}catch(e){}
	if(reply.length == 0 ){setAlarm(r1);return;}
	if(confirm(r0+"\n"+show)){reply=encodeURIComponent(reply);URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+reply ;document.location.href = URL;if(applet==1){document.getElementById("MathView").destroy();}}
    }
//]]>
</script>
    <table class="schaersvoorde_form">
	<tr>
	<td>
	    !if $(question$n) != $empty
		$(question$n)
		<br />
	    !endif
	    !if $(formula$n) != $empty
		!if $embed=1
		    !if $mathview = 3
			!!! hmmm
			    !insmath $(formula$n)
			<br />
		    !else
			<table>
			    <tr>
			    <th>
				!insmath $(formula$n)
			    </th>
			    <th>
				<form name="mydefaultform" id="mydefaultform" action="">
				    !if $inputs=1
					!if $wims_user=supervisor
					    <table summary="inputfield"><tr><th>&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;</th><th><textarea  id="myinput0" style="$textareastyle" cols="$cols" rows="$rows" name="reply">$(answer$n)</textarea></th></tr></table>
        				!else
					    <table summary="inputfield"><tr><th>&nbsp;&nbsp; $m_rightarrow &nbsp;&nbsp;</th><th><textarea  id="myinput0" style="$textareastyle" cols="$cols" rows="$rows" name="reply">$(reply$n)</textarea></th></tr></table>
					!endif
				    !else
					<table summary="inputfields" cellspacing="1">
					!set a_items=!itemcnt $(answer$n)
					!if $a_items != $[floor($inputs)]
					    !set use_lines=1
					!else
					    !set use_lines=0
					!endif
					!for p=1 to $inputs
					    !if $wims_user=supervisor
						!if $use_lines=1
						    !set deelantwoord=!line $p of $(answer$n)
						!else
						    !set deelantwoord=!item $p of $(answer$n)
						!endif
						<tr><th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$m_rightarrow&nbsp;&nbsp;</th><th><input type="text" id="myinput$[$p-1]" style="$inputstyle" size="$cols" name="reply" value="$deelantwoord" /></th><th>$(ex$p)&nbsp;</th></tr>
        				    !else
						!set deelantwoord=!item $p of $(reply$n)
						<tr><th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$m_rightarrow&nbsp;&nbsp;</th><th><input type="text" id="myinput$[$p-1]" style="$inputstyle" size="$cols" name="reply" value ="$deelantwoord" /></th><th>$(ex$p)&nbsp;</th></tr>
					    !endif
					!next p
					</table>
				    !endif
				</form>
			    </th>
			    </tr>
			</table>
		    !endif
		!else
		    !insmath $(formula$n)
		    <br />
		!endif
	    !endif
	    !if $exotext != $empty
		<br />
		$exotext
	    !endif
	</td>
    !if $image=1
	!if $XSIZE > 450 or $mathview=3
	    !! arbitrary value to produce a better layout ...
	</tr><tr>
	!endif
	<td>
	    !if $draw=1
	    !! for fly
		!set insdraw_size=$XSIZE,$YSIZE
		!insdraw $(image$n)
	    !endif
	    !if $plot=1
		!! for GNUplot
		!set insplot_set=$(image_settings$n)
		!insplot $(image$n)
	    !endif
	    !if $svg=1
		!exec svgdraw $(image$n)
	    !endif
	</td>
    !endif
    !if $applet=1
	!if $XSIZE > 450 or $mathview=3
	    !! arbitrary value to produce a better layout ...
	</tr><tr>
	!endif
	<td>
	    $(object$n)
	</td>
    !endif
!if $embed != 1 or $[$embed+$mathview]=4
    !if $XSIZE > 450 or $mathview=3
	</tr><tr>
    !endif
	<td>
	    !if $mathview=3
		<table summary="java input applet" $paperbg width="580">
		    <tr>
		    <th>
			<object classid="java:MathView.class" id="MathView" width="580" height="280" type="application/x-java-applet;jpi-version=1.4" >
			    <param name="java_codebase" value="$appletdir" />
			    <param name="java_archive" value="MathView.jar" />
			    <param name="java_code" value="MathView" />
			    <param name="mayscript" value="true" />
			    <script language="javascript" type="text/javascript">
				var thisbackground=document.bgColor;
				if(thisbackground){var obj="\<param name=\"bgcolor\" value=\""+thisbackground+"\" /\>"}else{var obj="\<param name=\"bgcolor\" value=\"#ffffff\" /\>"}
				document.write(obj.toString());
			    </script>
			    <param name="largefont" value="$largefont">
			!if $wims_user=supervisor
			    <param name="oldreply" value="
			    !nospace $(answer$n)
			    "/>
			!else
			    <param name="oldreply" value="
			    !nospace $(reply$n)
			    "/>
			!endif
			    <param name="smallfont" value="$smallfont">
			    <param name="helptext" value="$applettext">
			    <param name="wimsvars" value="$varlist">
			    <param name="special_fraction" value="$special_fraction">
			    !! declare varlist=x,y,z,s    or varlist=x y z s
			!if $mathviewpanel=$empty
			    <param name="my_panel" value="$module_title:and:or:sqrt():+:-:*:/">
			!else
			    <param name="my_panel" value="$mathviewpanel">
			!endif
			$nojava
			</object>
		    </th>
		    </tr>
		</table>
	    !else
		!if $inputs=1
		    <form name="mydefaultform" id="mydefaultform" action="">
			<table>
			    <tr>
			!if $inputtext1!=$empty
			    <td>
				$inputtext1:
			    </td>
			!endif
			    <td>
			!if $wims_user=supervisor
            		    <textarea  id="myinput0" style="$textareastyle" cols="$cols" rows="$rows" name="reply">$(answer$n)</textarea>
        		!else
            		    <textarea  id="myinput0" style="$textareastyle" cols="$cols" rows="$rows" name="reply">$(reply$n)</textarea>
        		!endif
			    </td>
			    </tr>
			</table>
		    </form>
		!else
		    !if $inputs>1
		    <form name="mydefaultform" id="mydefaultform" action="">
			<table>
			!set a_items=!itemcnt $(answer$n)
			!if $a_items != $[floor($inputs)]
			    !set use_lines=1
			!else
			    !set use_lines=0
			!endif
			!for p=1 to $inputs
			    <tr>
			    <td>
				!if $inputs>=2
				    $p)&nbsp;
				!endif
				$(inputtext$p)
			    </td>
			    <td>
				$m_rightarrow
			    </td>
			    <td>
			    !if $wims_user=supervisor
				!if $use_lines=1
			    	    !set deelantwoord=!line $p of $(answer$n)
				!else
			    	    !set deelantwoord=!item $p of $(answer$n)
				!endif
			    !else
				!set deelantwoord=!item $p of $(reply$n)
			    !endif
				<input id="myinput$[$p-1]" style="$inputstyle" size="$cols" name="reply" value="$deelantwoord" />
			    </td>
			    <td>
				$(ex$p)
				&nbsp;
			    </td>
			    </tr>
			!next p
			</table>
		    </form>
		    !endif
		!endif
	    !endif
	</td>
!endif
	</tr>
    </table>
    <table class="schaersvoorde_form">
	<tr>
    !if $inputs !=0
	<th>
    	    <input type="button" style="$mybuttonstyle" onclick="sendanswer();" value="$send" />
    	</th>
    !endif
	<th>
	    <input type="button" style="$mybuttonstyle" onclick="dontknow();" name="but2" value="$dontknow" />
	</th>
	</tr>
    </table>
!exit
