!! 7 types of input are possible with this page , single or in any combination
!! 1) mathview inputapplet via id="MathView" ; 
!! 2) inputfields via id="myinput0" ... id="myselect100"
!! 3) selectboxes via id="myselect0" ... id="myselect100"
!! 4) mathml inputfields via id="mathml0" ... id="mathml100"
!! 5) svg answer (via draw or inputfields/textarea [ read_svg();]
!! 6) FlyApplet drawing via ReadDrawing() : coordinates/points/lines x1:y1,x2:y2,x3:y3....x_n:y_n (wordmax (=20) is adjustable upperlimit ; wordmin (=1) is adjustable underlimit) from FlyApplet0...FlyApplet100
!! 7) InvulGrid applet via ReadApplet(0,1,2,3) ; carefull applet produces large strings (html/latex)
!if $my_arrows=$empty
    !set my_arrows=2
!endif
<script type="text/javascript">
//<![CDATA[
<!-- no validator  -->
    var descr_list="$description";
    var descr_cnt = 30;
    var description = list2array(descr_list,descr_cnt);

    function dontknow(){
	myConfirm('$dontknow','%3F','$wims_ref_name','$session','$module','$counter','#ffbd55');
    }

    function sendanswer(){
	var input;
	var show="<ol>";
	var inputfieldnumber = 0;
	var reply = new Array();

	if(document.getElementById("MathView")){
	<!-- there can only be one...mathview -->
	    input=document.getElementById("MathView").getLinear();input = input+'';
	    if( input.length == 0){setAlarm(r1+"\ 1");return;}
	    if( input.length > 100){setAlarm(r2); return;}
	    if(input.indexOf('error')!=-1){setAlarm(input);return;}
	    input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
	    input = nthroot(input);if(input ==" error"){return;}
	    if(input.indexOf(',') != -1){setAlarm(r4);return;}
	    if(check_f(input) == 0){return;}if(check_o(input) == 0){return;}
	    if(check_log_NaN(input) == 0){return;}if(check_sqrt_NaN(input) == 0){return;}
	    input = science(input);if(input == "error"){return;}
	    if(check_x(input) == 0){return;}
	    show = "<li>"+description[inputfieldnumber] + input+"</li>";
	    if(input.indexOf("[") !=- 1){
		if(input.indexOf("sqrt[")!=-1){input=specialroot(input);if(input=="error"){return;}}
		if(input.indexOf("log[")!=-1){input=speciallog(input);if(input=="error"){return;}}
		if( input.indexOf("[") !=-1){setAlarm(r13);return;}
	    }
	    input = input.replace(/#/g,' ');
	    reply[inputfieldnumber] = input;
	    inputfieldnumber = 1;
	}

	if(document.getElementById("InvulGrid0") ){
	    var p = 0;var tmp_show;var tmp_reply;var tmp_htmlreply;var tmp_latexreply;
	    var latexreply = "";var invulgrid;
	    !if $decimals=1
		var decimals=1;
	    !else
		var decimals=0;
	    !endif
	    while( document.getElementById('InvulGrid'+p )){
		invulgrid = document.getElementById('InvulGrid'+p);
		tmp_show = invulgrid.ReadApplet('1');
		tmp_reply = invulgrid.ReadApplet('0');
		tmp_htmlreply = invulgrid.ReadApplet('2');
		tmp_latexreply = invulgrid.ReadApplet('3');
		if(tmp_reply.indexOf('error')!= -1){setAlarm(r26+"<br />(java applet no."+parseInt(p+1)+")");return;}
		if(tmp_reply.indexOf("?") != -1){dontknow();return;}
		if(decimals == 0){ 
		    tmp_reply = tmp_reply.replace(/\./g,'');
		    tmp_show = tmp_show.replace(/\./g,'');
		}
		reply[inputfieldnumber] = tmp_reply+"\n"+tmp_htmlreply+"\n"+tmp_latexreply;
		show = show + "<li>"+description[inputfieldnumber] + tmp_show + "</li>"
		inputfieldnumber++;
		p++;
		if(p>10){setAlarm(r2);dontknow();}
	    }
	}
	
	if(document.getElementById("FlyApplet0") ){
	<!-- id="FlyApplet0" is not interfering with non-readable FlyApplet based illustrations (id="FlyApplet") -->
	    var p=0;
	    while( document.getElementById("FlyApplet"+p) ){
		try{
		    input = document.getElementById('FlyApplet'+p).ReadDrawing();
		}catch(e){
		    setAlarm(r1+" $counter");return;
		}
		if(input.indexOf("error")!=-1){
		    setAlarm(r1+" $counter");return;
		}
		var tmp = input.split(',');
		if( tmp.length > $wordmax ){setAlarm(r6);return;}
		if( tmp.length < $wordmin ){setAlarm(r26);return;}
		for(var r = 0;r < tmp.length;r = r + 2){
		    show = show + "<li>"+description[inputfieldnumber] +"( "+tmp[r]+" : "+tmp[r+1]+" )</li>";
		    reply[inputfieldnumber] = tmp[r]+":"+tmp[r+1];
		    inputfieldnumber++;
		}
		p++;
		if(p>10){setAlarm(r2);dontknow();}
	    }
	}

	if(document.getElementById("myinput0")){
	    var p=0;
	    while(document.getElementById("myinput"+p)){
		input = document.getElementById("myinput"+p).value;
		if(input.length == 0){setAlarm(r1+"\ "+parseInt(p+1));return;}
		input = nthroot(input);if(input == "error"){return;}
		if(input.indexOf(',') != -1){setAlarm(r4);return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}
		if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}
		if(check_sqrt_NaN(input)==0){return;}
		input = science(input);if(input == "error"){return;}
		if(check_x(input) == 0){return;}
		show = show + "<li>"+description[inputfieldnumber] + input + "</li>";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[")!=-1){input=specialroot(input);if(input=="error"){return;}}
		    if(input.indexOf("log[")!=-1){input=speciallog(input);if(input=="error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input=input.replace(/#/g,' ');
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
		p++;
		if(p>100){setAlarm(r2);dontknow();}
	    }
	}
	
	if( document.getElementById("myselect0") ){
	    var p = 0;var options;var option_value;var option_text;
	    while(document.getElementById("myselect"+p)){
		options = document.getElementById("myselect"+p).options;
		try{ 
		    option_value = options[options.selectedIndex].value;
		    option_text = options[options.selectedIndex].text;
		}catch(e){setAlarm(r1+parseInt(p+1));return;}
		reply[inputfieldnumber] = option_value;
		show = show + "<li>" + description[inputfieldnumber] + option_text + "</li>";
	    	inputfieldnumber++;
		p++;
		if(p>100){setAlarm(r2);dontknow();}
	    }
	}
	
	if(document.getElementById("mathml0")){
	    var p = 0;
	    while(document.getElementById("mathml"+p)){
		input = document.getElementById('mathml'+p).value;
		if (input.length == 0){setAlarm(r1+" "+parseInt(p+1));return;}
		input = nthroot(input);if(input == "error"){return;}
		if(input.indexOf(',') != -1){setAlarm(r4);return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}if(check_sqrt_NaN(input) == 0){return;}
		input=science(input);if(input == "error"){return;}
		if(check_x(input) == 0){return;}
		show = show + "<li>" + description[inputfieldnumber] + input + "</li>";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[") != -1){input = specialroot(input);if(input == "error"){return;}}
		    if(input.indexOf("log[") != -1){input = speciallog(input);if(input == "error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input = input.replace(/#/g,' ');
		if(p>99){break;}
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
		p++;
		if(p>100){setAlarm(r2);dontknow();}
	    }
	}
	
	try{
	    var svg_reply = read_svg();
	    if(svg_reply.length > 100 ){setAlarm(r2);dontknow();}
	    for( var p = 0 ; p < svg_reply.length ; p++){
		input = svg_reply[p];
		if (input.length == 0){setAlarm(r1+" "+parseInt(p+1));return;}
		input = nthroot(input);if( input == "error"){return;}
		input = arrows(input,$my_arrows,"","");if(input == "error"){return;}
		if(check_f(input) == 0){return;}
		if(check_o(input) == 0){return;}
		if(check_log_NaN(input) == 0){return;}
		if(check_sqrt_NaN(input) == 0){return;}
		input = science(input);if(input == "error"){return;}
		show = show + "<li>" + description[inputfieldnumber] + input + "</li>";
		if( input.indexOf("[") !=- 1 ){
		    if(input.indexOf("sqrt[") != -1){input = specialroot(input);if(input == "error"){return;}}
		    if(input.indexOf("log[") != -1){input = speciallog(input);if(input == "error"){return;}}
		    if(input.indexOf("[") != -1){setAlarm(r13);return;}
		}
		input = input.replace(/#/g,' ');
		reply[inputfieldnumber] = input;
		inputfieldnumber++;
	    }	
	}catch(e){}
	if(reply[0].length == 0 ){setAlarm(r1);return;}
	show = show + "</ol>";
	myConfirm(show,reply,'$wims_ref_name','$session','$module','$counter','#5aeb6e');
    }
//]]>
</script>
<table id="exercise" class="exercise" >
    <tr>
    <td class="exercise_t">
	!if $(question$n) != $empty
	    $(question$n)
	!endif
	!if $embed=1
	    !if $(formula$n) != $empty
	    <table class="exercise">
		<tr>
		<td class="exercise_m">
		    !insmath $(formula$n)
		</td>
		<td class="exercise_m">
		!if $inputs=1
		    !if $wims_user=supervisor
			$m_rightarrow &nbsp;&nbsp;<textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(answer$n)</textarea>&nbsp;$ex1
        	    !else
        		$m_rightarrow &nbsp;&nbsp;<textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(reply$n)</textarea>&nbsp;$ex1
		    !endif
		!else
		    <ul class="vlist">
		    !set a_items=!itemcnt $(answer$n)
		    !if $a_items != $[floor($inputs)]
			!set use_lines=1
		    !else
			!set use_lines=0
		    !endif
		    !for p=1 to $inputs
			<li>
			!if $wims_user=supervisor
			    !if $use_lines=1
				!set deelantwoord=!line $p of $(answer$n)
			    !else
				!set deelantwoord=!item $p of $(answer$n)
			    !endif
        		!else
			    !set deelantwoord=!item $p of $(reply$n)
			!endif
			$m_rightarrow&nbsp;&nbsp;<input type="text" id="myinput$[$p-1]" class="schaersvoorde_input" size="$cols" value="$deelantwoord" />&nbsp;$(ex$p)
			</li>
		    !next p
		    </ul>
		!endif
		</td>
	    </table>
	    !endif
	!else
	    !if $(formula$n) != $empty
		!insmath $(formula$n)
	    !endif
	!endif
	!if $exotext != $empty
	    $exotext
	!endif
    </td>
!if $image=1
    !if $make_tr=1
    </tr>
    <tr>
    !endif
    <td class="exercise_t">
    !if $draw=1
	!set insdraw_size=$xsize,$ysize
	!! voor answer.phtml gebruiken we de opgeslagen variabele "insdraw_settings"
	!insdraw $(image$n)
    !endif
    !if $plot=1
	!set insplot_set=$(image_settings$n)
	!insplot $(image$n)
    !endif
    !if $svg=1
	!exec svgdraw $(image$n)
    !endif
    </td>
!else
    !if $applet=1
	!if $make_tr=1 
        </tr>
	<tr>
        !endif
	<td class="exercise_c" id="object$n">
	    $(object$n)
	</td>
    !endif
!endif
!if $mathview=3
    </tr>
    <tr>
    <td class="exercise_c">
	<object classid="java:MathView.class" id="MathView" width="580" height="280" type="application/x-java-applet;jpi-version=1.4" >
	    <param name="java_codebase" value="$appletdir" />
	    <param name="java_archive" value="MathView.jar" />
	    <param name="java_code" value="MathView" />
	    <param name="mayscript" value="true" />
	    <script type="text/javascript" />
	    //<![CDATA[
	    var thisbackground=document.bgColor;if(thisbackground){var obj="\<param name=\"bgcolor\" value=\""+thisbackground+"\" />"}else{var obj="\<param name=\"bgcolor\" value=\"#ffffff\" />"} document.write(obj.toString());
	    //]]>
	    </script>
	    <param name="largefont" value="$largefont">
	!if $wims_user=supervisor
	    <param name="oldreply" value="
	    !nospace $(answer$n)
	    "/>
	!else
	    <param name="oldreply" value="
	    !nospace $(reply$n)
	    "/>
	!endif
	    <param name="smallfont" value="$smallfont" />
	    <param name="helptext" value="$applettext" />
	    <param name="wimsvars" value="$varlist" />
	    <param name="special_fraction" value="$special_fraction" />
	    !! declare varlist=x,y,z,s    or varlist=x y z s
	!if $mathviewpanel=$empty
	    <param name="my_panel" value="$module_title:and:or:sqrt():+:-:*:/">
	!else
	    <param name="my_panel" value="$mathviewpanel" />
	!endif
	    <a onmouseover="return escape('<img src=\'$gifdir/java.jpg\' alt=\'Get JAVA\' />');" href="http://www.java.com/$lang/download/manual.jsp?locale=$lang" >
	    	$nojava
	    </a>
	</object>
    </td>
!else
    !if $embed != 1
     !if $make_tr=1
	</tr>
	<tr>
     !endif
	!if $inputs=1
	<td class="exercise_t" id="use_inputs">
	    !if $wims_user=supervisor
        	$(description[1])&nbsp;<textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(answer$n)</textarea>&nbsp;$ex1
    	    !else
    		$(description[1])&nbsp;<textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(reply$n)</textarea>&nbsp;$ex1
    	    !endif
	</td>
	!else
	    !if $inputs>1
	    <td class="exercise_t" id="use_inputs">
		<ul id="zebra_list">
	        !set a_items=!itemcnt $(answer$n)
		!if $a_items != $[floor($inputs)]
	            !set use_lines=1
		!else
	    	    !set use_lines=0
		!endif
		!for p=1 to $inputs
		    <li>
		    !if $wims_user=supervisor
			!if $use_lines=1
			    !set deelantwoord=!line $p of $(answer$n)
			!else
			    !set deelantwoord=!item $p of $(answer$n)
			!endif
        	    !else
			!set deelantwoord=!item $p of $(reply$n)
		    !endif
			$(description[$p])&nbsp;$m_rightarrow&nbsp;&nbsp;<input type="text" id="myinput$[$p-1]" class="schaersvoorde_input" size="$cols" value="$deelantwoord" />&nbsp;$(ex$p)
		    </li>
		!next p
		</ul>
	    </td>
	    !endif
	!endif
    !endif
!endif
    </tr>
</table>
<div id="send_buttons" class="embedded_central">
!if $inputs != 0
    <input type="button" class="schaersvoorde_ok_button" onclick="javascript:sendanswer();" value="$send" />
!endif
    <input type="button" class="schaersvoorde_nok_button" onclick="javascript:dontknow();"  value="$dontknow" />
</div>
!exit
