<script type="text/javascript"  src="$jsdir/geogebra2wims.js"></script>
<script type="text/javascript">
    var list_of_things=new Array();
    !if $list_of_things=$empty 
	!! A list of all possible object names
	list_of_things=['text','point','line','segment','circle','function','polygon','conic','ellipse','polynomial','vector','number','angle'];
    !else
	list_of_things=$list_of_things
    !endif
    function sendanswer(){
	var reply=geogebra2wims(list_of_things);
	reply=encodeURIComponent( reply );
	var t=confirm(" $send ?");
	if(t==true){
	    var URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+reply ;
	    document.location.href = URL;document.getElementById("ggbApplet").destroy();
	}
    }

    function dontknow(){
	var t=confirm(" $dontknow ?");
	if(t==true){
	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=%3F' ;
	    document.location.href = URL;document.getElementById("ggbApplet").destroy();
	}                                                                                                                                                                 
    } 
</script>
<p align="center">
<table summary="" bgcolor="$bgcolor1" cellpadding="$cellpadding" cellspacing="$cellspacing">
    <tr>
    <td valign="top" align="left">
	$(question$n)
	!if $(formula$n) != $empty
	    <br>
	    !insmath $(formula$n)
	!endif
	!if $exotext != $empty
	    <br>
	    $exotext
	!endif
	!if $inputs>0
	    <table summary="">
		<form name="sendtext" id="sendtext" action="">
		    !for i=1 to $inputs
			<tr>
			<td>
			    $(inputtext$i)
			</td>
			<td>
			    $m_rightarrow
			</td>
			<td>
			!if $wims_user=supervisor
			    !set voorzeggen=!item $i of $(answer$n)
			    <input  style=$textareastyle name="myvar1" size=$cols value=$voorzeggen>
			!else
			    <input  style=$textareastyle name="myvar1" size=$cols value="$myvar1">
			!endif
			</td>
			</tr>
		    !next i
		</form>
	    </table>
	!endif
    </td>
    !if $XSIZE>640
    </tr><tr>
    !endif
    <td  valign="top">
	!if $width=$empty
	    !set width=640
	    !set height=480
	!endif
	<p align="center">
	    <applet id="ggbApplet" name="ggbApplet" code="geogebra.GeoGebraApplet" codebase="java/geogebra" archive="geogebra.jar" width=$width height=$height>
		<param name="language" value="$taal">
		<param name="filename" value="../../$module_dir/$ggb">
		<param name="showToolBar"  value="$showToolBar">
		<param name="showMenuBar"  value="$showMenuBar">
		<param name="framePossible" value="$framePossible">
		<param name="customToolBar" value=$customToolBar>
		<param name="showAlgebraInput" value="$showAlgebraInput">
		$nojava
	    </applet>    
	    <script type="text/javascript">
		$appletcommand
	    </script>
	</p>
    </td>
    </tr>
</table>
<table summary="">
    <tr>
    <th>
	<input type=button style="$mybuttonstyle" onclick="sendanswer();" name="but1" value="$send">
    </th>
    <th>
	<input type=button style="$mybuttonstyle" onclick="dontknow();" name="but2" value="$dontknow">
    </th>
    </tr>
</table>
</p>

