<script type="text/javascript"  src="$jsdir/geogebra2wims.js"></script>
<script type="text/javascript">
//<![CDATA[
<!-- no validator -->
    function dontknow(){
	myConfirm('$dontknow','?','$wims_ref_name','$session','$module','$counter','$nok_send_color');
    }

    var list_of_things=new Array();
    !if $list_of_things=$empty 
	!! A list of all possible object names
	list_of_things=['text','point','line','segment','circle','function','polygon','conic','ellipse','polynomial','vector','number','angle'];
    !else
	list_of_things=$list_of_things
    !endif
    function sendanswer(){
	var reply=geogebra2wims(list_of_things);
	myConfirm("<br />$send<br />",reply,'$wims_ref_name','$session','$module','$counter','$ok_send_color');
    }
//]]>
</script>
<table id="exercise" class="exercise">
    <tr>
    <td class="exercise_t">
	$(question$n)
	!if $(formula$n) != $empty
	    <br />
	    !insmath $(formula$n)
	!endif
	!if $exotext != $empty
	    <br />
	    $exotext
	!endif
	!if $inputs>0
	    !set a_items=!itemcnt $(answer$n)
	    !if $inputs != $a_items
		!set use_lines=1
	    !else
		!set use_lines=0
	    !endif
	    <ul class="vlist">
		!for i=1 to $inputs
		<li>
		    !if $wims_user=supervisor
			!if $use_lines=1
			    !set voorzeggen=!line $i of $(answer$n)
			!else
			    !set voorzeggen=!item $i of $(answer$n)
			!endif
			$(description[$i])&nbsp;$m_rightarrow&nbsp;<input id="myinput$[i-1]" class="schaersvoorde_textarea" size="$cols" value="$voorzeggen" />&nbsp;$(ex$p)
		    !else
			$(description[$i])&nbsp;$m_rightarrow&nbsp;<input id="myinput$[$i-1]" class="schaersvoorde_textarea" size="$cols" value="" />&nbsp;$(ex$p)
		    !endif
		</li>
		!next i
	    </ul>
	!endif
    </td>
!if $make_tr=1
    </tr>
    <tr>
!endif
    <td class="exercise_c">
	!if $width=$empty
	    !set width=640
	    !set height=480
	!endif
	<object classid="java:geogebra.GeoGebraApplet.class" type="application/x-java-applet;jpi-version=1.4" id="ggbApplet" name="ggbApplet" width=$width height=$height>
	    <param name="java_code" value="geogebra.GeoGebraApplet" />
	    <param name="java_codebase" value="java/geogebra" />
	    <param name="java_archive" value="geogebra.jar" />
	    <param name="language" value="$taal" />
	    <param name="filename" value="../../$module_dir/$ggb" />
	    <param name="showToolBar"  value="$showToolBar" />
	    <param name="showMenuBar"  value="$showMenuBar" />
	    <param name="framePossible" value="$framePossible" />
	    <param name="customToolBar" value=$customToolBar />
	    <param name="showAlgebraInput" value="$showAlgebraInput" />
	    <param name="mayscript" value="true" />
	    <a onmouseover="return escape('<img src=\'$gifdir/java.jpg\' alt=\'Get JAVA\' />');" href="http://www.java.com/$lang/download/manual.jsp?locale=$lang" >
		$nojava
	    </a>
	</object>
	!if $appletcommand != $empty
	    <script type="text/javascript">
	    //<![CDATA[
		$appletcommand
	    //]]>
	    </script>
	!endif
    </td>
    </tr>
</table>

<div id="send_buttons" class="embedded_central">
    <input type="button" id="schaersvoorde_ok_button" onclick="javascript:sendanswer();" value="$send" />
    <input type="button" id="schaersvoorde_nok_button" onclick="javascript:dontknow();" value="$dontknow" />
</div>

!exit
