!if $noselect=1
    <script type="text/javascript" src="$jsdir/nocut.js"></script>
!endif
<script type="text/javascript">
//<![CDATA[

    var stickit=0;
    function showimage() {
	MijnVenster1=window.open("$wims_ref_name?&session=$session&module=$module&cmd=getins&special_parm=insert-1.gif", "", "width=$XSIZE,height=$YSIZE,left=0,top=0");
        MijnVenster1.focus();
    }
    function showScribble(){
	if(stickit == 0){
	    stickit=1;
	    document.getElementById('stickit_area').style.display = "block";
	}
	else
	{
    	    stickit=0;
            document.getElementById('stickit_area').style.display = "none";
        }
    }
    !if $time=1
	var clps = 0;function update() {if(clps) {clearTimeout(clps);clps  = 0;}var t = new Date();document.clock.time.value = ""  + t.getHours() + ":"  + t.getMinutes() + ":" + t.getSeconds();clps = setTimeout("update()", 1000);}function startclock() {clps = setTimeout("update()", 500);} startclock();
    !endif
//]]>
</script>

!set wims_texsize=$mytexsize

!if $debug=1
    !if $wims_exec_error != $empty
	<p align="center">
	    <span style="schaersvoorde_alarm">$wims_exec_error</span>
	</p>
    !endif
!endif
<table style="width:100%" >
    <tr>
    <td style="vertical-align:top;text-align:left;float:left;white-space:nowrap">
	!if $exotitle != $empty
		<kbd>$exotitle</kbd>
	    <br/>
	!endif
	!if $roundingtext!=$empty
		<span class="schaersvoorde_alarm">
		    $roundingtext
		</span>
	    <br/>
	!endif
	<span class="schaersvoorde_alarm">
	    $no_back_button
	</span>
	!if exam notin $session
	    <br/>
	    !href target=wims_mhelp module=$module&+session=$session&+cmd=help <img src="$gifdir/help.jpg" alt="help" /></a>
	    <a onmouseover="return escape('$helptext')"><img src="$gifdir/tip.jpg" alt="tip" /></a>
	!endif
    </td>
    <td>
	<div id="alarmtext" style="opacity:0.8;position:absolute;top:0px;left:0px;z-index:100;display:none;background-color:yellow;border:4px solid red;width:400px;"></div>
    </td>
    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
	<table>
	    <tr>
	    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
		<textarea id="stickit_area" cols="20" style="display:none;background-color:yellow;font-size:16px;border:2px solid red;width:220px;height:60px;"></textarea>
	    </td>
	!if $viewlogo=1
	    <td style="vertical-align:top;text-align:right;white-space:nowrap;">
		<a onmouseover="this.T_OPACITY=70;this.T_PADDING=10;this.T_BORDERCOLOR='red';this.T_BORDERWIDTH=1;return escape('$logotext')">
		    $logo
		</a>
	    </td>
	!endif
	!if $questiontype isin 0,7
	    !if $mathview isin 1,2
		<td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
		    !if exam isin $session
			!! hope this is not interfering with something important...
			!set help_session=!nospace $session _mhelp
		    !else
			!set help_session=!replace internal . by , in $session
			!set help_session=!item 1 of $help_session
			!set help_session=!nospace $help_session _ mhelp
		    !endif
		    <a onmouseover="return escape('$mathchecktext')" onclick="wims_help=window.open('$wims_ref_name?wims_window=new&+lang=nl&+session=$help_session&+module=$module&+cmd=help&+myvar4=$session','wims_help','status=no,toolbar=no,location=no,menubar=no,scrollbars=yes,resizable=yes')">
			<img src="$gifdir/math.jpg" alt="mathematical inputfield" border="0" />
		    </a>
		</td>
	    !endif
	!endif
	!if $scribbling=1
	    <td style="vertical-align:top;text-align:right;white-space:nowrap;">
		<a onclick="javascrip:showScribble();" onmouseover="return escape('Post-It Memo')" >
		    <img src="$gifdir/pencil.png" width="50" height="70" alt="scribling" />
		</a>
	    </td>
	!endif
	!if $calculator=3
	    <td style="vertical-align:top;text-align:right;white-space:nowrap;">
		<table>
		    <tr>
		    <th>
	    		<script type="text/javascript">
			    function ReadCalculator(){
				var calc=document.getElementById("javacalculator").ReadApplet();
			        var t=confirm("$send \n"+calc);
				if(t==true){
				    total=encodeURIComponent(calc);
			    	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+calc ;
				    document.location.href = URL;
			    	    document.getElementById("calculator").destroy();
				}
			    }
			</script>
			<object id="javacalculator" width="100" height="50" classid="java:Rekenmachien.class" type="application/x-java-applet;jpi-version=1.4">>
			    <param name="java_codebase" value="$appletdir" />
			    <param name="java_archive" value="Rekenmachien.jar" />
			    <param name="java_code" value="Rekenmachien.class" />
			    <param name="fontsize1" value="10" />
			    <param name="fontsize2" value="10" />
			    <param name="fontsize2" value="14" />
			    <param name="language" value="$taal" />
			    <param name="pencolor1" value="0,0,0" />
			    <param name="pencolor2" value="255,0,15" />
			    <param name="bgcolor1" value="200,250,255" />
			    <param name="#fffff0" value="200,210,210" />
			    $nojava
			</object>
		    </th>
		    </tr><tr>
		    <th>
			<input style="font-size:8px;background-color:orange" type="button" onclick="javascript:ReadCalculator();" value="$send" />
		    </th>
		    <tr>
		</table>
	    </td>
	!else
	    !if $calculator=2
		<td style="vertical-align:top;text-align:right;white-space:nowrap;">
		    <a onclick="window.open('$htmldir/mathcalc.html','calculator','width=280,height=370,left=0,top=0')">
			<img src="$gifdir/xcalc.png" width="50" height="70" alt="calculator" />
		    </a>
		</td>
	    !else
		!if $calculator=1
		    <td style="vertical-align:top;text-align:right;white-space:nowrap;">
			<a onclick="window.open('$htmldir/basicalc.html','calculator','width=300,height=200,left=0,top=0')">
			    <img src="$gifdir/xcalc.png" width="50" height="70" alt="calculator" />
			</a>
		    </td>
		!endif
	    !endif
	!endif
	!if $debug=1
	    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
		!href target=wims_mhelp session=$session&+module=$module&+cmd=help
		    <img src="$gifdir/exec.png" alt="debug-info" />
		</a>
	    </td>
	!endif
	!if $time=1
	    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
		<table>
		    <tr>
		    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
			<form id="clock" name="clock" action="">
			    <input style="text-align:center;background-color:#fffff0;color:green;font-size:100%;" type="text" id="time" name="time" size="9" />
			</form>
		    </td>
		    </tr><tr>
		    <td style="vertical-align:top;text-align:right;float:right;white-space:nowrap;">
			<a target="nieuw" href="http://www.mozilla-europe.org/$taal/"><img src="$gifdir/getFireFox.gif" alt="get FIREFOX" border="0" /></a>
		    </td>
		    </tr>
		</table>
	    </td>
	!endif
	    </tr>
	</table>
    </td>
    </tr>
</table>
<p style="text-align:center">
    !if $goback=1
	<span class="schaersvoorde_alarm">
	    $errortext &nbsp;
	</span>
    !else
	!if $goodbadsign>0
	    <span class="schaersvoorde_alarm">
		$(remark$[$n-1]) &nbsp;
	    </span>
	!endif
    !endif
    !if $try = $maxtry
	!set alarm=!record 52 of $remarkdir/commonremarks.$taal
	<div style="color:black;background-color:orange;border:2px solid red;width:400px">
	    $alarm
	</div>
    !endif
</p>
<p style="text-align:left">
!if $total_exos>1
    $questionnumber $n)
!endif
</p>
