<style type="text/css">
     a:link{color:blue;text-decoration:none;}
     a:hover{color:red;text-decoration:none;}
</style>
!if $noselect=1
    <script type="text/javascript" src="$jsdir/nocut.js"></script>
!endif
<script type="text/javascript">
    function showimage() {
    MijnVenster1=window.open("$wims_ref_name?&session=$session&module=$module&cmd=getins&special_parm=insert-1.gif", "", "width=$XSIZE,height=$YSIZE,left=0,top=0");
     MijnVenster1.focus();
    }
</script>
!if $time=1
    <script type="text/javascript">var clps = 0;function update() {if(clps) {clearTimeout(clps);clps  = 0;}var t = new Date();document.clock.time.value = ""  + t.getHours() + ":"  + t.getMinutes() + ":" + t.getSeconds();clps = setTimeout("update()", 1000);}function startclock() {clps = setTimeout("update()", 500);} startclock();</script>
!endif		
!set wims_texsize=$mytexsize

!if $debug=1
    !if $wims_exec_error != $empty
	<p align="center">
	    <font color="$fontcolor3">$wims_exec_error</font>
	</p>
    !endif
!endif
<table summary="" width="100%">
    <tr>
    <td valign="top" align="left">
	!if $exotitle != $empty
	    <small>
		<em>    
		    $exotitle
		</em>
	    </small>
	    <br/>
	!endif
	!if $roundingtext!=$empty
	    <small>
		<font color="red">
		    $roundingtext
		</font>
	    </small>
	    <br/>
	!endif
	    <small>
		<font color="red">
		    $no_back_button
		</font>
	    </small>
	!if exam notin $session
	    <br/>
	    <small>
		$helptext
		!href target=wims_mhelp module=$module&+session=$session&+cmd=help
		&nbsp;&nbsp;&nbsp;&nbsp;<em>$wims_name_help popup</em>
		</a>
	    </small>
	!endif
    </td>
    <td valign="top" align="right">
	<table summary="">
	    <tr>
	!if $viewlogo=1
	    <td valign="top" align="right">
		<div>
		    <a onmouseover="this.T_OPACITY=70;this.T_PADDING=10;this.T_BORDERCOLOR='red';this.T_BORDERWIDTH=1;return escape('$logotext')">
			$logo
		    </a>
		</div>
	    </td>
	!endif
	!if $questiontype isin 0,7
	    !if $mathview isin 1,2
		<td valign="top" align="right">
		    !if exam isin $session
			!! hope this is not interfering with something important...
			!set help_session=!nospace $session _mhelp
		    !else
			!set help_session=!replace internal . by , in $session
			!set help_session=!item 1 of $help_session
			!set help_session=!nospace $help_session _ mhelp
		    !endif
		    <a onmouseover="return escape('$mathchecktext')" onClick="wims_help=window.open('$wims_ref_name?wims_window=new&+lang=nl&+session=$help_session&+module=$module&+cmd=help&+myvar4=$session','wims_help','status=no,toolbar=no,location=no,menubar=no,scrollbars=yes,resizable=yes')"
			<img src="$gifdir/math.jpg" alt="mathematical inputfield" border="0"></a>
		    </a>
		</td>
	    !endif
	!endif
	!if $scribbling=1
	    <td valign="top" align="right">
		<a onClick="window.open('$htmldir/scribbling.html','scribbling','width=320,height=260,left=0,top=0,status=no,menubar=no,resizable=yes,toolbar=no')">
		    <img src="$gifdir/pencil.png" width="50" height="70" alt="scriblingpad" >
		</a>
	    </td>
	!endif
	!if $calculator=3
	    <td valign="top" align="right">
		<table summary="">
		    <tr>
		    <th>
	    		<script type="text/javascript">
			    function ReadCalculator(){
				var calc=document.getElementById("calculator").ReadApplet();
			        var t=confirm("$send \n"+calc);
				if(t==true){
				    total=encodeURIComponent(calc);
			    	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+calc ;
				    document.location.href = URL;
			    	    document.getElementById("calculator").destroy();
				}
			    }
			</script>
			<applet id="calculator" codebase="$appletdir" archive="Rekenmachien.jar" code="Rekenmachien.class" width="100" height="50">
			    <param name="fontsize1" value="10">
			    <param name="fontsize2" value="10">
			    <param name="fontsize2" value="14">
			    <param name="language" value="$taal">
			    <param name="pencolor1" value="0,0,0">
			    <param name="pencolor2" value="255,0,15">
			    <param name="bgcolor1" value="200,250,255">
			    <param name="bgcolor2" value="200,210,210">		    
			    $nojava
			</applet>
		    </th>
		    </tr><tr>		    
		    <th>
			<input style="font-size:6pt;background-color:orange" type="button" onclick="javascript:ReadCalculator();" value="$send">
		    </th>
		    <tr>
		</table>
	    </td>
	!else
	    !if $calculator=2
		<td valign="top" align="right">
		    <a onClick="window.open('$htmldir/mathcalc.html','calculator','width=280,height=370,left=0,top=0')">
			<img src="$gifdir/xcalc.png" width="50" height="70" alt="calculator" >
		    </a>
		</td>
	    !else
		!if $calculator=1
		    <td valign="top" align="right">
			<a onClick="window.open('$htmldir/basicalc.html','calculator','width=300,height=200,left=0,top=0')">
			    <img src="$gifdir/xcalc.png" width="50" height="70" alt="calculator" >
			</a>
		    </td>
		!endif
	    !endif
	!endif
	!if $debug=1
	    <td valign="top" align="right">
		!href target=wims_mhelp session=$session&+module=$module&+cmd=help
		    <img src="$gifdir/exec.png" alt="debug-info">
		</a>
	    </td>
	!endif
	!if $time=1
	    <td valign="top" align="right">
		<table summary="">
		    <tr>
		    <td valign="top" align="right">
			<form name="clock" action="">
			    <input style="text-align:center;background-color:$bgcolor1;color:green;font-size:100%;" type="text" name="time" size="9">
			</form>
		    </td>
		    </tr><tr>
		    <td valign="top" align="right">
			<a target="nieuw" href="http://www.mozilla-europe.org/$taal/"><img src="$gifdir/getFireFox.gif" alt="get FIREFOX" border="0"></a>
		    </td>
		    </tr>
		</table>
	    </td>
	!endif
	    </tr>
	</table>
    </td>
    </tr>
</table>
<p align ="center">
    !if $goback=1
	<font color="$fontcolor3">
	    $errortext &nbsp;
	</font>
    !else
	!if $goodbadsign>0
	    <small>
		$(remark$[$n-1]) &nbsp;
	    </small>
	!endif
    !endif
    !if $try = $maxtry
	<center>
	    <hr>
		<font color="$fontcolor3">
		    !set alarm=!record 52 of $remarkdir/commonremarks.$taal
		    $alarm
		</font>
	    <hr>
	</center>
    !endif
</p>
<center>
    <div id="alarmtext" style="opacity:0.6;z-index:100;display:none;background-color:orange;font-size:16px;border:2px solid red;width:300px"></div>
</center>
<p align="left">
!if $total_exos>1
    <small>
	$questionnumber <b>$n</b>)
    </small>
!endif
</p>
