!!hotspot questions
<script type="text/javascript">
//<![CDATA[
<! -- no validator -->
    function dontknow(){
	myConfirm('$dontknow','?','$wims_ref_name','$session','$module','$counter','$nok_send_color');
    }

//]]>
</script>
!set n=$counter
<table id="exercise" class="exercise">
    <tr>
    <td class="exercise_t">
	!if $(question$n) != $empty
	    $(question$n)
	    <br />
	!endif
	!if $(formula$n) != $empty
	    !insmath $(formula$n)
	    <br />
	!endif
	!if $exotext=$empty
	    $exotext
	!endif
    </td>
    <td class="exercise_c">
	!set ins_attr = ismap 
    	!href cmd=reply&$no_name
	!if $draw=1
	    !set insdraw_size=$(image_settings$n)
	    !insdraw $(image$n)
	!endif
	!if $plot=1
	    !set insplot_set=$(image_settings$n)
	    !insplot $(image$n)
	!endif
    </td>
    </tr>
</table>

<div id="send_buttons" class="embedded_central">
!if $inputs != 0
    <input type="button" id="schaersvoorde_ok_button" onclick="javascript:sendanswer();" value="$send" />
!endif
    <input type="button" id="schaersvoorde_nok_button" onclick="javascript:dontknow();"  value="$dontknow" />
</div>
!exit
