<script type="text/javascript">
//<![CDATA[
<!-- no validator  -->
!if $goback=1
    !!! this is used for filling_in the inputfields myinput[n] after a return: the inputfields are present in a variable-string and thus can "not be filled" by wims... note: if $embed=1 ... WIMS will fill in the rejected answer...see below [id=myinput]
    function refill(){var hi="$(reply$n)";if(hi.length !=0){hi=hi.split(',');for(var i=0;i<hi.length;i++){document.getElementById("myinput"+i).value=hi[i];}}}
!endif
    <!-- do not use "' in description -->
    var descr_list="$description";
    var descr_cnt = 30;
    var description = make_description(descr_list,descr_cnt);

    function dontknow(){
	myConfirm('$dontknow','?','$wims_ref_name','$session','$module','$counter','$nok_send_color');
    }
//]]>
</script>

<!-- standard the drag & drop library is included: images (static;fly;gnuplot [id=image$$n]) may be added by setting the "dhtml" variable -->
<script type="text/javascript" src="$jsdir/wz_dragdrop.js"></script>
<table id="exercise" class="exercise" ><!-- begin table id="exercise" -->
    <tr>
    <td class="exercise_t">
    !if $(question$n) != $empty
	$(question$n)
    !endif
    !if $(formula$n) != $empty
	<table class="exercise">
	    <tr>
	    <td class="exercise_m">
	    !if $display=1
		!insmath $$$$ $(formula$n) $$$$
	    !else
		!insmath $(formula$n)
	    !endif
	    </td>
	!if $embed=1
	    <td class="exercise_m">
	    <!-- to read these inputfields use document.getElementById('myinput0') in tailormade javascript.js -->
		!if $wims_user=supervisor
		    <textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(answer$n)</textarea>
		!else
		    <textarea id="myinput0" class="schaersvoorde_textarea" cols="$cols" rows="$rows">$(reply$n)</textarea>
		!endif
	    </td>
	!endif
	    </tr>
	</table>
    !endif
    !if $exotext != $empty
	$exotext
    !endif
    </td>
    !if $image=1 
        !if $make_tr=1
	    </tr>
	    <tr>
        !endif
	<td class="exercise_t">
	!if $draw=1
	    !set ins_attr= id="myimage"
	    !set insdraw_size=$xsize,$ysize
	    !insdraw $(image$n)
	!else
	    !if $plot=1
		!set ins_attr= id="myimage"
		!set insplot_set=$(image_settings$n)
		!insplot $(image$n)
	    !else
		!if $svg=1
		    !exec svgdraw $(image$n)
		!else
		    <span style="schaersvoorde_alarm">set variable draw/plot/svg ---&gt; 1</span>
		!endif
	    !endif
	!endif
	</td>
    !else
	!if $applet=1
    	    !if $make_tr=1
		</tr>
		<tr>
	     !endif
	<td class="exercise_t">
	    $(object$n)
	</td>
	!endif
    !endif
    !if $make_tr=1
	</tr>
	<tr>
    !endif
    <td class="exercise_c"><!-- begin module_dir/js/*.js -->
	!read $javascript
    </td><!-- end module_dir/js/*.js -->
    </tr>
</table><!-- end table id="exercise" -->

!if $inputs=yes
    <div id="send_buttons" class="embedded_central">
	<input type="button" id="schaersvoorde_ok_button" onclick="javascript:sendanswer();" value="$send" />
	<input type="button" id="schaersvoorde_nok_button" onclick="javascript:dontknow();"  value="$dontknow" />
    </div>
!endif
$dhtml
!if $goback=1
    !!! after the inputelements are in the DOM-tree: fill-in the previous answers
    <script type="text/javascript">
    //<![CDATA[
	<!-- no validator  -->
	try{document.onload=refill();}catch(e){}
    //]]>
    </script>
!endif
!exit
