<script type="text/javascript">
//<![CDATA[
    var URL;
    function dontknow(){
	t=confirm(r0+"\n$dontknow ?");
	if(t==true){URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=%3F';
	document.location.href = URL;
	}
    }
//]]>
</script>
!set n=$counter
!! multiplechoice=1 choose from $options possibilities
!! each possibility is called ex1,ex2,ex3...ex10 etc
<table id="exercise" class="exercise">
    <tr>
    <td class="exercise_t">
	$(question$n)
	!if $(formula$n) != $empty
	    <br />
	    !insmath $(formula$n)
	!endif
	!if $applet=1
	    <br />
	    $(object$n)
	!endif
	!if $exotext != $empty
	    <br />
	    $exotext
	!endif
    <td>
!if $XSIZE>450
    </tr>
    <tr>
    !endif
    <td class="exercise_m">
	<table class="exercise">
	    <tr>
	!if $options*$xsize>1024
	    !set one_row=0
	!else
	    !set one_row=1
	!endif
	!set t=0
	!for p=1 to $options
	    !increase t
	    <td style="vertical-align:top;background-color:lightblue;padding:10px;border-spacing:5px" onMouseover="this.style.backgroundColor='yellow';" onMouseout="this.style.backgroundColor='lightblue';">
		<a onclick="var t=confirm(r0+'$p');if(t==true){window.location.href = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=$p'; return false}">
	    !if $multiimage=1
		!if $draw=1
		    !set insdraw_size=$xsize,$ysize
		    !insdraw $(ex$p)
		!else
		    !if $plot=1
			!set insplot_set=$(image_settings$n)
			!insplot $(ex$p)
		    !else
			!if $svg=1
			    $(ex$p) 
			!else
			    <span class="schaersvoorde_alarm">error:define draw,plot or sgv mode </span>
			!endif
		    !endif
		!endif
	    !else
		!if $math=0
		    <span class="schaersvoorde_link">$(ex$p)</span>
		!else
		    !insmath $(ex$p)
		!endif
	    !endif
		</a>
	    </td>
	    !if $t=2 and $one_row=0
	    </tr>
	    <tr>
	    !set t=0
	    !endif
	!next p
	    </tr>
	</table>
    </td>
</table>

<div id="send_buttons" class="embedded_central">
    <input type="button" class="schaersvoorde_nok_button" onclick="javascript:dontknow();"  value="$dontknow" />
</div>

