!set n=$counter
<script type="text/javascript">
//<![CDATA[
<!-- no validator -->
!if $description=$empty
    var desc_list = null;
    var default_desc = "$youranswer ";
    var desc_cnt = 30;
!else
    var desc_list="$description";
 !set desc_cnt = !itemcnt $description
    var desc_cnt = $desc_cnt;
    var default_desc = null;
!endif
    var description = list2array(desc_list,desc_cnt,default_desc);
    var URL;

    function dontknow(){
	var t=confirm(r0+"\n$dontknow ?");
	if(t==true){
	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n=%3F' ;
	    document.location.href = URL;
	}
    }
    
    function TexAppInputs(num){
	if( document.getElementById('TexApp1') ){ // starts with 1
	    var p = 1;
    	    while ( document.getElementById('TexApp'+p) ){
		document.getElementById('TexApp'+p).changeInputfields(num);
		p++;
	    }
	}
    }
    
    function sendanswer(){
	var reply = new Array();var show ="";
	var p = 1;var tmp;var tmp1;var cnt = 0;var ans = new Array();
	if( document.getElementById('TexApp1') ){ // starts with 1
    	    while ( document.getElementById('TexApp'+p) ){ 
		tmp1 = document.getElementById('TexApp'+p).ReadApplet()+"";
		ans = tmp1.split(',');
		for(var s = 0; s < ans.length; s++){
		    tmp = ans[s];tmp=tmp.replace(/\ /g,'');
		    if(tmp.length == 0){setAlarm(r1+" "+ parseInt(cnt+1));return;}
		    if(tmp.indexOf(',')!=-1){setAlarm(r4);return;}
		    if(check_x(tmp) == 0){return;}
		    if(tmp.indexOf('error')!=-1){setAlarm(tmp);return;}
		    tmp = science(tmp);if(tmp == "error"){return;}
		    if(tmp.indexOf("[") != -1){
			if(tmp.indexOf("sqrt[")!=-1){tmp = specialroot(tmp);if(tmp == "error"){return;}}
			if(tmp.indexOf("log[") !=-1){tmp = speciallog(tmp) ;if(tmp == "error"){return;}}
		        if(tmp.indexOf("[") != -1){setAlarm(r13);return;}
		    }
		    tmp = arrows(tmp,2,"","");if(tmp == "error"){return;}
		    reply[cnt] = tmp; 
		    show = show + "\n"+parseInt(cnt+1)+") "+tmp; 
		    cnt++;
        	}
		p++;
    	    }
	}
	var num_applets = p;
	if( document.getElementById('myinput0') ){
	    var s = 0;
	    while( document.getElementById('myinput'+s) ){
		tmp = document.getElementById('myinput'+s).value;
		if(tmp.length == 0){setAlarm(r1+" "+ parseInt(cnt+1));return;}
		if(tmp.indexOf(',')!=-1){setAlarm(r4);return;}
		if(check_x(tmp) == 0){return;}
		if(tmp.indexOf('error')!=-1){setAlarm(tmp);return;}
		tmp = science(tmp);if(tmp == "error"){return;}
		if(tmp.indexOf("[") != -1){
		    if(tmp.indexOf("sqrt[")!=-1){tmp = specialroot(tmp);if(tmp == "error"){return;}}
		    if(tmp.indexOf("log[") !=-1){tmp = speciallog(tmp) ;if(tmp == "error"){return;}}
		    if(tmp.indexOf("[") != -1){setAlarm(r13);return;}
		}
		tmp = arrows(tmp,2,"","");if(tmp == "error"){return;}
		reply[cnt] = tmp;
		show = show + "\n"+ parseInt(cnt+1)+") "+tmp; 
		cnt++;p++;s++;
		if(s>100){setAlarm(r2);dontknow();}
	    }
	}
	var t=confirm(r0+"\n"+show);
	if(t == true){ 
	    reply = encodeURIComponent(reply);
	    URL = '$wims_ref_name?session=$session&+module=$module&+cmd=reply&+reply$n='+reply ;
!!	    for(var s = 1; s < num_applets ; s++){
!!		document.getElementById("TexApp"+s).destroy();
!!	    }
	    document.location.href = URL;
	}
    }
//]]>
</script>

<div id="wait_for_applet" style="text-align:center;display:block;"><img src="$gifdir/wait.gif" alt="wait...wait"></div>
!! TexApp is in exotext or in object_n
<table id="exercise" class="exercise" >
    <tr>
    <td class="exercise_t">
	!if $(question$n) != $empty
	    $(question$n)
	    <br />
	!endif
	!if $(formula$n) != $empty
	    !insmath $(formula$n)
	    <br />
	!endif
	!if $exotext != $empty
	    <br />
	    $exotext
	!endif
    </td>
!if $image=1
    !if $make_tr=1
    </tr>
    <tr>
    !endif
    <td class="exercise_c">
    !if $draw=1
	!set insdraw_size=$xsize,$ysize
	!insdraw $(image$n)
    !endif
    !if $plot=1
	!set insplot_set=$(image_settings$n)
	!insplot $(image$n)
    !endif
    !if $svg=1
	!exec svgdraw $(image$n)
    !endif
    </td>
!endif
!if $(object$n) != $empty
    !if $make_tr=1
    </tr>
    <tr>
    !endif
    <td class="exercise_c">
	$(object$n)
    </td>
!endif
    </tr>
</table>

<div id="send_buttons" class="embedded_central">
    <input type="button" class="schaersvoorde_ok_button" onclick="javascript:sendanswer();" value="$send">
    <input type="button" class="schaersvoorde_nok_button" onclick="javascript:dontknow();"  value="$dontknow">
!if $control_inputs = 1
    <input type="button" class="schaersvoorde_extra_button" onclick="javascript:TexAppInputs(1)" value="+">
    <input type="button" class="schaersvoorde_extra_button" onclick="javascript:TexAppInputs(-1);" value="&minus;">
!endif
</div>
