
!readproc adm/docsheet.prep
!read $docdef content
<p><center>
La registrazione dei punteggi è
 !set dd=!getscorestatus sheet=$sh
 !if $dd=yes
  !if $wims_scorereg!=suspend
   attiva, ma puoi
   !href cmd=resume&job=suspend sospenderla
.
  !else
   stata da te sospesa.
   !href cmd=resume&job=reopen Riattivala
.
  !endif
 !else
  disattivata per questo tipo di connessione.
 !endif

!if $wims_user=supervisor
 <p>
 !href module=adm/class/sheet&sheet=$sh $wims_name_sheetmanagement
.&nbsp;
 !set d_=!translate / to , in $sheet_docpage
 !distribute items $d_ into d_,b_
 !href target=wims_doc module=adm/doc.it&job=edit&doc=$d_&block=$b_ Modifica questa pagina
.&nbsp;
 !href cmd=resume Ricomincia
.
!endif
</center>

!tail

