!read names.phtml
!if $job=print
 !changeto print.phtml
!endif

!if $public!=P
 !changeto class.phtml
!endif

!header

!if $error!=$empty
 !read msg.phtml
 !tail
 !exit
!endif

!if $wims_user=supervisor and $job=raw
$name_textsource
 <p><hr><pre>
 !sh awk 'BEGIN {a=0};\
	/^:/ {a=1};\
	a==1 {print}' bases/sheet/$sh.def
 </pre><hr>

!set wims_menu_items=!append line participantview,1,cmd=resume&job=read \
to $wims_menu_items

 !tail
 !exit
!endif

!set intro=!record 0 of $data
!set dur=!words2items $(intro[3;])
!distribute items $dur into duration,year
!read adm/title.phtml 3\
$sheet_title\
$name_level $(intro[5;]), $name_duration $duration mn ($year)<br>$(intro[8;])\

<div class="wims_sheet_desc">$sheet_desc</div> <p>

$sheet_remark
<p>

!if $n=0
 $name_empty
!else
 <div class="wims_sheet">
 <p><ul class="wims_sheet_list">
 !for i=1 to $n
  !set ex=!record $i of $data
  !distribute lines $ex into di,pa,require,we,ti,de
  !set got=!word $i of $scores
  !set mean=!word $i of $means
  <li class="wims_sheet_list"><p>$i. 
  !href module=$di&cmd=new&worksheet=$public$shn&$pa $ti
, $de
 </li>
 !next i
 </ul>
 </div>
 !if $wims_user=supervisor
 !set wims_menu_items=!append line import,1,cmd=reply&job=import \
 sheetsource,1,cmd=reply&job=raw\
 to $wims_menu_items
 !endif
!endif

!set wims_menu_items=!append line printable,1,cmd=reply&job=print\
to $wims_menu_items

!tail

