!read adm/class/class.lang names.phtml

!read adm/css.phtml
!header1

!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$module_title

!if $error!=$empty
 <div class="wims_alertmsg">
 !read lang/msg.phtml.$moduclass_lang
 </div>
 !set wims_ref_class=wims_button
<p class="wimscenter">
 !href module=home $wims_name_back2
</p>
 !goto end
!endif

!form reply

!if $wims_user=supervisor
 !default job=user
 !if $job=none
  $name_passwdtype :
  <ul>
   !set ch_$job=checked
   <li><input type="radio" name="job" $ch_user value="user" /> $name_userpasswd.</li>
   !if $part!=$empty and $job=part
    <li><input type="radio" name="job" $ch_part value="part" /> $name_partpasswd <span class="tt">$part</span> ($name_warning1).</li>
   !endif
   <li><input type="radio" name="job" $ch_class value="class" /> $name_classpasswd ($name_warning1).</li>
  </ul>

 !else
    <fieldset class="property_fields halfwidth blockcenter">
     <legend>
      $(name_$(job)passwd)
      !if $job=part
       <span class="tt">$part</span>
      !endif
      </legend>
      <input type="hidden" name="job" value="$job" />
 !endif
!else
  <input type="hidden" name="job" value="user" />
  <fieldset class="property_fields halfwidth blockcenter">
!endif
 !if $job=user or $job=none
  <div class="field box">
   <label for="old">$name_actualpasswd</label>
   <input type="password" size="16" name="old" id="old" />
  </div>
 !endif
   <div class="field box">
     <label for="pw1">$name_newpasswd</label>
     <input type="password" size="16" name="pw1" id="pw1" />
   </div>
   <div class="field box">
     <label for="pw2">$name_newpasswd2</label>
     <input type="password" size="16" name="pw2" id="pw2"/>
   </div>
   <div class="wimscenter wimsform">
    <input type="submit" value="$wims_name_tosave" />
   </div>
  </fieldset>

<p class="small">$name_jetable
!set wims_ref_class=wims_button_help
!href target=wims_mhelp cmd=help $wims_name_help
</p>

!formend
<p>
$name_alphanumer
!if $wims_user=supervisor
 ($name_emptypasswd).
!endif
</p>
!endif
:end
!tail

!distribute item $ into job,pw1,pw2,old

