!read adm/class/class.lang names.phtml

!read adm/css.phtml
!header1

!read adm/class/classname.phtml $wims_classname\
$wims_institutionname

!read adm/title.phtml 1\
$classname\
$module_title

!if $error!=$empty
 <p></p>
 !read lang/msg.phtml.$moduclass_lang
<p></p>
 !href module=home $wims_name_back2
. <p></p>
 !goto end
!endif

!form reply

!if $wims_user=supervisor
 $name_passwdtype: <ul>
 !default job=user
 !set ch_$job=checked
 <li><input type="radio" name="job" $ch_user value="user"> $name_persopasswd
 </li>
 !if $part!=$empty and $job=part
  <li><input type="radio" name="job" $ch_part value="part"> $name_partpasswd
  <tt>$part</tt> ($name_warning1).</li>
 !endif
 <li><input type="radio" name="job" $ch_class value="class"> $name_classpasswd 
 ($name_warning1).
 </li>
 </ul>
!else
 <input type="hidden" name="job" value="user">
!endif
<table>
<tr><td align="right">$name_actualpasswd</td>
	<td><input type="password" size="16" name="old"></td></tr>
<tr><td align="right">$name_newpasswd</td>
	<td><input type="password" size="42" name="pw1"></td></tr>
<tr><td align="right">$name_newpasswd2</td>
	<td><input type="password" size="42" name="pw2"></td></tr>
</table>
<input type="submit" value="$wims_name_tosave"> <p></p>
<small>$name_jetable
!set wims_ref_class=wims_button_help
!href target=wims_mhelp cmd=help $wims_name_help
</small>
</form>
<p>
$name_alphanumer
!if $wims_user=supervisor
 ($name_emptypasswd).
!endif
</p>
!endif
:end
!tail

!distribute item $ into job,pw1,pw2,old

