<p><center><h1>Spiacente</h1></center> <p>
Questo server (<font color=red>$httpd_HTTP_HOST</font>) ha raggiunto
il limite massimo di corsi interattivi che può ospitare. La
creazione di nuovi corsi &egrave; perciò sospesa. <p>

&Egrave; possibile <a
!mailurl $wims_site_manager contattare il gestore del sito\
WIMS@$httpd_HTTP_HOST creazione di un corso
 per far attivare il corso manualmente. <p>

&Egrave; possibile creare un corso interattivo su un qualsiasi altro
sito WIMS. <p>
Infine, &egrave; possibile 
<a href="http://wims.unice.fr/download/wims">scaricare WIMS</a>
e installarlo localmente su un server linux.

