
<h1 class="wims_docu_title">$tit</h1>

!if $error!=$empty
 !read docu/en/msg.phtml
 <p><hr> <p>
!endif

!if $titb=$empty
 <p>
 The block <tt>$block</tt> is not yet created.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 This page is not yet open to reading. Come back later!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 This page is expired. You can no longer read it. Sorry!
 <p>
 !exit
!endif

<h3>$titb</h3>

!if $sheetdata=$empty
 <p>
 There is no exercise data in this page.
 <p>
 !exit
!endif

Here are the exercises of this page under worksheet format. You can use cut
and paste to insert them
!if $wims_user=supervisor
 into a sheet of your choice of your class.
!else
 into a sheet of a virtual class under your responsibility.
!endif

<pre>
$sheetdata
</pre>
