<center><h1>$tit</h1></center>

!if $fcnt<1
 This document has no content yet.
 !href cmd=reply&job=edit&block=main Create the first page
.
 <p>
 !exit
!endif

<p>$table_header
<caption>List of blocks of the document</caption>
$table_hdtr
<th>Name<th>Title<th>Action
!for i=1 to $fcnt
 !set s_=!line $i of $slist
 !set t_=!line $i of $tlist
 !set t_=!trim $t_
 !default t_=No title
 $table_tr
 <td><tt>$s_</tt></td>
 <td>$t_</td>
 <td align=center>
 !href cmd=reply&job=read&block=$s_ Read
&nbsp;
 !if $editable=yes
  !href cmd=reply&job=edit&block=$s_ Edit
 !endif
</td>
!next i
$table_end <p>

<center>
Total available disk space: $quota_total Meg. Free disk space: $quota_free Meg.
<p>
!!!href cmd=reply&job=file File deposit
!!&nbsp;&nbsp;
!!!href cmd=reply&job=read&block=main Entrance page of the document
!!</center> <p>
!set wims_menu_tail=!append line doch_upload,1,cmd=reply&job=file\
doch_main,1, cmd=reply&job=read&block=main\
to $wims_menu_tail


