!nocache
!if $error!=$empty
 !read docu/$en/msg.phtml
 <p>
 !exit
!endif

<h1 class="wims_docu_title">$tit</h1>

!if $titb=$empty
 <p>
 The block <tt>$block</tt> is not yet created.
 <p>
 !exit
!endif

!if $datetest<0
 <p>
 This page is not yet open to reading. Come back later!
 <p>
 !exit
!endif

!if $datetest>0
 <p>
 This page is expired. You can no longer read it. Sorry!
 <p>
 !exit
!endif

:newblock
<a name=$block></a>
<h3>$titb</h3>

!read $docdir/$doc/$block.def content

!if $waitblock$(waitblock_$block)!=$empty
 !set waitblock=$(waitblock_$block),$waitblock
 !set waitblock=!nonempty items $waitblock
 !set block=!item 1 of $waitblock
 !set gotblock=!append item $block to $gotblock
 !set waitblock=!item 2 to -1 of $waitblock
 !read $docdir/$doc/$block.def
 <p>
 !goto newblock
!endif
